### ISSUE TITLE
inventory full

### ISSUE THREAD

**Issue by Ghenghis** [NECROBOTIO/NecroBot#1547]
says inventory full, but have 700/900

please add the full inventory bag for higher level players, so we can choose amount for each type

**Comment by tangdami** [comment]
Mine keeps saying pokemon inventory full, but I set CP 1800 and IV 95, but my inventory still has lots of pokemons with much lower CP and IV. I had to log in and transfer manually....

**Comment by ShootTheWhoop** [comment]
Maybe you have, KeepPokemonsThatCanEvolve to true. That takes precedence from what I've noticed.

**Comment by tangdami** [comment]
Thanks for your reminder. I just double checked, I have lots of Arcanine and Aerodactyl (not able to evolve) with CP and IV much lower than the values I set... I managed to use another bot to transfer them manually... Weird.

**Comment by actislav** [comment]
there are some more settings check them too PokemonsNotToTransfer list and special filter per pokemon PokemonsTransferFilter

**Comment by nfettinger** [comment]
@Ghenghis, is your original issue resolved?

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
