### ISSUE TITLE
Getting Errors On Google Login Attempts

### ISSUE THREAD

**Issue by kcalcitas** [NECROBOTIO/NecroBot#1548]
Screenshot below - please help! Thank you.
<img width="680" alt="screen shot 2016-07-31 at 11 11 54 am" src="https://cloud.githubusercontent.com/assets/14828758/17278332/7730c4b4-574a-11e6-8e31-c440324e9d11.png">

**Comment by Kaffetjuven** [comment]
Me too, i dont know what the problem is. Just tries to restart every other second.

**Comment by recon88** [comment]
You have to provide the full error, otherwise we can't help you.
Make the size of the window bigger und take another screenshot when it happens.
