### ISSUE TITLE
{Suggestions} Pokemon Keep Filtering

### ISSUE THREAD

**Issue by DazedRogue** [NECROBOTIO/NecroBot#1570]
Just 2 ideas.

1: Allow custom keep filtering of Pokemon in config by Name & CP / IV & Move set

Example:
KeepAllPokemon:

Dragonite,
1000CP,
90IV,
DragonBreath/DragonClaw
So any Dragonite caught with 1000 +CP 90 +IV and both moves are kept regardless if multiples are caught and any not meeting ALL the requirements are transferred.

2: Might seem silly, but some sort of immunity from being transferred for individual pokemon that you may want to keep for 1 reason or another. I may want to keep my starter Charmander or my first Pikachu without risking it being transfered because a higher CV / IV one gets caught. Maybe make the bot recognize Mon's with their names in [ ]'s and gives them immunity.

I think these are 2 suggestions that would be a huge benefit to the user and the bot.

**Comment by StewieGriffin** [comment]
You 2nd idea is implemented in the game, just Favorite the pokemon and it becomes protected from transfer
