### ISSUE TITLE
[Suggestion] check for a match TypeOfPokemon=TheAttackTypePokemon

### ISSUE THREAD

**Issue by Fenixxia** [NECROBOTIO/NecroBot#1574]
Hi. For several days trying to convey important information.
In the game, except the most important parameter IV there exists an equally important parameter STAB. The final level of evolution, this parameter is more important than IV. STAB = Same-type attack bonus) gives 1.25 attack pokemon. So even pokemon with IV = 100% will do less damage than the same pokemon but with STAB.
This implies that you need to enter the check for this parameter. All final levels of evolution in mandatory and voluntary in the following, if required by the user and the user wishes to pokemon the best quality. Most likely, it is necessary to introduce such a function through the filter for each pokemon. What would the user himself could choose what pokemon he is interested in or Tick ALL. What to do with a pokemon WITHOUT STAB? Need to give user choice to give the candy or leave the inventory. Maybe someone who doesn't want to part with her only dragon, but without STAB.
The perfect pokemon for the evolution and further development looks like this:
1) IV 100%
2) having a STAB first movement
3) lv 30 is the maximum level of pokémon available to catch in the game. Even if the player is higher level then the pokemon can not be higher than 30.
4) the final form of evolution

This message was translated with a program and may have errors.

**Comment by DazedRogue** [comment]
I have suggested something about an hour or so ago that if implemented would help in this regard. The Custom Transfer Filtering. You can define the values to be met by the pokemon or they get transferred.  ALL values are to be met, CP & IV & Move Set

Example:

Ninetales: CP1000 IV95	Ember   Flamethrower   

Any Caught Ninetales that is lower than 1k CP and IV 95 and different moves is transferred, while any that meet or exceed ALL the requirements are kept.

**Comment by Nordsted** [comment]
I am looking for this feature as well - anyone looking into it?
