### ISSUE TITLE
full pokemon, cant transfer during sniping mode

### ISSUE THREAD

**Issue by aapikz** [NECROBOTIO/NecroBot#1575]
![full inventory](https://cloud.githubusercontent.com/assets/14224262/17278972/7c9379be-571e-11e6-8417-6adaace391ad.png)

i wish it should check pokemon inventory if full to transfer/evolve during manual sniping mode

**Comment by recon88** [comment]
Check your settings: "KeepMinIvPercentage" - and - "TransferDuplicatePokemon"
Put the first higher and set the second to true

**Comment by yy4cmm** [comment]
it does transfer, just configure it properly, using PokemonsTransferFilter for all duplicates you want to keep and their values, and making sure "KeepMinCp" and  "KeepMinIvPercentage" is not lower than the pokemons you are capturing, if you are getting all pokemons with a cp or iv higher than those values, it will keep them

**Comment by guidedbymoon** [comment]
why am i getting no snipable pokemon at each pokestop everytime

**Comment by recon88** [comment]
@guidedbymoon because you are probably using the precompiled version which does not include the fixed sniping. You would have to compile it on your own if you want the fixed version of wait for the next release.

**Comment by Briskey** [comment]
You guys aren't understanding the issue.  The bot does not stop sniping when your inventory is full. Yes it's an issue.  No it's not user error.  It will continue sniping until it runs out of locations and pokemon to catch to transfer/evolve.  This should be ran atleast between sniping spots.  Would DRASTICALLY increase exp per hour.

**Comment by recon88** [comment]
Just checked the code. Gues you are right but that should be easy to fix.

**Comment by guidedbymoon** [comment]
is there a list of locations to snipe that i would just paste in config or how does it work do i just random locations that i find and want pokemon from?

**Comment by aapikz** [comment]
yes offcourse i have 
KeepMinIvPercentage": 95.0, 
TransferDuplicatePokemon": true 

i only snipe pidgey,caterpie,weedles and i dont need to set it on PokemonsTransferFilter .... 
temporary fix is lower the MinPokeballsToSnipe: 20 
because it doesnt stop sniping.. unless i got no balls,,

**Comment by gmmn2016** [comment]
hey aapikz, how did you get the sniping to work? i have no clue.  can u teach me

**Comment by gmmn2016** [comment]
hey Briskey, ohw do u use the sniping?

**Comment by recon88** [comment]
@gmmn2016 this is an issue tracker, not a discussion forum. If you have any question, please visit our discord server and ask there: https://discord.gg/VXKxNFr

**Comment by bastiflew** [comment]
Snipe() method should return a result, to Execute() method, and quit sniping task when pokemon inventory is full

**Comment by AbuGosok** [comment]
@bastiflew tried your quick fix, did not work. I still had to restart the bot regularly. It does cleanup on startup.

**Comment by NecronomiconCoding** [comment]
should be fixed with upcoming version
