### ISSUE TITLE
Hatching eggs -> prioritize 10 km

### ISSUE THREAD

**Issue by franner** [NECROBOTIO/NecroBot#1579]
Thanks for adding hatching eggs (incurbator) in the latest versions.

I was hoping that you might add a priority list which eggs to hatch first. So the priority list would suggest:
1. 10 km egg
2. 5 km egg
3. 2 km egg

I have tried looking at the process and I think the bot chooses the upper left egg with incurbator always. That way it might take many movements to get to the 10 km egg which is in another place in the list through it would be chosen eventually. I don't know if this is on purpose.

**Comment by RoseFlunder** [comment]
Just for your information: The current logic prefers "long distance eggs" for the limited usage incubators and "short distance eggs" for the unlimited usage incubator.

But its still the question if this behaviour should be customizable.

**Comment by franner** [comment]
Okay then thats the reason it only chooses the lower eggs currently as I only have the unlimited incurbinated (used the rest previously)..

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2008

**Comment by RoseFlunder** [comment]
PR available:
[https://github.com/NECROBOTIO/NecroBot/pull/2479](https://github.com/NECROBOTIO/NecroBot/pull/2479)
