### ISSUE TITLE
Erro when location (latitude or longitude) is negative

### ISSUE THREAD

**Issue by kanfkasndklasdn** [NECROBOTIO/NecroBot#1591]
It take as a worth value and overwrites with default conf file

**Comment by Iormangund** [comment]
yeah, problem is 
if (settings.DefaultLongitude <= 0)
doesn't account for negatives. was going to make an issue but you bear me to it.
I guess we need to convert it to absolute first then check it, that or just remove <

**Comment by simplyphp** [comment]
Resolved for lat, lon and altitude, just awaiting merge.

**Comment by recon88** [comment]
Has been merged already. Closing.
