### ISSUE TITLE
Web socket => ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by LeaklessGfy** [NECROBOTIO/NecroBot#1608]
Hi,

I asked for documentation for websocket and some reply me a simple link that lead through a project.
1/ We're not involve in the project so we can't guess that
2/ It's not an answer

I got this "ERR_INSECURE_RESPONSE" error when I try to make communication between socket, guess it's linked to the cert.pfx file but again without documentation ... Hard to guess.
When I try to import this certificate to google it required a password... I don't have it.

So I repeat my self, this is an issue that required to be consider, could we have documentation without having disrespectful answer ?

https://github.com/NecronomiconCoding/NecroBot/issues/1540

Thanks !

**Comment by actislav** [comment]
"necro" is password, but any client can ignore self signed cert... and make connection with "insecure" host, just try another one (dark for example from chrome apps)

**Comment by LeaklessGfy** [comment]
Oh yeah get that. Thanks

Also this socket server can work with socket.io ? I try to make connexion, it work but got no event ... some the connect event don't trigger ... :/

**Comment by LeaklessGfy** [comment]
Ok I create a new socket service with the original object and not socket.io.

Thanks again !

**Comment by actislav** [comment]
i do not sure about socket.io, as i can say it will not work with our web socket service just out of box, it must be supported from server side, but just a simple javascript will 
create index.html, past `<html>
  <body>
    <p id='message'></p>
    <script>
      var HOST = 'wss://127.0.0.1:14251'
      var ws = new WebSocket(HOST);
      var el = document.getElementById('message');
	  var messages = '';
      ws.onmessage = function (event) {
	    messages = event.data + "<br>" + messages;
        el.innerHTML = messages;
      };
    </script>
  </body>
</html>` 
and open in your browser

**Comment by LeaklessGfy** [comment]
Yup thanks, I'm working  on it now :D socket.io wasn't the best choice
