### ISSUE TITLE
Using Great/Ultraballs instead of Pokeballs

### ISSUE THREAD

**Issue by blackouter** [NECROBOTIO/NecroBot#1615]
Not using Pokeballs on low CP/IV Pokemons anymore - instead using the "best" ball available.

**Comment by mcdax** [comment]
I have the same problem since the bot has updated to v0.5.0

**Comment by otong123** [comment]
same here v0.5.0 
always use ultra ball

**Comment by lolcheat321** [comment]
I posted my solution in the my own thread, just change te config:

  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000,

**Comment by blackouter** [comment]
works fine, thank you.

**Comment by ahmadsafar** [comment]
fix with this [#1619](https://github.com/NecronomiconCoding/NecroBot/pull/1619)
