### ISSUE TITLE
Using berry on everything

### ISSUE THREAD

**Issue by blackouter** [NECROBOTIO/NecroBot#1622]
Bot is wasting all Razz Berries on low cp/iv pokemon like Rattatas etc.
0.5.0

**Comment by BennySupreme** [comment]
Same

**Comment by OgaaaH** [comment]
me too

**Comment by Lionegg** [comment]
Me too plz help me, i have lost all of my berrys, and when a need for a legendary pokemon, i just dont have the fuking berrys
