### ISSUE TITLE
Rocket API

### ISSUE THREAD

**Issue by deathart** [NECROBOTIO/NecroBot#1631]
Hi,

This repos yamashi/Rocket-API is delete ?

**Comment by er4zox** [comment]
Getting the same error:

$ git submodule update --force
Cloning into 'C:/git/NecroBot/FeroxRev'...
remote: Repository not found.
fatal: repository 'https://github.com/yamashi/Pokemon-Go-Rocket-API/' not found
fatal: clone of 'https://github.com/yamashi/Pokemon-Go-Rocket-API' into submodule path '.../git/NecroBot/FeroxRev' failed

**Comment by navidemad** [comment]
Yes, change in .gitmodules: **yamashi** to **FeroxRev**
Then in the prompt type:
```
git submodule sync
git submodule init
git submodule update
```

**Comment by septemus** [comment]
https://github.com/NecronomiconCoding/NecroBot/pull/1524

**Comment by septemus** [comment]
Should be fixed. All you need to do is pull latest and `git submodule update --init`

**Comment by deathart** [comment]
What ? https://github.com/NecronomiconCoding/NecroBot/commit/a3c5a4077cf52d3c5a999eb3b1b2c21304fac732
