### ISSUE TITLE
UseSnipeOnlineLocationServer doesn't work

### ISSUE THREAD

**Issue by opallblue** [NECROBOTIO/NecroBot#1632]
I set snipe as follow, but it doesn't work. Need help!

"UseSnipeOnlineLocationServer": true,
"UseSnipeLocationServer": false,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,

**Comment by Cuuup** [comment]
Same problem

**Comment by koubie** [comment]
@Tsuki ? can you make a new updated compiled file like yesterday for the new updated v0.5.0 Release version?
thank you

**Comment by recon88** [comment]
Has been fixed in 0.5.0

**Comment by xsorifc28** [comment]
What/where is the online server? Is it pokesnipers.com ?

**Comment by recon88** [comment]
Skiplagged but it's currently overloaded and slow.
