### ISSUE TITLE
V 0.5.0 ---- Always use Ultraball till it empty

### ISSUE THREAD

**Issue by OgaaaH** [NECROBOTIO/NecroBot#1633]
Always use Ultraball till it empty

**Comment by lolcheat321** [comment]
Change your configs so that:

"UseGreatBallAboveIv": 100000,
"UseUltraBallAboveIv": 100000,

To keep the script from tossing your good balls at the pokemon.

**Comment by OgaaaH** [comment]
It doesnt work
Pada tanggal 1 Agt 2016 08.28, "lolcheat321" <notifications@github.com>
menulis:

**Comment by duracelpupu** [comment]
"UseGreatBallAboveCp": 100000,
  "UseUltraBallAboveCp": 100000,
  "UseMasterBallAboveCp": 100000,
  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000,
  "UseGreatBallBelowCatchProbability": 0.01,
  "UseUltraBallBelowCatchProbability": 0.01,
  "UseMasterBallBelowCatchProbability": 0.01,

with this i got it to use normal pokeballs for now

**Comment by OgaaaH** [comment]
Thanks , it works

**Comment by duracelpupu** [comment]
am still looking into how it works with pokemons tht kinda need it so ill post it somewhere if ill make some changes

**Comment by iplaywithdrums** [comment]
Think of CatchProbability as the decimal form, as opposed to percentage form.

"UseGreatBallBelowCatchProbability": 0.12,
"UseUltraBallBelowCatchProbability": 0.08,

http://i.imgur.com/C8np0Gx.png

**Comment by duracelpupu** [comment]
yup thts wht am looking at right now. its just tht at this time of day and place where im using the bot am only geting bad pokemons its hard to adjust it.

**Comment by OgaaaH** [comment]
"UseGreatBallAboveCp": 500,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 0,
  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000,
  "UseGreatBallBelowCatchProbability": 0.4,
  "UseUltraBallBelowCatchProbability": 0.3,
  "UseMasterBallBelowCatchProbability": 0.0,



thats my setting , seems normal now

**Comment by duracelpupu** [comment]
ill try those or some with little bit less % on it

**Comment by DLHC** [comment]
Hi there, i've got the same issue, they keep use my Ultraball.... i've follow you guys code

"UseGreatBallAboveCp": 500,
"UseUltraBallAboveCp": 1000,
"UseMasterBallAboveCp": 0,
"UseGreatBallAboveIv": 100000,
"UseUltraBallAboveIv": 100000,
"UseGreatBallBelowCatchProbability": 0.4,
"UseUltraBallBelowCatchProbability": 0.3,
"UseMasterBallBelowCatchProbability": 0.0,

but seems not work......


`{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": false,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 0,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 22.280250,
  "DefaultLongitude": 114.173884,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "KeepPokemonsThatCanEvolve": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "KeepMinCp": 700,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "PrioritizeIvOverCp": true,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 60,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 10,
  "MaxTravelDistanceInMeters": 20000,
  "TotalAmountOfPokebalsToKeep": 140,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 50,
  "UseGreatBallAboveCp": 500,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 0,
  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000,
"UseGreatBallBelowCatchProbability": 0.4,
"UseUltraBallBelowCatchProbability": 0.3,
"UseMasterBallBelowCatchProbability": 0.0,
  "TransferDuplicatePokemon": true,
  "FavoriteMinIvPercentage": 0.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 50
    },
    {
      "Key": "itemNanabBerry",
      "Value": 50
    },
    {
      "Key": "itemWeparBerry",
      "Value": 50
    },
    {
      "Key": "itemPinapBerry",
      "Value": 50
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "farfetchd",
    "farfetchd",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "zubat": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pidgey": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Weedle": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Caterpie": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Rattata": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Spearow": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Ekans": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Clefairy": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Oddish": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Paras": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Venonat": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Bellsprout": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Goldeen": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magikarp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonite": {
      "KeepMinCp": 360,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}`

**Comment by JavaReturn** [comment]
Hello! I think there is an error, I have lost 100hiperpotion... I think everybody would put it like this "ItemHyperPotion" whit the first in cap, or recycling, you will leave everything... I think you can put strangeitems in value 100
