### ISSUE TITLE
KeepMinCP not being honored

### ISSUE THREAD

**Issue by sammyx91** [NECROBOTIO/NecroBot#1635]
Hi,

after the auto upgrade to the latest version this is setting is no longer being honored! 

I have it set to 700 however it still is transferring Pokemon over 700 cp.

This was not an issue until my app auto upgraded.

thanks

**Comment by sammyx91** [comment]
[11:30:04] Scyther	- CP: 1317  IV: 30.21%   [Best CP: 1379  IV: 34.05%] (Candies: 75)
[11:30:09] Scyther	- CP: 1155  IV: 55.19%   [Best CP: 1379  IV: 34.05%] (Candies: 76)


 "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": -33.86882,
  "DefaultLongitude": 151.209296,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "KeepMinCp": 700,
  "KeepMinDuplicatePokemon": 2,
  "KeepMinIvPercentage": 90.0,
  "PrioritizeIvOverCp": false,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokebalsToKeep": 200,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 20,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.4,
  "UseMasterBallBelowCatchProbability": 0.05,
  "TransferDuplicatePokemon": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [

**Comment by recon88** [comment]
Check the PokemonsTransferFilter
