### ISSUE TITLE
Option for Berry use

### ISSUE THREAD

**Issue by paperc07** [NECROBOTIO/NecroBot#1647]
It is automatically using berries on every pokemon which isn't the end of the world, but maybe add an option to use berries on a certain cp or iv amount

**Comment by reinforcers** [comment]
agree on this one, an option for berries by CP or IV perhaps

**Comment by narusFR** [comment]
Would appreciate this too

**Comment by GUICenter** [comment]
Sorry, didn't see this as I searched razz not berry. Thanks.
