### ISSUE TITLE
SNIPING not displaying results(escape/success/flee) after v0.5.0 update

### ISSUE THREAD

**Issue by Mr-SoloSilver** [NECROBOTIO/NecroBot#1660]
![bug1](https://cloud.githubusercontent.com/assets/20763544/17282422/95bf3c8e-5773-11e6-8fad-dd7b39c5f00a.PNG)

No results being displayed, only the action. see screenshot.

thanks!

**Comment by koubie** [comment]
how did you make the sniping work? I cant figure out how. please help
