### ISSUE TITLE
Not Showing Hatched Egg's

### ISSUE THREAD

**Issue by Energex22** [NECROBOTIO/NecroBot#1669]
The log no longer seems to show when a egg hatches... Really wish it did, enjoyed knowing.... lol
Also noticed that no matter the speed i set, the egg's seem to take quite a while to rack up the km, around 4 time the length if i was actually walking the speed i set.

**Comment by eyeball3r** [comment]
What's your travel speed set to?

**Comment by dddbliss** [comment]
Are you taking into account that while the bot is doing transfers, item management, evolutions / leveling, you are not actually moving? This will add time to an eggs hatching.

The log not showing is a bug, I noticed today that it doesn't for me as well.

**Comment by Energex22** [comment]
yeah i figured that the pokestops ect would account for about 1/2 the time i'm thinking of, might just be a glitch, noticed even on my phone that it doesn't track 100% correctly...
