### ISSUE TITLE
Default Values in Settings after Update (new unset Values)

### ISSUE THREAD

**Issue by Aneduna** [NECROBOTIO/NecroBot#1678]
You probably want to keep your Settings file after an update, but after an update the default value is ignored and set to 0, false, null. I'm not experienced with the newtonsoft Json Deserializer, but it may has to something with either
[NullValueHandling](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm )
or
[DefaultValueHandling](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm.)

I'm not sure how to do that, but even a notification after a new value is added would be awesome

**Comment by recon88** [comment]
Please check #1801 for further updates and information.
