### ISSUE TITLE
Pokemon level up issues?

### ISSUE THREAD

**Issue by KapilTapsi** [NECROBOTIO/NecroBot#1679]
Pokemons with highest cp should be leveled up first to its maximum, then next maximum. 
any specific configuration for this.

How to configure for only two duplicate pokemons(with maximun cp in their category).

My question may be in wrong category. I'm sorry for that.

**Comment by pikachukaki** [comment]
i wanna ask this too it has option to evolve but high cp/iv pokemons wont have nothing to evolve only level up/power up!!!

**Comment by recon88** [comment]
Please join our Discord if you need help with the configuration: https://discord.gg/VXKxNFr
