### ISSUE TITLE
Ultraballs and Greatballs being used for every pokemon

### ISSUE THREAD

**Issue by chimichandra** [NECROBOTIO/NecroBot#1681]
Ultraballs and greatballs are used on every pokemon. Accumulating PokeBalls...

**Comment by Aneduna** [comment]
Set these Values in the settings, happening because #1678 
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,

**Comment by chimichandra** [comment]
Thanks! It works. I did not try decimals in the probability.

**Comment by Victh** [comment]
@Aneduna I've updated my config with your value above, but why I still catch weaker monsters with great balls?

![sshot-681](https://cloud.githubusercontent.com/assets/9425865/17283779/89cd2146-57de-11e6-8b0e-01e31c7ac310.jpg)

**Comment by Aneduna** [comment]
Because "UseGreatBallAboveIv": 85
Change that if you want. This setting is good because it ensures that this high IV Pinsir does not escape

**Comment by Victh** [comment]
@Aneduna can I disable the IV checking altogether? Like just doing raw CP checking?

**Comment by Aneduna** [comment]
"UseGreatBallAboveIv": 101,
"UseUltraBallAboveIv": 101,
May just work fine, but i'm not sure
Also Just checking for CP everywhere at once is not possible(?). You'd have to change every option where iv is mentioned

**Comment by hotylerho** [comment]
Can I disable the razzberry using settings?  thank you

**Comment by Aneduna** [comment]
Not Yet. Would be a good feature to implement.
Correct me if i am wrong tho
The condition to useBerry is 
`if ((isLowProbability && isHighCp) || isHighPerfection)` in CatchPokemonTask.cs Line 59

in useBerry there doesn't seem to be another condition
