### ISSUE TITLE
Can I disable the function for using Razz Berry to catch pokemon? Thank you

### ISSUE THREAD

**Issue by hotylerho** [NECROBOTIO/NecroBot#1691]

**Comment by rherartt** [comment]
you can throw all the berries away so it wont use

**Comment by Aneduna** [comment]
Not yet, but if you are compiling from source, you can change
`if ((isLowProbability && isHighCp) || isHighPerfection)` in CatchPokemonTask.cs Line 59
to
`if (false)` 

but it is a pretty dirty hack

**Comment by Andrerm124** [comment]
About to submit a pull request implementing this feature (As well as logging razzberry use)
