### ISSUE TITLE
[12:52:21] You're outside of your defined radius! Walking to start (2888124.53678202m away) in 5 seconds. Is your LastPos.ini file correct?

### ISSUE THREAD

**Issue by artsy23** [NECROBOTIO/NecroBot#1694]
not sure what i should do

**Comment by Aneduna** [comment]
duplicate issue
#1675 
#1684

**Comment by tangdami** [comment]
Same issue happened after the new API throttling. Had to restart the bot every time..

**Comment by actislav** [comment]
if u using snipe i finally fix it in @ #1706
