### ISSUE TITLE
poke UI

### ISSUE THREAD

**Issue by ndut1986** [NECROBOTIO/NecroBot#1695]
can you make poke ui where we can see whole pokemon on our storage with their cp, IV, candies that pokemon has, and stardust that we have, then we can chose manually upgrade, evolve, or transfer it

**Comment by antwa** [comment]
just use android emulator and disable GPS.

**Comment by Aneduna** [comment]
This Project only has console. Making a gui would be counter intuitive.
Look at some forks, maybe one has a gui. Or you can use @antwa method and use an emulator to start the game. If you have gps disabled you will not get soft banned

**Comment by dbw-holic** [comment]
@ndut1986 Try this, [necrobotvisualizer](https://github.com/nicoschmitt/necrobotvisualizer)

**Comment by Fazy5** [comment]
Ill have to go against @Aneduna  on that.. I have been using my mobile to check on pokemons/evolve on choice/transfer on choice etc .. and have never been softbanned. I turn Bot off, use it, and then turn it back on the very second (bot has a location im no where near , like ~5000km away) and i have never been softbanned.
Just do the following.
- Turn GPS off "THEN" start the pokemon go app.
OR
- If you have marshmallow, Just disable all 4 permissions pokemon go app asks for. and when you open the game it will ask for permission, just choose never ask and then deny all 4 permissions.

**Comment by Aneduna** [comment]
@Fazy5 
> If you have gps disabled you will not get soft banned

**Comment by recon88** [comment]
As mentioned above, use necrobotvisualizer for now. We might or might not implement our own UI but that's currently not a high priority.
