### ISSUE TITLE
Still catching "LURED" pokemons even if its on the pokemontoignore list

### ISSUE THREAD

**Issue by erikeleria** [NECROBOTIO/NecroBot#1697]
https://i.imgur.com/T4EKK3Z.jpg

https://i.imgur.com/HjSqOey.jpg

**Comment by jbadumm** [comment]
is UsePokemonToNotCatchFilter set to true?

**Comment by erikeleria** [comment]
Yes its set to true.

**Comment by recon88** [comment]
Could you please get on our Discord and ask for assistance there? This doesn't seem to be a bug but wrong configuration.
https://discord.gg/VXKxNFr
