### ISSUE TITLE
Getting an unstable servers error resets GPX pathing

### ISSUE THREAD

**Issue by GediminasMasaitis** [NECROBOTIO/NecroBot#1699]
When using GPX pathing and getting an unstable servers error: 

> [10:56:56] Niantic Servers unstable, throttling API Calls.

It makes you walk straight to the starting point, not along the path. 
Tested to be the case on v0.4 and v0.5

**Comment by PhilPhonic** [comment]
Same here with v0.5.0 (and 0.4.0)
The bot is also "spamming":
> [17:53:29] (UPDATE) [Evolves] Potential Evolves: 4 | 30 required for mass evolving
> [17:53:29] (INFO) Not enough Pokemons to trigger a lucky  egg. Waiting for 26 more (4/30)
seems like he is checking something on every waypoint? perhaps this is the reason why we get resetted?

**Comment by recon88** [comment]
Check #1856 for further information and updates.
