### ISSUE TITLE
Too many things to list

### ISSUE THREAD

**Issue by dmo1111** [NECROBOTIO/NecroBot#1704]
Im grateful for this place but it seems someone is trying to hijack this project for the worst. 

I mean, several things don't work correctly.  I know people arent that bad at coding.

**Comment by hilycker** [comment]
Who that someone would be?

**Comment by GediminasMasaitis** [comment]
Some real illuminati shit you've uncovered there m8.

**Comment by nfettinger** [comment]
This is not helpful to developers. You need to list specific issues you are having, including methods you use to reproduce the issue. If you have time, finding the root cause, and suggesting a fix will help expedite the fixing of the problem.

I suggest this issue be closed.
