### ISSUE TITLE
Always using ultraball

### ISSUE THREAD

**Issue by xspel** [NECROBOTIO/NecroBot#1709]
I already set
`  "UseGreatBallAboveCp": 0,
  "UseUltraBallAboveCp": 2500,
  "UseMasterBallAboveCp": 3000,
  "UseGreatBallAboveIv": 0,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 100.0,
  "UseUltraBallBelowCatchProbability": 10.0,
  "UseMasterBallBelowCatchProbability": 5.0,`

still using only ultraball or I did something wrong?

**Comment by Aneduna** [comment]
Can you check the balls you have in your inventory? Maybe you don't have any other balls?
Then check if you are sniping.
Also a Screenshot of a catch may be helpful

**Comment by neosmocking** [comment]
yeah it still using ultraball... :( 

back using version 0.4.0

**Comment by Aneduna** [comment]
Please make a screenshot of a catch message, where it is throwing an ultra ball where it should use a great/poke ball

**Comment by Kazpers** [comment]
Can confirm issue:
![image](https://cloud.githubusercontent.com/assets/14245832/17290362/5b2a5b06-57de-11e6-8ee0-35ff6c53a57a.png)

**Comment by neosmocking** [comment]
sorry forgot to screen shoot, now my ultra ball is gone, I'm using v 0.4.0 to collect them again.

**Comment by Kazpers** [comment]
Actually I think it has to do with the new Config options and how they interact with each other...

**Comment by Kazpers** [comment]
No I was wrong. After restarting the bot again, it went back to using Ultraballs every time.

**Comment by Aneduna** [comment]
Yea, seems like it is bugged for you. You are using the release version? The Release version does exactly what is does. Very Strange

**Comment by S1068835** [comment]
I have the same problem. AboveIv and CatchProbability were all 0 with update 0.5. I changed them, but I still catch every pokemon with an ultraball.

**Comment by xspel** [comment]
I already got version 0.5.0 from auto update.


![untitled](https://cloud.githubusercontent.com/assets/20769071/17290845/b4beb3a2-580a-11e6-99e4-21dc1e1c6868.png)
And this ultraball from 200+ now just 54.

**Comment by xdiablo1990** [comment]
Just change this:
  "UseGreatBallAboveIv": 100000,
  "UseUltraBallAboveIv": 100000, 

now use pokeball

Sorrry for  me english ahahha :8ball:

**Comment by Aneduna** [comment]
@xdiablo1990 Exactly that is the problem, it does not seem to work

**Comment by neosmocking** [comment]
this is how it should be.

![2016-08-01_17-14-16](https://cloud.githubusercontent.com/assets/20575324/17291011/a87b76c4-580b-11e6-8e59-c3bce5bc83e7.png)

**Comment by xdiablo1990** [comment]
use this confing:
"UseGreatBallAboveCp": 100000,
"UseUltraBallAboveCp": 100000,
"UseMasterBallAboveCp": 100000,
"UseGreatBallAboveIv": 100000,
"UseUltraBallAboveIv": 100000,
"UseGreatBallBelowCatchProbability": 0.01,
"UseUltraBallBelowCatchProbability": 0.01,
"UseMasterBallBelowCatchProbability": 0.01,

**Comment by S1068835** [comment]
@xdiablo1990 this seems to work for now

**Comment by Kazpers** [comment]
Yes that seems to be a workaround, although it removes all detail and just uses weakest ball every time. Still much better.

**Comment by xdiablo1990** [comment]
i just try help us guys :)

**Comment by xdiablo1990** [comment]
us can help now¿ check this https://github.com/NecronomiconCoding/NecroBot/issues/1721

**Comment by xspel** [comment]
Worked! Thanks. But just temporary now dev have to fix this next release.

**Comment by xdiablo1990** [comment]
I just looked for a solution and I'm glad that I work and sorry for my English hahaahaha

**Comment by Metero** [comment]
I solved the problem with my configs:
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,

befor the changes, i was wondering about the same issues. can somebody confirm?
(ver 0.5.0)
![unbenannt](https://cloud.githubusercontent.com/assets/4226833/17298726/785db8ee-580b-11e6-8a73-c3b2e7b0e584.PNG)

**Comment by DRockwell** [comment]
Issue is the setting using "25.0" as 25% instead of "0.25"

**Comment by JSBeard** [comment]
It's the IV functionality. The catch probability works fine.

**Comment by iruca1602** [comment]
i use @Metero config, only change into this:
"UseGreatBallAboveIv": 85,
"UseUltraBallAboveIv": 95,

it works!

**Comment by dddbliss** [comment]
Tracking bug on #1879

**Comment by dddbliss** [comment]
Merged for next release.
