### ISSUE TITLE
Bot stop working after awhile.

### ISSUE THREAD

**Issue by N3evin** [NECROBOTIO/NecroBot#1717]
I realize that the bot stop working after i leaving it on for some time. It will the continue when i pressed enter.

**Comment by sawirth** [comment]
Try set  `StartupWelcomeDelay` to false. The bot will then continue automatically when an error occurs.
Did you get an error message before it stopped?

**Comment by N3evin** [comment]
Hi, i did set it to false, there is no error. It just happen to stop there. It stops from 2pm, then when i come back i pressed enter then the time continue from 7pm.

**Comment by sawirth** [comment]
did your pc went to energy saving mode or something?

**Comment by N3evin** [comment]
Nope did not.

**Comment by NecronomiconCoding** [comment]
Are you using 0.5.0 ?

**Comment by N3evin** [comment]
Yeah I'm using 0.5.0

**Comment by Sylencer90** [comment]
Facing the same issue, had to restart twice. It randomly starts freezing without any error output.
No sniping feature on.

**Comment by baklaforever** [comment]
sniping is buggy i turned it off as well

**Comment by colinodell** [comment]
I can confirm this same behavior - the console stops updating after some amount of time, and pressing a key causes it to "unfreeze" and resume.  Sometimes I'll see a message about "throttling" some time after it "unfreezes" but not always.

The application itself does not close and there are no errors in the console.

**Comment by GeForce66** [comment]
I also have the error with lots of "throttling API" messages after a random amount of time since bot start.
Therefore the bot is rendered useless when in this state.
Bug?

**Comment by theloser** [comment]
Check your console setting. If "QuickEdit" is on, a click into the console window will select a single character and "stop" output to console (and the program) until you press ENTER or ESC. Turn "QuickEdit" off.

**Comment by N3evin** [comment]
Yeah, quick edit is not on. But it happen.

**Comment by recon88** [comment]
If this is still an issue on 0.6.2, open a new ticket a provide steps to reproduce
