### ISSUE TITLE
limited usage incubators dont used

### ISSUE THREAD

**Issue by Phoenix10King** [NECROBOTIO/NecroBot#1718]
goodmorning
after update 0.5.0

my bot use only the unlimited usage incubators with 2km eggs
and never uses the limited x3 usage incubators 

i do have 5 limited usage incubators  but no one is used 
why ???

**Comment by Megurine** [comment]
True.

**Comment by Aneduna** [comment]
What eggs do you have?

**Comment by Megurine** [comment]
2km and 5km.

**Comment by Aneduna** [comment]
I'm not sure, but it may be that limited incubators are only used on 10km eggs to maximize efficiency

**Comment by Aneduna** [comment]
Just Checked, should actually use limited incubators also on lower eggs

**Comment by Phoenix10King** [comment]
i do have all kind of eggs 2km 5km and 10km
any idea how to fix that ??

**Comment by Aneduna** [comment]
No, sorry. It is working for me.

is `"UseEggIncubators": true,` true?

it should be on by default and im not sure if it is using the regular incubator if it is off, but please check

**Comment by Phoenix10King** [comment]
UseEggIncubators True
but nothing happens, was true from before

**Comment by recon88** [comment]
Can others confirm that it is not using limited eggs?

**Comment by mik5u** [comment]
its using 1 incubator only for me to

**Comment by AcidBurns** [comment]
confirming: I got 2, 5 and 10km eggs and 3 incubators. only the unlimited one is used, the others are not used until i manually insert an egg. Reuse does not occur once the egg is hatched

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
