### ISSUE TITLE
[Help Request] Bot Won't Evolve from List

### ISSUE THREAD

**Issue by jakesmurf** [NECROBOTIO/NecroBot#1722]
My PokemonToEvolve list isn't being used.  My bot isn't evolving any pokemon at start up or during use and I can't figure out why.  I didn't have this problem using the same-ish config before.  .  

Trying to use the new keeppokemonthatcanevolve/whatever the new evolvekeptpokemonatwhateverbagcapacity setting doesn't seem to help in any context and only results in my bag filling up with pokemon that I want to evolve but it simply won't....

`If I enable "EvolveAllPokemonWithEnoughCandy" it will evolve, but then it consumes candy of species that I don't actually want evolved (Dratini's).  `

EDIT:  Actually, my bot won't evolve anything even with EvolveAllWithEnough enabled now....

**Comment by superjacke** [comment]
same here...
I just use the 0.4.0 earlier release to evolve atm

**Comment by recon88** [comment]
Try setting KeepPokemonsThatCanEvolve to false

**Comment by h3300420** [comment]
ME to ,it is first Transferded, not first evolve.

**Comment by recon88** [comment]
This seems to be an issue with your configuration. Please visit our Discord for further help: https://discord.gg/VXKxNFr
