### ISSUE TITLE
[Suggestion] use 'AND' rather than 'OR' in the conditions to choose higher level ball

### ISSUE THREAD

**Issue by nmly** [NECROBOTIO/NecroBot#1725]
It seems that there are three conditions (cp, iv, success rate) to decide which ball to use. But it doesn't make sense to throw a greater ball on something with low success rate and pretty low cp as well. I guess the conditioning control in the code is 'OR' which cause a waste of higher level ball. If possible, changing to 'AND' would be ideal.

**Comment by sawirth** [comment]
In the config you can define when to use which ball. Currently my config looks like this:
```
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 0,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,
```
The default values are 0 so it always uses the best ball first (except masterball) since the code looks like this:
```
if (ultraBallsCount > 0 && (
                    pokemonCp >= session.LogicSettings.UseUltraBallAboveCp ||
                    iV >= session.LogicSettings.UseUltraBallAboveIv ||
                    probability < session.LogicSettings.UseUltraBallBelowCatchProbability))
                return ItemId.ItemUltraBall;

            if (greatBallsCount > 0 && (
                    pokemonCp >= session.LogicSettings.UseGreatBallAboveCp ||
                    iV >= session.LogicSettings.UseGreatBallAboveIv ||
                    probability < session.LogicSettings.UseGreatBallBelowCatchProbability))
                return ItemId.ItemGreatBall;

```

**Comment by sawirth** [comment]
Try to set these values to something like this:
```
"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 0,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,
```
The default values are zero which makes the bot select the best ball first (except masterball).

**Comment by nmly** [comment]
thanks @sawirth 

there is the values in my config

"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.025,


But i do see that it is throwing the great balls on something with success rate about 19% but at cp around 600. :) So I guess that it could avoid the waste if change to 'AND'.

**Comment by sawirth** [comment]
imo this is not a waste because it was a low probability and that means a better ball is required. 
So I would stick to current implementation. 
Are you constantly running out of ultra or great balls?

**Comment by nmly** [comment]
@sawirth 

yes i constantly running out great balls, when i put the success rate threshold as 0.3. It seems to get some stock now after i put as 0.2....
