### ISSUE TITLE
Polish letters are not displayed correctly

### ISSUE THREAD

**Issue by jasio77** [NECROBOTIO/NecroBot#1737]
I noticed that polish letters aren't displayed correctly when set to Polish language.
![screenshot_1](https://cloud.githubusercontent.com/assets/20771421/17293027/03a26468-57ee-11e6-8569-18da7412e214.png)

**Comment by RoseFlunder** [comment]
have you tried to set the cmd font to "Consolas" in the settings of the cmd? (right click in title bar -> settings)

**Comment by Marsinator** [comment]
#1768

**Comment by recon88** [comment]
Do what @RoseFlunder said and it will work ;)
