### ISSUE TITLE
use pokeball at high CP for specific pokemon ( like Pinsir...)

### ISSUE THREAD

**Issue by cr4sh62** [NECROBOTIO/NecroBot#1745]
I should be great to choose what ball use on what pokemon.

I put the config to : 
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.25,
  "UseUltraBallBelowCatchProbability": 0.19,
  "UseMasterBallBelowCatchProbability": 0.05,

But I still catch pinsir 1500+ and the bot use a ultraball for nothing ... same with pinsir/ rattata etc ... 85+ or 95+ who nobody needs.

Can you just add a section "usepokeballfor" then put Pinsir and other crap like this in ?

Thanks

**Comment by theloser** [comment]
> But I still catch pinsir 1500+ and the bot use a ultraball for nothing

So, you had some Masterballs at that time? If no, using Ultraballs is correct according to your settings.

> same with pinsir/ rattata etc ... 85+ or 95+ who nobody needs

What were their catch probabilities? Were they below 19%? If so, everything works how you wanted it to work (see "UseUltraBallBelowCatchProbability": 0.19).

**Comment by cr4sh62** [comment]
I don't get Masterball :D but , this option for pokemon like Pinsir where candies are useless ( 2000+ ... ) If you fail some pokeball it's not a bad thing :) and you keep great and ultra ball for usefull pokemon that can be great !

**Comment by recon88** [comment]
**OP's suggestions:**
Add a whitelist for Pokeballs only:
- UsePokeballsFor
Everything you put in there will caught by pokeballs. If you run out of Pokeballs, it will use the next higher one?!

**My Suggestions:**
Add an ignore list for every pokeball
- pokemonToIgnoreWithPokeball
- pokemonToIgnoreWithGreatball
- pokemonToIgnoreWithUltraball

**Comment by sawirth** [comment]
@recon88 imo the current ways to config the usage of pokeballs together with the ItemRecycleFilter should be good enough so the bot doesn't "waste" better balls. 
Together with the logic in OptimizeRecycleBalls the player should always have a decent amount of the right balls.
Best way to fix it if you increase `UseUltraBallAboveCp` and decrease `UseUltraBallBelowCatchProbability`.

This just adds three more settings and increases code complexity with only a small benefit.

**Comment by JonWallsten** [comment]
I would also like a feature like this. Looking through my logs I have so many CatchFlee for Dratinis. And they are rare as it is. I would like to use Ultra balls no matter CP/IV just for the candy. But if I use the settings we have no these balls will also be used for mons I don't really care about.
