### ISSUE TITLE
[FeatureRequest] Transfer Pokemon based on MOVES

### ISSUE THREAD

**Issue by yoshi2323** [NECROBOTIO/NecroBot#1753]
I need to get rid of high IV pokemon with the wrong moveset, my accounts are bursting....
Best thing for me would be a list to add pokemon + their desired moves + individual IV cutoff:

"Dragonite": { "Move1": "DragonBreathFast", "Move2":"DragonClaw", "minIV":95},
........

edit: maybe we just need to add move1 and move2 attributes to the "PokemonsTransferFilter" to achieve this

**Comment by yoshi2323** [comment]
my idea was to check for move1 AND move2, to filter out pokemon where BOTH moves are best

**Comment by burgerbutts** [comment]
As of right now it seems to be keeping pokemon of any CP/IV value as long as they have a single skill from the move list.

There should definitely be a way to consider which pokemon the bot should keep, and an option to consider one or both moves. Something similar to this, I would assume:

- check settings to use single or both moves
- has single or both moves
- check PrioritizeIvOverCp
- compare to find the best
- transfer the rest
