### ISSUE TITLE
IndexOutOfRangeException when starting the bot

### ISSUE THREAD

**Issue by KaskadekingDE** [NECROBOTIO/NecroBot#1755]
The bot doesn't work for me anymore. I also deleted my config and generated a new one but it just throws a IndexOutOfRange Exception:

`[15:30:05] System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei PoGo.NecroBot.Logic.Tasks.GetPokeDexCount.<Execute>c__async0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>c__async0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>c__async0.MoveNext()`

**Comment by dddbliss** [comment]
Fixed in #1646
