### ISSUE TITLE
Favoriting Pokemon runs even though it is already a favorite

### ISSUE THREAD

**Issue by nfettinger** [NECROBOTIO/NecroBot#1763]
Marking high IV pokemon as favorites is run even though the pokemon is already marked as a favorite.
It seems that pokemon.Favorite is always 0. 

Edit:
After a bit of debugging, it appears that the favorite request to the server is not accepted. Logging into the account with a device shows that the Pokemon is not marked as a favorite. This is most likely an issue with the API.

**Comment by ifbatmanwasreal** [comment]
Was wondering why it kept favoriting over and over again. Got kind of annoying

**Comment by nfettinger** [comment]
I suggest in the meantime, configure AutoFavoritePokemon to false to reduce the spam.

**Comment by ifbatmanwasreal** [comment]
Yup, that's what I did. No point in favoriting if it's not even going to register.

**Comment by lorenzbaum** [comment]
In Python i used [POGOProto](https://github.com/AeonLucid/POGOProtos/) and the following code worked for me:

    def favoritePokemon(self, pokemon, favorite):
        # Create request
        payload = [Request_pb2.Request(
            request_type=RequestType_pb2.SET_FAVORITE_POKEMON,
            request_message=SetFavoritePokemonMessage_pb2.SetFavoritePokemonMessage(
                pokemon_id=pokemon.id,
                is_favorite=favorite
            ).SerializeToString()
        )]

        # Send
        res = self.wrapAndRequest(payload)

        # Parse
        self._state.favorite.ParseFromString(res.returns[0])

        # Return everything
        return self._state.favorite

Maybe you could reuse it.

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.

**Comment by turbozapekanka** [comment]
Yes it keeps Favoriting in 0.6.2

**Comment by simplyphp** [comment]
https://github.com/AeonLucid/POGOProtos/issues/110
