### ISSUE TITLE
Fix plz Russian translite

### ISSUE THREAD

**Issue by Melinio** [NECROBOTIO/NecroBot#1768]
![11111](https://cloud.githubusercontent.com/assets/12205598/17297020/773539aa-580c-11e6-949d-eb82466470f8.png)

**Comment by Oolaruu** [comment]
Latest 0.5.0 looks to be russian for me, with 
"TranslationLanguageCode": "ru_RU",
http://prntscr.com/c08kp5

Then indeed need to be updated for sure.
If you give me help, i can have a look.
@Melinio

**Comment by Melinio** [comment]
maybe not the same encoding
I use the latest version
  "TranslationLanguageCode": "ru_RU",
http://clip2net.com/s/3AM91W8

**Comment by Oolaruu** [comment]
Then must be your windows?
or something else, but in my computer except that it's not updated.
Russian are fine. W10 - Eng/Fr main language.

**Comment by h3k1ru** [comment]
Change console font to Lucida.
![tju1n4u](https://cloud.githubusercontent.com/assets/20730021/17304614/2f9bad68-582f-11e6-9688-63510aa88261.png)

**Comment by Oolaruu** [comment]
Indeed, it 's what I have too.
http://prntscr.com/c0ec0p

**Comment by Oolaruu** [comment]
Similar issue
https://github.com/NECROBOTIO/NecroBot/issues/1737

**Comment by Marsinator** [comment]
#1737
