### ISSUE TITLE
[Feature request] Ignoring all pokemon when sniping

### ISSUE THREAD

**Issue by GediminasMasaitis** [NECROBOTIO/NecroBot#1771]
When using sniping, I'd like to ignore all Pokemon that I encounter at my location, and only collect pokestops. This way, I'd save all pokeballs for the Pokemon I snipe.

The only way to do this right now is to add all low-tier and mid-tier Pokemon into the `PokemonsToIgnore` list. It would be great to have a boolean value among the lines of `IgnoreAllPokemonEncountersIfSniping`.

**Comment by actislav** [comment]
i think, you can set "PokemonToSnipe": { ... "Pokemon": [] } list to empty and have what you want

**Comment by GediminasMasaitis** [comment]
> i think, you can set "PokemonToSnipe": { ... "Pokemon": [] } list to empty and have what you want

No, that would do the exact opposite - it wouldn't snipe any Pokemon, and would capture pokemon at my location.

**Comment by actislav** [comment]
sorry my mistake/a misunderstanding, yes you are absolutely right, but it is a very specific feature, and already can be done by manipulating config settings...
