### ISSUE TITLE
LuckyEgg Evolution (or any evolution for that matter, I think)

### ISSUE THREAD

**Issue by anwachukwu** [NECROBOTIO/NecroBot#1783]
I set "UseLuckyEggsMinPokemonAmount": 85.

However, I get the message something like [Evolves] Evolutions Required 85 | 80 showing that it has enough Pokemon to evolve, but never actually enters any evolution sequence.

**Comment by icyak** [comment]
same for me

**Comment by recon88** [comment]
From Discord: 
![evolve](http://i.imgur.com/BzraIsV.png)

**Comment by oebanez** [comment]
pokemon will evolve depen on "EvolveKeptPokemonsAtStorageUsagePercentage", if u set it on 0.9. the bot will wait until your storeage in (250*0.9) = 225.

**Comment by recon88** [comment]
Just checked on Discord. This seems to be a bug and will be fixed.

**Comment by xsorifc28** [comment]
In the meantime, how can we configure lucky eggs to be triggered ?

**Comment by actislav** [comment]
i made some fixes and improvements in logic and behavior of evolve task in my pull request, now all will more clearly to understand. #1852
