### ISSUE TITLE
[Feature Request] Sort Pokemon by Lvl instead of CP or IV

### ISSUE THREAD

**Issue by anwachukwu** [NECROBOTIO/NecroBot#1784]
I find often that the best balanced Pokemon are those of higher levels...unless I have a Dragonite that has naturally high CP, most of my highest CP Pokemon are those with the highest Lvl (ie. 1-40). It would be beneficial to just keep the highest level Pokemon as they essentially have the highest potential.

**Comment by Andrerm124** [comment]
I've always wondered why this isn't the default option. I'd make this change but I think it's more of a preference thing; something I think more involved developers should decide upon.

**Comment by tangdami** [comment]
Yeeeeeeeeeeeeeees!!
I always find it very difficult to balance the CP and IV. But if there is an option to KeepMinLevel as my current LV, then picking a better IV. That would be much easier and straightforward.

**Comment by DeityOfChaos** [comment]
If this is going to be added please make it optional - I am used to the way this is x'D

I honestly think IV > all as I have thousands of candy of pretty much every pokemon, so the level doesn't really bother me x'D
