### ISSUE TITLE
Sniping and walk behavior when disconnected

### ISSUE THREAD

**Issue by can99** [NECROBOTIO/NecroBot#1798]
so the scenario is
1. necro snipe
2. character teleport to snipe location
3. connection interrupted/disconnected
4. bot reconnected
5. xxxxxxxx.xx miles away from [start point]
6. bot [walking] to [start point] at [walking speed] instead of teleport after 5sec

![image](https://cloud.githubusercontent.com/assets/20637900/17299210/932edc44-5837-11e6-8930-0751908f3eca.png)

**Comment by jasio77** [comment]
Are you using manual sniping?
If you are, then set SnipeAtPokestops to false and wait until there's fix for it.

**Comment by can99** [comment]
no, i'm using auto discord sniping

**Comment by roychross** [comment]
whats your config to make it work right?

**Comment by can99** [comment]
@roychross refer tohttps://github.com/NecronomiconCoding/NecroBot/wiki/Automatic-Locations-Sniping-Guide
you need:
1. discord id with some coords server & room
2. pokegolocationfeeder , put your discord on this config
3. latest necrobot 5.0, set the bot same with the instruction above, but "SnipeIgnoreUnknownIv": true, so it will scan most of the coords

**Comment by actislav** [comment]
bug already fixed and merged to master #1852 in commit 3388bb563656d0456b5c20d15f16e91d6bfff1d1 @simplyphp simplyphp committed on GitHub an hour ago
