### ISSUE TITLE
[Feature Request] Auto-use Incense whenever there is an active LuckyEgg

### ISSUE THREAD

**Issue by ANR2ME** [NECROBOTIO/NecroBot#1804]
Automatically activate Incense whenever there is an active LuckyEgg (which may be triggered by MassEvo),
Having another option to measure the LuckyEgg's remaining time would be better, so Incense won't be used if there is only a few seconds remaining to take advantage of double exp.

**Comment by Lord-Haji** [comment]
Also stop the bot movement if any PokeStop found near
Use of Lure Modules..

**Comment by Oolaruu** [comment]
When an Incense is used, display how many Incense still remaining in inventory.
