### ISSUE TITLE
Crash after 30min in v0.5.0

### ISSUE THREAD

**Issue by kaardilugeja** [NECROBOTIO/NecroBot#1832]
Hi, 

I am still experiencing issues with the latest version. Wasn't this fixed before?

**Comment by Oolaruu** [comment]
Which issues ?
Can you be more specific ?

**Comment by davegranlet** [comment]
he's refering to when the bot crashed after 30 mins while sniping, it IS fixed and any issues your having now with sniping are most likely caused by server lag.

**Comment by davegranlet** [comment]
this is a NON issue

**Comment by kaardilugeja** [comment]
@davegranlet 

I'm not even using sniping mode and the bot still crashes after 30min.

**Comment by davegranlet** [comment]
please post a screen
