### ISSUE TITLE
Transfer behavior not working as expected.

### ISSUE THREAD

**Issue by kbtbc** [NECROBOTIO/NecroBot#1837]
I have seven venusaurs, and have removed the relative entry from 'do not transfer' list and added the following specs:

    "Venusaur": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 4
    },

Upon starting, it still keeps all seven.  Only three are higher than either 1500CP or 95IV, but none transfer out.   It seems to add the '4' duplicate to the number of qualified pokemon to keep, instead of including the qualified keepers in the total count.

**Comment by somani6** [comment]
I guess the Venusaur is in your 'PokemonsNotToTransfer' List, so it doesn't get transfered at all.

**Comment by vipery** [comment]
I have same problem with snorlax.    Set "KeepMinDuplicatePokemon": 1 but in inventory still 6 snorlax with low cp and 95 IV

**Comment by vipery** [comment]
Sure removed from NotTransferList and:

"Snorlax": {
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 95.0,
  "KeepMinDuplicatePokemon": 1
},

**Comment by vipery** [comment]
For example. 

"Dragonite": {
"KeepMinCp": 2600,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},

1. Dragonite 2900 / 78
2. 2100 / 95

Will keep both? Just scare about settings. Few days ago bot was transfer my 2900 Dragonite

**Comment by Svennohz** [comment]
#1547

**Comment by kbtbc** [comment]
I mentioned I had removed it from the 'do not transfer' list already.  The behavior is still not as expected.
