### ISSUE TITLE
sniping error

### ISSUE THREAD

**Issue by mik5u** [NECROBOTIO/NecroBot#1839]
im using this config for manual sniping

"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,

![snipe](https://cloud.githubusercontent.com/assets/20777924/17302885/f1a608bc-5826-11e6-8b52-e32b0e89e68e.png)

**Comment by davegranlet** [comment]
caused by the server issues, open it again in a few days if it still there

**Comment by recon88** [comment]
Just let it run and wait for it to be working again
