### ISSUE TITLE
When multiple Pokemon have the same IV the one with the lowest stamina is kept

### ISSUE THREAD

**Issue by mmmfrieddough** [NECROBOTIO/NecroBot#1840]
I noticed this when I had a few Snorlax all with 100 IV and the bot decided to keep the one with the lowest CP. Looking at the code I see this in Inventory.cs:
`results.AddRange(pokemonList.Where(x => x.PokemonId == pokemon.Key)
                            .OrderByDescending(PokemonInfo.CalculatePokemonPerfection)
                            .ThenBy(n => n.StaminaMax)
                            .Skip(amountToSkip)
                            .ToList());`
I believe `.ThenBy(n => n.StaminaMax)` should be `.ThenByDescending(n => n.StaminaMax)` so that when the first pokemon on the list is kept it is the highest stamina.

**Comment by dddbliss** [comment]
#1772 corrects logic to use IV and CP

**Comment by mmmfrieddough** [comment]
@dddbliss Sorry I didn't see taht. Thank you!
