### ISSUE TITLE
Add 3rd party snipe list?

### ISSUE THREAD

**Issue by irishneil** [NECROBOTIO/NecroBot#1842]
I'm not too clued in i must admit, but would it be possible to have setting where you could link a 3rd party API list.

For example, im still using a test version of v0.4.0 for http://pokesnipers.com/

The API is: http://pokesnipers.com/api/v1/pokemon.json and constantly updates.

(Current API)
{"results":[{"id":3352,"name":"Grimer","coords":"35.6899071521,139.79440664","until":"2016-08-01T17:44:20.000Z","icon":"http://pokesnipers.com/assets/icons/88-5b29e3e1580edf62df57a0313e03c67abcb3dab742aab1bb8d7f6cdf2951f5bc.png"},{"id":3347,"name":"Haunter","coords":"40.7923407814,-73.9445697786","until":"2016-08-01T17:46:03.000Z","icon":"http://pokesnipers.com/assets/icons/93-c0139d3462432786eeb6bdd1687d8871995397e583f7b01a86b4f2c062f0b83d.png"},{"id":3351,"name":"Farfetch'd","coords":"35.6302674104,139.733149929","until":"2016-08-01T17:47:10.000Z","icon":"http://pokesnipers.com/assets/icons/83-cffc58369f4e82c5bf89f2edc199116eaa142c13ef7d0cef5cc34c3c4bd75ef4.png"},{"id":3350,"name":"Grimer","coords":"40.8169088389,-73.927577775","until":"2016-08-01T17:50:36.000Z","icon":"http://pokesnipers.com/assets/icons/88-5b29e3e1580edf62df57a0313e03c67abcb3dab742aab1bb8d7f6cdf2951f5bc.png"}]}

For example,

"UseAPIList" : true,
"UseAPIurl" : http://pokesnipers.com/api/v1/pokemon.json,

The guys pokesnipes only shows limited Pokemon, though its a fantastic feature, Adding this could open the door for API's for specific pokemon for farmers who only wanted, charmender, pikatu' etc.

So instead of sniping set locations, it will snipe new cords, searching for specific pokemon

**Comment by t-p-l-k** [comment]
You can use PogoLocationFeeder to get locations from pokesnipers and discord channels. Check this:
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by NecronomiconCoding** [comment]
Pokesnipers is too unstable to make this effort
