### ISSUE TITLE
Help with the GPX path

### ISSUE THREAD

**Issue by alfan85** [NECROBOTIO/NecroBot#1846]
i made my GPX file on[ http://www.geoplaner.com]( http://www.geoplaner.com) , then opened with notepad++ and deleted all the altitudes as shown in the necrobot [wiki http://i.imgur.com/Px6Ba22.png](wiki http://i.imgur.com/Px6Ba22.png) .
Then changed the config.json to true and added the GPX file name "x.gpx" .. then i moved the file on the same folder of the exe file, but it won't start, ill show you the next screens.. Can anyone help ?
![gpx file error](https://cloud.githubusercontent.com/assets/20748779/17304025/1a844dfe-57e9-11e6-86fd-92fad8e3a70b.jpg)
![Uploading GPX error.jpg…]()

**Comment by recon88** [comment]
Please join our Discord if you need help setting up the bot:
https://discord.gg/VXKxNFr
