### ISSUE TITLE
bot not working, but only for one account

### ISSUE THREAD

**Issue by XxMrSpacexX** [NECROBOTIO/NecroBot#1847]
i'm having this problem only with one account, i have other 4 accounts running and they're working really well..
here is the problem:
![necrobot error](https://cloud.githubusercontent.com/assets/5768372/17304116/430e5676-5824-11e6-8d72-955d90e135cf.png)
can anyone explain to me how to fix this?
thank you :)

**Comment by somani6** [comment]
prolly a formatting issue in the config/auth.

**Comment by XxMrSpacexX** [comment]
yeah, i just replaced auth.json and now it works fine
thank you

**Comment by HuKaers** [comment]
+wrong bot, log mentions another bot than NecroBot .........
