### ISSUE TITLE
[Suggestion] Discord Bot to filter coordinate chats

### ISSUE THREAD

**Issue by estrong1** [NECROBOTIO/NecroBot#1853]
The addition of the Coordinate chats on Discord are awesome, they make it really easy to snipe high IV pokemon, however users on the server are neglecting to read the rules of the channels and are clogging up the chat with non-coordinate posts.  This is putting alot of unnecessary stress on the moderators which could easily be relieved with a bot which would filter posts to only allow ones with numbers/coordinates in them.

**Comment by recon88** [comment]
This was suggested before. We are thinking about it.
