### ISSUE TITLE
Skiplagged API

### ISSUE THREAD

**Issue by SilasMueller** [NECROBOTIO/NecroBot#1854]
Hi,
i dont know the current implementation but it looks like skiplagged changed their api a bit.
i guess the old call would look something like this:
http://skiplagged.com/api/pokemon.php?bounds=38.907192,-77.036871

the new, working one looks like this:
http://skiplagged.com/api/pokemon.php?bounds=40.76356269219236,-73.98657795715332,40.7854671345488,-73.95812508392333

but as i said, im not sure which one is implemented atm in necrobot

**Comment by recon88** [comment]
Check the code ;) We are already using skiplagged but it doesn't seem to be reliable.
