### ISSUE TITLE
Problems with 0.5.0 Recycler:

### ISSUE THREAD

**Issue by DeityOfChaos** [NECROBOTIO/NecroBot#1855]
NecroBot 0.5.0 Recycler recycled all my max potions/max revives (while configured to keep them), I don't know how to stop it from killing all my max potions and good stuff.
It erased all of it in a 'quiet' or 'silent' recycle (appeared in the output).

Posting separately:
https://github.com/NECROBOTIO/NecroBot/issues/1623

**Comment by nfettinger** [comment]
These are the new configuration options:
  "TotalAmountOfPokebalsToKeep": 160,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,

**Comment by recon88** [comment]
It should be working fine with the settings above. If it's still not doing the job, visit our Discord and ask for help there: https://discord.gg/VXKxNFr

**Comment by DeityOfChaos** [comment]
What about the max revives etc?

Would it look like this?
"TotalAmountOfMaxRevivesToKeep": 60,
