### ISSUE TITLE
Enhance GPX pathing with LastPos.ini

### ISSUE THREAD

**Issue by nfettinger** [NECROBOTIO/NecroBot#1856]
Currently, any interruption to the server (whether it be a bot restart, a throttling hickup, etc), causes the GPX path to start over from the beginning. I suggest adding an index value to the LastPos.ini file that is read in and starts the path from where it left off. 

This could be ignored when UseGpxPathing is set to false.

**Comment by GediminasMasaitis** [comment]
An alternative is to make the GPX task start from the point that's closest to the `LastPos.ini` coordinate. This would make the bot _always_ start from the closest point, not only when it was interrupted there. It would also remove the need to store an extra index in the .ini file.

**Comment by Energex22** [comment]
Too bad i get this problem... and have this option turned off
