### ISSUE TITLE
Ultraball waste

### ISSUE THREAD

**Issue by DeityOfChaos** [NECROBOTIO/NecroBot#1858]
0.5.0 is using ultraballs as default ball (uses against everything, even bad pokemons). 
If there is a new config setting to prevent this then the new config parameters should be added to the automatically generated 'config.json' file. If there isn't a way to stop this then I assume it's a bug.

Posting separately:
https://github.com/NECROBOTIO/NecroBot/issues/1623

**Comment by t-p-l-k** [comment]
Check #1801

**Comment by dddbliss** [comment]
Duplicated issue with #1801, follow it there.

**Comment by RenjarP7** [comment]
Ultraballs are not used as default but are used for bad pokemons... 
In config I wrote:

> "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1200,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 95,
  "UseUltraBallAboveIv": 97,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.4,
  "UseMasterBallBelowCatchProbability": 0.05,


And the Bot still uses Greatballs for 
Pidgeotto Lvl: 4 WP: (123/128) IV: 82.00% | Chance: 39.11%

**Comment by Aneduna** [comment]
Chance: 39.11%
"UseUltraBallBelowCatchProbability": 0.4
