### ISSUE TITLE
Please add pofile info, stardust item n more

### ISSUE THREAD

**Issue by distan29** [NECROBOTIO/NecroBot#1863]

**Comment by recon88** [comment]
Could you please provide more information? What exactly do you want to be displayed?

**Comment by henriquemaciel** [comment]
I dont understand. The relevant information is at the top of the window, it would be something more than that?

**Comment by recon88** [comment]
Stardust is already being displayed in the window title. So we need exact information about what he wants to be implemented. What "Profile Info"? What does "item n more" mean?

**Comment by DrMirage** [comment]
for me is the count of total pokemons interesting

**Comment by NorwegianVikings** [comment]
I personally would like:
Pokemon you have / max pokemon you can have
Items you have / max items you can have

**Comment by distan29** [comment]
something like that, sir. :D.. stardust, total of pokemon etc.

**Comment by Oolaruu** [comment]
He is maybe talking about something like that

**[03:32:37] ----------------------------**
[03:32:37] Latitude: 52.379189
[03:32:37] Longitude: 4.899431
**[03:32:37] ----------------------------**
[03:32:37] Your Account:

[03:32:37] Name: 
[03:32:37] Team: 
[03:32:37] Level: 29 (LvLUp in ∞hours | 119455/350000 XP)
[03:32:37] Stardust: 203221
**[03:32:37] ----------------------------**
[03:32:37] ====== DisplayHighestsCP ======
[03:32:37] # CP 2470/2500 | (90.55% perfect)    | Lvl 25         NAME: 'Dragonite'
[03:32:37] ====== DisplayHighestsPerfect ======
[03:32:37] # CP 2045/2045 | (100.00% perfect)   | Lvl 23         NAME: 'Snorlax'

**Comment by distan29** [comment]
dont forget about total pokemon u have :D

**Comment by Oolaruu** [comment]
Well, provide more detailed infos, what would you like to have, why ? how ? where ?

**Comment by distan29** [comment]
i love necrobot very much, so i wont use other bot :D,
Stardust : Because it need for lvl up my favorite pokemon :D
