### ISSUE TITLE
(ERROR) System.FormatException

### ISSUE THREAD

**Issue by LeaklessGfy** [NECROBOTIO/NecroBot#1865]
Got this strange error on the 0.5.0 version:
![capture](https://cloud.githubusercontent.com/assets/16725289/17305056/feb16996-5828-11e6-80e8-f62b440ecd5d.JPG)

Thanks :)

**Comment by recon88** [comment]
Please visit our Discord and ask for help there: https://discord.gg/VXKxNFr 
Also we would need a translation as most of us can't spreak that language in your screenshot ;)
