### ISSUE TITLE
Delay between evolutions and CatchEscape-CatchSuccess interval not free from other actions

### ISSUE THREAD

**Issue by cbnolok** [NECROBOTIO/NecroBot#1866]
I'd suggest to put a timer between each pokemon evolution, since having 50 pokemons evolved in 5 seconds or so is very suspicious.
Also, if you set DelayBetweenPokemonCatch to a sufficiently high value (i got this "issue" at 4400), between a CatchEscape and a CatchSuccess 2+ attempt the bot will do other tasks (transferring pokemons in my case), which shouldn't be a legit action and therefore suspicious. Is it intended? Wouldn't be better to not do anything between these actions?

**Comment by recon88** [comment]
Yes it is intended. The bot doesn't have animations, that's why it's working that fast.
Don't worry about it.

**Comment by cbnolok** [comment]
Sure, i got why the bot is doing this fast but my fear is that this could became a reason to get softbans :D

**Comment by recon88** [comment]
You only get a sofban for jumping too far in a short time.
