### ISSUE TITLE
As showed, bot used UltraBalls to every pokemons. Now I have only PokeBalls.

### ISSUE THREAD

**Issue by JiMikl** [NECROBOTIO/NecroBot#1871]
(PKMN) (CatchSuccess) | (Normal) Abra Lvl: 19 CP: (297/325) IV: 70.00% | Chance: 34.35% | 64.96m dist | with a UltraBall (8 left). | Candies: 28

**Comment by baklaforever** [comment]
do this
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 2000,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.15,
  "UseUltraBallBelowCatchProbability": 0.08,
  "UseMasterBallBelowCatchProbability": 0.05,

**Comment by N0ct3** [comment]
This is probably the issue that happens while upgrading older settings to V0.5. See #1801 for explanations and a workaround

**Comment by JiMikl** [comment]
thanx for all
