### ISSUE TITLE
[Suggestion] Add Feature of throws

### ISSUE THREAD

**Issue by Fazy5** [NECROBOTIO/NecroBot#1872]
Add an option to enable or disable excellent+curve throws. So that max xp is gained ?

**Comment by henryzolo** [comment]
Dude this would be telling Niantic one is absolutely cheating XD

**Comment by henriquemaciel** [comment]
Perfect.

**Comment by MarkoHess** [comment]
I'm for the opposite of that. When i play the game on my phone, i sometimes miss the pokemon because it jumps or attacks me. So a random number of throws missed per pokemon would be nice.

**Comment by GediminasMasaitis** [comment]
I know I'd **love** fully customizable throw settings! For example:

    NiceThrowChance: 0.25,
    GreatThrowChance: 0.15,
    ExcellentThrowChance: 0.02,
    ForceGreatThrowAboveIV: 95.0,
    ForceExcellentThrowAboveIV: 99.9,
    ForceGreatThrowAboveCP: 2000.0,
    ForceExcellentThrowAboveIV: 2500.0,

Maybe even settings for individual Pokemon - although that may or may not be overkill.
