### ISSUE TITLE
can i power up using minimum IV AND minimum CP?

### ISSUE THREAD

**Issue by Mikey9191** [NECROBOTIO/NecroBot#1873]
I am just wondering whether i can power up my pokemon using both IV and CP, because so far it seems that i can only choose to power up based on iv or CP. let's say i want a criteria to power up pokemon that have at least 1000CP AND have at least 90% IV, how can i do that? 
because if i prioritize IV the bot would power up any weak pokemon and if i choose CP it would power up any pokemon regardless of IV.

**Comment by henriquemaciel** [comment]
I agree.

**Comment by li81** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/1862 Kinda the same issue
