### ISSUE TITLE
[Feature Request] Generate custom config file during setup

### ISSUE THREAD

**Issue by Unentertained** [NECROBOTIO/NecroBot#1876]
Okay, so I am currently working on how to do this but as of right now I don't have anything for a PR.

During the initial setup the CLI could ask the user questions about how they would like their configuration and then output the json file. I believe this would eliminate any confusion regarding the different terms and options, as well as making sure everything is correctly formatted.

**Comment by jaypeeb0917** [comment]
I completely agree with this or the devs can just attach recommended configs for each type that are commonly used. Like normal build, snipe build and mass build. That way the users will stop asking questions how to do this and that. Less problem for the support staff. Leave the tweaking of the config to the advanced users.

**Comment by theloser** [comment]
Delete any existing config.json, start the bot and you get a clean, 100% perfect working configuration. Adjust to your needs. Done.

**Comment by Andrerm124** [comment]
@jaypeeb0917 The issue with this is that by implementing many options, it's going to conflict with a ton of other things (Such as config merging etc). It'd take quite a bit of work (Such as an entire config overhaul)

**Comment by jaypeeb0917** [comment]
Excuse my ignorance but I don't get it. Here's a scenario.. user 8787 has been releasing different builds by tweaking the config. Everyone is waiting for his releases. So why cant devs do that? I am sure they know better and if they do that everyone is happy. Less questions from new users and not so advanced users about what to tweak. The default config we use is not helping. Take the startupdelay set to true. Why??? I am not sure why that is even there when we set it to false anyway.

**Comment by Andrerm124** [comment]
Well I've just implemented a feature (got committed about 20 minutes ago) that will correctly save all the options you've changed and just add new options with their default values when they're added. 

Do you mean you want the config to actually save what you've put in (Which is what the above is) or do you mean you want the bot to automatically create multiple configs for you to choose between. If it's the latter then you can just alter the original config and save it with a different name, swapping it out and restarted when needed. 

Sorry if I'm not getting your point, it's late and I'm quite tired hahah

**Comment by Andrerm124** [comment]
Actually I can think of a way to potentially allow you to choose a specific config on startup (Like having 3 config files that you can pick between) however it'll be about 12 hours before I get to take a look

**Comment by jaypeeb0917** [comment]
Haha no prob. What I meant is simplier. Just configs that are already set according to their desired effect like sniping, farming or human like botting. Sticky it somewhere since we dont have a forum site.. maybe paste bin or google drive? That way people will stop asking in the help channel about configs esp the noobs and new user. Maybe in the announcement section of discord??
