### ISSUE TITLE
back to home

### ISSUE THREAD

**Issue by kusan-thana** [NECROBOTIO/NecroBot#1878]
An option allowing user to go back to default location would be great I think (after a time or a key stroke). This would avoid to have a teleportation when we exit the application and start playing on phone.

**Comment by kennybon** [comment]
This is a good idea.

**Comment by actislav** [comment]
this logic is already exists FarmPokestopsTask, but does not work because of last coordinate, which saves to lastcoord.ini not applied on start of bot, just warn you
