### ISSUE TITLE
[Feature Request] Keep both best IV and best CP

### ISSUE THREAD

**Issue by Algent** [NECROBOTIO/NecroBot#1880]
Add an option to exclude from transfer for each Pokemon both the highest IV and the highest CP, regardless of iv/cp values and other settings. 

Something like "KeepMinBestBothIvAndCp: true". Maybe allow it to be set globally and in a PokemonsTransferFilter.

**Comment by GediminasMasaitis** [comment]
This would be great. I wonder how would it interact with `KeepMinDuplicatePokemon`? Override it and keep at least 2 regardless? Or would the `KeepMinBestBothIvAndCp` be active only when `KeepMinDuplicatePokemon > 2'?

**Comment by recon88** [comment]
See #1862
