### ISSUE TITLE
Can't log in useing google

### ISSUE THREAD

**Issue by undyingUmbrage** [NECROBOTIO/NecroBot#1881]
The bot sasys to put app password into config file. But have 2-steps auth disabled and my google account doesn't even get this function. I can still authentificate on my phone with same google login/password. It started just about 5 minutes ago on all my accounts.

**Comment by recon88** [comment]
Please check the Wiki: https://github.com/NECROBOTIO/NecroBot/wiki 
Or visit us on the Discord server for further help: https://discord.gg/VXKxNFr
