### ISSUE TITLE
[fix] Hardcoded console size breaks the build.

### ISSUE THREAD

**Issue by Cyberek** [NECROBOTIO/NecroBot#1884]
https://github.com/NECROBOTIO/NecroBot/commit/98f33df
```
Console.SetWindowSize(165, 30);
```
It sets console width to 165 while on my screen maximum possible width is 117. It is better to have default console width and height settings set in windows then hardcoding it into the code itself.

I can prepare a PR which will remove this hardcode. Just let me know.

**Comment by recon88** [comment]
Sure go ahead.

**Comment by Cyberek** [comment]
Ok
