### ISSUE TITLE
PTC servers are probably down or your credentials are wrong. Try google .  HELP

### ISSUE THREAD

**Issue by donib69** [NECROBOTIO/NecroBot#1885]
PTC servers are probably down or your credentials are wrong. Try google . 
ok , ptc servers are not down ffor sure , cus i can login from browser or from phone in my account not using google , and my credentials are not wrong cus they worked before , 
helo me

**Comment by ifbatmanwasreal** [comment]
Discord for help

**Comment by donib69** [comment]
@ifbatmanwasreal who should i contact ?

**Comment by ifbatmanwasreal** [comment]
There's a #helpme channel

https://discord.gg/VXKxNFr

**Comment by jawad90** [comment]
servers are down thats why

**Comment by Wcidd** [comment]
Servers are having connection problems, please be patient
