### ISSUE TITLE
sniper not working

### ISSUE THREAD

**Issue by jonsnowwatch** [NECROBOTIO/NecroBot#1888]
Hi guys, ever since 4.0 my sniper has stopped working. Updated to 5.0 today still no luck. (using online server and/or cords)
here's my setting 

  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 200,
  "MinPokeballsWhileSnipe": 100,
  "MinDelayBetweenSnipes": 100,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,

I always have enough balls to snipe. But I dont see any message that shows im sniping. 

Please help and thanks for your time!

**Comment by Linewalker** [comment]
Servers down.

**Comment by DeityOfChaos** [comment]
NecroBot is currently using an external API from SkipLagged/Pokemon to detect which pokemons are out there to be sniped.
SkipLagged is down for maintenance right now, so the sniper won't work.

**Comment by Cuuup** [comment]
If you want it to be working again and use the API from pokesnipers.com, just revert back to 4.0 and download Tsukis Necrobot

**Comment by Linewalker** [comment]
I've my own sniper code for this case working with 0.5.0, no use of using another bot.
