### ISSUE TITLE
PTC servers are probably down or your credentials are wrong. Try google . 

### ISSUE THREAD

**Issue by donib69** [NECROBOTIO/NecroBot#1889]
PTC servers are probably down or your credentials are wrong. Try google . 
they are not really down ant my credentials are right

Helo me 
or contact me on discord

**Comment by jakerxiii** [comment]
Poodlecorp hit Niantic servers offline.

**Comment by blopez0909** [comment]
go to discord for help. https://discord.gg/VXKxNFr

**Comment by donib69** [comment]
@jakerxiii a can login from browser
