### ISSUE TITLE
Bot crashing after some time using PTC

### ISSUE THREAD

**Issue by MyUncleSam** [NECROBOTIO/NecroBot#1891]
I have two bots, one using PTC and one using Google. The bot using Google is running and not crashing. The one with PTC is crashing after some hours.

One message e.g.:
![image](https://cloud.githubusercontent.com/assets/12820919/17307361/ff629ab6-5834-11e6-8ae9-f39f89c9c437.png)

Is there a fix or anything I could do?

**Comment by recon88** [comment]
Please visit our Discord and try to resolve that issue with one of the helpers there: https://discord.gg/VXKxNFr
