### ISSUE TITLE
Is the discord server down?

### ISSUE THREAD

**Issue by ifbatmanwasreal** [NECROBOTIO/NecroBot#1897]
I can't use the Discord sniping. I also can't join the channel. Are these two things related? I'd ask for help in Discord, but I'm not able to access the server at the moment. Also, skiplagged seems to be down as well.

**Comment by recon88** [comment]
If you are not able to access this Discord it means the Discord User Limit has been reachted. I am sorry for the inconvienience. Discord told us everything should be fixed in max 6 Hours
