### ISSUE TITLE
PTC Login issue

### ISSUE THREAD

**Issue by Goon2k4** [NECROBOTIO/NecroBot#1898]
When i use my ptc login is returns a red command line stating
Account not verified! Exiting....
I can login through the pokemon go app without issue.

Anyone else have this issue?

**Comment by blopez0909** [comment]
did you actually read the auth file? it's password first then user. anyways if you need more help go to the discord server. https://discord.gg/VXKxNFr

**Comment by undyingUmbrage** [comment]
have something like this useing google account. The bot sasys to put app password into config file. Can't even join discord channel for help :(
