### ISSUE TITLE
[SUGGESTION] Make the bot faster

### ISSUE THREAD

**Issue by sammuelsgs** [NECROBOTIO/NecroBot#1899]
add a way to make it faster or not.... im only getting 75kEXP/H

**Comment by blopez0909** [comment]
the api only allows you to do a task so fast, also doing it faster would just get you banned faster.

**Comment by Sylencer90** [comment]
only 75k exp.... im getting around 30k and im happy with.

**Comment by sawirth** [comment]
buy some lucky eggs to get more XP ;)

**Comment by DeniMM** [comment]
there are configs , which can make the bot faster. please use discord for this.
