### ISSUE TITLE
Issue with Google Auth [BUG]

### ISSUE THREAD

**Issue by boosie212** [NECROBOTIO/NecroBot#1900]
I tried using the Necrobot on a new computer.  The old computer I use it on works perfectly fine.  I am logged into my google account on my default browser.  I have the newest version (0.5.0) of Necrobot.  The auth file is definitely entered correctly.  I have tried switching the fields for username and password as well as eliminating the line for GoogleRefreshToken.  I have also tried logging into a different username.  I know for sure this is not an issue with my username nor is it an issue with the servers as they have been running all day and I have had no issues logging into the app on my phone.  I have tried troubleshooting this for hours and have used countless resources on Discord to no avail.  The only thing I can think of is that the .exe cannot communicate with the APIs and therefore cannot connect to the pokemon servers.  I was told that I would need to speak with someone who is familiar with how the APIs work.

I also get the following response from the following URL
URL: https://pgorelease.nianticlabs.com/plfe/
Response: Dude, this is the Player Frontend.

Please see image showing that the .exe is repeatedly showing "Logging in using Google", but does not seem to connect.
![capture](https://cloud.githubusercontent.com/assets/20780793/17308246/0567732e-5807-11e6-9e88-f68c4b01397f.JPG)

**Comment by recon88** [comment]
Could you please post your auth file with censored mail and password?

**Comment by orakles** [comment]
Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.GUI.MainForm.DisplayPositionSelector()
Using google as login; this problem only happens with google; ptc works just fine for me o,O

**Comment by boosie212** [comment]
{
  "AuthType": "google",
  "GoogleUsername": "xxx@gmail.com",
  "GooglePassword": "xxx",
  "PtcPassword": null,
  "PtcUsername": null
}

**Comment by recon88** [comment]
Weird, could you try downloading a fresh copy of the bot and just change the auth file?
Also try without "@gmail.com" at the end.

**Comment by boosie212** [comment]
@recon88 I just tried the fresh install from the Release.zip file for .0.5.0.  I tried the username with and without @gmail and both didn't work.

**Comment by boosie212** [comment]
Am I missing files in the main folder when the .exe is first setup?
![capture](https://cloud.githubusercontent.com/assets/20780793/17333705/5fcdd2c8-58a1-11e6-8e5f-b7d1cc29211e.JPG)

**Comment by boosie212** [comment]
![capture](https://cloud.githubusercontent.com/assets/20780793/17334038/c2fb1576-58a2-11e6-8d6c-4744e3231fca.JPG)

This should provide a lot more information.  I tried installing 0.4.0 and turning off autoupdate.  When I run the .exe in version 0.4.0, this is the error I receive.  Does this help?

**Comment by boosie212** [comment]
I now know the issue.  I was only able to visit https://pgorelease.nianticlabs.com/plfe/ when using FoxyProxy, but cannot access it when I turn FoxyProxy off.  Is there anything I can change in the settings/config/auth files to allow me to run the bot with FoxyProxy turned on as this is the only when I can communicate with the servers.

**Comment by recon88** [comment]
Might be possible that your IP got banned. Try getting a new one.

**Comment by boosie212** [comment]
@recon88 I always have FoxyProxy turned on.  I can only access https://pgorelease.nianticlabs.com/plfe/ with it turned on.  I can still access it right now so my IP is not banned.  I've never been able to access https://pgorelease.nianticlabs.com/plfe/ without FoxyProxy turned on.  When FoxyProxy is turned off the error reads:

This site can’t be reached

The webpage at https://pgorelease.nianticlabs.com/plfe/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

When I choose Details for more information, I get the message

Problem found
Windows received an HTTP error message: 403 (Forbidden) from Detected "pgorelease.nainticlabs.com"

**Comment by recon88** [comment]
Again, try resetting your Router if you didn't do that already. I doubt it's an issue with the bot.

**Comment by boosie212** [comment]
@recon88 I agree with you, it's not an issue with the bot at all.  I am blocked from that website by a proxy on this computer.  I cannot turn off the proxy.  I do not have access to a router.  The only way for me to access the website is by using the Google Chrome extension called FoxyProxy.  I am wondering if i can pass the connection through the FoxyProxy in order to get the Bot to work.  I don't think I am doing a good job explaining the issue.

**Comment by boosie212** [comment]
![capture](https://cloud.githubusercontent.com/assets/20780793/17336348/d00ca730-58ab-11e6-9c05-185abc566a88.JPG)

**Comment by boosie212** [comment]
![capture1](https://cloud.githubusercontent.com/assets/20780793/17336350/d66ebfd2-58ab-11e6-86fc-46c4e1e2a6ef.JPG)

**Comment by recon88** [comment]
No you can't but you could try a free VPN for that. 
A proxy feature for the bot itself was already requested: #1945

**Comment by gingerpumpa** [comment]
This is very alike my problem, but i don't need vpn or anything to go pgorelease site. But I don't have @gmail.com I have @mydomain.no
