### ISSUE TITLE
Question: Evolve only commons

### ISSUE THREAD

**Issue by Phoenix10King** [NECROBOTIO/NecroBot#1901]
in my account now i have a ton from kabutobs, pigeys, and hell common pokemons and i want to evolve them all through lucky egg .. but i dont want the bot to bother my dratinis, magikarps, eevees and my rare pokemons as i reach lvl 30 and am looking forward for stronger to evolve ... how can i set this to the bot ??? to evolve all the commons but dont touch my rares or that who gonna give me strong pokemons

the settings i get from confing.json of the bot are
EvolveAllPokemonAboveIv
EvolveAllPokemonWithEnoughCandy
KeepPokemonsThatCanEvolve
PokemonsToEvolve [4]
UpgradePokemonCpMinimum 1000
UpgradePokemonIvMinimum 95
UseLuckyEggsMinPokemonAmount 30
UseLuckyEggsWhileEvolving

so which of the above has to be enable (True and in which value) in order to evolve all commons with lucky egg and leave for me my rares (because i didnt found any option like pokemons to dont evolve)

**Comment by DeniMM** [comment]
Go to config, put all pokemons you want to evolve in this list:

  "PokemonsToEvolve": [
    "caterpie",

and make UseLuckyEggsWhileEvolving to true.

also use discord next time, if you don't have a dev problem.

**Comment by Phoenix10King** [comment]
really sorry!
can i have the link for Discord please??

**Comment by NecronomiconCoding** [comment]
read the readme :happy:
