### ISSUE TITLE
Ignoring pokemon not working

### ISSUE THREAD

**Issue by W1-PopelierE** [NECROBOTIO/NecroBot#1903]
I put some on the ignore list with:
  "PokemonsToIgnore": [
    "Pidgey",
    "Rattata",
    "Caterpie",
    "Weedle",
    "Spearow",
    "Goldeen"
  ],
But it doesn't work. Any ideas?
I also did it without a Capital letter

**Comment by Wcidd** [comment]
Have you set "UsePokemonToNotCatchFilter": to true?

**Comment by recon88** [comment]
Seems to be working fine for me. Would you please visit our Discord server and show someone your full config file? https://discord.gg/VXKxNFr

**Comment by W1-PopelierE** [comment]
I apperently just cant read. 
Have you set "UsePokemonToNotCatchFilter": to true?
i didnt xD
