### ISSUE TITLE
SnipingScanOffset?

### ISSUE THREAD

**Issue by W1-PopelierE** [NECROBOTIO/NecroBot#1904]
what does:
  "SnipingScanOffset": 0.002,
do?
Sorry for the question here. I tried discord but the server is down

**Comment by RivalzZz88** [comment]
jea, is sniping already running? i think the server are down, isn't it ?

**Comment by W1-PopelierE** [comment]
Sniping is running for me.
but what does the offset do?

**Comment by RivalzZz88** [comment]
how do you running the sniper at the moment ? i didnt changed anything on my config but there will coming no messages about sniping anymore at the time

**Comment by W1-PopelierE** [comment]
Well i am using a feeder.

**Comment by Mikey9191** [comment]
Sniping is not working for me either, i am using pogo feeder as well, did you change the configs to make it work? it says connected but nothing happens

**Comment by W1-PopelierE** [comment]
I have just followed the tutorial from necrobot
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by W1-PopelierE** [comment]
still no answer:
what does:
"SnipingScanOffset": 0.002,
do?

**Comment by recon88** [comment]
It's used to calculate the borders of the scanned region. Don't set it too high ;)

**Comment by W1-PopelierE** [comment]
but define high

**Comment by RivalzZz88** [comment]
So W1 u are using Discord for finding Snipes ? i got an account but i can't login there to activate it ( rooms etc. ) so down ?

**Comment by RivalzZz88** [comment]
whats about the Pokersniper.com site from yesterday ?

**Comment by W1-PopelierE** [comment]
i havent even checked any discord rooms i just let my feeder do the work. I did not check if they were online
use the room: "sniping" that one is doing all the work atm

**Comment by Mikey9191** [comment]
I have used the tutorial but it only says new connection then nothing happens. anyone else with the same problem?

**Comment by W1-PopelierE** [comment]
Create a new issue for this.

**Comment by Mikey9191** [comment]
i guess i will

**Comment by recon88** [comment]
@Mikey9191 
Visit our Discord for configuration issues: https://discord.gg/VXKxNFr

**Comment by Mikey9191** [comment]
well the discord channel isn't working right now

**Comment by recon88** [comment]
Then wait for it being back. Discord is working on the issue.

**Comment by Mikey9191** [comment]
ok thanks
