### ISSUE TITLE
Automatically Level Up Pokemon

### ISSUE THREAD

**Issue by PokemonRS** [NECROBOTIO/NecroBot#1905]
Is it possible to make additional settings for the Level Up Pokemon?
To so specify what Pokemon have to Level Up.
Or make to Level Up came only to Favorite Pokemon.

**Comment by tw88** [comment]
yes please, it makes no sense upgrading a ( /every ) 700cp dratini just bc its 100%IV

**Comment by Whosdaman** [comment]
What if the all evolve logic was IV and CP instead of being forced to select one or the other?
