### ISSUE TITLE
[Question] PokemonsTransferFilter

### ISSUE THREAD

**Issue by wele** [NECROBOTIO/NecroBot#1907]
looking through the wiki and reading up on it i created this:
"PokemonsTransferFilter": {
    "Arcanine": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 5
    }
}

Question: Is the logic AND or OR ? shouldn't these 2 have been transferred since it did not meet both criteria of 1800 AND 80%? example:
![image](https://cloud.githubusercontent.com/assets/2280652/17309355/577e993a-57f3-11e6-8c8d-ffaeee0f9b6a.png)
![image](https://cloud.githubusercontent.com/assets/2280652/17309383/715b9a24-57f3-11e6-9bed-ab72e01718db.png)

Thanks

EDIT:
1 thing to note is that i do only have 4 Arcanine's, 2 meet both criteria while 2 do not.

**Comment by W1-PopelierE** [comment]
"KeepMinDuplicatePokemon": 5
so if you have 4 it needs 1 more then it will transfer the lowest if he catches one more.

**Comment by recon88** [comment]
If you need more help, visit our Discord: https://discord.gg/VXKxNFr
