### ISSUE TITLE
History of pokestops

### ISSUE THREAD

**Issue by kusan-thana** [NECROBOTIO/NecroBot#1910]
My configuration make the bot turn in a circle or something, always revisiting previous pokéstops.
Would it be possible to add a feature so the bot wouldn't go to a previous pokestop?

And since it's always the same paths, there is a point where I don't find any pokemons anymore...

**Comment by mush35** [comment]
i think there was a pokestop delay in the previous versions. now cant find it.

**Comment by recon88** [comment]
So you are using GPX pathing? If not, just higher the max distance.
