### ISSUE TITLE
Sniper issue, not using all the feeder locations.

### ISSUE THREAD

**Issue by OverCraftX** [NECROBOTIO/NecroBot#1911]
When the bot listen the sniper location feeder, if it plot 20 new locations from the last time it launched the sniper round, the bot only try to find 2-3-4 locations but never the 20 new ones.

I have always more than 100 pokeballs, thats not the problem, nor the exceed time (most of the entrys dont have even exceed time). It just only check a few of the last ones, never everything as it should.

**Comment by GediminasMasaitis** [comment]
I have noticed this too, although I figured it was just my configuration issue which I didn't bother to fix. But maybe it is a bug - would be nice to hear from some more people.

I'm using NecroBot v0.5 and PogoLocationFeeder v.0.0.2.1, if it matters.

**Comment by Linewalker** [comment]
Again, no bug, the external server for the pokemon check is down.

**Comment by xSilentxReaperx** [comment]
I am running 0.4.0 so I can continue using sniping. It wasn't working for me on 0.5, so I went back down to 0.4 and disabled automatic updates.

**Comment by skupfer** [comment]
Working fine here, lower the sniperdelay

**Comment by Linewalker** [comment]
I just set up my own Live Map server on ubuntu online and changed url in sniping task. working fine and easy fix :-)

**Comment by OverCraftX** [comment]
some pictures:

![feeder2](https://cloud.githubusercontent.com/assets/20661590/17313069/e2a58572-5858-11e6-867f-18de846f0cf4.jpg)

![feeder1](https://cloud.githubusercontent.com/assets/20661590/17313072/e6d6000e-5858-11e6-8eb7-4e3c5cb41685.jpg)
