### ISSUE TITLE
Ultraball and Greatball wasting

### ISSUE THREAD

**Issue by techrayftw** [NECROBOTIO/NecroBot#1918]
Hey, I don't know why, but since the last update, the bot keeps using Ultraballs for every pokemon till there is no ball left. It's annoying, because those pokemon could have been caught with an normal pokeball easily. 

Hope you guys understand what i meant ^^

I think there is a new setting in the config, which i didn't set up correctly... but i couldn't find a way to fix it.

Added my actual config file... And yes, i changed it to txt so that it was accepted by github.

[config.txt](https://github.com/NECROBOTIO/NecroBot/files/394884/config.txt)

**Comment by theloser** [comment]
Check your config, it is wrong.

**Comment by techrayftw** [comment]
@theloser : would be nice if you could check what i did wrong then...

**Comment by evansims** [comment]
You might give [this configuration a try.](https://github.com/NECROBOTIO/NecroBot/issues/1746#issuecomment-236575074) It solved the issue for me.

**Comment by proesd** [comment]
see #1746

**Comment by theloser** [comment]
> "UseGreatBallBelowCatchProbability": 20.0

That instructs the bot to use GreatBalls whenever chance to catch is less then 2000% (which always is true!). Change it to:

>  "UseGreatBallBelowCatchProbability": 0.2,
>  "UseUltraBallBelowCatchProbability": 0.03,
>  "UseMasterBallBelowCatchProbability": 0.0,

**Comment by techrayftw** [comment]
Alright, just saw it on the other issues :) Thank you so much, it works right now pretty good :) Keep up the great work
