### ISSUE TITLE
v.0.5.0  Wrong pokeballs being used/ pokemon not evolving automatically. 

### ISSUE THREAD

**Issue by bluefire501** [NECROBOTIO/NecroBot#1919]
Since the update the bot has only been using ultra balls and it does no evolve Pokemon anymore.
Also it does not prioritize ultra balls over poke balls anymore.
[17:24:55] (UPDATE) [Evolves] Potential Evolves: 139 | 30 required for mass evolving
[17:23:04] (PKMN) (CatchSuccess) | (Normal) NidoranMale Lvl: 1 CP: (10/11) IV: 35.00% | Chance: 100% | 64.80m dist | with a UltraBall (1 left). | Candies: 53

**Comment by actislav** [comment]
evolve will happen when your storage will be full at EvolveKeptPokemonsAtStorageUsagePercentage (if you set KeepPokemonsThatCanEvolve to true), in new version there will be correct message about it, for now you can change EvolveKeptPokemonsAtStorageUsagePercentage to 0.0, and all will be ok

**Comment by actislav** [comment]
UltraBall used if you do not have any other, or just your settings incorrect like UseGreatBallAboveCp > 10000 and UseUltraBallAboveCp > 10

**Comment by proesd** [comment]
for setting ultra ball reference this #1746

**Comment by bluefire501** [comment]
"UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
