### ISSUE TITLE
Account not verified?

### ISSUE THREAD

**Issue by MatthewSH** [NECROBOTIO/NecroBot#1921]
NecroBot continues to say my PTC account isn't verified, but it is. I verified it when I created the account. 

Any thoughts?

**Comment by theloser** [comment]
Change username and password (don't know why, but it works):

  "PtcUsername": "your ptc password",
  "PtcPassword": "your ptc username"

**Comment by MatthewSH** [comment]
Hm. That's weird. It's working now. Thanks. :)
