### ISSUE TITLE
Transfer...

### ISSUE THREAD

**Issue by distan29** [NECROBOTIO/NecroBot#1928]
![untitled](https://cloud.githubusercontent.com/assets/20714659/17311514/1ee892e6-5876-11e6-8f75-031db56cdc89.png)

**Comment by hilycker** [comment]
Explain what's the problem at least, considering language isn't even english

**Comment by proesd** [comment]
what happened with the transfer ? have you set your config correctly ?

**Comment by DeniMM** [comment]
i don't see an issue.

**Comment by NorwegianVikings** [comment]
I think he means why his 342CP goldeen got transfered when "best" is 39CP, but this is because "PrioritizeIvOverCp": true,

Change to false if you want highest CP to be kept, instead of highest IV
