### ISSUE TITLE
PTC Servers are probably down OR your credentials are wrong. Try google

### ISSUE THREAD

**Issue by ArcanumSK** [NECROBOTIO/NecroBot#1929]
Looks like ban per IP from login servers, I swiched my dyn. IP and it just logged in. Maybe try to implement proxy.

**Comment by adipiatek** [comment]
I am playing on PTC, teleporting a lot really a lot and works fine.

**Comment by proesd** [comment]
confirmed, me too, login using PTC get the same message. another 5 using google is fine

**Comment by ArcanumSK** [comment]
Well I am running 2 bots for a friend... maybe its accounts per ip thing or something. As I said I just changed my ip and they both logged in so...

**Comment by Ricktza** [comment]
Ip bans confirmed. Can't login via my home connection, but I can over mobile. 
I had two bots running part of the day.

**Comment by TuxySquidGuy** [comment]
Confirming IP ban on PTC.
Cant log in via computer, can not log in on wifi from phone, can log in on data from phone.

**Comment by Ricktza** [comment]
Seems Google is unaffected. Google accounts of mine work on both home and mobile.

**Comment by SlinkyDinky** [comment]
I had the same issue. Seems to be working now. Weird. O_O

**Comment by recon88** [comment]
PTC seems to be broken every now and then. Also yes, IP bans are possible.

**Comment by ArcanumSK** [comment]
So no support for using proxy or proxies in scope ?

**Comment by recon88** [comment]
Open another ticket requesting that feature ;)

**Comment by ArcanumSK** [comment]
Oh ok.

**Comment by Ricktza** [comment]
I can now login again. Very strange.

**Comment by iamthasasquatch** [comment]
Sorry I have been at work but to add, yes I could login with google on necrobot while i couldnt on ptc. At the same time the same PTC account could login using tomthebotter and another POGOBot that was written in python. I could login to my phone on the same account as well.
