### ISSUE TITLE
Snipe Rare Pokemon

### ISSUE THREAD

**Issue by actisys** [NECROBOTIO/NecroBot#1932]
I have pulled the latest commit but i dont see the snipe rare pokemon via pokesnipe is working? can anyone advise me on this? 

As my setting:-
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,

**Comment by NorwegianVikings** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by DeniMM** [comment]
Please use discord for questions like this.
