### ISSUE TITLE
(INFO) Logging in using Google

### ISSUE THREAD

**Issue by CarvenSi** [NECROBOTIO/NecroBot#1933]
Help! Infinite Logginging !
---------------------------------
[02:22:18] (UPDATE) Perfect! You already have the newest Version 0.5.0
[02:22:18] (INFO) Logging in using Google
[02:24:20] (INFO) Logging in using Google
[02:26:21] (INFO) Logging in using Google
---------------------------------
My "AUTH" file 
{
  "AuthType": "google",
  "GoogleUsername": "**********@gmail.com",
  "GooglePassword": "************",
  "PtcPassword": null,
  "PtcUsername": null
}

**Comment by NorwegianVikings** [comment]
{
  "AuthType": "google",
  "GooglePassword": "xxxxxxxxxxxxxx",
  "GoogleRefreshToken": null,
  "GoogleUsername": "xxxxxxxxxxxxxxx@gmail.com",
  "PtcPassword": null,
  "PtcUsername": null
}

**Comment by CarvenSi** [comment]
It's doesn't work!

**Comment by NorwegianVikings** [comment]
Okey, but seems like they fixed it? Duplicate issue #1900

**Comment by CarvenSi** [comment]
This link is doesn't work! I can't conect to it! https://pgorelease.nianticlabs.com/plfe/

**Comment by CarvenSi** [comment]
Man! This is what I got :
Dude, this is the Player Frontend. 
 And what?

**Comment by CarvenSi** [comment]
Man! This is what I got :
Dude, this is the Player Frontend. 
 And what?

**Comment by proesd** [comment]
{
  "AuthType": "google",
  "GoogleUsername": "*****st@gmail.com",
  "GooglePassword": "***23",
  "PtcPassword": null,
  "PtcUsername": null
}

my auth.json, work with fresh install ..  strange :/

**Comment by NorwegianVikings** [comment]
Try a fresh install or just wait until the devs release a fix or the next compiled release.

**Comment by CarvenSi** [comment]
I don't know but it's work! I don't know how!
