### ISSUE TITLE
No Pokemon found to snipe

### ISSUE THREAD

**Issue by Jleonel** [NECROBOTIO/NecroBot#1934]
Hello there,
   I am a new user to the bot, so this is probably a stupid question, but whenever I set up to try to use the sniping option I always run into No Pokemon found to snipe! message, any ideas?

**Comment by Marsinator** [comment]
please follow https://github.com/NecronomiconCoding/NecroBot/wiki/Sniping-Setup

and use automatic-sniping

**Comment by Jleonel** [comment]
But when I use the auto sniping set up nothing ever pops up, I know it's my discord account that's causing the problem, I just can't get it to work, can you talk me through?
