### ISSUE TITLE
Level reward not being collected

### ISSUE THREAD

**Issue by WatIsGithub** [NECROBOTIO/NecroBot#1936]
Hello, i was just wondering if the bot is counting with level rewards or if it is possible. Logged on the account with Nox nearby last position of the bot 30 minutes after shutting it down to avoid softban and after having to choose gender+look i got rewards for all the levels up to actual 28 (about 1100 items). So i started to wonder if it wasn´t picked up for a reason(my stupidity/not possible to emulate?). Can you explain to me this behaviour? Or was it just because i didn´t login to the account after creating and started to bot straight away? Maybe add this information about logging in first into info to let people know before you turn on the bot. Thanks for patience with newbie

**Comment by NorwegianVikings** [comment]
It never collects level up rewards after my experience, might be possible to integrate

**Comment by WatIsGithub** [comment]
I think that would definately speed up the leveling :)
