### ISSUE TITLE
Pokeballs being recycled

### ISSUE THREAD

**Issue by manoelbgn** [NECROBOTIO/NecroBot#1938]
I've set the "TotalAmountOfPokebalsToKeep" to 350, in theory, the bot should keep the greatballs and ultraballs and throw away the common ones, but instead of it, now I have 349 pokeballs, 1 ultraball and 0 gratballs. In my case, the bot is throwing away ultraballs and greatballs, and giving priority to pokeballs.

**Comment by Marsinator** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Config#catching

**Comment by NorwegianVikings** [comment]
You sure it does not use the great/ultraballs to capture pokemon?

**Comment by Marsinator** [comment]
#1746 potentially

**Comment by Chaos2522** [comment]
Mine works fine, got 450 Hyperballs - 100 greatballs 100 pokeballs if set to 650.
It allways recycles pokeballs first.
