### ISSUE TITLE
Random incremental WalkingSpeed changes

### ISSUE THREAD

**Issue by DoubleDrop9000** [NECROBOTIO/NecroBot#1941]
Re: config.json "WalkingSpeedInKilometerPerHour"

Would be great if this could be set at a randomly sliding value between 2 defined values.
**For example: Setting walk speed to between "0" and "9" could result in an output of "4.5" that gradually increases or decreases at set increments (say 0.1) over time.**

This would be a great way to appear 'human' and reduce soft-bans.

**Comment by RoseFlunder** [comment]
Duplicate of [https://github.com/NECROBOTIO/NecroBot/issues/2140](https://github.com/NECROBOTIO/NecroBot/issues/2140)
