### ISSUE TITLE
Encounter Problem: EncounterNotFound" 

### ISSUE THREAD

**Issue by viiet** [NECROBOTIO/NecroBot#1942]
Encounter Problem: EncounterNotFound" 
any idea what would cause this.

**Comment by NorwegianVikings** [comment]
Need log of the event

**Comment by viiet** [comment]
[NecroBot-2016-08-01-19.txt](https://github.com/NECROBOTIO/NecroBot/files/394993/NecroBot-2016-08-01-19.txt)
@NorwegianVikings

**Comment by zeeeez** [comment]
[NecroBot-2016-08-01-20.txt](https://github.com/NECROBOTIO/NecroBot/files/394997/NecroBot-2016-08-01-20.txt)

**Comment by NorwegianVikings** [comment]
Not much to go on based on the error message, not sure. But could be related to Niantic changing their API and throttling down search requests from one every second to one every 5 seconds. As I said, not sure #1780

**Comment by viiet** [comment]
@NorwegianVikings do u know which settings exactly? im looking through trying to figure out which settings i need to bump up to 5 secs

**Comment by zeeeez** [comment]
Changed all delays to 5000ms (5 seconds). Still get the error.

**Comment by SwoleSnorlax** [comment]
Getting exact same issue

**Comment by dalthran** [comment]
Same problem aswell

**Comment by LiqwdE** [comment]
I'm running 4 bots. 1 in cali, 2 in alabam, and 1 in japan. Tokyo bot throwing this error, but all configs the same. Translation error of some kind?

**Comment by phingorani** [comment]
It's strange that I keep getting (ATTENTION) Encounter problem: EncounterNotFound but in randomly will actually catch a pokemon in the midst.

**Comment by Ninjistix** [comment]
i'm having this same problem right now, recently started

**Comment by Oolaruu** [comment]
Duplicate Issues:
#1960 
#1952 
#1977 
#1972
