### ISSUE TITLE
Config doesn't work! 

### ISSUE THREAD

**Issue by CarvenSi** [NECROBOTIO/NecroBot#1943]
I have this in Config 
-----------
],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
------------
But Bot catch pidgey and other!

**Comment by Doedelpumpe** [comment]
You have set the filter to "True" in the config file? 

"UsePokemonToNotCatchFilter":

**Comment by NorwegianVikings** [comment]
You have? "UsePokemonToNotCatchFilter": true,

**Comment by Marsinator** [comment]
UsePokemonToNotCatchFilter (Value)

When UsePokemonToNotCatchFilter is set to true, any Pokemon listed in the PokemonsToIgnore list will be skipped when determining what Pokemon to catch.
