### ISSUE TITLE
Recycling/Transfering work ocassionaly

### ISSUE THREAD

**Issue by panoszik** [NECROBOTIO/NecroBot#1949]
Even i have set up correctly the config recycling occurs only at the start of the session and Transfering works for some pokemon..For example i set up max voltorbs number to 2 with min cp 450 and i have voltorbs with lower than that catching my space..this happens with most pokemon..any help?thanks

**Comment by blopez0909** [comment]
do you have prioritizeivovercp set to true? those voltorbs could be at the iv threshold.

**Comment by panoszik** [comment]
it is set to false

**Comment by panoszik** [comment]
[config.zip](https://github.com/NECROBOTIO/NecroBot/files/395051/config.zip)
here is the config file take a look if y have time

**Comment by recon88** [comment]
Please come to our Discord for configuration help: https://discord.gg/VXKxNFr
