### ISSUE TITLE
[BUG] Move1 and Move2 Not translated in Console even if lang files ok

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#1953]
Hi.

I noticed that, keys :
displayHighestMove1Header
displayHighestMove2Header

are not translated in console, even if all languages have already translated those 2 words.

Thanks.

**Comment by fr3k4life** [comment]
Same here for collected items

**Comment by recon88** [comment]
If this is still an issue on 0.6.2, open a new ticket a provide steps to reproduce
