### ISSUE TITLE
KeepMinDuplicatePokemon Change

### ISSUE THREAD

**Issue by Fazy5** [NECROBOTIO/NecroBot#1962]
Shouldn't "KeepMinDuplicatePokemon" be "KeepMaxDuplicatePokemon" ?? Because even of 1500 cp+ i dont want my inventory to be filled with say 20 1500+ nedokings.. thats not something i'd want. kindly change it to max from min.

**Comment by AiksuCoding** [comment]
This is not a developmental issue, please use Discord for configuration help.
