### ISSUE TITLE
Looting no items

### ISSUE THREAD

**Issue by EVGAFTW** [NECROBOTIO/NecroBot#1963]
[21:16:59] XP: Fort Mason, Gems: 50, Items: 0

Works on the last build I used on Friday. Not functioning now.

**Comment by JSBeard** [comment]
Is your item bag full? Do you have "RecycleInventoryAtUsagePercentage": 0.95, set at something below 1.0?

**Comment by EVGAFTW** [comment]
The bot says it has looted gems: 50-100 and items: 0. I'm thinking it is
misconfigured. That should be my experience. Not gems. I do notice the
items replenishing though. As all of a sudden I have 30 more Pokéballs. But
it is not indicating that.

I have tried re-downloading and new configurations with no success.

**Comment by recon88** [comment]
Check our Discord for configuration help_ https://discord.gg/VXKxNFr

**Comment by EVGAFTW** [comment]
Not fixed and Discord referred me here. Thanks for not helping.
