### ISSUE TITLE
Sniping error

### ISSUE THREAD

**Issue by mars5838** [NECROBOTIO/NecroBot#1973]
"[21:16:55] (ERROR) System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346"

I get this error a lot and I'm not sure what it means

**Comment by streppelchen** [comment]
To check for available pokemon at the given locations, necrobot requests another service (which one depends on the specific version of necrobot). This service can be slow/offline, that's the error you see.

Instead i'd suggest using PogoLocationFeeder along side with the UseSnipeLocationServer Setting

**Comment by mars5838** [comment]
sorry im terrible with coding and programing im guessing pogofeeder is a snipe server? how wouldi imput this into the config file?

**Comment by Squirrel3098** [comment]
@mars5838 you would go to their website, find geocodes then add them in new instances of the current list of snipable geocodes

formatting looks something like this

`    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 34.1312081422,
        "Longitude": -118.533058234
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],`

**Comment by mars5838** [comment]
so i dont need to change any of these lines?

"UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,"

>

**Comment by mars5838** [comment]
Nevermind I think i sorted it out thank you very much for your patience and help!
