### ISSUE TITLE
bot crash again and again

### ISSUE THREAD

**Issue by HZH1907** [NECROBOTIO/NecroBot#1975]
Four bots crash one by one...I just can't run them more than 2 hours.
And things below show up many time before crash.

`[12:09:46] Niantic Servers unstable, throttling API Calls.`
`[12:09:47] Niantic Servers unstable, throttling API Calls.`
`[12:09:47] Niantic Servers unstable, throttling API Calls.`
`[12:09:47] Niantic Servers unstable, throttling API Calls.`
`[12:09:47] Niantic Servers unstable, throttling API Calls.`
`[12:09:47] Niantic Servers unstable, throttling API Calls.`
`.....................................many time....................................`
`[12:11:23] Niantic Servers unstable, throttling API Calls.`
`[12:13:50] Current Operation was canceled.`
`[12:13:51] Logging in using Ptc`
`....................................and crash.....................................`

It runs in a VMWARE WIN 7 because I am using a Macbook.
Is it cause by servers unstable? That is four PTC accounts.
Other two google accounts never been that problems...

**Comment by Squirrel3098** [comment]
Yeah probably PTC. their trainer club accounts have been known to have shitty even for legit players.

**Comment by HZH1907** [comment]
@Squirrel3098 OK  THANK YOU~
