### ISSUE TITLE
Problem I found

### ISSUE THREAD

**Issue by lolcheat321** [NECROBOTIO/NecroBot#1977]
What is happening?
 (ATTENTION) Encounter problem: EncounterPokemonFled
 (ATTENTION) Encounter problem: EncounterNotFound
(ATTENTION) Encounter problem: EncounterPokemonFled
 (ATTENTION) Encounter problem: EncounterNotFound

**Comment by Squirrel3098** [comment]
I'm not a developer but i believe it has to do with slow user to server interaction with niantic servers as it has only happened to me while the loads are high. alternative is that maybe it has to do with sniping?

**Comment by recon88** [comment]
Duplicate of #1856
