### ISSUE TITLE
Not sure if this is a bug or a feature that doesn't exist yet.

### ISSUE THREAD

**Issue by omar972** [NECROBOTIO/NecroBot#1978]
I have the bot set to wait until there are 50 pokemon ready to evolve, use a lucky egg then evolve them. But the problem is, it doesn't keep the pokemon that can evolve that are on the pokemon to evolve list.

'''
  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": false,
  "UseLuckyEggsMinPokemonAmount": 50,
  "UseLuckyEggsWhileEvolving": true,
'''

For example, I have Spearow in my pokemon to evolve list with over 1.5k candy, it transfers the ones it catches, would be great to have it not transfer any pokemon that I have enough candy for and have them on my pokemon to evolve list.

**Comment by JSBeard** [comment]
"KeepPokemonsThatCanEvolve": true, 

That needs to be your setting if I'm not mistaken.

**Comment by omar972** [comment]
@JSBeard That would keep all pokemon that can evolve, not only the ones that are in the pokemon to evolve list If I'm not mistaken.

@AiksuCoding If I'm correct, please re-open this issue.
