### ISSUE TITLE
Best CP/IV Stat

### ISSUE THREAD

**Issue by JSBeard** [NECROBOTIO/NecroBot#1980]
Can someone explain where these Best CP/IV stats are coming from, because in some instances it's showing the best CP as being lower than their current CP. 

![capture](https://cloud.githubusercontent.com/assets/20742740/17317345/7ab96af4-5831-11e6-9b5b-2b1dc94f1ac2.PNG)

**Comment by SwoleSnorlax** [comment]
If you set prioritize iv to true, it will show the highest iv pokemon and also its cp. If the highest iv pokemon is low cp, it will still transfer the lower iv one. lmk if you get it

**Comment by JSBeard** [comment]
Not sure we are talking about the same thing. Take the Growlithe for example. It hadoesn’t a CP at capture of 926, but when transferring it shows that CP, but then says "Best CP 256".

**Comment by JSBeard** [comment]
Or is that showing another Growlithe that is being kept in my inventory?
