### ISSUE TITLE
Option for renaming

### ISSUE THREAD

**Issue by wele** [NECROBOTIO/NecroBot#1983]
Hello,

On top of the rename pokemon option already in place, would it be possible to add to rename only if the pokemon hasn't already been renamed?

with rename enabled for iv 90+
Pikachu -> 92_Pikachu

But if i've already renamed that 92_Pikachu to PikaBoo
PikaBoo does not change
but the original (not renamed) would be changed to 92_Pikachu

Thanks

**Comment by vieryfl** [comment]
i prefer rename to be Pikachu_92
so if i sort by name, i get all Pikachu that already sort by IV
i think on older version, this is the format that necrobot using
can i have this format back?

**Comment by Whosdaman** [comment]
Agreed with @vieryfl

**Comment by NorwegianVikings** [comment]
Just change this to get the old format

New format:
"RenameTemplate": "{1}_{0}",

Old format:
"RenameTemplate": "{0}_{1}",

**Comment by nfettinger** [comment]
The new order allows sorting by name, putting the highest IV values at one end, and the lowest at the other. This can be very useful.

**Comment by nfettinger** [comment]
Also, adding the ability to append the text to a changed name would add a LOT of complexity to the parser. More than likely, it would have issues with bugs.

**Comment by Sasstraliss** [comment]
if name contains "_" + IV, good enough ;)
