### ISSUE TITLE
[Suggestion] Pre Selected locations per level

### ISSUE THREAD

**Issue by Phoenix10King** [NECROBOTIO/NecroBot#1984]
I just wondering .. and basically i want to ask ..
its possible at the new update to add an option for pre selected locations ???

lets say
i want from bot
on levels 1-10 to farm from (-33.859048, 151.213183)
on levels 11-20 to farm from (40.764883,-73.972967)

and continues like that ???

**Comment by streppelchen** [comment]
since the pokemons level adjust to your level it honestly doesn't make too much sense to do this. instead you can, from the very beginning on, catch whatever you want to have later, and get candies for that type of pokemon already.

**Comment by Phoenix10King** [comment]
yes but there are players like me that they cant spoof 
and the only method to get strong pokemons is the matter of luck wile farming
so we can have that option in order to change were ever we want when we are lower levels !!

am not talking about lvls30+ that need days to level up

**Comment by nfettinger** [comment]
It is my opinion that adding additional presets like this will make the unchanged bots more detectable. Requiring the user to select a location increases the randomness in the system, even if they all do go to Central Park in NYC.
