### ISSUE TITLE
Great balls only?

### ISSUE THREAD

**Issue by 750z** [NECROBOTIO/NecroBot#1990]
Pretty sure i checked the config and everything was ok, its only using great balls to catch any and everything

**Comment by Aneduna** [comment]
Is your issue that it is using no ultra balls or that it is not using Pokeballs?

**Comment by 750z** [comment]
its not using pokeballs

**Comment by Aneduna** [comment]
Have you checked if you have any Pokeballs and the bot not just recycled all Pokeballs and such using Greatballs?

Also please post a screenshot.

**Comment by 750z** [comment]
I had about 14 great balls, and its finished using them now, and now its using pokeballs to capture

**Comment by Energex22** [comment]
You must have a setting in the config wrong... i currently am only using pokeballs, have tons of ultra and Great balls

**Comment by Aneduna** [comment]
Please post a Screenshot of Throws where it should have used Pokeballs instead of Greatballs and post the section of the config with the throw conditions.

**Comment by Energex22** [comment]
These are my settings:
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,

The use masterball catch probability and others are using fractions..... so 0.2 is like below 20%

**Comment by baklaforever** [comment]
"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 2000,
  "UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.15,
  "UseUltraBallBelowCatchProbability": 0.08,
  "UseMasterBallBelowCatchProbability": 0.05,

**Comment by Wcidd** [comment]
@750z Could you please paste your "ball" config

**Comment by 750z** [comment]
im currently trying @Energex22 updated config right now.

**Comment by bignuts** [comment]
would be awesome if someone could implement a genetic algorithm that choose the right ball for you in each situation, with this custom setting i'm having more problem than before!

**Comment by theloser** [comment]
It's already implemented that you can choose exactly when you want the bot to use which pokeball, and (for me) it's working perfect. With #1966 been fixed, it will be less confusing in the settings, and nobody should have any more trouble (as long as he or she is not using wrong config values -- 99% of "issues" about "wrong usage of pokeballs" are config related).

**Comment by 750z** [comment]
Just want to mention that @Energex22 config is working for me.
Thank you everyone else!
