### ISSUE TITLE
[Feature Request] Set minimum CP for high IV pokemons

### ISSUE THREAD

**Issue by twelvedollar** [NECROBOTIO/NecroBot#1996]
Currently my inventory is always spammed with lots of high IV pokemons but with really really low CP (between 10 and 50).
I'd like to be able to specify something as followed:

MinCPtoKeepIV 1000

Therefore I'd like to only keep high IV pokemons which have at least 1000 CP.

**Comment by streppelchen** [comment]
"KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "and"

does exactly that.
you set the min CP you want and the min IV and set the operator to "and", so it will only keep those pokemon with an CP of at least 1250 and IV of at least 90.

or are you talking about catching?

**Comment by twelvedollar** [comment]
I don't have "KeepMinOperator" setting possibilities in my config

**Comment by streppelchen** [comment]
it is possible that this is a feature that is coming in the next version

**Comment by twelvedollar** [comment]
seems so. alright thanks I'll wait until the new version is released
