### ISSUE TITLE
Can't snipe a thing

### ISSUE THREAD

**Issue by kadaro90** [NECROBOTIO/NecroBot#1998]
I haven't got anything from sniping so far and I'm running NecroBot for like 2 days now. Is it rare to catch from sniping? I'm using the manual preset (8 nest loc/5 pokes) as the auto doesn't search any locations for me... I'm sure it's my preset but what am I doing wrong? Thanks

**Comment by Oolaruu** [comment]
Servers are maybe down, can be related.

**Comment by FatmaBlub** [comment]
Maybe your option is turned off? Check up the config file (config.json) and prove if the following option is set to "true":
>> "SnipeAtPokestops": true <<

**Comment by kadaro90** [comment]
No, sure it's on. I'm getting the sniper notifications in the bot but it doesn't find anything... When I'm on the auto preset though I get no notifications neither in Necrobot nor PogoFeeder...

**Comment by 750z** [comment]
api is down apparently.  The master has been fixed but you need VS to run that, otherwise you will have to wait for the new release

**Comment by sagiGL** [comment]
how do u use the vs ? on the pogo location feeder or the necrobot ?

**Comment by swc-tine** [comment]
Master has been fixed ? still same API call to skiplagged..
