### ISSUE TITLE
[Suggestion - Fix] Evolving/KeepPokemonThatCanEvolve calculation process

### ISSUE THREAD

**Issue by heypunisher** [NECROBOTIO/NecroBot#2001]
Hi!
Currently, the way the NecroBot is programmed for fonctions like "KeepPokemonsThatCanEvolve" and the mass evolving counter is a bit off. 

It doesn't take into account that evolving a pokemon gives 1 candy.  

i.e. evolving a pidgey is 12 candies. 
With 200 candies, KeepPokemonsThatCanEvolve will keep 16 pidgeys, as in 16x12 = 192 & 17x12 > 200. 

But in reality, it should keep 18 pidgeys, as in 18x11+1 = 199 & 19x11+1 > 200

I assume same goes for the amount of possible current evolutions.

**Comment by bignuts** [comment]
Also i suggest to keep pokemon to mass evolve only if pokemons are on the evolve list, i'm currenly ammassing pidgey/caterpie/weedle and i don't want to keep pidgeotto/kakuna ect because they need more candied to evolve

**Comment by theloser** [comment]
Evolution gives you candies? I don't think that's how it works! Of course you get one candy, if you transfer the Pidgeotto you got from evolving your Pidgey. but **if** you transfer the Pidgeotto (and therefor get a candy) depends on your transfer settings.

I agree you could optimize the calculation of how many pokemon the bot should keep, but I guess that would be a very complex calculation...

**Comment by heypunisher** [comment]
Yes, the evolution itself grants 1 candy. 
Therefore, evolving a pidgey is 10 candies if you count the transfer.

**Comment by theloser** [comment]
> Yes, the evolution itself grants 1 candy. 

Oh, I didn't know that. I just tested it and you are right, my bad.

**Comment by recon88** [comment]
So could anyone sumarize what exactly the enhancement is about?

**Comment by progz** [comment]
I agree with heypunisher.
If I have 144 candies for pidgey, it should kept me 13 pidgey and not twelve.
Because for each evolution, we will get 1 candy.

With 144 candies, I can evolve 12 pidgey directly.
But each pidgey evolved, we'll give me 1 candy. So I will get 12 extra candies and now I can evolve my last pidgey (the 13).

**Comment by NorwegianVikings** [comment]
@recon88 When
"KeepPokemonsThatCanEvolve": true, 
only keep pokemon that are in
 "PokemonsToEvolve": [

**Comment by progz** [comment]
+1

**Comment by nfettinger** [comment]
To sum up the issue, I am seeing 2 distinct fixes.
1. When KeepPokemonsThatCanEvolve is set to true, it is not counting the candy that is gained from evolving said Pokemon, it needs to increase the number held.
2. Pokemon that are not in the PokemonsToEvolve list are still being held.
