### ISSUE TITLE
Luresinpe option

### ISSUE THREAD

**Issue by pkosukhin** [NECROBOTIO/NecroBot#2003]
It would be great to have luresnipe as an option. I mean if we meet any pokestop (or may be several adjacent pokestops) with lure module installed, stop near of it and snipe till the lure ends. We can use this option with the same parameters
  "MinPokeballsToSnipe": 
  "MinPokeballsWhileSnipe": 
as for the autosnipe.

**Comment by recon88** [comment]
What would be the advantage over just farming pokemons which is faster? A lure only spawns a pokemon every 5 minutes. Don't see why the bot should wait there.

**Comment by Sky427** [comment]
I think what OP wants to do goes something like this 
Bot running normally
Detects Pokestop with Lure module 
Checks time remaining
Saves location
Continue running normally
Every 5 minutes snipe location until timer is out 
Then go back 1 more time 5 minutes later to check if a module is still there if not ignore it as usual

This would add to the number of catches per hour if done this way you could also end up sniping so much that you would be constantly catching pokemon.

**Comment by recon88** [comment]
Don't think this would give much of an advantage. If you put your bot in Central Park, there are Lures all over the place and Pokemon on mass. It's cathing Pokemon there all day with literally no break.
