### ISSUE TITLE
[Suggestion] Egg Incubator Improvement

### ISSUE THREAD

**Issue by Tomabl** [NECROBOTIO/NecroBot#2008]
The egg incubator always develops the first egg "in row", how about implementing the user choice to only develop 10km eggs (if available)? Thanks!

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/1579

**Comment by Whosdaman** [comment]
How about longest eggs first flag?

**Comment by recon88** [comment]
Duplicate of #1579
