### ISSUE TITLE
Source code cannot be loaded

### ISSUE THREAD

**Issue by nisanb** [NECROBOTIO/NecroBot#2009]
Hi !
I've just tried to download and run SLN sourcecode 0.5.0
I downloaded the zipped sourcecode but it seems like files are missing
C:\Users\nisan\Desktop\NecroBot-0.5.0\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\nisan\Desktop\NecroBot-0.5.0\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj'.  C:\Users\nisan\Desktop\NecroBot-0.5.0\FeroxRev\PokemonGo.RocketAPI\PokemonGo.RocketAPI.csproj

**Comment by Oolaruu** [comment]
Please, read here.
https://github.com/NECROBOTIO/NecroBot/wiki/Source-Code

**Comment by nisanb** [comment]
Thank you @Oolaruu 
Once I finished editing, how can I compile to the same way the Release.zip is compiled ?

**Comment by LookAtMyC** [comment]
@nisanb just check your bin/debug folder inside the project. The files should be there once you've created the solutions.

**Comment by nisanb** [comment]
I'm getting a few errors when trying to compile

> `Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'POGOProtos' could not be found (are you missing a using directive or an assembly reference?)	PokemonGo.RocketAPI	C:\Users\nisan\Desktop\NecroBot-0.5.0\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs	6	Active
`

>
