### ISSUE TITLE
Log File Disable

### ISSUE THREAD

**Issue by nisanb** [NECROBOTIO/NecroBot#2010]
Hi!
I'd appreciate an option to disable all log files writings (I think the issue causing crashes when multiple instances are opened)

Thanks ;)

**Comment by streppelchen** [comment]
are you running multiple instances from the same folder? 
normally the logfiles are no problem, and seperate instances should be run from different folders.

**Comment by nisanb** [comment]
I'm running instances from separate folders

**Comment by recon88** [comment]
Duplicate of #1917
