### ISSUE TITLE
Change Locations & GPX Route Files doesn´t work

### ISSUE THREAD

**Issue by Flacer9090** [NECROBOTIO/NecroBot#2011]
Hello,

if i try to change my GPX Path, downloading the Period: Lilydale_Period.gpx and put it in the same Directory as NecroBot.exe. Then I change the Lat and Long and set GPXPathing on true.

The bot always crash: https://postimg.org/image/ps0oawgv5/

Can someone help me?

**Comment by LookAtMyC** [comment]
post your config. 
You might have set wrong "" for the default Lat/Long

**Comment by Flacer9090** [comment]
Directory : https://postimg.org/image/y6q27a42f/
Config: https://postimg.org/image/l7wgnfv8n/

**Comment by Dark-pho3nix** [comment]
You must use GPXP with period and no comma :)

**Comment by recon88** [comment]
Check the Wiki or our Discord for configuration help: https://discord.gg/VXKxNFr
