### ISSUE TITLE
alternative to skiplagged

### ISSUE THREAD

**Issue by swc-tine** [NECROBOTIO/NecroBot#2012]
Can we use http://trackemon.com as an alternative to skiplagged for sniping since it's heaving big issues ?

**Comment by streppelchen** [comment]
that site isn't even useable in the browser for me

**Comment by swc-tine** [comment]
works for me though I don't know where their api location is or if it's available to use by the bot.

**Comment by recon88** [comment]
Trackemon doesn't work properly. Also they don't offer a proper API.
Please provide working alternatives.

**Comment by swc-tine** [comment]
I don't know any other that offers a working API

**Comment by recon88** [comment]
Will be fixed in next release.
