### ISSUE TITLE
[FeatureRequest] dynamic loading of config file

### ISSUE THREAD

**Issue by Cyberek** [NECROBOTIO/NecroBot#2013]
It would be nice to be able to dynamically load config file allowing to change all of the settings (such as pokemons to snipe, walking speed, distance, delays etc).
It could load it every few minutes (like every 5 minutes) or whenever the file changes.
It would be nice such "reload" of config would not restart process from the scratch.

**Comment by theloser** [comment]
To add to this: would be great to use different auth.json files also (per command line option?!) so we can use one instance of the bot to run for multiple accounts.

**Comment by nfettinger** [comment]
Reloading the config file would probably require a restart from scratch within the bot, especially when changing between things like GPX and sniping.

**Comment by nfettinger** [comment]
@theloser Please enter a separate issue for dealing with command line options (to replace auth.json files). This would help batch file users.

**Comment by theloser** [comment]
@nfettinger Done.
