### ISSUE TITLE
[FeatureRequest] minimize to tray

### ISSUE THREAD

**Issue by askovpen** [NECROBOTIO/NecroBot#2014]
[FeatureRequest] minimize to tray

**Comment by nfettinger** [comment]
This would require the program to run outside of the console, in a dedicated GUI environment. Such a tradeoff would limit the use to windows, prevent multiple instances, and the ability to launch through SSH and other means.

**Comment by theloser** [comment]
I just stumbled across ConEmu (http://conemu.github.io/), which can run multiple terminals in one window and which can be minimized to the system tray. Really awesome for running multiple bots -- and it's free like in beer :-)
