### ISSUE TITLE
A linux release or ?

### ISSUE THREAD

**Issue by LeaklessGfy** [NECROBOTIO/NecroBot#2015]
Hello,

I'm wondering if you guys plan to export this to linux ? Your bot is maybe the best for now so I'm wondering why only target Windows user ?

Thanks :)

**Comment by fr3k4life** [comment]
You can run this with the "mono" tool.
It doesn't work atm. but I hope it will be soon.

**Comment by Kostronor** [comment]
See #2022

**Comment by recon88** [comment]
I saw people getting it to work with Mono. Check our Discord, maybe they are around there: https://discord.gg/VXKxNFr
