### ISSUE TITLE
necrobot has gotten really slow 

### ISSUE THREAD

**Issue by bjens39** [NECROBOTIO/NecroBot#2018]
idk what happen just got really laggy like the time is stuck at 9 and takes ages to to login and got to pokestops, its not my config im at 300 speed

**Comment by tq01m4m** [comment]
so did i

**Comment by mennas** [comment]
same here...

**Comment by bjens39** [comment]
glad its not only me, thought it might of been my end

**Comment by mennas** [comment]
lol

**Comment by marrcha** [comment]
Umm, have you changed time between bot actions? I put it on 2000, its kind of fast for me.

**Comment by mennas** [comment]
i use 1 supposed to be faster
anyway its normal now

**Comment by bjens39** [comment]
yeah mines fine now
