### ISSUE TITLE
[FeatureRequest] save last coordinates for later start from

### ISSUE THREAD

**Issue by Cyberek** [NECROBOTIO/NecroBot#2019]
It would be nice that bot would save last visited coordinates and start from that point when restarted.

**Comment by Oolaruu** [comment]
Please, have a look into your config folder
You have a LastPos.ini

Or you are talking about the last position when the script loot from a pokestop or caught a pokemon ?

**Comment by Cyberek** [comment]
Ok, my bad, it works fine. Sorry for bothering.
