### ISSUE TITLE
Not starting on mono

### ISSUE THREAD

**Issue by Kostronor** [NECROBOTIO/NecroBot#2022]
I tried the v0.5.0 with mono again and got this:

```
> mono NecroBot.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'

```

Is there anything I'm missing?

**Comment by fr3k4life** [comment]
would be wonderful if this works!

**Comment by recon88** [comment]
I saw people getting it to work with Mono. Check our Discord, maybe they are around there: https://discord.gg/VXKxNFr

**Comment by Kostronor** [comment]
@recon88 I was the one getting it to work on mono. But new versions seem to have broken that

**Comment by Kostronor** [comment]
@recon88 seems like this is an issue with the current release. Can we reopen the issue?

**Comment by NecronomiconCoding** [comment]
Is there any Stack that you could provide?

**Comment by Kostronor** [comment]
Sure, provided it at the top while creating the issue. Nothing more output

**Comment by streppelchen** [comment]
just gave it a quick try: if you place the packages alongside the exe manually it will start, but then i have got the problem that it stops after "Playing as xxxx".

**Comment by Kostronor** [comment]
@streppelchen can you elaborate what package you mean and what you did exactly?

**Comment by Dewamade** [comment]
I dont use mono but wine instead and its works flawlessly with pogolocationfeeder

**Comment by recon88** [comment]
@Dewamade feel free to provide a tutorial and we will implement it in our Wiki.

**Comment by Dewamade** [comment]
Im using ubuntu lts 16,
1. install wine http://askubuntu.com/questions/762867/unable-to-install-wine-for-ubuntu-16-04
2. install winetricks 
$ sudo apt-get install winetricks
$ winetricks dotnet45
Just simple as that

**Comment by recon88** [comment]
Can anyone try that guide and confirm it's working?

**Comment by Dewamade** [comment]
Proof
http://imgur.com/gkfeXtL

**Comment by cbnolok** [comment]
Wouldn't it be better to make it working with mono? Even if it works with wine+dotnet45 there is still an issue tbh.

**Comment by recon88** [comment]
What would be that said issue? It seems to be working fine.

**Comment by cbnolok** [comment]
It works with wine but not with mono, and i see wine as a workaround. As 
a c# application, this is supposed to run directly with mono imho.

**Comment by recon88** [comment]
This requires extra work by the devs. The current focus is stability so I suggest using Wine for now.

**Comment by ipanggabean** [comment]
I'm sorry to bring this up again, but it seems like I can't use wine even after following Dewamade's instruction. I seems to need 32bit version of wine, and installing dotnet version 2, 3, 4, and 4.5, but failing when installing version 3.

If I use fresh 64bit version of wine, I can run the bot, but seems like it can't reach the network, causing the login to always fail.

Is it possible to get detailed explanation on how to run the bot using wine?
