### ISSUE TITLE
Bot throw every hyperball away and keeps greatball ....

### ISSUE THREAD

**Issue by Rinkaku** [NECROBOTIO/NecroBot#2024]
my setting : "TotalAmountOfPokebalsToKeep": 500

**Comment by Wcidd** [comment]
Whole pokeball settings please

**Comment by Rinkaku** [comment]
"TotalAmountOfPokebalsToKeep": 500
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 0,
  "UseUltraBallAboveIv": 0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,

**Comment by Wcidd** [comment]
Bot throw every **hyperball** away and keeps greatball ....
What is a hyperball?

**Comment by Rinkaku** [comment]
ah sry , its german for ultraball

**Comment by somani6** [comment]
"UseGreatBallAboveIv": 0,
"UseUltraBallAboveIv": 0,

That means a UltraBall is used for everything above 0 IV - so effectively every time. Change it to something more suitable.

**Comment by rem-0-rseful** [comment]
Try adding this as one of the entries under ItemRecycleFilter:

```
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemGreatBall",
      "Value": 75
    },
```

That should save up 100 UltraBalls and 75 GreatBalls respectively.
Also, if you're adding that to the end of the function, ensure you remove the comma after the last parentheses. 

**note:** untested.

**Comment by recon88** [comment]
Check our Discord for configuration help please: https://discord.gg/VXKxNFr

**Comment by somani6** [comment]
ItemRecycleFilter does no longer affect Balls

**Comment by Rinkaku** [comment]
@rem-0-rsefu

Thanks , works like a charm. *.*
