### ISSUE TITLE
New Setting: Moving 

### ISSUE THREAD

**Issue by Kostronor** [NECROBOTIO/NecroBot#2025]
I thought about a new setting. If you don't want to get banned but want to change your base farming location, what would be awesome is a setting saying "while walking, move there slowly" while catching all pokemon and pokestops on the way.

**Comment by somani6** [comment]
Set your WalkingSpeedInKilometerPerHour to something around 6 what is a normal human walking speed. The Ret is already done (Human Walking).
If you want your customized route, use a gpx file and you'r fine.
https://github.com/NECROBOTIO/NecroBot/wiki/GPX-Pathing-Setup

**Comment by Wcidd** [comment]
You have 'LastPos.ini' in your config folder, if you change coords, the bot will walk to the LastPos coords.
For slowly walking there set 'disableHumanWalking' to false and lower the KMph.
All of this is already implemented

**Comment by Kostronor** [comment]
So lastpos is not your login position but the first position to walk to? 

I suggest documenting this as a feature for others to find

**Comment by Kostronor** [comment]
@Wcidd I tested that and it is not working:

I shut down the bot and modified `LastPos.ini` to be somewhat far away. I started the bot again and it started at it's starting position. The bot does not move to the position in `LatsPos.ini` but overrides it.

How do I get the bot to move from one point to another over time without using gpx?

**Comment by Wcidd** [comment]
@Kostronor 
I meant that LastPos is the last coords the bot recieved from your config.jason
So if you change your coords without deleting LastPos.ini it should walk there.

**Comment by Kostronor** [comment]
@Wcidd sadly my softban tells a different story. Changes my coordinates without modifying LastPos.ini and the bot started at coordinates, not LastPos => Softban

**Comment by Wcidd** [comment]
Sorry i was totally wrong, but i think the only way to do that is using gpx file
