### ISSUE TITLE
Not mass evolving

### ISSUE THREAD

**Issue by Troelsnap** [NECROBOTIO/NecroBot#2026]
Hi,

I had auto evolving pokemons from the 0.4 version, worked like a charm and using egg beforehand.

However after it migrated to 0.5, it does not evolve when I have 100 - it does come up with a notice that I have a 100 to evolve, even up to 153 to evolve.

Copied the CFG in from 0.5 to a 0.4 bot and ran it, it instantly evolved all the pokemons correctly.

**Comment by romkazor** [comment]
Can you post your settings for this?

**Comment by rem-0-rseful** [comment]
Ensure that the Pokemon you wish to evolve are listed under PokemonsToEvolve, as well as that EvolveAllPokemonWithEnoughCandy is set to _true_.

**Comment by recon88** [comment]
Check our Discord for configuration help please: https://discord.gg/VXKxNFr 

There's also a small bug with evolving and eggs currently. That should be fixed in the next version. Not sure if it's related to your issue

**Comment by Troelsnap** [comment]
All the pokemons are listed in the list, I added a few myself. Probably the bug recon is mentioning - as it works fine in the previous version - with a straight up copy of the cfg file.

**Comment by Troelsnap** [comment]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": false,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 0,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 55.673215799999987,
  "DefaultLongitude": 12.582126399999993,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 0.9,
  "KeepMinCp": 1500,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,
  "PrioritizeIvOverCp": false,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 100,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": false,
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokebalsToKeep": 400,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 3000,
  "UseGreatBallAboveIv": 50,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 50.0,
  "UseUltraBallBelowCatchProbability": 20.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "TransferDuplicatePokemon": true,
  "FavoriteMinIvPercentage": 0.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "goldeen",
    "paras",
    "ekans",
    "staryu",
    "psyduck",
    "krabby",
    "venonat",
    "magnemite",
    "poliwag"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Magikarp": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "magmar",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by Troelsnap** [comment]
just copy pasted in my entire cfg, didnt change much - but for what I needed
