### ISSUE TITLE
[FeatureRequest] MaxRunTime/ExitAfterMinutes

### ISSUE THREAD

**Issue by Okkaaj** [NECROBOTIO/NecroBot#2027]
Should be easy to implement. 

Close the app after running certain amount of time. For example,` ExitAfterMinutes: 90 ` would exit the application after 1,5 hours has passed. 

... or then I just might do it myself. :)

**Comment by recon88** [comment]
Just use a simple batch file for that. 
If you want to do it yourself, make sure you create a pull request ;)
