### ISSUE TITLE
[Feature Request] Show coords on catch and show move damage in summary

### ISSUE THREAD

**Issue by Sasstraliss** [NECROBOTIO/NecroBot#2030]
1) Show the lat/long coords in the line for catching a pokemon, so we can declare it on sniping channels.
2) Show the damage in brackets next to the moves each pokemon has during the pokemon listing at the start.

**Comment by theloser** [comment]
Totally agree with number 1 (great idea!), don't need number 2 though...

**Comment by redChrillz** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2030

**Comment by nfettinger** [comment]
Setting the print output value to debug will do this.
