### ISSUE TITLE
[Bug] Periodical crash (TaskCanceledException)

### ISSUE THREAD

**Issue by Sasstraliss** [NECROBOTIO/NecroBot#2041]
On some of my bots after 1hr 31 seconds, twice in a row

System.Threading.Tasks.TaskCanceledException was unhandled
Message: An unhandled exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.dll
Additional information: A task was canceled.

**Comment by recon88** [comment]
Should be fixed in next release
