### ISSUE TITLE
[Feature] Snipe for Pokedex

### ISSUE THREAD

**Issue by kaardilugeja** [NECROBOTIO/NecroBot#2042]
Hey,

Mabye when #2038 is implemented we could add feature to snipe for pokemons that are not yet caught to  fill your pokedex? Something like SnipeForPokedex: true, or smth?

Edit: Minor text fixes.

**Comment by qwe900** [comment]
thats would be awesome

**Comment by ChemiHatake** [comment]
unfortunately I think its impossible without changing 'PokedexEntry' in the API.
