### ISSUE TITLE
a misunderstand of Transferring in wiki.

### ISSUE THREAD

**Issue by yanrongmao** [NECROBOTIO/NecroBot#2044]
I've found some problems at NecroBot Wiki. It located at chapter Transferring.
for example, i've set the value of KeepMinIVPercentage to 100. at this word 

> Below the KeepMinIVPercentage value

i understood that is my Pokemon could not be transferred when it's value of KeepMinIVPercentage equals 100. 
then i saw an another word 

> This value specifies that a Pokemon that has an IV higher than this value will not be transferred. 

i understood that is my Pokemon could be transferred when the value of KeepMinIVPercentage  is 100.
because it is not higher than this value (100), it is equals 100 reality. so ,i think the second word should be change to 

> This value specifies that a Pokemon that has an IV below than this value will be transferred.

or take an opposite explain; 

in fact, my Pokemons were be trasferred when i set the value of KeepMinIVPercentage  to 100.
it make me heart-broken. -_-!

**Comment by kaardilugeja** [comment]
I think your pokemons got transferred due to the fact that no pokemon has IV higher than 100. So if you set KeepMinIVPercentage to 100 that means your pokemon must have higher IV than 100 to not get transferred when TransferDuplicatePokemon is set to true. Maybe this situation could be handled better in the code if this is the case.

**Comment by Wcidd** [comment]
Waiting to know from devs if 100IV is incuded when KeepMinIVPercentage=100

**Comment by Wcidd** [comment]
Was bugged, after next releace it will be fixed

**Comment by kaardilugeja** [comment]
This change should be reflected in Wiki as well. Right now it says that only pokemons with "higher than this value" will not be transferred.

**Comment by Wcidd** [comment]
True, will do that, thanks!

**Comment by yanrongmao** [comment]
thanks very much, more exactly is ,some of my Pokemons were be transferred, not all.
