### ISSUE TITLE
Bot is working VERY slow

### ISSUE THREAD

**Issue by KASHiRiNKiTO** [NECROBOTIO/NecroBot#2051]
Hi,
very nice bot! It works perfect.

But now I have an issue. It works very slow for some reason. It takes a long time to log in and then all other actions are very slow aswell. It works very good and fast yesterday. (Everything is updated).

I use a second account and the bot works very fast, but one account is very slow.

**Comment by recon88** [comment]
Please visit our Discord for help:  https://discord.gg/VXKxNFr
