### ISSUE TITLE
[Enhancement] Post "Potential Evolves" with intervals

### ISSUE THREAD

**Issue by NorwegianVikings** [NECROBOTIO/NecroBot#2059]
Right now the bot is only posting the (update) [evolves] Potential Evolves, when the bot is ready to begin mass evolve. It would be nice if the bot posted the update with potential evolves like every 10min, so you could see the progress to next mass evolve.

**Comment by recon88** [comment]
Sounds good but definitely needs an option to turn it off and another one to set the delay for it.

**Comment by NorwegianVikings** [comment]
Edit: When "EvolveAllPokemonWithEnoughCandy": true, it will post updates with intervals. But if you want to evolve based on inventory% and not based only one potential/eggRequirement, it will not post updates

**Comment by BennettStaley** [comment]
in the previous version it would display [Evolves] Potential Evolves: 20| 80 required for mass evolving when you had "UseLuckyEggsWhileEvolving" and "UseLuckyEggsMinPokemonAmount" set up correctly. However now it does not. and setting "UseLuckyEggsMinPokemonAmount" to something like 2 still fails to trigger the lucky egg. Definitely bugged.

**Comment by actislav** [comment]
fix it in #2213
