### ISSUE TITLE
Transferring pokemons which are above "KeepMinCp" value

### ISSUE THREAD

**Issue by noodle-** [NECROBOTIO/NecroBot#2063]
A recent commit has messed this up.

Before: Any pokemon above "KeepMinCp" would not be transferred.
Now: Only the best pokemon is kept, "KeepMinCp" seems to be ignored

example: 
My config includes "KeepMinCp": 2100
but after starting the latest version: [screenshot](http://i.imgur.com/3gehh1B.png)

**Comment by NecronomiconCoding** [comment]
Whats your KeepMinOperator set to ?

**Comment by noodle-** [comment]
Oh.
"KeepMinOperator": "and"

Apparantly that got added recently in 9d86123777a208562a642ae18968a53bf0f0d7a6 .

That's a horrible default value if the previous default behaviour was the same as  "or".

I've fixed it in #2071
Thanks for pointing me in the right direction.
