### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by seemonyeh** [NECROBOTIO/NecroBot#2064]
![error](https://cloud.githubusercontent.com/assets/20796481/17331379/f4224fdc-590d-11e6-8dd6-740c88f2e5dd.png)

**Comment by nfettinger** [comment]
This appears to be a connection close request from the server that was not handled gracefully in the API.

**Comment by seemonyeh** [comment]
So what does that mean ...?

**Comment by recon88** [comment]
Feel free to create an issue ticket at the API's repo:
https://github.com/NECROBOTIO/NecroBot-Rocket-API/issues
