### ISSUE TITLE
PokemonsTransferFilter cannot work correctly

### ISSUE THREAD

**Issue by thomasbad** [NECROBOTIO/NecroBot#2066]
Tested with 3 different setting and accounts, but still founds that the PokemonsTransferFilter entry cannot work correctly with override by global setting.

For example, if below setting have been set:
"KeepMinCp": 1900,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 95.0,
"KeepPokemonsThatCanEvolve": false,

"PokemonsTransferFilter": {
    "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 10
    },
  },

Then the bot will try to transfer the Snorlax which is CP below 1900 and IV below 95, the PokemonsTransferFilter setting and KeepMinDuplicatePokemon setting won't work, which will caused the account will flood with Snorlax with CP>1900 easily and got Pokemon inv full alert

**Comment by guidedbymoon** [comment]
filter overrides the global setting you can just set filter to what you want, also you have duplicate to 10 that means that it will only consider transferring any snorlax when 11 snorlax is in inventory

what i did is remove all of pokemon transfer filters and set to
"KeepMinCp": 2000,
  "KeepMinDuplicatePokemon": 0,
  "KeepMinIvPercentage": 90.0,

this will make you have all pokemon with iv 90 but also all pokemon with 2000cp, duplicate  only comes into play if you have a pokemon with less than iv for example if you have two piddys with 45 iv and 50iv if duplicate is 1 it will keep the 50iv, but if you put duplicate to zero then it will only keep piddys with iv greater than the setting

**Comment by Furyslayer** [comment]
For the snorlax it is keeping if any one of those settings are met.  So it is keeping all snorlax above 90 and all snorlax above 2000.  Set your numbers higher.

**Comment by thomasbad** [comment]
Yes, but the problem is, with the example I have set, my pokemon inventory floods with 32 qty Snolax instead of 10 qty.

And it still keeps bunch of pokemon with very low CP and IV which is not in the evolve list too. And, none of the entries under Pokemon transfer filter works either as it have override by global setting, which should be reverse instead.

And anything under pokemon transfer filter will caused the global setting of KeepMinDuplicatePokemon" won't work on them too. Which means if you've got goldduck under "PokemonsTransferFilter", it will keeps flooding your pokemon inventory with the CP above you global setting until it is full

**Comment by thomasbad** [comment]
@recon88 I think they misunderstanding my lang instead it is closed...

**Comment by recon88** [comment]
Please join our Discord and ask for configuration help: https://discord.gg/VXKxNFr

**Comment by guidedbymoon** [comment]
`

`just set duplicate to zero and see what happens it will fix
