### ISSUE TITLE
Not Evolving?

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#2067]
https://i.imgur.com/MzOM3RP.png

I think I have the correct settings enabled but it's not evolving anything.

The only setting I am unsure about is:

  "EvolveAboveIvValue": 100.0,
  "EvolveAllPokemonAboveIv": true,

I think those are to always evolve something thats 100.00 IV correct? and it shouldn't effect anything else?

But everything else is :

  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseLuckyEggsMinPokemonAmount": 40,
  "UseLuckyEggsWhileEvolving": true,

  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "ekans",
    "sandshrew",
    "geodude",
    "vulpix",
    "zubat",
    "growlithe",
    "psyduck",
    "meowth",
    "paras",
    "venonat",
    "diglett",
    "poliwag",
    "machop",
    "ponyta",
    "magnemite",
    "doduo",
    "seel",
    "voltorb",
    "exeggcute",
    "cubone",
    "rhyhorn",
    "koffing",
    "horsea",
    "goldeen",
    "staryu",
    "omanyte",
    "eevee",
    "krabby",
    "drowzee",
    "spearow"

Doubled the required and still not evolving
https://i.imgur.com/KdILBIa.png

**Comment by Simpuhl** [comment]
I am at 110 evolves out of 40 now, still hasn't evolved anything just a heads up

**Comment by noodle-** [comment]
Probably because you haven't reacht 90% of your pokemon inventory yet.

see "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,

Set it to 0.1 or whatever and then it should start revolving pokemons regardless of inventory percentage.
