### ISSUE TITLE
NECROBOT Using Great and Ultra Balls when it should NOT

### ISSUE THREAD

**Issue by thesticks00** [NECROBOTIO/NecroBot#2069]
Hey guys. As of the latest release 5.0 the bot is prioritizing using UltraBalls and GreatBalls regardless of the level. I watched as the bot continued to use ultra's and Great balls on level 4 pokemon wasting the supplies over and over. Now I am down to nothing but regular pokeballs  and of course now all I see is catchflees or catch escapes because I have nothing to catch higher level pokemon. Is there currently a fix for this?

**Comment by recon88** [comment]
Duplicate of #1745 and possibly #1862

**Comment by nfettinger** [comment]
Please update your config. There are new filters for which balls to use.
