### ISSUE TITLE
[FeatureRequest]Add PokemonNotToEvolve?

### ISSUE THREAD

**Issue by Beltian** [NECROBOTIO/NecroBot#2072]
Is there anyway to add a list of pokemon not to evolve, currently I want all pokemon to be evolved except magikarp. I tried setting the evolve all with enough candy's and setting only evolve certain ones, but it still evolves magikarp even without it being in the list to evolve.

**Comment by Dyzson** [comment]
"PokemonsToEvolve": [
    "bulbasaur",
    "ivysaur",
    "squirtle",
    "wartortle",
    "caterpie",
    "metapod",
    "weedle",
    "kakuna",
    "pidgey",
    "pidgeotto",
    "rattata",
    "spearow",
    "ekans",
    "sandshrew",
    "clefairy",
    "vulpix",
    "jigglypuff",
    "zubat",
    "oddish",
    "gloom",
    "paras",
    "venonat",
    "diglett",
    "meowth",
    "psyduck",
    "mankey",
    "poliwag",
    "poliwhirl",
    "abra",
    "kadabra",
    "machop",
    "machoke",
    "bellsprout",
    "tentacool",
    "geodude",
    "graveler",
    "ponyta",
    "slowpoke",
    "magnemite",
    "doduo",
    "seel",
    "grimer",
    "shellder",
    "gastly",
    "haunter",
    "drowzee",
    "krabby",
    "voltorb",
    "cubone",
    "koffing",
    "rhyhorn",
    "horsea",
    "goldeen",
    "staryu",
    "omanyte",
    "kabuto"
  ],

not listed: Charmander, Charmeleon, Pikachu, Nidoran F, Nidorina
, Nidoran M, Nidorino, Growlithe, Bellsprout, Weepinbell, Exeggcute, Magikarp, Eevee, Dratini, Dragonair.

**Comment by recon88** [comment]
As mentioned above, just put all in the list and keep whatever you don't want to evolve out of it
