### ISSUE TITLE
PrioritizeIvOverCp issue

### ISSUE THREAD

**Issue by claudiogbr** [NECROBOTIO/NecroBot#2076]
![untitled](https://cloud.githubusercontent.com/assets/3168552/17332001/8898d096-58cd-11e6-9671-7c23ce6b85a7.jpg)

With same IV the pokemon with lowest cp should be transfered

**Comment by nfettinger** [comment]
Maybe rounding the IV in the print statement is hiding why one was chosen over the other.

**Comment by Wcidd** [comment]
Fixed in 0.6
