### ISSUE TITLE
Recycling/egg incubating not working ?

### ISSUE THREAD

**Issue by sasgey** [NECROBOTIO/NecroBot#2079]
got this problem with 4 different accounts and different hardware (google & ptc)
in the bot it all looks like its recycling all the items that it needs to, but if i check that in pogo-app my inventory is more than full (1200/350) and i have to clear the inventory by hand.

same with incubating eggs ... in the bot it looks like its doing its job, but in the app i got tons of eggs and unused incubators

anyone else noticed this ?

**Comment by recon88** [comment]
Should be fixed in next release.
