### ISSUE TITLE
[FeatureRequest] GUI Pokemon list

### ISSUE THREAD

**Issue by Aralyn** [NECROBOTIO/NecroBot#2081]
I think it would be a good idea to add a list (GUI) with Pokémon in our inventory and the ability to evolve, recharge and transfer as bot "PokeCrot" :
![capture](https://cloud.githubusercontent.com/assets/20797150/17332999/0a950d96-58d1-11e6-967d-a510d6e56e41.PNG)

**Comment by nfettinger** [comment]
This is what the Websocket is used for. Please see the following project:
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by Aralyn** [comment]
Wow... It's very cool ! Thank very much ;)
