### ISSUE TITLE
[FeatureRequest] - Add option to write csv log for spotted/captured pokemon

### ISSUE THREAD

**Issue by Alekc** [NECROBOTIO/NecroBot#2083]
It would be nice (since we already have all necessary data) to be able to dump pokemon data in separate csv file (with name, lvl, cp, IV, etc), in order to be able to use it later (i.e. finding where did that rare one was captured). 

I believe there is a **DumpPokemonStats** setting but if I am not wrong that does different thing.

**Comment by ANR2ME** [comment]
Having an option to dump a list of pokemons found within travel radius from default location before closing the program would also nice :) so we could create a data of what kind of pokemons found within an area, and each pokemon's occurrence ratio in that area.

**Comment by Menton** [comment]
DumpPokemonStats does almost exactly what you are suggesting. It shows various data: http://prnt.sc/c0qrnx However, it does not yet save any location data.

**Comment by Alekc** [comment]
Yes, and last 3 columns are not really needed for statistical data analysis :) 

I think needed columns are

- name
- lvl
- trainer lvl
- IV
- CP
- Lat
- Lon
- TimeStamp
- Lured by Incense/Lure/Normal

**Comment by Menton** [comment]
@Alekc it was recently updated. I think that it shows (more than) enough information now ;)
