### ISSUE TITLE
"KeepMinIvPercentage" issue

### ISSUE THREAD

**Issue by dfmeier** [NECROBOTIO/NecroBot#2084]
"KeepMinIvPercentage": 90.0, transfered eevee and dratinis (latest source)

![proof](https://cloud.githubusercontent.com/assets/12189742/17333330/42062bc4-58d2-11e6-9041-4658d13bbb6b.jpg)

**Comment by recon88** [comment]
Post your full config

**Comment by NorwegianVikings** [comment]
He is using the lastest source, it seems to not honor that if a pokemon is over the MinValue for CP or IV, it will be kept. It counts these as duplicates eventhough both are over the set CP or IV value.

**Comment by dfmeier** [comment]
The latest release with the same config collect and kept them only the new source transferred and only these two types of pokes.

**Comment by dfmeier** [comment]
Please find bellow my config (coordinates removed)
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/397349/config.txt)

**Comment by pacinoallstars** [comment]
i've had the same yesterday, im waiting for an update.

**Comment by Naprosnia** [comment]
this happens to me. I change the option "TransferWeakPokemon" to false and it works Ok.
