### ISSUE TITLE
[Feature Request] Level, CP, IV Keep/Evolve Filter

### ISSUE THREAD

**Issue by josephdouce** [NECROBOTIO/NecroBot#2085]
I think it would be benficial to filter kept pokemon on Level/IV instead of CP/ IV

CP is really ambiguis as a good CP Polywhirl is not the same as a Polywrath. Setting the min CP to 1500 means good 100IV base pokemon get transfered as Dratini, Squirtle etc never meet the 1500cp requirment.

**Comment by nfettinger** [comment]
Levels and CP can always be changed, IV cannot. The goal was to make the recycle filter most applicable to this variable.

**Comment by josephdouce** [comment]
The issue is not IV IV is great, no issue there the issue is CP is totally meaningless and changes for every pokemon, if you could set keep to IV>95% and LvL>25 would be great as it is I can set min CP to 1500 and a prefect lvl 30 dratini will always get transferred it will never meet the min CP.

**Comment by yps** [comment]
A perfect dratini will never get transferred because it has 100%IV because you set the filter to 95%IV. I don't see any problem here. I got a 133CP Snorlax with 100%IV and it will never get transferred because it will always prioritize IV over CP.

**Comment by Simpuhl** [comment]
As long as IV is priority you shouldn't have anything to worry about.

I keep IV 100 CP 1 if I could. IV 100 is rare. Ill level that bitch hardcore if I have to

**Comment by josephdouce** [comment]
Also it would be nice to only keep pokemon that meet both filters.

**Comment by Simpuhl** [comment]
Well, it would keep the best one, so eventually you would get one that meets both hopefully... So it already does that

**Comment by tangdami** [comment]
A 133 CP Snorlax with 100IV? I will transfer it in a heartbeat because it's useless compared to the 2300 CP Snorlax with 90 IV, which can save you tons of stardust. 
Please add an option as @josephdouce mentioned! Thanks!

**Comment by yps** [comment]
@tangdami yeah then you get rekt when it is powered up. You have so much stardust anyways when you bot. So stardust will never be a problem.

**Comment by josephdouce** [comment]
level will always be better filter option then CP since CP changes based on pokmon level. if i set min CP to keep to 500 then it could keep a 10IV 501CP dragonite, it could also keep a 501cp 100IV dratini, one of which is totally useless. If if filtered based on level the 10CP 500IV dragonite could be easily ignored.

**Comment by josephdouce** [comment]
Basically dont change the IV filter, replace CP with LVL
