### ISSUE TITLE
transfer duplicate pkmn not seeming to work

### ISSUE THREAD

**Issue by GamingMaster777** [NECROBOTIO/NecroBot#2086]
it keeps saying "transferring blah blah blah..." but not <transfered>"pokemon" is transfered or something. sometimes it says set transferduplicatepokemon to true or mannualy transfer and it already is true

**Comment by nfettinger** [comment]
please check your configuration of KeepPokemonsThatCanEvolve. It may be holding on to some for XP purposes

**Comment by burnshroom** [comment]
I have the same issue and "KeepPokemonsThatCanEvolve" is set to false.

In my inventory I have 54 Snorlax.
