### ISSUE TITLE
Bot NOT evolving EXP pokemons

### ISSUE THREAD

**Issue by henryzolo** [NECROBOTIO/NecroBot#2087]
Have been botting all night and end up having several hundred of each CPWR ("caterpie","weedle","pidgey","rattata") candies. Not sure if it is a bug but it is really annoying. I posted my setting here. Anyone having the same issue?

Here is my setting:
  "EvolveAllPokemonWithEnoughCandy": true,
  "KeepPokemonsThatCanEvolve": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 50,
  "UseLuckyEggsWhileEvolving": true,

"PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],

**Comment by theloser** [comment]
How many Pokemon do you have in total? Is your pokemon inventory filled less then 90%? The bot will only mass evolve if you reach 90+% (i.e. 230 of 250).

**Comment by pikkiamitanto** [comment]
"EvolveKeptPokemonsAtStorageUsagePercentage": 0.0,

it should not wait the mass evolve and evolve when it can

**Comment by Simpuhl** [comment]
Same problem here, i posted not sure what happened to my post tho, it disappeared

**Comment by henryzolo** [comment]
I was trying to stock up the CPWR to mass the evole and use lucky egg, but somehow the bot transferred them away, not sure if I need to set "TransferDuplicatePokemon": false.
But if I config it like that, what happen to those pokemons that I don't want to have more than one...

**Comment by henryzolo** [comment]
@theloser the bot is only keeping one of each, so it will never reach the storage limit I set.

**Comment by henryzolo** [comment]
Just thought of a possible solution here:

add those EXP pokemons to the list 
"PokemonsNotToTransfer": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",



this might help, gonna try it out tonight.

**Comment by theloser** [comment]
> the bot is only keeping one of each, so it will never reach the storage limit I set.

Huh? In your first post you said you "end up having several hundred of each".

**Comment by henryzolo** [comment]
@theloser Several hundred candies~

**Comment by theloser** [comment]
Oh, sorry. My bad.
