### ISSUE TITLE
Pokemon rare list

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2088]
What about having a central pokemon rare list in the config, which u can use for multiple stuff like:
**not transfer rares, only snipe rares, only evolve rares, only use great/ultra/masterballs on rares.**

Then you only would have to manage one list instead of manies, if you want. But it should still be possible to switch to many lists on user decision via flag or something.

Ad default rare list one could use this one as starting point: https://i.imgur.com/Sfrn4lQ.png
or some combinations those toplists: https://pokemon.gameinfo.io/pokemon

**Comment by Simpuhl** [comment]
Only evolve rares? wouldn't the rares already be the evolved versions?

Id like onlylevelrares

**Comment by ANR2ME** [comment]
Having legendary list would also be nice :)

**Comment by Oolaruu** [comment]
bulbapedia.bulbagarden.net/wiki/Legendary_Pokémon
