### ISSUE TITLE
Mass evolving not evolve all pokemon

### ISSUE THREAD

**Issue by progz** [NECROBOTIO/NecroBot#2089]
Hi,

As you can see on the screenshot below, I don't understand why Necrobot is not evolving all of my weedle only some of them. I had enough candies !
[Screenshot of my NecroBot console](http://hpics.li/c630262)
[My config.json file](http://pastebin.com/rCn8mTWr)

If you need other information, just ask :)

**Comment by recon88** [comment]
Should be fixed in next version
