### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2092]
for some reason the bot does not translate the actual pokemons names.

everything else is getting translated fine, but not their names. please take a look

**Comment by Marsinator** [comment]
https://images-2.discordapp.net/.eJwFwUsOwiAQANC7sJdBoHx6AXfGK4yUUBJgGhhXxrv73ld8ZhO7OJmvtQMcdSWah1xME0uWhai0jFddMlEHZMZ09jx4gVZRexu2aEMIygbnQN-V2pw3UflotHE2Ak8cqyFXGrdr0rvlLl_Ph_j9Ac2lJ08.VPQrziX4p4biEmWtAlZxZcsMnmg.PNG

**Comment by Silverarrows1986** [comment]
https://gyazo.com/ea9c0d6f7186908156714318fc0902cf

https://gyazo.com/30f541a48eedb7661719e9d4068fb802

**Comment by starrheld** [comment]
@Marsinator - It's because someone will have to translate them to their german name. Not a bug.

**Comment by sebastianbrandner** [comment]
i have tried to add some lines to the translation.de.json but it does not work

```
{
  "PokemonStrings": [
	{
		"Key": "001",
		"Value": "Bisasam"
	},
	{
		"Key": "002",
		"Value": "Bisaknosp"
	}
  ],
  "TranslationStrings": [
    {
      "Key": "pokeball",
      "Value": "Pokéball"
    },
```

i used the json property name and added it to the same file

**Comment by starrheld** [comment]
Translation of Pokémon name is not implemented for any language, but if you do that for every Pokémon and send a pull commit it will get implemented in the future most likely. @sebastianbrandner

**Comment by sebastianbrandner** [comment]
@starrheld ok, i'll extract the information from the pokewiki.de list :)

should i add it to the existing translation files (translation.<lang>.json) or add another file like pokemon.<lang>.json?

**Comment by starrheld** [comment]
@sebastianbrandner -
Check this one out, do exactly the same:
https://github.com/NECROBOTIO/NecroBot/pull/2070

**Comment by sebastianbrandner** [comment]
@starrheld i just cloned the master branch and in this translation.de.json file there is every pokemon translated

so i think, this bug is maybe already solved?

**Comment by AiksuCoding** [comment]
It come in 0.6
