### ISSUE TITLE
Weird Transfer

### ISSUE THREAD

**Issue by ANR2ME** [NECROBOTIO/NecroBot#2093]
May i know why Charmander CP:95 IV:80.56% is being transferred while the Best is CP:12 IV:65.26% on the latest source from git (just build it a few minutes ago, where last commit is "add back the missing files") ?

Is this because of the new config called "TransferWeakPokemon" which is enabled by default on auto-migration? and what is the criteria for "Weak" for this config?

![transferweak](https://cloud.githubusercontent.com/assets/7974720/17334915/368c4938-5902-11e6-89ea-3af195c4db34.jpg)

**Comment by Simpuhl** [comment]
Dang, that sucks. Definitely a bug

**Comment by ANR2ME** [comment]
Slowpoke seems to get it also, it seems to transfer the best one it self at the end O.o

![transferweak2](https://cloud.githubusercontent.com/assets/7974720/17335091/f1f03054-5902-11e6-9d92-2268f6de7988.jpg)

**Comment by Wcidd** [comment]
Transfer config please?

**Comment by Simpuhl** [comment]
Dang that slowpoke was higher cp and Iv

**Comment by ANR2ME** [comment]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": false,
  "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 0,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 0.0,
  "UpgradePokemonIvMinimum": 97.5,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "MaxSpawnLocationOffset": 0,
  "DelayBetweenPlayerActions": 0,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 96.5,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 3,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 4,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 0,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.5,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 0,
  "MinPokeballsToSnipe": 0,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 0,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{0}_{1}",
  "MaxPokeballsPerPokemon": 0,
  "MaxTravelDistanceInMeters": 600,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 100,
  "UseUltraBallAboveCp": 300,
  "UseMasterBallAboveCp": 0,
  "UseGreatBallAboveIv": 70,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.3,
  "UseMasterBallBelowCatchProbability": 0.09,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 97.5,
  "AutoFavoritePokemon": true,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 25
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 40
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "aerodactyl",
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsToIgnore": [
    "pinsir"
  ],
  "PokemonsTransferFilter": {
    "Mew": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": []
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "dratini",
      "magikarp",
      "eevee",
      "charmander"
    ]
  },
  "PokemonToUseMasterball": null
}

**Comment by burgerbutts** [comment]
Pretty sure its using these settings:

"KeepMinCp": 2000,
"KeepMinIvPercentage": 95.0,

It's honestly not a very good feature. It would be more preferable to have a maximum duplicate option that would automatically transfer the weakest versions of each pokemon.

**Comment by Simpuhl** [comment]
Mine is setup the same way and doesn't do that. I'm using the latest "release" not the current code version

**Comment by Simpuhl** [comment]
"KeepMinOperator": "or", 

WHATS THIS DO???

**Comment by ANR2ME** [comment]
"KeepMinCp": 2000,
"KeepMinIvPercentage": 95.0,
It worked well for latest (0.5) release, it just started to behave strangely on latest commit

**Comment by burgerbutts** [comment]
That's because of this commit: https://github.com/NECROBOTIO/NecroBot/commit/b968fa24fb920deeed3e77dc535761dad832e602

It will deem anything under those values as 'weak' and transfer them.

**Comment by LordDeimos** [comment]
I like the idea, keep the pokedex tidy and clean from crappy pokemon. On my side using last git commit is working without any problems.
But i use:
`"KeepMinCp": 1350,
"KeepMinIvPercentage": 85.0,`

**Comment by ANR2ME** [comment]
But this "weak" thing should be configurable using it's of threshold value isn't? to prevent cleaning up pokemons we wanted to upgrade later

**Comment by Simpuhl** [comment]
It's obviously throwing away pokemon that are better than the current one. It should have tosses the other charmander and slowpoke in this case.

**Comment by ANR2ME** [comment]
Not sure how it sort the transfer list, looks weird to me

**Comment by Simpuhl** [comment]
The charmander and slowpoke it transfered had higher CP and IV.

It may have just transferred recently captured instead of checking everything again before transfer to only do weaker version of duplicate.

**Comment by RichardZhaoE** [comment]
Pokemon are not transferring, my inventory is keeping like two of each. switched back to 5.0. Whatever new transfer they added with these and operators are causing the glitch.

**Comment by theloser** [comment]
This:

> "TransferWeakPokemon": true

transfers all pokemon with less CP than KeepMinCP **OR** perfection less then KeepMinIvPercentage (if PrioritizeIvOverCp is set to true) **OR** which are not favored.

Glad I tested this on my low level account which only had crap :-)

**Comment by burgerbutts** [comment]
I guess it's a good feature if you haven't already setup your config to rid yourself of trash by increasing those values.

My config for non-specific pokemon are:

  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 100.0,
  "KeepMinDuplicatePokemon": 1,

and an example of a pokemon I have setup manually:

    "Dragonite": {
      "KeepMinCp": 2900,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": []
    }

This rids my inventory of all pokemon that aren't one of the very best versions, while keeping at least the minimum count.

This "TransferWeakPokemon" feature could of been handled instead by adding a "KeepMaxDuplicatePokemon" setting that transfers the lowest calculated value based on the "PrioritizeIvOverCp" setting, until the "KeepMinDuplicatePokemon" value is met or "KeepMaxDuplicatePokemon" is less than the current total count.

**Comment by theloser** [comment]
I would prefere the "KeepMaxDuplicatePokemon" a lot more then "TransferWeakPokemon", because "TransferWeakPokemon" will cause a LOT of trouble (and issues full of hate :-))

**Comment by ANR2ME** [comment]
And it's enabled by default, which will probably surprised many people who didn't aware of this config

**Comment by Simpuhl** [comment]
This should not be on by default until people understand it better

**Comment by djdookie** [comment]
It's a bad habit to implement new features and set it to active by default.
Let the ppl decide if they want to try new features! Not everyone is checking the whole new config, especially after autoupdate. ;)

**Comment by alloin** [comment]
![ss 2016-08-02 at 08 00 38](https://cloud.githubusercontent.com/assets/20567055/17339390/fa5c2ee4-58eb-11e6-8b6d-188a04203280.png)
  "KeepMinCp": 1600,
  "KeepMinIvPercentage": 95.0,

**Comment by Energex22** [comment]
AGREED with djdookie

**Comment by Wcidd** [comment]
Will be set to false by default in 0.6.1

**Comment by Simpuhl** [comment]
![image](https://cloud.githubusercontent.com/assets/262571/17339640/a2aef0ea-58a1-11e6-91a1-f13775f8247f.png)

:(

**Comment by jonamur** [comment]
I lost all my rare pokemon to this - not nice - but hey ho we are botting so........
