### ISSUE TITLE
Necrobot w/ Proxy

### ISSUE THREAD

**Issue by boosie212** [NECROBOTIO/NecroBot#2097]
I now know the issue of the repeating "Logging in using Google" error.   I am only able to visit https://pgorelease.nianticlabs.com/plfe/ when using FoxyProxy, but cannot access it when I turn FoxyProxy off.  This is the error I get when running version 0.4.0

![error 0 4 0](https://cloud.githubusercontent.com/assets/20780793/17335678/c5993fa0-58a8-11e6-97f2-b6409686175d.JPG)

This is what I get when running version 0.5.0.

![Uploading Error 0.5.0.JPG…]()

Is there anything I can change in the settings/config/auth files to allow me to run the bot with FoxyProxy turned on as this is the only when I can communicate with the servers.

This is in reference to #1900 open issue ticket.

**Comment by boosie212** [comment]
This is what I get when running version 0.5.0.

![error 0 5 0](https://cloud.githubusercontent.com/assets/20780793/17335844/8d2fdc40-58a9-11e6-9bbf-f2b8de2bfea8.JPG)

**Comment by recon88** [comment]
Please stick to your old ticket.
