### ISSUE TITLE
Bot is not logging

### ISSUE THREAD

**Issue by RichardZhaoE** [NECROBOTIO/NecroBot#2098]
In the recent latest commits, the bot has stopped creating log files. Switched back to 5.0 and it logs perfectly fine.

**Comment by NecronomiconCoding** [comment]
It should save the logs every minute. Are you sure its not working?

**Comment by theloser** [comment]
Confirmed. No more logs. (If i delete the log directory it will be re-created as soon as I start the bot, but no logfiles will be written.)

**Comment by LordDeimos** [comment]
Confirmed also on my end on latest commit, no more log files.

**Comment by Simpuhl** [comment]
Did you let it run for more than a few mins?

**Comment by theloser** [comment]
Jup. Several hours.

**Comment by NecronomiconCoding** [comment]
fixed in https://github.com/NECROBOTIO/NecroBot/commit/4781b914e13816fa6111fd3fd4d0ad9944aedb6f

**Comment by theloser** [comment]
Thanks!
