### ISSUE TITLE
Using Ultra Balls to low lvl Pokemon

### ISSUE THREAD

**Issue by asindkhu** [NECROBOTIO/NecroBot#2101]
after the latest update, it has been using ultra ball to catch any Pokemon if it is available. However my settings are as such;
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 0,
  "UseUltraBallAboveIv": 0,

it worked fine before the update.

**Comment by theloser** [comment]
Check these settings:

>  "UseGreatBallBelowCatchProbability": ?
>  "UseUltraBallBelowCatchProbability": ?

I bet they are wrong.

**Comment by Andrerm124** [comment]
"UseGreatBallAboveIv": 80,
  "UseUltraBallAboveIv": 90,

Should have something like that

**Comment by nfettinger** [comment]
This is not the place for configuration issues. Please use Discord, or reference the wiki.

**Comment by asindkhu** [comment]
"UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
These are wrong? I have kept them unchanged in all previous versions

**Comment by theloser** [comment]
Sorry, my bad, @Andrerm124 is right.
