### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by freezea** [NECROBOTIO/NecroBot#2102]
can someone upload me relase.zip with debug files? i cant compiled

**Comment by nfettinger** [comment]
This is not a developmental issue, Please use Discord and the wiki.

**Comment by davegranlet** [comment]
this is not a issue this is you being lazy, please use the Issues tab for real problems.

**Comment by freezea** [comment]
@nfettinger  yes cunts, this is problem cause i CANT RUN BOT
