### ISSUE TITLE
Fody.1.28.3

### ISSUE THREAD

**Issue by Brumotti** [NECROBOTIO/NecroBot#2103]
please tell me why visual studio shows this error:
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.28.3\build\Fody.targets.	PoGo.NecroBot.CLI	\NecroBot-master\PoGo.NecroBot.CLI\PoGo.NecroBot.CLI.csproj	249

**Comment by nfettinger** [comment]
You need to use Visual Studio 2015 with current .NET support.
This is not an issue with development, please use discord for future help.
