### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by progz** [NECROBOTIO/NecroBot#2104]
Hello,
I don't know why but some of my Pokemon with the best IV are not renamed.

As you can see on the screenshot below, I have got a gyarados IV : 94,88%.
It is not renamed in my Pokemon list. It still with its official French name.

[Screenshot of my Necrobot console](http://hpics.li/7cf8108)
[Screenshot of my Gyarados not renamed](https://thesilphroad.com/research)
[Link yo my config.json](http://pastebin.com/rCn8mTWr)

If you have any questions, just asked :)

Regards,
Adrien

**Comment by nfettinger** [comment]
This is not the place for help issues. Please use discord. I can answer your question there in less than a second.
