### ISSUE TITLE
Suggestion: Kill Bot After Set Time

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#2111]
Would it be possible to have the bot kill itself after a set amount of minutes?

I don't like to overdo it but id love to be able to start it in the morning before I go to work and it stop itself after 3 or 4 hours.

Then when I get home a few hours later start it back up again, or when I go to sleep. This way it kills itself and not stay on all night.

Would be cool to also add the option that if its time to kill the bot but an **incense** or **lucky egg** is still active to continue doing it's thing until it's timer runs out and do pop a new incense or lucky egg

**Comment by recon88** [comment]
Use a batch file for that
