### ISSUE TITLE
TransferWeakPokemon

### ISSUE THREAD

**Issue by Silverarrows1986** [NECROBOTIO/NecroBot#2112]
pls add "TransferWeakPokemon": false,  as default or it will delete like 140 pokemons by start :)

**Comment by askovpen** [comment]
TransferWeakPokemon ignore KeepMinDuplicatePokemon

**Comment by dzik87** [comment]
make it false b default. after latest update it just transfered all my caught pokemons :/

**Comment by dzik87** [comment]
Make if false by default. I have  lost over 100 caught pokemons after recent update ....

**Comment by breakdownbanana** [comment]
Definitely make it false. It transferred all of my pokemon.

**Comment by crush89** [comment]
yeah please make it false as default. By the way, how is "weak" defined?

**Comment by dzik87** [comment]
ihmo pokemon what do not match any other criterias. now it just dont keep weakest one even if there is only one pokemon.

**Comment by RichardZhaoE** [comment]
This new transfer feature is causing the original to bug out. It's keeping 2 or more of every other pokemon even though they are not the best, and they are not particularly listed on any of the filters.

**Comment by wele** [comment]
Damn... it straight transferred everything....

**Comment by breakdownbanana** [comment]
If only we had a bot that could walk around for us and catch everything back ... Oh wait.

**Comment by djdookie** [comment]
Lol, this evil bug, deleting a lot of good pokemons, coming via autoupdate to all running clients, really made it into the release v.0.6.0.... hours after the bug was reported... #2093 
Pretty bad news! :-/

**Comment by dzik87** [comment]
that's the point for ppl who are just updating it is like wasting alot of time :/

**Comment by Chaos2522** [comment]
sent away last copies of many pokemon -> 86% IV 560 CP Squirtle gone and about 100 more, was my highest IV of that group by far

**Comment by Wcidd** [comment]
Will be set to false in 0.6.1
