### ISSUE TITLE
Dump CSV File needs improvement

### ISSUE THREAD

**Issue by Doedelpumpe** [NECROBOTIO/NecroBot#2113]
You can not open the csv file in excel in a descent way. The construction of the csv file is not supported to transfer it into excel with "text to columns".

Can we change it to this form : 

Name,Level,CP,IV,Move1,Move2,Candies
<name>,<level>,<cp>,<iv>,<move1>,<move2>,<candies>
<name>,<level>,<cp>,<iv>,<move1>,<move2>,<candies>
...

I tried to find the creation code in visual studio but didnt find it *blush*

**Comment by markuznw** [comment]
In Libreoffice btw there is no problem, you can reorder with 2 clicks (select column, press the ascending or descending button, press extended) and it will autosort everything for you :P

**Comment by Silverarrows1986** [comment]
openoffice is no problem to open and sort it right

**Comment by theloser** [comment]
Are you using the latest version of the bot? The dump file already has this format:
```
pokemonid,pokemonlevel,cp,perfection,stamina,staminamax,move1,move2,candy,ownername,origin,heightm,weightkg,individualattack,individualdefense,individualstamina,cpmultiplier,battlesattacked,battlesdefended,creationtimems,numupgrades,additionalcpmultiplier,favorite,nickname
Machamp,35,2408,100,148,148,BulletPunchFast,CrossChop,860,,0,1.547057,130,15,15,15,0.5507927,0,0,1468666113935,36,0.2107711,0,100_Machamp
Farfetchd,27,975,100,82,82,CutFast,AerialAce,3,,0,0.7734474,12.53807,15,15,15,0.4431075,0,0,1470101201840,32,0.2510361,0,100_Farfetch
Aerodactyl,20,1237,100,104,104,BiteFast,AncientPower,1,,0,1.375577,53.48305,15,15,15,0.481685,0,0,1470078041457,14,0.1157151,0,100_Aerodact
```
...and it's working pretty well in Excel: "Text to column" and select "Comma" as separator -- done!

**Comment by recon88** [comment]
Already fixed. Will be shipped with next version
