### ISSUE TITLE
ApiFailureStrategy Error

### ISSUE THREAD

**Issue by xiachaolun** [NECROBOTIO/NecroBot#2122]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0535	'ApiFailureStrategy' does not implement interface member 'IApiFailureStrategy.HandleApiFailure(RequestEnvelope, ResponseEnvelope)'	PoGo.NecroBot.Logic	C:\Users\Administrator\Downloads\NecroBot-0.6.0\NecroBot-0.6.0\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs	15	Active

I successfully complied any version before 0.4.0 but when I get into later versions, e.g. 0.5.0 and 0.6.0, I constantly get the same error above.

**Comment by recon88** [comment]
Please follow the Wiki instructions: https://github.com/NECROBOTIO/NecroBot/wiki/Source-Code

**Comment by xiachaolun** [comment]
Of course I have followed this wiki ....

**Comment by recon88** [comment]
Try setting it up again then
