### ISSUE TITLE
[Suggestion] Level > CP or Attack instead of IV or CP

### ISSUE THREAD

**Issue by Menton** [NECROBOTIO/NecroBot#2124]
After studying the list of my pokemons I came to the conclusion, that CP and IV are not the best criteria in order to find the strongest pokemon. Let me explain:

1) First thing I noticed was that pokemon have different levels and that their level is always <= player level. Then I noticed, that pokemon of the same species and same level always have the same maximum CP. For instance in http://prnt.sc/c0qrnx you can see, that all my lvl 27 pidgeotto can have 944 CP at best. However, they actually have a lower CP.

2) When comparing the two pidgeotto with lowest CP you can see, that they only differ in one single thing(excl. IV): one has 806 CP and the other one has 807 CP. This also influences IV, and therefore IV is slightly better for the 807 one. This tendence can be seen easily when comparing with the others as well.

3) As one can see in http://prnt.sc/c0qrkn, two pidgeys with same level and same CP (228) can have different IV. As far as I understand this is due to different attacking abilities. However, again maximum CP is the same, independent of IV (because they are the same lvl).

My conclusion: To find the best pokemon one should care about the pokemon level first, since it defines what CP a pokeman can have at best. The second criteria should be either CP or the attack abilities. Why? Because people who don't want to use their stardust will be interested in having a pokemon with maximum CP (if possible 944/944 for a pidgeotto level 27). However, if a player is going to use his stardust he cares more about the abilities. When he uses his stardust on the pokemon with the best abilities he will end up with the best Pokemon possible. 

I suggest: 
pre lvl 30 Pokemon: Level > CP > Attacks
after having lvl 30 pokemon: Level > Attacks > CP
(of course users should be able to choose between them by themselves)

Why didn't I care about IV? As far as I understand IV is a calculated number based on various things, such as attack ability power and also CP. However, this number is only a fast and easy way to compare 2 pokemon of same species and level in order to determine which one is stronger. While a level 1 pidgey even if it was IV 100% will always be weaker than a level 30 pidgey, IV fails to compare pokemon at different levels. Furthermore, IV will rise when you use stardust on your pokemon as will CP. Meaning that if I compare 2 pidgeotto level 27:
1. has CP 807 but a weaker attack
2. has CP 806 and a stronger attack
Having IV as criteria instead of Attack/CP as I suggested, it will choose one of them depending on whether 1 CP is more important than the different attack abilities. And If they were 810 and 800 the result could be different. So I think that IV is not reliable enough to work as a good criteria for high lvl pokemon.

I hope that one can understand my point. Please tell me if I'm mistaking something.

**Comment by CedricBongaerts** [comment]
I would just recommend adding an option: "TransferPokemonUnderLevel"
This way you filter out all the low pokes that do pass both the IV 'or' CP. 
One more way to filter them out more easily.

**Comment by Simpuhl** [comment]
IV is always the best criteria + move set

CP doesn't matter because you can level them up.

I wish there was a way to change move sets, maybe in future for now I keep all 100 IV regardless of CP

**Comment by tangdami** [comment]
I also agree with @Menton . Stardust is very difficult to accumulate for higher Level pokemons (5000 stardusts for lv 30), why not just save them for even higher level ones? It's always better to catch a higher level pokemons (like > lv 30) then save those precious stardusts later to power up the higher level one with better move set and IV?

**Comment by Menton** [comment]
@CedricBongaerts I do agree, such an option would make it easy to sort out low level pokemon while keeping only higher ones. 

@Simpuhl Maybe you are willing to explain why you think that IV is the best criteria?

@tangdami I totally agree, that is the reason why I would like to give the user a choice between these 2 different criterias. However, as far as I understand pokemon cant go past lvl 30, that is why I suggested this as default.

In general I wanted to point out, that as soon as one can somehow level pokemon, a good IV stat will always be worth keeping, if it remains constant during leveling. However, this is not yet possible and even  if leveling will be a thing, I assume that IV will drop at every level up in order to increase the difficulty to get a perfect pokemon. But this is speculation.
However, for this state of the game I don't yet see why IV is considered "the best" or even "a good" criteria without any other consideration.

**Comment by tangdami** [comment]
To my knowledge IV will be constant even with power up, but the best wild pokemons are having only lv 30 as you mentioned. So it's always a good idea to "catch" wild pokemons with lv 30, then pick ones with better IV or Move sets, then power up them. Because our limited stardusts are not for just one Pokemon, but for a couple of  pokemons. 

Therefore, I never used stardust to power up now, I will wait till I get some Lv 30 ones with better IV (like 90~95% + would be good enough). And for lv 30+ pokemons, each power up consumes more than 5000 stardusts, that's crazy!

Likes like none of current bots have level options. I hope Necro would be the first one.

**Comment by Simpuhl** [comment]
@Menton,

IV is a set #, once the pokemon has it you change change it. They are the rarest to find.

They are the strongest. IF you have a 2000 CP Dragonite with 50% IV and a 2000 one with 100% IV the 2000 one is literally twice as strong.

They are so  rare to find stuff at 100% that I am willing to blow 100k stardust to level something up.

if you want to be a serious Gym competitor, or a serious trainer-to-trainer competitor if and when direct combat gets rolled out, you’ll need to know about IVs.

**Comment by Menton** [comment]
@Simpuhl I did some additional testing and I have to admit that you are right. IV actually determines how close you can get to what was shown as max CP. I definitely misunderstood something, thanks for making this clear to me. 

I thought that by Power Ups one can actually improve IV. Since this was terribly wrong I guess that my suggestion is not really viable. For me it would be okey to remove this post.

**Comment by josephdouce** [comment]
No your suggestion is corrent to some extent Level > IV since IV changes based on type of pokemon its better to filter based on level instead of CP.

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
