### ISSUE TITLE
v0.6.0 wasting greatballs and ultraballs again

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2128]
After 0.6.0 update, the bot agian is wasting my great- and ultraballs.
Possible reason: normal pokeball empty. But I don't want to use better balls instead, because I need them for sniping rares, bot wasting them on commons!

![0 6 0_ball_logic_failure](https://cloud.githubusercontent.com/assets/17240204/17338831/583accee-58e9-11e6-8f74-51e0f1f1dc87.JPG)

My options according ball usage:
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1800,
  "UseMasterBallAboveCp": 2500,
  "UseGreatBallAboveIv": 90,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.15,
  "UseUltraBallBelowCatchProbability": 0.05,
  "UseMasterBallBelowCatchProbability": 0.02

That's crap, pls fix! ;)

**Comment by Dravenfilth** [comment]
you have 0 pokeballs, and 0 great balls.....what else do you want it to use?

**Comment by jasio77** [comment]
To not use better balls for low-tier pokemons. Just ignore them if there isn't any normal pokeballs.

**Comment by djdookie** [comment]
The bot should stop throwing better balls, if the thresholds for balls aren't matached.
We had that behaviour earlier.

**Comment by djdookie** [comment]
Why do you close this thread? It is a new bug!
