### ISSUE TITLE
bot keeps trying to transfer pokemons that are stuck in gyms

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2130]
http://puu.sh/qnoBy/b88e4170ff.png

please see screenshot. kingler and snobilikat are in gyms, hence not transferrable. bot tries to transfer them over and over

**Comment by ChemiHatake** [comment]
I couldn't recreate this bug, Please post your transfer related config and provide more info.

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
