### ISSUE TITLE
Transferred all my pokémon

### ISSUE THREAD

**Issue by tehmushy1** [NECROBOTIO/NecroBot#2135]
Started it up (no problems yesterday, or earlier today), after leaving it for a couple of minutes I came back to see it had transferred all of my pokémon and I was left with only a CP 395 Pikachu it had just caught. 

Is "TransferWeakPokemon" new? Because it was set to 'true' but hadn't transferred anything previously and I didn't notice it before.

**Comment by Energex22** [comment]
Dude freaking learn to read other posts here... there has been so many started..

**Comment by djdookie** [comment]
Thanks on the 4th thread on this. Read first pls!

**Comment by tehmushy1** [comment]
Yeah I just saw it now after posting, I've had the tab open for a while and only just wrote it.
