### ISSUE TITLE
Please return the periodic display of the contents of the bag. it was very convenient.

### ISSUE THREAD

**Issue by bossrus** [NECROBOTIO/NecroBot#2136]
in earlier versions of neсrobot the log displays the contents of the bag. it was convenient. I do not know why you do it removed, but return it, please

**Comment by Energex22** [comment]
Yes it is nice, but i noticed that it was being spammed in version 0.6 or w/e the newest

**Comment by Wcidd** [comment]
This is implemented in 0.6
