### ISSUE TITLE
More Transfer Issues

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#2138]
![image](https://cloud.githubusercontent.com/assets/262571/17339337/40a0e314-58a0-11e6-8135-e2a84e2f66a0.png)

It's transfiguring what it considers the best all of a sudden? 

Just lost like all my top shit :(

**Comment by Energex22** [comment]
Same as my subject and many others posted, have these settings 

"TransferWeakPokemon": false,
  "TransferDuplicatePokemon": false,
  "TransferDuplicatePokemonOnCapture": false,


although mine is still transferring the pokemon

**Comment by djdookie** [comment]
Please join other threads instead of opening new all the time.
