### ISSUE TITLE
Please add random speed (ex: 15-40)

### ISSUE THREAD

**Issue by aliceaia** [NECROBOTIO/NecroBot#2140]
Please add random speed (ex: 15-40). This number will automatically change each time moving to pokestop. Thanks so much.

**Comment by Sylencer90** [comment]
Requested this a while ago, like on 0.3 or sth. Has never been added tho.

**Comment by aliceaia** [comment]
I think this will be better than we move to a fixed rate.

**Comment by RoseFlunder** [comment]
How would you specifiy it? Two settings like:
MinWalkingSpeedInKilometerPerHour
MaxWalkingSpeedInKilometerPerHour
Or do you have another idea?

**Comment by aliceaia** [comment]
@RoseFlunder
Exactly. And the tool will randomly select a number between min - max for each move.

**Comment by ANR2ME** [comment]
Slightly randomize the Altitude would also be nice, together with speed.

**Comment by RoseFlunder** [comment]
Working on
MinWalkingSpeedInKilometerPerHour (default value?)
MaxWalkingSpeedInKilometerPerHour (default value?)
