### ISSUE TITLE
(ERROR) Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..

### ISSUE THREAD

**Issue by k3tzor** [NECROBOTIO/NecroBot#2141]
Hi there, suddenly I'm getting an error while not changed a thing to my computer. 

**(ERROR) Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..**

Already changed my IP, logged out all account from my computer. Tried everything but still it gives me the ERROR. I CAN login to the Pokemon GO app, I CAN do pokestops, CAN do gyms, CAN do everything. Just not the bot anymore.

**Comment by Sylencer90** [comment]
Weird.

Can you post some logs?

**Comment by MrLuisArano** [comment]
How did you change your IP? (also logs would be helpful)

**Comment by k3tzor** [comment]
I don't have any logs anymore because I deleted everything.. This is the most recent log: 
```
[10:44:32] Logging in using Google
[10:44:33] Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..
```

I'm having a dynamic ip trough my service provider, just a reset from my modem and I have a new IP

**Comment by benda95280** [comment]
Same Here.
Ive launched the 5.0 version, get it working for 10 minutes, i've try another time to give a screenshot here, and Working ... :(

**Comment by benda95280** [comment]
And, check on your phone, Pokemon closed, it was still runing in background (new update ?)

**Comment by k3tzor** [comment]
Closed everything on phone etc. Still not working.

**Comment by k3tzor** [comment]
The problem still existsts.. Did a tour with the app, still everything works. Can you guys don't do the "ban" check? And let me just login?
