### ISSUE TITLE
v0.6.0 wasting greatballs and ultraballs again

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2142]
This is #2128 
Why you closed it? It's a bug!

**Comment by RiPPERD** [comment]
its also transfered ALL my bloody pokemon apart from the favourited ones!!! ive lost all pokemon now except a few i had favourited... wtf is going on?

**Comment by recon88** [comment]
@djdookie visit our Discord and ask for configuration help to make sure it's really bug or not: https://discord.gg/VXKxNFr

**Comment by VaanC** [comment]
TransferWeakPokemon=false

**Comment by djdookie** [comment]
Lol it is not the TransferWeakPokemon issue ^^
