### ISSUE TITLE
Newest Version 0.6.0

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2143]
Why when I download the newest version which is 0.6.0 it says this:
http://i.imgur.com/HhCcwo8.png

**Comment by aliceaia** [comment]
Maybe the author forgot to change the version number.

**Comment by ObsessedHacker** [comment]
@aliceaia what do you mean "maybe"? download the 0.6.0 version and see for yourself!

**Comment by Sylencer90** [comment]
Yeah happens to me too, obviously some1 forget to change the version number. No big deal.

**Comment by aliceaia** [comment]
@ObsessedHacker
I also received a similar notice, but the tool is still operating normally

**Comment by morrrido** [comment]
The new version (0.6.0) transfered dozens of my pokemons for no reason including two Mr.Mimes I had... seriously...

**Comment by ultiferrago** [comment]
Mine too. Including my wartortle, which I had 97 candies for....

**Comment by MASSV** [comment]
Also started my bot and did not notice updating, trasfered 150 pokes, some of which i wanted...wtf

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
