### ISSUE TITLE
Bot refuses to acknowledge "UseLuckyEggsWhileEvolving"

### ISSUE THREAD

**Issue by BennettStaley** [NECROBOTIO/NecroBot#2145]
I've tried toggling all the evolve command mentions but now the bot doesn't display the X out of Y for evolves noted at **"UseLuckyEggsMinPokemonAmount"** and simply evolves whenever it hits the maximum defined at **"EvolveKeptPokemonsAtStorageUsagePercentage"** WITHOUT using a lucky egg.

Whereas previous versions the **"UseLuckyEggsMinPokemonAmount"** would override the other command.

Intentional?

**Comment by BennettStaley** [comment]
Noting that this was not fixed in 6.1

**Comment by Menton** [comment]
About the lucky egg thing: have you ever actually logged into this account on a phone/bluestacks? I made the experience that the bot is unable to use lucky eggs if it was never logged into the account. 

About the other thing: I'm experiencing the same issue and I don't have any solution to it.

**Comment by BennettStaley** [comment]
Yep. Definitely logged in. noticed that was happening yesterday. @Menton

**Comment by Wcidd** [comment]
If this is still an issue in 0.6.3 please reopen a ticket
