### ISSUE TITLE
Transferred the best / only one pokemons

### ISSUE THREAD

**Issue by jbanaszczyk** [NECROBOTIO/NecroBot#2146]
New version 0.6 - suddenly started transferring pokemons.
Some very stong, some onlu ones (Gyarados, Venusaur, Aerodactyl and so on)

Machop              CP:   42            IV: 48.22% [Best CP: 615                IV: 52.91%] (Candies: 37)
Poliwag             CP:  254            IV: 44.39% [Best CP: 519                IV: 51.29%] (Candies: 27)
Gastly              CP:  258            IV: 47.61% [Best CP: 258                IV: 47.61%] (Candies: 13)
Ninetales           CP:  267            IV: 38.81% [Best CP: 29                 IV: 74.21%] (Candies: 33)
Charmander          CP:  372            IV: 14.62% [Best CP: 372                IV: 14.62%] (Candies: 12)
Bellsprout          CP:  418            IV: 42.87% [Best CP: 418                IV: 42.87%] (Candies: 86)
Pinsir              CP:  421            IV: 24.07% [Best CP: 1555               IV: 91.50%] (Candies: 74)
NidoranF            CP:  443            IV: 34.12% [Best CP: 443                IV: 34.12%] (Candies: 77)
Nidoking            CP:  461            IV: 69.03% [Best CP: 1586               IV: 83.02%] (Candies: 9)
Bulbasaur           CP:  484            IV: 44.81% [Best CP: 484                IV: 44.81%] (Candies: 58)
Poliwag             CP:  519            IV: 51.29% [Best CP: 519                IV: 51.29%] (Candies: 27)
Gastly              CP:  541            IV: 63.53% [Best CP: 258                IV: 47.61%] (Candies: 13)
Eevee               CP:  544            IV: 68.16% [Best CP: 545                IV: 68.71%] (Candies: 154)
NidoranM            CP:  559            IV: 42.38% [Best CP: 499                IV: 59.48%] (Candies: 9)
Oddish              CP:  573            IV: 62.04% [Best CP: 603                IV:  5.56%] (Candies: 77)
Machop              CP:  615            IV: 52.91% [Best CP: 615                IV: 52.91%] (Candies: 37)
Electrode           CP:  680            IV: 16.50% [Best CP: 680                IV: 16.50%] (Candies: 43)
Farfetchd           CP:  696            IV: 59.35% [Best CP: 696                IV: 59.35%] (Candies: 28)
Cloyster            CP:  709            IV: 57.47% [Best CP: 709                IV: 57.47%] (Candies: 42)
Nidoking            CP:  726            IV: 54.37% [Best CP: 1586               IV: 83.02%] (Candies: 11)
Hitmonchan          CP:  748            IV: 78.74% [Best CP: 748                IV: 78.74%] (Candies: 16)
Beedrill            CP:  841            IV: 40.96% [Best CP: 841                IV: 40.96%] (Candies: 21)
Dodrio              CP:  862            IV: 48.74% [Best CP: 862                IV: 48.74%] (Candies: 7)
Butterfree          CP:  870            IV: 31.72% [Best CP: 870                IV: 31.72%] (Candies: 9)
Magmar              CP:  882            IV: 40.70% [Best CP: 882                IV: 40.70%] (Candies: 32)
Tangela             CP:  888            IV: 65.59% [Best CP: 888                IV: 65.59%] (Candies: 16)
Golbat              CP:  901            IV: 78.92% [Best CP: 1085               IV: 92.90%] (Candies: 18)
Weezing             CP:  922            IV: 72.01% [Best CP: 922                IV: 72.01%] (Candies: 50)
Parasect            CP:  957            IV: 76.53% [Best CP: 957                IV: 76.53%] (Candies: 37)
Sandslash           CP: 1007            IV: 84.67% [Best CP: 1007               IV: 84.67%] (Candies: 7)
Clefable            CP: 1032            IV: 60.54% [Best CP: 1032               IV: 60.54%] (Candies: 15)
Raticate            CP: 1044            IV: 49.37% [Best CP: 1044               IV: 49.37%] (Candies: 20)
Rhydon              CP: 1093            IV: 83.71% [Best CP: 366                IV: 92.48%] (Candies: 32)
Primeape            CP: 1204            IV: 42.85% [Best CP: 1204               IV: 42.85%] (Candies: 46)
Scyther             CP: 1214            IV: 56.87% [Best CP: 1214               IV: 56.87%] (Candies: 20)
Lapras              CP: 1215            IV: 63.97% [Best CP: 1936               IV: 91.36%] (Candies: 53)
Dewgong             CP: 1220            IV: 13.89% [Best CP: 1189               IV: 80.74%] (Candies: 35)
Raichu              CP: 1233            IV: 54.09% [Best CP: 1233               IV: 54.09%] (Candies: 48)
Lickitung           CP: 1239            IV: 73.30% [Best CP: 986                IV: 80.40%] (Candies: 35)
Gengar              CP: 1251            IV: 73.99% [Best CP: 1123               IV: 97.17%] (Candies: 12)
Jolteon             CP: 1253            IV: 56.59% [Best CP: 1406               IV: 86.70%] (Candies: 155)
Electabuzz          CP: 1262            IV: 40.85% [Best CP: 1387               IV: 47.38%] (Candies: 130)
Scyther             CP: 1266            IV: 31.17% [Best CP: 1214               IV: 56.87%] (Candies: 19)
Arbok               CP: 1271            IV: 60.76% [Best CP: 1271               IV: 60.76%] (Candies: 9)
Tauros              CP: 1329            IV: 60.91% [Best CP: 1329               IV: 60.91%] (Candies: 24)
Kangaskhan          CP: 1345            IV: 75.18% [Best CP: 1345               IV: 75.18%] (Candies: 6)
Electabuzz          CP: 1362            IV: 25.94% [Best CP: 1387               IV: 47.38%] (Candies: 130)
Raichu              CP: 1376            IV: 47.03% [Best CP: 1233               IV: 54.09%] (Candies: 47)
Pidgeot             CP: 1405            IV: 62.18% [Best CP: 1409               IV: 63.96%] (Candies: 6)
Jolteon             CP: 1406            IV: 86.70% [Best CP: 1406               IV: 86.70%] (Candies: 158)
Rapidash            CP: 1410            IV: 84.71% [Best CP: 1240               IV: 91.60%] (Candies: 13)
Hypno               CP: 1419            IV: 79.15% [Best CP: 1235               IV: 93.28%] (Candies: 12)
Tentacruel          CP: 1479            IV: 56.21% [Best CP: 1479               IV: 56.21%] (Candies: 18)
Venusaur            CP: 1485            IV: 13.14% [Best CP: 1623               IV: 16.37%] (Candies: 59)
Charizard           CP: 1494            IV: 39.36% [Best CP: 1494               IV: 39.36%] (Candies: 13)
Golduck             CP: 1518            IV: 26.38% [Best CP: 1563               IV: 44.01%] (Candies: 19)
Aerodactyl          CP: 1558            IV: 79.81% [Best CP: 1558               IV: 79.81%] (Candies: 32)
Golduck             CP: 1563            IV: 44.01% [Best CP: 1563               IV: 44.01%] (Candies: 20)
Flareon             CP: 1610            IV: 49.53% [Best CP: 2228               IV: 100.00%](Candies: 155)
Dragonite           CP: 1618            IV: 61.38% [Best CP: 2442               IV: 81.51%] (Candies: 18)
Venusaur            CP: 1623            IV: 16.37% [Best CP: 1623               IV: 16.37%] (Candies: 59)
Machamp             CP: 1633            IV: 70.75% [Best CP: 1755               IV: 62.86%] (Candies: 34)
Slowbro             CP: 1658            IV: 51.60% [Best CP: 1539               IV: 91.59%] (Candies: 40)
Machamp             CP: 1666            IV: 55.54% [Best CP: 1755               IV: 62.86%] (Candies: 34)
Gyarados            CP: 1715            IV: 79.06% [Best CP: 1715               IV: 79.06%] (Candies: 124)

**Comment by Sylencer90** [comment]
"TransferWeakPokemon": false,

**Comment by recon88** [comment]
Please check the closed tickets before opening a new one.
