### ISSUE TITLE
Transferred most of my pokemon, regardless of my max CP threshold

### ISSUE THREAD

**Issue by destroyhumns** [NECROBOTIO/NecroBot#2149]
"KeepMinCp": 1750,
"PrioritizeIvOverCp": false,

Regardless of these settings, it still transferred almost all of my pokemon. Not sure what the problem here is. Also, it is using ultra balls, then great balls, THEN pokeballs.

**Comment by nfettinger** [comment]
Upgrade your config.json to the newest version, then try again.

**Comment by VaanC** [comment]
TransferWeakPokemon=false ....

**Comment by Sylencer90** [comment]
"TransferWeakPokemon": false,

I do recommend to put PrioritizeIVOverCp on true as well.

**Comment by Fluxona** [comment]
Same.. PrioritizeIVoverCP was on. did not see the config update so as soon as i restarted it, it transferred ALL my pokemon, including rares and high cp's and only kept the ones with 90+ iv..

**Comment by Fluxona** [comment]
does TransferWeakPokemon really solve this problem? because I tried on another one before restarting and it did the exact same thing
