### ISSUE TITLE
New Update Caused All Pokemon to Transfer

### ISSUE THREAD

**Issue by nomadskid** [NECROBOTIO/NecroBot#2153]
Previously, the bot was set up to discard all pokemon except for the highest CP. However, after update 25 minutes ago, it decided to get rid of everything. Snorlax, Lapras, Tauros, Blastoise, Charizard. All over 1500 CP. How do I prevent this from happening again?

**Comment by recon88** [comment]
Read the closed Tickets please.

**Comment by eryen** [comment]
"KeepMinIvPercentage": 90.0,
what da heck this works for
