### ISSUE TITLE
v0.6 transfer all high Ev lvl pokemons

### ISSUE THREAD

**Issue by eryen** [NECROBOTIO/NecroBot#2154]
I just updated to 0.6 and bot transfered all my perfect lvl more than %90.

100 pokemons with %97 perfect lvl pokemons wasted

**Comment by recon88** [comment]
Read the closed Tickets please.

**Comment by blubukirsten** [comment]
Instead of wait for 0.6.1, I would recommend to stop the distribution of 0.6.0 now, thus guys who not yet upgrade will not affect by this issue.

**Comment by alpadev** [comment]
Enabling this by default is really awkward. One would have no clue such thing would happen after upgrading.
Also what is considered weak? It also dropped a 100% Traumato.

**Comment by recon88** [comment]
Will be changed in 0.6.1
