### ISSUE TITLE
Latest version recycled all my pokeballs

### ISSUE THREAD

**Issue by simonwicks** [NECROBOTIO/NecroBot#2156]
<img width="659" alt="screen shot 2016-08-02 at 19 20 10" src="https://cloud.githubusercontent.com/assets/5250062/17340067/91bf508c-58e6-11e6-8b87-86d866d0769c.png">

"TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 10,
  "TotalAmountOfRevivesToKeep": 10,
  "TotalAmountOfBerriesToKeep": 70,

**Comment by nguyennk** [comment]
Yup ... cause ur total pokeball is exceed what you set -- 120

You have 81 poke + 123 great = 204 ball total so it will get rid of 81 poke + 3 great --> you have 120 great ball left

**Comment by AMigone2** [comment]
It transferd almost all my pokemon....

**Comment by simonwicks** [comment]
> Yup ... cause ur total pokeball is exceed what you set -- 120

You have 81 poke + 123 great = 204 ball total so it will get rid of 81 poke + 3 great --> you have 120 great ball left

> 

Ok, I misunderstood how it worked. Thanks!
