### ISSUE TITLE
New version did not transfer keep Pokeballs value

### ISSUE THREAD

**Issue by JSBeard** [NECROBOTIO/NecroBot#2160]
Check it before you launch. 390 great balls and 150 ultra balls just went poof because it reverted to a value of 120.

**Comment by Simpuhl** [comment]
Noticed this also, I had to reset all that

**Comment by JSBeard** [comment]
Assuming it is in part due to the spelling correction of "Pokebals" to "Pokeballs" in that line. All ofor my other configs moved over

**Comment by Chaos2522** [comment]
Wow, i didnt notice until now, the bot itself showed false values -> let me believe i had over 400 ultraballs and 200 pokeballs 150 greatballs left. in fact i lost all but 118 ultra + 2 pokeballs :/

**Comment by JSBeard** [comment]
Are you sure it did that, or did it show your inventory and then recycle?

**Comment by Chaos2522** [comment]
Is showing the correct values now (had to restart the bot) up until now it displayed false values after it caught a pokemon -> with pokeball (201 left) while in fact i had only 2 remaining

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
