### ISSUE TITLE
[BUG] PrioritizeIvOverCp

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2161]
"KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 100.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

![iv](https://cloud.githubusercontent.com/assets/20729182/17340237/a7c42aa2-58ef-11e6-9df7-23aa3f6ef6ed.png)

**Comment by Fluxona** [comment]
same problem here. even though I put transferweakpokemon:false..

**Comment by eryen** [comment]
"KeepMinIvPercentage": 90.0,
bot f*cked all pokemons at once

**Comment by ilya-olkhovskij** [comment]
Everyone have that bug. KeepMinDuplicatePokemon seems like not working too.

`[21:28:43] (TRANSFERED) Spearow  (CP:275|IV:76.02%) [Best CP: (CP:275|IV:76.02%)] Candies: 1016`

**Comment by noodle-** [comment]
> "TransferWeakPokemon": true,

see https://github.com/NECROBOTIO/NecroBot/issues/2112 and https://github.com/NECROBOTIO/NecroBot/issues/2093

**Comment by eryen** [comment]
thia is not the answer
we have an option for keep high perfect lvl pokemons
 "KeepMinIvPercentage": 90.0,

**Comment by opixboyz** [comment]
yeah me too. lots of my pokemon collection poof missing transfered lol

**Comment by ilya-olkhovskij** [comment]
Use "TransferWeakPokemon": false,

**Comment by Sylencer90** [comment]
"KeepMinCp": 1500,
"KeepMinIvPercentage": 100.0,
"KeepMinOperator": "and",  <- what is this? That means it will ONLY keep them when BOTH requirements (CP AND IV) are filled.

**Comment by ilya-olkhovskij** [comment]
> <- what is this? That means it will ONLY keep them when BOTH requirements (CP AND IV) are filled.

Yes.

**Comment by opixboyz** [comment]
Use "TransferWeakPokemon": false, i change it now but it seems my bot won't transfer weak pokemon with low cp n iv and it will make my inventory pokemon full..

**Comment by Simpuhl** [comment]
Many of these I only had 1 of, they where also the highest IV

GONE..

It didn't even keep the "1"

![image](https://cloud.githubusercontent.com/assets/262571/17340611/cd9739a8-58a5-11e6-9f11-00aaf4d64b06.png)

**Comment by SDMU** [comment]
luckily i stopped the the .exe when i noticed the increasing amount of tranfers

**Comment by recon88** [comment]
Please update to 0.6.1 and make a new Ticket if that's still an issue.
