### ISSUE TITLE
LevelUpByCPorIv

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2163]
How is working now this? Before I set:
"UpgradePokemonIvMinimum": 95.0,
"LevelUpByCPorIv": "iv",

Now, we have:   "UpgradePokemonMinimumStatsOperator": "and"

So for what we need  "LevelUpByCPorIv": "iv",? And how to set upgrade pokemony only by IV not CP?

**Comment by cwirek91** [comment]
smh like that?   "UpgradePokemonCpMinimum": 5000.0,

**Comment by Simpuhl** [comment]
change the and to or

should fix issue

My pokemon still aren't being upgraded tho, can't figure out why.

Does it have anything to do with the upgradeloop setting?

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
