### ISSUE TITLE
Bot ignores "TotalAmountOfBerriesToKeep"

### ISSUE THREAD

**Issue by TeachMeSenpai** [NECROBOTIO/NecroBot#2164]
It keeps everything recycle and optimized but berry count keeps rising and it does not recycle...

Is it just me or bug overall?

**Comment by eLyiN** [comment]
Same

**Comment by RoseFlunder** [comment]
Should fix: [https://github.com/NECROBOTIO/NecroBot/pull/2246](url)

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
