### ISSUE TITLE
Updated transfer all pokemon 

### ISSUE THREAD

**Issue by patgoins** [NECROBOTIO/NecroBot#2168]
had autoupdate on.... Ran the bot for about 5 mins and next thing I know it starts to transfer all my pokemon regardless of CP/IV or anything. 

![screenshot_8_2_16__1_34_pm](https://cloud.githubusercontent.com/assets/6116663/17340759/37998d36-58b7-11e6-8041-80cd1f26d2ab.jpg)

**Comment by m3ct0n** [comment]
"TransferWeakPokemon" switch to false

**Comment by Caliboss** [comment]
same thing just happened to me :( so sad to see my dragonite gone.. luckily i stopped it before it got garados

**Comment by recon88** [comment]
Use 0.6.1
