### ISSUE TITLE
Updated to version 6 and it transferred almost all my pokemon :(

### ISSUE THREAD

**Issue by Caliboss** [NECROBOTIO/NecroBot#2169]
i updated to version 6 and luckily i was on the game with my phone.. i saw it transferring all my good high cp pokemon. i shut the bot off after i saw what it said on the screen it was transferring like kadabra cp 588, highest cp caught 588.  so it was transferring the ones i wanted to keep basically.

i just turned auto update off because it was working fine for over 10 hours with no errors and doing exactly what i wanted it to do.. after i figured out how it evolves pokemon @ .9 and the correct pokeball transfer settings. so i feel more secure  i took the old config from version 5 and put it in the folder that was just updated =/

**Comment by deathart** [comment]
Me too I still have 6 ( diferent on your account)

**Comment by RinneganMadara** [comment]
There's a new command that transfers weak pokemon. The default is set to true (for no logical reason), on top of ignoring any IV percentages set by other settings.

**Comment by recon88** [comment]
0.6.1 fixes that.

**Comment by theloser** [comment]
Turn AutoUpdate off.
Update manually.
Save your old config somewhere save.
Start Bot, it creates a default config.
Read the config.
Read it again.
Read it again until you understand everything.
If you dont understand an option, go to the discord channel and ask for help.
Change the config to your needs.
Start the bot with the new config on a test account.
If everything works as expected. copy the new config to your other accounts.
No more bad surprises.

You're welcome :-)
