### ISSUE TITLE
Transfer broken

### ISSUE THREAD

**Issue by notaslave2u** [NECROBOTIO/NecroBot#2170]
Rather than keeping one of each pokemon the way it is set, the CP of each pokemon, or keeping by the IV I set, it just started transferring everything, so I have 25 of the 116 caught left now. Luckily I caught it before it sent off those too.

**Comment by Razzzle** [comment]
Has been reported as a bug, implemented a new feature and this has now been rectified in 0.6.1 please update.

https://github.com/NECROBOTIO/NecroBot/pull/2126
