### ISSUE TITLE
0.6.0 - Not transfering pokemons while having evolve enabled

### ISSUE THREAD

**Issue by dzik87** [NECROBOTIO/NecroBot#2174]
Even with KeepWeakest to false it does not transfer pokemons what can be used to gain candys. I have list of low pokemons to evolve and in 0.5.0 it was sending some of them if havent got enough candys. Now it keeps them all. I reversed for test to 0.5.0 where it properly calculate it and transfer over pokemons what we cannot evolve. New option to KeepWeakestPokemon seems like broke all bot logic. Cheers.

**Comment by recon88** [comment]
#2187
