### ISSUE TITLE
Not ignoring pokemons on ignorelist

### ISSUE THREAD

**Issue by Westermark** [NECROBOTIO/NecroBot#2176]
so i here is my CFG, I got almost all pokemons on ignorelist, and still it catches caterpie, zubats and shit.

https://gyazo.com/769bbf5ed37bfd03f7c758d2c3cd5997

https://gyazo.com/9ead5fc0e5fff40db57734a2c89b13bd
https://gyazo.com/fea6fdabb18320bb1a0bfd4d3e558efd
https://gyazo.com/3bbf384740abcdd511202b5b13706d02
https://gyazo.com/0334332905aecac4e5f96cb8c794fc3a
https://gyazo.com/1dc88db0d2e1e0f7d8041d8970cae55f
https://gyazo.com/5cf6e0862f373cb118a2a9cc54d3789b
https://gyazo.com/7d9cd5e7379f0ff6e3718b375111fea7
https://gyazo.com/66f79c4969404b9522daa349c1eaaf41
https://gyazo.com/f87c8b02329dc71f9e8584a89dc15580
https://gyazo.com/c13b4cbefdae5df50580dff745d746e2

It wouldnt let me attach my CFG, So i made a gyazo story of it... :O

**Comment by eLyiN** [comment]
Also it's keeping the pokemon that can evolve without set up in Config, if i'm not wrong...

**Comment by nfettinger** [comment]
It sounds like he is complaining that the logic tries to catch those pokemon instead of ignoring them and not using balls on them.

**Comment by Westermark** [comment]
The thing im complaning about is that i put all pokemons on ignore list, except dragonite, arcanine, snorlax, lapras and such pokemons. still my bot catches weedles, catherpies, pidges and so on.

**Comment by Marsinator** [comment]
please use pastebin.com for your config

and mention the version of the bot you are running.

**Comment by Westermark** [comment]
http://pastebin.com/bdpexxeq

Version 0.6.0

**Comment by Westermark** [comment]
I updated my bot to 0.6.3 and the problem still persists. 
https://i.gyazo.com/thumb/1200/_bda39c90f7ae85410efc8fbd9341a8d9-png.jpg

I will be more specific this time. I only want the bot to catch the pokemons that gets reported from the feeder, I dont want it to catch other random pokemons meanwhile its waiting for a sniping target.

i remade the config some so ill attach it once again so you guys could se if i did anything wrong again.
http://pastebin.com/XEhCK6Nq

**Comment by Marsinator** [comment]
devs?
