### ISSUE TITLE
[BUG] Using Pokeball better than should

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2177]
"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,

![ultraball](https://cloud.githubusercontent.com/assets/20729182/17341256/031d1e3c-58f4-11e6-9aa4-79bfba688f6f.png)

**Comment by manu23100** [comment]
Same here.What's happening?

**Comment by somani6** [comment]
works fine for me, but i have all Probability values down to 0.0 so the never apply... i'll test it

**Comment by djdookie** [comment]
I have a similar problem that the bot uses greatballs and ultraballs when normal pokeballs are empty, even with thresholds like above. The bot should never be allowed to do that, or it should be configurable. Don't catch crappy pokemons with your best balls! ;)

**Comment by Kostronor** [comment]
I found the problem, this fixes it:

```
  "UseGreatBallBelowCatchProbability": 0.02,
  "UseUltraBallBelowCatchProbability": 0.01,
  "UseMasterBallBelowCatchProbability": 0.005,
```

**Comment by djdookie** [comment]
Going down to lower probabilities fixed it? Sounds weired and unintended. Still a bug that must be fixed, if you ask me. ;)

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.

**Comment by Kostronor** [comment]
The thing is, it is not 0..100 but 0..1 so having it greater 1 will always use the ball. My current settings seen above are 20% 10% 5%

@simplyphp the bug would be that config defaults are too high. Should I open a new issue or reopen this one?

**Comment by djdookie** [comment]
True, you define probabilities with a double value between 0 to 1. But I never saw different default values. Right now, they are correct at 0.2, 0.1, 0.05. Same for the op, see above. Possibly you misconfigured that in your own config?

**Comment by djdookie** [comment]
I checked the code. Bot takes better balls if normals are empty. Right now it's intended and not configurable.

**Comment by djdookie** [comment]
I guess at the screenshot from op, pokeballs and greatballs are just empty. Then bot uses ultraballs for everything.
