### ISSUE TITLE
Can someone please share their sniper setting with me?

### ISSUE THREAD

**Issue by jonsnowwatch** [NECROBOTIO/NecroBot#2179]
following is mine:

"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 200,
  "MinPokeballsWhileSnipe": 100,
  "MinDelayBetweenSnipes": 1000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,

I have 300+ pokeballs. But not matter how I change these values, my sniper havent worked since v4.0.....

guys please help :/

**Comment by Simpuhl** [comment]
Did you set all the locations to be near your main starting location?

**Comment by jonsnowwatch** [comment]
starting point is in San francisco. however I'm pretty much blind since pokevision is down... Was hoping this online sniper server can help me, but it didnt work = =
