### ISSUE TITLE
Bot only use ultraball

### ISSUE THREAD

**Issue by manu23100** [NECROBOTIO/NecroBot#2180]
Since the new update necrobot only catch pokemon with ultraball while the config is prepared to catch with pokeballs,can anyone help me? thanks.

**Comment by somani6** [comment]
check the following values:

  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1200,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 90,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,

**Comment by recon88** [comment]
Also duplicate #2177
