### ISSUE TITLE
[BUG] UseLuckyEggsMinPokemonAmount

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2181]
"UseLuckyEggsMinPokemonAmount": 15,
![evolve](https://cloud.githubusercontent.com/assets/20729182/17341413/c28790f4-58f4-11e6-8899-33c82a99bc8e.png)

**Comment by JayRabxx** [comment]
Lower your value on this line:
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
