### ISSUE TITLE
Pokemon dump file very hard to read

### ISSUE THREAD

**Issue by Briskey** [NECROBOTIO/NecroBot#2183]
The new pokemon list dump file has a lot more info in it, which is awesome, but there is no format which makes it extremely hard to read.. example: [https://gyazo.com/7d9465925c7714725200f0fdc43894ee](url) The old dump file system looked MUCH cleaner.

**Comment by recon88** [comment]
You are supposed to import it into Excel or w/e you prefer and let that program format it for you
