### ISSUE TITLE
[BUG] TransferDuplicatePokemon

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2184]
"KeepMinCp": 0,
  "KeepMinIvPercentage": 100.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "PokemonsNotToTransfer": [],

Dosnt transfer any Pokemons.

**Comment by recon88** [comment]
Please ask for configuration help on our Discord: https://discord.gg/VXKxNFr
