### ISSUE TITLE
KeepMinCP not always working

### ISSUE THREAD

**Issue by eternalflamez** [NECROBOTIO/NecroBot#2185]
The bot transferred a Magmar after catching it, even though it should have kept it according to my settings.
Bot text: (TRANSFERED) Magmar  - CP: 1349  IV: 66.15%   [Best CP: 1272  IV: 89.00%] 

Relevant settings:
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 90.0,

**Comment by cwirek91** [comment]
set:
  "TransferWeakPokemon": false,

**Comment by eternalflamez** [comment]
That was a quick reply! Thanks! By the way this feature is not listed on the wiki (yet).
