### ISSUE TITLE
0.6.1 - Crash on Startup: Exceptiion caught, writing LogBuffer. System.ArgumentNullException

### ISSUE THREAD

**Issue by Bam30** [NECROBOTIO/NecroBot#2188]
Since Update
![clipboard03](https://cloud.githubusercontent.com/assets/20801581/17341865/e936b6d8-58f6-11e6-9719-78210e076143.jpg)

**Comment by recon88** [comment]
Try deleting config folder and start again

**Comment by Bam30** [comment]
Thanks works again!
