### ISSUE TITLE
  "MinDelayBetweenSnipes": 60000,

### ISSUE THREAD

**Issue by vipery** [NECROBOTIO/NecroBot#2189]
In last compiled version 0.6.0 with PogoFeeder teleport like a hell between without delay. I think is not work properly. I want decrease jump to 1 min, dont want teleport every 3-5 sec

**Comment by recon88** [comment]
Not sure but I think the delay is for manual sniping, not for pogofeeder sniping.

**Comment by vipery** [comment]
How i can increase delay? My xp / hour has increased doable, after updating from 0.5.0 to 0.6.0.

**Comment by recon88** [comment]
What's wrong about having more xp/hour? :D

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
