### ISSUE TITLE
0.6.1 transferring duplicates bugged

### ISSUE THREAD

**Issue by derek0309** [NECROBOTIO/NecroBot#2190]
"KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 91.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

i have 10+ zubat widdle etc. not transferring at all, thanks

**Comment by recon88** [comment]
Please ask for configuration help on our Discord: https://discord.gg/VXKxNFr

**Comment by somani6** [comment]
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0, Lower this value i guess
