### ISSUE TITLE
6.1 did not fix 2 step authorization

### ISSUE THREAD

**Issue by Azrielexen** [NECROBOTIO/NecroBot#2191]
2 Step Authorization is not even turned on in my gmail settings. My email is connected to my university login but they share the same username and password. Even replacing the google password in the config file with the app password generator doesn't help with this error.

**Comment by NecronomiconCoding** [comment]
educational Accounts are currently not handled by GPSOAuth. I am sorry :cry:

**Comment by Azrielexen** [comment]
Ah that is extremely unfortunate, it used to handle it just fine! Any word on when they might start handling it?
