### ISSUE TITLE
Upgrade / Level Up

### ISSUE THREAD

**Issue by AllUpps** [NECROBOTIO/NecroBot#2193]
I want to upgrade all pkmn with iv = 100 
But it just does nothing.

settings:
 "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 100,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 100.0,
  "UpgradePokemonMinimumStatsOperator": "and",

**Comment by cwirek91** [comment]
I get:

  "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 10000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 5000.0,
  "UpgradePokemonIvMinimum": 100.0,
  "UpgradePokemonMinimumStatsOperator": "or",

And same not working..

**Comment by recon88** [comment]
Please visit our Discord for configuration questions: https://discord.gg/VXKxNFr

**Comment by AllUpps** [comment]
its not a config problem. it just doeent work by "UpgradePokemonIvMinimum": 100.0,

**Comment by Marsinator** [comment]
#2334
