### ISSUE TITLE
Update failure / language not working

### ISSUE THREAD

**Issue by roflinger** [NECROBOTIO/NecroBot#2196]
[21:30:50] (UPDATE) Perfect! You already have the newest Version 0.5.0

I use 0.6.1 

flag "de" also not working for german language

  "TranslationLanguageCode": "de",
  "AutoUpdate": true,

**Comment by BlauDev** [comment]
>flag "de" also not working for german language

The v0.6.1 zip file doesn't have the "Translations" folder inside "Config". Download the v0.6.0 zip and copy the missing folder from it.

**Comment by roflinger** [comment]
oh i see thx, but what about the 

"21:30:50 Perfect! You already have the newest Version 0.5.0" ? any idea? it´s since 0.5.0 it also didn´t update to 060

**Comment by BlauDev** [comment]
It's a problem with the the way the version is checked

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
