### ISSUE TITLE
Bot worked, but now can't launch

### ISSUE THREAD

**Issue by JSBeard** [NECROBOTIO/NecroBot#2198]
![20160802_123032](https://cloud.githubusercontent.com/assets/20742740/17342286/6a7a95a6-58ad-11e6-90ce-b8cdcb460ad8.png)
Screenshot is the error I get on launch. Worked originally, but not anymore.

**Comment by recon88** [comment]
There's an error in your config. Delete config folder and let it create new files.

**Comment by JSBeard** [comment]
@recon88 any way to determine where the error is? Deleted config, reopened and reestablished it and getting the same error.

**Comment by recon88** [comment]
Quite hard. Check auth file as well.
Did you put " " around your name and password?

**Comment by JSBeard** [comment]
Yes, reran config again. Seems to be something in the Pokémon to evolve list but I didn't change those before getting the error the first time. Drawing that conclusion because it is the only thing I didn't reconfigure a second time. (Pain in the ass on remote desktop). Did any of the Pokémon reference names between this version and the last?

**Comment by recon88** [comment]
Can you post the erroring config please to pastebin and give me the link to it?

**Comment by JSBeard** [comment]
Got it. I'd seen the change of NidoranMale and NidoranFemale to NidoranM and NidoranF so thought that the reference had changed and changed it in my config to match. Weird that I ran it like 3 or 4 times after that change without issue.
