### ISSUE TITLE
Suggestion: delay between catching pokemon via manual sniping

### ISSUE THREAD

**Issue by Briskey** [NECROBOTIO/NecroBot#2199]
Currently, the bot only catches pokemon via manual sniping once every ~3-6 seconds or so.  As seen here: [https://gyazo.com/39633753a626653ae6007c374bc9a1ac](url).  A configurable option to decrease this delay would drastically increase exp, if it's possible.  If not, it's cool, thanks for the amazing bot Necro and crew!

**Comment by recon88** [comment]
Could you try DelayBetweenPokemonCatch ?

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
