### ISSUE TITLE
[BUG] TransferDuplicatePokemon

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2202]
"KeepMinCp": 5000,
"KeepMinIvPercentage": 99.9,
"KeepMinOperator": "or",
"PrioritizeIvOverCp": true,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,
"PokemonsNotToTransfer": [],

Dosnt transfer any Pokemons.

**Comment by recon88** [comment]
#2187
