### ISSUE TITLE
TransferDuplicatePokemonOnCapture transfers Pokemon while encountering/catching other Pkmn

### ISSUE THREAD

**Issue by KuschelCore** [NECROBOTIO/NecroBot#2205]
This seems wrong to me. A human can't transfar any pokemon while catching another :D But still thanks for your great work!
http://www2.pic-upload.de/img/31360854/bug.png

**Comment by recon88** [comment]
Don't see what's wrong there: CATCHSUCCESS means, that the pokemon was catched already.

**Comment by KuschelCore** [comment]
the order. he catched a pkmn -> used a berry (means he's trying to catch another one) -> transfers the previous pkmn -> catches the new pkmn with a berry in use. this is impossible
