### ISSUE TITLE
"KeepMinDuplicatePokemon": 1 not working

### ISSUE THREAD

**Issue by spamfighter82** [NECROBOTIO/NecroBot#2208]
"KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

doesn't keep at least one Pokemon anymore, transferred everything below 90% IV away :(

**Comment by recon88** [comment]
Set TransferWeakPokemon to false. If that doesn't help, visit our Discord https://discord.gg/VXKxNFr
