### ISSUE TITLE
Default "TransferWeakPokemon" to false.

### ISSUE THREAD

**Issue by VCoValon** [NECROBOTIO/NecroBot#2212]
I have just come back to find that 90% of my Pokemon have been transferred because of this ridiculous change.

I honestly can't believe that this was said as true by default.

**Comment by recon88** [comment]
Do you even check for new releases? 0.6.1 is out for a while which fixes that...

**Comment by VCoValon** [comment]
Do you understand respect? I've only opened it 10 minutes ago, to which it updated to 0.5.0, and then reopened, displaying the message stating how it's the latest version.

It unfortunately did not go on to update again.

**Comment by VCoValon** [comment]
Close a thread that has a legitimate issue, pathetic.

**Comment by recon88** [comment]
I don't see an issue here. It was fixed and set to false by default in 0.6.1
Ignore the version it tells you

**Comment by VCoValon** [comment]
Except I manually had to install the correct version.
