### ISSUE TITLE
User Credentials Are Invalid And Login Failed (PTC)

### ISSUE THREAD

**Issue by Manamanaa** [NECROBOTIO/NecroBot#2214]
I checked it 100 times, these credentials should work, whats wrong? Im using newest version, ptc, i did accepted terms of use on ptc webpage.

**Comment by recon88** [comment]
Did you login into your account manually?
Try swapping password and name

**Comment by Manamanaa** [comment]
I didn't. What do you mean by swapping password and name?

**Comment by recon88** [comment]
I mean, make sure you put your password in the passoword field, not the way around.
Also check if the PTC servers are having issues.

**Comment by Manamanaa** [comment]
I checked and there are small issues, but not in here, europe

**Comment by recon88** [comment]
Mind visiting us on discord for further support? https://discord.gg/VXKxNFr 
Just ask in #support
