### ISSUE TITLE
help me setting pokeballs for catchsuccess

### ISSUE THREAD

**Issue by thiron** [NECROBOTIO/NecroBot#2217]
(CatchSuccess) | (Lure) Horsea Lvl: 10 CP: (190/227) IV: 37.00% | Chance: 47.34% | 23.82m dist | with a UltraBall (56 left). | Candies: 3 | lat: -6.175013 long: 106.827725False

how do I capture using pokebal first until exhausted

**Comment by recon88** [comment]
Discord for settings help: https://discord.gg/VXKxNFr
