### ISSUE TITLE
[Vietnamese language] try add this language

### ISSUE THREAD

**Issue by nguyenthanhcongsoict** [NECROBOTIO/NecroBot#2220]
[translation.vi.zip](https://github.com/NECROBOTIO/NecroBot/files/398015/translation.vi.zip)

**Comment by Oolaruu** [comment]
Go here:
https://github.com/NECROBOTIO/NecroBot/blob/master/PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

It's the most updated I hope language after En
Once done, I'll help you to put into NecroBot.

**Comment by nguyenthanhcongsoict** [comment]
thank you :)
http://pastebin.com/adCKxXhC

**Comment by Oolaruu** [comment]
Done my friend.

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/2247
