### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by distan29** [NECROBOTIO/NecroBot#2223]
can you guys explain to me what IV mean?

**Comment by Oolaruu** [comment]
http://lmgtfy.com/?q=Pokemon+Go+IV+meaning

**Comment by distan29** [comment]
Ty sir :D 
i just find this "

    Combat Power is only an average of your Pokemon’s stats and is only a rough estimation of a Pokemon’s strength. -source

There are 3 IV's that we know of; Attack, Defense, and Stamina. Defense and Stamina are important when it comes to defending in gym battles, and Attack and the move you are attacking with's base damage and attack speed are important for attacking gyms.

So for defense of gyms, a Pokémon with a lower cp but higher Defense and Stamina may be a better pick than a higher cp Pokémon who just has really high Attack. For attacking, you will want to prioritize Pokémon with higher attack and lower defense, as you can always dodge to avoid taking a lot of damage. See here for more info.

Also, see here or here for an IV calculator."

**Comment by theloser** [comment]
IV = individual values (attack/defense/stamina)

But that's not a developement issue, go to the discord channel and ask for help (or just use @Oolaruu's link :-))
