### ISSUE TITLE
How to prioritize evolve over transfer?

### ISSUE THREAD

**Issue by Revoss** [NECROBOTIO/NecroBot#2226]
Hello,

I'd like to auto evolve my pidgeys, rattatas, etc, but the program keeps transfering them. 

 "EvolveAllPokemonWithEnoughCandy": true,

**Comment by theloser** [comment]
Do you have
```
  "KeepPokemonsThatCanEvolve": true
```
?

**Comment by actislav** [comment]
fix it in #2213

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
