### ISSUE TITLE
transferred most pokemon

### ISSUE THREAD

**Issue by faris2000** [NECROBOTIO/NecroBot#2232]
once is updated it transferred all my pokemon that are not on my don't transfer list despite having keep minimum 2 before transfer and keep pokemon that evolve set to true

**Comment by theloser** [comment]
Check "TransferWeakPokemon" -- is it set to true? Then you are transfering ALL pokemon which CP is less than KeepMinCp OR which iv perfection is less than KeepMinIvPercentage (because they are weak). Bummer.

Edit: It's not a bug, it's a feature (since 0.6.1 disabled by default :-))

**Comment by recon88** [comment]
You should have skipped 0.6.0 and updated to 0.6.1
Set

**Comment by faris2000** [comment]
oh ok i didnt know bc it auto updated then transfered a lot

**Comment by faris2000** [comment]
and yes its on and but it was set to 1250 :(

**Comment by faris2000** [comment]
and yes it was on and but it was set to 1250 :( i just changed it now thank you
