### ISSUE TITLE
throws away all pokemon after update!

### ISSUE THREAD

**Issue by thomasmoors** [NECROBOTIO/NecroBot#2234]
WTF!

**Comment by jasio77** [comment]
Set TransferWeakPokemon to false.

**Comment by SweetCherry** [comment]
This is nothing new man

In future you may use 
 "AutoUpdate": false,
 "StartupWelcomeDelay": false,

They you have time to study the config before the bot runs off

**Comment by cedriclecat** [comment]
REKT

**Comment by JeremyVriens** [comment]
Fixed in https://github.com/NECROBOTIO/NecroBot/pull/2126
