### ISSUE TITLE
Noting happens after 0.6.0 Update

### ISSUE THREAD

**Issue by NukeTheBawm** [NECROBOTIO/NecroBot#2238]
After opening Necro to update it automatically, I get the "Logging in with google" message 3 times. Have tried closing and opening 4 times now, still, nothing. Thanks

**Comment by SweetCherry** [comment]
Please manually download the update and overwrite your existing file!
Thanks

**Comment by nfettinger** [comment]
Have you tried renaming your config.json file so that it gets recreated?

**Comment by boosie212** [comment]
I had it working after disabling my proxy, but am now having trouble again with the newest release.

**Comment by NukeTheBawm** [comment]
@nfettinger rename to what exactly?

**Comment by boosie212** [comment]
I changed it to config1.  It created a new config file, but still same issue

**Comment by boosie212** [comment]
@NukeTheBawm what do you get when you visit this website https://pgorelease.nianticlabs.com/plfe/

**Comment by NukeTheBawm** [comment]
@boosie212  "dude, this is the player frontend"
Btw this is not the computer I am running my bot on

**Comment by recon88** [comment]
A lot of Server IPs were banned. Try the bot on your computer first.

**Comment by boosie212** [comment]
I would check on the computer you are running the bot on.  I get the same message on the computer im running the bot.  I actually fixed the issue by turning off the proxy on this computer by going into regedit.  It was working fine for about 30 minutes then reverted back to this state.

**Comment by boosie212** [comment]
@recon88 how can you determine if your IP was banned?

**Comment by NukeTheBawm** [comment]
I was using a vpn, but it works on my phone..

**Comment by boosie212** [comment]
@NukeTheBawm the bot works on your phone?  What VPN do you use?

**Comment by NukeTheBawm** [comment]
@boosie212 I meant vanilla pokemon go works on my phone, and I use Betternet

**Comment by recon88** [comment]
The bot should tell you if your IP was banned. Bot not sure if that works properly yet as it is a new feature.

**Comment by NukeTheBawm** [comment]
i use a VPN on my pc that runs the bot. but when i run the bot, i get the singing in with google message a hundred times. When i load up pokemon go on my phone, i can catch pokemon and pokestops are usable, so I'm not banned..

**Comment by boosie212** [comment]
Im about 90% sure both of our issues do not have to do with banned IPs.  I'm getting the same message consistently as well.

**Comment by boosie212** [comment]
and now im back up again...weird

**Comment by jordanpillefernandez** [comment]
help !!!

**Comment by recon88** [comment]
Seems to be issues with the login server itself? Not sure guys. But glad you are in again

**Comment by NukeTheBawm** [comment]
im still broken

**Comment by boosie212** [comment]
@recon88 Not a closed issue.  NukeTheBawm is the one that opened this
