### ISSUE TITLE
Transfer of all Pokemon

### ISSUE THREAD

**Issue by vacanickel** [NECROBOTIO/NecroBot#2239]
After the update the bot started to transfer all my Pokemon, without a change in the config. I can't figure out to tell it, to always leave one of a kind.

**Comment by bhwollen** [comment]
Same issue here. Annoying. Lost a lot of pokemon I only had one of...

**Comment by SweetCherry** [comment]
Please study the config next time, you have to change

  "TransferWeakPokemon": true,
to
  "TransferWeakPokemon": false,

If you dont want that

**Comment by nfettinger** [comment]
Please ask in Discord for help.

**Comment by recon88** [comment]
#2232
#2230
#2202
and so on.. please check closed tickets first

**Comment by alpadev** [comment]
just want to complete your list :P
#2239 #2234 #2232 #2230 #2197 #2195 #2192 #2178 #2171 #2169 #2168 #2162 #2158 #2157 #2154 #2153 #2152 #2149 #2146 #2138 #2135 #2134 #2123 #2093

**Comment by sevenzsu** [comment]
It's such a huge design flaw! Any setting that delete things should at least a warning or default to false, especially  when the development is in such a fast pace and the document cannot keep up with. Also I think KeepMinDuplicatePokemon should trump TransferWeakPokemon.

**Comment by recon88** [comment]
Or you just read the changelog to make sure there's nothing new that could ruin your setup before updating.
Or just stop botting at all if you are not prepared for something like that.
The devs are Humans as well and mistakes happen.

**Comment by sevenzsu** [comment]
I understand mistakes happen. Not trying to blame devs, just trying to suggest how should we prevent this problem down the road. Many users have the autoupdate turns on. And from my coding career I think devs should be very cautious about delete functions.
