### ISSUE TITLE
After update does not evolve any pokémon

### ISSUE THREAD

**Issue by arykelton** [NECROBOTIO/NecroBot#2242]
After update does not evolve any pokémon only shows potential Pokemon evolve
my config:

"TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.778915,
  "DefaultLongitude": -73.962277,
  "WalkingSpeedInKilometerPerHour": 100.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 30000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 10,
  "MaxTravelDistanceInMeters": 10000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1300,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 90,
  "UseUltraBallAboveIv": 90,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,

**Comment by NorwegianVikings** [comment]
change to this and it should work

"EvolveKeptPokemonsAtStorageUsagePercentage": 0.1,
"KeepPokemonsThatCanEvolve": true,

remember u need to add the pokemons name to the evolve list

**Comment by nfettinger** [comment]
This is not a dev issue.
