### ISSUE TITLE
Sniping

### ISSUE THREAD

**Issue by NukeTheBawm** [NECROBOTIO/NecroBot#2243]
I have edited the config file with all the things necessary *I think* and everytime the bot goes to snipe, its always unable to find any pokemon. Thanks! will provide config if needed

**Comment by SweetCherry** [comment]
PLEASE STOP CREATING NEW ISSUES!

Come to the discord chat! Please keep this repo clean

**Comment by darksoon** [comment]
sniping works perfect ;)
