### ISSUE TITLE
Transfer problem

### ISSUE THREAD

**Issue by AvengedPM** [NECROBOTIO/NecroBot#2253]
So my Necrobot (0.6.1) has started to transfer every pokemon under my KeepMinCp and is only keeping the ones above that value and the ones in the PokemonsToEvolve list, leading to me losing nearly all my Pokemon except for the really strong ones.

It seems to ignore the KeepMinIvPercentage and KeepMinDuplicatePokemon. 

I've included my config file (converted to txt). 
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/398182/config.txt)
Any help?

**Comment by Whosdaman** [comment]
Funny enough, KeepMinDuplicatePokemon was removed from my config, and now its keeping every pokemon. I think they removed it, and I don't know why... I hope they readd it

**Comment by Basetonic** [comment]
I have exactly the same problem as **AvengedPM**

**Comment by lotrez** [comment]
I really hope they add back the KeepDuplicatePokemon because now I can't really get my config to work like before

**Comment by Draniella** [comment]
it happend exactly the same to me, oh my pokemons....oh well....its a problem i hope they fix it soon n_n

**Comment by recon88** [comment]
Try setting TransferWeakPokemon to false

**Comment by Draniella** [comment]
already, i have to transfer it by myself. just informing :+1:

**Comment by marcandres** [comment]
+1 I hope it fixed soon

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
