### ISSUE TITLE
Transfer issue with lastest update

### ISSUE THREAD

**Issue by Basetonic** [NECROBOTIO/NecroBot#2255]
Hello,

I had an issue with the latest update. A few hours ago the Bot was running just fine and than is suddenly stopped working. So I restarted it and noticed that it was updating. After it has finished, it started as usual but I noticed that it began transfering a lot of my pokemons that were on my **"PokemonsNotToTransfer"** and also that it didn't follow the restrictions of the **"PokemonsTransferFilter"**.

For exemple I had a :
_Porygon,  LVL: 20,  CP: 938 / 966,  IV: 83.12_

and also this : 
 _"Porygon": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 20.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"_

And it transfered my Porygon ...
It did it also to other pokemons that were labeled in **"PokemonsNotToTransfer"**

I checked all the script again and except some new features due to the update, everything looks as it was before when it was working correctly. I'm afraid to start it again and loose some pokemons ...

**Comment by kingmc95** [comment]
Same here,
it transfered all my pokemons.
Luckily I was using a new account for this.
I'm using the older version until the bug is fixed.
Just changed Auto update in config to false ...

**Comment by recon88** [comment]
#2197
