### ISSUE TITLE
Evolution/Transfer calculation may be wrong

### ISSUE THREAD

**Issue by netboy07** [NECROBOTIO/NecroBot#2258]
I'm using release v0.6.1
My mass evolution triggered by  "EvolveKeptPokemonsAtStorageUsagePercentage": 98.0
However, I noticed that I had more pidgeys, weedle and caterpies in my inventory that the required due to the message:
 (INFO) Waiting to evolve XX Pokemon once ....

Just after finishing my mass evolution I still have 200 pidgeys and 400 pidgey candies and I have a new mesage:
 (INFO) Waiting to evolve 57 Pokemon once 311 more are caught! (522/833 for 98% inventory)

I think that  version v0.6 and v0.6.1 (tested with both) does not transfer exccess of pokemons prior to evolution.

My config:

"EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 98.0,
  "KeepPokemonsThatCanEvolve": true,

 "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey"
  ],

Thanks for your support

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
