### ISSUE TITLE
Another Transfer Issue

### ISSUE THREAD

**Issue by kia4545** [NECROBOTIO/NecroBot#2260]
So it's not transferring correctly 

Globally I have set to keep 1 duplicate but then I have every pokemon in the transfer list with the setting per pokemon. I have set to keep 3 snorlax but I have 5 now as an example. Config below.

http://pastebin.com/JzsxMHJU

**Comment by RichardZhaoE** [comment]
I believe there is still an issue with the transferring. For some reason it's keeping two of each pokemon for me even though i do not have them listed in any filter and with keepminduplicatepokemon at 1. All too buggy =(. It's filling up my pokemon inventory fast.

**Comment by simplyphp** [comment]
A duplicate means a duplicate, having 1 means you have 0 duplicates. Having 2 means you have 1 duplicate.

**Comment by RichardZhaoE** [comment]
That function would usually mean having 1 = 1. Not 2. Not sure when that changed.

**Comment by RichardZhaoE** [comment]
Total number of that Pokemon species in your inventory is greater than KeepMinDuplicatePokemon

According to the wiki config ^ Meaning if = 1, i should only have 1? Not 2?

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
