### ISSUE TITLE
0.6.1 is not evolving

### ISSUE THREAD

**Issue by turbozapekanka** [NECROBOTIO/NecroBot#2265]
Displays potential evolves and does nothing

**Comment by Sasstraliss** [comment]
What does your config file look like? Pastebin it for us :)

**Comment by SweetCherry** [comment]
yes version 0.6.1 does not evolve stuff

**Comment by turbozapekanka** [comment]
http://pastebin.com/sYUzWLfx

**Comment by SweetCherry** [comment]
"EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,

The upper value should be higher

**Comment by turbozapekanka** [comment]
I have it set to 95 on another config, still does not evolve

**Comment by turbozapekanka** [comment]
Is it possible that it does not evolve until Pokemon inventory is full>?

**Comment by recon88** [comment]
Evolve issues are known. There are tickets about it already.
