### ISSUE TITLE
Errors Necro 0.6.1 does not work?

### ISSUE THREAD

**Issue by Mistery90** [NECROBOTIO/NecroBot#2266]
Hello i used 0.6.1 for 1,5 hour and this pop up http://prntscr.com/c0upml  i tried to reset bot but same thig. it just goes like that.

**Comment by CakeHole83** [comment]
Getting total crashes but not been fast enough with the printscreen before it shut down.

**Comment by redline187** [comment]
there is a directory called log with a log file with the errors.

**Comment by simplyphp** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
