### ISSUE TITLE
Option to disable "Press key to start" when bot stops mid session and then tries to start again

### ISSUE THREAD

**Issue by wygasmateusz** [NECROBOTIO/NecroBot#2267]
Hello ,

If PTC crash ""Press key to start" stopping bot on long bot session. If it is possible option to dissable it will be helpfull :+1:

**Comment by wygasmateusz** [comment]
Hello ,

If PTC crash ""Press key to start" stopping bot on long session. If it is possible option to dissable it will be helpfull :+1:

**Comment by LiqwdE** [comment]
In confin, set welcome message to false

**Comment by nfettinger** [comment]
This can be changed via the config.
