### ISSUE TITLE
Sniping filter issue

### ISSUE THREAD

**Issue by Jurplez** [NECROBOTIO/NecroBot#2274]
"UsePokemonSniperFilterOnly": false,

Still catching only filtered pokemons for some reason, I checked it with adding a Dratini to the filter and suddenly it started picking them up from PoGofeeder from then on when it did not before

**Comment by simplyphp** [comment]
No version number supplied, unable to verify this still exists. If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
