### ISSUE TITLE
KeepMinDuplicatePokemon keeping more than 1?

### ISSUE THREAD

**Issue by wele** [NECROBOTIO/NecroBot#2276]
`  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
`

I *believe* in 0.5 this used to only keep 1 of the same pokemon (excluding those with entries in PokemonsTransferFilter) 

However with 0.6 i find that there's 6 pidgeys that didn't get transferred... i have the following entry in the PokemonsTransferFilter
`"Growlithe": {
      "KeepMinCp": 650,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 5,
      "Moves": [],
      "KeepMinOperator": "and"
    },
`
but instead of keeping 5 growlithes, it's keeping 6? looks like a lot of it doing a +1 of the keepminduplicatepokemon setting whether it is global or entry specific.

**Comment by simplyphp** [comment]
No version number supplied, unable to verify this still exists. If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.

**Comment by RichardZhaoE** [comment]
Confirmed problem still not fixed in 6.2. Using the latest release. At least two of each pokemon still in my inventory

**Comment by wele** [comment]
@simplyphp i actually did supply 0.6 =P but i guess this is still a bug in 0.6.2 per @RichardZhaoE

**Comment by simplyphp** [comment]
Unique = 1
Duplicate = 2+
you cannot set duplicate to 1 and expect it to have 0 duplicates
if its set to 1 , you will have 2, and it will not transfer out until you have 3
in which case it will transfer 1.
