### ISSUE TITLE
Bot dumps all pokeballs

### ISSUE THREAD

**Issue by NukeTheBawm** [NECROBOTIO/NecroBot#2278]
I have the max total amt. of pokeballs to keep to 120, but for some reason, the purple recycle text says it removes about 3/4 of my pokeballs. Thanks!

[18:22:31] (RECYCLING) 24x ItemPokeBall

( i had 35, it dumped 24, eventually, im gonna run out)

**Comment by OuttaControlX** [comment]
did you set how many pokeballs/greatballs/ultraballs to keep? they are separate values.

**Comment by NukeTheBawm** [comment]
@OuttaControlX i only see pokeballs to keep

**Comment by recon88** [comment]
Total amount = ALL types combined. Set it higher

**Comment by OuttaControlX** [comment]
CAREFULLY go through all the options, you will see it, as well as the circumstances to use each ball type under, theres many many options take 15 minutes and go through them all.

**Comment by OuttaControlX** [comment]
@recon88 he has done that, thats why i know its his indivual pokeball setting.

**Comment by NukeTheBawm** [comment]
@OuttaControlX  im telling you its not there http://paste.ubuntu.com/21956094/
