### ISSUE TITLE
6.2 Transferring not functioning properly. KeepMinDuplicatePokemon

### ISSUE THREAD

**Issue by RichardZhaoE** [NECROBOTIO/NecroBot#2279]
"KeepMinDuplicatePokemon": 1,

Still not transferring pokemon until 3 or more count. Have not touched any of my settings since 5.0 which have been transferring pokemon every 2 count or more. Also, no additional transfer filters are being used.

**Comment by RichardZhaoE** [comment]
#2276

**Comment by RichardZhaoE** [comment]
#2276

**Comment by marcandres** [comment]
+1 KeepMinDuplicatePokemon it doesn't work

**Comment by simplyphp** [comment]
Unique = 1
Duplicate = 2+
you cannot set duplicate to 1 and expect it to have 0 duplicates
if its set to 1 , you will have 2, and it will not transfer out until you have 3
in which case it will transfer 1.
