### ISSUE TITLE
6.2 Bug: "UsePokemonSniperFilterOnly": false

### ISSUE THREAD

**Issue by Jurplez** [NECROBOTIO/NecroBot#2280]
Only catches the pokemons listed in the filter, already added a diff pokemon on the list and after it's added, it gets sniped. Doesn't work if it isn't in the list

**Comment by ChemiHatake** [comment]
Please provide more information about the issue.

**Comment by Jurplez** [comment]
Any pokemon that's not listed as a snipeable pokemon in the list of pokemon that comes after ''LocationsToSnipe'' will not even get an attempt to get sniped

**Comment by simplyphp** [comment]
Working as intended, the pokemon has to be in the list of ones you want to snipe.

**Comment by Jurplez** [comment]
Isn't it when the filter states false that you'd get every pokemon from sniping?

**Comment by TankTheFrank** [comment]
If it's intended, channels for 100 iv are useless. The whole point of high iv channels is to snipe all regardless if it's in that list or not.
