### ISSUE TITLE
evolveFilter does work at all

### ISSUE THREAD

**Issue by xiachaolun** [NECROBOTIO/NecroBot#2281]
I haven't checked 6.1 or 6.2, but for any version between 4.0 - 6.0, the evolve filter does not work -- the bot either evolves all the pokemons (that can evolve, i.e. >= the least iv or with enough candies) or none. 

I am not sure if this sentence works as expected:
IEnumerable<PokemonId> pokemonIds = filter as PokemonId[] ?? filter.ToArray();

**Comment by recon88** [comment]
Check 0.6.2 and confirm it's an issue with that.

**Comment by xiachaolun** [comment]
@recon88 OK, I checked 6.2 the same problem.

**Comment by simplyphp** [comment]
Set this setting and see if it works:
"EvolveKeptPokemonsAtStorageUsagePercentage": 10.0,
