### ISSUE TITLE
Hatching Eggs - Ignore Pokestops

### ISSUE THREAD

**Issue by Mysteryman123** [NECROBOTIO/NecroBot#2284]
Could there be a setting in config where the bot walks to the pokestops but doesn't collect from them, so that the eggs can hatch?

**Comment by Marsinator** [comment]
collecting from pokestops only takes a few ms, it doesnt slow down the process of hatching significantly. I dont think we need this.

**Comment by Mysteryman123** [comment]
The suggestion is to allow you to just hatch eggs and to same the same level while doing it, because I have had friends and people comment on how I leveled up overnight without leaving my home. I just think it would be another feature that might work for others who just want their eggs to hatch and avoid detection from friends.

**Comment by Wcidd** [comment]
Ask support
