### ISSUE TITLE
Same Transfer issue

### ISSUE THREAD

**Issue by kia4545** [NECROBOTIO/NecroBot#2285]
So it's not transferring correctly

Globally I have set to keep 1 duplicate but then I have every pokemon in the transfer list with the setting per pokemon. I have set to keep 3 snorlax but I have 5 now as an example. Config below.
tested on 0.6.0 0.6.1 0.6.2
http://pastebin.com/JzsxMHJU

**Comment by Fluxona** [comment]
snorlax is in the default nottotransfer list

**Comment by kia4545** [comment]
Please check my Config via pastebin link

**Comment by djdookie** [comment]
What CP and IV have your 5 Snorlax'?

**Comment by kia4545** [comment]
below 100 iv and 3000 cp

**Comment by djdookie** [comment]
Are they favorites? I believe they aren't touched by the bot if they are.

**Comment by BigAlGit** [comment]
I'm having the same issue with the transfer filter.  It seems like the filter doesn't even matter in my case.

**Comment by kia4545** [comment]
no favorites

**Comment by kia4545** [comment]
Solved wiki needs updating/clarification...Wiki need major update.

**Comment by BigAlGit** [comment]
@kia4545 How did you solve it?

**Comment by kia4545** [comment]
they changed the setting so let say you want 1 of all the keepduplicate needs to be set to 0 and this hold true the pokemon transfer list so I want to keep 3 snorlax I have to set it to 2...hope this helps.

**Comment by BigAlGit** [comment]
So, if I want a transferfilter to set pidgeys to keep 0, I set the keepduplicate to 1 and the keep to -1?

Thanks!
