### ISSUE TITLE
Crashes in v0.6.1 and v0.6.2

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2288]
I got crashes since v0.6:

![exception1](https://cloud.githubusercontent.com/assets/17240204/17348105/6d05f664-5914-11e6-9412-82c345a237c3.JPG)
![exception2](https://cloud.githubusercontent.com/assets/17240204/17348106/6d07c21e-5914-11e6-91e9-3ea6994c7fcb.JPG)

In english it would be something like: object not referenced.

**Comment by recon88** [comment]
Server issues
