### ISSUE TITLE
User Credentials

### ISSUE THREAD

**Issue by Kalanhar** [NECROBOTIO/NecroBot#2290]
Hello,
Sry to bother, i am just a regular user not a programmer so i am a little bit confused.
Seconds ago, before doing the regular Necrobot restart (each 6 hours) it updated to 0.6.2 
Before the update everything was working perfectly fine, but after the update i get:

[Error] Credentials are invalid and logic failed

As for other accounts both PTC and Google, all work but the one i am currently using.
The account i am using logs perfectly on the phone, i can spin poke stops and everything is fine (yes i have been botting arroung my own appartament.

I would really appreciate some help, i am confused since the credentials are correct.
Thank you in advance

**Comment by emwedk** [comment]
Did you check if your authtype is set as it's supposed? ptc or google?

**Comment by Marsinator** [comment]
please make sure you used the correct info in your auth.json

{
  "AuthType": "ptc",
  "GooglePassword": null,
  "GoogleRefreshToken": null,
  "GoogleUsername": null,
  "PtcPassword": "password",
  "PtcUsername": "user"
}

for google:
{
  "AuthType": "google",
  "GooglePassword": "pass",
  "GoogleRefreshToken": null,
  "GoogleUsername": "user@gmail.com",
  "PtcPassword": null,
  "PtcUsername": null
}

**Comment by Wcidd** [comment]
ask support
