### ISSUE TITLE
Current operation was canceled.

### ISSUE THREAD

**Issue by CakeHole83** [NECROBOTIO/NecroBot#2292]
Getting current operation was canceled while moving on a gpx path. It then reloggs and moves me back to the starting point of the path which is FAR away,

**Comment by Marsinator** [comment]
please provide the gpx file and the bot version you are running as well as your config.json

**Comment by CakeHole83** [comment]
[config + gpx file.zip](https://github.com/NECROBOTIO/NecroBot/files/398362/config.gpx.file.zip)
Also after it says Niantic servers are unstable it starts to move back to start. Shouldn't it check for the next point?

**Comment by Wcidd** [comment]
ask support
