### ISSUE TITLE
Necro keeps eating all my pokemons

### ISSUE THREAD

**Issue by emwedk** [NECROBOTIO/NecroBot#2293]
Before the update i was able to set a KeepMinCP on every single pokemon in [PokemonsTransferFilter] with [KeepMinDuplicatePokemon: 0] - and it wouldn't transfer ALL pokemons

since update 6.0 or 6.1 it just keeps transfering every single one except the ones in [PokemonsNotToTransfer]
 - doesnt matter if it's set as above, or if [keepMinDuplicatePokemon: 3]

Here's my config
[config.ini](http://emwe.dk/config.json)

haven't had any issues with the bot before and i've looked the config through like 10 times
don't see a real issue with it - maybe others will

Thanks in advance

**Comment by shaunoneil** [comment]
This is known, see #2197

**Comment by Fluxona** [comment]
yes, transferweakpokemon has to be false
