### ISSUE TITLE
Repeating INFO and UPDATE, No Pokestops with GPX pathing

### ISSUE THREAD

**Issue by BigAlGit** [NECROBOTIO/NecroBot#2296]
I have had this issue on the last few builds (including 0.6.2), and cannot seem to figure out what is causing it.  I am more than willing to help troubleshoot, just let me know what I can do to help.

It does look like the issue seems to only be present when I am using GPX pathing.  The issue is not present when setting it to false.  It happens with any paths set (I have tried 4 different ones).

I get a repeating set of INFO and UPDATE rather than pokestops or catching.  I know for a fact that the path is littered with pokestops, yet none of them are used.  When I set it to the same start point without GPX pathing, it hits all of the pokestops without issue.  Screenshots are shown to help (first is with pathing, the second is without).

I can send my config file, but I run into the same issues even with default settings (as long as GPX is enabled).  I currently have 168 of 400 pokemon and my items are about half full.

Thank you!

![gpx pathing](https://cloud.githubusercontent.com/assets/20688149/17348216/dd5af22a-58e2-11e6-9dc7-fbb65c4e4e4b.PNG)
![no pathing](https://cloud.githubusercontent.com/assets/20688149/17348217/dd5b93ba-58e2-11e6-97cf-2d7faf47d436.PNG)

**Comment by Wcidd** [comment]
Support channel is the place to ask for support

**Comment by Marsinator** [comment]
Actually it's not.

**Comment by Wcidd** [comment]
People are having problems with this

**Comment by BigAlGit** [comment]
I am still having the issue on 0.6.3.  I tried it on another computer with a completely new setup and it does the same.

**Comment by redline187** [comment]
got this problem also made a gpx path with alot of pokestops but its only fetching like 10% of the pokestops
