### ISSUE TITLE
evolve when storage <90% is being ignored

### ISSUE THREAD

**Issue by OlafBakker** [NECROBOTIO/NecroBot#2298]
Started evolving right away, also used a lucky egg @ 57 evolves while min was set @ 80.

**Comment by simplyphp** [comment]
What version? What is your setting for KeepPokemonsThatCanEvolve

**Comment by Marsinator** [comment]
are you sure you have enough candy?

**Comment by Marsinator** [comment]
devs: interaction between evolvewithegg and evolvewhenhitbaglimitpercentage?

**Comment by OlafBakker** [comment]
"EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,

had the issue with 6.2
6.1 is waiting patiently for my invent to go over 90 before evolving
So same setting, different outcome

(had enough candy but not enough pokemons)

**Comment by morrrido** [comment]
Same settings, same problem, evolves right away, doesn't wait for limit
