### ISSUE TITLE
Ignore Min # duplicate or Min # CP

### ISSUE THREAD

**Issue by calevoque** [NECROBOTIO/NecroBot#2300]
Pokemon found keep being transfered even though KeepMinDuplicatePokemon is set to 1 and KeepMinCp is set to 800
All the rest was left with the default configuration, hence I have 0 pokemons now ...

Thanks for your help

**Comment by Marsinator** [comment]
please see if "TransferWeakPokemon": is true or false in your config.json

you would want it to say false.
also what version of the bot are you running

**Comment by calevoque** [comment]
Thanks, I'll try that, it means TransferWeakPokemon set to true overwrites KeepMinDuplicatePokemon ?
I'm running v0.6.2

**Comment by theloser** [comment]
TransferWeakPokemon will transfer ANY pokemon with CP less than KeepMinCP **or** with perfection less than KeepMinIvPercentage -- regardless how KeepMinDuplicatePokemon is configured.
