### ISSUE TITLE
[Issue] Last position

### ISSUE THREAD

**Issue by li81** [NECROBOTIO/NecroBot#2302]
Is there a fix for this: http://puu.sh/qnE6i/29cae28b8c.png?

It stops my bot from working and I have to reboot it everytime to make it work.

**Comment by Marsinator** [comment]
change your starting gps to a more crowded area. please state which version of the bot you are using and if my suggest change did fix that.

**Comment by li81** [comment]
Can you link me the site for new gps cords, i'll try that first

**Comment by theloser** [comment]
Wtf? Just pick some coords! maps.google.com, click **anywhere** and copy those coords! Geez...

(Sorry for the rant.)

**Comment by li81** [comment]
Forgot obv, no need to be rude.

**Comment by Wcidd** [comment]
Support channel
