### ISSUE TITLE
[FR Transl] V0.6.2 Move1 / Move2 / Candy Not translated lang files is ok

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#2303]
Hello.

According to #1953 issue I still have the bug on v0.6.2.
- Fresh install
- Fresh config files
- French language

http://prntscr.com/c0vh57

    "Key": "displayHighestMove1Header"
    "Key": "displayHighestMove2Header"
    "Key": "candies"

**Comment by Marsinator** [comment]
reproduce:   "TranslationLanguageCode": "fr",

**Comment by Oolaruu** [comment]
and all languages.
de :  http://prntscr.com/c0viz3
ru_RU : http://prntscr.com/c0vkf4


It's the same for Objets: http://prntscr.com/c0vk4b

**Comment by Dyzson** [comment]
In Polish translation is the same.
