### ISSUE TITLE
6.1 - broken backpack cleaning?

### ISSUE THREAD

**Issue by golitsyn** [NECROBOTIO/NecroBot#2305]
in 5.0 if the bag is full, it start transfering Pokemons.
in 6.1 if the bag is full, it not start transfering Pokemons and continues to try to snipe Pokemons (of course without success)

**Comment by Marsinator** [comment]
please update to 0.6.2 first and see if the problem persits

**Comment by simplyphp** [comment]
It's your settings, you're keeping the pokemon because you've set them too loosely for keep.
