### ISSUE TITLE
Favoriting is not working 

### ISSUE THREAD

**Issue by paperc07** [NECROBOTIO/NecroBot#2308]
"FavoriteMinIvPercentage": 100.0,
"AutoFavoritePokemon": true,

It says its Favorited but when you go into game they are not

**Comment by Sylencer90** [comment]
Not working for me either, haven't tried 0.6.2 tho.

**Comment by simplyphp** [comment]
This is an issue with POGOProtos code, not ours, and we've already opened an issue:
https://github.com/AeonLucid/POGOProtos/issues/110
