### ISSUE TITLE
Bot won't even run after new update.

### ISSUE THREAD

**Issue by projectoffset** [NECROBOTIO/NecroBot#2309]
New version is 0.6.2

Started it up and I repeatedly get this error: http://imgur.com/lrTSYVD

Can anyone tell me what the issue is here? It seems to occur randomly.

**Comment by DrisBigB** [comment]
I got this problem too, when the servers had glitch, and after reconnect the coords in LastPos.ini (in Config folder) shows bigger difference than _MaxSpawnLocationOffset": 10_ <-- this number

**Comment by simplyphp** [comment]
Was a Niantic server issue
