### ISSUE TITLE
[Request] Transfer: Keep each, highest CP AND highest IV Pokemon

### ISSUE THREAD

**Issue by tiagovit** [NECROBOTIO/NecroBot#2312]
I wanted to keep at least two of each pokemons, one with higher CP and the other with higher IV
with time eventually the one with higher IV would be the same with higher CP.

The way I find it more easily is to take always the best CP/IV from, for example, Snorlax, and then automatically edit:

"Snorlax": {
      "KeepMinCp": 1800,  
      "KeepMinIvPercentage": 95.0, 
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },

Edit (by Taranis01):

"Snorlax": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "KeepBestPokemon":  false/ cp/ iv/ both 
      "Moves": [],
      "KeepMinOperator": "or"
    },

**Comment by Taranis01** [comment]
I'd suggest to add a new line: "KeepBestPokemon": "both" </-- Value: false, cp, iv or both (for best of each) --/>
For the Amount of best Pokemons kept the KeepMinDuplicatePokemon line could be used (while when it is
"KeepBestPokemon": "both"
"KeepMinDuplicatePokemon": 1,
then 2 of the best cp and 2 of the best iv will be kept.
If the 2 best cp are also the 2 best iv then there will be only 2 of that kind of pokemon (automatically after the best pokemon is calculated for cp and iv separately
