### ISSUE TITLE
[Feature Request] KeepMaxDuplicatePokemon within PokemonsTransferFilter?

### ISSUE THREAD

**Issue by wele** [NECROBOTIO/NecroBot#2313]
Bot 0.6.2

I think the KeepMinDuplicatePokemon might be more confusing than anything, is it possible to add a KeepMaxDuplicatePokemon?

"Magikarp": {
      "KeepMinCp": 160,
      "KeepMinIvPercentage": 90.0,
      "**KeepMaxDuplicatePokemon**": 3,
      "Moves": [],
      "KeepMinOperator": "and"
    },

**Comment by simplyphp** [comment]
Most people want duplicates so they can evolve them, this would add further obscurity to an already fairly difficult to understand set of logic.

**Comment by LiqwdE** [comment]
It's not a completely bad idea. I want duplicates for evolving... but I don't need 17 snorlax or 23 eevee. Love the minimum,  but max would be nice as well. Minimum 3, max 9, keep the biggest cp/iv depending on config
