### ISSUE TITLE
(INFO) Logging in using Google

### ISSUE THREAD

**Issue by ohtheirony** [NECROBOTIO/NecroBot#2316]
I cannot login using Google, getting no error messages, just logging in messages every 30 seconds or so, please help me solve this.

**Comment by Oolaruu** [comment]
Servers might be unstable.
Try again maybe in few minutes.

Edit: Just tried it, I can login no problem Google(Europe)

**Comment by ohtheirony** [comment]
Yeah, it is probably not the server, i think it is related to me not having a proper "google" domain as my login info, my account uses my own domain, but is still a Google account.

I am able to login using ptc, also EU.

**Comment by ohtheirony** [comment]
![login](https://cloud.githubusercontent.com/assets/20804801/17349346/3738b248-591d-11e6-94f0-2b97929e0270.png)

**Comment by ohtheirony** [comment]
Earlier today

**Comment by ohtheirony** [comment]
![logging in](https://cloud.githubusercontent.com/assets/20804801/17349348/424d8fbe-591d-11e6-8543-37573893f177.png)

**Comment by simplyphp** [comment]
Niantic is having issues.
