### ISSUE TITLE
Niantic removed bonuses from bonus throws

### ISSUE THREAD

**Issue by op85** [NECROBOTIO/NecroBot#2318]
It appears that we are still receiving bonus from throws yet they have been removed from the pogo app

**Comment by jonsnowwatch** [comment]
lol interesting

**Comment by op85** [comment]
Away of detecting bots and tweaks I would imagine before a ban wave. Why else remove the bonuses?

**Comment by jonsnowwatch** [comment]
because they are assholes :^) I dont know

**Comment by noodle-** [comment]
It might be a good idea to randomize the perfection of each throw to try and avoid that way of detecting bots.

With an option like ```UsePerfectThrowEverytime``` for people who don't care about potentially getting banned

**Comment by op85** [comment]
But we're still getting the bonuses even tho in the app they are not giving the bonuse even if you get a nice, great or excellent throw. Must be the way it's linked. Niantic have removed the link but not the part that bots link to. They could easily flag people still getting the bonuses and know they using bots or tweaks. Several tweaks removing throw bonuses now

**Comment by lorilith** [comment]
Do folks that have not updated their google/ios app still get these bonuses?  If so, we should be safe as long as any version detection sees us as a previous version
