### ISSUE TITLE
[request] pokestops only if needed

### ISSUE THREAD

**Issue by xzipyx** [NECROBOTIO/NecroBot#2319]
Since I am on a high level already, it'd be nice to have a snipe only option. it should only visit pokestops when needed (min pokeballs reached etc). this would avoid unnecessary xp farm.
maybe a max lvl for farming xp option would be nice to have, too

**Comment by Wcidd** [comment]
Manual Sniping

**Comment by xzipyx** [comment]
was added now to possible feature =)
