### ISSUE TITLE
<Suggestion> Adding move types in dumps

### ISSUE THREAD

**Issue by evrentlbs** [NECROBOTIO/NecroBot#2321]
I suggest that more detailed dump files which includes move types like that:

instead of,

`NAME: Dragonite (Dragonite_85)  LVL: 19      CP: 1863 / 1900     IV: 84.67      MOVE1: DragonBreathFast     MOVE2: HyperBeam            Candies: 123`
`NAME: Golduck (Golduck_28)      LVL: 27      CP: 1643 / 1841     IV: 27.62      MOVE1: WaterGunFast         MOVE2: IceBeam              Candies: 857`
`NAME: Magmar (Magmar_76)        LVL: 26      CP: 1620 / 1682     IV: 76.06      MOVE1: EmberFast            MOVE2: FireBlast            Candies: 18`

suggestion,

`NAME: Dragonite (Dragonite_85)  LVL: 19      CP: 1863 / 1900     IV: 84.67      MOVE1: DragonBreathFast [Dragon]     MOVE2: HyperBeam  [Normal]         Candies: 123`
`NAME: Golduck (Golduck_28)      LVL: 27      CP: 1643 / 1841     IV: 27.62      MOVE1: WaterGunFast [Water]          MOVE2: IceBeam [Ice]               Candies: 857`
`NAME: Magmar (Magmar_76)        LVL: 26      CP: 1620 / 1682     IV: 76.06      MOVE1: EmberFast [Fire]              MOVE2: FireBlast [Fire]            Candies: 18`

thanks.

**Comment by Wcidd** [comment]
Well the name of the move kinda suggests what element it is...

**Comment by evrentlbs** [comment]
not for all of them ex: HyperBeam [Normal]
what the HyperBeam ??
