### ISSUE TITLE
TransferWeakPokemon not in Wiki

### ISSUE THREAD

**Issue by SirRob1997** [NECROBOTIO/NecroBot#2322]
The new config option `TransferWeakPokemon` isnt shown and explained in the Wiki.

**Comment by Sylencer90** [comment]
It will basically transfer all pokemon below the KeepMinCp and KeepMinIV, regarless of KeepMinDuplicatePokemon : 1

**Comment by SirRob1997** [comment]
Alright, the wiki entry would still be useful to prevent questions like this one. 
Thanks alot
