### ISSUE TITLE
Bot doesn't evolve after the first batch of evolving with lucky egg. And use incense if lucky egg is active.

### ISSUE THREAD

**Issue by omar972** [NECROBOTIO/NecroBot#2324]
If you have the bot set to use a lucky egg when it has a certain amount of pokemon ready to be evolved, it successfully waits until that amount is met and evolves them all. But after that, even if the lucky egg is still active, it doesn't evolve until that amount is met again. Seems like a waste.

Another suggestion, a config option to use an incense if a lucky egg is active.

**Comment by Simpuhl** [comment]
I like both Idea's and I understand what your saying.

Basically if you start to acquire more evolves's it should automatically evolve it if the lucky egg is still active.
