### ISSUE TITLE
Follow roads dont go thru buildings and ponds

### ISSUE THREAD

**Issue by redline187** [NECROBOTIO/NecroBot#2326]
The bot is now going thru buildings like a ghost and walking on water like jesus 

the bot should follow roads like a real human

**Comment by theloser** [comment]
If you want your bot to follow roads, you have to create a gpx file with the exact path you want it to move. I think there is no other way in which this can be achieved, because the bot does not know anything about "roads", "buildings", "forrest" or "water"...

**Comment by redline187** [comment]
maybe Google Maps Directions API would be usefull to go for next pokestop

**Comment by Simpuhl** [comment]
Actually there is, a few other bots do it using googlem aps api.

For example: PokeMate (not trying to advertise) you can edit/delete this if its against the rules which im too lazy to lookup.

it uses google api key u must get first in order to use the bot

**Comment by theloser** [comment]
But -- why? If you think it's to obvious that a bot walks through buildings while a human can't, and therefore the bot probably will be detected, I'd say, there are more conspicious actions like evolving three pokomens per second (while it takes 15-20 seconds if you are doing this on your phone).

**Comment by simplyphp** [comment]
People play pokemon inside buildings all the time.
