### ISSUE TITLE
New Version From Release Skipped All Pokemon

### ISSUE THREAD

**Issue by norcahyo-a** [NECROBOTIO/NecroBot#2330]
I Download V 0.6.2 from repository, and do config again..
But until now, my bot stoll Skipped 'all pokemon'

[06:47:10] Skipped KabutoFalse
[06:47:10] Skipped HorseaFalse

But if i use V 0.5.0 from my backup,
Pokemon still catch'up..

Any Config must i do for this issue ?
*Attached my config and my log*

[NecroBot-2016-08-03-06.txt](https://github.com/NECROBOTIO/NecroBot/files/398421/NecroBot-2016-08-03-06.txt)
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/398419/config.txt)

**Comment by xiachaolun** [comment]
set UsePokemonSniperFilterOnly to false
