### ISSUE TITLE
the Perfect Value of this Settings

### ISSUE THREAD

**Issue by 17Curfis** [NECROBOTIO/NecroBot#2332]
Dear NecroBOT,

i want to ask about this config

```
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
```
How to setting or change the value to the perfect value? thanks

**Comment by theloser** [comment]
1) This is not a development issue, go to discord to ask for help
2) There are no perfect values, everyone can set those to what fullfills his/hers needs
3) Default values are: 0.2, 0.1 and 0.05
