### ISSUE TITLE
Upgrade Specific Pokemon

### ISSUE THREAD

**Issue by HepatitisB** [NECROBOTIO/NecroBot#2334]
With these  following options: 

"LevelUpByCPorIv": "iv",
"UpgradePokemonCpMinimum": 1000.0,
"UpgradePokemonIvMinimum": 99.9,
"UpgradePokemonMinimumStatsOperator": "or",
"AutomaticallyLevelUpPokemon": true,

Can we also have the option to name a specific pokemon we want to power up?

**Comment by guidedbymoon** [comment]
i have those same settings but it doesn't power up my 2000 dragonite whats wrong?

**Comment by Simpuhl** [comment]
I have my minimum set to 100.0 but its not leveling up any of the 3 100% ones that I have :/

for CP I have 0.0 and I use "and" instead of or 

Does it need to be 99.9 to do the 100's?

**Comment by emwedk** [comment]
Good idea 
could be a nice added feature to the PokemonsTransferFilter 
maybe even with Evolve Specific Pokemon settings

**Comment by guidedbymoon** [comment]
i tried 99% minimum still doesn't level up

**Comment by emwedk** [comment]
Did u Off-topic- guys try to change
UpgradePokemonMinimumStatsOperator
to or ?

**Comment by simplyphp** [comment]
Does your pokemon have enough candy? Do you have enough stardust? Is the pokemon already at level cap / max cp?

**Comment by HepatitisB** [comment]
The "or" part was from a moderator chat I copied, but I have mine on "and." Don't know what it does exactly, but I am also having the same issues as others stated above.

**Comment by Wcidd** [comment]
I'd like to see this Feature ;) @simplyphp

**Comment by Simpuhl** [comment]
Same here, plenty of stardust and candy. Not leveling and they meet the criteria

**Comment by guidedbymoon** [comment]
somehow my snorlax with those requrments upgraded but my other pokemon dragonite didn't

**Comment by Whosdaman** [comment]
Tbh, the level upgrader needs more of an explanation, because it is a little complicated to figure out at first. I think it needs to have an option to use a max amount of stardust, instead of a min amount to collect...

**Comment by Simpuhl** [comment]
Yeah leveling is broken for sure

**Comment by Marsinator** [comment]
#2193
