### ISSUE TITLE
[Feature Request] New user, filled up Auth.json and few config.json in console

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#2335]
Hello,

Another request that I can suggest specially for new user, who have just downloaded the bot (not from an update) would be:

- Welcome message
- Choose your AuthType:   [1] Google or  [2] Ptc
- Write your Username
- Write your Password
- Choose your destination: [1] Co-ords1 or [2] Co-ords2 etc
Specially for based region pokemon
- Confirm

Or something similar.

Save Auth.json + Config.json, Autoclose, Restart
Enjoy

Thanks

**Comment by Andrerm124** [comment]
I'd assign myself to this issue if I could. I'm almost completed and will reference this issue when pushing.
