### ISSUE TITLE
[Feature Request] Auto detect Windows/Apps language or Google language

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#2336]
Hello,

Currently work in progress to be translated into 25 languages, it would be interesting that the bot detect which language we are using via Windows/Apps or Google language etc etc.

Thanks.

**Comment by nfettinger** [comment]
Unfortunately, in C#, getting the installed culture/language of the system is unreliable. Once detected, the program would have to make the change in the config.json, which is something that wouldn't be desirable.
Also, this can easily be manually changed in the config.json.

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/2699
