### ISSUE TITLE
Updated ignore list to catch no pokemon.

### ISSUE THREAD

**Issue by TuxySquidGuy** [NECROBOTIO/NecroBot#2338]
I updated the list to include formatting to ignore all of the pokemon. Would like to change the link in the Wiki under FAQ

http://pastebin.com/raw/MJGQ6aez

**Comment by emwedk** [comment]
maybe group them in both Max Evolved State and Rarity ? 
so 3 groups 
- rattata, ratticate etc.

-bulbasaur, eevee etc.

- venusaur, arcanine etc. 

?

**Comment by TuxySquidGuy** [comment]
This list is in Pokedex order and is intended to be used in your config file to ignore all pokemon.
I do not see the reason to order them in any other way.

**Comment by anonemon** [comment]
Great! Would be nice to have this featured in the wiki :-)
