### ISSUE TITLE
Bot doesn't AutoUpdate from .5.0

### ISSUE THREAD

**Issue by emwedk** [NECROBOTIO/NecroBot#2339]
Guess the title says it all

**Comment by Wcidd** [comment]
It does, just not set to state 0.6.2 yet

**Comment by Oolaruu** [comment]
Autoupdate from 4.0 working
http://prntscr.com/c0wjgk

**Comment by emwedk** [comment]
that's odd, i did it from .4.0, tho i did it 5 minutes before .6.2 pushed, so it might have been .6.0 that's the issue
