### ISSUE TITLE
Transfer bug

### ISSUE THREAD

**Issue by noodle-** [NECROBOTIO/NecroBot#2342]
With these settings:
```
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
```

Old behaviour: Pokemons that are below ```"KeepMinCp": 1250,``` or ```"KeepMinIvPercentage": 90.0,``` and don't have the best IV of it's type will be transferred.

I'm not sure about this but as far as I have been able to figure this out...: 
Current behaviour: Pokemons that are below ```"KeepMinCp": 1250,``` or ```"KeepMinIvPercentage": 90.0,``` will be transferred if there's another Pokemon of it's type that has either exceeds ```"KeepMinCp": 1250,``` **or**  ```"KeepMinIvPercentage": 90.0,```

This causes the following issue as illustrated with the poor Exeggutor.
![example](https://cloud.githubusercontent.com/assets/812565/17350465/2f14c3cc-5927-11e6-9372-59bbe5110156.png)

**Comment by emwedk** [comment]
change 
"TransferWeakPokemon": false,

**Comment by emwedk** [comment]
it's an issue from .5.0

**Comment by Wcidd** [comment]
Confirmed problem, should be fixed by next releace

**Comment by noodle-** [comment]
>change "TransferWeakPokemon": false,

It already is set to false.
