### ISSUE TITLE
Since Update - Cant Login

### ISSUE THREAD

**Issue by Kay1972** [NECROBOTIO/NecroBot#2345]
I have updated the program and unable to get it to log into my account, just keeps acting as if it attempts over and over, but not going in.   Was using it perfectly fine before the update.   Even (after turning off my location) logged into it with my phone and able to go in with no issues (so not banned), but I can't get this program to work anymore.   Please help!

![image](https://cloud.githubusercontent.com/assets/20805671/17350674/b034a520-58f6-11e6-82f3-eca3a17c5fb8.png)

**Comment by NukeTheBawm** [comment]
I got the same error a while ago, try turning off your proxy or VPN if enabled. If you have neither, then it is because the auto updater is a little buggy, just manually install the newest version and you'll me good to go :)

**Comment by Kay1972** [comment]
I have neither and I did manually install.... but acts as if I didn't as you can tell from the message.  Any other ideas?

**Comment by NukeTheBawm** [comment]
Have you recently updated your config file? if so, what did you change

**Comment by Kay1972** [comment]
I changed 

Line 17 "DefaultLatitude": (my location removed) ,
Line 18 "DefaultLongitude": (my location removed),
Line 47 "UseSnipeOnlineLocationServer": false,
Line 48 "UseSnipeLocationServer": false,

and that is it for this update.    I had a lot more changed in my working version.  I also attempted to turn off the auto update checking, but it still did it anyway?

**Comment by NukeTheBawm** [comment]
Hmm not sure. Must be a server issue.

**Comment by Kay1972** [comment]
I can log in with my phone tho...  So I am lost

**Comment by Kay1972** [comment]
Even though I have manually installed the latest one, it's stuck on thinking there is an update.   I have 0.6.2 ATM

**Comment by Kay1972** [comment]
HA!!  I got it to work!!   Just rebooted my PC!   Not sure why that worked, but it did.   All set now.  Thanks for trying at least :)
