### ISSUE TITLE
Bug: Crashes when adding "mr. mime"/"farfetch'd" to do not transfer list

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#2348]
mr. mime

![image](https://cloud.githubusercontent.com/assets/262571/17350860/0683b64a-58df-11e6-8936-9598a9e712dd.png)

farfetch'd

![image](https://cloud.githubusercontent.com/assets/262571/17350878/1f7ca1e8-58df-11e6-95b8-df0324c46398.png)

**Comment by Simpuhl** [comment]
Same issue with farfetch'd

![image](https://cloud.githubusercontent.com/assets/262571/17350878/1f7ca1e8-58df-11e6-95b8-df0324c46398.png)

**Comment by ChemiHatake** [comment]
use "mrmime" and "farfetchd"

**Comment by Simpuhl** [comment]
Thank you

**Comment by Oolaruu** [comment]
Fixed?
