### ISSUE TITLE
Doesn't Evolve or Transfer Mons

### ISSUE THREAD

**Issue by darkendvoid** [NECROBOTIO/NecroBot#2349]
http://pastebin.com/eFNa4X7Y
http://imgur.com/a/1DxQv

Somehow a similar config I used transferred all my 100IV mons and I'm left with a inventory of 250 mons that wont transfer or evolve even though they meet both criteria. 

I generated this default conf and then modified it to keep 100iv mon above 500 CP. Keep pokemon is set to 1 so this should expectedly keep the 1 highest IV mon, and transfer all duplicates unless they are both 100iv and over 500cp unless they have enough candy for evolution, and only then should the number of evolvable pokemon be kept. 

[10:32:33] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:32:36] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:32:39] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:32:40] (POKESTOP) Name: バードハウス XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemGreatBall, Lat: 35.717517, Long: 139.770778
[10:32:41] (INFO) Traveling to Pokestop: ゴリラ舎 (56m)(11seconds)
[10:32:42] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:32:46] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:32:49] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[10:33:52] (UPDATE) [Evolves] Potential Evolves: 0
I have evolvable mons and transferrable ones due to lack of candy but bot does not behave as expected. 

(edit: I do still have some of the original mons, but some are missing, either way there are mons that can be evolved, transferred due to lack of candy, and kept due to being highest iv value, or duplicates above 100iv and 500cp)

**Comment by ChemiHatake** [comment]
'  "KeepPokemonsThatCanEvolve": true,' There's a problem with this function at the moment, It keeps all the pokemon of the type that can evolve instead of just 1 or 2.

if you want it to transfer them all change it to false.

**Comment by darkendvoid** [comment]
I would prefer that it evolve them as the conditions have been met, but its reporting evolveable mons as 0.

**Comment by ChemiHatake** [comment]
Are you sure you have enough candies?

**Comment by ChemiHatake** [comment]
I found the problem,
'  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,'
it will only evolve pokemon with more than 95% iv
set it to false

**Comment by darkendvoid** [comment]
Sorry it appears I posted the old link - http://pastebin.com/eFNa4X7Y

  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,

these are my current settings that I was testing with. 

Yes there is enough candy to evolve most of all mons I have in my inventory, extra mons that cant be evolved should be transfered but it appears theres issues with the keeppokemonsthatcanevolve and evolveallpokemonswithenoughcandy .

**Comment by darkzurvan** [comment]
I'm having roughly the same problem as you, and I've seen plenty of other people reporting something similar. For me, anything on the evolve list won't transfer and nothing automatically evolves, but duplicates of mons not on the evolve list transfer fine. Some of the new parameters aren't being friendly with each other. I'm fairly sure the devs are aware and have said it will "be fixed in the next release, be patient." on other similar posts. Fingers crossed.

**Comment by darkendvoid** [comment]
@darkzurvan Hopefully so, submitted this in an attempt to provide as much information on the issue as possible, if mods determine this is the same issue as know open issue they are welcome to close it

**Comment by xeniusw** [comment]
You need to add those pokemons to   

"PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "zubat",
    "spearow",
    "drowzee",
    "pidgey",
    "rattata"

**Comment by darkendvoid** [comment]
@xeniusw they are already in the config I posted.

**Comment by darkzurvan** [comment]
@xeniusw Yeah that's the problem, pokemon specifically listed in the pokemonstoevolve list seem to be exempt from being transferred for us, regardless of candy amount or settings related.

**Comment by darkendvoid** [comment]
@darkzurvan The list is causing transfer errors for me as well as the fact that it's saying I have 0 mons to evolve but actually have candy for 60+

**Comment by sebastianbrandner** [comment]
in 0.6 there may be a bug with this

in 0.5 this settings worked well, it kept only the best pokemons to evolve and the amount depends on the number of candy.

now it keeps ALL pokemons that can evolve which is useless, because you need to catch more pks to get more candy to evolve, so this should be fixed in the code and not via config adoptions

**Comment by darkendvoid** [comment]
I cant confirm if the issue is fully fixed but it is transferring in 6.3

**Comment by darkzurvan** [comment]
@darkendvoid Yeah I won't confirm just yet either but 0.6.3 does seem to have fixed most of the previous issues. Maybe my biggest problem was trusting auto-update to get me out of the crappy 0.5.0 release it got me in to.
