### ISSUE TITLE
bot transfered all of my pokemon lol

### ISSUE THREAD

**Issue by xspel** [NECROBOTIO/NecroBot#2350]
`"KeepMinCp": 2500,
  "KeepMinIvPercentage": 99.9,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,`

I set like this and all pokemons are gone except the cp2500+ and iv99.9+.

**Comment by ChemiHatake** [comment]
"KeepMinCp": 2500, - it will only *keep* pokemon with more than  2500 cp
OR
"KeepMinIvPercentage": 99.9, - it will only keep pokemon with 99.9%+ iv...

**Comment by emwedk** [comment]
Change 
  "TransferWeakPokemon": false,

issue from .5.0

**Comment by xspel** [comment]
@emwedk Right!!!! Thanks. I just changed that to true then my pokemons are gone. haha
