### ISSUE TITLE
NecroBot: from 'educational use ONLY' to commercial usage.

### ISSUE THREAD

**Issue by fklosowski** [NECROBOTIO/NecroBot#2351]
Hello,

allegro.pl, the polish auction service allows people to sell Pokemon Go game level boosting, which means technically, that sellers use NecroBot to help their customers to gain XP, powerful creatures, and items.

Here's the link to auctions' listing where some people offers this service for even about 50$:

http://allegro.pl/listing/listing.php?order=pd&string=pokemon%20go%20boost&bmatch=base-relevance-uni-1-3-0613

I only found this email address to contact this auction service:

prasa@allegro.pl

Cheers

**Comment by emwedk** [comment]
very safe to give away your google acc ;)

**Comment by Wcidd** [comment]
Cant be sure they are using necrobot in any way

**Comment by fklosowski** [comment]
How then, people from Poland promise in their auctions' descriptions they are going to catch Pokemon creatures in New York, Central Park and other locations across the globe?
