### ISSUE TITLE
Bot using greatballs and ultraballs when settings are set like this

### ISSUE THREAD

**Issue by athanatos1** [NECROBOTIO/NecroBot#2353]
I have my settings like this when sniping, but it still uses the great and ultra balls...
  "UseGreatBallAboveCp": 2000,
  "UseUltraBallAboveCp": 2500,
  "UseMasterBallAboveCp": 3000,
  "UseGreatBallAboveIv": 90,
  "UseUltraBallAboveIv": 100,
  "UseGreatBallBelowCatchProbability": 0.09,
  "UseUltraBallBelowCatchProbability": 0.08,
  "UseMasterBallBelowCatchProbability": 0.05

http://prntscr.com/c0wz0q

wtf?

**Comment by emwedk** [comment]
maybe sniping has it's own settings for use of pokeballs - maybe hence it isn't using a regular pokeball for a 27CP Charizard? XD

**Comment by SDMU** [comment]
i think the program has its own rules for catching pokemon like charizard

**Comment by bxgitter** [comment]
It makes perfect sense. The chance of catching the charizard is listed as 0.0288 (2.88%). Your setting is
"UseGreatBallBelowCatchProbability": 0.09,
"UseUltraBallBelowCatchProbability": 0.08,
"UseMasterBallBelowCatchProbability": 0.05
So anything below 0.05 (5%) will use masterball and if you don't have masterball then you will use ultraball.

**Comment by athanatos1** [comment]
Ahh. So that's how the math works? I thought percents worked like this 1.00 = 1 % 10.0 = 10 %, etc.

**Comment by bxgitter** [comment]
Mathematically speaking,
1% = 1 percent
1.00 = 100%
0.05 = 5%
Probability of 0.08 = 8%

With the settings, there is a little inconsistency as some are in percentage and some are in probability.
When the setting has "percentage" in the name, then the number is referring to %. When it says probability, then use a decimal.
