### ISSUE TITLE
Transferring Pokemon based on moves and IV

### ISSUE THREAD

**Issue by abali1** [NECROBOTIO/NecroBot#2354]
Is there anyway to tweak the settings in config to transfer pokemon based on their moves and IV. 
So for example, you have a pidgey with certain movies and an IV of 80 and then you catch a podgy with moves that are already preset that you wanna keep and an IV of 70. It should priorities the moves first and then if you catch another one with a greater IV, it transfers them.

Because i saw moves in config but don't know how it works. 

Does that make sense? Can anyone help?

Thanks

**Comment by emwedk** [comment]
do 
  "DumpPokemonStats": false,

run the app for 5-10 seconds (till the "dumps" folder shows up)
open your folder where Necro is installed
and open the file (preferably with notepad++)
then let's take Arcanine - 6 commas ahead, you'll see a move, might be called (DragonBreathFast) - which is a kind of weak move (6dmg if i remember correct) 

you'll need to know which moves damages the most to get the most out of it

then you open your config.ini
ctrl+f and search for "PokemonsTransferFilter"
paste in below the PokemonsTransferFilter line

"Arcanine": {
      "KeepMinCp": 2000,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 6,
      "Moves": [FireFangFast,Flamethrower],
      "KeepMinOperator": "and"
    },

or something a like
Hope it helped you

**Comment by abali1** [comment]
Should it not be DumpPokemonStats:True??

**Comment by emwedk** [comment]
Yes sir ;) ty

**Comment by abali1** [comment]
Quick question, is this going to cause theoretically the bot to store 6 min pokemon of arcaninie, and if KeepMinDuplicatePokemon: 2, it will only keep 2?

**Comment by simplyphp** [comment]
It would keep 3 because 2 duplicates + 1 original =3

**Comment by simplyphp** [comment]
Fixed in #2367

**Comment by darkfriend77** [comment]
How does the AND / OR apply on the moves ...

A)
- cp or iv or moves
- cp and iv and moves

B)
- cp and moves or iv and moves
- cp and moved and iv and moves
