### ISSUE TITLE
[HELP] sniping isnt working last few days

### ISSUE THREAD

**Issue by rherartt** [NECROBOTIO/NecroBot#2355]
here's my config:

"TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.774578,
  "DefaultLongitude": -73.972774,
  "WalkingSpeedInKilometerPerHour": 120.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 320,
  "DelayBetweenPokemonCatch": 320,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 99.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 70,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 15,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokeballsToKeep": 320,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,
  "TotalAmountOfBerriesToKeep": 0,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85,
  "UseUltraBallAboveIv": 95,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,

**Comment by actisys** [comment]
download latest version and go to [wiki there to grab ](https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide)

**Comment by rherartt** [comment]
i already have the latest version and i think i have the right settings, the problem might be something else
