### ISSUE TITLE
[Additional Feature] to #2346 's

### ISSUE THREAD

**Issue by emwedk** [NECROBOTIO/NecroBot#2358]
In addition to #2346 's issue

Since information is stacking up in the application title, 
it might be around time to switch CMD out with CMDer 

It's possible to split screen a CMDer - tho im not sure if it's possible to make it fixed absolution, so the info split would only be as tall as needed at the top

I bet it's writable, i just don't have the skills

![cmder-split](https://cloud.githubusercontent.com/assets/13709064/17351426/ab088c5a-592e-11e6-8ace-b765bd50dd41.png)

**Comment by psc0304** [comment]
If you ever used any Bitcoin mining application, they have a fixed section which keeps showing you all the info, and the below will be lines popping up. 
Like this: http://i.stack.imgur.com/RwFtk.png

**Comment by emwedk** [comment]
i've never done that Kappa - true story tho
didn't know it is possible in CMD!

btw - set a "!" in front of the start of your url to show the image

**Comment by nfettinger** [comment]
This would require a third party installation to run the program. Why not just edit the console prints to keep a persistent section. I would happily work on this if it would be beneficial.
