### ISSUE TITLE
Removal of one line brings 100% improvement of XP per hour

### ISSUE THREAD

**Issue by xiachaolun** [NECROBOTIO/NecroBot#2359]
PoGo.NecroBot.CLI/ConsoleEventListener.cs:  **Logger.Write(session.Translation.GetTranslation(TranslationString.RequireInputText))**

With this line, every time the bot logs in, I have to press a key. When some exception occurs, the bot will automatically re-log in, however, it will get blocked because I am away from keyboard.

**Comment by SDMU** [comment]
does 'StartupWelcomeDelay'=false bring about the same problem ?

**Comment by xiachaolun** [comment]
@SDMU By setting the delay to false, it solves the problem.
