### ISSUE TITLE
Delay between catching pokemon via manual sniping

### ISSUE THREAD

**Issue by Briskey** [NECROBOTIO/NecroBot#2361]
I previously made a ticket about this same issue, but it was closed, and i was asked to reopen it if it was still present in 0.6.2.  Well, it is, so i decided to reopen the ticket.  First off, the issue is that while manual sniping, the bot seems to ignore delay rules, and has a random delay of anywhere from 3-6 seconds in between catching pokemon.  I have all delay settings set to 0 and have tried just about everything from 0-5000, and nothing changes.  It should be pretty easy to replicate, as there are not any special conditions, and it seems to happen every time you manual snipe.  Currently my bot manual snipes for weedles, pidgeys, and caterpies.  It then farms pokestops and evolves once the inventory is at 90%.  With this kind of config, having a 3-6 second delay between catches while sniping is HUGE.  400-500% slower than it would be otherwise.  If you want to look further into this issue, I can post screenshots and/or my config, however I'm positive it's not user error.

**Comment by emwedk** [comment]
as i just mentioned in #2353 
the sniping might have it's own settings for most of all

**Comment by Briskey** [comment]
Are there any devs that can confirm this?

**Comment by Mikey9191** [comment]
Hi Briskey, i am having the exact same problem. i was trying one of those mass XP configs to farm and evolve pokemons and as you mentioned there is an unnecessary delay and i don't know why. i have also tried changing the settings with no luck. have you been able to find a solution?

**Comment by Briskey** [comment]
Nope, still nothing.
