### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by Negatory** [NECROBOTIO/NecroBot#2362]
When I open the release and open the config file, the only file i see is translation and not the login files. Any suggestions to fix this?

**Comment by Oolaruu** [comment]
You have to double-click on the .exe to have 
Auth.json
Config.json
into the Config folder.

Give it a try :)

**Comment by FAndresCO** [comment]
necrobot.exe opens to create files

**Comment by huhjess** [comment]
I have the same problem. I have a mac. I used crossover, however, no files were created when I run the exe on crossover. does anyone know why
