### ISSUE TITLE
recycling pokeballs

### ISSUE THREAD

**Issue by FAndresCO** [NECROBOTIO/NecroBot#2363]
I have a problem, is that the bot is recycling all basic pokeballs, and leave me 0.

You can change the limit pokeballs in inventory?
translated with google translator

![captura de pantalla 19](https://cloud.githubusercontent.com/assets/20806975/17352225/7f592ef4-58fa-11e6-9623-a62f2ec99124.png)

translated with google translator

**Comment by shendude** [comment]
The bot recycles pokeballs in a "smart" fashion. As in it recycles the worst balls first and tries to keep the better ones, up to the TotalAmountOfPokebalsToKeep value (which in this case is likely set to 120). I do not believe there is currently a setting to save regular pokeballs specifically.

**Comment by FAndresCO** [comment]
ooooo Thanks :+1:
