### ISSUE TITLE
doubt in drafting config.json

### ISSUE THREAD

**Issue by FAndresCO** [NECROBOTIO/NecroBot#2368]
doubt in drafting config.json
In version 0.6.1 and 0.6.2, "TotalAmountOfPokeballsToKeep" appears double LL.
In version 0.5 "TotalAmountOfPokebalsToKeep" appears with an L.

This may generate some error ??
![captura](https://cloud.githubusercontent.com/assets/20806975/17352540/e727c00c-58fc-11e6-9001-8f1c53f74188.PNG)

**Comment by Whosdaman** [comment]
It was a typo that the devs fixed
