### ISSUE TITLE
about pogo location feeder

### ISSUE THREAD

**Issue by jihaoran0509** [NECROBOTIO/NecroBot#2369]
When I am using the pogo location feeder, if there is 2 or more pokemons appeared together, the necrobot will not catch them all

**Comment by NurAdam** [comment]
i got that a lot too. Anyone know why that happen? care to explain to us?

**Comment by Jurplez** [comment]
Actually, this is not the case, I've been having problems too. It's just skipping pokemon that aren't on the filter list, despite even having it on false.

**Comment by jihaoran0509** [comment]
Maybe to change the

> MinDelayBetweenSnipes

**Comment by simplyphp** [comment]
Fixed
