### ISSUE TITLE
Transfer weak pokemon

### ISSUE THREAD

**Issue by SDMU** [NECROBOTIO/NecroBot#2370]
Is there a set CP or IV or list of pokemon which the program considers as weak ? It will be helpful to know how the program decides which pokemon are weak . Thank You .

**Comment by xtrsyz** [comment]
Below value set on
"KeepMinCp"
"KeepMinIvPercentage"

**Comment by SDMU** [comment]
but then wouldn't " keep duplicate"=0 achieve the same result ?

**Comment by ANR2ME** [comment]
I think "keep duplicate" = 0 will keep at least 1 pokemon, while TransferWeakPokemo will transfer all (non-favorited) pokemons, including the best one (if it's below the threshold)

**Comment by SDMU** [comment]
Let's hope what you say is true because I want to keep 1 of each pokemon I catch , the condition being that it should be the highest one :)

**Comment by xtrsyz** [comment]
if you want to keep 1 of each pokemon, set "TransferWeakPokemon": false
