### ISSUE TITLE
[locale] zh_CN pokemon names from ID 1 to 151

### ISSUE THREAD

**Issue by MapleEve** [NECROBOTIO/NecroBot#2374]
妙蛙种子,
        妙蛙草,
        妙蛙花,
        小火龙,
        火恐龙,
        喷火龙,
        杰尼龟,
        卡咪龟,
        水箭龟,
        绿毛虫,
        铁甲蛹,
        巴大蝴,
        独角虫,
        铁壳蛹,
        大针蜂,
        波波,
        比比鸟,
        比雕,
        小拉达,
        拉达,
        烈雀,
        大嘴雀,
        阿柏蛇,
        阿柏怪,
        皮卡丘,
        雷丘,
        穿山鼠,
        穿山王,
        尼多兰母,
        尼多娜,
        尼多后,
        尼多兰公,
        尼多力诺,
        尼多王,
        皮皮,
        皮可西,
        六尾,
        九尾,
        胖丁,
        胖可丁,
        超音蝠,
        大嘴蝠,
        走路草,
        臭臭花,
        霸王花,
        派拉斯,
        派拉斯特,
        毛球,
        末入蛾,
        地鼠,
        三地鼠,
        喵喵,
        猫老大,
        可达鸭,
        哥达鸭,
        猴怪,
        火爆猴,
        卡蒂狗,
        风速狗,
        蚊香蝌蚪,
        蚊香蛙,
        快泳蛙,
        凯西,
        勇基拉,
        胡地,
        腕力,
        豪力,
        怪力,
        喇叭芽,
        口呆花,
        大食花,
        玛瑙水母,
        毒刺水母,
        小拳石,
        隆隆石,
        隆隆岩,
        小火马,
        烈焰马,
        呆呆兽,
        呆壳兽,
        小磁怪,
        三合一磁怪,
        大葱鸭,
        嘟嘟,
        嘟嘟利,
        小海狮,
        白海狮,
        臭泥,
        臭臭泥,
        大舌贝,
        刺甲贝,
        鬼斯,
        鬼斯通,
        耿鬼,
        大岩蛇,
        索利普,
        索利柏,
        大钳蟹,
        巨钳蟹,
        闪电球,
        顽皮弹,
        蛋蛋,
        椰蛋树,
        可拉可拉,
        嘎啦嘎啦,
        沙瓦朗,
        艾比郎,
        大舌头,
        瓦斯弹,
        双弹瓦斯,
        铁甲犀牛,
        铁甲暴龙,
        吉利蛋,
        蔓藤怪,
        袋龙,
        墨海马,
        海刺龙,
        角金鱼,
        金鱼王,
        海星星,
        宝石海星,
        吸盘魔偶,
        飞天螳螂,
        迷唇姐,
        电击兽,
        鸭嘴火龙,
        大甲,
        肯泰罗,
        鲤鱼王,
        暴鲤龙,
        乘龙,
        百变怪,
        伊布,
        水伊布,
        雷伊布,
        火伊布,
        3D龙,
        菊石兽,
        多刺菊石兽,
        化石盔,
        镰刀盔,
        化石翼龙,
        卡比兽,
        急冻鸟,
        闪电鸟,
        火焰鸟,
        迷你龙,
        哈克龙,
        快龙,
        超梦,
        梦幻

Appreciate if someone added it into future translations.

**Comment by sebastianbrandner** [comment]
just clone the git repo and add it to the translations.<lang-code>.json files if you want to translate something. i think this would help the developers

**Comment by Wcidd** [comment]
Do what above says
