### ISSUE TITLE
[featurerequest]LANG:JP

### ISSUE THREAD

**Issue by B100c** [NECROBOTIO/NecroBot#2375]
I have created File:translation.jp.json.
Incomplete , but it should be easy to understand in Japanese.

**Comment by B100c** [comment]
"Key": "pokeball",
      "Value": "モンスターボール"
    },
    {
      "Key": "greatPokeball",
      "Value": "スーパーボール"
    },
    {
      "Key": "ultraPokeball",
      "Value": "ハイパーボール"
    },
    {
      "Key": "masterPokeball",
      "Value": "マスターボール"



  "PokemonStrings": [
    {
      "Key": "bulbasaur",
      "Value": "フシギダネ"
    },
    {
      "Key": "ivysaur",
      "Value": "フシギソウ"
    },
    {
      "Key": "venusaur",
      "Value": "フシギバナ"
    },
    {
      "Key": "charmander",
      "Value": "ヒトカゲ"
    },
    {
      "Key": "charmeleon",
      "Value": "リザード"
    },
    {
      "Key": "charizard",
      "Value": "リザードン"
    },
    {
      "Key": "squirtle",
      "Value": "ゼニガメ"
    },
    {
      "Key": "wartortle",
      "Value": "カメール"
    },
    {
      "Key": "blastoise",
      "Value": "カメックス"
    },
    {
      "Key": "caterpie",
      "Value": "キャタピー"
    },
    {
      "Key": "metapod",
      "Value": "トランセル"
    },
    {
      "Key": "butterfree",
      "Value": "バタフリー"
    },
    {
      "Key": "weedle",
      "Value": "ビードル"
    },
    {
      "Key": "kakuna",
      "Value": "コクーン"
    },
    {
      "Key": "beedrill",
      "Value": "スピアー"
    },
    {
      "Key": "pidgey",
      "Value": "ポッポ"
    },
    {
      "Key": "pidgeotto",
      "Value": "ピジョン"
    },
    {
      "Key": "pidgeot",
      "Value": "ピジョット"
    },
    {
      "Key": "rattata",
      "Value": "コラッタ"
    },
    {
      "Key": "raticate",
      "Value": "ラッタ"
    },
    {
      "Key": "spearow",
      "Value": "オニスズメ"
    },
    {
      "Key": "fearow",
      "Value": "オニドリル"
    },
    {
      "Key": "ekans",
      "Value": "アーボ"
    },
    {
      "Key": "arbok",
      "Value": "アーボック"
    },
    {
      "Key": "pikachu",
      "Value": "ピカチュウ"
    },
    {
      "Key": "raichu",
      "Value": "ライチュウ"
    },
    {
      "Key": "sandshrew",
      "Value": "サンド"
    },
    {
      "Key": "sandslash",
      "Value": "サンドパン"
    },
    {
      "Key": "nidoranFemale",
      "Value": "ニドラン♀"
    },
    {
      "Key": "nidorina",
      "Value": "ニドリーナ"
    },
    {
      "Key": "nidoqueen",
      "Value": "ニドクイン"
    },
    {
      "Key": "nidoranMale",
      "Value": "ニドラン♂"
    },
    {
      "Key": "nidorino",
      "Value": "ニドリーノ"
    },
    {
      "Key": "nidoking",
      "Value": "ニドキング"
    },
    {
      "Key": "clefairy",
      "Value": "ピッピ"
    },
    {
      "Key": "clefable",
      "Value": "ピクシー"
    },
    {
      "Key": "vulpix",
      "Value": "ロコン"
    },
    {
      "Key": "ninetales",
      "Value": "キュウコン"
    },
    {
      "Key": "jigglypuff",
      "Value": "プリン"
    },
    {
      "Key": "wigglytuff",
      "Value": "プクリン"
    },
    {
      "Key": "zubat",
      "Value": "ズバット"
    },
    {
      "Key": "golbat",
      "Value": "ゴルバット"
    },
    {
      "Key": "oddish",
      "Value": "ナゾノクサ"
    },
    {
      "Key": "gloom",
      "Value": "クサイハナ"
    },
    {
      "Key": "vileplume",
      "Value": "ラフレシア"
    },
    {
      "Key": "paras",
      "Value": "パラス"
    },
    {
      "Key": "parasect",
      "Value": "パラセクト"
    },
    {
      "Key": "venonat",
      "Value": "コンパン"
    },
    {
      "Key": "venomoth",
      "Value": "モルフォン"
    },
    {
      "Key": "diglett",
      "Value": "ディグダ"
    },
    {
      "Key": "dugtrio",
      "Value": "ダグトリオ"
    },
    {
      "Key": "meowth",
      "Value": "ニャース"
    },
    {
      "Key": "persian",
      "Value": "ペルシアン"
    },
    {
      "Key": "psyduck",
      "Value": "コダック"
    },
    {
      "Key": "golduck",
      "Value": "ゴルダック"
    },
    {
      "Key": "mankey",
      "Value": "マンキー"
    },
    {
      "Key": "primeape",
      "Value": "オコリザル"
    },
    {
      "Key": "growlithe",
      "Value": "ガーディ"
    },
    {
      "Key": "arcanine",
      "Value": "ウインディ"
    },
    {
      "Key": "poliwag",
      "Value": "ニョロモ"
    },
    {
      "Key": "poliwhirl",
      "Value": "ニョロゾ"
    },
    {
      "Key": "poliwrath",
      "Value": "ニョロボン"
    },
    {
      "Key": "abra",
      "Value": "ケーシィ"
    },
    {
      "Key": "kadabra",
      "Value": "ユンゲラー"
    },
    {
      "Key": "alakazam",
      "Value": "フーディン"
    },
    {
      "Key": "machop",
      "Value": "ワンリキー"
    },
    {
      "Key": "machoke",
      "Value": "ゴーリキー"
    },
    {
      "Key": "machamp",
      "Value": "カイリキー"
    },
    {
      "Key": "bellsprout",
      "Value": "マダツボミ"
    },
    {
      "Key": "weepinbell",
      "Value": "ウツドン"
    },
    {
      "Key": "victreebel",
      "Value": "ウツボット"
    },
    {
      "Key": "tentacool",
      "Value": "メノクラゲ"
    },
    {
      "Key": "tentacruel",
      "Value": "ドククラゲ"
    },
    {
      "Key": "geodude",
      "Value": "イシツブテ"
    },
    {
      "Key": "graveler",
      "Value": "ゴローン"
    },
    {
      "Key": "golem",
      "Value": "ゴローニャ"
    },
    {
      "Key": "ponyta",
      "Value": "ポニータ"
    },
    {
      "Key": "rapidash",
      "Value": "ギャロップ"
    },
    {
      "Key": "slowpoke",
      "Value": "ヤドン"
    },
    {
      "Key": "slowbro",
      "Value": "ヤドラン"
    },
    {
      "Key": "magnemite",
      "Value": "コイル"
    },
    {
      "Key": "magneton",
      "Value": "レアコイル"
    },
    {
      "Key": "farfetchd",
      "Value": "カモネギ"
    },
    {
      "Key": "doduo",
      "Value": "ドードー"
    },
    {
      "Key": "dodrio",
      "Value": "ドードリオ"
    },
    {
      "Key": "seel",
      "Value": "パウワウ"
    },
    {
      "Key": "dewgong",
      "Value": "ジュゴン"
    },
    {
      "Key": "grimer",
      "Value": "ベトベター"
    },
    {
      "Key": "muk",
      "Value": "ベトベトン"
    },
    {
      "Key": "shellder",
      "Value": "シェルダー"
    },
    {
      "Key": "cloyster",
      "Value": "パルシェン"
    },
    {
      "Key": "gastly",
      "Value": "ゴース"
    },
    {
      "Key": "haunter",
      "Value": "ゴースト"
    },
    {
      "Key": "gengar",
      "Value": "ゲンガー"
    },
    {
      "Key": "onix",
      "Value": "イワーク"
    },
    {
      "Key": "drowzee",
      "Value": "スリープ"
    },
    {
      "Key": "hypno",
      "Value": "スリーパー"
    },
    {
      "Key": "krabby",
      "Value": "クラブ"
    },
    {
      "Key": "kingler",
      "Value": "キングラー"
    },
    {
      "Key": "voltorb",
      "Value": "ビリリダマ"
    },
    {
      "Key": "electrode",
      "Value": "マルマイン"
    },
    {
      "Key": "exeggcute",
      "Value": "タマタマ"
    },
    {
      "Key": "exeggutor",
      "Value": "ナッシー"
    },
    {
      "Key": "cubone",
      "Value": "カラカラ"
    },
    {
      "Key": "marowak",
      "Value": "ガラガラ"
    },
    {
      "Key": "hitmonlee",
      "Value": "サワムラー"
    },
    {
      "Key": "hitmonchan",
      "Value": "エビワラー"
    },
    {
      "Key": "lickitung",
      "Value": "ベロリンガ"
    },
    {
      "Key": "koffing",
      "Value": "ドガース"
    },
    {
      "Key": "weezing",
      "Value": "マタドガス"
    },
    {
      "Key": "rhyhorn",
      "Value": "サイホーン"
    },
    {
      "Key": "rhydon",
      "Value": "サイドン"
    },
    {
      "Key": "chansey",
      "Value": "ラッキー"
    },
    {
      "Key": "tangela",
      "Value": "モンジャラ"
    },
    {
      "Key": "kangaskhan",
      "Value": "ガルーラ"
    },
    {
      "Key": "horsea",
      "Value": "タッツー"
    },
    {
      "Key": "seadra",
      "Value": "シードラ"
    },
    {
      "Key": "goldeen",
      "Value": "トサキント"
    },
    {
      "Key": "seaking",
      "Value": "アズマオウ"
    },
    {
      "Key": "staryu",
      "Value": "ヒトデマン"
    },
    {
      "Key": "starmie",
      "Value": "スターミー"
    },
    {
      "Key": "mrMime",
      "Value": "バリヤード"
    },
    {
      "Key": "scyther",
      "Value": "ストライク"
    },
    {
      "Key": "jynx",
      "Value": "ルージュラ"
    },
    {
      "Key": "electabuzz",
      "Value": "エレブー"
    },
    {
      "Key": "magmar",
      "Value": "ブーバー"
    },
    {
      "Key": "pinsir",
      "Value": "カイロス"
    },
    {
      "Key": "tauros",
      "Value": "ケンタロス"
    },
    {
      "Key": "magikarp",
      "Value": "コイキング"
    },
    {
      "Key": "gyarados",
      "Value": "ギャラドス"
    },
    {
      "Key": "lapras",
      "Value": "ラプラス"
    },
    {
      "Key": "ditto",
      "Value": "メタモン"
    },
    {
      "Key": "eevee",
      "Value": "イーブイ"
    },
    {
      "Key": "vaporeon",
      "Value": "シャワーズ"
    },
    {
      "Key": "jolteon",
      "Value": "サンダース"
    },
    {
      "Key": "flareon",
      "Value": "ブースター"
    },
    {
      "Key": "porygon",
      "Value": "ポリゴン"
    },
    {
      "Key": "omanyte",
      "Value": "オムナイト"
    },
    {
      "Key": "omastar",
      "Value": "オムスター"
    },
    {
      "Key": "kabuto",
      "Value": "カブト"
    },
    {
      "Key": "kabutops",
      "Value": "カブトプス"
    },
    {
      "Key": "aerodactyl",
      "Value": "プテラ"
    },
    {
      "Key": "snorlax",
      "Value": "カビゴン"
    },
    {
      "Key": "articuno",
      "Value": "フリーザー"
    },
    {
      "Key": "zapdos",
      "Value": "サンダー"
    },
    {
      "Key": "moltres",
      "Value": "ファイヤー"
    },
    {
      "Key": "dratini",
      "Value": "ミニリュウ"
    },
    {
      "Key": "dragonair",
      "Value": "ハクリュー"
    },
    {
      "Key": "dragonite",
      "Value": "カイリュー"
    },
    {
      "Key": "mewtwo",
      "Value": "ミュウツー"
    },
    {
      "Key": "mew",
      "Value": "ミュウ"
    }
  ]
}

**Comment by B100c** [comment]
I want you to support them with updates.

**Comment by Oolaruu** [comment]
OK, I'm on it.
What about the other strings, keep in english ?

**Comment by Wcidd** [comment]
Pull request

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2496
