### ISSUE TITLE
Since this new thing im keeping unlimited of pokemons because they meet the move requirement of nothing?

### ISSUE THREAD

**Issue by xeniusw** [NECROBOTIO/NecroBot#2377]
How do i set up the moves so my shit doesn't return with an error?

    "Machamp": {
      "KeepMinCp": 1700,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [KarateChopFast],[CrossChop],
      "KeepMinOperator": "or"

I've tried

      "Moves": [KarateChopFast,CrossChop],
      "Moves": [KarateChopFast],[CrossChop],

**Comment by xiachaolun** [comment]
No, it is because the logic of transferring does not work.

**Comment by Seyrenvox** [comment]
the transfering logic are work. but those "Move" setting will override the operator setting, as i elaborated here https://github.com/NECROBOTIO/NecroBot/issues/2364

**Comment by simplyphp** [comment]
Resolved in #2367
