### ISSUE TITLE
Pokemon transfer

### ISSUE THREAD

**Issue by chimichandra** [NECROBOTIO/NecroBot#2378]
Since pokemon transfer logic is all fucked up now and NO SETTING works, can we a global override be implemented to prevent transferring any favorited pokemon?

At least those manually favorite might be safe next time...

**Comment by Whosdaman** [comment]
You can't transfer favorited Pokemon anyway. It's built into the app

**Comment by chimichandra** [comment]
Never mind that. How do i delete this?
