### ISSUE TITLE
[suggestion] dump items and eggs

### ISSUE THREAD

**Issue by reinforcers** [NECROBOTIO/NecroBot#2380]
just as title says dump not only pokemons but also  items and eggs in inventory would be helpful.

**Comment by HansonWK** [comment]
It already does dump items. You can;t dump eggs unfortunately.

To dump items, set:

`  "TotalAmountOfPokeballsToKeep": 250,
  "TotalAmountOfPotionsToKeep": 1,
  "TotalAmountOfRevivesToKeep": 1,
  "TotalAmountOfBerriesToKeep": 30,

and

`"ItemRecycleFilter":`
