### ISSUE TITLE
Google login troubles

### ISSUE THREAD

**Issue by INeededAUsername** [NECROBOTIO/NecroBot#2383]
![image](https://cloud.githubusercontent.com/assets/20808233/17353703/36bbfd46-5910-11e6-85ee-661abef77ea5.png)
Before 6.3, necrobot would keep showing logging in using google over and over again, but now it's not doing anything at all. Help?

**Comment by Kay1972** [comment]
I had the same issue, rebooting my PC fixed it.  (Weird, but it did)!

**Comment by INeededAUsername** [comment]
I rebooted. Nothing happened.

**Comment by INeededAUsername** [comment]
The weirdest thing is that it works perfectly fine for my alt. I'm not banned or anything.

**Comment by simplyphp** [comment]
Must be something with the sign in servers, no issues here.
