### ISSUE TITLE
Keep Pokemon Base on 2 set of Move?

### ISSUE THREAD

**Issue by linuslee0216** [NECROBOTIO/NecroBot#2384]
As there are recommend Offensive Movesets and Defensive Movesets  for Pokemon, can I set Keep Pokemon Base on 2 set of Move? Like this?

"Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["dragonBreathFast","dragonClaw"],
      "KeepMinOperator": "and"
    },

"Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["steelWingFast","hyperBeam"],
      "KeepMinOperator": "and"
    },

**Comment by Unentertained** [comment]
The pokemon "Dragonair" can not learn the moves "Steel Wing" or "Dragon Claw".

As far as filtering pokemon based on their moves; this has already been suggested in issues #1570 #1753

**Comment by linuslee0216** [comment]
Thanks for reply. Sorry for typo, I mean Dragonite. 
And you misunderstand my question. I want to Keep Pokemon Base on 2 sets of Moves not one set of Moves.
e.g. I want to keep Dragonites that learned Steel Wing and Dragon Claw, also Dragon Breath and  Hyper Beam . Could it be possible?
