### ISSUE TITLE
[suggestion] KeepMinOperator per Pokemon

### ISSUE THREAD

**Issue by streppelchen** [NECROBOTIO/NecroBot#2385]
20kilo on discord had the idea to setup KeepMinOperator per pokemon instead of globally, so you could chose individually which filter applies to which pokemon

    "Koffing": {
      "KeepMinCp": 850,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "and"
    },
    "Weezing": {
      "KeepMinCp": 1850,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"

  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 97.0,
  "KeepMinOperator": "or",           
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",

**Comment by simplyphp** [comment]
Already implemented :)
