### ISSUE TITLE
Sniping issue

### ISSUE THREAD

**Issue by freyying1234** [NECROBOTIO/NecroBot#2389]
I followed both the manual and automatic setup to snipe but none of them worked. I followed exactly the steps specified in the manual sniping option but I keep getting sniping server is offline. When I try the automatic sniping option, I can successfully run the server locally and connect necrobot to the server but after the connection is done, no pokemon or any server showed up in the pogolocationfeeder. The running server just hang at the line where it says a new connection from localhost:port.

**Comment by simplyphp** [comment]
This is a configuration issue on your end, sniping is working fine.

**Comment by freyying1234** [comment]
all of a sudden automatic sniping works
