### ISSUE TITLE
Deleting my files

### ISSUE THREAD

**Issue by XFirstlight** [NECROBOTIO/NecroBot#2393]
Every time you update the bot, my files in the same folder with necro bot.exe get renamed and some removed. I've lost hours of work already. I have auto update off and my config files and auth are fine.

It removed a python script I had in the same folder. I can't find that script anywhere on my system now.

**Comment by emwedk** [comment]
i've been testing it a couple hours ago #2344
and atleast for me, it only does it when i do the AutoUpdate
if i download the Relase.zip and past it on top, it wont happen

just make a backup of all files - it isn't bulletproof, even tho they are working hard af to try to make it ;)

**Comment by ANR2ME** [comment]
I lost all of my alternative config.json (with different hunting location each) a few version back >.<
I can only advice you to keep a backup config outside the folder where the EXE existed (to be safe).

**Comment by emwedk** [comment]
it has been fixed in 6.3 - they've been renamed to .old ;)
