### ISSUE TITLE
[SAMPLE] try this sample hopefully it will help

### ISSUE THREAD

**Issue by RoaderKills** [NECROBOTIO/NecroBot#2394]
this is my config file as of now... if you can tweak it further do so.. and post

[my sample config file.txt](https://github.com/NECROBOTIO/NecroBot/files/398683/my.sample.config.file.txt)

**Comment by ANR2ME** [comment]
What is the issue you're having?

**Comment by RoaderKills** [comment]
I want to make it better config in all parameters

**Comment by Wcidd** [comment]
Go to settings...
