### ISSUE TITLE
AND / OR not working at same time

### ISSUE THREAD

**Issue by 20kilo** [NECROBOTIO/NecroBot#2395]
As @Streppel already posted im trying to make both variables work at same time, i have config for all 151 pokemons all like that: 

    "Koffing": {
      "KeepMinCp": 850,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "and"
    },
    "Weezing": {
      "KeepMinCp": 1850,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"

Some AND and some OR, but the rule is not beeing followed correctly, the bot only obay the one in the begin of the config file as listed here:

  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 97.0,
  "KeepMinOperator": "or",                  <----------- HERE
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",

in this case only OR will be working, as this exemple under:

    "Growlithe": {
      "KeepMinCp": 850,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "and"
    },

he's keep cp850+ OR iv90+ and not the AND as it supposed to be!

**Comment by emwedk** [comment]
so it will erase both, or just one of the 2?

**Comment by IXSharks** [comment]
he's keep cp850+ OR iv90+ and not the AND as it supposed to be! dont understand ?

**Comment by actislav** [comment]
and in programmer definition :) which means Growlithe with cp850+ and the same time with iv90+

**Comment by abali1** [comment]
Would you be able to share your config with all the pokemon listed in the transfer list?? 
Also so the error thats occuring is, hes only storing CP850 or an IV90+ but not both?? If i got that right?

**Comment by actislav** [comment]
"he's keep cp850+ OR iv90+ and not the AND as it supposed to be!" for you case you mast use "or"

**Comment by abali1** [comment]
aah so for example. if i wanna keep only 90iv+ i should just have set as or on both the top of config and the transferlist?

**Comment by 20kilo** [comment]
yeah my explain was bad sorry,  
 "KeepMinOperator": "and"  should only keep the growlithe that have 850cp+ plus 90iv+ (same pokemon need to have both parameters i set)
 "KeepMinOperator": "or"  should keep both the growlithe that have 850cp+ or growlithe with 90iv+(only 1 parameters need to be meet)

**Comment by abali1** [comment]
@20kilo Did you say that you had all the pokemon listed under PokemonsTransferFilter?? If you did, would you mind sharing your config file, as i am looking to do the same thing as well.

**Comment by whiteshark-1975** [comment]
the code doesnt detect IV100 when using or with low cp value it works fine, 
 "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 3000.0,
  "UpgradePokemonIvMinimum": 99.0,
  "UpgradePokemonMinimumStatsOperator": "or",
i deleted the filter becoz i wanna go pretty straight with this,. same rule apply to all my pokemons. if IV 100 power up to max.

**Comment by Wcidd** [comment]
fixed 0.6.3
