### ISSUE TITLE
Bot ignoring pokeballs related configs?

### ISSUE THREAD

**Issue by TravisMeister** [NECROBOTIO/NecroBot#2396]
Somehow the bot seems to Ignore the configs that I have set.
```
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 1800,
  "UseGreatBallAboveIv": 95,
  "UseUltraBallAboveIv": 98,
  "UseGreatBallBelowCatchProbability": 0.5,
  "UseUltraBallBelowCatchProbability": 0.4,
  "UseMasterBallBelowCatchProbability": 0.05,
```

And even tho with these settings it still using Greater Balls on weaker pokemons, ignoring all the conditions above.
For example: https://i.gyazo.com/666738a7d9ae6844b23a558b0bf6f494.png

No wonder when I look at my items i always have 0 Greater/Ultra Balls.

**Comment by sliverfishes** [comment]
>   "UseGreatBallBelowCatchProbability": 0.5,
0.5 = 50% and that pokemon's chance was 40.01% so it used the great ball.

**Comment by A-Charvin** [comment]
The same issue since the bot used all the Ultra/Great balls on weaker pokemons. Ignoring the CP and IV settings. A fixed config settings?

**Comment by datwh0re** [comment]
im using:

"UseGreatBallAboveCp": 1200,
  "UseUltraBallAboveCp": 1500,
  "UseMasterBallAboveCp": 1800,
  "UseGreatBallAboveIv": 95,
  "UseUltraBallAboveIv": 98,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,

and it works perfectly, had the same issues like you before.

**Comment by Kostronor** [comment]
#2177 :)
