### ISSUE TITLE
Evolutions will not be transferred but kept if it is tier 3

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#2398]
Caterpie evolutions will end up keeping the metapods when it should be transferring metapods (imo). Is this working as intended?

**Comment by emwedk** [comment]
it's because it will always check to see if it has enough for evolving any of them
maybe they could do something alike, "remember if evolved to metapods" if, then wait to evolve till metapod is evolved

 tho im 100.0% sure they are aware of the issue ;)

**Comment by wetshrimp** [comment]
not sure if we are talking about the same thing. i'm trying to say that metapod should NOT be evolved into butterfree for the purpose of EXP and should be  transferred instead.
