### ISSUE TITLE
Stardust Deficiency!!!

### ISSUE THREAD

**Issue by oydoy** [NECROBOTIO/NecroBot#2400]
The XP farming is too effective! I have more levels than stardust to upgrade my pokemon. To get more stardust, could you make an option to do this?

1.) Wander around catching pokemons
2.) Go for pokestops after you use up all the pokeballs
3.) Once bag is filled, go wander for pokemon. 
4.) Repeat.

**Comment by emwedk** [comment]
i would really like to see that feature! upvoted

**Comment by ANR2ME** [comment]
You should configure it to only evolve/upgrade your best pokemons to use stardusts and candies more efficient, also using combination of CP,IV, and chance to use each balls efficiently  :)
