### ISSUE TITLE
Not using Razzberries when catching pokemon

### ISSUE THREAD

**Issue by BennySupreme** [NECROBOTIO/NecroBot#2401]
"UseBerriesMinCp": 800,
 "UseBerriesMinIv": 0.0,
 "UseBerriesBelowCatchProbability": 0.35,
 "UseBerriesOperator": "and",

Thats my config. Bot wont use berries at all even with pokemon under these circumstances.

**Comment by NurAdam** [comment]
why close ? is it working now?

**Comment by BennySupreme** [comment]
yeah, not sure why
