### ISSUE TITLE
Please help! How to fix this constant spam of Info every 10-30 seconds? Very Frustrating since new update!

### ISSUE THREAD

**Issue by mysticfury** [NECROBOTIO/NecroBot#2402]
May anybody please help me here with this problem?  Ever since I upgraded to 0.6.2 and 0.6.3 it's been doing this. I don't see any stupid settings on config.json that allows me to see what needs to change so it doesn't do this every 10-30 seconds. Any help on how to fix this? Was wondering if anyone can fix this issue. This wasn't happening prior to 0.6.2

My settings:
pastebin.com/MjawMe3t

![annoyingassnecrobotinfothing_03](https://cloud.githubusercontent.com/assets/20809140/17355684/38b5c1e4-5907-11e6-869e-5415349b700b.png)

**Comment by Rykee** [comment]
Happening to me too
![image](https://cloud.githubusercontent.com/assets/11543371/17355638/49e3945a-5952-11e6-97c0-ee930d29a3ee.png)

Temporary workaround: 
  "ShowPokeballCountsBeforeRecycle": false,

**Comment by Wcidd** [comment]
"ShowPokeballCountsBeforeRecycle": false,

**Comment by Rykee** [comment]
That's not a solution.. It still spams the info multiple times instead of doing it just once. @Wcidd
