### ISSUE TITLE
[Question] Many connections from IP = softban

### ISSUE THREAD

**Issue by tw0r** [NECROBOTIO/NecroBot#2403]
Too many connections from one IP leads to softban 
first: Looting failed
secon: No usable Pokestops found in your area

Tried from two different IPs at the same time and the one where was multiple bots get banned. 

What now? Set delay between player action or any other delay for longer time? Or what is the maximum of connection? 

I do have now the delays set on 500.

**Comment by markuznw** [comment]
How many do you use? :o

**Comment by tw0r** [comment]
Not so many ... fifty maybe?

**Comment by streppelchen** [comment]
50 connections from the same ip with a delay that's 1/10th of the default? really? if that isn't already causing problems right now, it will for sure.
use some vpn service or even vps and distribute them. and keep the DelayBetweenPlayerActions at 5000

**Comment by tw0r** [comment]
OK...seems good few days ago, now it causing bit troubles...Im going to make some changes...

**Comment by Wcidd** [comment]
questions in support
