### ISSUE TITLE
[Question]About Script

### ISSUE THREAD

**Issue by FreeHitss** [NECROBOTIO/NecroBot#2405]
"KeepMinOperator": "or",
  "UseBerriesOperator": "and"

can someone explain me this?

**Comment by emwedk** [comment]
"UseBerriesMinCp": 650,
OR (if none of the next 2 is true)
  "UseBerriesMinIv": 94.0,
OR (if the next isn't true)
  "UseBerriesBelowCatchProbability": 0.2,

else it's the other way around.

the AND is pretty self explanatory - it use berries on both MinCP, MinIV and CatchProb

the "KeepMinOperator": "and" is for 
  "KeepMinCp": 1600,
  "KeepMinIvPercentage": 98.0,

and the same rules apply
