### ISSUE TITLE
[Feature Request](half-advanced) Use PokeBalls Relative to Pokemon LVL & IV

### ISSUE THREAD

**Issue by emwedk** [NECROBOTIO/NecroBot#2406]
EDIT based on ANR2ME 's answer

> As i remember IV is a combination of ATK+STAMINA+DEF divided by something (i forgot)

> Edit: here is the commit 7b31ce2

tho, i guess my calculations still could work for the primary issue im adressing
- that one is forced to throw UltraBalls at 26CP, 100% IV Pokemons

~~If i've understood IV correctly, it is the Pokemon's LVL's current CP divided by it's max CP times 100
 e.g  current  /  max   * 100
          510    /    750   * 100 = 68 IV
so i thought, instead of being forced to use a ultra ball on a LVL 1-10, 100% IV with less than 750CP
we could make a IF statement~~

Then let us call it something else than IV - PossibleCombatPower = PCP
          currentCP  /  maxCP   * 100
e.g           510      /    750      * 100 = 68 PCP

.# im uncertain if it's known before you catch the Pokemon, what the maxCP is, else, there must be a way to avoid throwing ultraballs at low CP #.

$pcp = currentCP / maxCP * 100 
$i = Variable = e.g 10
IF $TrainerLVL(-2 * $i) is less than or equal to 0 THEN $i = $TrainerLVL / 3 (rounded up so 0.01 is 1)
.# if TrainerLVL is 18 and Variable is 10 the SUM would be 18(-20) which is -2 - which we then turn into TrainerLVL divided by 3 (just to secure script i guess) #.

IF $pcp is above or equal to [UseMasterBallAbovePCP]
THEN use MasterBall

ELSE IF $PokeLVL is higher or equal to $TrainerLVL-$i  .# where $i is the Variable #.
AND AND || OR OR .# a way to change this would also be good #.
 IF $pcp is above or equal to [UseUltraBallAbovePCP]
THEN use UltraBall

ELSE IF $PokeLVL is higher or equal to $TrainerLVL-($i*2)
AND AND || OR OR
IF $pcp is above or equal to [UseGreatBallAbovePCP]
Then use GreatBall

ELSE use PokeBall

-->   "UsePokeBallsRelativeToLVL": 10,   <--
-->   "UseGreatBallAbovePCP": 25,   <--
-->   "UseUltraBallAbovePCP": 50,   <--
-->   "UseMasterBallAbovePCP": 99,   <--
-->   "UseBallMinOperator": "and || or",   <--

and Override Defaults
.#  "UseGreatBallAboveCp": 750,
.#  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 80.0,
    "UseUltraBallAboveIv": 90.0,
.#  "UseGreatBallBelowCatchProbability": 0.5,
.#  "UseUltraBallBelowCatchProbability": 0.4,
.#  "UseMasterBallBelowCatchProbability": 0.05,

I realise i've basically just written half a script through this.
But im no master of C# or C++ or whatever
it might help any of u devs if u find it a good idea

**Comment by ANR2ME** [comment]
As i remember IV is a combination of ATK+STAMINA+DEF divided by something (i forgot)
