### ISSUE TITLE
Some troubles with transfer

### ISSUE THREAD

**Issue by AleksLiar** [NECROBOTIO/NecroBot#2408]
Hello frm Russia!
So, I have a problem with transferring. In config I choose same values as before, in last versions of bot:
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 10.0,

And few days ago I saw that my top CP pokemon is gone, all of them. Before I have 1800+ CP pokemons and now - only 500 CP and bot transfered all pokemons to candy.
Some troubles with evolutions too. Choose using lucky egg when 120 pokemons caught and 90% inventory full before evolve but its not start, in log a message that I dont caught enough pokemon yet. When I choose 70% inventory full to start, its not waiting till 120 pokemons wiil be caught and starts bypassing this value, so lucky egg isnt used in this conditioins.

My Config values now:
  "EvolveAboveIvValue": 10.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 10.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseLuckyEggsMinPokemonAmount": 120,
  "UseLuckyEggsWhileEvolving": true,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

I want just two things:
1. Kept top value CP+Iv pokemon 1 by type, even its CP less than Min (1500)
2. Kept all pokemon that I can evolve and do it when pokemon backpack is full + at least 120 potential evolves with lucky egg.

**Comment by ANR2ME** [comment]
TransferWeakPokemon = true will transfer all pokemons below the KeepMinCP/IV threshold (including the best one, but excluding favorited one i think)

**Comment by AleksLiar** [comment]
With that value bot collect 250 pokemons and transfering noone.
