### ISSUE TITLE
[Question] AutomaticallyLevelUpPokemon

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2409]
"AutomaticallyLevelUpPokemon": true,
"AmountOfTimesToUpgradeLoop": 5,
"GetMinStarDustForLevelUp": 10000,
"LevelUpByCPorIv": "iv",
"UpgradePokemonCpMinimum": 5000.0,
"UpgradePokemonIvMinimum": 100.0,
"UpgradePokemonMinimumStatsOperator": "or",

I want upgrade Pokemons only which have 100% IV. Should I set UpgradePokemonIvMinimum 100.0 or 99.9?

**Comment by HansonWK** [comment]
100. Please use the discord for simple questions.

**Comment by cwirek91** [comment]
Noone answer there?

**Comment by akatimka** [comment]
same issue.
use 5.0 use 6.3 
pokemons ddnt upgrade.
But by hand i can upgrade..
