### ISSUE TITLE
logic.dll not found 

### ISSUE THREAD

**Issue by yashkudalkar** [NECROBOTIO/NecroBot#2414]
\NecroBot-master\PoGo.NecroBot.Logic\bin\Debug\PoGo.NecroBot.Logic.dll' could not be found			

this folder are not there or not getting generated

**Comment by RoseFlunder** [comment]
I just checked out the current master branch and did "Build -> Clean solution" and afterwards "Build -> Build solution" and the dll is there.

**Comment by Moolaned** [comment]
Doesnt work for me either. Same error message.

**Comment by Oolaruu** [comment]
I just checked also, and the .dll is there.

**Comment by Wcidd** [comment]
use 0.6.3
