### ISSUE TITLE
[Possible Feature]  Walk around without always heading directly to pokestops. and others

### ISSUE THREAD

**Issue by mikeNickaloff** [NECROBOTIO/NecroBot#2415]
_It maybe be a good idea to **not always journey directly to every pokestop**._  

 _Often times pokemon aren't on the direct route between the two - maybe the bot should spend some time making small side trips zig-zagging en route to the pokestop?_
 
 _Maybe take some sort of bezier curve between the two points using a random offset that you can specify in Config_
 
```
RandomExplorationBetweenStops:  true,
RandomExplorationOffsetMax:  75,
RandomExplorationOffsetMin:  -75,
```

_Also maybe have a feature that allows you to **not even travel to pokestops at all**, but just randomly trudge around a certain radius_
```
TravelByPokeStops:  false,
FullyExploreAroundDefaultCoordinates:  true,
FullyExploreRadius:  250,
```

 _Then you could just have it kind of like walk around in ever growing circles or something until it hits that radius then walks back to the starting point._

_What about something that allows to **slow down the speed of searching** -- like say if we wanted it to only really search for pokemon once every minute or so rather than constantly._

```
PokemonSearchInterval:  60000,
```

_Finally, maybe the ability to "sleep" and "wake up" so that it would stop searching at say,  11pm and wouldn't start again until say 7am._

```
LimitHuntByTimeOfDay: true,
StartHuntTime:  7:00am,
EndHuntTime:  11:00pm,
```

**Comment by ANR2ME** [comment]
Walking on route will require access to Google Maps API, but it will certainly better in emulating human-walking behaviour :D

**Comment by mikeNickaloff** [comment]
definitely, but then the bot would require an API key, which would have a limit and so on and so forth - and since thats a fairly large implementation step, I'd say the next best thing is to at least look in areas that have not yet been travelled to imho.

**Comment by xzipyx** [comment]
pokestops only when needed (for example minamountpokeballs reached)

**Comment by Linewalker** [comment]
To get a Google API key for yourself to enter in config is not that problem. I like this request.
