### ISSUE TITLE
[Request for Max greatball, ultraball,potion,superpotion,hyperpotion,revive,berry]

### ISSUE THREAD

**Issue by evetaku** [NECROBOTIO/NecroBot#2416]
can we add manualy for
TotalAmountOfGreatballToKeep
TotalAmountOfUltraballsToKeep
TotalAmountOfSuperpotionToKeep
TotalAmountOfHyperpotionToKeep
TotalAmountOfReviveToKeep
TotalAmountOfBerryToKeep ???

or please add in config in next update

**Comment by Revoss** [comment]
why

**Comment by emwedk** [comment]
Revoss - i actually also find it anoying to run around with 700 ultraballs, unable to catch pokemons, cuz they require a regular pokeball. 

evetaku - It's already inthere, just add the following lines after
{
      "Key": "itemUnknown",
      "Value": 0
    },

**THEESE LINES and alter them**

{
      "Key": "itemPokeBall",
      "Value": 75
    },
    {
      "Key": "itemGreatBall",
      "Value": 75
    },
    {
      "Key": "itemUltraBall",
      "Value": 75
    },
    {
      "Key": "itemMasterBall",
      "Value": 200
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 0
    },
    {
      "Key": "itemMaxPotion",
      "Value": 0
    },
    {
      "Key": "itemRevive",
      "Value": 0
    },
    {
      "Key": "itemMaxRevive",
      "Value": 0
    },

**Comment by emwedk** [comment]
And pls dev's - keep it inthere - maybe even make it a possibility to alter them after start

**Comment by thesticks00** [comment]
EMWEDK, can you possibly assist me?  I am in the population where the bot (latest update) is using great balls and ultra balls for everything. I believe I started on version 4 and now on the latest release. Not sure if it is carrying forward settings that are causing this, but I dont know the settings to prevent the abuse of ultra and great balls on this last release. Pleas assist.  Thank you.

**Comment by emwedk** [comment]
Are you using the PokemonSniper or nah @thesticks00 ?

**Comment by Wcidd** [comment]
@thesticks00 go to support
