### ISSUE TITLE
error message and bot stops

### ISSUE THREAD

**Issue by Caliboss** [NECROBOTIO/NecroBot#2418]
this is the error i keep getting on every on version 5 and now 6.3. happened's like every hour and bot stops. anyone have a idea of how to fix? or what it is.

![error2](https://cloud.githubusercontent.com/assets/20801021/17357859/c0edebf2-5913-11e6-9411-549a5cf2d374.png)

**Comment by mikeNickaloff** [comment]
Whenever I get that error message i save my configuration file elsewhere then download a clean copy of the bot, then enter the values that I want from my old config file into the new default one.

This works 100% of the time

**Comment by Caliboss** [comment]
so you just start fresh. ill give it a shot.
