### ISSUE TITLE
RequireInputText

### ISSUE THREAD

**Issue by AIS94** [NECROBOTIO/NecroBot#2419]
Hello guys. How do I remove "Program will continue after the key press..." line ? Where is this line triggered ? I have problems with internet and bot stops right here...

**Comment by mikeNickaloff** [comment]
Change this option in the **configuration file**

`"StartupWelcomeDelay": true,`

to 

`"StartupWelcomeDelay": false,`

**Comment by AIS94** [comment]
@mikeNickaloff thanks a lot +1:

**Comment by mikeNickaloff** [comment]
np
