### ISSUE TITLE
Berries Not Used

### ISSUE THREAD

**Issue by ThatAce** [NECROBOTIO/NecroBot#2420]
the bot didnt use the berries when encountering pokemon with chance lower than 40%

**Comment by RoseFlunder** [comment]
Post your settings when to use berries please:
"UseBerriesMinCp": 
  "UseBerriesMinIv":
  "UseBerriesBelowCatchProbability": 
  "UseBerriesOperator":

**Comment by Wcidd** [comment]
Go to support
