### ISSUE TITLE
[BUG] Bot not using berry on every second attempt and subsequent

### ISSUE THREAD

**Issue by NurAdam** [NECROBOTIO/NecroBot#2421]
Every time bot using **Berrie** it will only use **1** per **Pokemon**. On previous release it will always use Berrie on every attempt until the Berrie run out. Is it normal or there is a known bug? 

here is my parameter.

"UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "or",

![untitled](https://cloud.githubusercontent.com/assets/20807194/17357743/d81a42d0-5990-11e6-91b8-3c7e17bbbc60.jpg)

**Comment by pkosukhin** [comment]
Same. Bot should use berry with every attempt!

**Comment by djdookie** [comment]
Confirmed.
