### ISSUE TITLE
[Question] Regarding PokemonTransferFilter

### ISSUE THREAD

**Issue by abali1** [NECROBOTIO/NecroBot#2423]
What are the settings i need to make sure that the pokemon caught is to my specifications.

For example:
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
I want to only keep golducks that have greater than 80iv and has the moves ConfusionFast,HydroPump. Also i don't want there to be a limit on CP so i don't mind if the Golduck is only 100CP as long as it matches the moves and IV criteria and obviously if i do catch a greater CP Golduck with the same requirements, the other one should be transferred. 
What do i need to set KeepMinOperator, in the actual pokemontransferfilter and at the start of config file.

Can someone help??

**Comment by fr3k4life** [comment]
I think:
"Golduck": {
"KeepMinCp": 0,
"KeepMinIvPercentage": 80,
"KeepMinDuplicatePokemon": 100,
"Moves": [ConfusionFast,HydroPump],
"KeepMinOperator": "and"
},

will do it.
