### ISSUE TITLE
 [enhancement] Create a GUI for Necrobot

### ISSUE THREAD

**Issue by bobbelalle** [NECROBOTIO/NecroBot#2424]
Is it possible to create  a GUI for necrobot? i think it would be great for newbie users like me.

**Comment by mikeNickaloff** [comment]
Probably once the configuration/features are more or less not going to change much anymore, and the GUI wont have to be updated every time a new release comes out (pretty much daily)

Right now, it would just be double the work trying to maintain a GUI along with developing the backend. 
Unless you're volunteering, I don't think the developers want to double down on every update they release just yet.

**Comment by Kostronor** [comment]
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by bobbelalle** [comment]
thank you guys
