### ISSUE TITLE
Transfer all Mons under IV 90

### ISSUE THREAD

**Issue by Sad0wl** [NECROBOTIO/NecroBot#2428]
What i must change in config file to do it? 
Try couple of changes bat its not helps, or even prevent bot from start.
So i appreciate a hint about it.

**Comment by marrcha** [comment]
Have you tried  "PrioritizeIvOverCp": true, and MinKeepIV or smthing like that set to 90?

**Comment by emwedk** [comment]
"KeepMinCp": 1,
  "KeepMinIvPercentage": 90.0,
  "PrioritizeIvOverCp": true,

and remove all from 

  "PokemonsTransferFilter": {

**Comment by Sad0wl** [comment]
i did it and its strange  i dont see its transferring pokos at all right now.

**Comment by Wcidd** [comment]
Go to support
