### ISSUE TITLE
Evolve conflict

### ISSUE THREAD

**Issue by srwgin** [NECROBOTIO/NecroBot#2430]
"EvolveKeptPokemonsAtStorageUsagePercentage": 65.0,
  "UseLuckyEggsMinPokemonAmount": 100,
  "UseLuckyEggsWhileEvolving": true,
it will evolve pokemons when 65% in bage immediately

**Comment by emwedk** [comment]
change this
 "KeepPokemonsThatCanEvolve": true,

**Comment by PokemasterMike** [comment]
why does it evolve if KeepPokemonsThatCanEvolve is set to false ? isnt this a bug ?

**Comment by Gorrock** [comment]
There is no bug here: You've told the bot to evolve pkmn when your bag is 65% full, and to only use a lucky egg when there are 100 pkmn available to evolve. If your capacity is 250 pkmn, the evolution will happen when you have 163 pkmn in your storage (not 163 that can evolve). To use a lucky egg, set the "UseLuckyEggsMinPokemonAmount" to less.
