### ISSUE TITLE
[IDEA] Master Server for Rare Pokemons

### ISSUE THREAD

**Issue by Zignixx** [NECROBOTIO/NecroBot#2431]
Just a idea, if its possible to create a little Master Server for NecroBot. If a player found a rare Pokemon / High IV Pokemon (about 95 or higher?), it will send the coords to the Master Server.

With that, we can use a sniper/feeder to catch all rare Pokemons?

Thanks! :)

**Comment by mikeNickaloff** [comment]
Yes its possible.

**Comment by Zignixx** [comment]
Nice! Would be nice so we can create a better feeder with that. :)

**Comment by mikeNickaloff** [comment]
Now we just need somebody to pay for the server and everything is good to go!

**Comment by Zignixx** [comment]
What do you think, how many traffic it will be? Maybe i can host a little api server for that :P

**Comment by Zignixx** [comment]
Or we can use discord for that? Just a master channel (iv 90, iv 100, rare or some like that) and the bot post the coords, name, iv and time into the channel so every feeder can use the channels. With that we dont need a server :)
