### ISSUE TITLE
UsePokemonSniperFilterOnly is ignored

### ISSUE THREAD

**Issue by TankTheFrank** [NECROBOTIO/NecroBot#2437]
Reopening #2280. This is definitely not intended, the flag is skipped in SnipePokemonTask, it checks only for Missingno as id or if the id is in the snipe list ignoring this flag.

**Comment by Rykee** [comment]
UsePokemonSniperFilterOnly which really should be UsePokemonSniperOnly, means the bot won't catch any pokemon when visiting pokestops, only when sniping. The sniping filter still effect this. 
Working as intended, but bad choice if words for sure.

**Comment by TankTheFrank** [comment]
I see, it makes sense.

**Comment by Wcidd** [comment]
@simplyphp
