### ISSUE TITLE
No Pokestops available (Too many request from 1 IP = softban)

### ISSUE THREAD

**Issue by ButterForce** [NECROBOTIO/NecroBot#2439]
Looking at my logs it shows from 8/2/16 8pm PST the servers start rejecting all requests if there are too many requests from 1 IP address. If the client can have a IP connect option via a JSON file that would be great.

**Comment by emwedk** [comment]
u mean to proxy to owned IP's ?

**Comment by Caliboss** [comment]
i been messing with config so much.. im softbanned lol.. its been 15min still not able to click a poke stop
