### ISSUE TITLE
[Featurerequest] KeepMinLevel

### ISSUE THREAD

**Issue by spamfighter82** [NECROBOTIO/NecroBot#2440]
Could we have a KeepMinLevel instead of KeepMinCP, a level 28 90%IV would make for are great pokemon to actually invest Stardust opposed to a level 1 95%IV since that stuff is hard to come by. 

KeepMinCP doesnt help much since the spread between the actual CP is to high, a wild Magikarp would never have more than 225 CP but a Eevee could be as high as 923 CP

**Comment by emwedk** [comment]
it's somehow related to this i created #2406
i would also like to see the KeepMinLvl
also inside the   
"PokemonsTransferFilter": {

upvoted

**Comment by PokemasterMike** [comment]
+1 for keepMinLevel instead of CP

**Comment by Sad0wl** [comment]
+1

**Comment by darkfriend77** [comment]
+1

**Comment by ChemiHatake** [comment]
Do you want keepMinLevel instead of CP?
or both?

**Comment by darkfriend77** [comment]
KeepMinLevel is usable for all pokemons ... cp is different for each ... i would prefer only Level

**Comment by spamfighter82** [comment]
I think i would use minLevel over CP every time, but it doesn't hurt to have the option to choose what you prefer, maybe other ppl like CP more.

**Comment by ChemiHatake** [comment]
so maybe I can add an option to choose between CP/Level

**Comment by spamfighter82** [comment]
that would be really cool, i just to be able to keep lets say all pokemon lvl > 25 and IV > 90% without making a matching CP filter for each of the 151.

**Comment by darkfriend77** [comment]
Yep ... minlevel ... is far better to qualify ... but ... cp can be fine for individual filters ...

**Comment by josephdouce** [comment]
+1

**Comment by lokfukobe** [comment]
+1
