### ISSUE TITLE
(request) DoNotTransferIV100(true)

### ISSUE THREAD

**Issue by dody19852002** [NECROBOTIO/NecroBot#2443]
prevent accidentally transferring iv100

**Comment by emwedk** [comment]
"KeepMinCp": 1600,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "and",   <--- both "and" and "or" should suffice, but dont hang me up on it
  "PrioritizeIvOverCp": true,

tho noew i think about it, u might be talking about the
  "TransferWeakPokemon": true,
which might have transfered some iv100 ??

**Comment by dody19852002** [comment]
"KeepMinCp": 4000,
"KeepMinIvPercentage": 100.0,
"KeepMinOperator": "or", 
"PrioritizeIvOverCp": true,

thats my config rightnow for almost all my pokemon, because my inventory getting full frequently, so i decided only keeping 100 as minIv because necro will keep the best Iv by default even there is no Iv100 
transferweakpokemon base on best move i guess, it will be useful next week i guess when everyone's inventory is full of iv100 pokemon
