### ISSUE TITLE
[bug] bot starts evolving immediatly if KeepPokemonThatCanEvolve is set to false

### ISSUE THREAD

**Issue by PokemasterMike** [NECROBOTIO/NecroBot#2447]
i have it set to 95% of inventory (and use lucky egg on 180+ which doesnt matter here) and as soon as i change the setting it evolves all of my pidgeys even if my pokeinventory is only 80 pokemon

the setting shouldnt have any impact on that

from the wiki:

KeepPokemonsThatCanEvolve (Value)
When NecroBot determines how many Pokemon to transfer due to duplicates, it will create a count based on the number of candies the account has for that species compared to the number required to evolve.
For example, if the account has 5 Pidgeys (12 candies to evolve) and 24 candies, NecroBot will keep the top two Pidgeys and transfer the rest.

also: the wiki isnt really clear (and neither is the code probaly....) on what criteria to use when determining when to evolve...

EvolveAllPokemonWithEnoughCandy (Value):
When EvolveAllPokemonWithEnoughCandy is set to true, any Pokemon listed in the PokemonsToEvolve list will be evolved every 5 Pokestops limited by the number of Pokemon and candies you have. If this is not set, Pokemon will not be evolved based on this list criteria.

EvolveKeptPokemonsAtStorageUsagePercentage (value)
The setting 'EvolveKeptPokemonsAtStorageUsagePercentage' determines how much of the pokemon storage should be full before evolution starts.

which one takes priority ? what does EvolveAllPokemonWithEnoughCandy even do at all ????

**Comment by rherartt** [comment]
KeepPokemonsThatCanEvolve false will make the bot evolve 1 by 1, you must change it to true if you want to keep them and wait to reach the number you want to evolve

**Comment by ChemiHatake** [comment]
EvolveAllPokemonWithEnoughCandy  evolves all pokemon that have enough candies when there are enough candies to evolve 1 pokemon.
