### ISSUE TITLE
Set the config so it keeps and auto-evolves selected pokemons 'pidgeys' when enough candy

### ISSUE THREAD

**Issue by MrHugiii** [NECROBOTIO/NecroBot#2449]
#1 The idea is that the bot auto-evolves pidgeys, rata and pokemons from a set list whenever there are enough candy for it. And do not evolve any other pokemons. 

#2 Alternatively how to a config it so it keeps and store 'up to 30 pidgeys' and stop transferring the weaker ones.

Thanks in advance for the help!

**Comment by Wcidd** [comment]
Go to support channel Mars will help you there
