### ISSUE TITLE
[SUGGESTION] triggering a pokeball-run mode when pokeball is below than a value

### ISSUE THREAD

**Issue by nmly** [NECROBOTIO/NecroBot#2450]
So we can set a threshold for the pokeball-run mode in terms of total ball number or some specific ball number. It will resume the normal mode when the number is higher than another value.

In terms of pokeball-run mode, the bot is ignoring most of pokemons and running for pokestop only. It may also use a list to name a few really rate pokemons to capture under this mode.

**Comment by thesticks00** [comment]
I think this is a great idea. It would be awesome if you can do this to automate as the OP suggested. If easier could we get one line you could toggle "TRUE" or "FALSE" to enable a pokeball farming to stock up on balls? I think many users may be running low on pokeballs and this feature would be amazing to add.

**Comment by Linewalker** [comment]
Have a look at my request #1491. Just the automatism is missing.
