### ISSUE TITLE
REQUEST: Minimum ULTRAballs for Snipings

### ISSUE THREAD

**Issue by sinfuego** [NECROBOTIO/NecroBot#2452]
Well, sniping can cost you all your ultraballs, but it is also great to keep some on hand.  Right now Sniping only looks at generic pokeballs minimum.  It would help a lot if it is was defined a little bit more.

**Comment by SweetCherry** [comment]
Yeah the RecycleFilter does ignore and delete the good items like MaxPortion, MaxRevive and MasterBall... -.-

I tried to add this codeline to "ItemRecycleFilter":, from a older version but it does just ignore them -.- please fix the recycle filter! this would also fix the problems with sniping! When mine goes to snipe, he takes 3-4 greatballs with him, so the sniping function is pretty useless at the moment....

    {
      "Key": "itemGreatBall",
      "Value": 20
    },
    {
      "Key": "itemUltraBall",
      "Value": 30
    },
    {
      "Key": "itemMasterBall",
      "Value": 50
    },
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 20
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },
    {
      "Key": "itemRevive",
      "Value": 25
    },
    {
      "Key": "itemMaxRevive",
      "Value": 50
    },

**Comment by sinfuego** [comment]
Recycling is a whole different thing bro.

**Comment by SweetCherry** [comment]
Sure, but both have to work since you want usable balls to snipe!
Mine does keep 1-3 master and greatball so the sniping function is for bad pokemons only! Please :8ball:
