### ISSUE TITLE
BUG: "SnipeIgnoreUnknownIv": true does not work

### ISSUE THREAD

**Issue by sinfuego** [NECROBOTIO/NecroBot#2453]
"SnipeIgnoreUnknownIv": true does not work. The bot keeps sniping everything.

**Comment by Taranis01** [comment]
Read https://github.com/NECROBOTIO/NecroBot/wiki/Config#snipeignoreunknowniv-value again, it should be disabled to stop sniping everything

**Comment by Wcidd** [comment]
New ticket opened to clear confusion
