### ISSUE TITLE
Question:  How do I use the KeepMinOperator function + Bot transferring all non-favorited pokemon

### ISSUE THREAD

**Issue by bedesv** [NECROBOTIO/NecroBot#2455]
Hey guys, I'm having a bit of trouble using the keepMinOperator function, how exactly do I use it?  Is it only "and" or "or"?  

Also, the bot has transferred all of my pokemon other than my favourited ones, it disregarded all of my settings and transferred all my pokemon!!!  I know I can't get them back but how can I stop it from doing this again.  

Config file:  http://pastebin.com/4vzyQKqm

**Comment by bedesv** [comment]
I did ask both of these questions on the discord chat but no one answered me

**Comment by emwedk** [comment]
Set this to false
  "TransferWeakPokemon": false,

for the pokemon multi transfer fix

**Comment by emwedk** [comment]
and yes, the Operators is only "and" and "or"

if you choose "or" it will only take the last options, as far as im concerned
e.g 
 "KeepMinCp": 1600,
  "KeepMinIvPercentage": 98.0,
  "KeepMinOperator": "or",

would only pick 
  "KeepMinIvPercentage": 98.0,

**Comment by noodle-** [comment]
I think there's more to it than setting TransferWeakPokemon to false.

![asdf3](https://cloud.githubusercontent.com/assets/812565/17362897/99ede58e-5977-11e6-9f09-d7b4caf87072.png)

```
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
  "TransferWeakPokemon": false,
```

[full config](http://pastebin.com/mSCL66an)

**Comment by Rykee** [comment]
I think, 
 "KeepPokemonsThatCanEvolve": true, 
overrule KeepMinCV\KeepMinIV
So if you had 10 pidgeys but only enpugh candies to evolve 4, it would transfer the 6 weaker ones.
Not sure tho.

**Comment by Wcidd** [comment]
Config setup wrong, nothing to do with bot

**Comment by noodle-** [comment]
@Wcidd Then what exactly is wrong with my config?
