### ISSUE TITLE
activate sniping by default?

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2457]
can we have these 4 set by default in necros config?

  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,

so people who ask for sniping will only have to be pointed to installing the feeder.
I dont see any harm in having those active and not using feeder, unless im missing something.

**Comment by emwedk** [comment]
hmm - that's a shared opinion
tho i bet the majority uses it

**Comment by nfettinger** [comment]
No, this is a feature you must configure, and therefore it needs to be enabled by the end user.
