### ISSUE TITLE
[Enhancement] Dependency between "EvolveKeptPokemonsAtStorageUsagePercentage" and  "UseLuckyEggsMinPokemonAmount"

### ISSUE THREAD

**Issue by Darkztar** [NECROBOTIO/NecroBot#2462]
For now there is no dependency between these two parameters.

E.g.:
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0   
"UseLuckyEggsMinPokemonAmount": 30 

Then the bot waits until 90% of inventory and evolves, but if you have 30 possible evolutions before the 90% inventory, it won't use egg and won't evolve.

It would be great if the bot starts to evolve if there are enough for egg OR the inventory is at specified percentage.

Thank you.

**Comment by cbnolok** [comment]
Good one. Suggestion: and then keeps evolving until you have no evolvable pokemon, not stopping when you are right below the EvolveKeptPokemonsAtStorageUsagePercentage

**Comment by Darkztar** [comment]
@cbnolok: this can't happen I think, because evolving doesn't decrease your number of pokemon and so you won't get less pokemon as the StorageUsagePercentage until the evolutions are transferred. So it shouldn't stop evolving.

**Comment by cbnolok** [comment]
You're right, i mistaken this with another fixed bug, sorry ^^

**Comment by simplyphp** [comment]
Its referring to using lucky eggs when mass evolving, it does correctly use a lucky egg prior to doing mass evolving.

**Comment by Darkztar** [comment]
yes, but the priority is "EvolveKeptPokemonsAtStorageUsagePercentage" > "UseLuckyEggsMinPokemonAmount"

So If you have enough evolutions for egg, but the Storage Usage Percentage is not reachead it won't evolve, it is very bad.

Please allow that it will start to evolve before the Storage Usage Percentage is reached, but there are enough for egg.
