### ISSUE TITLE
Closed Issue with no info to why

### ISSUE THREAD

**Issue by emwedk** [NECROBOTIO/NecroBot#2463]
im kinda sorry for this, but i'd really like to know why this got closed without an answer. 
if it's something the dev's are working on, or a request that's already been requested that i've missed :)
together with another one linked from there
#2358
#2346

**Comment by Wcidd** [comment]
Sorry about that, got 2 mixed up, have reopened and labled! :)

**Comment by ANR2ME** [comment]
I think it's because those are more related to UI instead of the logic, since NecroBot doesn't really have UI (yet) as of now, those info might be available later in the UI.
