### ISSUE TITLE
[Sugestions] and [Transfer pokemon bug]

### ISSUE THREAD

**Issue by Adriskye** [NECROBOTIO/NecroBot#2464]
Option panel
Pokemon panel , to manage them meanwhile bot works

Snipe option for any web (example: http://pokesnipers.com/) without 3ºrd programs
Option for manage items( max pokebals, masterbals, hiperballs.....)
Use eggincubator

////////////
Maybe bug dont know rly if i have to change something more than this but those options not working for me
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

Updated

**Comment by Oolaruu** [comment]
Please, could you edit your title to be a bit more clear ? before it get closed.
Thanks.

**Comment by Kostronor** [comment]
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by Adriskye** [comment]
i have like 30 rattatas and it dont transfer it :/
