### ISSUE TITLE
REQUEST: Only level up EVOLVABLE pokemon

### ISSUE THREAD

**Issue by sinfuego** [NECROBOTIO/NecroBot#2467]
Currently you can only decide to lvl up based on CP or IV. However, a HIGH IV pokemon that is already fully leveled is not necessary good one. Therefore I would like to have an option to only let it evolve high IV pokemon that doesn't had any evolves.

**Comment by Rabelaiss** [comment]
Its better to level up manually, because the bot dont know what pkm have the best moveset
