### ISSUE TITLE
[BROKEN] "UseLuckyEggsWhileEvolving: true" does not hold-off on evolving Pokemon

### ISSUE THREAD

**Issue by Taranis01** [NECROBOTIO/NecroBot#2468]
Several people on discord reported that their bot evolves single Pokemon and without using lucky egg (e.g. Mars).
A workaround is to enable `KeepPokemonsThatCanEvolve` but then other Pokemons won't be transferred

The feature `KeepPokemonsThatCanEvolve` needs to be imported to `UseLuckyEggsWhileEvolving` while beeing enabled for Pokemons on the `PokemonsToEvolve (List)` only

**Comment by Rykee** [comment]
It transferes pokemons just fine for me. It even calculates how many pokemons you can evolve with the candy you have and transfers the others.

**Comment by Taranis01** [comment]
@Rykee do you have  `KeepPokemonsThatCanEvolve` enabled?

**Comment by Rykee** [comment]
@Taranis01 Yes I use these settings: 
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 98.0,
  "KeepPokemonsThatCanEvolve": true,
  "UseLuckyEggsMinPokemonAmount": 30, //doesn't really matters because of the storage restriction
  "UseLuckyEggsWhileEvolving": true,

**Comment by Caliboss** [comment]
i just noticed mine acting up.. i have 170 pokemon in stash.. bot says i have 210/225 and and once it gets 15 more i can evolve a potential of only 2... i have like 100 pidgeys.. how i fix this?

**Comment by Caliboss** [comment]
here is my config, im sure i have done it right..

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": false,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 0,
  "GetMinStarDustForLevelUp": 0,
  "LevelUpByCPorIv": "cp",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 38.575725,
  "DefaultLongitude": -121.48884,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 500,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 0,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 30000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 90.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.4,
  "UseUltraBallBelowCatchProbability": 0.2,
  "UseMasterBallBelowCatchProbability": 0.05,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 0.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [

**Comment by Taranis01** [comment]
@Rykee if you disable it it wont work anymore. that is the whole reason for my post ^^
It causes that Pokemon you do not have on your `PokemonsToEvolve (List)` will not be transfered

@Caliboss you possibly have Pidgeys in your PokemonNotToTransfer List or PokemonTransferFilter List.
For further questions/next time please ask in the Discord channel. Please also delete your posts here to keep thread clean. Your Question is not related to topic
