### ISSUE TITLE
[bug] Necrobot trying to loot the same spot trigger false positive soft ban

### ISSUE THREAD

**Issue by Alekc** [NECROBOTIO/NecroBot#2471]
I noticed that lately this issue was happening quiet often, not sure if it's related to some recent changes in bot or niantic being more unstable. 

What happens is following:

```
Looting pokestop: Trajan XP
Traveling to Pokestop: Falklands Memorial (never reached it)
```

At this point I am getting error about niantic being unstable
```
PTC Servers are probably down OR your credentials are wrong. Try google
```

About 40 seconds later (after relogin) I am seeing bot trying to loot pokestop Trajan XP which has already been looted thus entering in error thinking that it has been soft banned. 

I'd say the best way to deal with it would be to mimic human behaviour: when you can't loot a pokestop you just move forward to the next one.

**Comment by nfettinger** [comment]
The bot can automatically detect when a Pokestop timer is not expired yet, and it should not trigger the softban routine. Please ensure that you are not softbanned by using a device. Your travel speed could be too high.

**Comment by Alekc** [comment]
I was not softbanned since everything was working fine once I've restarted client (btw my speed is 15kmh). 

Unfortunately for whatever reason I don't have softban related messages in my log file, but from what I've seen bot was definitely trying to loot the Pokestop which has been already looted previously. 

If I am to speculate about how that happened I'd say that once an exception is thrown and we do a restart/refresh of connection, bot takes the last known position and try to resume it's advance from nearest pokestop which happens to be already looted. Is it possible that pokestop timer are being cleared after connection restart?

**Comment by nfettinger** [comment]
The pokestop timer is retrieved from the server.

**Comment by Alekc** [comment]
Ok, then it looks like it's server being a bit out of sync issue where we collect from stop A from server B, server B goes down, we connect to server C which reports that stop A is not looted but then stops us from looting it. 

Just got the similar issue, looting stop A -> moving to stop B -> failing to loot stop B. 

After restarting of the app everything is fine.

I guess I will keep an eye on log and wait for this situation to repeat (trying to loot the same stop even if it was already looted) to see if that was indeed the case. 

p.s. what about trying to move to next stop even if there is a softban and looting has failed?

**Comment by Copoutside** [comment]
The bot IS occasionally trying to take the same Pokéstop twice in a row and failing for 5 minutes until the stop respawns before it moves on to the next. I can restart the bot to force it to move on to the next stop, but that requires babysitting it.
Proof: http://i.imgur.com/6krDIzA.png
I'm on 0.6.3.

The softban message is untrue in this case.

**Comment by Alekc** [comment]
And in your case looks like there was not any exception present in the middle of 2 looting calls.

**Comment by MODKILLER1001** [comment]
this is the same for me

**Comment by Copoutside** [comment]
Right. I haven't been getting any exceptions during any of the times it's been doing this, and the servers have been stable matching the timestamps. It's happened about four more times since I last posted here.
