### ISSUE TITLE
[BUG] Wrong special character readout

### ISSUE THREAD

**Issue by fr3k4life** [NECROBOTIO/NecroBot#2474]
In translation.de.json it is correct with ö,ä,ü,é,..
but in the console Window some random chars are Displayed.
Also there are no signs for "Nidoran Male and Female".
I tried to fix it, but I'm not able to compile the projects to test it.

Greets

Alex

**Comment by ChemiHatake** [comment]
I can compile it for you if you want, just upload the text file and ill pr.

**Comment by fr3k4life** [comment]
I edited ConsoleEventListener in in the CLI project.
Could you upload the whole project somewhere for me so I can test it at first?^^

**Comment by Oolaruu** [comment]
Nidoran with special character ♂ and ♀ might have caused a bug on another bot, this is why (i guess) it was removed for NidoranM (male) or NidoranF (female) so I guess it's still understandable for anyone with F(female) and M(male).

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/2485

**Comment by fr3k4life** [comment]
Sure it is, but I think with the right character loading/formatting it wouldn't be a problem.

**Comment by nfettinger** [comment]
The following should fix the issue for the majority of users, others simply dont have the right fonts installed on their system.

Console.OutputEncoding = System.Text.Encoding.Unicode
