### ISSUE TITLE
Selective sniping

### ISSUE THREAD

**Issue by ExarSenpai** [NECROBOTIO/NecroBot#2475]
Hey, I have a question, why I am having a  issue of the bot selectively sniping. I run it on multiple bots and half of them will go for it and half will just not so i know the coordinates are good. If anyone knows a fix that would be great, I mean it is not a huge deal or anything i was just wondering.

**Comment by Wcidd** [comment]
Please ask in the support channel

**Comment by ExarSenpai** [comment]
In discrod?

**Comment by Marsinator** [comment]
yes in discord.
