### ISSUE TITLE
[bug] transfer weak pokemon

### ISSUE THREAD

**Issue by sagiGL** [NECROBOTIO/NecroBot#2477]
the pick the way it is now doesn't keep at least 1 of the type like it used to be when the transferweakpokemon  and transferduplicate is true and set for at least 1 pokemon to keep.
it just transferred almost all my pokemon XD its began from patch yesterday.

**Comment by emwedk** [comment]
#2112 - yeah 
lot's of us suffered from it - im glad i used my test dolly before running the other instances

**Comment by sagiGL** [comment]
i dont really mind since it didn't transfer my 100% iv but i just want to know how to fix this. i don't want to go back to haxbot,  necro much more visual XD

**Comment by nfettinger** [comment]
TransferWeakPokemon is now defaulted to false.
