### ISSUE TITLE
[Bug] Pokemon Inventory is full

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2480]
http://i.imgur.com/iquwr2W.png
It doesn't evolve all the Pokemons and then transfer them.
something is wrong.

**Comment by tom3232** [comment]
@ObsessedHacker Check if you have the latest release
Try the following settings:
```
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
```

**Comment by ObsessedHacker** [comment]
@tom3232 Yep latest version.
I just did and it doesn't transfer them.

**Comment by StevasaurousREX** [comment]
Those settings transferred a few but not all that I had that were duplicates.

**Comment by Rykee** [comment]
Could you link your config? (pastebin)

**Comment by ObsessedHacker** [comment]
@Rykee NVM I used someone else's config. it's fine now.

**Comment by Rykee** [comment]
Close the issue then.

**Comment by hughpearse** [comment]
no, its broken for me also

**Comment by hughpearse** [comment]
I have 2 accounts with identical configurations, one account is catching pokemon, the other is not. The one that is not catching them is complaining that the inventory is full.
http://pastebin.com/9GFEQs66

**Comment by nfettinger** [comment]
@hughpearse Please ask for help in the Discord chat rooms. If you find a specific issue with the program, please feel free to open a new issue.
