### ISSUE TITLE
[BUG] UseLuckyEggsMinPokemonAmount

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2481]
"EvolveAboveIvValue": 100.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 69,
  "UseLuckyEggsWhileEvolving": true,

![evolve2](https://cloud.githubusercontent.com/assets/20729182/17364839/db5a1bae-5982-11e6-8580-5c8770105c12.png)

**Comment by ShaggyHW** [comment]
what is suposed to be the bug? if it is because you have it set to 69 and its not evolving yet its because its waiting to get the pokemon inventory to 90% full before poping the egg and start evolving

**Comment by cwirek91** [comment]
It should evolving at 69 potential evolves. I think so

**Comment by simplyphp** [comment]
Lucky egg count is to ensure you dont waste a lucky egg on less than that many pokemon. Working as intended, it does not mean "evolve at this count".
