### ISSUE TITLE
Bug: Transfers high Cp pokemon keeping less cp pokemon

### ISSUE THREAD

**Issue by KapilTapsi** [NECROBOTIO/NecroBot#2482]
![untitled](https://cloud.githubusercontent.com/assets/20764254/17364979/1d8216da-59a1-11e6-8bd0-037a22b7d596.jpg)

In third last line Kakuna of high cp is transfered

**Comment by archimendus** [comment]
Change "PrioritizeIvOverCp": true, to false.
In your settings the Bot will keep the pokemon with higher IV!

**Comment by Linewalker** [comment]
Only 40.35% IV, there's a filver for Prio: CP oder IV. No bug.

**Comment by KapilTapsi** [comment]
Thanks. I didn't read that in configuration. I'll check it
