### ISSUE TITLE
[REQUEST] Add the possibility to level up all pokémon as high as possible

### ISSUE THREAD

**Issue by VanStorm** [NECROBOTIO/NecroBot#2483]
It would be nice to have an option (maybe as an startup option) to level all pokémon to the maximum level that is possible with the current stardust and candies.
Of course this should use the minimum iv and / or minimum cp settings from the config.

It would be nice to have something like that since most people tend to have several 100k stardust on their account and the normal speed of leveling up is really slow especially if you're on a high trainer level and want to get them ready for battles.

**Comment by nfettinger** [comment]
This feature is already supported:
  "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
