### ISSUE TITLE
PrioritizeIvOverCp is not working

### ISSUE THREAD

**Issue by jasio77** [NECROBOTIO/NecroBot#2486]
When PrioritizeIvOverCp is set to "true" and KeepMinOperator to "or" it still leaves Exeggutor CP 2075, IV 59.5.
Exeggutor isn't on PokemonsTransferFilter.

**Comment by jasio77** [comment]
Similiar issue. #2489

**Comment by jasio77** [comment]
It doesn't apply to PokemonsTransferFilter. aswell.

**Comment by Naprosnia** [comment]
Maybe your "KeepMinCp" amount may be less than 2075.
bot keeps pokemon with >= cp "OR" >= iv.

**Comment by jasio77** [comment]
But still, PrioritizeIvOverCp should work as it worked or there's no sense to keep this setting.

**Comment by Naprosnia** [comment]
When you got 2 mew's, and "KeepMinDuplicatePokemon": 1 (for example),  bot need to transfer one. and use PrioritizeIvOverCp to choose.

"KeepMinCp": 2500,
"KeepMinIvPercentage": 95,
"KeepMinOperator": "or",
"PrioritizeIvOverCp": true,

Mew 1- cp: 3000 iv: 80
Mew 2 - cp: 5 iv: 100

Bot transfer mew 1 and keep mew 2.

**Comment by Naprosnia** [comment]
If you got "KeepMinDuplicatePokemon": 10, and it is not full.  bot keeps pokemons with:

CP >= "KeepMinCp": 2500,
OR "KeepMinOperator": "or",
IV >= "KeepMinIvPercentage": 95,

**Comment by jasio77** [comment]
@Naprosnia but IV is better than CP. You can upgrade your pokemon. It's better to have higher IV rather than CP which you can upgrade. That's for what is PrioritizeIvOverCp, you can only transfer by IV, only by CP, IV or CP, IV and CP.

**Comment by Naprosnia** [comment]
but if you want to ignore cp, maybe if change "KeepMinCp" to high values  (5000 [not normal for wild pokemons]), bot will ignore lower cp's and use iv only.

**Comment by jasio77** [comment]
So that way, PrioritizeIvOverCp isn't needed. It's for THAT! To not put values that you said. It's a bug and it should be fixed. No way around. If this setting exists, and it's not working as it intended, then it should be fixed.

**Comment by Naprosnia** [comment]
you right ;)

**Comment by simplyphp** [comment]
It's already fixed in the repository, but not latest version. The next release will have the fixed included.

**Comment by Taranis01** [comment]
This bug is the same for `"LevelUpByCPorIv": "iv",` , is that fixed in the latest version too?
