### ISSUE TITLE
KeepMinDuplicatePokemon not working properly

### ISSUE THREAD

**Issue by jasio77** [NECROBOTIO/NecroBot#2487]
When set to 1 it keeps 2 pokemons. When set to 0 it keeps 1 pokemon. (that's how it should work when set to 1).
Also it's the same for pokemons on PokemonsTransferFilter.

**Comment by Rykee** [comment]
As the name of the setting implies you specify how many !duplicates! you want to keep. So it works as intended.

**Comment by jbadumm** [comment]
I set it to 1 and it keeps sending away all pokemons of one type

**Comment by jasio77** [comment]
On discord someone said to report that. Post here your issues with this setting.

**Comment by jasio77** [comment]
On discord someone said to report that. Post here your issues with this setting. Before it wasn't working like that.

**Comment by jasio77** [comment]
It wasn't working like that before. If it was set to 1, it kept only 1 pokemon.

**Comment by jasio77** [comment]
@simplyphp Why are you closing that? From nowhere it started working differently.

**Comment by nombredisponible** [comment]
Same here... It emptied my entire account! Just kept 20 of 93 Pokemon :( But PrioritizeIvOverCp works just fine.
