### ISSUE TITLE
LevelUpByCPorIv not working

### ISSUE THREAD

**Issue by jasio77** [NECROBOTIO/NecroBot#2489]
When LevelUpByCPorIv is set to "iv" and UpgradePokemonMinimumStatsOperator set to "or" it still upgrades pokemons by CP.

**Comment by Rykee** [comment]
Confirmed. 
Workaround:
 set "UpgradePokemonCpMinimum": to a very high value.

**Comment by jasio77** [comment]
Similiar issue. #2486
