### ISSUE TITLE
Best pokemons get transfered

### ISSUE THREAD

**Issue by jbadumm** [NECROBOTIO/NecroBot#2490]
![wtf](https://cloud.githubusercontent.com/assets/20769174/17365210/1f9a8ff4-5985-11e6-8220-ba1eb2fd34a4.PNG)

Bot transfers best pokemons. It was the only dratini (same for cloyster/austos)
It's in german.

Config:
  "KeepMinDuplicatePokemon": 1,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by jbadumm** [comment]
copied my configs into a txt
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/399423/config.txt)

**Comment by Rykee** [comment]
Set TransferWeakPokemon to false, 
I couldn't find it in the wiki but I think if a Pokemon doesn't reach either of 
"KeepMinCp": or
"KeepMinIvPercentage": they get transferred.

**Comment by jbadumm** [comment]
thanks
