### ISSUE TITLE
[BUG] Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by cwirek91** [NECROBOTIO/NecroBot#2491]
Bot crashed

![newtonsoft json jsonreaderexception](https://cloud.githubusercontent.com/assets/20729182/17365302/c06d3f3a-5985-11e6-8c97-b4896cbc1484.png)

**Comment by Linewalker** [comment]
Check config for missing " at the start or end of a string.

**Comment by nfettinger** [comment]
This does not seem to be a configuration issue, but a corrupted response returned from the server.

**Comment by nfettinger** [comment]
Is this reproducible?

**Comment by cwirek91** [comment]
First time i got on 1 bot of 6

**Comment by cwirek91** [comment]
Now

https://cloud.githubusercontent.com/assets/20729182/17366925/00d45d8a-598e-11e6-8847-27c1ea3b0199.png

**Comment by simplyphp** [comment]
Configuration/client end issue.
