### ISSUE TITLE
[Issue] CatchFilter not working

### ISSUE THREAD

**Issue by CedricBongaerts** [NECROBOTIO/NecroBot#2492]
I seem to be having an issue with the following:
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": true,

It seems to be mixing up the SniperFilter with the regular one.

I'll give an example:
If I set sniping on and set the filter for the following:

`  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "bulbasaur",
      "charmander",
      "squirtle",
      "golduck",
      "primeape",
      "poliwrath",
      "grimer",
      "cloyster",
      "gastly",
      "haunter",
      "hypno",
      "kingler",
      "exeggcute",
      "scyther",
      "electabuzz",
      "magmar",
      "lapras",
      "eevee",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "mewtwo",
      "mew"
    ]
  },`

My bot seems to be skipping every normal capture that I come across, even though my   `"PokemonsToIgnore": [],` is empty.

When turning "UsePokemonSniperFilterOnly" to false, it starts capturing all the pokes. Though I don't want to snipe specific pokes.

Hope this can be fixed. Started with the 0.6.2 update. First I thought it was me, but I redownloaded the 0.6.3 and it seems to be the same on this version.

Here is my pastebin which gives the following issues:
http://pastebin.com/y1bLxPY9

https://discordcdn.com/attachments/210366942459068416/210369045462122497/unknown.png
https://discordcdn.com/attachments/210366942459068416/210369501621911553/unknown.png

Thanks

**Comment by Marsinator** [comment]
it will only capture whats in your sniper filter if you set sniper to true

**Comment by CedricBongaerts** [comment]
If I don't want it to snipe everything, only the requested. But everything that I find (normal). How should I proceed?

**Comment by Marsinator** [comment]
fill the sniping list with sniping targets, but dont use "UsePokemonSniperFilterOnly": true, leave it at false
