### ISSUE TITLE
[Crash] Bot crashed

### ISSUE THREAD

**Issue by s10035147** [NECROBOTIO/NecroBot#2493]
![image](https://cloud.githubusercontent.com/assets/20797028/17365367/71eec60c-59b8-11e6-8866-5d6806188c09.png)

**Comment by Marsinator** [comment]
is this happening on 0.6.3?

**Comment by s10035147** [comment]
Affirmative.

**Comment by simplyphp** [comment]
It's already fixed in the repository, but not latest version. The next release will have the fixed included.
