### ISSUE TITLE
Bot not detect Farfetchd from Location Feeder

### ISSUE THREAD

**Issue by Naprosnia** [NECROBOTIO/NecroBot#2495]
Bot not detect Farfetchd from Location Feeder, whenever the farfetchd appears, is ignored.

**Comment by Marsinator** [comment]
I did snipe farfetchds in the past, havent done so in 0.6.3 yet.

potential bug.

**Comment by Naprosnia** [comment]
yes. i got all 151 pokes on the list ;), even with "UsePokemonSniperFilterOnly": false

**Comment by Tomabl** [comment]
I have sniped farfetchds with version 0.6.3, so this is working fine.
