### ISSUE TITLE
[Feature Request] Add Japanese language support

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#2496]
Hello.

Feature request: https://github.com/NECROBOTIO/NecroBot/issues/2375 
Pull request: https://github.com/NECROBOTIO/NecroBot/pull/2413

Even if the japanese language given by @B100c (no compilation error and bot is working) I was unable to display japanese language.

Would it be possible to add support for japanese ?

Thank you.

**Comment by Marsinator** [comment]
https://stackoverflow.com/questions/3780378/how-to-display-japanese-kanji-inside-a-cmd-window-under-windows
