### ISSUE TITLE
[SUGGESTION] Split default location to seperate json file

### ISSUE THREAD

**Issue by thrca** [NECROBOTIO/NecroBot#2497]
It would be extremely helpful to have DefaultLatitude and DefaultLongitude read from a seperate file, such as location.json, if available, this way, a common config for multiple bots could be maintained easier with differing locations.  For backwards compatibility, if location.json does not exist, it should proceed to look for this information in config.json

**Comment by Marsinator** [comment]
the devs will decide on this.

**Comment by theloser** [comment]
To add to this: it would be great if there would be something like a "default.json" with every setting set to default. This file should change with every new version and new setting that is implemented, and requires no editing.

There should be an **addiional **"custom.json" were only those options are entered for which the user wants "non default" settings, i.e. DefaultLatitude/DefaultLongitude. Settings in "custom.json" will override the "default.json" settings.

This was it would be easy to separate "default" and "custom" settings.

**Comment by nfettinger** [comment]
Splitting the configuration into multiple files has been discussed, and declined by the developers.

**Comment by nfettinger** [comment]
@theloser when upgrading, the config.json file is automatically upgraded to include the missing keys and their default values.

**Comment by theloser** [comment]
@nfettinger This only works on auto updates and new releases, right? What if I am compiling current master versions between rnew releases? There is no auto aupdate feature for this, so I have to check for config changes manually (or am I missing something?).

**Comment by thrca** [comment]
My use case is as follows:  Lets say I maintain 20 bots.  I want to keep the configs common, as updates come out, or I tweak certain features to work a specific way, but all 20 bots are in different locations.  I have to manually merge changes to 20 different config files, which are all identical except for the default location (and auth, which is in another file already).  The only other thing that is typically unique per bot is the websocketport.
