### ISSUE TITLE
[Suggestion] Change "UseTransferIvForSnipe" to "UseKeepMinIvPercentageForSnipe"

### ISSUE THREAD

**Issue by theloser** [NECROBOTIO/NecroBot#2498]
Please change "UseTransferIvForSnipe" to "UseKeepMinIvPercentageForSnipe", because there is no "TransferIv" setting.

**Comment by Taranis01** [comment]
It also would make sense to start all settings with their according category too. For example for Sniping settings put the "Snipe" always in the beginning: Snipe_UseKeepMinIvPercentage

**Comment by Marsinator** [comment]
I do agree on cleaning up the config even further.
It's up to the devs

**Comment by Taranis01** [comment]
@Marsinator best would be to be able to sort values and to comment them. But for that an other language/file type would be needed as json does not support this
