### ISSUE TITLE
System.IO

### ISSUE THREAD

**Issue by darksachiro** [NECROBOTIO/NecroBot#2499]
![capture](https://cloud.githubusercontent.com/assets/16268964/17365870/6721ea9a-5956-11e6-8fee-aef8bbf674ac.PNG)

**Comment by Linewalker** [comment]
Set GPXPath to off if you don't have the GPX file.

**Comment by Naprosnia** [comment]
Maybe change "UseGpxPathing" to false in configs. Or confirm gpx file path.

**Comment by nfettinger** [comment]
This is a configuration issue, not a development one.

**Comment by darksachiro** [comment]
![capture](https://cloud.githubusercontent.com/assets/16268964/17366750/c981681a-595a-11e6-9b44-38a3b37e7f28.PNG)

**Comment by darksachiro** [comment]
It is set to false and does not work also I apologize for posting in the wrong section
