### ISSUE TITLE
KeepMinOperator is not used when evaluating TransferWeakPokemonTask

### ISSUE THREAD

**Issue by jenixavire** [NECROBOTIO/NecroBot#2500]
`if ((pokemon.Cp >= session.LogicSettings.KeepMinCp) ||
                    (PokemonInfo.CalculatePokemonPerfection(pokemon) >= session.LogicSettings.KeepMinIvPercentage &&
                     session.LogicSettings.PrioritizeIvOverCp) ||
                    pokemon.Favorite == 1)
continue;`

This check just combines whether PrioritizeIvOverCp is true and then OR checks if pokemon has either higher cp or higher iv then in KeepConfig declared. My expectation would be that TransferWeakPokemon will check "weak" pokemons by using the KeepMinOperator. So a pokemon with 2000 cp and 85 iv with KeepMinCp=2000 and KeepMinIv=90 and PrioritizeIvOverCp = false and KeepMinOperator = "and" will lead to transfer that pokemon.

**Comment by qwer4790** [comment]
the "or" and "and" are reversed..the "or" is actually "and"

**Comment by noodle-** [comment]
Why was this TransferWeakPokemonTask even added when minkeepcp and minkeepiv we're doing the job just fine before?

**Comment by theloser** [comment]
Hm, I think you missed some "(" and ")" in your interpretation:

TransferWeakPokemon will skip (not transfer) the current pokemon if

1) Pokemon CP is greater or equal to KeepMinCP
**OR**
2) Pokemon Perfection is greater or equal to KeepMinIvPercentage **AND** PrioritizeIvOverCP is set to true
**OR**
3) Pokemon is favored

**Comment by Adriannyo** [comment]
> TransferWeakPokemon will skip (not transfer) the current pokemon if
> 
> 1) Pokemon CP is greater or equal to KeepMinCP
> OR
> 2) Pokemon Perfection is greater or equal to KeepMinIvPercentage AND PrioritizeIvOverCP is set to true
> OR
> 3) Pokemon is favored

If `TransferWeakPokemon = true` will it still keep at least one of each?

**Comment by theloser** [comment]
@Adriannyo No.

**Comment by Adriannyo** [comment]
@theloser So, how would I achieve what v0.5.0 was doing: Keep at least one of each, KeepMinDuplicatePokemon = 1, KeepMinCP = 2000, KeepMinIV = 95.0 while also keeping evolvable Pokemon according to amount of candies and transfer everything else?

**Comment by theloser** [comment]
@Adriannyo please go to the discord channel if you have any config related question, thank you!

**Comment by jenixavire** [comment]
> 1) Pokemon CP is greater or equal to KeepMinCP
OR
2) Pokemon Perfection is greater or equal to KeepMinIvPercentage AND PrioritizeIvOverCP is set to true
OR
3) Pokemon is favored

Yeah, I get the idea of that. My problem with that is: you can't force that he should ONLY skip the pokemon transfer if it is ABOVE KeepMinCP AND ABOVE KeepMinIvPercentage. This is just a hardcore version of an OR to skip the transfer - but when using KeepMinOperator I would think that you can force it to only skip it if both are true (KeepMinOperator = "and")!
