### ISSUE TITLE
[Sugesstion] Transfer All Pokemon Below **** Cp/Iv

### ISSUE THREAD

**Issue by ThatAce** [NECROBOTIO/NecroBot#2504]
how about adding config to transfer all pokemon below **** cp/iv or maybe priotizing one

**Comment by 750z** [comment]
+1

**Comment by HansonWK** [comment]
It already does this.

**Comment by Adriskye** [comment]
it does but not working properly

**Comment by simplyphp** [comment]
It's already fixed in the repository, but not latest version. The next release will have the fixed included.
