### ISSUE TITLE
Filter for sniping

### ISSUE THREAD

**Issue by 750z** [NECROBOTIO/NecroBot#2505]
Filter to ignore some pokemon while sniping. 
The amount of pokeballs i waste on lickitung only to be transferred seems like a waste

**Comment by Rykee** [comment]
There is a filter which pokemon you want to snipe already..

"PokemonsTransferFilter": {},
  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "bulbasaur",
      "ivysaur",
etc.
