### ISSUE TITLE
What are the input strings these pokemon?

### ISSUE THREAD

**Issue by evrentlbs** [NECROBOTIO/NecroBot#2506]
Nidoran♂ (Pokémon)
Nidoran♀ (Pokémon)
Farfetch'd (Pokémon)
Mr. Mime (Pokémon)

for ex I want to add these pokemon to lists below:

`  "PokemonsTransferFilter": {`
`    "Snorlax": {`
`      "KeepMinCp": 0,`
`      "KeepMinIvPercentage": 0.0,`
`      "KeepMinDuplicatePokemon": 100`
`    },`
`    "Dragonite": {`
`      "KeepMinCp": 0,`
`      "KeepMinIvPercentage": 0.0,`
`      "KeepMinDuplicatePokemon": 100`
`    }`
`  },`
`  "PokemonToSnipe": {`
`    "Locations": null,`
`    "Pokemon": [`
`      "snorlax",`
`      "dragonite"`
`    ]`
`  },`

thanks.

**Comment by simplyphp** [comment]
Ask in #support discord channel, not here. https://discordapp.com/channels/209253611031625728/209274880275906560
