### ISSUE TITLE
Sniping with several Accounts

### ISSUE THREAD

**Issue by AllUpps** [NECROBOTIO/NecroBot#2508]
I am running 3 bots with one pogo feeder. it seems that they cant snipe the same coord. it is shown on every 3 but only one will catch it.

**Comment by AllUpps** [comment]
i also tried 3 pogo feeder on diffrent ports and still only one starts to catch

**Comment by theloser** [comment]
I have four bots and one pogofeeder running and every single bot is sniping. Sometimes all four of them succeed, sometimes only a few, sometimes none. Don't know why, but I don't bother :)

**Comment by AllUpps** [comment]
i just saw sometimes all 3 bots start catching the pokemon after the message sniping a pkmn at 12.12 44.12 appears. but sometimes only 2 or just one starts even catching. the others just do nothing -> no message like catch flee etc. just nothing

**Comment by AllUpps** [comment]
sometimes it start catching sometimes nothing happens

**Comment by AllUpps** [comment]
everyting i get is:
#[19:58:23] (SNIPER) Sniping ein Lahmus mit unknown IV in 22.244511,114.151784...
and then just moves on without doing anything. i feel like missing lots of snipes because of this.

**Comment by theloser** [comment]
There are a lot of false announcements in the channels, so sometimes there just is no pokemon to snipe.
