### ISSUE TITLE
[Enhancement] "KeepMinLevel" & "TransferAllUnderThreshold"

### ISSUE THREAD

**Issue by CedricBongaerts** [NECROBOTIO/NecroBot#2509]
The following two options would be great if they were added.

Currently I have the bot setup as such:

```
  "KeepMinCp": 1400,
  "KeepMinIvPercentage": 85.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
```

Though in my eyes two issues come in mind:
1) Even though you set up the 'KeepMin' options, it keeps 1 of each poke that you catch. It would be nice to get an option for the bot to "TransferAllUnderThreshold".

In other words: (Using the example above) If the poke does not have a CP of 1400 'or' a IV of 85.0 simply transfer it.

2) With the above example: It would also be nice to have an option to filter out, based on levels.
I don't think alot of people are going to level up a 1 dratini with 100%IV.
It would be nice to have an option to simply transfer all pokes under a certain level regardless of threshold stated above.

Hope this is clear!

Thanks

**Comment by nfettinger** [comment]
I believe the configuration item you are looking for is TransferWeakPokemon

**Comment by CedricBongaerts** [comment]
TransferWeakPokemon does not seem to do this. (Just tried it out)

**Comment by ScrubbyMcScrubber** [comment]
I've just tried this and it didn't do anything.

`  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
`
