### ISSUE TITLE
Pokestop Problem

### ISSUE THREAD

**Issue by bignuts** [NECROBOTIO/NecroBot#2510]
I have a problem with pokestop, as i'm running a quite small loop, 1,5 km total in my town, with a total of 5 pokestop on gpx path, i'm getting some random pokestop each loop.

First run i get 3/5, second 2/5 , third 4/5 ect

with the help of necrobot visualizer i managed to spot the error, i don't know if the error was on prior release, i think everything was fine. I have also modified the track with the exact coordinate of pokestop shown on necrobot info log, the still getting same result even if i'm running on it.

Anyone has got the same problem?

edit: Also using CentralParkPokeStop.gpx poested here, the bot is skipping some Pokestop even in the first run, there's difference in NecrobotVisulaizer and the the screenshot preview of the path here on github.

edit2: same issue here apparently #2296

**Comment by theloser** [comment]
What's ypur walking speed? With the default walking speed of 31 km/h you'll finish your loop in about 3 minutes. Pokestops have a cooldown of 5 minutes, so after completing a single loop the pokestops are probably still on  cooldown.

**Comment by bignuts** [comment]
My walking speed is 15 km/h, if i run for the first time the bot still i don't get all teh pokestop on the way. And also i see there's a file called LastPos with last coordinate of the bot, everytime i start the bot keeps starting at initial coord in setting file.

**Comment by nfettinger** [comment]
Are you sure the timers have expired after each run. I assume so since it is such a long loop, but please double check.

**Comment by bignuts** [comment]
I already checked, i'm posting some screenshot so everyone can see the problem.

http://imgur.com/a/vN2yQ

**Comment by theloser** [comment]
You are saying

> each zig zag created by the path should be a pokestop

How do you know? NecrobotVisualizer doesn't show them, so how do you know there are pokestops Because of the "red signs" in the first picture? These are not pokestops, theses are markers for the gpx trail!

**Comment by bignuts** [comment]
> How do you know? NecrobotVisualizer doesn't show them, so how do you know there are pokestops Because of the "red signs" in the first picture? These are not pokestops, theses are markers for the gpx trail!

Because i'm having the same issue with my own rounte, and i know for sure that the bot is walking on them, i'm pretty sure that also each marker is a pokestop on Central park path, i posted this just to have more evidence of this.

**Comment by spamfighter82** [comment]
gpx sure has some issues. sometimes it skips waypoints (especially at the end) and i have made a route from my neighborhood and the bot wont activate all pokestops (and yes, not even on the 1st run and the route is about 10km with a walking speed of only 12km/h)

**Comment by bignuts** [comment]
I'm pretty sure that release 0.4 and below wasn't having this issue.

**Comment by spamfighter82** [comment]
what he should walk like:
https://postimg.org/image/bj1f5wiup/
what he actually does:
https://postimg.org/image/9f4o6n2mv/

and doenst really care about most of the pokestops

**Comment by bignuts** [comment]
> what he should walk like:
https://postimg.org/image/bj1f5wiup/
what he actually does:
https://postimg.org/image/9f4o6n2mv/

and doenst really care about most of the pokestops

yeah i noticed it too, is not accurate at all.

Anyway i found another problem running CentralParkPokestops_Period.gpx, the bot doesn't complete the path, here's a picture (http://imgur.com/a/M2v7I) should i open new issue for this? @nfettinger

**Comment by spamfighter82** [comment]
I have the feeling that route breakes after a certain amount of waypoints, added more to catch more pokestops and now he travels to the beginning of the track even sooner.
