### ISSUE TITLE
[IDEA] AboveMaxReachableCP for transfer/evolve/power-up

### ISSUE THREAD

**Issue by Zahlii** [NECROBOTIO/NecroBot#2511]
Hi,

In addition to #2406 I would like to propose the following filter possibilities:

(* means settings for Keep/Evolve/Upgrade)

*AboveMaxReachableCP: 2500,
*MinLevel: 80,0, // percentage of trainer level, i.e. level 20 means we keep only pokemon with level 16

**Explanation:**
Filtering by IV or CP alone isn't enough, even when used in combination.

If we filter on IV AND CP we may lose Pokemon which could be very strong when evolved or powered up (e.g. Dragonite IV 100 Level 10)
If we filter on IV OR CP we end up with high-IV low-level Pokemon taking up space (e.g. a IV 95 Level 1 Dragonite which takes 5 million stardust)

As such we need the MinLevel-setting and I would suggest using that as a percentage of the trainer level (since the Pokemon we catch depend on that level).

However, even if I have a goddamn 100 IV Golbat I don't want to bother keeping it because it's maximum CP when fully upgraded is 1921.

As such I would propose **calculating the maximum reachable CP for every Pokemon**, taking into account it's IV and further evolutions. That is, a Level 1 Dratini with 99 IV will have around 3490 MaxCP.

This way, we will be able to only keep Pokemon that have the potential to be really strong while at the same time having an appropriate level (not taking millions of stardust/candies). It also keeps strong not-yet evolved pokemon!

**Comment by spamfighter82** [comment]
That goes even further than my #2440 and i am for it.
+1
