### ISSUE TITLE
Can we have the feature to skip a pokemon if the IV does not meet our requirements?

### ISSUE THREAD

**Issue by Gemori** [NECROBOTIO/NecroBot#2512]
I want to be able to catch all pokemon if they meet lets say 100 iv. If not, skip them. Is this possible?

**Comment by nfettinger** [comment]
You dont want the XP and candy from catching then transferring the weak ones?

**Comment by XManuel1239** [comment]
nfettinger, well, if i would want 100 iv pokemon i would like it not to waste any on weak,so i think that is great

**Comment by Gemori** [comment]
I'm not interested to rushing to max trainer level. That looks too suspicious.

**Comment by Gemori** [comment]
From what I've seen in game, you cannot transfer a "favorite" pokemon. Is there a way we can auto favorite 100 iv pokemon? And then have the bot transfer everything else? This would work.
