### ISSUE TITLE
[Request] Load auth.json file per command line option

### ISSUE THREAD

**Issue by theloser** [NECROBOTIO/NecroBot#2517]
As said in #2013 

It would be great to use different auth.json files per command line option, so we can use one instance of the bot with the same config.json but with different auth.json files / different accounts.

**Comment by nfettinger** [comment]
I suggest that when using the command line options for configuring the login information, the auth.json is ignored completely.

**Comment by nfettinger** [comment]
for example. Necrbot.exe --auth "google" --user "abc@gmail.com" --pass "123"

**Comment by theloser** [comment]
Sure, that's one way to do it.
I was thinking of "necrobot.exe --authfile account1.json", "necrobot.exe --authfile account2.json" and so on...

**Comment by nfettinger** [comment]
I personally dont see how your suggested method is any simpler than having separate folders.

**Comment by theloser** [comment]
One folder compared to 30 folders (no, I am just using four accounts, but others obviously are going crazy, see #2520 :-)), 30 times to check a config.json for the correct settings after an manual upgrade (see my last comment on #2497) -- a single folder with a single config.json and an option to use this single config.json on multiple accounts would be great. Even better: see my first comment an #2497 .
