### ISSUE TITLE
Hard drive memory issue

### ISSUE THREAD

**Issue by tojejo** [NECROBOTIO/NecroBot#2520]
Hello i had issue last night with Necro version 6.2.0, i dont know if its repaired at 6.3.0 but i cant see it in changes log.
Problem was with large log files, around 100-300 MB for each .txt file log. So it made by the night about 5-10 logs for each account - its about 1 GB in each account. Got around 40 GB with 30 accounts running for 10 hours.

**Comment by nfettinger** [comment]
You can edit and rebuild the bot to lower the log level so that not as much is printed out.

**Comment by nfettinger** [comment]
Also, try turning this value off: VerboseRecycling

**Comment by tojejo** [comment]
Thanks, i'll try turning VerboseRecycling off, because right now its enabled, but what is this function for? ;)

**Comment by nfettinger** [comment]
It removes this type of text from the output:
[09:36:54] (RECYCLING) 25x ItemPokeBall
[09:36:58] (RECYCLING) 7x ItemGreatBall
[09:37:03] (RECYCLING) 13x ItemPotion
[09:37:08] (RECYCLING) 2x ItemSuperPotion
[09:37:14] (RECYCLING) 1x ItemRevive

**Comment by nfettinger** [comment]
You could suggest adding a configuration option to disable the background logging if you don't need it.
