### ISSUE TITLE
Crashing NecroBot

### ISSUE THREAD

**Issue by lorenzbaum** [NECROBOTIO/NecroBot#2521]
After a few hours NecroBot 0.6.3 is crashing: 
![screenshot 2016-08-03](https://cloud.githubusercontent.com/assets/16428818/17368172/3806b348-5993-11e6-8b8f-8eec83f1377d.png)
Sorry for the German log, i hope it can help you

**Comment by nfettinger** [comment]
Looks like a corrupted response from the server caused this.

**Comment by lorenzbaum** [comment]
Maybe you should catch it, that the bot is not completely crashing.

**Comment by Linewalker** [comment]
#2491 should just be catched.

**Comment by SwoleSnorlax** [comment]
Same issue
