### ISSUE TITLE
Pokemon Not Getting Transferred

### ISSUE THREAD

**Issue by abali1** [NECROBOTIO/NecroBot#2526]
Ok, so i have some moves setup for pokemon such as Snorlax and Dragonite but they are not getting transferred even tho they are not in the PokemonNotToTrasnfer list and i have the following settings:
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 0,
  "KeepMinIvPercentage": 80.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,

  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

    },
    "Snorlax": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["ZenHeadbuttFast","HyperBeam"],
      "KeepMinOperator": "and"

Can anyone see why my pokemon arent getting transferred,??

**Comment by bignuts** [comment]
keep min cp 0, keeps all snorlax with cp more than 0, so every snorlax?
Also transfer weak pokemon set to true did you try that?

**Comment by abali1** [comment]
what i want to do is just keep the snorlaxes with the moves and in the IVPercetange i have listed regardless off CP.

**Comment by Taranis01** [comment]
@bignuts i wouldnt try transfer weak pokemon as it is not clear how that defines what is weak
@abali1 are you sure your "Moves" Syntax is right?
PriortizeIvOverCp is broken in latest release version, you may try to put it of (as you have put the operator to "and" it wont do anything anyway

**Comment by abali1** [comment]
@Taranis01 yeah my moves syntax is right and your suggesting i put the operator to "or" instead??

**Comment by Taranis01** [comment]
@abali1 yes! sorry for beeing vague

**Comment by abali1** [comment]
@Taranis01 will try it and comment back.

**Comment by Taranis01** [comment]
"ken" from the discord channel said that it works only when only one move is used as a requirement, try this too and report back

**Comment by bittzz** [comment]
From my understanding Pokemon wont get transfered from PokemonNotToTrasnfer list, they can only be "Spared" from beeing transfered.

**Comment by BigAlGit** [comment]
@abali1 I haven't been able to get the transfer filter work for anything to transfer a pokemon with the last few builds.

**Comment by Marsinator** [comment]
looks like it doesnt transfer when the pokemon has one of the two movesets. it should only not transfer when it has BOTH movesets.

or there should be an option of and/or for movesets 1 and 2

**Comment by abali1** [comment]
Yeah guys so heres the breakdown:
1. If the pokemon has one of the moves (move 1), it will be kept without checking move 2
2. the IV and CP are being completely ignored but thats due to IVoverCP being broken in the latest release
3. Settling KeepMinOperator: "and" is what we need to do incase people are confused between "or" & "and"

**Comment by bittzz** [comment]
@abali1 this is my results from some testing

1. Pokemon only go through PokemonTransferFilter when beeing transfered by TransferDuplicatePokemon
2. Pokemon will be kept if it has one of the Moves, IV and CP is ignored
3. Pokemon will be kept without any of the Moves if it meets the min IV or/and min CP

**Comment by abali1** [comment]
@bittzz I would have to agree with all those, i am currently looking for a way to find a temporary fix to this until the developers get to it. Will keep you posted. Also get back to me if you find anything else.

**Comment by bittzz** [comment]
U can solve it if u have VS

Change "KeepMinCp": too 5000, this will make all pokemons except the best one go through PokemonTransferFilter

then change the statement in TransferDuplicatePokemonTask.cs to
or change the if statement in TransferDuplicatePokemonTask.cs to
if (duplicatePokemon.Cp >= pokemonTransferFilter.KeepMinCp ||
PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) > pokemonTransferFilter.KeepMinIvPercentage &&
pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move1) && pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move2))

this will make it save all Snorlaxes are above 80% IV and have ZenHeadbuttFast & HyperBeam as Moves

Beware tho, ull need to mention all ur pokemons in PokemonTransferFilter

**Comment by abali1** [comment]
@bittzz ahahahah I literally just did the same thing!!!! I was about to message as well.
