### ISSUE TITLE
No information about "TransferDuplicatePokemonOnCapture"

### ISSUE THREAD

**Issue by Tim1975** [NECROBOTIO/NecroBot#2528]
Hi,
i hope this is not the wrong place, but i have no idear where to ask.

The Parameter "TransferDuplicatePokemonOnCapture" is not in the wiki and i ask what exactly it does?

Anybody an idear?

Normaly i thing it transfers Pokemons directy after he catched it (if the pokemon is "transferable" (>KeepMin etc). But i am not sure.

Can anybody explain this parameter pls?

Thanks!

**Comment by Taranis01** [comment]
your thoughts are right, thats what it does

**Comment by Tim1975** [comment]
But what happend when i set it to "false".
When will the duplicates transfered when it is set to false?

**Comment by Taranis01** [comment]
they will transfered later, i dont know the exact time.
Please use the Discord channel for other questions
