### ISSUE TITLE
[BUG]UseGreatBallAboveCp/UseUltraBallAboveCp doesn't work

### ISSUE THREAD

**Issue by zeropo** [NECROBOTIO/NecroBot#2529]
Necrobot always uses ultraballs first, then greatballs, so the balls left are always pokeballs.

**Comment by nfettinger** [comment]
What version are you using? What does your config look like? Could we see some output?

**Comment by zeropo** [comment]
@nfettinger 
version:
0.6.3(in fact all versions doesn't work)
config:
http://imgur.com/a/P78SG
output:
http://imgur.com/a/2peW9

really hope to fix this, missed some rare pokemons due to no great/ultraball:(

**Comment by lisim** [comment]
Note im also getting this issue, first i thought it was because the Min catch number was all set to 0 but changing this has not fixed anything

**Comment by Agger84** [comment]
@zeropo your probability values should be in decimals. 
for example 20% is .2 (not 20.00) 5% is .05

**Comment by FabryB** [comment]
See #1746
