### ISSUE TITLE
TransferWeakPokemon

### ISSUE THREAD

**Issue by bittzz** [NECROBOTIO/NecroBot#2530]
When botting your Pokemon-space fill up really fast, even if you have high min IV and min CP. And we are all lazy so clearing out the trash manually i a pain in the ass.

My suggestion is, with a few tweaks to the code make it possible to only save high IV pokemons with the best move set. 
Three changes would make this possible.

#1 
As of now TransferDuplicatePokemon: true & KeepMinDuplicatePokemon: 0 will make the bot keep 1 of each Pokemon regardless of IV, CP & Move set. To get rid of the last one we need to use   TransferWeakPokemon: True. The problem with this is it doesnt check settings in PokemonsTransferFilter, which means it will remove low IV/ CP pokemons but the high IV/CP pokemons can possibly have shit Move set.

We can solve this by extending the conditions in the if statement in TransferWeakPokemonTask.cs
something like this
```
		var pokemonTransferFilter = session.Inventory.GetPokemonTransferFilter(duplicatePokemon.PokemonId);

                if (((pokemon.Cp >= session.LogicSettings.KeepMinCp) ||
                    (PokemonInfo.CalculatePokemonPerfection(pokemon) >= session.LogicSettings.KeepMinIvPercentage &&
                    session.LogicSettings.PrioritizeIvOverCp) ||
                    (PokemonInfo.GetLevel(pokemon) >= session.LogicSettings.KeepMinLvl && session.LogicSettings.UseKeepMinLvl) ||
                    pokemon.Favorite == 1)) || ((pokemon.Cp >= pokemonTransferFilter.KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(pokemon) > pokemonTransferFilter.KeepMinIvPercentage) ||
                    pokemonTransferFilter.Moves.Contains(pokemon.Move1) || pokemonTransferFilter.Moves.Contains(pokemon.Move2))
```
#2
As of now the bot checks the Move set with a "or" condition alongside the IV and CP. It also uses "or" condition with MOVE1 and MOVE2. This makes the bot save Pokemon with 1 correct move regardless of second move, IV and CP.
To fix this we need to change the IF statement to something like this

```
                if ((duplicatePokemon.Cp >=
                    pokemonTransferFilter.KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >
                    pokemonTransferFilter.KeepMinIvPercentage) &&
                    (pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move1) &&
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move2)))
```
#3
A pokemon can have multible good Move sets and although pokemonTransferFilter.Moves can contain more then 2 moves it creates a problem for Pokemon with 2 diffrent move sets with 4 diffrent moves. Dragonite for example have according to pokemongo.gamepress.gg Dragon Breath & Dragon Claw as best offensive Move set and Steel Wing & Dragon Pulse as best defensive Move set.
Even though we can add "Moves": ["dragonBreathFast", "dragonClaw", "steelWingFast", "dragonPulse"] to our config, this makes it possible for the bot to save a Dragonite with Dragon Breath & Dragon Pulse and so on.

To solve this we could extend "Moves": [] to "MoveSet1": [] & "MoveSet2": []

**Comment by abali1** [comment]
Well it has not been defined what defines TransferWeakPokemon so keep it set to false for now. As for the config, PrioritizeIvOverCp is currently broken and being worked on by the developers.

**Comment by bittzz** [comment]
@abali1 Im pretty sure TransferWeakPokemon is the same as the old "KeepMinDuplicatePokemon": 0.

With TransferWeakPokemon it will transfer everything below minIV &/or minCP 
Without TransferWeakPokemon it will keep atleast 1 of each Pokemon.

**Comment by abali1** [comment]
@bittzz you got a copy of the TransferDuplicatePokemonTask.cs file that I can view?? For some reason, and i am guessing its a basic error, I cannot get it to compile.

**Comment by bittzz** [comment]
@abali1 I dont have VS on this computer. I just looked at the source here on github.
But can take a look at yours if u pastebin it

**Comment by abali1** [comment]
@bittzz I am bit confused to exactly where you are asking this if statement to be changed/added.

**Comment by bittzz** [comment]
@abali1 
in TransferDuplicatePokemonTask.cs https://github.com/sawirth/NecroBot/blob/6f30f141bc9729e3b1a430cdd29f5e35656eade0/PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs

You can see this If statement
```
                if (duplicatePokemon.Cp >=
                    pokemonTransferFilter.KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >
                    pokemonTransferFilter.KeepMinIvPercentage ||
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move1) ||
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move2))
```

Just swap out the last two "||" with "&&"

so it becomes
```
                if (duplicatePokemon.Cp >=
                    pokemonTransferFilter.KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >
                    pokemonTransferFilter.KeepMinIvPercentage &&
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move1) &&
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move2))
```

**Comment by abali1** [comment]
@bittzz jesus christ, i am idiotic. Yes i see what you mean!!

**Comment by bittzz** [comment]
actually u need to add some brackets aswell

```
 if (duplicatePokemon.Cp >=
                    (pokemonTransferFilter.KeepMinCp ||
                    PokemonInfo.CalculatePokemonPerfection(duplicatePokemon) >
                    pokemonTransferFilter.KeepMinIvPercentage) &&
                    (pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move1) &&
                    pokemonTransferFilter.Moves.Contains(duplicatePokemon.Move2)))
```

**Comment by bittzz** [comment]
Okey! got everything working, and servers go down =/
