### ISSUE TITLE
pokemon level filter,

### ISSUE THREAD

**Issue by Szili89** [NECROBOTIO/NecroBot#2534]
Hi!
It could be nice if we could filter by the level of the pokemons also.
As I realized this feauter not available yet, or?

**Comment by spamfighter82** [comment]
#2523 seem like we get our wish

**Comment by Szili89** [comment]
And how does this works because I have just add this line to the config:
"KeepMinLvl": 25,
But when I started the program it is deleting it always.

**Comment by nfettinger** [comment]
For configuration help, please use the wiki and Discord Chat.
