### ISSUE TITLE
When will the duplicates be transfered if "TransferDuplicatePokemonOnCapture=FALSE"?

### ISSUE THREAD

**Issue by Tim1975** [NECROBOTIO/NecroBot#2538]
Does anybody know what the trigger for transfering duplicate pokemon is, when TransferDuplicatePokemonOnCapture=FALSE (which means they wont be transfered direct after the catch)?

**Comment by abali1** [comment]
So from my understanding, once you reach your KeepMinDuplicatePokemon value, it will transfer it the next time it encounters the pokemon. 

For example: 
KeepMinDuplicatePokemon: 1 (this means that there will be the orignal pokemon and one extra)
You catch a pidgey and then you catch another one later. They have not been transferred yet, but once you catch the third, the settings are checked against your captured pidgeys and the two closest are kept while the other one is transferred.

**Comment by Tim1975** [comment]
If i set "KeepMinDuplicatePokemon = 1", i will have 2 pokemon of every typ stored?
Or only one?
And if i set it to "0", does it mean every pokemon will be transfered or do i still leave ONE of every pokemon in my inventory?

**Comment by FabryB** [comment]
KeepMinDuplicatePokemon has been changed between 0.6.2 and 0.6.3
Until 0.6.2 it was keep = X
From 0.6.3 it is keep = X + 1

So this means from 0.6.3 if you set it to 0, it will keep 0 DUPLICATED pokemons.
I think this was changed to better reflect the name, but the config autoupdateder didn't change your value subtracting 1, so if you updated from <= 0.6.2 to 0.6.3 you have to manually subtract 1.

Ofc the final number of pokemons you have is also influenced by other parameters: IV and CP

**Comment by Tim1975** [comment]
Thanks. One more question:

Example:
"Magmar":
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"

Now, i find 5 Magmas:
1. CP1450 -> will be not transfered
2. CP1430 -> will be not transfered
3. CP1400 -> will be transfered or not?
4. IV98 -> will be transfered or not?

**Comment by Caydenz** [comment]
KeepMinCp and KeepMinIvPercentage have a higher priority than KeepMinDuplicatePokemon. None will be transferred.
