### ISSUE TITLE
[Feature Request] Collect Coins/Stardust from Pokemon holding Gyms

### ISSUE THREAD

**Issue by stuartmeek** [NECROBOTIO/NecroBot#2541]
The timeout is 21 hours and you have to manually click a button in the "store" to get the rewards, which means that at some point the timer is going to hit zero in the middle of the night and you lose time logged until it is claimed.
Would be great if the bot could claim those rewards for you (and let you know if your Pokemon has been kicked out of a Gym?)

**Comment by nfettinger** [comment]
Duplicate

**Comment by stuartmeek** [comment]
You've marked this as a duplicate of a ticket that was closed without being resolved and which asks for a new issue to be raised if this is still the case in 0.6.2 - can I ask why?
As far as I can see it isn't something the bot is doing in 0.6.3 - is there a config option i've missed?
