### ISSUE TITLE
Multiple snipe locations, only seems to catch last one

### ISSUE THREAD

**Issue by cjhwick** [NECROBOTIO/NecroBot#2544]
Using PoGo location feeder, just updated to latest release. 

If there's a back log of pokemon/co-ords in the feeder it seem to go through all of them and stop to catch the last one. Any settings I should be changing to avoid this? 

"MinDelayBetweenSnipes": 60000 currently

![](https://i.gyazo.com/ab1d8ee9370f2cd95d93f0a8fd126af8.png)

**Comment by djdookie** [comment]
I also see those blocks again and again now. I thought it's like a queue, and the bot didn't find the time to sniper. If he is ready to sniper, a lot of those pokemons are gone meanwhile. But I could be wrong.
It really just seems to snipe the latest from queue, but doesn't try the others anymore.

**Comment by cjhwick** [comment]
Must have been a problem with PoGo feeder, just updated to their release 4 hours ago and it's working as expected.
