### ISSUE TITLE
[Suggestion] Lowering KeepMinDuplicatePokemon transfers worst exemplars, not best

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2545]
If you lower **KeepMinDuplicatePokemon** and you have maximum duplicates for one or more pokemon types (you are at the the defined limit for one or more types), the bot starts transferring duplicates.

But unfortunately always the best exemplar is transferred instead of the worst (regarding IV).
This logic should be optimized. One could use **LevelUpByCPorIv** or a similar new parameter to let the user decide how to determine the better exemplars, by IV or CP.

I wonder that the transferring logic with dropping duplicates seems to differ from the normal transfer logic at this point?!

**Comment by Simpuhl** [comment]
I think this makes perfect sense, if at any case it's going to transfer something it should always be the weakest rather you choose to use CP or IV as primary.

**Comment by Knulen** [comment]
If you set **KeepMinDuplicatePokemon** to 0 and you have for example:
  **"KeepMinCp": 1800,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "or",**
Then it will still keep all the Pokemon above 90IV or 1800CP right?

The same for specific filters, for example:
    **"Blastoise": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"**
This will still keep all the Pokemons above 1800CP or 80IV?
