### ISSUE TITLE
Compile currently broken

### ISSUE THREAD

**Issue by Github-Nutzer** [NECROBOTIO/NecroBot#2546]
Error	CS0535	'ApiFailureStrategy' does not implement interface member 'IApiFailureStrategy.HandleApiFailure(RequestEnvelope, ResponseEnvelope)'	PoGo.NecroBot.Logic	O:\NecroBot-master\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs

**Comment by nfettinger** [comment]
Update your submodules. For additional support use Discord.
