### ISSUE TITLE
Auto Favorite not working (release 0.6.3 )

### ISSUE THREAD

**Issue by hughpearse** [NECROBOTIO/NecroBot#2547]
Currently I have several pokemon with 100% IVs. Necrobot outputs to the terminal periodically saying it is processing favorites, however when i open my phone none of them have a star.

  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": true,

**Comment by nfettinger** [comment]
This is an issue with the RocketAPI. The bot tries to send the favorite request, but the server either refuses it, or doesn't understand the message sent.

**Comment by nfettinger** [comment]
Please recreate this issue in the RocketAPI repository.
