### ISSUE TITLE
Request a funtion to ignore the pokemon you don't want

### ISSUE THREAD

**Issue by pogoaccount** [NECROBOTIO/NecroBot#2549]

**Comment by nfettinger** [comment]
Already exists in the config.json  
PokemonsToIgnore[]

**Comment by abali1** [comment]
Just add it to the Config.json

**Comment by pogoaccount** [comment]
when I change the pokemon items in config.json, the necrobot can't run

**Comment by hellatoker** [comment]
what is the proper syntax for this? im a bit new and also would like to ignore a bunch of pokemon
