### ISSUE TITLE
(NullReferceneException)Exception happening quite frequently

### ISSUE THREAD

**Issue by Sprinting** [NECROBOTIO/NecroBot#2550]
![image](https://cloud.githubusercontent.com/assets/16353379/17372229/8fe0750e-59c0-11e6-88ef-874facaebfcb.png)
This has been happening quite frequently Idk what's the issue

**Comment by nfettinger** [comment]
Duplicate of

**Comment by Sprinting** [comment]
How do I delete Issues? Sorry, I'm quite new
