### ISSUE TITLE
upgrading not detecting IV100

### ISSUE THREAD

**Issue by whiteshark-1975** [NECROBOTIO/NecroBot#2551]
https://gyazo.com/5bb95ccee5329f35275a5f95d465ef8a     "UpgradePokemonCpMinimum": 3300.0,
  "UpgradePokemonIvMinimum": 0.99,
  "UpgradePokemonMinimumStatsOperator": "or",     if  i set   "UpgradePokemonIvMinimum": 99.0    nothing happens anymore

**Comment by Simpuhl** [comment]
Mine actually says 100.0 for IV min "and" 0.00 for CP

Won't level up any of my 3 perfect IV's

**Comment by whiteshark-1975** [comment]
same here like the code just skip the iv100, mayby the iv100 has a special state that conflicts with the code.
ive read it over and over but just dont see the flaw.
        public async Task<List<PokemonData>> GetPokemonToUpgrade()
        {
            var upgradePokemon = new List<PokemonData>();

            if (!_logicSettings.AutomaticallyLevelUpPokemon)
                return upgradePokemon;

            var myPokemon = await GetPokemons();
            myPokemon = myPokemon.Where(p => p.DeployedFortId == string.Empty);
            
            IEnumerable<PokemonData> highestPokemonForUpgrade = (_logicSettings.UpgradePokemonMinimumStatsOperator.ToLower().Equals("and")) ?
                myPokemon.Where(
                        p => (p.Cp >= _logicSettings.UpgradePokemonCpMinimum &&
                            PokemonInfo.CalculatePokemonPerfection(p) >= _logicSettings.UpgradePokemonIvMinimum)).OrderByDescending(p => p.Cp).ToList() :
                myPokemon.Where(
                    p => (p.Cp >= _logicSettings.UpgradePokemonCpMinimum ||
                        PokemonInfo.CalculatePokemonPerfection(p) >= _logicSettings.UpgradePokemonIvMinimum)).OrderByDescending(p => p.Cp).ToList();

            return upgradePokemon = (_logicSettings.LevelUpByCPorIv.ToLower().Equals("iv")) ?
                    highestPokemonForUpgrade.OrderByDescending(PokemonInfo.CalculatePokemonPerfection).ToList() :
                    highestPokemonForUpgrade.OrderByDescending(p => p.Cp).ToList();
        }

i took a look on other bots based on necro, they use different approach but cant confirm theyr method work

**Comment by whiteshark-1975** [comment]
why dont we use the GetHighestsPerfect to obtain the list

**Comment by Simpuhl** [comment]
What ever makes it work would be nice

**Comment by Marsinator** [comment]
#2334 #2193

**Comment by Simpuhl** [comment]
This was closed but it still doesn't work :100: %
