### ISSUE TITLE
Request a funtion to change the ignorned catching pokemon in config.json

### ISSUE THREAD

**Issue by pogoaccount** [NECROBOTIO/NecroBot#2552]

**Comment by nfettinger** [comment]
I misunderstand what you need here. You can manually edit your config.json file and add the additional ones you want ignored.

**Comment by pogoaccount** [comment]
How could I change this
"PokemonsNotToTransfer": [
    "**venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"**
  ],
  "PokemonsToEvolve": [
    **"caterpie",
    "weedle",
    "pidgey",
    "rattata"**
  ],
  "PokemonsToIgnore": [
    **"caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"**

**Comment by pogoaccount** [comment]
If I change the items in bold face, the bot could not run

**Comment by IamAii** [comment]
I try adding Pokemon to my evolve list and the bot doesnt run also. 
I also have pokemon on my ignore part, and well it doesnt ignore them.

**Comment by abali1** [comment]
@pogoaccount What do you mean the bot could not run?? If you add the names of pokemon to ignore exactly the same way then it should work,
@IamAii can you show us your config file?

**Comment by Aneduna** [comment]
If you want to add dratini to 
>"PokemonsToEvolve": [
"caterpie",
"weedle",
"pidgey",
"rattata"
],

you could change it to

"PokemonsToEvolve": [
"caterpie",
"weedle",
"pidgey",
"rattata",
"dratini"
],

**Comment by pogoaccount** [comment]
If you can not understand, I could give a example
when I change these items as bellow
"PokemonsNotToTransfer": [
   // "venusaur",
    //"charizard",
    //"blastoise",
    //"clefable",
    //"muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ]
**the bot says: the exception caught. witting log buffer**

**Comment by theplaymate** [comment]
remove the commented pokemon, and it should work fine

**Comment by pogoaccount** [comment]
OH! I got it! Thank you

**Comment by abali1** [comment]
@pogoaccount yeah it should be renamed to
"PokemonsNotToTransfer": [
"venusaur",
"charizard",
"blastoise",
"clefable",
"muk",
"chansey",
"gyarados",
"ditto",
"snorlax",
"articuno",
"zapdos",
"moltres",
"dragonite",
"mewtwo",
"mew"
]

**Comment by pogoaccount** [comment]
@abali1 I should delete the items instead of adding //

**Comment by pogoaccount** [comment]
thank you @theplaymate

**Comment by abali1** [comment]
@pogoaccount you can do that or just add new pokemons like i did by copying one of commented pokemon and pasting it below and changing the name in quotation marks,

**Comment by Aneduna** [comment]
"Issue" solved. you can close the issue now @pogoaccount

**Comment by IamAii** [comment]
@abali1  -- The file is running just doesnt ignore the poke on the ignore list, and also Doesnt evolve my pidgeys like it did 2 days ago. When I add NidoranF or M to the list it doesnt work at all, cant figure out how to add those stupid things. got over 1300 candy for them.

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "StartupWelcomeDelay": true,
  "AmountOfPokemonToDisplayOnStart": 15,
  "ShowPokeballCountsBeforeRecycle": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1500.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.773674,
  "DefaultLongitude": -73.97102,
  "WalkingSpeedInKilometerPerHour": 45.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.09,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 3,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 1.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": true,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 100000,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 60,
  "TotalAmountOfRevivesToKeep": 50,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1500,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 2100,
  "UseGreatBallAboveIv": 95,
  "UseUltraBallAboveIv": 99,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew",
    "eevee"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToIgnore": [
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 125,
      "KeepMinIvPercentage": 1.0,
      "KeepMinDuplicatePokemon": 5,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 5,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1200,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 5,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 450,
      "KeepMinIvPercentage": 25.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 1300,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 800,
      "KeepMinIvPercentage": 75.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}
