### ISSUE TITLE
why do we have to choose? "LevelUpByCPorIv": 

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2553]
So I want to only have 100% pokemon and have them powered up only.
It should start with the 100% Pokemon that are the highest level and need the most dust.

As far as I can tell there is no option to do that yet, is there?

**Comment by Aneduna** [comment]
You can set to only keep 100% and not delete duplicates. That way you keep all 100% but nothing else.

**Comment by Simpuhl** [comment]
I currently have it set to level up anything that's 100% IV and over 0.0 CP

but it doesn't level up shit, I got min dust set to 200,000 but I got almost 400,000 :(

**Comment by Aneduna** [comment]
it could be that the 100% is broken, try setting it to 99% or smth like that.

And to @Marsinator im not sure if it starts at the pokemn with the highest level tho

**Comment by Marsinator** [comment]
@aneduna this is about powering up though, not transfers.

**Comment by Aneduna** [comment]
"LevelUpByCPorIv": "cp",
  "UpgradePokemonCpMinimum": 0.0,
  "UpgradePokemonIvMinimum": 99.0,
  "UpgradePokemonMinimumStatsOperator": "and",

Yea, I know.

**Comment by AllUpps** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2587
