### ISSUE TITLE
[Bug] Sniping currently misses feeded rares

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#2554]
With version 7a1e93be the sniping seems to leave out rare pokemons feeded by PogoLocationFeeder.
Multiple bots running on v0.6.3 catch a lot more of those rares, in direct comparison.
All bots use the same PogoLocationFeeder.
Seems to be a bug in this build.

**Comment by Simpuhl** [comment]
Off topic:

Question about sniping, Can you choose any location and not get soft banned or do you need to choose nests near the location your farming?

**Comment by nfettinger** [comment]
@Simpuhl Please ask for assistance in the Discord chat rooms.
