### ISSUE TITLE
[IDEA] Add Stardust/H as well as Evolution counter on title bar

### ISSUE THREAD

**Issue by Zahlii** [NECROBOTIO/NecroBot#2555]
Nothing more to say

**Comment by Aneduna** [comment]
Seems like a reasonable Enhancement

**Comment by nfettinger** [comment]
We are trying to move away from a long complicated title bar. Instead, the visualizer or a persistent portion of the console would be better.

**Comment by Simpuhl** [comment]
It does how ever the title bar is already huge as fuck, so if we did this maybe if we can have the bot extend itself by default also?

Or remove the long title bar all together and make the thing just show up more often within the cmds

**Comment by Aneduna** [comment]
Doing a persistent portion of the console is harder than it sounds tho. Maybe a Large Summery Message every 20 Pokestops or 20 minutes (random numbers) would be easier

**Comment by nfettinger** [comment]
Technically, the Visualizer should be able to display everything in the title bar currently, and all future requests without an issue.
