### ISSUE TITLE
Add "gps positions" shortcuts

### ISSUE THREAD

**Issue by zaikar** [NECROBOTIO/NecroBot#2561]
It would be nice to add something to use various Gps coordinantes in one same config and changing them over a "name" like:

Gpscordinatesname: "sydney";

name: "sydney"
loc: "100,0230"
loc "-22,0990"

name "tokyo"
loc: "100,0230"
loc "-22,0990"

So by just changing the "gpscordinatename" we can change our own list of places.

Easy to implement in favor of pragmatism.

Thanks

**Comment by nfettinger** [comment]
You can create various GPX files, and assign which one is run in your config.json
