### ISSUE TITLE
Transfer completely ruined after update

### ISSUE THREAD

**Issue by Sheetka** [NECROBOTIO/NecroBot#2562]
Hey guys! I had my bot on autoupdate and I found out when looking at my dumps that I lost TONS of pokemon, but kept the high cp ones.

Now I think I've fixed it, though it still keeps one of each pokemon for some reason.

If someone could look at my config I'd really appreciate it cause I'm lost

http://pastebin.com/jZFr6g7K

It also stores loads of pidgeys rattatas weedles and catterpies instead of evolving them right away

**Comment by nfettinger** [comment]
"RecycleInventoryAtUsagePercentage": 0.9,
this is for 90%
