### ISSUE TITLE
NecroBot only finding Pokemon with CP<25

### ISSUE THREAD

**Issue by nr1864** [NECROBOTIO/NecroBot#2569]
I have my bot running in Central park, New York. My trainer level is 23. Why is the bot only finding and catching pokemon with CP<25?

**Comment by Aneduna** [comment]
I am currently level 28 with latest dev. I currently don't have that issue. it should also not be an issue with the configs. They have nothing to do with the quality of pokemons.

What Version are you using?
Please post a screenshot of the issue

**Comment by nfettinger** [comment]
This could be a configuration issue, but it does not appear to be a bug.
