### ISSUE TITLE
Only finding low CP Pokemon

### ISSUE THREAD

**Issue by SystematicSkid** [NECROBOTIO/NecroBot#2570]
Hey guys, I love the bot, this is my only issue, every time I look in the console I notice it is catching very low level CP Pokemon, but as soon as I go out with my phone to manually catch them I always find Pokemon in the hundreds, any reason for this? Maybe a setting?

**Comment by nr1864** [comment]
Im getting the same thing. Im wondering whats causing it

**Comment by Aneduna** [comment]
duplicate #2569

**Comment by nfettinger** [comment]
I marked #2569 as a duplicate of this

**Comment by nfettinger** [comment]
Could it just be printing the value wrong. Could someone please verify this?

**Comment by nr1864** [comment]
Running version. 0.5.0
![image](https://cloud.githubusercontent.com/assets/20798316/17373794/aa057c34-595e-11e6-9143-bb4eb6b6522f.png)

**Comment by Aneduna** [comment]
These are the Levels you are looking at

**Comment by SystematicSkid** [comment]
Wow, thats really good, what coords are those? And this is what mine looks like,
http://image.prntscr.com/image/681bcc9b8e5442b29431e51c9988c3c3.png

**Comment by nr1864** [comment]
Oh! I was unaware of that Aneduna. Thanks! :)

**Comment by SystematicSkid** [comment]
Is that true? If so then what does the other lvl mean?

**Comment by nr1864** [comment]
I assume that's the actual level of the pokemon. While CP is combined stats?

**Comment by nr1864** [comment]
Magikarp Lvl: 22 CP: (138/165)
=
Magikarp [Pokemon Level] CP: (CP level)

**Comment by Aneduna** [comment]
22 = Pokemon Level
138 = current CP
165 = CP if 100% iv

**Comment by SystematicSkid** [comment]
Oooh, wow, thank you Aneduna!
