### ISSUE TITLE
Avoid using ultraball on rattata/pidgey/sparrow etc

### ISSUE THREAD

**Issue by Alekc** [NECROBOTIO/NecroBot#2571]
Is there a way to avoid using ultraballs on low level pokemon? I'd rather try to get them with greater balls max (and move to next pokemon if I'm unable to catch them within setted limit)?

**Comment by Marsinator** [comment]
"UseGreatBallAboveCp": 800,
  "UseUltraBallAboveCp": 1800,
  "UseMasterBallAboveCp": 2100,
  "UseGreatBallAboveIv": 90.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.3,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,

please play around with this values.
