### ISSUE TITLE
[BUG] Evolve pokemons when Pokemon Storage is nearly full not working

### ISSUE THREAD

**Issue by Rykee** [NECROBOTIO/NecroBot#2572]
As requested from #2182 by @NecronomiconCoding 
Relation to: #2465 (Caused by this bug)

The bug still appears in 0.6.3. 
If your Pokemon count reaches 241 the bot thinks your storage is full so it won't catch any more pokemon and want to transfer them. 
However the evolver knows the Storage still has 9 more space and if your "EvolveKeptPokemonsAtStorageUsagePercentage" is high enough (>=96.8) it won't start evolving the Pokemons.

Necessary config for the bug: 
"EvolveAllPokemonWithEnoughCandy": true, //For evolving
"EvolveKeptPokemonsAtStorageUsagePercentage": 100.0, //at least on 96.8 to reach the 242 limit
"KeepPokemonsThatCanEvolve": true,

Temporary workaround: 
"EvolveKeptPokemonsAtStorageUsagePercentage": 96.4 //at most!

My whole config: http://pastebin.com/JBV4fnk3

**Comment by nfettinger** [comment]
I see nothing in the code that prevents the logic from catching a Pokemon when the inventory is almost full.

**Comment by Rykee** [comment]
@nfettinger The bot thinks the inventory is full. 
As theloser said in #2465 

> That's not a bot issue I think but a general error with Pokemon Go: the number of pokemon you see in your Pokemon Go app on your phone is the number of pokemon plus the number of eggs you own (although there is a second tab which reads "9 of 9 eggs"). I already reported this to Niantic weeks ago and I got no response. And I think because the bot receives this number from Niantic it is wrong, too.

And if the bot thinks the Storage is full it'll try to transfer pokemons. (usually can't at that point, with my cfg at least)

```
else if (encounter.Status == EncounterResponse.Types.Status.PokemonInventoryFull)
                {
                    if (session.LogicSettings.TransferDuplicatePokemon)
                    {
                        session.EventDispatcher.Send(new WarnEvent
                        {
                            Message = session.Translation.GetTranslation(TranslationString.InvFullTransferring)
                        });
                        await TransferDuplicatePokemonTask.Execute(session, cancellationToken);
                    }
                    else
                        session.EventDispatcher.Send(new WarnEvent
                        {
                            Message = session.Translation.GetTranslation(TranslationString.InvFullTransferManually)
                        });
                }
```
