### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by FreeHitss** [NECROBOTIO/NecroBot#2574]
"TransferWeakPokemon": false,"

what is this? im having full inventory after 3-4hours and my bot doesnt transfer often. am i doing something wrong?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for help.

**Comment by abali1** [comment]
@FreeHitss TransferWeakPokemon basically will transfer pokemon that your settings deem not viable so mainly CP, if your min CP requirement is 1200 then any pokemon with CP less than 1200 will get transferred regardless of the IV so be careful of that, and as for your transfers. I cannot say unless until i see the config file or if there are any errors you are getting.
