### ISSUE TITLE
Unclear how and/or applys with moves.

### ISSUE THREAD

**Issue by darkfriend77** [NECROBOTIO/NecroBot#2575]
How does the AND / OR apply on the moves ...

A)
- cp or iv or moves
- cp and iv and moves

B)
- cp and moves or iv and moves
- cp and moved and iv and moves

**Comment by darkfriend77** [comment]
Example.:

"Arcanine": {
"KeepMinCp": 2000,
"KeepMinIvPercentage": 80.0,
"KeepMinDuplicatePokemon": 6,
"Moves": [FireFangFast,Flamethrower],
"KeepMinOperator": "and"
},

**Comment by nfettinger** [comment]
Please use the Discord chat for configuration help.
