### ISSUE TITLE
[v6.3] Transfer issues (KeepMinIvPercentage, KeepMinCp)

### ISSUE THREAD

**Issue by sturze** [NECROBOTIO/NecroBot#2578]
Hey guys,

i am struggling with the tansport settings... I am trying to get a configuration keeping only one of any pokemon, since it is not over IV 98, or it is not over CP2500. 
i tryed the following config, but its just not working.... whats wrong?!?!
```
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 98.0,
  "KeepMinOperator": "or",
  "KeepMinDuplicatePokemon": 1,
 "UseTransferIvForSnipe": true,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

  "PokemonsTransferFilter": {
    "Mew": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 0.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "or"
    }
  },
  "PokemonsNotToTransfer": [
    "zapdos",
    "moltres",
    "articuno",
    "mewtwo",
    "mew"
  ],
```

**Comment by Simpuhl** [comment]
Reading all the other reads on here regarding the same issue, it appears that there is a known bug the developers are working on.

**Comment by sturze** [comment]
@Simpuhl 
Thanks! that makes sense... so i'am not allone on this... good to hear that i am not to stupid to set this up :laughing:

**Comment by Marsinator** [comment]
we are fixing  "KeepMinOperator": "or",

please wait for next release

**Comment by sturze** [comment]
v.9.4 same issue
both eighter over cp2500 nor over IV 98
```
CP  412/ 414 | (97.81% perfect)	| Lvl 07	 NAME: Pinsir 
CP  840/ 848 | (93.41% perfect)	| Lvl 14	 NAME: Pinsir   
```
still no transfer... :cry:
