### ISSUE TITLE
[ISSUE] not receiving names to snipe

### ISSUE THREAD

**Issue by yy4cmm** [NECROBOTIO/NecroBot#2579]
yesterday with 6.1 it was working fine, today instead of "sniping a snorlax" it says something like "trying to snipe a pokemon" and the result is a "no pokemon found to snipe", its like its not receiving any names and when trying to snipe it doesnt actually look for anything

**Comment by Aneduna** [comment]
The Message trying to snpe a pokemon comes when a "missigno" is sent. Look into PogoFeeder or w/e you are using, if a missigno was sent

**Comment by yy4cmm** [comment]
was getting ONLY that message, for more than half an hour, with the feeder next to it seeing all diferent pokemons, i fixed it now using an old release and having it autoupdate.
NOTE: the issue is on a fresh download of last build.

**Comment by Aneduna** [comment]
Maybe the Changes in PogoFeeder caused that

**Comment by Aneduna** [comment]
Cant Confirm. Latest Commit on PogoFeeder & Necrobot seems to be working fine
