### ISSUE TITLE
moves arent translated in 0.6.4 [DE trans]

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2584]
please see the screen: http://puu.sh/qoBRa/2473b3ef9e.png

moveitself is translated to "bewegung", while the actual movename is not translated at all.

I wouldnt mind keeping them in English as most of the info found about the best moveset on the web is in English anyways and so are the inputs we use in the config.

So either translate the moves too, or (preferably), make bewegung say "move1"/"move2" again

**Comment by Oolaruu** [comment]
Moves are not translated ever for me (fr)
Anyway i'm gonna build the "move set template" in english for everyone.
Just need to found a complete list in english for that.

**Comment by Marsinator** [comment]
can we have this list publicly available. so people know what to put in the moves command in the config?

**Comment by Marsinator** [comment]
its the same with the english pokemon names. foreigners dont know them by heart
