### ISSUE TITLE
0.6.4 have 8 files, 0.6.0 have 5 files only (Release.zip)

### ISSUE THREAD

**Issue by Oolaruu** [NECROBOTIO/NecroBot#2585]
Hello.

Currently v0.6.4 got 8 files, whereas before v0.6.0 have only 5 files.
Would it be possible to revert back to have only 5 files ?

This is not a high priority Or maybe there's a reason for that.

Thanks.

**Comment by Marsinator** [comment]
I am pretty sure there is a reason for this.
Why does it matter anyways?

**Comment by Aneduna** [comment]
I think you can safely remove them (it did not crash on startup)

**Comment by Oolaruu** [comment]
It was just a simple remark on the number of files between the two versions.
There are no significant even if files have less is always better. I removed them just like before and it works.
If it's not really "needed" why to publish them ?

**Comment by NecronomiconCoding** [comment]
Its just the vshost files, if we are in a hurry we do not remove the files
