### ISSUE TITLE
Pls Add time to go to a pokestop, not only the Distance (meters)

### ISSUE THREAD

**Issue by codrin91** [NECROBOTIO/NecroBot#2586]

**Comment by Kostronor** [comment]
I get a timeframe `(122m)(29seconds)`

**Comment by Oolaruu** [comment]
I get a timeframe also.

**Comment by theloser** [comment]
> (INFO) Traveling to Pokestop: xxxxx (95m)(10seconds)

It has been there for a while now. Maybe some language files are incomplete? What language are you using?

**Comment by nfettinger** [comment]
It sounds like the user is running an outdated version. The distance/time should not be dependent on the translation files.

**Comment by codrin91** [comment]
I use it language,
![schermata 2016-08-03 alle 20 25 42](https://cloud.githubusercontent.com/assets/19703401/17377108/b4f47c26-59b8-11e6-935f-5cefa1872cd5.png)

**Comment by codrin91** [comment]
okay the it trans is :
 {
      "Key": "eventFortTargeted",
      "Value": "Arrivo al Pokestop: {0} in ({1}m)"
    },
and I edit to:
{
      "Key": "eventFortTargeted",
      "Value": "Arrivo al Pokestop: {0} ({1}m)({2}seconds)"
    },
And works :
![schermata 2016-08-03 alle 20 31 08](https://cloud.githubusercontent.com/assets/19703401/17377279/5990a2fa-59b9-11e6-9c74-b5cb0b3cb2b9.png)

**Comment by theloser** [comment]
@nfettinger See, it does depend on the language file someone is using (I edited my language files to leave out some useless information...)
