### ISSUE TITLE
[v6.4][Bug] Bot Still Not Auto Leveling 100% IV Pokemon

### ISSUE THREAD

**Issue by Whosdaman** [NECROBOTIO/NecroBot#2587]

**Comment by Whosdaman** [comment]
Maybe we could get a rework for the auto leveler? So we can set filters and stuff for it too? For example, auto level all above 95.0, but limit to 1 duplicate, beginning with highest percent first (including 100%!)

Highest priority should be getting the bot to level 100% Pokémon though.

**Comment by AllUpps** [comment]
comfirmed, still not working
