### ISSUE TITLE
UseKeepMinLvl and KeepMinLvl

### ISSUE THREAD

**Issue by xrhaomx** [NECROBOTIO/NecroBot#2588]
I had my settings as follows: 

"KeepMinLvl": 25,
"UseKeepMinLvl": false,

Despite UseKeepMinLvl being false, it transferred everything below level 25 anyway ^_^

**Comment by nfettinger** [comment]
That value does not appear in the default config.

**Comment by ChemiHatake** [comment]
If the UseKeepMinLvl is set to true, It will keep all the pokemon above the level set in KeepMinLvl when necrobot transfers duplicates/weak pokemon 

if its set to false, it will still do the process but it won't filter pokemon above the level set in KeepMinLvl, and in your case, 25.
