### ISSUE TITLE
[IDEA] Option to use only unlimited incubators

### ISSUE THREAD

**Issue by Knulen** [NECROBOTIO/NecroBot#2590]
As far I know this doesn't work automatically?
I would like the option to choose if I only want to use the unlimited egg incubators or all egg incubators. And maybe even add the option to give a preference which eggs to use with the limited and unlimited. Like 2.0KM for unlimited and 10.0KM for limited Egg Incubators.

**Comment by septemus** [comment]
Why? What benefit is there to save them? I feel like this is unnecessary.

**Comment by nfettinger** [comment]
This sounds like a needless option. You can configure it not to use incubators at all, and it will default to the best eggs first.

**Comment by Knulen** [comment]
If you have a new account, you can save the limited incubators for when you get to a higher level so the Pokemon you'll get are higher level as well

**Comment by Owinger** [comment]
MaxEggPlayerLevel: 20

**Comment by nfettinger** [comment]
If you want that, please disable your incubator use, and run it manually. Anything else will require you to edit the source code.
