### ISSUE TITLE
[Error] after 6.0.4

### ISSUE THREAD

**Issue by Rawrlex** [NECROBOTIO/NecroBot#2593]
![ss 2016-08-03 at 07 59 38](https://cloud.githubusercontent.com/assets/12886208/17376359/8086debe-59b5-11e6-91fa-da1ce5497fe5.png)

**Comment by Rawrlex** [comment]
..

**Comment by nfettinger** [comment]
This looks like a file format issue, but I cannot tell for sure because it is not in English.
Please use Discord chat for help with this. This tracker is for developmental issues only.
