### ISSUE TITLE
[Bug maybe] The bot catch the pokemon which  I've ignored 

### ISSUE THREAD

**Issue by pogoaccount** [NECROBOTIO/NecroBot#2595]
"PokemonsToIgnore": [
    "ivysaur",
    "charmeleon",
    "wartortle",
    "nidorino",
    "nidorina",
    "poliwhirl",
    "weepinbell",
    "tauros",
    **"pinsir",**
    "magmar",
    "electabuzz",
    "victreebel",
    "poliwrath",
    "vileplume",
    "nidoqueen",
    "nidoking",
    "clefable",
    "golduck",
    "golem",
    "weezing",
    "rhydon",
    "omastar",
    "tentacruel",
    "starmie",
    "hypno",
    "wigglytuff",
    "kabutops",
    "dewgong",
    "scyther",
    "pidgeot",
    "gengar",
    "kangaskhan",
    "seaking",
    "cloyster",
    "tangela",
    "jynx",
    "porygon",
    "gloom",
    "farfetchd",
    "omanyte",
    "onix",
    "dodrio",
    "kingler",
    "sandslash",
    "alakazam",
    "arbok",
    "magneton",
    "primeape",
    "raichu",
    "venomoth",
    "golbat",
    "magneton",
    "primeape",
    "raichu"
  ],
Though I wrote this, the bot  catch **pinsir**.

**Comment by pogoaccount** [comment]
@IamAii you may have the same problem

**Comment by IamAii** [comment]
I cant figure out why it is ignoring the ignore list.

**Comment by nfettinger** [comment]
This is a confirmed bug, the Ignore list is not used in the determination of whether or not to catch a Pokemon.

**Comment by ChemiHatake** [comment]
did it snipe that pinsir? or was it just a normal catch?

**Comment by slxdegrees** [comment]
Did you turn this on? "UsePokemonToNotCatchFilter": false,"
