### ISSUE TITLE
Player defined delay does not appear to be used between evolves

### ISSUE THREAD

**Issue by nfettinger** [NECROBOTIO/NecroBot#2597]
The following setting is not being used between evolves:
DelayBetweenPlayerActions

Instead, the evolves happen without any delay at all. This prevents users from humanizing the bot and putting a real delay of 21 seconds in their configuration.

**Comment by Simpuhl** [comment]
I noticed this also

**Comment by ChemiHatake** [comment]
Fixed it, now testing, will pr after I'm done.
