### ISSUE TITLE
New error in latest release 

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#2598]
![image](https://cloud.githubusercontent.com/assets/262571/17376765/d8a966f6-596b-11e6-95aa-dfbc95159e34.png)

**Comment by ExpressNaab** [comment]
yep me too

**Comment by BigAlGit** [comment]
Wonder if it is a server issue, just popped up for me too.

**Comment by Simpuhl** [comment]
I think it may be a google issue, I had to sign in on my phone again... hmm

**Comment by nfettinger** [comment]
This is a corrupted server response. There is already an issue to handle the error code.

**Comment by Simpuhl** [comment]
@nfettinger 

Is it safe to continue running the bot and ignore the error then?
