### ISSUE TITLE
Minduplicate: 0 deletes everything

### ISSUE THREAD

**Issue by averes2** [NECROBOTIO/NecroBot#2599]
I just auto updated and it deleted everything

**Comment by dzik87** [comment]
confirmed. stop changing it back and forward .... i had it set to 0 as for 0.6.3 and now it is changed again

**Comment by nfettinger** [comment]
This is a configuration issue. Please check your config every time you update. If you are the forgetful type  like me, please set StartupWelcomeDelay to true.

**Comment by averes2** [comment]
The release notes did not mention a change with MinDuplicate
