### ISSUE TITLE
Suggestion more webs for snipe

### ISSUE THREAD

**Issue by Adriskye** [NECROBOTIO/NecroBot#2600]
Add https://discordapp.com chats for snipe like

#90iv_room https://discord.gg/yA3Cw
#90ivplus_only https://discord.gg/vqCaY

Maybe other people can add more webs/bots or chat for snipe

**Comment by nfettinger** [comment]
This is not a developmental issue. Please refrain from entering issues here that dont relate to the Necrobot code itself.
