### ISSUE TITLE
Need a Config

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2601]
Hello.

I need your help because I lost my mind trying to properly configure the config file.
I was using NecroBOT and then switched to another BOT because NecroBOT config was ruined, reinstalled it, and still it didn't work as I wanted, and that's not only that, I'm sick of this config.

I need a config file that will do the following:
1) 300 km/h.
2) Central Park.
3) Keep EVERY Pokemon till the inventory is full and ONLY then it will evolve them ( ALL OF THEM ) and ONLY then it will transfer Duplicated Pokemons or WEAK Pokemon that I don't need.
4) Keep every item that I get from Pokestop and ONLY when the inventory is full it will delete what's not needed.
5) Auto Update.
6) Auto Snipe Pokemon ( Yes I have Location Feeder and I know how to use it ).
7) Won't Transfer the RARE Pokemon!
8) Other stuff that will increase XP/h, such as Auto Using Incubators and stuff that I don't know about.
9) Delay 0 between actions and stuff.

**Comment by Simpuhl** [comment]
Let me get some snack, blanket and bottle for you also lol

**Comment by nfettinger** [comment]
If you rename your config.json file, it will be recreated to the default one.
For future reference, questions like this belong in the discord chat room.

**Comment by Fazy5** [comment]
1) 300km/hr for a human ? Good luck getting banned in 5 mins max maybe ?

And this is where the answer ends
