### ISSUE TITLE
the bot transfer all my pokemon help please

### ISSUE THREAD

**Issue by svetlaan** [NECROBOTIO/NecroBot#2602]
the bot worked properly then changing place I reboot and is the bug appeared, I have the same with 0.6.3 or version 0.6.4

Sorry for my English

**Comment by nfettinger** [comment]
Please ask for help editing your configuration using the Discord chat rooms.

**Comment by svetlaan** [comment]
Ok thx

**Comment by dzik87** [comment]
"KeepMinDuplicatePokemon":  set to 1. they keep changing how it works. in 0.6.3 0 meant keep 0 extra pokemnos now in 0.6.4 means keep 1 each.

**Comment by svetlaan** [comment]
it solved my problem thank you I lost 15 pokemon with this shit :'(
