### ISSUE TITLE
TransferWeakPokemonTask is not honoring KeepMinOperator

### ISSUE THREAD

**Issue by jenixavire** [NECROBOTIO/NecroBot#2603]
`{
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "and",
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 0,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true
}`

I would expect that a Pokemon with 1500 CP and 85 IV would get transfered by TransferWeakPokemon because it doesn't match first AND second criteria. In fact NecroBot keeps the Pokemon because it OR checks those criterias in the referenced Task instead of honouring the KeepMinOperater. I already submitted this behaviour in #2500 but someone prematurely closed it.
Thanks for your time & help. Awesome Project.

**Comment by nfettinger** [comment]
KeepMinOperator is not used anywhere in Necrobot. Not sure where you got this configuration item.

**Comment by jenixavire** [comment]
@nfettinger maybe you would check your settings first before closing something: https://github.com/NECROBOTIO/NecroBot/blob/master/PoGo.NecroBot.Logic/Settings.cs#L177 It is in every config.json since version 0.6.0
