### ISSUE TITLE
[Feature request] Auto levelup favorite pokemons

### ISSUE THREAD

**Issue by Revoss** [NECROBOTIO/NecroBot#2604]
Is not included right? I think I;d be a good idea

**Comment by Fazy5** [comment]
Is the favourite feature working now ? Does it really favourite the desired pokemons or just spams that it has done it ?

**Comment by ShaggyHW** [comment]
@Fazy5 even without the autofavourite feature if you can favorite any pokemon by yourself, i think the option fot the bot to auto level your favorites would be welcomed by almost everyone

**Comment by Fazy5** [comment]
Agreed
