### ISSUE TITLE
How to input GoogleUsername containing dots, i.e.: "lekka.lokka66"?

### ISSUE THREAD

**Issue by qualo138** [NECROBOTIO/NecroBot#2605]
Hi,

I have an email containing dot,

How to input GoogleUsername containing dots, i.e.: "lekka.lokka66"?

**Comment by Alekc** [comment]
try to remove the dot. If i remember correctly google just ignore dots anyway in the name (ale.kc = alekc = ale....kc)

**Comment by nfettinger** [comment]
Please use the Discord chat rooms from now on!
valid format is abc.xyz@gmail.com

**Comment by kirito-su** [comment]
Simply do not use the Dont..
