### ISSUE TITLE
Bot resetting GPX route when server is unstable 

### ISSUE THREAD

**Issue by Tiburcio23** [NECROBOTIO/NecroBot#2606]
Hello,

Whenever a "**Niantic Servers unstable, throttling API Calls**." message comes up, the bot resets the GPX route.
This means that it doesn't matter how far it is along the route, when this error is encountered the bot will move back to the start of the route.
This is very suspicious as it will move along a line across the city and going through buildings, streets and whatever is in the way.

Please see the attached screenshot and you will see the straight line from **Center Drive** towards **Grand Amy Plaza**. That's when the error occurred.

I have tried with another GPX track (at another city) and the same thing happened whenever the "servers unstable"  message came up.

![route_reset](https://cloud.githubusercontent.com/assets/20822488/17376902/979424f2-5985-11e6-8c08-6eef6d58740b.png)

**Comment by nfettinger** [comment]
This is a duplicate issue.
