### ISSUE TITLE
[bug snipe]

### ISSUE THREAD

**Issue by Adriskye** [NECROBOTIO/NecroBot#2608]
"UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,

It keeps sniping pokemons on config , not only from pokezz

**Comment by nfettinger** [comment]
set the value to false.
