### ISSUE TITLE
[Proposal] add config explanation file to releases. 

### ISSUE THREAD

**Issue by Alekc** [NECROBOTIO/NecroBot#2611]
Right now our wiki is waaaaaay  out of sync, and we are adding new settings with every release (I believe that just in the current one we had about 8 new settings). 

What about creating md file with explanation for various config parameters and "force" developers to alter it if they add new settings.

**Comment by nfettinger** [comment]
The wiki is worked on when we have time.

**Comment by ifbatmanwasreal** [comment]
What someone should do is write a comment with every command to explain what they do. I did this for one of my configs.

It's pretty much useless though cause the organization of the config changes and so do the commands.

![untitled](https://cloud.githubusercontent.com/assets/8885748/17377647/98ee3ac4-5988-11e6-9680-1128cafc8963.png)
