### ISSUE TITLE
Problem with System.NullReferenceException

### ISSUE THREAD

**Issue by frazzzer89** [NECROBOTIO/NecroBot#2613]
I just copied this text from log file, can you help me?

[21:31:02] Pidgey	- CP: 100  IV: 62.25%   [Best CP: 176  IV: 35.19%] (Candies: 10)
[21:31:07] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoGo.NecroBot.Logic.Inventory.<DeletePokemonFromInvById>d__8.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:строка 57
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:строка 39
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by nfettinger** [comment]
Duplicate issue.
