### ISSUE TITLE
Getting NullReferenceException at update v0.6.4

### ISSUE THREAD

**Issue by kemalelmizan** [NECROBOTIO/NecroBot#2615]
![bug necrobot](https://cloud.githubusercontent.com/assets/15223219/17377367/937ac6e2-59e3-11e6-96f7-711d4a8b16a0.png)

And after this error it loops at start and get error again.
I didn't get any error like this at previous version.
I think it's because I have 0 pokeballs and 0 greatballs? I'm not sure.

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by SwoleSnorlax** [comment]
same issue

**Comment by VadarGaming** [comment]
Same issue, this only seems to be happening on one of my accs though.

**Comment by VadarGaming** [comment]
seems like this has just fixed itself

**Comment by brokenHDD** [comment]
Same issue here, even after verifying my google account.

**Comment by VadarGaming** [comment]
This error does not seem to be related with pokeballs as i have chekced the acc and it has x118 of normal pokeballs and 4 greatballs

**Comment by brokenHDD** [comment]
k

**Comment by VadarGaming** [comment]
Error has now popped up on another bot running

**Comment by dzik87** [comment]
i loged in manually went thru welcome stuff then logout and started bot again - it works now ok.
