### ISSUE TITLE
[Suggestion] Rename KeepMinDuplicatePokemon to NumberKeepOfEachPokemon

### ISSUE THREAD

**Issue by PokemasterMike** [NECROBOTIO/NecroBot#2618]
Since its working now as of before, rename it to reflect what it actually does. Less confusion, everybody wins. (maybe set the default to 1 ?)

**Comment by Fazy5** [comment]
Default to 0 makes more sense. No duplicates as default.

**Comment by Simpuhl** [comment]
So if i have this set to 1,

I'm currently keeping 2 total?

0 would be keeping 1 total?

**Comment by elmaarmut** [comment]
You shouldn't be keeping 2 if you have it set to 1. The 2nd one is probably being kept due to your min CP or min IV settings.

**Comment by noremac13** [comment]
Is there a way to set it so I keep 0 of each?  I don't care about keeping unique Pokemon if they are bad so I would rather have that space for higher IV/CP Pokemon instead of a 500CP 42% Porygon or some trash like that.

**Comment by Simpuhl** [comment]
Transfer weak Pokémon true 

Duplicate 0
