### ISSUE TITLE
Error right now

### ISSUE THREAD

**Issue by eLyiN** [NECROBOTIO/NecroBot#2622]
[20:46:57] (ERROR) System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() en C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:línea 324
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() en C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:línea 24
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() en C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:línea 16
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() en C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:línea 36

**Comment by Caliboss** [comment]
damn man.. same issue here.. i tried redownloading, resetting up. nothing helps

**Comment by eLyiN** [comment]
PogoFeeder confirmed!

**Comment by Caliboss** [comment]
what u mean

**Comment by eLyiN** [comment]
Close PogoLocFeeder and it works! atleast for me

**Comment by nfettinger** [comment]
Duplicate issue.
