### ISSUE TITLE
Keep Getting errors "End of stack trace from previous location where exception was thrown" continuously with 0.6.4

### ISSUE THREAD

**Issue by Kara-ism** [NECROBOTIO/NecroBot#2626]
Hi,
I'm getting errors "End of stack trace from previous location where exception was thrown" which let my account logged in again and again.

The version I used is 0.6.4, please take a glance of this occurrence.
Thanks!!"D

http://pastebin.com/TrMvU1uf

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by sollematthew** [comment]
@nfettinger Where the is the ticket for this?
