### ISSUE TITLE
[Bug] 0.6.4 - PrioritizeIvOverCp

### ISSUE THREAD

**Issue by morrrido** [NECROBOTIO/NecroBot#2627]
"PrioritizeIvOverCp": false
it is transfering stronger CP pokemons.
![064](https://cloud.githubusercontent.com/assets/20801587/17378113/9b483d8e-59b4-11e6-9a7d-8bc144a11865.png)

**Comment by lamlam77777** [comment]
You set this settting to false
So CP over IV

**Comment by Numbe9988** [comment]
check if "TransferWeakPokemon" is true.

**Comment by morrrido** [comment]
> You set this settting to false
> So CP over IV

Maybe thats the point of me complaining about a bug?
I Chose CP over IV, and it transfer the HIGHEST CP........

Also, "TransferWeakPokemon": false,

**Comment by lamlam77777** [comment]
I think the bot used the max cp
