### ISSUE TITLE
Rename Pokemons

### ISSUE THREAD

**Issue by carminaburana123** [NECROBOTIO/NecroBot#2628]
Even when setting 
  "KeepMinIvPercentage": 0.0,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
the app doesn't rename all pokemons
I also tried:
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,

**Comment by nfettinger** [comment]
Configuration issue, please use Discord chat.
