### ISSUE TITLE
debian version and speed script 

### ISSUE THREAD

**Issue by Tagada22** [NECROBOTIO/NecroBot#2629]
hello ,

i'm new in this domaine but not possible to have this version on debian ?

And i have others questions , its possible to speed the bot ?

Thanks

**Comment by VadarGaming** [comment]
speeds for walking etc can be changed in the config, for debian idk.

Just run it on windows server 2012 xD

**Comment by nfettinger** [comment]
Several forks have been created for debian builds. Please use the Discord chat channels for further assistance.
