### ISSUE TITLE
farfetchd and mrmime dont work on  "PokemonsToIgnore": [

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2636]
they still get caught, even though they are on the list. everything else is getting ignored, as advertised.

 "PokemonsToIgnore": [
    "rattata",
    "zubat",
    "spearow",
    "farfetchd",
    "mrmime",
    "kangaskhan",
    "drowzee",
    "seel",
    "psyduck",
    "weedle"

**Comment by Marsinator** [comment]
reported by a user on discord. he is on 0.6.4 however

**Comment by nfettinger** [comment]
This is a known issue that the ignore filter is not used.

**Comment by Marsinator** [comment]
it does seem to work for some pokemon though.

[21:31] Kisame: [15:31:46] (INFO) Skipped Psyduck
[15:31:46] (INFO) Skipped Zubat
[21:32] Kisame: it works on all pokemon but farfetch,mrmime,kangaskha
[21:40] Mars: tauros?
