### ISSUE TITLE
Config Question about transferring pokemons

### ISSUE THREAD

**Issue by jaypeeb0917** [NECROBOTIO/NecroBot#2638]
Why am I still retaining these pokemons despite having these settings:
Ivysaur CP 1114 IV 35
Nidoqueen CP 1417 IV 35

Config:
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1000,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
"PokemonsNotToTransfer":  <-----BLANK

The two examples I posted are the only copies of each kind. So only one Ivysaur and Nidoqueen. Is it because I have not found a higher IV and CP and it is keeping it because of KeepMinDuplicatePokemon1 ?? 
Hoping for someone to confirm if what I think is right or wrong. Thanks.

**Comment by nfettinger** [comment]
Please use Discord chat rooms
