### ISSUE TITLE
p

### ISSUE THREAD

**Issue by feedbuck** [NECROBOTIO/NecroBot#2639]
![necro problem](https://cloud.githubusercontent.com/assets/20823270/17379230/b83daff2-59c1-11e6-8f20-ee16fad3d89b.png)
 
Please help! Thanks

(Why do u nfettinger keep closing this?)

**Comment by swc-tine** [comment]
I got it too, No idea why they keep closing it lol

**Comment by SirRob1997** [comment]
they are aware alot of people already submitted this issue

**Comment by feedbuck** [comment]
ok u can close this now if u want

**Comment by aruby813** [comment]
Usually it means the server is down.

**Comment by theloser** [comment]
According to discord: " If you're running a lot of  bots, Niantic has started limiting IPs so those accounts who have excessive requests / multiple accounts from the one location are temporarily blacklisted and receive empty map objects"

**Comment by swc-tine** [comment]
I'm running 1 and got those errors

**Comment by mik5u** [comment]
im running 2, and got same thing

**Comment by feedbuck** [comment]
Im running 1 bot, whats happenind? :C
