### ISSUE TITLE
[Observation] Transfer Before Catch Guarantees Success

### ISSUE THREAD

**Issue by Whosdaman** [NECROBOTIO/NecroBot#2642]
Running 4 bots, and every single time a Pokemon is transferred immediately before a throw is made, the Pokemon is caught 100% of the time. I noticed this when a pokemon would escape, 1, 2, 3...etc. times then in between throws a pokemon would be transferred and the very next throw was a success.

This also is true for transfers before the initial throw as well.

Can anyone confirm these findings? Maybe we can take advantage of this and get a function for holding pokemon to purposefully transfer before attempting to catch a pokemon.

**Comment by nfettinger** [comment]
I dont seem to follow what you are asking here.

**Comment by Whosdaman** [comment]
Well unfortunately the log doesn't record transfers. But here I go to explain...

Bot looks for pokemon, finds pokemon X and catches it.
Pokemon X will be transferred, but before the bot is able to transfer it, pokemon Y shows up.
Pokemon Y is tough to capture, and escape out of first throw, then the second throw.
Before bot is able to throw the third pokeball, bot transfers Pokemon X.
After, the bot throws the third ball and the result is a success.

I am saying this happens every single time a pokemon is transferred before a throw. It will guarantee a catch.

**Comment by PokemasterMike** [comment]
maybe its an issue with the log, i.e. flush buffer bug ?!?
in the log it looks like....

[22:08:01]pokemonX has been transferred
[22:09:02]pokemonX has been caught [CP 123, IV 77%, etc]

**Comment by Whosdaman** [comment]
No @pokemastermike, it would be more like

[22:09:02]pokemonY has escaped [CP 123, IV 77%, etc]
[22:08:01]pokemonX has been transferred
[22:09:02]pokemonY has been caught [CP 123, IV 77%, etc]

**Comment by wakrad** [comment]
[22:09:02]pokemonY has escaped [CP 123, IV 77%, etc]
[22:08:01]pokemonX has been transferred
or
[22:08:01]pokemonY With LOWER CP has been transferred
then
[22:09:02]pokemonY has been caught [CP 123, IV 77%, etc]

**Comment by artuan00** [comment]
I believe it's just a bit of lag in their capture being logged/received.
