### ISSUE TITLE
No usable pokestops found in your area

### ISSUE THREAD

**Issue by Sheetka** [NECROBOTIO/NecroBot#2644]
I have suddenly been getting this a lot, even with an older version of the bot.

Anyone know what gives?

**Comment by Kachime** [comment]
Same, with both of my account

**Comment by XEngine** [comment]
+1

**Comment by vpvp** [comment]
same

**Comment by Whosdaman** [comment]
I am getting this on every bot right now. Probably the servers are down

**Comment by Sheetka** [comment]
Someone mentioned new IP bans

**Comment by EJMason** [comment]
Just started getting this?

**Comment by Ricktza** [comment]
Same.

**Comment by vpvp** [comment]
there is new pokemon go update in google store, maybe thats why...

**Comment by ifbatmanwasreal** [comment]
Can't get un soft banned. I think it's happening guys.

It was fun while it lasted!

**Comment by Sheetka** [comment]
OOOOOOH DAAAAARN

**Comment by fuqua123** [comment]
same here, cant get unbanned and no pokestops found nearby, happend a few minutes ago.

**Comment by MickuMo** [comment]
Same here, I think this is it guys!

**Comment by brokenHDD** [comment]
Servers are currently down so calm down. 

http://downdetector.com/status/pokemon-go

**Comment by cepoterbang** [comment]
if u'r guys login manually.. everything work fine... maybe server issue..

**Comment by ifbatmanwasreal** [comment]
No this is a panic thread. The servers are fine. The bot is dead. No body exists on purpose. No body belongs anywhere. Everyone is gonna die.

**Comment by nfettinger** [comment]
Make sure you are not banned, running multiple accounts off of a single IP will cause this issue.

**Comment by brokenHDD** [comment]
nfettinger, you're a frigging nazi.

**Comment by Sheetka** [comment]
Someone hold my hand

**Comment by ifbatmanwasreal** [comment]
@Sheetka 

We can go down with this ship together.

**Comment by darksoon** [comment]
i have the same, but i can play in nox ;) so keep cool

**Comment by ifbatmanwasreal** [comment]
lol it's just a server thing, I'm just playin'. The bot and all of our accounts will be fine.

**Comment by oOTSXSTOo** [comment]
u guys are genius, funny

**Comment by fuqua123** [comment]
i can still get on pokemon go on my iphone using google login, so i dont get what server thing ??
