### ISSUE TITLE
[Suggestion] Close the "issue" tab when Niantics server are down

### ISSUE THREAD

**Issue by theloser** [NECROBOTIO/NecroBot#2654]
...or this will be flooded with issues like "boooh, i can't login, your bot suckz" :)

Niantic's server are down atm, and issues raise like there will be no tomorrow...

**Comment by nfettinger** [comment]
Problem is, nobody knows if it is just a few minutes item, or a few hours.

**Comment by AdamWinter** [comment]
I cannot log in either iin bot. But I can in game and it is actually very fast and stable. I am in Czech republic, so I suppose only some servers are down.

**Comment by vpvp** [comment]
same, iam from czech republic as well... Bot isnt runing, but on phone is all right and stable

**Comment by theloser** [comment]
@AdamWinter @vpvp Wrong issue, go away.

**Comment by AdamWinter** [comment]
@theloser you mad? "D

**Comment by FourtyOneCZ** [comment]
Prihlaseni opet mozne. Nyni se potykam s zadnymi pokepointy. Ze by zmeny v Niantic Labu ?

**Comment by Whosdaman** [comment]
Because the other thread got locked, another bot found a fix for this issue:

https://github.com/PocketMobsters/PokeMobBot/commit/52e7c7b6ba398eb9c96fd007be168513f9bed44a

**Comment by theloser** [comment]
@FourtyOneCZ @Whosdaman Wrong issue. Go away.

**Comment by AddiIgneel** [comment]
Any idea how long will this last?

**Comment by GamingMaster777** [comment]
i think they shut down the server to target the bot. who knows?

**Comment by TheSavior** [comment]
It is a protobuf issue. I'm not sure if Necrobot uses these protobufs, but essentially all the map projects and python bots are watching this issue: https://github.com/AeonLucid/POGOProtos/issues/131

**Comment by GamingMaster777** [comment]
first wats a protobuf and 2nd pokemobBot work. its a mod of necro or something. legit works right now

**Comment by GamingMaster777** [comment]
nvm poke mob bot is wak as well
