### ISSUE TITLE
Fully customizable logic for evolve/transfer/upgrade

### ISSUE THREAD

**Issue by Zahlii** [NECROBOTIO/NecroBot#2655]
Considering #2511 , #2406 , #2440 I think I have a viable solution that puts an end to all the different configuration options and problems, which could aslo avoid confusions.

We have the following filter options:
- IV // IV value as normal
- currentCP // Current CP values
- maxEvolvedCP // CP that can be reached based on the last evolution and the current IV, i.e. Level 1 Dratini with 99 IV would be 3495 or so
- level // current level of the pokemon
- trainerLevel // current trainer level

And on further implementations possibly
- candiesForUpgrade  // self explaining
- dustForUpgrade // self explaining
- isCommonPokemon // true for rattata, pidgey, weedle etc used to farm
- canBeEvolved // enough candy to be evolved
- canBeUpgraded // enough candy/stardust to be upgraded
- CPRank // ranked between the same pokemon, i.e. Magikarp 152 CP is CPRank1, Magikarp 148 CP is rank 2
- IVRank // same as above

Now we add the following configuration options:
- KeepPokemonLogic: String
- UseKeepPokemonLogic: Boolean

- EvolvePokemonLogic: String
- UseEvolvePokemonLogic: Boolean

- UpgradePokemonLogic: String
- UseUpgradePokemonLogic: Boolean

A PokemonLogic could then be sth like that:

`maxEvolvedCP >= 2800 && level >= 0.8*trainerLevel && IVRank <= 3 // sniping setup for the three most strong and easily upgradeable pokemon`

`isCommonPokemon && canBeEvolved // EXP farm setup`

The BIG advantage is that we can combine them both so that we can BOTH farm XP and keep important strong pokemon!

For the implementation it could perhaps be done by just running some kind of eval on it.

EDIT:
Of course every Pokemon could have it's own settings - the same as with the current config!

Example Config (keeps strong ones, evovles and keeps common ones, upgrades strongest ones):
```
{
  "KeepPokemonLogic":"(maxEvolvedCP >= 2800 && level >= 0.8*trainerLevel && IVRank <= 3) || (isCommonPokemon && canBeEvolved)",
  "EvolvePokemonLogic":"isCommonPokemon && canBeEvolved",
  "UpgradePokemonLogic":"maxEvolvedCP >= 2800 && !canBeEvolved && canBeUpgraded && IVRank <= 2",
  "Pokemon":{
    "Charizard":{
      "UpgradePokemonLogic":"level>25 && iv>90"
    }
  }
}
```

**Comment by facinick** [comment]
this would be perfect. too much confusion with current config file. increasing xp and iv both would be great.

**Comment by Kartoffelbrust** [comment]
This is more complicated than the current config at least to me so i don't like it at all

**Comment by littlemonster1** [comment]
sound good to me. I would use something like 
axEvolvedCP >= 2800 && level >= 0.8*trainerLevel && IVRank <= 3 && IV >= 95%
though :D

**Comment by josephdouce** [comment]
[https://github.com/NECROBOTIO/NecroBot/issues/2652](https://github.com/NECROBOTIO/NecroBot/issues/2652)

**Comment by Zahlii** [comment]
@littlemonster1 maxEvolvedCP would take into account the IV while calculating it too

**Comment by Adriskye** [comment]
They should do in a easy panel , not in the config file , it will be more easy for people to set everything

**Comment by RoseFlunder** [comment]
Don't know how to implement it properly, but would be nice.

**Comment by Zahlii** [comment]
@RoseFlunder probably the old minCP minIV etc..although I would remove them and put the default logic from the current config into it, e.g. `currentCP > 1000 || iv > 95`

**Comment by RoseFlunder** [comment]
A library which could be useful to implement it:
[https://csharpeval.codeplex.com/](https://csharpeval.codeplex.com/)
