### ISSUE TITLE
[minor] Changing wording in settings configuration (on first run)

### ISSUE THREAD

**Issue by Alekc** [NECROBOTIO/NecroBot#2657]
Right now there is following text
```
[21:10:48] () ### Setting Default Position ###
[21:10:48] () Please enter a Latitude (Right click to paste)
xxx
[21:12:46] () Lattitude accepted: 51.4978968
[21:12:46] () Please enter a Longitude (Right click to paste)
xxx
```

Which is a bit confusing because on windows (at least W10) you can't right click to paste. 
I think we should change it to more generic one (remove right click to paste)

**Comment by Adriskye** [comment]
http://www.howtogeek.com/howto/25590/how-to-enable-ctrlv-for-pasting-in-the-windows-command-prompt/

**Comment by Oolaruu** [comment]
It would be interesting to directly paste a co-ords entirely like
Lat,Long
So users can found a nice spot, and just copy/paste directly both infos.

**Comment by Alekc** [comment]
Yes Adriskye (you can also press shift+ins), but average user should not be "tricked" in thinking that it should work for everyone :)

**Comment by abratar** [comment]
On Windows 10 its activated by default so you can right click to paste. If I'm not mistakes, it's the "Quick Edit Mode" setting in cmd... turn it on if you disabled it somehow

**Comment by facinick** [comment]
you can right click to paste in windows 10. and i think we have a bigger issue going on so..
