### ISSUE TITLE
help for log setting pokestop

### ISSUE THREAD

**Issue by thiron** [NECROBOTIO/NecroBot#2660]
log : Tidak ada PokeStop yang bisa digunakan di sekitarmu. Apakah jarak maksimal terlalu kecil?

translation.id.json

**Comment by Venzhel** [comment]
Biasakan membaca sebelum bertanya.

Google translate english to indonesia

**Comment by nfettinger** [comment]
This is not the place for configuration help. Use the Discord chat rooms

**Comment by aldyjrz** [comment]
semua bot sedang tidak bisa digunakan, mungkin Niantic melakukan update

**Comment by thiron** [comment]
siap om...
saya udah baca om, mungkin yang indo bisa membantu menjelaskan gitu om @Venzhel 

@aldyjrz okay om, terimakasih atas infonya
