### ISSUE TITLE
No usable pokestops found in your area, all the time!

### ISSUE THREAD

**Issue by feedbuck** [NECROBOTIO/NecroBot#2661]
Can someone help me?

**Comment by murfman** [comment]
same thing happening to me.

**Comment by chauhan-rahul** [comment]
same here!!

**Comment by carlanivans** [comment]
https://otakukart.com/animeblog/2016/08/03/minimum-scanning-time-doubled-see-effects/

**Comment by somani6** [comment]
Please reffer to #2659

**Comment by nfettinger** [comment]
Duplicate of #2645
