### ISSUE TITLE
Multi-Bot Management

### ISSUE THREAD

**Issue by WatIsGithub** [NECROBOTIO/NecroBot#2662]
Would it be possible to make "simple"(yes, i dare to call it simple, but it isn´t at all, i know) to manage multiple program instances? For example creating main window with choice of folder where the bot is located, than autorun, check if it is running correctly (scan latest actions and in case of red lines/softban/no pokestops) and in case of error restart it?

I could try to program it myself, but it is quite long time ago since i had C at Uni and most likely i would break my brain over something more complicated than Hello world or spend days/weeks on it.

Thank you for your patience and understanding with over-demanding newbie

**Comment by nfettinger** [comment]
For now, it is much SIMPLER to have copies of the bot, and use a batch or cron job to manage them all.

**Comment by wowstin** [comment]
Yeah I'm just using a batch with a taskkiller and timer to reboot every hour incase it runs into issues while im afk

**Comment by WatIsGithub** [comment]
True, i was overcomplicating it. Thanks for the idea with batch, that is quite simple and possible to make it myself. Sorry for bothering
