### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by forReason** [NECROBOTIO/NecroBot#2663]
![Uploading Banned.jpg…]()

**Comment by nfettinger** [comment]
?

**Comment by wowstin** [comment]
Troll? Lol

**Comment by Huskynarr** [comment]
Which Level? Can you say other, how far you are going? :)

**Comment by poccix** [comment]
I think wrong font for this message, so i think its a fake :P

**Comment by forReason** [comment]
im lvl 36 but poccix dismantled it :D
