### ISSUE TITLE
WebSocketPort always uses 14252?

### ISSUE THREAD

**Issue by vascofg** [NECROBOTIO/NecroBot#2664]
![websocket_bot](https://cloud.githubusercontent.com/assets/634441/17381141/625d9894-59c2-11e6-8cd6-c652f28df2bc.png)

It seems this changed in a recent update (i think on 0.6.0). It's preventing external apps (like bot visualizer) from accessing bots running on this port, as multiple bots all try to bind to this same port (14252).

**Comment by nfettinger** [comment]
Using tip, I am able to configure the port correctly.
