### ISSUE TITLE
Wrong transfer

### ISSUE THREAD

**Issue by xtrsyz** [NECROBOTIO/NecroBot#2665]
![2016-08-04_3-23-01](https://cloud.githubusercontent.com/assets/4731553/17381119/91ef2686-59f4-11e6-8db7-8d06e748060b.jpg)
Pidgeoto transfer better iv
sometime this happen

**Comment by mush35** [comment]
try to increase your mincp and min ip also you can increase the duplicate amount 

those are worked for me

**Comment by xtrsyz** [comment]
if mincp or miniv increase, why that keep lower cp/iv and transfered better cp/iv

**Comment by somani6** [comment]
does this happen soloely to pokemons in the 'ToTransfer' list?

**Comment by Rick058** [comment]
Pretty sure it was this line, correct me if im wrong

` "PrioritizeIvOverCp": false,`

**Comment by xtrsyz** [comment]
Bulbasaur CP:595 IV:87.57 (transfered)
Bulbasaur CP:14 IV:65.33 (best)

Pidgeotto CP:788 IV:70.32 (transfered)
Pidgeotto CP:391 IV:66.84 (best)

something wrong with that?

**Comment by somani6** [comment]
how is your TransferWeakPokemon setting? Just to be sure in what part to search for an error :)

**Comment by xtrsyz** [comment]
"KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 2,
  "TransferWeakPokemon": false,

**Comment by somani6** [comment]
thx - i'm not entirely sure if i am right but i may have an idea why this is wrong - need to wait until ferox is fixed to be able to test properly ;)

**Comment by xtrsyz** [comment]
favorite pokemon cause this problem.
calculated as the best pokemon.

**Comment by JaEdmuva** [comment]
Hi, I'm having a really anoying issue, idk if it's a config related issue, look:

**(TRANSFERED) Grimer  - CP: 205  IV: 84.33%   [Best CP: 205  IV: 84.33%] (Candies: 115)
(TRANSFERED) Venonat - CP: 391  IV: 49.15%   [Best CP: 391  IV: 49.15%] (Candies: 158)
(TRANSFERED) Bulbasaur       - CP: 533  IV: 22.23%   [Best CP: 533  IV: 22.23%] (Candies: 195)
(TRANSFERED) Lickitung       - CP: 693  IV: 62.05%   [Best CP: 693  IV: 62.05%] (Candies: 46)
(TRANSFERED) Hitmonlee       - CP: 850  IV: 73.42%   [Best CP: 850  IV: 73.42%] (Candies: 27)
(TRANSFERED) Gengar  - CP: 145  IV: 61.20%   [Best CP: 145  IV: 61.20%] (Candies: 122)**

and this is my config section for transfering pkmn:

"KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 85.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 2,
"TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

any help would be appreciated guys.. thanks

**Comment by xtrsyz** [comment]
@JaEdmuva set "TransferWeakPokemon": true,

**Comment by xtrsyz** [comment]
@JaEdmuva "TransferWeakPokemon": false,

**Comment by schwartzadev** [comment]
solved
