### ISSUE TITLE
Bot just transferd my 1700 cp pinsir?!?!

### ISSUE THREAD

**Issue by abratar** [NECROBOTIO/NecroBot#2667]
So i have the setting KeepMinCp on 1300 but my pinsir with 1700+ just got transfered, it had 85% iv and now im sitting with this 600 cp pinsir 91% iv... i mean wtf is this setting useful for? fix this please -.-

**Comment by wowstin** [comment]
Was it a dup?

**Comment by carlanivans** [comment]
u must have prioritize iv over cp true

**Comment by wowstin** [comment]
91 iv is betteR than 85 will ever be so in the bots prospective it's better, you can set it to not prioritize iv over cp

**Comment by abratar** [comment]
yes ofc i said my other didn't get transferd... and yes i have the same setting for some days now but after updating to 6.4 it just transferd my pinsir which i had like 3 days ....

**Comment by carlanivans** [comment]
anyways bot isnt working for now so wait it out ill say

**Comment by thomasmoors** [comment]
the bot only works well if you inspect your settings every (fucking) time...

**Comment by nfettinger** [comment]
This issue tracker is not for configuration issues.

**Comment by abratar** [comment]
if you prioritize iv over cp then i saves those which have more iv, thats obvious but the setting KeepMinCp will keep all of my pokemon that are above this setting even if the iv is bad, well atleast in all older version.... but why the fuck did they change it?

**Comment by Mofon** [comment]
Make sure of the following in your config: KeepMinOperator is set to 'or', UseKeepMinLvl is set to 'false', TransferWeakPokemon is set to 'false', KeepMinDuplicatePokemon is set to '1' and UseKeepMinLvl is set to 'false'.

**Comment by Menton** [comment]
@abratar you should go through all the settings. If you did so, you would have seen the following passage:

"Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"

And as the wiki explains these kind of pokemon specific settings are > than global settings. This is why you lost your Pinsir. Now please calm down.
