### ISSUE TITLE
So nfettinger doesn't read the issue and just closed my thread...

### ISSUE THREAD

**Issue by abratar** [NECROBOTIO/NecroBot#2669]
Very very nice of you, my thread was about the fucking bot not the configuration... WTF... read first then close the thread! The bot had issues with the setting KeepMinCp and you just close it like everything is fine? sure kid...

**Comment by ifbatmanwasreal** [comment]
I can't wait for him to close this issue...

**Comment by Saik19922** [comment]
Salty. Also - Priorities/Setting conflicts for specified pokemon.

**Comment by nfettinger** [comment]
Several other people clearly pointed out your issue. I read through, verified it was a configuration issue, then closed it.

**Comment by Aneduna** [comment]
He read it and it seemed like a configuration issue.
It seems like a Configuration For me

**Comment by abratar** [comment]
im new to this github but if this is the wrong section where should i post it? atleast you could tell me that and not just close it... i just thought "issues" mean things like bot issues and such... well obvs not, only things like pokemon go server down shitty things are "issues" for you

**Comment by Aneduna** [comment]
Discord for Configuration issues

**Comment by Messepark** [comment]
issues with keepmincp ?

delete everything except config.json

download newest version - copy config.json - everything will be fine

**Comment by abratar** [comment]
nfetting i have the same settings for like a week and it never transferd before...

**Comment by Venzhel** [comment]
Well, nothings wrong with the bot. The problem is your config. Check again. Do you set PrioritizeIVoverCP true? Or check your config again, 1 by 1. Don't be angry like crazy, it's just pinsir tho lol

**Comment by abratar** [comment]
i wasnt angry, only after he closed it -.- im calm

**Comment by Messepark** [comment]
probably you disabled "autoupdate" ... ??? :)

**Comment by abratar** [comment]
what has that to do with the issue?

**Comment by nfettinger** [comment]
Based on your language, I would say you were not calm.

**Comment by Messepark** [comment]
as i said: issues with keepmincp ?

delete everything except config.json

download newest version - copy config.json - everything will be fine

had the same problem, because of disabeled autoupdate

**Comment by Venzhel** [comment]
And if you are new in this github, at least respect the rules in here.

**Comment by abratar** [comment]
Messepark thats what i said.. its only for the newest version... the older worked fine

**Comment by Messepark** [comment]
@abratar .... YES.

copy your config.json into the newest version. only config.json and auth.json

**Comment by Saik19922** [comment]
Bots are fresh, they are changing rapidly atm.

So its not a bot issue. Just do what @Messepark says

**Comment by abratar** [comment]
what are you talking about?

**Comment by dddbliss** [comment]
@abratar issue appears from several here that is configuration, please join discord and others can help you figure it out, this is not the forum for issues for these type of complaints. I am closing this issue due to the nature of this particular issue.

**Comment by abratar** [comment]
there is no "new version"...

**Comment by Messepark** [comment]
have a look ... at startup ... on the top... which version ?

**Comment by Messepark** [comment]
0.5.0 ?

**Comment by abratar** [comment]
as i said ... the NEWEST

**Comment by abratar** [comment]
0.6.4 omg..

**Comment by Venzhel** [comment]
Okay @abratar, how about this?
Post your "issue" on DISCORD, D-I-S-C-O-R-D. Can't find it at github? Google always on 24/7, use it and have fun with it :)

**Comment by Messepark** [comment]
@abratar : just wanted to help =) ... for me - everything works fine, since i deleted the whole bot... and do a fresh config

**Comment by abratar** [comment]
ok thanks, i will... thats what i asked at the beginning.. im new so i dont know where to post it... dont just throw shit at me, you could just say that i have it to post at discord. thats it

**Comment by nfettinger** [comment]
This thread is not beneficial. Please keep future chat civil and on point to the future development of the repository.
