### ISSUE TITLE
[suggestion] logic to prioritize iv as well as cp for least loss.

### ISSUE THREAD

**Issue by facinick** [NECROBOTIO/NecroBot#2671]
an option to catch pokemons with CP greater than existing pokemons of same kind and catch and transfer others directly.
also a logic to level up keeping CP and IV both in mind. usually high ivs have very low cp. already lost many high cv pokemons with 4 digit cp for high iv pokemons with 3 digit cp. knowing that IV can generate only a max of 10 percent difference in strength.

**Comment by piratefinn** [comment]
Are you possibly referring to the already existing config line PrioritizeIVOverCP? When set to false it should sort by CP instead of IV and thus delete the one with lower CP. If this config line is of course erroneous, then that is another matter.

**Comment by facinick** [comment]
but what if i want a good iv as well as cp? bot should be able to decide if chosing a lower cp for better iv is WORTH it? i got my 2350 cp pokemon exchanged by 750 cv pokemon. is this what we all want?

**Comment by elmaarmut** [comment]
Doesn't this already exist?

  "KeepMinOperator": "or",

Make this "and" instead of "or".

**Comment by facinick** [comment]
and if i have 2 pokmeons above specified minimums then?

**Comment by piratefinn** [comment]
If you have two, then surely the one I mentioned would come into play. At this point I'm thinking you are asking for a much more complicated approach for judging transferal, such as an algorithm based on both CP and IV to determine some sort of "strength" total value.
Feel free to do so if so, just pointing it out.
