### ISSUE TITLE
i have 18 arcanine. what is the bot not transferring them?

### ISSUE THREAD

**Issue by facinick** [NECROBOTIO/NecroBot#2672]
i did remove arcanine from pokemons NOT to transfer list. still im full of arcanine and snorlax and aerodactyl.

**Comment by ifbatmanwasreal** [comment]
Post config

**Comment by Aneduna** [comment]
This is a Config Issue not a bot issue. Get help on Discord not on github

**Comment by Venzhel** [comment]
Why tf people posting this kind of problem in here?

**Comment by elmaarmut** [comment]
Because you have Arcanine, Snorlax and Aerodactyl in your

"PokemonsTransferFilter": {
    }

Empty it. And perhaps learn to read :)

**Comment by nfettinger** [comment]
Please seek additional help in our Discord chat rooms.
