### ISSUE TITLE
no usable pokestops found everywhere¿?

### ISSUE THREAD

**Issue by charlyplay** [NECROBOTIO/NecroBot#2673]
I tried to use necrobot a few minutes ago , then it said that  no usable pokestops found were found in the place I was choosing , then I changed the coords to Barcelona , Spain and it says the same thing , I also changed the location to santa monica , USA ; the same text appears in loop saying my pkmns , items , pokedex info , and an attention text saying it .
I attach an screenshot showing it.
![21f74106387243ae10fef1d579fbe46e](https://cloud.githubusercontent.com/assets/20824689/17381756/d5ef713c-59cd-11e6-90fc-5cd041526659.png)

**Comment by nfettinger** [comment]
Duplicate

**Comment by projectoffset** [comment]
Bots are broken.

**Comment by charlyplay** [comment]
I am srry i didnt saw the duplicate :(((
