### ISSUE TITLE
no usable pokestops found

### ISSUE THREAD

**Issue by chriminix** [NECROBOTIO/NecroBot#2675]
hello i download the newest version but then if i logged in only this will write on my commandline -.-

!
![necro](https://cloud.githubusercontent.com/assets/20824827/17381794/0eb441e6-59ce-11e6-93fe-096672ac7a71.PNG)

**Comment by aquilaah** [comment]
same problem here

**Comment by blopez0909** [comment]
known issue, wait for fix.

**Comment by spiritpaze** [comment]
same

**Comment by AlexisjrFreitas** [comment]
same here

**Comment by Whosdaman** [comment]
https://github.com/PocketMobsters/PokeMobBot/commit/52e7c7b6ba398eb9c96fd007be168513f9bed44a

They found a fix ^

**Comment by elmaarmut** [comment]
For god's sake, check other posts before posting. There is one about this, and it is getting fixed.

**Comment by nfettinger** [comment]
Duplicate of #2654

**Comment by AMFOS22** [comment]
Just keeps repeating the same thing
