### ISSUE TITLE
Current Bug (No Pokestops) - BlueStacks App works fine

### ISSUE THREAD

**Issue by RentonXD** [NECROBOTIO/NecroBot#2680]
As the title says Pkmn Go on Bluestacks works fine and you see an can use pokestops there as normal. 

Maybe an API Issue?

**Comment by IstenesImre** [comment]
Yep

**Comment by piratefinn** [comment]
Definitely API, see the current commits to the project for the next update.

**Comment by Corgano** [comment]
Duplicate of #2645

**Comment by IstenesImre** [comment]
You are duplicated.

**Comment by RentonXD** [comment]
it's no duplicate because this info isn't given there... <.<

**Comment by nfettinger** [comment]
Duplicate of #2654
