### ISSUE TITLE
[SUG] Renaming Pkmn

### ISSUE THREAD

**Issue by head0r** [NECROBOTIO/NecroBot#2682]
Could you please fix that renaming tool?
It's pretty cool, but would be better if the Pokemon i renamed by myself were not re-renamed.
e.g. i named my Gyarados "Gyros", everytime i start the bot it's renamed to 92_Gyarados. 
Sucks.

Pls try to change it :) 
sth like... "OnlyRenameStandard": true / false,

ty

**Comment by somani6** [comment]
Favorite them, then they should be untouched

**Comment by nfettinger** [comment]
@head0r I am unable to reproduce this. Ones with custom names have never been renamed in my experience.

**Comment by head0r** [comment]
After starting every pkmn above iV90 ist renamed. Even the customs. Try it.
But favoriting them works, thank you. Should have tried that before *d'oh*

**Comment by somani6** [comment]
@head0r yes thats how it should work according to the code :)
@nfettinger you can try this by changeing the language. all mons will be translated
