### ISSUE TITLE
Attention No usable pokestops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by Toekan1** [NECROBOTIO/NecroBot#2683]
Hey guys,

I really hope you can help me. Since 1 hour, it says :'Attention No usable pokestops found in your area. Is your maximum distance too small? I cant solve this issue. I tried multiple latitudes and longitudes. If someone could help me out, i would really appreciate it!

Thanks in advance

**Comment by razzzzamatazz** [comment]
duplicate of #2645

**Comment by elmaarmut** [comment]
Learn to read.

Why would you post this when #2645 already exists?

**Comment by head0r** [comment]
[NicCage: "You don*t saaaaay"]

**Comment by nfettinger** [comment]
Duplicate of #2654

**Comment by 17yongga** [comment]
VPN would fix your problem.
