### ISSUE TITLE
No usable Pokestops

### ISSUE THREAD

**Issue by txisme** [NECROBOTIO/NecroBot#2687]
After last update (0.6.4) it started appear the message:

"(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?"

So now my BOT is just in a loop. Whats wrong? My maximum distance is the default one, i tried already to maximize it and still the same error, even in different initial positions.

**Comment by Sadfaffel** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2645

**Comment by Cuuup** [comment]
Duplicate of #2654

**Comment by artuan00** [comment]
#2645

**Comment by nfettinger** [comment]
Duplicate of #2645
