### ISSUE TITLE
[6.4] Possibility to setup more than 1 moveset to keep

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [NECROBOTIO/NecroBot#2692]
Hey guys, 
so I wanted to setup my bot for 6.4 release (disregarding of the momentary outage) and stumbled over a wonderful feature, new to this version. The "Moves" setting at "PokemonsTransferFilter". I just asked Mars if it's possible to put in more than one Moveset (like you can see in the examples below). He said, possibly not but I should submit an issue. My question now, is it possible or not and if not, could that be implemented, cause there is a different setup for attack and defense on alot of Pokemon.

"Snorlax": {
      "KeepMinCp": 100,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 92.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["ZenHeadbutt","HyperBeam"],
 ["TackleFast","Earthquake"],
      "KeepMinOperator": "and"
    }

or 

    "Snorlax": {
      "KeepMinCp": 100,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 92.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["Lick","HyperBeam"],
      "KeepMinOperator": "and"
    }
and
    "Snorlax": {
      "KeepMinCp": 100,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 92.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": ["ZenHeadbutt","HyperBeam"],
      "KeepMinOperator": "and"
    }

**Comment by Marsinator** [comment]
I do see the need to add this. One might wanna have two perfect pokemon of the same kind. one with the optimal moveset for attacking, one for defending.

**Comment by actislav** [comment]
added in PR #2694 but you must now use moveoperator to correct work with keeping values, also moves in array will check just any intersect, like u can add 10 moves, and it will triggered even if only 1 meet
