### ISSUE TITLE
DownloadSettings UPDATE!!! FIX for no pokestops.

### ISSUE THREAD

**Issue by BoBeR182** [NECROBOTIO/NecroBot#2700]
I got the request!!!

[->] Response for DownloadSettings { "hash": "54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5" }
https://gist.github.com/ruffnecktsk/c36e7ffd8d90ccf07abfab575f4cc511

decoded. Need responses too

i see get_player request changed, now app sending version 4 { 1: 2 2 { 1: "0.31.0" } }

I have caught the RPC requests, but I have no idea what to do next. Here is the raw request of /plfe/rpc : http://cdn.auroraen.com/2U2k0f412L24/1254_Request.txt

here is one of /plfe/380/rpc: http://cdn.auroraen.com/130s1L3V2l2h/1683_Request.txt

**Comment by ShallowHacker** [comment]
Yeah the no pokestops is annoying.lol
