### ISSUE TITLE
No usable pokestops found in your area

### ISSUE THREAD

**Issue by Trenars** [NECROBOTIO/NecroBot#2701]
Looks like since last update, all i'm getting is that there are no usable pokestops found in the area... I have double checked and tripple checked the coordinates, they are spot on between 4 pokestops with some 30 more in the area. distance is set to 2000 metres. haven't changed anything before bot stopped working. Also, if I log in with client, i can get all those poke stops and catch pokemons...

Any advice/help would be appreciated!

**Comment by wrrion15** [comment]
#2645
