### ISSUE TITLE
[Request]variable Altitude

### ISSUE THREAD

**Issue by Taranis01** [NECROBOTIO/NecroBot#2744]
Sooner or later the ban wave will come. The altitude could be one of many point niantic will use to flag bot users. thats why i would suggest to make the Altitude dynamic or, which would be much better, to use longitude/latitude to derive the corresponding altitude. 

I had a look how that may be possible:
- Using a DEM Database 
http://www.gpsvisualizer.com/elevation
- Google API (each user will need to set up an auth key)
https://developers.google.com/maps/documentation/elevation/intro
https://developers.google.com/maps/documentation/elevation/start

**Comment by Marsinator** [comment]
sounds good and reasonable cause is given

**Comment by ChemiHatake** [comment]
I'll be working on it,

**Comment by ChemiHatake** [comment]
Its done, I just need them to merge/close my pending pull request
