### ISSUE TITLE
Static Values in RequestBuilder

### ISSUE THREAD

**Issue by Panthere** [NECROBOTIO/NecroBot#2746]
Hiyo.
I've told a few people, time to make an issue now.
https://github.com/NECROBOTIO/NecroBot-Rocket-API/blob/3fc40bee9d8ec597c1875193c2615e6dc4bb5bce/PokemonGo.RocketAPI/Helpers/RequestBuilder.cs#L38

Way too obvious if 5 million requests use the same device ID.
I recommend editing ISettings.cs and adding appropriate ranges for the bot to transition through along with a setting for a custom 'profile' for the phone you use.

Something like:
bool transitionUp;
switch (rand)
{
case 0:
transitionUp = true;
}

if (transitionUp)
AccelXYZ/whatever += rand.next(min, max)
else
// subtract

**Comment by Marsinator** [comment]
was already considered by the devs, need to create a pool of potential phones we could use

**Comment by Taranis01** [comment]
Also connected with https://github.com/NECROBOTIO/NecroBot/issues/2752 / API using iOS auth

**Comment by NecronomiconCoding** [comment]
was fixed in v0.7.1
