### ISSUE TITLE
Language/information issues

### ISSUE THREAD

**Issue by Meowrouane** [NECROBOTIO/NecroBot#2747]
![image](https://cloud.githubusercontent.com/assets/20751663/17462420/5ed2d5b0-5ca4-11e6-89df-d250613c21a5.png)

*the expression is too long, cannot see the whole informations

*I choosed to keep language EN, yet it started in FR

**Comment by Oolaruu** [comment]
Why not something like : 
Lv: 28 (>>1h08min)
>> of course mean next level in ?

**Comment by Meowrouane** [comment]
the whole 00.00:09:20 thing, 
or maybe force the window to work on full screen instead of half screen, modified log window i mean

**Comment by Marsinator** [comment]
headbar not completely shown on smaller resolutions/screens.
needs improvement

**Comment by Oolaruu** [comment]
Well I think h:min are just right needed.
