### ISSUE TITLE
The current source does not compile.

### ISSUE THREAD

**Issue by Terminators24** [NECROBOTIO/NecroBot#2749]
Missing references:
using POGOProtos.*;
using PokemonGo.RocketAPI.*;
using PoGo.NecroBot.Logic.PoGoUtils;

The last release of Necrobot only works in the non-source one.

**Comment by theplaymate** [comment]
You have to build it using an x86 profile. Change build configuration to x86 instead of Any CPUYou have to build it using an x86 profile. Change build configuration to x86 instead of Any CPU

**Comment by Marsinator** [comment]
try loading release.zip for now

**Comment by theplaymate** [comment]
You have to build it using an x86 profile. Change build configuration to x86 instead of Any CPU.

**Comment by Terminators24** [comment]
Yes, I dowloaded the release.zip that contains the already compiled version.
But the source code needs to be filled with references.
@theplaymate it doesn't matter the x86 because it misses entire dir of references files.

**Comment by theplaymate** [comment]
@Terminators24  its matters now. Due to the need of encrypt.dll which is currently only in x86. Just change platform and hit rebuild it will automatically pull the required packages

**Comment by Terminators24** [comment]
@theplaymate See: 

using POGOProtos.;
using PokemonGo.RocketAPI.;
using PoGo.NecroBot.Logic.PoGoUtils;

They are not nuget packages, they are other projects linked to the main.
If they miss, It won't compile in whatever achitectures.

**Comment by theplaymate** [comment]
@Terminators24  doesn't seem to be an issue on my end. Just pulled the latest git and build success. VS Version incompatibility maybe?

**Comment by Terminators24** [comment]
@theplaymate  No, i just solved the problem in that way: git downloaded me 2 empty dir, so I had to fill manually them by downloading the related project and then, adding some fixes to references and else, finally I've been able to compile.

**Comment by truimagz** [comment]
empty api and proto folders can't compile either
