### ISSUE TITLE
DumpPokemonStats & TransferWeakPokemon

### ISSUE THREAD

**Issue by koubie** [NECROBOTIO/NecroBot#2750]
What are these features and what do they do?
I can't find them on wiki, can anyone help with an explanation please
thank you very much

**Comment by Marsinator** [comment]
dumppokemon=create log when starting bot, can be found in necro folder->dumps

transferweak=transfers all your weak pokemon (belowcp, belowiv)

**Comment by Taranis01** [comment]
@Marsinator about transferweak: that means it force transfer for all pokemon below KeepMinCP/IV value?

**Comment by koubie** [comment]
So, what if the Pokemon meet either IV but below CP or meet CP but below IV? will it be transferred too or no? @Marsinator
