### ISSUE TITLE
[v.0.7.0] DisplayHighestCP / DisplayHighestsPerfect is blank

### ISSUE THREAD

**Issue by arxnoa** [NECROBOTIO/NecroBot#2751]
It worked in v0.6.4 even when Bot was down, but now my logs just show this:

[22:29:07] ====== DisplayHighestsCP ======
[22:29:07] ====== DisplayHighestsPerfect ======

Pokemon dump to file still works fine.
Have tried with both old, and brand new config file.

**Comment by ChemiHatake** [comment]
Redownload the new version, (dont forget to save your auth/config somewhere)

**Comment by arxnoa** [comment]
This is with latest version v0.7.0

**Comment by semtex58** [comment]
is it possible to create an excel sheet or similar with all pokemons and the the values, CP, IV...?
