### ISSUE TITLE
[About API]

### ISSUE THREAD

**Issue by dgateles** [NECROBOTIO/NecroBot#2752]
> GMT +1, 1:30 - This API is not flag-proof. Any account using this API will easily be flagged as not playing through the official app. For now the devs have had enough of it and you can't blame them.
> 
> Altitude for example hasn't been fixed. Also all API requests will appear to Niantic to be coming from IOS users, this is wierd if it is matched with a device which normally runs Android. There is much to be done, but we have gotten a working API and with that our job is done, for now.

Remember that.

**Comment by Marsinator** [comment]
we are aware of that
