### ISSUE TITLE
bot wont connect

### ISSUE THREAD

**Issue by xxhamsterxx** [NECROBOTIO/NecroBot#2753]
my password is correct

**Comment by bobys16** [comment]
restart your computer and try to open bot again .

**Comment by pswalia2u** [comment]
Same here bot is not accepting google accounts.

**Comment by Marsinator** [comment]
make sure you use Quotes (" ") and put username in the username field and pass in the password field

**Comment by Marsinator** [comment]
@pswalia2u it does after a restart

**Comment by Fazy5** [comment]
Just right click Necrobot.exe and select "Run as Administrator" and you'll have no problem :)
