### ISSUE TITLE
[Bug] Potential Evolves / Waiting to evolve / Amount of Pokemon seen

### ISSUE THREAD

**Issue by Rawrlex** [NECROBOTIO/NecroBot#2754]
The bots spams, like in 0.6.4, the following things:
-Potential evolves
 >Maybe decrease the amount of this message

-Waiting to evolve
 >Maybe decrease the amount of this message

-Amount of Pokémon seen
 >Maybe move this into the progress bar or do a config where you can switch this off

**Comment by Fazy5** [comment]
Its fine the way it is i think. Nobody keeps looking at the bot window
