### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sddds** [NECROBOTIO/NecroBot#2756]
Possibly due to this

C:\Users\1\Desktop\NecroBot-0.7.0\POGOProtos\POGOProtos\POGOProtos.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\1\Desktop\NecroBot-0.7.0\POGOProtos\POGOProtos\POGOProtos.csproj'.

**Comment by theplaymate** [comment]
Pull the latest version again and try. Works fine for me.

**Comment by Marsinator** [comment]
please redownload source from git if you must compile.

if you dont, use the release.zip

**Comment by rNadom** [comment]
Says you are missing the PogoProtos project.
Try re-init your submodules conf ('git submodule init') then update pull the latest submodules ('git submodule update --force')?

**Comment by yupdon** [comment]
@rNadom It initialized for me but pulled no 'new' files.

**Comment by truimagz** [comment]
same here, missing api and proto files

**Comment by yupdon** [comment]
@Marsinator I'd like to compile of not to simply keep top 3 duplicates....and I can't change the code with the info provided by this thread so far
