### ISSUE TITLE
login to another account

### ISSUE THREAD

**Issue by Venin87** [NECROBOTIO/NecroBot#2757]
Hello,
this has nothing to do with this version of necro, i had the same problem in the previous as well, after i introduce the google pass and user, it logs me to some lvl 1 account. i triple checked it, on the phone it works..but as soon as i try to user the same credentials in auth.json it fails. no error, no nothing..it even catches pokemon on the low lvl account. I know i'm beeing noobish but please help if u can.
Thanks,

**Comment by Beatz89** [comment]
are you sure you have set the correct login type in the auth.json file?
you can set ptc/google
 "AuthType": "google",

**Comment by Venin87** [comment]
yes. it is corect. it works on the ptc account. on google it doesnt login to the right account. For exemple it doesnt login to my lvl 30 account. in logins to a lvl 1 account .

**Comment by Venin87** [comment]
please close this thread. i finally got it somehow working.
