### ISSUE TITLE
No usable pokestop in your area ERROR

### ISSUE THREAD

**Issue by piyus191** [NECROBOTIO/NecroBot#2758]
It is giving an error "No usable pokestop in your area.If your maximum distance too small" ?
I have also tried to change max distance and also the latitude & longitude but still not working.Please help.

![image](https://cloud.githubusercontent.com/assets/20887381/17462522/b405e210-5ccd-11e6-865f-0f04da66b767.png)

**Comment by Marsinator** [comment]
please update to 0.7.0

**Comment by 182blnk** [comment]
its 0.7.0 still No usable pokestop in your area.If your maximum distance too small.

**Comment by poutros** [comment]
@182blnk No, it isn't.

**Comment by bulubebek** [comment]
try to change your location. :)

**Comment by lordoflies** [comment]
Ver 0.7.0 and I have exactly the same problem. The bot does nothing but gives the error given above

**Comment by Sparco2313** [comment]
Same problem on v0.7.0, redownloaded and still not working

**Comment by 182blnk** [comment]
no it isnt thats +44 lol...on the source code folder pogoProtos is empty

**Comment by lordoflies** [comment]
I changed the altitude to 10.0 (default) and it worked

**Comment by AuroraFire** [comment]
Delete the previous file and folder and redownload the bot. It's working for me.

**Comment by newvalak** [comment]
Which is latest version and still working at this time i must download? Please give the link
