### ISSUE TITLE
【bug】Translation language file

### ISSUE THREAD

**Issue by MythHack** [NECROBOTIO/NecroBot#2760]
Translation language file naming rules and automatically get the system language can not be repaired bug
![image](https://cloud.githubusercontent.com/assets/7798759/17462534/180a7d7e-5ce3-11e6-97a3-09532d4e761e.png)
![image](https://cloud.githubusercontent.com/assets/7798759/17462535/1bf18810-5ce3-11e6-89e9-e97d4e11030a.png)
?????

**Comment by MythHack** [comment]
I do not know how to fix this problem haaaaaaaa

**Comment by ViBE-HU** [comment]
i guess this cause the following:
[17:00:56] () [ERROR] Issue loading translations
[17:00:56] () [ERROR] Fatal Error
[ERROR] No replacement translations: Check appropriate files for typos
Ending Application...2

**Comment by MythHack** [comment]
Yes, but because the standard question, I have not thought of a way to repair
