### ISSUE TITLE
Organization/University google account log in issue

### ISSUE THREAD

**Issue by erichuxuchen** [NECROBOTIO/NecroBot#2764]
I have an issue with the my account login. I understand completely how to get everything setup.

The issue is, my Gmail account is through a'University'. So essentially it is: example@school.ca
When I go to Gmail, I put in my school whole email address, it directs me to the organization to log in, then it redirects back to Gmail.
The latest bot as of (v 0.7.0, says that I have 2 step auth enabled because of it. I do not have it enabled. However, I did turn it on to try it, but it doesn't work that way either. The only thing I can think of is the bot thinks it's a two step since it the log in is required through the organization.
Could anyone help me?
I really appreciate it.

**Comment by Kemosabe9** [comment]
I have this exact same problem! its driving me crazy lol.

**Comment by Taranis01** [comment]
After you enable 2factor auth did you try to set up an app password and use it instead of your google password? edit: just seen in the other thread that app password didnt worked too
If that doesnt work i'd suggest to create a real google or ptc account ;)

**Comment by BlauDev** [comment]
It's a problem with Google Edu accounts or with custom domains.  See  #2224

**Comment by erichuxuchen** [comment]
I have tried to enable 2factors auth and used an app password, but its still not working.
