### ISSUE TITLE
[Enhancement] Different colors for console logging of PKMN Escape & Flee events

### ISSUE THREAD

**Issue by daouid** [NECROBOTIO/NecroBot#2766]
A little visual improvement would be to show pokemon escape and flee events in a different color than CatchSuccess events.

**Comment by daouid** [comment]
I guess it was added by some very recent commit.

New suggestion change red to yellow.

**Comment by MyUncleSam** [comment]
yes it was, but red is the error color for me. could you switch it to another color please? e.g. orange
