### ISSUE TITLE
AND vs. OR in setting

### ISSUE THREAD

**Issue by koubie** [NECROBOTIO/NecroBot#2767]
So, I just want to make sure I get this right to not transfer the pokemons I want to keep
Or = The pokemon just needs to meet either IV or CP, it will be kept?
And = The pokemon has to meet BOTH IV and CP to be kept?
Please correct me if Im wrong
thank you

**Comment by Taranis01** [comment]
you are right!
and please ask such questions in the discord support/settings channel next time

**Comment by koubie** [comment]
where the support/setting at? @Taranis01

**Comment by Taranis01** [comment]
@koubie  in the discord channel are subchannels called "support" and "settings" https://discord.gg/VXKxNFr

**Comment by koubie** [comment]
Oh yeah I clicked on that and it said invalid or expired @Taranis01 not sure why

**Comment by Taranis01** [comment]
reason could be that the channels reaches its cap
if the reason is that the link expired try https://discord.gg/f4WwD
