### ISSUE TITLE
Modify EnableHumanizedThrows?

### ISSUE THREAD

**Issue by nd3r** [NECROBOTIO/NecroBot#2768]
Hi,

I am trying to make the bot miss more throws and I enabled "EnableHumanizedThrows" but it still looks like it succeeds a lot. 

According to PokéAdvisor my catch success rate is 93% and I want to decrease that value to look more "human" but can't understand which parameters to change in the config file.

Is it possible to modify this in some way?

**Comment by koubie** [comment]
You need to adjust these number lower I guess
"NiceThrowChance": ,
  "GreatThrowChance": ,
  "ExcellentThrowChance": ,
  "CurveThrowChance": ,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,

**Comment by Taranis01** [comment]
This are the lines that effect the success chance
please use the discord settings channel next time

 //---Pokeball Throw---//
  "EnableHumanizedThrows": true,	
  "NiceThrowChance": 40,
  "GreatThrowChance": 50,
  "ExcellentThrowChance": 30,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverCp": 1000,	
  "ForceExcellentThrowOverCp": 1500,	
  "ForceGreatThrowOverIv": 90.0,	
  "ForceExcellentThrowOverIv": 95.0,	
  //---Pokeball Usage---//
  "MaxPokeballsPerPokemon": 6,	
  "UseGreatBallAboveCp": 2000,	
  "UseUltraBallAboveCp": 2250,			
  "UseMasterBallAboveCp": 2500,					
  "UseGreatBallAboveIv": 999.0,	
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,

**Comment by tygole** [comment]
Thanks for info!

**Comment by tygole** [comment]
I tried the settings now, currently running
