### ISSUE TITLE
Can't evolve pokemon

### ISSUE THREAD

**Issue by raccoon19** [NECROBOTIO/NecroBot#2770]
Evolving always fails:

(Evolving) Pidgey for 500 xp
(Evolving) Pidgey failed. Result: FailedPokemonMissing, stop evolving Pidgey.

I don't know why. Maybe he is transfering pokemon before evolving them.

**Comment by Beatz89** [comment]
In the config file have you got the "KeepPokemonsThatCanEvolve": true,
