### ISSUE TITLE
Possibly not a problem ?

### ISSUE THREAD

**Issue by PokeBotUK** [NECROBOTIO/NecroBot#2771]
When running with CatchPokemon = false

![image](https://cloud.githubusercontent.com/assets/20753079/17462686/18fa4628-5cad-11e6-8fbe-dd09f36997aa.png)

Does this mean you are ignoring pokemon (as intended) or is something wrong ?

**Comment by LachieKimber** [comment]
+1 

I'm having the same error/attention message. And yes, I do have my settings so no Pokemon is caught. Just wondering if this is an issue or anything.

**Comment by NecronomiconCoding** [comment]
Thank you, fixing it :smile:

**Comment by NecronomiconCoding** [comment]
https://github.com/NECROBOTIO/NecroBot/commit/3f53082ac683b6ec2d9d5d4206caec3f1f4cd6f9
