### ISSUE TITLE
System.ArgumentOutOfRangeException: Argument must be in range of -180 to 180

### ISSUE THREAD

**Issue by SKOx0** [NECROBOTIO/NecroBot#2774]
GeoCoordinatePortable.GeoCoordinate.set_Longitude(Double value) na C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:linha 129
   em PoGo.NecroBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) na C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:linha 16
   em PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() na C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:linha 30
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() na C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:linha 66
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() na C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:linha 36

**Comment by NecronomiconCoding** [comment]
You are using a Location that is out of bounds.
