### ISSUE TITLE
Don't use high level balls with low CP pokemon

### ISSUE THREAD

**Issue by roytam1** [NECROBOTIO/NecroBot#2787]
```
[22:21:37] (PKMN) (CatchSuccess) | (Normal) Pidgey Lvl: 2 CP: (24/30) IV: 31.00% | Chance: 100% | 60.70m dist | with a UltraBall (142 left). | Candies: 1088 | lat: 2
2.4527058753438 long: 114.164232502271
```

It seems to be a waste of using high level balls on low CP/Lv pokemon.

**Comment by JustRegisteredToSayThis** [comment]
This is supposed to be determined by the following variables:
`"UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
`
If you have no other balls of course it will also revert to the ones available.

**Comment by valdez70** [comment]
its happened when recycle pokeball before catch a pokemon and u have 0 pokeball.

**Comment by roytam1** [comment]
> This is supposed to be determined by the following variables

I have these settings in unchanged(default) values

> its happened when recycle pokeball before catch a pokemon and u have 0 pokeball.

but I have Great balls and PokeBalls, and it still uses Ultra Ball for catching weak pokemons.

**Comment by roytam1** [comment]
> This is supposed to be determined by the following variables

I have these settings in unchanged(default) values

> its happened when recycle pokeball before catch a pokemon and u have 0 pokeball.

but I have Great balls and PokeBalls, and it still uses Ultra Ball for catching weak pokemons.

**Comment by roytam1** [comment]
> This is supposed to be determined by the following variables

I have these settings in unchanged(default) values

> its happened when recycle pokeball before catch a pokemon and u have 0 pokeball.

but I have Great balls and PokeBalls, and it still uses Ultra Ball for catching weak pokemons.

**Comment by roytam1** [comment]
> This is supposed to be determined by the following variables

I have these settings in unchanged(default) values

> its happened when recycle pokeball before catch a pokemon and u have 0 pokeball.

but I have Great balls and PokeBalls, and it still uses Ultra Ball for catching weak pokemons.

**Comment by valdez70** [comment]
(INFO) Current Pokeballs: 9 | Greatballs: 125 | Ultraballs: 0 | Masterballs: 0

(RECYCLING) 9x ItemPokeBall

(PKMN) (CatchSuccess) | (Normal) Rattata Lvl: 17 CP: (232/282) IV: 39.00% | Chance: 36.31% | 65.77m dist | with a GreatBall (119 left). |

**Comment by valdez70** [comment]
> 
but I have Great balls and PokeBalls, and it still uses Ultra Ball for catching weak pokemons.

so idk

**Comment by roytam1** [comment]
OK I found my config.json is weird (just unchanged since 0.5.0):
```
  "UseGreatBallAboveIv": 0.0,
  "UseUltraBallAboveIv": 0.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
```

fixing them making it works normally again.
