### ISSUE TITLE
Mobile device Specifications inside config.json

### ISSUE THREAD

**Issue by xEzitx** [NECROBOTIO/NecroBot#2788]
Please could you explain the reason behind the Device Specs inside the config.json as I feel that if they're all the same it's going to be easier to ban people as they will all have the same device.

**Comment by bulubebek** [comment]
#2781

**Comment by JustRegisteredToSayThis** [comment]
It's on the wiki:

> DeviceID (Value)

Android: Settings -> About Phone -> Info.

iOS: Settings -> General -> About.

If you're going to be using this on devices, outside of just botting, it is wise to have your IDs match.

**Comment by xEzitx** [comment]
Cheers,
