### ISSUE TITLE
prioritizeivovercp=false doesnt work

### ISSUE THREAD

**Issue by tojejo** [NECROBOTIO/NecroBot#2789]
it is still transferring pokemon with higher CP and lower IV, and leaving ones with lower CP with higher IV,
despite i have set:
prioritizeivovercp=false
transferweakpokemon=false

**Comment by Squamoto** [comment]
Same for me. Lost so many of my friends :(

**Comment by calvinke8** [comment]
check transfer filter settings

**Comment by tojejo** [comment]
transfer filter works well, this applies to pokemons not included in filter.
yeah i can add them manually to the filter but i dont want to add every signle regular pokemon to the filter while them should be filtered well with keepmincp=x parameter

**Comment by adelintru** [comment]
Can confirm this as well. I also tried setting prioritizeivovercp=true, to see what happens, but it keeps transferring Pokemons without a clear reason. I guess I will wait until this gets fixed. Many thanks to the developers anyway! You guys doing a great job!

**Comment by calvinke8** [comment]
Try taking everything out of the filter section and see if it fixes it. Seems like the filter overwrites the general rules. So if you have keepminIV 80 and its 90 for a pkmn in the filter, it will transfer it

On Aug 7, 2016, at 11:27 AM, tojejo <notifications@github.com<mailto:notifications@github.com>> wrote:


transfer filter works well, this applies to pokemons not included in filter.
yeah i can add them manually to the filter but i dont want to add every signle regular pokemon to the filter while them should be filtered well with keepmincp=x parameter

-
