### ISSUE TITLE
how to get sniping working with https://pokezz.com

### ISSUE THREAD

**Issue by delrio1110** [NECROBOTIO/NecroBot#2790]
here is my config
"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,

**Comment by ShrekIII** [comment]
I guess the main problem is that https://pokezz.com is down...

**Comment by GreatApo** [comment]
pokezz.com is not down now (atleast for me).
Change the "SnipeAtPokestops" to true, worked for me!
