### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by lotsobearfreshtea** [NECROBOTIO/NecroBot#2792]
says build error when ctrl - f5ing?

any issues?

**Comment by fabriciodsr** [comment]
@lotsobearfreshtea Everything is working fine, mate.

Just download the last release [here](https://github.com/NECROBOTIO/NecroBot/releases)

If u want to compile the code, make sure u cloned the repository correctly using [GIT.](https://github.com/NECROBOTIO/NecroBot/wiki/Source-Code)

If yes, just:
1. Open the solution called "NecroBot for Pokemon Go.sln".
2. Right click on "PoGo.NecroBot.CLI" and click on "Set as Startup Project".
3. Press CTRL + F5 or just Right click at solution and "Build"
