### ISSUE TITLE
[Suggestion] - Auto-Update Check WITHOUT Restarting BOT

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2793]
So I came up with the idea that instead of RESTARTING the BOT and it will check for updates every lunch of the BOT it will check for updates every minute or an hour or whatever.
I mean.. If you go to sleep and you get an update and you want it as soon as possible you will need to RESTART the BOT, but with my suggestion it will auto-update by itself so you won't even feel that the BOT RESTARTED.

**Comment by kolet** [comment]
good idea

**Comment by s10035147** [comment]
Kinda impossible if there are updates to the config file itself. Reason being that when the bot is running, changes to the config file will still need the bot to be restarted for it to have any effect unless there is a system to shut the bot down, update, and then restart the bot automatically.

Is it really feasible? (Do we still need our legs to walk at all?)

**Comment by ObsessedHacker** [comment]
@s10035147 Dude, The idea here is that for example: the updates only get when we restart the bot, so instead of this, we just wait for X time and then it will check for updates, if it found any it will restart the bot.
that's it.
