### ISSUE TITLE
any help be great new to necrobot

### ISSUE THREAD

**Issue by craigyjr** [NECROBOTIO/NecroBot#2798]
hey guys im new to necrobot ive signed in and used coordinates for new york but all i get is this 
![image](https://cloud.githubusercontent.com/assets/20816456/17463110/417a459e-5cb7-11e6-9fba-b51f9d00b118.png) i dunno how to change settings

**Comment by s10035147** [comment]
restart the bot. there was an update that requires you to restart it carefully. or else just redownload it

**Comment by craigyjr** [comment]
ive just downloaded it for the first time approx 20 minutes ago  and restarted bot a number of times
