### ISSUE TITLE
Device Info example?

### ISSUE THREAD

**Issue by ReadyHub** [NECROBOTIO/NecroBot#2801]
Could anyone tell us where we can find this info in our android device to replace it with the info in config?

DeviceId, AndroidBoardName, AndroidBootloader, DeviceBrand, DeviceModel, DeviceModelIdentifier, DeviceModelBoot, HardwareManufacturer, HardwareModel, FirmwareBrand, FirmwareTags, FirmwareType, FirmwareFingerprint

**Comment by ClashofJeann** [comment]
+1
wiki page maybe?

**Comment by fabriciodsr** [comment]
@ReadyHub Hello, mate.

You can download or find any build.prop from android devices on internet and change like bellow:

Tip: Keep the bold letters at DeviceId
Tip²: Replace the Xs for any number at DeviceId

That's a build.prop info from Samsung Galaxy S5

"DeviceId": "XXXe1aaXXXXfXXbX",
"AndroidBoardName": "MSM8974",
"AndroidBootloader": "unknown",
"DeviceBrand": "samsung",
"DeviceModel": "SM-G928F",
"DeviceModelIdentifier": "SM-G928F",
"DeviceModelBoot": "qcom",
"HardwareManufacturer": "samsung",
"HardwareModel": "SM-G928F",
"FirmwareBrand": "samsung",
"FirmwareTags": "release-keys",
"FirmwareType": "user",
"FirmwareFingerprint": "samsung/zenltexx/zenlte:5.1.1/LMY47X/G928FXXS2AOK9:user/release-keys",

**Comment by ReadyHub** [comment]
@fabriciodsr Thanks for that, but DeviceId not in build.prop. also what about AndroidBootloader?

And are you sure about all inputs?

**Comment by kurokuns** [comment]
What happen if I do not change it ?

**Comment by ClashofJeann** [comment]
You risk ban... (more risk than with the id)

**Comment by fabriciodsr** [comment]
@ReadyHub Put any numbers at the **X**s for DeviceId, just keep the letters.
AndroidBootloader is a number for each android phone just like DeviceId, but i dont have any example to show and they dont need this kind of info just you. (To unlock unlock ur bootloader and change thing on ur phone).

"DeviceId": "**XXX**e**X**aa**XXXX**f**XX**bX"

> And are you sure about all inputs?

About the **Samsung Galaxy S5**, yes.

**Comment by mrnitrate** [comment]
build.prop from Samsung Galaxy S6

"DeviceId": "**XXX**e1aa**XXXX**f**XX**b**X**",
  "AndroidBoardName": "universal7420",
  "AndroidBootloader": "unknown",
  "DeviceBrand": "samsung",
  "DeviceModel": "SM-G925T",
  "DeviceModelIdentifier": "SM-G925T",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "SM-G925T",
  "FirmwareBrand": "samsung",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/zeroltetmo/zeroltetmo:5.0.2/LRX22G/G925TUVU1AOCG:user/release-keys"

**Comment by ReadyHub** [comment]
@fabriciodsr I cannot find my deviceId, where i can get it?

**Comment by ClashofJeann** [comment]
there are many apps on play store:
search "device id" install app you will find easily.

**Comment by kurokuns** [comment]
hmm.. build.prop info from Asus Zenfone 2 please..

**Comment by ReadyHub** [comment]
@ClashofJeann I got my device id, should I put it like from "device id app" or change with X as @fabriciodsr said?

**Comment by Taranis01** [comment]
search for this in Android Build.Prop:

```
"DeviceId": -> Device ID App -> randomize it
"AndroidBoardName": "MSM8974",
"AndroidBootloader": "unknown",
"DeviceBrand": "samsung", --> ro.product.brand
"DeviceModel": --> ro.product.device
"DeviceModelIdentifier": --> ro.product.device / ro.product.name
"DeviceModelBoot": "qcom",
"HardwareManufacturer": --> ro.product.manufacturer
"HardwareModel": --> ro.product.modell
"FirmwareBrand": --> ro.product.brand
"FirmwareTags": --> ro.build.tags
"FirmwareType": --> ro.build.type
"FirmwareFingerprint": --> ro.build.fingerprint
```

Another Galaxy S6.
```
  "DeviceId": "XXXXXXDXEDXDXXFC"
  "AndroidBoardName": "universal7420",		
  "AndroidBootloader": "unknown",		
  "DeviceBrand": "samsung",		
  "DeviceModel": "zeroflte",		
  "DeviceModelIdentifier": "zerofltexx",		
  "DeviceModelBoot": "qcom",		
  "HardwareManufacturer": "samsung",
  "HardwareModel": "SM-G920F",		
  "FirmwareBrand": "samsung",		
  "FirmwareTags": "release-keys",		
  "FirmwareType": "user",		
  "FirmwareFingerprint": "samsung/zeroltexx/zerolte:6.0.1/MMB29K/G925FXXU3DPDP:user/release-keys",
```

@mrnitrate i think devicemoddel and devicemodellidentifier should be different, but who cares ;)

**Comment by CyberBaby** [comment]
Can we have a sample for iOS, many thanks~
Thanks for your great work!!!

**Comment by fabriciodsr** [comment]
> @ClashofJeann I got my device id, should I put it like from "device id app" or change with X as @fabriciodsr said?

@ReadyHub 

I'll not put my DeviceId on BOT Information, because if they ban my fake account they'll have my original DeviceId and probaly ban all accounts associated to this.

Ofc I guess they'll do it, but its for security.

So I recommend you to use a fake DeviceId too.

**Comment by gokudr** [comment]
hey   fabriciodsr@   where in the bot can i find this  file

**Comment by fabriciodsr** [comment]
@gokudr 

> hey fabriciodsr@ where in the bot can i find this file

If u're running the last [release](https://github.com/NECROBOTIO/NecroBot/releases), just go to Config > config.json and open with Notepad++ or simply Notepad to find it.

**Comment by gokudr** [comment]
@fabriciodsr 

got it thx you

**Comment by MrWalk** [comment]
For Device ID you guys are saying to literally put random numbers? And the rest follow the build.prop for?

**Comment by fabriciodsr** [comment]
@MrWalk Just to match as a real phone, mate.

**Comment by MrWalk** [comment]
@fabriciodsr  So not random out of no where, but use an app that randomize and still matches a phone theoretically? Sorry, terrible at all this. Appreciate the help.

**Comment by SEVEN986** [comment]
I can't find "FirmwareFingerprint": --> ro.build.fingerprint in my prop.build
help pls

**Comment by fabriciodsr** [comment]
@MrWalk 

> @fabriciodsr So not random out of no where, but use an app that randomize and still matches a phone theoretically? Sorry, terrible at all this. Appreciate the help.

If you get **2 same model android phones**:

- They'll have the **same build.prop**, except possibly the build date/hour.
- Both DeviceId and AndroidBootloader **are different**.
- All other options **are the same**.

**Comment by fabriciodsr** [comment]
@SEVEN986

> I can't find "FirmwareFingerprint": --> ro.build.fingerprint in my prop.build
help pls

You can use the **ro.build.version.base** instead of **ro.build.fingerprint**

**Comment by SEVEN986** [comment]
@fabriciodsr I have version.base_os and it's blank. should I leave that blank?

**Comment by fabriciodsr** [comment]
@SEVEN986 

> @fabriciodsr I have version.base_os and it's blank. should I leave that blank?

I would fill the bot with other informations instead of my own phone, because this:

> I'll not put my DeviceId on BOT Information, because if they ban my fake account they'll have my original DeviceId and probaly ban all accounts associated to this.

>Ofc I guess they'll do it, but its for security.

>So I recommend you to use a fake DeviceId too.

But u can leave that blank if u have the **Model** filled, just to "match a real phone"

**Comment by Triky313** [comment]
But not for iPhone..!? ;x

**Comment by Avadom** [comment]
need for Sansung galaxy S4
