### ISSUE TITLE
Possible Soft Ban

### ISSUE THREAD

**Issue by dizzyddevil** [NECROBOTIO/NecroBot#2802]
I am going around to stops in my area. Everything is working fine, then it says possible soft ban and starts showing 1/45,2/4,3/45,etc. I close necrobot and open again and it works fine. Has done this about 3 times but now is working fine.

**Comment by rherartt** [comment]
you dont have to close the bot, just wait

**Comment by rousseauxy** [comment]
Mostly happens when you pass a pokestop you already looted

**Comment by Rick058** [comment]
The softban unban messages just loop for me, when I switch over to VPN it instantly continues botting. Looks more like my IP got flagged?
