### ISSUE TITLE
[ERROR] No replacement translations

### ISSUE THREAD

**Issue by Kinsiinoo** [NECROBOTIO/NecroBot#2805]
![trans](https://cloud.githubusercontent.com/assets/20649992/17463201/484e5be4-5cc1-11e6-9d8f-348cb53b0941.PNG)

**Comment by Lord255** [comment]
hello,
finally someone who has the same problem like me.
i have downloaded the release.zip and first run do the same for me too.
 affected: 0.7.0 and 0.7.1

**Comment by koenboots** [comment]
I just cleanly installed the new release (0.7.1) and used to setup at first launch. It asked me if the default language needs to be changed. Although my native language is Dutch, I prefer using all software in English (as is my operating system). So I chose not to change de default language (being English I'd figure), but it has set to Dutch anyway.

Currently my config file reads `"TranslationLanguageCode": "nl",`. Should I replace it with `""`, or remove the line entirely?

**Comment by Fulkol** [comment]
Had the same problem, right click and solve compatibility problems made it work, went thru the console set up and it is running currently, but I have no configuration file in any of the folders of the bot (to be clear, no config.json on my computer) 
Ideas? :D

**Comment by ViBE-HU** [comment]
same here

**Comment by koenboots** [comment]
> Currently my config file reads "TranslationLanguageCode": "nl",. Should I replace it with "", or remove the line entirely?
Remove the language code seems to have done the trick. So, to keep it in English, the line should read `"TranslationLanguageCode": "",`

**Comment by Lord255** [comment]
i dont have a config because its not creating it. so how or where to change:
"TranslationLanguageCode": "", <?

**Comment by deathart** [comment]
same here

**Comment by inegyzet** [comment]
I copied config.json from version 0.6.4. I run necrobot.exe. It threw an error, but it made an auth.json file in the Config directory. I wrote my ptc user name and password in it (and changed "AuthType": "google" to "AuthType": "ptc") and now it works 
![kepkivagas](https://cloud.githubusercontent.com/assets/20889572/17463727/c3c1562c-5ccc-11e6-9712-aea350fcb813.JPG)

**Comment by somani6** [comment]
Pull request #2755 removed the string EventPokemonCapture and replaced it with two new ones.

As long as 'EventPokemonCapture' exists in the langauge dependend json files it will crash.

**Comment by wxyz80** [comment]
I'm simply cut out the whole translations folder from the config folder, that solved the problem.

**Comment by somani6** [comment]
@wxyz80 yes that works if you don't need any translations :). the code checks if a translation file exists, if not it will skip any further lines - so no error.

**Comment by somani6** [comment]
Added a quick fix to my PullRequest #2817

**Comment by inegyzet** [comment]
I tried to delete the trnslation folder, but after this I could not log in.
