### ISSUE TITLE
Lured pokemons are skipped

### ISSUE THREAD

**Issue by daika7ana** [NECROBOTIO/NecroBot#2807]
I left my bot in a highly populated area, with multiple lures around. However my bot is totally ignoring (Lured)-type pokemons and only goes for (Normal).
 I am fairly sure it is not a config problem. Been using this config for a while now and this just started happening. 
3-5 lures in the area constantly, but every few minutes it barely grabs one of them.

**Comment by PokemasterMike** [comment]
same for me, disabled lures for now
