### ISSUE TITLE
new to necrobot, getting errors.

### ISSUE THREAD

**Issue by glitterjesus** [NECROBOTIO/NecroBot#2809]
![boogity](https://cloud.githubusercontent.com/assets/20889055/17463295/a2228d56-5c90-11e6-869d-f1459605fa0e.png)
it just keeps repeating like this

**Comment by colinodell** [comment]
Check the `DefaultLatitude` setting in your `config.json`.  It should be a number between -90 and 90.

**Comment by somani6** [comment]
you entered an invalid latitude. I think you mixed up longitude and latitude

**Comment by Fulkol** [comment]
Your coordinates are crap
only numbers are allowed
