### ISSUE TITLE
Snipe on necro bot

### ISSUE THREAD

**Issue by Flariann** [NECROBOTIO/NecroBot#2810]
How do you use snipe on necro bot ? Is it active with the starting config ?

**Comment by somani6** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Sniping-Setup

**Comment by Rick058** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

It works great for me, be sure to update everything to the latest version.

**Comment by Flariann** [comment]
Oh, get it now. Thanks !
