### ISSUE TITLE
C:\Users\User\Desktop\Pokémon\DevBot\POGOProtos\POGOProtos\POGOProtos.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Sebastian\Desktop\Pokémon\DevBot\POGOProtos\POGOProtos\POGOProtos.csproj'.  C:\Users\NAME\Desktop\Pokémon\Bot\POGOProtos\POGOProtos\POGOProtos.csproj

### ISSUE THREAD

**Issue by Devoti** [NECROBOTIO/NecroBot#2813]
C:\Users\NAME\Desktop\Pokémon\BOT\POGOProtos\POGOProtos\POGOProtos.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\NAME\Desktop\Pokémon\BOT\POGOProtos\POGOProtos\POGOProtos.csproj'.  C:\Users\NAME\Desktop\Pokémon\BOT\POGOProtos\POGOProtos\POGOProtos.csproj

So I'm getting this error.. What can it be?

**Comment by colinodell** [comment]
Are you using the source code?  If so, make sure you've cloned the git submodules as well.

**Comment by Devoti** [comment]
I do use the source!
How do I do that? I'm not used to github..

**Comment by Devoti** [comment]
Never mind... I was just being stupid there!

**Comment by somani6** [comment]
https://help.github.com/articles/fork-a-repo/

**Comment by Devoti** [comment]
Getting this instead now:
https://gyazo.com/aa77357badb78b96c016244fc09dff00

**Comment by colinodell** [comment]
It looks like you'll need the `Google.Protobuf` library/DLL/whatever they call it in .NET world:  https://github.com/NECROBOTIO/NecroBot/blob/f6a86900ef8670b10bb445afe27c907e584e5202/PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj#L76

**Comment by Devoti** [comment]
Fixed it aswell :p Thanks!

**Comment by colinodell** [comment]
Awesome!

If everything is working, feel free to close this issue :)

**Comment by aapikz** [comment]
i have the same error how did u fix it?
