### ISSUE TITLE
Device information for NOX

### ISSUE THREAD

**Issue by TheMaskedMonkey** [NECROBOTIO/NecroBot#2819]
I would this ask this on the Discord but that looks to be dead at the moment. So...

Does anybody have device information that would match NOX?

The Settings -> About isn't too informative.

Thanks.

**Comment by Taranis01** [comment]
open build.prop (google for more info about this) and search for the entries here: https://github.com/NECROBOTIO/NecroBot/issues/2801#issuecomment-238089579

that discord is down is no excuse for all the people spamming the issue tracker

**Comment by TheMaskedMonkey** [comment]
Thank you!
