### ISSUE TITLE
[Suggestion] Add "TransferWeakMoveSet" "KeepBestCP" Along With A Few Other Things

### ISSUE THREAD

**Issue by MapError** [NECROBOTIO/NecroBot#2820]
Right now the bot is kinda still hording Pokemon and I think an additaonl settings or two could help complement the other settings the bot offers. 

My suggestion is add a "TransferWeakMoveSet" and add "KeepBestCP" with the "KeepBestCP" being a true or false and remove "KeepMinCP" which would be replaced by "KeepBestCP" this would allow to have best cp possible without have to have mess with the current "KeepMinCP". 

Enhancement to rename "TransferWeakPokemon" to "TransferWeakIV"

Right now with all default settings and enabling "TransferWeakPokemon" and prorizing IV over cp to true its hoarding for example 4 Slowbro with the addition  of "TransferWeakMoveSet" if should transefer all the weak move set and only keep the one for example that has 15/55 move set. This way I keep the best IV with best Move Set and best possible CP for my level, this also allows to only keep 1 of ever Pokemon but only best and if I need to change things all I would do is tweak the current settings the bot offers.

I think overall this would be a great as it should help filter things more. 

I hope I explained things well.

**Comment by Taranis01** [comment]
There was already a request for a feature to keep the best X pokemon. i would like to link to that too but cant find it anymore ;)

**Comment by MapError** [comment]
Right now over these previous version bot loves to horde Pokemon  haa Hopefully a few more tweaks and settings can improve.
