### ISSUE TITLE
UseLuckyEggsWhileEvolving still not working

### ISSUE THREAD

**Issue by wkc60908** [NECROBOTIO/NecroBot#2821]
Hi all,

I've set the UseLuckyEggsWhileEvolving to true, but it keeps evolving based on EvolveAllPokemonWithEnoughCandy.

Did I just set it wrongly or is the UseLuckyEggsWhileEvolving overriding other options?  Thanks.

**Comment by koenboots** [comment]
I've just installed release 0.7.1 and ran it the default settings initially. I noticed that Pokémon were evolved immediately, so I changed these lines in the config file. That seems to have done the trick.

`"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": true,
"EvolveKeptPokemonsAtStorageUsagePercentage": 95.0,
"KeepPokemonsThatCanEvolve": true,
"UseLuckyEggsMinPokemonAmount": 75,
"UseLuckyEggsWhileEvolving": true,`
