### ISSUE TITLE
User-Agent?

### ISSUE THREAD

**Issue by ReadyHub** [NECROBOTIO/NecroBot#2823]
Hello all, I've connect my android phone to a proxy server on my PC and launch "Pokémon GO".

I got request to Niantic servers, but the User-Agent was something like this "Dalvik/**X**.**X**.**X** (Linux; U; Android **X**.**X**.**X**; **XX-XXXXX** Build/**XXXXXX**)".
BTW I read the source code and found that User-Agent in the bot source code like this "Niantic App"!

What we should use? "Niantic App" or the User-Agent I got from proxy?

**Comment by thekjohn** [comment]
anything here ?
