### ISSUE TITLE
Trashed all my Ultra balls, Great balls.

### ISSUE THREAD

**Issue by mitoomi** [NECROBOTIO/NecroBot#2827]
Had this "TotalAmountOfPokeballsToKeep": 120,

All the good pokeballs are getting trashed.

Added this    
 "Key": "itemPokeBall",
      "Value": 15
    },
    {
      "Key": "itemGreatBall",
      "Value": 35
    },
    {
      "Key": "itemUltraBall",
      "Value": 70
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    }

also does not seem to work

Please help thanks

**Comment by Aneduna** [comment]
Screenshot of Ultraballs getting recycled would be nice. I think the bot never throws them away. No matter the settings

**Comment by mitoomi** [comment]
1 hour into the bot,

[23:56:36] (INFO) Current Pokeballs: 58 | Greatballs: 8 | Ultraballs: 1 | Masterballs: 0
[23:56:36] (INFO) Current Total Potions: 94 | Total Revives: 68 | Berries: 54 | Total Incense: 12 | Lucky Eggs: 9 | Lures: 9

**Comment by Aneduna** [comment]
This does not mean that the bot threw them away?

This just means that the acc does not have them anymore (Probably used because of bad settings)

**Comment by mitoomi** [comment]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 2000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.778915,
  "DefaultLongitude": -73.962277,
  "WalkingSpeedInKilometerPerHour": 200.0,
  "MaxSpawnLocationOffset": 10,
  "DeviceId": "529e8aa6201f78b5",
  "AndroidBoardName": "msm8994",
  "AndroidBootloader": "unknown",
  "DeviceBrand": "OnePlus",
  "DeviceModel": "OnePlus2",
  "DeviceModelIdentifier": "ONE A2003_24_160604",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "OnePlus",
  "HardwareModel": "ONE A2003",
  "FirmwareBrand": "OnePlus2",
  "FirmwareTags": "dev-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447840820:user/release-keys",
  "DelayBetweenPlayerActions": 0,
  "DelayBetweenPokemonCatch": 10,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 10.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 10,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 10000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 2000,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemPokeBall",
      "Value": 15
    },
    {
      "Key": "itemGreatBall",
      "Value": 35
    },
    {
      "Key": "itemUltraBall",
      "Value": 70
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    }
  ],

Please kindly advise?

**Comment by Aneduna** [comment]
So this is probably a settings issue and should be discussed in discord.
If everyone posted an issue with config help. Github issues would be spammed.

**Comment by mitoomi** [comment]
Ok my bad, Thanks anyway

**Comment by PokemasterMike** [comment]
you have
"SnipeAtPokestops": true,
"MinPokeballsToSnipe": 10,
"MinPokeballsWhileSnipe": 0,
this would use all your pokeballs in rapid succession, check your log how many pokemon you caught and close this please
