### ISSUE TITLE
Still getting the "no usable pokestops" issue.

### ISSUE THREAD

**Issue by kinggee211** [NECROBOTIO/NecroBot#2831]
I know this has been spammed here recently but I'm still getting the error.

Not softbanned, running 7.1, max distance on 3000.

Why is this happening, thanks.

**Comment by itz420anytime** [comment]
uninstall everything or delete it and start new check the lat and long too on google maps make sure theyre right

**Comment by kinggee211** [comment]
ive done that twice now, deleted the whole folder and started again. Lat i set as 50 and long i set as 0

**Comment by itz420anytime** [comment]
you need actual lat and long haha those arent coordinates

**Comment by kinggee211** [comment]
haha am i being a tool? what should i put in?

**Comment by itz420anytime** [comment]
just type in google coordinates for where you played pokemon go last and input those coords into the config file

**Comment by itz420anytime** [comment]
like i chose philly because thats where im near coords look kinda like this 39.95, -75.166667 sometimes longer firt one is lat second is long

**Comment by Linewalker** [comment]
If only long is negative, please refeer to this: https://github.com/NECROBOTIO/NecroBot/issues/2822 and this https://github.com/NECROBOTIO/NecroBot/issues/2798, otherwise its a config problem an no issue itself.

**Comment by kinggee211** [comment]
ot it working thanks guys, i redownloaded and didnt change location

**Comment by prophetal** [comment]
hmm i get the same error after 2 pokestops he not find anything else ?
