### ISSUE TITLE
(ERROR) System.ArgumentNullException: Value cannot be null. Parameter name: value

### ISSUE THREAD

**Issue by Magnaleikha91** [NECROBOTIO/NecroBot#2834]
Anyone can help? Checked username and password, nothing wrong...
![aasd](https://cloud.githubusercontent.com/assets/20828547/17463578/daf9ac06-5cf2-11e6-9ba0-9dfce4d85ad5.png)

**Comment by colinodell** [comment]
Do you have a `DeviceId` set in your `config.json`?

**Comment by Magnaleikha91** [comment]
I don't think so, any idea how to do that? (I'm new :D )

**Comment by colinodell** [comment]
1. Exit the bot
2. Rename your `config.json` file or move it somewhere else
3. Run the bot; it'll help you generate a fresh configuration file with everything you need

If you had previously customized the settings before and want to keep those, also do the following:

4. Exit the bot
5. Manually copy over the settings from your old `config.json` into the new one
6. Start the bot again

**Comment by toquengtoketin** [comment]
That is not a fix, this is a logic error by the source that was committed by ChemiHatake, the merge broke the latest clone.

**Comment by Magnaleikha91** [comment]
What should I do then @toquengtoketin? Sorry for being absent minded, hehe, coz' I'm just "commoners"... :p

**Comment by toquengtoketin** [comment]
for me, since im also debugging and adding stuff, goto;
https://github.com/NECROBOTIO/NecroBot/tree/v0.7.1

and reclone the 0.7.1 source and use that, wait until the current master build is fixed in the mean time.

**Comment by beastminder1985** [comment]
@toquengtoketin still getting the same issue. I might be doing something wrong though
