### ISSUE TITLE
KillSwitch

### ISSUE THREAD

**Issue by nisanb** [NECROBOTIO/NecroBot#2835]
Is KillSwitch option suppose to work?
Because it doesn't

**Comment by Aneduna** [comment]
Killswitch option checks for the file on this github, so that in case of bans or smth the bot can be disabled. Changing the setting in your folder does nothing

**Comment by dkfd3vil** [comment]
How do you mean it isnt working?

**Comment by nisanb** [comment]
I tried creating the file on my necrobot folder, and configuring it as
disabled, but it won't stop the bot

**Comment by dkfd3vil** [comment]
it isnt meant for the enduser, but more of a way to disable the bots from the developers, you shouldnt use the killswitch ;), cause you can just exit your bot

**Comment by Aneduna** [comment]
Creating the file file on your local machine is not doing anything because it is not supposed to do anything. Necrobot checks the file on github.

**Comment by nisanb** [comment]
Alright..Thanks!
