### ISSUE TITLE
stuck on log in

### ISSUE THREAD

**Issue by MorKSD** [NECROBOTIO/NecroBot#2836]
I have completed the set up, fixed both auth and config, but the bot remains stuck on log in:

[18:02:45] (UPDATE) Perfect! You already have the newest Version 0.7.1
[18:02:45] (INFO) Logging in using Google

.... nothing happens

**Comment by LeoRedin** [comment]
same problem here. all setup was with default options...

**Comment by LeoRedin** [comment]
if you close it and then start again may work

**Comment by MorKSD** [comment]
it doesn't, I've tried different accounts, tweaks in the config, reboot, still stuck

**Comment by itzjaydon** [comment]
mine worked on restart but says unable to load dll

**Comment by her0shima** [comment]
me to, stuck on login, close and restart still not work

**Comment by Magnaleikha91** [comment]
Same here

**Comment by itzjaydon** [comment]
see if this helps at all https://www.youtube.com/watch?annotation_id=annotation_3322155969&feature=iv&src_vid=vCa_FdnIhJE&v=5bget_MFsKg

**Comment by ReadyHub** [comment]
Run as administator ...

**Comment by her0shima** [comment]
I 've run administrator, but still stuck

**Comment by ReadyHub** [comment]
Check firewall, try to use proxy or vpn

**Comment by her0shima** [comment]
thanks readyhub there is proxy in my internet explorer. i remove the proxy and the bot work #sorry for my bad english

**Comment by Bam30** [comment]
Same here.
Works on my Desktop Windows 7, but on VMWare VPS with WIndows 7 Home Premium (32bit, NET Framework 4.6.2) it stucks.
Tried with and without VPN, Proxy, Firewall on/off.

Could it have something to do with TLS? OpenVPN in VPS gives me TLS error. Though in Host system TLS works.

**Comment by MorKSD** [comment]
When I run as admin it gives me this error:
[18:49:28] (ERROR) System.UnauthorizedAccessException: Accesso al percorso 'C:\Windows\system32\LogFiles\WMI\RtBackup' negato.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   in System.IO.FileSystemEnumerableIterator`1.MoveNext()
   in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   in System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   in System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   in PoGo.NecroBot.Logic.State.VersionCheckState.<CleanupOldFiles>d__5.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\VersionCheckState.cs:riga 143
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.NecroBot.Logic.State.VersionCheckState.<Execute>d__4.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\VersionCheckState.cs:riga 39
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:riga 36
[18:49:28] (INFO) Logging in using Google
[18:49:28] (ERROR) You need to fill out GoogleUsername and GooglePassword in auth.json!

**Comment by GeMoo** [comment]
@MorKSD 
> 18:49:28 You need to fill out GoogleUsername and GooglePassword in auth.json!

fill your username and password in Config\auth.json

**Comment by MorKSD** [comment]
the problem is that I already fill user and psw, and yes I also used " "

**Comment by Bam30** [comment]
I fixed it by cloning an older state of the VM which was before I installed a VPN and Proxy Program.
Now it works even with proxy and firewall activated.

Regards

**Comment by wetshrimp** [comment]
did you get this to work? same

**Comment by daika7ana** [comment]
I had the same issue. I managed to fix it after logging off on my phone, logging back in, and only after that, the bot started. See if it does it for you as well.
