### ISSUE TITLE
[Error]Issue loading translations

### ISSUE THREAD

**Issue by wxyz80** [NECROBOTIO/NecroBot#2837]
Is there anyone who gets the same error when trying to start the software?
![necro1](https://cloud.githubusercontent.com/assets/20888906/17463621/fd6de596-5cc9-11e6-8b05-bfbbcb264c02.jpg)

**Comment by Fulkol** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2805

**Comment by Syllabear86** [comment]
yes, i have the same error, and don t know how to fix it!
