### ISSUE TITLE
PogoLocationFeeder is founding me just 1 snipping server..

### ISSUE THREAD

**Issue by Tavorib** [NECROBOTIO/NecroBot#2838]
Hey,
So I'm having that issue that the PogoLocationFeeder is founding me just 1 snipping server and its 'pokesnippers' .. 
How can I fix it so it will be founding me the all other else snipping servers.?.
please help me .. 
Thanks :) :+1:

**Comment by Aneduna** [comment]
This is not an issue from necrobot. Go to the github of PogoLocationFeeder

**Comment by Tavorib** [comment]
Ok thanks
