### ISSUE TITLE
(INFO) Amount of Pokemon Seen: 145/151, Amount of Pokemon Caught: 145/151

### ISSUE THREAD

**Issue by dody19852002** [NECROBOTIO/NecroBot#2839]
(INFO) Amount of Pokemon Seen: 145/151, Amount of Pokemon Caught: 145/**151**

is that supposed to be 250 in  inventory?

**Comment by Aneduna** [comment]
What is the issue?

**Comment by Linewalker** [comment]
And btw. he won't get anymore pokemons, as i know. Perhaps we need a little string fix in the output "Seen/Total possible:" and "Caught/Total cacheable".
