### ISSUE TITLE
Snipe Specific Pokemon?

### ISSUE THREAD

**Issue by user8285** [NECROBOTIO/NecroBot#2841]
Is there a file to edit to only snipe specific pokemon?

**Comment by colinodell** [comment]
Have you tried adjusting the `PokemonToSnip` => `Pokemon` list?

**Comment by user8285** [comment]
@colinodell yeah i was playing around with that but had a crap load of errors after running the bot again. Im assuming to not snipe pokemon you add a // in front of the name correct? so like this //"venusaur" or
// "venusaur"? thanks in advance.

**Comment by colinodell** [comment]
I don't believe that JSON supports comments.  You'll have to completely remove `"venusaur",` if you don't wish to snipe them any more.
