### ISSUE TITLE
How can I get  my device info?

### ISSUE THREAD

**Issue by MatteCarra** [NECROBOTIO/NecroBot#2845]
How can I get  my device info?
I can not find for example DeviceModelIdentifier and HardwareModel.
I have a OnePlus One.

**Comment by Zubinexu** [comment]
Not sure , If correct it should go to WIKI. 

IN YOUR PHONE, Download "AIDA64",
  And using it fill in the info on you config
  I Dont know exactly that is correct but here what I found

  "DeviceId" : AIDA64 > Android > Android Id
  "AndroidBoardName": AIDA64 > System > Board
  "AndroidBootloader": AIDA64 > Android > Bootloader
  "DeviceBrand": AIDA64 > System > Brand
  "DeviceModel": AIDA64 > System > Device Model
  "DeviceModelIdentifier": AIDA64 > Android > Build ID
  "DeviceModelBoot": AIDA64 > System > Hardware
  "HardwareManufacturer": AIDA64 > System > Manufacturer
  "HardwareModel": AIDA64 > System > Model
  "FirmwareBrand": AIDA64 > System > Device Model
  "FirmwareTags": AIDA64 > Android > Tags
  "FirmwareType": AIDA64 > Android > Type
  "FirmwareFingerprint": AIDA64 > Android > Fingerprint

**Comment by fr0gg** [comment]
any ideas on iphones?

**Comment by aapikz** [comment]
anyone know phone device generator? i think its not really good idea to use same phone running in 10 bots at same time

**Comment by Zubinexu** [comment]
Actually the only value you have to modify is "DeviceId" , 

the rest are for overachievers or for people that want or need to emulate personal phone.

**Comment by RELAXccc** [comment]
@Zubinexu i guess it adds atleast some credibility to your account if you use the same Info as your actual Phone you play on

**Comment by martinwind** [comment]
CANT find "AndroidBootloader": AIDA64 > Android > Bootloader

**Comment by poutros** [comment]
@martinwind Usually, the bootloader is "unknown" so don't worry much about it. Leave it as default.

**Comment by wakrad** [comment]
you can download apps on playstore https://play.google.com/store/apps/details?id=com.alphabetlabs.deviceinfo&hl=in

**Comment by Zubinexu** [comment]
New release has a wiki how to get values

**Comment by Haglerd** [comment]
I dont see this, "DeviceModel": AIDA64 > System > Device Model I see a device, and a model, but not a device model

**Comment by poutros** [comment]
@Haglerd It's literally the first value there.

**Comment by Haglerd** [comment]
Well. Actually mine shows Manufacturer first... Then, Model is next. Then later in the list I have Device. However, there is no "DeviceModel": AIDA64 > System > **Device Model**!

**Comment by poutros** [comment]
Weird. Mine shows:
Device Model
Device Type
Manufacturer
...

**Comment by Haglerd** [comment]
So, which should I go with for firmwarebrand and devicemodel? 
AIDA64 - System 
Manufacturer: motorola 
Model: droidx
Brand:  verizon
Board: cdma
Device: cdma_shadow 
hardware
platform
So on...

**Comment by JustRegisteredToSayThis** [comment]
@Haglerd are you on an emulator?
Typically the DeviceModel would be the full name of you phone, which usually comes down to Brand + Model. Manufacturer's vary in this themselves too, but say you have a Samsung Galaxy S5, that's your DeviceModel

**Comment by Haglerd** [comment]
In that case, then HardwareModel would be the same as FirmwareBrand and DeviceModel?

**Comment by JustRegisteredToSayThis** [comment]
It could be, some manufacturers have differing designations, others don't, others just leave it blank.

**Comment by wowkiller123** [comment]
anyone know the set up for iphone?

**Comment by Haglerd** [comment]
Alright, well I will just try to find it elsewhere I guess....
