### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by UAVova** [NECROBOTIO/NecroBot#2846]
SOLVED

**Comment by toquengtoketin** [comment]
update rocket api and protos here;
https://github.com/NECROBOTIO

**Comment by UAVova** [comment]
@toquengtoketin It's already up to date. I used installation guide, so i don't skipped this step

**Comment by RELAXccc** [comment]
You have do download the GREY parts separately and extract them into the folders.
so you have to download 3 Zip files:
NecroBot-master,  FeroxRev @ 84d9ff7  and POGOProtos @ d8c43a1

**Comment by toquengtoketin** [comment]
What RELAX said, you have to place the PROTOS and API src's int he correct dirs.

**Comment by UAVova** [comment]
@RELAXccc What i downloaded:
[https://github.com/NECROBOTIO/NecroBot-Rocket-API](https://github.com/NECROBOTIO/NecroBot-Rocket-API)
[https://github.com/NECROBOTIO/POGOProtos-0.31.0](https://github.com/NECROBOTIO/POGOProtos-0.31.0)
[https://github.com/NECROBOTIO/NecroBot](https://github.com/NECROBOTIO/NecroBot)
Run the necroBot project and included all the other stuff into it. It should be enough, right?

**Comment by UAVova** [comment]
@toquengtoketin You can manually link them into solution using Add -> Existing project, if you want to, so it's not a problem.

**Comment by RELAXccc** [comment]
@UAVova yes, extract
"NecroBot-Rocket-API" into the FeroxRev Folder
"POGOProtos-0.31.0" into the POGOProtos Folder
then you should be fine.
If you still can't compile, try to "Reload Project":
![gitklick](https://cloud.githubusercontent.com/assets/20889998/17463843/9bf06ab2-5cd0-11e6-8f3f-edacc8559c1d.png)
