### ISSUE TITLE
CatchError and very few pokemons

### ISSUE THREAD

**Issue by thekjohn** [NECROBOTIO/NecroBot#2847]
Hi all!

Sometimes I am still getting CatchError and then for a long time (sometimes a few minutes) the bot can't find any pokemons to encounter.

My walk speed is 10.6 km/h.

**Comment by thekjohn** [comment]
is there any chance the server "softbans" pokemon catch because the bot does not respect the probability value of the encounter and always sends hit = true ?

**Comment by SDMU** [comment]
does that occur only at a specific location ?

**Comment by ShallowHacker** [comment]
thekjohn, not as far as I am aware. My bots running fine. I even have mine set to 100% of the time use excellent throws as curveballs. That's how i've always set it up. I only run it on my spare accounts so my worries are little to none.

**Comment by thekjohn** [comment]
then I have no idea what's happening here :(

**Comment by thekjohn** [comment]
how often do you get CatchError ?

**Comment by ShallowHacker** [comment]
Once every hour or more? Like, hardly ever at all...

**Comment by ShallowHacker** [comment]
And I'm running the bot I'm Goldengate park sanfran and I'm in Seattle wa.
Lol
