### ISSUE TITLE
Transfer filter moves operator question

### ISSUE THREAD

**Issue by Skullmonkey** [NECROBOTIO/NecroBot#2848]
How do I it set it up to keep a specific move sets?

I get if I want a single move set I use
```
    "Dragonite": {
      "Moves": ["SteelWing","DragonClaw"],
      "MovesOperator": "or"
    },
```
Say if I would like to save an attacker (DragonBreath,DragonClaw)  and defenders (SteelWing,DragonClaw), how would I configure that?

(Also, either a wiki update is needed or at least an example in the config.)

**Comment by SDMU** [comment]
won't using "and " solve your problem ?

**Comment by Aneduna** [comment]
He wants to keep the Dragonite either if it has the Movesets

DragonBreath and DragonClaw
or
SteelWing and DragonClaw

which is not possible at the moment?

**Comment by q32103940** [comment]
wiki still needs to document it...

the way OP want's it, im guessing the closest the config can do would be to transfer all dragonites with Dragon Pulse, Hyper Beam with movesoperator as "or"
