### ISSUE TITLE
Can't Keep Pokemon

### ISSUE THREAD

**Issue by Rexsa** [NECROBOTIO/NecroBot#2849]
No matter what I do, I can't keep 1 duplicate of each pokemon. Some guidance would be much appreciated!

**Comment by Bannz** [comment]
and how make it keep 2 pokemon with good CP and IV.. always transfered by bot and left just 1 pokemon.. even that cp higher than IV ..

**Comment by user8285** [comment]
Line 50 "KeepMinDuplicatePokemon" Have u tried that?

**Comment by Aneduna** [comment]
So this is probably a settings issue and should be discussed in discord.
If everyone posted an issue with config help, Github issues would be spammed.

**Comment by Bannz** [comment]
I have tried fill 2 .. but still left 1 pokemon.. how come??

**Comment by SDMU** [comment]
fill 0

**Comment by SDMU** [comment]
as a result 0 duplicate pokemon will be left

**Comment by Bannz** [comment]
@SDMU huh?!! sorry? so there isnt pokemon left?

**Comment by SDMU** [comment]
there will be . only 1 pokemon of each

**Comment by Aneduna** [comment]
Isn't keepMinDuplicatePokemon = 1 keeping only 1 of each pokemon?

I think @Rexsa may look into TransferList, because these Settings overwrite keepMinDuplicatePokemon

**Comment by Rexsa** [comment]
I just deleted the config file to reset everything. I will change things one by one to see where I fucked up.
