### ISSUE TITLE
What do i do to keep Hyber, Max Potion, Ultra ball, Max revive?

### ISSUE THREAD

**Issue by missyyou94** [NECROBOTIO/NecroBot#2853]
My bag is limited.
I want to keep hyper potion and max potion instead potion? 
I want to keep max revive instead revive?
I want to keep ultra ball, greater ball instead pokeball?
And what do i do?

**Comment by jgwallace3** [comment]
My observation is that if you set a limit on potions, then when the limit is reached, the lesser potions are discarded first. The same applies to revives and balls.

**Comment by SDMU** [comment]
I guess the program automatically tries to save the items with higher value . If you don't want to keep normal pokeballs , all your great and ultra balls will be used to catch pokemon . Also if possible ask such issues on discord app

**Comment by SDMU** [comment]
is verbose recycling on ? what do you see there ?

**Comment by missyyou94** [comment]
"VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
It true?

**Comment by jgwallace3** [comment]
Do your max potions, revives and balls total less than 90% of inventory
space?
