### ISSUE TITLE
Keep more than one pokemon to evolve per species

### ISSUE THREAD

**Issue by alessandro1989g** [NECROBOTIO/NecroBot#2857]
Hi!
I am new to this community and I want to thank you all for your great work!

I have a question: how can I set the config file to keep a specific number of pokemon which I can evolve?

Let's say I have 53 pidgey candies and 7 pidgey. I can hypotetically evolve 5 pidgey. In fact I can first evolve one pidgey, using 12 candies, then I get 2 candies back, one from the evolution and one from the transfer. I used 10 candies. I can keep doing this until I ran out of candies. 
How can I set the program to release the pidgey I do not need and to keep the ones I need?

Thanks!

**Comment by SDMU** [comment]
use the keepmincp and keepminiv options

**Comment by alessandro1989g** [comment]
There are no min cp or iv which I need. I just want to release the pokemon that I cannot evolve and keep the others, to maximize the XP from the evolution settings. Is there a way to do that?

**Comment by Aneduna** [comment]
@SDMU is wrong.

"KeepPokemonsThatCanEvolve": true, should be the setting you are looking for. I'm not sure if that setting is also calculating the candies you get from evolving tho.

**Comment by alessandro1989g** [comment]
I do not think it does, I tried it and it did not work. 

The best thing to do in my opinion is to build and option to 
1) keep every useful pokemon that can evolve, not caring about cp or iv
2) accumulate a certain number of pokemon (like 40)
3) use a lucky egg
4) evolve all the pokemon that can evolve, maybe inserting a list of "forbidden pokemon evolutions"

**Comment by Aneduna** [comment]
It should exactly do that with the setting.
Altough it is waiting for 90% Pokemon Inventory to actually evolve.

"KeepMinDuplicatePokemon": 1 or 0 
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
Have to be enabled though to actually recycle

**Comment by Aneduna** [comment]
Also Config issues should be handled in the discord to not spam Github issues

**Comment by alessandro1989g** [comment]
Ok thanks!

**Comment by RELAXccc** [comment]
i found a list of all Pokemon for you, i dont know if its 100% accurate:
`"Bulbasaur", 
"Ivysaur", 
"Venusaur", 
"Charmander", 
"Charmeleon", 
"Charizard", 
"Squirtle", 
"Wartortle", 
"Blastoise", 
"Caterpie", 
"Metapod", 
"Butterfree", 
"Weedle", 
"Kakuna", 
"Beedrill", 
"Pidgey", 
"Pidgeotto", 
"Pidgeot", 
"Rattata", 
"Raticate", 
"Spearow", 
"Fearow", 
"Ekans", 
"Arbok", 
"Pikachu", 
"Raichu", 
"Sandshrew", 
"Sandslash", 
"NidoranFemale", 
"Nidorina", 
"Nidoqueen", 
"NidoranMale", 
"Nidorino", 
"Nidoking", 
"Clefairy", 
"Clefable", 
"Vulpix", 
"Ninetales", 
"Jigglypuff", 
"Wigglytuff", 
"Zubat", 
"Golbat", 
"Oddish", 
"Gloom", 
"Vileplume", 
"Paras", 
"Parasect", 
"Venonat", 
"Venomoth", 
"Diglett", 
"Dugtrio", 
"Meowth", 
"Persian", 
"Psyduck", 
"Golduck", 
"Mankey", 
"Primeape", 
"Growlithe", 
"Arcanine", 
"Poliwag", 
"Poliwhirl", 
"Poliwrath", 
"Abra", 
"Kadabra", 
"Alakazam", 
"Machop", 
"Machoke", 
"Machamp", 
"Bellsprout", 
"Weepinbell", 
"Victreebel", 
"Tentacool", 
"Tentacruel", 
"Geodude", 
"Graveler", 
"Golem", 
"Ponyta", 
"Rapidash", 
"Slowpoke", 
"Slowbro", 
"Magnemite", 
"Magneton", 
"Farfetchd", 
"Doduo", 
"Dodrio", 
"Seel", 
"Dewgong", 
"Grimer", 
"Muk", 
"Shellder", 
"Cloyster", 
"Gastly", 
"Haunter", 
"Gengar", 
"Onix", 
"Drowzee", 
"Hypno", 
"Krabby", 
"Kingler", 
"Voltorb", 
"Electrode", 
"Exeggcute", 
"Exeggutor", 
"Cubone", 
"Marowak", 
"Hitmonlee", 
"Hitmonchan", 
"Lickitung", 
"Koffing", 
"Weezing", 
"Rhyhorn", 
"Rhydon", 
"Chansey", 
"Tangela", 
"Kangaskhan", 
"Horsea", 
"Seadra", 
"Goldeen", 
"Seaking", 
"Staryu", 
"Starmie", 
"MrMime", 
"Scyther", 
"Jynx", 
"Electabuzz", 
"Magmar", 
"Pinsir", 
"Tauros", 
"Magikarp", 
"Gyarados", 
"Lapras", 
"Ditto", 
"Eevee", 
"Vaporeon", 
"Jolteon", 
"Flareon", 
"Porygon", 
"Omanyte", 
"Omastar", 
"Kabuto", 
"Kabutops", 
"Aerodactyl", 
"Snorlax", 
"Articuno", 
"Zapdos", 
"Moltres", 
"Dratini", 
"Dragonair", 
"Dragonite", 
"Mewtwo", `
