### ISSUE TITLE
Only Catch choosen pokemon?

### ISSUE THREAD

**Issue by Paradyse19** [NECROBOTIO/NecroBot#2859]
Is there a way to tell the bot that it should only catch 1 or 2 pokemon?

kind regards

**Comment by RELAXccc** [comment]
i guess you have to make a "PokemonsToIgnore" list for the config.json that ignores everything escept the 1 or 2 Pokemon you want.
I dont really have a list that you can copy-paste, but here is a list that has all evolveable pokemons in it:

`: [
    "bulbasaur",
    "ivysaur",
    "charmander",
    "charmeleon",
    "squirtle",
    "wartortle",
    "caterpie",
    "metapod",
    "weedle",
    "kakuna",
    "pidgey",
    "pidgeotto",
    "rattata",
    "spearow",
    "ekans",
    "pikachu",
    "sandshrew",
    "nidoranFemale",
    "nidorina",
    "nidoranMale",
    "nidorino",
    "clefairy",
    "vulpix",
    "jigglypuff",
    "zubat",
    "oddish",
    "gloom",
    "paras",
    "venonat",
    "diglett",
    "meowth",
    "psyduck",
    "mankey",
    "growlithe",
    "poliwag",
    "poliwhirl",
    "abra",
    "kadabra",
    "machop",
    "machoke",
    "bellsprout",
    "weepinbell",
    "tentacool",
    "geodude",
    "graveler",
    "ponyta",
    "slowpoke",
    "magnemite",
    "doduo",
    "seel",
    "grimer",
    "shellder",
    "gastly",
    "haunter",
    "drowzee",
    "krabby",
    "voltorb",
    "exeggcute",
    "cubone",
    "koffing",
    "rhyhorn",
    "horsea",
    "goldeen",
    "staryu",
    "magikarp",
    "eevee",
    "omanyte",
    "kabuto",
    "dratini",
    "dragonair"
  ]`

**Comment by SDMU** [comment]
enter the rest of the pokemon in the ignore list

**Comment by Paradyse19** [comment]
okay imma do it like that then thx

**Comment by RELAXccc** [comment]
@Paradyse19  and set 
`"UsePokemonToNotCatchFilter": true`
(i did also edit my above post)

**Comment by AndreasGilja** [comment]
What do i do whit USe proxy ANd useproxyusername ??

Sendt fra min iPhone

Den 7. aug. 2016 kl. 19.10 skrev RELAXccc <notifications@github.com<mailto:notifications@github.com>>:


i guess you have to make a "PokemonsToIgnore" list for the config.json that ignores everything escept the 1 or 2 Pokemon you want.
I dont really have a list that you can copy-paste, but here is a list that has all evolveable pokemons in it:

: [
"bulbasaur",
"ivysaur",
"charmander",
"charmeleon",
"squirtle",
"wartortle",
"caterpie",
"metapod",
"weedle",
"kakuna",
"pidgey",
"pidgeotto",
"rattata",
"spearow",
"ekans",
"pikachu",
"sandshrew",
"nidoranFemale",
"nidorina",
"nidoranMale",
"nidorino",
"clefairy",
"vulpix",
"jigglypuff",
"zubat",
"oddish",
"gloom",
"paras",
"venonat",
"diglett",
"meowth",
"psyduck",
"mankey",
"growlithe",
"poliwag",
"poliwhirl",
"abra",
"kadabra",
"machop",
"machoke",
"bellsprout",
"weepinbell",
"tentacool",
"geodude",
"graveler",
"ponyta",
"slowpoke",
"magnemite",
"doduo",
"seel",
"grimer",
"shellder",
"gastly",
"haunter",
"drowzee",
"krabby",
"voltorb",
"exeggcute",
"cubone",
"koffing",
"rhyhorn",
"horsea",
"goldeen",
"staryu",
"magikarp",
"eevee",
"omanyte",
"kabuto",
"dratini",
"dragonair"
]

-

**Comment by RELAXccc** [comment]
@Paradyse19 i found a list of all 151 Pokemon for you. I don't know if its 100% accurate:
`"Bulbasaur", 
"Ivysaur", 
"Venusaur", 
"Charmander", 
"Charmeleon", 
"Charizard", 
"Squirtle", 
"Wartortle", 
"Blastoise", 
"Caterpie", 
"Metapod", 
"Butterfree", 
"Weedle", 
"Kakuna", 
"Beedrill", 
"Pidgey", 
"Pidgeotto", 
"Pidgeot", 
"Rattata", 
"Raticate", 
"Spearow", 
"Fearow", 
"Ekans", 
"Arbok", 
"Pikachu", 
"Raichu", 
"Sandshrew", 
"Sandslash", 
"NidoranFemale", 
"Nidorina", 
"Nidoqueen", 
"NidoranMale", 
"Nidorino", 
"Nidoking", 
"Clefairy", 
"Clefable", 
"Vulpix", 
"Ninetales", 
"Jigglypuff", 
"Wigglytuff", 
"Zubat", 
"Golbat", 
"Oddish", 
"Gloom", 
"Vileplume", 
"Paras", 
"Parasect", 
"Venonat", 
"Venomoth", 
"Diglett", 
"Dugtrio", 
"Meowth", 
"Persian", 
"Psyduck", 
"Golduck", 
"Mankey", 
"Primeape", 
"Growlithe", 
"Arcanine", 
"Poliwag", 
"Poliwhirl", 
"Poliwrath", 
"Abra", 
"Kadabra", 
"Alakazam", 
"Machop", 
"Machoke", 
"Machamp", 
"Bellsprout", 
"Weepinbell", 
"Victreebel", 
"Tentacool", 
"Tentacruel", 
"Geodude", 
"Graveler", 
"Golem", 
"Ponyta", 
"Rapidash", 
"Slowpoke", 
"Slowbro", 
"Magnemite", 
"Magneton", 
"Farfetchd", 
"Doduo", 
"Dodrio", 
"Seel", 
"Dewgong", 
"Grimer", 
"Muk", 
"Shellder", 
"Cloyster", 
"Gastly", 
"Haunter", 
"Gengar", 
"Onix", 
"Drowzee", 
"Hypno", 
"Krabby", 
"Kingler", 
"Voltorb", 
"Electrode", 
"Exeggcute", 
"Exeggutor", 
"Cubone", 
"Marowak", 
"Hitmonlee", 
"Hitmonchan", 
"Lickitung", 
"Koffing", 
"Weezing", 
"Rhyhorn", 
"Rhydon", 
"Chansey", 
"Tangela", 
"Kangaskhan", 
"Horsea", 
"Seadra", 
"Goldeen", 
"Seaking", 
"Staryu", 
"Starmie", 
"MrMime", 
"Scyther", 
"Jynx", 
"Electabuzz", 
"Magmar", 
"Pinsir", 
"Tauros", 
"Magikarp", 
"Gyarados", 
"Lapras", 
"Ditto", 
"Eevee", 
"Vaporeon", 
"Jolteon", 
"Flareon", 
"Porygon", 
"Omanyte", 
"Omastar", 
"Kabuto", 
"Kabutops", 
"Aerodactyl", 
"Snorlax", 
"Articuno", 
"Zapdos", 
"Moltres", 
"Dratini", 
"Dragonair", 
"Dragonite", 
"Mewtwo", 
"Mew"`

**Comment by Paradyse19** [comment]
>  i found a list of all 151 Pokemon for you. I don't know if its 100% accurate

thanks
