### ISSUE TITLE
Sniping from discord channels does not work

### ISSUE THREAD

**Issue by mensurdurakovic** [NECROBOTIO/NecroBot#2860]
I setup my PoGoLocationFeeder with right channel infos and in Necro bot I set "UseSnipeOnlineLocationServer" and "UseSnipeLocationServer" to true, but it only snipes pokemons from pokesnipers.com and not single one from discord channels ? Anyone noticed this problem? Also I am not sure if this problem is related to Necro or PoGoFeeder but PoGoFeeder updates screen with new pokemons every minute

**Comment by Aneduna** [comment]
PoGoFeeder also only gets the snipes from pokesnipers.com
It is an issue from https://github.com/5andr0/PogoLocationFeeder/issues/203

**Comment by mensurdurakovic** [comment]
I am sure that PoGoLocationFeeder together with Necro bot was sniping pokemons from discord channels until this update. So it's their issue, you can close this now

**Comment by Aneduna** [comment]
You have to close issue. I'm no Mod
