### ISSUE TITLE
Error at start of bot

### ISSUE THREAD

**Issue by JackSbirrow** [NECROBOTIO/NecroBot#2863]
This is the first time that I use NecroBot. I downloaded the 0.7.1, now there is the 0.7.2
When I open it, the bot immediatly says: 
FATAL ERROR: no replacement translations: Check appropriate files for typos.

What must i do?

**Comment by olokos** [comment]
Same here, update 0.7.2 is broken, lol

**Comment by phanoob** [comment]
change to "en" your language in config

**Comment by JackSbirrow** [comment]
There is no the config file because I deleted the 0.7.1 and downloaded the 0.7.2 so it must be already "en"

**Comment by SDMU** [comment]
or set auto update to false and continue using 0.71

**Comment by SDMU** [comment]
you can always redownload 0.71

**Comment by phanoob** [comment]
I have deleted config  folder before launch 0.72

**Comment by satanvagina** [comment]
Same here.

**Comment by marnixx9** [comment]
Same error. The bot doesn't even create an config file since it gives this error.

**Comment by MythHack** [comment]
01:14:25] (ERROR) System.ArgumentNullException: 值不能为 null。
参数名: value
   在 Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   在 POGOProtos.Networking.Signature.Types.DeviceInfo.set_DeviceId(String value) 位置 C:\Users\ciamo\Source\Repos\NecroBot\POGOProtos\POGOProtos\Networking\Signature.cs:行号 2126
   在 PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests) 位置 C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:行号 65
   在 PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) 位置 C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:行号 151
   在 PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) 位置 C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:行号 200
   在 PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() 位置 C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:行号 0
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() 位置 C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:行号 52
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() 位置 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:行号 181
[01:14:45] (ATTENTION) Due to login failure your player profile could not be retrieved. Press any key to re-try login.

**Comment by TheGreatestDude** [comment]
Same issue here, I still have the previous version but that's now giving me the same error.

**Comment by JackSbirrow** [comment]
I re-downloaded 0.7.1 and now when I open it, the bot stays in black screen mode

**Comment by JackSbirrow** [comment]
In the 0.7.1 I typed my PTC info, now when I re-open it, the bot says "You must compilate the Google information" and it get closed. So I went into confing file and I typed my Google information and when I open the bot it still says the same error.

P.S. I skip the update when It want update

**Comment by defex10** [comment]
All version broken, but how?

**Comment by somani6** [comment]
#2805

**Comment by JackSbirrow** [comment]
@somani6 If I delete all the translation files and run NecroBot.exe It gets a forced close

**Comment by somani6** [comment]
anny error?
this works fine for me. anyway i pulled a fix already with #2817. you can also use langauge "en" with unpatched 0.7.2 version it will work fine as well.

**Comment by JackSbirrow** [comment]
I'm going to change all the "EventPokemonCapture" in "EventPokemonCaptureSuccessSuccess" like you did in every language file. Is it right?

**Comment by somani6** [comment]
only 1 success but yes you can do that as well - you only need to edit your language since only this file gets loaded.

**Comment by JackSbirrow** [comment]
I edited my language file like you said but still the red error

**Comment by somani6** [comment]
what language?

**Comment by JackSbirrow** [comment]
IT

**Comment by JackSbirrow** [comment]
I changed all the language files from "eventPokemonCapture" to "EventPokemonCaptureSuccessSuccess"
but always error

**Comment by somani6** [comment]
there is another error in IT language at eventFortTargeted..

change it to:
```
    {
      "Key": "eventFortTargeted",
      "Value": "Arrivo al Pokestop {0} in : ({1}m)"
    },
```

i will update the file in my pullrequest as well

**Comment by somani6** [comment]
and change eventPokemonCapture to EventPokemonCaptureSuccess not EventPokemonCapture**SuccessSuccess**

**Comment by JackSbirrow** [comment]
I did it but now when I open console it crashes like when I delete the translation folder

**Comment by somani6** [comment]
it works for me after the 2nd change, when i change language to "it".

**Comment by somani6** [comment]
you can download the whole file here:
https://raw.githubusercontent.com/somani6/NecroBot/bb654606e543dd775a984ba665d377847d422f14/PoGo.NecroBot.CLI/Config/Translations/translation.it.json

**Comment by JackSbirrow** [comment]
[](http://puu.sh/qt4px/1dd774f7fc.png) I get this error when I open the .exe

**Comment by somani6** [comment]
what error :)

**Comment by JackSbirrow** [comment]
This http://puu.sh/qt4px/1dd774f7fc.png Then i must close it because the programm doesn't answer

**Comment by somani6** [comment]
oh, thats something else

**Comment by JackSbirrow** [comment]
It's the same error that i get when I delete the translation folder

**Comment by somani6** [comment]
hm if i delete the translation folder it gets recreated after starting the bot with an all english translation.

**Comment by somani6** [comment]
the error you are receiving has not much to do with translation. the bot is trying to get the altitude based on your coords.

**Comment by JackSbirrow** [comment]
I have no the config folder to set the coords because this is the folder when you download it. But this error appeared when I changed the IT folder or when i delete all

**Comment by somani6** [comment]
looks like some others have the same issue: #2927

**Comment by JackSbirrow** [comment]
Maybe other people used the bot before and now get this error. Instead this is the first time for me

**Comment by somani6** [comment]
issue looks like some strange answers from google maps.

**Comment by somani6** [comment]
EventPokemonCaptureSuccess

NOT

EventPokemonCaptureSuccessSuccess

**Comment by JackSbirrow** [comment]
Already did it

**Comment by somani6** [comment]
wrong paste :D - wait :)

**Comment by JackSbirrow** [comment]
I corrected it first

**Comment by somani6** [comment]
what do you have in your config for the following values:

`DefaultLatitude
DefaultLongitude`

**Comment by JackSbirrow** [comment]
I have no config file because I always get that error and it can't create a config file

**Comment by somani6** [comment]
ah! ok that might be the issue :)

**Comment by JackSbirrow** [comment]
So what have I to do?

**Comment by somani6** [comment]
do you have a config folder or nothing at all? - i try to recreate your issue :)

**Comment by JackSbirrow** [comment]
I have the config folder, open it, then there is just the Translation folder with all the languages

**Comment by somani6** [comment]
if you have no config.json or auth.json at all the bot should ask you

> [20:57:05] () This is your first start, would you like to begin setup? Y/N

maybe try to download current release again and overwrite everything, then update translation file again from https://raw.githubusercontent.com/somani6/NecroBot/bb654606e543dd775a984ba665d377847d422f14/PoGo.NecroBot.CLI/Config/Translations/translation.it.json or set your language to 'en'.

**Comment by JackSbirrow** [comment]
I have already downloaded it three times and always get this error

**Comment by JackSbirrow** [comment]
Did it for the fourth time but still error

**Comment by somani6** [comment]
ok, it might be a framework dependend issue ... 
 I have attatched a complete default config as .txt give it a try :)

what os are you using with what .net version?
(https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx)

[auth.txt](https://github.com/NECROBOTIO/NecroBot/files/405657/auth.txt)
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/405659/config.txt)

**Comment by JackSbirrow** [comment]
I'm using Windows 8 (not 8.1) with Framework 4.6 if i'm right.
I downloaded your files and compiled with my information, then i put them in the Config folder but always error at start

**Comment by somani6** [comment]
just to be sure, did you rename the files from auth.txt to auth.json and config.txt to config.json? can't upload the .json format.

**Comment by JackSbirrow** [comment]
Yes and still error

**Comment by warmo137** [comment]
Im having the same problem. I only started using it about 3hrs ago. It lasted about 45mins. I got out of the mod to change some settings. Once i tried starting it back up it stated there was an update. I clicked no.
It then asked me to type in my google acc and pass. So i did. Then it took me back to the bot folder. I clicked back on the app and it stated that i didnt have my google details in the json folder (which i did) 
I tried updating it. It did. Then asked for my details again and same problem.
Everything i do seems to end up in me apparently no having my details in the json folder.

**Comment by somani6** [comment]
hm maybe https://developers.google.com/maps/documentation/elevation/usage-limits is the reason... i think the elevation part has to get removed again.

**Comment by JackSbirrow** [comment]
I had the same problem of @warmo137 with the 0.7.1 (in auth.json there were already my Google details) and if I would choose "Auth type: PTC" and then started the console it said "Auth: google" even if i choosed PTC in auth.json
Then I updated at 0.7.2 and now i have this problem
