### ISSUE TITLE
The most recent update

### ISSUE THREAD

**Issue by MadeBySaints** [NECROBOTIO/NecroBot#2864]
This most recent update caused a bit of a ruckus. After the update only moments ago, my main files were moved to a folder named /tmp, and my config completely reset. it kind of screwed up EVERYTHING.

**Comment by Krishn4k** [comment]
Same for me

**Comment by Zoast** [comment]
Same, I keep getting the error Issue loading translation.

**Comment by SDMU** [comment]
use 0.7 or 0.71 and set auto update to false . and keep a spare copy of your config file :P

**Comment by markuznw** [comment]
Same, 0.7.2 is totally borked :D

**Comment by MadeBySaints** [comment]
@SDMU I agree with this, but they shouldnt push an update like that without testing - this just burned the end user. (in a way) :/

**Comment by SDMU** [comment]
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/405628/config.txt)


rename this to config.json and see if this helps

**Comment by SDMU** [comment]
you'll have to use you own auth.json

**Comment by defex10** [comment]
0.7.1 is also broken.
Cant login anymore...

**Comment by MadeBySaints** [comment]
wait a minute - i just went thru the files in my instance - everything that had the .old at the end, just delete the .old part, and the previous version of your bot should work again

**Comment by soulbeaster** [comment]
My bot running in 0.7.2 version, just download manually the file release, and replace to your old file, dont forget backup ur config file to replace the new one in 0.7.2
