### ISSUE TITLE
TRANSFERED problem

### ISSUE THREAD

**Issue by SklyC** [NECROBOTIO/NecroBot#2865]
(TRANSFERED) Rattata - CP: 350  IV: 46.18%   [Best CP: 386  IV: 41.53%]

Why not transferred IV: 41.53% is transferred IV: 46.18%?

**Comment by Aneduna** [comment]
"PrioritizeIvOverCp": false ?

This is either a duplicate of #2840 or a config issue which should be handled in discord

**Comment by SklyC** [comment]
"PrioritizeIvOverCp": false,
is it to change to true?

**Comment by Aneduna** [comment]
Is it so hard to look into a wiki before asking this question?
https://github.com/NECROBOTIO/NecroBot/wiki/Config#transferring
