### ISSUE TITLE
cannot log in with google

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#2868]
Initializing NecroBot logger at time 8/7/2016 10:09:12 AM...
[10:09:16] New update detected, would you like to update? Y/N
[10:09:19] Downloading and apply Update...
[10:09:23] Finished downloading newest Release...
[10:09:24] Finished unpacking files...
[10:09:24] Logging in using Google
[10:09:24] You need to fill out GoogleUsername and GooglePassword in auth.json!

this is on 0.7.2
didnt work on 0.7.1 either

**Comment by 20giis** [comment]
yes me too!!!!!!!!

**Comment by 20giis** [comment]
whoever made that last update WTFF

**Comment by whatstheyolk** [comment]
im the same, does anyone know how to log in?

**Comment by TheGreatestDude** [comment]
There isn't a way to log in using Google, just have to wait for an update.

**Comment by whatstheyolk** [comment]
any idea how long an update like that would take?

**Comment by TheGreatestDude** [comment]
It's probably a simple typo in the code, maybe an hour? Time to find, amend then test?

**Comment by whatstheyolk** [comment]
cool thanks for your help

**Comment by Jameslaos** [comment]
I restarted the bot and then it worked.

**Comment by hen0va** [comment]
just download the latest and reconfigure, works for me

**Comment by whatstheyolk** [comment]
still doesnt work for me

**Comment by wetshrimp** [comment]
doesnt work for me on google. wtf.

**Comment by palmpje94** [comment]
I cannot log in to the 7.2 bot with PTC, the bot worked fine on 7.0 then i closed it to make some changes in the config and then after update it says: You need to fill out GoogleUsername and GooglePassword in auth.json!, so i unpacked 7.0 and still having the same problem...
