### ISSUE TITLE
Translation error after latest update ! 

### ISSUE THREAD

**Issue by rlmrso** [NECROBOTIO/NecroBot#2870]
Title says enough

**Comment by ClashofJeann** [comment]
+1

**Comment by thedarkdestructor** [comment]
Same here. The bot is not starting. Is some config file missing?

**Comment by somani6** [comment]
#2805

**Comment by natsirtS** [comment]
same here, translation error for 0.7.2 and cant log in with google account for 0.7.1

**Comment by TheMrCaveman** [comment]
+1 +1

**Comment by marnixx9** [comment]
+1

**Comment by Bannz** [comment]
change to "en" config.

**Comment by ClashofJeann** [comment]
only english translation is working, deal with it... I Hope a fix asap.

**Comment by marnixx9** [comment]
@Bannz  It wont create an config file. The only thing in the config folder is the folder called translations?

**Comment by erictoman** [comment]
Only erase alll translations. You only can use English

**Comment by somani6** [comment]
fix is already requested, needs to be aproved by devs

**Comment by EzeGameRR** [comment]
Solution for me: Delete translations folder

**Comment by erictoman** [comment]
Erase all files in Translations folder

**Comment by marnixx9** [comment]
Delete all translations in the folder then start it up.

**Comment by MadeBySaints** [comment]
please close this issue

**Comment by JackSbirrow** [comment]
I have the same problem and If i delete all the translations and open the .exe I get and error in the console and the programm gets a forced close
