### ISSUE TITLE
.exe wont create json/config file

### ISSUE THREAD

**Issue by southpearlerrl** [NECROBOTIO/NecroBot#2871]
I run my .exe file and it opens but doesnt create the json file i need to edit to get the bot running

**Comment by Triky313** [comment]
First start need a Y for yes or N for no.. push y and it is created.

**Comment by xReMuSx** [comment]
Just copy the config.json from v0.7.1 and set "TranslationLanguageCode": "en"

**Comment by southpearlerrl** [comment]
i tried downloading 0.7.1 but still not luck

**Comment by xReMuSx** [comment]
Then try deleting everything from the Translation folder
