### ISSUE TITLE
How can I config multiple bots?

### ISSUE THREAD

**Issue by andrew1135** [NECROBOTIO/NecroBot#2873]
Hi, my english is not very good, so please excuse me.

my question is

How can i config multiple bots?

regards.

**Comment by Aneduna** [comment]
Create multiple folders

**Comment by Bannz** [comment]
no you cant.. but you can multiple folders..

**Comment by andrew1135** [comment]
ok, thanks

**Comment by whatstheyolk** [comment]
does anyone know how to sign in with a google account?

**Comment by Aneduna** [comment]
@whatstheyolk look into wiki or ask on discord?
