### ISSUE TITLE
Romanian language missing from the update/release package

### ISSUE THREAD

**Issue by cristisilaghi** [NECROBOTIO/NecroBot#2875]
Look at the latest version (v0.7.2), file "translation.ro.json" is not included even if the file exists on Github. Do we miss something?

**Comment by Zubinexu** [comment]
Da domnule lipseste.

**Comment by cristisilaghi** [comment]
You can close this, this PR should fix the problem: https://github.com/NECROBOTIO/NecroBot/pull/2895
