### ISSUE TITLE
Bot not ignoring pokemon filling me up with pidgeys and rattatas

### ISSUE THREAD

**Issue by RiPPERD** [NECROBOTIO/NecroBot#2876]
as title says ignore filter not working, any ideas on fix?

**Comment by SDMU** [comment]
set pokemonNotToTransfer to true

**Comment by RELAXccc** [comment]
where is the problem with with pidgeys and rattatas? Set pidgeys and rattatas to evolve -> Free EXP

**Comment by SDMU** [comment]
sorry i meant this
 "UsePokemonToNotCatchFilter": false,

set this to true

**Comment by RiPPERD** [comment]
thanks for ya help... been suing this for a while now but it keeps getting new features and i cant keep up lol

set it to true now... RELAXccc im not looking for exp im looking for all the pokemon lol... gotta catch em all remember not catch 100x pidgys and rats lol
