### ISSUE TITLE
Error when upgrade to 0.7.2

### ISSUE THREAD

**Issue by soulbeaster** [NECROBOTIO/NecroBot#2880]
After autoupdate, i got no exe found
![image](https://cloud.githubusercontent.com/assets/20718422/17464045/658049be-5cff-11e6-9e34-a95f5125447a.png)

**Comment by TheMaskedMonkey** [comment]
Had the same issue. Just redownload and copy all files except the config folder (if you want to keep your config)

**Comment by RELAXccc** [comment]
start the `NecroBot.vhost.exe`

**Comment by soulbeaster** [comment]
@RELAXccc not work bro, better download release file 0.7.2 directly like @TheMaskedMonkey say. and it WORK NOW :)

**Comment by MadeBySaints** [comment]
this issue has already been addressed #2864

**Comment by soulbeaster** [comment]
thanks, issue close :)
