### ISSUE TITLE
Traslation issue

### ISSUE THREAD

**Issue by chavacf4** [NECROBOTIO/NecroBot#2882]
error fatal  :c

**Comment by somani6** [comment]
#2805

**Comment by Jameslaos** [comment]
delete all the translation files, that worked for me.

**Comment by xReMuSx** [comment]
Or you can just copy the config.json from v0.7.1 and set "TranslationLanguageCode": "en"

**Comment by joerigh** [comment]
but i love to use my mother language
lol
