### ISSUE TITLE
update v0.7.2  snipe dont work

### ISSUE THREAD

**Issue by amp33** [NECROBOTIO/NecroBot#2884]
the last update snipe pokemon dont work anymore

**Comment by xReMuSx** [comment]
Mine is working fine but only with pokesnipers

**Comment by amp33** [comment]
i have pogolocationfeeder

**Comment by GummiBoat** [comment]
Working fine, changed nothing sniping-related in the config.

**Comment by amp33** [comment]
hmmz seems working now

**Comment by Bannz** [comment]
anyone can explain me about pokesniping?

**Comment by GummiBoat** [comment]
It loads the area without actually putting your character there and touches the Pokémon, thus "sniping" it from across the world.

**Comment by Bannz** [comment]
@GummiBoat and how to make it possible in config?

**Comment by SDMU** [comment]
@Bannz  read the wiki

**Comment by Bannz** [comment]
ok.. is it safe?

**Comment by GummiBoat** [comment]
Nothing is safe, that's why you shouldn't use your main account.

**Comment by wetshrimp** [comment]
does it just miss a lot of snipes? like previous versoins

**Comment by Bannz** [comment]
@GummiBoat I've read wiki. but how make it works? I mean step.. .exe running while I change config? or i shut it first?

**Comment by GummiBoat** [comment]
you need to set the config key of "SnipeAtPokestops" or so to true, and then reboot the bot. if you want other sniping locations, get them in the resources-section.

**Comment by DmitrySilchenko** [comment]
Guys please read the Docs!  Sniping works perfect with 0.7.3 right now. Took me 5 minutes to setup following the guide in 'wiki'.  The devs did some amazing job here.

**Comment by marthepusi** [comment]
i've followed every guide i can find on wiki and forum. but i can't make snipe work.
any ideas?
