### ISSUE TITLE
New versions being created under tmp folder during update

### ISSUE THREAD

**Issue by elmaarmut** [NECROBOTIO/NecroBot#2885]
Please fix this. After a few updates, my Necrobot.exe is currently located at 

C:\Users\lenovo\Desktop\\Release\tmp\tmp\Release\tmp\NecroBot.exe

And it is not pretty to look at, or to scroll into :D

Also, not a big fan of the RED escape logs. Orange or something with a less sense of urgency would be nice :)

**Comment by MadeBySaints** [comment]
this has already been addressed here #2864
