### ISSUE TITLE
 "PrioritizeIvOverCp": true,

### ISSUE THREAD

**Issue by AriSrijaya** [NECROBOTIO/NecroBot#2886]
"PrioritizeIvOverCp": true,

not work, my bot transfer 
[00:25:31] Eevee	- CP: 272  IV: 94.40%   [Best CP: 664  IV: 91.55%] (Candies: 505)
[00:25:37] Eevee	- CP: 664  IV: 91.55%   [Best CP: 834  IV: 85.25%] (Candies: 506)
[00:26:23] Venusaur	- CP: 476  IV: 61.48%   [Best CP: 1022  IV: 47.28%] (Candies: 295)
[00:26:32] Venusaur	- CP: 1022  IV: 47.28%   [Best CP: 248  IV: 45.05%] (Candies: 296)

**Comment by SDMU** [comment]
is that your transfer list ?

**Comment by RELAXccc** [comment]
what is your `KeepMinCp` perhaps it cant transfer the other ones?

**Comment by Taranis01** [comment]
is "TransferWeakPokemon": on true?
--> Force Transfer of ALL Pokemon below "KeepMinCp" and "KeepMinIvPercentage"

or is "KeepMinOperator":  on "and" ?

and guys use the fkn discord channel

**Comment by RELAXccc** [comment]
@Taranis01 i think discord is down, atleast i cant join

**Comment by AriSrijaya** [comment]
@sdmu yes 

@RELAXccc  mykeepmincp is 1500

@Taranis01 transferweakpokemon set false brother
and my setting like this on transfer filter for KeepMinOperator
      "KeepMinOperator": "or",
      "MovesOperator": "or"

**Comment by Mikey9191** [comment]
having the same issue

**Comment by Magnaleikha91** [comment]
many of my good pokemon transferred... ToT
