### ISSUE TITLE
0.7.2 breaks login

### ISSUE THREAD

**Issue by spamfighter82** [NECROBOTIO/NecroBot#2887]
{
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "xxxxx",
  "PtcPassword": "xxxxx"
}

(Error) You need to fill out GoogleUsername and GooglePassword in auth.jason

**Comment by GummiBoat** [comment]
Download the official release with the "Download" Button on the readme page.

**Comment by MadeBySaints** [comment]
this has already been addressed, please close

**Comment by hogtrough** [comment]
Still receiving the error...

**Comment by craigbaines** [comment]
trying out the bot for the first time an i just get stuck on the logging in... part
