### ISSUE TITLE
0.7.2 cannot find pokestop again

### ISSUE THREAD

**Issue by thotg** [NECROBOTIO/NecroBot#2888]

**Comment by shaofluff** [comment]
same here, idk.

**Comment by edigmato** [comment]
i just want to say TANK YOU GUYS YOU ARE THE BEST HAKERS IN THE F@#^* WORLD

**Comment by edigmato** [comment]
and the you can solve the issue kipping the 0.7.0 version

**Comment by edigmato** [comment]
in config file set "AutoUpdate": false,
