### ISSUE TITLE
PokeZZ works in Necro?

### ISSUE THREAD

**Issue by CamiloRguez** [NECROBOTIO/NecroBot#2889]
PokeZZ not work for me. I do not know if Necro or PoGoFeed problem.

Thks in advance

**Comment by MadeBySaints** [comment]
if you check pokezz.com, you would know that that service is currently offline.

**Comment by CamiloRguez** [comment]
Its online for me, I've used it all day with PokeSniper 2

**Comment by saahilz** [comment]
the location feeder is not working at the moment , once they have updated location feeder and change it to pokezz it will be all good

**Comment by MadeBySaints** [comment]
@CamiloRguez well then... about a half hour ago that was completely down! lol my apologies for misinformation :) i can confirm the site is working again also

**Comment by Bannz** [comment]
anyone can explain me about pokesnipe?? sorry.. :(

**Comment by MadeBySaints** [comment]
@Bannz you are asking a bunch of general help questions in the issues section of necrobotio, this section is for ISSUES with the bot. not a general help area. If you do some research, chances are, your question has been answered elsewhere.
