### ISSUE TITLE
Not catching pokemons if "No usable PokeStops found in your area."

### ISSUE THREAD

**Issue by jbanaszczyk** [NECROBOTIO/NecroBot#2890]
The case:
I've limited "MaxTravelDistanceInMeters" to very small value: 100,
There constantly exist a few lure modules (at least 3)
Bot travels between them, gets goods from pokestops and catches pokemons. OK.
If all pokestops were, bot does not move (OK), buy does not catch pokemons - WRONG. They exist and can be catched.
Many thanks for your effort :)

**Comment by jbanaszczyk** [comment]
Location: Poland
  "DefaultLatitude": 52.230304,
  "DefaultLongitude": 21.006026,
  "MaxTravelDistanceInMeters": 100,

**Comment by RELAXccc** [comment]
@jbanaszczyk do you have the latest version? This error is associated with the Old (not working) API

**Comment by markuznw** [comment]
@RELAXccc Nope it happens also on 0.7.2 which in my case borked everything up, see previous opened issues :)

**Comment by RELAXccc** [comment]
@markuznw jea.. i got that and deleted my answer :D 
@jbanaszczyk perhaps try a GFX Path to fix temporarry

**Comment by somani6** [comment]
GPX File won't help. if the usable pokestop list is empty, there is no pokemon hunting according to the coding.
