### ISSUE TITLE
KeepPokemonsThatCanEvolve incorrect

### ISSUE THREAD

**Issue by alessandro1989g** [NECROBOTIO/NecroBot#2891]
Hi!
I think KeepPokemonsThatCanEvolve keeps the wrong number of Pokémon to evolve. The correct number should be

numberOfCandiesNeeded = numberOfPokemonToEvolve* (CandiesPerPokemon-2) +2

for example, to evolve 3 pidgey I need 

3*(12-2)+2 = 32 candies

Therefore the correct number of evolvable pokemon should be 

numberOfPokemonToEvolve = (numberOfCandiesNeeded-2)/CandiesPerPokemon

**Comment by minhoolee** [comment]
Why was this issue closed? This is currently a crucial calculation error, especially for configs that farm low candy pokemon like pidgey. Having 500 pidgey candies, with the current algorithm, ends with > 50 candies leftover.
