### ISSUE TITLE
How to read out the correct device values of an android device?

### ISSUE THREAD

**Issue by Superleo1810** [NECROBOTIO/NecroBot#2892]
Hello,
I'm just wondering how to read out all the values of an android device required to spoof another device instead of the OnePlus 2. I can't locate where to find i.e. DeviceModelBoot or FirmwareTags.

**Comment by RELAXccc** [comment]
#2845

**Comment by Haglerd** [comment]
Everyone saying search first and check the wiki, but the wiki didnt show me anything on this. I also looked at the #2845 and it isn't completely accurate either. Specifically around the two values that @Superleo1810  is asking about!

**Comment by pythoneer** [comment]
To change the device information in /Config/auth.json to YOUR personal device, you will need android-sdk with adb (and drivers for your phone). Here are the correlating values with the command to run to grab the value off your phone:
"DeviceId": "", // adb.exe shell settings get secure android_id
"AndroidBoardName": "", // adb.exe shell getprop ro.product.board
"AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader
"DeviceBrand": "", // adb.exe shell getprop ro.product.brand
"DeviceModel": "", // adb.exe shell getprop ro.product.model
"DeviceModelIdentifier": "", // adb.exe shell getprop ro.product.name
"DeviceModelBoot": "qcom",
"HardwareManufacturer": "", // adb.exe shell getprop ro.product.manufacturer
"HardwareModel": "", // adb.exe shell getprop ro.product.model
"FirmwareBrand": "", // adb.exe shell getprop ro.product.name
"FirmwareTags": "", // adb.exe shell getprop ro.build.tags
"FirmwareType": "", // adb.exe shell getprop ro.build.type
"FirmwareFingerprint": "" // adb.exe shell getprop ro.build.fingerprint
