### ISSUE TITLE
No Pokestops found in area regardless of config

### ISSUE THREAD

**Issue by shaofluff** [NECROBOTIO/NecroBot#2893]
I was using 0.7.1 and everything was working great, necrobot was locating pokestops, picking up pokemon, everything, then once it forced me to update to 0.7.2 (because otherwise 0.7.1 no longer logs you in), it is not locating pokestops anymore, but pokefarmer does and the older versions of necrobot, anyone know what's up?

**Comment by harnonsinho** [comment]
same

**Comment by shaofluff** [comment]
"We are back! The bot is back!" Nevermind.

**Comment by Sanskritmp** [comment]
#2863
