### ISSUE TITLE
No .exe in the latest 0.7.2

### ISSUE THREAD

**Issue by centoxe** [NECROBOTIO/NecroBot#2897]
There isn't an .exe to open in the latest version, what should i do, dont want to mess up my config

**Comment by hellnest** [comment]
You can easily unzip the Release.zip.old file to update

**Comment by nekmot** [comment]
take a backup copy of your config.-.-...

**Comment by centoxe** [comment]
I dont have the old release, already deleted it and saved my config, can someone send me a link to it?

**Comment by Sanskritmp** [comment]
Located at tmp folder.
#2863
