### ISSUE TITLE
HIGH CPU USAGE

### ISSUE THREAD

**Issue by eukaristia** [NECROBOTIO/NecroBot#2898]
PLeace check, i use multiple bot, every bot got avarage 20% cpu usage

**Comment by shaofluff** [comment]
That is normal lol

**Comment by Saik19922** [comment]
0.2% each process for me..

**Comment by RELAXccc** [comment]
@eukaristia  @Saik19922 what are your cpus

**Comment by MadeBySaints** [comment]
I'm using currently a core i5-4460 (i know i know...) @ 3.20 GHz and im only seeing a MAX of 0.3% cpu usage for each bot.
