### ISSUE TITLE
won't let me sign in with ptc

### ISSUE THREAD

**Issue by aaron25th** [NECROBOTIO/NecroBot#2899]
even though the config is set for ptc it keeps trying to login with google

**Comment by palmpje94** [comment]
same for me

**Comment by nekmot** [comment]
same :/

**Comment by Nestade** [comment]
same

**Comment by MadeBySaints** [comment]
ptc is a horrible premise anyways :/ niantic should support account linking, so you can use ptc or google for the same account

**Comment by ermismo** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/20890849/17464174/7e4d443c-5cd8-11e6-9f4c-28e7ffe24904.png)
Same problem...

**Comment by xnikolai** [comment]
Had this issue also. What I did to fix it is download the latest Release.zip 0.72 and extracted it to my current directory. It now works fine.

**Comment by nekmot** [comment]
Thanks nikolai, somehow it worked now! +1

**Comment by aaron25th** [comment]
i fixed it by downloading and compiling again they updated the auth file
