### ISSUE TITLE
Stuck at Logging in...

### ISSUE THREAD

**Issue by craigbaines** [NECROBOTIO/NecroBot#2901]
Downloaded the latest compiled release an i get stuck at the 

"Logging in using Google" stage. 

It seems to be doing nothing now ?

**Comment by ydragoo** [comment]
same here stuck in logging  the version 0.7 was working but not any more

**Comment by Cyrus-Wong** [comment]
me too, ver. 0.7.2 stuck at logging in, google account.

**Comment by SDMU** [comment]
close and restart helps ?

**Comment by craigbaines** [comment]
Nope, this is all i get.

![efe1a6d131510ebd665ccea908f79567](https://cloud.githubusercontent.com/assets/9383958/17464191/79ecde3c-5cd0-11e6-83a7-e7c85a693353.png)

**Comment by Cyrus-Wong** [comment]
Thanks @SDMU, now bot is running!!

**Comment by heanforce** [comment]
This happened to me on my vserver after 30 minutes (running 8 clients).
Now I cannot login on my vserver anymore (seems like an ip ban for me).
Because on my local computer everything works fine.

**Comment by craigbaines** [comment]
Im on my local machine, im only trying to use one account, an i have restarted it multiple times :'(

**Comment by craigbaines** [comment]
Ok, now i look dumb, it logged in. Hmm, guess ill close it. Persevere if this happens to you people lol

**Comment by AndreasGilja** [comment]
Hi do u GOT enny god Xp farm cordinatrs or somthing to lvl UPP fast sang Get stat dust ?

Sendt fra min iPhone

Den 7. aug. 2016 kl. 19.56 skrev Cyrus-Wong <notifications@github.com<mailto:notifications@github.com>>:


Thanks @SDMU<https://github.com/SDMU>, now bot is running!!

-

**Comment by birdblue4u2** [comment]
Restart worked for me

**Comment by Asakura235** [comment]
Did u just push the x and restart the bot or restart ur pc?
