### ISSUE TITLE
Logging Error

### ISSUE THREAD

**Issue by Utopik** [NECROBOTIO/NecroBot#2903]
I take this error

![adsiz](https://cloud.githubusercontent.com/assets/20828530/17464190/3c2ac238-5ce1-11e6-8f68-06f463017329.jpg)

**Comment by MadeBySaints** [comment]
this is not a bot issue, its a user issue. do as the red text instructs, and close this issue.

**Comment by Kendama165** [comment]
Same for me even when PTC is chosen.

**Comment by daidai0129** [comment]
Same issue for me.

**Comment by Utopik** [comment]
@MadeBySaints i done already it.

**Comment by ydragoo** [comment]
even for me i have put the user name and passe word in the config folder in the auth.json file and nothing

**Comment by chriszhangz** [comment]
It is the update method issue, just download the latest zip and paste to your folder

**Comment by ermismo** [comment]
Go to config.json change "AutoUpdate" false

**Comment by Zak13** [comment]
^yeah that fixed my issues aswell
