### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by Utopik** [NECROBOTIO/NecroBot#2904]
I take this error

![adsiz](https://cloud.githubusercontent.com/assets/20828530/17464203/9db0ee60-5ce1-11e6-8d54-f39413b51c65.jpg)

**Comment by hellnest** [comment]
just do exactly what it said. Press Y and enter. So the app will rebuild the translation. Please check carefully before report it as error -_-

**Comment by HZH1907** [comment]
change your (translation.XX) file a line from
"Key": "eventPokemonCapture",
to
"Key": "eventPokemonCaptureSuccess",
will make it work
