### ISSUE TITLE
Bot will transfer while attempting to capture

### ISSUE THREAD

**Issue by rsxaeon** [NECROBOTIO/NecroBot#2907]
The bot will (or at least the log makes it appear so) transfer a pokemon while in the middle of catching another one.   As this is not possible to do from the normal app, the behavior could be used by niantic to identify users.  
![image](https://cloud.githubusercontent.com/assets/2752246/17464197/6f247c58-5c9e-11e6-9dee-d5834b20296f.png)

**Comment by MadeBySaints** [comment]
I have noticed this as well - also happens with some evolves ( i have yet to get a screen cap of that )

**Comment by chriszhangz** [comment]
I believe this is the log issue not the bot movement issue cause it always show this before a success catch. That means it happened after a success catch but log it before that.

**Comment by MadeBySaints** [comment]
i wonder if its a security thing? like the bot sees that you missed capturing a pokemon, leaves the battle, does something else to un-softban just in case, then attempts to catch the pokemon again.
