### ISSUE TITLE
Potential Device Text Problem

### ISSUE THREAD

**Issue by KnowJack20** [NECROBOTIO/NecroBot#2909]
1) Thanks for providing this tool!  :smile: 

2) Suggest the NecroBot team reconsider the device text choice:

As a engineer who has dabbled in Android apps, I understand the purpose/need to provide the bot a device identification.    
But;  the choice of using a small clone Android mfg from China (OnePlus) as the device type for bot is bad idea.  In a couple of days, there will be more "OnePlus" bots phoning Naintic severs than the company has every produced and sold in entire world!  Any intelligent person can dig up the annual "devices shipped" report of phones sold by OnePlus.  Be surprised of they do not already have the data as part of app development and marketing.

To make matters even worse, OnePlus is banned in India and sold there with different name, and not sold commonly in USA by any of the top 3 phone companies.  So neither of those locations should have many "OnePlus" devices calling the servers.  In my humble opinion, it is going to be very very easy to regionally find the bot devices using this ID outside of Asia.

Another point for reference:  Do you know that ALL the Android emulators (BlueStacks, Meme, Droid4x, Nox, etc) use Samsung device(s) as spoofed ID?  Even Genymotion has default device profile for a Samsung device installed.  This is because Samsung sells more phones/tablets across the entire world than almost anyone.   I will be changing my device text to Samsung S5/6 with a random device ID to help reduce probability of detection. 

Best luck with project!

**Comment by Zahlii** [comment]
I suggest using sth like this as shipped per default with the bot:
```
@echo off
cd /D %APPDATA%
cd ..
cd Local\Android\sdk\platform-tools
echo "DeviceId": ", 
adb.exe shell settings get secure android_id
echo ","AndroidBoardName": "
adb.exe shell getprop ro.product.board
echo ","AndroidBootloader": "
adb.exe shell getprop ro.boot.bootloader
echo ","DeviceBrand": "
adb.exe shell getprop ro.product.brand
echo ","DeviceModel": "
adb.exe shell getprop ro.product.model
echo ","DeviceModelIdentifier": "
adb.exe shell getprop ro.product.name
echo ","DeviceModelBoot": "qcom",
echo ","HardwareManufacturer": "
adb.exe shell getprop ro.product.manufacturer
echo ","HardwareModel": "
adb.exe shell getprop ro.product.model
echo ","FirmwareBrand": " 
adb.exe shell getprop ro.product.name
echo ","FirmwareTags": "
adb.exe shell getprop ro.build.tags
echo ","FirmwareType": " 
adb.exe shell getprop ro.build.type
echo ","FirmwareFingerprint": "
adb.exe shell getprop ro.build.fingerprint
echo "
pause
```

(not tested and somehow the newliens should be removed too)
