### ISSUE TITLE
error loading translations

### ISSUE THREAD

**Issue by cekdicoba** [NECROBOTIO/NecroBot#2912]
i change translation to id but fatal error..
![error](https://cloud.githubusercontent.com/assets/20890850/17464232/49b2f4a2-5d04-11e6-8343-591823b95090.png)

**Comment by hellnest** [comment]
Press Y and enter. Coba Dulu

**Comment by cekdicoba** [comment]
jadi tapi ya balik ke english,

**Comment by HZH1907** [comment]
change your (translation.XX) file a line from
"Key": "eventPokemonCapture",
to
"Key": "eventPokemonCaptureSuccess",
will make it work

**Comment by cekdicoba** [comment]
ok fix, thanks
