### ISSUE TITLE
Transfrer not following my rules

### ISSUE THREAD

**Issue by Mikey9191** [NECROBOTIO/NecroBot#2916]
i set the minimum iv to 80, minumim cp to 1300, the operator is or and the priority to iv, transfer weak pokemon is false. it is STILL transferring pokemon abover 80 iv. what to do from here?

**Comment by SDMU** [comment]
set prioritzeIvOverCp to true

**Comment by SDMU** [comment]
is keep minimum operator set to 'and' ?

**Comment by Mikey9191** [comment]
no, because i wanna keep any pokemon above 80 OR above 1300CP, isn't that how it works?

**Comment by Magnaleikha91** [comment]
I also edited D:\Pokemon GO\NecroBot-master\PoGo.NecroBot.Logic/Settings.cs like yours, and failed. We edited the same file, didn't we?

**Comment by Mikey9191** [comment]
no i am talking about the config.json file

**Comment by ChemiHatake** [comment]
what is  "KeepMinDuplicatePokemon" set to?

**Comment by Mikey9191** [comment]
it is set to 1, i think that is the problem then, didn't think of that

**Comment by Mikey9191** [comment]
wait, even if it is set to one, shouldn't it still not transfer pokemon that falls under my keep category?

**Comment by Mikey9191** [comment]
if found the problem, the bot will follow the rules of the individual pokemon transfer filter first THEN the global setting.
