### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dkhodaba** [NECROBOTIO/NecroBot#2923]
Can we add the different types of Pokeballs, Potions and Revives into the Item Recycle Filter? (e.g. itemMaxPotion, itemHyperPotion, itemPotion, itemRevive, itemMaxRevive, itemPokeball, ItemUltraBall, ItemGreatBall)

I thought I remembered these Key/Value pairs being in Settings.cs in an older version, but I haven't seen them in the updates since the API was fixed.

**Comment by Saiteik** [comment]
Hello,

There is a new intelligent method for recycling which basically does the following:

Total to keep - ex: 200

It will begin recycling the weakest pokeballs until you eventually end up with the max amount of balls you want to keep as either greatballs or ultraballs only. This also applied to the potions, berries, and revives.

**Comment by dkhodaba** [comment]
Okay. Thank you for the answer. I kind of miss the line item level control, but this is nearly as good.
