### ISSUE TITLE
Necrobot versions .70 through .72 tell me I need to fill out auth.json if I don't complete the tutorial setup

### ISSUE THREAD

**Issue by averes2** [NECROBOTIO/NecroBot#2924]
If I do complete the tutorial setup it hangs at logging into google.

**Comment by proesd** [comment]
Just fresh install it..

**Comment by averes2** [comment]
I have fresh installed versions .70 and .71 and this is the same problem

**Comment by deadman96385** [comment]
Do you have 2 factor auth on your google? Currently Necro does not support it

**Comment by proesd** [comment]
I mean fresh install 0.7.2 as well

**Comment by averes2** [comment]
The issue was with versions .70 and .71, thanks, .72 worked :)

**Comment by proesd** [comment]
and close this issues

**Comment by wetshrimp** [comment]
google never worked for me ever since new api
