### ISSUE TITLE
"KeepMinCp" not working

### ISSUE THREAD

**Issue by clansman000** [NECROBOTIO/NecroBot#2928]
With this configuration I can keep the higher IV pokemon. 
All the other pokemon of the same type will be transfered, ignoring KeepMinCp value.

 "KeepMinCp": 2000,
  "KeepMinIvPercentage": 98.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

![sold](https://cloud.githubusercontent.com/assets/11960643/17464374/fddb9524-5cdc-11e6-9138-6ef5898b2d13.png)

**Comment by Caydenz** [comment]
Check the entire configuration file. Snorlax has it's own settings in there.

**Comment by Shirajuki** [comment]
You have thin on true: ["PrioritizeIvOverCp": true,]

**Comment by Saiteik** [comment]
The logic here is the "or" I can clearly see you have a 98% perfect snorlax which takes precedence over the  2240 and 2230 Snorlax because you specified in your config to prioritize IV over CP

**Comment by Mikey9191** [comment]
@Saiteik if it is set to or, shouldn't the logic be "keep min xx IV OR keep min xx CP" ??

**Comment by Caydenz** [comment]
KeepMinOperator is set to "or". This mean it will keep any Snorlax that has over 2000 cp OR over 98 IV.

**Comment by Mikey9191** [comment]
yes exactly

**Comment by Mikey9191** [comment]
@Caydenz Does  individual pokemon tranfer settings at the bottm take precedence over the main transfer settings?

**Comment by Caydenz** [comment]
@Mikey9191 yes, they do. The individual settings have a higher priority than the global settings.

**Comment by Mikey9191** [comment]
@Caydenz Thank you, i was not paying attention to that

**Comment by clansman000** [comment]
ok, problem found :)
    
"Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

**Comment by clansman000** [comment]
Thanks :)
