### ISSUE TITLE
Translations don't working

### ISSUE THREAD

**Issue by Spofff** [NECROBOTIO/NecroBot#2929]
![image](https://cloud.githubusercontent.com/assets/16848732/17464402/25a5db1a-5cb4-11e6-9efe-f050a70517a6.png)

**Comment by Spofff** [comment]
obs: version  0.7.2

**Comment by Pouncer123** [comment]
change your (translation.XX) file a line from
"Key": "eventPokemonCapture",
to
"Key": "eventPokemonCaptureSuccess",
will make it work

**Comment by Spofff** [comment]
Thank you !

**Comment by master2014** [comment]
where do i change (translation.XX) file a line from
"Key": "eventPokemonCapture",
to
"Key": "eventPokemonCaptureSuccess",

**Comment by HZH1907** [comment]
@master2014 
path: 
config/Translations/translation.xx

**Comment by master2014** [comment]
[image: Inline afbeelding 1]

2016-08-07 20:51 GMT+02:00 HZH1907 <notifications@github.com>:
