### ISSUE TITLE
210xp

### ISSUE THREAD

**Issue by Colkkill** [NECROBOTIO/NecroBot#2930]
When a pokemon is captured it appears that you gain 210xp instead of the maximum of 110. Is this a real value?

**Comment by gallantdon** [comment]
That is an excellent throw with a curveball, it's a real value

**Comment by kompressor96** [comment]
exactly, 
excellent throw +100 xp
curve ball +10 xp

total: 210 xp

**Comment by Colkkill** [comment]
I was under the impression they took away the bonus for nice great and excellent
