### ISSUE TITLE
Location problem?!

### ISSUE THREAD

**Issue by Chocopasta** [NECROBOTIO/NecroBot#2935]
So I was running the bot and everything was working, I closed it for a while, got back and started it up again, and it said there was an update, so I updated it. After the update the .exe file was gone, and I was not able to start the program anymore. I redownloaded it 8 times now (the updated version aswell as 1 version before the update) and by all versions I got this weird error.. Even with the versions that worked before updating it. I have my coords set for Central Park (well I had that, not sure if it saved it since the config is not there anymore). 

Please tell me how to fix this, thanks!! :)
![necrobot problem](https://cloud.githubusercontent.com/assets/20891353/17464461/a2a3653a-5cdf-11e6-89b4-4c1d62ea84ef.png)

And after this popping up on the program I get a windows notification that the app or program was not responding anymore, and all I can do is close the necrobot again. The auth and cofigs are not showing up neither.

**Comment by Saiteik** [comment]
There are numerous post for this issue already, please wait for the devs to review and update accordingly.

**Comment by Chocopasta** [comment]
Ahh, okay. Thanks for the response anyway! :)! I'll delete my post.

**Comment by Chuuck64** [comment]
#2863
