### ISSUE TITLE
Potential Softban

### ISSUE THREAD

**Issue by khai89** [NECROBOTIO/NecroBot#2936]
Hello, I use a different starting coordinate from my device after 3 minutes. After about 5 minutes of running the bot, i get the message "looting failed, potential softban." "Unban now" then with a countdown. Help me , anyone?

**Comment by proesd** [comment]
just let the countdown, and you will get looting

**Comment by khai89** [comment]
Are you sure I won't be ban?

**Comment by khai89** [comment]
@proesd

**Comment by kaidesu2390** [comment]
Common issue, only soft

**Comment by khai89** [comment]
Am i supposed to log out from my device if i want to use the bot?

**Comment by scati** [comment]
just turn off your gps on your device, and you will be fine
