### ISSUE TITLE
Mass of Red Errors after using for hours.

### ISSUE THREAD

**Issue by HobbitCraft** [NECROBOTIO/NecroBot#2938]
[https://gyazo.com/0b013c58f5778e33c1b7ece72f56fcce](url) Working fine for multiple hours then had a mass of red errors. Not a coding master so had no clue where to start! Help!

**Comment by Willovent** [comment]
The google map api key has arrived at his limit. This is why

**Comment by baomx888** [comment]
how can I solve googl map api problem?

**Comment by kompressor96** [comment]
restart your modem

**Comment by MrProblematic** [comment]
same here..

**Comment by carminaburana123** [comment]
This is the error i get

```
Parameternaam: value
   bij Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   bij Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   bij PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:regel 36
   bij PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:regel 65
   bij PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:regel 42
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:regel 82
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:regel 66
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 36
[20:48:24] (INFO) Logging in using Google
```

**Comment by PewSztiePoll** [comment]
[21:53:15] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

Same here

**Comment by itz420anytime** [comment]
restarting my modem didnt do anything think they changed the api again?

**Comment by Caliboss** [comment]
ran for about 30min then i got same message, kept relogging my accounts.. gonna get softbanned that way

**Comment by DagooNn** [comment]
same here

**Comment by askovpen** [comment]
same

**Comment by zno3** [comment]
does this related to altitude?

**Comment by DagooNn** [comment]
+all time problem with translation

**Comment by lucbas** [comment]
@zno3 yes

https://developers.google.com/maps/documentation/elevation/start

**Comment by Sheetka** [comment]
same here, dunno if its because of 1.7.2 if someone can confirm its happening with 1,7,1 well thatd be great

**Comment by jessewhite007** [comment]
Looks like google maps api (the one being used by the bot for altitude) has a limit of 2500 calls per day
https://developers.google.com/maps/documentation/geocoding/usage-limits

**Comment by jessewhite007** [comment]
There isn't really a way around that if you continue using google for altitude. I'll dig around for other altitude api alternatives

**Comment by Caliboss** [comment]
lol.. dam so should i use my own city? im in San Francisco on bot

**Comment by lucbas** [comment]
With v0.7.2 the elevation gets calculated for each movement so that "real" information is sent.
0.7.1 does not dynamically send the elevation and currently still works.

**Comment by jessewhite007** [comment]
probably a good idea to build a hashmap for the lat / long to altitude so we don't have to query the api every time

**Comment by itz420anytime** [comment]
if i downloaded 7.2 how do i get back to 7.1 i downloaded 7.1 again and when i say no to the update it just closes

**Comment by Sheetka** [comment]
can we disable this feature for now? in 1.7.2

**Comment by askovpen** [comment]
```
{
   "error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}
```
suggest add gmaps api key in auth.json

**Comment by lucbas** [comment]
@itz420anytime go into the config and set auto-update to false

**Comment by itz420anytime** [comment]
thanks lucbas

**Comment by Sheetka** [comment]
Im starting up bots one by one now and it seems to work like that, but if I mass activate them all I instantly get these red errors

**Comment by zno3** [comment]
or maybe using gpx route? is that include altitude?

**Comment by mavericknick** [comment]
@zno3 No, GPX routes have only lat and long IIRC.

**Comment by claudionores** [comment]
guys i ran it for the first time now and got a lot of red errors after some minutes of running.
when i repaste de files the problem keeps going, and after i skiped the prompt setup with a "N" and set up the auth.json and config.json by myself the problem was solved. Try this on yours.

**Comment by MrProblematic** [comment]
so, there's no way to disable dynamic altitude? Should i w8 a new exec release? XD

**Comment by zno3** [comment]
hmm only able to find elevation on gpx file, maybe convert altitude to elevation?

**Comment by centoxe** [comment]
I can confirm 0.7.0 is workking flawlessly you should just use this until 0.7.2 is fixed
download it here
https://github.com/NECROBOTIO/NecroBot/releases

**Comment by claudionores** [comment]
is there any way to make necrobot skip autoupdates?

**Comment by centoxe** [comment]
yeah when you download the 0.7.0 release just set it up as usual, it will ask if you want to update put it as no, after its done setting up go into auth.json and set auto updates to false

**Comment by claudionores** [comment]
cool, thanks ^^

**Comment by MrProblematic** [comment]
Im running 0.71 now.. working fine! thx @centoxe

**Comment by centoxe** [comment]
@MrProblematic No problem, there will be an update soon i hope

**Comment by DLHC** [comment]
Im running 0.70 and say no to update

yes it show "Logging in use ptc", and i wait and wait and wait and wait and wait and wait and wait and it close.

i open NecroBot.exe again, say no to update, but it showsup "fill in google acc and password" again, and it close...
