### ISSUE TITLE
[Request] PokemonTo : UseUltraball + ExcellentThrow + CurveThrow + Berries

### ISSUE THREAD

**Issue by tada41** [NECROBOTIO/NecroBot#2943]
In the wait of the Master ball, the following suggestions of lists options can be useful for the rare Pokemons : 

- PokemonToUseUltraball (List)
- PokemonToDoExcellentThrow (List) 
- PokemonToDoCurveThrow (List) 
- PokemonToUseBerries (List)

**Comment by Bitzz** [comment]
I love this too.
