### ISSUE TITLE
download

### ISSUE THREAD

**Issue by Cixxz** [NECROBOTIO/NecroBot#2946]
Cant download new bot

**Comment by AxiomCro** [comment]
I just downloaded it and it works fine, you need to describe your issue with a few more details so we can try to help.

**Comment by Cixxz** [comment]
i clicked on the new bot to download and does nothing

**Comment by kompressor96** [comment]
just go to the page https://github.com/NECROBOTIO/NecroBot/releases/ 

and click release.zip of the version 0.7.1, because the last version has a problem with altitude google requests

**Comment by Cixxz** [comment]
thx
