### ISSUE TITLE
GPX Pathing Issue

### ISSUE THREAD

**Issue by AppleXInno** [NECROBOTIO/NecroBot#2947]
Hello, im new here and im not a computer genius but im having issue with gpx path.

i download the pre-made gpx path and put both into the main folder and when i try to run the bot i got an error:

**[02:49:39] () JSON Exception: Invalid JavaScript property identifier character: .. Path 'DefaultLatitude', line 18, position 31.
[02:49:39] () Exceptiion caught, writing LogBuffer.**

and this is the current setup:

**"DefaultLatitude": -37,757896.0,
  "DefaultLongitude": 145,3525110.0,
  "WalkingSpeedInKilometerPerHour": 25.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": true,
  "GpxFile": "Lilydale2_withStops_Comma.gpx",**

So i do some research and it says by removing , from the coordinate will work so i did and yet i got another error:

**[02:51:18] () Exceptiion caught, writing LogBuffer.
Unhandled Exception: System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90**

and this is the setup:

**"DefaultLatitude": -37757896.0,
  "DefaultLongitude": 1453525110.0,
  "WalkingSpeedInKilometerPerHour": 25.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": true,
  "GpxFile": "Lilydale2_withStops_Comma.gpx",**

I try with comma also period gpx with , and . coordinate both give me same error.

anyone can help me solve this problem?

**Comment by langit7** [comment]
"DefaultLatitude": -37.757896,
"DefaultLongitude": 145.3525110,
