### ISSUE TITLE
Transfer IV/CP for duplicate pokemon

### ISSUE THREAD

**Issue by Artixia** [NECROBOTIO/NecroBot#2952]
Hi,

For exemple i catch a Drowzee : CP 570 and 46% and the max is : CP 368 and 100%.
The problem is that the bot transfer the CP 570 and not the 368, why ? What parameter ?

Thanks

**Comment by langit7** [comment]
"PrioritizeIvOverCp": true, ..

**Comment by anillulla10** [comment]
I am having same problem, my PrioritizeIvOverCp is false

**Comment by Artixia** [comment]
Me too, PrioritizeIvOverCp is false. help ?
