### ISSUE TITLE
can't use lat and long

### ISSUE THREAD

**Issue by davird** [NECROBOTIO/NecroBot#2953]
can't use Brisbane's lat and long. error pops saying pls input only values
-27.469771, 153.025124

**Comment by kompressor96** [comment]
edit them on the config file, it's easier

**Comment by davird** [comment]
tried that. bunch of red errors appear when i start necro after that.

**Comment by kompressor96** [comment]
if you write here what type of error appears we can help you

**Comment by davird** [comment]
bunch or red lines and app crashes (closes). log shows this - [ERROR] Please input only a VALUE for example: 40.778915
