### ISSUE TITLE
AuthType PTC tries to login with Google - Please mark as fixed

### ISSUE THREAD

**Issue by gummozz** [NECROBOTIO/NecroBot#2954]
**EDIT: Found a solution that worked for my problem. Fresh install of 7.2.

Start the bot for the first time and select "NO" for the first time setup - this generates a completelyu different Auth.json - wich if filled out manually works just fine. I'm guessing the issue lies in the "First time setup" failing to fill in all the required data.**

After the recent 7.2 update I was introduced to some problems.

Even though "AuthType" is set to "ptc", the bot says "logging in with Google" (changing the AuthType to google does not reverse this). It failes to sign in and says that "you need to fill in google login".

If I fill it out with jibbrish the same problem occurs. I have done several fresh installs, and also tried to go back to 7.0 and 7.1 - both showing the same issue.

Log is in Swedish: Please note that I have tried to update the client this way aswell - same issue.

Initializing NecroBot logger at time 8/7/2016 8:52:04 PM...
Initializing NecroBot logger at time 8/7/2016 8:52:56 PM...
[20:52:56] New update detected, would you like to update? Y/N
[20:52:58] Update Skipped
[20:52:58] Loggar in med Google
[20:52:58] Du kommer att behöva ange Google-användarnamn och Google-lösenord i filen auth.json

**Comment by kompressor96** [comment]
disable autoupdate
