### ISSUE TITLE
Not sniping for dragonair?

### ISSUE THREAD

**Issue by AriesDm** [NECROBOTIO/NecroBot#2958]
Hi, is there anything that I miss out on the config? It seems like my bot is not catching any Dragonair or dragonite. Please help!

**Comment by kompressor96** [comment]
just give it time. sniping may be not easy to every pokemon

**Comment by Nibiru92gr** [comment]
Also check if in config file its like that 

`   "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
	  "dratini",
	  "dragonair",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },`

**Comment by AriesDm** [comment]
Thanks guys! problem solved!!!!
