### ISSUE TITLE
A lot Of red Stuff in French Error

### ISSUE THREAD

**Issue by jawad90** [NECROBOTIO/NecroBot#2961]
[20:04:06] Traveling to Pokestop: The Metropolitan Club (23m) (5 seconds)
[20:04:06] System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : value
   à Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   à Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   à PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:ligne 36
   à PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:ligne 65
   à PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:ligne 42
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 82
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:ligne 66
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 36

**Comment by anton101101** [comment]
Also getting these errors.

**Comment by kompressor96** [comment]
use the version 0.7.0 with autoupdate false in the config file

**Comment by Tomasz365** [comment]
Did you use autoupdate? I experienced the same error (with English language), but after "clean install" the exception does not appear again.

**Comment by Nibiru92gr** [comment]
These errors come from version 7.2 where google api is used for altitude to make bot more realistic. They will fix it in an  incoming version

**Comment by jawad90** [comment]
yep but its working now after doing what @kompressor96 said

**Comment by s-p-c** [comment]
May be it is related to https://developers.google.com/maps/documentation/elevation/usage-limits.
