### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by HyperXcloud** [NECROBOTIO/NecroBot#2963]
I have been trying to find good configs for the necrobot bot but the problem is that I cant find any good and working necrobot configs for rare pokemon sniping and pokestops. Is there some that this website can direct me too or can someone please send me a config that suits my description? Thank you for your time!

**Comment by Nibiru92gr** [comment]
http://pastebin.com/u/drz3244 download 7.0 and if u got error with googlemail get in config and put false on autoupdate.

**Comment by saahilz** [comment]
just use location feeder and edit the config
