### ISSUE TITLE
No Snipe

### ISSUE THREAD

**Issue by kairasdream** [NECROBOTIO/NecroBot#2967]
Sniping is not working.
This is my config:

  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,

**Comment by Nibiru92gr** [comment]
Use this link
http://pastebin.com/u/drz3244

setup following the guide. If it asks when you execute google account things just disable autoupdate.

**Comment by facinick** [comment]
same here.

**Comment by kairasdream** [comment]
[22:14:53] (ERROR) The connection to the sniping location server was lost.

**Comment by facinick** [comment]
ITS working now

**Comment by facinick** [comment]
restart
