### ISSUE TITLE
7.2 - error direct after start

### ISSUE THREAD

**Issue by Tim1975** [NECROBOTIO/NecroBot#2970]
![zwischenablage-2](https://cloud.githubusercontent.com/assets/20778677/17464658/7f325af2-5ce4-11e6-89b2-46446c8c277d.jpg)
I get this direct after starting the bot.

**Comment by AnatolySamoilenko** [comment]
the same for me

**Comment by GitClucked** [comment]
Same here. Posting in case others have the same issue.
