### ISSUE TITLE
Bug - Red Text

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2972]
![](http://i.imgur.com/UQObwDD.png)

**Comment by centoxe** [comment]
Common error in 0.7.2 Use 0.7.1 instead, it works flawlessly
download it here https://github.com/NECROBOTIO/NecroBot/releases

**Comment by PewSztiePoll** [comment]
use 0.7.0 version instead.

**Comment by s0niez** [comment]
i use old version but it say fill out google name , i filled it but cant run this app
