### ISSUE TITLE
Google Maps API OVER_QUERY_LIMIT when finding out altitude

### ISSUE THREAD

**Issue by ArcanumSK** [NECROBOTIO/NecroBot#2973]
```
{
   "error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}
```

https://github.com/NECROBOTIO/NecroBot/blob/master/PoGo.NecroBot.Logic/Utils/LocationUtils.cs#L34-L36

**Comment by jamie2016-1** [comment]
Theres not much you can do about this, the max you can call is 2500 times for free.

**Comment by ChemiHatake** [comment]
it'll be fixed in 0.7.3

**Comment by jamie2016-1** [comment]
You can easily check for the error as follows and return the APIs values elevation or a default which is configurable. See code snippet below

if (!json.Last.ToString().Contains("OVER_QUERY_LIMIT"))
     elevation = (double)json.SelectToken("results[0].elevation");
 else
      elevation = Defaultalt;

**Comment by davedevils** [comment]
i have fix allready in a pull request

**Comment by JustRegisteredToSayThis** [comment]
returning a default on error is probably worse than using a default throughout, you could jump big values.
I think the best might be to have people set up their personal API key when setting up the bot at https://console.developers.google.com/apis/api/elevation_backend/overview

**Comment by Zahlii** [comment]
Wouldn't it be enough to get the altitude for start location and then do a random +- 5% on it? That's just one request per session instead of per event
