### ISSUE TITLE
Remote Server Error

### ISSUE THREAD

**Issue by ersinacar** [NECROBOTIO/NecroBot#2977]
Hi,
I got this error at my first run. There is nothing wrong with my connection or pokemon go servers. I can login into game and play. But the app gives remote server error. Any suggestion ?

![necro](https://cloud.githubusercontent.com/assets/1131655/17464676/66f2bd02-5ced-11e6-8dec-a7a89096b496.png)

**Comment by Jordano3710** [comment]
Yep mines is doing the exact same just happened there idk what it is i would greatly appreciate any suggestions

**Comment by marburger93** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/2974

**Comment by ChemiHatake** [comment]
will be fixed in 0.7.3, revert to 0.7.1 and wait for the new release

**Comment by keremkayseri** [comment]
guys can you help me i dont know how to install i have the old bot so now i downloaded the the update with the first file named pokemon go bot master then i click on it and there are 3 files in it. i clicked on the builds only and pulled them into the old bot file with 32 datas in it. then i click on the old bot (pokemon.go.rocketAPIconsole) but then it says that there is a new update so what do i have to do? sorry for bad english i´m german

**Comment by marburger93** [comment]
@keremkayseri Ich vermute, dass du keine Hilfe für die alte Version bekommst. Es gibt aktuell schon eine neue Version (0.7.3), funktioniert aktuell ohne Probleme. Ich musste jedoch ich die Konfiguration erneut durchführen. Die Übersetzung scheint in der 0.7.3 nicht zu funktionieren, mit "de" ist es noch immer in Englisch.
