### ISSUE TITLE
Error problem 

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#2978]
After 2-3 minutes of using necrobot.exe I got this error plenty of times. Any thoughts?
![1](https://cloud.githubusercontent.com/assets/20891856/17464696/00a3c612-5cee-11e6-96dc-8a2910e97365.jpg)

**Comment by jlelse** [comment]
Same for me just now.

**Comment by egsix** [comment]
I think we must change back to 0.7.1 but how? :/
