### ISSUE TITLE
EXP for Accurate Throw Bonus Should be Completely Removed

### ISSUE THREAD

**Issue by Copoutside** [NECROBOTIO/NecroBot#2980]
As of now, Niantic's official app has a "bug" that has removed catch rate and XP bonuses for throws within the circle. The bot is still rewarding these bonuses, or at least definitely the XP bonuses, which is a dead giveaway for any possible incoming perma'bans.

**Comment by Makozer** [comment]
i dont think that they would search for bots on "this" way ...

**Comment by MadeBySaints** [comment]
if its a "bug" thats causing it niantic will do 1 of 2 things - 1. fix the bug (in which case why would we remove the exp for accurate throw bonuses?) and 2. remove the feature from the game completely. (which they have been known to do already)

**Comment by Copoutside** [comment]
I'm saying that, for the duration of this bug, if it actually is a bug and not a disguise of easily catching modified clients, like bots, for example, the xp bonus from the bot should be removed to hide the fact that's it's an obviously modified client. It can be reintroduced when Niantic reintroduces the bonus, if they do. It can't be that hard for Niantic to be like, "Oh, now let's search this time span for any catches with accompanying accuracy bonuses to see obviously suspicious accounts."

I'm just gonna suggest that it be publicly suggested that settings configurations should have nice, great, and excellent throws be set at 0%, at the very least, for now.
