### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by Fulachs** [NECROBOTIO/NecroBot#2981]
[21:25:22] (ERROR) System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   bei Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 36.
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 65.
   bei PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:Zeile 42.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 82.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 66.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.

**Comment by PewSztiePoll** [comment]
Download 0.7.0 release version of the bot

**Comment by egsix** [comment]
How can download the 0.7.0 version ?

**Comment by PewSztiePoll** [comment]
@egsix [releases](https://github.com/NECROBOTIO/NecroBot/releases)
And set autoupdate setting to false in the config.json

**Comment by egsix** [comment]
@PewSztiePoll  thanks dude

**Comment by centoxe** [comment]
https://github.com/NECROBOTIO/NecroBot/releases
Link for 0.7.0

**Comment by panacuba** [comment]
Im also having this issue and Im using the latest version 0.7.2. I tried deleting all the files and reinstalling, even rebooting my pc, and nothing so far.

**Comment by MatteCarra** [comment]
Same problem with 0.7.2

**Comment by PewSztiePoll** [comment]
@MatteCarra and @panacuba please read my first answer in this thread. You should use 0.7.0 version for now.
