### ISSUE TITLE
Null Value Exception in MoveNext()

### ISSUE THREAD

**Issue by DarkflowNZ** [NECROBOTIO/NecroBot#2986]
[NecroBot-2016-08-08-05.txt](https://github.com/NECROBOTIO/NecroBot/files/405676/NecroBot-2016-08-08-05.txt)
[NecroBot-2016-08-08-06.txt](https://github.com/NECROBOTIO/NecroBot/files/405677/NecroBot-2016-08-08-06.txt)
[NecroBot-2016-08-08-07.txt](https://github.com/NECROBOTIO/NecroBot/files/405678/NecroBot-2016-08-08-07.txt)

The bot was running fine until it attempted to move to a new stop which threw a null value exception. Logs are attached

**Comment by PewSztiePoll** [comment]
[Look for the solution here](https://github.com/NECROBOTIO/NecroBot/issues/2938)

**Comment by DarkflowNZ** [comment]
Thanks dude, too many API calls makes sense. I'll close
