### ISSUE TITLE
Doesn't Snipe Every Pokemon

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#2988]
I have NecroBOT and Location Feeder.
But sometimes Location Feeder says there is a pokemon somewhere and the NecroBOT doesn't snipe it. some pokemons it snipe for and some pokemons it doesn't snipe for.

**Comment by head0r** [comment]
depends on the pkmn you have listed in your config.json.
did you check it? almost at the bottom of the config. NecroBot only snipes the listed ones.

**Comment by ObsessedHacker** [comment]
@head0r Ok, that means that I'll have to type each pokemon there is in this game.
You got a full list of pokemons? Can you give me that from the config file so I just copy-paste?
