### ISSUE TITLE
ArgumentOutOfRangeException error

### ISSUE THREAD

**Issue by powrdash** [NECROBOTIO/NecroBot#2990]
Hi I am having the problem as the picture below. 
Not sure how can I fix it? 

I have tried to use v0.7.0 and set auto update to false , 
but still doesn't work. 

<a href="http://imgur.com/IoYEpYV"><img src="http://i.imgur.com/IoYEpYV.png" title="source: imgur.com" /></a>

**Comment by blupoiz0n** [comment]
im getting this too

**Comment by Mozin0r** [comment]
same

**Comment by Mozin0r** [comment]
i think it's just an update

**Comment by Parry1217** [comment]
if i were to make a giant guess, it would be the progressbar.cs requires a certain width on the console to display.  if you right click on the command prompt window, you can change the defaults, to greater than 71.. i dont know what the value should be but i would imagine 200-300 would do it.
