### ISSUE TITLE
[Feature request] AFK / Log-off timers

### ISSUE THREAD

**Issue by GediminasMasaitis** [NECROBOTIO/NecroBot#2991]
I've been looking at the most successful botting scene - Runescape, and "borrowing" some ideas. One thing they do and we don't is AFK timers / log-off timers. A person doesn't play 24/7, he goes to sleep, takes a break. And even when he's playing he doesn't walk all the time - he sometimes stops on a red light, or goes to a shop to buy a drink, etc.

We should imitate that by short afk periods, as well as long log-off periods. All configurable of course - to go with our zoo of settings.

**Comment by panacuba** [comment]
I like the logic behind this :+1:

**Comment by GediminasMasaitis** [comment]
Why was this issue closed?
