### ISSUE TITLE
[Suggestion] Automatically retrieve real Altitude 

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [NECROBOTIO/NecroBot#2992]
Automatically retrieve real Altitude from Google Maps (or any DB which has long+lat-> alt).

And additionally: Automatically generate missing sensor data (compass, gyro sensor,...)
--> every stuff that is send to the server and missing in the bot, but available in the real application.

**Comment by Psifour** [comment]
This was already done prior to the newest version. https://github.com/NECROBOTIO/NecroBot/commit/30a02149ca0e3d8978509584ecc77195d7153a58 undoes this by setting altitude to a static value of 20 (which is <1/10th of my current and just as wrong for most other users).
