### ISSUE TITLE
No Pokestops In Your Area (Rexburg, Idaho Lat: 43.82097 Lon: -111.786690)

### ISSUE THREAD

**Issue by jc1994jc** [NECROBOTIO/NecroBot#2993]
Had this problem before and the new api fixed it. I used the default location and it only soft banned me. Went to another place and now there's no pokestops. Is this a harder ban? Or a for good ban? Or did they just change the api again?

**Comment by josepy5** [comment]
If you actually pay attention, there are several other topics asking the same thing. Maybe next time before you deicide to make a topic, try reading for once your question might already be answered. Also they are making a fix atm. Its API related.

**Comment by Mozin0r** [comment]
download 0.7.0 version i use it and it work https://github.com/NECROBOTIO/NecroBot/releases

**Comment by jc1994jc** [comment]
All I saw were error messages out the wazoo. None of them mentioned the no pokestops in your area. Btw, update. There's pokestops in downtown OKC but not rexburg idaho. I just moved from there and i know for a fact that there are tons of pokestops there, its a college town.
