### ISSUE TITLE
[bug] transfer pokemon

### ISSUE THREAD

**Issue by Adriskye** [NECROBOTIO/NecroBot#2996]
"TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,

i have like 30 rattatas voltorbs...... and them all like 10-200 cp and dont get transfered

**Comment by panacuba** [comment]
Try a stock config, might help you. And run only one instance. Also a fresh install might help you

**Comment by Mozin0r** [comment]
download 0.7.0 version i use it and it work https://github.com/NECROBOTIO/NecroBot/releases

**Comment by Adriskye** [comment]
Its fresh intaled btw , eventho think they should check it or something

**Comment by jck357** [comment]
I have the same issue.

**Comment by jck357** [comment]
Do you use "UseKeepMinLvl"?

**Comment by Adriskye** [comment]
nop
