### ISSUE TITLE
Cannot SNIPE

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#2997]
SNIPE doesn't work, any thoughts?

**Comment by Caliboss** [comment]
i couldnt get it to work, they say go in discord for advice but.. 0 people there are willing to help.

**Comment by Mozin0r** [comment]
download  0.7.0 version i use it and it work https://github.com/NECROBOTIO/NecroBot/releases

**Comment by egsix** [comment]
@Mozin0r i have it but still snipe doesn't work :/

**Comment by MrProblematic** [comment]
Im using 0.70 and isn't working @Mozin0r

**Comment by Mozin0r** [comment]
are you sure auto update are disable ??

**Comment by egsix** [comment]
Yes

**Comment by projectoffset** [comment]
I'm also using 0.7.0 with a disabled autoupdater. 

I'm currently getting an Internal Server Error (500) for the sniper. Any thoughts? Is the tracker just down?

**Comment by QixinDeng** [comment]
same Error(500)

**Comment by Mozin0r** [comment]
very strange :-/

**Comment by kairasdream** [comment]
I had same issue. Now fixed. Do it like this.
Config:
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,

**Comment by projectoffset** [comment]
Just an update, it seems to be working for me now. I downloaded 0.7.1 and overwrote the necessarily files (my necrobot still says 0.7.0 however)

@kairasdream: mine was already like this and I was still receiving the Internal Server error.

**Comment by egsix** [comment]
@kairasdream  thx a lot! fixed! :+1:

**Comment by kairasdream** [comment]
Your welcome :)
