### ISSUE TITLE
impossible launch bot

### ISSUE THREAD

**Issue by sob555** [NECROBOTIO/NecroBot#3001]
![bug](https://cloud.githubusercontent.com/assets/20892270/17464978/f4dc7246-5cea-11e6-97af-9c62e6849cef.jpg)

I have this problem, have you a solution plz ?

**Comment by panacuba** [comment]
This has been temporarily resolved by downgrading to version 0.7.1

**Comment by progz** [comment]
Or you can upgrade to 0.7.3 now
