### ISSUE TITLE
someone please help with this screenshot.

### ISSUE THREAD

**Issue by waynemasquerade** [NECROBOTIO/NecroBot#3002]
![bot](https://cloud.githubusercontent.com/assets/20892278/17464984/7135bc4e-5d1d-11e6-9cc8-ffd5e202712c.jpg)

**Comment by panacuba** [comment]
downgrade to version 0.7.1. This issue has already been posted.

**Comment by msx752** [comment]
@waynemasquerade 
you dont have to downgrade version,
firstly delete "translations" folder in config file, after that re open bot. (you may delete config.json)

**Comment by MyUncleSam** [comment]
#2973 this is the issue
