### ISSUE TITLE
[Issue]:Higher CP Pokemons are getting transferred 

### ISSUE THREAD

**Issue by anillulla10** [NECROBOTIO/NecroBot#3004]
**[01:40:04] (TRANSFERED) NidoranFemale   - CP: 377  IV: 31.50%   [Best CP: 134  IV: 10.06%] (Candies: 668)
[01:40:07] (TRANSFERED) NidoranFemale   - CP: 134  IV: 10.06%   [Best CP: 38  IV: 94.66%] (Candies: 669)
[01:40:10] (TRANSFERED) Venonat - CP: 14  IV: 91.51%   [Best CP: 269  IV: 62.62%] (Candies: 83)**

This is my transfer log, following are my settings for Keeping and transfering pokemons

"KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 7,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false

Happening with many people, please help

**Comment by shetonaz** [comment]
"KeepMinCp": 1500,
Change 1500 to the value you want to keep the pokemons. Example: 150, so they will keep pokemons from 150cp and above

**Comment by shetonaz** [comment]
Also if you dont want to transfer same pokemon but with different cp make false on this line : "TransferDuplicatePokemon": true,

**Comment by anillulla10** [comment]
KeepMinIVPercentage:100 solved my problem.
