### ISSUE TITLE
Sniping error

### ISSUE THREAD

**Issue by pacioc193** [NECROBOTIO/NecroBot#3007]
I have this problem during sniping, Any help?

![necro](https://cloud.githubusercontent.com/assets/3874577/17465058/fc459948-5cec-11e6-80ce-da4370532b54.PNG)

**Comment by DmitrySilchenko** [comment]
my sniper works actually, but be careful it can snipe too frequent. setup your delay appropriately.
did you use latest 0.7.3 version?
