### ISSUE TITLE
Cannot Launch Bot (Username Incorrect)

### ISSUE THREAD

**Issue by TheGreaper** [NECROBOTIO/NecroBot#3009]
Keeps telling me the username and PW i'm using is incorrect and cannot sign in. Have repeatedly rechecked my info and it is fine. Not sure how to fix.

**Comment by shetonaz** [comment]
downgrade to 0.7.1 try to login without your last config files, and run bot as administrator, that helped me. After you login when put back config file from other version.

**Comment by shetonaz** [comment]
Oh and also, make autoupdate in config to false
