### ISSUE TITLE
fill out password in auth.json?

### ISSUE THREAD

**Issue by lilmalossi** [NECROBOTIO/NecroBot#3012]
hi got a problem when i press update no i get this messenge
and it auto closes

Initializing NecroBot logger at time 8/7/2016 10:16:11 PM...
Initializing NecroBot logger at time 8/7/2016 10:19:54 PM...
[22:19:54] New update detected, would you like to update? Y/N
[22:19:56] Update Skipped
[22:19:56] Logging in using Google
[22:19:56] You need to fill out GoogleUsername and GooglePassword in auth.json!

**Comment by CyberChrist777** [comment]
same
![error](https://cloud.githubusercontent.com/assets/20803440/17465080/5b66479c-5cbb-11e6-92f7-6fcbc0852119.png)

**Comment by Aboukaied** [comment]
yes i have the same problem when i downgraded to 0.7.1, although i am 100% sure it says "ptc" as the way to login.

**Comment by lilmalossi** [comment]
thats it !!!

**Comment by shetonaz** [comment]
Make autoupdate in config file to FALSE, when it should work

**Comment by csong5** [comment]
same. Can not login with ptc

**Comment by lilmalossi** [comment]
i cant log in with google

**Comment by lilmalossi** [comment]
dude i love u the auto update to false worked love uuuuuuuuu

**Comment by micro097** [comment]
thank change auto update to false worked

**Comment by Aboukaied** [comment]
yeah it did work now, thanks ! <3

**Comment by lonewolfHQ** [comment]
DONT SKIP UPDATE YOU NUBS, download the 0.7.3, play around with the settings and it works, i downloaded this version put in my old config and it works i have auto update on true.

**Comment by Marsinator** [comment]
I strongly advice to keep updating to the latest version
