### ISSUE TITLE
Snipe works, but NB wont catch sniped pkmn

### ISSUE THREAD

**Issue by head0r** [NECROBOTIO/NecroBot#3014]
Use 0.7.2 and got sniping finally working for me.
My problem is that Necrobot shows me hundreds of sniped pokemon but tries to catch about every 10th.
It seems it ignores them, even theyre listed in my config.

>   "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "UsePokemonSniperFilterOnly": false,

**Comment by Marsinator** [comment]
"UseSnipeLocationServer": false,
put that to true. also activate pokesnipers=true in config.json of pogolocationfeeder

and please do update to 0.7.3
