### ISSUE TITLE
Error after logging, problem with moving

### ISSUE THREAD

**Issue by dematr** [NECROBOTIO/NecroBot#3015]
System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : value
   à Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   à Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   à PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:ligne 36
   à PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:ligne 65
   à PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:ligne 42
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 82
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:ligne 66
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 36

**Comment by soulbeaster** [comment]
here bro #2994

**Comment by dematr** [comment]
already fixed in 0.7.3
