### ISSUE TITLE
This isn't an issue, I didn't know where to post, just wanted to say Thanks!

### ISSUE THREAD

**Issue by slimeon** [NECROBOTIO/NecroBot#3019]
So, I was just about to post about an issue I had with 0.7.2 and when I restarted the bot to check the version of it I got an update. You're working quickly and what you're making is working!
Thanks guys for everything keep up the good work!! :)

**Comment by Marsinator** [comment]
Much appreciated. Come join us in Discord :)

**Comment by inegyzet** [comment]
Your work is awesome! Thank you!
