### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by pacioc193** [NECROBOTIO/NecroBot#3024]
i change the language on the config.json but it doesn't affect the bot language. Is a bug?

**Comment by globus243** [comment]
german language seems seems to be broken since 0.7.3 which language are you trying?

**Comment by pacioc193** [comment]
Italian. The bot automatically replace any language into english. i think bug

**Comment by head0r** [comment]
look at the .jsons in the translations dir. every file is available, but open any of them, it is english translation

**Comment by globus243** [comment]
yeah same for me, there is another issue regarding spanish with the same problem.

**Comment by head0r** [comment]
tried to replace the files woth old ones, but NB rewrites them after startup. marking them read-only will cause an error in the app

**Comment by pacioc193** [comment]
No, i have copy an old correct language file, but the bot automatically overwrite it on the start!

**Comment by Marsinator** [comment]
we are aware of that problem and working on a fix right now.

**Comment by Marsinator** [comment]
#2747

**Comment by ChemiHatake** [comment]
was fixed.
the only languages that won't work right now are: vi, cs and ca.
fixes are going to be implemented soon.
