### ISSUE TITLE
No usable pokestops found in your are!!!

### ISSUE THREAD

**Issue by Abstroos** [NECROBOTIO/NecroBot#3025]
Bot showing error although there are enough pokestops around the area!! Please help.

**Comment by pacioc193** [comment]
Here work very good. Have you set a correct spawn point?

**Comment by Abstroos** [comment]
Do you mean the latitude and longitude??

**Comment by TiermitBier** [comment]
same for me. no pokestops around. my coords and my max distance are fine, im literally in the middle of 3 pokestops..

**Comment by pacioc193** [comment]
Have you got the last version? Have you got the correct auth.json with the new parameter?

**Comment by Abstroos** [comment]
Hey I've tried a a location closeby. It worked.
