### ISSUE TITLE
How do you get the websocket working?

### ISSUE THREAD

**Issue by pokeemerald** [NECROBOTIO/NecroBot#3026]
Hello, I was really happy when I saw an option to enable/disable a websocket in the config file.

Well, I activated it and tried to connect to it, but Chrome only gives me a CONNECTION_RESET Error.

Does anyone know how to get it working?

**Comment by muxahuk** [comment]
just had the same error.. go to config.js open with editor and try to searsh for "websocket" u'll have 2 resoults found.. first one is true/false ( wich u have to make true ), and seccond is port number.
