### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by tanpaulus0605** [NECROBOTIO/NecroBot#3027]
how to setting transfer pokemon just less 1000 CP ?
i do not want to use "KeepMinIvPercentage" and "KeepMinLvl"

**Comment by Marsinator** [comment]
"keepmincp" 1000

**Comment by wakrad** [comment]
you can set 
"KeepMinLvl" to 1
and 
"KeepMinIvPercentage"
to 50

but your pokemon will be full in a hour

**Comment by tanpaulus0605** [comment]
@wakrad thanks
