### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by thepra** [NECROBOTIO/NecroBot#3029]
![bugbug](https://cloud.githubusercontent.com/assets/7032509/17465128/4ac31080-5cef-11e6-8f1b-248f0446c883.PNG)

**Comment by Marsinator** [comment]
are you on 0.7.3?

**Comment by thepra** [comment]
was, yes, now updated to 0.7.5

**Comment by asalazar-pley** [comment]
It just began happening to me, I have deleted all my files and updated to 0.7.6, and keeps happening
<img width="1139" alt="screen shot 2016-08-08 at 11 39 48 am" src="https://cloud.githubusercontent.com/assets/8482108/17491539/e4a60758-5d5c-11e6-90c2-b2c8221de86f.png">

It is only happening for one account but not for the other.

**Comment by asalazar-pley** [comment]
I just stopped it for a while, log in with the actual game, and restarted it about 1hr later, and it is working with no problems again
