### ISSUE TITLE
New Configuration for Keep Duplicate pokemons + Evolve

### ISSUE THREAD

**Issue by Oglass** [NECROBOTIO/NecroBot#3033]
hey,
instead of a static number i suggest u add "As much as u can evolve", boolean configuration.
for example if i have 120 candies of pidgey it will keep 10 pidgeys.

new configuration which means "Evolve untill the end", for pokemons who have 3rd evolve the bot will never upgrade... for example dragonair.

thx for all your hard work!!

**Comment by jck357** [comment]
Another enhancement in keeping duplicate pokemons to evolve is to take the extra candy into account that you get from evolving. (not the transfer) So if you have 122 pidgey candies it will keep 11 pidgeys.
