### ISSUE TITLE
Not preferring IV over CP?

### ISSUE THREAD

**Issue by oxidoex** [NECROBOTIO/NecroBot#3035]
(TRANSFERED) Rhyhorn - CP: 918  IV: 69.98%   [Best CP: 930  IV: 60.75%] (Candies: 36)

**Comment by lonewolfHQ** [comment]
you nob down preffere IV over CP loool it could delete all your high CP pokemons wich you dont want! look trough the logs and put "prefereIvoverCP" on false!

**Comment by oxidoex** [comment]
Can it be conditional that if CP > 1500, prefer CP over IP if a high IV pokemon is caught but is of low level?

**Comment by pacioc193** [comment]
I have same problem! I have it on false!!

**Comment by oxidoex** [comment]
And in my above example, there is no big difference in CP, but IV had a good difference. So I'd say most would prefer IV over CP there.

It would be much helpful if the bot could determine something like the above condition?

**Comment by skupfer** [comment]
Whats your setting for PrioritizeIvOverCp?

**Comment by oxidoex** [comment]
false

**Comment by pacioc193** [comment]
also mine is false.

![image](https://cloud.githubusercontent.com/assets/3874577/17465233/431e0ec2-5cf2-11e6-931e-335c971fba2b.png)

**Comment by oxidoex** [comment]
But as lonewolfHQ mentioned, I don't want to set it 'true' and then lose a 1500 CP pokemon over a 99% IV 100 or less CP pokemon.

**Comment by oxidoex** [comment]
Just an opinion, if the bot knew maximum CP of all pokemons for a given level, couldn't a setting or formula be added depending on that so the bot could compare level and IV , and level and CP for a captured pokemon and decide to keep the most favorable?

**Comment by Marsinator** [comment]
PrioritizeIvOverCp must be true if you want it to keep best iv
