### ISSUE TITLE
KeepMinOperator & KeepMinDuplicatePokemon not working correctly

### ISSUE THREAD

**Issue by Frankkz** [NECROBOTIO/NecroBot#3036]
What should happen:
I only want to keep a pokemon that has at least 75.0% IV and is at least lvl20. If there are none that meet those requirements it should transfer them.
What actually happens:
Instead, it will just keep all above 75% & lvl20, sometimes it even keep those below lvl 20. I'm not sure why that is.

Picture;
http://image.prntscr.com/image/0c3d68e3086f4d7d829e89168e3e1efa.png

Settings;
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 0,
  "KeepMinIvPercentage": 75.0,
  "KeepMinLvl": 20,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,

In the picture you'll see;
2x Nidoran 75%+ IV, lvl20+
4x Zubat 80%+ IV, lvl20+
1x Golbat 93% IV, lvl1
1x Ninetales 77% IV, lvl4

None of these have any special settings on my PokemonTransferList.

My full Config.json can be found here: http://pastebin.com/csdY1VL3

**Comment by Taranis01** [comment]
`"KeepMinOperator": "and",` is only for CP and IV.
that means right now a pokemon needs only to meet one of the requirements.

I dont know if you could call it "Broken" but yes that needs to be enhanced.
`"KeepMinOperator": `"and", needs to be expanded in order to work for all three `"KeepMin..." ` settings (= more possible combinations instead of AND or OR  = 9 Different Options)

**Comment by Frankkz** [comment]
And to add on to that KeepMinCP is a bad value to base yourself on, just to give an example; a lvl30 magikarp has a CP of around 200.
IMO they shoud move away from CP and use MinLvl instead. These are just some quick thoughts so it's possible I'm overlooking other reasons why KeepMinCP would be useful.

**Comment by Marsinator** [comment]
minlevel is already in the config.
