### ISSUE TITLE
Null Exception Thrown

### ISSUE THREAD

**Issue by FallenDev** [NECROBOTIO/NecroBot#3039]
For reference: After 30 minutes of normal operation, Null Reference thrown. 
[error.txt](https://github.com/NECROBOTIO/NecroBot/files/405738/error.txt)

**Comment by Marsinator** [comment]
are you on 0.7.3?

**Comment by FallenDev** [comment]
I used the newest commit, and compiled.

**Comment by FallenDev** [comment]
I'll sync again and give it a go, see there was a new commit about ten minutes ago.

**Comment by Marsinator** [comment]
please get back to us here letting us know about the progress

**Comment by FallenDev** [comment]
Alright, going to give it a go on this version
![capture5](https://cloud.githubusercontent.com/assets/12104989/17465310/dbaac99a-5cc1-11e6-9640-c58603baae94.PNG)

**Comment by FallenDev** [comment]
Seems to be working great, I'll keep you updated if it starts throwing that exception again, when it threw it, and what the bot was doing at the time it threw the exception.

**Comment by FallenDev** [comment]
Update: Has run smoothly for an hour now. Perhaps it was an abnormality? @GrimmGringo @Marsinator I'll keep you both notified if that changes.
