### ISSUE TITLE
Problem on trasnfer pokemon

### ISSUE THREAD

**Issue by pacioc193** [NECROBOTIO/NecroBot#3040]
Is this normal?
![image](https://cloud.githubusercontent.com/assets/3874577/17465192/21863394-5cf1-11e6-9565-43f11fa1b2ab.png)

**Comment by Marsinator** [comment]
yes.
if you want to keep highercp pokemon, put ivovercp to false

**Comment by pacioc193** [comment]
It is already on false, first time that the bot transfer a highter CP.
