### ISSUE TITLE
limited basic and other ball

### ISSUE THREAD

**Issue by sob555** [NECROBOTIO/NecroBot#3041]
Hi, this line is for all ball i think ?

 "TotalAmountOfPokeballsToKeep": 480,

If i want limited basic ball at 50, great ball at 200 and ultra ball illimited, how i can make taht plz ?

Thanks you for your job

**Comment by GummiBoat** [comment]
It will spread evenly for the most useful balls you will receive/need automatically. No need to worry about going empty.

Also, since this is a question and not an issue, please refreain from opening such things in the issues section. There is a public discord where you will receive help.
