### ISSUE TITLE
Confusing, Help Please

### ISSUE THREAD

**Issue by EyesReye** [NECROBOTIO/NecroBot#3042]
Do i have to Change my Device ID Etc etc to my own or a fake one or let it be as it is? 
I want to be "more" safe since it is my highest lvl account.

Thank you,

**Comment by GummiBoat** [comment]
If you want to be safe, use your own. I'm not sure if it matters, but it's not a good idea to use your main account anyways. I have zero problems using the fake one so far though.

**Comment by EyesReye** [comment]
Do i have to change everything or just the Device ID?

**Comment by GummiBoat** [comment]
Everything. There's a more detailed information on the 0.7.2 Release Note.

Also, since this is a question and not an issue, please refreain from opening such things in the issues section. There is a public discord where you will receive help.

**Comment by EyesReye** [comment]
In Discord you get zero help since people are just spamming stuff instead of asking for help.

**Comment by Marsinator** [comment]
I wouldnt call it zero help, the amount of questions is just overwhelming
