### ISSUE TITLE
Having more pokemon than duplicate settings!

### ISSUE THREAD

**Issue by munzuradam** [NECROBOTIO/NecroBot#3053]
Hi,

My settings are very close to the standard. I have  
```
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 2,
```

I have checked all the other settings and modified them but non of those did solve my problem. Which if we come to my problem: I have 8 Electabuzzs, 6 Slowbros and some other duplicate pokemons in my inventory. If you look at the settings you can see it shouldn't be. My transfer filter is empty btw. So after some checking I noticed that all of those pokemons have more than 1250cp so even while they are obvious duplicates they are not being transferred.
I actually have resolve for you too. Basically KeepMinCp and probably the other keepmins are more primary/primal than KeepMinDuplicatePokemon which it shouldn't be. Only thing you have to do is making KeepMinDuplicatePokemon primary, as it should be.

Whatever, I hope this message is not too confusing because it's my third edit and I won't be able to simplify it any longer.

**Comment by skupfer** [comment]
KeepMinCp, Min stands for M I N I M U M ... If your mons are above this threshold, they WONT get transfered

**Comment by munzuradam** [comment]
I got the point after I sent the message as always. But if I wouldn't, I definitely would after reading your memo @skupfer, thanks.
