### ISSUE TITLE
Only catch pokemon

### ISSUE THREAD

**Issue by TheManiac3** [NECROBOTIO/NecroBot#3054]
I only want to catch pokemon through walking or sniping but don't want to farm pokestop because it makes me feel like i am doing all the things so fast than my friends. I don't know where to ask this.. Can anybody guide me for this issue?

**Comment by GummiBoat** [comment]
You will need to get the Pokestops in order to keep your ball-count up. Disable sniping if it is too fast for you and set your walkingspeed down.

Also, please refrain from asking questions in the Issues section on github. There is a public discord, where you will recieve help.
