### ISSUE TITLE
Indenting problem during transfer

### ISSUE THREAD

**Issue by pacioc193** [NECROBOTIO/NecroBot#3059]
This is not a problem but, you can fix in the next release?

![image](https://cloud.githubusercontent.com/assets/3874577/17465341/0f705898-5cf5-11e6-91df-1983f61f1c1c.png)

**Comment by GummiBoat** [comment]
That is completely normal. The bot sorts out your Pokemons by best CP/IV on the first start, or if you caught anything on your own in the meantime. You can disable this in the config, if you don't want that to happen. You will need to set the value of keeping duplicate Pokemons to a higher value.

**Comment by pacioc193** [comment]
This is a problem where Pidgeotto and Raticate is correctly indented. Kakuna nope. It's a graphic things!

**Comment by Taranis01** [comment]
in the future please refrain from asking such questions in the issue tracker. We have a discord channel where you will recieve help.
This tracker is only for reporting confirmed Bugs and Feature Requests. Using it for all other questions will cause important issues to be unnoticed (as it is happening right now)
