### ISSUE TITLE
[ERROR] Error converting value "pokezz.com - API ServiceMaleaintenance"

### ISSUE THREAD

**Issue by soulbeaster** [NECROBOTIO/NecroBot#3060]
![image](https://cloud.githubusercontent.com/assets/20718422/17465350/17b95642-5d1f-11e6-9abd-e95169449e56.png)

Pokezz ERROR or NecroBot ERROR ???

**Comment by pacioc193** [comment]
Also here, maybe a problem on pokezz error?

![image](https://cloud.githubusercontent.com/assets/3874577/17465398/44033af2-5cf6-11e6-847a-157123c699b0.png)

**Comment by soulbeaster** [comment]
@pacioc193 still waiting confirmation, but if u see pokezz website, they still work properly
