### ISSUE TITLE
Sniping error version 0.7.3

### ISSUE THREAD

**Issue by ShallowHacker** [NECROBOTIO/NecroBot#3062]
![error](https://cloud.githubusercontent.com/assets/20712709/17465355/e3621b42-5ca9-11e6-9048-4bfc1fee78ba.png)

**Comment by pacioc193** [comment]
Also on 0.7.4 , maybe a problem of pokezz?

![image](https://cloud.githubusercontent.com/assets/3874577/17465395/2afbdc12-5cf6-11e6-8377-2c1199d086be.png)
