### ISSUE TITLE
how do i setup sniping properly?

### ISSUE THREAD

**Issue by lilmalossi** [NECROBOTIO/NecroBot#3063]
so as the title says how do i set it up properly?

**Comment by Taranis01** [comment]
please ask in the discord channel and don't use the issue tracker for such questions.
This tracker is only for reporting confirmed Bugs and Feature Requests. Using it for all other questions will cause important issues to be unnoticed (as it is happening right now)

**Comment by lilmalossi** [comment]
got a link for me?

**Comment by Taranis01** [comment]
look at the main page of this github repository *rolleyes*

**Comment by noodle-** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Sniping-Setup
