### ISSUE TITLE
auth does not work

### ISSUE THREAD

**Issue by gigi944** [NECROBOTIO/NecroBot#3067]
credentials are insered, but it seems not see them:

![image](https://cloud.githubusercontent.com/assets/17876308/17465389/00f04016-5cf6-11e6-880d-90293da4dda6.png)

**Comment by Aboukaied** [comment]
which version are you using ? incase you are still using 0.7.2, there is a fix for this on the newest patch 0.7.3

**Comment by ViezeVingertjes** [comment]
Disabling auto update seems to fix it...

**Comment by GummiBoat** [comment]
The newest patch is 0.7.4 and it has a broken auto-updater. Disable it in the config, as the pre-poster said, and you should be fine.

**Comment by gigi944** [comment]
thanks all
