### ISSUE TITLE
Always new update v0.7.4

### ISSUE THREAD

**Issue by nevertrustme** [NECROBOTIO/NecroBot#3070]
I take v0.7.4 and necro bot ask me new update detected then i click on yes and i see v0.7.4

**Comment by GummiBoat** [comment]
#3069

**Comment by gigi944** [comment]
same here

**Comment by ObsessedHacker** [comment]
same

**Comment by argaa153** [comment]
same

**Comment by DmitrySilchenko** [comment]
my god, can you people look at current bugs before opening duplicates? please stop opening issue again and again.

**Comment by Greyhair0** [comment]
0.7.5 is out, run necrobot again and update to 0.7.5, everything will be fixed.
