### ISSUE TITLE
Pogo feder non funziona..

### ISSUE THREAD

**Issue by luigidanield2** [NECROBOTIO/NecroBot#3071]
Volevo sapere perche pogo feder non funziona ma funziona solo con pokesnipers cioe vede solo il server di pokesniper perche?? E  i server neceobot.io???grazie siete fantastici veramente geni

**Comment by pacioc193** [comment]
PEnso che la migliore lingua con cui fare domande sia l'inglese. Comunque pogo feder per il momento non è funzionante. Il nuovo bot lavora autonomamente con Pokezz. Lo attivi tramite "config.json". Al momento sembra ci siano dei problemi con Pokezz, vediamo cosa succede.

**Comment by luigidanield2** [comment]
Ok volevo farvi i complimenti siete unici....veramente bravi
