### ISSUE TITLE
Catch selected pokemon only.

### ISSUE THREAD

**Issue by Auraa** [NECROBOTIO/NecroBot#3072]
hi friends, i wanted to catch only **dratini,** is it possible? thank you :)

**Comment by GummiBoat** [comment]
You would need to ignore every other pokemon except for dratini.

Just enable sniping and snipe the location "Latitude": -37.764294491535196,"Longitude": 145.35822987556458

Please refrain from asking future questions in the issues section. There is a public discord, where people will help you.

**Comment by Auraa** [comment]
sorry. i didnt know. can you please give me an example where i can enable? please. thank you.
