### ISSUE TITLE
necrobot.exe keep updating

### ISSUE THREAD

**Issue by argaa153** [NECROBOTIO/NecroBot#3073]
after update 0.7.4 and finished the app just keep detecting the same update

**Comment by ObsessedHacker** [comment]
same

**Comment by jakerxiii** [comment]
Same thing with me :/ Just got it now

**Comment by PassiveModding** [comment]
same for me
cant run if you have ptc now because upon skipping new update it only checks for google auth

**Comment by GummiBoat** [comment]
#3069 

disable auto-update

**Comment by WalkingResurrector** [comment]
Yeah, And all it does is says I have to re-auth and then it closes application, reopens and asks for update!!

**Comment by doness** [comment]
thanks @GummiBoat

**Comment by blackiceiceo** [comment]
how do you disable auto update? And will that fix the problem?

**Comment by Aboukaied** [comment]
@blackiceiceo go to the config file the second line, just write FALSE instead of TRUE

**Comment by pwnyprod** [comment]
[#3069](https://github.com/NECROBOTIO/NecroBot/issues/3069)

disable auto-update -.-

**Comment by progz** [comment]
Fixes in the 0.7.5 !
