### ISSUE TITLE
Update Stuck on 0.74

### ISSUE THREAD

**Issue by Shin88ryu** [NECROBOTIO/NecroBot#3074]
On ver. 0.74 Necrobot stay stuck on "Update Detection". 
If selected yes, it will download update every time.
If selected no, it will crash.

**Comment by doness** [comment]
Same problem

**Comment by GummiBoat** [comment]
#3069 

disable auto-update

**Comment by elmaarmut** [comment]
Indeed, disable auto update. For some reason buggy updates circulate lately, if the new one doesn't work as intended just use the old one (copy a backup of the whole thing before upgrading just in case, every time)

**Comment by iAmObamaCare** [comment]
Unfortunately disabling auto-updates conflicts with the PoGoFeeder


[17:31:54] (ERROR) Error converting value "Pokezz.com - API ServiceMaleaintenance" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[0].name', line 1, position 69.

This is probably one of the reasons for the update.

**Comment by Kirtasher** [comment]
PoGoFeeder working for me, try disabling pokezz

**Comment by EthanBianchi** [comment]
0.7.5 is out, re-download the latest release. The Update loop has been fixed, and authentication errors are gone.
