### ISSUE TITLE
SNIPE ERROR

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#3075]
It was working and now I got this error. Any thoughts?
![1](https://cloud.githubusercontent.com/assets/20891856/17465411/edd5b566-5cfe-11e6-8466-e1e4b95841bc.jpg)

**Comment by GummiBoat** [comment]
Update to 0.7.4, it shouldn't happen anymore.

**Comment by zathrath03** [comment]
Pokezz.com is conduction API ServiceMaintenance. This is not a problem with NecroBot.

See their API json: https://pokezz.com/pokemons.json

**Comment by egsix** [comment]
I updated to 0.7.5 and it's working fine now. Thx anyway both.
