### ISSUE TITLE
Can't connect to pokezz.com for sniping

### ISSUE THREAD

**Issue by NGDALI** [NECROBOTIO/NecroBot#3078]
Whenever it starts sniping I get this:
"Error converting value "Pokezz.com - API ServiceMaleaintenance" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[0].name', line 1, position 69."

**Comment by GitClucked** [comment]
Just got this as well. Lol.

**Comment by GummiBoat** [comment]
Restarting and waiting for an update is the only thing possible to do right now.

#3075

**Comment by jonsnowwatch** [comment]
pokezz is not stable, just leave the bot on for a while it will be okay. Happened to me this morning, and then it went away within an hour

**Comment by BryanSuero** [comment]
PokeZZ is on maintenance...https://pokezz.com/pokemons.json

**Comment by iAmObamaCare** [comment]
Thanks for that @BryanSuero , was waiting for the explanation

**Comment by BryanSuero** [comment]
The only way to get pokemon from PokeZZ is via websocket right now, I can't help with that because I don't have VisualStudio installed

**Comment by zathrath03** [comment]
Pokezz.com is conduction API ServiceMaintenance. This is not a problem with NecroBot.

See their API json: https://pokezz.com/pokemons.json

**Comment by MOBSTERX** [comment]
What configs do i have to turn on just for only sniping with Pokezz.com?

**Comment by zathrath03** [comment]
I use the following. Additionally, inside of PokemonToSnipe near the bottom, delete the lat/long from Locations and make sure the list of pokemon includes the pokemon you want to snipe and only the pokemon you want to snipe.
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": true,
  "SnipePokemonNotInPokedex": true,

**Comment by MOBSTERX** [comment]
Thanks for helping me. :) :+1:

**Comment by zathrath03** [comment]
My pleasure! In the future, the discord chat is the correct place to get help. https://discord.gg/VXKxNFr
