### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#3079]
http://i.imgur.com/0XJC9ux.png

**Comment by daneil1999123** [comment]
u got the newest update 7.5 ?

**Comment by BryanSuero** [comment]
Looks like a JSON problem, use a clean installation.

**Comment by wtttttgg** [comment]
where is the update?

**Comment by BryanSuero** [comment]
All the updates are on "Releases", https://github.com/NECROBOTIO/NecroBot/releases
