### ISSUE TITLE
Add Fav. Pokemon Tranfer ; Disable

### ISSUE THREAD

**Issue by acenoob123** [NECROBOTIO/NecroBot#3081]
plz :dancer:  ty

**Comment by GummiBoat** [comment]
Just put your favorite pokemon in the "PokemonsNotToTransfer" List for now

**Comment by head0r** [comment]
pretty sure that faved pokemons cant be transferred... in game you arent able although

**Comment by acenoob123** [comment]
it doesnt even tranfers low cp/iv of tht pokemonnottotranfer list.
so asked just an suggestion no bot has it :+1:
