### ISSUE TITLE
Forgot "evee" in pokemon

### ISSUE THREAD

**Issue by PokeIdeas** [NECROBOTIO/NecroBot#3082]
i keep trying to set evee as a pokemon to evolve automaticly but it crashes the client

**Comment by ShallowHacker** [comment]
Spell it right then.

**Comment by spamfighter82** [comment]
eevee

**Comment by Taranis01** [comment]
lol

**Comment by ShallowHacker** [comment]
Pretty sure this can be closed.

**Comment by doodlemeat** [comment]
Close please

**Comment by PokeIdeas** [comment]
"Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },

i get an error i can printscreen with this:

 "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
    "eevee"
  ],

**Comment by PokeIdeas** [comment]
pretty sure its that as if i take that "eevee" line out it works.

**Comment by spamfighter82** [comment]
you are missing a , after "rattata"....

**Comment by PokeIdeas** [comment]
<3
