### ISSUE TITLE
MOVES in transfer settings needs syntax or explanation

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#3083]
I see the moves [] but not sure of the syntax.

how much can i keep in the array? is it OR or AND in the array list? etc

EXAMPLE:
[ dragonbreath, hyperbeam]
will this toss any pokemon that doesnt have this exact combo? or does it keep any pokemon that has ANY of these values?

steelwing/hyperbeam kept in that case?

furthermore, what if i want everything but water pulse on vaporeon? how can i write that?
[ watergun, aqua tail, hydropump ] ??

lastly, what's the actual syntax inside the [ ]. do i need quotes, commas, hyphens, certain names, caps, etc

**Comment by GummiBoat** [comment]
You only can have two moves. You should know that, if you play PokemonGo. You can specify which move it needs in order to be kept. I think it is AND by default,as all the other operators.

**Comment by wetshrimp** [comment]
i understand the 2 moves but are we limited to just 2 in the array or does it scan for everything in the array to see if it needs to keep?

ex: [dragonbreath, hyperbeam] (not even sure how to type the moves in there -- proper name, ""s, ??, delimiters)
does that keep dragonites with ONLY dragonbreath AND hyperbeam or ANY dragonbreath / hyperbeam?

like steelwing/hyperbeam -- kept or no ?

hence the need for the syntax/faq

**Comment by spamfighter82** [comment]
he has a point there

**Comment by Seyrenvox** [comment]
this was my issue before API change. so, i assume "MovesOperator" is about correlation between moves in the array.
in your case, it would keep Dragonite with DragonBreath AND HyperBeam. Dragonite with **only** DragonBreath or **only** HyperBeam will be transferred.

**Comment by Taranis01** [comment]
yes ofc MovesOperator is that setting needed

**Comment by wetshrimp** [comment]
alright thanks that solves half of it. now the other half, what's the proper syntax for the moves or movenames? and separated by comma? an example of a working one would help.

another example -- how do i keep all vaporeons that DONT have water pulse (if have water pulse, transfer!)

**Comment by Taranis01** [comment]
`"Moves": ["move1","move2"],`
