### ISSUE TITLE
IVoverCP

### ISSUE THREAD

**Issue by DrCocoKicker** [NECROBOTIO/NecroBot#3087]
My bot is transferring my highest rated pokemon even though i have "PrioritizeIvOverCp": false. set, any way this can be fixed

**Comment by head0r** [comment]
just mark them as favourite

**Comment by Suny2589** [comment]
you should prioritize IV than CP , so it won't transfer biggest IV's but it will transfer CP instead .
`"PrioritizeIvOverCp": true,`
