### ISSUE TITLE
Can't login (google)

### ISSUE THREAD

**Issue by LilDenDen** [NECROBOTIO/NecroBot#3088]
since the update it says i haven't typed in my login info when i have. i have deleted auth and regenerated it multiple times 
                                                                                                                                                  thanks!

**Comment by GummiBoat** [comment]
#3069 

Disabling auto-update seems to fix it.

**Comment by EthanBianchi** [comment]
Double check you're on the newest version. 0.7.5, this release fixed those issues you're experiencing.
May need a clean installation

**Comment by LilDenDen** [comment]
ty for the quick response. ill try both.

**Comment by LilDenDen** [comment]
yep! the new update fixed it! thanks guys!
