### ISSUE TITLE
Pokezz Error 0.7.5

### ISSUE THREAD

**Issue by Shin88ryu** [NECROBOTIO/NecroBot#3090]
Having this error - "Error converting value "Pokezz.com - API ServiceMaleaintenance" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[0].name', line 1, position 69. -

It doesn't appear with 0.73

**Comment by head0r** [comment]
#3078

**Comment by zathrath03** [comment]
Pokezz.com is conduction API ServiceMaintenance. This is not a problem with NecroBot.

See their API json: https://pokezz.com/pokemons.json

**Comment by Shin88ryu** [comment]
So, need to wait until it goes "online" ?
