### ISSUE TITLE
How to keep less pokeballs thn other ones

### ISSUE THREAD

**Issue by STCOZT** [NECROBOTIO/NecroBot#3091]
Ive just coded this lines below but it is not working. Isn't there any way to keep better balls rather than the pokeballs ?
"TotalAmountOfPokeballsToKeep": 40,
  "TotalAmountOfUltraballsToKeep": 95,
  "TotalAmountOfGreatballsToKeep": 55,

**Comment by GummiBoat** [comment]
No, this is not possible right now. The bot will automatically spread your balls evenly. You won't need to worry about going out, or not being able to catch anything.

Also, please refrain from asking questions in the issues section. There is a public discord, where you will recieve help.

**Comment by head0r** [comment]
Bullshit. You can just add the keys to your config.

>   "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPotion",
      "Value": 3
    },
    {
      "Key": "itemRevive",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 22
    },
    {
      "Key": "itemHyperPotion",
      "Value": 25
    },
    {
      "Key": "itemMaxPotion",
      "Value": 30
    },
    {
      "Key": "itemPokeBall",
      "Value": 60
    },
    {
      "Key": "itemGreatBall",
      "Value": 80
    },
    {
      "Key": "itemUltraBall",
      "Value": 80
    },

**Comment by STCOZT** [comment]
thx for the comments i'll try it
