### ISSUE TITLE
[Suggestion] Walking Speed Range

### ISSUE THREAD

**Issue by burntable** [NECROBOTIO/NecroBot#3093]
I'd like to have the option to set the walking speed in a specific range.

Something like:
  "MinWalkingSpeedInKilometerPerHour": 8.8,
  "MaxWalkingSpeedInKilometerPerHour": 18.9,

So the bot changes its speed after every stop withing that range. 
That would help to hatch some eggs and makes it less obvious for any bot detection, I guess.

**Comment by TakRiuto** [comment]
Nice idea!!
