### ISSUE TITLE
Dump File fills all the information into the first Column of each Row

### ISSUE THREAD

**Issue by Chaos2522** [NECROBOTIO/NecroBot#3094]
It doesnt seperate the information into columns, it just pastes everything into the first of each row

A2: Jynx,4,179,100,37,37,PoundFast,DrainingKiss,212,,0,1.359141,49.1376,15,15,15,0.25572,0,0,1469337200200,0,0,0,100Jynx

B2 empty C2 empty...

**Comment by zathrath03** [comment]
It's properly outputting comma separated value (CSV) format. The program you're using to open it isn't parsing the data properly.

**Comment by Chaos2522** [comment]
Im using MS-Excel 2016, and it mashes everything into the first columns :/

**Comment by Chaos2522** [comment]
![screen1](https://cloud.githubusercontent.com/assets/20784936/17465756/7dfbc42c-5d00-11e6-9b8c-4c483b4225e4.png)

**Comment by zathrath03** [comment]
Change the file to a .txt file. This will force Excel to open the file using the Import Text Wizard where you can specify the list separator. Please close this issue and bring the discussion to the support chat in discord: https://discord.gg/VXKxNFr

**Comment by Chaos2522** [comment]
They sent me here, your method works, thanks closed :)
