### ISSUE TITLE
CatchEscpe is missing a bracket and is now red.

### ISSUE THREAD

**Issue by TheMaskedMonkey** [NECROBOTIO/NecroBot#3095]
I've noticed a small change and I'm not sure if this is intentional so correct me if I'm wrong.
I thought I'd make an issue thread since I'm unable to find any other issue reporting this.

Here's an image:
https://i.imgur.com/pqKTmiu.png

**Comment by Ferdi342** [comment]
Yeah, I think it shouldn't be red, maybe an error as you saying

**Comment by elmaarmut** [comment]
It is red, and it is catching a bracket. The red is possibly by design, but not so sure on the missing bracket :P

**Comment by colinodell** [comment]
I agree, red should be reserved for errors.

Perhaps use gray, orange, or yellow instead?
