### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by semperna** [NECROBOTIO/NecroBot#3098]
I already re-installed it around 5 times and it keep saying
<INFO>Logging in using google
in the version 0.7.2 it logged in 2 seconds and now ins't working

**Comment by progz** [comment]
Use latest version 0.7.5 :)

**Comment by semperna** [comment]
i'm using it[http://imgur.com/a/4HJ2v](url)

**Comment by zathrath03** [comment]
Disable Auto Update. There seems to be a bug affecting google logins when Auto Update is true.
