### ISSUE TITLE
stuck at LOGGING IN!

### ISSUE THREAD

**Issue by sjc3419901** [NECROBOTIO/NecroBot#3100]
After update perfect!
I'm stuck at (info) logging in using google almost 1 hour.
It worked this morning I don't know whats going on

**Comment by progz** [comment]
Use latest version 0.7.5

**Comment by kudka10** [comment]
Restart app works for me

**Comment by sjc3419901** [comment]
Yeah it is latest version

**Comment by sjc3419901** [comment]
alright works again ty
