### ISSUE TITLE
Some additional ideas for the bot

### ISSUE THREAD

**Issue by Mitness** [NECROBOTIO/NecroBot#3101]
Sry guys im new here and don't know where the right section is for ideas @_@

my first idea is some more functions for the "UseEggIncubators" section like:

-> "UseAllKindsOfEggs" false/true
---> "Priority2kmEggs" false/true
---> "Priority5kmEggs" false/true
---> "Priority10kmEggs" false/true

and a additional function to show up the top 50/100 IV pokemons in youre team for filtering the best out right after opening the bot and stop after creating table:

->"ShowUpIVTableAtStart" false/true
---> "IVTableAmount50" false/true
---> "IVTableAmount100" false/true

Sorry for might the wrong section @_@

**Comment by GummiBoat** [comment]
It's the right section and those are really nice ideas :)

**Comment by temel38** [comment]
or give the incubator prioritys like; 

"Priority2kmEggs" true/false
"Priority5kmEggs" true/false
"Priority10kmEggs" true/false
