### ISSUE TITLE
How to write Nidoran Male and Female in PokemonsToEvolve list properly?

### ISSUE THREAD

**Issue by arslancharyev31** [NECROBOTIO/NecroBot#3102]
When I add "NidoranMale" or "NidoranFemale" in PokemonsToEvolve list Necro crashes at start up. What's wrong?

**Comment by GummiBoat** [comment]
I think the bot saves it under NidoranM and NidoranF, not sure tho. Will look it up and answer if that's not the case.

**Comment by Seyrenvox** [comment]
NidoranMale, NidoranFemale

**Comment by arslancharyev31** [comment]
>  NidoranM and NidoranF
I tried them too, but Necro still crashes

**Comment by somani6** [comment]
post crashlog and/or your PokemonToEvolve section plz

**Comment by Simpuhl** [comment]
Seems like this is fixed now if you add them this way "nidoranmale" or "nidoranfemale"

**Comment by arslancharyev31** [comment]
Logs:
```[03:15:01] JSON Exception: After parsing a value an unexpected character was encountered: ". Path 'PokemonsToEvolve[0]', line 183, position 4.
[03:15:01] Exceptiion caught, writing LogBuffer.```
But in console it shows NullPointerException.
And config:
  "PokemonsToEvolve": [
    "NidoranMale"
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],

**Comment by 666dsa666** [comment]
I belive you can't use uppercase ;)

**Comment by arslancharyev31** [comment]
Same error with lowercase...

**Comment by somani6** [comment]
you are missing a comma after "NidoranMale",

**Comment by arslancharyev31** [comment]
Oh man... What a shame on me ;) Thx a lot
