### ISSUE TITLE
Use GPX file not working?

### ISSUE THREAD

**Issue by spardadt** [NECROBOTIO/NecroBot#3104]
Noob here but I'm trying to tell the bot to use a gpx file but it seems like it's not working. Anyone knows how to make it work?

**Comment by GummiBoat** [comment]
GPX is not implemented currently. Use the manual sniping.

**Comment by spardadt** [comment]
ah ok thanks for the info

**Comment by KurtKoko** [comment]
I am using the Automatic Location Snipe. And it works perfectly.
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

;) just try it

**Comment by stethekiller** [comment]
Why is GPX not available currently yet?
