### ISSUE TITLE
Evolved without using lucky egg or proper amount

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#3105]
![image](https://cloud.githubusercontent.com/assets/262571/17465581/c944ced4-5caf-11e6-894e-1ee6b9252628.png)

Just started evolving, didnt use my lucky egg and as u can see I should get a few more before it starts but doesnt

**Comment by zorroiscool** [comment]
ive just experienced it myself.

**Comment by GummiBoat** [comment]
Is your config set up correctly?

Also it says "Catch 7 more Pokemon to use a Lucky Egg!". I think those are the seven that you needed in order to activate the next one, if existing.

**Comment by head0r** [comment]
go to the config, look for
     "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

when youve got 225 pkmn it starts evolving.

**Comment by Simpuhl** [comment]
So basically my inventory was almost full so it evolved but my number to use the lucky egg wasn't reached so it didnt use it. I guess I made a mistake

fixed.
