### ISSUE TITLE
Pokestop Items: 0

### ISSUE THREAD

**Issue by Dexter145** [NECROBOTIO/NecroBot#3106]
Since version 0.74 I get the following notification at every Pokestop:

"[00:00:17] (POKESTOP) XP: Babies Having Fun with Fish, Gems: 50, Items: 0"

Why aren't  there any items?

**Comment by centoxe** [comment]
Bag may be full?

**Comment by Dexter145** [comment]
No, bag is not full, I still receive items while leveling up.

**Comment by Dexter145** [comment]
I think my bag is indeed full, but the "RecycleInventoryAtUsagePercentage" is at 90%, so I think the recycling not
