### ISSUE TITLE
HOW TO SNIPE?

### ISSUE THREAD

**Issue by facinick** [NECROBOTIO/NecroBot#3107]
can someone tell how to snipe? using online snipe or run a separate sniping application on windows? and from which website is this sniping pokemons? and what should be config setting to allow sinpe for best results

**Comment by GummiBoat** [comment]
There's a wiki entry for it. Enable "SnipeAtPokestops" and you're pretty much good to go. If you need additional locations, add them yourself.

Please ask future questions on the public discord, not in the issues section.

**Comment by facinick** [comment]
last question, it misses most of the pokemons in pogo feeder, how to make sniping faster?

**Comment by facinick** [comment]
@pacioc193 @GummiBoat  thanks a lot
