### ISSUE TITLE
[Suggestion] Only Power-Up Favorited Pokemon

### ISSUE THREAD

**Issue by Fourhundred57** [NECROBOTIO/NecroBot#3108]
^^^that

This way you could prevent auto-leveling of that 95%IV Pidgeoto you found.

**Comment by Taranis01** [comment]
while the evolved pidgeoto has the best attack values compare to other air pokemon.
just to let you know ;)

**Comment by Fourhundred57** [comment]
:-p

My example stands corrected. That said — I'm sure the core concept is still valid; it's just to give the user more control over the automated evolutions.

But hey, I'm not a coder, so I'll let the smart folks decide if this makes sense to implement.

**Comment by Taranis01** [comment]
I think i would prefer a List were you could specify the Pokemon you want to be upgraded. You are definitely right that there is some control missing
