### ISSUE TITLE
low level pokemon

### ISSUE THREAD

**Issue by ExperienceTesla** [NECROBOTIO/NecroBot#3111]
every time the bot find a pokemon the level is very very low. i'm lvl 20 and i cant find pokemon over 50. this is a new softban or a bot problem? sorry for my bad english

**Comment by GummiBoat** [comment]
Wrong locations, probably. You may want to enable sniping too. The spot i used to farm before the bot released again was only filled with 20-80cp stuff. Sniping improved it alot.

**Comment by ExperienceTesla** [comment]
sorry, i'm a bit noob, how i activate sniping?

**Comment by spamfighter82** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by ExperienceTesla** [comment]
thanks :) issue resolved
