### ISSUE TITLE
Softban 24/7

### ISSUE THREAD

**Issue by Mudisen** [NECROBOTIO/NecroBot#3118]
Hey guys!
First time I am using Necrobot, and it seems like it doesn't work?
It always get stuck at pokestops. 
Then it tries to remove soft ban x/45 * 20 times and still no positive results.
What do I do?
Help me please.

**Comment by GummiBoat** [comment]
Change your Location to somewhere else. And let the soft ban removal run until it's done. Usually shouldn't take more than 45 tries.

**Comment by Mudisen** [comment]
Doesn't work. Tried to change from Japan to Union Square in SF. It tries to run the soft ban removal run so many times. The Necrobot is all Cyan colored. This is the 30th time it's running the soft ban removal run.
Any suggestions?

**Comment by GummiBoat** [comment]
No, sorry. It seems you need to switch accounts. Other users are reporting similar issues, just try not to get softbanned for now, or remove it manually with NOX.
