### ISSUE TITLE
Deviceinfo

### ISSUE THREAD

**Issue by CakeHole83** [NECROBOTIO/NecroBot#3120]
How do you get the DeviceModelBoot from adb? 
Cheers!

**Comment by Simpuhl** [comment]
Was wondering this also, nothing in wiki

**Comment by LordDeimos** [comment]
Because it's under your eyes in front page: https://github.com/NECROBOTIO/NecroBot#this-release-features-automatic-device-id-generation

**Comment by CakeHole83** [comment]
Though it tells us all the other values but not the DeviceModelBoot?

**Comment by DNA64** [comment]
The simplest way to get your device ID is to download "Device ID/Android ID" from the Google Play Store. You can get all the other information you need from here: https://www.androiddevice.info/devices.

**Comment by CakeHole83** [comment]
Thanks alot. :)

**Comment by Simpuhl** [comment]
@DNA64 

Thank you very much

Is it safe to assume that

  "FirmwareTags": "dev-keys",
  "FirmwareType": "user",

are all the same?

What about   "AndroidBootloader"

those are the only things I can't seem to get

**Comment by DNA64** [comment]
@Simpuhl Give me a minute and I'll edit the post with more info.

**Comment by Simpuhl** [comment]
Thanks,

Hopefully we can just get a full list to help everyone out. That would be very kind of you

**Comment by Simpuhl** [comment]
You have a few duplicates, not questioning you but are you sure its correct
**"DeviceBrand": "ro.product.manufacturer",**
**"HardwareManufacturer": "ro.product.manufacturer",**

Also

"DeviceId": "ro_board_platform",
Are you sure that's accurate? I got my device id via an app and it's completely different

**Comment by DNA64** [comment]
@Simpuhl Sorry! Noted, I'm helping too many people at once here >.<
I'll double check.

**Comment by Simpuhl** [comment]
@DNA64 

No need to apologize, just don't want things to be incorrect and many people will probably look at this post for reference since this seems like the easiest way to get the accurate information

By the way thanks again for your help

**Comment by Simpuhl** [comment]
Not trying to reopen but did we confirm if some of those options are supposed to be duplicates or not? Doesn't seem correct. It may be incorrect on the front page also.

@DNA64
