### ISSUE TITLE
un-softban not successfully unbanning?

### ISSUE THREAD

**Issue by WhipJr** [NECROBOTIO/NecroBot#3122]
necrobot completed a full cycle to unban me however it moved onto a new pokestop and tried again could this be permaban or did they possibl0y change it?

**Comment by tojejo** [comment]
i also got the same on all accounts, maybe new api again?

**Comment by AcidBurns** [comment]
never had that, I also decreased the stock travel speed of 31 km/h down to a more suitable 11.9 ;)

**Comment by WhipJr** [comment]
I wouldnt think so this early. but it can't be counted out. not even sure how i was banned. i closed out of it to switch a setting, opened it then bam, banned. as for the travel speed, im going to do that just in case.
