### ISSUE TITLE
Config.json does not populate

### ISSUE THREAD

**Issue by IamRobRoy** [NECROBOTIO/NecroBot#3125]
I am having an issue where, after running Necro Bot for the 1st time the config file does not populate. I have uninstalled and reinstalled multiple times. The Bot runs 100% fine with generic settings. I am just unable to customize them without the file. Any help is appreciated, thank you.

**Comment by zathrath03** [comment]
Is the file present, just blank? Or is the file missing entirely? It should be in the config sub folder from your installation directory.

**Comment by IamRobRoy** [comment]
Missing completely in the sub folder.
