### ISSUE TITLE
Curious about the new Necrobot's safety when it comes to preventing Permabans. 

### ISSUE THREAD

**Issue by syphon3980** [NECROBOTIO/NecroBot#3126]
I know it is hard to say as no permabans have been issued yet, and will probably come out in waves when pvp/trading is released, but I had read on reddit under the necrobot status that the new api, or w/e is actually set up to mark cheaters and ban them. 

How safe are we to use necrobot?

**Comment by somani6** [comment]
using a bot NEVER protects you from getting banned.

**Comment by xafelld** [comment]
I am not an expert but there are probably numerous ways they can detect bots. 
We really will not know what they are looking for until they start hard bans. Then there will at least be some empirical data related to "this behavior/code got banned" and post/ReadMe's with "So far no bans with this version!"

**Comment by CakeHole83** [comment]
Anyone that teleports from continent to continent or runs at over human walking/running speed for 12 hours straight will probably be banned even if they don't catch us through data. ;)
