### ISSUE TITLE
SNIPE ERROR??

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#3128]
It says that SNIPE works but it doesn't found any pokemon...
![image](https://cloud.githubusercontent.com/assets/20891856/17465695/d5db0c14-5d07-11e6-9eef-683c88ee09f3.png)

**Comment by head0r** [comment]
paste your relevant lines of your config pls :)

**Comment by egsix** [comment]
"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,

**Comment by Simpuhl** [comment]
@egsix are you only snipping things from pokezz.com or your own locations?
