### ISSUE TITLE
Snipe is very bad

### ISSUE THREAD

**Issue by teknojix** [NECROBOTIO/NecroBot#3130]
![screenshot_6](https://cloud.githubusercontent.com/assets/13542417/17465734/8618e114-5d08-11e6-9729-fcd1d079220f.png)

It is not fake coords.

**Comment by head0r** [comment]
Same here. Is there a way to change it?
What does **"SnipingScanOffset"** in the config mean?

**Comment by egsix** [comment]
Why you snipe these? lol.

**Comment by somani6** [comment]
yes it  is... all around the same coords and pidgeys and shit - what do you use to feed your bot with coords?

**Comment by somani6** [comment]
SnipingScanOffset sets the permiter that gets scanned around given coords.
The default Value of 0.003 is half a mile, max is 0.06 (10 miles).

**Comment by teknojix** [comment]
snipingscanofsset default setting. 0.003
