### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by JackSbirrow** [NECROBOTIO/NecroBot#3131]
When I tried to enter with PTC it said that the PTC server were offline or wrong username/password.
So I tried with Google (I went into auth.json and edited with my Google information) but when I run the .exe it says that i must fill the auth file with my Google information but I already did it! So I tried again with PTC and now says that I must fill the PTC information in the auth file. Really?

**Comment by egsix** [comment]
Try to put these -> " <- when you write it.

**Comment by JackSbirrow** [comment]
I forgot a " in google. Now it always says "Log in as Google" and never starts

**Comment by zathrath03** [comment]
Set AutoUpdate to false. There appears to be a login bug related to AutoUpdate.
#3100

**Comment by JackSbirrow** [comment]
Still stucked with Google and even with PTC. I tried to restart the app many times already

**Comment by zathrath03** [comment]
delete auth.json and allow it to regenerate it the next time you open the app. Make sure you've set AutoUpdate to false in config before relaunching.

**Comment by JackSbirrow** [comment]
I deleted it and now the app says  that i must fill the auth file with my Google information but of corse I can't if I deleted the auth...

**Comment by JackSbirrow** [comment]
Still stucked.

**Comment by zathrath03** [comment]
Then it's pointed to the wrong location. If it was looking at the file you
deleted, it would prompt you to do the initial setup. I recommend a clean
install, then copy your config file back over.

**Comment by JackSbirrow** [comment]
It re-created the auth.json but still stucked in "Login as PTC"

**Comment by zathrath03** [comment]
I still recommend a clean install. I'm not a developer, just another user
trying to help out, so I don't know if there is a deeper problem. But a
clean install should solve your problem short term.

**Comment by JackSbirrow** [comment]
I deleted the whole folder of the bot and re-extracted it and still the same problem
