### ISSUE TITLE
(ATTENTION) Encounter problem: EncounterPokemonFled

### ISSUE THREAD

**Issue by arabcurry** [NECROBOTIO/NecroBot#3132]
can someone please help me it says (ATTENTION) Encounter problem: EncounterPokemonFled. how to fix?

**Comment by GummiBoat** [comment]
Throwing Berries.

No, the pokemon simply fled before being able to catch it. Happens from time to time.

**Comment by arabcurry** [comment]
but then after that is says (UPDATE) [Evolves] Potential Evolves: 0 and then it doesnt do anything else

**Comment by GummiBoat** [comment]
What is your config and position?

**Comment by arabcurry** [comment]
"TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 35.6328964,
  "DefaultLongitude": 139.8803943,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 1,
  "DelayBetweenPokemonCatch": 1,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 500,
  "KeepMinIvPercentage": 25.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 10,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": true,
  "UseBerriesMinCp": 800,
  "UseBerriesMinIv": 27.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "and",
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 3000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 80.0,
  "UseUltraBallAboveIv": 90.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
thats all of it

**Comment by GummiBoat** [comment]
Set "DisableHumanWalking" to "false". And disable "SnipeAtPokestops" for now, it's broken since PokeZZ is under Maintenance

**Comment by mariobros33** [comment]
How can I set pokeZZ? :o
