### ISSUE TITLE
Pokezz.com sniper feature not working anymore?

### ISSUE THREAD

**Issue by DeityOfChaos** [NECROBOTIO/NecroBot#3140]
It was working for me just few hours ago with the same configuration - it used to say stuff like (Ignore the silly pokemon name/coordinates in this example):
Sniping a John Cena with unknown IV at 1337.666, -420.360

The site is up though :s

**Comment by head0r** [comment]
theyve got api problems. set it off and try the Pogo finder or sth else :)
OTHERWISE YOU'LL GET AN RKO FROM NOWHERE!

**Comment by DeityOfChaos** [comment]
how 2 get Pogo Findur
*insert dank memes here*

**Comment by GummiBoat** [comment]
just write a simple script that starts NecroBot or PokeSniper2, let them do their stuff for a few minutes, then start the other one and let them do their stuff. Repeat.
