### ISSUE TITLE
api changed again

### ISSUE THREAD

**Issue by whatsupyo** [NECROBOTIO/NecroBot#3142]
.....

**Comment by burntable** [comment]
....

**Comment by GummiBoat** [comment]
No. Bot still running.

**Comment by vcafezinho** [comment]
Just tried pokesniper and it is working so API did not change. Is something else

**Comment by Mamutebr** [comment]
API on Brazil work
API on Canada dowm..
probably down the server

**Comment by vcafezinho** [comment]
So maybe something with Login servers

**Comment by Lord255** [comment]
0,7,5 works
