### ISSUE TITLE
No usable pokemon stop again!

### ISSUE THREAD

**Issue by sstshenshutao** [NECROBOTIO/NecroBot#3143]
No usable pokemon stop again! I think maybe it is not working again

**Comment by ericjwg** [comment]
boom....

**Comment by heanforce** [comment]
And here we go again. Niantic strikes back ;)

**Comment by Nw0006** [comment]
Do a clean install and clean config fixed this error for me

**Comment by Lord255** [comment]
0,7,5 works

**Comment by Nw0006** [comment]
this is on 0.7.5 but again a clean install fixed it
