### ISSUE TITLE
Bug - Red Text

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#3144]
![](http://i.imgur.com/gQgPrNF.png)

**Comment by ObsessedHacker** [comment]
![](http://i.imgur.com/itoxzNm.png)

**Comment by sddds** [comment]
#3143

**Comment by ObsessedHacker** [comment]
![](http://i.imgur.com/dT6ynq7.png)

**Comment by lilmalossi** [comment]
same

**Comment by scati** [comment]
same

**Comment by Mamutebr** [comment]
I managed to fix this by making a new installation
a new configuration

**Comment by ObsessedHacker** [comment]
![](http://i.imgur.com/8szemyB.png)

**Comment by lilmalossi** [comment]
i got the feeling its on the server side giving problems
sometimes its working

**Comment by xnikolai** [comment]
Had the same problem, fixed it using Mamutebr's suggestion

**Comment by ObsessedHacker** [comment]
@Mamutebr @xnikolai Guys, you are wrong.
@lilmalossi Was right! It was server issues.
I'm saying this because sometimes it works and sometimes it's not.

**Comment by lilmalossi** [comment]
^^
