### ISSUE TITLE
Pokemon from Eggs

### ISSUE THREAD

**Issue by diogocmartins** [NECROBOTIO/NecroBot#3146]
Bot isn't showing the pokemon hatched from eggs.

Can you add this feature please?

**Comment by Simpuhl** [comment]
It does show it.

**Comment by diogocmartins** [comment]
Mine doesn't , it only says, putting x km egg in incubator

**Comment by Simpuhl** [comment]
u diddnt have 1 in to begin with or you leveled up and got a new incubator and it put something inside
