### ISSUE TITLE
BOTS DOWN AGAIN :(

### ISSUE THREAD

**Issue by teknojix** [NECROBOTIO/NecroBot#3147]
![screenshot_8](https://cloud.githubusercontent.com/assets/13542417/17466015/abe2f768-5d0d-11e6-948a-6f7ff5a9f82d.png)

**Comment by KJThaDon** [comment]
same

**Comment by TheTurquoise** [comment]
same

**Comment by ivanwing12** [comment]
same

**Comment by AndreasGilja** [comment]
Bot stopped working

Sendt fra min iPhone

Den 8. aug. 2016 kl. 01.13 skrev Eyüphan Kundakcı <notifications@github.com<mailto:notifications@github.com>>:


[screenshot_8]<https://cloud.githubusercontent.com/assets/13542417/17466015/abe2f768-5d0d-11e6-948a-6f7ff5a9f82d.png>

-

**Comment by Dexter145** [comment]
Same here, but App stuck at Loading

**Comment by diogocmartins** [comment]
Still working for me..

**Comment by darkzurvan** [comment]
Red text came up for me again for a minute but it started working again after a restart. I don't think this one is worth a panic wave just yet.

**Comment by xeroun** [comment]
ptc login still works

**Comment by vcafezinho** [comment]
@Dexter145 I am guessing that is something with Login Servers. In some places it still working

**Comment by qzqzqz** [comment]
it seems only a few arent working.
not really sure if api related, actually dont think so

**Comment by GummiBoat** [comment]
Don't worry. Everything is fine. There are just a few problems with niantic.

**Comment by panoszik** [comment]
me too not working google login

**Comment by TheTurquoise** [comment]
and now it s working again pals

**Comment by TheTurquoise** [comment]
restart a couple of times until it works

**Comment by marburger93** [comment]
General Pokemon Go server problem ;-)
http://allestörungen.de/stoerung/pokemon-go

**Comment by qwer4790** [comment]
I have 3 accounts, two of them work fine and one like this..Still be able to login via app, guess it's server issue

**Comment by Deathkebab** [comment]
It's nothing we can do right now , we just have to wait there is problems with niantic servers ...

**Comment by xafelld** [comment]
Damn botters causing server issues... oh w8....

**Comment by saahilz** [comment]
this is mostly affecting Google accounts PTC seems to be working

**Comment by ChemiHatake** [comment]
http://ispokemongodownornot.com/ 
it says it works...
weird.

**Comment by vcafezinho** [comment]
@ChemiHatake See here, http://downdetector.com/status/pokemon-go

**Comment by Dexter145** [comment]
@saahilz my PTC account not working ether

**Comment by scati** [comment]
is working for me now.

**Comment by Auraa** [comment]
still working for me :)

**Comment by vcafezinho** [comment]
Working again Guys

**Comment by StephenFierce** [comment]
back online :)

**Comment by Dexter145** [comment]
Works on phone now, bot still gives me errors.

**Comment by Skydev0h** [comment]
Not really works even on phone, so it seems that at least some servers are really having a **bad time**!
