### ISSUE TITLE
Pogo/Necro not working.

### ISSUE THREAD

**Issue by idkniko** [NECROBOTIO/NecroBot#3150]
I KNOW I shouldn't bring pogo problems to the necro side, but I cant manage to figure out which is causing me problems. I have the config set up like this btw 
  "DefaultLatitude": 40.778915,
  "DefaultLongitude": -73.962277,
   "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
    "SnipePokemonNotInPokedex": false,
    "UsePokemonSniperFilterOnly": false,
    "UseSnipeOnlineLocationServer": true,
somehow it manages to stay like this
![fig2](https://cloud.githubusercontent.com/assets/20893895/17466041/a2b2d0bc-5cba-11e6-9bca-03611d61d8ca.PNG)
![figuire1](https://cloud.githubusercontent.com/assets/20893895/17466042/a2b5c132-5cba-11e6-9665-e15842c2091e.PNG) please let me know if anything is up?!

**Comment by scati** [comment]
try again, i had the same problem a minute ago. i think it was the server
