### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by KrakenBear** [NECROBOTIO/NecroBot#3151]
Hi, 

Has anyone successfully know a work around the login error, i have set up as ptc but ultimately google doesnt work either but all i get is the "login creditentials are invalid"  which there not. 

i have the auth and config files set up fine so unsure what else i can do here. Has anyone found a way round it? 

Cheers

**Comment by ChemiHatake** [comment]
the username in the google login credentials
should be without the @gmail.com
example: lelk@gmail.com -> lelk

**Comment by scati** [comment]
change auto to    "AutoUpdate": false,

**Comment by KrakenBear** [comment]
Seems to be same, auto update is to false and although i would want to use the pc accoutn i have tried it with google as above and just says user and password are incorrect, which i know are right. Hmm
