### ISSUE TITLE
servers are down

### ISSUE THREAD

**Issue by user8285** [NECROBOTIO/NecroBot#3152]
servers are down.....   https://pokemongostatus.org/

**Comment by xafelld** [comment]
Damn botters causing server issues! Oh w8....

**Comment by doness** [comment]
what the heck.. i think.. i got banned

**Comment by qwer4790** [comment]
It's funny because two of my accounts still work even though server is down......and one of my account is down.

**Comment by xafelld** [comment]
They are rebooting to implement another bot break!

**Comment by GummiBoat** [comment]
Hourly server restarts are a great idea to stop bots... :smirk:
