### ISSUE TITLE
Snipe Issue

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#3159]
It says that is sniping but can't find any pokemon. What to do?
![image](https://cloud.githubusercontent.com/assets/20891856/17466114/71c0cf12-5d10-11e6-9f4b-10c1029861dd.png)

**Comment by StephenFierce** [comment]
there are no pokemon (which you selected) in that area

**Comment by Sanskritmp** [comment]
#3078 
Read other issues so as to avoid spamming the section.
Requesting to close the issue.
