### ISSUE TITLE
GetOnlyVerifiedSniperInfoFromPokezz not working as it should?

### ISSUE THREAD

**Issue by ThomasSRL** [NECROBOTIO/NecroBot#3207]
508                     if (pokemon.verified || !session.LogicSettings.GetOnlyVerifiedSniperInfoFromPokezz) 
509                     { 
510                         SnipeLocations.Add(SnipInfo); 
511                     } 

Shouldn't this need an else statement?
I'm getting bad results using Pokezz. (Read: no snipes what so ever)

I'm thinking it never adds the info to the location if you dont care about verified snipes?

**Comment by Energex22** [comment]
I currently have to use the "pogo feeder", to receive any sniper information at all.

**Comment by ken0908** [comment]
same here dont get anything from pokezz

**Comment by Energex22** [comment]
i see that the pogo feeder is trying to update to receive information, maybe they updated something, the pokezz

**Comment by ChemiHatake** [comment]
pokezz API is down. http://www.pokezz.com/pokemons.json

**Comment by Simpuhl** [comment]
Same here, I'd like to just get info from pokezz verified only and not use the pogo feeder but couldnt get it to work. Assumed something was broken.

**Comment by ThomasSRL** [comment]
Seems like it is broken then :( sadface...
Tbh the whole config has just way to many possible options imo, and they could be grouped a little better.

**Comment by TemhAAhmeT** [comment]
While only verified snipes is possible with pokezz, wish to wotk it again.

**Comment by Laiiiff** [comment]
Sorry for the spam, but does anybody know how to change from snipefrompokezz to pogo feeder in the config?

**Comment by Simpuhl** [comment]
Just open pogofeeder and it will automatically work

**Comment by ThomasSRL** [comment]
If   "UseSnipeLocationServer": true, then it wont even us pokezz @Laiiiff 

Also  "UseSnipeOnlineLocationServer": false,  has no use in current code.

**Comment by Laiiiff** [comment]
Thank you very much guys, it works :) :+1:

**Comment by Simpuhl** [comment]
Wait so it does work? Maybe I have it configured incorrectly.

How can I make it use pokezz.com and not the pogo feeder than? 

What does your config look like if I may ask because I tried various settings and it wasn't working, thought it was broken. Tried following wiki best I could

**Comment by ThomasSRL** [comment]
Hi @Simpuhl,
I dont have the pokezz working. 
But logic in the bot should be: 
if using locationserver (IE feeder) then
    do some stuff with feeder
else if usepokezz is true then
   do some stuff with pokezz;

**Comment by Simpuhl** [comment]
@ThomasSRL 

Ah I see

yeah that's what it should do but it doesn't. i only got it to work with the feeder also

**Comment by Simpuhl** [comment]
Still not working in 8.1

**Comment by ThomasSRL** [comment]
I'm not sure if this is a bug or not? Can any of the developers check the code?

**Comment by dddbliss** [comment]
Just updated pokezz to latest api implementation.

**Comment by Simpuhl** [comment]
Awesome
