### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by ken0908** [NECROBOTIO/NecroBot#3208]
"SnipingScanOffset": 0.005, 

and i dont get verified pokemon data from pokezz only fake cords from discord, how can i change that?

**Comment by Energex22** [comment]
I don't receive the pokemon's IV information, and using the pogo feeder only receives info from pokesnipers.

Also i think that is the area around the cords you receive.

**Comment by GummiBoat** [comment]
Questions are to be asked on Discord.

**Comment by nfettinger** [comment]
Closing off topic.
