### ISSUE TITLE
Stuck on Google Login

### ISSUE THREAD

**Issue by dgateles** [NECROBOTIO/NecroBot#3209]
Stay on (INFO) Logging in using Google

**Comment by nerclid** [comment]
did you use full email address "example@gmail.com" ?

**Comment by dgateles** [comment]
@nerclid Yes with and without

**Comment by Energex22** [comment]
i have had this issue also, tried the actual game and it took me a couple min's to actually login with the game..

**Comment by salman102** [comment]
Try taking a backup of config file. Then delete both Config & Auth files. Now try to run the exe and later provide credentials in auth and then overwrite the config.

**Comment by dgateles** [comment]
@salman102 nothing

**Comment by progz** [comment]
Just tu bo sure, you are using release 0.7.6 ?

**Comment by edoth76** [comment]
yes me too with the same issue ... ptc login normally, but stuck on gmail login

**Comment by nfettinger** [comment]
With version 0.7.6, I am able to use a google account without issues. This is most likely a configuration issue. Closing as off topic.

**Comment by dgateles** [comment]
You able to use google, fuck others because "probably a configuration issue". I have downloaded the last release and setup again and again and continue stuck on google.
