### ISSUE TITLE
Cannot run Necrobot

### ISSUE THREAD

**Issue by lolol1236** [NECROBOTIO/NecroBot#3211]
When I start the exe file, it takes around 10 seconds to something to pop up, and the only thing that pops up is an error message saying that I cannot access the file/device and it is because may not have access to the file. I tried run as admin, but same happens
HELP PLEASE!

**Comment by salman102** [comment]
post a screenshot

**Comment by GummiBoat** [comment]
Put it in a folder, where you know, you will have read and write access. (e.g. \Desktop\Bot\)
Try setting up your login credentials manually in the auth.json. (Open it with Notepad or Notepad++)
Try re-downloading the entire thing and reset the config by doing so.

**Comment by EthanBianchi** [comment]
On Windows 10 I occasionally get a "SmartScreen Defender" "error" that tells me it's protecting me from harmful programs. I have to click "More Information" and then click "Run Anyway".. Idk if this is your exact problem, but sounds similar.

**Comment by GummiBoat** [comment]
Oh yeah true, some anti virus programs block it. Try putting the folder in the exceptions-list.

**Comment by lolol1236** [comment]
I've put it in desktop already and I can't run it the first time so I don't have a auth or config.json :(

**Comment by lolol1236** [comment]
Also I was going to post a screenshot but it's in korean...

**Comment by nfettinger** [comment]
This sounds like a permissions issue with file/exe access due to platform or antivirus setup. For further assistance, please visit the Discord chat rooms and ask for help there. Closing as off topic

**Comment by lolol1236** [comment]
Changed my computer language to show u guys the screenshot
![untitled](https://cloud.githubusercontent.com/assets/20907124/17483423/f432c48a-5d53-11e6-89d2-3b1c79757a24.png)

**Comment by lolol1236** [comment]
Where is the discord chat room?
