### ISSUE TITLE
[Bug] Possible softban

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#3214]
![](http://i.imgur.com/uf4NyTZ.png)

**Comment by EthanBianchi** [comment]
I don't understand what the bug is or what lead to the softban. We need more information if this truly is a "bug", but honestly from what I've been experiencing personally, anymore than 3-bots on a single IP will do that.

**Comment by Saiteik** [comment]
You cannot run multiple bots on a single IP anymore, they can detect this and will softban all accounts making request from that IP. Stop all your bots, wait some time, and run one. You may want to research for VPN options to run multiple bots.

**Comment by ObsessedHacker** [comment]
@EthanBianchi Config: http://pastebin.com/D921s78c
@Saiteik So what you are saying is that I need to use Proxy settings in "config/auth.json", right?

**Comment by djdookie** [comment]
@ObsessedHacker I believe there is no proxy implementation in the code yet, just variables which you can set.

**Comment by ObsessedHacker** [comment]
@NecronomiconCoding Close issue, please. I'm using proxy in each bot and issue solved.

**Comment by KevHart95** [comment]
@ObsessedHacker Did you set the login proxy in auth.json?

**Comment by ObsessedHacker** [comment]
@KevHart95 Yes.
  "UseProxy": true,
  "UseProxyHost": 45.248.87.167,
  "UseProxyPort": 1080,

**Comment by KevHart95** [comment]
I'm using one VM for 3 necrobots now, solved ;-)

**Comment by progz** [comment]
If you don't want to use proxy, you can theter the data connection from your smartphone.
Practically all smartphones can tether (sharing their data connection with your other devices), mobile network is a giant proxy network, a lot of user have the same IP address.

**Comment by ObsessedHacker** [comment]
@KevHart95 I'm glad you got it fixed for you, but what about me?
@progz I won't use it, but thanks for the help.
Any other help?

**Comment by h4rdboot** [comment]
i just got softbanned on 3 accounts (2 on 1 IP one on another), all 3 went down in the space of 2 mins.
I logged into the accounts on the proper app and nothing was picked up on map, retried on bot and still softbanned and wouldnt clear, 
my solution: reset my auth.conf file (regenerated new id etc.) and added my login details back into it and it seems to be working for now so maybe fix = reset the auth settings (brand, deviceid etc) in auth.json?

**Comment by bradleytje97** [comment]
@obsessedhacker @kevhart95 @progz is there als solution yet?  I stopped running 40 accs already for too long Ik can't find solution yet? Update..
