### ISSUE TITLE
encrypt.dll

### ISSUE THREAD

**Issue by hammela** [NECROBOTIO/NecroBot#3216]
A friend of mine gets an error after logging in. 
Saying that the modul "Resources/encrypt.dll" wasn't found. 
Can anyone help? :)

**Comment by GummiBoat** [comment]
Redownload. You should have the encrypt-dll in the zip-file.

**Comment by salman102** [comment]
check if the DLL was taken down by your antivirus

**Comment by hammela** [comment]
He already did this. 
Right now the *.dll is in his Resources folder. That' the odd thing.

**Comment by EthanBianchi** [comment]
I got this error when attempting to open the Solution/Project in Visual Studio. I had to completely re-download everything fresh , git clone --recursive https://github.com/NecronomiconCoding/NecroBot.git.

**Comment by hammela** [comment]
SOLVED
As it turned out there wasn't an "Resources" folder but the *.dll was in the general folder, so for everyone: just create a folder named "Resources" and drag the *.dll there. This should fix the issue.
