### ISSUE TITLE
change IP with VPN Proxy List

### ISSUE THREAD

**Issue by Ghenghis** [NECROBOTIO/NecroBot#3217]
running more then one get ip ban,
every 5 minutes change IP with VPN Proxy List can this be added to the bot?

**Comment by GummiBoat** [comment]
I don't think this is necessary. Just setup a proxy for each Bot-Instance you're running, and change it if you have the feeling, it's ip-softbanned.

**Comment by EthanBianchi** [comment]
This would be ridiculously hard to implement, where would we get multiple proxies for every single user of Necrobot? It would be next to impossible to change the Proxy every 5 minutes for every 2-accounts for every single user. The proxies would have to be free and probably not work 50% of the time, or Necrobot would become a paid-service.

**Comment by Rick058** [comment]
Without a private proxy you will still get soft banned quite fast Had them running for 6 minutes on a proxy, and getting the messages already. Same issue with my own IP, my VPN IPs and now also my proxy IPs. It's getting difficult.

**Comment by Ezoteric** [comment]
thats weird, i ran the bot for 6 hours straight and the only problem i had was that my pokemon bag was full :P

**Comment by WatIsGithub** [comment]
Ezoteric: Most likely because you ran only 1 instance, right?

**Comment by nfettinger** [comment]
Make sure you are not using the same device ID for more than 1 instance.

**Comment by nfettinger** [comment]
This is not a development issue. Closing as off topic.
