### ISSUE TITLE
Logs, Player info

### ISSUE THREAD

**Issue by ozjaban** [NECROBOTIO/NecroBot#3220]
My logs don't show my player level, exp etc.
I haven't really changed anything a lot, just some basic stuff in conf, left everythhing as is.
Everything works, just not showing me my current exp and level status and stuff.
Thank you.

**Comment by EthanBianchi** [comment]
Look at the top border of the console window.

**Comment by ozjaban** [comment]
Wow I AM AN IDIOT...there it is :D :D
Thank You.
