### ISSUE TITLE
Everytime I run Necrobot

### ISSUE THREAD

**Issue by lolol1236** [NECROBOTIO/NecroBot#3221]
![untitled](https://cloud.githubusercontent.com/assets/20907124/17483481/35e3d8d8-5d54-11e6-8202-bbef5534c3f6.png)
This happens :( help

**Comment by Simpuhl** [comment]
Try running it as administrator?

**Comment by lolol1236** [comment]
Already tried that same result

**Comment by ObsessedHacker** [comment]
@lolol1236 Maybe try Windows Update?
Or maybe ReDownload and Re-Install and Re-Configure?

**Comment by nfettinger** [comment]
Please check for permissions issues, as well as antivirus protection.
Closing as off topic. Further assistance can be found using the Discord Chat rooms.
