### ISSUE TITLE
many Golbats?

### ISSUE THREAD

**Issue by errormind** [NECROBOTIO/NecroBot#3224]
ive got the problem, that i have many golbats after evolving, which will not be transfered.
i twould be nice if you could help me.
regards
my config file is atached :)
[config.zip](https://github.com/NECROBOTIO/NecroBot/files/407053/config.zip)

**Comment by progz** [comment]
For config support, you should go to discord : https://discord.gg/VXKxNFr ! There is a lot of people helping each other.

**Comment by ubulem** [comment]
In PokemonsTransferFilter you have
```
    "Golbat": {
      "KeepMinCp": 1600,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
```
So I think it keeps all golbats with IV great or equal than 60

**Comment by Energex22** [comment]
i have kind of been wondering about this myself, i have seen a few pokemon not on that list, collecting up multiples that don't even have close IV or CP values.

**Comment by errormind** [comment]
Thank you very much!!
There where 60 golbats in total ^^
