### ISSUE TITLE
Necrobot doens't  prioritize better balls

### ISSUE THREAD

**Issue by Testvade** [NECROBOTIO/NecroBot#3226]
When inventory is full, bot doesn't recycle pokeballs to get better balls. It just show "inventory is full" and doesn't spin pokestops anymore. it makes my inventory only has pokeballs. Do you know how to fix it?

**Comment by Energex22** [comment]
They should be recycled automatically from time to time, not sure the exact timing of the recycling, but this option should be this way "  "VerboseRecycling": true,  " pretty sure this is what turns it on.
Also it should prioritize the order of the balls, recycling the worst balls first. But i do see this loop from time to time, i normally just restart necrobot

**Comment by nfettinger** [comment]
The inventory is recycling pokeballs correctly in my test. This is probably a configuration issue. Please use the Discord Chat rooms for further assistance.
