### ISSUE TITLE
Necrobot crashes when changing devicepackagename

### ISSUE THREAD

**Issue by itterror** [NECROBOTIO/NecroBot#3227]
Whatever you set devicepackagename to it provides an invalid argument exception.
Using the predefined name, or a random name produces no errors.
Must look stupid for Niantic if everything stays the same, but packagename always has random Values,
so it would be great to be able to set it properly

**Comment by nfettinger** [comment]
Please provide more information. I can manually change the DeviceId in auth.json, and I have no issues.

**Comment by itterror** [comment]
What information do you need, please specify.

**Comment by jumitate** [comment]
Hello,

I am having the same problem - this is the error:

![image](https://cloud.githubusercontent.com/assets/20780918/17484634/bec71448-5d82-11e6-92dd-a8769b4ee4fe.png)


Here is the auth file - disregard "null" fields:
![image](https://cloud.githubusercontent.com/assets/20780918/17484681/f4ee66ac-5d82-11e6-9d59-5bd02d2984b3.png)

the details in the config file are from an actual device i own.

**Comment by nfettinger** [comment]
There is a proxy issue with PTC in the API, this may be a side effect of that.

**Comment by nfettinger** [comment]
Please try without a proxy and let us know if your issue persists.

**Comment by itterror** [comment]
I use google login without proxy :)

**Comment by nfettinger** [comment]
Proxies are working in source, Please wait for the next release if you are unable to build yourself.
If you are using a PTC account, the API is being updated as we speak to fix an authentication issue.

**Comment by jumitate** [comment]
@nfettinger - Using //  "DevicePackageName": "galaxy-s5-gold", // the client starts and gets stuck as per below: 

![image](https://cloud.githubusercontent.com/assets/20780918/17485430/a90b0e4a-5d85-11e6-925d-f1457bcf13a4.png)

removing proxy reference brings me to the same point as per above.

thanks

**Comment by sub7even** [comment]
you need to write   null   without  "

Yellow: wrong
Green: ok
![image](https://cloud.githubusercontent.com/assets/20596841/17485563/3a0e3d7e-5d8e-11e6-91fb-880cc7be926a.png)

**Comment by itterror** [comment]
As mentioned above (maybe nfettinger read the info provided, thank you).
IT IS NOT RELATED TO PTC, AS I HAVE THE SAME PROBLEM WITH GOOGLE.

**Comment by jumitate** [comment]
@sub7even - thanks for your reply. as i said in my original post ignore "null" fields, but just to be on the safe side, this is how the config looks like:

![image](https://cloud.githubusercontent.com/assets/20780918/17485741/72f0d32a-5d86-11e6-91b8-f4f026ac966e.png)

thanks
