### ISSUE TITLE
3 bots per ip fix

### ISSUE THREAD

**Issue by DrPiggy** [NECROBOTIO/NecroBot#3231]
hey, could you just make the proxy feature you added the config for but never made? then we could easily put a diffrent proxy for each 3 bots and have infinite bots :)

**Comment by nfettinger** [comment]
Each instance should be configured separately. Each can have its own proxy.

**Comment by ObsessedHacker** [comment]
@DrPiggy Great suggestion, if this will be automated - even better!
I just wish there will be an automated solution for that issue.

**Comment by nfettinger** [comment]
Proxies are implemented in source. Please wait for the next release for support.
