### ISSUE TITLE
"SnipePokemonNotInPokedex" : is this working ?

### ISSUE THREAD

**Issue by Kachime** [NECROBOTIO/NecroBot#3234]
"SnipePokemonNotInPokedex": true

Is this feature working ? because currently necrobot is sniping everything coming from pogolocationfeeder, not only the one missing in my pokedex

**Comment by Simpuhl** [comment]
That's in addition to the LIST you have at the bottom.

So if something isn't listed but you haven't seen it yet or in pokedex it will also catch it.

**Comment by Kachime** [comment]
Ok, so if i leave the list empty, it'll only catch the missing one.
Thanks a lot for your help !

**Comment by Kachime** [comment]
Well it gives an error message when pokemon list is empty.
I put "mew"only and it's working.

"PokemonToSnipe": {
    "Locations": null,
    "Pokemon": [
      "mew"
    ]
  }

**Comment by ChemiHatake** [comment]
Ill make it work even if the list is empty

**Comment by Simpuhl** [comment]
I think minimum you have to put ""

**Comment by JaEdmuva** [comment]
Hi, it'll be nice if there is an option/config to snipe pokemon that are in the pokedex, but not in your inventory... it'll be like "SnipePokemonNotInInventory" cause due to a missconfiguration pkmn may be erroneously transfered and you have to look for them all again, so the pkmn is in the pokedex but you do not have it!

**Comment by Marsinator** [comment]
@chemihatake maybe have it ignore the list at all? say put an option to have it snipe only for those missing, no matter waht the list says. if set to false it should snipe for those missing PLUS the ones on the sniping list

**Comment by ChemiHatake** [comment]
@Marsinator Sorry for the delay, 
totally forgot about that.
I'll be working on it tomorrow

**Comment by hughpearse** [comment]
Yea ideally you want to "catch 'em all", meaning you want it both in your pokedex and your inventory.

So by setting "SnipePokemonNotInPokedex": true, the setting should get a list of the ones you are missing, apply the ignore list and snipe those.

By setting "SnipePokemonNotInPokedex": false, it should get a list of all Pokémon available for sniping, apply the ignore list and snipe those.

The ignore list is always applied to data first.

rfc?

**Comment by nfettinger** [comment]
I agree with @hughpearse. Is this not how it is currently working?

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17525091/7cd1a5b2-5e8b-11e6-9dd3-07af3c60ee31.png)

This is how mine works with 8,1

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17525153/bbc07226-5e8b-11e6-8cdb-44877de5c8cf.png)


This is with 8.1

**Comment by dddbliss** [comment]
If SnipePokemonNotInPokedex is true:
* Get All Pokemon not yet caught in pokedex
* Get All Pokemon in PokemonToSnipe
* Return combined list of both

If SnipePokemonNotInPokedex is false:
* Get All Pokemon in PokemonToSnipe
* Return PokemonToSnipe

*Note*: We do not currently apply any PokemonToIgnore to the lists.
