### ISSUE TITLE
Permanent Device Ban?

### ISSUE THREAD

**Issue by luloak2** [NECROBOTIO/NecroBot#3236]
I tried to play with my iPhone (with and without Necrobot running), but the map stays empty (normally 5-6 Pokestops in a few hundred meters distance) for some days now (since the last major security update of Pokemon Go -> Unknown6 validation). I have already reinstalled Pokemon Go, cleared the cache and tried to connect using VPN/Proxy.
Maybe I should mention that my iPhone is jailbroken, Niantic has automatic jailbreak detection at least for Ingress to prevent GPS-Spoofing (which won't let you even start the game), so maybe they added this to Pokemon Go, too - but: 
I also noticed that the versions of Necrobot until release 0.7.1, so before the automatic Device ID generation was implemented, had the same problem(s) and were unable to find any Pokestops or Pokemon nearby. The versions greater than 0.7.1 are working fine, but I am still getting the same problem(s) with my iPhone.

So is it possible that Niantic is banning devices permanently? Has anyone else experienced this problem?

**Comment by nfettinger** [comment]
Please take off topic questions to our Discord Chat rooms.
