### ISSUE TITLE
Blank ro.boot.bootloader for specific device info?

### ISSUE THREAD

**Issue by erikk00** [NECROBOTIO/NecroBot#3237]
I'm setting up my specific device info and when I do:

"AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader

I am getting a completely blank response:

> C:\ADB>adb.exe shell getprop ro.boot.bootloader
> 
> 
> C:\ADB>  

This is for an LG G5 rooted.  Here are the other values I receive:

"DeviceId": "", // adb.exe shell settings get secure android_id				UNIQUE TO ME?
"AndroidBoardName": "", // adb.exe shell getprop ro.product.board			msm8996
"AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader
"DeviceBrand": "", // adb.exe shell getprop ro.product.brand				lge
"DeviceModel": "", // adb.exe shell getprop ro.product.model				LG-H830
"DeviceModelIdentifier": "", // adb.exe shell getprop ro.product.name			h1_tmo_us
"DeviceModelBoot": "qcom",
"HardwareManufacturer": "", // adb.exe shell getprop ro.product.manufacturer		LGE
"HardwareModel": "", // adb.exe shell getprop ro.product.model			LG-H830
"FirmwareBrand": "", // adb.exe shell getprop ro.product.name				h1_tmo_us
"FirmwareTags": "", // adb.exe shell getprop ro.build.tags				release-keys
"FirmwareType": "", // adb.exe shell getprop ro.build.type				user
"FirmwareFingerprint": "" // adb.exe shell getprop ro.build.fingerprint			lge/h1_tmo_us/h1:6.0.1/MMB29M/(UNIQUE TO ME?):user/release-keys

Removed a couple values that I think are unique to my specific phone.

**Comment by nfettinger** [comment]
This is expected.

**Comment by erikk00** [comment]
Just out of curiosity do I then not use that line in my auth.json?  Or put ""?

**Comment by erikk00** [comment]
As per discord help from nfettinger (thanks again) in case anyone else finds this and needs the answer.  you should use "" for that variable.  Don't leave out the line and don't just choose something random.
