### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by niparo** [NECROBOTIO/NecroBot#3238]
requires confirmation to install update (press Y of N)

it would be much easier if it actually does auto-update and install without confirmation.
The problem is when you run lots of bots with auto update on "true", they get stuck on 
press y or n to update  resulting in hours of non farming bots.

**Comment by nfettinger** [comment]
Every time you update, you should verify the config of each instance to ensure the default settings of new items do not conflict with your previous configuration.
