### ISSUE TITLE
LastPos.ini [is this working/how it works?]

### ISSUE THREAD

**Issue by JaEdmuva** [NECROBOTIO/NecroBot#3239]
Hi guys, I see the LastPos.ini file in the config folder and it's changing constantly, which is just fine. But, whenever I close the bot, shouldn't it take the info in that file as starting position? 'cause I see it always takes the position in the config.json file as the starting position, not the lastpos.ini data.

**Comment by nfettinger** [comment]
The lastpos.ini is to ensure that when you restart the bot (on error or on purpose), it does not teleport you from where it was, to the default or configured start location.

**Comment by JaEdmuva** [comment]
with restart, what do you mean exactly? cause if it's supposed to take that info when I close and the reopen the bot, It's not working!
