### ISSUE TITLE
')' or operator expected (at index 212)

### ISSUE THREAD

**Issue by WalecznaKaczucha** [NECROBOTIO/NecroBot#3240]
Error such as the topic.

**Comment by ChemiHatake** [comment]
can we get a screenshot of the error please

**Comment by WalecznaKaczucha** [comment]
http://imgur.com/a/3dQA3

**Comment by nfettinger** [comment]
Please check your config.json and auth.json for stray or missing " and ,
Are you using a language other than Enlgish?
This is typically what causes parsing issues like this.

**Comment by Marsinator** [comment]
this is not a problem in the users config, @nfettinger . we will fix it with the next release.

**Comment by WalecznaKaczucha** [comment]
Oh, waiting for next release :+1:  :)

**Comment by jurannus** [comment]
This was fixed by a revert from grimm
