### ISSUE TITLE
Unexpected character encountered

### ISSUE THREAD

**Issue by Recolance** [NECROBOTIO/NecroBot#3242]
After about an hour of runtime, this error occurs.

After some testing, restarting the bot does not fix it, although changing my IP address does have an effect of it. This has happened many times through the day and some instances of the bot may have it occur while others do not. Although, once one instance of the bot has it occur, the rest follow over the course of a few minutes.

As mentioned, changing my IP causes things to work again, although they soon end up the same. Not sure what end this is on, but it is not an issue with my config.

https://gyazo.com/985a889976d2585e204254be5eff0c04

**Comment by dddbliss** [comment]
Closing as issue is with skiplagged downtime.
