### ISSUE TITLE
Not enough Pokeballs to start sniping! Doesn't update its value

### ISSUE THREAD

**Issue by dansali** [NECROBOTIO/NecroBot#3246]
It will repeat the same amount of pokeballs even though the bot has gone through multiple pokestops. I've also had it say Not enough Pokeballs to start sniping (0/1) when it's set to 100.

> [01:46:22] Not enough Pokeballs to start sniping! (94/100)
> [01:46:22] Traveling to Pokestop: Queen Victoria Market Sign (65m) (0 seconds)
> [01:46:23] Name: Queen Victoria Market Sign XP: 50, Gems: 0, Items: 1 x ItemSuperPotion, 2 x ItemPokeBall, Lat: -37.806709, Long: 144.957096
> [01:46:23] Not enough Pokeballs to start sniping! (94/100)
> [01:46:24] Traveling to Pokestop: Market Day (94m) (0 seconds)
> [01:46:25] Name: Market Day XP: 50, Gems: 0, Items: 1 x ItemPotion, 2 x ItemPokeBall, Lat: -37.80659, Long: 144.956037
> [01:46:25] Not enough Pokeballs to start sniping! (94/100)
> [01:46:25] Traveling to Pokestop: History of Victoria market  (54m) (0 seconds)
> [01:46:26] Name: History of Victoria market  XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemRazzBerry, Lat: -37.807075, Long: 144.955963
> [01:46:26] Not enough Pokeballs to start sniping! (94/100)
> [01:46:26] Traveling to Pokestop: Victoria Markets (66m) (0 seconds)
> [01:46:27] Name: Victoria Markets XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemGreatBall, Lat: -37.807666, Long: 144.956054
> [01:46:27] Not enough Pokeballs to start sniping! (94/100)

**Comment by nfettinger** [comment]
Is this still an issue in 0.8.1?

**Comment by dansali** [comment]
Yes it seems to be @nfettinger

**Comment by dddbliss** [comment]
Fixed.
