### ISSUE TITLE
Always keep 1 Pokemon

### ISSUE THREAD

**Issue by Oncoming-Storm** [NECROBOTIO/NecroBot#3247]
What I mean is that everytime you catch a pokemon it trasfers it if it's below the CP you've set.. What I want is I want it to always keep 1 of each pokemon and trasfer that if it finds one with higher CP I don't really know if that's an option already but I've seen some cool pokemon I would want to evolve but I don't have it anymore and the bot transfered it.

Sorry if that wasn't completely clear please ask if you want me to elaborate and thanks in advance!

**Comment by nfettinger** [comment]
This is already supported using the config.
KeepMinDuplicatePokemon
For further assistance, use Discord chat.
