### ISSUE TITLE
How to set auto transfer inventory pokemon.

### ISSUE THREAD

**Issue by AriesDm** [NECROBOTIO/NecroBot#3249]
Hi, my pokemon inventory is full and I was wondering why it did not transfer them away. Can anyone help me? Thank you!

**Comment by Energex22** [comment]
This would be a nice feature!! like once it see's full inventory of pokemon, looks for duplicates ect... i thought that this was done somehow, but i cant get mine to empty out correctly.

**Comment by nfettinger** [comment]
Closing as off-topic. Please use Discord chat for issues related to this.
