### ISSUE TITLE
sniping not working

### ISSUE THREAD

**Issue by mrturkk** [NECROBOTIO/NecroBot#3250]
it wont snipe anything even the `sniping text isnt coming anymore` please help mee tho

**Comment by Energex22** [comment]
i use the POGO Feeder to get sniping information, Search "Pogo Feeder"

**Comment by mrturkk** [comment]
how can i `install` it could u maybe give me a short tutorial<3

**Comment by Massnl** [comment]
check if pogo feeder is updated to newest version, and if it still shows new pokemons
its working fine for me.

**Comment by Massnl** [comment]
https://github.com/5andr0/PogoLocationFeeder/releases

i think these are the settings for pogofeeder
"UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 6000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
what i have atleast

**Comment by dansali** [comment]
Guys this isn't a chat room, this is for issues regarding the code, there isn't issues sniping.

**Comment by jonsnowwatch** [comment]
there are issues regarding sniping. it stopped working since 0.7.4 with same sniper config.

**Comment by Omigof** [comment]
sniping still works, but pokezz.com is offline now, go read manual/auto location sniping setup for another sniping method.

**Comment by Tolc** [comment]
pokezz.com is not offline... 
Still the sniping does not seem to happen in 0.7.6, with the same config that previously worked (in 0.6.4):

```
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 15000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,
```

Any idea on what the problem is?

**Comment by dansali** [comment]
Works fine for me, just doesn't tell you it's sniping. If you look at the distance of the pokemon you start catching and its like 100000m away, then obviously its sniping.

**Comment by PokemasterMike** [comment]
it doesnt work for me neither... the log says "sniping snorlax at xy"... but then no catch/escape/flee happens, just nothing at all....

**Comment by dansali** [comment]
> [03:38:06] (CatchEscape) | (Normal) Pidgey Lvl: 27 CP: (436/524) IV: 37.00% | Chance: 28.81% | 15613245.21m dist | with a GreatBall (6 left). | lat: 59.316928 long: 18.063683
> [03:38:10] (CatchSuccess Attempt #2) | (Normal) Pidgey Lvl: 27 CP: (436/524) IV: 37.00% | Chance: 28.81% | 15613245.21m dist | with a GreatBall (5 left). | 210 EXP earned | Candies: 71 | lat: 59.316928 long: 18.063683
> [03:38:16] (CatchEscape) | (Normal) Rattata Lvl: 19 CP: (252/315) IV: 31.00% | Chance: 34.35% | 15613304.87m dist | with a GreatBall (4 left). | lat: 59.316989 long: 18.062602
> [03:38:20] (CatchSuccess Attempt #2) | (Normal) Rattata Lvl: 19 CP: (252/315) IV: 31.00% | Chance: 34.35% | 15613304.87m dist | with a GreatBall (3 left). | 210 EXP earned | Candies: 116 | lat: 59.316989 long: 18.062602
> [03:38:31] Scanning for Snipeable Pokemon at 22.27972,114.158091...
> [03:38:41] (CatchSuccess) | (Normal) Rattata Lvl: 30 CP: (419/498) IV: 45.00% | Chance: 27.33% | 7424006.60m dist | with a GreatBall (2 left). | 210 EXP earned | Candies: 119 | lat: 22.283992 long: 114.161910
> [03:38:48] (CatchSuccess) | (Normal) Pidgey Lvl: 24 CP: (364/466) IV: 18.00% | Chance: 30.56% | 7424346.96m dist | with a GreatBall (1 left). | 210 EXP earned | Candies: 74 | lat: 22.282084 long: 114.150206
> [03:38:55] (CatchSuccess) | (Normal) Weedle Lvl: 19 CP: (176/243) IV: 14.00% | Chance: 34.35% | 7425100.79m dist | with a GreatBall (0 left). | 210 EXP earned | Candies: 65 | lat: 22.287393 long: 114.145282
> [03:39:02] (CatchSuccess) | (Normal) Weedle Lvl: 4 CP: (33/47) IV: 10.00% | Chance: 78.21% | 7423865.71m dist | with a UltraBall (5 left). | 210 EXP earned | Candies: 68 | lat: 22.278448 long: 114.152807
> [03:39:09] (CatchSuccess) | (Normal) Pidgey Lvl: 16 CP: (253/310) IV: 31.00% | Chance: 37.43% | 7423538.31m dist | with a UltraBall (4 left). | 210 EXP earned | Candies: 77 | lat: 22.280907 long: 114.165440
> [03:39:16] (CatchSuccess) | (Normal) Caterpie Lvl: 29 CP: (257/367) IV: 8.00% | Chance: 27.8% | 7423612.26m dist | with a UltraBall (3 left). | 210 EXP earned | Candies: 45 | lat: 22.282069 long: 114.166369
> [03:39:22] (CatchSuccess) | (Normal) Pidgey Lvl: 17 CP: (283/330) IV: 47.00% | Chance: 36.31% | 7424260.08m dist | with a UltraBall (2 left). | 210 EXP earned | Candies: 80 | lat: 22.280370 long: 114.148348
> [03:39:38] (CatchSuccess) | (Normal) Pidgey Lvl: 4 CP: (57/71) IV: 30.00% | Chance: 78.21% | 7423422.57m dist | with a UltraBall (1 left). | 210 EXP earned | Candies: 83 | lat: 22.274392 long: 114.153643
> [03:39:45] (CatchSuccess) | (Normal) Pidgey Lvl: 13 CP: (214/252) IV: 43.00% | Chance: 41.52% | 7424358.08m dist | with a UltraBall (0 left). | 210 EXP earned | Candies: 86 | lat: 22.282955 long: 114.151878

Check the distance guys, you sure it's 100% not working?

**Comment by PokemasterMike** [comment]
this is the sniping via skipagged, which works.... but no "rare sniping" via pokezz (because API is down - ok cant do anything here) neither pogofeeder works... :(

**Comment by dansali** [comment]
PogoFeeder was working fine for me. Did you download the latest version?

http://imgur.com/Ooo0gX5

**Comment by Tolc** [comment]
Checked that before coming here, all the distances are around 55-60m, and only basic Pokemons, not those I put in the PokemonToSnipe list.
Maybe a pokezz.com issue only. Website seems to be working just fine, but maybe they shot down their API?...

**Comment by PokemasterMike** [comment]
see #3275

**Comment by Tolc** [comment]
Well, I don't think it is linked.
I checked the code, the url that is called is [http://pokezz.com/pokemons.json](http://pokezz.com/pokemons.json), which gives an empty json array as a response.

I also checked pokezz.com page code: they were previously using ajax to update the list, calling this same URL to get the json. 
**But they are now using web sockets...** Therefore this json is not required for their website to work anymore, so they probably just mocked it to respond with an empty array no matter what.

Should I open a specific issue for this?

**Comment by kirito-su** [comment]
What seems to have worked for me is changing it to 

>  "SnipingScanOffset": 0.3,

instead of .003 .. please let me know if i did a bad thing, but to ME, its a good thing because I'm back to sniping.. I pretty much moved the 3 over one spot at a time, and tested for sniping..

**Comment by kirito-su** [comment]
@mrturkk See Above and see if that works for you. Change 

```
 "SnipingScanOffset": 0.003,
to
 "SnipingScanOffset": 0.3,
```

I sorta happenstance figured out something out on my own, maybe. Still want someone to explain the Scanoffset to me, and if it really needs to be that small. (original value of .003)

**Comment by nfettinger** [comment]
Please update to 0.8.1 and create a new issue if the problem persists.
