### ISSUE TITLE
Pokemonnottotransfer bug.

### ISSUE THREAD

**Issue by Massnl** [NECROBOTIO/NecroBot#3251]
For the 4th time today, my chansey got transfered, while chansey is in the nottotransferlist, and after the 1st transfer i started favouriting every chansey i saw, but they still get transferred.
my settings
  "KeepMinCp": 1550,
  "KeepMinIvPercentage": 80.0,
  "KeepMinLvl": 20,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
My chansey's met atleast 1 criterium (iv84/cp450 and 2nd iv94/cp25) they were both favourited, chansey is in the nottotransferlist but still got transfered. 

i also experienced this with a bulbasaur iv 91 who still got transfered

**Comment by aaron25th** [comment]
try making a pokemon transfer filter in the config for chansey

**Comment by Massnl** [comment]
Added that filter, to the list. 

So for every pokemon i add to the list i will have to create a seperate filter too? if so then i think there is no problem.
