### ISSUE TITLE
No usable pokestops loop

### ISSUE THREAD

**Issue by aaron25th** [NECROBOTIO/NecroBot#3255]
Last time the update fixed this for me does anyone know to to fix it

![image](https://cloud.githubusercontent.com/assets/20888296/17487278/199d4db6-5d8c-11e6-9ea9-ed6b758718fa.png)

**Comment by nfettinger** [comment]
Please post information regarding the version you are running, location, etc.

**Comment by dansali** [comment]
I had this same issue when I changed my coordinates, have you tried restarting the bot? It fixed it for me

**Comment by kenlim123** [comment]
i'm having the same issue when i open more then 3 bots , i heard we can only open max of 3 bots at 1 time? dunnoe is it true or no.

**Comment by meetloaf13** [comment]
I had this problem on an earlier version, but I found that if I let it run, it would come out of the loop.

It would go in and out of this loop for a while.  I had it placed in downtown LA.  Updated to .6 and changed my locale to Santa Monica Beach and haven't experienced it yet.

**Comment by Dafuq313** [comment]
I have this problem too.
I use the last version,coordinates from Tokyo Disneyland.I used many coordinates,the same problem.This looks like a softban but the bot doesnt try to unban it.I tried with another tool ( QuickSpin ) to unban it,same problem,it says there are no pokestops.
I even let the bot like this for about ~20 mins,still in this loop.Help ?

**Comment by aaron25th** [comment]
"DefaultLatitude": 40.78331,
  "DefaultLongitude": -73.964869,
that is central park im on 0.7.6 and max tarvel is 2000

**Comment by Rick058** [comment]
Same issue on v0.7.6 - running 1 or 4 bots doesn't change anything - changing the proxy only temporarily fixes it. Even tweaked the stats below back to their original settings, or even lowered down but also did not seem to solve anything.

  "WalkingSpeedInKilometerPerHour": 15.0,
  "DelayBetweenPlayerActions": 6000,
  "DelayBetweenPokemonCatch": 3000,

**Comment by aaron25th** [comment]
ok just seems to of fixed its self required a few restarts its annoying because at night it will just loop and achieve nothing

**Comment by Dafuq313** [comment]
I still have the problem and i am facing it for hours.I restarted for like 10k times until now.

**Comment by SAiBOTiERT** [comment]
same here. probably another kind of softban...

**Comment by fass1993** [comment]
I have the same Problem (V.0.7.6). 
Bot works for few minutes then it shows loot fail and soft ban :/

**Comment by jkfever** [comment]
me too i had a same problem ..

**Comment by Ryzison** [comment]
running more than 2-3 bots?  

https://www.reddit.com/r/pokemongobotting/comments/4wnrcs/no_pokestops_founds_niantic_bans_ip_now/

**Comment by KevHart95** [comment]
I got the same issue if I run more then 3 bots

**Comment by Sylencer90** [comment]
"WalkingSpeedInKilometerPerHour": 33.0,
  "DelayBetweenPlayerActions": 3000,
  "DelayBetweenPokemonCatch": 1500,

facing same issue after like an hour or so

**Comment by justrk** [comment]
Got the same problem. im running with 0.7.6 and using 15 km/h at santa monica.
Try to restart necrobot but still got the same issue

**Comment by Dafuq313** [comment]
I just tested it.I created a new account and i have the same issue ... Also,i used VPN too,the problem didnt disappear.

**Comment by dansali** [comment]
How about try and create a new account and use a VPN with that account rather than using the same IP? It could be a softban with your IP address.

**Comment by Rick058** [comment]
What 'temporarily' fixed this error in my case:
1) I disabled my proxy in auth.json 
2) Started the bot, it still decided to loop so I changed up my coördinations back to Central Park, NY
3) Starting the bot again, still loops ... connecting to my VPN and it seems to work again!
4) Disabled my VPN after the 45/45 finished and it works completely fine on my own IP again.
... 20 minutes running now and no problems while running **one** bot.
5) Starting bot 2 on the same config.json as bot 1, softban unban starts right away.
6) Bot 2 works after the 45/45 soft ban, still playing on my **own** IP!
7) Bot 1 now running for 40 minutes, bot 2 for 20 minutes - starting bot 3 now.
_Will update when it stops, this seemed to work fine for me. Might worth a try, VPN services as hide.me vpn or cyberghost vpn are free and worked for me_

**Comment by aaron25th** [comment]
im running 6 bots fine now i think its niantic servers because pokestops aren't loading on my phone

**Comment by nfettinger** [comment]
Closing because it sounds like the issue has been identified as not a code problem

**Comment by PokeyMasta** [comment]
so how do you disable it? this is mine atm

{
  "AuthType": "google",
  "GoogleUsername": "",
  "GooglePassword": "",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "galaxy6",
  "DeviceId": "002c7e3954fd15d1",
  "AndroidBoardName": "universal7420",
  "AndroidBootloader": "G920FXXU3DPEK",
  "DeviceBrand": "samsung",
  "DeviceModel": "zeroflte",
  "DeviceModelIdentifier": "SM-G920F",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "samsungexynos7420",
  "FirmwareBrand": "zerofltexx",
  "FirmwareTags": "dev-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/zerofltexx/zeroflte:6.0.1/MMB29K/G920FXXU3DPEK:user/release-keys"
