### ISSUE TITLE
No 'incense' settings...

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3257]
I was wandering inside config file, and i saw that 'incense' usage is not into settings. Can you implement this function?  :+1:

**Comment by nfettinger** [comment]
What is aroma?

**Comment by Profetorum** [comment]
Sorry man, i'm italian, i have corrected title and 3d

**Comment by Aneduna** [comment]
"UseIncenseConstantly": true,

Or do you want any other logic?

**Comment by Profetorum** [comment]
Ok, fail. Sorry i failed. :dancers:
