### ISSUE TITLE
(Attention)Pokemon Inventory is full, transferring...

### ISSUE THREAD

**Issue by xAznboyszx** [NECROBOTIO/NecroBot#3259]
For those having this error, simply increase your KeepMinCp. I've noticed that even if you were to increase your KeepMinIV and set PrioritizeIvOverCp to true, it simply makes no difference. Hope this helps anyone else that's having this issue

**Comment by Aneduna** [comment]
Why open an issue when there is no issue?

Every config help is supposed to go to discord anyways!

**Comment by nfettinger** [comment]
This is not the place for announcements or config issues.
Closing as off-topic.
