### ISSUE TITLE
[Bug] Necrobot client has stopped working "Unhandled exception"

### ISSUE THREAD

**Issue by progz** [NECROBOTIO/NecroBot#3260]
Everything was working right when it bugs.
![necrobot](https://cloud.githubusercontent.com/assets/510107/17487874/17ed9970-5d97-11e6-90dc-4844c93b75d8.JPG)

The bot was launched since 1 hour.
Version : 0.7.6
Config.json : [Link](http://pastebin.com/Bk29L1Kz)

It's the first time, it happens. I use necrobot multiple hour a day and work perfectly.

Need more informations ? Ask :)

**Comment by nfettinger** [comment]
Is this issue reproducible?

**Comment by Nilrem711** [comment]
Same Problem, after ~2H same problem every time 
after a restart its working again

**Comment by progz** [comment]
I can't reproduce. I Try but it won't.
I think you can close this issue, I will comment again in it if I found something.

**Comment by Sutkuss** [comment]
Same here. This bug appears only when bot runs for a longer period of time. I get this in log after the crash:
**[23:35:44] Exceptiion caught, writing LogBuffer.**

**Comment by nfettinger** [comment]
This is a catch for an invalid server response. Duplicate.
