### ISSUE TITLE
snip error "the websocket protocol is not supported on this platform

### ISSUE THREAD

**Issue by cador69** [NECROBOTIO/NecroBot#3262]
i cant use snip

system.paltformnotsupportedexception : the websocter protocol is not support on this platform.
at system.net.websockets.clientwebsocet..ctor<>
at pogolocationfeeder.repository.pokezzrarepokemonrepository.<startclient>d__7.movenext<>

erorr

**Comment by Aneduna** [comment]
What os are you using?

**Comment by cador69** [comment]
w7 ..

before API update its work ...

**Comment by nfettinger** [comment]
Please include additional information about your system

**Comment by Aneduna** [comment]
Are you running Necrobot as Administrator?
Are you using an additional firewall/ what are your settings for the firewall?

**Comment by cador69** [comment]
im running as admin
not using add firewall.. private setting

.exe what ??
PogoLocationFeeder / necrobot ?

**Comment by cador69** [comment]
![image](https://cloud.githubusercontent.com/assets/20692826/17488565/237e4956-5dc4-11e6-8ced-92478fce1611.png)

![image](https://cloud.githubusercontent.com/assets/20692826/17488590/3e9414c8-5dc4-11e6-8991-95f0c1855072.png)

**Comment by Aneduna** [comment]
@nfettinger I don't see the error, but every System information was given i could think of.

**Comment by Linewalker** [comment]
It's a PokeFeeder problem. I would probably say, update to SP1 and then install the latest Framework 4.5 update.

**Comment by cador69** [comment]
ok i'll test

**Comment by nfettinger** [comment]
Since this is an issue with the platform, and not with NecroBOT, I am closing this issue. Feel free to create a new one if you find more useful information, or an actual bug in the bot.
