### ISSUE TITLE
Your maximum items combined is over your max item storage

### ISSUE THREAD

**Issue by refix** [NECROBOTIO/NecroBot#3265]
(ERROR) [Configuration Invalid] Your maximum items combined (balls+po
tions+revives=1000) is over your max item storage (350)
(ATTENTION) Press any key to exit, then fix your configuration and ru
n the bot again.

Is there a fix for this without shredding my entire inventory? You can still collect items from stops if your bag is full if you've never logged into the game. Any help?

**Comment by progz** [comment]
It's a config problem. Please go to discord to get support : https://discord.gg/VXKxNFr

**Comment by Aneduna** [comment]
I'm not sure if it is implemented to let the combined items be over your max items, because the situation is very rare and only minimally useful.

@progz it is more of a feature request for a new Config option i think

**Comment by refix** [comment]
Is it possible to compile my own version without this limit?

**Comment by Aneduna** [comment]
Go into LoginState.cs and comment lines 140 to 146
(may work, not tested)

**Comment by Aneduna** [comment]
I just saw
```
if ((session.Profile.PlayerData.MaxItemStorage * session.LogicSettings.RecycleInventoryAtUsagePercentage/100.0f) > currentTotalItems)
                return;
```
in RecycleItemsTask.cs

So it should not recycle if over 100% Inventory. So your problem might not exist?

**Comment by nfettinger** [comment]
This is a configuration issue.
