### ISSUE TITLE
pokemon lvl

### ISSUE THREAD

**Issue by jinjinjin2** [NECROBOTIO/NecroBot#3267]
Hello friends,

using the bot forst time and it is great. Super workd done here. But i cant find any description what the pokemon lvl is for. Is it an important info? where does it come from? what is max lvl? 

Sorry for maybe a stupid question...

**Comment by marnixx9** [comment]
If you are level 20, the max level wild pokemon you will find is 20. The Higher the level the higher the CP. Let's say an level 20 growlithe is between 700 and 750. If you catch a level 20 grow with 100%iv you will get 750cp. The higher the level and the higher the IV how better it is

**Comment by marnixx9** [comment]
You will never find an level 1 magikarp that has 200cp. So ye

**Comment by jinjinjin2** [comment]
thanks a lot
