### ISSUE TITLE
NecroBot V0.7.6 stuck on Logging in Using Google

### ISSUE THREAD

**Issue by Harry2101** [NECROBOTIO/NecroBot#3268]
Hey i just downloaded the 7.6 version and its my first time using this and i followed what it prompted and set up a google account (which was never used with pokemon go) and put custom coords and then it said Perfect You are using the newest version 0.7.6 .
and then it says 
(INFO) Logging in using Google

and its been on this^ for a while... 
any help please? 
TIA

**Comment by Profetorum** [comment]
Restart Necro.

Anyways, it's a temp solution obv, but it's a minor bug

**Comment by furthurr** [comment]
i have the same bug .. i am run the bot with mac and wine

**Comment by Harry2101** [comment]
Thank you @Profetorum  !!! Restarting worked.... lol
