### ISSUE TITLE
run bot on mac with wine

### ISSUE THREAD

**Issue by furthurr** [NECROBOTIO/NecroBot#3270]
i am using wine ... with winetricks i was installed net4.5.2 and net verifier but when i run the bot the bot pass of :

(INFO) Logging in using Google

i need some dll for this???

**Comment by Harry2101** [comment]
same problem ... :(

**Comment by dansali** [comment]
I tried using Mono on a Ubuntu Server with this, however it seemed to stop right after Logging in section too. I think it might have something to do with the title of the program? Maybe if we compiled it without the title containing all the information it might work...

**Comment by akeenDeveloper** [comment]
Why don´t you install a virtual machine with vmware?
I used it, it works!

**Comment by nfettinger** [comment]
This is not the place for platform talk unless you have specific code changes to make compilation more compatible. Please take further issues to our Discord chat rooms.
