### ISSUE TITLE
[FEATURE REQUEST] Stop exp when an high iv pkm can be sniped

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3271]
It's possibile to modify config in order to stop exping when a 95+ iv (example) can be sniped (and then making it back to exp) ??
 I don't think so...
Would be a nice idea

**Comment by Psifour** [comment]
Just lower the minimum time between sniping and it will check more often for possible snipes (which should have good results if you aren't in channels with trash being posted).
