### ISSUE TITLE
Lootban

### ISSUE THREAD

**Issue by fatto92** [NECROBOTIO/NecroBot#3272]
Hello, so i get this on all my accounts "Looting failed, possible softban. Unban in: 1/45" it continues and never unbans me...anyone knows? anyone that got this aswell?

regards, fatto

**Comment by vingesus** [comment]
Might be an IP softban, try another IP (Use proxy or vpn) :)

**Comment by fatto92** [comment]
mind helping me with another IP? :)

**Comment by vingesus** [comment]
Yes i do, sorry - Use a free vpn client ( google that shit ), or find a working proxy and use it in your auth.json file :)

**Comment by fatto92** [comment]
ok, thank you!

**Comment by LikeSundayLikeRain** [comment]
It's more like account related. If you try to restart the bot, it will tell you there's no poke stop. I've running multiple bot on my machine, some of them don't have that issue.
I wonder if Niantic add a api call limit.

**Comment by fatto92** [comment]
was IP related! thank you vingesus!
