### ISSUE TITLE
[Suggestion] BOT Manager

### ISSUE THREAD

**Issue by ObsessedHacker** [NECROBOTIO/NecroBot#3274]
Since most of the users who use NecroBOT has more than one account, I thought it will be great if somehow there was a BOT manager that have nice GUI and easily changeable settings.

A bot manager that allows you to add a bot, change, restart every X minutes, report for crashes, shortcuts and etc...

Something like:

![](http://uploads.tapatalk-cdn.com/20160807/c18c6b8548dbe5b7f65642550d182f74.jpg)

**Comment by pehur** [comment]
I second this.

**Comment by nisanb** [comment]
I third this

**Comment by nfettinger** [comment]
This would be better supported by using a different repository.

**Comment by ObsessedHacker** [comment]
The point in this suggestion is that we are able to use and edit one or create a separate config file for each for, which is amazing!

**Comment by EriCLownbomb** [comment]
good suggestion

**Comment by nfettinger** [comment]
Spoke with the Developers. This is NOT a feature worth supporting.
