### ISSUE TITLE
[Fix] Sniping scan of a location

### ISSUE THREAD

**Issue by daouid** [NECROBOTIO/NecroBot#3275]
Sniping seems to give up too early of fail to properly scan for pokemon.

Detected:
 by running multiple instances of NecroBot and a single sniping server

Symptoms: 
some bots fail to see Pokemon to snipe and give up while others, for the same pokemon in the same location successfully find them.

Possible fix:
 if time based: increase delay
or 
 if result based: number of loops of scan

**Comment by daouid** [comment]
https://i.imgur.com/IcfWXhW.png

**Comment by PokemasterMike** [comment]
same for me... with pokezz api down using pogofeeder doenst bring any results...

**Comment by dontmesswithfreitag** [comment]
same here, some fix would be good.
from nox i have noticed that you need to stay in the new location for a couple of seconds before pokemons appear.

**Comment by PokemasterMike** [comment]
[19:30:50] Skipped Sandshrew
[19:30:50] Name: Palisades 1935 Bridge XP: 50, Gems: 0, Items: 1 x ItemRazzBerry, 1 x ItemMaxRevive, 1 x ItemSuperPotion, Lat: 34.0151, Long: -118.499998
[19:30:50] Sniping a Snorlax with Unknown IV at 40.54737,-74.176061...
[19:30:52] Traveling to Pokestop: The Christian Institute (145m) (17 seconds)

**Comment by Marsinator** [comment]
ill mark it as potential bug, let the devs take a look
