### ISSUE TITLE
A way to disable automatic incubating with basic incubators

### ISSUE THREAD

**Issue by CreativiTimothy** [NECROBOTIO/NecroBot#3276]
The bot is indeed hatching my eggs, but it's wasting my basic incubators (3-time use) on 2km eggs. An option to disable that would be really helpful! Ideally, the default setting should be only use the permanent incubator imo. Thank you!

**Comment by Marsinator** [comment]
the bot uses 10km>5km>2km eggs for basic incubators and 2km>5km>10km for the infinite

**Comment by CreativiTimothy** [comment]
?Ok, I understand. But no option to disable it?
