### ISSUE TITLE
Suggestion: New parameter in config... "RatePokemonOnly"

### ISSUE THREAD

**Issue by Morthym** [NECROBOTIO/NecroBot#3278]
say, I only want to "check" the Pokemons in my account, without opening each one in the Game to check the stats, copy them into an Excel-sheet etc.

When the "RatePokemonOnly" param is true, only the starting table connected to "AmountOfPokemonToDisplayOnStart" is shown.

Possible?

**Comment by Marsinator** [comment]
not needed. we do have dumps for that.

**Comment by Morthym** [comment]
do you have an explanation or a link to a wiki for the "dumps"? ty
