### ISSUE TITLE
Transferfilter not all moves recognized

### ISSUE THREAD

**Issue by Byte-M3** [NECROBOTIO/NecroBot#3280]
I am trying to transfer pokemon based on their moves. I havent been able to figure out what's going on exactly, most moves work fine, some moves are not recognized.

These moves crash the software:
"firefang",
"mudslap",
"bubble",
Maybe there are more, I haven't tried them all yet.

**Comment by Brewfasa** [comment]
Mudslap works fine for me havent tested the rest

**Comment by Byte-M3** [comment]
can you test with rhydon?

**Comment by Marsinator** [comment]
http://pastebin.com/FWkSuDwT

Please use the names from this list

**Comment by Byte-M3** [comment]
Solved, didn't know the correct syntax of some moves.

**Comment by ruchern** [comment]
@Marsinator Which ones to look at?
