### ISSUE TITLE
International characters shown wrong

### ISSUE THREAD

**Issue by DBa2016** [NECROBOTIO/NecroBot#3281]
At least German characters (and accents in "Pokéball" etc.) are shown wrong, see attached screeshot.
![natchars](https://cloud.githubusercontent.com/assets/20729632/17489895/961caaf8-5da0-11e6-8cc2-38b3280c184d.png)

**Comment by Epinikion** [comment]
u can change the used font in cmd to e.g. "Consolas" which will show the right Umlaut even in Pokestop names.

right click cmd title -> settings -> font -> choose "Consolas" (I use Consolas at 14pt)

**Comment by DBa2016** [comment]
You are right, my bad.
