### ISSUE TITLE
[Feature Request] Account Info dump

### ISSUE THREAD

**Issue by khangdpham** [NECROBOTIO/NecroBot#3282]
Since Pokeadvisor is gone. It would be nice if we can have a data dump file on-the-go showing info:
- Level , Stardusts 
- Pokemon lists, CP and IV
- Inventory

**Comment by Psifour** [comment]
Set  "DumpPokemonStats": true
and the dump of your pokemon will be in a folder called Dumps in your necrobot folder.

Level, Stardust, and Inventory are pointless from my perspective as Level doesn't change rapidly, stardust should always be high enough to not matter, and your inventory should be almost identical to the limits you set for the bot to keep.

**Comment by nfettinger** [comment]
You can also view this information using the visualizer.
