### ISSUE TITLE
Help config getting softban..

### ISSUE THREAD

**Issue by Lowerman** [NECROBOTIO/NecroBot#3285]
> {
>   "TranslationLanguageCode": "pt-br",
>   "AutoUpdate": true,
>   "TransferConfigAndAuthOnUpdate": true,
>   "UseWebsocket": false,
>   "StartupWelcomeDelay": false,
>   "AmountOfPokemonToDisplayOnStart": 10,
>   "ShowPokeballCountsBeforeRecycle": true,
>   "CatchPokemon": true,
>   "AutomaticallyLevelUpPokemon": false,
>   "AmountOfTimesToUpgradeLoop": 5,
>   "GetMinStarDustForLevelUp": 5000,
>   "LevelUpByCPorIv": "iv",
>   "UpgradePokemonCpMinimum": 1000.0,
>   "UpgradePokemonIvMinimum": 95.0,
>   "UpgradePokemonMinimumStatsOperator": "and",
>   "DisableHumanWalking": false,
>   "DefaultLatitude": 40.778915,
>   "DefaultLongitude": -73.962277,
>   "WalkingSpeedInKilometerPerHour": 31.0,
>   "MaxSpawnLocationOffset": 10,
>   "DelayBetweenPlayerActions": 5000,
>   "DelayBetweenPokemonCatch": 2000,
>   "DumpPokemonStats": false,
>   "EvolveAboveIvValue": 95.0,
>   "EvolveAllPokemonAboveIv": false,
>   "EvolveAllPokemonWithEnoughCandy": true,
>   "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
>   "KeepPokemonsThatCanEvolve": false,
>   "KeepMinCp": 1250,
>   "KeepMinIvPercentage": 90.0,
>   "KeepMinLvl": 6,
>   "KeepMinOperator": "or",
>   "UseKeepMinLvl": false,
>   "PrioritizeIvOverCp": false,
>   "KeepMinDuplicatePokemon": 2,
>   "UseGpxPathing": false,
>   "GpxFile": "GPXPath.GPX",
>   "VerboseRecycling": true,
>   "RecycleInventoryAtUsagePercentage": 90.0,
>   "UseEggIncubators": true,
>   "UseLuckyEggConstantly": false,
>   "UseLuckyEggsMinPokemonAmount": 30,
>   "UseLuckyEggsWhileEvolving": false,
>   "UseIncenseConstantly": false,
>   "UseBerriesMinCp": 1000,
>   "UseBerriesMinIv": 90.0,
>   "UseBerriesBelowCatchProbability": 0.2,
>   "UseBerriesOperator": "or",
>   "UseSnipeOnlineLocationServer": true,
>   "UseSnipeLocationServer": true,
>   "SnipeLocationServer": "localhost",
>   "SnipeLocationServerPort": 16969,
>   "GetSniperInfoFromPokezz": true,
>   "GetOnlyVerifiedSniperInfoFromPokezz": true,
>   "MinPokeballsToSnipe": 0,
>   "MinPokeballsWhileSnipe": 0,
>   "MinDelayBetweenSnipes": 5000,
>   "SnipingScanOffset": 0.003,
>   "SnipeAtPokestops": true,
>   "SnipeIgnoreUnknownIv": false,
>   "UseTransferIvForSnipe": false,
>   "SnipePokemonNotInPokedex": false,
>   "RenamePokemon": false,
>   "RenameOnlyAboveIv": true,
>   "RenameTemplate": "{1}_{0}",
>   "MaxPokeballsPerPokemon": 10,
>   "MaxTravelDistanceInMeters": 1000,
>   "TotalAmountOfPokeballsToKeep": 120,
>   "TotalAmountOfPotionsToKeep": 80,
>   "TotalAmountOfRevivesToKeep": 60,
>   "TotalAmountOfBerriesToKeep": 50,
>   "UseGreatBallAboveCp": 1000,
>   "UseUltraBallAboveCp": 1250,
>   "UseMasterBallAboveCp": 1500,
>   "UseGreatBallAboveIv": 85.0,
>   "UseUltraBallAboveIv": 95.0,
>   "UseGreatBallBelowCatchProbability": 0.2,
>   "UseUltraBallBelowCatchProbability": 0.1,
>   "UseMasterBallBelowCatchProbability": 0.05,
>   "EnableHumanizedThrows": false,
>   "NiceThrowChance": 40,
>   "GreatThrowChance": 30,
>   "ExcellentThrowChance": 10,
>   "CurveThrowChance": 90,
>   "ForceGreatThrowOverIv": 90.0,
>   "ForceExcellentThrowOverIv": 95.0,
>   "ForceGreatThrowOverCp": 1000,
>   "ForceExcellentThrowOverCp": 1500,
>   "TransferWeakPokemon": false,
>   "TransferDuplicatePokemon": true,
>   "TransferDuplicatePokemonOnCapture": true,
>   "FavoriteMinIvPercentage": 95.0,
>   "AutoFavoritePokemon": true,
>   "UsePokemonToNotCatchFilter": false,
>   "UsePokemonSniperFilterOnly": false,
>   "WebSocketPort": 14251,
>   "ItemRecycleFilter": [
>     {
>       "Key": "itemUnknown",
>       "Value": 0
>     },
>     {
>       "Key": "itemLuckyEgg",
>       "Value": 200
>     },
>     {
>       "Key": "itemIncenseOrdinary",
>       "Value": 100
>     },
>     {
>       "Key": "itemIncenseSpicy",
>       "Value": 100
>     },
>     {
>       "Key": "itemIncenseCool",
>       "Value": 100
>     },
>     {
>       "Key": "itemIncenseFloral",
>       "Value": 100
>     },
>     {
>       "Key": "itemTroyDisk",
>       "Value": 100
>     },
>     {
>       "Key": "itemXAttack",
>       "Value": 100
>     },
>     {
>       "Key": "itemXDefense",
>       "Value": 100
>     },
>     {
>       "Key": "itemXMiracle",
>       "Value": 100
>     },
>     {
>       "Key": "itemSpecialCamera",
>       "Value": 100
>     },
>     {
>       "Key": "itemIncubatorBasicUnlimited",
>       "Value": 100
>     },
>     {
>       "Key": "itemIncubatorBasic",
>       "Value": 100
>     },
>     {
>       "Key": "itemPokemonStorageUpgrade",
>       "Value": 100
>     },
>     {
>       "Key": "itemItemStorageUpgrade",
>       "Value": 100
>     }
>   ],
>   "PokemonsNotToTransfer": [
>     "venusaur",
>     "charizard",
>     "blastoise",
>     "clefable",
>     "muk",
>     "chansey",
>     "gyarados",
>     "ditto",
>     "snorlax",
>     "articuno",
>     "zapdos",
>     "moltres",
>     "dragonite",
>     "mewtwo",
>     "mew"
>   ],
>   "PokemonsToEvolve": [
>     "caterpie",
>     "weedle",
>     "pidgey",
>     "rattata"
>   ],
>   "PokemonsToIgnore": [
>     "caterpie",
>     "weedle",
>     "pidgey",
>     "rattata",
>     "spearow",
>     "zubat",
>     "doduo"
>   ],
>   "PokemonsTransferFilter": {
>     "Golduck": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Farfetchd": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Krabby": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Kangaskhan": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Horsea": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Staryu": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "MrMime": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Scyther": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Jynx": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Electabuzz": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Magmar": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Pinsir": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Tauros": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Magikarp": {
>       "KeepMinCp": 150,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Gyarados": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Lapras": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Eevee": {
>       "KeepMinCp": 600,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Vaporeon": {
>       "KeepMinCp": 1600,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 4,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Jolteon": {
>       "KeepMinCp": 1600,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 4,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Flareon": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Porygon": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Snorlax": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     },
>     "Dragonite": {
>       "KeepMinCp": 1000,
>       "KeepMinLvl": 6,
>       "UseKeepMinLvl": false,
>       "KeepMinIvPercentage": 60.0,
>       "KeepMinDuplicatePokemon": 2,
>       "Moves": [],
>       "KeepMinOperator": "or",
>       "MovesOperator": "or"
>     }
>   },
>   "PokemonToSnipe": {
>     "Locations": [
>       {
>         "Latitude": 38.556807486461118,
>         "Longitude": -121.2383794784546
>       },
>       {
>         "Latitude": -33.859019,
>         "Longitude": 151.213098
>       },
>       {
>         "Latitude": 47.5014969,
>         "Longitude": -122.0959568
>       },
>       {
>         "Latitude": 51.5025343,
>         "Longitude": -0.2055027
>       }
>     ],
>     "Pokemon": [
>       "venusaur",
>       "charizard",
>       "blastoise",
>       "beedrill",
>       "raichu",
>       "sandslash",
>       "nidoking",
>       "nidoqueen",
>       "clefable",
>       "ninetales",
>       "golbat",
>       "vileplume",
>       "golduck",
>       "primeape",
>       "arcanine",
>       "poliwrath",
>       "alakazam",
>       "machamp",
>       "golem",
>       "rapidash",
>       "slowbro",
>       "farfetchd",
>       "muk",
>       "cloyster",
>       "gengar",
>       "exeggutor",
>       "marowak",
>       "hitmonchan",
>       "lickitung",
>       "rhydon",
>       "chansey",
>       "kangaskhan",
>       "starmie",
>       "mrMime",
>       "scyther",
>       "magmar",
>       "electabuzz",
>       "jynx",
>       "gyarados",
>       "lapras",
>       "ditto",
>       "vaporeon",
>       "jolteon",
>       "flareon",
>       "porygon",
>       "kabutops",
>       "aerodactyl",
>       "snorlax",
>       "articuno",
>       "zapdos",
>       "moltres",
>       "dragonite",
>       "mewtwo",
>       "mew"
>     ]
>   },
>   "PokemonToUseMasterball": [
>     "articuno",
>     "zapdos",
>     "moltres",
>     "mew",
>     "mewtwo"
>   ]
> }

**Comment by Marsinator** [comment]
"WalkingSpeedInKilometerPerHour": 31.0,

try changing this to 15.

close the bot and wait for 10 minutes, then open it up again.

**Comment by Lowerman** [comment]
any idea to farm faster ?

**Comment by PokemasterMike** [comment]
dont ask here, ask in the discord !!!

**Comment by Lowerman** [comment]
still I get softban ..

**Comment by Psifour** [comment]
Not a code issue. Please mark invalid.

@Lowerman Many knowledgeable people are available in discord to assist you with configuring the bot.

**Comment by iwantmyfile5** [comment]
As the OP of the thread you should have the option to close the issue.

**Comment by dansali** [comment]
Should be top right corner of your screen on github to "close issue"
