### ISSUE TITLE
Necrobot doesn't transfer pokemons

### ISSUE THREAD

**Issue by Clid1337** [NECROBOTIO/NecroBot#3287]
Hello, my bot doesn't transfer any pokemons. I already have had this problem, but when i changed config, it started working, but now it's back. Do you have any ideas or configs?

**Comment by Profetorum** [comment]
Do you recognize your problem in this?
#3283

**Comment by Clid1337** [comment]
No, i have a message "pokemon inventory is full,transfering..." and when i change my config it trasfers many pokemons. No idea :/

**Comment by nfettinger** [comment]
Since others are able to transfer Pokemon correctly, I must assume this is a configuration issue. Please seek additional help using the Discord chat rooms.
