### ISSUE TITLE
running in Ubuntu?

### ISSUE THREAD

**Issue by shaoli12800** [NECROBOTIO/NecroBot#3289]

**Comment by Psifour** [comment]
As far as I can see this should run easily under wine. However posting as an issue when you haven't confirmed there is one is a misuse of this system. I may switch to my other partition later and check.

**Comment by Marsinator** [comment]
please come back when its confirmed not working in wine

**Comment by tenzing1984** [comment]
Sorry. We needed to config the file first. Connecting to Google Cloud Database. 
The error page vanish in 1 second. So it looked like it crashed. Sorry again for wasting time devs.

Cheers!

**Comment by dansali** [comment]
I originally had this running on 0.6 before the whole unknown6 thing, mono seemed to run it and freeze at the login section (my guess is the title of the program can't be changed on linux?)

This is the error I get now


> Unhandled Exception:
> System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.7.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
> File name: 'PoGo.NecroBot.Logic, Version=0.7.6.0, Culture=neutral, PublicKeyToken=null'
> [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.7.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
> File name: 'PoGo.NecroBot.Logic, Version=0.7.6.0, Culture=neutral, PublicKeyToken=null'
>

**Comment by nfettinger** [comment]
Update submodules.

**Comment by michaelvdnet** [comment]
It seems to be that [The assembly loader used (FodyCostura)](https://github.com/Fody/Costura) doesn't support linux yet.

Will see if I can make a work around later tomorrow.

**Comment by qwert95** [comment]
@michaelvdnet nice, keep us updated :)
anyway, what is better is compiling in windows and trying to run with mono or directly build on linux with mono's xbuild?

**Comment by michaelvdnet** [comment]
@qwert95 Don't think that should matter

**Comment by michaelvdnet** [comment]
Alright, just including the raw libraries doesn't seem to really do it, next error:

```
[12:48:18] () Exceptiion caught, writing LogBuffer.
exception inside UnhandledException handler: (null)

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type                                                                                        initializer for 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exce                                                                                       ption. ---> System.InvalidOperationException: Operation is not valid due to the                                                                                        current state of the object.
  at System.Net.Http.HttpClientHandler.set_Proxy (IWebProxy value) <0x41a93930 +                                                                                        0x00077> in <filename unknown>:0
  at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor () <0x41a93650 + 0x                                                                                       000af> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at PokemonGo.RocketAPI.Client..ctor (ISettings settings, IApiFailureStrategy a                                                                                       piFailureStrategy) <0x41a92d40 + 0x000bb> in <filename unknown>:0
  at PoGo.NecroBot.Logic.State.Session.Reset (ISettings settings, ILogicSettings                                                                                        logicSettings) <0x41a92b00 + 0x0009f> in <filename unknown>:0
  at PoGo.NecroBot.Logic.State.Session..ctor (ISettings settings, ILogicSettings                                                                                        logicSettings) <0x41a4a010 + 0x00123> in <filename unknown>:0
  at PoGo.NecroBot.CLI.Program.Main (System.String[] args) <0x419b7720 + 0x0057b                                                                                       > in <filename unknown>:0
```

**Comment by michaelvdnet** [comment]
```
[14:18:49] () Exception caught, writing LogBuffer.
exception inside UnhandledException handler: (null)

[ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Specified method is not supported.
  at System.TermInfoDriver.set_WindowWidth (Int32 value) <0x7f49ed0768d0 + 0x00032> in <filename unknown>:0
  at System.ConsoleDriver.set_WindowWidth (Int32 value) <0x7f49ed0615f0 + 0x0003b> in <filename unknown>:0
  at System.Console.set_WindowWidth (Int32 value) <0x7f49ed060440 + 0x0000c> in <filename unknown>:0
  at PoGo.NecroBot.CLI.Resources.ProgressBar.fill (Int32 amt, ConsoleColor barColor) <0x409eb540 + 0x00064> in <filename unknown>:0
  at PoGo.NecroBot.CLI.Resources.ProgressBar.start (System.String startText, Int32 startAmt) <0x409eb060 + 0x0005f> in <filename unknown>:0
  at PoGo.NecroBot.CLI.Program.Main (System.String[] args) <0x408ea1b0 + 0x009eb> in <filename unknown>:0
```

Mono doesn't support this.

Remove line 30 and 32 of [this](https://github.com/NECROBOTIO/NecroBot/blob/master/PoGo.NecroBot.CLI/Resources/ProgressBar.cs) file.

**Comment by michaelvdnet** [comment]
Program requires kernel32, should have known it...

There is no easy work around to get linux.

**Comment by qwert95** [comment]
Well, a lot of people here asked to run on linux because of the raspberry pi boards and similar products, so getting a Win 10 IoT working version would be anyway great if not as useful.
Or am I asking for too much work? :smile: I'm not a C# guy unluckily.

**Comment by nikhiljha** [comment]
I added all required libs and I'm getting this now:

```
Symbol file is not a valid
StackTrace:
  at Mono.CompilerServices.SymbolWriter.MonoSymbolFile..ctor (System.IO.Stream stream) <0x7fda2a40 + 0x002bf> in <filename unknown>:0
```

I don't like that this was written in C# but whatever.

**Comment by michaelvdnet** [comment]
@qwert95 Well if C# and .NET run on IoT (never used it) then this program will probably too, given the required toolset is available for IoT.
The only reason it's currently not running under linux is because it needs windows only dll's to work.

**Comment by napstr** [comment]
There were people who had trouble with even building it in mono.
Here is a fork that should build in mono:
[](https://github.com/napstr/NecroBot)

I used `nuget restore` to get the dependencies into the project and then ran `xbuild "NecroBot for Pokemon Go.sln"`

Here is a Rocket API fork that uses @michaelvdnet ' [fix](https://github.com/NECROBOTIO/NecroBot/issues/3289#issuecomment-238615898) 
[](https://github.com/napstr/NecroBot-Rocket-API)

This makes the bot go this far:
![](https://puu.sh/qvIE6/2d91ab812c.png)
where indeed in starts calling stuff from kernel32.dll and fails.

**Comment by qwert95** [comment]
Cool, nice work. :panda_face: 

For the guys who use the Necrobot discord's chat : when someone comes in #development and asks about linux support or shows he wants to make some tests, please link to him this issue page so we can keep all the "linux stuff" in one place.

**Comment by Gius95** [comment]
@napstr Can you please try if method WebClientExtensions.DownloadString works correctly? I'm using your forked repo, but my raspberry crash on every kind of download because can't verify TLS certs.

**Comment by jaimerson** [comment]
Ubuntu user here, couldn't run on wine, used virtualbox with windows just fine. For a headless solution, maybe vagrant: http://aka.ms/vagrant-win7-ie8

**Comment by SaubereSacheLP** [comment]
Could the developer please implement this into the public solution?

**Comment by michaelvdnet** [comment]
RtlFillMemory is basically an odd proxy around memset, which in turn should be either C#able or could be multiplatformed for linux

**Comment by Aquilum** [comment]
So why not explore using the entirely managed encryption library at (https://github.com/zone117x/pokemongo-encrypt-sharp)? Integration looks to be a fairly straightforward change to the FeroxRev submodule.

**Comment by AmazingGamerBoy** [comment]
@jaimerson I've tried to install virtually but it did not work. Could you please share how you installed it please?

**Comment by jaimerson** [comment]
@AmazingGamerBoy I installed it on a Windows 10 machine on VirtualBox and it ran just like described on the wiki. I'm using Ubuntu 16.04.

**Comment by AmazingGamerBoy** [comment]
Ok thanks

**Comment by AmazingGamerBoy** [comment]
@jaimerson Thank you so much! It worked for me! Much appreciated!

**Comment by AmazingGamerBoy** [comment]
Now i'm running into a different problem. Kernel drivers are not loading or downloading.

**Comment by AmazingGamerBoy** [comment]
Anyone who can fix this problem for me, I will give them my vps to run their bot 24/7 for an entire month. The vps has 6gb ram, 30gb storage, cpu fair shair, and 10gbit/s internet. Please contact me if you want to help me get the bot working. Thanks, and remember i got to level 30 in 3 days.

**Comment by michaelvdnet** [comment]
This is not a linux help thread @AmazingGamerBoy

**Comment by KevinCollmer** [comment]
Closed. Due to the latest commit a few seconds ago.
