### ISSUE TITLE
Berry

### ISSUE THREAD

**Issue by Strichel** [NECROBOTIO/NecroBot#3291]
Berry system seems not workking.
Whatever u put in there, it throws berries on every pokemon or on no pokemon

**Comment by Marsinator** [comment]
please post the relevant parts of your config and provide a screenshot where the rules you put were not applied

**Comment by Strichel** [comment]
"UseBerriesMinCp": 1000,

  "UseBerriesMinIv": 90.0,

  "UseBerriesBelowCatchProbability": 0.2,

  "UseBerriesOperator": "or",

 

Von: Marsinator [mailto:notifications@github.com] 
Gesendet: Montag, 8. August 2016 20:28
An: NECROBOTIO/NecroBot
Cc: Strichel; Author
Betreff: Re: [NECROBOTIO/NecroBot] Berry (#3291)

 

please post the relevant parts of your config and provide a screenshot where the rules you put were not applied

**Comment by nfettinger** [comment]
This is a configuration issue. Please use discord chat for additional help.
