### ISSUE TITLE
Wtf ! Spam issues

### ISSUE THREAD

**Issue by Naografix** [NECROBOTIO/NecroBot#3293]
See that : http://i.imgur.com/YKZ4C2v.png

**Comment by Marsinator** [comment]
thats the niantic servers being unstable

**Comment by ben1122a** [comment]
I am having the same problem. I think it might have something to do with the pokemon go servers, and not necrobot. Could be wrong though.

**Comment by pehur** [comment]
Have the same problem on 2 gmail accounts, PTC seems to work fine
