### ISSUE TITLE
Problem with 0.7.6 after connecting to google

### ISSUE THREAD

**Issue by dematr** [NECROBOTIO/NecroBot#3294]
that's what it is saying:
 
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:ligne 135
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 36

**Comment by Marsinator** [comment]
niantic servers are unstable, wait for things to stabilize.

#3293
