### ISSUE TITLE
Error when loging in

### ISSUE THREAD

**Issue by NGDALI** [NECROBOTIO/NecroBot#3297]
[20:32:55] (ERROR) System.NullReferenceException: Az objektumhivatkozás nincs beállítva semmilyen objektumpéldányra.
   a következő helyen: PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() hely: C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs, sor: 408
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() hely: C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs, sor: 24
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() hely: C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs, sor: 16
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() hely: C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs, sor: 36

**Comment by Bunchhieng** [comment]
Server is currently down. https://pokemongostatus.org/

**Comment by ivanwing12** [comment]
Same

**Comment by gesshuh** [comment]
same here, server maybe

**Comment by Marsinator** [comment]
niantic servers are unstable. #3293 #3294 #3295

**Comment by nfettinger** [comment]
Server issue
