### ISSUE TITLE
Disconnects 

### ISSUE THREAD

**Issue by ReyVanJizz** [NECROBOTIO/NecroBot#3298]
Hey guys,

I'm getting since an hour the following disconnects.

The connection is first stable, then after a few seconds it disconnects.
[NecroBot-2016-08-08-20.txt](https://github.com/NECROBOTIO/NecroBot/files/407446/NecroBot-2016-08-08-20.txt)

Please see LogFile attached.

Any ideas?

regards

**Comment by nfettinger** [comment]
Server issue

**Comment by Marsinator** [comment]
servers are unstable. wait for this to end.

#3293 #3294 #3295 #3297
