### ISSUE TITLE
Syste.NullReferenceException

### ISSUE THREAD

**Issue by Meta28** [NECROBOTIO/NecroBot#3300]
Sometimes I keep getting this error, last time it happened after I ran out of regular pokeballs, and it didn't switch to greatballs or higher. Same code started to show up in different occasions but I can't remember which atm.

http://prntscr.com/c372e4

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

**Comment by Meta28** [comment]
Sry, delete
