### ISSUE TITLE
DeviceID always re-generated?

### ISSUE THREAD

**Issue by hancux** [NECROBOTIO/NecroBot#3302]
I understand that version 0.7.6 come with a new feature to generate android device information in auth.json (DeviceID, DeviceBrand, DeviceModel, etc).

However, I find it funny to see that DeviceID always re-generated everytime I run the exe. 
Does it make sense to always generate a new DeviceID everytime?

Thanks.

**Comment by Marsinator** [comment]
potential bug, forwarded to dev

**Comment by ruchern** [comment]
"DevicePackageName": "custom",

in Auth.json.

**Comment by iwantmyfile5** [comment]
Did you try this? It's from the release page for v0.7.6:
##IMPORTANT
Add the following to your auth.json file to not overwrite your current custom device information:
"DevicePackageName": "custom",

**Comment by Marsinator** [comment]
@ruchern: thats not a fix for the actual problem

**Comment by iwantmyfile5** [comment]
@Marsinator It might be intentional though, perhaps its coded to generate random ones so everyone isn't on the same device, and if you want to lock it, then you have to change the setting.

**Comment by ruchern** [comment]
@Marsinator Did you read v0.7.6 changelog?
