### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by Amf1** [NECROBOTIO/NecroBot#3303]
[21:42:07] (ERROR) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoGo.NecroBot.Logic.Inventory.<GetPlayerStats>d__24.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:строка 379
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в PoGo.NecroBot.Logic.Tasks.UseIncubatorsTask.<Execute>d__0.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\UseIncubatorsTask.cs:строка 29
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:строка 57
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:строка 36

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

**Comment by grjaznov** [comment]
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:строка 408
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:строка 24
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:строка 16
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() в C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:строка 36

**Comment by otong123** [comment]
same here

it always appear when i'm run the exe

when logging in , it appear
