### ISSUE TITLE
NullSystemReference 

### ISSUE THREAD

**Issue by SirWindfield** [NECROBOTIO/NecroBot#3308]
I get the Attention logging information that an error occurred followed by this message:
![screenshot_4](https://cloud.githubusercontent.com/assets/5113257/17491713/0e5a60a2-5da9-11e6-8b6e-ba73a34df7b8.png)

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

**Comment by sebab1** [comment]
I'm getting the same issue

**Comment by HomerunMonkey** [comment]
having this issue as well

**Comment by nfettinger** [comment]
Server issue

**Comment by quelladesoreta** [comment]
same here
