### ISSUE TITLE
ERROR frequently

### ISSUE THREAD

**Issue by sifmarcy** [NECROBOTIO/NecroBot#3309]
[ERROR.txt](https://github.com/NECROBOTIO/NecroBot/files/407462/ERROR.txt)

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

**Comment by sifmarcy** [comment]
So its related to Niantic server?

**Comment by dansali** [comment]
Yes the servers are unstable and that was the cause of the error messages
