### ISSUE TITLE
Device package name crash

### ISSUE THREAD

**Issue by Zierk59** [NECROBOTIO/NecroBot#3310]
Hi, how I can get my DevicePackageName from my own device? I have Sony Xperia M4 Aqua (E2303).
It's crashing for me. I am using google auth.
"DevicePackageName": "xperia-m4-aqua",

**Comment by dansali** [comment]
##IMPORTANT
Add the following to your auth.json file to not overwrite your current custom device information:
"DevicePackageName": "custom",

**Comment by dansali** [comment]
To change the device information in /Config/auth.json to YOUR personal device, you will need android-sdk with adb (and drivers for your phone). Here are the correlating values with the command to run to grab the value off your phone:
"DeviceId": "", // adb.exe shell settings get secure android_id
"AndroidBoardName": "", // adb.exe shell getprop ro.product.board
"AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader
"DeviceBrand": "", // adb.exe shell getprop ro.product.brand
"DeviceModel": "", // adb.exe shell getprop ro.product.model
"DeviceModelIdentifier": "", // adb.exe shell getprop ro.product.name
"DeviceModelBoot": "qcom",
"HardwareManufacturer": "", // adb.exe shell getprop ro.product.manufacturer
"HardwareModel": "", // adb.exe shell getprop ro.product.model
"FirmwareBrand": "", // adb.exe shell getprop ro.product.name
"FirmwareTags": "", // adb.exe shell getprop ro.build.tags
"FirmwareType": "", // adb.exe shell getprop ro.build.type
"FirmwareFingerprint": "" // adb.exe shell getprop ro.build.fingerprint

**Comment by Zierk59** [comment]
Facepalm. There is not info about DevicePackageName variable.

**Comment by dansali** [comment]
Yes that is correct

**Comment by nfettinger** [comment]
Closing as Off Topic
