### ISSUE TITLE
Make "Snipe to location" and "Snipe via pogolocationfeeder" work together?

### ISSUE THREAD

**Issue by qwer4790** [NECROBOTIO/NecroBot#3311]
When I set "snipeusinglocationserver" to true and feeder coords with pogolocationfeeder, "snipe to location" that was set in "Pokemon to snipe" section is not working, can we make them work together?

**Comment by Marsinator** [comment]
recent pogofeeder added pokezz. renders pokezz in necro redundant if both run at the same time.

depends on what the devs want to do with necro+feeder.

**Comment by qwer4790** [comment]
It looks like pokezz is not working in pogofeeder? It never returns any result.

**Comment by nfettinger** [comment]
We cannot help with issues pertaining to other sources.
