### ISSUE TITLE
Getting NullReference Exceptions

### ISSUE THREAD

**Issue by VirtualVirus** [NECROBOTIO/NecroBot#3312]
![image](https://cloud.githubusercontent.com/assets/20912047/17491803/c7e69690-5dc6-11e6-9250-b8d8104798af.png)

I tried understanding the code for inventory.cs but still not able to debug this.

Is this because the bot is referring to a pokemon that I deleted while playing the game through my phone.

**Comment by SirWindfield** [comment]
#3308

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

https://pokemongostatus.org/

**Comment by VirtualVirus** [comment]
Thanks for the update; closing this issue since its redundant.
