### ISSUE TITLE
[BUG] All pokeballs is recycled

### ISSUE THREAD

**Issue by iqbalsuzetta** [NECROBOTIO/NecroBot#3313]
sometimes i found system recycling all of  my pokeballs randomly

**Comment by dansali** [comment]
Double check your config, jump on discord. This is not an issue, this is not a chat room.

**Comment by iqbalsuzetta** [comment]
![image](https://cloud.githubusercontent.com/assets/18052839/17492041/570f936e-5dd4-11e6-9f3f-3a4d690c1a47.png)
like this

**Comment by dansali** [comment]
Raise   "TotalAmountOfPokeballsToKeep": 350, inside your config
