### ISSUE TITLE
Log Error (System.NullReferenceException)

### ISSUE THREAD

**Issue by bonxraw** [NECROBOTIO/NecroBot#3316]
Necrobot v.0.7.6
This shows up after login with google auth.

> [20:43:33] Spiele als censored
[20:43:34] Gehe sicher, dass Lat & Lng richtig sind. Schließe das Programm falls nicht! Lat: 40.7789165156211 Lng: -73.9623117943482
[20:43:34] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoGo.NecroBot.Logic.PoGoUtils.PokemonInfo.GetCandy(PokemonData pokemon, List`1 PokemonFamilies, IEnumerable`1 PokemonSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\PoGoUtils\PokemonInfo.cs:Zeile 590.
   bei PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<>c__DisplayClass2_0.<Execute>b__0(PokemonData pokemon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:Zeile 33.
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:Zeile 30.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:Zeile 16.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.
[20:43:34] Einloggen mit Google
[20:44:07] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:Zeile 135.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.
[20:44:07] Einloggen mit Google

>

**Comment by nfettinger** [comment]
Duplicate.

**Comment by bonxraw** [comment]
Sorry didnt saw this. Just wanted to help
