### ISSUE TITLE
KeepMinCp not removing all pokèmon below the value

### ISSUE THREAD

**Issue by Laiiiff** [NECROBOTIO/NecroBot#3317]
"EvolveAboveIvValue": 15.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 10.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2200,

So, I don't want to keep all the bad pokemons that have a lower CP than 2200, I even did put KeepMinDuplicatePokemon to 0 but is not working (I don't know if that changes anything but I tried)

  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 0,

**Comment by Aneduna** [comment]
This is a Configuration issue and should be discussed on discord.

You may want to look into the transferlist tho

**Comment by Laiiiff** [comment]
Oh I see, almost each pokemon has his own configuration, I thought that KeepMinDuplicatePokemon and KeepMinCp were gonna do the work but nothing :\ 
My transfer list is 
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"

So yeah I don't wanna say that it may be an issue because I'm not an expert in those things :) Ty for replying tho

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
