### ISSUE TITLE
why system recycle all of my pokeballs, how can i fix it?

### ISSUE THREAD

**Issue by iqbalsuzetta** [NECROBOTIO/NecroBot#3318]
![image](https://cloud.githubusercontent.com/assets/18052839/17492137/b12bbea4-5dd4-11e6-84c8-0bd12baab8ce.png)

**Comment by dansali** [comment]
"TotalAmountOfPokeballsToKeep": 350,

This is not a bug!!!! I've already told you once. This is not a chat room. There is a discord link for you to discuss this with others

**Comment by gates17** [comment]
go to config.json and reset your parameteres.
you can find more help at wiki under config, to check the fieldname for your pokeballs and change the value you want to have.
you will have to configure limit for pots as well depending on the number of items you wanna stock

**Comment by Marsinator** [comment]
seek #support or #settings in discord for config help
