### ISSUE TITLE
Bag capacity

### ISSUE THREAD

**Issue by KuroshN** [NECROBOTIO/NecroBot#3321]
Hi Guys,
is it possible that you have the bag-capacity hardcoded to 350? because 
although I have 500 space, calculate the bot still with a capacity of 350!

**Comment by Marsinator** [comment]
calculate the bot still with a capacity of 350!

please explain

**Comment by KuroshN** [comment]
the bot recycales items if it is more then 350 items in my Bag.
I bought 3 x 50 updates for my bag

**Comment by PedroSeda** [comment]
Did you reconfigure after buying the upgrades?

**Comment by dansali** [comment]
There is no config for bagsize

**Comment by KuroshN** [comment]
how can i reconfig that
this is all i can change
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,

**Comment by nfettinger** [comment]
Bagsize should be retrieved from the server.

**Comment by PedroSeda** [comment]
"TotalAmountOfPokeballsToKeep": 325,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,
  "TotalAmountOfBerriesToKeep": 25,

They sum 350, you have to change the values
