### ISSUE TITLE
GPX giving null exception

### ISSUE THREAD

**Issue by gates17** [NECROBOTIO/NecroBot#3323]
Is there anyway to find out which of the pokestops on my gpx file is crashing my route and subsequently my bot usage?
The log for the error is shown below

[NecroBot-2016-08-08-20.txt](https://github.com/NECROBOTIO/NecroBot/files/407499/NecroBot-2016-08-08-20.txt)

**Comment by dansali** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3295

Not a GPX issue!

Pokemon servers are unstable!
