### ISSUE TITLE
[Feature Request] Walking a set path

### ISSUE THREAD

**Issue by TheGreatestDude** [NECROBOTIO/NecroBot#3334]
Hi,

Would it be possible to have a feature that (once provided two lat/long coordinates) will walk that path and get the Pokestops within say 100m of the path? I think it'd be a great way of hatching your eggs and getting Pokestops/Pokemon at the same time.

Also - Automatic gym battles
        - Custom item retaining xPokeball xGreatball x---
        - Checklist of what Pokemon to retain/avoid/evolve (instead of text file)

**Comment by nfettinger** [comment]
Read the wiki about GPX files.

**Comment by TheGreatestDude** [comment]
But what about the other things?

**Comment by Marsinator** [comment]
gyms is a thing we might consider in the future.

custom retaining isnt needed, the bot always tries to retain the best balls.
other items are in the config.
checklist is something for a gui, maybe in a future release.
