### ISSUE TITLE
config item Key

### ISSUE THREAD

**Issue by zybertronix** [NECROBOTIO/NecroBot#3339]
Running on 0.7.6. 
having problem on adding pokemon list to evolve 
default value : 
 ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],

but when added more it gives me an error and closes the bot. 
is there any other parameters that i missed ? 
 thanks sorry for the earlier OT post

**Comment by Profetorum** [comment]
which error does it give?

**Comment by benda95280** [comment]
give us your values :)

**Comment by spamfighter82** [comment]
i bet you either spelled a name wrong or forgot a comma ;)

**Comment by nfettinger** [comment]
This is a configuration issue. Closing as off-topic.
Please use our Discord chat rooms for additional help.

**Comment by zybertronix** [comment]
sorry for the late reply guys i was working in the office and have to do some stuff. 
THank you so much you guys helped me a lot it was the comma i was missing some. 

thank you again
