### ISSUE TITLE
[bug] incense not working

### ISSUE THREAD

**Issue by PokemasterMike** [NECROBOTIO/NecroBot#3340]
is this bug actually recognized ? or did it get burried ?
(ekans is in the ignore list, growlithe is not (actually the name ist not in the conifg at all) and growlithe is from an incense... so clearly not working as it should)
[21:21:14] (INFO) Skipped Ekans
[21:21:14] (INFO) [Pokemon ignore filter] - Ignoring Growlithe as defined in settings
[21:21:15] (INFO) [Pokemon ignore filter] - Ignoring Growlithe as defined in settings
[21:21:17] (INFO) [Pokemon ignore filter] - Ignoring Growlithe as defined in settings
[21:21:18] (INFO) [Pokemon ignore filter] - Ignoring Growlithe as defined in settings
[21:21:19] (INFO) [Pokemon ignore filter] - Ignoring Growlithe as defined in settings

**Comment by Marsinator** [comment]
please create a pastebin of your config and post it here

**Comment by PokemasterMike** [comment]
http://pastebin.com/69qXKadL

**Comment by daika7ana** [comment]
It is working.
You have `"UsePokemonSniperFilterOnly": true` and Growlithe is not on that list. #

**Comment by PokemasterMike** [comment]
@daika7ana please learn to read

**Comment by daika7ana** [comment]
Do you want an Explain Like I'm 5 version?
`"UsePokemonSniperFilterOnly": true` will only catch pokemons that are in the PokemonToSnipe list at the bottom of the page.
In that list you only have 

>       "slowbro",
      "exeggutor",
      "porygon",
      "caterpie",
      "weedle",
      "pidgey",
      "eevee",
      "charizard",
      "alakazam",
      "chansey",
      "gyarados",
      "lapras",
      "snorlax",
      "dratini",
      "dragonite"

Now, either add Growlithe to that list or set `"UsePokemonSniperFilterOnly": false`.
I know how to read, tyvm.

**Comment by nfettinger** [comment]
Please keep responses respectful and helpful.
It appears this is a configuration issue to me so I am closing
