### ISSUE TITLE
Pidgeotto to pidgeot doesn't count as potential evolve.

### ISSUE THREAD

**Issue by Plegu** [NECROBOTIO/NecroBot#3346]
I have 5 pidgeottos and 200 pidgey candy and still the console says that "Potential evolves: 0".

**Comment by Marsinator** [comment]
well did you list them in your evolve list?

**Comment by kirito-su** [comment]
```
"PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgeotto",
    
```

But I must say, that you fair better, ** EXP wise, to just get more pidgey and evo them, for the same 500 or 1000 XP.  You can get TWICE the experience that way!
