### ISSUE TITLE
Moves filter list

### ISSUE THREAD

**Issue by ruchern** [NECROBOTIO/NecroBot#3347]
Is the "moves" in the custom pokemon filter list to keep or to transfer?

**Comment by Marsinator** [comment]
keep

**Comment by HZH1907** [comment]
@Marsinator 
How to use it?Like this?
`"Snorlax": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [lick,bodyslam],
      "KeepMinOperator": "or",
      "MovesOperator": "and"
    },`
