### ISSUE TITLE
Cant trasfer all pokemon

### ISSUE THREAD

**Issue by Kiwaaa2** [NECROBOTIO/NecroBot#3348]
Hey,

I got the problem that the bot doesnt send all my pokemon below cp 450 iv 75.
Maybe someone can help me

  "KeepMinCp": 450,
  "KeepMinIvPercentage": 75.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": „and“,
  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,

  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

When i forget something say it. Thanks!

**Comment by Marsinator** [comment]
"KeepMinDuplicatePokemon": 1, <-this will always keep at least 2 copies (1 duplicate, 1 original) of each pokemon

**Comment by Kiwaaa2** [comment]
Yeah, but it still doesnt work..
