### ISSUE TITLE
Snipe problem

### ISSUE THREAD

**Issue by egsix** [NECROBOTIO/NecroBot#3352]
It seems that working, but it doesn't find any pokemon to snipe. :/
![1](https://cloud.githubusercontent.com/assets/20891856/17493714/3da7a4da-5dba-11e6-965d-bec040ec7ab7.jpg)

**Comment by Profetorum** [comment]
post your config

**Comment by egsix** [comment]
@Profetorum  
 "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 6000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,

**Comment by ChemiHatake** [comment]
Because these locations are the locations from the snipe location list,  that list is static and it won't find amything most of the time. 

And because the pokezz api is not working you can only snipe effectively with pogolocationfeeder

**Comment by egsix** [comment]
The site of pokezz is working. Anyway I am using pogolocationfinder but I asked if anyone knew how to fix this. Yesterday with the same snipe loc list in version 0.7.0 was working fine btw. Thx anyway.

**Comment by kirito-su** [comment]
Your current config is set to look at location listed further down below .. 

Open your config, do a Ctrl + F, and search for "Locations" - With the Quotation Marks!

Your Config will have Locations [ 
{    Lat 1233.5566
     Long= 695.3643654
},

You want to either A. Use a Pokemon Go Feeder for Locations or B. and Online Location Server like Pokezz if that works for you.. for me it didn't so i just use PoGoFeeder as it pulls a lot of sources into ONE.
....
 "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "mew",
      "mewtwo",
      "venusaur",
....

**Comment by PokemasterMike** [comment]
this is actually a bug #3275 . please close this

**Comment by kirito-su** [comment]
@pokemastermike 

My err Solution - to what ailed me was to change the snipeoffset..

```
"SnipingScanOffset": 0.3

"instead of the .003 that it was before, and I AM sniping, as I wasn't before
```
