### ISSUE TITLE
Sniping auto set?

### ISSUE THREAD

**Issue by Creston1** [NECROBOTIO/NecroBot#3353]
Is sniping auto set for rares or good pokemon? I have never used necro, so I have 0 idea what I am doing.

**Comment by egsix** [comment]
If you go at config and look down about what pokemons is set to snipe, you will see.

**Comment by PokemasterMike** [comment]
there is discord for questions, please close this, this is not a message board

**Comment by Creston1** [comment]
For me it says nothing, but I woulden't know how to right in the pokemon
