### ISSUE TITLE
PLz Make automatic proxy settings

### ISSUE THREAD

**Issue by LordMichel** [NECROBOTIO/NecroBot#3355]
I geting soft ban because run more then 2 accounts in same IP adress.
Please make one configuration default for one IP per account in proxy automatic configure if possible.
Thanks...

**Comment by LordDeimos** [comment]
And then everyone using the same proxy wil get softbanned again since everyone is using the same IP.
That's not a smart idea.

Either way, use only 1 bot or find on your own a proper proxy.
