### ISSUE TITLE
someone happened to this?

### ISSUE THREAD

**Issue by FAndresCO** [NECROBOTIO/NecroBot#3356]
![mew](https://cloud.githubusercontent.com/assets/20806975/17494212/56e10252-5d79-11e6-86e6-d73b64c30773.PNG)

**Comment by Rick058** [comment]
Someone is just trolling by spamming false information in the discord sniping chat, ignore it. Had to restart my bots because it kept on going trying to snipe 'Mew'.

**Comment by FabryB** [comment]
Yeah me too, but it's not related to the bot, someone flooeded discord with FAKE Mew sightings.
So at most it's an issue with PogoLocationFeeder
