### ISSUE TITLE
Trying to snipe mew inifantly

### ISSUE THREAD

**Issue by aaron25th** [NECROBOTIO/NecroBot#3357]
any one know how to stop this like disable it until mew is relesed

![image](https://cloud.githubusercontent.com/assets/20888296/17494221/ab1483ee-5dab-11e6-96d3-612df04c9953.png)

**Comment by Tustin** [comment]
Try setting the option GetOnlyVerifiedSniperInfoFromPokezz in config.json to true. It should ignore Pokemon that aren't available yet.

**Comment by aaron25th** [comment]
ok thanks

**Comment by FabryB** [comment]
see #3356 
To disable you just have to remove Mew from the PokemonToSnipe->Pokemon in config.json.

In my opinion the config to go trough pokezz is too much restricitive, it takes down many legit snipe too.

**Comment by spamfighter82** [comment]
Same here, just remove Mew and all other Legendarys from the PokemonToSnipe list, they are not real anyways

**Comment by pehur** [comment]
I have that option already on true, still had the same problem.. after relogging it is gone

**Comment by lokat** [comment]
me too.. I just restart the bot

**Comment by aaron25th** [comment]
ye i already had it true

**Comment by FabryB** [comment]
I just removed all of these:
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"

From the snipe list

**Comment by spamfighter82** [comment]
also, "SnipePokemonNotInPokedex": false,

**Comment by Linewalker** [comment]
There should be an option for a max Snipeoffset counter (eg. 6x then walking on an collecting new from the list)

**Comment by nfettinger** [comment]
This appears to be a configuration issue, so closing.
