### ISSUE TITLE
I cant get past logging in 

### ISSUE THREAD

**Issue by Garbage-Chan** [NECROBOTIO/NecroBot#3358]
My configs and auths are brand new and I cant get past logging in any advise?

**Comment by a7mag3ddon** [comment]
I had this, i had to download the correct ENCRYPTxx.dll for my system and rename to encrypt.dll hope this helps

**Comment by Attix22** [comment]
Follow these steps:
1. Make sure the service (google / ptc) is online
2. If using google check wether you are using 2 factor authentication (google it)
3. Check if you are missing any proxy settings.
4. If possible try a different network (Tethering, different wifi whatever is available)

**Comment by nfettinger** [comment]
Off topic
