### ISSUE TITLE
Automatic 90-100 iv pokemon list/feed

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3359]
Is it possibile to create an automatic system to list/feed best pokemon (90%+ ivs for example) , instead of manual discord channels or similar? I mean...when i caught a over 90iv, i notice it into Necro, and tell other with discord. But if it were possible to do it automatically, for every Necro running, it would be amazing in terms of quantity of information!

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support or #plus_90_iv channel.

**Comment by Profetorum** [comment]
But it's a request of improvement, not an issue.
