### ISSUE TITLE
Transfering

### ISSUE THREAD

**Issue by winstonnolten** [NECROBOTIO/NecroBot#3360]
I was finetuning my transfer list and i encountered an issue. If i want my bot to keep a Krabby above 500 how do i know what to put at the KeepMinLvl property? i noticed that different CP 's matches different levels at different pokemons.

e.g. 

"Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"

"Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"

as you can see the CP's differ but the levels are the same

**Comment by Rabelaiss** [comment]
Why did you post the same code twice ?

**Comment by winstonnolten** [comment]
Damn copy-waste fault but the last pokemon should be a dratini. with a different cp but same lvl. But still how do i know what the put at KeepMinLvl?

**Comment by xafelld** [comment]
I use the "IV" Calculator tool at the Silph road to estimate what is the appropriate CP to set to keep. 

HOWEVER, Level is really a better filtering mechanism anyway. If a trainer is level 30,  It makes since to keep 4 Krabby's that are level 25+ and then pick the one with the highest IV to evolve. Does it really make sense to dump a bunch of "Hard earned (bot gathered) stardust into the evolved version??

**Comment by tangdami** [comment]
I set every KeepMinLvl to 30, but I still got lots of low CP, Lvl and IV pokemons not transferred.. had to transfer manually, weird.

**Comment by xafelld** [comment]
"UseKeepMinLvl": TRUE ???

**Comment by tangdami** [comment]
"KeepMinCp": 2250,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 30,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,

I config it carefully, got lots of weak pokemons with 10~30% IV, 100~600 CP... PS: not related to transfer filter.

**Comment by nfettinger** [comment]
Please ask configuration questions in Discord chat. If you have a specific feature request, please enter a new issue.
