### ISSUE TITLE
When transferring duplicates, "PrioritizeIvOverCp" does not seem to work

### ISSUE THREAD

**Issue by DBa2016** [NECROBOTIO/NecroBot#3363]
Quite frequently, the pokemon kept has lower IV than the one which is transferred, regardless of "PrioritizeIVoverCP" set to "true".

**Comment by Saiteik** [comment]
Please submit a screenshot to prove this is occurring.

**Comment by DBa2016** [comment]
Yupp, did not have a screenshot at hand, here we go (-> attached). I marked the "offending" transfers red.

Also attached the config.json file (zipped).
[config.zip](https://github.com/NECROBOTIO/NecroBot/files/407854/config.zip)



![transfers](https://cloud.githubusercontent.com/assets/20729632/17498226/5605bf06-5dc6-11e6-95f4-0a0b3ddcade0.png)

**Comment by nfettinger** [comment]
Duplicate #3338
