### ISSUE TITLE
Somebody is stealing your content

### ISSUE THREAD

**Issue by TMaddox** [NECROBOTIO/NecroBot#3364]
His website is http://www.pokecrot.com/ he claims its his and accepts donations for "his work".

https://github.com/Ar1i/PokemonGo-Bot had the same problem, this is why he publishes builds only now. (since api change, they thought he wouldnt be able to implement the new api by himself and he would stop copying, but instead he is copying now your bot)

Sry for my bad english.

**Comment by nfettinger** [comment]
Noted. Thank you
