### ISSUE TITLE
[Request] Auto transfer for below "%x" IV value

### ISSUE THREAD

**Issue by blidrosia** [NECROBOTIO/NecroBot#3369]
Auto transfer for below "%x" IV value. (apart from duplicate rules)

**Comment by JaEdmuva** [comment]
isn't the KeepMinIvPercentage setting for that?

**Comment by nilsbrychzy** [comment]
I think this is already implenented, vor am i wrong?

**Comment by nilsbrychzy** [comment]
@JaEdmuva has the answer

**Comment by blidrosia** [comment]
what I want is bot transfers pokemons below %50 IV for example. not above.

**Comment by ChemiHatake** [comment]
just set KeepMinIv to 50
and KeepMinCp to 9999 (something high, doesn't matter)
and then the MinKeepOperator to "or"
and it will transfer all pokemon below 50% IV

**Comment by romeoDo** [comment]
most of the issues up here are from people who is too lazy to do some basic research. F*K the developer LIFE *facepalm*

**Comment by blidrosia** [comment]
Do you understand me? I literally want to keep %85 above pokemon and  transfer %50 below pokemon. I don't want to keep %50 above pokemon.

**Comment by Simpuhl** [comment]
Enable TransferWeakPokemon

**Comment by blidrosia** [comment]
Which pokemon is weak?

**Comment by schwartzadev** [comment]
solved: use KeepMinIvPercentage
