### ISSUE TITLE
https://discord.gg/VXKxNFr Expired?

### ISSUE THREAD

**Issue by yupdon** [NECROBOTIO/NecroBot#3375]
Not sure what happened but I may have oops'd - I uploaded a .rar file containing a config (to be nice) and then everything shut down? Am i banned for that? Is there a different invite / way to join the server?

**Comment by nfettinger** [comment]
Archive files are prohibited from Discord, and will result in link deletion, and a possible ban/mute. These are automated and given out by the server.
