### ISSUE TITLE
Stuck here

### ISSUE THREAD

**Issue by kyulix** [NECROBOTIO/NecroBot#3376]
![capture](https://cloud.githubusercontent.com/assets/20726291/17495921/ffc0c4c0-5d88-11e6-9962-69361d60dda3.PNG)

when i fill in everything this gets stuck and when I close out of necrobot 0.76 and reopen it it starts all over again asking me if I want to set it up

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help.
