### ISSUE TITLE
Proxy support for Pogo Location Feeder

### ISSUE THREAD

**Issue by Sheetka** [NECROBOTIO/NecroBot#3377]
Having difficulties getting Pogo Location Feeder to run on a bot with a proxy attached to it.

Anyone had success with this?

**Comment by s-giordano** [comment]
I have the same problem

**Comment by s-giordano** [comment]
Necrobot, for example, has a exe.config xml for placing proxy settings, but this not.

**Comment by schwartzadev** [comment]
This doesn't relate to necrobot.
