### ISSUE TITLE
[Suggestion] MaxPlayerLevel option in config

### ISSUE THREAD

**Issue by nilsbrychzy** [NECROBOTIO/NecroBot#3378]
I think a maximum level would be nice, so if it reached it the bot will close. Good for automation.

```json
"UseMaxPlayerLevel": "true/false",
"MaxPlayerLevel": "25",
```

As example.

**Comment by schwartzadev** [comment]
Thank you. This may not be accepted because of the obvious use for farming (and selling) bots.
