### ISSUE TITLE
Evolves Pokemon but shouldnt

### ISSUE THREAD

**Issue by TiermitBier** [NECROBOTIO/NecroBot#3387]
After updating to 0.7.7 the bot suddenly starts evolving all pokemon.

  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,

did not change anything, i dont want him to evolve anything.

**Comment by Simpuhl** [comment]
Is your inventory almost full?

**Comment by TiermitBier** [comment]
No. Not the item inventory and not the pokemon inventory, all have plenty of space left.

**Comment by PestoPresto** [comment]
I have the same bug, except "EvolveAllPokemonAboveIV": true

Pokemon and item inventory has lots of room as well.

**Comment by ChemiHatake** [comment]
the problem is with KeepPokemonThatCanBeEvolved
set it to false for the time being.
it isn't since 0.7.7, its just since 0.7.7 not only EvolveAllPokemonWithEnoughCandy
can trigger the evolve check.

**Comment by PestoPresto** [comment]
So a temporary solution would be to set "KeepPokemonsThatCanEvolve": true and set "EvolveKeptPokemonsAtStorageUsagePercentage" to a higher percentage?

**Comment by Menton** [comment]
I have the same Issue. I set evolve pokemon to false, it evolves everything nevertheless.

**Comment by EllaVader** [comment]
Setting"KeepPokemonsThatCanEvolve": false, fixed it.

**Comment by actislav** [comment]
ChemiHatake, the problem is with our commits... just revert all your evolve commits pls, and all will be fine

**Comment by nfettinger** [comment]
Please upgrade to the latest version and create a new issue if the problem persists.
