### ISSUE TITLE
Transfering better CP pokemons than worse cp

### ISSUE THREAD

**Issue by shetonaz** [NECROBOTIO/NecroBot#3389]
[00:33:06] Dratini     	- CP:  383  IV:  60.91%   [Geriausias CP:   70  IV:  83.87%] (Saldainiai: 15)

It gave away 383cp dratini instead of 70, "PrioritizeIvOverCp": false,
So whats the problem?

BTW ITS IN LITHUANIAN

**Comment by Simpuhl** [comment]
Your cp70 is much better IV

**Comment by shetonaz** [comment]
Yeah, but i set Prioritize IV over Cp to false, so bot should keep better CP pokemons, not better IV

**Comment by massi93** [comment]
Did you check the filter at the end of lines  in config file? there is kind of filter for rules like the one you are talking too ("PrioritizeIvOverCp")

**Comment by shetonaz** [comment]
@massi93 yea I saw it and checked it,but there's no dratini there so it should use default code, instead of filters as is there no dratini in filter section.

**Comment by massi93** [comment]
maybe there is a bug, If I were you i would try to make a new filter rule for Dratini, or wait until its fixed

**Comment by shetonaz** [comment]
Happened with goldeen, pinsir,exeggutor too, so maybe it's a bug?

**Comment by nfettinger** [comment]
Duplicate #3338
