### ISSUE TITLE
[Bug] since 0.7.7: "EvolveKeptPokemons" overrides "UseLuckyEggsMinPokemonAmount"

### ISSUE THREAD

**Issue by Rawrlex** [NECROBOTIO/NecroBot#3392]
"UseLuckyEggsMinPokemonAmount" is overriding "EvolveKeptPokemonsAtStorageUsagePercentage"

First was set to 200 and second to 95%, after restarting it started to evolve my 250 pokémons. So I set the first one higher, but well. Please fix this, thanks!

**Comment by ChemiHatake** [comment]
the problem is with KeepPokemonThatCanBeEvolved
set it to false for the time being.
it isn't since 0.7.7, its just since 0.7.7 not only EvolveAllPokemonWithEnoughCandy
can trigger the evolve check.

**Comment by Marsinator** [comment]
can confirm.

**Comment by ChemiHatake** [comment]
#3388 
It is unusual because I've debugged it in every way possible with multiple accounts and it didn't occur.
anyway just set KeepPokemonThatCanBeEvolved to false for now

**Comment by viennej** [comment]
EvolveKeptPokemonsAtStorageUsagePercentage doesn't seem to be used also.

**Comment by ChemiHatake** [comment]
It is used if KeepPokemonThatCanBeEvolved is true.

**Comment by viennej** [comment]
I set it to true and the bot is looking at the value of UseLuckyEggsMinPokemonAmount to start the evolve instead of EvolveKeptPokemonsAtStorageUsagePercentage

**Comment by actislav** [comment]
oh my god, so many logic mistakes done by chemi...
rawrlex, UseLuckyEggsMinPokemonAmount means only use egg if u have enough pokemon count to trigger it, its not trigger evolve task by it self, evolve triggered by another settings like EvolveKeptPokemonsAtStorageUsagePercentage or EvolveAllPokemonAboveIv or EvolveAllPokemonWithEnoughCandy

**Comment by ChemiHatake** [comment]
@actislav not true, the count itself is triggered within the same class of the evolve task.
which means whenever it counts the evolves, it also checks the number of pokemon to use lucky egg and storage usage percentage

**Comment by bibi2810** [comment]
I think the code is working as intended now in 0.8.0, Luckyegg is now triggered when there is enough pokemon to evolve and the evolution can only be triggered by Evolvekeptpokemonatstorageusagepercentage 
(y)

**Comment by bibi2810** [comment]
From 0.8.0, evolve is only started by Evolvekeptpokemonatstorageusagepercentage, when triggered it also relates to evolveallpokemonaboveiv and evolveallpokemonwithenoughcandy and useluckyeggsminpokemonamount. I tried to set the latter two to true without Evolvekeptpokemonatstorageusagepercentage (=false), then nothing happened. So I think evolution mainly depends on Evolvekeptpokemonatstorageusagepercentage now. Other variables are dependent on it.

**Comment by Rawrlex** [comment]
Working in 0.8.0 again, indeed.
