### ISSUE TITLE
Transfer Bug

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#3393]
![image](https://cloud.githubusercontent.com/assets/262571/17497387/7f28d7b0-5d76-11e6-8979-fcf5e0d5a383.png)

Any reason why it transfered this Magmar even though its IV was higher than what it think its "best"?

**Comment by ChemiHatake** [comment]
check your config, your KeepMinIv or KeepMinCp might be causing this.

**Comment by Simpuhl** [comment]
Negative:

  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 98.0,
  "KeepMinLvl": 10,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

**Comment by daika7ana** [comment]
Check if you have a special "Magmar" case under `PokemonsTransferFilter` because this overrides the default.

**Comment by Simpuhl** [comment]
It's set to

    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

I guess it doesn't prioritize IV in that case? 

Ill just delete make it like level 5000 or something to fix that

**Comment by daika7ana** [comment]
Yep.

**Comment by pacioc193** [comment]
I have the same problem, but i remove all filter, still same problem

**Comment by Simpuhl** [comment]
If I set

**Comment by daika7ana** [comment]
The 4 best that you get.
If you have 5: 1200 1300 1400 1500 1700. The 1200 gets dumped.

**Comment by padmanek** [comment]
"Magmar": {
  "KeepMinCp": 1500,

That's why it keeps it. Prioritization works on Pokemon that meet the conditions. Your 1501 Magmar does, the transferred one doesn't. I don't see any bug here.

**Comment by Simpuhl** [comment]
@daika7ana 

How do I make it always choose IV first tho?

I have it set above already, if that's the case then we are back to why it transferred my magdar to begin with

**Comment by Simpuhl** [comment]
@padmanek 

I have 

`"PrioritizeIvOverCp": true,`

Tho

**Comment by padmanek** [comment]
@Simpuhl Set MinCP to some crazy number and it will only care about IV :)

**Comment by daika7ana** [comment]
Because the special "Magmar" case had the following:
"KeepMinIvPercentage": 90.0
and "KeepMinCp": 1500.

None of your Magmars had an IV of 90 or higher, HOWEVER one of them had a CP higher than the one set. So, in programming logic, the condition was met.
So you had 1 magmar that fit 1 condition, and 1 that fit none. Therefore it kept the 1500 CP one.

**Comment by Simpuhl** [comment]
Yeah, I made an edit above. I'm stupid for not getting it at first... makes perfect sense now. Sorry. Ill close this
