### ISSUE TITLE
No pokestops found in your area

### ISSUE THREAD

**Issue by rex20161** [NECROBOTIO/NecroBot#3396]
https://snag.gy/MPj4Qf.jpg

was working fine - updated to latest version was working fine again then just recieve the message shown in screenshot?

**Comment by pacioc193** [comment]
what are your coordinates?

**Comment by massi93** [comment]
Check coordinates, mine is working fine with latest update

**Comment by rex20161** [comment]
coordinates are fine - it was working for 15 mins then failed to loot - then failed to find any stops

**Comment by XenoEktika** [comment]
I am having the same problem as Rex20161

**Comment by Quadral25** [comment]
i think it's because of the android update

**Comment by rogueless** [comment]
I'm not using on android and it's giving me the same error.

**Comment by rex20161** [comment]
seems to be on the server side - working fine again with no changes made :)

**Comment by massi93** [comment]
Try this, erase every single file you have related to the bot, redownload and set everything as it was in the previous bot. If its working for me it must work for you

**Comment by rex20161** [comment]
hmmm really weird.... seems to be working again i think this is a server side issue because its completely hit and miss at the moment, guess it depends where you live lol

**Comment by Sylencer90** [comment]
Works just fine here, 0.7.7.

**Comment by SoNiiice** [comment]
I have the same problem with v0.7.7

**Comment by anifan115** [comment]
Change coordinates. I had Yoyogi Park in Japan set and kept having that issue.

**Comment by fass1993** [comment]
i have the same problem v0.7.7 (coordinates Sydney)

**Comment by rex20161** [comment]
i dont think coords have anything to do with it - the problems comes and goes - its a server issue i think

**Comment by SoNiiice** [comment]
https://pokemongostatus.org/

the change of coordinates did not work

**Comment by rex20161** [comment]
Obviously login is fine that doesn't mean there isn't other issues :)

**Comment by zlips** [comment]
thats the new way from niantic to banned, wait for a few minute and try again

**Comment by kaiomm** [comment]
It seems it is link to your ip and location, it also happens when using multiple instances over the same ip. It might compare some geolocation shit with your requests to f*** we up

**Comment by nfettinger** [comment]
This is probably related to a softban, and not a bug in the code.
