### ISSUE TITLE
Please add an option to transfer by max amount

### ISSUE THREAD

**Issue by ViBE-HU** [NECROBOTIO/NecroBot#3402]
The actual mechanism is maybe cool but for me it's slow and useless. Please create an option which transfers the pokémons by CP (or IV) and the max amount.

For example I have 5 Rattata and I set the max amount to 3 then the bot will transfer the last 2 lower CP pokémons.

**Comment by edaovacikli** [comment]
Are you looking for KeepMinDuplicatePokemon perhaps?

**Comment by ViBE-HU** [comment]
Yes but somehow the bot does not transfer. Nothing happens and when the inventory is full the bot does nothing just alerts.

**Comment by edaovacikli** [comment]
Check KeepMinCp, KeepMinIvPercentage, KeepMinLvl. They overwrite KeepMinDuplicatePokemon.

**Comment by ViBE-HU** [comment]
And how can I configure it to ignore these KeepMinCp, KeepMinIvPercentage, KeepMinLvl and only care about KeepMinDuplicatePokemon?

**Comment by edaovacikli** [comment]
Set them as high as possible to ignore them.

**Comment by ViBE-HU** [comment]
Finally! Thanks. This did the job. The tutorial should mention this too...
