### ISSUE TITLE
How can I set the Telegram bot?

### ISSUE THREAD

**Issue by ViBE-HU** [NECROBOTIO/NecroBot#3403]
As I see there is no info about this in the wiki. Could someone help me?

**Comment by Simpuhl** [comment]
There's actually no info for about 15 different things in the conf

:(

**Comment by ViBE-HU** [comment]
Yeah, you're right btw... :D

**Comment by Delta1977** [comment]
create ab bot an key here https://core.telegram.org/bots , add parameters to config

**Comment by MineMalox** [comment]
0. You install the Telegram app.
1. You go in your Telegram app and search for the user "BotFather" and start to chat with him.
2. You type /newbot.
3. You give your Bot a Name.
4. Now you have to give you bot a Username ending with "bot" something like: necrobot_bot or necrobot
5. Now you are getting an HTTP API Code with you are adding in the config.json under "TelegramAPIKey"
6. You set UseTelegramAPI to true.
7. Have fun with the BOT!

**Comment by Rabelaiss** [comment]
Sorry but what are you goint to use a telegram bot for ?
I mean the purpose

**Comment by MineMalox** [comment]
You can check your Pokemon GO Stats when you're not at you Computer.

**Comment by ViBE-HU** [comment]
Thanks @MineMalox. You're awsum.

**Comment by Rabelaiss** [comment]
Holy shh thanks man! gg

**Comment by TemhAAhmeT** [comment]
Nice :D Now working

**Comment by aVitomin** [comment]
http://c2n.me/3B12jG7.png

This correct settings or no ? Or i need paste only "Key" without bot id ?

**Comment by MineMalox** [comment]
I created an Wiki Page need only an Admin to merge it:

-> https://github.com/MineMalox/NecroBot/wiki/Telegram

@aVitomin you need to set UseTelegramApi to true!

**Comment by Firedor** [comment]
@MineMalox You da real MVP.

**Comment by schwartzadev** [comment]
@Simpuhl What else would you like added to the wiki?

**Comment by Simpuhl** [comment]
Go to the configuration page on wiki, then do a find for every command in the config file. Anything that can't be found. There's quite a few. I'm on mobile or else I'd do it

**Comment by juliofreez** [comment]
so i set UseTelegramAPI to true and put my HHTP API Key in the config.json. If i want to start it, it just stops working

**Comment by MineMalox** [comment]
Look in the wiki

**Comment by nfettinger** [comment]
This is not the place for questions
