### ISSUE TITLE
Crashes at open!

### ISSUE THREAD

**Issue by rogueless** [NECROBOTIO/NecroBot#3404]
"NecroBot client for Pokemon Go has stopped working"

The bot itself says "() Exceptiion caught: writing LogBuffer." 

Anyone else with this problem?

**Comment by ChemiHatake** [comment]
please take a screenshot

**Comment by roy827** [comment]
Initializing NecroBot logger at time 8/8/2016 11:45:23 PM...
[23:45:25] Exceptiion caught, writing LogBuffer.
Initializing NecroBot logger at time 8/8/2016 11:45:57 PM...
[23:45:59] Exceptiion caught, writing LogBuffer.
Initializing NecroBot logger at time 8/8/2016 11:48:23 PM...
[23:48:25] Exceptiion caught, writing LogBuffer.
Initializing NecroBot logger at time 8/8/2016 11:50:24 PM...
[23:50:26] Exceptiion caught, writing LogBuffer.
Initializing NecroBot logger at time 8/8/2016 11:52:34 PM...
[23:52:36] Exceptiion caught, writing LogBuffer.

same problem, same erroe

**Comment by roy827** [comment]
0.7.7 crashes, so i go back to 0.7.6 and it works

**Comment by nfettinger** [comment]
TODO: Add better printouts on why the log could not be opened. Probably as simple as printing the error code.

**Comment by dddbliss** [comment]
Old version.
