### ISSUE TITLE
suggestion regarding "[Evolves] Potential Evolves"

### ISSUE THREAD

**Issue by zorroiscool** [NECROBOTIO/NecroBot#3405]
is it possible to elaborate upon receiving the following notification "[Evolves] Potential Evolves: 1" (or whatever number of potential evolves, there are) it would be interesting to know which Pokemon the bot has decided will be evolved in the future.

Ive set my evolves number to trigger very high and in the meanwhile id like to know what it is planning for me. I think others will appreciate it as well.
plus you can set the "extended version" to be shown only upon login or once in every X time.
or maybe even to disable/enable it all together.

**Comment by ChemiHatake** [comment]
it does tell you how many potential evolves there are every farming cycle

**Comment by zorroiscool** [comment]
perhaps i did not make my self clear.
i know it does tell me how many potential evoles there are.
but i would like it to elaborate and tell me which specific pokemons are going to be evolved (and their current stats).

**Comment by PedroSeda** [comment]
That may prove too verbose for 100+ pokemon, I did that while testing and it filled the window with stats, is that what you are looking for? Or maybe what species and how many of each?

**Comment by zorroiscool** [comment]
thats what im looking for sheet of info regarding those potiential evolutions.
but your making me doubt my own request, im afraid it will be verbose..
yet it would be nice as an option for people to try for themselves and decide whether theyre interested in this type of massive info update or not.

**Comment by nfettinger** [comment]
Setting the print level in the source to debug or lower will print majority of this stuff for you. It is not desirable to see this in released versions because people will complain that the log is too cluttered, and that the log files are growing too big too fast.
