### ISSUE TITLE
Everysingle co-ordinate says possible softban latestversion-

### ISSUE THREAD

**Issue by Jordano3710** [NECROBOTIO/NecroBot#3408]
Hi, I have tried everything and idk what it is iv used lots of co-ordinates and used other versions also and it keeps saying possible softban? Any help

**Comment by head0r** [comment]
maybe its because you are... softbanned? 
when "traveling" that much it is likely that the bot is not able to bypass the softban.
how long did you wait?

**Comment by Jordano3710** [comment]
Hey thanks for helping but its all sorted now i just waited, waited and waited haha but finally but thanks for commenting man!
