### ISSUE TITLE
Slower than usual?

### ISSUE THREAD

**Issue by Gernatch** [NECROBOTIO/NecroBot#3412]
Does anyone notice the actions are going slower than usual? Has this been brought up yet? I looked but didn't see a post. 

No matter what I set the delay between player actions to, it takes about 7-10 seconds for each action. Thoughts?

**Comment by centoxe** [comment]
i notice it too

**Comment by CoderHaxSrubz** [comment]
even with an OG .7.6 config its slower

**Comment by Willovent** [comment]
some informations are no longer display (time for the next pokestop etc..). So it's not slower, just less flooding.

**Comment by Diablosito33** [comment]
Ignoring willoven... It is indeed slower, even decreasing the delay max EXP/h i've got so far is 20k... LUL

**Comment by djdookie** [comment]
I am still running 0.7.6 and nothing changed here: still 125k/h for 3 bots. Everything works fine.
So I guess if there is a slowing problem, it refers to the new version 0.7.7
Thanks for this info, I will not upgrade then! ;)

**Comment by Mamutebr** [comment]
I noticed. one average of 25 to 30 k hours
So I try to put to evolve Pokemons as
pidey
weedle
cartepie
Zubats
etc

**Comment by YoryP** [comment]
I noticed it too, so I came back to NecroBot v0.7.6 and now it's ok. Hope it will be fixed in the next version

**Comment by Diablosito33** [comment]
They mentioned an "IMPROVE" on delay, guess it wasn't just the delays we can manually edit on config.json. So noobs (like me) will not be able to edit those delays, and we are kinda stuck on this...
The telegram update is so nice xD I want it, but i want EXP too.

**Comment by Gernatch** [comment]
Thanks guys. Rolling back now. =)

**Comment by Gernatch** [comment]
Never mind, you can't roll back. That's bugged. Once you roll back, it asks if you want to update. When you say no, it fails to authenticate. It says the information needs to be updated in auth.json, but I had already updated the info. They must have changed the way the auth.json is read.

**Comment by djdookie** [comment]
More reports on low xp now. #3437 
This is a real showstopper!

**Comment by zawhie** [comment]
@Gernatch: Disable Autoupdate in config.json, after that 0.7.6 will work again.

**Comment by Gernatch** [comment]
That did it, thanks.
