### ISSUE TITLE
Proxy support not working?

### ISSUE THREAD

**Issue by athanatos1** [NECROBOTIO/NecroBot#3415]
We need something that confirms in the bot that the proxy is loaded and working, which also shows current ip address in use. 

Getting soft banned with more then 3 accounts and also, what KIND of proxy does the bot support?? Socks 5, regular proxies, etc?

**Comment by djdookie** [comment]
Duplicate of my earlier issue #3235

**Comment by nfettinger** [comment]
Duplicate
