### ISSUE TITLE
Necrobot Issue - 1st Launch Google type "Logging in using Google" Stuck

### ISSUE THREAD

**Issue by CDAGaming** [NECROBOTIO/NecroBot#3421]
I don't know if it's just me but every time it launches for the 1st time, & I use The Google Account type, It never goes past "Logging in using Google"

Workaround: Exit NecroBot & Relaunch it(I launch it as Administrator)

**Comment by masakaji** [comment]
same issue

**Comment by KillerOffers** [comment]
Just close and open!

**Comment by ipatrickjoseph** [comment]
can someone help me? 
![1](https://cloud.githubusercontent.com/assets/20921623/17507304/8bb924b4-5e41-11e6-9a6e-4f726f46b8fe.PNG)
