### ISSUE TITLE
No usable Pokestops issue 

### ISSUE THREAD

**Issue by Kryolu** [NECROBOTIO/NecroBot#3423]
![](http://puu.sh/quuV4/3e92429fdb.png)

Maximum distance = 1500m, but it's still not working, i saw that's because server are unstable, but seems wrong, help ?

**Comment by Fulachs** [comment]
Updating to 0.7.7 helped me

**Comment by Kryolu** [comment]
i've already got the 0.7.7

**Comment by Rick058** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3255#issuecomment-238303920
tl;dr of what I did to get rid of this issue:
1) Download a VPN (Hideme.vpn for example) and enable it
2) Start the bot, let it go until it finishes the unban softban 45/45
3) After that, feel free to disable the VPN again. Be sure to not use more than 3 bots at a time, more than 3 causes an instant softban loop.

**Comment by CDAGaming** [comment]
I Pulled from the repo again and rebuilt solution in vs, worked for me
