### ISSUE TITLE
@Admins Telegram Wiki Page

### ISSUE THREAD

**Issue by MineMalox** [NECROBOTIO/NecroBot#3425]
I created an Telegram Wiki Page please add it to the official Wiki.

-> https://github.com/MineMalox/NecroBot/wiki/Telegram

**Comment by Diablosito33** [comment]
Well, thanks... xD

**Comment by aVitomin** [comment]
you helped me do it xD

**Comment by schwartzadev** [comment]
Thanks. Implemented a while ago.
