### ISSUE TITLE
0.7.7 google login hangs

### ISSUE THREAD

**Issue by vfuyong** [NECROBOTIO/NecroBot#3426]
The login does not proceed, but 0.7.6 is working.

**Comment by mrjinglesusa** [comment]
Same

**Comment by Energex22** [comment]
Same with ptc also...

**Comment by KurtKoko** [comment]
Overall Status:
Status: Offline

The server status is currently Offline because The Login Gateway is offline.

The overall status is based on the status checks performed against the Login Gateway as well as the Google login checks performed in various regions.

**Comment by KralElite** [comment]
It works now I just got in

**Comment by KralElite** [comment]
I had the same issue but it worked just now

**Comment by mrjinglesusa** [comment]
Worked now as well - Pokemon server issue it seems
