### ISSUE TITLE
Failed XXX. Result: FailedPokemonMissing, stopping evolving XXX

### ISSUE THREAD

**Issue by weedorbeat** [NECROBOTIO/NecroBot#3431]
[Evolves] Potential Evolves: 65
Used Lucky Egg, remaining: 2
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Caterpie successfully for 1000EP
Weedle successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Caterpie successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Weedle successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Weedle successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Caterpie successfully for 1000EP
Rattata successfully for 1000EP
Pidgey successfully for 1000EP
Rattata successfully for 1000EP
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Weedle. Result: FailedPokemonMissing, stopping evolving Weedle
Failed Caterpie. Result: FailedPokemonMissing, stopping evolving Caterpie
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata
Failed Pidgey. Result: FailedPokemonMissing, stopping evolving Pidgey
Failed Rattata. Result: FailedPokemonMissing, stopping evolving Rattata

**Comment by schwartzadev** [comment]
I had the same issue. When i opened it on my phone, i was indeed out of candies. Before evolves, necro tells you there are 76 possible evolutions. That number might be taken from the amount of candies you would have after transferring the evolved pokemon. If you have transferring disabled, you still have those potential evolves, but it cannot evolve them because the evolved pokemon were not transferred, freeing up more candies.
