### ISSUE TITLE
Settings for the snipe

### ISSUE THREAD

**Issue by manbir2004** [NECROBOTIO/NecroBot#3432]
i tried setting it up but nothing working for me can some one tell me what to turn on and what to turn off for the snipes settings 

Thanks in advance.

**Comment by arabcurry** [comment]
"UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
this is mine and it work fine but small amount of xp for me but that me something difrent.
good luck

**Comment by emwedk** [comment]
Read this section and you'll be good 
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by manbir2004** [comment]
Yes thank you it works now :)
