### ISSUE TITLE
Any setting for this?

### ISSUE THREAD

**Issue by calixtocarls** [NECROBOTIO/NecroBot#3434]
I spent all day trying to set the robot, but so far can not configure it the way you want. You know the definition to capture all pokemons, while maintaining the strongest three of each? Example: having a Vaporeon 1804, 1752 and 1714, as well as other low-low, do not want to miss any of the three, but would like the robot keeps the three and to transfer the others (if I capture a stronger, would be replaced by the weakest of the three). I took some down Pokemons low, low configured to transfer down Pokémon, but lost several good Pokemons, lost 160 CP CP, how can I set it to download only the weakest of each type?

**Comment by emwedk** [comment]
go to discord for help ;)
this is not an issue regarding the bot

**Comment by actislav** [comment]
simple answer: KeepMinDuplicatePokemon = 3, PrioritizeIvOverCp = false

**Comment by calixtocarls** [comment]
I've already set that way, but it did not work, it leaves only a pokemon

**Comment by actislav** [comment]
check your personal per pokemon transfer settings in section,  "PokemonsTransferFilter":

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
