### ISSUE TITLE
snipe don't work

### ISSUE THREAD

**Issue by mostgod** [NECROBOTIO/NecroBot#3435]

**Comment by emwedk** [comment]
works fine - read this section and you'll be good
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by userix** [comment]
What about the built in Pokezz feature?  I have it set to true, but it still doesn't find anything to snipe. is there something else I need to do to get the bot to work with Pokezz?

**Comment by mostgod** [comment]
tq, is't work again
