### ISSUE TITLE
Newbie attempting to download.

### ISSUE THREAD

**Issue by Invaderofbunnie** [NECROBOTIO/NecroBot#3439]
I am attempting to download the script to my computer. 

I have very basic scripting knowledge.
Currently following the steps found : https://github.com/NECROBOTIO/NecroBot/wiki/Compiled-Releases

I have unzipped the files, but how do I run the program? Steps say 
" run the program (NecroBot.exe)."
...Where is this?

I am so sorry for being so ignorant to this stuff, I'd appreciate any help.

**Comment by Wolved** [comment]
Just make sure you actually download the release.zip , not the source.

You should find the .exe in the root directory

**Comment by ChemiHatake** [comment]
You should have a file named 'NecroBot.exe' in the folder you extracted
the files to.

if you have any more questions please go over to the discord chat:
https://discordapp.com/invite/VXKxNFr
you'll get your answers faster there.

**Comment by Invaderofbunnie** [comment]
ooh Thank you very much @ChemiHatake  I will take my install questions over there. 

I did not download the release.zip @Wolved that would help!

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
