### ISSUE TITLE
Moves Question - What am I doing wrong?

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#3442]
"Golduck": {
            "KeepMinCp": 2000,
            "KeepMinLvl": 0,
            "UseKeepMinLvl": false,
            "KeepMinIvPercentage": 95.0,
            "KeepMinDuplicatePokemon": 2,
            "Moves": [ "Water Gun", "Hydro Pump" ],
            "KeepMinOperator": "or",
            "MovesOperator": "and"
        },`

![image](https://cloud.githubusercontent.com/assets/262571/17500303/211f82f0-5d89-11e6-9465-73612e1d1be9.png)

**Comment by actislav** [comment]
WaterGunFast or WaterGunFastBlastoise only exists....  and HydroPump

**Comment by Simpuhl** [comment]
I don't understand what you mean... Do I not type the moves that way?

**Comment by FaNuCeDeX** [comment]
If I understand actislav right, you have to remove the space between HydroPump and you also have to remove the space between WaterGun. And just 'Watergun' doesn't exist, so it's WaterGunFast or WaterGunFastBlastoise.

**Comment by Simpuhl** [comment]
Is there a list of all the moves somewhere

**Comment by FaNuCeDeX** [comment]
That's a question that belongs on Discord.
https://discordapp.com/invite/VXKxNFr

And next to that, I also don't know the answer.

**Comment by Simpuhl** [comment]
I got it figured out through trial and error.

Thanks
