### ISSUE TITLE
detected a realistic traveling , using default settings inside config.json

### ISSUE THREAD

**Issue by jawad90** [NECROBOTIO/NecroBot#3443]
i saw that msg after changing the device ID in config.json

**Comment by jawad90** [comment]
why downvoting if you dont have an answer ? ...

**Comment by Wolved** [comment]
It's not an error or something if you're trying to say that, it's just a default setting which is enabled.

**Comment by jawad90** [comment]
i know its not but i changed the deviceID because everyone is using the default one but it stills use the default like the title says

**Comment by nfettinger** [comment]
This is working as expected.
