### ISSUE TITLE
[Bug] Crashed after a few hours

### ISSUE THREAD

**Issue by ANR2ME** [NECROBOTIO/NecroBot#3447]
After running a few hours of NecroBot 0.7.6 it crashed with this exception in the console.
![necrobot076crash1](https://cloud.githubusercontent.com/assets/7974720/17500501/452f9b9a-5e00-11e6-8406-454fc1d38aad.jpg)
Shouldn't this exception be caught to prevent crashing the process?

**Comment by ANR2ME** [comment]
Crashed again on 0.7.7
![necrobot077crash1](https://cloud.githubusercontent.com/assets/7974720/17501655/e6506734-5e0a-11e6-9b95-4e0102697550.jpg)

**Comment by KralElite** [comment]
I am pretty sure it has been fixed

**Comment by ANR2ME** [comment]
Yep, it seems to be fixed in 0.7.8 :) Thanks guys
