### ISSUE TITLE
Bot ignores the "ignore pokemon" setting? 

### ISSUE THREAD

**Issue by ProfKush** [NECROBOTIO/NecroBot#3448]
I put the names of the pokemon I don't want it to catch and it still goes for them why?

**Comment by ProfKush** [comment]
Also btw the "TransferWeakPokemon" setting, what is considered weak?

**Comment by Seyrenvox** [comment]
did you set "UsePokemonToNotCatchFilter" to TRUE?

**Comment by ProfKush** [comment]
Thx!
