### ISSUE TITLE
sniping not working

### ISSUE THREAD

**Issue by sirvts** [NECROBOTIO/NecroBot#3452]
https://gyazo.com/7c63f977d6934f653088ddeaba9ab693
always happening !

**Comment by centoxe** [comment]
thats supposed to happen... lol

**Comment by mytab0r** [comment]
try change scan "SnipingScanOffset":

**Comment by sirvts** [comment]
Already changed and still the same...

**Comment by sirvts** [comment]
https://gyazo.com/559e2b1b243ce12fac47a9aa5097ad50

Still happening everytime...

**Comment by schwartzadev** [comment]
Please put this on the Discord chat: https://discord.gg/VXKxNFr. Channel #support or #sniping

**Comment by schwartzadev** [comment]
Changing `SnipingScanOffset` to 0003 might work also
