### ISSUE TITLE
Min IV AND CP while keeping additional Min CP

### ISSUE THREAD

**Issue by Pokemongobottttttt** [NECROBOTIO/NecroBot#3453]
Not sure if this is possible
I want it to keep minimum cp 1800 as its own value, no matter what reguardless of IV
Then keep IV 93 and up ONLY if cp is 1000 or over.

examples: 
Cp:100 IV:97 = transfered
Cp:1200 IV:94 = keep
Cp:2000 IV:20 = keep

**Comment by centoxe** [comment]
this might have to do with your settings for minimum duplicates for each pokemon

**Comment by Pokemongobottttttt** [comment]
Will min dup overide these values?

  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 93.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

**Comment by ChemiHatake** [comment]
"KeepMinCp": 1800,
"KeepMinIvPercentage": 93.0,
"KeepMinOperator": "or",

**Comment by Aqvkao** [comment]
You can use "PokemonsTransferFilter" to realise this, but individually for each pokemon :>

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
