### ISSUE TITLE
coords for dragonite/snorlax

### ISSUE THREAD

**Issue by centoxe** [NECROBOTIO/NecroBot#3454]
what are some coords to find rare pokemon like these

**Comment by anifan115** [comment]
Please check the discord server

**Comment by MetaExtreme** [comment]
use the pokesniping option
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide
and check this out for some issues
https://github.com/NECROBOTIO/NecroBot/issues/3386
