### ISSUE TITLE
Distance too small?

### ISSUE THREAD

**Issue by Argaroth123** [NECROBOTIO/NecroBot#3458]
The bot doens't work anymore. it's just constanly saying, is your maximum distance too small?
And i tried evrything too make it work again but nothing helped.
Can anybody please help me with this problem?

**Comment by XenoEktika** [comment]
i have the same problem

**Comment by Latpip** [comment]
This is believed to be an IP ban

**Comment by ChemiHatake** [comment]
if this happens, you've probably ran more than 3 bots at once.
you'll need add proxies in your config.

**Comment by XenoEktika** [comment]
ohh wow thanks,  I was running 7 :-P

**Comment by XenoEktika** [comment]
you dont have  alink with instructions on adding proxies by any chance?

**Comment by schwartzadev** [comment]
Research proxies or vpns. Solved
