### ISSUE TITLE
Telegram + Necrobot  ?

### ISSUE THREAD

**Issue by Harry2101** [NECROBOTIO/NecroBot#3459]
https://github.com/MineMalox/NecroBot/wiki/Telegram

This is the link for telegram and that can control your Necrobot on Phone.

But, does it really start Necrobot without actually opening my laptop? SO i can just open Telegram and open the Bot and it just starts what Necrobot does? Thanks.

**Comment by PedroSeda** [comment]
No, it does not control NecroBot, it just shows some information about you and your pokemons for now

**Comment by tmorrish** [comment]
Can a switch be added for /top /all for sorting by IV or CP ie /topcp /topiv /alliv /allcp

**Comment by schwartzadev** [comment]
@MineMalox see above

**Comment by schwartzadev** [comment]
No, Telegram does not wake Necrobot. (They both need to be started independently)

_closed_
