### ISSUE TITLE
Possible cause of "No Usable Pokestops" IP ban.

### ISSUE THREAD

**Issue by Latpip** [NECROBOTIO/NecroBot#3460]
Ok so ive tested this 3 times and it has worked all 3 times on different accounts. If you change your location over a large distance then you will get softbanned which is the typical spin 45 pokestops softban. However, i have noticed that if you change your location, get softbanned, then change your location AGAIN without getting yourself un-softbanned first(via 45 pokestop spin) then you'll get IP softbanned and thus will receive the "No usable pokestops in your area" repeat message. In terms of how long the ban lasts I believe it might be random as mine have lasted from 30 minutes to 8+ hours. These are just my thoughts, It'd be nice if some other people tested this theory out to see if it holds out.

**Comment by fass1993** [comment]
I don't get softbanned if i use max. 3 bots with different accs at the same time. But i dont kow why???

**Comment by gemeluna** [comment]
I got softbanned with all accounts if I try to use more than 3 bots too.
Using 3 bots and open the game with another account goes fine though

**Comment by anggaeps** [comment]
get same error  "no usable pokestops in your area", i setup my coordinates to sydney whic is many pokestop there
