### ISSUE TITLE
Argument out of range error after update to latest version

### ISSUE THREAD

**Issue by hianghao** [NECROBOTIO/NecroBot#3463]
![image](https://cloud.githubusercontent.com/assets/20620594/17500885/5269e3c2-5e0c-11e6-999d-3552530385d9.png)

Hi, After updating I have this error. I've tried to redownload the latest version but i kept getting the same error.  I am very certain that the lat and long in my config is correct though.

**Comment by ChemiHatake** [comment]
Please post your latitude here.

**Comment by hianghao** [comment]
![image](https://cloud.githubusercontent.com/assets/20620594/17501002/552e5722-5e0d-11e6-8c0e-4e40428a265a.png)

**Comment by hianghao** [comment]
I noticed that after I changed GPX path to false, this error doesn't come out and it works. But the GPX file which I am using is downloaded from this section, the Magikarp farming. I am not really sure what happened,

**Comment by ChemiHatake** [comment]
the coords should be close to the starting spot of the GPX path

**Comment by nfettinger** [comment]
Configuration issue. Please use Discord chat for further help.
