### ISSUE TITLE
Sniping and Farming

### ISSUE THREAD

**Issue by MetaExtreme** [NECROBOTIO/NecroBot#3465]
Is there a way to snipe and after a certain period it changes to normal farming again?
Because sniping uses a lot of my ultraballs so it would be good to switch over to farming and get some new ultraballs and then start sniping again.

**Comment by sirvts** [comment]
https://gyazo.com/559e2b1b243ce12fac47a9aa5097ad50
anyone knows how to fix?

**Comment by MetaExtreme** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3386

**Comment by qdoth** [comment]
what is snipingscannoffset function ??

**Comment by jjskuld** [comment]
```SnipingScanOffset``` is only used when sniping from fixed location list. It is used to determine the bounds of the search area when it looks for pokemon to snipe. According to the code, 0.003 = half a mile; maximum 0.06 is 10 miles

**Comment by schwartzadev** [comment]
Find snipingscannoffset in the config.json file and make sure it is 0 < x < 0.06

**Comment by jjskuld** [comment]
@MetaExtreme To go back to farming again, increase ```MinDelayBetweenSnipes```.  The default is ```60000``` or 60 seconds.. If you increase to larger value, then it will farm longer before sniping again.

**Comment by jjskuld** [comment]
@schwartzadev If you increase ```SnipingScanOffset``` to 0.06 it will find a large number of pokemon and that will make you run out of balls sooner.  

Do not decrease this value to 0 unless you want to look for pokemon to snipe only at a very specific location.
