### ISSUE TITLE
What do |"MinPokeballsToSnipe": 20| and |"MinPokeballsWhileSnipe": 0| do?

### ISSUE THREAD

**Issue by MetaExtreme** [NECROBOTIO/NecroBot#3469]
What do |"MinPokeballsToSnipe": 20| and |"MinPokeballsWhileSnipe": 0| do?

**Comment by UraharaKisuke07** [comment]
if Pokeballs>20, the bot will go on sniping. If while sniping Pokeballs drop to 0, the bot won't snipe unless you have >20 Pokeballs

**Comment by mytab0r** [comment]
@MetaExtreme 

[MinPokeballsToSnipe](https://github.com/NECROBOTIO/NecroBot/wiki/Config#minpokeballstosnipe-value) (Value)

When NecroBot goes on a sniping journey, it will only proceed if the number of pokeball-type items it has exceeds this value.

MinPokeballsWhileSnipe (Value)

During a sniping journey, NecroBot will end the journey if the number of pokeball-type items becomes less than this value when hopping between locations.

**Comment by thejasonhsu** [comment]
For future reference, please use the discord chat as this isn't a real issue: 
[https://discord.gg/VXKxNFr](https://discord.gg/VXKxNFr)

**Comment by schwartzadev** [comment]
Thanks @thejasonhsu 
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
