### ISSUE TITLE
Is the screen's width adjustable?

### ISSUE THREAD

**Issue by doniface** [NECROBOTIO/NecroBot#3470]
I ran NecroBot in my laptop, and the process's messages were line broken like this:

[09:10:00] (xxxxxx) xxx xx xxxxx xxxxx xxxxx xxxxxxxxx
xxxx xxxx xxxxxx xxxx.
[09:10:12] (xxxxxx) xxx xx xxxxx xxxxx xxxxx xxxxxxxxx
xxxx.

I think if I can drag the width of the screen or set the value in config, the problem can be solved, can it be fixed?

**Comment by Napalmburns** [comment]
I have the same issue. I would love to widen the screen.

**Comment by Rick058** [comment]
I assume you mean the width of the command prompt?
In that case --> http://www.howtogeek.com/howto/19982/how-to-make-the-windows-command-prompt-wider/

**Comment by rex20161** [comment]
you can resize the same way you would with any other app..... click the very edge (your mouse cursor will turn in to this: http://downloadicons.net/sites/default/files/diagonal-resize-window--pointer-icon-72844.png) then just drag to what ever size you desire

**Comment by Napalmburns** [comment]
yes, this is the fix. Thank you so much @Rick058

**Comment by doniface** [comment]
that also fixed for me, too.
and lead me to another problem, like this example:
[09:51:12] (捕捉) (捕捉成功) | (一般) 小拉達 等級: 6 CP: (77/96) IV: 34.00% | 捕獲機率: 62.29% | 距離63.88公尺 | 使用寶貝球捕捉 (剩餘25個) | 經驗值+210 | 還有17顆該種類的糖果 | 座標: xx.xxxxxxx,xx.xxxxxxx
[09:51:32] (補給站) 名稱：xxxxx 經驗值：50, 金幣：0, 物品：1 x ItemRevive, 2 x ItemPokeBall

as you can see the first messages' length is more longer than the second, so even you adjust the screen's width, some messages still over the width and the line break again, like this:

(xxx) xxx xx xx x x xxx xxxxx
(xxx) xxx x x x x xxx xxxxx
(xxx) xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxx

I think maybe I can assaign the message's length, IF the length is longer than the value, then line break occured, so the program can format the message, like this

(xxx) xxx xx xx xx xxxx
(xxx) xxx xx x x x xx
(xxx) xxxx xx x xxx xxx
        xxxx xxx xxx xx
        xxxx xxx xxxx xx  <-- this message is too long, need to break.
(xxx) xxx xxx xxx

**Comment by Marsinator** [comment]
reopened

**Comment by nfettinger** [comment]
Setting the width natively in the app is not something that would just increase complexity in the configuration files. It can be set manually, which works on all OS's.
