### ISSUE TITLE
Google Login error 0.7.7

### ISSUE THREAD

**Issue by Dinkmetri** [NECROBOTIO/NecroBot#3472]
I keep getting this error when trying to log in

Initializing NecroBot logger at time 8/8/2016 8:59:37 PM...
[20:59:38] Perfect! You already have the newest Version 0.7.7
[20:59:38] Logging in using Google
[20:59:39] Make sure you have entered the right Email & Password.

I have my live account linked to my gmail account, and the pokemon go app lets me use my live account. I tried both on the bot but the same error persists.

**Comment by KralElite** [comment]
try to do it normally and recheck in the config auth file if your login info is right

**Comment by Marsinator** [comment]
are you sure you put the data in auth.json?

**Comment by edoth76** [comment]
same case with me, already check write with quote, check that the account clear, not been banned. email & pass checked with browser and correct.
Any idea? Proxy should be modified?

**Comment by martinwind** [comment]
yeah using google not work

**Comment by nfettinger** [comment]
Configuration or server issue. Not seeing this now.
