### ISSUE TITLE
I am unable to pick up the items of pokestops

### ISSUE THREAD

**Issue by Kurama9C** [NECROBOTIO/NecroBot#3478]
It's been eight hours it took a softban and I can not pick up items in pokestops , this could be a ip ban as seen in another post ? I think it was not a permanent ban , they still can enter the account normally .

**Comment by schwartzadev** [comment]
It is likely that your inventory is full.
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
