### ISSUE TITLE
Soft Banned after 4th bot running

### ISSUE THREAD

**Issue by centoxe** [NECROBOTIO/NecroBot#3480]
ive been running 3 bots for a few hours now, now when i have the 4th one open, it softbanned all of them after 2 min... Fix? for this?

**Comment by Marsinator** [comment]
dont run 4 bots

**Comment by KralElite** [comment]
lololol

**Comment by KralElite** [comment]
Wait you can run more than one bot?

**Comment by cswxin** [comment]
@KralElite just copy documents and edit config json
