### ISSUE TITLE
Logging in using google v0.7.7

### ISSUE THREAD

**Issue by masakaji** [NECROBOTIO/NecroBot#3482]
I keep getting "logging in using google" and never go pass it. I could log in v.0.7.6.

**Comment by Marsinator** [comment]
did you restart the bot yett

**Comment by kelvin912** [comment]
how to restart? i just close it and reopen but the issue still

**Comment by masakaji** [comment]
Yes I did it. but I can't log in yet. I updated necrobot from v0.7.6 to v.0.7.7 automatically 2 hours ago.

**Comment by KOTR2003** [comment]
Still having the issue? Niantic servers are bogged/slow.

I just re-launched just fine. Confirm the auth.json is still setup proper.

**Comment by masakaji** [comment]
the issue is still having. I tried to restart many times and confirmed the auth.json.

**Comment by kurozani** [comment]
same here, it was fine in last version but once updated, I can't login, I tried to download the 7.6 version, but it said i haven't write my email and password :(

**Comment by alex51job** [comment]
same issue with masakaji.

**Comment by masakaji** [comment]
same as kurozani

**Comment by ascer0** [comment]
unstable server niantic .. wait 15 minutes and try again ..

**Comment by parbonature** [comment]
i can play as usual, but sometime quit the game, maybe because of Niantic server

**Comment by kurozani** [comment]
I waited for 3 hours now XD

**Comment by schwartzadev** [comment]
Try updating to latest. There seems to be an issue where if you try to sign in on the not-latest version, authentication fails. See #3542

**Comment by parbonature** [comment]
I failed work in version 078, I run 076 with 3 account,2 ptc, 1 google

**Comment by masakaji** [comment]
I updated necrobot to v0.7.8 but the issue is still having. I also tried to work in v0.7.6 & v0.7.7, but it said " you need to fill out googleusername and googlepassword in auth.json". so i checked my auth.json. And then, i restarted necrobot however the issue is still having.......
