### ISSUE TITLE
device settings not in use?

### ISSUE THREAD

**Issue by reinforcers** [NECROBOTIO/NecroBot#3483]
are device set no longer in use? because when I update it transfer my old setting then when i start the program suddenly it was reverted back to default settings

**Comment by schwartzadev** [comment]
Try copying the old information into the new config. It might have been an issue while updating. More detail would be great!

**Comment by nfettinger** [comment]
It probably could not merge your settings due to some unknown reason, and opted for a default config over a corrupted or outdated one.
