### ISSUE TITLE
Bot limit/ability [HELP]

### ISSUE THREAD

**Issue by KralElite** [NECROBOTIO/NecroBot#3484]
So what is the maximum amount of bots you can use ON THE SAME ACCOUNT without getting banned.  Is it true I can use 3 bots for lets say "account A" without getting them banned?  And the three bots will individually rack up points for me on that one account?

**Comment by Marsinator** [comment]
wait, are you trying to have 3 bots work with the same account?

**Comment by KralElite** [comment]
yeah

**Comment by KralElite** [comment]
is that not what multi-bot support means? I feel kinda dumb if that what it doesn't mean

**Comment by ChemiHatake** [comment]
it means you can run an amount of bots on an amount of different accounts.

**Comment by KralElite** [comment]
*facepalm*
