### ISSUE TITLE
Setting GPX path

### ISSUE THREAD

**Issue by hianghao** [NECROBOTIO/NecroBot#3485]
Hi, I am trying to set a GPX path but noticed that in the wiki section it says sourcing for new provider or something. Can i just use existing public submitted gpx path and modify the coordinate? Or I'll need specific tools to do it? I tried google gpx pathing but it doesn't return useful information.

**Comment by schwartzadev** [comment]
Yes, you can use other GPX files, however there are a couple different formats and they may not all work. Mileage may vary.
