### ISSUE TITLE
dupplicate pokemon not transfer

### ISSUE THREAD

**Issue by Mellowz** [NECROBOTIO/NecroBot#3486]
in a latest version 0.7.7 will not transfer duplicate pokemon, my inventory is full with duplicate pokemon.

**Comment by KOTR2003** [comment]
Need to post the config to confirm that's not the issue. Mine is still working fine.

**Comment by Mellowz** [comment]
@KOTR2003 sorry, here it is http://pastebin.com/JzCwA1cG

**Comment by Marsinator** [comment]
"KeepMinDuplicatePokemon": 1, means you keep 2 pokemon at all times (0=keep the original, 1=also keep 1 duplicate)

**Comment by KOTR2003** [comment]
^ beat me to it haha

**Comment by Mellowz** [comment]
@Marsinator i change already but that's was not fix

**Comment by ascer0** [comment]
ha ha... the same problem here... change the value and tranfer pokemn but not the duplicate .. only transfer are not listed in this part 
 "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

but exmaple i have 30 blastoise.. not 2 or 1 .. and .. i whish keep each one pokemon

**Comment by Magnaleikha91** [comment]
Ah, have this issue too.

**Comment by Mellowz** [comment]
thank you remove the PokemonsNotToTransfer and it's will work.
