### ISSUE TITLE
softbaned and unbanned please help

### ISSUE THREAD

**Issue by otong123** [NECROBOTIO/NecroBot#3494]
i wanna ask is there anyone same problem with me

i have 4 id but only 1 always get softbanned and unbanned, i change the ip with vpn and still get softbanned

not long after that the 3 id get softbanned and unbanned too

is there a solution?

thanks Mr or Mrs

**Comment by schwartzadev** [comment]
Try only 3 at once. That is the typicial max for ip bans

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by bulubebek** [comment]
duplicate #3417 #3408 #3351

1. you are "traveling" too much
2. run 3 bots at max
3. use VPN

**Comment by otong123** [comment]
thanks for advice
