### ISSUE TITLE
cant login in the lastest version

### ISSUE THREAD

**Issue by paulobortoli** [NECROBOTIO/NecroBot#3499]
it keeps saying that i have to fill out my log in informations in the auth.json, but i've arleady done that. What should i do?

this is my log file

[22:59:19] Perfect! You already have the newest Version 0.7.7
[22:59:19] Logging in using Ptc
[22:59:19] You need to fill out PtcUsername and PtcPassword in auth.json!

**Comment by martinwind** [comment]
same

**Comment by kurozani** [comment]
same here, it was fine in last version but once updated, I can't login, I tried to download the 7.6 version, but it said i haven't write my email and password :(

**Comment by iwantmyfile5** [comment]
It's not related to 0.7.7, I was using it fine until I got the same error. I think its Niantic servers crashing again, as everyone seems to have gotten the issue simultaneously.

**Comment by Jaysay1212** [comment]
If it was entered in the config, then check for quotes around both. "PtcUsername": "username",
"PtcPassword": "password",

Make sure in the auth.json that "AuthType": null, is not so. make sure it is "ptc" as well

**Comment by nnzw2000** [comment]
you just have to add the inverted commas
