### ISSUE TITLE
[ERROR] null refrence always

### ISSUE THREAD

**Issue by theosoft-git** [NECROBOTIO/NecroBot#3500]
[09:18:38] Logging in using Ptc
[09:18:41] Playing as somebody
[09:18:42] Detected realistic Traveling , using Default Settings inside config.json
[09:18:42] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.6992080261247 Lng: -73.9929001753199
[09:18:42] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:行号 361
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:行号 24
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:行号 16
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:行号 36
[09:18:42] Logging in using Ptc
[09:18:44] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:行号 135
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:行号 36
[09:18:44] Logging in using Ptc
[09:18:47] Playing as somebody
[09:18:47] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.6992080261247 Lng: -73.9929001753199
[09:18:47] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:行号 361
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:行号 24
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:行号 16
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:行号 36
[09:18:47] Logging in using Ptc
[09:18:49] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:行号 135
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() 位置 C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:行号 36

**Comment by radjesh** [comment]
Same here :(

**Comment by P-rus** [comment]
Also same in my script

**Comment by SirKoriban** [comment]
Try setting this value from true to false:

"SnipeAtPokestops": false,

Fixed it for me.

**Comment by schwartzadev** [comment]
Is this still happening with the latest?

**Comment by fartb0i** [comment]
I don't see it happening.

**Comment by nfettinger** [comment]
Duplicate of #3295
