### ISSUE TITLE
error  no pokestop availble always softban

### ISSUE THREAD

**Issue by allenperick** [NECROBOTIO/NecroBot#3503]
Every 5mins its always no pokestop available in the are or the are is to small etc etc..

Maybe the api is getting updated again so not bots in the following hours

**Comment by schwartzadev** [comment]
Please use better English and more detail. Ask on the discord chat, not github.

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
