### ISSUE TITLE
Telegram Invalid token format

### ISSUE THREAD

**Issue by abratar** [NECROBOTIO/NecroBot#3505]
So I just created a bot with Telegram but it's token looks at the end like "[...]--PM4"  so when I start the bot it gives me this :" System.ArgumentException: Invalid token format".

My othe bot key has not the --PM4 or whatever and it works... I think its because of the "-" at the end of the key...

**Comment by schwartzadev** [comment]
There seems to be an issue with underscores and potentially dashes in the telegram key. Try the key without the `--` and then without the `--PM4`. Please share results.

**Comment by abratar** [comment]
But my other bot key has 2 underscores and it works

**Comment by Marsinator** [comment]
3461
