### ISSUE TITLE
Alter update 0.7.7 (null reference exception)

### ISSUE THREAD

**Issue by evetaku** [NECROBOTIO/NecroBot#3509]
![zzzzzzzzzzzzzzzzzzzzzz](https://cloud.githubusercontent.com/assets/6820983/17502834/706d6b9c-5e15-11e6-9653-26712f456f82.png)

what' happen ? before update its fine

**Comment by thtguy365** [comment]
having the same issue here was working a few hours ago

**Comment by fartb0i** [comment]
I had this even before the update. So, this has nothing to do with the update.

**Comment by schwartzadev** [comment]
duplicate #3500
