### ISSUE TITLE
A humanizer option

### ISSUE THREAD

**Issue by Leigha888** [NECROBOTIO/NecroBot#3512]
Can we get a true/false option added to the config to disable the 5 ~sec action delay?

  "DelayBetweenPlayerActions": 1000, 

yet there is approximately 5 seconds delay between actions. I'm assuming its built in humanizer.

**Comment by schwartzadev** [comment]
See `DelayBetweenPlayerActions` in the config

**Comment by Leigha888** [comment]
Did you even bother read what I said?
