### ISSUE TITLE
IP is falsely reported as blacklisted

### ISSUE THREAD

**Issue by MSZ28** [NECROBOTIO/NecroBot#3517]
Hi. I can't use my google account on the bot after 0.7.7 and on 0.7.8.
it says my IP is blacklisted but it is not. because i can login to pokemon go on my phone and play the game... no problems there! so Niantic has not blocked my IP... Some thing is wrong with the bot.
I even deleted the whole bot and re installed and re configured it... still no success... Please help me if there is a solution.
Thanks

**Comment by schwartzadev** [comment]
Is your phone on mobile networks or on your wifi? try using a proxy or VPN and see if the issue persists.

**Comment by MSZ28** [comment]
on both wifi and cellular, my phone works fine ... I tried some different VPNs and Proxies but the problem is just with the Bot...

**Comment by aVitomin** [comment]
mac address ban maybe

**Comment by MSZ28** [comment]
> mac address ban maybe
 little bit odd then!!! Like I am the only one that gets MAC Banned! and every thing in my config file is so normal and I just ran the bot for a few hours... not even a whole day!!!
I guess that is not my case... Some thing else should be wrong!

**Comment by schwartzadev** [comment]
In this case, your IP is probably not blacklisted because you can use it with your phone. It is probably a problem with your config or installation. Try deleting and doing a fresh install.

**Comment by MSZ28** [comment]
Just now for the second time I deleted the whole thing, re-downloaded and re-Configured it from scratch... No success yet... This the message:

> Initializing NecroBot logger at time 8/9/2016 8:46:48 AM...
[08:46:50] Perfect! You already have the newest Version 0.7.8
[08:46:50] Logging in using Google
[08:46:52] Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..

**Comment by thedarkfalcon** [comment]
I'm getting similar behaviour here #3473

**Comment by schwartzadev** [comment]
@thedarkfalcon are you also getting the "Your IP might have been Blacklisted by Niantic. Exiting.." error?

**Comment by thedarkfalcon** [comment]
@schwartzadev yes. I have described the behaviour, and posted a snippet of a log in the other issue.

**Comment by MSZ28** [comment]
@schwartzadev Unfortunately no... I just have 1 laptop... and my phone... nothing else...

**Comment by MSZ28** [comment]
Ok, I solved my problem:
Used a VPS in another country so now I have a new IP and it is not a public IP (like some public/free VPNs) ... Now I am not black listed!
