### ISSUE TITLE
Cant even log in

### ISSUE THREAD

**Issue by AguilaHub** [NECROBOTIO/NecroBot#3520]
Just opened the bot for the first time, started a setup and when i finished the bot started loging in to google. Thats all i got by now and it isnt looking to get better

**Comment by ryfoster** [comment]
try close and reopen the program

**Comment by Jaysay1212** [comment]
#3500 ?

**Comment by vfuyong** [comment]
even a fresh installation doesnt login. This started from 0.7.7 and it was not fixed in 0.7.8.

**Comment by Firetribe** [comment]
Same problem, only tried with 0.7.8, no login possible with PTC. Reverted back to 0.7.6, everything is working fine...
Just tell me what I can do to help fix this :)

**Comment by nfettinger** [comment]
Sever issue.
