### ISSUE TITLE
Unable to Multibot with mutliple google accounts

### ISSUE THREAD

**Issue by Reborn1990** [NECROBOTIO/NecroBot#3521]
When I try to run my second bot with my second gmail account it says the username and password are incorrect. They are not. I can swap the order of gmail account bots and the other account that was just working will do the same thing. Is there a trick to getting multiple gmail accounts working or??? Thanks!!!

**Comment by jinkawasaki333** [comment]
It works for me. Maybe your login account is just wrong.

**Comment by parbonature** [comment]
maybe missing ( " )

**Comment by Reborn1990** [comment]
no like I said in original post. both bots work when the other isn't on. Did you do anything special to get it to run?

**Comment by parbonature** [comment]
I try from my ptc account, its work, I don't know with google

**Comment by Reborn1990** [comment]
I got it working =)!
