### ISSUE TITLE
giving error idk why but after some loop bot start then again this error (system null reference)

### ISSUE THREAD

**Issue by azmanomer** [NECROBOTIO/NecroBot#3525]
[06:07:35] (ERROR) System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\Inventory.cs içinde: satır 361
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs içinde: satır 24
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\State\InfoState.cs içinde: satır 16
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\State\StateMachine.cs içinde: satır 36

**Comment by schwartzadev** [comment]
duplicate #3500

**Comment by semihusta** [comment]
aynı sorun bende de var çözebildin mi ömer
