### ISSUE TITLE
Pokemons are not evolving

### ISSUE THREAD

**Issue by mtronca** [NECROBOTIO/NecroBot#3529]
"EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,

  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],

and still it doesnt evolve my pidgeys... it says i have 10 potentials evolves but it doesnt evolve my pokemons.

**Comment by dmo1111** [comment]
same with above settings

**Comment by Rick058** [comment]
My evolving works on these settings:

`  "EvolveAboveIvValue": 40.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 10.0,
  "KeepPokemonsThatCanEvolve": false,`

PokemonsToEvolve: http://pastebin.com/raw/8ixm8VBR
pastebin to prevent a long ass message.
