### ISSUE TITLE
Issues with Telegram

### ISSUE THREAD

**Issue by therealiskandar** [NECROBOTIO/NecroBot#3530]
Thanks for this update, it's really helpful.
But, if I may give suggestions:

-Showing IV points will be a great addition
-'Eggs Hatched' value is always the same as 'Pokestop visited' value
-'Pokedex entries' shows wrong counts

**Comment by schwartzadev** [comment]
@MineMalox

**Comment by schwartzadev** [comment]
duplicate #3409
