### ISSUE TITLE
Can someone pass me the download link?

### ISSUE THREAD

**Issue by bluezerodany** [NECROBOTIO/NecroBot#3531]

**Comment by kadektop2** [comment]
check out the releases tab.

**Comment by schwartzadev** [comment]
https://github.com/NECROBOTIO/NecroBot/releases/
Don't post this sort of question in the issues section.
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by Rick058** [comment]
https://github.com/NECROBOTIO/NecroBot/releases/download/v0.7.8/Release.zip

Download > unzip > run .exe > follow steps
Guide:  https://github.com/NECROBOTIO/NecroBot/wiki/Compiled-Releases
