### ISSUE TITLE
7.8

### ISSUE THREAD

**Issue by cwalther65** [NECROBOTIO/NecroBot#3532]
Transfered all pokemon after up date to 7.8

**Comment by schwartzadev** [comment]
Please elaborate

**Comment by Dreker** [comment]
same here!

FUCK

**Comment by Rick058** [comment]
Maybe check your config.json settings after an update to ensure everything is still correct?

**Comment by elen1981** [comment]
where‘s the link to download?

**Comment by cwalther65** [comment]
Yea I Just Figured Out Why It Did It Wish I Would Have Checked first.

**Comment by danooh** [comment]
check your config.

the default line of pokemon duplicates to keep changed.

it states "KeepMinDuplicatePokemon": 0,

just change it to 1 again.

**Comment by Jaysay1212** [comment]
@elen1981  https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.7.8 scroll down and click Release.zip

**Comment by Dreker** [comment]
@danooh thx, fixed now.

i lost all pokemons LOL

**Comment by cwalther65** [comment]
Have to change keepminduplicatepokemon from 0 to 1 in config

**Comment by cwalther65** [comment]
Late lol

**Comment by Dreker** [comment]
just this need fix or more something?

**Comment by phoojunior** [comment]
transfer item not function.. im not programers cant setup config.json..

always realese update every time.. and always more bug.. sadly..

**Comment by willbp** [comment]
same here, have a solution guys?

**Comment by Jaysay1212** [comment]
@willbp  check danooh's comment up above

**Comment by elen1981** [comment]
yeah~got it，thank guys

**Comment by willbp** [comment]
mine config:

...
"PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
...

fail to me

**Comment by DariusFoxy** [comment]
Did they eliminate the line that tells you how far til the next pokestop. it used to say, distance and time expected to next poke. Not sure how to get it back, thanks.

**Comment by deduijk** [comment]
I lost my nicest ones b4 i saw a pokemon i was sure i had only 1 of being transferred.. ARGG

Ah well. my fault. Did check the config, but missed that one.
