### ISSUE TITLE
Inventory is full, no items looted. Fix?

### ISSUE THREAD

**Issue by TayTay582** [NECROBOTIO/NecroBot#3533]

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by mkernell** [comment]
you are probably over the maximum item recycle value thats why it doesnt recyle. Check you max potions,pokeballs,berry value make sure its around 300
