### ISSUE TITLE
The new update might of messed up Necrobot

### ISSUE THREAD

**Issue by AlgorithmHD** [NECROBOTIO/NecroBot#3537]
After the new update for Pokemon GO many people are getting errors or in my case it transfers almost all the pokemon (i was lucky to stop the program before it did) This might only be happening to me but idk.

**Comment by danooh** [comment]
just check your config.
some1 alrdy opened an issue stating your prob.

the config states "KeepMinDuplicatePokemon": 0, <= change it to 1 and you'll be fine

**Comment by Dreker** [comment]
@danooh  what is the new limit?

**Comment by Jaysay1212** [comment]
@Dreker  It seems to start to teleport around 50km/hr but I've had no problems with up to 30km/hr

**Comment by zybertronix** [comment]
new version has a different config setting im using the one from 0.7.7

**Comment by danooh** [comment]
@Dreker dnno yet. but somethin over 30km/h sounds reasonable. i guess some devs will figure it out in some hours as a new pop up window intends to keep drivers off playing GO while playing.

**Comment by nfettinger** [comment]
This is not an issue with the code.
