### ISSUE TITLE
multibotting causing softbans

### ISSUE THREAD

**Issue by azeroth7** [NECROBOTIO/NecroBot#3539]
so when using 4 different accounts i get softbans on all of them, while using two seems to run smoothly

**Comment by danooh** [comment]
yea. i experienced that prob last night.
your ip will get softbanned for some minutes.
2-3 run smoothly here as well.
have u tried using proxies? i could not test it yet

**Comment by xafelld** [comment]
That has been happening for a little while with any bot. Ninantic is banning IP's of people muli-botting. You will need to figure out how to proxy.

**Comment by H2OKing89** [comment]
I am having the same issue with 3 running

**Comment by zybertronix** [comment]
same here running on 6

**Comment by azeroth7** [comment]
this happened to me first time today, been using four accounts till now running smoothly so i guess it has to do with the new update they released or sth

**Comment by zybertronix** [comment]
can anybody confirm ? running multiple accounts will softban your IP ?

**Comment by H2OKing89** [comment]
I have 1 running fine and two that go in and out of softban all 3 are on 7.8

**Comment by Seyrenvox** [comment]
currenlty running 3 bots. 15 minutes gap runtime. delay action set to 2s (2000ms). walkspeed around 40~60kmph. been running for 52 mins (since the first bot started). no major issue. i'm using the latest Necrobot (7.8)

**Comment by Magnaleikha91** [comment]
Running 2, one of mine is normal, when the other one, said looting failed, possible soft banned.

**Comment by H2OKing89** [comment]
I'll trow up a log file
[NecroBot-2016-08-08-22.txt](https://github.com/NECROBOTIO/NecroBot/files/408166/NecroBot-2016-08-08-22.txt)

**Comment by Rick058** [comment]
3 bots at a time + pogo sniper on
100km/h walking in Central Park, NY.
Delay action = 2, catch Pokemon = 1
__ Running for hours, no issues at all.

**Comment by Seyrenvox** [comment]
i don't know why i can't mention anyone here.
Magnaleikha: you can try Rick's trick here https://github.com/NECROBOTIO/NecroBot/issues/3423#issuecomment-238409033

H2Oking: try to update, maybe? or change location? or VPN active? i never understand about throw exception in coding

**Comment by Seyrenvox** [comment]
thank you, Rick. been wantin to ask you about that, since an hour ago. but i don't know how to message someone here in Github

**Comment by H2OKing89** [comment]
trying the vpn, looks good so far

**Comment by schwartzadev** [comment]
3/ip seems to be the limit.

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
