### ISSUE TITLE
What is "TransferWeakPokemon" Setting

### ISSUE THREAD

**Issue by ProfKush** [NECROBOTIO/NecroBot#3540]
What is "TransferWeakPokemon" setting, what is considered weak? How does it work?

**Comment by DLHC** [comment]
DO NOT CHOOSE "true", 

YOU WILL LOOSE MANY OF YOUR PETS

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
