### ISSUE TITLE
Declining update fails authentication

### ISSUE THREAD

**Issue by schwartzadev** [NECROBOTIO/NecroBot#3542]
Often when a new update is released, if I decline, (google) authentication fails. If I restart and accept, install the update and continue, authentication succeeds. I have heard talk about this in other issues as well. #3412 among others.

`[23:06:07] (UPDATE) New update detected, would you like to update? Y/N `
`n  `
`[23:06:09] (UPDATE) Update Skipped  `
`[23:06:09] (INFO) Logging in using Google  `
`[23:06:09] (ERROR) You need to fill out GoogleUsername and GooglePassword in auth.json!  `

**Comment by nfettinger** [comment]
Working as expected.
