### ISSUE TITLE
No Usable Pokestops In Your Area

### ISSUE THREAD

**Issue by blaketek14** [NECROBOTIO/NecroBot#3545]
After updated into 0.7.8, the bot always says No Usable Pokestops In Your Area
how can i fix it ?

**Comment by PokemonGodDan** [comment]
Agree, I am having the same problem

**Comment by zybertronix** [comment]
use 0.7.7 the newest release 7.8 has a different configuration setting  u can copy the config from 7.7 then paste it overwritting the one on 7.8

**Comment by schwartzadev** [comment]
If you haven't changed your config, this is probably an issue with the PoGo servers. Be patient and try again later.
