### ISSUE TITLE
Transfer Weak Pokemon??

### ISSUE THREAD

**Issue by jc1994jc** [NECROBOTIO/NecroBot#3549]
There's an option i find in the config file for transfer weak pokemon. this isnt explained in the transfer section in the wiki. Was just hoping someone could shed some light on this. I'm looking for a way to transfer any pokemon below a certain cp regardless of whether there's a duplicate of them or not. I still want the keep at least one duplicate filter on but i just want it all over level 1000cp. is this possible?

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
