### ISSUE TITLE
How i can see Device Setup in my phone Lenovo A-7000a??

### ISSUE THREAD

**Issue by poke081** [NECROBOTIO/NecroBot#3550]
can anyone help me about device setup in auth.json??
if you can help, please give me example about it...
Thank you

**Comment by bulubebek** [comment]
device information will be created automatically during first run. but you also can set it manually to suite your need. you can get Lenovo A-7000a devinfo [here](specdevice.com/showspec.php?id=5f3e-7da7-ffff-ffffda27ddfd#tabs-6).

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by poke081** [comment]
@bulubebek Thank you for information.. about "AndroidBootloader" is disable, its no problem..

@schwartzadev  : sorry about it...
