### ISSUE TITLE
Egg incubators in 0.7.7 and 0.7.8 release no longer counting km walked by bot?  

### ISSUE THREAD

**Issue by wyvern19** [NECROBOTIO/NecroBot#3553]
Ran 0.7.7 for 30 min and 0.7.8 for a while and see no change on the egg incubators.
[NecroBot-2016-08-08-20.txt](https://github.com/NECROBOTIO/NecroBot/files/408173/NecroBot-2016-08-08-20.txt)

**Comment by enerai** [comment]
set a lower average walking speed and try again.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by wyvern19** [comment]
Odd.  I had no issues with 0.7.3 to 0.7.6.   "WalkingSpeedInKilometerPerHour": 21.0 and still no change.  Only Pokestop looting and that is working without issues.

**Comment by dwaah** [comment]
21.0 is too high.

**Comment by wyvern19** [comment]
using 15 and still no change in egg km to go.

**Comment by wyvern19** [comment]
this had been working in previous releases without issue

**Comment by dwaah** [comment]
Mine is set to 14.4 and works just fine. (v0.7.8)
