### ISSUE TITLE
It recycled my ultraball and hyper potion

### ISSUE THREAD

**Issue by Zandrick** [NECROBOTIO/NecroBot#3556]
How to config to not let it recycled my greatball, ultraball and potion?

**Comment by danooh** [comment]
post your config

**Comment by Zandrick** [comment]
I see. Thanks so much!

**Comment by Zandrick** [comment]
How about if i want to keep two same pokemon, one with highest CP one with highest IV?
Is it able to do so?

**Comment by schwartzadev** [comment]
Do NOT post configs on Github @danooh @Zandrick 
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
