### ISSUE TITLE
Transfer random pokemon on start-up. 

### ISSUE THREAD

**Issue by DeusZtyr** [NECROBOTIO/NecroBot#3557]
The bot sometimes transfer random pokemon that are not duplicated when starting and continue to transfer until the program is closed. For example: Transferred Pidgeot CP 1208 (best CP 1208). 

Also My high CP eevee always get transferred away keeping a 172cp eevee instead. 

I found out that both issues have something to do with their IV like IVabove90or95 can only be keep but i have adjusted the MinIVtokeep to 0 but problem still exist

**Comment by schwartzadev** [comment]
Seems like you favor iv over cp. The bot keeps the 172 cp eevee because it has a higher IV

**Comment by willbp** [comment]
The bot dont delete all pokemons?
config ... "KeepMinCp": 1250,
if one pokemon < 1250CP he transfered?
