### ISSUE TITLE
[FEATURE] Bring Back Distance/Time to next pokestop output

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#3558]
As the title says, did they eliminate the line that tells you how far til the next pokestop. it used to say, distance and time expected to next poke. Not sure which line would apply to this, or if it's shut off somewhere else or how to get it back, thanks.

**Comment by schwartzadev** [comment]
Yes, this disappeared a few updates back. It would be great to have a true/false switch in the JSON to include this...

**Comment by nfettinger** [comment]
I have these changes made in a local branch. I will push when I have time.

**Comment by JohnnyVicious** [comment]
I see this is active again in 0.8.1 so thank you very much! @nfettinger
