### ISSUE TITLE
Sniping Parameters

### ISSUE THREAD

**Issue by MrForsaken** [NECROBOTIO/NecroBot#3560]
So, Every time I run this it refuses to snipe anything at all in the pogofeed list, 
Or rather it tries and never finds anything. 

((SNIPER) Did not find a Pokemon within the SnipingScanOffset!)

I was told over and over that means it has expired, or the coordinates are wrong. That's all fine and all, However when I manually snipe They are caught with no issue, and are infact there.

I have tried different configs moderators have sent and still have this odd issue. Any suggestions?

**Comment by sirvts** [comment]
im having the same problem :\

**Comment by raynsk** [comment]
i m having the same issue too, feel frustrating... 

But found a away to solve the problem, it has to be solved in code level. Search out the snipe function in SnipePokemonTask.cs, add some delay (2 to 3 seconds) between tele-porting, get object, encounter, etc... calls.

I believe it is server side restriction.

**Comment by xuninho** [comment]
I have same problem.

**Comment by MrForsaken** [comment]
So after adding this delay has anyone else had any luck...?

**Comment by gjc12g** [comment]
where to find SnipePokemonTask.cs cant find it anywhere...

**Comment by raynsk** [comment]
\NecroBot-master\NecroBot-master\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs

Just found out that more delay is needed for a higher success rate.

**Comment by alwayzgame** [comment]
any solution?

**Comment by MrForsaken** [comment]
No solutions yet. A bunch of random guesses. Nothing that actually works.

**Comment by raynsk** [comment]
![snipe](https://cloud.githubusercontent.com/assets/20840146/17506549/37f16012-5e3c-11e6-8d93-bc6f0ebdd966.png)

I succeeded by adding delay in code.

**Comment by cjhwick** [comment]
Can you explain what you added?

**Comment by alwayzgame** [comment]
how to add delay?

**Comment by michaelgaryscott123** [comment]
please explain

**Comment by raynsk** [comment]
I think it may be just a temp fix...

I added a 10 seconds delay before calling the GetMapObjects() in Snipe function in SnipePokemonTask.cs.

And some 3-4 seconds before EncounterPokemon.

I have read in somewhere that GetMapObjects() cannot be called in less than 10 seconds.

**Comment by raynsk** [comment]
delay is called, e.g. 10000 ms

 await Task.Delay(10000, cancellationToken);

**Comment by Tomabl** [comment]
Just put your "SnipingScanOffset" to 0.01. This works for me.

**Comment by gjc12g** [comment]
@raynsk now I've seen the file
but how do we modify it? cuz the files we usually download the "relase.zip"file 
do we need to download whatever showed in the screenshot into the computer and modify it ?
![image](https://cloud.githubusercontent.com/assets/20920231/17524170/6adca2fe-5e2b-11e6-91e6-5c047417f262.png)

**Comment by nfettinger** [comment]
Please update to the latest version and create a new issue if the problem persists.
