### ISSUE TITLE
Duplicates as hell

### ISSUE THREAD

**Issue by hijackerz** [NECROBOTIO/NecroBot#3561]
Hello , have 17 snorlax , 18 charichard , 8 drasgonites , alot of shity pokemons , can anyone make a config so its only keep 1 of the best ? so i dont have much duplicates ,

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
