### ISSUE TITLE
Seems that Nautic is flagging IPs 

### ISSUE THREAD

**Issue by PokemonGodDan** [NECROBOTIO/NecroBot#3565]
Bots aren't working and errors which I recall were"can't find pokestops" and "no lure pokemon" keep appearing. To fix this problem currently, I changed my IP address via VPN.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
