### ISSUE TITLE
Recycle frequency and logic changed?

### ISSUE THREAD

**Issue by mooglemd** [NECROBOTIO/NecroBot#3566]
Since I updated from 0.7.7 to 0.7.8, the bot either never recycles after the initial recycle on login or does so extremely seldomly. I still have the recycle at 90.0 unchanged. But I have accounts with 600, 700 and 800. I end up getting inventory full etc unable to pick up items. 0.7.7 was fine. I played around with it alot and it seems like I have to set my numbers of items to collect significantly lower and set the recycle at to 10.0 to get it to even recycle at a decent rate.

**Comment by mattxx3** [comment]
same here

**Comment by prankkiss** [comment]
me too

**Comment by fadh22** [comment]
i got same problem too, i want to use 7.7 back but i lost it because its an auto update, can u please uplod version 7.7 and share the lin, plizzz

**Comment by mattxx3** [comment]
You can still get 7.7 on the release tab of github. Just make auto update false after extracting the zip.

**Comment by nfettinger** [comment]
Recycling is working for me using 0.8.0.
