### ISSUE TITLE
Why is it transferring all the pokemon?

### ISSUE THREAD

**Issue by sukhmypreet** [NECROBOTIO/NecroBot#3567]
Im new to necrobot, and I started up the bot with a new account, I as using it just fine, me being the curious person I am, I restarted the bot, and it randomly started transferring ALL of the pokemon! I read to go to the config, but all it shows me is translation.ca etc. How do I fix this? Thank you.

**Comment by danooh** [comment]
alrdy solved #3532

**Comment by gianpokemon** [comment]
already change but still transferring :(

**Comment by loneable** [comment]
I LOOKED AT MY CONFIG AND IT WAS ALREADY SET TO 1 AND ITS STILL TRANSFERRING ALL OF MY POKEMON QTF I KNEW I SHOULD HAVE KEPT THE OLD ONE RUNNING NOT ITS ALL FUCKED PLEASE TELL US HOW TO FIX FFS

**Comment by suicun93** [comment]
transfering all pokemon
I'm crying :'(

**Comment by LazyBrand** [comment]
Me too :'( Halp me...

**Comment by djscoobyg2** [comment]
This is a new error, just check about every hour for an update, I know how you feel, lost a 2187 snorlax </3

**Comment by nfettinger** [comment]
This is a configuration issue. Please make sure your config.json is compatible with the version you are running (try starting from scratch with the default one, and copy your desired settings back in). 
Disclaimer. Never use Necrobot on an account that matters. There is always a risk of failure, or a ban.
