### ISSUE TITLE
[FEATURE] Bounding box for walking

### ISSUE THREAD

**Issue by lorilith** [NECROBOTIO/NecroBot#3570]
I would like an option to create a (upperleft lowerright latlong is fine) bounding box outside of which the bot will not walk. It seems to migrate away from heavily populated pokestop areas instead of moving slightly farther towards a higher cluster of pokestops.

Setting an upper left lower right lat longs will help to keep it on the right track without restorting to GPX pathing.

**Comment by deduijk** [comment]
It already has a circular radius in which it will walk? Maybe the circle you're using is too small?
Check radius:
https://www.freemaptools.com/radius-around-point.htm

**Comment by lorilith** [comment]
The circle i use must be large enough to walk in a given area.  The problem comes in when i wish it to use a rectangle.  it prefers closer pokestops with no regard for the next few steps.  This causes a walk towards the wrong edge of the circle.  If we could set bounding coordinates (rectangle) or circle by config, it would allow for a bot to walk down  few roads rather than wander off the beaten path only to end up too far away from a pokestop to continue.

**Comment by deduijk** [comment]
Tracking a bot 'walking' on a map would be great, then you can see these types of issues. It would be good if a bot tries to stick to the roads, at least in city areas and not walk through a house or something... not too human like that way:).

**Comment by lorilith** [comment]
I use https://github.com/nicoschmitt/necrobotvisualizer with websocket for the moment

**Comment by deduijk** [comment]
Seems cool. Trying it out, but get an error on the npm install step

**Comment by badinbed** [comment]
The config is already polluted with too many highly situational options. Just create a ptx path for your case. Gives you more control anyway.

**Comment by deduijk** [comment]
WTF. now see it walks straight. That's not what i expect with "DisableHumanWalking": false,

**Comment by deduijk** [comment]
how do you make ptx paths? (sorry for the dumb question)

**Comment by nfettinger** [comment]
The current method uses a circle with a radius defined by the configuration. Other methods should use GPX paths.
