### ISSUE TITLE
[FEATURE] Runtimer; auto stop and return to home location

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#3572]
It would be nice if you could set a timer either in config or at runtime that stops the script after x minutes.
Alternatively a "stop button".

Max speed and variations on this by the humanizer will be taken into account to calculate the time needed to arrive back at the home coordinates (if possible; with stat how long till the next pokestop i figure this is possible), so when the timer is 0 you're back at home coordinates.

**Comment by schwartzadev** [comment]
I currently use caffeine and set a timer with that. Once the time finishes, computer sleeps and necro ends. In the meantime, I suggest that. Good ideas.

**Comment by nfettinger** [comment]
Duplicate of #3258
