### ISSUE TITLE
Snipe all Pokemon?

### ISSUE THREAD

**Issue by MystK** [NECROBOTIO/NecroBot#3574]
Is it possible to snipe all Pokemon without having to add it to the PokemonToSnipe.Pokemon array?

**Comment by Zedilurk** [comment]
Unless I'm understanding sniping wrong, the idea of sniping isn't just to catch Pokemon, it's to teleport an unnatural and potential unsafe distance (that could easily flag you as a bot) for the sake of catching a super rare Pokemon. There are fail safes in place that prevent you from doing this super often (ie, one teleport every 16 hours might appear like a strange GPS issue, where every 10 minutes will look super suspicious). 

So adding all Pokemon would result in your teleport to a rare Pokemon being potentially wasted on a Weedle, Pidgey, Rattata, etc.

**Comment by MystK** [comment]
What I use sniping for is 100IV Pokemon. I'm interested in all Pokemon, and since there's no min IV or min CP yet for sniping, I wanted to put all Pokemon onto the sniping list.

**Comment by vfuyong** [comment]
I dont think sniping involves teleporting, can someone confirm?

**Comment by katareborn** [comment]
To snipe you port to a specific lat/long coordinate click on the Pokémon then port back to your original location before throwing the poke ball making the game think that you caught the Pokémon in your starting position

**Comment by nfettinger** [comment]
Please use discord chat for configuration questions.
