### ISSUE TITLE
Google Sign in

### ISSUE THREAD

**Issue by bccapone18** [NECROBOTIO/NecroBot#3577]
It wont work when using my google information. keeps telling me to make sure i input the right username and password...there is no google username just your email?

**Comment by bccapone18** [comment]
anyone have the same issue?

**Comment by bccapone18** [comment]
or know how to fix it?

**Comment by vfuyong** [comment]
revert back to 0.7.6

**Comment by bccapone18** [comment]
how do i do that?

**Comment by schwartzadev** [comment]
Did you decline the newest update?

**Comment by vfuyong** [comment]
I have a 0.7.6 version here
https://www.sendspace.com/file/o8vbhj

**Comment by nfettinger** [comment]
Update to the newest version
