### ISSUE TITLE
Pokestop Pokeball farm bug/issue

### ISSUE THREAD

**Issue by peteristired** [NECROBOTIO/NecroBot#3578]
Turned off all the options (catching/transfering/evolving) to off and set the pokeballs to keep to 750, the bot doesn't delete normal pokeballs to farm great and ultra ones, is it intended or is there a way to make the bot farm great and ultra balls?

**Comment by VXT108** [comment]
I have the same problem. It was working well in 0.7.7

**Comment by nfettinger** [comment]
What you are asking is already implemented, and is already working as expected.
