### ISSUE TITLE
Always get 210 XP for pokemon

### ISSUE THREAD

**Issue by JimmyNeutrino** [NECROBOTIO/NecroBot#3579]
why do i always get 210 XP for pokemon? Can I change it to 100?

**Comment by elmaarmut** [comment]
Change your Pokeball throw settings in the config. For some reason you are always throwing excellent curve balls (CP limit, IV limit, excellent throw chance etc)

**Comment by Bobguy123** [comment]
Just checked and I'm also always getting 210 can anyone who is not share there settings?

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
