### ISSUE TITLE
how does i change my coordinates?

### ISSUE THREAD

**Issue by guilge** [NECROBOTIO/NecroBot#3580]
please help me,i will really thank you

**Comment by lorilith** [comment]
Not an issue, check Wiki and config file.

**Comment by Rick058** [comment]
config map > config.json

`DefaultLatitude `
`DefaultLongitude`

More info here: https://github.com/NECROBOTIO/NecroBot/wiki/Config

**Comment by guilge** [comment]
the .json file just wont open

**Comment by Rick058** [comment]
@guilge rightmouse button > open with ... > notepad
or install notepad ++ https://notepad-plus-plus.org/download/v6.9.2.html

**Comment by guilge** [comment]
thank you very,very much bro

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
