### ISSUE TITLE
Help with distanc

### ISSUE THREAD

**Issue by PokeyMasta** [NECROBOTIO/NecroBot#3584]

**Comment by PokeyMasta** [comment]
okay so i keep gtting this saying that my distance is not long enough. anyone know how to slove this it will work for a bit then this come on. 
![hlp](https://cloud.githubusercontent.com/assets/20919841/17504993/a20a97dc-5db2-11e6-9153-43d670ee7b14.png)

**Comment by PokemonGodDan** [comment]
You may have been IP flagged, use VPN

**Comment by Rick058** [comment]
Try https://github.com/NECROBOTIO/NecroBot/issues/3255#issuecomment-238303920

**Comment by PokeyMasta** [comment]
okay so how do you disable your prox? this is my atm 

{
  "AuthType": "google",
  "GoogleUsername": "",
  "GooglePassword": "",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "galaxy6",
  "DeviceId": "002c7e3954fd15d1",
  "AndroidBoardName": "universal7420",
  "AndroidBootloader": "G920FXXU3DPEK",
  "DeviceBrand": "samsung",
  "DeviceModel": "zeroflte",
  "DeviceModelIdentifier": "SM-G920F",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "samsungexynos7420",
  "FirmwareBrand": "zerofltexx",
  "FirmwareTags": "dev-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/zerofltexx/zeroflte:6.0.1/MMB29K/G920FXXU3DPEK:user/release-keys"
