### ISSUE TITLE
  "KeepMinDuplicatePokemon" its wrong.

### ISSUE THREAD

**Issue by kalilc** [NECROBOTIO/NecroBot#3589]

**Comment by kalilc** [comment]
"KeepMinDuplicatePokemon" on 0 should still keep the original pokemon, its the number of DUPLICATES you want. Thats why it started transfering everybody pokemons in 7.8. Even set to 1 here still transfer, im using on 2 but not sure if its safe too.

**Comment by spamfighter82** [comment]
not that again -.-

**Comment by kurozani** [comment]
thank you, changed it to 2 worked, changed it to 1 and all my lovely pokemon is gone, aarrgghhhh

**Comment by vfuyong** [comment]
Is this considered catastrophic?
