### ISSUE TITLE
PrioritizeIvOverCp not working

### ISSUE THREAD

**Issue by GRINSPANKER13** [NECROBOTIO/NecroBot#3590]
Running v0.7.8 and some of my pokemon with lower cp are being transferred.

`"PrioritizeIvOverCp": false,`

First time:
`[22:14:55] Marowak     	- CP:  170  IV:  91.23%   [Best CP: 1379  IV:  83.87%] (Candies: 1618)`
`[22:15:05] Snorlax     	- CP:  873  IV:  86.15%   [Best CP: 2611  IV:  84.15%] (Candies: 235)`
`[22:15:14] Rhyhorn     	- CP:  725  IV:  68.40%   [Best CP:  123  IV: 100.00%] (Candies: 1411)`

Second Time:
`[22:46:31] Farfetchd   	- CP:  160  IV:  70.21%   [Best CP:  992  IV:  90.91%] (Candies: 456)`
`[22:46:42] Aerodactyl  	- CP: 1438  IV:  79.62%   [Best CP:  851  IV:  88.84%] (Candies: 127)`
`[22:46:54] Aerodactyl  	- CP:  851  IV:  88.84%   [Best CP:  819  IV:  64.94%] (Candies: 128)`
`[22:47:05] Aerodactyl  	- CP:  819  IV:  64.94%   [Best CP:  680  IV: 100.00%] (Candies: 129)`

Third Time:
`[22:49:39] Golbat      	- CP:  250  IV:  79.10%   [Best CP: 1531  IV:  57.03%] (Candies: 4667)`
`[22:49:49] Rhyhorn     	- CP:  961  IV:  91.28%   [Best CP:  841  IV:  79.98%] (Candies: 1422)`
`[22:49:58] Rhyhorn     	- CP:  841  IV:  79.98%   [Best CP:  123  IV: 100.00%] (Candies: 1423)`

Full config: http://pastebin.com/Ti4Metw9

**Comment by pogoBotter** [comment]
For me, I've turned it TRUE but still it transfers higher IV pokemons because they have low CP.

**Comment by nfettinger** [comment]
Duplicate #3338
