### ISSUE TITLE
Can't find any Pokestops !!

### ISSUE THREAD

**Issue by ppa993** [NECROBOTIO/NecroBot#3592]
It's suddendly can not find any pokestops a few minute ago.

![image](https://cloud.githubusercontent.com/assets/13492824/17505614/8597755a-5e2c-11e6-9e2e-5d99a2b55b09.png)

**Comment by LTGRaven** [comment]
same fam

**Comment by suicun93** [comment]
hóng <3

**Comment by mirdhan123** [comment]
its work here

**Comment by kalilc** [comment]
Hello Bolny

**Comment by krzonsteam** [comment]
Same here

**Comment by sarah1598** [comment]
Me yoo.Can' work

**Comment by bastacs** [comment]
Banned ~ same with me, play with bot then get same notice , and i try play with nox player and BAMS!!!! NO POKESTOP ANYWHEREE GGTQ

**Comment by iamjiiyan** [comment]
same here

**Comment by Darkrox** [comment]
Got the same problem, 
Getting a new IP and closing all but 2 clients solved it though.

**Comment by bastacs** [comment]
UP UP IS WORKING~

**Comment by koubie** [comment]
ya'll know why?
because I bet all of you running multi accounts, correct me if im wrong
so your IP addresses have been banned =))

**Comment by ppa993** [comment]
It is up and running again, for like half a minute :<<

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
