### ISSUE TITLE
Transfered most of my pokemons

### ISSUE THREAD

**Issue by Asakura235** [NECROBOTIO/NecroBot#3594]
Yesterday I started to use necrobot and today when i run the program it transfered most of my pokemons . I still have 6 instead of 70 :) what should i do ?

**Comment by pogoBotter** [comment]
Should have checked your config and known what you are doing. That's what you get for doing random things despite being technically weak.

**Comment by Asakura235** [comment]
Really helpful :) mentality *****

**Comment by Simpuhl** [comment]
Lol^

**Comment by kalilc** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3589

**Comment by Asakura235** [comment]
Thanks

**Comment by kurozani** [comment]
changfe your duplicate to keep to 2, if you use 1, it will still transfer them

**Comment by funmix** [comment]
this happened to me once. only left one pokemon in the list. all others are gone. wondering which config should take note? so it won't transfer all the pokemon.

**Comment by RichardZhaoE** [comment]
This keepminduplicate thing will fuck over everyone one day. 
One of the devs @simplyphp, will tell you to put KeepMinDuplicates = 0 and that would mean it keeps NO DUPLICATES which means ONE OF EACH and =1 would mean ONE DUPLICATE or TWO OF EACH.

BUT, when you set it to 0, it'll literally toss all your pokemon. But when you set it to 1, it keeps 1 of each.

THEN, there was a version where if you set to 1, it KEEPS TWO OF EACH, which is where i set it to 0. Next version, it transferred ALL my pokemon. 

NOW, i set it back to one. 

AND NOW, @kurozani is telling you to set to 2? How does this even make sense. These settings need to be defined better and not in constant flux.

**Comment by Asakura235** [comment]
It keeps 2 now :) but it works .

**Comment by funmix** [comment]
Agree with @RichardZhaoE 

Otherwise will be same as me, all pokemon are gone. :)

**Comment by nfettinger** [comment]
Duplicate
