### ISSUE TITLE
[FEATURE] Better Humanlike Walking

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#3597]
I have the option: "DisableHumanWalking": false,

I would expect the humanizer to do its' thing, but when i follow it op visualizer i see straight paths. I cannot see a variance in speed either, but that might be only visual (or the update cycling between the bot and visualiser).

![pathing](https://cloud.githubusercontent.com/assets/20919235/17505358/e112e152-5e00-11e6-9fc2-30c3113f3730.png)

A human path will stick to more rules: 
- Not walking on water:) (unless there's a bridge)
- sticking to roads or paths mostly (unless not in a city or in a park)
- !!NO STRAIGHT VECTORS; i never seen a human walk straight lines: there needs to be some differentiation 
![pathing](https://cloud.githubusercontent.com/assets/20919235/17505473/a479aacc-5e01-11e6-813e-9e502fe80d15.png) (blue gray path would be more like a human (ignoring the paths atm, because that's probably too hard?)

Could a feature be implemented that will make sure there are no straight vectors?
Also: when using ptx paths: will there be some variation in the path the both will walk (so a bit straying to left and right)?

**Comment by teevthoj** [comment]
where do you download that visualiser at? i have teh 1.0.7 and it wont work

**Comment by deduijk** [comment]
https://github.com/nicoschmitt/necrobotvisualizer/releases

**Comment by member68** [comment]
You also need to set "UseWebsocket" to true in the Necrobot config file.

**Comment by LoktOoO** [comment]
I was thinking the same think about walk 'human'
We can use google API to plan a route ( 2500 per day so we should use it to plan 50 move at each call for example)
Use GPX file to plan more realistic move ( will be always the same between eache cycle)

**Comment by nfettinger** [comment]
Use GPX files.

**Comment by deduijk** [comment]
GPX files will not solve the issue.
AT least a random variance on the vector needs to be implemented: 
* Speed up, slow down (A human doesn't walk at a constant speed.)
* Variances within the travelling vector (slight  perpendicular movement on the vector, also random (but small amount)
