### ISSUE TITLE
Question on low CP

### ISSUE THREAD

**Issue by CrixalisRox** [NECROBOTIO/NecroBot#3601]
Question: My non-bot account at level 16 is getting pokemon with CP 800 above,
While my bot account at level 18 only get pokemon with CP less than 700. 
Both account is at same longitude and latitude. 

Appreciate your help and feedback.

thanks alot

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
