### ISSUE TITLE
0.7.8 User credentials are invalid and login failed

### ISSUE THREAD

**Issue by shadowppt** [NECROBOTIO/NecroBot#3604]
Hi Robot Master,

After updating v0.7.8 today, I meet error message `User credentials are invalid and login failed` when log in server, then robot is stopped and closed.
I am not sure this symptom is bug or my account is blocked. (ptc account)
Could you help to provide some suggestion about this symptom.

Thanks.

**Comment by schwartzadev** [comment]
Hi Robot User,

I recommend that you double check auth.json to make sure that the credentials are still there. Sometimes on update, the credentials get scrambled.

Thanks.

**Comment by shadowppt** [comment]
Hi Robot Master,

I had been check auth.json, the cerdentials are still there.
Is there possible item will cause this symptom?
Please give some suggestions to let me try to solve it.

Thanks.

**Comment by deduijk** [comment]
I had the same issue.
Just simply retyping user and pass solved it.

Alternative: delete config and aut and start the bot: you will be prompted for the information again and then is definitely works again. Might have missed a comma somewhere:)?

**Comment by shadowppt** [comment]
Hi Dedui,

Thanks for you suggesstion.
I had been delete config/auth.json, then retyping user and password again, the log shown as below.

[13:48:39] (UPDATE) Perfect! You already have the newest Version 0.7.8
[13:48:39] (INFO) Logging in using Ptc

It stopped at "Logging in using Ptc".
If I closed the robot and re-start it, it also shows "User credentials are invalid and login failed" and closed robot, this result show that this method can not be fixed on my side.

Thanks.

**Comment by hyohaluk** [comment]
@shadowppt 
same problem
thx .

**Comment by vfuyong** [comment]
This is a problem from 0.7.7, and after two released, it was not fixed yet.

**Comment by shadowppt** [comment]
Hi hyhaluk/vfuyong,

I meet this error message account, it still can not be logged in on smart phone.
Did you try to log on your smart phone?

Thanks.

**Comment by sameersmanohar** [comment]
Same issue I am facing. I tried from 0.7.8 to 0.8.0 all the latest ones. same issue happening for me too. this issue persists on setting up the bot fresh also.

**Comment by shadowppt** [comment]
Hi Sam,

I also try v0.8.0, the results are the same, but I still can not log in my ptc account...

Thanks.

**Comment by hyohaluk** [comment]
stuck here

![capture](https://cloud.githubusercontent.com/assets/20678249/17506435/0c4b6592-5e33-11e6-935a-0f4143ee0a03.PNG)

thx for solution

**Comment by sameersmanohar** [comment]
Yes "shadowppt" I am also not able to login with ptc and google both. the above screenshot is same I am getting.

**Comment by hyohaluk** [comment]
@shadowppt @sameersmanohar use v.0.7.7 instead

set  "AutoUpdate": false,  in config.json

this work!

**Comment by shadowppt** [comment]
Hi hyohaluk,

I try it on v0.7.7, it still failed...

**Comment by sameersmanohar** [comment]
Hey "hyohaluk" no. this trick also did nt work for me. I tried it. strucked at logging in screen.

**Comment by hyohaluk** [comment]
@shadowppt  @sameersmanohar  sorry man try v.0.7.6
![capture](https://cloud.githubusercontent.com/assets/20678249/17507075/bd52fd9c-5e37-11e6-9a8a-0b2d1a8cdcb5.PNG)

hope it'work

**Comment by sameersmanohar** [comment]
Hey Hyohaluk, it worked... it used to ... I updated and it got strucked. 
thanks thanks for WA.

regards

**Comment by hyohaluk** [comment]
@sameersmanohar  :D
