### ISSUE TITLE
sniper issue: keep looping coordinates without pokemons

### ISSUE THREAD

**Issue by acrohk** [NECROBOTIO/NecroBot#3605]
I use Pogo Location Feeder with necrobot 0.7.8, after running the bot for a while, I found it keeps looping for coordinates that have no pokemons.

to confirm it was not resending by the feeder, I close the feed program, and it is still looping.

**Comment by sirvts** [comment]
i have the same problem... cant snipe any pokemon for a 1hour already

**Comment by raynsk** [comment]
#3560

**Comment by acrohk** [comment]
no, it is not the same as #3560, that one was only an issue that need extra delay waiting for the pokemon to show up.

my issue here is, when sniping failed, the program will keep snipping for that again.

**Comment by CamiloRguez** [comment]
@raynsk I think that is no the same problem,

**Comment by sirvts** [comment]
@CamiloRguez how that fix the problem?

**Comment by CamiloRguez** [comment]
@sirvts If u remove last pokemon sniped u wont snipe for him again in the next loop (I think)

**Comment by acrohk** [comment]
@CamiloRguez yes I think so, have to wait for the next release to confirm.

**Comment by GediminasMasaitis** [comment]
Can confirm this bug. The sniper queues all Pokemon from the feeder, but doesn't remove it after sniping, resulting in something like this:

![image](https://cloud.githubusercontent.com/assets/7861188/17507369/f63b0b4c-5e17-11e6-860f-28969fced35b.png)

This repeats every sniping batch, with a few new Pokemon added at the end that got queued during the iteration.

**Comment by acrohk** [comment]
didn't have patience for the next release, just downloaded visual studio and compiled.
as @CamiloRguez said, the commit [ddfc92c](https://github.com/NECROBOTIO/NecroBot/commit/ddfc92c9fd800c022f0d2689996080ee47c80bdb) fixed this issue, and I'm happy now.
