### ISSUE TITLE
Corporate Account Log In

### ISSUE THREAD

**Issue by 942v** [NECROBOTIO/NecroBot#3610]
Can I use a private domain email that is managed by google?? 

Something like: username@mydomain.com

**Comment by jinkawasaki333** [comment]
It's easier to just try it out.

**Comment by 942v** [comment]
@jinkawasaki333 Thx for the reply. 

I did but it's not working :/

**Comment by jinkawasaki333** [comment]
Then it means that it has to be something ending with @gmail.com.

**Comment by schwartzadev** [comment]
solved
