### ISSUE TITLE
How do i transfer duplicated pokemons like snorlaxs and charizards?

### ISSUE THREAD

**Issue by a498716886** [NECROBOTIO/NecroBot#3612]
i tried to set up but nothing worked for me D:

**Comment by Unentertained** [comment]
Please read the wiki.
https://github.com/NECROBOTIO/NecroBot/wiki/Config#pokemontransferfilter-list

**Comment by a498716886** [comment]
maybe i typed in something wrong , thanks you :D ill look through it again

**Comment by Longpc** [comment]
delete it from PokemonsNotToTransfer and make sure your setting in PokemonsTransferFilter for them same with what you want :dancer:

**Comment by a498716886** [comment]
my snorlax setting are correct for sure but it doesnt transfer at all..

**Comment by XiaDao** [comment]
@a498716886  you can delete snorlax fromPokemonsNotToTransfer property list!
