### ISSUE TITLE
Logging in using Google

### ISSUE THREAD

**Issue by qwertzuiopii** [NECROBOTIO/NecroBot#3617]
[7:57:54] <UPDATE> Perfect! You already have the newest Version 0.8.0
[7:57:54] <INFO> Logging in using Google

nothing happens afterwards. any idea why it wont log in?
info: when changing the password in the auth.json it says wrong password
![unbenannt](https://cloud.githubusercontent.com/assets/20920788/17506309/1ff9a28c-5e08-11e6-8796-4665ca0450f8.PNG)

**Comment by mariodc2008** [comment]
Same issue here! Please help..

**Comment by Sheetka** [comment]
doesnt happen on earlier versions

**Comment by yihuxingkong** [comment]
maybe you should setup proxy settings in config/auto.json
console dont use system proxy by default.

**Comment by qwertzuiopii** [comment]
well i am using an automatic configuration script but that should not affect the bot at all. at least it didn't in the older versions.

**Comment by qwertzuiopii** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3426
looks like it is an older problem
"solution" to this was waiting, appearantly it worked for some people, but not for all

**Comment by yihuxingkong** [comment]
older versions do use system proxy
since 0.7.7 or 0.7.6 they changed it
so in newer versions if u cant access google without proxy, u need to setup proxy settings in config/auth.json

**Comment by Sheetka** [comment]
got the same, older version working fine. tried logging in with working sock5 proxy and without

**Comment by qwertzuiopii** [comment]
oh ye now i see ^^
thanks yihuxingkong
it works fine for me now with configured proxy settings
but why doesn't the bot use the system proxy?

**Comment by yihuxingkong** [comment]
#1929 
#1945

**Comment by Sheetka** [comment]
How did you fix it? I got proxy set up in auth

**Comment by qwertzuiopii** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20920788/17507808/0e619ba6-5e12-11e6-8d17-4d95c7b15cf3.PNG)

**Comment by Sheetka** [comment]
Yea I got the same.. weird..

**Comment by freewilly2u** [comment]
i dont have any proxy server how can i set?

**Comment by Sheetka** [comment]
for me it does work without proxy settings, but when I use a WORKING proxy (currently using it with Proxifier) it gets stuck on logging in

**Comment by jimz93** [comment]
i've got this issue since version 0.8.0 :(
any solution available yet?

**Comment by nfettinger** [comment]
Configuration issue.
