### ISSUE TITLE
0.8.0. Weird bug

### ISSUE THREAD

**Issue by bubinek000** [NECROBOTIO/NecroBot#3624]
Idk how to describe,screenshot explains that
![2016-08-09 1](https://cloud.githubusercontent.com/assets/7796656/17506503/a0791b80-5e09-11e6-8091-37e560df0b49.png)

**Comment by ntoenis** [comment]
Duplicate #3618

**Comment by iPollox** [comment]
Duplicate #3618

**Comment by bubinek000** [comment]
Sorry,didnt saw that

**Comment by schwartzadev** [comment]
Duplicate #3618
