### ISSUE TITLE
0.8.0: SnipeIgnoreUnknownIv - Option being ignored by sniper

### ISSUE THREAD

**Issue by JABirchall** [NECROBOTIO/NecroBot#3625]
^title
http://i.imgur.com/IDnZGp4.png

since 0.8.0 the bot is ignoring SnipeIgnoreUnknownIv option

also MinDelayBetweenSnipes is being ignored. the bot is trying to snipe instantly 1 after the other. Its not waiting the 5 seconds i have set

**Comment by sing1222** [comment]
> SnipeIgnoreUnknownIv (Value)

Used when  UseSnipeLocationServer  is set to  true  If NecroBot cannot determine the IV value from the sniping location service and this value is set to  true , it will snipe them anyways. If set to  false , Necrobot will ignore the Pokemon.

https://github.com/NECROBOTIO/NecroBot/wiki/Config#snipeignoreunknowniv-value

**Comment by JABirchall** [comment]
That description is backwards from the setting name...
The setting name basically describes it as "Do you want me to ignore pokemon with an unknown IV"

It should be called SnipeDONTIgnoreUnknownIv

**Comment by theloser** [comment]
I agree with @JABirchall , the description in the wiki is wrong! Back in the 0.6.x days I had to set "SnipeIgnoreUnknownIV" to "true" to IGNORE pokemon with unknown IV. Haven't tested the newer (0.7.x/0.8.x) releases, so I can't say if this setting is ignored or not.

**Comment by martinwind** [comment]
SnipeIgnoreUnknownIv, if true u wont snipe any pokemon with unknown iv

**Comment by theloser** [comment]
Just tested the newest releaese from source and it's working -- set SnipeIgnoreUnknownIv to TRUE to only snipe Pokemon with KNOWN IV.

**Comment by sing1222** [comment]
In V0.8.0, I set true still sniper and catch unknowm IV.

**Comment by JABirchall** [comment]
Dont know why this was closed as SnipeIgnoreUnknownIv is being ignored.

true or false sniper is trying to catch unknownIV pokemans
