### ISSUE TITLE
Gettin Softabanned

### ISSUE THREAD

**Issue by Blaucide** [NECROBOTIO/NecroBot#3627]
I'm getting istantly softabanned everytime is use the bot. Someone know something?

**Comment by Melancolie** [comment]
prolly the servers are in bad shape

**Comment by bastacs** [comment]
same with me

**Comment by CamiloRguez** [comment]
@Blaucide Some PoGO servers are down or laggy, maybe your problem its beacause of this

**Comment by 17yongga** [comment]
How many bots running at the same time? you can run at most 3 bots

**Comment by dsmello** [comment]
plz close that  log, have another ( 3623 )

**Comment by 17yongga** [comment]
What is the error message?

**Comment by crepito** [comment]
Same here. Only 1 bot running.
