### ISSUE TITLE
WebSocket ports for multiple copies

### ISSUE THREAD

**Issue by roytam1** [NECROBOTIO/NecroBot#3628]
I can connect to websocket of 1st started copy only.

Copy 1:
```
  "UseWebsocket": true,
  "WebSocketPort": 55301,
```
Copy 2:
```
  "UseWebsocket": true,
  "WebSocketPort": 55302,
```

When I start Copy 2 first, I can only able to connect localhost:55302, but not localhost:55301
If I start Copy 1 first, vice versa.

Tested with NecrobotVisualizer 1.0.8

**Comment by LordDeimos** [comment]
Necrobot reserve 2 port so for the second bot use 55303

**Comment by roytam1** [comment]
OK it works now :)
