### ISSUE TITLE
Suggestion - Do not release more code before some critical problems are resolved

### ISSUE THREAD

**Issue by vfuyong** [NECROBOTIO/NecroBot#3630]
There are at least one critical problems I can name:
- Unable to log in after 0.7.7

I am still on 0.7.6 because of this.

**Comment by jinkawasaki333** [comment]
Agree! Too many releases in a very short time, and everything is super messy.

**Comment by kurozani** [comment]
try 8.0 it works

**Comment by dsmello** [comment]
what's a critical for you ?

**Comment by jaypeeb0917** [comment]
Wait... 8.1 coming up in a sec. lol

**Comment by sing1222** [comment]
I don't think so.
You can choose update or not.
Auto update, auto transfer config to new version, what make you difficult?

**Comment by DBa2016** [comment]
@vfuyong : the "unable to login" is because of changed proxy handling. System proxy is not used anymore, needs to be explicitly set in auth.json.

**Comment by nfettinger** [comment]
This is not helpful to developers.
