### ISSUE TITLE
Is there a way to find out what each line means ?

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#3632]
Most are either explained or easy to figure out, but some i just have no idea what they mean.
like
"DumpPokemonStats": false,
or 
"AmountOfTimesToUpgradeLoop": 5,

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Config

**Comment by DariusFoxy** [comment]
I could have sworn i looked there.. most seem on the list, but not all. it just that the list has to catch up to the new edits ?

**Comment by Oolaruu** [comment]
Then I suggest to wait that Wiki get an update.

**Comment by jaypeeb0917** [comment]
That is an issue that nobody cares. Config and Wiki is dead! I have requested for it to be updated and nobody cares. RIP.

You will have to experiment on this man!

**Comment by nfettinger** [comment]
Read the Wiki, or enter a specific issue for an item that is missing / outdated.
