### ISSUE TITLE
Snipe .... repeatttt ... no pokemon to snipe !!!

### ISSUE THREAD

**Issue by missyyou94** [NECROBOTIO/NecroBot#3634]
![1211](https://cloud.githubusercontent.com/assets/20890127/17506940/f0e2f47e-5e36-11e6-97fd-8ec1bc57665a.png)

**Comment by sirvts** [comment]
https://gyazo.com/bf2180c6136dace9a0e571efb7131215

annoying...

**Comment by xThreeh** [comment]
no pokemon to snipe too :(

**Comment by sazzanm** [comment]
same here :(

**Comment by a498716886** [comment]
i think its the problem with the new pogobot feeder.. most of them are fake

**Comment by sirvts** [comment]
@a498716886  rly??

**Comment by Ryzison** [comment]
with "GetSniperInfoFromPokezz" and "GetSniperInfoFromPokeSnipers" both set to false in config, I haven't seen many fails, tho I do have a rather specific snipe list.

**Comment by sirvts** [comment]
@Ryzison still failing a lot..

**Comment by Zerotask** [comment]
Even with that change I get a bunch of Did not find a Pokemon within the SnipingScanOffset (which is default 0.005)

**Comment by Ryzison** [comment]
yeah same, seems right after I said something i started seeing them again, going to have to live with the people reporting fakes, they each only takes a second or two out of the equation. My only advice would be shorten your  "PokemonToSnipe" to specifically what you want.

**Comment by mjusuf** [comment]
use this: https://github.com/5andr0/PogoLocationFeeder 
and setting like this
**NECROBOTIO**
```
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 5,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 2000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
```
**PogoLocationFeeder**
```
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UsePokeSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 3,
  "ShowLimit": 30
```

**Comment by STCOZT** [comment]
Same for me..
@mjusuf It doesn't work still having lots of fails but thx anyway.

**Comment by sirvts** [comment]
@STCOZT true, still having tons of fails :\

**Comment by Lordseis03** [comment]
Doesnt work but thanks for helping out @mjusuf

**Comment by mjusuf** [comment]
with version v0.7.7?
yeah, not always success snipe, but sometimes working

like this
![snipe](https://cloud.githubusercontent.com/assets/12285684/17508715/8721ee64-5e40-11e6-8fde-c423e8b21a9e.png)

**Comment by a498716886** [comment]
@sirvts  yes i saw plenty mew and mewtwos being posted on the feeder.. i would prefer the would one with cmd style .. cuz i can actually get something out of it
