### ISSUE TITLE
Device problem

### ISSUE THREAD

**Issue by Nuggeten** [NECROBOTIO/NecroBot#3635]
Hello, I have put all the informations since my Samsung Galaxy S6 with Aida64 but I have a problem when I put this one   "DevicePackageName": "galaxy-s6"

https://gyazo.com/53407ee2f18df280878ba340b7cbbe2d

Thanks for help.

**Comment by daika7ana** [comment]
The name is not supposed to go there. 
Set `"DevicePackageName": "custom"`

**Comment by Nuggeten** [comment]
ok, thanks you.
