### ISSUE TITLE
getElevation method output non realistic random number

### ISSUE THREAD

**Issue by LoktOoO** [NECROBOTIO/NecroBot#3638]
Hello,

Just add a look to the LocationUtils.
Randomize done on Elevation is almost worst than having it fixed to 10. Let me explain why :+1: 
1 degree = 111.325 km
The current function don't take into account the previous value nor a realistic gap between change.

**Comment by Meeplez** [comment]
damn, we should pull chords from google or something...

**Comment by nfettinger** [comment]
The Niantic API Does not support an elevation parameter right now. If they do, this will be handled in the RocketAPI.

**Comment by LoktOoO** [comment]
Sorry but you are wrong, Signature use Altitude : 
generateLocation1(authticket, lat, lng, alt): 
    firstHash = xxhash.xxh32(authticket, seed=0x1B845238).intdigest()
    locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
    if not alt:
        alt = "\x00\x00\x00\x00\x00\x00\x00\x00"
    return xxhash.xxh32(locationBytes, seed=firstHash).intdigest()


RocketApi use it also in the request builder : 

 var locationBytes = BitConverter.GetBytes(_latitude).Reverse()
                .Concat(BitConverter.GetBytes(_longitude).Reverse())
                .Concat(BitConverter.GetBytes(_altitude).Reverse()).ToArray();
            sig.LocationHash1 = BitConverter.ToUInt32(x.ComputeHash(locationBytes), 0);

Otherwise, if it's not used I don't understand why someone would add a method like GetElevation..
