### ISSUE TITLE
Sniping legendary.. is it possible?

### ISSUE THREAD

**Issue by Blaucide** [NECROBOTIO/NecroBot#3639]
NecroBot tries to Snipe Mew, MewTwo and others since the last PoGo Update
someone got the same?

**Comment by spamfighter82** [comment]
some ppl like to feed the feeder with bullshit

**Comment by WoShiSaBi** [comment]
nope mew mewtwo and others are fakes and legendarys are only for events from my research

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by Blaucide** [comment]
So how can NecroBot see them?
