### ISSUE TITLE
Still No Pokestops avaiable in my area.

### ISSUE THREAD

**Issue by Blaucide** [NECROBOTIO/NecroBot#3641]
Is this a PoGo Servers problem or is about the new 0.8 Version?

**Comment by Enragedmaster** [comment]
Used 7.8 , Used 8.0 , Same problem.

**Comment by can99** [comment]
it's ip softban, did you run multiple bot?

**Comment by Blaucide** [comment]
Yeah i'm using multiple bots since 0.7.6 and never got this ip softban, can i use vpn to avoid ?
