### ISSUE TITLE
Pokemonnottotransfer bug.2.0

### ISSUE THREAD

**Issue by Massnl** [NECROBOTIO/NecroBot#3643]
Yesterday i posted this. 
"For the 4th time today, my chansey got transfered, while chansey is in the nottotransferlist, and after the 1st transfer i started favouriting every chansey i saw, but they still get transferred.
my settings
"KeepMinCp": 1550,
"KeepMinIvPercentage": 80.0,
"KeepMinLvl": 20,
"KeepMinOperator": "or",
"UseKeepMinLvl": false,
"PrioritizeIvOverCp": true,
My chansey's met atleast 1 criterium (iv84/cp450 and 2nd iv94/cp25) they were both favourited, chansey is in the nottotransferlist but still got transfered.

i also experienced this with a bulbasaur iv 91 who still got transfered"

i made a filter for it it worked for a while, but my storage kept getting full, so i turned "transferweakpokemon" to "true" and it got instantly removed again. So the "transferweakpokemon" overrules the "nottotransferfilter".

**Comment by PokemasterMike** [comment]
please ask in discord and provide a full dump of your config (on pastebin.com)

**Comment by Massnl** [comment]
which channel in discord?

**Comment by Massnl** [comment]
i found out, when i updated the file it didnt copy the filter, so my custom chansey was gone again. So thats probably why chansey got deleted. (yes i defenitly made the filter and saved it.).

but then something is wrong when you update the program, i will test now if it keeps working with "transferweakpokemon = true"

**Comment by Massnl** [comment]
updated to 0.8.0 and my filter got removed again. so the filter probably works fine, it just gets removed after each update.

please close this issue, i will create a new one with correct problem
