### ISSUE TITLE
[Bug]  Periodic NullReferenceException v0.7.8, happening since v0.4

### ISSUE THREAD

**Issue by Sasstraliss** [NECROBOTIO/NecroBot#3644]
![error_0 7 7](https://cloud.githubusercontent.com/assets/5234450/17507377/787d9382-5e4e-11e6-99cc-27eb19f0bf93.png)

(Filename is wrong)

Been getting this error since version 0.4, sporadically every hour or two on some of my bot instances.

**Comment by nfettinger** [comment]
Duplicate
