### ISSUE TITLE
Incubator not accumulating distance

### ISSUE THREAD

**Issue by arjunxyz** [NECROBOTIO/NecroBot#3648]
Since the v0.8.0 version of the bot came out, my bot has walked a considerable distance (+5 kms), but the egg incubators still show the same distance remaining, and no eggs have hatched. Any ideas about what's causing the error?

**Comment by nfettinger** [comment]
Could be a softban issue.

**Comment by pogoBotter** [comment]
@nfettinger No it's not a softban issue. Could you please not assume and close issue? I am also having the same problem however low I put the walkingspeed.
PS: Please re-open the issue.
