### ISSUE TITLE
distance is too small?

### ISSUE THREAD

**Issue by polypalm** [NECROBOTIO/NecroBot#3650]
how can i fix this ? any idea why is that even happening?
[http://oi63.tinypic.com/ei08bp.jpg](url)

**Comment by StarvingDeveloper** [comment]
Looks like ban.

**Comment by zzxxzzxxSG** [comment]
Looks like API got issue again, or soft banned.

**Comment by polypalm** [comment]
any fix?

**Comment by marburger93** [comment]
no pokestops found, api was changed again.

**Comment by polypalm** [comment]
it fixxed by its own?
