### ISSUE TITLE
[REQUEST] Evolve after Transfer

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3651]
Why to evolve before having MORE candies?

![immagine](https://cloud.githubusercontent.com/assets/20842205/17508347/ce0892c8-5e14-11e6-82f0-c0a8b11986ac.png)

**Comment by Firefly1029** [comment]
does it for exp, change your config

**Comment by Profetorum** [comment]
mh? Are there settings in order to change this?

**Comment by actislav** [comment]
evolve task can account result of future transferring, as u can see jigglypuff candies = 34

**Comment by Profetorum** [comment]
Aw, great! Ty for answers
