### ISSUE TITLE
[Feature] Possibility to skip a pokestop

### ISSUE THREAD

**Issue by Tintin95** [NECROBOTIO/NecroBot#3652]
Sometimes I only wish search some specific pokemon but not get experience nor items from a pokestop. Is it possible to add a feature to avoid pokestop?

**Comment by nfettinger** [comment]
No, and I dont see why this would be desired.

**Comment by Tintin95** [comment]
ok, (1) thanks for implement the tool. (2)I think it's interesting to don't get experience of a pokestop but try to search only a few pokemons (with the pokemonsToIgnore). (3) And something more important: I was polite writting but your response are a bit disgusting. Could be u are blind and unable to see other's problem but I don't care anything about your shit :)
best ^^
