### ISSUE TITLE
[Logic/syntax] need a moveslist algorithm explanation and syntax

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#3656]
"Moves": [],

while the option is neat, the trouble is figuring out  how to input it in the array.

Water Gun
WaterGun
watergun
"Water Gun"
"WaterGun"
Water Gun Fast
Watergunfast
"watergunfast"

etc

furthermore, is there a way to keep multipl emovesets?
[watergun, hydropump/aquatail]
?

**Comment by nfettinger** [comment]
Duplicate issue.
