### ISSUE TITLE
no login 

### ISSUE THREAD

**Issue by nemwar** [NECROBOTIO/NecroBot#3657]
Hi,

since update from 0.7.6 no login via ptc and google possible.
What can I do?
Is there a known problem?

Thanks

**Comment by qwertzuiopii** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3617

**Comment by nemwar** [comment]
Sorry, but i have no proxy set at all....
what else can i do?

**Comment by Joloxx9** [comment]
It is not working for me also. Downloaded older version (7.5) and everything works great, but can't update due that bug.
