### ISSUE TITLE
Proxy with SSH Tunneling

### ISSUE THREAD

**Issue by CyberBaby** [NECROBOTIO/NecroBot#3661]
Does anyone try with the proxy with SSH Tunneling?

The bot stucked at Logging in Using Google.

[15:20:33] (INFO) Logging in using Google

Settings in auth.json
"UseProxy": true,
"UseProxyHost": "127.0.0.1",
"UseProxyPort": "1080",
"UseProxyAuthentication": false,
"UseProxyUsername": null,
"UseProxyPassword": null,

Btw, how do we confirm the network connection are going thru the Proxy?

Many thanks for your great work~

**Comment by nfettinger** [comment]
Please use discord chat to discuss

**Comment by genox87** [comment]
Same question, asked on #support channel but no one knows....

Anyway if i set up a ssh tunnel with putty and use with for example chrome i've 0 problems.

Necro show up this:

(INFO) Your IP: 80.xxx.xxx.xxx / Proxy IP is : INVALID PROXY

Can a dev check if con be fixed ?

Thanks

**Comment by CyberBaby** [comment]
I realized that the bot is currently support http proxy only. That's why SSH tunnel doesn't work. Hopefully socks proxy will be supported in future.
