### ISSUE TITLE
[PROPOSAL] The Bot can bypass the softban

### ISSUE THREAD

**Issue by Basetonic** [NECROBOTIO/NecroBot#3662]
Hello,

After seeing this video and trying it myself, it works !

https://www.youtube.com/watch?v=b28dLnGmJXo

Could it be possible to make the Bot do exactly the same thing so we could bypass the softban whenever ?

Thank you

**Comment by Seyrenvox** [comment]
i don't watch the video, but i know NecroBot can unban the softban

**Comment by ferbeb** [comment]
Have you even used the bot once?
It tries to unban by spinning 45 times all the time.

**Comment by Profetorum** [comment]
Already implemented O.o

**Comment by burntable** [comment]
this guy :D

**Comment by Basetonic** [comment]
Haha my bad :D Please delete
