### ISSUE TITLE
[Feature Request] Multiple config files

### ISSUE THREAD

**Issue by Zerotask** [NECROBOTIO/NecroBot#3666]
At the moment I use 2 different config files and have to copy & paste to switch them. It would be nice if you can define multiple configs and then set one active.

**Comment by Firefly1029** [comment]
I personally have yet to run into this but would be nice if on startup you could select "[1] config1 [2] config2"

**Comment by StarvingDeveloper** [comment]
More simple copy whole bot folder and edit config in them. Then create 2 shortcuts on desktop config1 and config2.

**Comment by vipery** [comment]
Will be nice add GrindUntil

MyLvl < 25, 1 config pure grinding
MyLvl > 25, 2 config grinding + sniping

**Comment by so2cute** [comment]
good 
-Functions are divided Fire; ex. ItemRecycleFilter , PokemonsToEvolve You can distinguish Monterrey after updating .

**Comment by delta50** [comment]
The program takes a CLI argument to specify a directory with the config folder. For example:

NecroBot.exe C:/PathToFolderWithAConfigFolder

**Comment by LudMiller** [comment]
Will it only use the config.json or the auth.json as well when i use the CLI argument? (i am currently not a at home, where my bot laptop is)

Because it would be nice to have one central config.json for multiple bots.

**Comment by delta50** [comment]
It uses everything the config folder. It might be nice to have some flags to specify the configuration files individually.

**Comment by nfettinger** [comment]
Adding even more complexity on top of the overloaded config is not desirable when the OS supports everything you are requesting easily.
