### ISSUE TITLE
solution to the fake coords sniper spam

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#3667]
we can send all coords into a temp array and then go thru them one at a time. then the ones that are deemed fake are removed from array. then carry on.
or kept in another array called fakecoords and bot can do a match check each time (might be slower logic but just an idea).

basically creating a local filter after doing a first check thru.
or a global check with all necro bots somehow (like haxton's burst)

**Comment by Firefly1029** [comment]
you mean a person checks them or the bot goes to it before adding it to the list?
