### ISSUE TITLE
Snipe Real Problem

### ISSUE THREAD

**Issue by Otar666** [NECROBOTIO/NecroBot#3669]
Right now i see 2 problems with the Snipe feature:

1- When it is scanning the other area, its not scanning your own area, so you lose all those pokemon around you to try for something extraordinary, but that isn`t always there. Can we have both?
2- It scans the same pokemon on the same order, so if you didnt find something first try is nice to try again, sometimes it find that pokemon, but most of the time you just lose the chance to scan for the others on the list, for me it keeps repeating the same 5~8 guys. Can we have options to cycle them better or prioritize if they have high IV por example?

Since this is my first post, i have to also thanks you all for this incredible Pokemon tool!

**Comment by Firefly1029** [comment]
Iv is unknown so they can't order by IV, most they could do it program it to order by which pokemon they THINK are better, or more rare

**Comment by slxdegrees** [comment]
Adjust your snipe filter to be more specific unless you wanna do it manually.

**Comment by Otar666** [comment]
@Firefly1029 you are wrong, at location feeder you can sometimes see IV's since they are user reported and have been captured, so they know some IV's for sure!
@slxdegrees This is no forum to give opinions, talk about the issues, or let a dev answer.
