### ISSUE TITLE
Sniping with server disabled will still attepmpt to snipe

### ISSUE THREAD

**Issue by Gandaflux** [NECROBOTIO/NecroBot#3670]
Unfortunatelly #3326 isn't fixed in latest version, commit 1a27226 from @dddbliss didnt help. 
Still there is same bug:

proof:
http://clip2net.com/s/3B1o8JX

my config:
http://pastebin.com/48qRknyi

**Comment by Gandaflux** [comment]
Checked what can be wrong i i discover that bot even with disabled sniping servers trying to connect with skiplagged.com

**Comment by nfettinger** [comment]
Not seeing the issue in the latest version.

**Comment by Gandaflux** [comment]
@nfettinger  Im seeing it in proxy logs. Since im using own (tinyproxy) linux proxy i see in logs that bot is getting data from skiplagged.com even with disabled SnipServer options. It runs without problem, but only sometimes it return error. Probably if bot doesnt get response from skiplagged.
