### ISSUE TITLE
Keypress for status/information

### ISSUE THREAD

**Issue by thecantero** [NECROBOTIO/NecroBot#3671]
Can we have a feature to provide status/information on some keyboard press?

Like `i` for account information/level, `p` for list of pokemons. Any keys that fits will do.

**Comment by ToHindahl** [comment]
This is a great idea!

**Comment by LudMiller** [comment]
i really want this feature too

**Comment by ntoenis** [comment]
Agreed

**Comment by Magnaleikha91** [comment]
agreed agreed agreed, 85% IV pokemon viewer! :P

**Comment by nfettinger** [comment]
Duplicate issue.
