### ISSUE TITLE
Is niantic change the API key again??

### ISSUE THREAD

**Issue by maliqoye** [NECROBOTIO/NecroBot#3672]
got this error No usable PokeStops found in your area. Is your maximum distance too small? tried many times

**Comment by blackuGT** [comment]
Nope, it's only broken bot issue...

**Comment by Firefly1029** [comment]
stop the bot wait or use a different account for a bit. Happens a lot.

**Comment by maliqoye** [comment]
10 minutes ago bot work fine.,

**Comment by blackuGT** [comment]
And?

**Comment by Firefly1029** [comment]
close it wait, or try other things. Happens a lot and to a lot of people

**Comment by maliqoye** [comment]
@blackuGT and now got that error No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by blackuGT** [comment]
@maliqoye Close bot and wait for update...

**Comment by slxdegrees** [comment]
Change the area. Sometimes there are just too many units in that particular area.
