### ISSUE TITLE
gpx resets every 30 minutes

### ISSUE THREAD

**Issue by illidan1337** [NECROBOTIO/NecroBot#3673]
i havent updated yet but this problem has been around since i first started using the bot a week and a half ago
so after 30 minutes the bot prints "Niantic Servers unstable, throttling API Calls." 
then it reconnects and sends me to the beginning of my gbx track
30 minutes after that i get the same thing

**Comment by illidan1337** [comment]
just got home and updated and ran the bot for 30 minutes again and sure enough the problem still exists

**Comment by nfettinger** [comment]
Duplicate issue.
