### ISSUE TITLE
Getting softban everytime change coordinates

### ISSUE THREAD

**Issue by sanzox5** [NECROBOTIO/NecroBot#3675]
HI there, i need help on topic above. i couldnt catch any. keep on getting softban after change the coordinates. Except when i do a fresh necrobot setup. any advice?

**Comment by blackuGT** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3623

**Comment by slxdegrees** [comment]
Are you changing the coordinates by a lot?

**Comment by situ1994** [comment]
Change "DisableHumanWalking": false, instead of true.

**Comment by bastacs** [comment]
Not Working

**Comment by tetsunoony** [comment]
do not run >= 3 pokemons include bot .. devices PER IP... will get SOFTBAN !!!!

**Comment by sanzox5** [comment]
found the solution:
"DisableHumanWalking": false
"WalkingSpeedInKilometerPerHour": 10.0

Working great for me. cheers
