### ISSUE TITLE
transferring

### ISSUE THREAD

**Issue by NZAguilar** [NECROBOTIO/NecroBot#3677]
All pokemon are being transferred - regardless of CP

**Comment by Firefly1029** [comment]
"prioritizeicovercp" might be your problem.

**Comment by situ1994** [comment]
keepdupicates in the config must be 0 change it to 1 or the number of duplicates you want.

**Comment by liweichen6** [comment]
Also "transfer weak pokemons" may cause this issue.

**Comment by g1218244** [comment]
me too...

**Comment by nfettinger** [comment]
Duplicate #3338
