### ISSUE TITLE
Not transferring anything. 

### ISSUE THREAD

**Issue by Firefly1029** [NECROBOTIO/NecroBot#3678]
My poke inventory keeps filling up because it keep 43 cp snorlax and 50 dragonite's. How can I make it get rid of EVERYTHING below like 700 cp, even with %100 iv

**Comment by actislav** [comment]
KeepMinIvPercentage = 101 UseKeepMinLvl = false PrioritizeIvOverCp = false KeepMinCp = 700 KeepMinOperator = "or"

**Comment by B3H1NDu** [comment]
Delete the Pokemon from the "PokemonsNotToTransfer" list in your config file.

**Comment by nfettinger** [comment]
Configuration issue.
