### ISSUE TITLE
How to deal with IP ban

### ISSUE THREAD

**Issue by MengranZhu** [NECROBOTIO/NecroBot#3679]
I just download the latest version and find that my IP was banned by N.

**Comment by blackuGT** [comment]
How you find this ban info?

**Comment by qwe900** [comment]
get a new ip, dont bot with more then 3 bots on same ip

**Comment by MengranZhu** [comment]
how to change the ip? actually I just use only one bot on my account

**Comment by Nilrem711** [comment]
Restart Router/ Use VPN

**Comment by tetsunoony** [comment]
do not pokemon >=3 accounts per IP ... IP will get BAN

**Comment by Nilrem711** [comment]
How is this in Public WiFis xD

**Comment by bastacs** [comment]
i play with 5 accounts, is safe :) , ~

**Comment by tetsunoony** [comment]
mail NIANTIC .. AND TELL THEM .. YOU BAN ME IN PUBLIC IP.

**Comment by MengranZhu** [comment]
I use the remote cloud service AWS EC2. Actually because I cannot install the KB29*** update with my win 8.1 system. However I can catch pokemon on my phone

**Comment by LudMiller** [comment]
where did you get the "not more then 3 bots" information from??

**Comment by Firetribe** [comment]
AFAIK AWS uses a specific IP Adress range for their public IPs, seems like Niantic banned all of them, as no phone would ever use an IP reserved for AWS EC2 instances. No luck for Necrobot running on EC2 without added tweaks ;)

**Comment by WuddyMarco** [comment]
I think what tetsunoony said is only what he is noticing running the bots. For me running 3 Bots at a time also results in temporary IP Ban which ist removed after approximately 5 mins. At the moment i test out how many i can really run simultan. Starting with 1 Bot and adding other after the bot runs for half an hour. 
At the moment i think its maximum 2 bots related to the last ban i recieved with 3 bots. This problem by the way seems to be new because about 12 hours ago running 3 bots was no problem and 36 hours ago running 20 was also no problem.

**Comment by burntable** [comment]
yeah that's true. running 2 bots at the same time (on different locations) works fine... even after getting softbanned/ip banned.

3 bots at the same time, results in an temporary ip ban.

yesterday I was running 3 bots at the same time without any problems.

**Comment by GwnBott** [comment]
i was running 2 bots, and stil got IP banned, (1 necro, 1 haxton) but the haxton is on crack (200-300kxp/h)
decided to leave haxton down and open a second necro for when i go to bed :p

**Comment by burntable** [comment]
now my 2nd bot got (ip?)banned, too. if I log in with nox, I can see why the bot can't find any pokestops...
because there are no pokestops...
the 1st bot is still running like a boss in central park nyc

**Comment by WuddyMarco** [comment]
That sounds not good. For me second bot runs about 15 minutes without no problem. Locations are NYC and Düsseldorf in Germany. I will try to add a third bot located in tokyo in a few minutes and hope that it will work.
Maybe it has to do with locations. Which ones you are using ?

**Comment by burntable** [comment]
Munich, Germany and NYC...
I stick to one bot at a time, for now.

**Comment by spamfighter82** [comment]
well 2 bots but also 4 PokemonGo-Map workers and no ban issues.

**Comment by WuddyMarco** [comment]
Ok 3 Necrobots are not able at the same time. After adding the third one i get banned after about 4 minutes.

**Comment by batgun** [comment]
I am using google cloud as vps. But now it seems they ip-banned all ops services. Anyone has a solution for this?
