### ISSUE TITLE
Sniping with pogo location feeder doesnt get me anything at all

### ISSUE THREAD

**Issue by a498716886** [NECROBOTIO/NecroBot#3681]
any other suggestions? it always scans and doesnt find anything

**Comment by vinhlv** [comment]
same me

**Comment by Blaucide** [comment]
same here

**Comment by lordslair** [comment]
See https://github.com/NECROBOTIO/NecroBot/issues/3386

Two options, try to change your SnipingScanOffset or try different feeders as you may receive old/not valid coords

(I tried, and still can snipe right now)

**Comment by a498716886** [comment]
@lordslair any other recommends for feeders?

**Comment by lordslair** [comment]
I currently use only sources from discord channels into PogoLocationFeeder
Most of the time, I can catch without error, or at the second try

**Comment by a498716886** [comment]
@lordslair  how do i set up discord channels into pogolocation feeder?

**Comment by a498716886** [comment]
@lordslair  and what kind of channels?

**Comment by lordslair** [comment]
@a498716886 You can go there for more infos https://github.com/5andr0/PogoLocationFeeder/wiki/Configuration-and-Usage

I mean, it's not a NecroBot problem related here

**Comment by a498716886** [comment]
@lordslair i have few questions about using sources only from the discord channels..  do i have to change anything from the configs? and which channel do i  need to join

**Comment by lordslair** [comment]
@a498716886 

You already should have a lot of channels in the Config\discord_channels.json
If you want to feed just from the discord channels, don't touch this file.
If you want **less** sources, delete some lines according to what you want/prefer

To feed only from channels open the config file Config\config.json

and try this

`{
  "Port": 16969,
  "UsePokeSnipers": false,
  "UsePokezz": false,
  "UsePokeSpawns": false,
  "UsePokewatchers": false,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 30
}`

Should work

**Comment by nfettinger** [comment]
Configuration issue.
