### ISSUE TITLE
google login

### ISSUE THREAD

**Issue by freewilly2u** [NECROBOTIO/NecroBot#3682]
stuck at here need help

![untitled](https://cloud.githubusercontent.com/assets/20922294/17509409/59b2b8a8-5e4c-11e6-97b4-87cc636d900d.png)

**Comment by WuddyMarco** [comment]
Open it again or try to press Enter does the Job for me. Sometimes the bots (sniperbot also) stops if you click to much in the window.

**Comment by Firefly1029** [comment]
if it's the first time launching just close and open.

**Comment by freewilly2u** [comment]
i have tried many time close and open also same.
even press enter also same

**Comment by Firetribe** [comment]
Should be this: #3684

**Comment by freewilly2u** [comment]
same problem using v0.7.6 without update

**Comment by edoth76** [comment]
same with me before, but since I change my internet connection it works fine, perhaps blocked by firewall or something ...
