### ISSUE TITLE
Auto Update isn auto, requests user input...

### ISSUE THREAD

**Issue by qwe900** [NECROBOTIO/NecroBot#3683]
please remove user input for autoupdate.... 
then make it more
CheckForUpdatesOnStart
1 true
0 false
3 automatic update

**Comment by jck357** [comment]
I think this is a good thing though.

**Comment by Dyndrilliac** [comment]
Maybe a command line switch would be best for this? For example:

.\Necrobot.exe -NoPromptAutoUpdate

Might remove the prompt and assume yes (triggering the auto update). Could make it more granular by adding an additional parameter allowing you to remove the prompt but prevent the application from automatically updating:

.\Necrobot.exe -NoPromptAutoUpdate [Y|y|N|n]

Where the default value for the parameter is Y.

**Comment by nfettinger** [comment]
Checking your config after every update is recommended to prevent accidental loss of Pokemon and items
