### ISSUE TITLE
Can't login if you choose not to Update to latest version.

### ISSUE THREAD

**Issue by thecantero** [NECROBOTIO/NecroBot#3684]
It says I need to setup my GoogleUser and GooglePassword and exits if I choose not to Update to latest version.

situation: version `0.8.0` is buggy and I'd like to use the previous version, I can't login if I choose not to update.

**Comment by Firefly1029** [comment]
go to config and turn auto update off.

**Comment by kurozani** [comment]
but if we didn't update, we can't login

**Comment by thecantero** [comment]
@Firefly1029 thanks, but that still doesn't fix the initial problem. When "choosing not to update"

**Comment by Firetribe** [comment]
The problem is with system proxy, since 0.7.6 the bot isn't using it anymore. You bot from work, I assume?

**Comment by edoth76** [comment]
please check your internet connection, firewall or internet connection setting. Me too before I change my internet connection to other internet provider, now works fine.
