### ISSUE TITLE
I'm getting softbanned every minute

### ISSUE THREAD

**Issue by DaddyCandy** [NECROBOTIO/NecroBot#3686]
I changed after 5 minutes the delay between actions to 5000 like in the previous version was, and i'm getting banned after a minute and a half lol 
What do I have to do? 
![image](https://cloud.githubusercontent.com/assets/20923053/17509516/9e0b9b46-5e1a-11e6-90ab-3bb7fde7f7bf.png)
(PS: Sorry for the lang in the img, i'm italian, but "softban" is worldwide, so you'll understand it anyway lol)

**Comment by GwnBott** [comment]
u aren't teleporting, sniping and getting soft-banned?

**Comment by Gingiangiallo** [comment]
only with 0.7.7+ versions, i'm in 0.7.7 and is running smooth, no softabns

**Comment by mimilo** [comment]
How you get 0.7.7 ? because when i started i want update necro software all time

**Comment by DaddyCandy** [comment]
I'm not doing anything different from 0.7.7 version, I've put always the same coo, not teleporting, nor sniping... Just did the "tutorial" to login and set the location.. Now it seems it's working, but I don't understand why changing the delay from 5'000 and 2'500 to 500 and 100, that's why I was being softbanned so often maybe..

**Comment by DaddyCandy** [comment]
mimilo you can get it here: https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.7.7

**Comment by mimilo** [comment]
Thank daddycandy , but i would update after the first running or not ?

**Comment by DaddyCandy** [comment]
You should not update or it will download the 8.0 :)

**Comment by MRokas** [comment]
It's due to too high speed and bot not confirming its not driving.

**Comment by mimilo** [comment]
OKey thank you so much have a nice day :)

**Comment by sanzox5** [comment]
change to 10km walking speed and change humanwalking to TRUE. working fine for me

**Comment by Rishabhpatted24** [comment]
Same problem here...!how do we fix? im runing on 19 speed...

**Comment by DaddyCandy** [comment]
Maybe it can be a misunderstanding of NecroBot himself, because sometimes it says that i'm softbanned 1/45 tries to unban, then it says that my inventory is full.. Maybe is it misunderstandings those 2 things?

**Comment by DaddyCandy** [comment]
MRokas how can we resolve it so?

**Comment by sanzox5** [comment]
found the solution:
"DisableHumanWalking": false
"WalkingSpeedInKilometerPerHour": 10.0

Working great for me. cheers

**Comment by bastacs** [comment]
u mean disable human walking change to " false" not true

**Comment by DaddyCandy** [comment]
sanzox5 i'll try, it seems so slow compared to other versions, but  at least it works :)

**Comment by Kraker01** [comment]
DisableHumanWalking is misleading... 

It should be changed to "HumanWalking" - True/False, otherwise it's complicated to understand. 

Is there any Wiki for that command?

**Comment by DaddyCandy** [comment]
I'm not getting softbanned with DisableHumanWalking False and 31.0 km/h

**Comment by emwedk** [comment]
doesn't seem like any of the fixes provided here is working for 0.8.0
is it confirmed that it works for 0.7.7? and are you using proxy as well?

**Comment by Magnaleikha91** [comment]
I think in the previous version, the DisableHumanWalking was set to False by default. Now it was set to True, and we need to change it to False to make things right (reasonable travel)

**Comment by tetsunoony** [comment]
softban....  mean... >3  poke devices include bot/device/map...in same ip

then... google soft ban ban gun appear!

**Comment by tetsunoony** [comment]
image
there are >3 humans are using pokemon devices in same WIFI... then...
everyone will get SOFTBAN!
