### ISSUE TITLE
can i use necrobot in other country ? without being constantly softbanned ?

### ISSUE THREAD

**Issue by skullkrasher99** [NECROBOTIO/NecroBot#3693]
can i ?

**Comment by phoojunior** [comment]
![fuckkk](https://cloud.githubusercontent.com/assets/20917363/17510059/be422cce-5e4f-11e6-9b77-5bd34b349b7e.jpg)

**Comment by DariusFoxy** [comment]
i'd love to know how long you have to wait to safely switch locations. Last night i was in San Diego, when i woke up i switched to NYC with no problem. But earlier, i took a 10 minute break and went to Japan and got soft banned for 45 seconds.  I'm sure there's something safe in between. any ideas ?

**Comment by Seyrenvox** [comment]
i switch location everytime i want without having to wait for 10 minutes, since the bot will auto unban me.
the case will be different if you run multiple bots.

**Comment by nfettinger** [comment]
Your IP is georeferenced and does not match your GPS cords.
