### ISSUE TITLE
Spam snipee, always repeat automatically after snipe one previous location

### ISSUE THREAD

**Issue by cikenpukpuk** [NECROBOTIO/NecroBot#3694]
what is this, when i already snipe one location, and then thats automatically repeat the previous location... please help me ... 
this my capture
![spam snipe](https://cloud.githubusercontent.com/assets/20737801/17509968/debc34da-5e46-11e6-9b75-509a10bae1cf.JPG)

**Comment by cikenpukpuk** [comment]
im using pogo location feeder #

**Comment by iPollox** [comment]
What are you talking about? They are all different

**Comment by cikenpukpuk** [comment]
nah wait i will capture before

**Comment by Leo231** [comment]
I have a problem with Necro, every 1-2 minutes he try to snipe like 30 locations (all fake) and i cant understand from where it takes that locations. I disabled in config both pokezz and pokesnipe, even if i close PogoFeeder he its doing the same.
