### ISSUE TITLE
  "KeepMinDuplicatePokemon" does not seem to work for me.

### ISSUE THREAD

**Issue by Gorrok101** [NECROBOTIO/NecroBot#3697]
Hi all

I have played the game manually for some time and after the radar removal i thought to look for other means like your amazing tool.

I have alot of Pokemon space and would like to keep at least 6 of each (dont ask why) so i found the setting   "KeepMinDuplicatePokemon" which sounded perfect.

But for some reason when i set that do 5 it still just kept transferring. 

I thought maybe the CP or IV is too low, so i set that very low. (120 / 20%). and still i was seeing transfers. Only way i could stop it was "TransferDuplicatePokemon": false, - I dont mind the odd manual cleanup but now i was overrun with Pidgeys and Rattata. 

So i thought lets put all the pokemon in the   "PokemonsNotToTransfer":  and then have the annoying ones in the    "PokemonsToIgnore":  section.

I now have no more transfers it seems, but i am still for some reason it is picking up the ones on the Ignore list. 

Anyone able to give me some advice please.

**Comment by kurozani** [comment]
I changed the number to 2, and have no problem, got that problem when I set it to 1

**Comment by Gorrok101** [comment]
Just answered my own question - UsePokemonToNotCatchFilter set to true.
So no longer catching trash.

But ideally i would like to bot to keep 6 Pokemon and transfer the rest.
That way i can keep 6 low CP low IV Magicarps for instance.

**Comment by actislav** [comment]
TransferWeakPokemon = false and KeepMinDuplicatePokemon = 6 and u must to choose which to PrioritizeIvOverCp, can keep both by cp and iv in same time

**Comment by Gorrok101** [comment]
Thank you for the quick response will try that out.
