### ISSUE TITLE
Why always Evolving under IV???

### ISSUE THREAD

**Issue by jackindojogja** [NECROBOTIO/NecroBot#3703]
I have problem while bot evolving pokemon, it always evolving under 90IV where i set on config evolve above 90 IV.

![evolve1](https://cloud.githubusercontent.com/assets/20923433/17510217/2ab8cc80-5e48-11e6-9622-62c4eb5f18b0.jpg)

this my config : 

> {
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 250,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 30,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": true,
  "AmountOfTimesToUpgradeLoop": 20,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 0.0,
  "UpgradePokemonIvMinimum": 90.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": -7.7827290787192389,
  "DefaultLongitude": 110.37498235702515,
  "WalkingSpeedInKilometerPerHour": 31.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 0,
  "DelayBetweenPokemonCatch": 0,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 0.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 0.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 2000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 6000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 30,
  "MaxTravelDistanceInMeters": 5000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 0,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 100,
  "TotalAmountOfRevivesToKeep": 50,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 2000,
  "UseMasterBallAboveCp": 2500,
  "UseGreatBallAboveIv": 90.0,
  "UseUltraBallAboveIv": 99.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 99,
  "GreatThrowChance": 98,
  "ExcellentThrowChance": 97,
  "CurveThrowChance": 100,
  "ForceGreatThrowOverIv": 1.0,
  "ForceExcellentThrowOverIv": 2.0,
  "ForceGreatThrowOverCp": 1,
  "ForceExcellentThrowOverCp": 2,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 100.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "bulbasaur",
    "ivysaur",
    "charmander",
    "charmeleon",
    "squirtle",
    "wartortle",
    "caterpie",
    "metapod",
    "weedle",
    "kakuna",
    "pidgey",
    "pidgeotto",
    "rattata",
    "spearow",
    "ekans",
    "pikachu",
    "sandshrew",
    "nidoranFemale",
    "nidorina",
    "nidoranMale",
    "nidorino",
    "clefairy",
    "vulpix",
    "jigglypuff",
    "zubat",
    "oddish",
    "gloom",
    "paras",
    "venonat",
    "diglett",
    "meowth",
    "psyduck",
    "mankey",
    "growlithe",
    "poliwag",
    "poliwhirl",
    "abra",
    "kadabra",
    "machop",
    "machoke",
    "bellsprout",
    "weepinbell",
    "tentacool",
    "geodude",
    "graveler",
    "ponyta",
    "slowpoke",
    "magnemite",
    "doduo",
    "seel",
    "grimer",
    "shellder",
    "gastly",
    "haunter",
    "drowzee",
    "krabby",
    "voltorb",
    "exeggcute",
    "cubone",
    "koffing",
    "rhyhorn",
    "horsea",
    "goldeen",
    "staryu",
    "omanyte",
    "kabuto",
    "dratini",
    "dragonair"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {},
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "charmander",
      "charmeleon",
      "charizard",
      "squirtle",
      "wartortle",
      "blastoise",
      "pidgey",
      "pidgeotto",
      "pidgeot",
      "pikachu",
      "raichu",
      "nidoranFemale",
      "nidorina",
      "nidoqueen",
      "nidoranMale",
      "nidorino",
      "nidoking",
      "clefairy",
      "clefable",
      "vulpix",
      "ninetales",
      "jigglypuff",
      "wigglytuff",
      "oddish",
      "gloom",
      "vileplume",
      "psyduck",
      "golduck",
      "growlithe",
      "arcanine",
      "poliwag",
      "poliwhirl",
      "poliwrath",
      "machop",
      "machoke",
      "machamp",
      "bellsprout",
      "weepinbell",
      "victreebel",
      "tentacool",
      "tentacruel",
      "geodude",
      "graveler",
      "golem",
      "ponyta",
      "rapidash",
      "slowpoke",
      "slowbro",
      "seel",
      "dewgong",
      "grimer",
      "muk",
      "shellder",
      "cloyster",
      "gastly",
      "haunter",
      "gengar",
      "drowzee",
      "hypno",
      "exeggcute",
      "exeggutor",
      "koffing",
      "weezing",
      "rhyhorn",
      "rhydon",
      "kangaskhan",
      "goldeen",
      "seaking",
      "staryu",
      "starmie",
      "scyther",
      "electabuzz",
      "magmar",
      "pinsir",
      "magikarp",
      "gyarados",
      "lapras",
      "ditto",
      "eevee",
      "vaporeon",
      "jolteon",
      "flareon",
      "omanyte",
      "omastar",
      "kabuto",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by actislav** [comment]
EvolveAllPokemonWithEnoughCandy = false

**Comment by jackindojogja** [comment]
thanks, it work!
also +with delete list PokemonsToEvolve :D
