### ISSUE TITLE
Can't Start The Bot.

### ISSUE THREAD

**Issue by TheOfficalOne** [NECROBOTIO/NecroBot#3706]
When i Start the bot it spams this message in the command prompt. Help Please?

Unable to load DLL 'Resources/encrypt.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
 
And Says The Area Is Too Small Or Something.

**Comment by lordrudedude** [comment]
I'm having the same issue.

**Comment by nfettinger** [comment]
Antivirus is blocking the bot.
