### ISSUE TITLE
Necro V0.8.0 sniping bug

### ISSUE THREAD

**Issue by Leo231** [NECROBOTIO/NecroBot#3712]
I have a problem with Necro, every 1-2 minutes he try to snipe like 30 locations (all fake) and i cant understand from where it takes that locations. I disabled in config both pokezz and pokesnipe, even if i close PogoFeeder he its doing the same.

  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,

**Comment by minseedsa** [comment]
how to disabled in config im noob Programer , pls help

**Comment by Leo231** [comment]
Change the parameter value from "true" to "false" . But i think there its a bug that dont really disable that functions after you change the value to false.

**Comment by minseedsa** [comment]
ty ;a lot ser , i use bot  for my girlfriend talk "pls go walk for my egg" ty ser

**Comment by Leo231** [comment]
![example](https://cloud.githubusercontent.com/assets/20923635/17511372/3e07128c-5e2b-11e6-9af4-c482d3a22458.jpg)

A screenshot for example.

**Comment by ObsessedHacker** [comment]
same

**Comment by tq01m4m** [comment]
same

**Comment by mooogai** [comment]
same

**Comment by Leo231** [comment]
It seems that V0.7.7 work fine, ill use that till new update

**Comment by xuninho** [comment]
@leo231 great
