### ISSUE TITLE
Just had 10 pokemon in a row CatchFlee

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#3713]
Just transfered to a new location.  Threw berries, used great ball, but even level 15's and less broke and flee'd ?  what's up??

**Comment by alxxzhu** [comment]
Softban Youll be unable to catch any pokemon for 1-2 hours or so

**Comment by DariusFoxy** [comment]
i guess i went too far too fast ?   how long should you wait between countries ?

**Comment by tetsunoony** [comment]
u run too many bots include devices in same ip..
google ban >3 devices current

**Comment by DariusFoxy** [comment]
no i only run 1

**Comment by GummiBoat** [comment]
let it run, it should automatically unban you at the next pokestop.

**Comment by NecroBoTPhile** [comment]
@tetsunoony so whats the solution to that !! can i run multple acc ?

**Comment by DariusFoxy** [comment]
proxies

**Comment by DariusFoxy** [comment]
btw you were right, i set pokemoncatch to false and let it run a few minutes til i found a pokestop, then turned it back on.. we're in business.
