### ISSUE TITLE
Logging in using PTC

### ISSUE THREAD

**Issue by mikegrimmers** [NECROBOTIO/NecroBot#3714]
Hi all,

The bot just sits on the "logging in using ptc" screen and does not progress - any ideas?

**Comment by BlackWaltz89** [comment]
Hi, same here. Since an hour or so. New account tho.

**Comment by imTrainer** [comment]
same here, stuck logging in using google whole day..

**Comment by hyohaluk** [comment]
use v.0.7.6 or down v. it'work for me

**Comment by imTrainer** [comment]
thx hyohaluk, v.0.7.6 is working

**Comment by bitcoin85** [comment]
same problem here. why is 0.8 not working?!

**Comment by BlackWaltz89** [comment]
Thanks, 0.7.6 does not fix the issue for me.

**Comment by BlackWaltz89** [comment]
Solved, security software blocked access for this application to the internets. :) Thanks for helps.

**Comment by mikegrimmers** [comment]
Not the issue for me unfortunately

**Comment by Gandaflux** [comment]
Sometimes it stuck on login when you provide not working proxy server.

**Comment by Sheetka** [comment]
Same here
