### ISSUE TITLE
Sniping BUG

### ISSUE THREAD

**Issue by d3vilsn0w** [NECROBOTIO/NecroBot#3716]
![image](https://cloud.githubusercontent.com/assets/19762306/17511208/8364f8a8-5e3f-11e6-97fa-4f7e9462824d.png)

Have a look. It'd be great if you could help me out.

**Comment by langit7** [comment]
just expire or fake spot

**Comment by d3vilsn0w** [comment]
I'm using PokeLocationFeeder.

**Comment by d3vilsn0w** [comment]
It works fine on the other acc bot thou.

**Comment by langit7** [comment]
You can check the  timer, because    "MinDelayBetweenSnipes": 60000, all bot not snip on the same time, the cords is expire
