### ISSUE TITLE
Best settings for fast level up and pokemon farming

### ISSUE THREAD

**Issue by kingkong91108** [NECROBOTIO/NecroBot#3717]
I would love a setting that allows me to snipe super rare pokemons and not transferring them while also catching pidgeys and level me up fast. Is there such a setting for that, that doesnt include a broken sniping coordinates?

**Comment by theloser** [comment]
This is not a development issue, please go to discord and ask for help.

**Comment by minseedsa** [comment]
i thing cant set best farm, sure Error
