### ISSUE TITLE
Can we please have an option to keep at least 1 of all pokemons?

### ISSUE THREAD

**Issue by MrMime71** [NECROBOTIO/NecroBot#3719]
got a kid asking me why his pokemons dissapear.. he is not after fights or gyms.. He want me to catch them all... 
So a:
"KidModeKeepOneOfEachPokemonToMakeTheKidQuiet": true, would be nice without having to type in all the whole list of pokemontransferfilter..

/Pal

**Comment by actislav** [comment]
KeepMinDuplicatePokemon = 1 TransferWeakPokemon = false

**Comment by Seyrenvox** [comment]
maybe you want to start reading the wiki before asking a feature
