### ISSUE TITLE
Failed Pidgey. Result was FailedInsufficientResources, stopping evolving Pidgey

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3720]
![image](https://cloud.githubusercontent.com/assets/20842205/17511483/45826e42-5e23-11e6-86c3-faac84c357e8.png)

**Comment by actislav** [comment]
it possible only if pidgeotto in your PokemonsToEvolve list

**Comment by Profetorum** [comment]
y but this problem is only with pidgey; other pkms in PokemonsToEvolve list does not spam fails
