### ISSUE TITLE
0.8 dumping pokemons crazily

### ISSUE THREAD

**Issue by victorchanchan956** [NECROBOTIO/NecroBot#3721]
just as it saids

**Comment by mikegrimmers** [comment]
There's a line in the config that states:

"KeepMinDuplicatePokemon": 0,

That needs to be changed to minimum 1, otherwise in theory, you won't keep any Pokemon.

**Comment by necr-0** [comment]
@mikegrimmers,

> Otherwise in theory, you won't keep any Pokemon.

You will, just not anything below the KeepMinIV/KeepMinCP settings.

@victorchanchan956 

Also ensure that TransferWeakPokemon (line 96) is set to false.

**Comment by victorchanchan956** [comment]
new update? this didn t happen before(i never change default settings)

**Comment by necr-0** [comment]
@victorchanchan956,

Yes by default 0.8 now has KeepMinDuplicatePokemon set to 0.

**Comment by necr-0** [comment]
@victorchanchan956,

Yes, by default 0.8 now has KeepMinDuplicatePokemon set to 0.
