### ISSUE TITLE
Soft ban bug?

### ISSUE THREAD

**Issue by helooguys** [NECROBOTIO/NecroBot#3722]
Hi i am using necrobot 0.8.0 and i am getting this after a while i havent changed the confing and stuff.
https://s10.postimg.org/divdo94o9/image.png 
Can you recommend me a more stable and reliable version of the bot cus 0.7.6 isnt working.
Sorry if i spam link me the if there is similar issue and delete that one.

**Comment by ObsessedHacker** [comment]
same

**Comment by helooguys** [comment]
Ok i think this is issue is similar but i am using 1 bot and never touched the config files.
https://github.com/NECROBOTIO/NecroBot/issues/3696

**Comment by MistahhJ** [comment]
Post your config. @helooguys

**Comment by Gingiangiallo** [comment]
i am using 0.7.7 no problems, downgrade version maybe

**Comment by situ1994** [comment]
Use the 0.8.0 version and use this config.
I worked around and fixed it.
[Config.txt](https://github.com/NECROBOTIO/NecroBot/files/408607/Config.txt)

**Comment by Gingiangiallo** [comment]
which change you made?

**Comment by situ1994** [comment]
changes like keepdupilcates, human walking, speed of walking etc.

**Comment by MistahhJ** [comment]
"DisableHumanWalking": true,

Change it to false.

**Comment by helooguys** [comment]
[confg.txt](https://github.com/NECROBOTIO/NecroBot/files/408611/confg.txt)
this is the config iam using its the stock one i never changed it.
