### ISSUE TITLE
Soft-banned every freaking time

### ISSUE THREAD

**Issue by jvvlcek** [NECROBOTIO/NecroBot#3724]
![krag](https://cloud.githubusercontent.com/assets/20924461/17511682/58147ca2-5e24-11e6-8ee4-303ee83594b7.png)

Still getting soft banned...
---- Getting softbanned on 4 different accounts, even with different locations..
Walking speed: 10.0
DisableHumanWalking: False
KeepMinDuplicates: 1

**Comment by Gingiangiallo** [comment]
version?

**Comment by jvvlcek** [comment]
Latest

**Comment by erlbinary** [comment]
![image](https://cloud.githubusercontent.com/assets/2863244/17511754/0a0c4ae8-5e57-11e6-8da6-8395a4bb8531.png)

Same Problem

**Comment by satanvagina** [comment]
Same problem, might be ip bans?

**Comment by jvvlcek** [comment]
I guess when you´ll get IP ban, the bot will tell ya.. Happend this on a virtual server

**Comment by drusty94** [comment]
same problem

**Comment by MetaExtreme** [comment]
Don't use more than 2 accounts on 1 IP.
This might be the problem.

**Comment by MistahhJ** [comment]
Here's my config. Bot has been running for 2 hours on the latest version with no problems. 

[config.txt](https://github.com/NECROBOTIO/NecroBot/files/408623/config.txt)

**Comment by jvvlcek** [comment]
When I use older version it says to fill out google username and password.. I´m done

**Comment by mooogai** [comment]
if you want to use an older version put in "false" at AutoUpdate and it should work.

**Comment by ThomasSRL** [comment]
Having the same problem sadly. @erlbinary

**Comment by Dequim** [comment]
same problem here, v0.7. 
( Slow walking speed, big delays... )

**Comment by jvvlcek** [comment]
My friend uses 4 accounts on 1 server.. This is so confusing

**Comment by jvvlcek** [comment]
Seems like 0.7.8 works.. We will see..

**Comment by Gandaflux** [comment]
with latest version you should use only 2 clients from one ip

**Comment by jvvlcek** [comment]
Soft banned after 6 minutes with 0.7.8.

**Comment by ThomasSRL** [comment]
If you cant lift a softban are you properly banned?

**Comment by tetsunoony** [comment]
> 3 account in same ip  WILL GET BAN!!!  
no fix

**Comment by MetaExtreme** [comment]
use a proxy then it will work
