### ISSUE TITLE
[Request] Keep 2 pokemons of each type: 1 with best CP and 1 with best IV

### ISSUE THREAD

**Issue by Yanush7** [NECROBOTIO/NecroBot#3725]
Hi

Currently (AFAIK) it is impossible to config the bot to keep 2 pokemons of each type depends on CP AND IV.

For example what I think will be very usefull is:

      "any": {"keep_best_cp": 1, "keep_best_iv": 1},

Or even pokemon specific settings:
      "Pidgey": {"keep_best_cp": 1, "keep_best_iv": 1},

**Comment by Profetorum** [comment]
^

**Comment by nfettinger** [comment]
You can already do this
