### ISSUE TITLE
(FIX) For everyone who is having problem with new version 0.8.0

### ISSUE THREAD

**Issue by situ1994** [NECROBOTIO/NecroBot#3728]
[Config.txt](https://github.com/NECROBOTIO/NecroBot/files/408610/Config.txt)
 use this config I customed and now it works fine just change your proffered lat and long and copy the rest of the text into your config file.
DO NOT USE MORE THAN 2 ACCOUNTS IN THE SAME IP.

**Comment by bastacs** [comment]
how many client can opened?

**Comment by situ1994** [comment]
2 maximum

**Comment by Rabelaiss** [comment]
Which problems this resolves?

**Comment by Seyrenvox** [comment]
what's the unusual from that config? the walking speed?

**Comment by situ1994** [comment]
@Rabelaiss all the problems including no usable pokestops
@Seyrenvox walkingspeed, humanwalking, number of duplicates etc.

**Comment by neurone3** [comment]
This will not fix the problem

**Comment by situ1994** [comment]
@neurone3 why? It works for me pretty well.

**Comment by Seyrenvox** [comment]
okay. disablehumanwalking was set to false as default. so, no. it's not unusual.
number of duplicates set to 1 as default, so, yes, not unusual.

what is the "problem" you talking about here, btw?

**Comment by situ1994** [comment]
@seyrenvox i was working around and tweaking few things and now it works so I posted here.

**Comment by Gandaflux** [comment]
For me  2 clients from 1 ip is fixing problem with soft-ip-ban.

**Comment by neurone3** [comment]
@situ1994  idk but still getting no usable pokestop error using your config file just copy pasted

**Comment by situ1994** [comment]
@neurone3 close it for 5 mins and then start again. It fixed the same problem that I had. And dont use more than 2 accounts in same IP

**Comment by Seyrenvox** [comment]
neurone: no usable pokestop can be bypass by switching IP.
try starting bot with VPN on.

**Comment by McGuim** [comment]
2 account / 30kmh / 0 min pkmn and working for about 1.5 hours peacefuly now.

I think that ip ban is related to number of actions taken in an time window, like run pokestops and catch pokemons.

**Comment by LazyBrand** [comment]
Stop my "pokestop distance" problem, thanks! Although it did transfer a couple of my high CP pokemon...

**Comment by Sudiddo** [comment]
thank you !

**Comment by Kraker01** [comment]
How many bots can you run on a VPN?

**Comment by maliqoye** [comment]
client?? recommended 2 maximum

if you run 3, you will got soft ban many times

**Comment by Seyrenvox** [comment]
two bots running. 60kmph walking speed. no VPN.
2sec delay action. 5 minutes gap runtime between.
been running for an hour now

**Comment by CHAOSxCREATOR** [comment]
sorry idiot question but what does being on the same ip means? Does it mean running the bot client in the same network? Or running multiple bot client at one device?

**Comment by hippopride** [comment]
Used a vpn to change ip and worked fine.
