### ISSUE TITLE
Any Good GPS Working Co-Ordinates?

### ISSUE THREAD

**Issue by Jordano3710** [NECROBOTIO/NecroBot#3730]
![image](https://cloud.githubusercontent.com/assets/20824860/17511778/7e809b26-5e1c-11e6-930c-c82c6183da94.png)

All i keep getting is this and i think its the gps could anyone give me a working gps co-ordinate please?

**Comment by MetaExtreme** [comment]
try this
"DefaultLatitude": 40.764897,
"DefaultLongitude": -73.972762,
if it doesn't work you are softbanned or blacklisted on Niantic servers
make you also have
"MaxTravelDistanceInMeters": 1000,

**Comment by Jordano3710** [comment]
Hey thanks @MetaExtreme Works Perfectly!

**Comment by situ1994** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3728 fix
