### ISSUE TITLE
EvolveKeptPokemonsAtStorageUsagePercentage

### ISSUE THREAD

**Issue by NunoAG** [NECROBOTIO/NecroBot#3732]
Hello,

The config file reader is reading EvolveKeptPokemonsAtStorageUsagePercentage and writing it back but this time multiplied by 100, until it reaches 100.

Ex.: I set it to 0.01. On the first iteration (run) the file handler (or whatever) writes it as 1 and in the second iteration as 100.

Regards,
Nuno

**Comment by NunoAG** [comment]
[Config Parser](https://github.com/NECROBOTIO/NecroBot/blob/master/PoGo.NecroBot.Logic/Settings.cs)
`if (EvolveKeptPokemonsAtStorageUsagePercentage <= 1.0)
            {
                EvolveKeptPokemonsAtStorageUsagePercentage *= 100.0f;
            }`

Why this?

**Comment by Unentertained** [comment]
I might be wrong, but it seems like you are trying to put in a decimal for what should be a percentage value.
So for 40 Percent: It should be 
EvolveKeptPokemonsAtStorageUsagePercentage: "40.0"

And Not:
EvolveKeptPokemonsAtStorageUsagePercentage: "0.40"

**Comment by NunoAG** [comment]
@Unentertained 

It's about logic, not an error, because actually the code accepts my 0.01 percentage.
In this case 0.01% of a 250 pokemon storage is 2.5 pokemons, meaning it will evolve all when it reaches this limit.

Regards,
Nuno
