### ISSUE TITLE
GPS traveling resets to start point after throttling API calls

### ISSUE THREAD

**Issue by Rincos926** [NECROBOTIO/NecroBot#3733]
I am setting up trips around 30km around the town to farm, every time when it reached somewhere in around 15km or 20km, message of throttling API calls appeared and my pointer just directly homing back through the town and start over.  Seems not related to Max Dis. in meters in config.

(I've also tried some trailing route, highway routes which also homing back somewhere in the middle of the trip)

Is it possible to log the location before exceptions that the pointer can resume traveling? Not a big problem but awkward though 

![aef67d37e289268b4d8431c6635c1676](https://cloud.githubusercontent.com/assets/20920034/17511152/4572cea2-5e54-11e6-8409-191e5318ce41.png)

**Comment by Rincos926** [comment]
Now it's telling me the start point is too far away from the point where exception occured ...

**Comment by illidan1337** [comment]
im getting a similar problem where the API throttles every 30 minutes and when it reconnects my gps signal goes back the the starting point
simply having the track resume from closest waypoint would fix the problem

**Comment by nfettinger** [comment]
Duplicate issue.
