### ISSUE TITLE
high cp pokemon transferred

### ISSUE THREAD

**Issue by mp0912** [NECROBOTIO/NecroBot#3734]
high cp pokemon also transferred and also high iv pokemon transferred... my prioritize iv over cp is false.
![asdsfafw](https://cloud.githubusercontent.com/assets/20653891/17511935/f985c0b4-5e42-11e6-9570-2572c019dccf.png)

**Comment by situ1994** [comment]
close the thread fix available here: https://github.com/NECROBOTIO/NecroBot/issues/3728

**Comment by MistahhJ** [comment]
"PrioritizeIvOverCp": true,

Change it to false.

**Comment by necr-0** [comment]
Ensure that your settings match this:

"KeepMinDuplicatePokemon": 0
"TransferWeakPokemon": false

Else, this will only keep Pokemon that meet your KeepMin criteria (IV and CP regardless).

@MistahhJ,

Read the OP.

> my prioritize iv over cp is false.

**Comment by necr-0** [comment]
Ensure that your settings match this:

"KeepMinDuplicatePokemon": 1
"TransferWeakPokemon": false

Else, the bot will only keep Pokemon that meet your KeepMin criteria (IV and CP regardless).

@MistahhJ,

Read the OP.

> my prioritize iv over cp is false.

**Comment by mp0912** [comment]
It is as u say

**Comment by mp0912** [comment]
PrioritizeIvOverCp is false
Keepminduplicate is 1 
Transferweak is false

**Comment by WuddyMarco** [comment]
If your PrioritizeIvOverCp is set to false than i cant see any problem. Your screenshot says that there ist a higher CP Pokemon in your inventory and so he will transfer every pokemon which ist lower than that.

**Comment by mp0912** [comment]
But it is showing best cp pokemon is of lesser cp than the transferred
pokemon

**Comment by necr-0** [comment]
@mp0912,

Could you post your config file to pastebin? http://pastebin.com/
I can give it a look then.

**Comment by mp0912** [comment]
http://pastebin.com/yjmmr4qe

**Comment by RobJohnson44** [comment]
I can confirm this issue
My relevant settings:

"PrioritizeIvOverCp": false,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinLvl": 6,
"KeepMinOperator": "or",
 "UseKeepMinLvl": false,

Bot log with this settings:
[12:35:10] (TRANSFERED) Vaporeon        - CP: 1467  IV: 70.91%   [Best CP: 956  IV: 93.40%] 

I suspect the KeepMin* settings conflicting with PrioritizeIvOverCp

**Comment by mp0912** [comment]
still the same issue
![dddddd](https://cloud.githubusercontent.com/assets/20653891/17515440/f6465978-5e55-11e6-80b4-63ec39f0bcf4.png)

**Comment by nfettinger** [comment]
Duplicate #3338
