### ISSUE TITLE
Private Proxy working?

### ISSUE THREAD

**Issue by marburger93** [NECROBOTIO/NecroBot#3736]
I use private proxy with login data in auth.json, 1 account per ip in the same walking-location but all accounts get soft bans to the same time
Walking speed: 20.0
DisableHumanWalking: False
Proxy not working and use main ip? How can I check this?

```
  "UseProxy": true,
  "UseProxyHost": "IP",
  "UseProxyPort": 82,
  "UseProxyAuthentication": true,
  "UseProxyUsername": "username",
  "UseProxyPassword": "password"
```

**Comment by somani6** [comment]
If a software don't support proxy u can always try to force it using a proxy with http://www.proxycap.com/

**Comment by ferbeb** [comment]
You could check with wireshark.

**Comment by Sheetka** [comment]
Working private sock5 proxy not working for me either, works fine without

**Comment by GreatApo** [comment]
Yeah, proxy seems not to work if we "check" it with  soft bans...

**Comment by marburger93** [comment]
yes, not working - i set HTTP Proxy in the auth.json but the bot use the main ip
with other programs the proxy is working
