### ISSUE TITLE
Sniping issue

### ISSUE THREAD

**Issue by skick1234** [NECROBOTIO/NecroBot#3737]
It re-snipe if it can't snipe any pokemon. It is very time-consuming because it snipe at a non-pokemon coordinate about 5-10times. Fix it, please! Like older version.

**Comment by Gandaflux** [comment]
:+1:

**Comment by necr-0** [comment]
You're not exactly being clear. If there's no Pokemon at your coordinates at the time of sniping, there's no Pokemon. Simple.

If the error you're receiving is "Did not find a Pokemon within the SnipingScanOffset!" then a fix will be implemented when the developers are awake (see #announcements in the Discord chat).
Further to this, you may change your settings to resemble this:

"SnipingScanOffset": 0.005

That should fix the above error.

Alternatively, combined with the above fix, try setting up PogoLocationFeeder. That'll snipe "confirmed" coordinates.

**Comment by Longpc** [comment]
I found that "UseSnipeOnlineLocationServer": false was missing at nearly version so BOT get too much snipping information from pokezz and pokersnipper (almost is spam).
Add this and use local pokefeeder only slove this problem for me

**Comment by skick1234** [comment]
"UseSnipeOnlineLocationServer": false
I use Feeder :) I also turn off get from pokesniper, pokezz,... i just get from discord
And i don't receive "Did not find a Pokemon within the SnipingScanOffset!"

**Comment by STCOZT** [comment]
Nothing works. Tried everything since this morning but nothing solve this issue. I think Feeder app should be updated...

**Comment by nfettinger** [comment]
This is not an issue with Necrobot
