### ISSUE TITLE
Transferring all pokemons

### ISSUE THREAD

**Issue by parthbathia** [NECROBOTIO/NecroBot#3742]
The bot is transferring all the pokemons.

**Comment by situ1994** [comment]
close this thread fix already available at https://github.com/NECROBOTIO/NecroBot/issues/3728

**Comment by necr-0** [comment]
This has been addressed on multiple occasions. Please, in the future, have a look at previous issues possibly related to your problem. Regardless, ensure your settings follow this:

"PrioritizeIvOverCp": true
"KeepMinDuplicatePokemon": 1
"TransferWeakPokemon": false
