### ISSUE TITLE
ask about verbose

### ISSUE THREAD

**Issue by BamBoo87** [NECROBOTIO/NecroBot#3743]
"VerboseRecycling": true, 
does somebody want to explain about that?

**Comment by Markersx** [comment]
I believe that if "VerboseRecycling": true, then it will show you this http://i.imgur.com/Q6VqTgm.png but if "VerboseRecycling": false, then it will show you this http://i.imgur.com/hkpooA3.png

**Comment by necr-0** [comment]
@Markersx 
Nah, that setting is this: DetailedCountsBeforeRecycling. Setting that to false will show the "Recycling quietly..." message.

I believe VerboseRecycling simply recycles more often, as to prevent the inventory from getting overly full.

**Comment by Markersx** [comment]
@necr-0 No I just checked I set VerboseRecycling to false and it showed the "Recycling Quietly..." message.

**Comment by BamBoo87** [comment]
hmmmm, ok i'll try that lol

**Comment by Markersx** [comment]
@necr-0 setting DetailedCountsBeforeRecycling to false makes it not show any recycling messages.
