### ISSUE TITLE
No inventory objects line anymore

### ISSUE THREAD

**Issue by Soukatsoui** [NECROBOTIO/NecroBot#3744]
Hello.

Necrobot doesn't show me anymore the line with the contents of my inventory, does anyone have the same bug and knows how to fix it, please?

Thanks :)

**Comment by necr-0** [comment]
Weird, mine is.
If you're using the latest version, ensure your setting is this:

"DetailedCountsBeforeRecycling": true

**Comment by Soukatsoui** [comment]
Well, it was on false, dunno why... Thanks for your answer :)
