### ISSUE TITLE
How to show IV of all pokemon in stock

### ISSUE THREAD

**Issue by NPRH1207** [NECROBOTIO/NecroBot#3745]
First of all big props to the dev-team. The bot is great.

I have a question concenring the IV-level. Is it possible to show the IV-level of all pokemon that are in the stock of my account? I have found the option "AmountOfPokemonToDisplayOnStart": 10, but it does not show the IV-level, right?

**Comment by StarvingDeveloper** [comment]
https://github.com/nicoschmitt/necrobotvisualizer/releases

but according to rumors soon necrobot getting GUI

**Comment by necr-0** [comment]
That option will display the IV level on startup.
If you want live updates, download NecrobotVisualiser and run that. Ensure that your settings have this though:

"UseWebsocket": true

**Comment by ShaneAbara** [comment]
@necr-0 how to use the NecrobotVisualizer?

**Comment by necr-0** [comment]
@ShaneAbara,

1. Download from their GitHub: https://github.com/nicoschmitt/necrobotvisualizer/releases
2. Extract the files to a folder within the root of the NecroBot directory.
3. Edit your NecroBot _UseWebsocket_ setting to _true_.
4. Run NecroBot.
5. Run the Visualiser (NecrobotVisualizer.exe).

**Comment by imperatorvespa** [comment]
You can use the bot. Change "DumpPokemonStats" to true in config.json.
It will create  a 'dumps' folder with a csv file. 
![iv-lvls](https://cloud.githubusercontent.com/assets/20925347/17513397/0581f9ac-5e2d-11e6-8b20-fbf611802342.jpg)

**Comment by ShaneAbara** [comment]
thanks for the tip @necr-0 & @imperatorvespa :+1:
