### ISSUE TITLE
[IDEA] A better way to move (Help avoid waveban in the future)

### ISSUE THREAD

**Issue by TakRiuto** [NECROBOTIO/NecroBot#3746]
Is possible to create a function that change from time to time the speed of movement? To make it more humane?

Is just a Idea :D

(Sorry, my english is bad D:)

**Comment by Meta28** [comment]
Yea, it would be great to specify speed ie. from 14 to 24 and the interval in which it changes...like every 5000ms it shuffles

**Comment by TakRiuto** [comment]
Is very util, for make the bot in low profile ;)

**Comment by Markersx** [comment]
#808
