### ISSUE TITLE
Sniping so far away?

### ISSUE THREAD

**Issue by nithdi** [NECROBOTIO/NecroBot#3748]
Hi, I'm using Necrobot and PogoFeeder in order to snipe Pokemons. When looking at Necrobots log, I can see that it works:

[12:15:34] (PKMN) (Gefangen) | (Wildes) Arkani Lvl: 2 CP: (127/132) IV: 74.00% |
 Chance: 24.04% | 9328473.19m entfernt | mit PokÃ©ball (142 verbleibend). | 210
EP erhalten | Bonbons: 7 | B: 34.011809 L: -118.495748

However, it always says that sniped Pokemon are several thousand kilometers away (9328km in the above case). Could this lead to a soft ban? How can I fix this?

My sniping config:
"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.008,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false

**Comment by necr-0** [comment]
That won't softban you.
It's simply a little bit of information (useless really) to show you how far from your "real" (ie, NecroBot) location you sniped. Don't stress.

**Comment by STCOZT** [comment]
@nithdi 
Are you able to snipe properly?? because i have the same settings but having tons of error since this morning..

**Comment by nithdi** [comment]
I also have alot of errors telling me that there were no Pokemon at the sniping spot. But sometimes it works.
