### ISSUE TITLE
opened 6 bot, but few minutes after all bot "softban" already

### ISSUE THREAD

**Issue by frager45** [NECROBOTIO/NecroBot#3751]
what should I do?

**Comment by WuddyMarco** [comment]
Learn to read ! There are lots of other people complaining. Maximum 2 Bots at the same time.

**Comment by Greatliu89** [comment]
Try Set config "DisableHumanWalking" to false

**Comment by brightjoyy** [comment]
even he open 6 bot , but if set the  "DisableHumanWalking" to false it work right ?
Greatliu89

**Comment by frager45** [comment]
@WuddyMarco 6 bot It works in older versions

@Greatliu89 my config:
"WalkingSpeedInKilometerPerHour": 70.0,
 "DisableHumanWalking": false,

**Comment by Greatliu89** [comment]
i never open 6 bot...
but set that can solve a lots of soft bans

**Comment by brightjoyy** [comment]
but now maximum is 2

**Comment by frager45** [comment]
ok, but i trying:
now change value: "WalkingSpeedInKilometerPerHour": 45.0, and satred 6 bot: 13.36 im waiting soft-ban

**Comment by frager45** [comment]
13.38 all soft-ban :D

**Comment by frager45** [comment]
maybe need proxy?

**Comment by Littlem0nk3y** [comment]
Hi,

Is it ok to open 4 bots on 2 computers with the same internet connection?


Thanks...
