### ISSUE TITLE
[HELP] Softban-issue; only one bot running

### ISSUE THREAD

**Issue by head0r** [NECROBOTIO/NecroBot#3753]
After starting 8.0 first time i get softbanned after minutes.
I only use one bot / one account and deactivated sniping.
The Delay of 2000/1000 worked well since V-0.3.
The last ban lasted about 15 minutes 

>   "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "WalkingSpeedInKilometerPerHour": 17.0,
  "MaxTravelDistanceInMeters": 600,
  "DelayBetweenPlayerActions": 2000,
  "DelayBetweenPokemonCatch": 1000,

**Comment by GummiBoat** [comment]
Do you have "DisableHumanWalking" on false?

**Comment by head0r** [comment]
Yes, i have.

**Comment by GummiBoat** [comment]
That's weird, I'm running around on 31 km/h and haven't been soft-banned once..

Are you sniping? If yes, which methods do you use?

**Comment by lilmalossi** [comment]
i cant find nearby pokestops -_-

**Comment by Batcooon** [comment]
I'm getting this too

**Comment by head0r** [comment]
PoGoLocationFeeder.GUI (last update).
But atm i was not sniping, not since yesterday.

> "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.03,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by Greatliu89** [comment]
new 0.8.0 will change config DisableHumanWalking to true default . recheck it

**Comment by Batcooon** [comment]
[05:38:04] (UPDATE) [Evolves] Potential Evolves: 0
[05:38:04] (INFO) No Eggs Available
[05:38:04] (INFO) No Incense Available
[05:38:04] (EGG) Incubator status update: 2.00km left
[05:38:04] (EGG) Incubator status update: 1.47km left
[05:38:05] (INFO) Amount of Pokemon Seen: 136/151, Amount of Pokemon Caught: 131/151
[05:38:05] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[05:38:07] (UPDATE) [Evolves] Potential Evolves: 0
[05:38:07] (INFO) No Eggs Available
[05:38:07] (INFO) No Incense Available
[05:38:07] (TRANSFERED) Rattata         - CP:  171  IV:  29.70%   [Best CP:  121  IV:  74.19%] (Candies: 15)
[05:38:07] (INFO) Amount of Pokemon Seen: 136/151, Amount of Pokemon Caught: 131/151
[05:38:08] (EGG) Incubator status update: 2.00km left
[05:38:08] (EGG) Incubator status update: 1.47km left
[05:38:09] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by NoiRequiem** [comment]
What is this disablehumanwalking supposed to do? I couldn't find it in the config list.

**Comment by head0r** [comment]
disabled since it was established - never changed it so far.
>   "DisableHumanWalking": false,

**Comment by Batcooon** [comment]
I'm getting the " No usable PokeStops found in your area. Is your maximum distance too small?" over and over again. and my Pokémon infinitely keep transferring

**Comment by head0r** [comment]
After restarting the bot i get the same issue... No usable stops.

**Comment by Batcooon** [comment]
so I got some info from some and he/she said you can only run one bot at the time. has to do with accounts using the same IP. I don't know if its the 0.8.0 update. or if its pokemon go

**Comment by head0r** [comment]
i always use ONE bot :) wrote it in the first post though

**Comment by head0r** [comment]
i think the PoGo servers are to blame...
[http://www.mmoserverstatus.com/pokemon_go](url)
They all are laggy. maybe thats the issue

**Comment by GummiBoat** [comment]
Yes, "No usable pokestops" is a niantic-server issue.

**Comment by Ezoteric** [comment]
it seems to me it says it when there is no pokestop near by.

i once had that and the first pokestop was like 2km away, but when i start it near a pokestop it never ever says it.
