### ISSUE TITLE
(ATTENTION) No Usable PokeStops found in your area. Again!

### ISSUE THREAD

**Issue by hammerhead13** [NECROBOTIO/NecroBot#3755]
Just started getting (ATTENTION) No Usable PokeStops found in your area. Again!. It was fine with the location 10 min ago and started getting Possible Softban 1/45 etc. Running on Latest Version. Walking speed set to 7km.

**Comment by Amf1** [comment]
same problem

**Comment by mimilo** [comment]
Change the lat and the ling in the config files , when you had this problem it come from a Soft ban too

**Comment by mimilo** [comment]
Don't use much more 2 account during the same time

**Comment by d2a6on** [comment]
@hammerhead13 @Amf1 could be PoGo servers. I am running fine with 10km walking speed.

**Comment by necr-0** [comment]
Try changing your longitude and latitude coordinates. Seems the bot is getting a bit picky with where it's stationed. And as @mimilo said, don't run more than two bots (though one is preferred) on the same IP.

The default settings should work fine:

>   "DefaultLatitude": 40.778915,
  "DefaultLongitude": -73.962277,

**Comment by Batcooon** [comment]
I use default and I'm running two bots. and I'm getting that error

**Comment by mimilo** [comment]
Use you spining ?

**Comment by hammerhead13** [comment]
Oddly enough it seems to be working again. Didnt change anything! The Coordinates im using are from a Pokemon that Got Away so Im combing the area again this morning with Hopes of a Capture this time. Lol. Thanks everyone for the info.

**Comment by hammerhead13** [comment]
Looks like a Intermittent Issue. I get the Softban and then if I close and reopen I get this error again with no Stops.
