### ISSUE TITLE
no usable pokestop?

### ISSUE THREAD

**Issue by lilmalossi** [NECROBOTIO/NecroBot#3756]
can find the pokestops

**Comment by marburger93** [comment]
Presumably softban, do you use multiple bots on an IP address ?

**Comment by d2a6on** [comment]
Either multiple bots or walking speed too high.

**Comment by lilmalossi** [comment]
walking speed is on 31km/h
and i use 3 bots

**Comment by Batcooon** [comment]
I'm using two and I got " No usable PokeStops found in your area. Is your maximum distance too small?"

**Comment by necr-0** [comment]
@lilmalossi,

There's your problem.
Only run 1 bot per IP at the moment. Two is possible, but seems to be throwing errors as well occasionally.

**Comment by lilmalossi** [comment]
even with privitize vpn?

**Comment by necr-0** [comment]
@lilmalossi, @Batcooon

There's your problem.
Only run 1 bot per IP at the moment. Two is possible, but seems to be throwing errors occasionally as well.

**Comment by Batcooon** [comment]
ohhh really?? would VPN work?

**Comment by Batcooon** [comment]
oh its working again!! but it took a while

**Comment by Batcooon** [comment]
so it only works with one bot? :/ @necr-0

**Comment by necr-0** [comment]
@Batcooon, 

It'll breakdown in a bit.
A VPN will work, but it's expected that Niantic will block their IP addresses soon. So I wouldn't expect it to last. But regardless, you'll have to setup your VPN in a different virtual instance to ensure that the bots are running off different IPs.

But without messing around, yes, it's only working with one bot at the moment.

**Comment by Batcooon** [comment]
@necr-0 

thank you for the information. on latest version I was running two bots and it was working perfectly. is it because of this new 0.8.0? Or is this Pokémon Go (Niantic)?

**Comment by Batcooon** [comment]
on the last version*^

**Comment by necr-0** [comment]
@Batcooon,

I am not sure, as I'm just running one bot at the moment.
But I believe it to be an error with NecroBot, not Niantic. It's possible that reverting back to 0.7.7 (not 0.7.8) may fix the error, but not 100% sure.

**Comment by Invaderofbunnie** [comment]
Im running 8.0 at the moment 
Only running 1 bot (because that's all my brain can handle at the moment)
Ran for about 45 minutes and then started giving me the issue.
