### ISSUE TITLE
Using proxy in auth settings results in no connection

### ISSUE THREAD

**Issue by MrSco** [NECROBOTIO/NecroBot#3758]
If use proxy is true then bot doesn't work at all

**Comment by theloser** [comment]
Bull. Shit. Works fine for me.

**Comment by BuschMartin** [comment]
Nope not for me too. See #3758

**Comment by theloser** [comment]
Sure the proxy you are trying to use is working?

**Comment by BuschMartin** [comment]
sure. this is the standard company proxy.
i use it e.g. in the browser and pokesniper2.

**Comment by PassiveModding** [comment]
make sure you use quatations for your proxy host and port "1.2.3.4" "6666" etc

**Comment by BuschMartin** [comment]
btw. I use the same config for v0.7.6 and there it works without problems
let me try 0.7.8....

0.7.8 don't works too. So the bug was added from 0.7.6 -> 0.7.8

**Comment by BuschMartin** [comment]
you can see my config in #3779

**Comment by nfettinger** [comment]
Duplicate #3235
