### ISSUE TITLE
Telegram: incorrect informations for the /profile command

### ISSUE THREAD

**Issue by graou13** [NECROBOTIO/NecroBot#3760]
Hello, when I do the /profile command bad information are displayed. 
It displays :

----- LVL 26 | #username# ----- 
 Experience: 983319/1100000 
 Pokemons caught: 2377 
 Pokemons deployed: 9 
 Pokestops visited: 4211 
 Eggs hatched: 4211 
 Pokemons envolved: 57 
 Pokedex entries: 227 
 KM walked: 85

Instead of :

----- LVL 26 | #username# ----- 
 Experience: 983319/1100000 
 Pokemons caught: 2377 
 Pokemons deployed: 9 
 Pokestops visited: 4211 
 Eggs hatched: 57 
 Pokemons envolved: 227
 Pokedex entries: 85
 KM walked: 158

What I guess is going on is that someone accidentally copy pasted the number of pokestops visited when filling the stats variable and everything was moved one index up in the stat array because of that.

**Comment by graou13** [comment]
Also mistyped "87" instead of "85" in the second part of the example

**Comment by iTayGNR** [comment]
Same here.

**Comment by GrimDemon** [comment]
#3754 fixes this.

**Comment by dfmeier** [comment]
Fix only if you use the bot in german. Forgot to update the Translation.cs
"ProfileStatsTemplateString"
"ShowPokeTemplate"
"HelpTemplate"

**Comment by GrimDemon** [comment]
So sad :-(

9 sie 2016 20:07 "MeieR" <notifications@github.com> napisał(a):

**Comment by schwartzadev** [comment]
Solved (#3754)
