### ISSUE TITLE
Socks support ?

### ISSUE THREAD

**Issue by cpanel10x** [NECROBOTIO/NecroBot#3763]
Or VPN in auth config

**Comment by Sanzzes** [comment]
Why the hell you need a vpn config in the bot. Use openVPN ore something like that

**Comment by cpanel10x** [comment]
openvpn can use for multiple bot :|

**Comment by marburger93** [comment]
i have the same problem, http also does not work.
https://github.com/NECROBOTIO/NecroBot/issues/3736
