### ISSUE TITLE
[IDEA] Destination file

### ISSUE THREAD

**Issue by FureszOszkar** [NECROBOTIO/NecroBot#3765]
I think the destination file (if the file is exist, the BOT go to the coordinate, instead to the next pokestop. After reach that, the file renamed.) will be a good feature, because the user can affect on the BOT move.

**Comment by nilsbrychzy** [comment]
You mean interactive controlling the bot to go somewhere other?
I think this is already in there, because if you enter a new location he goes to there from the last saved position!
Not what you want, but perhaps can help.
For the bot this feature is not needed I think.

**Comment by FureszOszkar** [comment]
Yes! When I start the BOT in the area, and I see on a pokemon go map that, the next street a Snorlax appeared, I would like to control the BOT movement.

**Comment by nfettinger** [comment]
Use GPX or sniping.
