### ISSUE TITLE
I'm lost.

### ISSUE THREAD

**Issue by ChickenChive** [NECROBOTIO/NecroBot#3769]
So i've set it up, successfully logged in but the script is running and can't find pokestops near the coords I put in. How do I stop the script to try new coords? or is this a common issue with Necrobot for PoGo? I'm not familiar at all with codes so if anyone wants to suggest a different product that is idiot friendly, feel free!

**Comment by necr-0** [comment]
It seems the bot is getting picky with coordinates at the moment.
Revert them back to their original values and it should work a-okay.

>   "DefaultLatitude": 40.778915,
  "DefaultLongitude": -73.962277,

**Comment by ChickenChive** [comment]
When you say original values, do you mean just don't enter lat/long when it asks on set up?

For some reason I can't open the .json files? Do I need a specific program to do that?

**Comment by necr-0** [comment]
@ChickenChive, 

Yep, that's what I mean.
As for editing, you can use Notepad, but I suggest download Notepad++. It's a lot more sophisticated and easier to work with when it comes to these types of files.

**Comment by ChickenChive** [comment]
Got it working, thanks buddy! Donation inbound tonight!
