### ISSUE TITLE
SoftBan

### ISSUE THREAD

**Issue by Nilexis** [NECROBOTIO/NecroBot#3771]
90% of the time my screen is light blue, telling me im softbanned and it's trying to unban by spinning stations. Is it suppossed to be like that? Because my friend told me its probably a bug and this isn't happenning to him.

**Comment by iPollox** [comment]
It should do it 45 times

**Comment by head0r** [comment]
#3753

**Comment by Nilexis** [comment]
yeah. but its doing it again and again, catching 2 rattata and softban again.

**Comment by necr-0** [comment]
As a tldr to what @head0r linked, you just need to change one of the settings.
Set _DisableHumanWalking_ to false.

**Comment by head0r** [comment]
@necr-0 same issues in my thread, but didnt work.

**Comment by Nilexis** [comment]
changed DisableHumanWalking to false. I will update if that helped later.

**Comment by Nilexis** [comment]
Looks like it is solved for now. Still softbans once in a while, but mich less. Thankes!
