### ISSUE TITLE
transferring same level value, caught pokemon unremained

### ISSUE THREAD

**Issue by sam19xp** [NECROBOTIO/NecroBot#3772]
![capture](https://cloud.githubusercontent.com/assets/20926006/17514365/d007df48-5e64-11e6-9da3-13bfbcad0f66.PNG)

after the update, I lost my pokemon cause of this. Its comparing the same cp value to itself and transferred instantly

**Comment by auth100488** [comment]
same here!!! haha!

**Comment by shetonaz** [comment]
"KeepMinDuplicatePokemon": 0,

Change 0 to prefered number

**Comment by auth100488** [comment]
Shit worked! Thanks

**Comment by sam19xp** [comment]
on what range? like any number? 0-10?

**Comment by shetonaz** [comment]
@sam19xp it depends how many same type of pokemons you want to keep. Lets say you want to keep like 2 of every type of pokemon, so you change 2 instead of 0.

**Comment by auth100488** [comment]
I used 1

**Comment by nfettinger** [comment]
Duplicate #3338
