### ISSUE TITLE
Pokeball number doesn't update

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#3773]
![image](https://cloud.githubusercontent.com/assets/20842205/17514417/ce973280-5e32-11e6-945a-42f378702dfe.png)

**Comment by tomy91** [comment]
Check your config and make sure **MinPokeballsToSnipe** is lower than **TotalAmountOfPokeballsToKeep**. Seems that You have set 120 minimum for sniping and 95 total.

**Comment by necr-0** [comment]
Can confirm this is an error at the moment.
Let it run for a little bit and it'll fix itself.
