### ISSUE TITLE
Proxy not working anymore

### ISSUE THREAD

**Issue by BuschMartin** [NECROBOTIO/NecroBot#3774]
Since 0.8.0 it hangs in the login dialog.

0.7.6 worked fine. I haven't tried 0.7.8 .

I tried the proxy in the auth.log and via 

```
<system.net>
   <defaultProxy>
      <proxy proxyaddress="http://....." bypassonlocal="false"	/>
   </defaultProxy>
</system.net>  
```

Proxy works without auth.

**Comment by MetaExtreme** [comment]
same here
![test](https://cloud.githubusercontent.com/assets/20824329/17514559/8d2056dc-5e33-11e6-8e4e-b541417c2d30.png)

my settings are
"UseProxy": true,
  "UseProxyHost": 81.21.77.204,
  "UseProxyPort": 8083,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

any solutions?

**Comment by BuschMartin** [comment]
btw. I use ptc login

**Comment by cpanel10x** [comment]
@MetaExtreme : Input string in ""

**Comment by BuschMartin** [comment]
@MetaExtreme  you must write the Host and Port as String:
```
"UseProxyHost": "81.21.77.204",
"UseProxyPort": "8083",
```

**Comment by MetaExtreme** [comment]
@BuschMartin ok thx :)
