### ISSUE TITLE
Special filters

### ISSUE THREAD

**Issue by Firefly1029** [NECROBOTIO/NecroBot#3776]
Keep losing high cp because it prioritizes iv. I'm trying to fix my config to keep a few of each so I can have more room but it keep deleting for example 1500 cp 70 iv, and keeping 600 cp 94 iv. This is in the filters like 
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },

even after setting it to "and" it still cares more about iv. http://prntscr.com/c3h6xl 

does the "PrioritizeIvOverCp" override everything else in the config. I'm trying to get this setup but worried it's going to delete my 2700 dragonite because of it's shit iv. I know iv is important but still. 

also, why does it transfer EVERYTHING if it doesn't have a custom filter and isn't on the "donottransfer" list. I did a test took blastoise off to see if it would listen to 
  "KeepMinCp": 1300,
  "KeepMinIvPercentage": 75.0,
but then it transferred every single one and ignored everything.

**Comment by MetaExtreme** [comment]
do "PrioritizeIvOverCp": false, and it will work

**Comment by Firefly1029** [comment]
With that can I remove stuff from the donottrasnfer list without losing them

**Comment by necr-0** [comment]
_PrioritizeIvOverCp_ will only affect a few settings. It should not affect the Pokemon under the DoNotTransferList. So setting it to _false_ won't have an effect on the Pokemon there. Without having to edit the configuration file however, simply set your Dragonite - and any other Pokemon you want to keep - in the app to favourite. Then the bot will not transfer them.

That being said though, the default settings in relation to a Dragonite will not transfer anything above 2600.

>     "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }

**Comment by Firefly1029** [comment]
I just used dragonite as an example, It was saving low cp so i was going to remove it from donottransfer list hoping it wouldn't removed above my keepmin settings. but when testing with blastoise I wasn't sure why but it makes sense now.

**Comment by Firefly1029** [comment]
also with some accounts I'm trying not to sign on to them at all yet just for the lolz. So I can't always favourite.

**Comment by d2a6on** [comment]
[04:21:07] (TRANSFERED) Machop          - CP:  894  IV:  80.34%   [Best CP:   79  IV:  92.04%] (Candies: 555)

Even though the value for my PrioritizeIvOverCp is false

**Comment by Firefly1029** [comment]
That's not good, but mine will still do similar, it got rid of a 13XXcp 41 iv for a 12XX 60iv

**Comment by nfettinger** [comment]
Duplicate #3338
