### ISSUE TITLE
Cannot LogIn

### ISSUE THREAD

**Issue by parthroxx** [NECROBOTIO/NecroBot#3777]
[16:54:06] Update Skipped
[16:54:06] Logging in using Google
[16:54:06] You need to fill out GoogleUsername and GooglePassword in auth.json!

**Comment by MetaExtreme** [comment]
go to your auth.json and check again and restart the bot

**Comment by dmkovsky** [comment]
maybe u forgot about put ur login and password in " "

**Comment by parthroxx** [comment]
i checked !!!Everything is proper , but cannot login..

**Comment by theloser** [comment]
What version are you using? Post you auth.json and config.json, so we can check.

**Comment by parthroxx** [comment]
Worked after update....
