### ISSUE TITLE
new proper config plz??

### ISSUE THREAD

**Issue by parthroxx** [NECROBOTIO/NecroBot#3780]
Please provide proper new config working properly....

**Comment by theloser** [comment]
Delete your config directory, start the bot and it will create new default auth.json and config.json. What else do you need?

**Comment by parthroxx** [comment]
my all high cp pokemons are transferred

**Comment by necr-0** [comment]
This isn't an issue. Nor a problem.
The application works. Sure, there's a few problems that need to be ironed out, but in its default form, it works. It's simply your settings that are messing with the way in which it runs, and as such, can cause it to send errors.

**Comment by theloser** [comment]
Works as desinged. Edit the config to your needs, this is not a development issue.

**Comment by necr-0** [comment]
@parthroxx,

See, that's a problem.
Now we can work with you.

Please post your configuration file onto Pastebin and link us here. I'll give it a look.
Quickly though, ensure that your settings match this: 

`"PrioritizeIvOverCp": false,`
`"TransferWeakPokemon": false,`

**Comment by parthroxx** [comment]
http://pastebin.com/f43Tje3B

**Comment by necr-0** [comment]
@parthroxx,

Change _PrioritizeIvOverCp_ to _false_.

**Comment by parthroxx** [comment]
one more off topic question, how to open application to fullscreen?

**Comment by necr-0** [comment]
@parthroxx,

...
The usual button in a windows form? Like, the little square thing between the minimise and close button.

**Comment by parthroxx** [comment]
it doesnt maximise it fully

**Comment by parthroxx** [comment]
![capture](https://cloud.githubusercontent.com/assets/20926308/17515256/ec35dbee-5e54-11e6-9cd8-f1c361031a3d.PNG)

**Comment by parthroxx** [comment]
@necr-0  after ur changes in config see this again!!!

[capture](https://cloud.githubusercontent.com/assets/20926308/17515319/5ae82614-5e55-11e6-9769-3feeff7c9e1f.PNG)

**Comment by necr-0** [comment]
@parthroxx,

F11 then for fullscreen.
As for the transferring problem, 100% sure you changed it? Can you check the config again?

**Comment by parthroxx** [comment]
yes sure i changed it

**Comment by parthroxx** [comment]
@necr-0 please upload one proper config for high cp pokemons please

**Comment by necr-0** [comment]
@parthroxx

http://pastebin.com/0e1M8iTJ

Use that with a **clean** install of 0.8, and it should work fine.
I'm off to bed, so if you're getting any problems (you shouldn't), I won't be able to help.

**Comment by parthroxx** [comment]
thank you so much
