### ISSUE TITLE
Cant run..

### ISSUE THREAD

**Issue by Purrygon** [NECROBOTIO/NecroBot#3782]
Hey everyone I'm encoutering a problem where after I set up my account and procceed, a msg pops up saying: (copied from logs)
[14:28:56] Perfect! You already have the newest Version 0.8.0
[14:28:56] Logging in using Google
[14:28:57] Make sure you have entered the right Email & Password.

And then it closes on its own, PS, I am putting the right email and password.

sidenote: is there anyway I can change my location after I selected one?
Thanks everyone

**Comment by maliqoye** [comment]
check your quotes.. 

RIGHT
PtcUsername: "blablabla"

**Comment by fumitu** [comment]
I have a similar problem! After the update it says: "<INFO> Logging in using Google" and then nothing happens

**Comment by maliqoye** [comment]
it happened when server is busy, close your bot and re-run it .. my bot 3hours running with no problem.

**Comment by fumitu** [comment]
I did it many times but it does not work

**Comment by Purrygon** [comment]
same here, it doesnt work...

**Comment by maliqoye** [comment]
put your auth.json and config.json here .. use http://www.spaste.com/site/index

**Comment by nfettinger** [comment]
Configuration issues belong in discord chat.
