### ISSUE TITLE
sniping problem in v0.8.0

### ISSUE THREAD

**Issue by looooozeeeeer** [NECROBOTIO/NecroBot#3783]
currently running pogolocationfeeder v0.1.5 with untouched setting.

the sniper keep repeating snipes from the same line it first snipe, like :

sniping dratini with 100 iv at x1x, y1y, nothing found at sniping offset
farm pokestop
sniping dratini with 100 iv at x1x, y1y, nothing found at sniping offset
sniping zubat with 101 iv at x2x, y2y, nothing found at sniping offset
farm pokestop
sniping dratini with 100 iv at x1x, y1y, nothing found at sniping offset
sniping zubat with 101 iv at x2x, y2y, nothing found at sniping offset
sniping doduo with 102 iv at x3x, y3y, nothing found at sniping offset
farm pokestop
sniping dratini with 100 iv at x1x, y1y, nothing found at sniping offset
sniping zubat with 101 iv at x2x, y2y, nothing found at sniping offset
sniping doduo with 102 iv at x3x, y3y, nothing found at sniping offset
sniping venonat with 999 iv at...

and so on, it always start with the very first snipe

i noticed that "usesnipelocationonlineserver" is missing, so i tried to add the line and set it to "true", but the line disappear as soon as i run the exe. nothing changed. keep sniping dratini. what did i do wrong? sorry for my bad english. still learning

**Comment by necr-0** [comment]
The devs are aware.
It'll be fixed in the next update. Refer to #announcements in the Discord chat for details.

**Comment by looooozeeeeer** [comment]
ah. thanks.

will wait for the next update,
much appreciated m8
