### ISSUE TITLE
Autoupdating

### ISSUE THREAD

**Issue by tonakriz** [NECROBOTIO/NecroBot#3786]
Hi,
what about separating updater and client? Just make a simple autoupdater checking github every minute or 5 and if there is an update it will kill client and start downloading, extracting new and replacing old files. I think that this would be more stable then actual sollution.

Sorry for my bad english, also I am right now typing on my phone.

**Comment by maliqoye** [comment]
did you mean launcher updater before run bot client ? 

that's a good idea,

**Comment by tonakriz** [comment]
Exactly. Just a small simple app periodically cgecking github for updates, i  case of update kill client and update. And restart client every like 15 minutes to prevent being stuck on some error for hours.

**Comment by maliqoye** [comment]
maybe need to wait, i think developer was thinking about it but no time to make it.
you should change your autoUpdate.. set it as false.
my bot running 3hours without being stuck and got an error ...

**Comment by nfettinger** [comment]
User interaction to verify config on every updated is something we will not drop.
