### ISSUE TITLE
Google Account Action Required

### ISSUE THREAD

**Issue by heodi** [NECROBOTIO/NecroBot#3789]
When my necrobot keeps running, my android device keeps popping up the notification about "Account Action Required" and I have to input the password of the google account.
Is this issue normal? Does anyone also counter the same issue?

**Comment by maliqoye** [comment]
not normal, that's the problem with your google sync on your phone ..

this article could help you, http://android.stackexchange.com/questions/136320/account-action-required-multiple-gmail-accounts

**Comment by GreatApo** [comment]
Happened to me yesterday.
Connect through phone and you will have to re-enter your password. Fixed.

**Comment by heodi** [comment]
Hello @GreatApo 

> Happened to me yesterday.
Connect through phone and you will have to re-enter your password. Fixed.

What is meaning of "Connect through phone" ? I have re-enter the password several times. How do you fix it?

**Comment by looooozeeeeer** [comment]
bumping this cz i had the same problem. need help

**Comment by GreatApo** [comment]
I opened the Pokemon apk in my phone, and when i chose to connect with my google account, i was asked to verify my account re-entering my password. Then i was normaly logged in pokemon go. After a while, i opened the bot from PC and i was up and running :)

**Comment by heodi** [comment]
I got this notification again after 2 hours from my last re-entering password. It seems the issue will happen again....
