### ISSUE TITLE
pokemon isn't transferred

### ISSUE THREAD

**Issue by GODSWIND1** [NECROBOTIO/NecroBot#3790]
In config.json, in PokemonTransferFilter, I have this
"Rattata": {
      "KeepMinCp": 370,
      "KeepMinLvl": 4,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
but It maintains Rattatas of 45cp 50 ... and Iv are less than 50%
any advice?
ty

**Comment by dmkovsky** [comment]
line 95/96  "TransferWeakPokemon": false, set it on true and check results

**Comment by STCOZT** [comment]
It migh also be because of;
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
If you change "KeepPokemonsThatCanEvolve": true, to false it might transfer it, as you have enough candies to evolve those pokemons its not transferring them.

**Comment by erikeleria** [comment]
"KeepMinDuplicatePokemon": 1, change to 0 .. it will not keep any below KeepMin threshold. I also raised an issue about this but it's not a coding bug.

**Comment by GODSWIND1** [comment]
i try first your solution erikeleria, i will report later

**Comment by GODSWIND1** [comment]
erikeleria your solution doesn't work, i put keepminduplicatepokemon to 0 in pokemontransferfilter and the other outside
