### ISSUE TITLE
it's doesnt work ,softban and no usable pokestop

### ISSUE THREAD

**Issue by daniel87kk** [NECROBOTIO/NecroBot#3792]
it's doesnt work ,softban and no usable pokestop , 
1 bot , 31km/h , humanwalking false , snipe false still not working ???
Pffttt

**Comment by GreatApo** [comment]
How many accounts are connected at the same network? The max is 2-3...

**Comment by daniel87kk** [comment]
1 account

**Comment by 666dsa666** [comment]
I think there is a bug with humanwalking false where the bot teleport way too fast and get softbanned.

**Comment by maliqoye** [comment]
my config works fine .. 

  "DisableHumanWalking": false,
  "DefaultLatitude": 37.808966,
  "DefaultLongitude": -122.410153,
  "WalkingSpeedInKilometerPerHour": 150.0,

**Comment by 666dsa666** [comment]
"WalkingSpeedInKilometerPerHour": 150.0,

Wow, don't you get any softban with that ?

**Comment by daniel87kk** [comment]
hahaha 150 like a jet

**Comment by GreatApo** [comment]
Change that to 20 or sth similar :P

**Comment by maliqoye** [comment]
@666dsa666 no, i'm not .. just work fine for 8hours

@daniel87kk lol, not catch the pokemon but crash the pokemon with my speed haha
