### ISSUE TITLE
GPX Tracking Wiki

### ISSUE THREAD

**Issue by KOTR2003** [NECROBOTIO/NecroBot#3793]
Missing the link in step 1 to https://wtracks.appspot.com/ on https://github.com/NECROBOTIO/NecroBot/wiki/GPX-Pathing-Setup

Right now it says:
> 1. Go to .
> 2. Create your path by right clicking on the...

**Comment by frager45** [comment]
after?

**Comment by KOTR2003** [comment]
Joking me right?

**Comment by LordDeimos** [comment]
They removed since the link is always in overquota because of pokemon go.

**Comment by KOTR2003** [comment]
Whats the purpose of the page then? Anyone with any common sense can figure out where they are trying to send you to, open the image from the following step and read.
