### ISSUE TITLE
egg incubation wont work

### ISSUE THREAD

**Issue by sysandrew** [NECROBOTIO/NecroBot#3797]
egg wont work

**Comment by 666dsa666** [comment]
What doesn't work ?

I had some error when putting the egg in the incubator but it was probably a mistake as the egg was definitely in the incubator.

Otherwise hatching egg works wonderfully.

**Comment by PassiveModding** [comment]
great explanation fo your problem, 10/10

**Comment by sysandrew** [comment]
it works now.. my bad,, tnx
