### ISSUE TITLE
Sniping not working

### ISSUE THREAD

**Issue by Shin88ryu** [NECROBOTIO/NecroBot#3798]
No sniping text appear and PoGoFeeder is always empty. Alway worked yesterday with 0.7.8

That's my setup for snipe.

  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 10,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by necr-0** [comment]
> PoGoFeeder is always empty

Error with PogoFeeder, Not NecroBot.
Did you update Pogo?

**Comment by Shin88ryu** [comment]
`Error with PogoFeeder, Not NecroBot.
Did you update Pogo?`

Yep. Latest is 0.1.5, right?

**Comment by necr-0** [comment]
@Shin88ryu, 

Yep, that's the latest.
Change the settings on Pogo to reflect this:

`{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UsePokeSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": null,
  "RemoveAfter": 15,
  "ShowLimit": 30
}`

Basically, ensure that _UsePokeSnipers_ is set to _true_.

**Comment by Shin88ryu** [comment]
Done, but nothing chaanged

**Comment by Tupilak** [comment]
If you use Pogo on windows 7 then there is a problem. You need windows 10 for it to work.

**Comment by Shin88ryu** [comment]
`If you use Pogo on windows 7 then there is a problem. You need windows 10 for it to work.`

I'm on Win 10. Yesterday PoGoFeeder works. Now, it don't show anything
