### ISSUE TITLE
Its not work?pls help

### ISSUE THREAD

**Issue by fadilomu** [NECROBOTIO/NecroBot#3799]
![not work](https://cloud.githubusercontent.com/assets/20926792/17515544/49b05192-5e63-11e6-9ca3-9a19e77cf6e9.png)

**Comment by fadilomu** [comment]
any sugest what i must to do?

**Comment by PassiveModding** [comment]
you probably have an ip soft ban

**Comment by Shin88ryu** [comment]
Close all bot. Wait 5 min. Then open max 2 bots

**Comment by fadilomu** [comment]
thanks sensei !! arigato gozaimasu
