### ISSUE TITLE
Incorrect data reported through Telegram

### ISSUE THREAD

**Issue by GrimDemon** [NECROBOTIO/NecroBot#3800]
Data reported:
> ----- LVL 26 | nkhgvj ----- 
>  Experience: 1038715/1100000 
>  Pokemons caught: 2251 
>  Pokemons deployed: 0 
>  Pokestops visited: 5563 
>  Eggs hatched: 5563 
>  Pokemons envolved: 42 
>  Pokedex entries: 387 
>  KM walked: 78

Problematic line of code in Translations.cs:
```
new KeyValuePair<TranslationString, string>(TranslationString.ProfileStatsTemplateString,
"----- LVL {0} | {1} ----- \n Experience: {2}/{3} \n Pokemons caught: {4} \n Pokemons deployed: {5} \n Pokestops visited: {6} \n Eggs hatched: {6} \n Pokemons envolved: {7} \n Pokedex entries: {8} \n KM walked: {9}"),
```

As You can see the data of Pokestops visited is reported twice and the rest of report is a mess. Also there i a spelling error. I don't know what type of data is returned from ProfileStatsTemplateString so I will not make a pull request.

**Comment by Plotin** [comment]
#3754 fixes this, when accepted

**Comment by GrimDemon** [comment]
Thank You!

**Comment by gigi944** [comment]
How do I configure Telegram with this new update? There's nowhere explained ç___ç

**Comment by GrimDemon** [comment]
https://github.com/NecronomiconCoding/Necrobot/wiki/Telegram

**Comment by Plotin** [comment]
@gigi944 The fix is not in the bot yet. The maintainers need to accept the pull request and build another release first.
