### ISSUE TITLE
Is it ok to open 4 bots on 2 computers with the same internet connection?

### ISSUE THREAD

**Issue by Littlem0nk3y** [NECROBOTIO/NecroBot#3802]
Is it ok to open 4 bots on 2 computers with the same internet connection?

**Comment by PassiveModding** [comment]
no run a vpn on one of the computers at least

**Comment by auth100488** [comment]
imagine if they were to ban all people playing at say .... a mcdonalds ... or on the free city wifi ... so yeah, its up to you ... but i'm using 6 bots all on the same ip... no big deal yet!

**Comment by Littlem0nk3y** [comment]
i tried but too many problems with the softban.. Dont you have the same prob?

**Comment by auth100488** [comment]
the softbans (for me) are very rare ... maybe its because of an external factor ... i can't tell ... what i CAN tell is that cellphones IP are SHARED ... therefore ... if they were to soft bans people based on IP total connections only .. that would make no sense at all. They, however, could identify devices using sessions id and or other stuff.

**Comment by Littlem0nk3y** [comment]
Auth100488, is it ok if i ask for the necrobot config from you?

**Comment by burbag** [comment]
Well, I'm botting with 4 acc and no have a problem yesterday but for a reason that I dont know, the bot keeps spinning to avoid the softban, I have the "Human Walking" to false but it keeps spinning.
Maybe Niantics improves their ban system ??

**Comment by GreatApo** [comment]
Some have problems with 3 some with 4 and others with 10...
One the bots and if you get a soft ban, wait a while and open less later. Most times 2-3 bots is the limit.

**Comment by auth100488** [comment]
Well all i changed was enabling humanlike walking... all 6 bots spawns at
close to each other .. roaming in 500meters area.. and changed the walking
speed to 8km/h (oh and that keepduplicate thing to 1)

**Comment by Littlem0nk3y** [comment]
Thanks, auth100488
