### ISSUE TITLE
Request: Select incubator

### ISSUE THREAD

**Issue by MushroomMaker** [NECROBOTIO/NecroBot#3805]
Hi, dont really know if its possible or not but would be awesome to be able to tell the bot which incubator its allowed to use infinite / disposable or maybe both depending on the botting players preference, this would be nice to have to those who bot to get a good level etc but at the same time want to hang out with friends playing pokemon go going around together hatching eggs, catching etc without worrying about the bot uses all incubators on 2km eggs

**Comment by nfettinger** [comment]
Duplicate issue.
