### ISSUE TITLE
Spinning issue

### ISSUE THREAD

**Issue by burbag** [NECROBOTIO/NecroBot#3809]
Hi Necrobot and thank you for your amazing work!

Well, I'm botting with 4 acc and no have a problem yesterday but  today for a reason that I dont know, the bot keeps spinning to avoid the softban, I have the "Human Walking" to false but it keeps spinning.
Once the spinning is done, the bot said that no pokestop is found around and needed to increase the radius range.
Maybe Niantics improves their ban system ??

**Comment by blackuGT** [comment]
Use max 2 acc
