### ISSUE TITLE
Extended Pokemon bag - StorageUsagePercentage

### ISSUE THREAD

**Issue by czyndzel** [NECROBOTIO/NecroBot#3810]
Hello,

I have extended pokemon bag to 400, but I can't use it to collect more pokemons to evolve with enough candy, because when i set "EvolveKeptPokemonsAtStorageUsagePercentage" to 100% there are only 350 pokemons and 114% doesn't work. How to fix that to start evolving when I collect for example 390 pokemons?

Best regards,
Sebastian

**Comment by nfettinger** [comment]
Duplicate issue.
