### ISSUE TITLE
Transfering all pokemons

### ISSUE THREAD

**Issue by mtronca** [NECROBOTIO/NecroBot#3812]
my bot is transfering all my pokemons, regardless CP or IV.

**Comment by Sylencer90** [comment]
TransferWeakPokemon= true? set it to false

**Comment by conso98** [comment]
same problem with this configuration

 "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by nfettinger** [comment]
Duplicate #3338
