### ISSUE TITLE
saying "there's no pokestop's in my area, is your maximum distance too small?" HELLPPP ME PLEAASSEEEEE

### ISSUE THREAD

**Issue by iHarrisonXII** [NECROBOTIO/NecroBot#3814]

**Comment by Profetorum** [comment]
#3815 duplicate.
And use search, this issue is everywhere

**Comment by RiPPERD** [comment]
just delete the bot and redownload the newer version

**Comment by XenoEktika** [comment]
If you run multiple bots this will happen, you need to set up proxies if you run multiple bots

**Comment by letuananh035** [comment]
UseProxy config ???? i don'nt know edit
