### ISSUE TITLE
Request: Recycle Items based on % instead of absolute numbers

### ISSUE THREAD

**Issue by kilolum** [NECROBOTIO/NecroBot#3818]
Hey I am neither developer nor a native english speaker so this request is probably not explained perfectly as i image this but I hope someone understands :D 

 I would think that some people sometimes upgrade their bags or intend to in the future and if we were able to set % valus for each item category we would not have to adjust those values in the future.

**old**:
```
  "TotalAmountOfPokeballsToKeep": 220,
  "TotalAmountOfPotionsToKeep": 90,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,

```

I think we would have to substract the lures, incents and lucky eggs from the bag capacity and then calculate the absolute numbers with the set percentages. 

**new ex:**
```
"BallsPercentageToKeep": 50,
"PotionsPercentageToKeep": 15,
"RevivesPercentageToKeep": 15,
"BerriesPercentageToKeep": 20
```

we would probably need another value like 

`"RecycleToPercentage": 85,`

Then everytime "RecycleInventoryAtUsagePercentage": 95.0, triggers the bot will calculate how many items should be deleted in order to have 85% filled bags with the shares that we set.

**Example:**

> 450 bag slots
> -3 lures
> -5 incents
> -3 lucky eggs
> ______________
> ->439 slots for balls, potions, revives and berries
> 
> 439*RecycleInventoryAtUsagePercentage/100 = 417,5
> 
> when those 417 items are reached the bot should recycle to for example 85% which equals 373,15
> balls to keep : 373,15 x BallsPercentageToKeep/100 = **186**,575
> potions to keep: 373,15 x PotionsPercentageToKeep/100 = **55**,9725
> revives to keep: 373,15 x RevivesPercentageToKeep/100 = **55**,9725
> berries to keep: 373,15 x BerriesPercentageToKeep/100 = **74**,63
> 

If you have any questions or ideas for improvement feel free to comment.

**Comment by nfettinger** [comment]
Duplicate issue.
