### ISSUE TITLE
Issue with eggs hatching

### ISSUE THREAD

**Issue by Usernameused** [NECROBOTIO/NecroBot#3819]
Sometimes the bot doesn't notify me what pokemon came out from the egg and directly puts the next in the incubator. It happens only to me?

**Comment by 666dsa666** [comment]
No, it happens to me too, not a big problem, but still it shouldn't happen.

**Comment by Usernameused** [comment]
Yes, not a big problem, but when is a 10km egg, I'm too much curious to know what came out.

**Comment by nfettinger** [comment]
Duplicate issue.
