### ISSUE TITLE
Sending back evolved pokemons

### ISSUE THREAD

**Issue by kaszabgc** [NECROBOTIO/NecroBot#3823]
Is there any way to force my bot to send freshly evolved worse pokemons?
I've set my bot to evolve pokemons like zubats and ratatas but he doesnt send them to the profesor even if they are clearly worse than others. Its not a big deal but after botting for like 10 hrs its a big mess in inventory.

**Comment by Unentertained** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Config#pokemontransferfilter-list
Make another entry for Golbat and Raticate. I just made an entry for nearly every pokemon and it cleans up itself.
