### ISSUE TITLE
If there isn't a Pokestop...

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#3824]
will the bot still wander around in the radius you've given it. I'm trying to farm a certain pokemon in a known zone. but not sure it's working.

**Comment by phoojunior** [comment]
same

**Comment by DariusFoxy** [comment]
well, after letting the bot run a while, the incubator has been ticking down and i found a dratini and a charmander.. so it seems to be working. but it spams the "no pokestops" like crazy.

**Comment by MetaExtreme** [comment]
just use the sniping option necrobot has
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

first start pokezz and then the necrobot and it will work

these are my settings
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,

here are the pokemons listed that will be caught during snipe is active
you can change the pokemons if you want

"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 0,
        "Longitude": 0
      },
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },

**Comment by DariusFoxy** [comment]
ok, i'll give it a try, but i'm stuck already. on the download page, what do i get, the CLI or the GUI or both ??
