### ISSUE TITLE
Issue with sniping, keep noticing "Did not find a Pokemon within the SnipingScanOffset!"

### ISSUE THREAD

**Issue by zhiyilv** [NECROBOTIO/NecroBot#3827]
The bot kept noticing "Did not find a Pokemon within the SnipingScanOffset!"
I think the problem comes from **not deleting previous unavailable** coordinates and the bot will thus loop all logged coordinates again and again.

Hope you guys fix this. Thanks!

**Comment by phytomorphogenesis** [comment]
**same problem**

**Comment by bassemmixez** [comment]
same here

**Comment by muchlish90** [comment]
same problem

**Comment by nunyaau** [comment]
Same
![screenshot_2](https://cloud.githubusercontent.com/assets/18028629/17518198/3fb6703c-5e8a-11e6-9a44-4727a56f7300.jpg)

**Comment by nunyaau** [comment]
Same
` "UseWebsocket": true,
  "WebSocketPort": 14251,

  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 1500,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,` 
![screenshot_2](https://cloud.githubusercontent.com/assets/18028629/17518302/c063d74c-5e8a-11e6-9900-59558763706a.jpg)

**Comment by elmaarmut** [comment]
Same, but I doubt it has to do with the Necrobot. Those coordinates are probably wrong.

**Comment by zawhie** [comment]
Disable Pokesnipers seems to be a workaround for now.
