### ISSUE TITLE
Telegram Stats: (German)

### ISSUE THREAD

**Issue by infslash** [NECROBOTIO/NecroBot#3828]
Erfahrungspunkte: 9232047/9500000 
 Pokemons gefangen: 24605 
 Pokemons verschickt: 47 
 Pokestops besucht: 38463 
 Eier geschlüpft: 38463 
 Pokemons entwickelt: 175 
 Pokedex Einträge: 3659 
 KM gelaufen: 142

The Stats are incorrect... maybe variable misspelling?

**Comment by Wolved** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/3754 should fix it

**Comment by infslash** [comment]
Thanks a lot, didn't check it cause I thought it was only a language problem and not many germans are in here :D

**Comment by Marsinator** [comment]
actually there are, they just use english :p
