### ISSUE TITLE
softban for no reason, does not lift.

### ISSUE THREAD

**Issue by Ptolemaio** [NECROBOTIO/NecroBot#3829]
As you can see by the screenshot, my location did not even change, just suddenly ban. Also, softban does not relent after 45. I think niantic found a way to track the bot.
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/20775479/17517171/24dad2aa-5e10-11e6-83e2-a1dfcae2b654.png">
<img width="960" alt="untitled1" src="https://cloud.githubusercontent.com/assets/20775479/17517176/2b75f4f0-5e10-11e6-99ba-f3c23506544c.png">

also config file for reference
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/408997/config.txt)

**Comment by Tomabl** [comment]
same here

**Comment by zybertronix** [comment]
what version are you using ?

**Comment by Ptolemaio** [comment]
version 0.8.0

**Comment by zybertronix** [comment]
try the configuration from 0.7.7 then copy config and replace the one from 0.7.8

**Comment by NecroBoTPhile** [comment]
What i observerd was if u using more than 2 accounts u start getting that msg,
i own 3 accounts ... which i used to bot ... now when i start the third all the bots gets softbanned 
maybe cuz of update or maybe its a gmail policy (somone mentioned on other thread)

**Comment by Ptolemaio** [comment]
I only had mine and my wife's account running, that's all. We both got softbanned at exactly the same time.

**Comment by theloser** [comment]
As stated before: two bots per IP address seem to be working, 3 or more will get you in trouble (at least softban). Just: don't!

**Comment by Ptolemaio** [comment]
As stated before: I was only using two.

**Comment by Ptolemaio** [comment]
And we got softbanned.

**Comment by burntable** [comment]
I get (ip)softbanned randomly when using only 2 bots over one ip.
Yesterday I was able to run 3 without any problems.

**Comment by theloser** [comment]
Did you or your wife log in with your phone at the same time (while your phone was on wifi)?

**Comment by LostSoulFly** [comment]
Looks likely that it's caused by teleportation related to the HumanWalking system. There is a commit that sets it disabled by default.

**Comment by zybertronix** [comment]
so having 3 or more bot accounts running getting softbanned. is there anyway we can proxy this thing ? it only happens today this morning. I guess all the employees in niantic are all in and working lol! last night it was fine.

**Comment by theloser** [comment]
@zybertronix Sure, just take a look at your auth.json, there you can set a proxy server. Just set a maximum of two bots per proxy server and you are fine to run hundreds of bots in parallel...

**Comment by fence1247** [comment]
Does the PoGoLocationFeeder count as a bot? I can't run more than

**Comment by theloser** [comment]
@fence1247 PogoLocationFeeder does not login to PGO, so is does NOT count as a bot.
