### ISSUE TITLE
Anti Virus Blocking Launch

### ISSUE THREAD

**Issue by YakumoSaitou** [NECROBOTIO/NecroBot#3830]
My Anti virus refuses to let the program launch?
Its only happend on this version (0.8) 0.7.x all worked fine without any issue.
Heres the reason my anti virus removes it:
09.08.2016 14.05.07;Malicious program deleted;C:\Users\NAME\Desktop\NAME\Custom Necros\NecroBot.exe;C:\Users\Administrator\Desktop\Rom Hack\Custom Necros\NecroBot.exe;UDS:DangerousObject.Multi.Generic;NecroBot Client for Pokémon GO;C:\Users\NAME\Desktop\NAME\Custom Necros\NecroBot.exe

**Comment by kanguwais** [comment]
Me too. My KIS 2016 detect it as malware and delete it.

**Comment by dansali** [comment]
They really added necrobot to their anti virus definitions.... really....
"UDS:DangerousObject.Multi.Generic;NecroBot Client for Pokémon GO"

**Comment by MetaExtreme** [comment]
ahhhh all our accounts got scammed ^^

**Comment by PenjagaHati** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20869593/17517477/cfeab496-5e6d-11e6-84c2-df6147dc2f6c.jpg)
:o

**Comment by ifbatmanwasreal** [comment]
@PenjagaHati

What the full message. Trojan.Win32.???

**Comment by sounddanezzboiz** [comment]
same with me, but i check file in virustotal.com is clean and only kis said this file was mailicius

**Comment by ifbatmanwasreal** [comment]
https://forum.kaspersky.com/index.php?showtopic=317836

Seems like false positive to me. Virustotal shows no problems.

**Comment by DizzyDaft** [comment]
yhe finally my KIS updated and bam 
![capture2](https://cloud.githubusercontent.com/assets/20776738/17518095/4dde3ace-5e3e-11e6-88ff-fec5c524e05c.JPG)
