### ISSUE TITLE
.exe crash by startup when I set telegram on true with API key

### ISSUE THREAD

**Issue by MisterWanted** [NECROBOTIO/NecroBot#3835]
NecroBot is starting up [                                              ]  100%
[15:08:19] (INFO) Exceptiion caught, writing LogBuffer.

Onverwerkte uitzondering: System.AggregateException: Er zijn één of meer fouten opgetreden. ---> Telegram.Bot.Exceptions.ApiRequestException: Invalid token ---> System.Net.Http.HttpRequestException: Statuscode van antwoord geeft geen succes aan: 401 (Unauthorized).
   bij System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bij Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij System.Threading.Tasks.Task`1.get_Result()
   bij PoGo.NecroBot.Logic.Service.TelegramService..ctor(String apiKey, ISession session) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Service\TelegramService.cs:regel 29
   bij PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.CLI\Program.cs:regel 160
[15:08:19] (UPDATE) Perfect! You already have the newest Version 0.8.0
[15:08:19] (INFO) Logging in using Google

**Comment by Wolved** [comment]
well pretty much as it stated : "Invalid token " double check your token

**Comment by aytac01** [comment]
you have to put the token like this   "TelegramAPIKey": "199999999:XXXXXXXXXXXXXXXXXX",
