### ISSUE TITLE
Crashes when adding new Pokemon to evolve

### ISSUE THREAD

**Issue by Zellerich** [NECROBOTIO/NecroBot#3838]
I typed in all the Pokemon i wanted to evolve in the config but the bot just crashes.
Maybe you could put every Pokemon that can evolve there by default.

**Comment by burntable** [comment]
probably forgot a ","
or you misspelled one of the names.

**Comment by theloser** [comment]
Post your config, it has some errors in it for sure.

**Comment by Zellerich** [comment]
I think the issue were Nidoran male and female. Don´t know how to write those in the config
