### ISSUE TITLE
autosnipe not work in necro

### ISSUE THREAD

**Issue by rudykevin88** [NECROBOTIO/NecroBot#3844]
nothing happen in necro core when start ...just catch around pokemon and pokestop...sniping not appear...my necro latest 8.0..please check and fix it and update ASAP..thanks very much...sory for my bad english..^^

**Comment by MetaExtreme** [comment]
Did you use PokeZZ?

**Comment by nico5721** [comment]
like this?

"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 0,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,

**Comment by rudykevin88** [comment]
my setting is like this:

"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 50,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.002,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,

**Comment by rudykevin88** [comment]
"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 50,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.002,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 50,
  "MaxTravelDistanceInMeters": 3000,
