### ISSUE TITLE
Bot transfering pokemons in the middle of catching pokemon

### ISSUE THREAD

**Issue by Wrakor** [NECROBOTIO/NecroBot#3849]
As you can see in this screenshot, a transfer is made in between throws at the same pokemon.

![image](https://cloud.githubusercontent.com/assets/2973191/17518639/a56dba60-5e40-11e6-9329-fef2f2303cb7.png)

This can make the bot easy to detect, since a normal player cannot do such a thing.
(it happens more with "EnableHumanizedThrows", since it often requires more than 1 throw to catch a pokmeon).

**Comment by GreatApo** [comment]
I have seen that too, it can be enchanted.

**Comment by burntable** [comment]
"TransferDuplicatePokemonOnCapture": false,

**Comment by Wrakor** [comment]
burntable, that is one way to temporarily fix it, yes. :)

**Comment by nfettinger** [comment]
Duplicate issue.
