### ISSUE TITLE
Several Reports of Sniping Spam |

### ISSUE THREAD

**Issue by ColeB27** [NECROBOTIO/NecroBot#3856]
Hey guys, I was just talking to several people in the Discord support chat, and they all seem to have the same problems, it's either getting IPBanned, or the Sniping Spam (as I like to call it)

Here is the issue:
using this config for the past 2-3 hrs , and suddenly it starts spamming this instead of looting pokestops  and catching pokemon. https://gyazo.com/ae35ff4bc1f7fcba0dc718c906d150e0

**Comment by nico5721** [comment]
for some people doesnt work at all on 0.8.0 :/
