### ISSUE TITLE
[SUGGESTION] Transfer list that ignores "KeepMinDuplicatePokemon"

### ISSUE THREAD

**Issue by tiny1980** [NECROBOTIO/NecroBot#3859]
I have keep duplicates set to 2, although it keeps stuff like Gobats and such, it would be nice to have another list we can add to to transfer no matter what.  Right now it's keeping 2 Metapods, kakunas, pidgeottos (actually lots of these), will have to figure out why...  lol...

anyways, just something we can add to to automatically transfer certain pokemon that ignores all constraints.  I really have no interest in keeping a 1600 CP, 99% IV Golbat!  lol!

**Comment by jsun102** [comment]
i think a more precise filter can be applied with the PokemonNotToTransfer list and setting minduplicates to 0. I'm only lvl28 now but I think it would be the best method when it becomes a slow grind

**Comment by nfettinger** [comment]
Duplicate #3338
