### ISSUE TITLE
"NecroBot Client for Pokemon GO has stopped working" Help

### ISSUE THREAD

**Issue by Flesxueuendi** [NECROBOTIO/NecroBot#3860]
So I try to launch Necrobot and this comes up, please help me resolve
![image](https://cloud.githubusercontent.com/assets/20928992/17519223/ef75ba02-5e42-11e6-81f4-d381ba73dc46.png)

**Comment by Rick058** [comment]
Does it stop working every time you start Necrobot.exe?
In that case, please make a new screenshot with also the top of the error.
From my own experiences it is most likely a small mistake in one of your config files, ex. missing a , or "

**Comment by Flesxueuendi** [comment]
@Rick058 This has been happening for the last 30 mins, it happens every time I try to launch. This is the entire error 
![image](https://cloud.githubusercontent.com/assets/20928992/17519466/f35f0e10-5e43-11e6-96e4-cec29312499c.png)

**Comment by tiny1980** [comment]
Make sure you have no typos in any of your lists of pokemon...  or that you didn't accidentally put "treu" (typo) in any of the constraint feilds.

I had a similar error a few versions ago, and it was a typo I made when changing one of the fields.

**Comment by Rick058** [comment]
Pretty sure there is still a small part missing from the top which is the line that says where the mistake is located, most likely a small mistake/typo in your configuration file.

**Comment by Flesxueuendi** [comment]
@tiny1980 @Rick058 Necrobot was running last night fine. Since then I have not changed the config or auth files :/

**Comment by Flesxueuendi** [comment]
@tiny1980 @Rick058 Dont worry, Rick you were right. My brother must of tried to change the bot to him, he misspelt Pidgeotto
