### ISSUE TITLE
Maximum distance to small?!

### ISSUE THREAD

**Issue by sagemkiller** [NECROBOTIO/NecroBot#3862]
whenever I start up the bot it continues to say (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small? how do I fix this and at the top it continues to say "not realistic traveling" how do I fix these issues please help!

**Comment by ifbatmanwasreal** [comment]
It's not letting you do anything because you used unrealistic travel settings. You are temporarily soft banned. Give it a bit. Or get to a pokestop and spin it til you're unbanned.

**Comment by Flesxueuendi** [comment]
This happened to me, I'm not sure if 'this' fixed the problem but its a try
  "MaxSpawnLocationOffset": (increase number),
I don't know if it will work though. Good luck man

**Comment by sagemkiller** [comment]
I changed it and it no longer says the not realistic traveling part but I still can not find pokestops within my area how do I fix that??? @ifbatmanwasreal
