### ISSUE TITLE
Kaspersky found Trojan ?!

### ISSUE THREAD

**Issue by K1ngM4st3r** [NECROBOTIO/NecroBot#3866]
Since 0.8.0 Kaspersky finds a Trjona in the .zip.
Did not happen on 0.7.8.

**Comment by ifbatmanwasreal** [comment]
It's a false positive.

https://forum.kaspersky.com/index.php?showtopic=317836&st=0&p=2371731&#entry2371731

**Comment by pkmgogogo** [comment]
but my Kaspersky go to delete 0.8.0.
your post said the file that is a false detection. it doesn't said PDM:Trojan.Win32.Bazon.a to a false detection

**Comment by nfettinger** [comment]
This is due to the unkown6 calculation
