### ISSUE TITLE
Is there any GUI for Necrobot?

### ISSUE THREAD

**Issue by iTayGNR** [NECROBOTIO/NecroBot#3867]
If anyone knows about one, I'd be happy to use one

**Comment by theloser** [comment]
https://github.com/nicoschmitt/necrobotvisualizer

**Comment by rootm0s** [comment]
I think there's future plans for GUI though

**Comment by iTayGNR** [comment]
@rootm0s i'm looking forward.
@theloser thanks! what's ia32?

**Comment by theloser** [comment]
@iTayGNR http://lmgtfy.com/?q=ia32

**Comment by iTayGNR** [comment]
@theloser lolol thanks. I know it by the name 32bit/x86
