### ISSUE TITLE
')' or operator expected (at index 212)

### ISSUE THREAD

**Issue by WideOcean** [NECROBOTIO/NecroBot#3870]
Same as issue #3240  which was already closed without proper explanation.

I am using version 0.7.8.
Necro was working fine. Then I modified the PokemonTransferFilter in the config file and got this error since.
What I did was changing the CP of some, setting the "UseKeepMinLvl" to true and setting the "KeepMinOperator" of some to "and".

Here my config file: (Are there any syntax errors?)

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "StartupWelcomeDelay": false,
  "AmountOfPokemonToDisplayOnStart": 10,
  "ShowPokeballCountsBeforeRecycle": true,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1700.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 35.633511709084274,
  "DefaultLongitude": 139.87992525100708,
  "WalkingSpeedInKilometerPerHour": 450.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 500,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1900,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 20,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 50,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1200,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeOnlineLocationServer": true,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 50,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 4000,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 50,
  "TotalAmountOfRevivesToKeep": 50,
  "TotalAmountOfBerriesToKeep": 100,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "WebSocketPort": 14251,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2000,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2000,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by NecroBoTPhile** [comment]
Just change it to orignal script,if u want a particular move set , i suggest u reduce ur min cp level,
once u get dumped with some pokemons just manually go through some of the pokemons and add them favorites ... then edit the script back to normal again

**Comment by NecroBoTPhile** [comment]
Why u edit KEEPMINLVL as long as u edit CP its good dont filter poekmons on LVL u might get low IV pokemon .... just a suggestion if dont complicate this shit ..keep the filters simple unless u know what ur doing

**Comment by WideOcean** [comment]
I want to use keepMinLevel in the TransferFilter because the default values was either CP or IV with keepMinOperator: "or". Let's say you have CP: 1900 and IV: 95 and keepMinOperator: "or". That would mean that the bot keeps all low-level Pokemon if they have IV 95.
A Pokemon with Level 4 (for example) even with IV 95 is useless.
That's why I want to use keepMinLevel.

**Comment by nfettinger** [comment]
Duplicate issue

**Comment by WideOcean** [comment]
Alright two duplicate closed issues both with no real solution...*thumbs up*
