### ISSUE TITLE
Softban PERMANENTLY

### ISSUE THREAD

**Issue by F4lc0n88** [NECROBOTIO/NecroBot#3871]
Hello, every once in a while (which use to be every minute or even less) my bot jsut start saying "possible soft ban" and start trying to "remove the ban" but the truth is that after 5-15 tries he just stop and keep on going, this didn't happen yesterday and just started with the new update, any advice? thanks

**Comment by deduijk** [comment]
There is an known issue in 0.8.0  there's a lot of topics on this already.

**Comment by zybertronix** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3872

**Comment by theloser** [comment]
Are you using more than 2 bots? --> Softban.

And PLEASE use the search function before opening a new issue.

**Comment by tiny1980** [comment]
"DisableHumanWalking": false,
