### ISSUE TITLE
SoftBanned Related Issue

### ISSUE THREAD

**Issue by zybertronix** [NECROBOTIO/NecroBot#3872]
It seems running more than 3 accounts at the same time with the same IP will get your account to be softbanneded. anyway we can proxy each accounts? or any other ways to do this ? it seems niantic is working very hard to get all the bots out. :(

**Comment by theloser** [comment]
More than two bots with same IP address --> ban.

And PLEASE use the search function before opening a new issue.

**Comment by F4lc0n88** [comment]
I am having that problem and I am only using 1 bot :S

**Comment by zybertronix** [comment]
is there any other way to proxy each bot so it wont detect same ip address ?

**Comment by theloser** [comment]
@F4lc0n88 You are teleporting a lot or using a high "walking speed" I guess? Also softban.
@zybertronix Sure. Just take a look at your auth.json, there you can edit proxy server settings.

**Comment by F4lc0n88** [comment]
@theloser I didn't change anything in the bot except for the evolve list, so I don't think so, plus, the incubator works fine, then i don't think it is a problem of speed :s

**Comment by zybertronix** [comment]
like @theloser says it was having 2 or more bot account running on the same ip why we are getting softbanned

**Comment by theloser** [comment]
@F4lc0n88 Did you login to PGO using the app on your phone while your bot was running?

**Comment by WuddyMarco** [comment]
@F4lc0n88 If you didn´t change anything then your config is the problem. Look at the other issues there will be the explanation for your problem like way to high walking speed and no human like movement and so on.

**Comment by F4lc0n88** [comment]
@theloser No, When i want to log in with the NOX i close the bot and then set the location from the lastpos file from the bot

**Comment by zybertronix** [comment]
are you running only one bot account ? can you show us ur config ?

**Comment by zybertronix** [comment]
@theloser are we safe on one bot account running ? coz right now i stopped all bot accounts. and also unban all 6 of them. So you think i can start again with only 1 account for now ? does it still safe ?

**Comment by zentama** [comment]
are u using pogo sniping i had lot softban because sniping spam , maybe that cause of your sofban

**Comment by theloser** [comment]
@zybertronix I currently run three bots -- two without a proxy server (they are using the same IP address) and one with a proxy server (this one has a differnet IP address). Works flawless.

**Comment by F4lc0n88** [comment]
{
  "TranslationLanguageCode": "es",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": false,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 34.010561,
  "DefaultLongitude": -118.495934,
  "WalkingSpeedInKilometerPerHour": 31.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 100,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "paras",
    "venonat",
    "meowth",
    "poliwag",
    "doduo",
    "krabby",
    "horsea",
    "goldeen",
    "staryu",
    "eevee",
    "nidoranMale",
    "nidoranFemale"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by zybertronix** [comment]
@theloser thank you for the info can you show me how you change the proxy in the config file settings ?
appreciate the help :)

**Comment by theloser** [comment]
Look at my comments, I wrote:

@zybertronix Sure. Just take a look at your auth.json, there you can edit proxy server settings.

**Comment by zybertronix** [comment]
@F4lc0n88 try setting disable human walking for false

**Comment by theloser** [comment]
@zybertronix None that I know of.

**Comment by zentama** [comment]
i got banned again after use sniping
[url=https://postimg.org/image/btlqld0x7/][img]https://s9.postimg.org/u967irf1r/tama.jpg[/img][/url][url=https://postimage.org/]host image[/url]
but bot Works normal if not using sniping

**Comment by F4lc0n88** [comment]
@zybertronix I tried to run the old version of the bot with the old config file and the delay for pokemon catching and pokestops catching is much higher than the one in the new version... that sounds like a reason for a soft ban right...?

**Comment by zentama** [comment]
[21:40:45][INFO] Application starting...
[21:40:45][INFO] Connecting to feeder service pogo-feed.mmoex.com
[21:40:45][INFO] Starting with Port: 16969
[21:40:46][INFO] New connection from 127.0.0.1:54431
[21:40:47][WARN] Experiencing connection issues. Throttling...
[21:41:16][WARN] Error

System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__1.MoveNext()
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[21:41:26][PKMN] PokeSpawns: Muk at 52.363486,4.888524 with unknown IV
[21:41:26][PKMN] PokeSpawns: Gyarados at -6.189247,106.814012 with unknown IV
[21:41:26][PKMN] PokeSpawns: Jolteon at 39.483846,-0.44703 with unknown IV
[21:41:26][PKMN] PokeSpawns: Marowak at 40.651069,-74.024458 with unknown IV
[21:41:26][PKMN] PokeSpawns: Farfetchd at 22.301685,114.169155 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dragonite at 48.885853,2.386615 with unknown IV
[21:41:26][PKMN] PokeSpawns: Venusaur at -6.185123,106.813274 with unknown IV
[21:41:26][PKMN] PokeSpawns: Lapras at 51.037391,-114.099228 with unknown IV
[21:41:26][PKMN] PokeSpawns: Porygon at 40.784507,-73.957013 with unknown IV
[21:41:26][PKMN] PokeSpawns: Magneton at 40.705729,-74.013074 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dragonite at -33.877762,151.211109 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dragonite at 39.950199,-4.856155 with unknown IV
[21:41:26][PKMN] PokeSpawns: Hitmonchan at 34.01031,-118.496934 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at 37.808420187,-122.418101045 with unknown IV
[21:41:26][PKMN] PokeSpawns: Hitmonchan at 34.01031,-118.496935 with unknown IV
[21:41:26][PKMN] PokeSpawns: Grimer at 47.684914,2.632774 with unknown IV
[21:41:26][PKMN] PokeSpawns: Nidoqueen at 41.379933,2.172771 with unknown IV
[21:41:26][PKMN] PokeSpawns: Venusaur at 1.378403,103.773769 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dragonite at -33.877763,151.211109 with unknown IV
[21:41:26][PKMN] PokeSpawns: Hitmonchan at 40.418332,-3.677972 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at 52.054773,4.4978144 with unknown IV
[21:41:26][PKMN] PokeSpawns: Haunter at 48.88061,2.373685 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at 40.714157,-74.017479 with unknown IV
[21:41:26][PKMN] PokeSpawns: Grimer at 51.339288,12.375283 with unknown IV
[21:41:26][PKMN] PokeSpawns: Nidoking at 48.857114,2.294282 with unknown IV
[21:41:26][PKMN] PokeSpawns: Porygon at 47.922608,1.916716 with unknown IV
[21:41:26][PKMN] PokeSpawns: Blastoise at 53.179667,-6.798638 with unknown IV
[21:41:26][PKMN] PokeSpawns: Chansey at 30.498774,-97.760642 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at 40.714156,-74.017481 with unknown IV
[21:41:26][PKMN] PokeSpawns: Gengar at 40.735214,-73.999301 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at -33.856542,151.203732 with unknown IV
[21:41:26][PKMN] PokeSpawns: Grimer at 22.320898,114.191634 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at -33.856541,151.203735 with unknown IV
[21:41:26][PKMN] PokeSpawns: Vaporeon at 22.448277,113.992072 with unknown IV
[21:41:26][PKMN] PokeSpawns: Lickitung at 53.867217,10.671444 with unknown IV
[21:41:26][PKMN] PokeSpawns: Raichu at -22.897888,-43.185348 with unknown IV
[21:41:26][PKMN] PokeSpawns: Dratini at 34.004513,-118.492645 with unknown IV
[21:41:26][PKMN] PokeSpawns: Charizard at 31.793,-106.257 with unknown IV
[21:41:26][PKMN] PokeSpawns: Venusaur at 22.304255,114.171106 with unknown IV
[21:41:26][PKMN] PokeSpawns: Charizard at 31.793031,-106.257592 with unknown IV
[21:41:26][PKMN] PokeSpawns: Snorlax at 40.771379,-73.978366 with unknown IV
[21:41:56][WARN] Error

**Comment by zybertronix** [comment]
@F4lc0n88  yes that is right, im using version 0.7.7 config file and using the 7.8 exe file it works fine

**Comment by robbinwehl** [comment]
Dear all, 

First of all credits to the builders of this Necrobot, very nice that you made it to build a api and bot. 

since i updated to 0.80 i get no items of the pokestops and the warning: softban. 

The strange things are: 

- I play at exact same location (all day long)
- I only play with 1 account


Might it be that there is a bug in the 0.80 version ?

**Comment by zentama** [comment]
bot Works fine here after all related to sniping turn to false . i just wait then not using sniping until this problem solved

**Comment by liekos47** [comment]
i've tried switch off all bot sniping feature too false and still get softban for every bot i managing.

**Comment by zentama** [comment]
how many bot u running liekos47 ?

**Comment by liekos47** [comment]
6 atm

**Comment by theloser** [comment]
@liekos47 More than 2 bots --> softban.
