### ISSUE TITLE
No useable pokestops Constantly

### ISSUE THREAD

**Issue by Choobos** [NECROBOTIO/NecroBot#3875]
Constantly gettitng no useable pokestops
![image](https://cloud.githubusercontent.com/assets/20929006/17519729/7e709afe-5e90-11e6-9de2-cca36207883c.png)

Have tried all suggested fixes.

**Comment by WuddyMarco** [comment]
Your IP is banned.
What have you tried. The Bot ist working proberly for about 3 hours now with 2 instances so its a problem with your config or something on your side. 
How many bots at the same time ?

**Comment by Choobos** [comment]
1 bot have used the config.txt file that is suppose to fix it.  Not banned thats a different error

**Comment by ceelsoin** [comment]
I also had the same error when running 5 bots at once in less than five minutes my ip is banned ... With the individual proxy settings for each button I can solve this problem?

**Comment by WuddyMarco** [comment]
@Choobos No als @ceelsoin also told you its the exact error you get when yor IP is banned. I dont know every config which was postet in the last hours so please post yours (only the relevant part) so we can look after it.

**Comment by Valoroth87** [comment]
I'm having the same problem here, im not using multiple bots tho, downloaded the bot, started it and after 5minutes i get this (i didnt change anything in  the config file)

**Comment by Valoroth87** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/20929648/17520390/dc09d0e0-5e4f-11e6-8fee-8ac647b4bea0.JPG)

**Comment by WuddyMarco** [comment]
Than change your config! I dont know what your problem is. It should be clear that warping around between stops gives you a much higher risk of being banned. There are like  100 threads at the moment relating to this problem. 
Please start reading instead of opening a new one every few seconds.

**Comment by Valoroth87** [comment]
what should i change in the config file tho? i didnt modify it :\
