### ISSUE TITLE
Delete all my max pokemons

### ISSUE THREAD

**Issue by CezharTAC** [NECROBOTIO/NecroBot#3878]
Hi i update my Necro and this happen, it transfer all my pokes, why ?![inssue](https://cloud.githubusercontent.com/assets/20929417/17519877/5ac43dd6-5e13-11e6-8896-5684afaeecc5.png)

**Comment by 6Vampire6** [comment]
"KeepMinDuplicatePokemon": **0**,

**Comment by FureszOszkar** [comment]
"PrioritizeIvOverCp":  false,

**Comment by jsun102** [comment]
transferweakpokemon to false minduplicate>1 are two checks I would do

**Comment by tiny1980** [comment]
I see 5 transfers total.  None really of any significance.
All were low CP/IV.  You need to tweak you tolerances, or add known pokemon to the Do not transfer list.
Also don't use TransferWeakPokemon.  Keep it set to false, many people are having issues with this for pokemon they want to keep.  It seems to ignore the DoNotTransfer list.  (At least it has in my experiences).

**Comment by goobs93123** [comment]
@tiny1980 What is the actual process for adding pokemon to the do not transfer list?
When i try to add a comma and tab over to write in the name, the spacing is far off and the code doesnt look as if it will run? How do i go about this?

**Comment by theloser** [comment]
"PokemonsNotToTransfer": [ "pokemon1", "pokemon2", "pokemon3" ]

**Comment by NecroBoTPhile** [comment]
@goobs93123 
see this 
"PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",


click ur scroller so that it blink after the comma of any pokemon -> hit enter -> use spacebar to allign the scroller.
hope it helps

**Comment by helooguys** [comment]
Can i ask a stupid question? How can i change the config file to not transfer pokemons whit big cp and make it transfer the low cp ones? Sorry if this question alerady persists.

**Comment by tanjonathan** [comment]
where to edit the code not to transfer.
