### ISSUE TITLE
Lat and Long

### ISSUE THREAD

**Issue by goobs93123** [NECROBOTIO/NecroBot#3880]
Anyone have any coordinates that have worked well for exp/hour AND good CP pokemon?

Thinking of starting a bot in a new location and wanted to see if anyone has had luck anywhere specific.

**Comment by WuddyMarco** [comment]
I tried a lot of different location and normaly over the time all where were approximatly at the same level. Now with the slow but steady config i´m using because all the softban issues i get 21k EP/h at NYC for the last 3 hours and 30k EP/h at Düsseldorf in Germany. 
But maybe someone else has better spots.

**Comment by Rick058** [comment]
I do 80k xp/h in Central Park, my config: http://pastebin.com/raw/P2U1FzFJ (I'm on v0.7.6 btw!)

**Comment by WuddyMarco** [comment]
You are using much higher walkingspeed. I´m at 10 at the moment thats why i call it slow but steady. On the first account i only need 40k to level 30 then i will switch this to another one an will try out your config.

**Comment by Rick058** [comment]
Yeah I only use 30km/h for my main account though and a different location for 45k/h xp. This is just fast leveling, evolves all the shitty Pokémon that can evolve and transfers them after.
Only keeping the top Pokémon pretty much, already have 9 Dragonites around 3300 CP. Don't need more lol

**Comment by WuddyMarco** [comment]
Way higher walkingspeed gives you a big advantage. 2 days ago the bots where running or better warping around at getten around 200k/h.

**Comment by goobs93123** [comment]
Is there an actual place in the config to change the location that your bot is playing? Or is that only possible during the initial setup?
