### ISSUE TITLE
Evolve

### ISSUE THREAD

**Issue by Botter22** [NECROBOTIO/NecroBot#3881]
Guys my bot just keeps evolving everything that has enough candy even though I set

 "EvolveAllPokemonWithEnoughCandy": false,
 "UseLuckyEggsMinPokemonAmount": 50,

any help?

**Comment by goobs93123** [comment]
Is your "EvolveAllPokemonAboveIv" value set to false?

Is your "KeepPokemonsThatCanEvolve" value set to true?

**Comment by Botter22** [comment]
"EvolveAllPokemonAboveIv": true,
  "KeepPokemonsThatCanEvolve": false,

But I set to evolve pokemons with 12 candy and to keep 20 each and high cp/iv so i only have 20 each.
