### ISSUE TITLE
Wasting my ultraballs =(

### ISSUE THREAD

**Issue by MomSpaghett1** [NECROBOTIO/NecroBot#3882]
Make the bot prioritize IV/CP over catchprobability to waste less ultraballs.

![Image](http://i.imgur.com/EYkqk0n.png)

**Comment by 6Vampire6** [comment]
Maybe the settings are combined by "or"?

Chance: 3.43%
"UseUltraBallBelowCatchProbability": 0.1 (=10%)

**Comment by spamfighter82** [comment]
well set the UseUltraBallBelowCatchProbability to 0.001

**Comment by theloser** [comment]
"UseUltraBallBelowCatchProbability:" 0.1 means "Use UltraBall if Catch chance less then 10%". And the catch chance was 3.x% which is less than 10%.

Works as designed.

**Comment by MomSpaghett1** [comment]
So if i set UseUltraBallBelowCatchProbability to 0.001 will it still use ultraballs as set for aboveiv and abovecp ?

**Comment by spamfighter82** [comment]
Give it a try and report back

**Comment by MomSpaghett1** [comment]
Will do !

**Comment by theloser** [comment]
Yes. If any condition is true the bot will use UltraBalls.
