### ISSUE TITLE
KeepMinLvl How to use properly? 

### ISSUE THREAD

**Issue by vipery** [NECROBOTIO/NecroBot#3885]
I have config

    "Aerodactyl": {
      "KeepMinCp": 1600,
      "KeepMinLvl": 15,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

But still have too many aerodactyls

Aerodactyl	29	1692	63.3251713677418
Aerodactyl	28	1677	79.6156439193471
Aerodactyl	24	1480	98.1735465823027
Aerodactyl	23	1423	100
Aerodactyl	20	1230	96.299969594208
Aerodactyl	14	855	91.6372670268361
Aerodactyl	13	804	100
Aerodactyl	10	610	90.8153216538868
Aerodactyl	6	353	93.445177770242
Aerodactyl	6	353	92.662830072064
Aerodactyl	2	94	92.6312035501801
Aerodactyl	1	30	92.662830072064

**Comment by ChemiHatake** [comment]
check the PokemonNotToTransfer filter

**Comment by spamfighter82** [comment]
"KeepMinOperator": "and",

**Comment by vipery** [comment]
"PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],

**Comment by NecroBoTPhile** [comment]
@vipery From what i can see u have all aerodactyls above 90 IV ... change the IV percentage

**Comment by theloser** [comment]
@spamfighter82 If he sets the Operator to "and" he will transfer all his Aerodactyl, right? Because none of his Aerodactyl matches all three conditions (CP > 1600 **and** IV > 90% **and** Level > 15).

**Comment by vipery** [comment]
There is no way keep "UseKeepMinLvl": true, working independent?

**Comment by spamfighter82** [comment]
with "UseKeepMinLvl": true, it ignores CP

**Comment by vipery** [comment]
There is no way cut? 

Aerodactyl 14 855 91.6372670268361
Aerodactyl 13 804 100
Aerodactyl 10 610 90.8153216538868
Aerodactyl 6 353 93.445177770242
Aerodactyl 6 353 92.662830072064
Aerodactyl 2 94 92.6312035501801
Aerodactyl 1 30 92.662830072064

And stay only?

Aerodactyl 29 1692 63.3251713677418
Aerodactyl 28 1677 79.6156439193471
Aerodactyl 24 1480 98.1735465823027
Aerodactyl 23 1423 100
Aerodactyl 20 1230 96.299969594208

**Comment by WideOcean** [comment]
> with "UseKeepMinLvl": true, it ignores CP

Source?

**Comment by spamfighter82** [comment]
i am running with

```
  "PokemonsTransferFilter": {
    "Arcanine": {
      "KeepMinCp": 1750,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Chansey": {
      "KeepMinCp": 300,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dratini": {
      "KeepMinCp": 600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dragonair": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 75.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Drowzee": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 300,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Exeggutor": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 25,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 2050,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        "iceShardFast",
        "blizzard"
      ],
      "KeepMinOperator": "and",
      "MovesOperator": "and"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Muk": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Nidoqueen": {
      "KeepMinCp": 5000,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Poliwrath": {
      "KeepMinCp": 100,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 65.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Slowbro": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 85.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1750,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    }
  },
```

and it works fine for so far except that it keeps pkmn that match one move intstead of both -.-

**Comment by vipery** [comment]
but u use  "UseKeepMinLvl": false,

**Comment by spamfighter82** [comment]
yeah was the wrong bot ^^, edited above

**Comment by vipery** [comment]
well it transfer all aerodatyls http://image.prntscr.com/image/a376fe0a16cc4699b781621347bd46a1.png

 "Aerodactyl": {
      "KeepMinCp": 1600,
      "KeepMinLvl": 15,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },

**Comment by theloser** [comment]
...as I predicted ten minutes ago.

**Comment by vipery** [comment]
But yes bot only keep 3x Aerodactyls

Aerodactyl	29	1692	63.3251713677418
Aerodactyl	28	1677	79.6156439193471
Aerodactyl	24	1480	98.1735465823027

**Comment by Pokemongobottttttt** [comment]
Does setting the individual values for specific pokemon have priority to the original IV and CP minimum that is set at the top of the config, or is it in addition to it?

**Comment by theloser** [comment]
I am pretty sure individual settings per pokemon are higher rated than KeepMinCp/Percentage/Lvl, but I maybe wrong.
