### ISSUE TITLE
Press any key & Sniper [HELP]

### ISSUE THREAD

**Issue by AndreasEnemyr** [NECROBOTIO/NecroBot#3886]
I need to press any key sometimes to keep the bot running, why? Not just at the beginning, like every 10 minutes :(

And i dont understand the snipe, anyone maby can explain?

**Comment by Sudiddo** [comment]
mine too :(

**Comment by wrrion15** [comment]
`"StartupWelcomeDelay": false,`
Find that in config file and change to `"StartupWelcomeDelay": false,`

Not sure if it will fix it, worth a shot tho!
