### ISSUE TITLE
Necrobot maybe softban issue

### ISSUE THREAD

**Issue by Hackflag** [NECROBOTIO/NecroBot#3888]
Hello,

I run 1 or 2 bots in the same time. Somehow one of the bots giving the "maybe softbanned" or "no pokestops in range" warning

im not softbanned, becaus if i log in in my account on my phone, the account works.
also im not out of range becaus i have a location with more than 670 pokestops in a range with 5km (i changed my MaxTravelDistanceInMeters to 5000)

i hope somoene can solve my problem. it is annoying.

anyway, thanks for the first bot that really works <3

- Tijs

**Comment by ObsessedHacker** [comment]
Same

**Comment by ericjwg** [comment]
ip banned.

**Comment by ericjwg** [comment]
or try update your auth.json

**Comment by burntable** [comment]
Here too. Did you snipe?
Leave the bots for a few minutes and it should work again. (Until the next ban)
I'm guessing it's somehow related to sniping.
I'll try another run without any sniping on 2 bots at the same.

**Comment by zybertronix** [comment]
pls post it here all conversation regarding soft banned issue >>>> https://github.com/NECROBOTIO/NecroBot/issues/3872

**Comment by munzuradam** [comment]
Do, what @burntable said. I had the same problem and got solved thanks to him.

**Comment by yavin03** [comment]
Same problem, i run 1 - 3 accounts on one desktop. They say possible softban and starts showing the countdown everytime it goes to poke stop. Eventually after 10 to 19 counts, its working again but same issue come just right after when it go to another pokestop.
Im using the default config, just changed the location. no sniping no gpx.

**Comment by yavin03** [comment]
@zybertronix just saw that, thanks

**Comment by Gov3rnt** [comment]
guys, i got no usable pokestop and its been 12 hours. i try to open my pokemon go on phone and the pokestop doesnt want show up. is it permanently ban (maybe) ? or just need time to clearing the softban?

**Comment by Hackflag** [comment]
im not using sniping (on that account) and not using gpx
