### ISSUE TITLE
[Suggestion] Split config.json file

### ISSUE THREAD

**Issue by progz** [NECROBOTIO/NecroBot#3890]
In 0.8.0, The config.json file is almot 500 lines.

I am wondering if it's not the time to split the config.json ?

For example : 
**main.json =>** 
>   "TranslationLanguageCode": "fr",
>   "AutoUpdate": true,
>   "TransferConfigAndAuthOnUpdate": true,
>   "UseWebsocket": false,
>   "WebSocketPort": 14251,
>   "StartupWelcomeDelay": false,
>   "DefaultLatitude": 45.757523,
>   "DefaultLongitude": 4.832354,
>  "AmountOfPokemonToDisplayOnStart": 10,
>   "WalkingSpeedInKilometerPerHour": 18.0,
>   "MaxSpawnLocationOffset": 10,
>   "DelayBetweenPlayerActions": 2000,
>   "DelayBetweenPokemonCatch": 1000,
>   "DumpPokemonStats": true,
>   "RenamePokemon": true,
>   "RenameOnlyAboveIv": true,
>   "RenameTemplate": "{1}_{0}",

**pokemon.json =>**
>   "EvolveAboveIvValue": 90.0,
>   "EvolveAllPokemonAboveIv": false,
>   "EvolveAllPokemonWithEnoughCandy": true,
>   "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
>   "KeepPokemonsThatCanEvolve": true,
>   "KeepMinCp": 1600,
>   "KeepMinIvPercentage": 85.0,
>   "KeepMinLvl": 6,
>   "KeepMinOperator": "or",
>   "UseKeepMinLvl": false,
>   "PrioritizeIvOverCp": true,
>   "KeepMinDuplicatePokemon": 1,
> 

**item.json =>**
>   "MaxPokeballsPerPokemon": 6,
>   "MaxTravelDistanceInMeters": 1000,
>   "RandomizeRecycle": false,
>   "RandomRecycleValue": 5,
>   "TotalAmountOfPokeballsToKeep": 160,
>   "TotalAmountOfPotionsToKeep": 80,
>   "TotalAmountOfRevivesToKeep": 40,
>   "TotalAmountOfBerriesToKeep": 60,

**snipe.json =>**
> "UseSnipeLocationServer": true,
>   "SnipeLocationServer": "localhost",
>   "SnipeLocationServerPort": 16969,
>   "GetSniperInfoFromPokezz": true,
>   "GetOnlyVerifiedSniperInfoFromPokezz": true,
>   "GetSniperInfoFromPokeSnipers": true,
>   "MinPokeballsToSnipe": 20,
>   "MinPokeballsWhileSnipe": 0,
>   "MinDelayBetweenSnipes": 60000,
>   "SnipingScanOffset": 0.003,
>   "SnipeAtPokestops": false,
>   "SnipeIgnoreUnknownIv": false,
>   "UseTransferIvForSnipe": true,
>   "SnipePokemonNotInPokedex": false,

**Comment by Flesxueuendi** [comment]
Good idea but I think it would be easier in one document, saves time searching for one line. I wouldn't mind it

**Comment by nfettinger** [comment]
This has been declined by the developers.

**Comment by progz** [comment]
It's too bad @nfettinger 
It seems to be important for some people, this issue get five +1 in minutes.

**Comment by MapleEve** [comment]
basement conf should be in one file
item logic should be in another
pet logic too.
Easy deployable and configureable.
