### ISSUE TITLE
Can't find pokemons nor pokestops

### ISSUE THREAD

**Issue by blackturtle25** [NECROBOTIO/NecroBot#3891]
Since Niantic's new security update the bot isn't working. I have the latest version and tried reinstalling, using google and ptc accounts, nothing worked.
I get the message line about the eggs, and they hatch over time, but no pokemons/pokestops at all. I'm using a GPX track which was working perfectly. I don't think I got softbanned, the app is working if I log in on my phone, I can catch and spin pokestops like before, but nothing happens when I run the bot except that my eggs hatch.

**Comment by jowar** [comment]
me2 dont finde pokestops, update from niantic?

**Comment by thomasmoors** [comment]
lower WalkingSpeedInKilometerPerHour and try again

**Comment by blackturtle25** [comment]
I tried to lower the speed to 10, then 8, then 5, then 3.. didn't work :(

**Comment by theloser** [comment]
How many bots are you running?

**Comment by jowar** [comment]
i have only running 1 bot with sniping

**Comment by blackturtle25** [comment]
I'm running only 1 too.

**Comment by jowar** [comment]
im not banned but the bot doesnt work he say no poke stop in the near
with nox pokemone goes fine

**Comment by theloser** [comment]
@blackturtle25 Turn of sniping, only use one bot (max: two) and don't login using your phone app. Use a walking speed of 15, set "DisableHumanWalking" to false, don't change your coords once you started the bot -- works fine for me.

**Comment by theloser** [comment]
@jowar So you are using the bot **and** NOX? Nothing more to say...

**Comment by blackturtle25** [comment]
As I already said, I'm not sniping, I'm using one bot, "DisableHumanWalking" is on false, and obviously I didn't change coords after I started the bot.  -- doesn't work for me..

**Comment by theloser** [comment]
@blackturtle25 @nfettinger closed a lot of issues in the last few minutes (thank god!), maybe he just read  the title and thought it's a duplicate because almost evey issue regarding "Pokestops not found" has to do with some kind of softban.

Sometimes I get those messages, too, but if I wait just a few minutes the bot recovers itself.

**Comment by blackturtle25** [comment]
@theloser I just tried to make a new one with screenshot and more specific description, this guy closed it 4 seconds after... ._.

**Comment by ZapPhoenix** [comment]
i have same issue, 1 bot tried vpns nothing is working.

**Comment by theloser** [comment]
I would probably have done the same, to be honest.
Just post your details here and I'll check.

**Comment by ZapPhoenix** [comment]
i got it to work change gps to 30.2693700000567:-97.7520240002252
