### ISSUE TITLE
Bug While Transferring Pokemons

### ISSUE THREAD

**Issue by KapilTapsi** [NECROBOTIO/NecroBot#3892]
First When I started necrobot today. I saw mass transfer. I don't know, it may be normal. 

But while transferring I noticed, the CP of best pokemon is displayed same as that of being transferred,
![untitledn](https://cloud.githubusercontent.com/assets/20764254/17521261/57a2cb74-5e70-11e6-8ab7-b9c6091b9428.jpg)

**Comment by Flesxueuendi** [comment]
R.I.P Aerodactyl and Kakuna 2k16-2k16.5

**Comment by martinwind** [comment]
keepmindupiclate 0

**Comment by nfettinger** [comment]
Duplicate #3338
