### ISSUE TITLE
Where can I find the definition of each key in Translation file?

### ISSUE THREAD

**Issue by doniface** [NECROBOTIO/NecroBot#3894]
Hi, need to know each key's definition in Translation file like this:

      "Key": "eventFortUsed",
      "Value": "名稱：{0} 經驗值：{1}，金幣：{2}，物品：{3} 其他資訊：{4}"

How and where do I know which {0}~{4} means? and can this key provide more information like {5}, {6}...?

**Comment by HugoMSantos** [comment]
**名稱** - name

**金幣** - gold (pokecoins?)

**物品** - article 

**其他資訊** - additional information

**Comment by nfettinger** [comment]
Use discord chat.
