### ISSUE TITLE
Querry: Why there is much softban in game . Every Minute I see Softban.

### ISSUE THREAD

**Issue by KapilTapsi** [NECROBOTIO/NecroBot#3898]

**Comment by chimichandra** [comment]
Lower you walking speed... "Speedier than ever" means more softban than ever.

**Comment by Marsinator** [comment]
youre moving to fast, running multiple bots or youre running a 2nd app that uses the same login at the same time

**Comment by ramzabeoulwe** [comment]
I have it set to 10:
"WalkingSpeedInKilometerPerHour": 10.0,
and I'm still getting a lot of "Possible soft-ban" messages.

I also miss to catch a lot of pokemons (Catchflee message).
