### ISSUE TITLE
ERROR SoftBan??

### ISSUE THREAD

**Issue by bmqf** [NECROBOTIO/NecroBot#3901]
this is happening to me straight, happens to somebody else ?? open 4 instances I can do for this not to happen ??
![erro bot](https://cloud.githubusercontent.com/assets/20930094/17522409/479c7e70-5e2d-11e6-9992-ff85907c7324.jpg)

**Comment by nfettinger** [comment]
Please use discord chat.

**Comment by mogibilal** [comment]
same here
