### ISSUE TITLE
Almost no incubator status change when walking

### ISSUE THREAD

**Issue by ramzabeoulwe** [NECROBOTIO/NecroBot#3902]
The bot has walked quite a lot for the last 20 minutes, but the egg incubator status changed from 5.0 to 4.99, so almost no effect. It was working a lot better in previous versions.

The walking speed in my config is:
"WalkingSpeedInKilometerPerHour": 10.0,

**Comment by nfettinger** [comment]
Did you disable humanlike walking?

Use Discord chat for configuration issues.
