### ISSUE TITLE
[Suggestion] Let the bot show his top 20 IV / CP pokemon every 30 minutes

### ISSUE THREAD

**Issue by PokemasterMike** [NECROBOTIO/NecroBot#3903]
after a 2 hour session id like to know what the bot caught in the mean time and going through the logs is kinda tedious. it would be nice if i could find the info about top IV/CP pokemon somewhere in the console (or even in the log if presented decently). if you want you can make a setting to turn it on/off but id find it quite useful to know what happened recently

**Comment by nfettinger** [comment]
You can view the dump file, or use the visualizer.
