### ISSUE TITLE
Transferred before catch?

### ISSUE THREAD

**Issue by wele** [NECROBOTIO/NecroBot#3904]
Not sure but this is the 3rd time i've actually seen this (can't find the other one in logs) however a pokemon was transferred before it was caught. Might just be a visual error but seems odd.

![image](https://cloud.githubusercontent.com/assets/2280652/17522521/3745766a-5e0c-11e6-9409-e711cca10c57.png)

**Comment by nfettinger** [comment]
Duplicate issue.
