### ISSUE TITLE
Did not find a Pokemon whitin the snipingscannoffset?

### ISSUE THREAD

**Issue by jogopelado** [NECROBOTIO/NecroBot#3907]
How can I resolve this error?

lose many Pokemon as well!

![screenshot_41](https://cloud.githubusercontent.com/assets/20930298/17522540/cedada12-5e2d-11e6-8e5f-31696a9697ee.jpg)

**Comment by nfettinger** [comment]
Use discord chat for help.

**Comment by Energex22** [comment]
i made my sniperoffset from "0.005" to "0.05" but still i get these errors. I think it means that there wasn't a monster there anymore, not sure...
