### ISSUE TITLE
Lastpos.ini not being read

### ISSUE THREAD

**Issue by hughpearse** [NECROBOTIO/NecroBot#3908]
Set up the bot with the necrobot visualizer.
Run the bot for a few minutes giving it enough time to distance itself from the starting location.
Close the bot.
Reopen the bot.

Result:
When the bot is reopened, it goes back to the starting location instead of resuming from where it was last.

![screenshot from 2016-08-09 16 38 01](https://cloud.githubusercontent.com/assets/681555/17522767/297e8b4a-5e50-11e6-93d0-afc57a3f6188.png)

**Comment by Simpuhl** [comment]
I believe that lastpos is only for sniping? At least that's the impression ive always had.

Side question: Where do we get this visualizer?

**Comment by nfettinger** [comment]
This file is not meant to pick up where you left off. It is to prevent teleporting on restarts. There is already an issue to start at nearest in GPX files.
