### ISSUE TITLE
No pokestops and no pokemons (I'm not softbanned)

### ISSUE THREAD

**Issue by blackturtle25** [NECROBOTIO/NecroBot#3910]
I have the latest version and tried reinstalling, using google and ptc accounts, nothing worked. It's like this since the latest relase of Pokemon GO came out.
I get the message line about the eggs, and they hatch over time, but no pokemons/pokestops at all. I'm using a GPX track which was working perfectly. I'm sure I didn't get softbanned, the app is working if I close the bot and log in on my phone, I can catch and spin pokestops like before, but nothing happens when I run the bot except that my eggs hatch.
Walking speed is set to 8, I've tried to use faster and lower speed too. Sniping is off, "DisableHumanWalking" is set to false. I'm running only 1 bot.

(I already posted this issue but a few minutes later someone closed it and I still didn't get any solution)

![asdasd](https://cloud.githubusercontent.com/assets/20930023/17522829/ba28858a-5e58-11e6-888a-60e3b52bb946.PNG)

**Comment by kan22955500** [comment]
me too

**Comment by blackturtle25** [comment]
@nfettinger could you please stop closing my issues??
