### ISSUE TITLE
separating config.json to bot_config.json and pokemon_config.json

### ISSUE THREAD

**Issue by msx752** [NECROBOTIO/NecroBot#3911]
people can save pokemon configs for every bot versions
>in bot_config.json we can use
- ..OTHER PROPERTIES
- ItemRecycleFilter

> in pokemon_config.json we can use
- PokemonsNotToTransfer
- PokemonsToEvolve
- PokemonsToLevelUp
- PokemonsToIgnore
- PokemonsTransferFilter
- PokemonToSnipe
- PokemonToUseMasterball

**Comment by nfettinger** [comment]
This is not desirable to the developers.
