### ISSUE TITLE
No pokestops and no pokemons, but I'm NOT softbanned (nfettinger please stop closing my issues for no reason)

### ISSUE THREAD

**Issue by blackturtle25** [NECROBOTIO/NecroBot#3912]
First of all, sorry about that I'm posting this for the 3rd time now, @nfettinger closed the first 2 right after I submitted. (I'd like to know why, but I guess we'll never know..)

I have the latest version and tried reinstalling, using google and ptc accounts, nothing worked. It's like this since the latest relase of Pokemon GO came out.
I get the message line about the eggs, and they hatch over time, but no pokemons/pokestops at all. I'm using a GPX track which was working perfectly. I'm sure I didn't get softbanned, the app is working if I close the bot and log in on my phone, I can catch and spin pokestops like before, but nothing happens when I run the bot except that my eggs hatch.
Walking speed is set to 8, I've tried to use faster and lower speed too. Sniping is off, "DisableHumanWalking" is set to false. I'm running only 1 bot.

The screenshot below shows what I see whenever I start the bot, even after hours.

![asdasd](https://cloud.githubusercontent.com/assets/20930023/17523088/af42c4fe-5e59-11e6-9783-7b9545b0ac31.PNG)

**Comment by nfettinger** [comment]
This is not the place to deal with configuration issues. Please use Discord Chat!

**Comment by blackturtle25** [comment]
@nfettinger this isn't a configuration issue
