### ISSUE TITLE
(request) Transfer all pokemon below set CP

### ISSUE THREAD

**Issue by Pokemongobottttttt** [NECROBOTIO/NecroBot#3913]
I am struggling to get what I want to work with keeping high IV only if CP is over 1000. And for it to also keep anything over 1800 CP reguardless of IV. So an easy solution is to have an option to transfer everything below 1000 CP

**Comment by nfettinger** [comment]
"TransferWeakPokemon": true

**Comment by Pokemongobottttttt** [comment]
what is considered weak?

**Comment by nfettinger** [comment]
Pokemon that do not meet your min CP or IV or Level, Depending on what you have configured.
Closing since this is a configuration issue.

**Comment by nfettinger** [comment]
You can get further help using our Discord chat channels.
