### ISSUE TITLE
Not to evolve specific pokemon

### ISSUE THREAD

**Issue by l3vz** [NECROBOTIO/NecroBot#3917]
my config is to evolve all above iv 10% , so when I farm pidgeys, weedles, etc, they can autoevolve to gain more exp

the problem is, necrobot also evolved dratini and other pokemons that I don't want to evolve
I  didn't put dratini into "PokemonsToEvolve" list but necrobot keep evolves them

I also tried to put this on transfer filter 
 "Dratini": {
      "KeepMinCp": 1000,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
so I won't keep a single dratini to evolve, unless it has iv 100% or 1000 cp which is very rare
but necrobot still evolves it before transfers it, 

well, it really desperate to see my 600+ dratini candies to power up my dragonite just gone into low level dragonairs.. 

can you help me with the config, or make this to a pull request 
- not to evolve specific pokemon or
- do transfer first before evolve

sorry for bad english
thanks

**Comment by nfettinger** [comment]
Configuration help should be sought out using the Discord Chat channels. This tracker is for code issues only. Feel free to create a feature request in the future if need be.
