### ISSUE TITLE
every 15 mins i get softbanned

### ISSUE THREAD

**Issue by isquirt** [NECROBOTIO/NecroBot#3922]
here is my configs. every 15 mins i get softbanned and then necrobot don't work for a bit, even if the bot try to unban me. if i close and restart, it say me that there is no pokestop available. i give my config

![image](https://cloud.githubusercontent.com/assets/20929404/17523725/ea0b4690-5e5b-11e6-991a-8cb672f0acd0.png)
![image](https://cloud.githubusercontent.com/assets/20929404/17523742/f0f60e90-5e5b-11e6-8756-50b0556a03b3.png)

**Comment by nfettinger** [comment]
Please use Discord chat for help.
