### ISSUE TITLE
Bot ddoses on login

### ISSUE THREAD

**Issue by deviantdealer** [NECROBOTIO/NecroBot#3927]
when running multiple bots when the servers lag and the bot tries to reconnect it is basically ddosing the servers, maybe there should be a timer between attempts to login.

**Comment by theloser** [comment]
FYI: Multiple bots (more than 2) --> instant softban.

**Comment by nfettinger** [comment]
This is not a developmental issue

**Comment by deviantdealer** [comment]
how is coding in a timer not a development issue?
