### ISSUE TITLE
Auto-transfer Transfers wrong pokemons

### ISSUE THREAD

**Issue by iTayGNR** [NECROBOTIO/NecroBot#3930]
Hey,
I had a 712CP growlithe, and it had transferred and replaced by a 374CP growlithe. WTF?
how can I prevent this from happening? that's not the first time it happens..

**Comment by nfettinger** [comment]
Please check your config for IV priority
There is also a known bug #3338

**Comment by iTayGNR** [comment]
@nfettinger how does it called in the config?

**Comment by iTayGNR** [comment]
@nfettinger 
`  "PrioritizeIvOverCp": false,`
that's not the problem..

**Comment by iTayGNR** [comment]
`[18:50:23] (CatchSuccess) | (Normal) Growlithe Lvl: 10 CP: (374/381) IV: 90.00% | Chance: 28.4% | 46.30m dist | with a GreatBall (4 left). | 210 EXP earned | Candies: 178 | lat: 32.790670 long: 34.966725`

`[18:50:32] Growlithe   	- CP:  798  IV:  54.33%   [Best CP:  374  IV:  90.04%] (Candies: 179)
`
From the log. WTF?
