### ISSUE TITLE
softban softban softban ...

### ISSUE THREAD

**Issue by jawad90** [NECROBOTIO/NecroBot#3934]
the bot stays at one pokestop and keeps saying that big ugly softban error line ... and sometimes the pokestop is only bugged thats why you cant loot from it but the bot stays there until i close it or is it because of that Device Id ?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by jawad90** [comment]
its not general ... this started after the 2 last releases
