### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by meetloaf13** [NECROBOTIO/NecroBot#3936]
I need some help understanding the log.  See the following output:
http://i.imgur.com/Yif6ayN.png

Does that mean All I had to do was level up my Hitmonchan and he would have been 100%?  If so, I'm not too excited about him being transferred.  And is the number in parens their "potential" for that specific Pokemon?

Is there a way I can transfer by the potential and the current?

I'm a little confused.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
