### ISSUE TITLE
softban in every 2-3 minutes

### ISSUE THREAD

**Issue by freewilly2u** [NECROBOTIO/NecroBot#3941]
any suggestion to avoid this problem?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by palmpje94** [comment]
api is out again?

**Comment by palmpje94** [comment]
i got the no pokestops in your area, dist to small? again on al 4 bots and 2 of 'm are 0.7.6 the other 2 are 0.8.0 and 0.8.1
