### ISSUE TITLE
egg hatched not

### ISSUE THREAD

**Issue by Gadriel45** [NECROBOTIO/NecroBot#3946]
egg does not move even after visiting pokestops 

help please

![oeuf bug](https://cloud.githubusercontent.com/assets/20750008/17524760/23fabdc8-5e60-11e6-9e83-d95585c4cdd0.PNG)

**Comment by spamfighter82** [comment]
WalkingSpeedInKilometerPerHour?
and 2 minutes is not long at all for hatching, even with the real client you can walk for 10min w/o making progress

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by Gadriel45** [comment]
"WalkingSpeedInKilometerPerHour": 90.0,
