### ISSUE TITLE
Bot Always earn 210 EXP

### ISSUE THREAD

**Issue by kingodd** [NECROBOTIO/NecroBot#3949]
I always earn  210 EXP when catch pokemon, will this causing my account ban?
coz too suspicious, if i able to make excellent throw and curve ball every time.

so i purposely set it lower 
  "NiceThrowChance": 40,
  "GreatThrowChance": 45,
  "ExcellentThrowChance": 15,
  "CurveThrowChance": 50,

but i still able to get 210 EXP every time.

Thanks,
Leon

**Comment by spamfighter82** [comment]
"EnableHumanizedThrows": true, its false by default

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
