### ISSUE TITLE
ERROR: Argument must be in range of -90 to 90

### ISSUE THREAD

**Issue by Yanniclord** [NECROBOTIO/NecroBot#3950]
Hi, i am getting this error after about 5 minutes of using Necrobot, and haven't found the answer to the fix yet.

http://pastebin.com/tkC8AR7L

**Comment by kingodd** [comment]
may be you take alook at

  "DefaultLatitude": 3.100000,
  "DefaultLongitude": -101.00000,

whether got set any value?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
