### ISSUE TITLE
Pokesnipers coords out of bounds

### ISSUE THREAD

**Issue by ThomasSRL** [NECROBOTIO/NecroBot#3951]
Hi,

Pokesnipers coords don't have punctuation in them it seems. I'm unsure if this is just graphical (debug).
But it would say:
sniping gyarados at 45748754,87842111
While it should be saying:
sniping gyarados at 45.748754,87.842111

Maybe add a check if the coords are inRange (-180; 180)?

**Comment by jjskuld** [comment]
I don't see this issue. Sniping is working from pokesnipers and the output is ok too.
<img width="636" alt="sniping" src="https://cloud.githubusercontent.com/assets/16908714/17525637/7713952c-5e18-11e6-84ee-14cba4b14b81.png">

**Comment by ThomasSRL** [comment]
Hi @jjskuld 
Thats weird, perhaps the coords on pokesnipers just didnt have punctuation then.
I'll try again later!
Either way an out of bounds check wont hurt :)

**Comment by suzsuzuki** [comment]
Same here
![poke](https://cloud.githubusercontent.com/assets/20933693/17529191/cd4ee90c-5e48-11e6-9e9d-0fa56cca9df9.png)

**Comment by ThomasSRL** [comment]
Can someone create an out-of-bounds check please? :)

**Comment by nfettinger** [comment]
There already is an out of bounds check for 90 to -90
