### ISSUE TITLE
Necrobot sniping issue

### ISSUE THREAD

**Issue by Laukais** [NECROBOTIO/NecroBot#3955]
Hello everyone here, i have this problem when sniping by necrobot, does any of you know a way to get rid of that?
https://gyazo.com/ec9218729d7a3ae4ed1c9dfc8a5ecfeb

I appreciate any help, thank you :)

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
Update to the newest version 0.8.1
