### ISSUE TITLE
Softban

### ISSUE THREAD

**Issue by Krome333** [NECROBOTIO/NecroBot#3959]
How its possible to not get it often .. i run at 6km/h .. help please :P

**Comment by theloser** [comment]
How many bots are you running?

**Comment by kilakuma** [comment]
i try 2 , 3 , 4 , 5 , 6 bot
and more than 2 bot is being soft baned

**Comment by TheBorna** [comment]
Increase delays if you are running more bots.

**Comment by theloser** [comment]
This has nothing to with "delays" -- Niantics blocks any IP address if more than two instances connect to their server from this address.

**Comment by TheBorna** [comment]
Oh I see, sorry.

**Comment by theloser** [comment]
@kilakuma Two bots are ok. More than two --> instant softban.
Please close this issue.

**Comment by Krome333** [comment]
i have only 2 and get often softban again

**Comment by theloser** [comment]
@Krome333 Check your config for walking speed, DisableHumanWalking, Lat & Long, Sniping etc. If the bot does something a real player can't (like moving fast or sniping) you'll probably get a softban.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
