### ISSUE TITLE
Only snipes, no movement.

### ISSUE THREAD

**Issue by Caydenz** [NECROBOTIO/NecroBot#3961]
> [19:53:49] (SNIPER) (Pokezz.com) Sniping a Arcanine with Unknown IV at 59.309412,18.082389...
> [19:53:53] (BERRY) Used Razz Berry | 46 remaining
> [19:53:54] (PKMN) (CatchSuccess) | (Normal) Arcanine Lvl: 5 CP: (382/402) IV: 62.00% | Chance: 13.78% | 6318985.85m dist | with a PokeBall (119 left). | 210 EXP earned | Candies: 9 | lat: 59.309412 long: 18.082390
> [19:53:54] (SNIPER) (Pokezz.com) Sniping a Lickitung with Unknown IV at 40.733584,-74.001964...
> [19:53:55] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:53:55] (SNIPER) (Pokezz.com) Sniping a Hitmonchan with Unknown IV at 40.736704,-74.005453...
> [19:54:00] (PKMN) (CatchEscape) | (Normal) Hitmonchan Lvl: 3 CP: (106/113) IV: 68.00% | Chance: 37.08% | 5936.81m dist | with a PokeBall (118 left). | lat: 40.736704 long: -74.005453
> [19:54:02] (TRANSFERED) Arcanine        - CP:  382  IV:  61.93%   [Best CP: 2488  IV:  79.65%] (Candies: 10)
> [19:54:02] (PKMN) (CatchSuccess Attempt #2) | (Normal) Hitmonchan Lvl: 3 CP: (106/113) IV: 68.00% | Chance: 37.08% | 5936.81m dist | with a PokeBall (117 left). | 210 EXP earned | Candies: 182 | lat: 40.736704 long: -74.005453
> [19:54:02] (SNIPER) (Pokezz.com) Sniping a Aerodactyl with Unknown IV at 45.525655,-122.685789...
> [19:54:07] (TRANSFERED) Hitmonchan      - CP:  106  IV:  67.57%   [Best CP: 1219  IV:  67.27%] (Candies: 183)
> [19:54:08] (PKMN) (CatchSuccess) | (Normal) Aerodactyl Lvl: 1 CP: (29/30) IV: 71.00% | Chance: 85.11% | 3929678.86m dist | with a PokeBall (116 left). | 210 EXP earned | Candies: 168 | lat: 45.525655 long: -122.685790
> [19:54:08] (SNIPER) (Pokezz.com) Sniping a Porygon with Unknown IV at 22.385193,114.202409...
> [19:54:09] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:09] (SNIPER) (Pokezz.com) Sniping a Farfetchd with Unknown IV at 22.296562,114.176215...
> [19:54:14] (TRANSFERED) Aerodactyl      - CP:   29  IV:  70.56%   [Best CP: 1850  IV:  92.63%] (Candies: 169)
> [19:54:15] (PKMN) (CatchSuccess) | (Normal) Farfetchd Lvl: 17 CP: (525/613) IV: 29.00% | Chance: 21.79% | 12962252.13m dist | with a PokeBall (115 left). | 210 EXP earned | Candies: 342 | lat: 22.296562 long: 114.176215
> [19:54:15] (SNIPER) (Pokezz.com) Sniping a Farfetchd with Unknown IV at 22.295328,114.174636...
> [19:54:17] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:17] (SNIPER) (Pokezz.com) Sniping a Blastoise with Unknown IV at 42.329358,-83.039535...
> [19:54:21] (BERRY) Used Razz Berry | 47 remaining
> [19:54:22] (TRANSFERED) Farfetchd       - CP:  525  IV:  28.65%   [Best CP:  999  IV:  61.53%] (Candies: 343)
> [19:54:23] (PKMN) (CatchSuccess) | (Normal) Blastoise Lvl: 6 CP: (369/419) IV: 17.00% | Chance: 6.23% | 774964.71m dist | with a GreatBall (0 left). | 210 EXP earned | Candies: 5 | lat: 42.329359 long: -83.039536
> [19:54:23] (SNIPER) (Pokezz.com) Sniping a Arcanine with Unknown IV at 19.418743,-99.133033...
> [19:54:26] (BERRY) Used Razz Berry | 46 remaining
> [19:54:28] (PKMN) (CatchSuccess) | (Normal) Arcanine Lvl: 12 CP: (928/1023) IV: 31.00% | Chance: 8.64% | 3370833.47m dist | with a PokeBall (114 left). | 210 EXP earned | Candies: 13 | lat: 19.418744 long: -99.133033
> [19:54:28] (SNIPER) (Pokezz.com) Sniping a Marowak with Unknown IV at 19.427365,-99.186487...
> [19:54:30] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:30] (SNIPER) (Pokezz.com) Sniping a Electabuzz with Unknown IV at 22.337069,114.193027...
> [19:54:33] (BERRY) Used Razz Berry | 45 remaining
> [19:54:36] (TRANSFERED) Arcanine        - CP:  928  IV:  30.83%   [Best CP: 2488  IV:  79.65%] (Candies: 14)
> [19:54:36] (PKMN) (CatchSuccess) | (Normal) Electabuzz Lvl: 24 CP: (1277/1453) IV: 23.00% | Chance: 18.34% | 12957569.13m dist | with a PokeBall (113 left). | 210 EXP earned | Candies: 2246 | lat: 22.337069 long: 114.193028
> [19:54:36] (SNIPER) (Pokezz.com) Sniping a Slowbro with Unknown IV at 22.398215,114.192841...
> [19:54:40] (BERRY) Used Razz Berry | 44 remaining
> [19:54:41] (PKMN) (CatchEscape) | (Normal) Slowbro Lvl: 27 CP: (1798/2003) IV: 28.00% | Chance: 11.52% | 12950815.50m dist | with a PokeBall (112 left). | lat: 22.398215 long: 114.192842
> [19:54:42] (BERRY) Used Razz Berry | 43 remaining
> [19:54:43] (PKMN) (CatchSuccess Attempt #2) | (Normal) Slowbro Lvl: 27 CP: (1798/2003) IV: 28.00% | Chance: 11.52% | 12950815.50m dist | with a PokeBall (111 left). | 210 EXP earned | Candies: 736 | lat: 22.398215 long: 114.192842
> [19:54:43] (SNIPER) (Pokezz.com) Sniping a Mr. Mime with Unknown IV at 41.197178,1.637252...
> [19:54:48] (TRANSFERED) Slowbro         - CP: 1798  IV:  27.68%   [Best CP: 2034  IV:  39.08%] (Candies: 737)
> [19:54:49] (PKMN) (CatchSuccess) | (Normal) Mr. Mime Lvl: 8 CP: (305/336) IV: 51.00% | Chance: 31.98% | 6134089.21m dist | with a PokeBall (110 left). | 210 EXP earned | Candies: 90 | lat: 41.197178 long: 1.637253
> [19:54:49] (SNIPER) (Pokezz.com) Sniping a Hitmonchan with Unknown IV at 21.284582,-89.660791...
> [19:54:51] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:51] (SNIPER) (Pokezz.com) Sniping a Cloyster with Unknown IV at 22.35435,114.109423...
> [19:54:52] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:52] (SNIPER) (Pokezz.com) Sniping a Electabuzz with Unknown IV at 22.32993,114.185225...
> [19:54:54] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:54:54] (SNIPER) (Pokezz.com) Sniping a Farfetchd with Unknown IV at 22.424625,113.988727...
> [19:54:56] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:13] (SNIPER) (PokeSnipers.com) Sniping a Lickitung with Unknown IV at 40.733584,-74.001964...
> [19:55:16] (BERRY) Used Razz Berry | 42 remaining
> [19:55:18] (PKMN) (CatchSuccess) | (Normal) Lickitung Lvl: 20 CP: (877/929) IV: 69.00% | Chance: 13.39% | 6050.35m dist | with a PokeBall (109 left). | 210 EXP earned | Candies: 138 | lat: 40.733584 long: -74.001964
> [19:55:18] (SNIPER) (PokeSnipers.com) Sniping a Farfetchd with Unknown IV at 22.295328,114.174636...
> [19:55:19] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:19] (SNIPER) (PokeSnipers.com) Sniping a Hitmonchan with Unknown IV at 21.284582,-89.660791...
> [19:55:21] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:21] (SNIPER) (PokeSnipers.com) Sniping a Cloyster with Unknown IV at 22.35435,114.109423...
> [19:55:23] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:23] (SNIPER) (PokeSnipers.com) Sniping a Electabuzz with Unknown IV at 22.32993,114.185225...
> [19:55:24] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:24] (SNIPER) (PokeSnipers.com) Sniping a Farfetchd with Unknown IV at 22.424625,113.988727...
> [19:55:26] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:55:26] (SNIPER) (PokeSnipers.com) Sniping a Farfetchd with Unknown IV at 22.295328,114.174636...
> [19:55:30] (BERRY) Used Razz Berry | 41 remaining
> [19:55:31] (PKMN) (CatchEscape) | (Normal) Farfetchd Lvl: 29 CP: (900/1047) IV: 30.00% | Chance: 16.68% | 12962407.89m dist | with a PokeBall (108 left). | lat: 22.295329 long: 114.174636
> [19:55:32] (BERRY) Used Razz Berry | 40 remaining
> [19:55:32] (PKMN) (CatchEscape Attempt #2) | (Normal) Farfetchd Lvl: 29 CP: (900/1047) IV: 30.00% | Chance: 16.68% | 12962407.89m dist | with a PokeBall (107 left). | lat: 22.295329 long: 114.174636
> [19:55:34] (BERRY) Used Razz Berry | 39 remaining
> [19:55:34] (PKMN) (CatchEscape Attempt #3) | (Normal) Farfetchd Lvl: 29 CP: (900/1047) IV: 30.00% | Chance: 16.68% | 12962407.89m dist | with a PokeBall (106 left). | lat: 22.295329 long: 114.174636
> [19:55:35] (PKMN) (CatchEscape Attempt #4) | (Normal) Farfetchd Lvl: 29 CP: (900/1047) IV: 30.00% | Chance: 16.68% | 12962407.89m dist | with a PokeBall (105 left). | lat: 22.295329 long: 114.174636
> [19:55:38] (TRANSFERED) Lickitung       - CP:  877  IV:  69.00%   [Best CP: 1341  IV:  78.82%] (Candies: 139)
> [19:55:38] (PKMN) (CatchSuccess Attempt #5) | (Normal) Farfetchd Lvl: 29 CP: (900/1047) IV: 30.00% | Chance: 16.68% | 12962407.89m dist | with a PokeBall (104 left). | 210 EXP earned | Candies: 346 | lat: 22.295329 long: 114.174636
> [19:55:38] (SNIPER) (PokeSnipers.com) Sniping a Dragonite with Unknown IV at 40.74147,-74.046766...
> [19:55:42] (BERRY) Used Razz Berry | 38 remaining
> [19:55:43] (PKMN) (CatchEscape) | (Normal) Dragonite Lvl: 18 CP: (1750/1800) IV: 78.00% | Chance: 3.53% | 8232.20m dist | with a PokeBall (103 left). | lat: 40.741471 long: -74.046766
> [19:55:43] (BERRY) Used Razz Berry | 37 remaining
> [19:55:44] (PKMN) (CatchEscape Attempt #2) | (Normal) Dragonite Lvl: 18 CP: (1750/1800) IV: 78.00% | Chance: 3.53% | 8232.20m dist | with a PokeBall (102 left). | lat: 40.741471 long: -74.046766
> [19:55:45] (BERRY) Used Razz Berry | 36 remaining
> [19:55:46] (PKMN) (CatchFlee Attempt #3) | (Normal) Dragonite Lvl: 18 CP: (1750/1800) IV: 78.00% | Chance: 3.53% | 8232.20m dist | with a PokeBall (101 left). | lat: 40.741471 long: -74.046766
> [19:55:46] (SNIPER) (PokeSnipers.com) Sniping a Aerodactyl with Unknown IV at 41.646542,-0.894892...
> [19:55:50] (BERRY) Used Razz Berry | 35 remaining
> [19:55:51] (PKMN) (CatchEscape) | (Normal) Aerodactyl Lvl: 30 CP: (1724/1856) IV: 54.00% | Chance: 10.93% | 5922185.20m dist | with a PokeBall (100 left). | lat: 41.646542 long: -0.894892
> [19:55:52] (BERRY) Used Razz Berry | 34 remaining
> [19:55:53] (PKMN) (CatchEscape Attempt #2) | (Normal) Aerodactyl Lvl: 30 CP: (1724/1856) IV: 54.00% | Chance: 10.93% | 5922185.20m dist | with a PokeBall (99 left). | lat: 41.646542 long: -0.894892
> [19:55:53] (BERRY) Used Razz Berry | 33 remaining
> [19:55:55] (TRANSFERED) Farfetchd       - CP:  900  IV:  30.10%   [Best CP:  999  IV:  61.53%] (Candies: 347)
> [19:55:55] (PKMN) (CatchSuccess Attempt #3) | (Normal) Aerodactyl Lvl: 30 CP: (1724/1856) IV: 54.00% | Chance: 10.93% | 5922185.20m dist | with a PokeBall (98 left). | 210 EXP earned | Candies: 172 | lat: 41.646542 long: -0.894892
> [19:55:55] (SNIPER) (PokeSnipers.com) Sniping a Farfetchd with Unknown IV at 22.424625,113.988727...
> [19:56:01] (TRANSFERED) Aerodactyl      - CP: 1724  IV:  54.15%   [Best CP: 1850  IV:  92.63%] (Candies: 173)
> [19:56:01] (PKMN) (CatchSuccess) | (Normal) Farfetchd Lvl: 10 CP: (335/361) IV: 64.00% | Chance: 28.4% | 12950383.53m dist | with a PokeBall (97 left). | 210 EXP earned | Candies: 350 | lat: 22.424625 long: 113.988728
> [19:56:01] (SNIPER) (PokeSnipers.com) Sniping a Arcanine with Unknown IV at 37.885187,-4.77996...
> [19:56:03] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:03] (SNIPER) (PokeSnipers.com) Sniping a Snorlax with Unknown IV at -6.257101,106.923548...
>                       [19:56:07] (BERRY) Used Razz Berry | 32 remaining
> [19:56:09] (TRANSFERED) Farfetchd       - CP:  335  IV:  64.13%   [Best CP:  999  IV:  61.53%] (Candies: 351)
> [19:56:09] (PKMN) (CatchSuccess) | (Normal) Snorlax Lvl: 21 CP: (1818/1867) IV: 80.00% | Chance: 13.07% | 16189370.04m dist | with a PokeBall (96 left). | 210 EXP earned | Candies: 181 | lat: -6.257101 long: 106.923548
> [19:56:09] (SNIPER) (PokeSnipers.com) Sniping a Lickitung with Unknown IV at 40.733584,-74.001964...
> [19:56:10] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:10] (SNIPER) (PokeSnipers.com) Sniping a Mr. Mime with Unknown IV at 40.362887,-4.395346...
> [19:56:12] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:12] (SNIPER) (PokeSnipers.com) Sniping a Lapras with Unknown IV at 59.307615,18.025974...
> [19:56:14] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:14] (SNIPER) Scanning for Snipeable Pokemon at 38.5568074864611,-121.238379478455...
> [19:56:14] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:14] (SNIPER) Scanning for Snipeable Pokemon at -33.859019,151.213098...
> [19:56:15] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:20] (BERRY) Used Razz Berry | 31 remaining
> [19:56:20] (PKMN) (CatchEscape) | (Normal) Golem Lvl: 15 CP: (940/987) IV: 69.00% | Chance: 9.66% | 16007551.50m dist | with a PokeBall (95 left). | lat: -33.881284 long: 151.206101
> [19:56:21] (BERRY) Used Razz Berry | 30 remaining
> [19:56:22] (PKMN) (CatchEscape Attempt #2) | (Normal) Golem Lvl: 15 CP: (940/987) IV: 69.00% | Chance: 9.66% | 16007551.50m dist | with a PokeBall (94 left). | lat: -33.881284 long: 151.206101
> [19:56:23] (BERRY) Used Razz Berry | 29 remaining
> [19:56:25] (PKMN) (CatchEscape Attempt #3) | (Normal) Golem Lvl: 15 CP: (940/987) IV: 69.00% | Chance: 9.66% | 16007551.50m dist | with a PokeBall (93 left). | lat: -33.881284 long: 151.206101
> [19:56:26] (PKMN) (CatchSuccess Attempt #4) | (Normal) Golem Lvl: 15 CP: (940/987) IV: 69.00% | Chance: 9.66% | 16007551.50m dist | with a PokeBall (92 left). | 210 EXP earned | Candies: 225 | lat: -33.881284 long: 151.206101
> [19:56:30] (BERRY) Used Razz Berry | 28 remaining
> [19:56:32] (PKMN) (CatchSuccess) | (Normal) Golbat Lvl: 24 CP: (1198/1317) IV: 45.00% | Chance: 12.22% | 16006632.63m dist | with a PokeBall (91 left). | 210 EXP earned | Candies: 49 | lat: -33.862868 long: 151.206920
> [19:56:34] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
> [19:56:38] (PKMN) (CatchEscape) | (Normal) Golbat Lvl: 9 CP: (463/491) IV: 66.00% | Chance: 20.02% | 16006717.71m dist | with a PokeBall (90 left). | lat: -33.860897 long: 151.204826
> [19:56:46] (PKMN) (CatchEscape Attempt #2) | (Normal) Golbat Lvl: 9 CP: (463/491) IV: 66.00% | Chance: 20.02% | 16006717.71m dist | with a PokeBall (89 left). | lat: -33.860897 long: 151.204826

 "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.05,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by nfettinger** [comment]
Duplicate issue
