### ISSUE TITLE
why like this v0.8.1

### ISSUE THREAD

**Issue by freewilly2u** [NECROBOTIO/NecroBot#3962]
![untitled](https://cloud.githubusercontent.com/assets/20922294/17525506/889a57c2-5e95-11e6-9c8a-5489c151d37f.png)

**Comment by theloser** [comment]
688 meters in 42 seconds?
373 meters in 23 seconds?

Your "walking speed" is too high, I suppose.

**Comment by freewilly2u** [comment]
i only set 10/h

**Comment by theloser** [comment]
Have you DisableHumanWalking set to true? Disable it (set it to false).

**Comment by polypalm** [comment]
that keeps going not fixxed

**Comment by freewilly2u** [comment]
it works...thank alot

**Comment by theloser** [comment]
Then close this issue, if it's fixed for you.

**Comment by pelari** [comment]
i'm using version 0.8.1 and using google account
but after click the e.xe file suddenly error like in attachent
when using version 0.8.0 it not happen
https://cloud.githubusercontent.com/assets/20940942/17542718/84e6f602-5ef5-11e6-9031-6db27218ec49.jpg
