### ISSUE TITLE
Pokemon captured using necrobot not shown playing PokemonGO

### ISSUE THREAD

**Issue by nieves24** [NECROBOTIO/NecroBot#3963]
the pokemon captured in the bot is not shown when you open the game on your mobile android phone

**Comment by theloser** [comment]
It takes a little time till the pokemon shows in your app (unless it's transferred by the bot in the meantime :-)).

**Comment by nieves24** [comment]
Sir just checked it now stil my gf's account has only 6 pokemons dunno if
its just me but when they are catching pokemon on the bots theres nothing
like transfered only catch sucess have you checked yours?

On Aug 10, 2016 1:02 AM, "andreas" <notifications@github.com> wrote:
>
> It takes a little time till the pokemon shows in your app (unless it's
transferred by the bot in the meantime :-)).

**Comment by theloser** [comment]
Wait, what? I didn't get it. So you checked your gf's Pokemon Go App and can't find the Pokemon which the bot on your account has catched? I wonder why...

Seriously: Post some screenshots of your bot running, post your config (to pastebin.com), so we can check.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
