### ISSUE TITLE
Looping Unban Message when updated to 0.8.1

### ISSUE THREAD

**Issue by CaptainInfected** [NECROBOTIO/NecroBot#3968]
I'm getting this looping unban message and it's bothering me. I tried changing coords over and over and tried using a VPN. I'm running 3 bots at the same time.

**Comment by Caydenz** [comment]
Should we guess the message?

**Comment by theloser** [comment]
Three bots --> instant softban.

**Comment by CaptainInfected** [comment]
Oh thanks <3

**Comment by RNimra** [comment]
@theloser  any tuts for running more than 2 bots?

**Comment by Caydenz** [comment]
@RNimra Use multiple computers with different IPs.

**Comment by theloser** [comment]
@RNimra Use two bots per IP address max! If you want to run more bots use proxy server (use max two bots per proxy server, too!).

**Comment by Krome333** [comment]
oh thx guys !! 
iv try run 4 bot .. i know now why i get error

**Comment by theloser** [comment]
@CaptainInfected Please close this issue, thanks.
