### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by lbjfanheat6** [NECROBOTIO/NecroBot#3972]
Hi all,

When I open the config folder inside the release folder, the only item that is there is a folder labeled "Translations". How can I config the bot to my liking if I do not have a config file?

Thanks

**Comment by Caydenz** [comment]
Open the bot and the config file will be generated. Use discord for support-related issues.

**Comment by LightAMV** [comment]
Run NecroBot.exe

**Comment by ariyako** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Compiled-Releases

**Comment by lbjfanheat6** [comment]
I don't have an auth file either...here's what I'm seeing
![image](https://cloud.githubusercontent.com/assets/20932274/17525974/0a194ea6-5e1a-11e6-8f7d-45a7093f2bbd.png)

**Comment by smoothrunnings** [comment]
Noobs. Copy the two Necrobot files from the root of your OLD release folder into the new one. Then copy the FILES from located inside the CONFIG folder from the OLD release folder and place them inside the CONFIG folder in the new Release folder. This app requires some know how experience. :)

**Comment by lbjfanheat6** [comment]
I get that part except my OLD release folder doesn't have the two Necrobot files

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
