### ISSUE TITLE
How exactly do I "snipe" a Pokemon?

### ISSUE THREAD

**Issue by LightAMV** [NECROBOTIO/NecroBot#3973]
I don't know how to set it up? How do I get a GPX file? Does it require coding, because I don't know how to code Python at all?

**Comment by Caydenz** [comment]
Snipe is bugged for now. Wait for a future release in order to use this feature.

**Comment by LightAMV** [comment]
@Caydenz I'm fully aware that sniping is bugged from another post, but in case it's fixed, how exactly do I set it up?

**Comment by Furak** [comment]
read the wiki to learn to configure the app, this is not an issue

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
