### ISSUE TITLE
I can't find "zh_hk.json" in folder "Translations"

### ISSUE THREAD

**Issue by sing1222** [NECROBOTIO/NecroBot#3974]
When I read the information about V0.8.1, I found "e9e07f7  Update translation.zh_hk.json (#3653)".
After updated, I didn't find "zh_hk.json" in folder "Translations". Should I download somewhere by myself?
Thanks a lot.

**Comment by nfettinger** [comment]
Try redownloading

**Comment by sing1222** [comment]
@nfettinger I tried download the latest released.zip(0.8.1), I also can't find "zh_hk.json" in folder "Translations".
