### ISSUE TITLE
No Pokestop Nearby

### ISSUE THREAD

**Issue by Eka90** [NECROBOTIO/NecroBot#3975]
Why my bot cant reach any pokestop nearby? am i banned? it just work well before then suddenly the pokestop dissapear

**Comment by Rashk999** [comment]
same

**Comment by smoothrunnings** [comment]
Update your version from 0.80 to 0.81

**Comment by Eka90** [comment]
already use 0.8.1

**Comment by muhfattah** [comment]
you got IP banned bro, what you need to do is changing IP adress. Open Auth.jason, change one number in "deviceID", it should work again.

**Comment by Eka90** [comment]
it still the same... XD

**Comment by jakesmurf** [comment]
Niantic has made it so that it's nearly impossible to run more than one bot at a time it seems.  

Shut down all bots but one, renew your IP (kill modem for 10 mins, use a vpn/proxy, something to that effect), and if that doesn't work wait for the ban to fall off and stop running multiple bots.

**Comment by Eka90** [comment]
i just running one bot.. how long for the ban fall off with that case?

**Comment by Eka90** [comment]
idk why and how... but it work again.. lol

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
