### ISSUE TITLE
This is with 8.1 update, lots of did not find pokemon with snipe

### ISSUE THREAD

**Issue by ochirutenshi** [NECROBOTIO/NecroBot#3976]
photo taken out.

is that articuno?

**Comment by AxiomCro** [comment]
does say so at 00:10:20

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17526118/13fe8000-5e90-11e6-8466-40a4ea47f187.png)


There still lots of did not find, anyone can explain. If it is NATURAL or NOT NATURAL.

**Comment by bossrus** [comment]
same problem. at the start of the bot it works fine, but if included snipe mode - after a while time are white string with "Did not find a Pokemon within the SnipingScanOffset!" appear. and the further - the more of these inscriptions is showing at a one time.
it was not until version 0.8.0.

**Comment by DieHoe** [comment]
Same here...! Verry anoying

**Comment by Royhome** [comment]
"GetOnlyVerifiedSniperInfoFromPokezz": false,
this solve my problem.
I use PogoLocationFeeder.GUI.v0.1.5 for sniping.
Seem that pokezz is not working.

**Comment by Royhome** [comment]
Sorry  should be   "GetSniperInfoFromPokezz": false,
and use PogoLocationFeeder.GUI.v0.1.5 for sniping.

**Comment by ochirutenshi** [comment]
any1 tried what royhome suggest?

and i dont know how to work pogolocationfeeder works with necro bot.
would be nice if you can make guide video on youtube.

**Comment by Royhome** [comment]
@ochirutenshi 
https://github.com/5andr0/PogoLocationFeeder
quite easy to set up
I still have some SnipingScanOffset error but not like crazy

**Comment by ONslaughTT** [comment]
Like royhome said, changing the pokezz info to false solve the error for most snipes attempt

**Comment by ONslaughTT** [comment]
oh no wait, a lot of errors again, its failing a lot again...

**Comment by Royhome** [comment]
@ochirutenshi  me too :(  I turned off sniping for now

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17527384/5b72fc2c-5e95-11e6-9a36-d36c73e77244.png)

LoL, HOPEFULLY it work soon and i will close once its working.

**Comment by ochirutenshi** [comment]
anyway royhome, do i need to download pokesniper 2 or just the pogolocationfeeder and it works like the gif on that page from your pasted link

**Comment by bossrus** [comment]
`"GetSniperInfoFromPokezz": false,
"GetOnlyVerifiedSniperInfoFromPokezz": false,`
but

> [21:01:37] (SNIPER) Sniping a Hitmonchan with Unknown IV at -33,414038,-70,59728...
[21:01:39] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!
[21:01:42] (SNIPER) Sniping a Arcanine with Unknown IV at 19,429916,-99,19791...
[21:01:42] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!

**Comment by Royhome** [comment]
@ochirutenshi   https://github.com/5andr0/PogoLocationFeeder/releases/tag/v0.1.5
here you go   download GUI version  unzip and run

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17527747/cf918654-5e96-11e6-9e4e-dd1c1e22ad8c.png)

Above is the one from the link you give and below is the one i finish install and run now, i didnt see the crosshair mark like the one on the picture. only written CC.

![image](https://cloud.githubusercontent.com/assets/20918437/17527786/ef2fbdf0-5e96-11e6-85f9-dcc53fbc1456.png)

**Comment by Royhome** [comment]
@ochirutenshi  may be that is why we have errors lol

**Comment by ONslaughTT** [comment]
or its just a screenshot of the old gui

**Comment by suzsuzuki** [comment]
pokesnipers problem here. using 0.81
![poke](https://cloud.githubusercontent.com/assets/20933693/17529257/0e06c406-5e49-11e6-95cc-1c99152c8643.png)

**Comment by swc-tine** [comment]
does it have to do with the decimal separator ? ifso someoone must have removed a "System.Globalization.CultureInfo.InvariantCulture"

**Comment by ochirutenshi** [comment]
swc-tine, awesome dude. you just talk a GOD language ^_^ im totally dumbfounded x_x
"System.Globalization.CultureInfo.InvariantCulture"
