### ISSUE TITLE
[FEATURE] Filter/exemption for "MaxPokeballsPerPokemon"

### ISSUE THREAD

**Issue by ltnhat96vn** [NECROBOTIO/NecroBot#3977]
It would be great if the bot would not give up on **specific pokemon** or pokemon **above certain IV**.

I don't mind giving up on a f*cking Pidgey playing hard to get, but I would mind a lot if the bot given up on a 90+ IV Snorlax. Either that bitch runs away, or I'm gonna get its ass into one of my balls.

_(Sorry for language though!)_

**Comment by nfettinger** [comment]
Set your value to a very high number, higher than the number of pokeballs to keep.
