### ISSUE TITLE
No info on meters and seconds for pokestops

### ISSUE THREAD

**Issue by STCOZT** [NECROBOTIO/NecroBot#3982]
It seems my bot just teleports to locations. There is no info like "108 meters will take 8 secs" or that should be stg like that im not sure. Also disablinghumanwalk is false so what am i doing wrong?

**Comment by JohnnyVicious** [comment]
This has been reported before, even duplicate by myself.
That part is made verbose again in 0.8.1

**Comment by STCOZT** [comment]
So i guess we should wait for the next update..

**Comment by JohnnyVicious** [comment]
No, this build is out, I have it running as we speak, just update :-)

**Comment by nfettinger** [comment]
Duplicate issue, I have a change locally that I will push soon
