### ISSUE TITLE
Skipping Pokemon?

### ISSUE THREAD

**Issue by spardadt** [NECROBOTIO/NecroBot#3983]
I keep getting the skipping so-and-so pokemon message. It says it doesn't have enough pokeballs. So should I just leave the bot be and let it get pokeballs and eventually it will start sniping, or is there actually something wrong?

**Comment by DieHoe** [comment]
Change "MinPokeballsToSnipe" to 1

**Comment by spardadt** [comment]
That fixed it. Thanks!
