### ISSUE TITLE
Well i keep getting softbanned 24/7

### ISSUE THREAD

**Issue by wellshit** [NECROBOTIO/NecroBot#3984]
Dont really know why but, my bot cant run 5 minutes without getting softbanned..

**Comment by theloser** [comment]
How many bots are you running?

**Comment by wellshit** [comment]
4?

**Comment by theloser** [comment]
Have you searched for "softban" before you opend an issue?
More than two bots --> instant softban.
**Go away.**

**Comment by jakesmurf** [comment]
I'm down to running 1 bot per MAC address myself.  If I try to run more than that I get IP banned almost instantly.  

I suggest you try using 4 VMs and place each client in it's own machine.

**Comment by wellshit** [comment]
So you think i can use 2 bots on main computer then 2 on another?

**Comment by theloser** [comment]
No.

**Comment by dinosamir** [comment]
i have only 1 bot and with no changes just today i keep having softban every minute:
unban in 1/45
successfully bypassed.

**Comment by dinosamir** [comment]
until 1 hour ago i never had this softban issue, any clue?

**Comment by Pokemongobottttttt** [comment]
Ive successfully ran 4 at once for about an hour.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
