### ISSUE TITLE
Autorename does not work on favorite pokemons

### ISSUE THREAD

**Issue by JohnnyVicious** [NECROBOTIO/NecroBot#3985]
I have autofavorite enabled above 95% IV, autorename happens above 90% IV.
I noticed the autorename does not happen for the favorited pokemon, it only renames the ones with IV from 90 till 94.99%.

**Comment by nfettinger** [comment]
The auto rename requires the name of the pokemon to be the default value.
Please use the Discord chat rooms for general help.

**Comment by JohnnyVicious** [comment]
Hello @nfettinger , I don't think you understood my reported issue correctly.
The name of the pokemon has not been changed when marked favorite.
A Pokemon that is marked as favorite and is above IV 90%, will not get renamed by the autorename feature.

**Comment by xsorifc28** [comment]
Favorited pokemons do not get renamed, even if the name was not changed.

**Comment by JohnnyVicious** [comment]
And I just established that custom names DO get changed so the name does not need to be the default value.

[22:58:15] (INFO) Pokemon Rapidash (10452687319875958028) renamed from Ponyta_94 to Rapidash_94.
[22:58:16] (INFO) Pokemon Nidorino (2171716443351493269) renamed from NidoranMa_90 to Nidorino_90.
[22:58:16] (INFO) Pokemon Hypno (15460691491091657756) renamed from Drowzee_94 to Hypno_94.
