### ISSUE TITLE
NecroBot Client for Pokemon GO has stopped working

### ISSUE THREAD

**Issue by yohanes146** [NECROBOTIO/NecroBot#3986]
![tes](https://cloud.githubusercontent.com/assets/20932573/17526314/e6904634-5e90-11e6-9b1d-65aa4d57c173.png)
Pls help... What's wrong with my config???

**Comment by theloser** [comment]
Sorry, I tried to hack your computer to check your config, but I failed. Can't (and won't) help you.

**Comment by bcowell** [comment]
Download a fresh copy of the latest release. Could be a misspelling/error in your config file.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
