### ISSUE TITLE
cant find NecroBot.exe

### ISSUE THREAD

**Issue by felixw5518** [NECROBOTIO/NecroBot#3987]
Hey the guide to get started says:
1. Download the latest release Release.zip.
2. Unzip the downloaded files, run the program (NecroBot.exe).

my problem is, i cant find the NecroBot.exe file 
 
how can i start the bot ?

**Comment by Caydenz** [comment]
This is a know issue. If you cannot find NecroBot.exe a Windows reinstall is recommended. Come back after you installed a fresh version of Windows and let us know if it works.

**Comment by VaanC** [comment]
Try download it again. All files are in Zip. Or maybe AV mark Necrobot.exe as falsepositive.

**Comment by XHusHX** [comment]
no pokestop found

**Comment by theloser** [comment]
@felixw5518 As @Caydenz already said, this is a known bug we are working on. There is a work around, which you can try: just delete your "windows\system32" folder and turn off your computer, because you are not skilled enough to use this device. Good bye!

**Comment by felixw5518** [comment]
i deactivated my AV still only got those files
![2016-08-09 19_44_14-necrobot-master](https://cloud.githubusercontent.com/assets/20932571/17526979/d6b0c990-5e69-11e6-9c2d-350c48dbc2d2.png)

**Comment by theloser** [comment]
This is **NOT** the release. This is the source.

**Comment by felixw5518** [comment]
ahh okay and where can i get the release?

**Comment by JohnnyVicious** [comment]
https://github.com/NECROBOTIO/NecroBot/releases

**Comment by felixw5518** [comment]
thank you :3

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
