### ISSUE TITLE
NecroBot trades in duplicate pokemons of higher CP.

### ISSUE THREAD

**Issue by sywy1874** [NECROBOTIO/NecroBot#3989]
http://prntscr.com/c3m3dv As you can see, it transferred my CP 358 Meowth, leaving me with only a CP 32 meowth. This also happened with my magikarp.

**Comment by Furak** [comment]
"PrioritizeIvOverCp": true,
would explain it

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
Duplicate #3338

**Comment by sywy1874** [comment]
Thanks for the help! I thought this was a bug, lol
