### ISSUE TITLE
NO POKESTOP FOUND AGAIN

### ISSUE THREAD

**Issue by XHusHX** [NECROBOTIO/NecroBot#3992]
why no pokestop found? niantic change the API again?

**Comment by LightAMV** [comment]
You are probably soft banned or something. Mine works fine. Check the coords and make sure it's correct, then wait a couple minutes and reopen necrobot.

**Comment by crmolinaz** [comment]
it was a server issue but by niantic side. Try again, its working again.

**Comment by XHusHX** [comment]
oke thanks dude

**Comment by bcowell** [comment]
You're most likely IP banned. Possibly from multi-botting or moving a large distance. Wait a few hours. Also this sort of question should be asked on discord, not here.

**Comment by TakRiuto** [comment]
Is happening to me, but in PokeBuddy dont happen! Is Necrobot

**Comment by schadis** [comment]
that is when someone trolls you and posts indian cords to the snipe channel cause india is geoblocket

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
