### ISSUE TITLE
WalkingSpeedInKilometerPerHour not used

### ISSUE THREAD

**Issue by Jaypascompris** [NECROBOTIO/NecroBot#3993]
Well, it seems the parameter value "WalkingSpeedInKilometerPerHour" is not used.

When started, the bot is way too fast, something like 50+ km/h
Even with:
"DisableHumanWalking": false
"WalkingSpeedInKilometerPerHour": 14.0

**Comment by JohnnyVicious** [comment]
I kinda have the same feeling, 113m in 17 seconds is kinda fast or the calculation of the distance is wrong.
My speed is set to 8kph.

**Comment by ilifin** [comment]
It seems the field is misnamed and it's actually defined as meters per second, not kilometers per hour. I set mine to 3.85 and it's now incubating eggs again

**Comment by bcowell** [comment]
Same issue. Value is set as 11km/h and getting ~32km/h from calculations.

**Comment by Jaypascompris** [comment]
As someone said earlier (the answer has been deleted?), the true value of the parameter is not kilometer(s) per hour but meter(s) per second.

Be careful, it could easily lead to a softban with a mistake like that!

**Comment by weedorbeat** [comment]
According code it is khp. In Navigation.cs line 36 the value is divided by 3.6 for mps and with this value continuous calculation. My value in the config is 13 and I had no problems so far.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by nfettinger** [comment]
Verified this is not an issue.

**Comment by weedorbeat** [comment]
Maybe its an issue. With 8.0.1 its really too fast:

[20:26:00] (INFO) Traveling to Pokestop: XXX (63m) (6 seconds)
[20:26:09] (PKMN) (CatchSuccess) XXX
[20:26:14] (POKESTOP) Name: XXX XP: 50, Gems: 0, Items: 1 x ItemRevive, 2 x ItemPokeBall, XXX
[20:26:14] (INFO) Traveling to Pokestop: XXX (78m) (7 seconds)

"WalkingSpeedInKilometerPerHour": 13.0,

63m/(13kpm/3,6) =17,4 <> 6
87m/(13kpm/3,6) = 24,1 <>7

**Comment by bcowell** [comment]
No it isn't. Where'd you get 3.6?
` int intTimeForArrival = (int) ( fortTargetEvent.Distance / ( session.LogicSettings.WalkingSpeedInKilometerPerHour * 0.8 ) );`

63m/(13kpm*0.8) = 63m / 10.4 = 6.05 ~= 6
78m/(13kpm*0.8) = 78 / 10.4 = 7.5 ~= 7

**Comment by weedorbeat** [comment]
See Navigation.cs in line 36

**Comment by bcowell** [comment]
So walking speed is fine. It may just be a different output?

**Comment by weedorbeat** [comment]
in the best case, yes. I'll just pay attention to the time in the logs and will report soon

**Comment by weedorbeat** [comment]
Its seems ok, if I take the difference of the logs it comes out. So only the output must be adjusted.

[20:47:52] (INFO) Traveling to Pokestop: XXX (50m) (4 seconds)
[20:48:04] (POKESTOP) Name: XXX XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemPotion, XXX

12s = 50m/(13kpm/3,6) = 13,84s (12s)

[20:48:05] (INFO) Traveling to Pokestop: XXX (53m) (5 seconds)
[20:48:16] (POKESTOP) Name: XXX XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemGreatBall, 1 x ItemRazzBerry, XXX

11s = 53m/(13kpm/3,6) = 14,67s (11s)

[20:48:16] (INFO) Traveling to Pokestop: XXX (108m) (10 seconds)
[20:48:43] (POKESTOP) Name: XXX XP: 50, Gems: 0, Items: 3 x ItemPokeBall, XXX

27s = 108m/(13kpm/3,6) = 29,90s (27s)
