### ISSUE TITLE
Sniping Question

### ISSUE THREAD

**Issue by LightAMV** [NECROBOTIO/NecroBot#3994]
Yes, the sniping does work, but it's very bugged.

> [10:29:56] (SNIPER) Did not find a Pokemon within the SnipingScanOffset!

20% of the time, it actually catches sniped pokemons. The rest shows this. Is it because I keep moving and it's out of range? Is it because of the timer?

How do I snipe at a certain range limit and how do I make my character stay on that range limit?

**Comment by bossrus** [comment]
same troube have i and https://github.com/NECROBOTIO/NecroBot/issues/3976

too much time is wasted

**Comment by LightAMV** [comment]
@bossrus I got soft banned :P I'll close once working.

**Comment by bossrus** [comment]
no. this is not a softban.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
