### ISSUE TITLE
Empty config folder?

### ISSUE THREAD

**Issue by lbjfanheat6** [NECROBOTIO/NecroBot#3995]
![image](https://cloud.githubusercontent.com/assets/20932274/17526620/d38cc7c0-5e1c-11e6-8f12-3e782b359b15.png)

I followed everything that the compiled release thread said to do but this is all I'm able to see. I don't see any auth.json files or any config files, only thing I can see is translation folder...

**Comment by LightAMV** [comment]
Open NecroBot.exe and set it up from there.

**Comment by theloser** [comment]
RTFM.
https://github.com/NECROBOTIO/NecroBot/wiki/Compiled-Releases

**Comment by lbjfanheat6** [comment]
NecroBot is running right now and still nothing

**Comment by smoothrunnings** [comment]
Copy the config files from your old folder... geez! It worked for and clearly others otherwise we'd see more people complaining about the same thing...

**Comment by theloser** [comment]
What does "nothing" mean? Be more precise!

**Comment by lbjfanheat6** [comment]
![image](https://cloud.githubusercontent.com/assets/20932274/17526746/66823376-5e1d-11e6-975b-4e927819f0db.png)

The NecroBot is running and there are no auth or config files in the config folder...

**Comment by lbjfanheat6** [comment]
@smoothrunnings I don't have any other folder...

**Comment by smoothrunnings** [comment]
@Ibjfanheat6 you need to have kept your old Release folder (version 0.80) otherwise you have to re-download the release.zip and start over again putting in your account info, your long/lat co-ordinates to get going again.

**Comment by theloser** [comment]
The bot can't run without any config.json or auth.json, and because it is running in the background, you are in the wrong folder, I suppose. Prove me wrong.

**Comment by lbjfanheat6** [comment]
@theloser @smoothrunnings You guys are right. I deleted and reinstalled NecroBot and it logged into my account without me having to type it in which means THERE IS an auth out there in my computer but I just can't seem to find it. I searched on my computer for files ending with .json or auth or config but the only files that popped up were unrelated

**Comment by lbjfanheat6** [comment]
![image](https://cloud.githubusercontent.com/assets/20932274/17527419/24f5138a-5e20-11e6-9694-5a51defc3d58.png)
This is an image of thee NecroBot after I deleted and reinstalled

**Comment by JohnnyVicious** [comment]
If the bot is running, go in the Task Manager and look at the Properties of the NecroBot.exe process, this should tell the location of that executable and hence the config folder with your files.

**Comment by theloser** [comment]
Open a command prompt and type:

> find auth.json /s /p

It will find your config files.

**Comment by lbjfanheat6** [comment]
@theloser Says "invalid switch"

**Comment by theloser** [comment]
Hrmpf. Just search your computer for "auth.json" or "config.json".

**Comment by lbjfanheat6** [comment]
@theloser Thanks so much. I was able to do it like you said with the command prompt, but you needed to but cd / [enter] then type dir, then type "find auth.json /s /p". A link to do what I did is here

http://www.dummies.com/computers/operating-systems/windows-xp-vista/how-to-search-for-files-from-the-dos-command-prompt/

Thanks again

**Comment by theloser** [comment]
If you found your files, please close this "issue", thanks.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
