### ISSUE TITLE
Help ... lol

### ISSUE THREAD

**Issue by ciblnt** [NECROBOTIO/NecroBot#3998]
I just downloaded today and im doing my best to set it up but im guessing its the way I have it configured but its not hitting enough pokestops. Like it'll hit one and then snipe forever and im burning thru balls. I need it to hit a pokestop and snipe a few tries then hit another pokestop and so forth. But its like it hits a pokestop then snipes for 20 minutes lol.

**Comment by Caydenz** [comment]
Use Discord for support related issues.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
