### ISSUE TITLE
Check inventory prior to pokestop

### ISSUE THREAD

**Issue by Sicarii** [NECROBOTIO/NecroBot#4001]
![invfull](https://cloud.githubusercontent.com/assets/20932673/17526816/cfb4ab8a-5e36-11e6-849f-a8f2d63f7fd0.gif)

Wouldn't it make more sense to check inventory at the point of travelling to a pokestop to avoid 'inventory is full, no items looted'?

**Comment by spamfighter82** [comment]
well if you go play outside you also wont check your inventory before using a pokestop

**Comment by Sicarii** [comment]
why not?

**Comment by theloser** [comment]
You still get the XP.

**Comment by nfettinger** [comment]
Duplicate issue.
