### ISSUE TITLE
[0.8.1] Snipe list is not clearing

### ISSUE THREAD

**Issue by dzik87** [NECROBOTIO/NecroBot#4003]
When pokemon is not found in location, list does not get cleared and it loops all the time on saved entries.

**Comment by jimmyjoneser** [comment]
I just reverted to 0.7.6 because it was the last version the snipingscanoffset worked for me, and now that version is even having the same issue of constant looping of the sniper, finding nothing. No matter what the config or bot version is, this seems to now be a consistent problem. Is it on the pogofeeder side? It wouldn't be so bad but my bot will stop doing other tasks and get caught in a sniper loop that gets longer and longer before player action resumes

**Comment by classmate01** [comment]
What version of Pogofeeder are you now using after reverting back to 0.7.6?

**Comment by jimmyjoneser** [comment]
I was still using 1.5, which I was using when I initially set up the bot and sniper. Anyways I gave up on that too and am now back on 0.8.1 with feeder 1.5. at least now it only unsuccessfully snipes about 5-10 times before going back to pokestops and the loops are no longer infinite.. I'm also now seeing more successful sniping in spurts, so it definitely works, just sporadically at best. Glad to see some progress anyway!

**Comment by classmate01** [comment]
Sounds pretty good to me. I will update my version to 0.8.1. and see the changes :)
Thanks buddy!

**Comment by NeCx** [comment]
Yes it is sniping the same coordinates over and over again. It should be fixed.
http://i.imgur.com/JA4RSkF.jpg

**Comment by Sociopaat** [comment]
yep same here, keeps scanning old coordinates
https://gyazo.com/90be9f3db125d14b3b570a7d82196dc0

**Comment by Marsinator** [comment]
[20:57] dzik: @Mars run pokeffeder
[20:57] dzik: let necrobot grab list
[20:57] dzik: turn off feeder
[20:57] dzik: it looks all the time on same coords and pokemons
[20:57] dzik: loops*
[20:57] Mars: and if you keep the feeder active?
[20:57] dzik: same
[20:58] dzik: but list get bigger and bigger

**Comment by lucabravi** [comment]
I quote the request, it is unusable

**Comment by djdookie** [comment]
Why not implement a sniping queue instead of a list. We want to work with a clear FIFO here, right? #4109

**Comment by deduijk** [comment]
I think there is more then 1 issue:
- decimal point problem (trying to locate pokemon without the decimal separator in it)
I think this is a mix-up with the decimal separator between regions.
- pokezz isn't always giving information. It seems sometimes is does, then necro picks it up correctly, when pokezz doesn't respond old information seems to be used (or loaded from pokezz, that is unclear)
- The snipe doesn't SEEM to work around locations. (setting some snipe coordinates plus `SnipingScanOffset: 0.05` doesn't bring up any (of course this could be correct, i haven't checked if there is indeed no pokemon there).

**Comment by dzik87** [comment]
Seems like that problem is solved in 0.8.4. At least list get cleared with visited ones.
Still some of them are not found even from pages like pokesnipers but so long as it do not loop it is much better.

**Comment by dddbliss** [comment]
Solved in 0.8.4.
