### ISSUE TITLE
Transferring Pokemon

### ISSUE THREAD

**Issue by Apexcery** [NECROBOTIO/NecroBot#4004]
I understand that this is an issue with my config, but I have never had this issue before and I am not sure what to change to have it work as it used to. It seems to be always transferring my Pokemon that are below the CP stated in the config but I want it to only transfer the one's with a lower CP than my highest of that Pokemon. If anyone could help, I'd greatly appreciate it.

[http://prnt.sc/c3mcsf](url)

My Config: [http://pastebin.com/B4RVgEP6](url)

**Comment by benda95280** [comment]
For me, changed 
  "KeepMinDuplicatePokemon": 0 **to** 1
solved the same problems

**Comment by Apexcery** [comment]
That fixed it! Thanks! Shame I didn't notice until it had been running for a while.
