### ISSUE TITLE
Lucky Egg 

### ISSUE THREAD

**Issue by kchan83** [NECROBOTIO/NecroBot#4005]
According to the FAQ, you can open the app with location services disabled to use the Lucky Egg for XP boost. However, when I run the the app it won't let me use the egg as the GPS is disabled.

Is there anyway i can activate the egg without enabling the location services 

Thanks!

**Comment by theloser** [comment]
First of all I am **very pleased you read the FAQ!**

Unfortunately the FAQ and the wiki are kind of "outdated". I think Niantic changed how some mechanics work and therefore I don't know a way how you manually can activate a lucky egg.

Have you tried to enable "UseLuckyEggConstantly" in your config.json? I never used lucky eggs with the bot, but it should immediately activate a lucky egg as soon as you restart the bot.

**Comment by kchan83** [comment]
thanks that works!
