### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Cleaf1991** [NECROBOTIO/NecroBot#4007]
Sorry my english is Bad, please try to understand :D 

i use a new Version but i dont have very much pokemon, the bot send 20 pokemon direct, and now i have only 30, and my sister have 89. how? bot catch one pokemon and send this direct to professor. And i use the bot, 2 days and i get really crap pokemon. 
and all times stay: Softban if my charakter get the pokeStop.
he Catch Spearow and set this direct.
he catch Squirtle and set this direct.
he catch Pidgey and set this direct no more Developments.

yesterday i use the bot and was perfekt, update to update It became getting worse.

and now i have a new Version but Nothing has changed.

i hope your can help me. Thanks and sorry for my english :D

**Comment by theloser** [comment]
Please go to discord to get help, your configuration is most likely set to transfer all (weak) pokemons.
And please close this issue.

**Comment by spamfighter82** [comment]
check your config for
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,

if this doesn't help, ask in the discord channel for more help

**Comment by JohnnyVicious** [comment]
Discord (Chat & Get Help!): https://discord.gg/VXKxNFr

**Comment by Cleaf1991** [comment]
give german speaker? :D

**Comment by theloser** [comment]
@Cleaf1991 Was?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
