### ISSUE TITLE
PokemonsTransferFilter can't all keep?

### ISSUE THREAD

**Issue by karisckm** [NECROBOTIO/NecroBot#4009]
2a5b850 Transfer keep logic will now use microsoft expression parser for string expression evaluation, backward compatible saved. In future, it wiil help to remove all keep* params from global and per Pokmon TransferFilter and replace it with one string expression with user already defined constants in *old format.

How can I set back to all keep when the Pokmon over the setting IV?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
