### ISSUE TITLE
softban, but only on gym system

### ISSUE THREAD

**Issue by ayuayutesa** [NECROBOTIO/NecroBot#4010]
sry, i think i got banned.. but just only on gym system.. if i enter the gym.. it's getting error.. could someone fix it? :3

for catching pokemon.. it's still work, but not for the gym :3

**Comment by jrwtf** [comment]
what kind of gym system ? are you talking about

**Comment by ayuayutesa** [comment]
i go to the gym.. and can't enter it.. can't fight

**Comment by TheBorna** [comment]
you can't have bot running and playing the game normal at the same time.

**Comment by ayuayutesa** [comment]
i close the bot after going work, and do normal playing after it.. but it can't enter a gym :3

**Comment by ayuayutesa** [comment]
are someone made an unbanned for this error?

**Comment by classmate01** [comment]
Try to modify your bot long/lat to your original location and let it run to remove the softban, then try again accessing the gym

**Comment by ayuayutesa** [comment]
ok, i'll try..

**Comment by ayuayutesa** [comment]
it's still can't enter it -,-" have pokemon with high CP but can't doing fight on gym? :v

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by classmate01** [comment]
Look's weird, I also experienced that yesterday but I managed to get bypass the softban.
BTW after you change your bot's location to your original position, have you checked if your account can get stuffs in pokestop?

**Comment by ayuayutesa** [comment]
i'm still can loot item or catch pokemon.. but for entering gym.. -_-"
