### ISSUE TITLE
Noob and Beginner question || How can I change the setting

### ISSUE THREAD

**Issue by aradzu10** [NECROBOTIO/NecroBot#4012]
Can I change the setting?
Like if I want that the bot will not evolve pokemons or someting like that...

**Comment by bcowell** [comment]
Read the wiki. And questions should taken to discord.

**Comment by jrwtf** [comment]
yes u can just enter in the folder called config and open a filled called like this config.json (using note pad or word pad )

**Comment by MetaExtreme** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Config

**Comment by JohnnyVicious** [comment]
Discord (Chat & Get Help!): https://discord.gg/VXKxNFr

**Comment by aradzu10** [comment]
Thanks you all!!! help a lot.
Closed.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
