### ISSUE TITLE
create a more statistics.

### ISSUE THREAD

**Issue by bossrus** [NECROBOTIO/NecroBot#4013]
very interesting seen a count of pokestop and count of successful catches in the window title.

thanx for your job. necrobot - the best of :)

**Comment by TakRiuto** [comment]
Nice idea :D

**Comment by theloser** [comment]
Just use the Telegram function:
```
----- LVL 27 | xxxxxx ----- 
 Experience: 111xyz/1350000 
 Pokemons caught: 2614 
 Pokemons deployed: 0 
 Pokestops visited: 4836 
 Eggs hatched: 4836 
 Pokemons envolved: 52 
 Pokedex entries: 455 
 KM walked: 106
```
Some values are wrong though, they will be fixed I suppose (or maybe they already have, I am still using 0.8.0).

**Comment by nfettinger** [comment]
The title is already too cluttered.
