### ISSUE TITLE
Necrobot 0.8.1 Transferring all pokemon, whats up with this?

### ISSUE THREAD

**Issue by mipana1988** [NECROBOTIO/NecroBot#4016]

**Comment by burntable** [comment]
bot 2 stronk 4 u

**Comment by Rashk999** [comment]
retype from 
"KeepMinDuplicatePokemon": **0,**
to
**"KeepMinDuplicatePokemon": 1,**

**Comment by mipana1988** [comment]
Worked thanks Rashk.

**Comment by classmate01** [comment]
Check your config as always when updating to new version.

Try to at least check the value of these
  "KeepMinCp": 1000,
  "KeepMinIvPercentage": 60.0,
  "KeepMinLvl": 15,

Also these

  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by bomba88** [comment]
Hey @mipana1988, after transferring all pokemons by necrobot and after changing "KeepMinDuplicatePokemon": 1, did you get your pokemons back?

**Comment by Rashk999** [comment]
@bomba88 no, the pokemons are gone, but now the bot is leaving 1 piece of all pokemon

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help. If you find a specific bug, please open a new issue.
