### ISSUE TITLE
[BIG REQUEST] NecroBot for Android

### ISSUE THREAD

**Issue by MetaExtreme** [NECROBOTIO/NecroBot#4018]
It would be very nice to get NecroBot for Android so I (we) don't have to run my (our) PC 24/7

**Comment by mdreamx** [comment]
Plz do this... :)

**Comment by JTBomb007** [comment]
That would be amazing!

How ever it doesn't really bother me.

**Comment by Andrerm124** [comment]
Probably not a priority right now I don't think

**Comment by nfettinger** [comment]
This is too big of a change to port over. Number one reason: the RocketAPI would not be supported.
