### ISSUE TITLE
google auth

### ISSUE THREAD

**Issue by mdreamx** [NECROBOTIO/NecroBot#4019]
Hi 

Im having problem using my main Google account.

I have no problem with PTC accounts, but when i try with my Google account, it's just stuck on:

- Perfect! You already have the newest Version 0.8.0
- Logging in using Google

My auth: (With my mail and password hidden)
{
  "AuthType": "google",
  "GoogleUsername": "***test@gmail.com***",
  "GooglePassword": "***testpassword***",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "nexus-6p",
  "DeviceId": "1534f0ff4d8f9ff6",
  "AndroidBoardName": "angler",
  "AndroidBootloader": "angler-03.52",
  "DeviceBrand": "google",
  "DeviceModel": "Nexus 6P",
  "DeviceModelIdentifier": "angler",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "Huawei",
  "HardwareModel": "Nexus 6P",
  "FirmwareBrand": "angler",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "google/angler/angler:6.0.1/MTC19X/2960136:user/release-keys"
}

**Comment by nfettinger** [comment]
This could be a server issue. Please seek additional help on the Discord chat channels.
