### ISSUE TITLE
change color of text for poke stops

### ISSUE THREAD

**Issue by smoothrunnings** [NECROBOTIO/NecroBot#4023]
When poke stops won't drop anything the txt changes to a deep red which I can barely see on my display. it would be nice to see it in a different color, maybe PINK or some other shade not used. :)

Thanks!

**Comment by Ambushed91** [comment]
Im working on something for the text

**Comment by TheBorna** [comment]
#4026, done. Now it's red.

**Comment by TheBorna** [comment]
![image](https://cloud.githubusercontent.com/assets/18235651/17528488/f944fa5c-5e6f-11e6-9e7e-0f39c61e4efa.png)

**Comment by smoothrunnings** [comment]
@TheBorna looks a lot better! :)

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
