### ISSUE TITLE
Another Noob Question || tracker

### ISSUE THREAD

**Issue by aradzu10** [NECROBOTIO/NecroBot#4025]
I didn't understand from the wiki if there is a Pokemons tracker.
Like if I add to a list Dratini and time to catch (or something...), it will look for dratini (Like PokeMap or something) and catch the number I told him to do. And if there isn't something like that, Can you pls make?

**Comment by saahilz** [comment]
please visit the Discord for a chat, this place is only for issues

**Comment by goobs93123** [comment]
where is discord?

**Comment by aradzu10** [comment]
https://discord.gg/VXKxNFr

**Comment by saahilz** [comment]
click on the code tab and the first link will take you to the Chat

**Comment by MetaExtreme** [comment]
use pokeZZ

**Comment by aradzu10** [comment]
Can you send a Link?

**Comment by aradzu10** [comment]
From some reson, it dosent work for me now... I will try later.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
