### ISSUE TITLE
Razz berries getting used indiscriminately

### ISSUE THREAD

**Issue by fkyl** [NECROBOTIO/NecroBot#4029]
Necrobot uses razz berries on Pokemon with low ivs and high catch rates under these settings (was working properly on v0.7.6):

  "UseBerriesMinCp": 3000,
  "UseBerriesMinIv": 0.95,
  "UseBerriesBelowCatchProbability": 0.1,
  "UseBerriesOperator": "or",

**Comment by random189268** [comment]
I believe the MinIv setting should be "95" instead of ".95". For example, mine is set to 90.0 for 90% or greater IV berry usage.

**Comment by fkyl** [comment]
Nice catch, works perfectly now.
