### ISSUE TITLE
Mass evolve messing up again!

### ISSUE THREAD

**Issue by JustRegisteredToSayThis** [NECROBOTIO/NecroBot#4031]
> [20:22:21] [Evolves] Potential Evolves: 166
> [20:22:22] Used Lucky Egg, remaining: 4
> [20:22:22] Pidgey successfully for 1000xp
> [20:23:11] Weedle successfully for 1000xp
> [20:23:11] Pidgey successfully for 1000xp
> [20:23:19] Weedle successfully for 1000xp
> [20:23:20] Caterpie successfully for 1000xp
> [20:23:20] Weedle successfully for 1000xp
> [20:23:22] Caterpie successfully for 1000xp
> [20:23:23] Weedle successfully for 1000xp
> [20:23:28] Caterpie successfully for 1000xp
> [20:23:29] Weedle successfully for 1000xp
> [20:23:29] Caterpie successfully for 1000xp
> [20:23:31] Weedle successfully for 1000xp
> [20:23:32] Caterpie successfully for 1000xp
> [20:23:33] Weedle successfully for 1000xp
> [20:23:34] Caterpie successfully for 1000xp
> [20:23:36] Weedle successfully for 1000xp
> [20:23:38] Caterpie successfully for 1000xp
> [20:23:38] Weedle successfully for 1000xp
> [20:23:41] Caterpie successfully for 1000xp
> [20:23:42] Weedle successfully for 1000xp
> [20:23:42] Caterpie successfully for 1000xp
> [20:23:44] Weedle successfully for 1000xp
> [20:23:46] Caterpie successfully for 1000xp
> [20:23:47] Weedle successfully for 1000xp
> [20:23:48] Caterpie successfully for 1000xp
> [20:23:49] Weedle successfully for 1000xp
> [20:23:54] Caterpie successfully for 1000xp
> [20:23:54] Weedle successfully for 1000xp
> [20:23:58] Pidgeotto   	- CP:  914  IV:  51.76%   [Best CP:  939  IV:  63.52%] (Candies: 101)
> [20:23:58] Pidgeotto   	- CP:  914  IV:  51.76%   [Best CP:  939  IV:  63.52%] (Candies: 102)
> [20:23:59] Pidgeotto   	- CP:  897  IV:  28.54%   [Best CP:  939  IV:  63.52%] (Candies: 103)
> [20:23:59] Pidgeotto   	- CP:  893  IV:  41.52%   [Best CP:  939  IV:  63.52%] (Candies: 104)
> [20:24:00] Pidgeotto   	- CP:  890  IV:  55.15%   [Best CP:  939  IV:  63.52%] (Candies: 105)
> [20:24:00] Pidgeotto   	- CP:  885  IV:  52.57%   [Best CP:  939  IV:  63.52%] (Candies: 106)
> [20:24:01] Pidgeotto   	- CP:  884  IV:  37.04%   [Best CP:  939  IV:  63.52%] (Candies: 107)
> [20:24:01] Pidgeotto   	- CP:  883  IV:  22.02%   [Best CP:  939  IV:  63.52%] (Candies: 108)
> [20:24:02] Pidgeotto   	- CP:  882  IV:  36.11%   [Best CP:  939  IV:  63.52%] (Candies: 109)
> [20:24:02] Pidgeotto   	- CP:  875  IV:  32.63%   [Best CP:  939  IV:  63.52%] (Candies: 110)
> [20:24:03] Pidgeotto   	- CP:  872  IV:  46.30%   [Best CP:  939  IV:  63.52%] (Candies: 111)
> [20:24:06] Pidgeotto   	- CP:  863  IV:  26.88%   [Best CP:  939  IV:  63.52%] (Candies: 112)
> [20:24:07] Pidgeotto   	- CP:  844  IV:  48.05%   [Best CP:  939  IV:  63.52%] (Candies: 113)
> [20:24:07] Pidgeotto   	- CP:  844  IV:  32.08%   [Best CP:  939  IV:  63.52%] (Candies: 114)
> [20:24:08] Pidgeotto   	- CP:  844  IV:  32.02%   [Best CP:  939  IV:  63.52%] (Candies: 115)
> [20:24:08] Pidgeotto   	- CP:  837  IV:  28.87%   [Best CP:  939  IV:  63.52%] (Candies: 116)
> [20:24:09] Pidgeotto   	- CP:  837  IV:  28.54%   [Best CP:  939  IV:  63.52%] (Candies: 117)
> [20:24:09] Pidgeotto   	- CP:  836  IV:  28.37%   [Best CP:  939  IV:  63.52%] (Candies: 118)
> [20:24:10] Pidgeotto   	- CP:  835  IV:  43.47%   [Best CP:  939  IV:  63.52%] (Candies: 119)
> [20:24:10] Pidgeotto   	- CP:  834  IV:  27.26%   [Best CP:  939  IV:  63.52%] (Candies: 120)
> [20:24:11] Pidgeotto   	- CP:  832  IV:  41.50%   [Best CP:  939  IV:  63.52%] (Candies: 121)
> [20:24:11] Pidgeotto   	- CP:  832  IV:  41.50%   [Best CP:  939  IV:  63.52%] (Candies: 122)
> [20:24:12] Pidgeotto   	- CP:  831  IV:  11.09%   [Best CP:  939  IV:  63.52%] (Candies: 123)
> [20:24:12] Pidgeotto   	- CP:  826  IV:  38.68%   [Best CP:  939  IV:  63.52%] (Candies: 124)
> [20:24:13] Pidgeotto   	- CP:  823  IV:  53.46%   [Best CP:  939  IV:  63.52%] (Candies: 125)
> [20:24:13] Pidgeotto   	- CP:  822  IV:  36.54%   [Best CP:  939  IV:  63.52%] (Candies: 126)
> [20:24:14] Pidgeotto   	- CP:  817  IV:  33.69%   [Best CP:  939  IV:  63.52%] (Candies: 127)
> [20:24:14] Pidgeotto   	- CP:  813  IV:  31.67%   [Best CP:  939  IV:  63.52%] (Candies: 128)
> [20:24:15] Pidgeotto   	- CP:  808  IV:  45.12%   [Best CP:  939  IV:  63.52%] (Candies: 129)
> [20:24:21] Pidgeotto   	- CP:  807  IV:  28.68%   [Best CP:  939  IV:  63.52%] (Candies: 130)
> [20:24:22] Pidgeotto   	- CP:  804  IV:  43.25%   [Best CP:  939  IV:  63.52%] (Candies: 131)
> [20:24:23] Pidgeotto   	- CP:  796  IV:  38.71%   [Best CP:  939  IV:  63.52%] (Candies: 132)
> [20:24:23] Pidgeotto   	- CP:  788  IV:  51.89%   [Best CP:  939  IV:  63.52%] (Candies: 133)
> [20:24:24] Pidgeotto   	- CP:  786  IV:  33.51%   [Best CP:  939  IV:  63.52%] (Candies: 134)
> [20:24:24] Pidgeotto   	- CP:  785  IV:  17.24%   [Best CP:  939  IV:  63.52%] (Candies: 135)
> [20:24:25] Pidgeotto   	- CP:  778  IV:  28.87%   [Best CP:  939  IV:  63.52%] (Candies: 136)
> [20:24:25] Pidgeotto   	- CP:  776  IV:  12.64%   [Best CP:  939  IV:  63.52%] (Candies: 137)
> [20:24:25] Pidgeotto   	- CP:  771  IV:  25.41%   [Best CP:  939  IV:  63.52%] (Candies: 138)
> [20:24:27] Pidgeotto   	- CP:  768  IV:  58.30%   [Best CP:  939  IV:  63.52%] (Candies: 139)
> [20:24:27] Pidgeotto   	- CP:  768  IV:  23.86%   [Best CP:  939  IV:  63.52%] (Candies: 140)
> [20:24:28] Pidgeotto   	- CP:  758  IV:  34.91%   [Best CP:  939  IV:  63.52%] (Candies: 141)
> [20:24:28] Pidgeotto   	- CP:  756  IV:  51.60%   [Best CP:  939  IV:  63.52%] (Candies: 142)
> [20:24:29] Pidgeotto   	- CP:  753  IV:  31.91%   [Best CP:  939  IV:  63.52%] (Candies: 143)
> [20:24:29] Pidgeotto   	- CP:  751  IV:  48.16%   [Best CP:  939  IV:  63.52%] (Candies: 144)
> [20:24:30] Pidgeotto   	- CP:  748  IV:  46.43%   [Best CP:  939  IV:  63.52%] (Candies: 145)
> [20:24:30] Pidgeotto   	- CP:  746  IV:  28.14%   [Best CP:  939  IV:  63.52%] (Candies: 146)
> [20:24:31] Pidgeotto   	- CP:  737  IV:  39.99%   [Best CP:  939  IV:  63.52%] (Candies: 147)
> [20:24:31] Pidgeotto   	- CP:  728  IV:  17.56%   [Best CP:  939  IV:  63.52%] (Candies: 148)
> [20:24:32] Pidgeotto   	- CP:  723  IV:  32.08%   [Best CP:  939  IV:  63.52%] (Candies: 149)
> [20:24:32] Pidgeotto   	- CP:  722  IV:  50.06%   [Best CP:  939  IV:  63.52%] (Candies: 150)
> [20:24:33] Pidgeotto   	- CP:  717  IV:  46.73%   [Best CP:  939  IV:  63.52%] (Candies: 151)
> [20:24:33] Pidgeotto   	- CP:  717  IV:  28.52%   [Best CP:  939  IV:  63.52%] (Candies: 152)
> [20:24:34] Pidgeotto   	- CP:  715  IV:  27.07%   [Best CP:  939  IV:  63.52%] (Candies: 153)
> [20:24:35] Pidgeotto   	- CP:  711  IV:  42.96%   [Best CP:  939  IV:  63.52%] (Candies: 154)
> [20:24:35] Pidgeotto   	- CP:  708  IV:  41.36%   [Best CP:  939  IV:  63.52%] (Candies: 155)
> [20:24:36] Pidgeotto   	- CP:  702  IV:  37.70%   [Best CP:  939  IV:  63.52%] (Candies: 156)
> [20:24:36] Pidgeotto   	- CP:  700  IV:  36.20%   [Best CP:  939  IV:  63.52%] (Candies: 157)
> [20:24:37] Pidgeotto   	- CP:  698  IV:  17.41%   [Best CP:  939  IV:  63.52%] (Candies: 158)
> [20:24:37] Pidgeotto   	- CP:  695  IV:  33.51%   [Best CP:  939  IV:  63.52%] (Candies: 159)
> [20:24:38] Pidgeotto   	- CP:  695  IV:  33.50%   [Best CP:  939  IV:  63.52%] (Candies: 160)
> [20:24:39] Pidgeotto   	- CP:  690  IV:  30.48%   [Best CP:  939  IV:  63.52%] (Candies: 161)
> [20:24:39] Pidgeotto   	- CP:  689  IV:  29.33%   [Best CP:  939  IV:  63.52%] (Candies: 162)
> [20:24:39] Pidgeotto   	- CP:  688  IV:  48.40%   [Best CP:  939  IV:  63.52%] (Candies: 163)
> [20:24:40] Pidgeotto   	- CP:  686  IV:  46.92%   [Best CP:  939  IV:  63.52%] (Candies: 164)
> [20:24:41] Pidgeotto   	- CP:  686  IV:  46.84%   [Best CP:  939  IV:  63.52%] (Candies: 165)
> [20:24:42] Pidgeotto   	- CP:  680  IV:  23.85%   [Best CP:  939  IV:  63.52%] (Candies: 166)
> [20:24:42] Pidgeotto   	- CP:  678  IV:  41.91%   [Best CP:  939  IV:  63.52%] (Candies: 167)
> [20:24:43] Pidgeotto   	- CP:  673  IV:  38.71%   [Best CP:  939  IV:  63.52%] (Candies: 168)
> [20:24:43] Pidgeotto   	- CP:  672  IV:  58.57%   [Best CP:  939  IV:  63.52%] (Candies: 169)
> [20:24:44] Pidgeotto   	- CP:  672  IV:  18.95%   [Best CP:  939  IV:  63.52%] (Candies: 170)
> [20:24:44] Pidgeotto   	- CP:  672  IV:  18.93%   [Best CP:  939  IV:  63.52%] (Candies: 171)
> [20:24:45] Pidgeotto   	- CP:  671  IV:  37.00%   [Best CP:  939  IV:  63.52%] (Candies: 172)
> [20:24:45] Pidgeotto   	- CP:  661  IV:  51.16%   [Best CP:  939  IV:  63.52%] (Candies: 173)
> [20:24:46] Pidgeotto   	- CP:  659  IV:  71.55%   [Best CP:  939  IV:  63.52%] (Candies: 174)
> [20:24:46] Pidgeotto   	- CP:  659  IV:  49.73%   [Best CP:  939  IV:  63.52%] (Candies: 175)
> [20:24:47] Pidgeotto   	- CP:  656  IV:   9.45%   [Best CP:  939  IV:  63.52%] (Candies: 176)
> [20:24:48] Pidgeotto   	- CP:  653  IV:  25.56%   [Best CP:  939  IV:  63.52%] (Candies: 177)
> [20:24:48] Pidgeotto   	- CP:  653  IV:  25.50%   [Best CP:  939  IV:  63.52%] (Candies: 178)
> [20:24:49] Pidgeotto   	- CP:  650  IV:  43.52%   [Best CP:  939  IV:  63.52%] (Candies: 179)
> [20:24:49] Pidgeotto   	- CP:  644  IV:  39.86%   [Best CP:  939  IV:  63.52%] (Candies: 180)
> [20:24:50] Pidgeotto   	- CP:  640  IV:  17.54%   [Best CP:  939  IV:  63.52%] (Candies: 181)
> [20:24:50] Pidgeotto   	- CP:  639  IV:  36.52%   [Best CP:  939  IV:  63.52%] (Candies: 182)
> [20:24:51] Pidgeotto   	- CP:  638  IV:  35.36%   [Best CP:  939  IV:  63.52%] (Candies: 183)
> [20:24:51] Pidgeotto   	- CP:  637  IV:  34.97%   [Best CP:  939  IV:  63.52%] (Candies: 184)
> [20:24:52] Pidgeotto   	- CP:  635  IV:  33.29%   [Best CP:  939  IV:  63.52%] (Candies: 185)
> [20:24:53] Pidgeotto   	- CP:  626  IV:  48.35%   [Best CP:  939  IV:  63.52%] (Candies: 186)
> [20:24:54] Pidgeotto   	- CP:  621  IV:  45.31%   [Best CP:  939  IV:  63.52%] (Candies: 187)
> [20:24:54] Pidgeotto   	- CP:  615  IV:  63.58%   [Best CP:  939  IV:  63.52%] (Candies: 188)
> [20:24:55] Pidgeotto   	- CP:  612  IV:  38.58%   [Best CP:  939  IV:  63.52%] (Candies: 189)
> [20:24:56] Pidgeotto   	- CP:  611  IV:  17.28%   [Best CP:  939  IV:  63.52%] (Candies: 190)
> [20:24:56] Pidgeotto   	- CP:  609  IV:  36.73%   [Best CP:  939  IV:  63.52%] (Candies: 191)
> [20:24:56] Pidgeotto   	- CP:  607  IV:  35.26%   [Best CP:  939  IV:  63.52%] (Candies: 192)
> [20:24:57] Pidgeotto   	- CP:  605  IV:  33.51%   [Best CP:  939  IV:  63.52%] (Candies: 193)
> [20:24:58] Pidgeotto   	- CP:  600  IV:  30.48%   [Best CP:  939  IV:  63.52%] (Candies: 194)
> [20:24:58] Pidgeotto   	- CP:  599  IV:  51.85%   [Best CP:  939  IV:  63.52%] (Candies: 195)
> [20:24:58] Pidgeotto   	- CP:  597  IV:  49.97%   [Best CP:  939  IV:  63.52%] (Candies: 196)
> [20:24:59] Pidgeotto   	- CP:  597  IV:  28.14%   [Best CP:  939  IV:  63.52%] (Candies: 197)
> [20:25:00] Pidgeotto   	- CP:  594  IV:  48.25%   [Best CP:  939  IV:  63.52%] (Candies: 198)
> [20:25:01] Pidgeotto   	- CP:  592  IV:  46.79%   [Best CP:  939  IV:  63.52%] (Candies: 199)
> [20:25:01] Kakuna      	- CP:  331  IV:  53.29%   [Best CP:  359  IV:  66.60%] (Candies: 108)
> [20:25:02] Kakuna      	- CP:  326  IV:  39.87%   [Best CP:  359  IV:  66.60%] (Candies: 109)
> [20:25:02] Kakuna      	- CP:  320  IV:  35.54%   [Best CP:  359  IV:  66.60%] (Candies: 110)
> [20:25:03] Kakuna      	- CP:  311  IV:  28.02%   [Best CP:  359  IV:  66.60%] (Candies: 111)
> [20:25:03] Kakuna      	- CP:  310  IV:  35.96%   [Best CP:  359  IV:  66.60%] (Candies: 112)
> [20:25:04] Kakuna      	- CP:  307  IV:  25.54%   [Best CP:  359  IV:  66.60%] (Candies: 113)
> [20:25:04] Kakuna      	- CP:  307  IV:  25.39%   [Best CP:  359  IV:  66.60%] (Candies: 114)
> [20:25:05] Kakuna      	- CP:  306  IV:  24.10%   [Best CP:  359  IV:  66.60%] (Candies: 115)
> [20:25:05] Kakuna      	- CP:  304  IV:  40.46%   [Best CP:  359  IV:  66.60%] (Candies: 116)
> [20:25:06] Kakuna      	- CP:  301  IV:  38.08%   [Best CP:  359  IV:  66.60%] (Candies: 117)
> [20:25:06] Kakuna      	- CP:  300  IV:  28.20%   [Best CP:  359  IV:  66.60%] (Candies: 118)
> [20:25:07] Kakuna      	- CP:  298  IV:  45.30%   [Best CP:  359  IV:  66.60%] (Candies: 119)
> [20:25:07] Kakuna      	- CP:  298  IV:  26.73%   [Best CP:  359  IV:  66.60%] (Candies: 120)
> [20:25:08] Kakuna      	- CP:  298  IV:  17.87%   [Best CP:  359  IV:  66.60%] (Candies: 121)
> [20:25:09] Kakuna      	- CP:  295  IV:  23.93%   [Best CP:  359  IV:  66.60%] (Candies: 122)
> [20:25:10] Kakuna      	- CP:  285  IV:  24.45%   [Best CP:  359  IV:  66.60%] (Candies: 123)
> [20:25:10] Kakuna      	- CP:  279  IV:  19.20%   [Best CP:  359  IV:  66.60%] (Candies: 124)
> [20:25:11] Kakuna      	- CP:  278  IV:  18.71%   [Best CP:  359  IV:  66.60%] (Candies: 125)
> [20:25:11] Kakuna      	- CP:  277  IV:  26.89%   [Best CP:  359  IV:  66.60%] (Candies: 126)
> [20:25:12] Kakuna      	- CP:  274  IV:  24.03%   [Best CP:  359  IV:  66.60%] (Candies: 127)
> [20:25:12] Kakuna      	- CP:  273  IV:  14.32%   [Best CP:  359  IV:  66.60%] (Candies: 128)
> [20:25:13] Kakuna      	- CP:  272  IV:  42.63%   [Best CP:  359  IV:  66.60%] (Candies: 129)
> [20:25:13] Kakuna      	- CP:  268  IV:  19.09%   [Best CP:  359  IV:  66.60%] (Candies: 130)
> [20:25:14] Kakuna      	- CP:  263  IV:  33.36%   [Best CP:  359  IV:  66.60%] (Candies: 131)
> [20:25:14] Kakuna      	- CP:  256  IV:  27.32%   [Best CP:  359  IV:  66.60%] (Candies: 132)
> [20:25:15] Kakuna      	- CP:  255  IV:   7.62%   [Best CP:  359  IV:  66.60%] (Candies: 133)
> [20:25:16] Kakuna      	- CP:  252  IV:  45.35%   [Best CP:  359  IV:  66.60%] (Candies: 134)
> [20:25:16] Kakuna      	- CP:  252  IV:  33.58%   [Best CP:  359  IV:  66.60%] (Candies: 135)
> [20:25:17] Kakuna      	- CP:  249  IV:  20.67%   [Best CP:  359  IV:  66.60%] (Candies: 136)
> [20:25:17] Kakuna      	- CP:  248  IV:  29.35%   [Best CP:  359  IV:  66.60%] (Candies: 137)
> [20:25:18] Kakuna      	- CP:  245  IV:  26.51%   [Best CP:  359  IV:  66.60%] (Candies: 138)
> [20:25:18] Kakuna      	- CP:  242  IV:  24.25%   [Best CP:  359  IV:  66.60%] (Candies: 139)
> [20:25:19] Kakuna      	- CP:  242  IV:  23.49%   [Best CP:  359  IV:  66.60%] (Candies: 140)
> [20:25:19] Kakuna      	- CP:  241  IV:  22.75%   [Best CP:  359  IV:  66.60%] (Candies: 141)
> [20:25:20] Kakuna      	- CP:  240  IV:  21.82%   [Best CP:  359  IV:  66.60%] (Candies: 142)
> [20:25:20] Kakuna      	- CP:  231  IV:  35.25%   [Best CP:  359  IV:  66.60%] (Candies: 143)
> [20:25:21] Kakuna      	- CP:  219  IV:  34.20%   [Best CP:  359  IV:  66.60%] (Candies: 144)
> [20:25:22] Kakuna      	- CP:  219  IV:  21.29%   [Best CP:  359  IV:  66.60%] (Candies: 145)
> [20:25:22] Kakuna      	- CP:  218  IV:  20.40%   [Best CP:  359  IV:  66.60%] (Candies: 146)
> [20:25:23] Kakuna      	- CP:  214  IV:  27.53%   [Best CP:  359  IV:  66.60%] (Candies: 147)
> [20:25:23] Kakuna      	- CP:  214  IV:  16.55%   [Best CP:  359  IV:  66.60%] (Candies: 148)
> [20:25:24] Kakuna      	- CP:  214  IV:  15.82%   [Best CP:  359  IV:  66.60%] (Candies: 149)
> [20:25:25] Pidgey      	- CP:  252  IV:  29.25%   [Best CP:  314  IV:  44.38%] (Candies: 200)
> [20:25:26] Pidgey      	- CP:  251  IV:  28.62%   [Best CP:  314  IV:  44.38%] (Candies: 201)
> [20:25:26] Pidgey      	- CP:  248  IV:  45.02%   [Best CP:  314  IV:  44.38%] (Candies: 202)
> [20:25:27] Pidgey      	- CP:  244  IV:  20.19%   [Best CP:  314  IV:  44.38%] (Candies: 203)
> [20:25:27] Pidgey      	- CP:  228  IV:  40.16%   [Best CP:  314  IV:  44.38%] (Candies: 204)
> [20:25:28] Pidgey      	- CP:  221  IV:  31.14%   [Best CP:  314  IV:  44.38%] (Candies: 205)
> [20:25:28] Pidgey      	- CP:  211  IV:  38.87%   [Best CP:  314  IV:  44.38%] (Candies: 206)
> [20:25:28] Pidgey      	- CP:  207  IV:  32.71%   [Best CP:  314  IV:  44.38%] (Candies: 207)
> [20:25:30] Pidgey      	- CP:  206  IV:  32.42%   [Best CP:  314  IV:  44.38%] (Candies: 208)
> [20:25:30] Pidgey      	- CP:  188  IV:  28.26%   [Best CP:  314  IV:  44.38%] (Candies: 209)
> [20:25:31] Pidgey      	- CP:  187  IV:  26.25%   [Best CP:  314  IV:  44.38%] (Candies: 210)
> [20:25:31] Pidgey      	- CP:  175  IV:  33.61%   [Best CP:  314  IV:  44.38%] (Candies: 211)
> [20:25:32] Pidgey      	- CP:  175  IV:  33.49%   [Best CP:  314  IV:  44.38%] (Candies: 212)
> [20:25:32] Pidgey      	- CP:  172  IV:  27.95%   [Best CP:  314  IV:  44.38%] (Candies: 213)
> [20:25:33] Pidgey      	- CP:  160  IV:   5.98%   [Best CP:  314  IV:  44.38%] (Candies: 214)
> [20:25:33] Pidgey      	- CP:  158  IV:  30.79%   [Best CP:  314  IV:  44.38%] (Candies: 215)
> [20:25:34] Pidgey      	- CP:  149  IV:  48.34%   [Best CP:  314  IV:  44.38%] (Candies: 216)
> [20:25:34] Pidgey      	- CP:  147  IV:  43.53%   [Best CP:  314  IV:  44.38%] (Candies: 217)
> [20:25:35] Pidgey      	- CP:  136  IV:  20.52%   [Best CP:  314  IV:  44.38%] (Candies: 218)
> [20:25:36] Pidgey      	- CP:  126  IV:  35.61%   [Best CP:  314  IV:  44.38%] (Candies: 219)
> [20:25:36] Pidgey      	- CP:  122  IV:  25.96%   [Best CP:  314  IV:  44.38%] (Candies: 220)
> [20:25:37] Pidgey      	- CP:  122  IV:  24.95%   [Best CP:  314  IV:  44.38%] (Candies: 221)
> [20:25:37] Pidgey      	- CP:  114  IV:  49.18%   [Best CP:  314  IV:  44.38%] (Candies: 222)
> [20:25:38] Pidgey      	- CP:  112  IV:  42.29%   [Best CP:  314  IV:  44.38%] (Candies: 223)
> [20:25:38] Pidgey      	- CP:  102  IV:  15.74%   [Best CP:  314  IV:  44.38%] (Candies: 224)
> [20:25:39] Pidgey      	- CP:   77  IV:  42.28%   [Best CP:  314  IV:  44.38%] (Candies: 225)
> [20:25:39] Pidgey      	- CP:   69  IV:   8.18%   [Best CP:  314  IV:  44.38%] (Candies: 226)
> [20:25:40] Pidgey      	- CP:   58  IV:  35.14%   [Best CP:  314  IV:  44.38%] (Candies: 227)
> [20:25:40] Pidgey      	- CP:   42  IV:  41.82%   [Best CP:  314  IV:  44.38%] (Candies: 228)
> [20:25:41] Pidgey      	- CP:   42  IV:  39.30%   [Best CP:  314  IV:  44.38%] (Candies: 229)
> [20:25:42] Pidgey      	- CP:   25  IV:  45.83%   [Best CP:  314  IV:  44.38%] (Candies: 230)
> [20:25:42] Pidgey      	- CP:   10  IV:  31.02%   [Best CP:  314  IV:  44.38%] (Candies: 231)
> [20:25:43] Weedle      	- CP:  171  IV:  48.75%   [Best CP:  182  IV:  22.70%] (Candies: 150)
> [20:25:43] Weedle      	- CP:  170  IV:  33.05%   [Best CP:  182  IV:  22.70%] (Candies: 151)
> [20:25:44] Weedle      	- CP:  165  IV:  25.61%   [Best CP:  182  IV:  22.70%] (Candies: 152)
> [20:25:44] Weedle      	- CP:  162  IV:  21.59%   [Best CP:  182  IV:  22.70%] (Candies: 153)
> [20:25:45] Weedle      	- CP:  142  IV:  36.61%   [Best CP:  182  IV:  22.70%] (Candies: 154)
> [20:25:45] Weedle      	- CP:  140  IV:  15.66%   [Best CP:  182  IV:  22.70%] (Candies: 155)
> [20:25:46] Weedle      	- CP:  139  IV:  30.40%   [Best CP:  182  IV:  22.70%] (Candies: 156)
> [20:25:52] Weedle      	- CP:  122  IV:  17.68%   [Best CP:  182  IV:  22.70%] (Candies: 157)
> [20:25:53] Weedle      	- CP:  117  IV:   8.32%   [Best CP:  182  IV:  22.70%] (Candies: 158)
> [20:25:54] Weedle      	- CP:  104  IV:  43.29%   [Best CP:  182  IV:  22.70%] (Candies: 159)
> [20:25:55] Weedle      	- CP:   36  IV:  31.98%   [Best CP:  182  IV:  22.70%] (Candies: 160)
> [20:25:55] Weedle      	- CP:   32  IV:   5.89%   [Best CP:  182  IV:  22.70%] (Candies: 161)
> [20:25:55] Weedle      	- CP:   25  IV:  28.46%   [Best CP:  182  IV:  22.70%] (Candies: 162)

Evolving only a fraction and for some reason transferring most of the pokemon that were primed for evolving, even though there's enough candy.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
Duplicate  #3244
