### ISSUE TITLE
KeepDuplicatePokemon is not working?

### ISSUE THREAD

**Issue by andr33z** [NECROBOTIO/NecroBot#4032]
i cannot catch pokemon because pokemon is full. when i check my pokemon was duplicate with snorlax..

**Comment by JustRegisteredToSayThis** [comment]
Snorlax has a few exceptions in the config since he's rare. 
The discord is mean for support https://discordapp.com/channels/209253611031625728/209357588020592641

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
