### ISSUE TITLE
Necrobot is trasfering all my pokemons!!! Help me!!!

### ISSUE THREAD

**Issue by danha1** [NECROBOTIO/NecroBot#4034]
Please, help me....

At the start the bot, it transfer all my pokemons, one by one... I don't know why...

Thanks

**Comment by NeCx** [comment]
Change this:
"KeepMinDuplicatePokemon": 1,

**Comment by saahilz** [comment]
is it transferring high IV and high CP ?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
