### ISSUE TITLE
[REQUEST] Seperate sniping file

### ISSUE THREAD

**Issue by head0r** [NECROBOTIO/NecroBot#4037]
Would be better if you exclude the sniping keys to an extra file (snipe.json or sthlt].
In my case i often change the pokemon to snipe whether i want to level up (snipe pidgeys and stuff) or farm rare ones. sometimes when i want to farm pokestops i turn sniping off.
Searching and changing those in the conifg sucks. 
thought about copying multiple configs, but hey, that sounds better.

Leave two keys in config:
 "UseSnipe": true / false
 "UseSnipeConfig": "\*path*

People could turn it on/off with one change and should eel free to create hundreds of snipe.json copies with different values. 
Everything else should be written into the snipe.json

> "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.03,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
"UsePokemonSniperFilterOnly": false,
"PokemonToSnipe": {
    "Locations": [
       [...]
   "Pokemon": [
       [...]

**Comment by NeCx** [comment]
I agree but partially. Config file should not be seperated into files but organized such as http://pastebin.com/iMxDSbLi

**Comment by theloser** [comment]
@NeCx Nice idea, but json has no "comments" :-/
I agree that we need something more organized and a "clean" configuration.

**Comment by nfettinger** [comment]
The developers have decided that separating out config files is not going to be supported.
