### ISSUE TITLE
Incubation not progressing when CatchPokemon = false and SnipeAtPokestops = false.

### ISSUE THREAD

**Issue by ghoti70** [NECROBOTIO/NecroBot#4039]
Happened to me in 0.8, and is still occurring in 0.8.1

Since sniping and catching runs me out of balls, I set both false for a couple hours to just restock Ultra and Great balls.    I noticed that when these settings are false, the distance countdown on incubating eggs does not go down.  Only settings changed are these two.   If I set CatchPokemon = true, eggs start to work again.

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
This sounds like a configuration issue, working for me without any sniping.

**Comment by ghoti70** [comment]
Did you set BOTH to false and let a bot run for at least 10 minutes?   Great testing.   This is observed behavior over the last 24 hours, including a bot that is running now.  Enabling either one after both are false will resume incubation.
