### ISSUE TITLE
non-stop softban

### ISSUE THREAD

**Issue by VCorleone** [NECROBOTIO/NecroBot#4043]
![unbenannt](https://cloud.githubusercontent.com/assets/20933763/17529032/07238006-5e72-11e6-99d7-a44bba17df1f.png)

What is the problem with my bot? It catches only one Pokemon in a long time and than you can see these problems?
Can you please help me?

**Comment by smoothrunnings** [comment]
You could be soft banned.

**Comment by VCorleone** [comment]
How can I handle it?

**Comment by Heavy1209** [comment]
i have same problem, anyone can help?

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.

**Comment by janpapenbrock** [comment]
30m/s equals 100km/h - maybe that is a little high?
