### ISSUE TITLE
Always Softbanned and Then Are you Distance To Small?

### ISSUE THREAD

**Issue by Heavy1209** [NECROBOTIO/NecroBot#4046]

**Comment by TakRiuto** [comment]
Is happen... But not is ban, in others bots, i can take pokestop...

**Comment by Heavy1209** [comment]
so can you tell me suggestion?

**Comment by bcowell** [comment]
You're IP banned. Could be from teleporting too much or multibotting. Take a break from botting and try again in a few hours. Also use discord next time.

**Comment by Heavy1209** [comment]
ok i will try your information thanks, how i can use discord?

**Comment by TakRiuto** [comment]
I dont have multibotting, and is the first time opening the bot today D: and in anothers bots still working my account...

**Comment by bcowell** [comment]
https://discord.gg/VXKxNFr just register an account, it's a messanger client. You can ask questions in the support section.

**Comment by DmitrySilchenko** [comment]
i afraid they started to count how many devices connect from IP.
can't run several bots - get softban VERY quickly now.  both in necrobot, and others too.  necrobot seems the best so far anyway.

**Comment by Heavy1209** [comment]
ok thank you, i will take a rest for run bot. any more suggestion?

**Comment by bcowell** [comment]
@Heavy1209 Set "DisableHumanWalking": false, lower your walking speed to 10-15 km/h, and only run one bot at a time.
