### ISSUE TITLE
Pokesnipers problem with latitude and longitude and "." "," issue

### ISSUE THREAD

**Issue by suzsuzuki** [NECROBOTIO/NecroBot#4048]
The latitude and longitude are wrong here, without "." or ","
![poke](https://cloud.githubusercontent.com/assets/20933693/17529388/73b6370a-5e49-11e6-8633-85ea30be0b92.png)

version 0.81

**Comment by deduijk** [comment]
Seems to be related to a decimal point issue?
The bot also created an issue with this in config: didn't "understand" a latitude with 1.2345 (became 12345!), had to change this in the config by hand to be able to use the bot at all.

So probably something to do with some regional settings on the commit/build.

**Comment by suzsuzuki** [comment]
Yes it happens with me too... need to change by hand the initial lat/long

**Comment by deduijk** [comment]
Might be tied to the commit/ release build with regards to their regional setting and ours.
For me ',' is a decimal separator.

**Comment by nfettinger** [comment]
The wiki clearly states the formatting required.

**Comment by suzsuzuki** [comment]
where?
