### ISSUE TITLE
Error with lastest Version 0.8.1

### ISSUE THREAD

**Issue by benda95280** [NECROBOTIO/NecroBot#4049]
> [20:56:15] (MÀJ) Encore 57 Pokémon à capturer pour en évoluer 3 d'un coup ! (160/217 pour 90% de votre inventaire)
> [20:56:15] (ŒUF) Incubation en cours, reste 4,27km
> [20:56:16] (INFO) Pokédex (151) : Rencontré 143 | Capturé 143
> [20:56:17] (INFO) SEVRES à 68m | 4s
> [20:56:26] (POKEMON) (Fuite) | (Normal) Abra Lvl: 22 CP: (326/377) IV: 54,00% | Chance: 31,92% | 64,51m dist | avec une PokéBall (reste 106) | lat: 48,853316 long: 2,334692
> [20:56:30] (POKESTOP) SEVRES +50XP |0| 2 x ItemPokeBall, 1 x ItemPotion

> [20:56:31] (ERREUR) System.FormatException: Le format de la chaîne d'entrée est incorrect.
>    à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
>    à System.Convert.ToDouble(String value)
>    à PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.GetSniperInfoFrom_pokesnipers(ISession session, List`1 pokemonIds) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:ligne 627
>    à PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:ligne 268
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    à PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 213
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:ligne 67
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 36

> [20:56:31] (INFO) Connexion via Google

Any Idea ?
I've got that somestimes

**Comment by bcowell** [comment]
Ask support questions on discord. https://discord.gg/VXKxNFr

**Comment by benda95280** [comment]
Support, it's an error ?
![image](https://cloud.githubusercontent.com/assets/1539408/17529705/a6111924-5e74-11e6-9915-675991c9f6c6.png)
