### ISSUE TITLE
Noob question but please assist

### ISSUE THREAD

**Issue by JohnnyHotSauce** [NECROBOTIO/NecroBot#4050]
Sorry in advance if this is annoying or an already answered question. i did search for an answer on here though. the info im getting when running application is this ( unable to load DLL resources/encrrypt.dll: the specified module could not be found <exception from Hresult: 0x8007007E> 

Not catching, not finding stops either. Please assist and i will be very grateful.

**Comment by bcowell** [comment]
Try to re-download latest version (https://github.com/NECROBOTIO/NecroBot/releases/download/v0.8.1/Release.zip). And ask support questions on discord. https://discord.gg/VXKxNFr
