### ISSUE TITLE
Pokemon not transfered ?

### ISSUE THREAD

**Issue by benda95280** [NECROBOTIO/NecroBot#4051]
I've removed all informations about Snorlax in my configuration file.
Too many still here ...

Config file here : http://pastebin.com/TsZhVdir

> [20:59:29] (INFO) ====== Classement par PC ======
> [20:59:29] (INFO) # CP 2883/2890 | (98,07% IV)  | Lvl 35         NOM: Ronflex            Attaque 1: Léchouille           Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP 2660/2668 | (97,76% IV)  | Lvl 30         NOM: Ronflex            Attaque 1: Psykoud’Boul         Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP 2489/2494 | (98,68% IV)  | Lvl 32         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Hydroqueue           Bonbons: 559
> [20:59:29] (INFO) # CP 2293/2293 | (100,00% IV) | Lvl 29         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Vibraqua             Bonbons: 559
> [20:59:29] (INFO) # CP 2248/2268 | (93,59% IV)  | Lvl 26         NOM: Ronflex            Attaque 1: Psykoud’Boul         Attaque 2: Séisme               Bonbons: 195
> [20:59:29] (INFO) # CP 2146/2172 | (91,41% IV)  | Lvl 27         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Hydrocanon           Bonbons: 559
> [20:59:29] (INFO) # CP 2131/2156 | (91,69% IV)  | Lvl 29         NOM: Grotadmorv         Attaque 1: Acide                Attaque 2: Vibrobscur           Bonbons: 58
> [20:59:29] (INFO) # CP 2107/2134 | (90,55% IV)  | Lvl 24         NOM: Ronflex            Attaque 1: Psykoud’Boul         Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP 2076/2099 | (91,05% IV)  | Lvl 21         NOM: Dracolosse         Attaque 1: Dracosouffle         Attaque 2: Dracochoc            Bonbons: 105
> [20:59:29] (INFO) # CP 2025/2045 | (92,46% IV)  | Lvl 23         NOM: Ronflex            Attaque 1: Psykoud’Boul         Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP 1921/2130 | (33,57% IV)  | Lvl 33         NOM: Akwakwak           Attaque 1: Choc Mental          Attaque 2: Psyko                Bonbons: 13
> [20:59:29] (INFO) # CP 1915/1925 | (96,41% IV)  | Lvl 26         NOM: Pyroli             Attaque 1: Flammèche            Attaque 2: Déflagration         Bonbons: 559
> [20:59:29] (INFO) # CP 1830/1850 | (92,04% IV)  | Lvl 23         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Hydroqueue           Bonbons: 559
> [20:59:29] (INFO) # CP 1813/1908 | (66,91% IV)  | Lvl 29         NOM: Grolem             Attaque 1: Jet-Pierres          Attaque 2: Pouvoir Antique      Bonbons: 153
> [20:59:29] (INFO) # CP 1772/1875 | (64,25% IV)  | Lvl 30         NOM: Feunard            Attaque 1: Flammèche            Attaque 2: Déflagration         Bonbons: 88
> [20:59:29] (INFO) ====== Classement par IV ======
> [20:59:29] (INFO) # CP  273/ 273 | (100,00% IV) | Lvl 06         NOM: Ossatueur          Attaque 1: Coud’Boue            Attaque 2: Massd'Os             Bonbons: 174
> [20:59:29] (INFO) # CP  366/ 366 | (100,00% IV) | Lvl 19         NOM: Leveinard          Attaque 1: Écras'Face           Attaque 2: Rafale Psy           Bonbons: 59
> [20:59:29] (INFO) # CP 1212/1212 | (100,00% IV) | Lvl 26         NOM: Persian            Attaque 1: Feinte               Attaque 2: Câlinerie            Bonbons: 17
> [20:59:29] (INFO) # CP   95/  95 | (100,00% IV) | Lvl 02         NOM: Ptéra              Attaque 1: Aile d’Acier         Attaque 2: Ultralaser           Bonbons: 135
> [20:59:29] (INFO) # CP  720/ 720 | (100,00% IV) | Lvl 16         NOM: Excelangue         Attaque 1: Léchouille           Attaque 2: Ultralaser           Bonbons: 85
> [20:59:29] (INFO) # CP 2293/2293 | (100,00% IV) | Lvl 29         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Vibraqua             Bonbons: 559
> [20:59:29] (INFO) # CP  386/ 387 | (98,79% IV)  | Lvl 09         NOM: Tygnon             Attaque 1: Pisto-Poing          Attaque 2: Casse-Brique         Bonbons: 194
> [20:59:29] (INFO) # CP 2489/2494 | (98,68% IV)  | Lvl 32         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Hydroqueue           Bonbons: 559
> [20:59:29] (INFO) # CP 1456/1459 | (98,25% IV)  | Lvl 19         NOM: Léviator           Attaque 1: Dracosouffle         Attaque 2: Hydrocanon           Bonbons: 1312
> [20:59:29] (INFO) # CP 2883/2890 | (98,07% IV)  | Lvl 35         NOM: Ronflex            Attaque 1: Léchouille           Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP  879/ 882 | (98,07% IV)  | Lvl 18         NOM: Lippoutou          Attaque 1: Écras'Face           Attaque 2: Choc Psy             Bonbons: 174
> [20:59:29] (INFO) # CP 1565/1570 | (98,02% IV)  | Lvl 35         NOM: Porygon            Attaque 1: Charge               Attaque 2: Rayon Signal         Bonbons: 94
> [20:59:29] (INFO) # CP 1178/1182 | (97,92% IV)  | Lvl 14         NOM: Noadkoko           Attaque 1: Psykoud’Boul         Attaque 2: Psyko                Bonbons: 219
> [20:59:29] (INFO) # CP 2660/2668 | (97,76% IV)  | Lvl 30         NOM: Ronflex            Attaque 1: Psykoud’Boul         Attaque 2: Ultralaser           Bonbons: 195
> [20:59:29] (INFO) # CP 1042/1046 | (97,36% IV)  | Lvl 13         NOM: Aquali             Attaque 1: Pistolet à O         Attaque 2: Hydroqueue           Bonbons: 559

**Comment by nfettinger** [comment]
Please use Discord chat for general help and configuration issues.

**Comment by theloser** [comment]
I suppose Snorlax is "Ronflex" in your language? You have the following:
```
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
```
All your Snorlax match these conditions and are therefore kept.
