### ISSUE TITLE
Bug issue and restart to logon after getting stuf from pokestop

### ISSUE THREAD

**Issue by tapaspartout** [NECROBOTIO/NecroBot#4060]
Here is the content : 
[21:13:18] Traveling to Pokestop: The Pilgrim (54m) (2 seconds)
[21:13:20] Name: The Pilgrim XP: 50, Gems: 0, Items: 1 x ItemGreatBall, 1 x ItemRazzBerry, 1 x ItemPotion, Lat: 40,773087, Long: -73,968437
[21:13:20] System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.Convert.ToDouble(String value)
   à PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.GetSniperInfoFrom_pokesnipers(ISession session, List`1 pokemonIds) dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:ligne 627
   à PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:ligne 268
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 213
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:ligne 67
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 36
[21:13:20] Logging in using Google

**Comment by nfettinger** [comment]
Please use Discord chat for general help and configuration issues.
