### ISSUE TITLE
Egg Incubation Distance Refresh Time?

### ISSUE THREAD

**Issue by g00tch** [NECROBOTIO/NecroBot#4061]
I've got everything finally set and working properly to my specifications. My only issue, is that on this last run, it took 25 minutes for it to update the distance traveled.

One of my eggs went from 1.02km needed to hatch, to .83km after a full 25 minutes of it "walking/running around", in a 3 mile radius, set to a 16kmh.

Not sure if that's a Niantic thing, or the bot.

**Comment by smoothrunnings** [comment]
reduce your walking speed in the config from 31.0KM to 5.0KM

**Comment by nfettinger** [comment]
Please use Discord chat for general help and configuration issues.
The server probably thinks you are in a car and isnt counting the travel
