### ISSUE TITLE
SoftBan

### ISSUE THREAD

**Issue by Draackzer** [NECROBOTIO/NecroBot#4064]
Hello friends, I have this problem with the softban, I read some solutions in this forum but I can fix my problem, what is happen? I appreciate your help
![softban](https://cloud.githubusercontent.com/assets/20934456/17530542/976759b0-5e3d-11e6-8fa5-0479adb81481.png)

**Comment by nfettinger** [comment]
Please use Discord chat channels for general issues and configuration questions.
