### ISSUE TITLE
deactivate item farming at pokestops

### ISSUE THREAD

**Issue by bastil** [NECROBOTIO/NecroBot#4067]
Hey guys, is it possible to deactivate the autofarming of items at pokestops? Just want that the bot catches pokemon.

**Comment by nfettinger** [comment]
Necrobot hits pokestops to gain experience. Removing this is probably not a desired feature.

**Comment by JTBomb007** [comment]
Personally not something you should turn off, how ever no harm in having the option.

Maybe a low priority request.

**Comment by bastil** [comment]
thanks for the fast response, but i am asking for that function because i dont want to lvl up so fast. ;) 

this was not a feature request it was more a question if its possible at the moment :)

**Comment by JTBomb007** [comment]
Can't say I noticed anything in the config mate, sorry.

**Comment by nfettinger** [comment]
This is not possible at the moment, unless you build your own source.
