### ISSUE TITLE
Bug : No usable Pokestop

### ISSUE THREAD

**Issue by 21accel** [NECROBOTIO/NecroBot#4068]
Hi, after I updated to version 0.8.1 I had an issue. I can't travel to any pokestop because it's said that there's not any usable pokestop in area, but in previous version (0.8.0) it can still find pokestop.
I never change the config file for latitude and longitude. Thanks.
![necrobot](https://cloud.githubusercontent.com/assets/9246548/17530781/3b02f9f2-5ea3-11e6-945b-aed97950984b.PNG)

**Comment by nfettinger** [comment]
Probably softbanned
Please use Discord chat for general help.
