### ISSUE TITLE
Pokezz sniping problems with coords

### ISSUE THREAD

**Issue by rigodonchu** [NECROBOTIO/NecroBot#4070]
Looks like it's not getting the . in the coords on pokezz feeding, and it just ignore it and converts them to a big number:

![error](https://cloud.githubusercontent.com/assets/20934605/17530976/2b78b838-5e7a-11e6-8bac-3a18e89ff0d5.jpg)

**Comment by nfettinger** [comment]
Please read the wiki on formatting. Commas are not accepted.

**Comment by rigodonchu** [comment]
But i didn't write a comma anywhere, it's getting the coords directly from pokezz
