### ISSUE TITLE
Pokemon "Moves" list logic enhancement.

### ISSUE THREAD

**Issue by arslancharyev31** [NECROBOTIO/NecroBot#4071]
As I understand, the bot won't transfer pokemons, containing moves, stated in this list. It does so, but it ignores minCp or minIV values, so it doesn't transfer weak pokemons. How about adding new operator, so it would look at both conditions: (minCp or minIV) and "moves" list.

**Comment by spamfighter82** [comment]
and if you are at it, please make it so, that if 2 moves are specified, the pkmn has both of em

**Comment by nfettinger** [comment]
This is a duplicate issue.

**Comment by nfettinger** [comment]
These features are requested in another issue.
