### ISSUE TITLE
Transferring Wrong Duplicates?

### ISSUE THREAD

**Issue by ItsLost** [NECROBOTIO/NecroBot#4073]
Hi, when I use the bot, on certain pokemon (jynx and pidgey so far) it transfers the highest duplicates? Help?

**Comment by theloser** [comment]
Need. More. Information.
For fuck's sake. Can't read your config files from here!

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
This is either a configuration issue, or related to #3338
