### ISSUE TITLE
Transfering higher cp pokemon instead of weaker ones

### ISSUE THREAD

**Issue by Dzoky** [NECROBOTIO/NecroBot#4075]
So my Seaking of 1251cp is gone because the bot thought it's weaker than my 210cp one... -.-" 
Telling so you would know, thanks for the awesome software!

Attaching an example with Poliwhirl.
![capturekjgk](https://cloud.githubusercontent.com/assets/20934720/17531240/bc91115e-5e83-11e6-9f40-65abc624363a.PNG)

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
Duplicate #3338

**Comment by Pokemongobottttttt** [comment]
You must have the Prefer IV over CP set to true. The poliwhirl it kept has a higher IV than the one it transferred, regardless of CP

**Comment by Dzoky** [comment]
Uhm... In my config:
"PrioritizeIvOverCp": false,
Meh, i'll just deal with it...

**Comment by Pokemongobottttttt** [comment]
show me these values

these values are what im looking for
"KeepMinCp": 1000,
"KeepMinIvPercentage": 90.0,
"KeepMinLvl": 6,
"KeepMinOperator": "and",
"UseKeepMinLvl": false,

plus this
"TransferWeakPokemon": true,

**Comment by Dzoky** [comment]
in my case:
 "KeepMinOperator": "or",
 "TransferWeakPokemon": false

I'm using default settings that came with the software just so you know. Will set them to your version and see what I get

**Comment by Pokemongobottttttt** [comment]
dont use mine, im experimenting

**Comment by Dzoky** [comment]
Still tried. With that config the bot started transferring all the pokemon one by one

**Comment by Pokemongobottttttt** [comment]
this seems to be working for me

  "KeepMinCp": 1700,
  "KeepMinIvPercentage": 96.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

**Comment by Pokemongobottttttt** [comment]
these are the results I get from those settings
![necro](https://cloud.githubusercontent.com/assets/20912369/17536656/7b252c42-5e64-11e6-9b84-2f720b80d238.png)

**Comment by Dzoky** [comment]
Not sure about the prioritization though. Lost a 1500 Tentacruel to a 1000 one
