### ISSUE TITLE
Feeders coords problem

### ISSUE THREAD

**Issue by rigodonchu** [NECROBOTIO/NecroBot#4076]
NOTE: I just got the issue closed and reddirected to the formatting in the wiki, I guess it's not right because i'm talking about the coords fed auto by pokezz when u enable it in the config file, and not any coords writen by me as a manual snipping location. Thanks!

Looks like it's not getting the . in the coords on pokezz feeding, and it just ignore it and converts them to a big number:
![error](https://cloud.githubusercontent.com/assets/20934605/17531314/9c7becac-5e7b-11e6-9ad8-bd8fa346a4f0.jpg)

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
dont use commas
