### ISSUE TITLE
Need More loot pokestop İts not enaugh pokeballss

### ISSUE THREAD

**Issue by mucro9** [NECROBOTIO/NecroBot#4078]
Need More loot pokestop İts not enaugh pokeballss.İts really making big probleam..

**Comment by Rashk999** [comment]
set   **"CatchPokemon": false,** bot will collect some for balls for you

**Comment by mucro9** [comment]
i know that but i mean its need be automoticly do that.Just need more loot pokestop in the game thats all.İts will not be hard for develepors.Thanx for reply

**Comment by iwantmyfile5** [comment]
This isnt a spot for PokmonGO suggestions. The developers of the bot have no control over the amount of loot given at pokestops. I suggest you switch locations to an area with a lot of pokestops if you find you're running out of pokeballs.

**Comment by mucro9** [comment]
My location has a lot of pokestop but bot is not checking enaugh time to loot pokestop.And then i need change the config settings then then..İts can be little bit more loot pokestop thats it.

**Comment by nfettinger** [comment]
Please choose a location with a higher ratio of Pokestops to Pokemon spawns.
For general help and Configuration questions, please use our Discord chat channels.
