### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GreYzZ** [NECROBOTIO/NecroBot#4079]
Hello,
I have a little suggestion for you.
Maybe add a function to keep the 2 best Pokemon of each.

**Comment by arslancharyev31** [comment]
It's solved by setting  KeepMinDuplicatePokemon to 2. Like:
     "KeepMinDuplicatePokemon": 2,

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
