### ISSUE TITLE
psycho pokemons problem

### ISSUE THREAD

**Issue by Rashk999** [NECROBOTIO/NecroBot#4080]
Bot is still transfering better drowzee instead of worser, for psyduck same problem
![drow](https://cloud.githubusercontent.com/assets/20931806/17531441/2c329972-5e7c-11e6-8756-b37065e5ff58.jpg)

**Comment by 1Drill** [comment]
rip the 723 drowzee...

put the pokemons you do not want to be transferred onto the PokemonsNotToTransfer list and it should work

**Comment by Rashk999** [comment]
@1Drill already rip for 897 drowzee and more .... 

i know, but your solution doesnt solve the problem

**Comment by nfettinger** [comment]
**For general help and Configuration questions, please use our Discord chat channels.
This is probably a configuration issue.

**Comment by Pokemongobottttttt** [comment]
you probably have preferIVoverCP set to true. Your 331CP one has 90.99 IV. So it keeps that one rather than the 723CP because the lower 73.40 IV

**Comment by Rashk999** [comment]
@Pokemongobottttttt i have it on false

**Comment by Pokemongobottttttt** [comment]
What are you IV CP values set to

**Comment by Rashk999** [comment]
dont know which line do you want so ...  

"UpgradePokemonIvMinimum": 95.0,
  "EvolveAboveIvValue": 95.0,
  "KeepMinIvPercentage": 90.0,
  "FavoriteMinIvPercentage": 95.0,

**Comment by Rashk999** [comment]
but... have a look on goldee...bot kept495CP and 37% and throw away 481CP 64%

**Comment by Pokemongobottttttt** [comment]
these values are what im looking for
  "KeepMinCp": 1000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
