### ISSUE TITLE
Ip Soft ban

### ISSUE THREAD

**Issue by Userman1986** [NECROBOTIO/NecroBot#4082]
More than 2 bots i have an ip soft ban
I try VPN - 3 types of them.
I try to automaticly change my ip every 60 seconds.
How can i run more than 2 bots on one computer ????

**Comment by Userman1986** [comment]
Try to anonimaize all traffic, that comes from my computer

**Comment by mytab0r** [comment]
u use own device info?

**Comment by Userman1986** [comment]
MAC ? where i need to look ? in auth?

**Comment by JameesJameesJamees** [comment]
Isnt it possible to let every bot run over his own VPN ?
That would avoid the IP Bans and you can run more than 2 Bots at the same time.
I suck at coding so idk how to implent this feature that the bot connects at start over a VPN.

**Comment by Userman1986** [comment]
I see just proxy settings in auth file.

**Comment by JameesJameesJamees** [comment]
Ive tried now the Proxy, it says after starting the bot: Make sure you have entered the right email & password. idk what to do and if a proxy is the answer of our problem.

**Comment by KevHart95** [comment]
@Userman1986 

> How can i run more than 2 bots on one computer ????

I'm using one virtual machine with own vpn for every two bots....

**Comment by Userman1986** [comment]
It seems i am a stupid bitch. Use proxy and be a winner....  i run 6 bot at the moment... but bots run only in 8080 port from proxy.......

**Comment by Userman1986** [comment]
8 bots, no issue.... the fuck sike.... kill all day on this shit and dont seen proxy use

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
