### ISSUE TITLE
necro bot error

### ISSUE THREAD

**Issue by semihusta** [NECROBOTIO/NecroBot#4083]
System.NullReferenceException: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
konum: PoGo.NecroBot.Logic.Inventory.d__28.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\Inventory.cs içinde: satır 361
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.d__2.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs içinde: satır 24
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.State.InfoState.d__0.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\State\InfoState.cs içinde: satır 16
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
konum: PoGo.NecroBot.Logic.State.StateMachine.d__3.MoveNext() C:\Users\Ömer\Documents\GitHub\Pokemon-Go-Rocket-API\PoGo.NecroBot.Logic\State\StateMachine.cs içinde: satır 36

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
Duplicate #3295
