### ISSUE TITLE
Transferring pokemon

### ISSUE THREAD

**Issue by Jaymer88** [NECROBOTIO/NecroBot#4084]
Hi guys, I normally just use the standard config/Language but after update 8.1 when i logged in it started to transfer all pokemon, i exited it sharpley so to not lose anymore, but 12 transfered some high cp pokemon. Anyone know whats going on?

**Comment by deduijk** [comment]
Read before posting!
There were about 300 issues opened with the same issue.
change 'KeepMinDuplicatePokemon' from 0 to the desired number -> problem solved.

**Comment by Jaymer88** [comment]
Ok, Could you tell me where to go to do that?

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
