### ISSUE TITLE
Luckyeggs

### ISSUE THREAD

**Issue by denniskoenn** [NECROBOTIO/NecroBot#4085]
I cannot use Luckyeggs 
He says that i have to find 29 pokemons to use

**Comment by jck357** [comment]
It wil evolve when "EvolveKeptPokemonsAtStorageUsagePercentage" is met. So if you desperately want to evolve, change that value to a lower number.

**Comment by denniskoenn** [comment]
[22:27:18] (INFO) Catch 29 more Pokemon to use a Lucky Egg!

**Comment by theloser** [comment]
Set "UseLuckyEggConstantly" to true to instantly use LuckyEggs.

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
