### ISSUE TITLE
Necrob. Error Help please!

### ISSUE THREAD

**Issue by WidowsNuclear** [NECROBOTIO/NecroBot#4087]
![necro error](https://cloud.githubusercontent.com/assets/20935016/17532108/4aecc704-5e7f-11e6-95d6-a0242cad21a8.JPG)

What means this ?

**Comment by random189268** [comment]
It looks like your latitude is not set to a range between -90 and 90.

**Comment by WidowsNuclear** [comment]
I setted Santa Moica Pier Coords. is this the reason why it dont work ? Latitude: 34.011144    Longitude: -118.493201

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
