### ISSUE TITLE
No pokestop items

### ISSUE THREAD

**Issue by LordBigPapa** [NECROBOTIO/NecroBot#4094]
After softban bypass (and before that) the bot doesn't get any items from a pokestop. Normally this is a softban thing only it's been more than 1,5 hours and still no items...

Any idea?

**Comment by automaticdai** [comment]
I think Niantic changed their APIs again. Hopefully not...

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
