### ISSUE TITLE
Can someone help me ? Ger.

### ISSUE THREAD

**Issue by 07AF** [NECROBOTIO/NecroBot#4097]
[22"40"18] () Exception caught, writing LogBuffer.

Unbehandelte Ausnahme: System.FormatException: Für folgendes Zeichen kann kein passendes Anführungszeichen gefunden werden: """.
   bei System.DateTimeFormat.ParseQuoteString(String format, Int32 pos, StringBuilder result)
   bei System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   bei System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   bei System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi)
   bei System.DateTime.ToString(String format, IFormatProvider provider)
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei PoGo.NecroBot.Logic.Logging.Logger.SetLogger(ILogger logger, String subPath, Boolean isGui) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Logging\Logger.cs:Zeile 61.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.CLI\Program.cs:Zeile 50.

get this after update ...

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
