### ISSUE TITLE
Getting Constant softban

### ISSUE THREAD

**Issue by noobz123** [NECROBOTIO/NecroBot#4103]
Hi, I don't know if this has to do with the new feature where it asks you "You are going too fast" and gives  you a button to click called "I'm a passenger". 

But I'm getting softbans on my bots very frequently despite not  having teleported. Is there any solution to this?

**Comment by ThMh** [comment]
"DisableHumanWalking": false,

**Comment by random189268** [comment]
Are you running too many bots on a single IP?

**Comment by redline187** [comment]
i have this also my settings worked fine before api change, im running 4 bots at same time

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
