### ISSUE TITLE
System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by Gandaflux** [NECROBOTIO/NecroBot#4106]
Looks like there is problem with data from pokesnipers. Of course setting **GetSniperInfoFromPokeSnipers** to **false** fix problem but i'm not sitting near computer to check errors all the time.

I think getting and reading data should not disconnect bot on fail, since right now i got crash on every  snip, so bot is doing relogs from long time. :(

![cb105-clip-42kb](https://cloud.githubusercontent.com/assets/20873230/17533513/580ac3e0-5e85-11e6-90d6-8ab24b8822bd.png)

**Comment by MacQwerty** [comment]
I've the same problem! Here is my config file is that helps: [config-file](http://pastebin.com/7iRNiKaP)


![untitled kopi](https://cloud.githubusercontent.com/assets/15525298/17533628/f4ce043a-5e85-11e6-89b4-f9d06a534640.png)

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
You need to use periods in your cords, not commas

**Comment by Gandaflux** [comment]
@nfettinger as you can see on screen it fail at GetSniperInfoFrom_pokesnipers() so its not my fault, not im using commas instead periods.

**Comment by elmaarmut** [comment]
Getting this every 5 minutes.
