### ISSUE TITLE
Question concerning transferring

### ISSUE THREAD

**Issue by DONRozeboom** [NECROBOTIO/NecroBot#4107]
Hi guys,

Quick question about the config for transferring.
I have TransferDuplicatePokemon on true, and KeepMinDuplicatePokemon set to 1.
However, I also have the value KeepPokemonsThatCanEvolve set as true.

I'm not sure what the outcome will be in this case. Will I keep all Pokemon that have enough candies to evolve, or will all duplicates be transferred due to the value mentioned earlier?

Thank you very much for the help.

**Comment by spamfighter82** [comment]
afaik KeepPokemonsThatCanEvolve only effects pkmn listed in "PokemonsToEvolve"

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
Use the wiki for configuration help.
