### ISSUE TITLE
Necrobot not transfering sniped pokemon?

### ISSUE THREAD

**Issue by yoyoyo2010** [NECROBOTIO/NecroBot#4108]
My inventory keeps reaching full when i use sniping. When I look in my inventory, the porygons, exeggutors, vaporeons, snorlaxes and so on have multiple duplicates.

**Comment by random189268** [comment]
Do you have specific settings in your config for those Pokemon? I had to remove those Poke-specific settings and then the bot started transferring away all the Porygon etc.

**Comment by Leo231** [comment]
By default, pokemon you named are in a "PokemonsNotToTransfer" list. Remove them from there and they will be transfered.

**Comment by yoyoyo2010** [comment]
vaporeon is not on the list though

**Comment by yoyoyo2010** [comment]
neither is porygon or aeradactyl.

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
This is a configuration issue.
