### ISSUE TITLE
All my pokemons transferred after update... 

### ISSUE THREAD

**Issue by Scar4face** [NECROBOTIO/NecroBot#4113]
What happened and all my pokemons transferred after update???

**Comment by PassiveModding** [comment]
you probably didnt update the config

**Comment by Scar4face** [comment]
Must i do it manually?? Where i can find it?

**Comment by Diegoifv** [comment]
same here but now with the 8.1 i cant login, y write my email and my password and when do a automatic restart say in re letters email and password incorrect

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
