### ISSUE TITLE
POKESTOPS..

### ISSUE THREAD

**Issue by MrPK2710** [NECROBOTIO/NecroBot#4114]
guys.. anyone know what i need to do to find the fucking pokestops... the bot dont finding..

**Comment by muhfattah** [comment]
Login with your phone, and then come again to necrobot.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by MrPK2710** [comment]
sorry and thx
