### ISSUE TITLE
[Bug?] Transfer BETTER CP pokemon, than worse

### ISSUE THREAD

**Issue by shetonaz** [NECROBOTIO/NecroBot#4115]
Hello, so my bot transfer better CP pokemon, thank worse.
I set my PrioritizeIvOverCP to false, so it shouldn't work, but it still somehow transfers few types of pokemon, even they're better in CP.
KeepMinCip is set to 600, and bot transfers 1200cp bot instead of 400Cp

**Comment by necr-0** [comment]
Could you please place on your config file on Pastebin? I'll give it a look.

**Comment by nfettinger** [comment]
Duplicate #3338
