### ISSUE TITLE
No nearby pokestop, walk around random? (request)

### ISSUE THREAD

**Issue by JohnnyVicious** [NECROBOTIO/NecroBot#4117]
Since some areas have like 5-6 pokestop close to eachother but the 7th one is far far away so travel time would be too long, it would be nice instead of having the bot stay put for a few minutes saying there is no pokestop...to have it randomly walk in between its location and the most nearby recently visited pokestop to get some distance for egg hatching.
I guess this would be implementing a variable with the previous pokestop coords and movement in the 'no pokestop' method.
Would be really appreciated for some nest locations :-)

**Comment by nfettinger** [comment]
You can use GPX files to set the absolute path.
