### ISSUE TITLE
TrendMicro quarantined Resources\encrypt.dll file

### ISSUE THREAD

**Issue by hakanakgun** [NECROBOTIO/NecroBot#4128]
\Resources\encrypt.dll is quarantined by TrendMicro program. I could not use the bot because it is giving following error: "Unable to load DLL 'Resources/encrypt.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

Could you please fix the file?

![2016-08-10_00-40-42](https://cloud.githubusercontent.com/assets/13259530/17534828/cf32d27e-5e93-11e6-8e3d-a10e18c0c448.png)

![2016-08-10_00-47-43](https://cloud.githubusercontent.com/assets/13259530/17534873/1180615a-5e94-11e6-9077-034fd1336c01.png)

**Comment by nfettinger** [comment]
This is an environment issue. Please add the bot and the dll to your antivirus whitelist.
It is flagging it because of the calculation for the Unkown6 packet.

**Comment by CharliePrown** [comment]
ah no, source of the bot untrusted maybe?

trend micro here too, manual scan of the file without any issues

**Comment by hakanakgun** [comment]
@nfettinger Hi, I could not put it to whitelist because IT procedures on my machine. Can't we do smt to bypass antivirus scan? Probably, they made an update on their library.

**Comment by CharliePrown** [comment]
nfettinger why did you close this topic that fast?

now i think it for sure is a virus as else you should not have closed this topic instant to get it from the issues main site, bad behaviour,,,,

**Comment by life4fun8817** [comment]
I got this issue too and no privilege to add to anti-virus while list.
Any other solution?
