### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by sagemkiller** [NECROBOTIO/NecroBot#4130]
some things changed before I went to work 5 hours ago it was running fine but now after I updated it it goes a lot slower and after a few pokestops it stops searching and gets stuck on one at the top it says "Detected realistic Traveling , using Default Settings inside config.json"

**Comment by theloser** [comment]
And I need money.

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
