### ISSUE TITLE
Request update : Sniper cp e iv filter

### ISSUE THREAD

**Issue by pokemongo444** [NECROBOTIO/NecroBot#4131]
tnx great job

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.

**Comment by pokemongo444** [comment]
i'm asking for a sniping option filter. tnx

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
