### ISSUE TITLE
config for mass XP?

### ISSUE THREAD

**Issue by bumbiizen** [NECROBOTIO/NecroBot#4134]
Anyone know how to do the config for the maximum of xp you can get? :)

**Comment by theloser** [comment]
Ask in the discord channel for help.

**Comment by bumbiizen** [comment]
thx!

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
