### ISSUE TITLE
i needed help updated

### ISSUE THREAD

**Issue by sagemkiller** [NECROBOTIO/NecroBot#4135]
please help sorry I dont have discord it makes my computer so much slower sorry for the 2nd post . some things changed before I went to work 5 hours ago it was running fine but now after I updated it it goes a lot slower and after a few pokestops it stops searching and gets stuck on one at the top it says "Detected realistic Traveling , using Default Settings inside config.json" it also keeps saying pokemon are full and that its transferring but does not transfer and whenever I use POGO it always says "did not find pokemon within SnipingScanOffSet!" I tried messing around with it changing the number but it doesn't help any idea what could be wrong? btw it does not catch anyone of the pokemon

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
