### ISSUE TITLE
pokemon inventory is full, transferring pokemon 

### ISSUE THREAD

**Issue by sebertooth** [NECROBOTIO/NecroBot#4136]
necrobot is not capturing any pokemon its just say "attention pokemon inventory is full, transferring pokemon "
![screenshot](https://cloud.githubusercontent.com/assets/20917924/17535065/076297cc-5eaa-11e6-8b4b-913ddccb024b.png)

**Comment by lucabravi** [comment]
you've reached the limit of 250/250 pokemon 
you have to release some pokemon sir ^_^

**Comment by sebertooth** [comment]
i have to do it manually before it was automatic i think

**Comment by theloser** [comment]
If all your pokemon match the "keep" criteria the bot doesn't know which pokemon to transfer. Transfer them manually and change your settings to keep less pokemon.

**Comment by lucabravi** [comment]
it is automatic but, if your config file says that pokemon have to be released only when under (for example) 1500cp or when they are less then 80% perfect.... then after a while you'll be full of >1500cp and 80%IVPerf pokemon

**Comment by random189268** [comment]
I had to remove them from my "DoNotTransfer" list in the config - wound up having a full inventory of Charizard, Dragonite, Porygon etc. with random IVs and CPs.

**Comment by sebertooth** [comment]
how can i edit my released pokemon criteria

**Comment by random189268** [comment]
"PokemonsNotToTransfer": [], in the config file

**Comment by theloser** [comment]
KeepMinIvPercentage, KeepMinCP, KeepMinOperator, KeepMinLvl, KeepMinDuplicatePokemon, PokemonsNotToTransfer, PokemonsTransferFilter

**Comment by sebertooth** [comment]
thank you very much for all the help
