### ISSUE TITLE
necrobot is tranfering all my pokemons!!!

### ISSUE THREAD

**Issue by Diegoifv** [NECROBOTIO/NecroBot#4138]
I dont know why but i start he necrobot and when the program start runing begins transferring all my pokemons and i dont know why, if some one can help me

**Comment by theloser** [comment]
Works as designed. Check your config.
And go to the discord channel to get more help.

**Comment by Diegoifv** [comment]
if you can say me how to do that it would be awesome, i dont know much about this program and how see te config. Thanks

**Comment by theloser** [comment]
> And go to the discord channel to get more help.

**Comment by Kiwaaa2** [comment]
I have the problem that my bot doesnt send anything when it starts. Sometime 1 or 2 pokemon maybe 3 but not all that under my cp value. I tried everything but nothing worked for me...

**Comment by theloser** [comment]
> And go to the discord channel to get more help.

**Comment by Kiwaaa2** [comment]
Discord channel to get help.. where no one answer your question.

**Comment by recon88** [comment]
For general questions or if help is needed with configuration, visit our Discord: https://discord.gg/VXKxNFr
