### ISSUE TITLE
[0.8.1] Getting softbanned a lot

### ISSUE THREAD

**Issue by Zarovzky** [NECROBOTIO/NecroBot#4139]
Im ising the default config and this is my LastPost.ini: 43,6698373951513:-79,3921926336325 

This is what i get:
![screenhunter_89 aug 09 23 58](https://cloud.githubusercontent.com/assets/11941881/17535136/20b0dcce-5e8d-11e6-82da-44ebdf7c1688.png)

And if i close the bot and run it again i get this:
![screenhunter_90 aug 09 23 58](https://cloud.githubusercontent.com/assets/11941881/17535170/49a07360-5e8d-11e6-886f-6f3770b2d8af.png)

What config should i use to avoid this behaviour?

**Comment by theloser** [comment]
How many bots are you running? Also check your walking speed, DisableHumanWalking, Sniping, Delays and so on. If your bot behaves "not human like" you'll probably and up with a softban.

**Comment by TrainMaestro** [comment]
i would reccomend you to use a vpn. that worked for me.also when ever it goes to softban loop.keep changing ip

**Comment by Zarovzky** [comment]
@theloser 
The setup is: 
"DisableHumanWalking": false,
should it be to true?

**Comment by Rick058** [comment]
Use VPN to get rid of the soft ban loop / no usable pokestops - run 2 bots per IP address, not more!
If you want to use more than 2 bots, configure the proxy settings in auth.json or get a VM with a VPN for another 2 bots. 
Speaking from own experience: config.json settings do not matter. "Not human like" is bs. I'm running at 100km/h in Central Park, NY with 2 delay on DelayBetweenPlayerActions (standard = 5000) and 1 delay on DelayBetweenPokemonCatch (standard = 2000/2500?) + auto sniping enabled.

**Comment by theloser** [comment]
@Rick058 Thanks for this clarification.

**Comment by Aurilius** [comment]
I'm only running one instance, and it still softbans me nonstop.  I've also noticed the bot is getting crazy high experience per hour.  Is there a way to throttle back the number of actions it is performing?  It is searching for pokemon way too often.

**Comment by Rick058** [comment]
@Aurilius 
To lower down the xp/hour change your config to:
`  "WalkingSpeedInKilometerPerHour": 15.0,`
`  "DelayBetweenPlayerActions": 5000,`
`  "DelayBetweenPokemonCatch": 2000,`

To get rid of your softban, try: https://github.com/NECROBOTIO/NecroBot/issues/3423#issuecomment-238409033 (tested on v0.7.6 btw, unsure if it works on the latest version)

**Comment by Aurilius** [comment]
It was the human like walking setting.  This most recent update changed my setting somehow so it was disabled instead of enabled.  I changed that and it fixed it instantly.

**Comment by Zarovzky** [comment]
@Aurilius so "DisableHumanWalking" is TRUE for you right now?

**Comment by Aurilius** [comment]
I didn't turn it off, but yes it was showing true.  Not sure what happened.  I changed it back to false, and it works fine now.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
