### ISSUE TITLE
Softban Loop

### ISSUE THREAD

**Issue by AtlonUWI** [NECROBOTIO/NecroBot#4141]
The program keeps entering a softban loop,

[17:52:31] Name: <PLACE NAME DEPRECATED FOR SAFETY> Looting failed, possible softban. Unban in: 8/45

Will repeat until softban is lifted/softban 45/45 is cleared, but then returns moments later.

N.B. I am running 3 instances of the bot from 3 separate folders with their unique files. All fully updated to v0.8.1

If the cause was the 3 separate instances, is there any proper way I can use the bot in many instances?

**Comment by theloser** [comment]
More than two bots per IP address --> softban. Use proxy server.

**Comment by Royhome** [comment]
tried log on using Nox.
No pokestops.
Maybe they change API again

**Comment by AtlonUWI** [comment]
Thank you for that, I will look into it shortly, is it on the wiki how to set up / use proxies with Necrobot?

**Comment by Royhome** [comment]
Sry I was. It was IP ban. It is working now.

**Comment by theloser** [comment]
Go to the discord channel to get help with proxy server.

**Comment by iGneouz** [comment]
yea,.. i get softbann twice
lol
thaks for the info

**Comment by Aurilius** [comment]
It is softbanning me with only 1 instance running.  It is performing actions so frequently that it just softbans me every minute or so.

**Comment by CameForTheCrown** [comment]
is it one bot per rig i have or is it one bot per internet ip?

**Comment by theloser** [comment]
Two bots per IP address.

**Comment by shetonaz** [comment]
@theloser i used 2 bots per IP address, and still got banned :D

**Comment by Utopik** [comment]
i got ban too. this ban is verry longgg

**Comment by theloser** [comment]
@shetonaz Happens to me, too, but only sometimes. I just chill and wait, after a few minutes softban is bypassed.
