### ISSUE TITLE
The Server Committed a Protocol Violation

### ISSUE THREAD

**Issue by Trillx** [NECROBOTIO/NecroBot#4152]
so a user for NECROBOT was logging in and all that occured was this might be something to look into 
dont know what it is ----------- thank you for your hard work DEV's

![ss 2016-08-09 at 04 04 19](https://cloud.githubusercontent.com/assets/20881828/17535669/dcd08088-5e44-11e6-970d-33a45245657b.png)

**Comment by theloser** [comment]
Maybe some errors with your proxy configuration?

**Comment by Trillx** [comment]
Nooo everything is fine with proxy

**Comment by theloser** [comment]
Sure? Prove it and post your auth.json.

**Comment by nfettinger** [comment]
If this is reproducible, please create a new issue. Closing
