### ISSUE TITLE
Doesnt Transfer all Pokemon

### ISSUE THREAD

**Issue by Kiwaaa2** [NECROBOTIO/NecroBot#4156]
I got the Problem that the bot doenst transfer all pokemon under cp 731 just a view of them, maybe 1 to 3 but i got ~10-20 pokemon under cp 731.

Maybe one of you can help me.

  "EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 731,
  "KeepMinIvPercentage": 80.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,

  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by aaron25th** [comment]
do you have more specific transfers filters further down the config

**Comment by PedroSeda** [comment]
It Prioritizes KeepMinDuplicatePokemon, so it keeps 1 of each pokemon even if it is lower than the KeepMinCP

**Comment by Kiwaaa2** [comment]
@aaron25th   
"PokemonsNotToTransfer": [
    "charizard",
    "gyarados",
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

@PedroSeda And in what should i change it`?

**Comment by FranManre** [comment]
> "EvolveAboveIvValue": 90.0,
> "EvolveAllPokemonAboveIv": true,
> "EvolveAllPokemonWithEnoughCandy": true,
> "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
> "KeepPokemonsThatCanEvolve": false,
> "KeepMinCp": 731,
> "KeepMinIvPercentage": 80.0,
> "KeepMinLvl": 6,
> "KeepMinOperator": "or",
> "UseKeepMinLvl": false,
> "PrioritizeIvOverCp": false,
> "KeepMinDuplicatePokemon": 1,
> 
> "TransferWeakPokemon": true,
> "TransferDuplicatePokemon": true,
> "TransferDuplicatePokemonOnCapture": true,

Set "KeepMinOperator": "or" to "KeepMinOperator": "and", with or operator it will keep also pokemons > 80% IV or > Lvl 6.
Also take a look on the last part of the config, something called "PokemonsNotToTransfer", to empy it, change all it for this one:
`"PokemonsNotToTransfer": [],`

**Comment by PedroSeda** [comment]
Well, if you don't need one of each pokemon, just change KeepMinDuplicatePokemon to 0. That will transfer all pokemon below 731CP, 80%IV or LVL6, but you can change those too

**Comment by Kiwaaa2** [comment]
@PedroSeda @franmanre Someone of you did fix it. Thanks!

**Comment by WishmasterNano** [comment]
setting `"KeepMinOperator": "or"`, to` "KeepMinOperator": "and"` should not be needet since `"KeepMinLvl": 6,` isnt a problem because of `"UseKeepMinLvl": false,`

**Comment by palooga** [comment]
I have the same problem. I have like 30 krabbys, etc. That do not ever get transferred.
