### ISSUE TITLE
Softban over and over again

### ISSUE THREAD

**Issue by Beastv1** [NECROBOTIO/NecroBot#4161]
I'm using 2 bots one on laptop and one on pc.  It always says "No usable pokestops found in your area."  Please help.

**Comment by CameForTheCrown** [comment]
you need to set up a proxy server

**Comment by AndreasGilja** [comment]
Tutuapp dont work now

Sendt fra min iPhone

Den 10. aug. 2016 kl. 00.44 skrev Beastv1 <notifications@github.com<mailto:notifications@github.com>>:


I'm using 2 bots one on laptop and one on pc. It always says "No usable pokestops found in your area." Please help.

-

**Comment by Beastv1** [comment]
@CameForTheCrown  how

**Comment by devildog81** [comment]
You are IP banned.

**Comment by fatchan** [comment]
make sure you have human walking enabled/not disabled. I think 0.8.0 had it off and 0.8.1 disabled it (as a fix), but since your config is saved by default, it might be carrying over the bad config.

**Comment by theloser** [comment]
Two bots on laptop and one on PC = Three bots --> instant softban.
Use proxy server -- if you don't know how, please go to the discord channels and ask for help.

**Comment by Beastv1** [comment]
Ok thanks everyone

**Comment by fatchan** [comment]
@theloser can I just use any socks5 proxy? I have my own source.

**Comment by theloser** [comment]
I don't know if a socks5 proxy is supported. Try it and report back. HTTPS proxy works for me.

**Comment by schwartzadev** [comment]
Socks5 is not supported yet.
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
