### ISSUE TITLE
Suggestion - No more new features, fix bugs first. 

### ISSUE THREAD

**Issue by vfuyong** [NECROBOTIO/NecroBot#4163]
I can see there are too many changes and new features, the testing does not catch up. Please consider this. 

I am still on 0.7.6, the much more stable version than higher.

**Comment by cawk** [comment]
We are working on fixing as many bugs as we come across to make releases as stable as we can

**Comment by schwartzadev** [comment]
Interesting (meta) feedback...Because this is open source, anyone can contribute to it. Because of this, many people have decided to add new things (i.e. Telegram) instead of fixing bugs. Also, squashing bugs isn't very enjoyable for devs. The devs are busy. Please respect them and their time.
