### ISSUE TITLE
Pokestops do not retrieve (enough) items (gems: 50 items: 0) How to keep more pokeballs?

### ISSUE THREAD

**Issue by Thujon** [NECROBOTIO/NecroBot#4170]
How do I keep more pokeballs/retrieve more stops that give pokeballs? I've read somewhere the bot only spins every 5th pokestop? I'm in Central Park and there are hundreds of pokestops there, but my bot only seem to only use one every 30 seconds.. 

How to solve this? It feels 

I miss alot of XP and pokeballs this way. is it the human speed? or what is it? anyone have the same issue?

Thanks in advance

**Comment by Thujon** [comment]
bump

**Comment by theloser** [comment]
>...every 5th pokestop

Bullshit.

What is your setting on TotalAmountOfPokeballsToKeep and how many Pokeballs do you have?

**Comment by iwantmyfile5** [comment]
The every 5th pokestop thing is for sniping and i believe it triggers the transfer pokemon loop, but i could be wrong about that part. It definitely isn't spinning every 5th pokestop, you probably just have it set to keep too many of the other items in your bag and theres not enough room for pokeballs

**Comment by Thujon** [comment]
I set the pokeballstokeep on 300(have 450 bagspace) and i have around 90 now since I was always around 0-5 pokeballs. I used Bluestacks to get more pokeballs and it seemed that I catch a bit more pokemon now. I started 30 minutes ago with 140 pokeballs so its dropping quite hard if you ask me.

**Comment by theloser** [comment]
Please set DetailedCountsBeforeRecycling to true and post EXACTLY how many Pokeballs you have according to the bot output.

**Comment by Thujon** [comment]
I threw everything else away and never been full bag since I have 450 bag space and only keep 5 potions etc. Set everything so its all about the pokeballs.

**Comment by theloser** [comment]
Please do what I asked for (post your bot output with the number of pokeballs). Otherwise I can't verify.

**Comment by Thujon** [comment]
Yes working on it now, was a reponse to iwantmyfile5*

**Comment by Thujon** [comment]
It's set to True and bot says I have 83 pokeballs left

**Comment by theloser** [comment]
POST. THE. EXACTLY. BOT. OUTPUT.

**Comment by Thujon** [comment]
Okeeee, What do you mean by bot output? I'm not used to this kind of computer language in English(I'm Dutch). Where do I find Bot Output?

**Comment by Thujon** [comment]
"TranslationLanguageCode": "nl",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 100,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 6,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 40.773481251816435,
  "DefaultLongitude": -73.973039388656616,
  "WalkingSpeedInKilometerPerHour": 31.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 1850,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": true,
  "GpxFile": "CentralPark_Period.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 300,
  "TotalAmountOfPotionsToKeep": 5,
  "TotalAmountOfRevivesToKeep": 5,
  "TotalAmountOfBerriesToKeep": 30,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemPokeBall",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "nidoranMale",
    "nidoranFemale",
    "spearow",
    "rattata",
    "zubat",
    "venonat",
    "krabby",
    "paras",
    "slowpoke",
    "jigglypuff",
    "seel",
    "oddish",
    "horsea",
    "voltorb",
    "doduo",
    "poliwag",
    "mankey",
    "ekans",
    "sandshrew",
    "bellsprout",
    "diglett",
    "goldeen"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by Thujon** [comment]
This?

**Comment by theloser** [comment]
The bot tells you exactly how many pokeballs you have. Something like:

> (INFO) xx Pokeballs | xx GreatBalls | xx UltraBalls

or something like this. Copy and paste this line.

**Comment by theloser** [comment]
No. Not your config.json.
Start the bot.
Watch the console.
Wait for a line which tells you how many balls are in your inventory.
Copy and paste this line.

**Comment by Thujon** [comment]
[01:41:56] (CatchSuccess Poging #2) | (Normal) Eevee Lvl: 6 CP: (165/177) IV: 69,00% | Kans: 49,83% | 56,04m ver | met een PokéBall (82 over). | 210 EXP verdiend | Candies: 382 | lat: 40,774275 long: -73,97322

**Comment by theloser** [comment]
No. This:

> [01:44:33] (INFO) 3 x Pokeballs, 4 x GreatBalls, 197 x Ultraballs, 0 x Masterballs

**Comment by Thujon** [comment]
I don't see that in my logm I used to see it but not anymore... what could have caused it?

**Comment by theloser** [comment]
It's right above the message:

> \(RECYCLING\) Recycling...

**Comment by theloser** [comment]
Start your bot.
Wait until it is recycling items.
MAKE A SCREENSHOT.
Post it.

**Comment by Thujon** [comment]
It havnt recycled in hours.. When should it recycle? May I ask, what is it you look for?

**Comment by Thujon** [comment]
I'll keep the bot running through the night, I'll check the log tomorrow and then will post anything with Recycle here. goodnight.

**Comment by RiPPERD** [comment]
"VerboseRecycling": true,

this line needs to be like this or it will NOT display items its recyling etc

**Comment by Thujon** [comment]
it's on true @RiPPPERD There was no single Recycle display whole night.. but it seems like it runs alright now.. weird?

**Comment by theloser** [comment]
Ok. Locate the log folder beneath your necrobot folder, pick a logfile from 3-4 hours ago, upload it here or paste it to pastebin.com and then link it here please. (Please DON'T paste the content of the logfile into you comment, ok?)

**Comment by Thujon** [comment]
[NecroBot-2016-08-10-18.txt](https://github.com/NECROBOTIO/NecroBot/files/411572/NecroBot-2016-08-10-18.txt)

**Comment by Thujon** [comment]
[NecroBot-2016-08-10-08.txt](https://github.com/NECROBOTIO/NecroBot/files/411576/NecroBot-2016-08-10-08.txt)

**Comment by Thujon** [comment]
Last one is a longer on, no recycles..

**Comment by theloser** [comment]
First of all thanks for the logfiles! I checked them and this is where it becomes really weird, because they contain some errors I can't explain. For example:

> [08:23:09] XP: The Falconer, Gems: 100, Items: 0

That's a log from a Pokestop, but it's logging wrong values: normally it should say:

> [08:23:09] Name: The Falconer, XP: 100, Gems: 0, Items: 1x PokeBall, ...

According to your logfile you never got any items (which isn't true), so your language file obviously is incorret. I can see you are using the language "nl" (because of this: "Broedmachine status update..."), right? There are a lot of error in this language file (I will create an issue for that), and maybe that's why we can't see any recycles...?!

Please, we have to check this again, so do me a favor: edit your config.json file and change to following (right at the start of the file). From:
```
 "TranslationLanguageCode": "nl",
```
To:
```
 "TranslationLanguageCode": "en",
```
Then start your bot again and we will have to check again in a few hours with new logfiles, ok?

Thanks a lot in advance!

**Comment by Thujon** [comment]
Changed it to EN and pokestops now do give the items picked up, I will run the bot for a few hours and will give you the log(s) of it.

**Comment by theloser** [comment]
Great, good luck!

**Comment by nfettinger** [comment]
Use Discord chat for help.
