### ISSUE TITLE
Recycling all my Potions

### ISSUE THREAD

**Issue by ImSharp** [NECROBOTIO/NecroBot#4173]
Whenever the bot starts recycling it will recycle all my Potions, Superpotions and Hyperpotions.

**Comment by Rick058** [comment]
You can change the amount to keep in your config.json

`  "TotalAmountOfPotionsToKeep": 50,`

**Comment by theloser** [comment]
Check your TotalAmountOfPotionsToKeep setting.

**Comment by ImSharp** [comment]
This is my `TotalAmountOfPotionsToKeep` setting:
`  "TotalAmountOfPotionsToKeep": 80,`

**Comment by theloser** [comment]
Set DetailedCountsBeforeRecycling to true and post how many Potions you have.

**Comment by ImSharp** [comment]
`DetailedCountsBeforeRecycling` is already on true.

**Comment by theloser** [comment]
> post how many Potions you have

**Comment by ImSharp** [comment]
Everytime I get any type of Potion it will be recycled so my number of Potions will be for ever 0.

**Comment by theloser** [comment]
For fuck's sake: because you have the detailed output from your bot, just POST IT HERE SO WE CAN VERIFY! (Or just close this issue.)

**Comment by ImSharp** [comment]
`[01:20:17] (POKESTOP) Name: A.W. Ross Bust XP: 50, Gems: 0, Items: Inventory is full, no items looted!, Lat: 34.06265, Long: -118.354688
[01:20:17] (INFO) Pokeballs: 19 | Greatballs: 3 | Ultraballs: 114 | Masterballs: 0
[01:20:17] (INFO) Potions: 5 | SuperPotions: 2 | HyperPotions: 0 | MaxPotions: 80
[01:20:17] (INFO) Revives: 66 | MaxRevives: 0
[01:20:17] (INFO) Berries: 56 | Incense: 0 | LuckyEggs: 0 | Lures: 6
[01:20:17] (RECYCLING) 16x ItemPokeBall
[01:20:18] (RECYCLING) 5x ItemPotion
[01:20:19] (RECYCLING) 2x ItemSuperPotion
[01:20:19] (RECYCLING) 6x ItemRevive
[01:20:20] (RECYCLING) 6x ItemRazzBerry`
Here you go.

**Comment by Rick058** [comment]
@ImSharp what @theloser means is that with your current settings you already have 80 potions in your inventory. So whenever you visit a Pokéstop and get new potions they will automatically get recycled because you are on your potion limit.

**Comment by theloser** [comment]
You got 80 MaxPotions, these are the BEST postions you'll ever get! That's how this works! The Bot recycles less potions if you have 80 Potions IN TOTAL.

**Comment by ImSharp** [comment]
Oh, sorry for wasting your time guys.  I though that 80 was the number referred to the max amount of any kind of Potions I could have in my Inventory.

**Comment by theloser** [comment]
Yeah, that's right. It's the max amount of ANY kind of potions you can have in your inventory. But why recycle MaxPoitions if you can recycle lesser Postions instead?
