### ISSUE TITLE
Can we use our own device info?

### ISSUE THREAD

**Issue by TravisMeister** [NECROBOTIO/NecroBot#4175]
Is that possible, because I got mine from my phone and everytime I start NecroBot it replaces the configs on the auth file with the default ones.

**Comment by theloser** [comment]
Set DevicePackageName to "custom" and use your own device settings.

**Comment by schwartzadev** [comment]
Yes. You must get it through adb, an app, or use this [database](http://specdevice.com/).

Next time, please use [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
