### ISSUE TITLE
Keeps EVERY Pokemon

### ISSUE THREAD

**Issue by palooga** [NECROBOTIO/NecroBot#4176]
It is not throwing away krabbys, rattatas, staryus,
I have like 20 of each and they are like all 0-600 cp and under 50 iv
Why does the bot not transfer?

Config below..
http://pastebin.com/jDfkFSZm

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by palooga** [comment]
Why not close the other 300 ones about this issue
