### ISSUE TITLE
error converting value " to type pogoprotos.bla

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#4177]
http://puu.sh/qvH5Z/1890bfb86c.png

screen taken on 0.8.2 precompiled source @cawk sent me to test

**Comment by cawk** [comment]
does this error happen alot looks more like a response error

**Comment by FranManre** [comment]
the value of the pokemon id on the server is empty

**Comment by cawk** [comment]
is a server error not an error to do with the code
