### ISSUE TITLE
not transferring evolved pokemons

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#4178]
itll evolve caught raticates but evolved raticates and fearows and arboks seem to stay until it clogs inventory, then bot cant catch anymore.

**Comment by necr-0** [comment]
Could you add your config file to Pastebin? I'll give it a look.
Seems like you might just have a problem with transfer settings.

**Comment by wetshrimp** [comment]
http://pastebin.com/sk0fj278

they are definitely not level 30 or 97 iv lol

thanks

furthermore
    "Exeggutor": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 28,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

yet i have around 6 level 24 exeggutors with like 80iv lol. ???

**Comment by nfettinger** [comment]
Use Discord chat for help.
