### ISSUE TITLE
NecroBot-0.8.1

### ISSUE THREAD

**Issue by ceyco** [NECROBOTIO/NecroBot#4183]
i download it an it has a Windows command script only has no .exe file anywhere in the files show how am i supposed to get the necro bot to start an run in CMD or even get it to make a config.json file? or am i stupid or blind??

thanks in adv

**Comment by Rick058** [comment]
You sure you downloaded this one > https://github.com/NECROBOTIO/NecroBot/releases/download/v0.8.1/Release.zip

And not the source code?

**Comment by necr-0** [comment]
Download "Release.zip" from the page: https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.8.1
Extract it and then run the application. There's an inbuilt setup that'll take you through it.

**Comment by schwartzadev** [comment]
solved
