### ISSUE TITLE
I just designed a GUI for Necrobot

### ISSUE THREAD

**Issue by iTayGNR** [NECROBOTIO/NecroBot#4188]
Hello there.

I heard that you're planning to make a GUI for the bot.
The moment I heard that I got excited, because once you have a GUI you're the winning bot out there.
I know that you're super busy with bug fixing and stuff, so I thought how can I help.
As a graphic designer, I started instantly to work on a GUI and I'd be glad to give it to you.

This is the index page with all menus opened: http://i.imgur.com/In5TdQZ.jpg
(don't forget F11 and 1920x1080 screen for best experience)
It's only about the design now. I'm not a programmer but I do know the internet programming languages pretty well (HTML, CSS, JS, PHP, JQUERY). not sure that can help but I'm open minded.

let me know what you think.
Itay

(sorry for the bad english and the fact I contacted you through here as an issue: Discord didn't let me send a private message to any of you)

**Comment by theloser** [comment]
Wow, looks great! Thumbs up!

There already is a "GUI" project for Necrobot: https://github.com/nicoschmitt/necrobotvisualizer (which also has features like evolve and transfer pokemons etc.)

I think what really could help is a GUI to get the bot running, so users don't have to fiddle with the JSON files.

**Comment by iTayGNR** [comment]
@theloser thanks!
I know about that GUI but i find it very messy. That's why I thought about a really clean GUI that I hope will be integrated with Necrobot in the future, Because Necrobot needs a GUI, that's for sure ;)

**Comment by Chaos2522** [comment]
I accidently recycled an 3.3k Dragonite with necrobotvisualizer GUI, wanted more information about it and clicked on it, thought i'll see moves, click was faster then the popping image of the trashcan, sadly it recycles it instantly. Tried to close the bot half second after that click, but it was gone anway

**Comment by hilmibou** [comment]
could somebody explain how to installa the necrobotvisualizer. i have a map called Release, the bot is running properly. (also installed Node V4.4.7, dont know if necessary) downloaded necrobotvisualizer from: https://github.com/nicoschmitt/necrobotvisualizer and now?

**Comment by theloser** [comment]
This is a visualizer issue, and it has a Readme, in which you can read:

> Go to the release tab, grab the latest and just launch it.

Have you tried this?

**Comment by hilmibou** [comment]
Hey theloser,

it keep saying connecting to the bot....

**Comment by Chaos2522** [comment]
Did you set Websocket to true?

"UseWebsocket": true,
  "WebSocketPort": 14251

**Comment by hilmibou** [comment]
yes i did

**Comment by GediminasMasaitis** [comment]
Hey iTayGNR, that looks amazing! I'd be interested in helping you out implement the logic behind it. I messaged you on Discord - Gedas#9879

**Comment by iTayGNR** [comment]
Work In Progress https://github.com/iTayGNR/NecroEase

**Comment by vandernorth** [comment]
If I can help, or if you want to merge something I made ( https://github.com/vandernorth/NecroBot.GUI ) let me know! Like your design!

**Comment by tibehrius** [comment]
@vandernorth ...man.... # I LOVE YOU!!!!!!!!!!!!!!!!!!!!! Your project is **VERY VERY nice**!!!!

Thanks again!!!!
