### ISSUE TITLE
RenameTemplate Issue: Not possible to switch from "{0}{1}" to "{1}{0}"

### ISSUE THREAD

**Issue by Chaos2522** [NECROBOTIO/NecroBot#4191]
Would like my bot to rename my Pokemon like "Dragonite100" instead of "100Dragonite"
But if i switch the template from "{0}{1}" to "{1}{0}", it simply ignores the change.

**Comment by theloser** [comment]
Please post the according line from your config. I changed the template, too, and it's working for me.

**Comment by Chaos2522** [comment]
"RenameTemplate": "{1}{0}", i'm using it like this.
If i switch those numbers forth and back, same outcome, using "de" version atm, could it have something to do with that?

**Comment by palooga** [comment]
`"RenameTemplate": "{0}{1}",`
I am about to test this and I'll see if it renames all mine. I currently use: 
`"RenameTemplate": "{1}_{0}",`

**Comment by theloser** [comment]
I have mine set this to "{1}_{0}" and it is working (I am using "en" as language though). Maybe there has to be a character between {0] and {1}? The default is "{0}_{1}"...

**Comment by Chaos2522** [comment]
It's set to 
"RenamePokemon": true,
"RenameOnlyAboveIv": false,
"RenameTemplate": "{0}{1}",

will try to switch de to en, sec

**Comment by palooga** [comment]
Any luck?

**Comment by avatarium** [comment]
it's working fine

why don't you use {0}_{1} ?

the name looks better as Dragonite_95, than Dragonite95, but that's just me

**Comment by Chaos2522** [comment]
Stock 0.8.1 works as intended, renaming them to Dragonite95 with "RenameTemplate": "{0}{1}",
de/en, doesnt matter. 
Looks like the one i compiled 30minutes ago is acting up, guess it's time to close thise one and wait if something changes at 0.8.2
