### ISSUE TITLE
Sniper shit since 0.7.7 each update with no help but worse

### ISSUE THREAD

**Issue by atolkien** [NECROBOTIO/NecroBot#4193]
The bot snipers but did not to find every time,can u guys just fix the bug, it has been here from 0.7.7 to the newest version

**Comment by cawk** [comment]
what is the issue?
if its regarding repeating the same list then that has been fixed please download and compile the source

**Comment by Chaos2522** [comment]
0.8.1 didnt work for me as 0.7.7 did, but if you compile your own from the repository, it'll fix those problems (adds pokewatcher and enables you to set all of those onlineserver to true) if you cant/wont compile it yourself, just wait for 0.8.2 to be released

**Comment by zenis12** [comment]
How to compile to fix that problem?

**Comment by Simpuhl** [comment]
@Chaos2522 

So with 0.8.2 we should be able to pokezz.com without the pogofeeder?

**Comment by atolkien** [comment]
Not repeating,just can't find the pokemon from top to bottom,most people in discord  snipering with ur bot have the same issues.

**Comment by zenis12** [comment]
Can someone upload a 0.8.1 version with that problem fixed?

**Comment by atolkien** [comment]
There is no fixed, so I can't

**Comment by zenis12** [comment]
Loop same snipe locations

**Comment by zenis12** [comment]
Thanks anyway ;-)

**Comment by atolkien** [comment]
They said the sniper no found issues could be fixed by adjusting the sniperoffset before, but now it seems doesn't work at all

**Comment by atolkien** [comment]
Not loop,just each snipers are no found

**Comment by atolkien** [comment]
Each snipers' answer is did not find a pokemon,but actually location have the pokemon the sniper shows

**Comment by atolkien** [comment]
And I put my snipperoffset to default, but each snippers are still "did not find a Pokemon within the snipingscanoffset

**Comment by kurozani** [comment]
my snipers didn't find the pokemon most of the time, but simetimes they found something

means it worked fine XD

**Comment by Chaos2522** [comment]
As most of the devs are currently sleeping and your problem has been resolved via update to the code, either wait for them to release 0.8.2 or compile the repository yourself

**Comment by atolkien** [comment]
Something not means work well, omg,just admit the issue can't be so embarrassing,sniper hundreds no found with one find is not just working"well"

**Comment by atolkien** [comment]
Most people in discord have the same issue,ur working fine means notingXD

**Comment by Chaos2522** [comment]
@atolkien you dont seem to understand what i'm trying to tell you, they noticed that it didnt work properlly and fixed it. If you build your own Necrobot from the repository right now -> Problem solved, 
So either fix it yourslef -> compile your own bot, or wait for them to compile it for you with 0.8.2.
The issue has been fixed, so there's no use in pointing it out anymore.

**Comment by RiPPERD** [comment]
sniping been working great for me today... got loads of rares today and maxed them out

you must turn on a few sniping options

**Comment by atolkien** [comment]
Wow such answer impressed me so much, u guys cut so many people's throat just because ur bot works fine for u.my config settings are exactly what u asked in the fixd post,now it begins to loop three times after  did not find a pokemon within the snipingscanoffset,everything is fine,ur bot is fine,just because two guys jumped in said oh today I got catch rare them all,hilarious!see the feederback by users before u said everything is fine.:)

**Comment by recon88** [comment]
For general questions or if help is needed with configuration, visit our Discord: https://discord.gg/VXKxNFr
