### ISSUE TITLE
Soft banned all times.... >_<

### ISSUE THREAD

**Issue by cikenpukpuk** [NECROBOTIO/NecroBot#4196]
![softbanned_2](https://cloud.githubusercontent.com/assets/20737801/17537886/7d4ceeea-5eca-11e6-8a0b-781315b682dc.JPG)

Softbanned all times, im not snipe and just opened 1 bot..
need help and proxy setting

**Comment by Strancyth** [comment]
Same issue for me...

**Comment by Rick058** [comment]
_1) Stop running more than 2 bots on the same IP, 2 is really the max._ 
2) Close all your running bots
4) Download and start hide.me VPN
5) Start the bot, let it run WITH VPN enabled for 5 - 10 minutes
6) It should force an unban now you are on a different IP and work correctly after
7) Disable the VPN or leave it on, doesn't really matter after 5 - 10 minutes.

This method worked for me on 0.7.6, unsure about latest release.

**Comment by palooga** [comment]
Post your config on pastebin and I will tell you why you are getting soft banned

**Comment by Strancyth** [comment]
Here is myconfig

http://pastebin.com/ZpcDv5su

**Comment by palooga** [comment]
Are you using PTC or Google Login?

**Comment by Strancyth** [comment]
google

**Comment by Strancyth** [comment]
@Rick058 this solved my issue but sooftban loop start
another time in 5 minutes

**Comment by palooga** [comment]
`"RenameTemplate": "{0} {1}%",`
I haven't read about this but what does the percentage do here? The default is usually `"{0}{1}"`
Could be picking up that you have all your pokemon named with a percentage which is odd so it bans you?


Maybe try disabling the sniper for a few minutes and let it collect pokestops then re-enable and see if it fixes because everything looks good to me. Sorry I can't help much more than that.

**Comment by cikenpukpuk** [comment]
@palooga  may u share u config please

**Comment by palooga** [comment]
http://pastebin.com/HkM67XAb
This should keep high CP pokemon and high IV pokemon. But check the settings to make sure it has what you are comfortable with. Do not come complaining to me if it does something you don't like. I spent hours tweaking this lol.

**Comment by Strancyth** [comment]
@palooga as i disable the sniper?
