### ISSUE TITLE
Niantic ninja update?

### ISSUE THREAD

**Issue by nerdcustoms** [NECROBOTIO/NecroBot#4197]
I see niantic just did a ninja patch on my iphone.  Bots are now showing "unable to find pokestops."  Can someone confirm it's not just me and that there will need to be a new update.

**Comment by kurozani** [comment]
nope, my bot is doinmg fine

but yeah, there is a new update this morning on pokemon go

anyone got the apk file? XD

**Comment by nerdcustoms** [comment]
The bots stopped working after closing and re-opening.  Can you close one out and confirm it still works when you open it?   Could be that they are just having too many server requests and I'm an unlucky one.

**Comment by kurozani** [comment]
I just did

and got a loop of softbanned, but still works :)

**Comment by nerdcustoms** [comment]
and as soon as I posted they, they started picking up again, must have been temporary server issue.  Thank you for your responses. :)

**Comment by danooh** [comment]
just closed and reopened mine - still working fine. keep in mind that it is 2 bots per ip - otherwise you'll get softbanned

**Comment by nerdcustoms** [comment]
that's probably why, I have 5 running.
