### ISSUE TITLE
Please help me.. I never use pogofeeder .. just a regular bot ..

### ISSUE THREAD

**Issue by phoojunior** [NECROBOTIO/NecroBot#4200]
![eror gila](https://cloud.githubusercontent.com/assets/20917363/17537986/b3f92dba-5ed3-11e6-878d-eb5635d784c9.jpg)
could not help me .. create bot like before her did not bother as it is now .. I am not a programmer ..

**Comment by danooh** [comment]
your latitude is wrong. check your config.
that is what the first red line states:
Argument must be in range of -90 to 90
Parameter name: latitude

**Comment by Rick058** [comment]
Your latitude / longitude is incorrect

**Comment by phoojunior** [comment]
could give me an example of that true?

**Comment by danooh** [comment]
"DefaultLatitude": 40.712784,
"DefaultLongitude": -74.005941,

**Comment by bulubebek** [comment]
double check your configuration file. this is not issue, mod pls close.

ps. lain kali baca guide di [wiki](https://github.com/NECROBOTIO/NecroBot/wiki) dulu.

**Comment by phoojunior** [comment]
ps. maksud nya apa? aku udah baca wiki.. tapi udah berkali2 ganti longatitude tetap bermasalah

@danooh thx.. im try it..

**Comment by Rick058** [comment]
He does log in though, if he messed up his `DefaultLatitude `and/or `DefaultLongitude `he would have received a different error. Guessing you messed something up under   `"PokemonToSnipe": {`
Mind to share your config.json settings?

**Comment by phoojunior** [comment]
please share config.json

**Comment by phoojunior** [comment]
![eror gila](https://cloud.githubusercontent.com/assets/20917363/17538245/49a0e4e6-5ed6-11e6-9a4d-6820af9e4594.jpg)
@Rick058  this my config.json... please share config.json work...

**Comment by bulubebek** [comment]
definitely wrong lat/long. here is the example for Jakarta (Monas)

```
  "DefaultLatitude": -6.175438, 
  "DefaultLongitude": 106.827189,
```

**Comment by theloser** [comment]
Your coordinates (lat/lng) are wrong. Check your configuration, then check it again. (Hint: ".")

**Comment by Rick058** [comment]
@phoojunior Yeah line 23 and 24 are completely wrong, see @bulubebek 's post for the right way to do it :) use www.latlong.net to find the right coordination.

**Comment by phoojunior** [comment]
@Rick058  wait im setting new line 23 and 24

**Comment by phoojunior** [comment]
![1](https://cloud.githubusercontent.com/assets/20917363/17538455/1dec1bf2-5ed8-11e6-962d-4f839f425335.jpg)
@Rick058  not work too..

**Comment by Rick058** [comment]
Remove the .0 behind it?
`-6.175438,`
`106.827189,`
Central Jakarta, Central Jakarta City, Special Capital Region of Jakarta. Correct?

**Comment by phoojunior** [comment]
![parah](https://cloud.githubusercontent.com/assets/20917363/17538504/93da98d4-5ed8-11e6-8ea4-213a81f6c4dd.jpg)

ok wait.. im remove 0 behind

**Comment by bulubebek** [comment]
@Rick058 correct! (just an example since I saw him define "id" as necro's language).
@phoojunior there is should be no additional ".0" on lat/long configuration. remove it.

**Comment by phoojunior** [comment]
@Rick058 thanks u very much.. working.. can u invite me friend.. if i have problem again D1947AE6
@bulubebek thank u.. coba kek kasih tau gitu dari awal.. maklumin lah saya bukan programer.. saling membantu.. bagi pin dong..

**Comment by bulubebek** [comment]
no BBM. :)
glad to help, please close this issue.
