### ISSUE TITLE
Is it risky to force perfect throws

### ISSUE THREAD

**Issue by TravisMeister** [NECROBOTIO/NecroBot#4201]
As title says, is it risky, if not why dont do it often, it gives extra exp right?

**Comment by kurozani** [comment]
i always use perfect throw

**Comment by bulubebek** [comment]
Humanized throws shipped with default config. Nothing to worry.

`"EnableHumanizedThrows": true,`

**Comment by TravisMeister** [comment]
good to know that, thanks guys.

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
