### ISSUE TITLE
always softban T_T

### ISSUE THREAD

**Issue by mostgod** [NECROBOTIO/NecroBot#4202]

**Comment by gokugoku363** [comment]
dont travel state to state or country to country when u put in the latitude and longitude... if you want to chance your location via longitude and latiude dont chance it too far for youll get soft banned

**Comment by Rick058** [comment]
Stop running more than 2 bots if you do, 90% of the time that is the issue when people are reporting a loop of softbans.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
