### ISSUE TITLE
How far can you snipe?

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#4205]
I"m a little confused how it works.  I'm currently using someone else's build set to 20000m and it seems to be working fine, but wondering what the safety limits are.

also, how can you snipe 20km away, but if you set your lat long to a place 20km away you'll get soft banned?  i have no idea how this works.

**Comment by erikk00** [comment]
sniping is intended for sniping across the world.  I don't even think there is an option for only snipe within some sort of range.  The concept of sniping is your character teleports to the other location, does NOTHING but start the pokemon capture attempt and then teleports back.  Then captures the mon when you're back where you started.  The servers don't register where you started the capture, only where you complete it.  Like if you're driving in a car and start a capture at a red light you can actually capture it at the next one.  

Sniping 20kms is almost certainly as noticeable by niantic as sniping 2000kms.  With the possible exception of region specific mon; if you catch a Mr Mime in Louisiana, they'd probably be able to notice that easily too.

**Comment by DariusFoxy** [comment]
oh i see. thanks for the info. so then the 20km is just his wandering range on the build i copied from. 
that's a good point about the mime's and region specific. maybe a good idea to turn them off when in the wrong country.
