### ISSUE TITLE
Unsabl Pokestop, distanc too small

### ISSUE THREAD

**Issue by PokeyMasta** [NECROBOTIO/NecroBot#4208]
Okay i try everything it still says the sam thing over and over. No useabl PokeStop found..... Max distance too small
![hlp](https://cloud.githubusercontent.com/assets/20919841/17538410/fafed784-5e59-11e6-8ce6-7e0ef7f5b8b8.png)

**Comment by palooga** [comment]
You are IP banned. You are probably running too many bots.

**Comment by AtomClock** [comment]
Are you trying to run many instances of the program with multiple account from the same IP ?

Niantic added a IP throttling.

You usually get that message when you are soft ban

**Comment by grittan** [comment]
yeah just happened to me also and now its back up

**Comment by AtomClock** [comment]
> You are IP banned. You are probably running too many bots.

For me it seems like as low as 2 accounts get me IP banned

**Comment by AtomClock** [comment]
To avoid that you can put your proxy setting in auth.json

**Comment by Chaos2522** [comment]
Either you are running more than 3 bots at the same time (same IP)which will get you ip-throttled, or your location is desolate (try to change it// increase max distance)

**Comment by grittan** [comment]
yeah im running two also and it worked all day but i mistakenly opened a third and it happened

**Comment by Chaos2522** [comment]
strange, running 3 for 48h now, only happens when i try to run 4+

**Comment by grittan** [comment]
i dont think there ip throttling is very accurate but something like running two under the same loggin could set it off

**Comment by PokeyMasta** [comment]
how do you fix the proxy, mine is on like null

> Either you are running more than 3 bots at the same time (same IP)which will get you ip-throttled, or your location is desolate (try to change it// increase max distance)

As this issue was resolved by @AtomClock "To avoid that you can put your proxy setting in auth.json"
please consider closing it. :)

**Comment by nfettinger** [comment]
****

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
