### ISSUE TITLE
Wont keep strong Pokemon i catch

### ISSUE THREAD

**Issue by gokugoku363** [NECROBOTIO/NecroBot#4210]
My necrobot will catch a pokemon (for example an eevee) but wont keep it because i already have an eevee. but the one i already have is 22 cp and the one necrobot just caught was 600 but it transfered the 600 cp eevee instead of transfering the weaker eevee and keeping the stronger one. How do i fix!?!?

**Comment by palooga** [comment]
It priotizes IV over CP. Change that setting or the duplicate. 
Learn to read.

**Comment by schwartzadev** [comment]
Probably a problem with your config.

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by kurozani** [comment]
open config

make sure your "prioritizeivovercp" is false
