### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by lappen1337** [NECROBOTIO/NecroBot#4214]
How can i actually change the language ? in the setup i wrote translation.de.json and translation.de and both did not work.
Thanks for the help

**Comment by Oolaruu** [comment]
Just    de

**Comment by palooga** [comment]
In your config file:
`{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,`
`
Change this line
`  "TranslationLanguageCode": "en",`
To
`  "TranslationLanguageCode": "de",`

WOW

**Comment by lappen1337** [comment]
WTF WHY I DONT SAW THIS LINE 
thank you guys very much
