### ISSUE TITLE
Upgrading Question

### ISSUE THREAD

**Issue by xShiroinekox** [NECROBOTIO/NecroBot#4216]
Hi guys... Good to learn that we are able to use this good bot.

A question about upgrading and leveling pokemon. 
I have set the req. for leveling the pokemons. So every 5th pokestop the will do recycle, transfer and upgrade. Everything is fine except for level up. It just won't level up pokemons.It is collecting the stardust over the GetMinStarDustForLevelUp. i set it at 40000. But it already 70000.

Thank you.

**Comment by anyhere** [comment]
any issues with changing delay to 0 ?? going for lucky egg + mass exp. whats the safest way to do it?

**Comment by xShiroinekox** [comment]
Any help is great. Please

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.

**Comment by anyhere** [comment]
sure thing net send me a link to how to download or get into to Discord chat please and forgive me didn't know.
