### ISSUE TITLE
 I need how to use more than three accounts?

### ISSUE THREAD

**Issue by sarah1598** [NECROBOTIO/NecroBot#4217]
I need how to use more than three accounts?

**Comment by Rick058** [comment]
Configure the proxy settings in auth.json in order to run more than 2 bots.

**Comment by sarah1598** [comment]
But I used the third, he began to unban

**Comment by sarah1598** [comment]
Then you can not use

**Comment by sarah1598** [comment]
Can you teach me how do I setting please?

**Comment by Chaos2522** [comment]
Pls take this conversation to the discord/support channel, this is not an issue with the current release.
Pls close this issue.

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
