### ISSUE TITLE
[Suggestion] Transfer weakest pokemon

### ISSUE THREAD

**Issue by beremp** [NECROBOTIO/NecroBot#4220]
I like to keep at least 1 of each pokemon. 

It seems like the bot transfers the duplicates it caught the latest.

I would prefer if the bot would transfer the weakest pokemon. Probably judging by CP and/or IV.

**Comment by beremp** [comment]
If this is how the bot works please let me know so I can close this issue

**Comment by wickedcody123456** [comment]
in the config

**Comment by beremp** [comment]
i used transferweakpokemon but that transferred all the low cp/iv pokemon. 

what i would like it to do is keep the stroger pokemon

Example: I already have a 25CP Pidgey and catch a 150CP Pidgey, then I would like to bot to keep the 150CP Pidgey and transfer the 25CP one.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
