### ISSUE TITLE
dust farm and transfer config [Request/Help]

### ISSUE THREAD

**Issue by trustedgamer** [NECROBOTIO/NecroBot#4221]
My config: http://pastebin.com/17Jd0XVX
Bot version: Latest v0.8.1
Problem: Sometimes bot catch some pokemon Paras, Magicarp etc. but sometimes transfer sometimes not.

I ask you for a help. To farm pokemons for dust, then transfer and only keep highest CP.

Thank you.

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
