### ISSUE TITLE
configuration  auth.json for lg g4 h815

### ISSUE THREAD

**Issue by coolconnor** [NECROBOTIO/NecroBot#4223]
how can i set the auth.json to emulate a lg g4?

  "AuthType": "google",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "lg-optimus-g",
  "DeviceId": "c2656e07820018a8",
  "AndroidBoardName": "geehrc",
  "AndroidBootloader": "MAKOZ10f",
  "DeviceBrand": "LGE",
  "DeviceModel": "LG-LS970",
  "DeviceModelIdentifier": "cm_ls970",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "LGE",
  "HardwareModel": "LG-LS970",
  "FirmwareBrand": "cm_ls970",
  "FirmwareTags": "test-keys",
  "FirmwareType": "userdebug",
  "FirmwareFingerprint": "google/occam/mako:4.2.2/JDQ39/573038:user/release-keys"

thanks.

**Comment by bulubebek** [comment]
check it [here](http://specdevice.com/showspec.php?id=e3e6-5def-ffff-ffff9717a7fa#tabs-6).
btw, this is not issue. please join discord chat to get help.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
