### ISSUE TITLE
How to hatch eggs faster

### ISSUE THREAD

**Issue by canuckle604** [NECROBOTIO/NecroBot#4225]
how do i set the bot so that i hatch my eggs faster please help me!!

**Comment by Simpuhl** [comment]
Increase your walking speed.

Keep it below 12 miles an hour.

Also don't stop to catch pokemon

**Comment by canuckle604** [comment]
isnt walking speed is KM/hr tho?

**Comment by Simpuhl** [comment]
http://lmgtfy.com/?q=12+mph+to+km

**Comment by canuckle604** [comment]
thanks
