### ISSUE TITLE
the bot just not working

### ISSUE THREAD

**Issue by wickedcody123456** [NECROBOTIO/NecroBot#4226]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior

to work

### Actual Behavior

printing random  stuff on the cmd prompt

### Your config.json
```
https://www.mediafire.com/folder/6kmq6knqhlc0d/the_bot_files
```

### Steps to Reproduce

am not sure it just started to happen logs files dump files are in here
https://www.mediafire.com/folder/6kmq6knqhlc0d/the_bot_files

### Other Information
Version: the latest
Windows Version: windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):everything

**Comment by Rick058** [comment]
Before I'll look into your config, pleas remove auth.json from the mediafire link... it has your login details in there. Anyone can access your account now, change your password right away please. www.pokemon.com

**Comment by Rick058** [comment]
Your mistake is on line 446 - 449.
Replace:
`        "Latitude": 51.5025343,`
`        "Longitude": -0.2055027`
`      },`
`       "lattude":122.405446141333`
`       "Longitude"40.7325313448872`
`      }`

With:
`        "Latitude": 51.5025343,`
`        "Longitude": -0.2055027`
`      },`
`	  {`
`       "Latitude": 40.7325313448872,`
`       "Longitude": 122.405446141333`
`      }`

The location is: Dashiqiao, Yingkou, Liaoning, China. Correct?
Please try again, if you have any other issues. Let me know.

**Comment by Simpuhl** [comment]
Lol,

Why would you upload your auth file dude... make sure you change your password now

**Comment by palooga** [comment]
fail boat

**Comment by wickedcody123456** [comment]
crap a give you guys an auth.json

**Comment by wickedcody123456** [comment]
it not high level anywhy

**Comment by wickedcody123456** [comment]
change my password thanks for helping

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
