### ISSUE TITLE
What's the fastest/safest way to change continents?

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#4227]
the title says it all.

**Comment by user8285** [comment]
Airplane

**Comment by DariusFoxy** [comment]
too slow. next.

**Comment by user8285** [comment]
jet?

**Comment by jawad90** [comment]
fake gps ?

**Comment by Ezoteric** [comment]
set coors in, downtown london, hong kong, syndey and central park NY <- i would use central park also as main spot to level up.
and wait like 1-2 days to be save.

**Comment by DariusFoxy** [comment]
ok, so that's what i've been doing. setting coors and then waiting overnight, but i wasn't sure if there was a better way. a few times i've been soft banned, but then it seems like touching a pokestop or waiting 1-2 minutes and it's gone. I was in tokyo last night and australia this morning for the Dratini Lakes.

**Comment by Ezoteric** [comment]
well you can use skiplagged to see where the region pokemon is in those towns, set te coor and catch it. BUT i cant catch all 3 within 15min no :P they will flee 100% so wait a realistic time to be save, yes you can do it after a hour but then yeah... easy to make a bot to spot those gains and bam massive perm bans :P

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
