### ISSUE TITLE
bot evolving before reaching "UseLuckyEggsMinPokemonAmount"

### ISSUE THREAD

**Issue by jawad90** [NECROBOTIO/NecroBot#4229]
the bot just keeps evolving and does not wait for "UseLuckyEggsMinPokemonAmount" to reach its amount after activating "EvolveAllPokemonWithEnoughCandy" and if this last one is set to false the bot does not evolve even after the "UseLuckyEggsMinPokemonAmount" is reached hpw im i supposed to make this work properly ? (plz dont tell me to go to discord because they dont know the answers)

**Comment by ChemiHatake** [comment]
oh wow another problem caused by "correcting" my code

**Comment by palooga** [comment]
What do you mean Chemi

**Comment by ChemiHatake** [comment]
@palooga you can read my "rant" in the referenced issue,

**Comment by jawad90** [comment]
@ChemiHatake i feel you bro lol ...

**Comment by ChemiHatake** [comment]
@jawad90 rip indeed

**Comment by palooga** [comment]
@ChemiHatake It is hard to work with monkeys hitting nails in with a wrench.

**Comment by ChemiHatake** [comment]
@palooga this is a weird way to describe the situation, but exactly.
