### ISSUE TITLE
"PokemonToIgnore" didn't work

### ISSUE THREAD

**Issue by Firedor** [NECROBOTIO/NecroBot#4230]
Since I use necrobot, the pokemon listed on PokemonToIgnore didn't work.

For example, now i'm sniping, in the PokemonToIgnore list there are weedles, rattatas, pidgeys... etc.

But in the log I can see the bot catches many of them. Why?

"PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],

**Comment by ChemiHatake** [comment]
check if UsePokemonToIgnoreFilter is set to true

**Comment by palooga** [comment]
"UsePokemonToNotCatchFilter": false,

**Comment by Firedor** [comment]
I try both, catch filter true and false, and I still get those rattatas.
![cvcv](https://cloud.githubusercontent.com/assets/20915853/17539572/788f046c-5eaf-11e6-9b88-75844f0cb158.PNG)

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
