### ISSUE TITLE
Error happened after update the latest version

### ISSUE THREAD

**Issue by doniface** [NECROBOTIO/NecroBot#4231]
### Expected Behavior
Normal start

### Actual Behavior
Error msg at first two line here:
[09:54:52] (提醒) System.UnauthorizedAccessException: 拒絕存取路徑 'F:\necrobot0.75\NecroBot.exe.old'。
   於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   於 System.IO.File.InternalDelete(String path, Boolean checkHost)
   於 System.IO.File.Delete(String path)
   於 PoGo.NecroBot.Logic.State.VersionCheckState.<CleanupOldFiles>d__5.MoveNext() 於 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Ver
sionCheckState.cs: 行 148
[09:54:52] (提醒) System.UnauthorizedAccessException: 拒絕存取路徑 'F:\necrobot0.75\Resources\encrypt.dll.old'。
   於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   於 System.IO.File.InternalDelete(String path, Boolean checkHost)
   於 System.IO.File.Delete(String path)
   於 PoGo.NecroBot.Logic.State.VersionCheckState.<CleanupOldFiles>d__5.MoveNext() 於 C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Ver
sionCheckState.cs: 行 148

It seems some path about the user 'ciamo' still set in the program, please check it out
(my laptop did not have the account: ciamo)

**Comment by qwert95** [comment]
Is 0.8.5 starting properly?

**Comment by doniface** [comment]
Yap it just fixed after next version
