### ISSUE TITLE
[Feature Request] Configurable Run Time with Auto Exit

### ISSUE THREAD

**Issue by RunBoris** [NECROBOTIO/NecroBot#4232]
To limit appearing like a bot it would be fantastic to have a config line for how long to run the bot, with a random variance so that 6 hours, for example, could end the run anywhere between 5:46 and 6:14 (but never exactly 6 hour 0 minutes).

Along with this feature it would be nice to have a Pokemon/stat dump on clean exit. Tough to do that on a forced/crashed exit, but seems doable on a timed and controllable exit.

**Comment by palooga** [comment]
Exit bot when you don't want it to run?

**Comment by RunBoris** [comment]
Instead of letting it run constantly overnight set it to run for a few hours. I'm sure Niantic is going to catch on to accounts running 8-10 hours over night. Timed exit would limit detection in that aspect.

**Comment by CameForTheCrown** [comment]
can i run more than one bot on the same acount?

**Comment by RunBoris** [comment]
That doesn't seem like a safe idea, nor applicable to this request.

**Comment by JustSomeWeirdGuy** [comment]
You can just use batch files. Just rename to .bat or you can edit to change time.


[Kill 1 Hour.txt](https://github.com/NECROBOTIO/NecroBot/files/410259/Kill.1.Hour.txt)

**Comment by schwartzadev** [comment]
solved by @JustSomeWeirdGuy
