### ISSUE TITLE
Trasnfer Pokemon Problem! bug

### ISSUE THREAD

**Issue by ascer0** [NECROBOTIO/NecroBot#4233]
i have a problem transfer pokemons ... in general works great..... 

but after past a time run the bot result in my pokemon storage are full .. ok now check in the app and i can see and have many duplicated pokemons .... but only occur whith specified pokemon liked blastoise..
slowbro .. porygon... and dont remember others.... (transfer manual and run the bot again)  now i delete the part to not tranfer list but the problem persist ... in the my last try .. active .. tranfer weak pokemon and the result in the lost my pokemon whith low level but again dont transfer this pokemon ..duplicated .. please help me... only ... pretend have each one pokemon .. regards

**Comment by palooga** [comment]
It is your config

**Comment by ascer0** [comment]
ok in general my config its the original only change this parts .. 

delete this

"PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

and change this value to 1
"KeepMinDuplicatePokemon": 0,

in the ducplicate i try to keep the value in 0 but result in transfer all pokemon

**Comment by cjmoore27** [comment]
I have the same issue with slowbro, porygon, and mrmime... so annoying to see all those guys stacking up!

**Comment by fartb0i** [comment]
It is not the config but there is something wrong in the bot. I have stacks of vaporeans and chanseys and etc. when I have set it to 2 duplicates.

**Comment by cjmoore27** [comment]
PS... #cheatersproblems

**Comment by ascer0** [comment]
yes fatb0i the same problem here but only occur with the mentioned pokemons 
 now i make a list to check problem with the bot
venusaur
blastoise
nidoqueen
nidoking
arcanine
poliwrath
rapitash
slowbro
farfetchd
exeggutor
hitmonchan
lickitung
rhydon
chansey
kangaskhan
mrmine
jynx
electabuzz
magmar
gyarados
vaporeon
flareon
porygon
kabutops
aerodactyl
snorlax
dratini 

the rest of pokemon transfer normal and keep accord iv and cp .. please check ..

**Comment by fartb0i** [comment]
I changed the keepminoperator = and for all of them in the transfer filter for all these Pokemons. It looks like it has solved the problem for me.

**Comment by ascer0** [comment]
Thanks bro .. works .. .. regards!
