### ISSUE TITLE
Bot is using ultra balls when I won't./Trash max pots.

### ISSUE THREAD

**Issue by Faux11** [NECROBOTIO/NecroBot#4235]
Good night everyone!
My problem is that i config my bot to not use ultra or great balls while farming, and the bot trash the pots when i have something write in.

[config.txt.txt](https://github.com/NECROBOTIO/NecroBot/files/410195/config.txt.txt)

i uploaded my config, but i have this writed in the cfg: 
"UseGreatBallAboveCp": 1400,
  "UseUltraBallAboveCp": 1900,
  "UseMasterBallAboveCp": 2000,
  "UseGreatBallAboveIv": 90.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.05,
  "UseUltraBallBelowCatchProbability": 0.05,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,

Potions/:
"ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemPokeBall",
      "Value": 30
    },
    {
      "Key": "itemGreatBall",
      "Value": 50
    },
    {
      "Key": "itemUltraBall",
      "Value": 100
    },
    {
      "Key": "itemMasterBall",
      "Value": 100
    },
    {
      "Key": "itemHyperPotion",
      "Value": 30
    },
    {
      "Key": "itemMaxPotion",
      "Value": 75
    },

Thanks for reading, hope you can help me! Have a good day =)

**Comment by palooga** [comment]
```
 "TotalAmountOfPokeballsToKeep": 200,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1400,
  "UseUltraBallAboveCp": 1900,
  "UseMasterBallAboveCp": 2000,
  "UseGreatBallAboveIv": 90.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.05,
  "UseUltraBallBelowCatchProbability": 0.05,
  "UseMasterBallBelowCatchProbability": 0.05,
```
It definitely still uses ultra balls and great balls because the probability is not ZERO. Goodjob. Genius.

ALSO

You have it set to keep ZERO potions. That is why it throws them away. Genius.

**Comment by Faux11** [comment]
lol damn i'm stupid lol thanks man

**Comment by Faux11** [comment]
you're a beast btw xd

**Comment by wickedcody123456** [comment]
"UseGreatBallAboveCp": 1400,
"UseUltraBallAboveCp": 1900,
"UseMasterBallAboveCp": 2000,
"UseGreatBallAboveIv": 0,
"UseUltraBallAboveIv": 0,
"UseGreatBallBelowCatchProbability": 0,
"UseUltraBallBelowCatchProbability": 0.
"UseMasterBallBelowCatchProbability": 0.05,
"EnableHumanizedThrows": false,

**Comment by Faux11** [comment]
well, i have that : "UseGreatBallAboveCp": 1400,
"UseUltraBallAboveCp": 1900,
"UseMasterBallAboveCp": 2000,
"UseGreatBallAboveIv": 0,
"UseUltraBallAboveIv": 0,
"UseGreatBallBelowCatchProbability": 0,
"UseUltraBallBelowCatchProbability": 0.
"UseMasterBallBelowCatchProbability": 0.05,
"EnableHumanizedThrows": false, 
stills using great/ultra :/

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
