### ISSUE TITLE
Bot generalizing items.

### ISSUE THREAD

**Issue by d1sconn3ct** [NECROBOTIO/NecroBot#4238]
Is it possible to make the bot not to generalize the items ingame?
For instance, the amount of pokeballs, greatballs and ultraballs in my inventory is always switching around.
I may have 180 pokeballs, 20 greatballs and 0 ultra balls at one time and in a couple of hours I may have 0 pokeballs, 0 greatballs and 200 ultraballs. Same goes for potions.

My point being, can this:
  _"TotalAmountOfPokeballsToKeep": **x**,
  "TotalAmountOfPotionsToKeep": **x**,
  "TotalAmountOfRevivesToKeep": **x**,
  "TotalAmountOfBerriesToKeep": **x**,_

Become something like this?:
  _"TotalAmountOfPokeballsToKeep": **x**,
  "TotalAmountOfGreatballsToKeep": **x**,
  "TotalAmountOfUltraballsToKeep: **x**,
  "TotalAmountOfPotionsToKeep": **x**,
  "TotalAmountOfSuperpotionsToKeep": **x**,
  "TotalAmountOfHyperpotionsToKeep": **x**,
  "TotalAmountOfMaxpotionsToKeep": **x**,
  "TotalAmountOfRevivesToKeep": **x**,
  "TotalAmountOfBerriesToKeep": **x**,_

**Comment by palooga** [comment]
The bot always keeps EVERY ultra and great ball. It just uses them when catching. That is why there is no filter. The TOKEEP filter will still use them if it needs it to catch a pokemon. If you want to just collect balls then turn off catching pokemon.

**Comment by d1sconn3ct** [comment]
Yes, the bot does keep them. But, in my case, maybe is just a coincidence, it just used all the great and ultra balls and filled up on pokeballs from pokestops and before it can get more from pokestops it has to spend some of them. My idea was just so the inventory wont eventually get full of pokeballs from catching high IV/CP pokemons, so it leaves room for great and ultraballs from pokestops.

**Comment by d1sconn3ct** [comment]
On a side note, I might just tweak it to use great and ultra balls on even higher IV/CP pokemons. That could solve my issue.

**Comment by deduijk** [comment]
Quote from https://github.com/NECROBOTIO/NecroBot/wiki/Config:
> 

ItemRecycleFilter (List)

List of max values mapped to each non-Pokeball, non-potion, and non-revive Pokemon Go item. During the recycling stage, any item that is over the max count is recycled to meet the value. This is to prevent full inventories.
TotalAmountOfPokebalsToKeep (Value)

Total amount of pokeball-type items to keep. Necrobot will try to intelligently prioritize higher pokeballs when farming Pokestops.
TotalAmountOfPotionsToKeep (Value)

Total amount of potion-type items to keep. Necrobot will try to intelligently prioritize higher potions when farming Pokestops.
TotalAmountOfRevivesToKeep (Value)

Total amount of revive-type items to keep. Necrobot will try to intelligently prioritize higher revives when farming Pokestops.

**Comment by nfettinger** [comment]
If you read the changelog, we went from your proposed method to the new one, because it is ALWAYS better to keep the better balls.

If you need help configuring Necrobot to use specific balls in certain scenarios, please use Discord chat.
