### ISSUE TITLE
Using more then 1 bot is causing softbans.. after update

### ISSUE THREAD

**Issue by rlmrso** [NECROBOTIO/NecroBot#4241]
With version 0.7.0 i could bot multiple (6) accounts... With the new update i can not. I tried changing device number in auth.json and locations in config.json. Also tried clean installs. NO my speeds are not to high i set it to 30km p/h Maxdist: 1000km (everything standard except locations). 

Hope You can fix this :D , Yall done a great job so far !

**Comment by padmanek** [comment]
It's not a bot issue. Niantic is blocking connections from the same IP.

**Comment by rlmrso** [comment]
So why i still can bot multiple accounts with version 0.7.0 at the same time?

**Comment by padmanek** [comment]
@rlmrso How many is multiple? Everyone on discord says you can run MAX  2 bots per IP now.

**Comment by bastacs** [comment]
max bots 0.81 = 2 ID
max walking = 50km 
is work for me :)

**Comment by Rick058** [comment]
Max bots per IP = 2
Rest doesn't seem to matter, config-wise.

**Comment by rlmrso** [comment]
Thanks, i hope they can change so we can have more bots at the same time running !

**Comment by padmanek** [comment]
@rlmrso they? It's Niantic's anti cheating feature. Don't expect them to disable that. Issue solved. Please close.

**Comment by Rick058** [comment]
Yesterday I ran 3 at a time, a week ago 20 at a time. They know how to cut down the amount of bots.
They want to get rid of us, not help us lol :^)

**Comment by rlmrso** [comment]
With they i dont mean niantic i mean bot developers.

**Comment by padmanek** [comment]
@rlmrso it's not the bot developers limiting bots to 2 at the time. It's Niantic! It can't be fixed! Jeez ppl....

**Comment by rlmrso** [comment]
... @padmanek The why i hear people saying they are still botting 3 acc. at the same time with the same bot like necro 0.7.0 ....

**Comment by padmanek** [comment]
@rlmrso servers are detecting too many connections from the same IP so they throttle them ( soft ban them) there's nothing that can be done about this.

**Comment by rlmrso** [comment]
How you know /

**Comment by padmanek** [comment]
@rlmrso you can run 3  on 0.8.1 too. Just set delay between player actions higher. The value is in milliseconds. That will still result in many soft bans. Those guys on 0.7.0 get it too. I can assure you of that.

**Comment by bastacs** [comment]
My Log 
4 ID Necrobot = AUTo soft banned
3 ID Necrobot = Auto Soft Banned
2 ID Necrobot = WORK

**Comment by rlmrso** [comment]
@bastacs i can only run 2 ... i tried 3 then it will give me errors with no pokestops

**Comment by bastacs** [comment]
same with me :) just run 2 id

**Comment by padmanek** [comment]
@rnlrso how I know? Discord, r/pokemongobotting, r/pokemongodev and also maybe because I'm following the commits on GitHub and contributing myself..

**Comment by rlmrso** [comment]
@padmanek i think it also depends on how stable niantic servers are... when its becoming unstable they will throttle more.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
