### ISSUE TITLE
How to setup Proxy

### ISSUE THREAD

**Issue by ValorRed** [NECROBOTIO/NecroBot#4243]
We have a proxy setup for going out to Internet. How can I setup the proxy for running NecroBot?

Thanks

**Comment by bulubebek** [comment]
Duplicate #3235
This is not an issue. Please search before you ask.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
