### ISSUE TITLE
[FEATURE] Rename Pokemon for given IV

### ISSUE THREAD

**Issue by matheuskessler** [NECROBOTIO/NecroBot#4245]
As the title suggests, automatically rename to IV

**Comment by perryhuynh** [comment]
This is already a feature with setting ` "RenamePokemon":` to `true` in the config

**Comment by deduijk** [comment]
More specific 2 settings:

`
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
`

Currently this renames pokemon to IV_pokemonname, provided it is higher then 95 iv. 
When you set the second option to false i presume it will rename all of them.

NOTE: when you evolve a renamed pokemon pokemon go will not rename that pokemon into the new evolution name. it will keep the renamed name, something to consider.

I don't know if transfer of the bot is based on name or type, but im sure someone else can answer that question.

**Comment by schwartzadev** [comment]
solved

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
