### ISSUE TITLE
Pokemon wont show up on phone

### ISSUE THREAD

**Issue by Grimmylifefreak** [NECROBOTIO/NecroBot#4246]
So when i was using you system on pokemon go it worked fine and nothing was happening then out of no where some of the pokemon i was catching was not showing up. I restarted the game but i still had pokemon not there that i caught. Whats wrong with it. So i have 85 pokemon out of 250 and i counted 26 down and 3 across but the last row only had 1 pokemon so that 76 pokemon i have 9 pokemon that do not exist at all where did they go?

**Comment by try2hack** [comment]
it transfered you Pokemon.


"KeepMinDuplicatePokemon": 1,
in config.json

**Comment by schwartzadev** [comment]
solved

This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
