### ISSUE TITLE
Transfer all pokemon

### ISSUE THREAD

**Issue by H4D3S** [NECROBOTIO/NecroBot#4247]
Hello, with the configuration default , they are transferred all pokemon and i seen an error on the count of pokemon caught up 
Release v0.8.1

![screenshot_20160809-223121](https://cloud.githubusercontent.com/assets/848354/17540281/dc6b4676-5e82-11e6-903d-6e02a957a505.png)

**Comment by try2hack** [comment]
"KeepMinDuplicatePokemon": 1,
in conig.json

**Comment by lFeeeeelipe** [comment]
This is because the eggs, friend.

**Comment by lFeeeeelipe** [comment]
You have 5 Pokemon and 9 eggs.
So 14

**Comment by H4D3S** [comment]
:o !!!! hehehe thx  :D

**Comment by xnikolai** [comment]
I think the default should be changed to 1 in the next release

**Comment by Dokha** [comment]
Ya its sama but pokemon perfect more than 90% still there even cp 148 (magicrab)
N poke cp more 1k still save
Move still so fast some time got soft banned
N make more time to unban
Please fix it Sensei...

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
This looks like an issue in the Necrobot Visualizer repository, not here.
