### ISSUE TITLE
Pokemon Keep Fleeing but Pokestops Works

### ISSUE THREAD

**Issue by makhao** [NECROBOTIO/NecroBot#4248]
Hi Guys,

After the latest update I am experiencing some kind of softban where I am not able to catch any pokemons. All of them escape in the encounter...while visiting pokestops I do still get my items but at times there is softban. Was wondering what is happening? I checked my JSON file and is valid..

**Comment by kurozani** [comment]
you level up, the pokemon is harder to caught? set the pokeball/razzberry

**Comment by makhao** [comment]
Ok I am not good in editing the config file so what command should I use? Or I should just tweak the requirement to use greatball to a lower CP?

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
