### ISSUE TITLE
cant teleport / jump gps

### ISSUE THREAD

**Issue by looooozeeeeer** [NECROBOTIO/NecroBot#4249]
i recently tried to jump / teleport from yayogi park, japan to austin by editing the lattitude and longitude lines in config and deleting the last cord file, but bot says no nearby pokestop, im pretty sure there are plenty in my new coord cz i had tried jumping with nox (without moving so it wont cause a softban)

when i return my coord to yayogi, bot doing normal, farm pokestop and sniping without problem. i tried use quickspin but it also says there r no pokestop nearby in my new coord (austin).

what did i do wrong?

using necrobot v0.8.1
using quickspin v1.3

**Comment by bulubebek** [comment]
do not jump/teleport in short time. stop your bot for a while, and retry it after 10-15 mins.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
