### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by jazzu20** [NECROBOTIO/NecroBot#4252]
this is my set up

"KeepMinCp": 500,
"KeepMinIvPercentage": 35.0,
"KeepMinLvl": 15,

"KeepMinIvPercentage" - worksfine
but the bot still keep lower than 500 cp..  
and lower than lvl 15

**Comment by Zaryabb** [comment]
Theres another setting which keeps all that are above IV 90 thats why. All those are 90+ IV thats why theyre being kept. Change keepiv to 100 or 101 to delete all except the ones u set there

**Comment by avatarium** [comment]
change to
"KeepMinOperator": "and",

**Comment by jazzu20** [comment]
thanks avatarium it works :D kudos!

**Comment by brightjoyy** [comment]
this is the way to keep best Cp and best IV for each one right?

**Comment by recon88** [comment]
Please visit our Discor for configuration help: https://discord.gg/VXKxNFr
