### ISSUE TITLE
Skipping almost every pokemon.. 

### ISSUE THREAD

**Issue by binarydaddy1234** [NECROBOTIO/NecroBot#4253]
Its literally going to poke stops and saying skipped *asdada* and its super annoying im getting no exp. Please fix.

Thanks.

**Comment by cavemanGit** [comment]
Make sure you have "UsePokemonSniperFilterOnly": false,

**Comment by Rick058** [comment]
Example of the error, screenshot/log(s)?
Include your config.json as well please, makes it a lot easier for us.

**Comment by binarydaddy1234** [comment]
Whoops was just my config sorry fixed it
