### ISSUE TITLE
How can i keep the highest CP and Highest IV.

### ISSUE THREAD

**Issue by brightjoyy** [NECROBOTIO/NecroBot#4254]
How can i change config by let them keep the highest CP and Highest IV for each pokemon and transfer can transfer all the stat that below.

**Comment by jazzu20** [comment]
set your desired cp and iv

e.g
  "KeepMinCp": 1000,
  "KeepMinIvPercentage": 90.0,
  "KeepMinOperator": "and",

**Comment by brightjoyy** [comment]
i will try thx jazzu20

**Comment by brightjoyy** [comment]
this can use from level 1 to any level right ?

**Comment by jazzu20** [comment]
yes. you can set the level too if you want

e.g 
"KeepMinLvl": 15,

**Comment by brightjoyy** [comment]
no i mean the character level

**Comment by jazzu20** [comment]
my bad... :D 

but yest that corrects

**Comment by recon88** [comment]
Please visit our Discor for configuration help: https://discord.gg/VXKxNFr
