### ISSUE TITLE
[Request] Can we get TransferWeakPokemon Defined in wiki config?

### ISSUE THREAD

**Issue by Reborn1990** [NECROBOTIO/NecroBot#4260]
Just wanted to say huge shout out to the DEVs for making this great!

Is there any way you could help me understand what all defines this Weak Pokemon feature. I turned it on and it began to transfer essentially all of my pokemon. Can we adjust the parameters for weak pokemon? 

Thank You!!!

**Comment by nfettinger** [comment]
Done
