### ISSUE TITLE
Fighting With Botted Accounts In Gyms

### ISSUE THREAD

**Issue by goobs93123** [NECROBOTIO/NecroBot#4261]
Has anyone actually tried playing a botted account in a gym battle?

For instance, i may have made an account yesterday and its currently level 27 and when i engage in a gym battle, it displays "error."

anyone else with this issue? xD

**Comment by goobs93123** [comment]
does it have anything to do with moving coordinates to quickly after botting? do i need to wait some 3 hour interval?

**Comment by Markersx** [comment]
set your location in the bot to the location of the gym wait for the bot to unban you then you can fight in the gym

**Comment by goobs93123** [comment]
TYVM
