### ISSUE TITLE
How can I set: "Moves" > "IV"?

### ISSUE THREAD

**Issue by Fenixxia** [NECROBOTIO/NecroBot#4262]
How can I set that the bot retained a pokemon with the desired movements in the first place. And then watching IV? Now the bot gives priority to IV. If there is a pokemon with great IV, but his movements are not qualified, he still would choose that pokemon.

**I tried different combinations, turned to the helpers. But the result is always the same. The bot gives priority to IV. I have what would have been two conditions simultaneously:
1) match the specified movement
2) if item 1 is executed, then choose the pokemon with the highest IV
3) if executed, paragraph 1 and 2, then select the pokemon with the highest LV**

 "PokemonsTransferFilter": {
    "Aerodactyl": {
      "KeepMinCp": 1,
      "KeepMinLvl": 30,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        "steelWingFast"
      ],
      "KeepMinOperator": "and",
      "MovesOperator": "and"

[config.txt](https://github.com/NECROBOTIO/NecroBot/files/410329/config.txt)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by nfettinger** [comment]
This is a duplicate issue for adding movesets to the config.

**Comment by Fenixxia** [comment]
I wrote above, I turned to the Helpers in the channel Deep. The conversation was, but the result is not obtained.

At the moment, the function does not work as should work.
