### ISSUE TITLE
Necrobot find rare Pokemon (WITH CONFIGURATION)

### ISSUE THREAD

**Issue by XxlPacolxX** [NECROBOTIO/NecroBot#4265]
A guy told me I can have rare Pokemon as snorlax , charizard just changing settings , which are not agradeceria configuration that your answers : D

**Comment by kaiofurius** [comment]
newfag google traduz

**Comment by AbyssDeep** [comment]
Hola, por lo que veo hablas español y utilizaste el google traductor, pero bueno, Para obtener pokemones raros tienes que hacer Snipping activando algunas cosas en la configuracion y descargando otro programa de Github que se llama "PogoLocationFeeder", si necesitas mas informacion escribeme

**Comment by XxlPacolxX** [comment]
yes i speak spanish :,v im sorry

its in spanish, 

como activo esas cosas y despues de descargarlo que hago

**Comment by AbyssDeep** [comment]
Necesitas descargar la ultima version del NecroBot que es la 0.8.2 y buscar en config.json estas configuraciones e igualarlas:
  "CatchPokemon": true,
  "UseSnipeLocationServer": true,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "SnipeAtPokestops": true,

Guarda la nueva configuracion ...............

Para el "PogoLocationFeeder" tambien necesitas cambiar las configuraciones que deben quedar iguales a estas: 
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UseRareSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 5,
  "ShowLimit": 40
}
Guarda la nueva configuracion............


Ahora solo necesitas abrir el ejecutable del PogoLocationFeeder y mantenerlo abierto, y por ultimo abrir el bot de NecroBot que es el que se encargara de capturar los pokemones..

**Comment by XxlPacolxX** [comment]
thanks my friend :) :+1:
