### ISSUE TITLE
PokemonsToIgnore gets deleted every time I launch Necrobot

### ISSUE THREAD

**Issue by CreativiTimothy** [NECROBOTIO/NecroBot#4266]
### Expected Behavior

Not catch Pokemon

### Actual Behavior
Deletes code

### Your config.json
```
  "UsePokemonToNotCatchFilter": true,
  "PokemonsToIgnore": [
	"zubat",
	"tentacool"
  ],
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by recon88** [comment]
Can you copy your full config to http://pastebin.com/ please?

**Comment by CreativiTimothy** [comment]
I'm very sorry. I just realized "PokemonToIgnore" had already been in the config, and I typed an extra one. It was confusing because UsePokemonNotToCatch seemed like something different. This issue can be closed
