### ISSUE TITLE
[Improvement] KeepMaxDuplicatePokemons

### ISSUE THREAD

**Issue by Fazy5** [NECROBOTIO/NecroBot#4272]
Expected Behavior:
limits the amount of each Pokemons you keep as per user other transfer filters.

Actual Behavior:
currently keepminduplicatepokemons only work in a sense to keep only 1 of each pokemons if you set it to 1, and No pokemons if you set it to 0.. But if i set it to for example 3, it will keep 3 minimum but If multiple other pokemon match my requirements they will all be kept. So i often end up with 10+ of pokemons that fullfill my requirements even though i set keep min to 3. It should keep 3 min, and Then start comparing cp with all those that arrive after and then transfer the extras (if prioritizeivovercp is set to false for example)

Your config.json:
prioritizeivovercp is false
keeppokemonsthatcanevolve is false
keepmincp is 5000
keepminivpercentage 100.0
keepminoperator is or
usekeepminlvl is false
keepminduplicatepokemon is 3
transferweakpokemon is false
transferduplicatepokemon is true
transferduplicatepokemononcapture is true

Steps to Reproduce:
Catch 3 pokemons that fulllfill your requirements, and after that catch more than fullfill your requirements and all will be kept. If KeepMaxDuplicatePokemon is inplemented, the bot will then start comparing pokemons after 3 are caught and keep the pokemon with max cp or 100% iv and transfer the rest.

Other Information:
Version: 0.8.1
Windows Version: Windows 10

What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
Transfer
Inventory

A MUCH NEEDED ENHANCEMENT/IMPROVEMENT !

**Comment by TemhAAhmeT** [comment]
I have same problem. I woke up and saw inventory was full and as you said so many dublicates doesnt match with my requirements.

**Comment by Fazy5** [comment]
Figured how keepminduplicatepokemon works... Sorry for this.
