### ISSUE TITLE
How can I get my device info? 

### ISSUE THREAD

**Issue by exclus** [NECROBOTIO/NecroBot#4276]
How can I get my device info?
I can not find for example on how can auth.json looks when is set on an iphone. I want to add my device information.
I have an iphone 6.

Sample of what I am expected:
"DeviceId": "689404f8b92fd71f",
  "AndroidBoardName": "___________",
  "AndroidBootloader": "",
  "DeviceBrand": "______", (iphone or Apple?)
  "DeviceModel": "______",
  "DeviceModelIdentifier": "________",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "______", (Apple?)
  "HardwareModel": "_____",
  "FirmwareBrand": "________",
  "FirmwareTags": "______",
  "FirmwareType": "____",
  "FirmwareFingerprint": "________________________"

Thanks in Advance.

**Comment by zimmey** [comment]
Download this if you have an android.

https://play.google.com/store/apps/details?id=com.finalwire.aida64&hl=en

Between the system and android tabs, it has all the information.

**Comment by poutros** [comment]
He said he had an iphone, @zimmey.

**Comment by hanurya** [comment]
try this, :+1: 
https://github.com/NECROBOTIO/NecroBot/wiki/Device-Setup.
