### ISSUE TITLE
Can do catch the Pokemon Only

### ISSUE THREAD

**Issue by WinshyUS** [NECROBOTIO/NecroBot#4277]
Can do catch the Pokemon Only
Do not want Pokestops
Thank you

**Comment by poutros** [comment]
Are you stupid? How the hell do you think you can get pokeballs withoug pokestops?

**Comment by WinshyUS** [comment]
I have a lot of pokeballs
I just lack of Three Pokemon
Now I do not want XP
....OK....

**Comment by poutros** [comment]
You get xp when you catch pokemon, dummy. Snipe those pokemon if you want them. And change `UsePokemonSniperFilterOnly` to true so that it only tries to catch those pokemon. Plus, "lot of pokeballs" is not enough, I guarantee you.

**Comment by poutros** [comment]
@WinshyUS What is your mother tongue?
