### ISSUE TITLE
whats the logic behind TransferWeakPokemon?

### ISSUE THREAD

**Issue by Mikey9191** [NECROBOTIO/NecroBot#4282]
my bot stopped transferring pokemon for no reason today, kept saying pokemon inventory full but never transferred, yes even the 20cp pidgey and ratata etc. only when i enabled TransferWeakPokemon it started actually transferring. i am just wondering what the logic behind that option is

**Comment by flapjack412** [comment]
it's just there for if you were to save them and then lucky egg and evolve them all but I see what you mean it should be selected and open for unselect.

**Comment by theloser** [comment]
Go to the doscord channels and ask for help, thanks. This is not a development issue.
