### ISSUE TITLE
Config for EXP/Level Grind

### ISSUE THREAD

**Issue by ShaneAbara** [NECROBOTIO/NecroBot#4285]
Can I request someone's config for EXP/Level Grind?

config.json

Thank you

**Comment by theloser** [comment]
Go to the doscord channels and ask for help, thanks. This is not a development issue.

**Comment by ShaneAbara** [comment]
Any link for that @theloser  thank you! :)

**Comment by theloser** [comment]
It's the FIRST link on the bot's main page, for fuck's sake!
