### ISSUE TITLE
Error Using google account after configure auth.json V 0.8.1

### ISSUE THREAD

**Issue by pelari** [NECROBOTIO/NecroBot#4287]
Dear All,

i'm using v 0.8.1 and google account, after i configured the config.json for the first time 
then error happen : 
(https://cloud.githubusercontent.com/assets/20940942/17542810/2a0f7ce4-5ef6-11e6-8b8f-c864fabaa5b1.jpg))

why this happen ?

**Comment by pelari** [comment]
Sorry the file is auth.json not config.json

**Comment by recon88** [comment]
Please use the latest version. Also make sure there are " " around your mail and password in auth.json
