### ISSUE TITLE
SKIPLAGGED SNIPING BROKER

### ISSUE THREAD

**Issue by erikeleria** [NECROBOTIO/NecroBot#4288]
https://gyazo.com/29b85fc29e93f1f923456dab1c47457b

IT WAS WORKING BEFORE UPDATING TO 0.8.2

**Comment by argaa153** [comment]
same

**Comment by poutros** [comment]
I'm pretty sure skiplagged wasn't implemented before 0.8.2 so...

**Comment by nfettinger** [comment]
Duplicate issue.
