### ISSUE TITLE
[bug] transfer list ignores keepminlevel

### ISSUE THREAD

**Issue by wetshrimp** [NECROBOTIO/NecroBot#4289]
"Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 29,
      "UseKeepMinLvl": true,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

It is keeping several Level 21-28 flareons as well with 40-80IV. Should be transferring those.
However, all these flareons are over 1500 (which is the minCP) but it shouldn't be following minCP.

This must be some sort of bug.

**Comment by brightjoyy** [comment]
why my bot it transfer all of my pokemon

**Comment by PokemasterMike** [comment]
guys ask in discord, not here... this is not a message board
and provide a full dump of your config ! (on pastebin.com)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
