### ISSUE TITLE
[HELP] Bot Crashes and Not Working

### ISSUE THREAD

**Issue by Nilexis** [NECROBOTIO/NecroBot#4291]
My bot works fine for like 30 minutes, and then the bot crashes and when i restart it there's only black screen and the only way to get the bot working again is by reinstalling it. What should I do?

**Comment by Nilexis** [comment]
BTW that problam has been only since the last update. The previous one worked fine.

**Comment by KillerOffers** [comment]
Try changing a false to true in "FastSoftBanBypass": true,
This worked for me.

**Comment by nfettinger** [comment]
We need more information such as the error your seeing when it crashes.

**Comment by Nilexis** [comment]
I reinstalled and changed the "FastSoftBanBypass" to true, I will update if it worked.

**Comment by Wcidd** [comment]
"Your issue was not created with the template, therefor we cant collect sufficiant information to understand the issue properly. Please create a new issue with the correct template"
