### ISSUE TITLE
Feature Request - Simulate Transfer ( then Confirm) Before it Transfer...

### ISSUE THREAD

**Issue by masterpowers** [NECROBOTIO/NecroBot#4293]
We all Know Transfered Pokemon is Irreversable especially if we have a 100% IV with 3k CP
Then its Drained down by wrong config...

This Feature SHould only Run Like a Welcome Message....
It will simulate a Transfer , and SHow you List of Pokemon 
that will be transfer...
So if your Pokemon That is 100% IV is on the List or a high CP is on the List...
it wount Get Transfer Immediately....

Also An Option to Confirm Each Transfer might be usefull in some cases...
Until we have perfected the way transferring pokemon is ...

We can inhibit wrong transfer by this method...

I hope it can be added thanks

**Comment by theloser** [comment]
I don't want this confirmation feature.

Just use your brain a try doing a valid configuration. Test it with some dummy account. And if it transfers your best pokemon, rince and repeat -- you are botting anyway, so there will be another perfect catch in no time.

**Comment by nfettinger** [comment]
NecroBOT is a BOT, not a new interface for the game. If you would like more manual control, Dont transfer anything, and use the visualizer to manually do it yourself.
