### ISSUE TITLE
Error: System.NullReferenceException: Object reference is not set to an instance of an object.

### ISSUE THREAD

**Issue by Markersx** [NECROBOTIO/NecroBot#4294]
![](http://i.imgur.com/e1NSLSq.png)
I have validated both my configs.
Version: 0.8.2
Windows Version: 7 64-bit
Logs: http://pastebin.com/rpHCSeCc

**Comment by Markersx** [comment]
V0.8.3 Fixed it.

**Comment by Markersx** [comment]
I think its still worth looking into this.

**Comment by nfettinger** [comment]
Duplicate #3295
