### ISSUE TITLE
V.0.8.02

### ISSUE THREAD

**Issue by kurozani** [NECROBOTIO/NecroBot#4295]
pokezz error,why?

**Comment by poutros** [comment]
Because it is down. Close this issue.

**Comment by theloser** [comment]
pokezz.com is donw, disable it in your config.json.

**Comment by verecundus** [comment]
verecundus commented 27 seconds ago
Try using https://github.com/5andr0/PogoLocationFeeder/releases

with

"DelayBetweenPlayerActions": 5000,
"DelayBetweenPokemonCatch": 2000,

and

"UseSnipeLocationServer": true,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"GetSniperInfoFromPokezz": true,
"GetOnlyVerifiedSniperInfoFromPokezz": true,
"GetSniperInfoFromPokeSnipers": false,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": false,
"MinPokeballsToSnipe": 20,
"MinPokeballsWhileSnipe": 0,
"MinDelayBetweenSnipes": 5000,
"SnipingScanOffset": 0.003,
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": false,
"UseTransferIvForSnipe": true,
"SnipePokemonNotInPokedex": true,

**Comment by theloser** [comment]
> "GetOnlyVerifiedSniperInfoFromPokezz": true

This is bad if the site is DOWN.

**Comment by kurozani** [comment]
I did the configure

can anyone suggest me a good snipe location please?? :)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
