### ISSUE TITLE
Transfer for all POKEMON ?

### ISSUE THREAD

**Issue by brightjoyy** [NECROBOTIO/NecroBot#4297]
when i start bot for my brother and it transfer all of his pokemon it not transfer the lowest CP like before how can i fix this ?

**Comment by KillerOffers** [comment]
Did you upgrade?

**Comment by brightjoyy** [comment]
0.8.2 it still transfer for all

**Comment by brightjoyy** [comment]
Did you try it? i dont know that only me or not that be this problem

**Comment by theloser** [comment]
That's not a bot but an configuration problem on your end. Please go to the discord channels to get help, thanks.

**Comment by KauKauHat** [comment]
Yap i have the same problem, almost all pokemons was transferred as Bulbasaur 500 cp +, Charmander 500 cp +, Squirtle and sow on, but not the eevee with 200 cp+

**Comment by xadwilliam** [comment]
same problem here..

**Comment by ppa993** [comment]
"KeepMinDuplicatePokemon": 0,

Set it to 1. Why we don't have 1 as default? @GrimmGringo please!!!

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
