### ISSUE TITLE
IP / Proxy Error

### ISSUE THREAD

**Issue by qwertzuiopii** [NECROBOTIO/NecroBot#4298]
It worked on 7.x yesterday with the proxy configs
![unbenannt](https://cloud.githubusercontent.com/assets/20920788/17543232/5de8385c-5ecf-11e6-8de9-d871f1f9ad6f.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/20920788/17543258/97080ffe-5ecf-11e6-94d5-353ca3718932.PNG)

pressing any key exits the bot

**Comment by masterpowers** [comment]
im also experiencing this... we might be wrong, or something else is wrong

**Comment by theloser** [comment]
@qwertzuiopii This is a proxy server in your business network I suppose? Do you have to use proxy authentication?

**Comment by masterpowers** [comment]
i tried running it again it work on my end...

**Comment by qwertzuiopii** [comment]
ok i dont know what happened :O 
i deleted my release folder and unzipped the new version.
configured it with the same ip as given above.
i get the error again, but now the bot just "ignores" it because i dont have to press any key to continue (why is still unclear to me)
![unbenannt](https://cloud.githubusercontent.com/assets/20920788/17544237/48772bd4-5ed6-11e6-80c6-3490e5bdfd47.PNG)
still, if i press just any button now the bot exits

**Comment by Zyfax** [comment]
Looks like your proxy is local. 10.0.0.0, 192.168.0.0 and 172.16.0.0 is used for local networks.

**Comment by midascodebreaker** [comment]
im getting this
```
[15:28:43] (INFO) Logging in using Ptc
[15:28:48] (INFO) Your IP is: 122.52.26.234 / Proxy IP is: INVALID PROXY
[15:28:48] (INFO) Press any key to exit so you can fix your proxy settings...
[15:29:26] (INFO) Playing as user1121212
```
Can Anyone help me with this

**Comment by Zyfax** [comment]
You may test the proxy settings in IE just to verify that the proxy is working.
![ie-proxy-settings](https://cloud.githubusercontent.com/assets/13405548/17545943/f0d41554-5edf-11e6-99d9-6c635225c4f7.PNG)

**Comment by nfettinger** [comment]
NecroBOT is only displaying what it sees on your network. The rest is up to you.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
