### ISSUE TITLE
No usable PokeStops found in your area.

### ISSUE THREAD

**Issue by lucasfoong** [NECROBOTIO/NecroBot#4299]
Is anyone facing this issue ?? After i open my necrobot !! all i see is this .. No usable PokeStops found in your area. ...

**Comment by venduss** [comment]
Same here.

**Comment by the-mentor** [comment]
i wonder if they made an api change again

**Comment by theloser** [comment]
Possible softban. Not a development issue, please go to the discord chat to ask for help, thanks.

**Comment by emwedk** [comment]
u can only use 2 instances. and speed is important too - they say between 10km/h to 60km/h

**Comment by hanurya** [comment]
possible softban, it happened few times before.
try changing location (lat and long).
and set speed 18.

**Comment by theloser** [comment]
> try changing location (lat and long).

Do this often and you'll get softbanned.

**Comment by ggminn95** [comment]
got same problem, n when i open pokemon go on nox player, seem there is no pokestop -_-

**Comment by theloser** [comment]
If you are using the bot AND the nox player on the same account your asking for a softban! Just: don't.
