### ISSUE TITLE
Pokezz.com Connection Error 

### ISSUE THREAD

**Issue by Timangzkie** [NECROBOTIO/NecroBot#4301]
How to fix?

**Comment by theloser** [comment]
Go to pokezz.com and read: "This page (http://pokezz.com/) is currently offline." How should we fix this? Disable pokezz.com in your sniper settings in config.json

**Comment by Timangzkie** [comment]
What's the use of (http:pokezz.com) in config.json?

**Comment by theloser** [comment]
If you don't know, just set ut to false. You probably don't need it.

**Comment by verecundus** [comment]
verecundus commented 27 seconds ago
Try using https://github.com/5andr0/PogoLocationFeeder/releases

with

"DelayBetweenPlayerActions": 5000,
"DelayBetweenPokemonCatch": 2000,

and

"UseSnipeLocationServer": true,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"GetSniperInfoFromPokezz": true,
"GetOnlyVerifiedSniperInfoFromPokezz": true,
"GetSniperInfoFromPokeSnipers": false,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": false,
"MinPokeballsToSnipe": 20,
"MinPokeballsWhileSnipe": 0,
"MinDelayBetweenSnipes": 5000,
"SnipingScanOffset": 0.003,
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": false,
"UseTransferIvForSnipe": true,
"SnipePokemonNotInPokedex": true,

**Comment by theloser** [comment]
> "GetOnlyVerifiedSniperInfoFromPokezz": true

This is bad if the site is DOWN.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
