### ISSUE TITLE
Skipplagged.com error

### ISSUE THREAD

**Issue by palooga** [NECROBOTIO/NecroBot#4304]
http://i.imgur.com/leVn4gV.jpg
What is going on please help

Been doing this for 5 minutes straight

**Comment by verecundus** [comment]
Try using https://github.com/5andr0/PogoLocationFeeder/releases

with   

"DelayBetweenPlayerActions": 5000,
"DelayBetweenPokemonCatch": 2000,

and

  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": true,
  "SnipePokemonNotInPokedex": true,

**Comment by palooga** [comment]
I didn't see the line in the config thank you. I'm retarded.
