### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Recolance** [NECROBOTIO/NecroBot#4306]
This is the most of the stacktrace I could find. Just happened randomly, was not interacting with the window at all..

https://gyazo.com/41ab634baafa8c495c90c72320f1aa9a

**Comment by Recolance** [comment]
Managed to catch the entire stackstrace https://gyazo.com/9d58f9230028fff435cf195483eb8a19

**Comment by tomtom2770** [comment]
Same Problem. After some time it just crashs

**Comment by nfettinger** [comment]
Duplicate #3295
