### ISSUE TITLE
Updated PogoLocationFeeder and Necrobot always shows Error: Pokewatchers.com

### ISSUE THREAD

**Issue by ashleynohay** [NECROBOTIO/NecroBot#4307]

**Comment by ashleynohay** [comment]
@verecundus Im already using the updated pogolocationfeeder. Anyway I will try your config.

**Comment by verecundus** [comment]
![sniper](https://cloud.githubusercontent.com/assets/20942060/17543902/a99df544-5e88-11e6-805a-a30e19bed2d2.jpg)

**Comment by xThreeh** [comment]
0.8.3 its already

**Comment by ashleynohay** [comment]
@verecundus it works like a charm. thanks mate. :)

**Comment by verecundus** [comment]
@ashleynohay You bet, bothered me for a while before i put 2+2 together

**Comment by ashleynohay** [comment]
@verecundus theres a new update again of necrobot. did you already update yours?

**Comment by sharan16** [comment]
My thing just stops at a pokestop, doesnt continue unfortunately
