### ISSUE TITLE
 Version 0.8.2 now can open three accounts over it?

### ISSUE THREAD

**Issue by sarah1598** [NECROBOTIO/NecroBot#4308]
Version 0.8.2 now can open three accounts over it?

**Comment by bastacs** [comment]
u try first

**Comment by sarah1598** [comment]
OK~I wiil do it.
And report

**Comment by sarah1598** [comment]
Currently we drove for five, after a 20, and was not unban

**Comment by sarah1598** [comment]
This new version 0.8.2 has been fixed - may
Hard programmers thank you

**Comment by recon88** [comment]
Please use the latest version 0.8.5
