### ISSUE TITLE
necrobot 0.8.2 crash

### ISSUE THREAD

**Issue by Dr-Death** [NECROBOTIO/NecroBot#4311]
Hi, when running NecroBot.exe 0.8.2 it crash.
Logs:
> [10.12.14] <> Exception caught, writing LogBuffer.
> 
> Unhandled Exception: System.NullRefernceException: Object reference not set to an instance of an object.
> 	at PoGo.NecroBot.CLI.Program.CheckKillSwitch<>
> 	at PoGo.NecroBot.CLI.Program.Main<String[] args>

**Comment by anifan115** [comment]
0.8.3 has the same issue

**Comment by Dr-Death** [comment]
yes, i just download 0.8.3 and it has the issue

**Comment by rachong** [comment]
Same here..i downloaded 0.8.2 and have the problems...also when download 0.8.3..it has the same problem

**Comment by rhinogator** [comment]
same here

**Comment by adobo111** [comment]
have the same problem

**Comment by recon88** [comment]
Please try downloading the latest version manually: https://github.com/NECROBOTIO/NecroBot/releases
