### ISSUE TITLE
(SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at .....

### ISSUE THREAD

**Issue by TagorHP** [NECROBOTIO/NecroBot#4312]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
works fine in 0.8.1, occured afer upgrade to 0.8.2

### Actual Behavior
(SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 47.526908,-122.063869...
(SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.5025343,-0.2055027...

### Your config.json
```
your config here
```

### Other Information
Version: 0.8.2
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): snipe @ "PokemonToSnipe"."Locations"

**Comment by ntoenis** [comment]
Im having issues getting skippedlagged to work at all. Just set "SnipeWithSkiplagged" to false,

**Comment by QixinDeng** [comment]
valid json checked by your website, same behavior, how to solve it?

**Comment by recon88** [comment]
Set the SnipingScanOffset a bit higher. Maybe something like 0.01
