### ISSUE TITLE
error in read text saying I need to fill out google user and password, when it is filled out

### ISSUE THREAD

**Issue by bobhill535627** [NECROBOTIO/NecroBot#4314]
![error necro](https://cloud.githubusercontent.com/assets/20942233/17543887/b4655ce2-5ea1-11e6-9fec-2f7a1db6a012.PNG)

I keep getting this error and my username and password is filled out. it ran fine before, but is now giving me this

**Comment by aeleos** [comment]
the new update reset the stored login info in auth.json. I would wait before using the bot for the time being, as after I fixed my login info as soon as the bot started it began transferring all of my pokemon from lowest cp to highest.

**Comment by bobhill535627** [comment]
I cannot even redownload the latest version, it continues to say download error

**Comment by xThreeh** [comment]
too

**Comment by recon88** [comment]
Please download the latest version here: https://github.com/NECROBOTIO/NecroBot/releases
Also make sure you put " " around mail and passwort in your auth.json
