### ISSUE TITLE
New Errors with Location Feeder ?

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#4318]
Is anyone else seeing screens like this?  I had an error with my config on update, but replaced with the a copy i had before update. not sure if this is ok.

![screenshot 3](https://cloud.githubusercontent.com/assets/20919071/17544039/aabf5d9a-5e89-11e6-9497-3868795fdcfc.png)

**Comment by DariusFoxy** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/20919071/17544069/e771a644-5e89-11e6-96f3-e6ebce131fec.png)

**Comment by bobhill535627** [comment]
are you able to download the newupdate, because I cannot, when I tried to reinstall the latest it just says error

**Comment by DariusFoxy** [comment]
this is what i have

https://github.com/5andr0/PogoLocationFeeder/releases

**Comment by theloser** [comment]
Sites (pokezz/pokewatchers) are down (you could just checked yourself), so disable them in your config for now.

**Comment by DariusFoxy** [comment]
where would that info be available ?

**Comment by bobhill535627** [comment]
I cannot get passed the update it asks would you like to update I say yes and then an error explains my google username and password are incorrect, when they are not

**Comment by DariusFoxy** [comment]
please don't hijack my thread. if you have an issue, start your own page.

**Comment by kurozani** [comment]
darius, pokezz is down, false it in conf

btw, can i see your snipe location please :)

**Comment by DariusFoxy** [comment]
Right now i'm trying to UNfuck my config from the 8.3 update.  The exp is largerly from a mass evolution, but lately i've been running around downtown Melbourne, Australia. roughly 40k xp/hr and 110 pokemon when things are working smoothy.

**Comment by palooga** [comment]
TFW the entire config gets fucked

**Comment by DariusFoxy** [comment]
i kept a back up with my best config, but i still have to go down line by line in the new one to adjust it.

**Comment by FantasyHuang** [comment]
Config\config.json
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeWatchers": false,

**Comment by DariusFoxy** [comment]
"UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

this is what i'm using right now, because i wasn't sure exactly what each line did. if you have some time i'd love some help understanding them. thanks
