### ISSUE TITLE
0.8.3 updates removes configs and reverts to default

### ISSUE THREAD

**Issue by JohnnyVicious** [NECROBOTIO/NecroBot#4320]
### Expected Behavior
Auto update and transfer configs

### Actual Behavior
Auto update and bye bye configs

### Your config.json
Well it is gone so no can do

### Steps to Reproduce
Update from 0.8.2 to 0.8.3

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by jayhao2000** [comment]
Your config.json

Well it is gone so no can do

What does it mean?

**Comment by theloser** [comment]
**Can't confirm**. I just used AutoUpdate to go from 0.8.1 to 0.8.3, all my settings are still there (and also it created a auth.json.old and config.json.old). Works flawless.

**Comment by owlran** [comment]
auto update to 0.8.3, and config also revert to default.

**Comment by qwer4790** [comment]
Mine went to default too..

**Comment by jayhao2000** [comment]
Do you guys get soft banned after a few minutes of normal running?

**Comment by DariusFoxy** [comment]
I went from 8.2 to 8.3 and lost config and auth. flawless my ass.

**Comment by dzik87** [comment]
Happens to me on one of my bots. It is very random tho.

**Comment by xRubin** [comment]
problem with upgrade 8.2 => 8.3
upgrade from 8.1 was correct

**Comment by recon88** [comment]
We are now on 0.8.5. Please create a new ticket if that issue still exists in further releases.
