### ISSUE TITLE
Necrobot automatically closing when refusing to update, PTC/GOOGLE not in config

### ISSUE THREAD

**Issue by athanatos1** [NECROBOTIO/NecroBot#4323]
http://prnt.sc/c3u3e8

When I refuse to update, it says there is no PTC OR GOOGLE information in the config, but there is. The same thing happens when autoupdate is false, the bot will crash.

**Comment by verecundus** [comment]
Delete everything in your auth.json and copy and paste this config then enter your info.
If that doesn't work then delete your auth.json and open notepad and copy and paste this and save as auth.json

{
  "AuthType": "google",
  "GoogleUsername": "null",
  "GooglePassword": "null",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "nexus-5x",
  "DeviceId": "243d758c62377b3e",
  "AndroidBoardName": "bullhead",
  "AndroidBootloader": "BHZ10k",
  "DeviceBrand": "google",
  "DeviceModel": "Nexus 5X",
  "DeviceModelIdentifier": "bullhead",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "LGE",
  "HardwareModel": "Nexus 5X",
  "FirmwareBrand": "bullhead",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "google/bullhead/bullhead:6.0.1/MTC19T/2741993:user/release-keys"
}

**Comment by athanatos1** [comment]
I don't want to use google, using PTC account. I shouldn't have to edit the config since the information is already in there.

**Comment by bobhill535627** [comment]
what did you change here, because I am having the same issue. it asks to update I say yes, and then an error comes up saying I need to type username and password, even though they are already there

**Comment by bobhill535627** [comment]
What is changed in there, cause it asks me to update and I do and then I get an error saying my username and password in google are not enetered when they are

**Comment by athanatos1** [comment]
I just noticed the bot is only looking for GOOGLE information before an update, which I do not use. I have ptc info filled out, but it still automatically closes before an update because no google info is in config.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
