### ISSUE TITLE
Bot v0.8.3 detected by Trendmicro office Scan agent as virus/malware

### ISSUE THREAD

**Issue by womanizer81** [NECROBOTIO/NecroBot#4324]
the download is directed beeing blocked by trendmicro and detected as virus/malware.
I was using 0.7.x version, until I found out that the encrypt.dll was removed by Trendmicro. after downloading the latest version 0.8.3. I am not able anymore to even download it.
Unfortunately I cannot change the settings in trendmicro, as it is supported by an external IT company :(

![image](https://cloud.githubusercontent.com/assets/20942387/17544088/7c907070-5ed5-11e6-94f7-699627a598b4.png)
![image](https://cloud.githubusercontent.com/assets/20942387/17544102/945075de-5ed5-11e6-9fec-2b939c513774.png)

**Comment by theloser** [comment]
Hehe... You lost.

There were some reports the other day that other anti virus companies also classify necrobot to be a "virus". Nothing we can do about it.

**Comment by huthutblur1** [comment]
try running in VM =)

**Comment by recon88** [comment]
False positive. Try putting it on the ignore list of your AV programm
