### ISSUE TITLE
[0.8.3] Sniper grab info from pages when disabled.

### ISSUE THREAD

**Issue by dzik87** [NECROBOTIO/NecroBot#4327]
sshot:
http://i.imgur.com/Lscg1E3.png

config:

  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

i use PokeFeeder to get snipe info so i am disabling all snipe pages in bot. but even if it is set to false it is still trying to get info.

**Comment by poutros** [comment]
Doesn't on mine.

**Comment by dzik87** [comment]
To be closed. I found reason. Update deleted and recreated my config.
