### ISSUE TITLE
How to downgrade Necrobot?

### ISSUE THREAD

**Issue by jayhao2000** [NECROBOTIO/NecroBot#4328]
I have a file for an older version.
But whenever I try to run the old file.
The prompt showed the latest version.

Any idea? Thanks

**Comment by necr-0** [comment]
Just download an older "Release.zip" from the /Releases page.

**Comment by athanatos1** [comment]
The bot will still ask to update, and if you refuse, it will automatically close. See issue #4323

**Comment by minseedsa** [comment]
if u not update , windows auto close.

**Comment by jayhao2000** [comment]
Is auto-updated.
I did download the older version, but whenever I open the prompt it showed the latest version.
So there is no other way to downgrade it?

**Comment by karunovsky** [comment]
"AutoUpdate": False,

change that in your config

but it still not found pokestop in 0.7.6

**Comment by recon88** [comment]
https://github.com/NECROBOTIO/NecroBot/releases
