### ISSUE TITLE
Let UseTransferIvForSnipe use the actual Pokemon IV rather than the reported one

### ISSUE THREAD

**Issue by Linus9000** [NECROBOTIO/NecroBot#4331]
As most snipable Pokemon seem to have unknown IV (with each of the three services currently implemented) I'd want that the bot attempts to snipe all the unknown Pokemon, but to flee from them if they have an IV less than KeepMinIV. Currently it snipes all the Pokemon (and potentially wastes berries and balls) even if it only has like 50% IV. If the bot knows the IV before throwing the first ball this would be optimal, but if not it could still run away after the first unsuccessful throw, couldn't it?

**Comment by xafelld** [comment]
I though about this but then realized that farming candies for the rare Pokemon is nice regardless of IV.
Implementing this would still be useful for some people I guess.

**Comment by BobbyWibowo** [comment]
The bot should be able to know the IV after encountering the Pokemon (before actually throwing any Pokeball), so yeah, it should be possible.

**Comment by PiscisSwimeatus** [comment]
The best would be to have a filter like PokemonsTransferFilter.
So you can set catch, CP, IV and level for each separate type.
Because you probrably want just high IV and CP on some types, but all for candy on others.

**Comment by Fazy5** [comment]
I second this request.. No neeed of sniping < 90% iv anyways...

**Comment by Wcidd** [comment]
"Your issue was not created with the template, therefor we cant collect sufficiant information to understand the issue properly. Please create a new issue with the correct template"

**Comment by Linus9000** [comment]
This was a request regarding a new feature. Therefore a template doesn't make sense.
