### ISSUE TITLE
no pokestop .

### ISSUE THREAD

**Issue by SmilingSword** [NECROBOTIO/NecroBot#4335]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by brightjoyy** [comment]
me too got no pokestop

**Comment by brightjoyy** [comment]
in 0.8.3

**Comment by thegodwarrior** [comment]
same problem

**Comment by powerseller1001** [comment]
since update to 0.8.3 no pokestops found anymore. Checked everything, json files are valid, still not working.

**Comment by iimkku** [comment]
same here, was working before and started a few minutes ago. This with 0.8.3 also

**Comment by TommyLingL** [comment]
yep, it was working in v0.8.1

**Comment by MrPK2710** [comment]
idem here

**Comment by brightjoyy** [comment]
and when i open in my iphone it cannot detect my location any more

**Comment by iimkku** [comment]
this is an IP ban, change IP and pokestops are there again. Better use VPN or some other method to mask your ip.

**Comment by SmilingSword** [comment]
new api?

**Comment by cvpride** [comment]
Disable these in your config, worked for me 

"GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

**Comment by SmilingSword** [comment]
still no pokestop

**Comment by brightjoyy** [comment]
guy can you open on your phone

**Comment by SmilingSword** [comment]
yeep

**Comment by brightjoyy** [comment]
and detect the loaction or not

**Comment by SmilingSword** [comment]
what you mean?

**Comment by nakuma85** [comment]
use this:

"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 5000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": true,
  "SnipePokemonNotInPokedex": true,

**Comment by Schweng** [comment]
Used. No effect.

**Comment by SmilingSword** [comment]
still the same no poke sto[

**Comment by SparkzZone** [comment]
same here no pokestops

**Comment by SmilingSword** [comment]
i heard it was new api been release coz i see a lot of bot implented new api in other forum

**Comment by nakuma85** [comment]
No new api, it's working fine for me

**Comment by cvpride** [comment]
get a default config and disable pokezz and pokewatchers

**Comment by brightjoyy** [comment]
maybe our ip got ban

**Comment by TommyLingL** [comment]
it is an ip ban, i just checked, using a vpn and everything fine now

**Comment by brightjoyy** [comment]
me too

**Comment by brightjoyy** [comment]
how can i solve this problem

**Comment by gapracoolz** [comment]
@TommyLingL i use vpn (Hide My Ip) but i got error when started necrobot

**Comment by halowarsss** [comment]
I tried a full version of "Auto Hide Ip" but necro freezed and closed with an error.
We are really interested in a tutorial, from those, who used VPN and working for them. 
What program you used and how did you set it to work necro?

**Comment by recon88** [comment]
You are ip banned. Get a Proxy or new IP
