### ISSUE TITLE
Translation path

### ISSUE THREAD

**Issue by AdamHazda** [NECROBOTIO/NecroBot#4338]
Hi, at first let me thank you for work you all did. (thum up)

I just updated to 0.8.3 and my translation doesn't work. 

I think there is set default path C:\Users\ciamo\source\repos\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs

And I can't change it. Can you please help me? Thank you very much!

Adam

**Comment by ha3u** [comment]
U should choose ur language in configuration.json
"TranslationLanguageCode"

**Comment by AdamHazda** [comment]
Yes, I have it all done but the path of translation file is set to C:\Users\ciamo\source\repos\NecroBot\PoGo.NecroBot.Logic\Common\Translations.cs 

and I don't have this folder and can't change it. I think it is author's folder and it sholud something like "Thisfolder/Translations/Translation.cs"

**Comment by nfettinger** [comment]
Please redownload Necrobot, or delete the translations folder and let it recreate it for you.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
