### ISSUE TITLE
any update let low cost windows bot 

### ISSUE THREAD

**Issue by minseedsa** [NECROBOTIO/NecroBot#4339]
in 0.8.0 i open 5 windows is work! 
in 0.8.1  4 bot work ,im ok!! 
in 0.8.2 3 windows working , fine !!
in 0.8.3 only 1 work or sometime all bad = ='' 
in 0.8.4 ........................................?

**Comment by jonsnowwatch** [comment]
same issue, just download the old release 7.6 is working best for me while running 2-3 bot at a time

**Comment by cekdicoba** [comment]
me too

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

If you find a specific bug, please feel free to open a new issue
