### ISSUE TITLE
what is this please help

### ISSUE THREAD

**Issue by hunterz88** [NECROBOTIO/NecroBot#4340]
![untitled](https://cloud.githubusercontent.com/assets/20942872/17544607/f2d02944-5f0a-11e6-8b26-926d28a32b50.png)

**Comment by ALiangLiang** [comment]
Me too.

**Comment by KillerOffers** [comment]
same here

**Comment by happysam5** [comment]
i think its an ip ban, i have it too. how bots were you running at once

**Comment by palooga** [comment]
It's called an IP ban

**Comment by happysam5** [comment]
does anyone know how long it lasts?

**Comment by BobbyWibowo** [comment]
That's IP ban. Get a VPN or something and you'll be good to go till the next IP ban (in which your normal IP will have to be unbanned already).

**Comment by ALiangLiang** [comment]
@happysam5 I'm use 2 bot with a IP.

**Comment by frendyyuniar** [comment]
Let alone by itself will find pokestop

**Comment by BobbyWibowo** [comment]
> does anyone know how long it lasts?

Should be random. But typically it's somewhere between 15 to 30 minutes. Some people report a couple of hours however.

**Comment by happysam5** [comment]
@ALiangLiang yeah ip ban for sure. i've had a couple, first few came only lasted 10 mins. new one seems to be lasting longer

**Comment by hunterz88** [comment]
ok then i'll use vpn

**Comment by jonsnowwatch** [comment]
ip ban only lasts 5-10 min which only happens if you are running more than 1 bot. if you are running 3+ you will get ip banned with in 5min :/

**Comment by palooga** [comment]
There is no set rule for IP ban or no one really understands it. Just if too many bots then it IP bans. Thats all.

**Comment by BobbyWibowo** [comment]
@jonsnowwatch You can still get IP ban with 1 bot depending on your config (for example if you force it to make too many API calls within a short period of time).

**Comment by erlbinary** [comment]
After i update Me Too

![image](https://cloud.githubusercontent.com/assets/2863244/17544753/c23f17b2-5f0b-11e6-9f10-cc547cd01809.png)

**Comment by jonsnowwatch** [comment]
according to what i have seen, it's about 5min multiplied by how many bots you are using. for example 3 bots = 3x5=15 min ip ban

**Comment by NagaCS** [comment]
@jonsnowwatch If thats true, then Niantic knows whats going on so why not just roll out permanent bans

**Comment by jonsnowwatch** [comment]
of course they know people are botting, theres no way a human being is getting 30k+ xp per hour let only 100k or more. They DO perm ban people, ask anyone who has played ingress. If i were them i would starting perm banning people when most of them are hitting lvl 40

**Comment by erlbinary** [comment]
Im only using one bot on my pc

**Comment by cvpride** [comment]
Set your configs to this 

"GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

**Comment by BobbyWibowo** [comment]
@erlbinary And as I said, you can still get IP ban even if you only run 1 account.

**Comment by frendyyuniar** [comment]
I also experienced the same thing, but a few minutes later BOT running normally, wait

**Comment by atchex** [comment]
solucion??

**Comment by Lastnet0709** [comment]
Check in here http://www.mmoserverstatus.com/pokemon_go

**Comment by Zaryabb** [comment]
Ive used 2 bots FOREVER!!!! like a couple days ive been constantly using 2 at the same time, dont tell me its an IP ban all of a sudden COINCIDENTLY right after the update to 8.3.... it was perfectly fine on 8.1 so the update made it much easier to get ip banned? I dont know but it is related to the update. Before the update ive been running 2 for 3 days

**Comment by palooga** [comment]
@Zaryabb What if niantic just updated something in their servers 30 minutes ago to change the logic of banning? shh shh its time to leave now

**Comment by BobbyWibowo** [comment]
@Zaryabb Look at you.

**Comment by Zaryabb** [comment]
Now i can only run one, i go to cmd release ip and then only the first bot i open works but the second one i open doesnt work. Vice versa also yes @palooga youre right that could be a possibility im sorry

**Comment by PokeyMasta** [comment]
Im having the same issue. im running 2 bot and now only 1 still same. it happen right after the update.

**Comment by edoth76** [comment]
change your IP, and they will works again ... try using VPN or if you had other internet providers (hot spot from smartphones) try to switch to them.
works for me :dancer:

**Comment by PokeyMasta** [comment]
which vpn you guys using taht free

**Comment by BobbyWibowo** [comment]
Google.

**Comment by nfettinger** [comment]
IP BAN

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
