### ISSUE TITLE
Version 8.2/8.3 - Bot crashing when using proxifier after renaming necrobot.exe to necrobot1.exe 

### ISSUE THREAD

**Issue by athanatos1** [NECROBOTIO/NecroBot#4341]
http://prntscr.com/c3u8f4

**Comment by palooga** [comment]
Please tell me why you need to change the name of the executable file?
This is called "USER ERROR"

**Comment by athanatos1** [comment]
Because, I am using multiple bots, which cannot have the same .exe filename "necrobot.exe", since there are different rules.

**Comment by BobbyWibowo** [comment]
If renaming the executable doesn't get you anywhere, try duplicating the whole directory instead?

**Comment by palooga** [comment]
Put them in a new folder?

**Comment by athanatos1** [comment]
Each necrobot1.exe, necrobot2.exe has individual folders, with all the files downloaded. This worked before 8.2,8.3 updates.

**Comment by palooga** [comment]
Well then someone fucked something up if it worked before. But I still don't understand why you need to rename the executable. Even with the same names, the PC still gives them a unique ID when you run multiple instances.

**Comment by athanatos1** [comment]
Because proxifier doesn't differentiate between process ID or folder path, just filename. If 10 bots had the default necrobot.exe, the one rule would apply to all of them. But if renaming to nb1.exe, nb2.exe, each different has different rules to use diff. proxies.

**Comment by Soatz** [comment]
Plz fix dis

**Comment by theloser** [comment]
I am using 0.8.5. and I can rename the .exe file so something else and it runs without crashing.

**Comment by Wcidd** [comment]
"Your issue was not created with the template, therefor we cant collect sufficiant information to understand the issue properly. Please create a new issue with the correct template"
