### ISSUE TITLE
PokemonGo App empty

### ISSUE THREAD

**Issue by emiliovalentino** [NECROBOTIO/NecroBot#4342]
Hi all,

When I open the Pokémon Go app on my iPhone it starts a new game... Anyone familiar with this issue? Already deleted and reinstalled the app, but this didn't solve the issue...

Thanks!

**Comment by palooga** [comment]
What do you even mean it starts a new game? The game doesn't even work unless you log into an account.

**Comment by emiliovalentino** [comment]
It starts with an empty account, showing Bulbasaur, Charmander & Squirtle...

**Comment by SmilingSword** [comment]
?

**Comment by LordDeimos** [comment]
Unless this is Niantic support, this issue have nothing to do with necrobot

**Comment by SmilingSword** [comment]
he is trolling dont mind him

**Comment by palooga** [comment]
nerd

**Comment by emiliovalentino** [comment]
[
![image](https://cloud.githubusercontent.com/assets/20942950/17544818/da8c03f2-5ed9-11e6-8c6c-562cd05aa852.png)
](url)

**Comment by emiliovalentino** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/20942950/17544869/24711b10-5eda-11e6-8069-7572e2fb4e48.PNG)

**Comment by RogueMaster** [comment]
If you have an account you botted up to 35 and never actually logged in, it will show you the start the game tutorial with the three starters. After getting one of the 3 or pikachu, you will notice you actually have all the pokemon and items your bot acquired.

**Comment by palooga** [comment]
Thank you for posting that image I will be sending it to niantic since you are so retarded

**Comment by emiliovalentino** [comment]
I played the game many times already on my iPhone .... It asks me to choose a nickname, what should I do?

**Comment by RogueMaster** [comment]
Pick a name . . .

**Comment by BobbyWibowo** [comment]
It didn't ask you to choose login method before starting the app? Oh right, iPhone. Everything about it is shitty.

**Comment by emiliovalentino** [comment]
Nope, empty account, no Pokémon / Items

**Comment by SmilingSword** [comment]
he just trolling man

**Comment by palooga** [comment]
How about sign out the account that it is logged into and then sign into your botted one? 
I hope you get banned from the repo for trolling

**Comment by emiliovalentino** [comment]
I'm not fucking trolling, it's not working!!!!!!!!

**Comment by SmilingSword** [comment]
all my lvl 40 account still working man. i check it

**Comment by SmilingSword** [comment]
unless you are loggin into different account >.>

**Comment by SmilingSword** [comment]
or bottling a different acc

**Comment by palooga** [comment]
He's either trolling or retarded. There's no question about that.

**Comment by 1Drill** [comment]
^

**Comment by kendallli** [comment]
if you are doing everything correctly you might be the very first person i know whose account is "operated" by Niantic.

**Comment by emiliovalentino** [comment]
It is working again, I did not do anything, I just tried it again and it showed my normal account so it's fixed!

**Comment by SmilingSword** [comment]
....

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
