### ISSUE TITLE
Wrong transfer 

### ISSUE THREAD

**Issue by tulam** [NECROBOTIO/NecroBot#4344]
![pensir](https://cloud.githubusercontent.com/assets/20606174/17544840/ac0fda3a-5ea7-11e6-9550-8b796df25eeb.gif)

Version: 0.8.3
Windows Version: 10
What is affected: transfer more strong bug (by CP and IV).

**Comment by mentosti** [comment]
#4325 
the same issue

**Comment by KauKauHat** [comment]
ya i sow 1 time eevee was transferred the same in 0.8.0

**Comment by DariusFoxy** [comment]
check config,  keep duplicant pokemon: 0

should be 1

**Comment by 1Drill** [comment]
add Pinsir to the PokemonNotToTransferList and it should be fixed

**Comment by BobbyWibowo** [comment]
Did you set `PrioritizeIvOverCp` to `true`?

**Comment by tulam** [comment]
1) I seted PrioritizeIvOverCP - true. 2) Transfer CP>Best CP and Transfer IV> Best IV
It is just 1 case what I saw.

**Comment by engharat** [comment]
I got one snorlax. In the config it is specifically written snorlax in the PokemonsNotToTransfer setion, but still the bot has transferred it! there is a strong bug for sure

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

Duplicate #3338
