### ISSUE TITLE
Any Decent Guide For Setting Up Proxy?

### ISSUE THREAD

**Issue by masterpowers** [NECROBOTIO/NecroBot#4349]
I dont know if im doing it correctly but i always get error
when using proxy...

**Comment by LordDeimos** [comment]
#4204 maybe related to this?

**Comment by masterpowers** [comment]
i think ive set it up, corretcly but not working, or its just timing out...
they should increase timeout , some proxy are just slow in connection...

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
