### ISSUE TITLE
[14:58:47] No usable PokeStops found in your area. 

### ISSUE THREAD

**Issue by jazzu20** [NECROBOTIO/NecroBot#4350]
when I open I open my account in m device. no pokestops / GYm etc. 

is it possible ban??

**Comment by ivanvanoosterhout** [comment]
Yeah same here, i used the default config file.

**Comment by iCreatZ** [comment]
i think, new update

**Comment by SmilingSword** [comment]
ip soft banned

**Comment by jazzu20** [comment]
I bot 2 accounts in my laptop and desktop. so it would safe if I bot just 1?

**Comment by SmilingSword** [comment]
my working now after chaning my moderm to new ip

**Comment by SmilingSword** [comment]
1-2 should be fine

**Comment by iCreatZ** [comment]
@SmilingSword how do u change the modem?

**Comment by Adriskye** [comment]
it worked for me since i updated the program (only 1 account boting_)

**Comment by 20giis** [comment]
http://www.wikihow.com/Change-Your-IP-Address-(Windows)

**Comment by 20giis** [comment]
to @iCreatZ

**Comment by CakeHole83** [comment]
2 account doesn't get you softbanned. If you have deafault settings on there shouldn't be a problem.
You dont need to change the modem. Just download a VPN and set it up.

**Comment by iimkku** [comment]
dudes this is not a support forum. your ip got banned! this is not a development issue.

**Comment by iCreatZ** [comment]
thanks @20giis

**Comment by jazzu20** [comment]
perfect. I just restarted my modem and it works good now. thanks guys

**Comment by ivanvanoosterhout** [comment]
Yess it is the IP address.. Change it and it will work

**Comment by Adriskye** [comment]
i did restart on bot and it worked :dancers:

**Comment by SmilingSword** [comment]
im using 1 account for bottling. after opening another acc instant soft banned again

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
