### ISSUE TITLE
encrypt.dll - Error

### ISSUE THREAD

**Issue by Litefora** [NECROBOTIO/NecroBot#4351]
I updated to the latest version, but since then the "encrypt.dll" is deleted out of the resources folder every time I try to copy it from the *.zip-file to it. Every anti virus software has been deactivated, but this doesn`t solve the problem. When trying to start the application the following error is thrown:

"The DLL "resoucres/encrypt.dll": The module couldn`t be found."
![error](https://cloud.githubusercontent.com/assets/20942462/17545198/26a0d914-5edc-11e6-99e4-ed6a31840115.jpg)

**Comment by Zyfax** [comment]
Workaround: Exclude the path where your bot is located in your antivirus.

**Comment by nfettinger** [comment]
Or whitelist it in your antivirus.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
