### ISSUE TITLE
IP change

### ISSUE THREAD

**Issue by REDDE4D** [NECROBOTIO/NecroBot#4362]
Not an Issue but i can't create an Pull Request.

Is it possible to add an Value to the config to set an IP for servers?

**Comment by SmilingSword** [comment]
yep it would be great to spoof ip by auto or manually

**Comment by theloser** [comment]
Hum, what?

I don't understand -- what do you want to "spoof", the IP address your bot uses to connect to Niantic's server? Impossible.

**Comment by SmilingSword** [comment]
what you mean impossible. fake the ip of one of bot to different ip so we can use another bot with different ip

**Comment by SmilingSword** [comment]
niantic use our wifi ip or mobile ip to know how many user using same ip

**Comment by Texquad** [comment]
So how do you change your IP associate with your bot?

**Comment by theloser** [comment]
@SmilingSword It's impossible to "fake" your IP, because that's how "the internet works". If you want to change your bot's IP address you have to run your bot on a different server with a different IP address or use a proxy server. Simple as that.

**Comment by Texquad** [comment]
Ok, that makes obvious sense. Is there a way to change which server your bot is running on?

**Comment by theloser** [comment]
http://lmgtfy.com/?q=how+to+use+a+proxy+server+or+a+vpn+server

**Comment by REDDE4D** [comment]
The thing is that I've got a server with 4 different IP's.
But the bot is using only one of them.
So i thougth thats an good and simple option instand of changing Server config.

**Comment by theloser** [comment]
Your sevrer has four different IP addresses? **External** IP addresses? How? :-)

**Comment by nfettinger** [comment]
You need to bind each instance to a specific hardware interface if you want them to all use different IPs

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
