### ISSUE TITLE
NecroBot not sniping preset location

### ISSUE THREAD

**Issue by necr-0** [NECROBOTIO/NecroBot#4363]
**Version:** 0.8.3
**Replicated on:** 0.8.2/0.8.3

The problem is pretty clear. The bot won't attempt to snipe any of the locations under the category _PokemonToSnipe_. I've checked (and double-checked), and the _SnipeAtPokestops_ setting is set to _true_. Regardless, the relevant parts of the configuration file are listed below.

**Sniping**
```
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 30000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
```

**Locations**
```
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 35.6328964,
        "Longitude": 139.8803943
      },
      {
        "Latitude": 40.712784,
        "Longitude": -74.005941
      },
      {
        "Latitude": 38.907192,
        "Longitude": -77.036871
      },
      {
        "Latitude": 37.77493,
        "Longitude": -122.419416
      },
      {
        "Latitude": 52.520007,
        "Longitude": 13.404954
      },
      {
        "Latitude": 51.507351,
        "Longitude": -0.127758
      }
    ],
```

Seems to be a problem with the bot itself, but if there's a configuration issue I'm missing, please point it out. Thanks!

**Comment by popsoda27** [comment]
set "UseSnipeLocationServer" to false

**Comment by necr-0** [comment]
@popsoda27,

Still not sniping.
![0 8 3 - sniping](https://cloud.githubusercontent.com/assets/20924421/17546144/076d409e-5f24-11e6-87ac-30d7d8cf8ca9.PNG)

**Comment by Gandaflux** [comment]
What about **SnipeWithSkiplagged** config ?

**Comment by necr-0** [comment]
@Gandaflux,

Set to _false_.

**Comment by Gandaflux** [comment]
@necr-0  Change it to true, thats why its not sniping.

**Comment by necr-0** [comment]
@Gandaflux,

Ah, seems that's the error.
I presumed SkipLagged was a service, similar to Pokezz or the like. Not sure why it has a .com on the end of it. Regardless, thanks!
