### ISSUE TITLE
no pokestop detected when get softbanned

### ISSUE THREAD

**Issue by ndut1986** [NECROBOTIO/NecroBot#4366]
cant find any pokestop after get softbanned
<a href="http://www.imagebam.com/image/30f09e499126707" target="_blank"><img src="http://thumbnails115.imagebam.com/49913/30f09e499126707.jpg" alt="imagebam.com"></a>

**Comment by R0jo** [comment]
Change your ip

**Comment by aVitomin** [comment]
it's ip ban
Change ip or wait some time and run again

**Comment by brightjoyy** [comment]
how to change my ip

**Comment by brightjoyy** [comment]
so how can i do can you told me

**Comment by R0jo** [comment]
restart your modem/router

**Comment by R0jo** [comment]
@ndut1986 yeah, you can use a vpn without any problems

**Comment by jasonisnear** [comment]
Well, my IP cannot be changed by restarting my router. What VPN would you recommend? I think mine got permanent ban since last night.

**Comment by blackuGT** [comment]
I got IP ban toooo...

**Comment by Disane87** [comment]
As I discovered, the softban is limited to 10 minutes.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
