### ISSUE TITLE
Keep the best CP [ AND ] keep the best IV

### ISSUE THREAD

**Issue by ilihack** [NECROBOTIO/NecroBot#4367]
_**Please, think about this Feature Request, because it will be handle much of problems and reduce pain.**_

_Its will be much better, to hold X of the best CP and Y of the best IV instead to have the TransferPokemonKeepDuplicateAmount Setting!
After this the setting PrioritizeIvOverCp can be also removed, because you can choose it instead wit with X&Y to_

no one more will be in pain, if him best IV or best CP are transferred

i cannot made the change self, because i have to little skills with this, and hope someone find this idea good.

Spegeli bot PokemoGoBot-GottaCatchEmAll already implemented this idea in his Version, but last weak i switched to Necrobot.

**> CHANGLOG SPEGLI BOT: KEEP THE BEST CP AND THE BEST IV**
> [ADDED] User can specify number of max IV and number of max CP Pokémon’s to keep for each family - 
> TransferPokemonKeepDuplicateAmount get removed, instead we have now 2 new options:
> TransferPokemonKeepAmountHighestCP = Keep X Highest Pokémon based on CP (when doing Transfer) - Default 0 (because CP are useless)
> TransferPokemonKeepAmountHighestIV = Keep X Highest Pokémon based on IV (when doing Transfer) - Default 1

**Comment by nfettinger** [comment]
Duplicate issue.
