### ISSUE TITLE
No usable pokestops found in your area, Is your distance too small?

### ISSUE THREAD

**Issue by STCOZT** [NECROBOTIO/NecroBot#4369]
Its the first time i am getting this error, its not a softban nor ipban. Is this a general problem ?

**Comment by polypalm** [comment]
got the same problem about 20 min now and i used 2 bots only... now i cant even 1

**Comment by RentonXD** [comment]
Same here. Even after latestest Update. Maybe a new Server Patch?

**Comment by Bionicle06** [comment]
Same.

**Comment by polypalm** [comment]
also tried VPN nothing

**Comment by STCOZT** [comment]
Yup I checked there is a new update for pokemon go > 1.3.0

**Comment by SmilinItalin** [comment]
1.3 was a couple days ago........

**Comment by polypalm** [comment]
that update was 10 hours ago

**Comment by danooh** [comment]
they softbanned our IPs, just tested it

**Comment by STCOZT** [comment]
really, sorry i didn't check it I've just got up :((

**Comment by STCOZT** [comment]
@danooh Is there a solution except waiting ?

**Comment by danooh** [comment]
@STCOZT restarting my router worked for. so it was rlly just ip-based

**Comment by Blackjesus69** [comment]
Using a VPN has worked for me so far

**Comment by wesker246** [comment]
It seems, that we pissed off Niantic so much, that they started to ip ban everything ;]

**Comment by RentonXD** [comment]
okay but what may caused these ip bans? o.O

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
