### ISSUE TITLE
Red text error

### ISSUE THREAD

**Issue by AceTotem** [NECROBOTIO/NecroBot#4370]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Run smooth

### Actual Behavior
Red texto and restarts( by the way can't connect to Pokezz.com)

### Your config.json
0.8.4 normal with sniper true

### Steps to Reproduce
I start pogolocation feeder and then open the app so it starts and then shows a red text and restarts the bot logging in as ptc again

### Other Information
Version: 0.8.4
Windows Version: Windows 10 Home 1511
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
The all thing. Cannot use it.
![image](https://cloud.githubusercontent.com/assets/20837602/17546199/e37cc22c-5ed8-11e6-813c-495705a8c05d.png)

**Comment by SmilinItalin** [comment]
I had the same problem, on 8.3 and now on 8.4........ and all the auth info and the config info isn not carrying over to the new patch.

**Comment by ThomasSRL** [comment]
Same problem here on 8.5, unsure what is causing it!

**Comment by nfettinger** [comment]
Duplicate #3295
