### ISSUE TITLE
Full Pokemon Inventory Notification

### ISSUE THREAD

**Issue by DSanHao** [NECROBOTIO/NecroBot#4379]
would you add full pokemon inventory notification? the bot keeps telling me "Did not find a Pokemon within the Location, pokemon despawned?" instead

**Comment by ANR2ME** [comment]
softban may be? just like "no usable pokestop" message

**Comment by DSanHao** [comment]
when I tried pokesniper2 it confirmed that my pokemon inventory is full. and I confirmed it by checked it through app

**Comment by nfettinger** [comment]
Duplicate issue.
