### ISSUE TITLE
Google App password. 2 step verification.

### ISSUE THREAD

**Issue by CakeHole83** [NECROBOTIO/NecroBot#4383]
Keeps giving me red text saying I need to login using google application password. The account I use doesn't have a google app password so the problem seems to be somewhere else.
Can this be part of an IP-softban or has something changed with the bot during the last two updates?
The last update given also deleted my account information in the authfile which doesn't normally happen.

**Comment by frendyyuniar** [comment]
use password security

**Comment by georgi-huklev** [comment]
Create a google app password here:
https://security.google.com/settings/security/apppasswords

**Comment by CakeHole83** [comment]
That doesnt matter when the account has no google two step verification to start with. These errors started showing about 15mins ago so shouldnt have anything to do with any account.

**Comment by georgi-huklev** [comment]
Can you login from your phone?

**Comment by frendyyuniar** [comment]
Us https://security.google.com/settings/security/apppasswords
![capture](https://cloud.githubusercontent.com/assets/20942918/17547131/9f67f516-5f0f-11e6-82b1-81f339873e9d.PNG)

**Comment by recon88** [comment]
Educational Account? Custom Domain?

**Comment by samesame27** [comment]
I was experiencing the same issue.

[06:13:36] Perfect! You already have the newest Version 0.8.5
[06:13:36] Logging in using Google
[06:13:36] You need to fill out GoogleUsername and GooglePassword in auth.json!

- could access the app through my phone from same wifi = likely not IP or account ban
- 0.8.5 also cleared my saved auth.json file and I had to manually reenter credentials
- created a fresh google app password
- did a full folder wipe and reinstall of the latest release

In the end I opened the log to paste the above in and saw there was a new json exception.... 
"JSON Exception: You need to properly configure your GoogleUsername using quotations."

So I put quotations around my name and the app password and am back on now. 

YMMV lol

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
