### ISSUE TITLE
After v0.8.4 update my bot is show error

### ISSUE THREAD

**Issue by dtscript** [NECROBOTIO/NecroBot#4386]
How to fix this  >> Error Message "User credentials are invalid and login failed."

**Comment by necr-0** [comment]
Possibly have an IP ban. Change your IP or use a VPN, and then report back.

**Comment by iimkku** [comment]
if there really was a bug like this you wouldn't be the only one. plase think twice before reporting issues or bugs related to software, not just that you have a problem with something.

**Comment by redstarksten** [comment]
stay use 0.8.1 version

**Comment by recon88** [comment]
Check auth.json if everything is right. Also make sure there are " " around your mail and password.
