### ISSUE TITLE
buged PrioritizeIvOverCp

### ISSUE THREAD

**Issue by Ellerancz** [NECROBOTIO/NecroBot#4387]
i have PrioritizeIvOverCp: false , 
but the system still compares according Iv
![foto1](https://cloud.githubusercontent.com/assets/20944443/17546819/34614c02-5ee4-11e6-9d41-952955b30a15.png)

### Other Information
Version: 0.8.4
Windows Version: win10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): transfer

**Comment by frendyyuniar** [comment]
all the problems is there, let it go, if it does not happen that sort of thing might be better not to use BOT :dancer:

**Comment by wesker246** [comment]
I've noticed, that it happens because of PokemonTransferFilter - it overrides every other settings in main section about keeping pokemons

**Comment by Lynael** [comment]
it's normal your pokemon don't have more than 1250CP and are less than 90% IV
