### ISSUE TITLE
Not Transferring Pokemons

### ISSUE THREAD

**Issue by Heart92** [NECROBOTIO/NecroBot#4388]
My bot is not transferring a lot of pokemons that aren't in the NotToTransferPokemons. Here is my setup:

 "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
__________________________________________________________

"PokemonsNotToTransfer": [
    "arcanine",
    "machamp",
    "muk",
    "exeggutor",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"

These pokemons that are not transfered are not included in the TransferFilter, like Ekans, Pidgeot, Goldeen, etc...

**Comment by necr-0** [comment]
Ensure that _KeepMinDuplicatePokemon_ is set to _0_, else the bot will transfer any Pokemon under your KeepMinIV/CP settings.

**Comment by theloser** [comment]
Because this is a config and not a development issue, please use the discord channels to get help. Thanks.

**Comment by Heart92** [comment]
But bot keeps a lot, like I have over 20 Bellsprout, which is not included in the TransferFilter, why does bot keep them all? should only keep 2

**Comment by Heart92** [comment]
Help please

**Comment by theloser** [comment]
Because this is a config and not a development issue, **please use the discord channels to get help.** Thanks.

**Comment by Heart92** [comment]
I don't get what you mean, I just made my account in gethub..

**Comment by theloser** [comment]
GitHub is NOT a support forum for config issues. It is for developers, and developers only. If you have any  questions about your config, please use [this link](https://discord.gg/VXKxNFr) to go to discord and ask for help.

**Comment by Heart92** [comment]
Thanks for the link, but I see everyone is asking for config issues here, not just me..

**Comment by theloser** [comment]
> everyone is asking for config issues here

Because they are all dumb as fuck. Config issues --> Go to discord, please! Thanks :+1:

**Comment by recon88** [comment]
Please keep the issue tickets a nice place.

**Comment by theloser** [comment]
@recon88 I am always trying to be nice and helpful. But if people **are** dumb as fuck can't help myself... :-)

**Comment by recon88** [comment]
Yea but no need to tell them in public. They won't notice ;)
btw what's your name on our Discord?
