### ISSUE TITLE
version 8.4 still cant sniping for me....

### ISSUE THREAD

**Issue by james50428** [NECROBOTIO/NecroBot#4391]
i can't use sniping when i use bots
but bot without anything works
i only add sniping tool
nothing else
version 8.4 & 8.3 will crash for me
idk is my fault or not

here is the screenshot of my problem 
![image](https://cloud.githubusercontent.com/assets/20561837/17547097/d8e67e04-5f17-11e6-8d55-368fefbcc588.png)

**Comment by necr-0** [comment]
Please post your configuration file to Pastebin and link us here.

**Comment by james50428** [comment]
http://pastebin.com/11CGQ6Xt
over here

thanks

**Comment by necr-0** [comment]
...
Where's the rest of the code?

**Comment by james50428** [comment]
there only few line
idk why i've tried to edit the original config file to the sniping method(according to the wiki)
then i open my bot and check the config file again still change what you see on the paste bin  only few lines


![image](https://cloud.githubusercontent.com/assets/20561837/17547535/5a133f6a-5f1a-11e6-975d-17931b49ad62.png)

**Comment by necr-0** [comment]
@james50428,

Oh. My. God.

Right, okay.
Um, you just need to edit those lines in the configuration files. Delete the app and re-download it. Don't remove everything else, just edit the lines of code.

**Comment by james50428** [comment]
still the same m8
sniper tookit will automatically change my config file
maybe i wont use sniper for now..
but thanks a lot

**Comment by necr-0** [comment]
Okay, seriously, just download the 0.8.5.
Extract it. Run it and go through the setup. Exit Then edit this line in your settings:

`"SnipeAtPokestops": true,`
Change it to false.

Save and you're good to go.
