### ISSUE TITLE
What was exactly was the 3rd party plugin?

### ISSUE THREAD

**Issue by palooga** [NECROBOTIO/NecroBot#4392]
What was exactly was the 3rd party plugin?
Thanks

**Comment by Omigof** [comment]
is this about pogolocationfeeder for auto location sniping?

**Comment by LordDeimos** [comment]
Look on pull request, it was a merge to support 3rd party plugin like web interfaces.
The PR was the #3895 there you can read something about it.

**Comment by Omigof** [comment]
so they're remove that guy plugin ( PR #3895 ) that was merged on v8.1 ?
sory my english is bad

**Comment by recon88** [comment]
It was just the plugin support. Nothing you should worry about.
