### ISSUE TITLE
Always get softban & IP ban after 10-20 minutes

### ISSUE THREAD

**Issue by Jojoushi81** [NECROBOTIO/NecroBot#4396]
Hello Guys,

This is my config
http://pastebin.com/shrR6rNG

I'm using Pokegofeeder and Necrobot 0.8.4 at same time.
Can u give the solution for this?

Thanks

**Comment by LordDeimos** [comment]
"DelayBetweenPlayerActions": 100,
  "DelayBetweenPokemonCatch": 100,


You're asking to get IP ban just for those 2 delay so low.....

**Comment by sventse** [comment]
@LordDeimos I had the same problem using the default config with 8.5

**Comment by Kjewn** [comment]
"DelayBetweenPlayerActions": 5000,
"DelayBetweenPokemonCatch": 2000,

Thats what im using atm LOL

**Comment by yonrin** [comment]
@Jojoushi81 yeah the guy is right. You're "pinging" them every 0.1 seconds. If they see that you've done this for 20 hours they will ban.

**Comment by Nick2400** [comment]
Still... 2 seconds between catching pokemon is unrealistic, set it to 15000

**Comment by jonsnowwatch** [comment]
all my delays are set to 0 with a walking speed of 300km/hour, im doing just fine with 0.7.6 :P

**Comment by LordDeimos** [comment]
5000 and 2000 are good values, I even use higher value. Cba to to IP ban every 20 min
