### ISSUE TITLE
Bug on launch

### ISSUE THREAD

**Issue by ASKcoTM** [NECROBOTIO/NecroBot#4397]
What it says on launch;

Exception caught, writing log buffer.

unhand-led exception: system.NullReferenceException: object reference not set to an instance of an object.
at PoGo.Necrobot.CLI.Program.CheckKillSwitch<>
at PoGo.Necrobot.CLI.Program.Main<string[] args>

What does this mean and how do i fix it. I have tried to re-download it but it dosn't work

**Comment by Exorsist2005** [comment]
I have a same problem and don't have any suggestions about it
![necrobot](https://cloud.githubusercontent.com/assets/20945111/17547829/bf4242e2-5ef1-11e6-9a86-17455d87293d.jpg)

**Comment by 4valanch3** [comment]
Same problem here. 
At each start, it wants to rebuild the translations folder. 
Walking speed is screwed, it the bot runs with 15km/h regardless of lower setting (7.2).

**Comment by nfettinger** [comment]
You typed something wrong in your config file. Missing a " or a , most likely.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
