### ISSUE TITLE
Can't found pokestop 

### ISSUE THREAD

**Issue by mostgod** [NECROBOTIO/NecroBot#4398]

**Comment by hilmibou** [comment]
same here

**Comment by palooga** [comment]
Screw off

**Comment by sazzanm** [comment]
same here x3

**Comment by mostgod** [comment]
I change the location remain the same can't found pokestop

**Comment by Kjewn** [comment]
Chance IP-adress, probebly Soft IP ban.

**Comment by letuananh035** [comment]
Software chance IP ?? you can help me ??

**Comment by wesker246** [comment]
Do Proxy/VPN or router reset (if your Internet provider gives different ips after new connection)

**Comment by minseedsa** [comment]
i try VPN Gate it Free

**Comment by letuananh035** [comment]
I use Wifi :)

**Comment by sazzanm** [comment]
yeah using vpn i can found pokestop , is there a way to get out of the ip ban without vpn ?

**Comment by wesker246** [comment]
@sazzanm Unfortunately, no. The only solution is to wait until its gone.

**Comment by buddiz87** [comment]
still banned almost an hour, anyone know how long does it take?

**Comment by mostgod** [comment]
i use wifi, and can't found again

**Comment by minseedsa** [comment]
3 Hr. ban

**Comment by brightjoyy** [comment]
now maximun is 2 bot per ip

**Comment by wesker246** [comment]
@buddiz87 It seems that it builds up gradually based on how many times I've been banned previously, but it need to be confirmed.

**Comment by Caliboss** [comment]
i restarted my router, restarted my ip from inside my routers config.. both didnt work. 
im guessing its like diablo 2.. i have to change my mac address in my router settings.
im searching for it but i cant find the option in this router :(

**Comment by sazzanm** [comment]
@Caliboss just use a vpn , while u have ip ban D:

**Comment by wesker246** [comment]
@Caliboss If your Internet provider doesn't give an option to get different ip after a new connection (router restart), doing mac adress change wont help.

**Comment by Caliboss** [comment]
i have never done a vpn.. dont even know where to start.. and dont i have to pay for that ?

**Comment by sazzanm** [comment]
@Caliboss  http://www.hackingdistrict.com/threads/does-anyone-know-how-to-bypass-the-multi-bot-ip-ban.224/ < ez tutorial

**Comment by Caliboss** [comment]
geez, cant even sign in on my phone. im kinda scared now :p

**Comment by 2hf** [comment]
Change your NecroBot version to 0.7.0. It works for me.

**Comment by sazzanm** [comment]
@Caliboss  yea here too , on my phone doesnt work too :/ just using vpn save me lol

**Comment by Caliboss** [comment]
i dont think im ipbanned anymore.. bot says i am. but i just caught a pokemon right in my front yard

**Comment by sazzanm** [comment]
@Caliboss  lol

**Comment by Caliboss** [comment]
nope im unbanned in bot too.. now i better just run 2 instead of 3.. and use longer settings like you guys suggested.. woooo!

**Comment by jemrick** [comment]
so what the update now? do we need to use the 7 version or the updated one?

**Comment by wesker246** [comment]
@jemrick problem lies on Niantic side, as they are banning our IPs, not the bot itself.
Moving forward from this conclusion, changing bot version won't do anything to solve the problem.
