### ISSUE TITLE
Evolve when 'X' pokemon can be evolved

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#4399]
A setting that allow necro to evolve only if he can evolve more than 'X' pokemon; else continue to transfer.
(for lucky egg utility improvement)

EDIT: I mean... I would like to evolve ONLY IF BOT CAN EVOLVE MORE THAN 'X' POKEMON, not if there're more than X pokemon in my bag.

EX: 250 is bag size
I want to evolve when i have more than 25 pkm to evolve. If there are less than 25 pkm to evolve, transfer other pokemon;
snipe/farm;
repeat;

**Comment by Kjewn** [comment]
I find it doing that when i put. use egg when evolve at 30

**Comment by Profetorum** [comment]
I don't mean that; ok, lucky is been used when pokemon to evolve > 'X' , but i would like to evolve ONLY when i have more than 'X' pokemon. 

With your hint, necro still evolving if there aren't enough pokemon for lucky egg; simply it doesn't use it

**Comment by theloser** [comment]
What's wrong with EvolveKeptPokemonsAtStorageUsagePercentage? Just set it to some value which accomplishes what you want.

**Comment by Profetorum** [comment]
You don't understand what i'm asking...

I would like to evolve ONLY IF BOT CAN EVOLVE MORE THAN 'X' POKEMON, not if there're more than X pokemon in my bag.

**Comment by theloser** [comment]
I fully understand what you want. And you can use EvolveKeptPokemonsAtStorageUsagePercentage to achieve this!

Tell me how many pokemon are in your inventory (that you want to keep), how big is your inventory, and how many pokemon you want to keep before evolving.

**Comment by theloser** [comment]
Ok, assuming you want to keep 200 pokemons. Just set EvolveKeptPokemonsAtStorageUsagePercentage to "95.0" to start evolving when your inventory is 95% filled (which is about 229 of max 241 pokemons you can keep) -- then you will evolve 29+ pokemon.

**Comment by Profetorum** [comment]
Nope, with this 29+pokemon could be evolved; there's no reason to think that those 29+ pkm are evolvable (has enough candies)

**Comment by Profetorum** [comment]
Why closed?

**Comment by recon88** [comment]
thelose already explained how to achieve that.
