### ISSUE TITLE
Add .appveyor.yml to git

### ISSUE THREAD

**Issue by JamieMagee** [NECROBOTIO/NecroBot#4401]
Adding the `.appveyor.yml` to git will allow other developers to run their own appveyor builds before creating pull requests.

**Comment by nfettinger** [comment]
We dont support other branches not created by the developers.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by JamieMagee** [comment]
I understand that you don't support branches created by other developers. I would just like to be able to run my own appveyor builds, before creating PRs back to this repo.

For example, I created a PR which built locally, but didn't build on appveyor due to differences in their environment. If I had been able to run my own appveyor builds, I wouldn't have wasted time in creating a PR that didn't build.
