### ISSUE TITLE
Account security issues

### ISSUE THREAD

**Issue by CakeHole83** [NECROBOTIO/NecroBot#4402]
Since 0.8.3 google is telling me someone has tried to login to my account in Germany. Since that specific account is only used with necrobot and for nothing else I am getting curious to if someone has made the bot send out information about the accounts to a third party? Is it just me getting these or is someone else getting strange notifications after last updates?

**Comment by Kjewn** [comment]
Thats because of your Proxy/VPN ;)

**Comment by theloser** [comment]
Using a proxy?

**Comment by bhenie** [comment]
thats exactly you are using VPN

**Comment by CakeHole83** [comment]
Even if I would it would occour on all accounts?

**Comment by yonrin** [comment]
it might not be of proxy though. My IPS says im in denmark sometimes but i live in norway. Contacted them and it was because of old ip's and that they haven't bought new ip's
(my location ip)

**Comment by CakeHole83** [comment]
Yeah but it still seems strange that it happend on one account. (I am running 6 through same VPN.)

**Comment by yonrin** [comment]
yeah but still i dont think the developer would do that to this community. What possible advantage would that give him? if he wants to sell the accounts, you can just change the password of your google account if you have a security setup, with confirmation to cellphone number

**Comment by bhenie** [comment]
try to not login in a couple day.. and then see, gmail notification. if there a warning again about login activity... yau have been hijacked.

**Comment by CakeHole83** [comment]
Nah I dont think it's the developers.

**Comment by Kjewn** [comment]
@CakeHole83 Should watch out with running 6 ;) Google has this problem more often then you would think. if im right you can check the IP adress that logged in. Check where your proxy is located to confirm

**Comment by isolah123** [comment]
that just happen for gmail account, mostly because unsettle login history (IP/VPN). the fastest way to escape this problem is to change your gmail password frequently or u can just ptc account.

**Comment by Sicarii** [comment]
I only run 1 client, no proxy/vpn....my android phone wouldn't clear/cancel the sign-in request until I did it

**Comment by CakeHole83** [comment]
When you get ip banned does the bot see it as you have entered the wrong information? First it asked me for two step verification and now when I got that it tells me to check so my information is correct. (Logged in on phone and it all works.)
