### ISSUE TITLE
Broken sniping&catching in 0.8.1+ versions

### ISSUE THREAD

**Issue by Gandaflux** [NECROBOTIO/NecroBot#4403]
Two bots on same computer.  Both sharing same configuration. 

0.8.1 is sniping and catching pokemons without problems
0.8.4 all the time says 'no pokemon found'

when i change 8.4 exe to 8.1 and run that, its working again.

![bot](https://cloud.githubusercontent.com/assets/20873230/17547429/7c975a40-5ee7-11e6-9fcd-638fe3d43c84.jpg)

**Comment by Kjewn** [comment]
Look what the offset is in both configs, there might be your problem.

**Comment by Gandaflux** [comment]
Please. read carefully. bot bots are sharing same config, and when i replace exe to old version (without changing config) its working. 

``
"SnipingScanOffset": 0.01
``

**Comment by chuahood** [comment]
"SnipingScanOffset": 0.01
that solved the issue?

**Comment by Gandaflux** [comment]
@recon88 why its closed? Its fixed somehow ?

**Comment by recon88** [comment]
Works fine for me. Just set the offset a bit higher.

**Comment by Gandaflux** [comment]
@recon88 It looks like not only i have such problem #4488

**Comment by recon88** [comment]
Will keep the other ticket open then

**Comment by Gandaflux** [comment]
ok, thanks

**Comment by jamalbaharun** [comment]
how much you set the spinning offset @recon88 ?
