### ISSUE TITLE
New Issues with 8.4

### ISSUE THREAD

**Issue by DariusFoxy** [NECROBOTIO/NecroBot#4406]
Keep getting these periodic crashes about every 5-20 minutes.  

Pokemon servers might be offline/unstable then crash.
![screenshot 6](https://cloud.githubusercontent.com/assets/20919071/17547631/0f4e90ce-5e9d-11e6-957b-5ecaa0198e0d.png)

**Comment by Kjewn** [comment]
Someone had that aswell, could be caused by the "snipeatpokestops" no idea why tho.

**Comment by DariusFoxy** [comment]
I'll try turning that to false..  what exactly does that do ?

**Comment by Kjewn** [comment]
Well, it looks for snipes when it finishes a pokestop, but somehow people report crashes by that.

**Comment by yonrin** [comment]
Happened to me to

**Comment by DariusFoxy** [comment]
still crashing.

**Comment by Markersx** [comment]
#4294

**Comment by DariusFoxy** [comment]
so far the only thing that stops it is turning off snipes. so the problem is somewhere in there

**Comment by nfettinger** [comment]
Duplicate #3295
