### ISSUE TITLE
I have issue when I went to gym 'error'

### ISSUE THREAD

**Issue by chitchitcit13** [NECROBOTIO/NecroBot#4408]
Has anyone actually tried playing a botted account in a gym battle?  For instance, i may have made an account yesterday and its currently level 25 and when i engage in a gym battle, it displays "error."  anyone else with this issue?

**Comment by Cyruz007** [comment]
Account softban

**Comment by chitchitcit13** [comment]
Yes softban but why i can catch pokemon which i have only issue when i engage in gym battle

**Comment by Cyruz007** [comment]
I don't know, I tried the same thing.
If you wait around 20-30min. it usally works. Properly because you jump to fast from your bots coordinates.

**Comment by Markersx** [comment]
if you set your bots coordinates to the gyms coordinates then wait for the bot to unban you it should work

**Comment by chitchitcit13** [comment]
Thanks sir
