### ISSUE TITLE
the translation problem with 0.8.5

### ISSUE THREAD

**Issue by FreshCodeMan** [NECROBOTIO/NecroBot#4409]
just now i updated to 0.8.5 and then it throwed an exception and crashed. the language i set is zh_CN, then i changed it into en.it works and doesn't throw exceptions any more.

**Comment by MarkusPaul89** [comment]
Tried to reproduce the problem, but zh_CN works fine for me at 0.8.5

**Comment by 4valanch3** [comment]
My 0.8.5 rebuilds the entire translation folder at restart. Weird, at least.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
