### ISSUE TITLE
Constant softban since 0.8.3

### ISSUE THREAD

**Issue by TheMaskedMonkey** [NECROBOTIO/NecroBot#4410]
Since updating from 0.8.3, I've been getting constant softbans and has even resulted in me being IP banned. (I'm assuming the IP ban is temporary too)

I'm not sure but my configs were perfect. Perfectly human like and haven't been modded unless there's a big configuration update.

Here's an image of the constant soft ban: https://i.imgur.com/0zQRZgG.png

I literally can't run any bot without the risk of it being softbanned and possibly flagged. (And no, like I said above, I haven't touched a single line in my config. It's just started happening since the update to 0.8.3 and higher)

**Comment by Kjewn** [comment]
Well, lower the speed, set your snipeoffset to 0.0013 and DONT diasble humanlike walking.

**Comment by TheMaskedMonkey** [comment]
I haven't. Like I said, I had them perfectly human like. They've been perfect till the recent changes.

**Comment by yonrin** [comment]
have you only had one bot active at the time?

**Comment by TheMaskedMonkey** [comment]
Only two. Been running both since 0.7.0 fine.

**Comment by yonrin** [comment]
thats weird. That still shouldnt give you a constant ip ban. Can you check your config, where it says delay between actions, and walking speed?

**Comment by sehvenseas** [comment]
I've heard some rumours, or read somewhere... that they r monitoring the amount of conections from each IP.. and if u have more than 1 connection it will get you IP banned

**Comment by Snake87r** [comment]
Attach the config file..
if you see the coordinate for the snipe pokemon are very distant between each other, maybe the app teleport you from one location to another and the niantic server ban you, try to disable the sniper function and see wath happen.

**Comment by can99** [comment]
same prob~ could running 8+ hours nicely last night with 8.1,
but after the update it works a while then constant softbanned

**Comment by TheMaskedMonkey** [comment]
> I've heard some rumours, or read somewhere... that they r monitoring the amount of conections from each IP.. and if u have more than 1 connection it will get you IP banned

No, that's not correct. Multiple people can login to their accounts from the same home connection and some cell towers share ips between multiple customers.

>thats weird. That still shouldnt give you a constant ip ban. Can you check your config, where it says delay between actions, and walking speed?

Not anything to result in a ban. Like I said, I try to keep it human like.

> same prob~ could running 8+ hours nicely last night with 8.1,
but after the update it works a while then constant softbanned

Same

**Comment by r3n3gatu** [comment]
guys you need  to make some changes and  you well be fine   hire are my settings  and  no soft ban 
just use  your brain :)) i`m lvl 31  and work fine.
![1](https://cloud.githubusercontent.com/assets/20945362/17548372/8d02f4ce-5ee3-11e6-8b77-c692bf8018d1.jpg)
![2](https://cloud.githubusercontent.com/assets/20945362/17548373/8d039be0-5ee3-11e6-81d3-dc5443ce6ed3.jpg)
![3](https://cloud.githubusercontent.com/assets/20945362/17548374/8d0fa156-5ee3-11e6-83f1-aa332a8f9928.jpg)

**Comment by yonrin** [comment]
this is a shot in the dark, but may it have something to do with device id? like if you have several bots that use the same device id?

**Comment by TheMaskedMonkey** [comment]
Both of my bots do have same the same device id thinking about it.

Could it be possible that Niantic have started comparing GEOIP information to the coordinates it's given. Could somebody test this?

**Comment by yonrin** [comment]
Make a new thread about it maybe so devs see it quicker.

**Comment by TheMaskedMonkey** [comment]
Filtering Necrobot.exe through one of my USA boxes seems to have fixed it so far. No soft ban going through New York.

For now, to me, it looks like they're checking coordinates to geoip lookups.

**Comment by TheMaskedMonkey** [comment]
I spoke too soon. One bot hit the softban.

**Comment by yonrin** [comment]
Is it able to bypass the softban?

**Comment by yonrin** [comment]
It might be that they check the ip adresses and if you have more than one, it compares the GEOIP to cords. that or device id

**Comment by TheMaskedMonkey** [comment]
I think there's more to it. People are reporting bans with 1 bot.

**Comment by yonrin** [comment]
That may be it. Where you running with the default deviceid or did you change it?

**Comment by fdahms** [comment]
maybe interesting: one bot with sniping got banned. the one without sniping works fine....

**Comment by TheMaskedMonkey** [comment]
Went down to 0.8.1 as suggested by a friend and my bots are perfectly. All the servers I previously tried with are ip banned as expected but the bots are fine on new ips. I think it's fair to say the latest version is causing this.

**Comment by yonrin** [comment]
@TheMaskedMonkey well it is good that it is not something with the account and more because of the client.

**Comment by TheMaskedMonkey** [comment]
Wow, nevermind. Both just got banned, different device id's... wtaf.

**Comment by yonrin** [comment]
perm or soft?

**Comment by TheMaskedMonkey** [comment]
soft

**Comment by yonrin** [comment]
thats really weird

**Comment by yonrin** [comment]
Ohh wait so they had different device id's all the time?

**Comment by TheMaskedMonkey** [comment]
They didn't. I updated them to and they both got softbanned still.

**Comment by yonrin** [comment]
Ohh okay

**Comment by TheMaskedMonkey** [comment]
Changed my delay's to:

`  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,`

Will let you know of the results.

**Comment by ruchern** [comment]
@TheMaskedMonkey That is the default.

**Comment by yonrin** [comment]
Yeah that is what i use, what where those values before?

Emil Hansen

_____________________________

**Comment by TheMaskedMonkey** [comment]
I found the custom config I was using had it set to "1" - Very silly of me to not notice but I guess if it works, why fix it?

Update: Bots seem good so far.

**Comment by yonrin** [comment]
Hahaha yeah I think that was the problem. 1000 request per seconds is kinda a lot

Emil Hansen




On Wed, Aug 10, 2016 at 12:16 PM +0200, "TheMaskedMonkey" <notifications@github.com<mailto:notifications@github.com>> wrote:


I found the custom config I was using had it set to "1" - Very silly of me to not notice but I guess if it works, why fix it?

Update: Bots seem good so far.

-

**Comment by TheMaskedMonkey** [comment]
They must of started detecting it server side.

**Comment by TheMaskedMonkey** [comment]
25 minutes and not a single softban. From my end, I'm saying it's confirmed they're checking for delay now.

**Comment by ruchern** [comment]
How many instances are you running?

**Comment by TheMaskedMonkey** [comment]
Just two like usual.

**Comment by recon88** [comment]
Set FastSoftBanBypass to true
