### ISSUE TITLE
Please Add Properties: "MinIvPokemonToSnipe"

### ISSUE THREAD

**Issue by Hastle31** [NECROBOTIO/NecroBot#4411]
Hey. Please add function, thats Snipes only pokemon with (value) IV above!
For unknown pokemon IV should 1 try to catch. After this attempt bot see the IV value. If this value less then Properties: "MinIvPokemonToSnipe", that non need catching this pokemon.

**Comment by BSchwetzel** [comment]
#4331

**Comment by Linus9000** [comment]
#4331 should be the same
