### ISSUE TITLE
Sniping issue?

### ISSUE THREAD

**Issue by denniskai1234** [NECROBOTIO/NecroBot#4413]
Just gettings tons of these:

http://i.epvpimg.com/daVve.png

Im using this config:

http://pastebin.com/8M16P7Ut

Im running a Location Feeder on my PC, but for some reasons it dont use any informations from it and just does the shit you can see above in the screenshot.

Any ideas?

**Comment by DariusFoxy** [comment]
pokewatchers and pokezz is down. i dunno where that info is listed, but i've heard. try this config.

{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": false,
  "UseRareSpawns": true,
  "UsePokewatchers": false,
  "PokeSnipers2Exe": null,
  "RemoveAfter": 15,
  "ShowLimit": 30
}

**Comment by denniskai1234** [comment]
Im not sure if this helps? I mean it looks like it dosent even try to connect to the feeder?

**Comment by nfettinger** [comment]
mrmime versus mr_mime

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
