### ISSUE TITLE
OH DAMN! Blacklisted?

### ISSUE THREAD

**Issue by Zaryabb** [NECROBOTIO/NecroBot#4414]
So currently using a VPN and when i start up the bot it says "possibly blacklisted by NIANTIC, exiting...." So i guess Niantic is going hard on the ban wave to prevent botting.

**Comment by yonrin** [comment]
if you have inhuman delays between actions or unrealistic walking speed well thatst the problem i guess? been using a bot on my alt acc for 2 days now and is still running now

**Comment by alienxp03** [comment]
@yonrin Which version are you using?

**Comment by Zaryabb** [comment]
What is your config file set up as? I do have a low delay between my actions and stuff

**Comment by yonrin** [comment]
im using v 0.8.5

**Comment by yonrin** [comment]
i have 5000 between action and 2000 between catch

**Comment by Zaryabb** [comment]
UHOH.... even on my app on phone i cant see any pokemon or pokestops or gyms..... oh shit please dont be banned BEWARE PEOPLE.

**Comment by WishmasterNano** [comment]
Wait a couple hours and try again. Had the same with not seeing any stops -> no manual unban.  I started up the bot after 2 hours and it worked again

**Comment by Zaryabb** [comment]
@WishmasterNano thanks man will do!

**Comment by Nikolovo** [comment]
@Zaryabb you can just reconnect your internet to get a new ip

**Comment by yonrin** [comment]
Not if they ban your geoip but most likely they will never do that

Emil Hansen




On Wed, Aug 10, 2016 at 12:17 PM +0200, "Nikolovo" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Zaryabb<https://github.com/Zaryabb> you can just reconnect your internet to get a new ip

-

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
