### ISSUE TITLE
Recycling Ultra Balls and Great Balls

### ISSUE THREAD

**Issue by ScarletGod** [NECROBOTIO/NecroBot#4415]
Starting the bot for the first time gave me a real shock, my 200+ ultra balls got transferred away in an instant, I've searched for issue regarding this problem.  I haven't found the reason why this happened.[http://pastebin.com/eRv1CBwV](url) my config can be found here

**Comment by theloser** [comment]
Because you have more MasterBalls than UltraBalls? Whats your TotalAmountOfPokeballsToKeep and hwo many Balls do you have in TOTAL?

**Comment by ScarletGod** [comment]
I had 240+ ultra balls, 180 great balls. My total amount of pokeballs to keep was 50, are all balls generalized? oh god

**Comment by vapp13** [comment]
Yes they are. The bot will keep 50 of your best pokeballs

**Comment by ScarletGod** [comment]
Thanks everyone! I'll take my leave now in shame

**Comment by theloser** [comment]
If you had 240 UltraBalls and 180 GreatBalls, and told the bot to keep 50 Balls IN TOTAL, the bot would have recycled all your GreatBalls and 190 UltraBalls.

First of all: Read the Wiki! And second: Why did you changed the default value of 120 to 50 when you apparently don't know what this does?
