### ISSUE TITLE
Costant softban

### ISSUE THREAD

**Issue by arancio93** [NECROBOTIO/NecroBot#4417]
Hi. Since the update of the bot I got constantly softbans, before them (I ran all night long the bot) no problem at all.

I run 1 bot, sometimes 2. Is my conf bad or something else?

**Comment by vapp13** [comment]
Probably is just an IP Ban. Wait 30min and try again!

**Comment by arancio93** [comment]
I got it 2 hours ago, still same issue

**Comment by PeYouRoti** [comment]
Hi, I have the same maybe Niantic change their system of soft ban and it is not possible anymore to spun the pokstop to get unbanned because there is no pokestop detected. Sorry for my english.

**Comment by thedarkfalcon** [comment]
Try reducing **WalkingSpeedInKilometerPerHour**. The default of 31.0 is too fast, try something like _15.0_ instead. Also make sure you have **DisableHumanWalking** set to _false_.

**Comment by arancio93** [comment]
I usually used to have 20. Probably with the update it changed again. I will use 15 instead

**Comment by Trenars** [comment]
Not sure if this is helpful to anyone, but still decided to share my rules around botting...
 1. I am using bot on 3 accounts simultaneously on same PC (same IP)
 2. I am NOT using any proxy service
 3. I NEVER been soft banned
 4. I AM using VPN
 5. I AM very careful when I change the countries. I always check how long would it take me to drive/fly from one location to other in real life and I am NOT using bot/logging in game for that period of time.
 6. I AM trying to set my IP to the geo location of my bot (or as close as possible)
 7. I ALWAYS double check my config file before each launch (cords, speed, delays and so on)
 8. I rarely use sniping (have used it for 3 hours in about week time)
 9. Movement speed is never greater than 10 km/h and delay between actions is about 5000 ms
 10. If I stop the bot, I leave 15 to 30 min before I restart it
 11. I never log in the accounts from the phone while bot is running (If I want to log in on my phone, I ensure Location settings are set to GPS only and GPS is turned off). If I want to log in on my phone and have GPS on, rule Nr 5 applies. 
 12. I use bot for no longer than 14 hours/day.

Hope this helps :)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
