### ISSUE TITLE
0.8.5

### ISSUE THREAD

**Issue by Morge0RG** [NECROBOTIO/NecroBot#4418]
0.8.5 Can't use pokestops, infity trying

**Comment by Shadx00** [comment]
same .. :(

**Comment by andersluu** [comment]
same :(

**Comment by BamBoo87** [comment]
same here

**Comment by andreseveres** [comment]
same me too

**Comment by eksdi** [comment]
IP Soft ban. Try again after 20-30 minutes. Make sure to bot 1 account per IP.

**Comment by vapp13** [comment]
IP Ban!

**Comment by gapracoolz** [comment]
I Use 1 IP 1 Bot and use Snipe Pokezz.com...after several minutes i got softband IP.

**Comment by BamBoo87** [comment]
wow now 1 IP 1 bot only?? :(

**Comment by Shadx00** [comment]
i have just 1 ip and 1 bot , but ban ?

**Comment by hclivess** [comment]
got banned too

**Comment by bastacs** [comment]
im just try to use 2 id , 
1 ID - walking 55km/hours >> Banned
2nd ID - walking 10 km/hours >> Working 
T_T

**Comment by recon88** [comment]
Don't use more than one bot on one IP
