### ISSUE TITLE
Multiple configured on the VPN?

### ISSUE THREAD

**Issue by eru0921** [NECROBOTIO/NecroBot#4419]
To install the VPN in 1PC, we move the 5bot.
Is this would be pointless ?
VPN connection destination has been changed from uwsc.

**Comment by theloser** [comment]
Wait, what?

**Comment by theloser** [comment]
Run multiple virtual machines, each connected to a different VPN and use 1 bot per VM.

**Comment by eru0921** [comment]
@theloser 
Thank you very much. Can you move the how much BOT from 1VPN?

**Comment by theloser** [comment]
This is a config issue. Please go to [Discord](https://discord.gg/VXKxNFr) and ask for help.
