### ISSUE TITLE
config and login info gone after update to latest

### ISSUE THREAD

**Issue by funmix** [NECROBOTIO/NecroBot#4420]
Hi Guys,

New update causing the config and auth info is gone. It doesn't backup the old config and replace.

Others please take note, as the default config KeepMinDuplicatePokemon is set to 0, it will transfer all your duplicate Pokemon.

**Comment by Morge0RG** [comment]
4 line   "TransferConfigAndAuthOnUpdate": true,

**Comment by funmix** [comment]
Hi @Morge0RG this option always true.

**Comment by ruchern** [comment]
Save a backup on your own somewhere.
