### ISSUE TITLE
encrypt.dll

### ISSUE THREAD

**Issue by NunoAG** [NECROBOTIO/NecroBot#4421]
Can you remove this encrypt.dll.
It's causing a lot of issues regarding trend micro, including mine, since mine it's just a client.

Regards,
Nuno

**Comment by theloser** [comment]
Sure, remove encrypt.dll, because the bot don't need it anyways...

**Comment by NunoAG** [comment]
If it's not needed and it's causing a lot of issues, should be removed/fixed.
Otherwise this will happen.
![image](https://cloud.githubusercontent.com/assets/9094873/17549426/0589f7ea-5ee8-11e6-8995-7e034dcddeea.png)

**Comment by theloser** [comment]
I should tell you that I was making a joke! Geez...
You did not delete the file, didn't you?

**Comment by cawk** [comment]
check that the encrypt.dll is in the debug folder
or the resource folder

**Comment by NunoAG** [comment]
No, trend deleted it for me

**Comment by recon88** [comment]
Put it on your Anti Virus whitelist
