### ISSUE TITLE
Is it necessary to use a VPN?

### ISSUE THREAD

**Issue by Pilskopf** [NECROBOTIO/NecroBot#4422]
Hey guys got some questions. Since a day everyone is talking about IPs and using of VPN´s.
Is it really necessary to use a VPN? Does that cost something?
Acually im using my private IP without any softban probs.
Thanks for the help

**Comment by theloser** [comment]
If you only run one or two bots at the same time you probably don't need a VPN or proxy server.

**Comment by Nikolovo** [comment]
if you want to use more than one bots

**Comment by Pilskopf** [comment]
Im using just 1 Bot atm. So there would be no problem, am i right?

**Comment by theloser** [comment]
> If you only run one or two bots at the same time you probably don't need a VPN or proxy server.

**Comment by polypalm** [comment]
with 2 bots i got softban with 1 no

**Comment by theloser** [comment]
@polypalm Maybe Niantic reduced it down to one bot per IP, nobody knows...

**Comment by feroniameimei** [comment]
I got softban even i only used 1 bot. And so I used vpn, its working now.

**Comment by DamonSalvat0re** [comment]
which program of vpn u guys using?

**Comment by feroniameimei** [comment]
im using hotspot shield vpn elite
