### ISSUE TITLE
always softban 1,5 hour, banned permanent? not found pokestop 

### ISSUE THREAD

**Issue by daniel87kk** [NECROBOTIO/NecroBot#4423]
always softban 1,5 hour, banned permanent? not found pokestop 
please give me answer ??
me run 2 bot

**Comment by necr-0** [comment]
> me run 2 bot

Run 1.

**Comment by JakeCube** [comment]
> ;

**Comment by polypalm** [comment]
1 bot is working 2 got softbanns

**Comment by bastacs** [comment]
i have 10pc  but same ip is work ? for 1 pc = 1 id ?

**Comment by PeYouRoti** [comment]
Is it possible to use two bots but not at the same time without getting ban?

**Comment by necr-0** [comment]
@PeYouRoti,

Yeah, that'll work.

**Comment by theloser** [comment]
Multiple bots using the same IP at the same time will get you softbanned.

**Comment by buddiz87** [comment]
i think it should be banned once you run more than 1 bot for each IP

**Comment by PeYouRoti** [comment]
Ok thanks necr-0

**Comment by jasonisnear** [comment]
So others can't even play this through a public wifi like in a cafe together?

**Comment by necr-0** [comment]
@jasonisnear, 

They can.
The API and the app work differently. With the API, it's impossible. For the app, no.

**Comment by PeYouRoti** [comment]
Good question jasonisnear, i think Niantic make a difference between public and personnal network.
