### ISSUE TITLE
i wait for 1-2 hours and i open bot agai. STILL NO POKESTOPS[SOLVED]

### ISSUE THREAD

**Issue by dany4242** [NECROBOTIO/NecroBot#4426]
please? anyone can do something for me ????

**Comment by Adriskye** [comment]
try to change loc, it worked for me

**Comment by Demikakarott** [comment]
i tried to change the location but still no pokestops

**Comment by dany4242** [comment]
can u give me ur LOC ? information?

**Comment by Shin88ryu** [comment]
Restart your router or change your IP.
It works for me

**Comment by robbinwehl** [comment]
Same here: 
I played for days in area:  51.990955,  5.918444 
now it is showing: no usable pokemon stops

**Comment by dany4242** [comment]
i already restart my route, still same.

**Comment by feroniameimei** [comment]
change your ip address with proxy or vpn, it also works for me after i got sofban

**Comment by dany4242** [comment]
THE PROBLEM SOLVE ! thanks! i resetting my router

**Comment by dany4242** [comment]
just RESET ur Router. or go to CMD and write ipconfig/renew

**Comment by robbinwehl** [comment]
didn't solve the problem over here!

**Comment by dany4242** [comment]
@robbinwehl do this:

open CMD(Windows+R then write cmd then ENTER) then RESET ur ROUTER

**Comment by Stevecek** [comment]
It doesnt work :/, I have static IP adress, so I cant change it. What proxy or VPN will you recommend me please? :)

**Comment by Hastle31** [comment]
anybody knows, ip ban is temporaly or permantly?
