### ISSUE TITLE
Sniping Issue

### ISSUE THREAD

**Issue by electronproton** [NECROBOTIO/NecroBot#4428]
Hello,

Using 0.8.5 and only sniping from online services like pokezz, pokesniper, skiplagged. Somehow it doesn't sniping from manual sniping points located at PokemonToSnipe -> locations

The problem is those online services often yield "Did not find a pokemon within the location, pokemon despawned?"

Any idea why?

config: http://pastebin.com/YxeqJq62

Thanks before

**Comment by yonrin** [comment]
Most often it is because of unverified pokemon locations. Basically people sending out fake info.

**Comment by electronproton** [comment]
@yonrin even when I disable all those online services (pokezz, pokesniper, etc) it still doesn't snipe to my manual sniping points.

**Comment by yonrin** [comment]
when you do that do you turn   "UseSnipeLocationServer": false, to TRUE?

**Comment by electronproton** [comment]
Answered, turns out SnipeWithSkiplagged need to set to TRUE, don't know why..
