### ISSUE TITLE
i can't catch any pokemon even rattata on my phone ???

### ISSUE THREAD

**Issue by brightjoyy** [NECROBOTIO/NecroBot#4429]
Can anyone help me to solve this problem and cannot get anything from pokestop too... , When i catch it seem like i got it but it still run away

**Comment by radjesh** [comment]
Softban

**Comment by fanaticrulez** [comment]
u gotta reset your network in your setting

**Comment by brightjoyy** [comment]
i mean on my phone not in the necrobot

**Comment by brightjoyy** [comment]
do you guy be like this or not

**Comment by fanaticrulez** [comment]
was like that  then i reset all works fine after that

**Comment by theloser** [comment]
This is a known bug: re-install you phone (not just the app, but the iOS/Android as well). Sorry for any inconvenience!

**Comment by necr-0** [comment]
You've got yourself a softban.
Find your closest PokeStop and spin it, exit it, enter back into it and then spin it again. Repeat this process 45 times.

**Comment by brightjoyy** [comment]
omg 45 time dont need to get out from the range right just spin it exit it and spin it ?

**Comment by necr-0** [comment]
@brightjoyy,

Yep.
That being said, @theloser's method will work as well (I think).

**Comment by brightjoyy** [comment]
i got it thxxx
