### ISSUE TITLE
This sniped before. Not anymore...

### ISSUE THREAD

**Issue by fatchan** [NECROBOTIO/NecroBot#4430]
### Expected Behavior
-Snipe pokemon from 
"PokemonToSnipe": {
    "Locations": [

### Actual Behavior
Just goes to pokestops like normal, no sniping or notification of sniping.

### Your config.json
http://pastebin.com/zTAWawKX

### Steps to Reproduce
-use my config, run 0.8.5

### Other Information
Version: 0.8.5
Windows Version: 0.8.5
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): snipe

**Comment by necr-0** [comment]
Set _SnipeWithSkiplagged_ to _true_.

**Comment by wwwwwwzx** [comment]
Same here. Can not do pidgey farming anymore if we would like to snipe at some specific locations (with Skiplagged).
