### ISSUE TITLE
useless feature snipping other pokemon at specific location since v 0.8.2++

### ISSUE THREAD

**Issue by joeskyfrog** [NECROBOTIO/NecroBot#4431]
this code/algorithm on config.json become useless/broken after 0.8.2++ update..
ex:
"MinPokeballsToSnipe": 60
"PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      }
}

that location is like a nest farm (pidgey,caterpie,etc)
still work with 0.8.1
with 0.8.1 the bot still snipe pokemon at that location with count the pokeball to snipe first..
no more work after 0.8.2++ update..

anyone get this issue?

**Comment by fatchan** [comment]
Yep, same here we both reported at same time, haha 

https://github.com/NECROBOTIO/NecroBot/issues/4430

**Comment by necr-0** [comment]
Set _SnipeWithSkiplagged_ to _true_.

**Comment by stanleyhafeld** [comment]
"Set SnipeWithSkiplagged to true." not working for me..

**Comment by joeskyfrog** [comment]
haha no more fast exp while snipping rare pokemon
@necro-0 that isn't the problem dude..

**Comment by fatchan** [comment]
@necr-0 
It works, but I never used skiplagged before, unless it was using it by default and didn't have an option.

**Comment by necr-0** [comment]
@joeskyfrog,

Is the issue that your bot is sniping Pokemon at the preset locations? If so, then you need to make that setting true. 

See this: https://github.com/NECROBOTIO/NecroBot/issues/4363

**Comment by Gandaflux** [comment]
reported same problem already

#4403

**Comment by joeskyfrog** [comment]
@necr-0 still not working after change the config "SnipeWithSkiplagged": true or the other pokezz, pokesnipers,pokewatcher set to false/true.. i already try the all config lol.. im on 0.8.5 version

**Comment by Gandaflux** [comment]
@joeskyfrog downgrade to 0.8.1 version and it will work again.

**Comment by Aeohard** [comment]
Same problem #4393

No one can solve this problem..

**Comment by joeskyfrog** [comment]
@Gandaflux yeah.. that's the only way i think too.. i hope the dev read this issue and will fix it later with the new version

**Comment by jjskuld** [comment]
Ok, I looked at the code to see what's going on. Apparently the setting to set is called ```GetSniperInfoFromSkiplagged```.  and NOT ```SnipeWithSkiplagged```.   ```SnipeWithSkiplagged``` appears in the configuration file, but is NEVER used in the code.

**Comment by georgi-huklev** [comment]
no this was changed after 8.5.0 release
At 8.5.0 tag is SnipeWithSkiplagged:
https://github.com/NECROBOTIO/NecroBot/blob/v0.8.5/PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs#L327

**Comment by Wcidd** [comment]
Please use the given template for opening issues so we can gather enough information to resolve issues
