### ISSUE TITLE
Hire are the Good Settings  no ban/softban    

### ISSUE THREAD

**Issue by r3n3gatu** [NECROBOTIO/NecroBot#4432]
You have to make changes hire ( i`m lvl 32 sow for my this settings are Exccelent bot  for lower lvl you have  to go down a looot ( go down everyware were sey MinCP , Minlv , balls ))
You have to assume now high CP Pokemon your lvl can cath :

 "WalkingSpeedInKilometerPerHour": 10.0  very important

  "UseBerriesMinCp": 800,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 6.2,    depending your lvl

  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 10,
  "TotalAmountOfRevivesToKeep": 10,
  "TotalAmountOfBerriesToKeep": 150,
  "UseGreatBallAboveCp": 680,
  "UseUltraBallAboveCp": 1100,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 6.2,
  "UseUltraBallBelowCatchProbability": 6.1,
  "UseMasterBallBelowCatchProbability": 6.05,
  "EnableHumanizedThrows": true,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 20,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 800,
  "ForceExcellentThrowOverCp": 900,   depending your lvl

**Comment by bastacs** [comment]
thats normal config, actually we need config/bot for multiclient working :D

**Comment by PokemasterMike** [comment]
all that matters are the delays...
start with 5000/5000 and adjust accordingly
