### ISSUE TITLE
Add a config to keep strongest one of every pokemon.

### ISSUE THREAD

**Issue by HunkDivine** [NECROBOTIO/NecroBot#4433]
like KeepOneOfAll = true

it would transfer all pokemon of this variant keeping the strongest only back. If new one is caught, checks if its stronger then keeps it otherwise transfers it.

Bypasses CP, IV and level checks otherwise.

**Comment by Profetorum** [comment]
What do you mean with "strongest"?

**Comment by necr-0** [comment]
Exactly what @Profetorum said.
What is your definition of "strongest"? For some, IV means the strongest. For others, CP. Options exist for both parties already.

**Comment by Fazy5** [comment]
keep min duplicate pokemon = 1
keep min cp = 5000
keep min level = 50
use keep min level = true
keep min iv = 100.0
keep min operator = "and"

Set these and it will only keep the strongest you catch.. no need to add what you are asking for. Kindly close the issue

**Comment by HunkDivine** [comment]
what i wanted to say was like : i have 10 pidgeys, right now it will transfer all of them if they are below the  CP IV lvl threshold. the new config should keep only one of these (from lets say CP comparision) even if it doesnt satisfy the global parameter.

but i guess even this works.
