### ISSUE TITLE
Mistake in the IV calculation?

### ISSUE THREAD

**Issue by poketeiger73** [NECROBOTIO/NecroBot#4434]
When this is the IV formula: ATK+STA+DEF/45*100.
![image](https://cloud.githubusercontent.com/assets/20941094/17549160/45d61f34-5eef-11e6-909b-569c35ebf3e3.png)
How is this possible?

The data are form my dump file. Is ther probably a mistake in the calculation?

**Comment by spamfighter82** [comment]
```
        public static double CalculatePokemonPerfection(PokemonData poke)
        {
            if (Math.Abs(poke.CpMultiplier + poke.AdditionalCpMultiplier) <= 0)
                return (poke.IndividualAttack + poke.IndividualDefense + poke.IndividualStamina)/45.0*100.0;

            //GetBaseStats(poke.PokemonId);
            var maxCp = CalculateMaxCpMultiplier(poke.PokemonId);
            var minCp = CalculateMinCpMultiplier(poke);
            var curCp = CalculateCpMultiplier(poke);

            return (curCp - minCp)/(maxCp - minCp)*100.0;
}
```

Dont ask my why they do that

**Comment by PokemasterMike** [comment]
probably not, if you want to double check use:
https://pokeassistant.com/main/ivcalculator

**Comment by BobbyWibowo** [comment]
God knows why they use that formula to calculate the perfection. Even Poke Assistant, the one @PokemasterMike linked, appears to be using `ATK+STA+DEF/45*100`.

**Comment by BobbyWibowo** [comment]
What does this part do?
```
if (Math.Abs(poke.CpMultiplier + poke.AdditionalCpMultiplier) <= 0)
```
It seems to be only returning the weird calculation below when it's false. Unfortunately it seemed to return the second calculation on most of my dumps.
