### ISSUE TITLE
It said no pokestop nearby.How can I solve this?

### ISSUE THREAD

**Issue by sarah1598** [NECROBOTIO/NecroBot#4435]
It said no pokestop nearby.How can I solve this?

Plz some one can help me what can I do this.

**Comment by WishmasterNano** [comment]
try changing your start location to a crowded spot, if it still occurs you are probably softbanned. Wait a couple hours and try again. Make sure you only use one bot per IP and have human speeds configurated.

**Comment by nekochan23** [comment]
turn off  your bot and wait for 10 minutes before starting up again.
you got softban.

**Comment by feroniameimei** [comment]
or you can change your ip address with vpn or proxy, should be worked.

**Comment by Korni1987** [comment]
only one bot?this is big shit

**Comment by DamonSalvat0re** [comment]
i tried using the vpn u said but my browser stopped working instead. xD

**Comment by jinkawasaki333** [comment]
Wow.. So it was 2 yesterday, and it got down to 1 now?
