### ISSUE TITLE
Upgrades not shown in console anymore

### ISSUE THREAD

**Issue by Linus9000** [NECROBOTIO/NecroBot#4436]
My Pokemon are upgraded automatically (which I can see in the logfiles), but there isn't an indication for it in the console anymore. I don't know if this only affects the german translation.

**Comment by terrenzio** [comment]
The #4447 is different

**Comment by Linus9000** [comment]
Update: English version is also affected, so seems to be a general problem..

**Comment by DBa2016** [comment]
Fixed by #4508

**Comment by cawk** [comment]
This was fixed earlier
