### ISSUE TITLE
0.8.5 is ignoring "KeepPokemonsThatCanEvolve": true

### ISSUE THREAD

**Issue by JustRegisteredToSayThis** [NECROBOTIO/NecroBot#4440]
Before upgrading I needed 7 more pokemon to start evolving, numbers and candies matched up. Now when I run the bot it starts transferring all of my pidgeys.
I have confirmed my config wasn't reset to default.

Config:
http://pastebin.com/XN78gZf5

**Comment by sackthesack** [comment]
You can add your "PokemonsToEvolve" list to the "PokemonsNotToTransfer".

**Comment by JustRegisteredToSayThis** [comment]
Yeah thanks that's a good stopgap fix but it should still be addressed because the normal logic should behave differently. It should transfer those pokemon that exceed your candy limit so you're able to evolve more when your inventory fills up.
It fills quite fast if you set those super commons to not transfer.

**Comment by nfettinger** [comment]
This is a duplicate issue.
