### ISSUE TITLE
Amazing - What is Sniping?

### ISSUE THREAD

**Issue by ChickenChive** [NECROBOTIO/NecroBot#4442]
Amazing work done in just one day.

Really good experience of getting help on forum too.

Quick question,

What is Sniping?

**Comment by BobbyWibowo** [comment]
These pages on the Wiki has some explanations:
https://github.com/NECROBOTIO/NecroBot/wiki/Config#sniping
https://github.com/NECROBOTIO/NecroBot/wiki/Sniping-Setup
