### ISSUE TITLE
Pokemon Despawned?

### ISSUE THREAD

**Issue by tristin13453** [NECROBOTIO/NecroBot#4443]
When I try sniping, it scans and thinks it has despawned? Please help me or provide me with a working config :)

Config: http://pastebin.com/yRZ8xuL0

**Comment by BobbyWibowo** [comment]
Ever thought that maybe the Pokemon was never in that coordinate to begin with or that it had indeed actually despawned?

**Comment by yonrin** [comment]
Seems like you are using manual sniping. Turn   "UseSnipeLocationServer": false, to TRUE and download pogolocationfeeder and turn that on, then the bot. Should work. 

https://github.com/5andr0/PogoLocationFeeder/releases/tag/v0.1.6

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
