### ISSUE TITLE
auto generate proxy

### ISSUE THREAD

**Issue by jhebkv** [NECROBOTIO/NecroBot#4444]
based on ahk i made this, is it possible to attach on the bot?
proxy:
gui,submit,nohide
urldownloadtofile,http://gimmeproxy.com/api/getProxy,proxy.json
sleep, 100
lastproxcount:=0
fileread,proxy,proxy.json
stringreplace,proxy,proxy,`",,all
stringsplit,value,proxy,`,,all
loop %value0%
{
	stringsplit,ip,% value%a_index%, `:,all
	loop %ip0%
	{
		if (ip1=="ip")
		{
			if ((ip2==proxyIP) && (lastproxcount==2))
			{
				if !hide
				msgbox,64,Error,Same proxy detected`nplease wait,5
				gosub, proxy
				break
			}
			lastproxcount:=lastproxcount+1
			proxyIP:=ip2
		}
		if (ip1=="port")
		{
			proxyPort:=ip2
			break
		}
		sleep, 100
	}
	sleep, 100
}
return

----
fileappend,
	(
	{
	"AuthType": "%aut%",
	"GoogleUsername": "%na%",
	"GooglePassword": "%pw%",
	"UseProxy": true,
	"UseProxyHost": "%proxyIP%",
	"UseProxyPort": "%proxyPort%",
	"UseProxyAuthentication": true
}
	),%nauthjson%

**Comment by nfettinger** [comment]
Defaulting people to the same IPs does nothing except get everyone banned.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
