### ISSUE TITLE
0.8.5 does not transfer config file during auto update

### ISSUE THREAD

**Issue by averes2** [NECROBOTIO/NecroBot#4445]
Autoupdate created a new config file resetting defaults to new.

Auth.json was also reset but I figure thats not a bug

**Comment by pixerx** [comment]
i got > User credentials are invalid and login failed.
Can someone explain this again why?

**Comment by Ferdy2003** [comment]
+1

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
