### ISSUE TITLE
ADD random delay to actions

### ISSUE THREAD

**Issue by SYNurg** [NECROBOTIO/NecroBot#4446]
Would it be possible to add random delay to action?

Currently the delay is hard set

"DelayBetweenPlayerActions": 5000,

Would it be possible to add a bit of randomness to this delay ?

(Not a dev but i was thinking something like this?)

"MaxDelayBetweenPlayerActions": 10000
"MinDelayBetweenPlayerActions": 5000,

int DelayBetweenPlayerActions = rnd.Next(5000,10000);

Thanks for your hard work.

**Comment by ThomasSRL** [comment]
Tbh I prefer 1 setting in the config, but just go: 
wait(round(randomRange(settingValue, 1.5 * settingvalue)));

**Comment by nfettinger** [comment]
Duplicate issue
