### ISSUE TITLE
Version 0.85 is broken

### ISSUE THREAD

**Issue by smoothrunnings** [NECROBOTIO/NecroBot#4448]
I copied over my conf files to the new release and started it, All I see is "Is your maximum distance too small?" 

So I started over scratch, I nuked the release folder and unziped the one from 0.85, then I ran the exe again. When it asks me put the Long and Lat info in the install refuses to allow me to right click into the window adding the coordinates. 

I am not sure if I need to show you my config since it won't allow work on a new install. I am using coordinates that my last install was using.

**Comment by kknoell** [comment]
same with me

**Comment by hijackerz** [comment]
My bot is working , but really , really SLOW !

**Comment by KauKauHat** [comment]
ame hear very slow

**Comment by XHusHX** [comment]
same with me

**Comment by repelsteeltjehd** [comment]
it's just removing all pokemon and that's about it xD

**Comment by smoothrunnings** [comment]
I just manually entered in the coordinates on my Japan bot which I verified and its doing the same thing. I think we'll see a version 0.86 soon!! I hope.

**Comment by kurozani** [comment]
uhm, mine is fine

the delay is 5000 and 2000 this time which indeed will make it slower

**Comment by hijackerz** [comment]
well yeah , it removed my best pokemon -.-' and its slow , and sniping dont works anymore xD

**Comment by hijackerz** [comment]
@kurozani can you link your config ?

**Comment by smoothrunnings** [comment]
It looks like reading through the threads from last night that people are saying that in this case what we are seeing is a soft IP ban. So I am going to stop for a hour or so and see if it changes.

**Comment by clownnut** [comment]
works for 5 mins then goes into "no usable poke stops found in your area. is your maximum distance too small?" error. same setting/location/ as before.

**Comment by Rabelaiss** [comment]
Working fine for me

**Comment by clownnut** [comment]
i might have been ip ban. anyone know is that perm or temp?

**Comment by smoothrunnings** [comment]
I know when I log in I don't see any pokemon stops. So lets hope it's just a temp ban. lol

**Comment by clownnut** [comment]
others said, might be 1-6hrs ban. we will see. running 2 bots at the same time, that's how i got the ip ban.
