### ISSUE TITLE
Sniping, how does it work???

### ISSUE THREAD

**Issue by ASKcoTM** [NECROBOTIO/NecroBot#4449]
how do you snipe or does this automatically snipe.
i understand the concept but i rarely find exceedingly rare Pokemon with the bot.

so how do i set it to find better ones of possible

**Comment by WishmasterNano** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki/Sniping-Setup

**Comment by ASKcoTM** [comment]
cheers
