### ISSUE TITLE
Keep Getting softban

### ISSUE THREAD

**Issue by Zandrick** [NECROBOTIO/NecroBot#4450]
"WalkingSpeedInKilometerPerHour": 18.0,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 100

"FastSoftBanBypass": this have to turn to true?

**Comment by ASKcoTM** [comment]
when i use softban bypass, i get softbans alot but it gets rid of them quickly. i also have human walking set 'false' so i'm not sure if it will help

**Comment by WishmasterNano** [comment]
your delays are way too low, try the default: actions 5000 and catch: 2000

**Comment by Zandrick** [comment]
@WishmasterNano Ok thanks

**Comment by ruchern** [comment]
100 = 100ms which is literally not realistic human reaction time at all.

Set higher.
