### ISSUE TITLE
NO POKESTOP FOUND AGAIN

### ISSUE THREAD

**Issue by XHusHX** [NECROBOTIO/NecroBot#4451]
why happened again?

**Comment by andreseveres** [comment]
me too.. what happen with necrobot 8.5 ?

**Comment by XHusHX** [comment]
the previous version is working good but this version is disappointed

**Comment by MrPK2710** [comment]
me too man.. w tf

**Comment by Chanawutzz** [comment]
me too

**Comment by WishmasterNano** [comment]
probably softbanned. make sure you are using only one bot per IP and have human config.
Try again after 1-2 hours

**Comment by robbinwehl** [comment]
This is probably not a softban as i have the same issue. 
I closed the bot and opened pokemon go on bluestacks, now i am able to get items from pokestops. 
So this issue is deffently in the bot.

**Comment by juantamadz** [comment]
my bot works again after i re-download the bot and input my basic account info and i used only default location and it works . i tried other suggestion from other thread but no luck

**Comment by XHusHX** [comment]
maybe the API was changed again

**Comment by robbinwehl** [comment]
additional info:

I already tested:

0.77
0.78
0.78 with config of 0.77
0.8
0.85 

all same but on bluestacks pokestops are working like a charm.

**Comment by tsenjc** [comment]
work with reduce speed

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by tsenjc** [comment]
i change the walking speed to 10 and it work for few hours

**Comment by tsenjc** [comment]
"WalkingSpeedInKilometerPerHour": 10.0,
