### ISSUE TITLE
Ball/Berry/Potion data not being shown in console anymore

### ISSUE THREAD

**Issue by rahulrverma** [NECROBOTIO/NecroBot#4454]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Ball/Berry/Potion numbers being shown in console

### Actual Behavior
Ball/Berry/Potion numbers not being shown in console anymore with v 0.8.5

**Comment by rahulrverma** [comment]
Please close. Shows randomly now.
![image](https://cloud.githubusercontent.com/assets/20796347/17549918/3d68e266-5f10-11e6-8c34-dd07fd43c8cf.png)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
