### ISSUE TITLE
Ignore logic, fix or remove

### ISSUE THREAD

**Issue by Leigha888** [NECROBOTIO/NecroBot#4455]
### Expected Behavior
Ignore pokemon section to ignore XXX pokemon you list.

### Actual Behavior
Ignores nothing.

### Your config.json
Trust me, its set up right.

### Steps to Reproduce
Just put anything in your ignore section, and the bot will not ignore it.

### Other Information
Version: This happens for a long time, just deciding to post about it.

What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
Config/ignore

**Comment by dr4bca** [comment]
Are you sure it's set up right? I used "PokemonsToIgnore" for some time and it always worked..
Maybe you forgot to switch "UsePokemonToNotCatchFilter" to true?

**Comment by JustRegisteredToSayThis** [comment]
I've been using this function successfully for quite some time. In fact I'm watching it right now

> [12:24:03] (INFO) Skipped Staryu
> [12:24:03] (INFO) Skipped Weedle
> [12:24:09] (INFO) Skipped Staryu

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
