### ISSUE TITLE
Permanent ban and bot/IP

### ISSUE THREAD

**Issue by charlieswb** [NECROBOTIO/NecroBot#4456]
I've seen someone in the chat said that at certain amount of softban, niantic will permanently ban you.
Is this true?
and
What is the safe amount of bot per IP now? Is 2 still ok?

PS. I have 3 instances VM up with 2 bot each. 2 of them've got IP banned, 1 haven't.

**Comment by ASKcoTM** [comment]
ive had more than 15 softbans at least, you should be alright

**Comment by kauegimenes** [comment]
How you guys know how many softbans? there is any log for that?

**Comment by jasonisnear** [comment]
Better just one. I was using two last night and got banned. Someone report they ran one bot and still got banned

**Comment by feedbuck** [comment]
i have like 30 softabans

**Comment by DBa2016** [comment]
Running multiple PoGo clients from the same IP does not necessarily get you bans - my wife and myself have our cellphones on the same IP when we are at home, and a weekend visitor was on the same IP, too, without any issues.
Reduce your walking speed and you'll be fine.

**Comment by theloser** [comment]
> I have 3 instances VM up with 2 bot each

@charlieswb Are those VMs connected to different VPNs? If not, go to [this site](http://www.whatsmyipaddress.net/) from within every VM and check the IP address -- it will always be the same, right?

**Comment by theloser** [comment]
@DBa2016 I think Niantic changed its softban mechanics on monday, so it could have worked last weekend. Also because Niantic will never tell how softbans work, we can only guess what's causing softbans. And because for most of us 1-2 bots work fine, we are assuming more than two bots will get you banned.

**Comment by charlieswb** [comment]
@theloser You're right. Thanks a lot.
Now I change each VM to difference IP and it works fine.
