### ISSUE TITLE
Can't remove softban with VPN

### ISSUE THREAD

**Issue by Fremder** [NECROBOTIO/NecroBot#4459]
Why i cant remove any Softban with a VPN using hide.me VPN

**Comment by Profetorum** [comment]
Same, using hide.me. 
Probably it's blacklisted

**Comment by Fremder** [comment]
Does anyone got a VPN up for Sharing would be kind

**Comment by feroniameimei** [comment]
i'm using hotspot shield vpn, mine is working fine

**Comment by cawk** [comment]
with vpn's alot of people are using them for the same reason so they get banned 
either purchase proxies or used ones that are not used alot

**Comment by DamonSalvat0re** [comment]
how do u use the hotspot shield vpn?

**Comment by theloser** [comment]
Please close this issue ang go to the discord channels to get help. Thanks.

**Comment by feroniameimei** [comment]
just download and install it

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
