### ISSUE TITLE
config provided sniping locations keep getting moved around under other settings

### ISSUE THREAD

**Issue by TankTheFrank** [NECROBOTIO/NecroBot#4461]
In 0.8.1 they are under session.LogicSettings.UseSnipeLocationServer false.

In 0.8.5 they moved further down under if (session.LogicSettings.GetSniperInfoFromSkiplagged)

Why should these (completely random for each version) additional settings have to be enabled/disabled to use a list of snipping locations in the config file?

**Comment by joeskyfrog** [comment]
yeah same issue #4431

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by TankTheFrank** [comment]
this IS about where it is in the source code - specifically various if/else branches in PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
