### ISSUE TITLE
Here is a fix for Bot and feeder

### ISSUE THREAD

**Issue by hijackerz** [NECROBOTIO/NecroBot#4462]
Use this config  on necro :) 

http://pastebin.com/xEQmFwQn

**Comment by hackinger1** [comment]
?

**Comment by WishmasterNano** [comment]
what is it fixing?

**Comment by robbinwehl** [comment]
This is not fixing anything. 
KM/h is set to 50

**Comment by Fremder** [comment]
It's 8.4 Config guys look the TAB's Name

**Comment by hijackerz** [comment]
Well , many had problems with pogo feeder and the bot run slowly :)

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
