### ISSUE TITLE
Why did my Config Transfer system get removed? 

### ISSUE THREAD

**Issue by Andrerm124** [NECROBOTIO/NecroBot#4464]
So I've just seen from all the issues that people's configs aren't being transferred which has probably caused a lot of pokemon to be crushed. 

I've taken a look at the code and for some reason the code I implemented to do this has been removed (#2728 Program.cs lines 59-65)

If this was a mistake I will reimplement it (On my phone right now), otherwise, could I get a reason? 

Commit that removed this code: #4380 
Missing code:

```
if( File.Exists( configFile ) )
 +            {
 +                if( !VersionCheckState.IsLatest() )
 +                    settings = GlobalSettings.Load( subPath, true );
 +                else
 +                    settings = GlobalSettings.Load( subPath );
 +            }

```

**Comment by theloser** [comment]
I can't find any commit which removed those lines -- did you find it?

**Comment by kentsang77** [comment]
Are you talking about the issue that makes many people's pokemons are being transferred ?

If so, I hope you really can fix it this time. Many issues report about it but marked as closed and being ignored. Many people's pokemons are transferred unexpectedly. Starting from version 0.6.x to latest 0.8.5.

**Comment by theloser** [comment]
@kentsang77 Did you even READ what he said?

> issues that people's configs aren't being transferred

**Comment by kentsang77** [comment]
@theloser

if the config didn't properly transfer during upgrade, some parameters may be reset.

The KeepMinDuplicatePokemon may be override as default which is ZERO. It may cause the pokemon transfer unexpectedly if user did set NON-ZERO before upgrade.

Sorry if it is not related to the issue.

**Comment by Andrerm124** [comment]
@kentsang77 You're right that would be a side effect. 

I managed to find the commit that removed it: #4380

**Comment by theloser** [comment]
> if the config didn't properly transfer during upgrade, some parameters may be reset.

I see. Sorry @kentsang77 for being rude!

**Comment by kentsang77** [comment]
@theloser 
no worries, addoil and thanks

**Comment by nfettinger** [comment]
@theloser Please be respectful in these issues. I know you are trying to help, but please keep it professional.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by theloser** [comment]
@nfettinger (Offtopic) This actually is one of the more polite answers from me, I did even appologize for being rude :-)
