### ISSUE TITLE
Necro wont start

### ISSUE THREAD

**Issue by nukesub** [NECROBOTIO/NecroBot#4466]
As soon as i click on necrobot.exe this happens ,can anyone help?
![11111](https://cloud.githubusercontent.com/assets/20946730/17550401/1620d35a-5ef5-11e6-9782-3e860837fd37.jpg)

**Comment by TheseusKingz** [comment]
probly a edit config is out. wot was your last config change . a had same thing with a bad input for ekans in evolve list . but looking at this i cant pick out wot line or config change it was . best  bet retrace your edits or swap out the config.jason for a new one an reedit

**Comment by nukesub** [comment]
i deleted everything and redownloded , this is what happening now! its not askig me to log in for the first time or anything, this just happens and thats it!

**Comment by thedarkfalcon** [comment]
Is the stack trace being written into the logs? That would be helpful to try and diagnose the problem.

**Comment by nukesub** [comment]
Files that help describe the problem:
  C:\Users\Fluid Space\AppData\Local\Temp\WERD104.tmp.WERInternalMetadata.xml
  C:\Users\Fluid Space\AppData\Local\Temp\WERA63E.tmp.appcompat.txt
  C:\Users\Fluid Space\AppData\Local\Temp\WERA67D.tmp.mdmp

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt



![32543](https://cloud.githubusercontent.com/assets/20946730/17552143/635d2c50-5efe-11e6-9e11-4e717803bf0a.jpg)

**Comment by thedarkfalcon** [comment]
I was actually referring to the necro log files, they can be found in _Release\Logs\NecroBot<timestamp>.txt_

**Comment by nukesub** [comment]
i paste that here is it again everthying...

Initializing NecroBot logger at time 8/10/2016 1:37:19 PM...
[13:37:19] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/10/2016 1:38:06 PM...
[13:38:06] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/10/2016 1:39:50 PM...
[13:39:50] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/10/2016 1:39:53 PM...
[13:39:53] Exception caught, writing LogBuffer.

**Comment by thedarkfalcon** [comment]
Seems like a its a windows or .NET issue. [Try do a clean boot and see if that fixes the issue.](https://support.microsoft.com/en-us/kb/929135)
What version of necro is this happening for? Is it new behaviour or has necro previously work for you?

**Comment by Exorsist2005** [comment]
i have a same problem. Win10 Home 32 bit, .net framework 4.6.2. Just try necrobot on win7 machine and everything works fine

**Comment by nfettinger** [comment]
This is a platform issue, probably to do with your antivirus.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
