### ISSUE TITLE
No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by markemonb** [NECROBOTIO/NecroBot#4467]
Never had this issue before. 
I am sure my location is correct and there are enough pokestops with in the radius
Is this a kind of ban or am i doing something wrong? I just updated necrobot a few hours ago.

**Comment by robbinwehl** [comment]
This is occuring on all versions (tested from 0.7 to 0.85)

**Comment by brightjoyy** [comment]
you  have to reset your rounter

**Comment by juantamadz** [comment]
just download the bot and input basic info and use default setting. try it

**Comment by jump-ocz** [comment]
pls don't open a bot more than one
it ip softban

**Comment by Plotin** [comment]
Just redownloaded, reset all config (let the bot create a new one), set default location to the town center and still get the no pokestops error.
Same bot account works with another bot-software, so it is no account problem

**Comment by jump-ocz** [comment]
for safety it only 1 
1bot 1ip

**Comment by exodia6666** [comment]
how long usually to recover from ip ban?

**Comment by robbinwehl** [comment]
Try to change your gps to another country /  far away from your current location... this is the only way i can get it working for now.
but this is not what you want.  ( i know this will give you a softban but this will work probably)

**Comment by feroniameimei** [comment]
or you can use vpn/proxy to change your ip address, mine is working fine.

**Comment by markemonb** [comment]
Redownloaded last version, kept original settings, still same error
I resetted router, but my ISP does not give me new IP
How long does an IP ban normaly take?

**Comment by feroniameimei** [comment]
i got IP ban too. try redownload the bot, before use the bot, change your ip address with vpn or proxy. im using hotspot shield vpn elite, already few hours still working fine.

**Comment by ANR2ME** [comment]
I keep getting softban IP after a few minutes since i changed my IP :( anyone know whats triggering this softban? i only have 1 bot running

**Comment by XHusHX** [comment]
fuck IP softban

**Comment by Jojoushi81** [comment]
change ur IP with resetting ur modem.. and check ur config...

**Comment by smoothrunnings** [comment]
Try waiting an hour or so.

**Comment by Proetheus** [comment]
It's problem of bot. We checked with different bots and several Ips. Everytime when Necrobot starting IP banned.

**Comment by JinchengShi** [comment]
It seems that Niantic has noticed us

**Comment by smoothrunnings** [comment]
@Protheus Others are reporting v0.85 is working fine for them. It's an IP ban. I checked with my Bluestacks going out through the same connection I am soft banned on and I don't see any poke stops but when I switch to a different network everything is fine.

**Comment by luiztomz** [comment]
bot more than 1 ID, will be softban 1 hour

**Comment by smoothrunnings** [comment]
They are picking up on multiple bots different ID's 1 IP. I had two bots going, one on a google account and other other a PTC account.

**Comment by Littlem0nk3y** [comment]
So, from 2 bots / computer, now it should be 1 bot / computer?

**Comment by trinitybest** [comment]
Hey guys, I used another computer, whose IP is different from the last one (a VM). Now it's fully working. I will recommend anyone, whose bot is not working, to create another VM. VM could be created using AWS or Azure by the way. :)

**Comment by markemonb** [comment]
I tried VPN software to change my IP, same error

**Comment by thedarkfalcon** [comment]
I think you are being banned because the (new?) default walk speed is too fast. I was constantly getting soft bans and "No PokeStops Found" in your area. Try reducing walk speed to something more reasonable (10-20km/h).

**Comment by JinchengShi** [comment]
my friend is using the 0.8.1 version, and it works well, maybe you should try

**Comment by coolio818** [comment]
Download a VPN, worked for me :)

**Comment by Painkiller1985** [comment]
Hey guys, first post and new to bots but a friend introduced me to necro yesterday, and started playing with it today, 2 bots on an ip gets me IP banned, and later on 1 solo bot got itself banned after 10-15 minutes i believe (rough guess as was afk for half hour at work)

its definately IP banned as some above have stated, bot wont work on any accounts i have access to on this terminal, and when i login with my phone there are no pokestops, gyms or pokemon on any accounts, unless i use my 4g instead of wifi!

ive tried one or 2 vpn/ip changers, and none seem to work, only one that changed my IP stopped me connecting to the internet entirely! can anyone suggest a good vpn if theyve had it working, such as coolio818's?

To clarify, i ran a fresh player with default config and it still got me ip banned after about an hour or so wait to be unbanned, and without running pogo feeder to snipe or any such app

**Comment by smoothrunnings** [comment]
@Painkiller1985 You can only have 1 ID for 1 IP. If you add more ID's to 1 IP the servers will soft ban you.

**Comment by Painkiller1985** [comment]
Ah ok, is this past day or 2 apu update? I've seen other topics about no pokestops where they've stated only 2 per ip, I can live with one, just identifying my new limitations :)

**Comment by smoothrunnings** [comment]
@Painkiller1985 Yeap I know, I was doing 2 ID, 1 IP last night too. But this morning once I noticed the soft ban I let the dust settle, then started my first bot making sure it was going then started my second bot, and within 30 minutes my IP was soft banned again. I stopped and waited and started only one and it's been running for an hour or so without any issues.

**Comment by Painkiller1985** [comment]
I let the dust settle for a while and let one run as mentioned above, but it still banned me after 15 or so minutes on a new account, so maybe they're blacklisting ip's to check up on after the ban gets lifted?

**Comment by smoothrunnings** [comment]
@Painkiller1985 Give it a reset for about an hour or two. Sorry I don't know how long it took as I left it alone at 7AM this morning, and checked it again at 9AM (I was on the road going to work).

**Comment by Painkiller1985** [comment]
I was considering the same thing tbh, but definately leaving it as 1 per IP, thought i'd report what i had found though

**Comment by monaheezy** [comment]
Cyberghost

**Comment by kodokngorek1** [comment]
just reset router it work for me

**Comment by Painkiller1985** [comment]
Thanks @monaheezy, will give that a try
@kodokngorek1 sadly that's not an option at work ;) but some ip's don't provide a new ip when you do a reset, unsure if mine is one at home but I'm a 1 bot guy now lol

**Comment by monaheezy** [comment]
Yeah I have the same softban issue. I was running a buddies bot for him on the same computer while he's away at a cottage for the week.

**Comment by Painkiller1985** [comment]
Any official word from the necro devs about what niantec have done? We can guess and deduce they've throttled connection requests and active links etc but my assumptions aren't a speck o nxt their educated deductions and discoveries lol

**Comment by smoothrunnings** [comment]
@kodokngorek1 In most North American cities the ISP's set their DHCP servers to an infinite amount of time for their IP leases. So rebooting the router doesn't get you a new IP address. The only way people can do this is to assign a different MAC Address to their WAN port on their router, this can be painful as it may mean they need to power down the modem for a couple of minutes, make the change on the router and power up the modem again and hope the modem isn't locked into the old IP, If it is then you need to power the modem down for a longer period of time.

**Comment by Jamby93** [comment]
How is botting with two bots any different of having two real mobile phones connected to the same Wifi network?
Has anyone tried to connect two real phone to the same network and see if they get soft-banned too?
I think it's impossible that Niantics bans IP Addresses based only on concurrent usage, lot of internet provider shares the same public ip natted to their internal network among lot of users (In Italy we have Fastweb that is completely based on this, but other mobile providers like Vodafone are doing the same).

**Comment by Painkiller1985** [comment]
It's probably because the bots access pokestops at a virtually superhuman rate, and when you Double that with 2 bots it screams alarm bells to them

And I'm in uk but I assume they do the same with ip times

**Comment by smoothrunnings** [comment]
@Jamby93 The rule is simple. 1 ID to 1 IP. It doesn't matter how many people you have connected to your hotspot, if Niantics see you're connections are coming from the same IP you'll be soft banned on the IP.

**Comment by Jamby93** [comment]
@JinchengShi What are you referring to with 'ID'? Don't we have fake Device Information randomized per bot?

**Comment by Painkiller1985** [comment]
123@gmail is 1 I'd 456@gmail is a second id

@smoothrunnings it's got to be more than 1ID to 1IP - earlier on i was botting with 1 + 2, I got ip banned, I logged on to 3 on my phone which had not been used to bot at all, but was also ip banned, i then turned my phone wifi off and 4g on, logged in to 1, 2 + 3 on my phone and all of them were fine and normal, reconnected phone to wifi and all 3 were banned again

So whilst long winded, there's no worry of having too many devices from one location, it would seem that it's purely down to the bots being inhumanity fast over a set time

On a similar note, as of the mandatory update this morning, my mock mock locations no longer works, so cant use pokemon go controls etc, perhaps the servers have become much more refined and sensitive to deter our nefarious ways >:)

**Comment by palmpje94** [comment]
I just came back from work and i had 2 ptc bots working when i left, now they both get the no usable pokestops found error with 8.1 8.5 and 7.6. I downloaded a vpn program and i started just 1 bot and still i get this error, also did i turn the default speed to 20 but it's not working:(

**Comment by wrau1** [comment]
Had the no pokestop issue. I have private internet access (ip masker) so I just switch my IP to a different location and was able to immediately able to start botting again.

**Comment by ususparasit** [comment]
i had an issue, that after i change my default location, necrobot only collect from1 pokestop and no activiy after that. i just reinstall it and found the new update v.8.5. but the issue not recovered yet.
i had reset my modem and the IP has changed but not helping this much. plz advice :) (just info, the other BOT still work for me ).
![image](https://cloud.githubusercontent.com/assets/20959333/17574973/a6346be2-5f8f-11e6-9c7c-63315e82d5b9.png)
