### ISSUE TITLE
How many bot we can open in one time?

### ISSUE THREAD

**Issue by brightjoyy** [NECROBOTIO/NecroBot#4468]
For 0.77 i can run for 4-5 bot it work
0.78 only 3
0.8 only 2 
and now 0.85 1 or 2 ??

**Comment by sousoullsullsu** [comment]
for 0.7.6 I run 2 bot and get ip softban.

**Comment by Fremder** [comment]
For me only works 1

**Comment by brightjoyy** [comment]
ok i have to use VM

**Comment by jump-ocz** [comment]
for safety it only 1 
1bot 1ip

**Comment by theloser** [comment]
It's not version dependant, it's the way Niantic blocks IP addresses.

**Comment by koenboots** [comment]
Wouldn't that mean legit players with their phone connected to the same wifi router get softbanned also?

**Comment by theloser** [comment]
We don't know how Niantic determines which IP address get banned and which are not. It just a guess. Maybe it's the number of connects to their server, maybe it's the number of actions per second/minute, maybe it's something else...!?

**Comment by Fremder** [comment]
@theloser Will it works again  that we can run 2 Bots at the same time ?

**Comment by charlieswb** [comment]
You'll get banned if 2 bots with same IP moving too far from each other I guess?

**Comment by Gandaflux** [comment]
@theloser you are sure that problem is not version dependant? Im running 3 bots on old 0.7 version, when i update to latest 0.8 i got softban after i run 2rd bot. Maybe some changes in past versions just send more requests or smth ?

**Comment by Fremder** [comment]
Gandaflux How i can downgrade to version 0.7 ?

**Comment by Gandaflux** [comment]
just download old version from 

https://github.com/NECROBOTIO/NecroBot/releases

**Comment by Fremder** [comment]
What Version u use exactly ?
Thanks

**Comment by theloser** [comment]
@Gandaflux that's interesting. Would you please share your config.json so I can check your settings? Maybe some "default" behaviour has changed in later versions... Thanks a lot in advance!

**Comment by charlieswb** [comment]
@Gandaflux In my opinoin, you dont get softbanned because you use new versoin. It's because naiantic've updated their softban rule overtime.

**Comment by Fremder** [comment]
@theloser Actually that works that u can get an older Version and use 2 Bots

**Comment by DamonSalvat0re** [comment]
@Fremder u just tried?

**Comment by Gandaflux** [comment]
Niantic show requests/sec usage when they change protocol, almost 2/3 traffic to their server are bots. ;)

So its obvious that they will try to stop us.

**Comment by Fremder** [comment]
@DamonSalvat0re Yes

**Comment by Fremder** [comment]
Gandaflux Thanks alot

**Comment by brightjoyy** [comment]
when i downgrade it told that i have to fill username in atuh.json but i already fill it

**Comment by Fremder** [comment]
You have to "  "AutoUpdate": false, "

And downgrade your Walkspeed otherwise u'll get Softbanned and u'll have to wait

**Comment by DamonSalvat0re** [comment]
what speed u changed to @Fremder

**Comment by koenboots** [comment]
Usually I run two bots. I've just downgraded one to version 0.7.8 (set walkingspeed to 6km/h), kept the other one running version 0.8.5. The downgraded one got banned after a minute.
So if this would work at all, you'd probably need to downgrade all bots. I haven't tested this myself yet though.

**Comment by brightjoyy** [comment]
@Fremder yes what speed u changed to ??

**Comment by recon88** [comment]
For general help visit our Discord: https://discord.gg/VXKxNFr
