### ISSUE TITLE
Usable Lure Modules

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#4469]
"UseLureModules": true 
or something like that

**Comment by WishmasterNano** [comment]
and what is it supposed to do? aktivate a lure and walk away?

**Comment by Profetorum** [comment]
y,but if you don't snipe away, your bot is always around default position. Why not?

**Comment by WishmasterNano** [comment]
hm.. but you would have to set the travel distance low enough so he comes around frequently to catch the lured pokemon and this would probably result in the bot running out of pokestops since they need 5min to reset
