### ISSUE TITLE
It have the way to open a lot of bot in one time or not?

### ISSUE THREAD

**Issue by brightjoyy** [NECROBOTIO/NecroBot#4471]
HELPP

**Comment by Fremder** [comment]
Tell us ur Problem sir

**Comment by brightjoyy** [comment]
i want to open a lot of bot in one time do you know or not

**Comment by WishmasterNano** [comment]
if you want to know if you can run multiple bots on one machine, yes. but you shouldnt run more then one per IP

**Comment by Profetorum** [comment]
you have to proxy each bot with a different IP

**Comment by brightjoyy** [comment]
Profetorum How??

**Comment by recon88** [comment]
For help with setting up the bot visit our Discord: https://discord.gg/VXKxNFr
