### ISSUE TITLE
KeepMinDuplicatePokemon : 1, still transfering pokemons

### ISSUE THREAD

**Issue by Jojoushi81** [NECROBOTIO/NecroBot#4474]
Hello again, Guys,

Thanks for help before.
This is my config.
http://pastebin.com/uBqw8Eg3

Can u help why my settings, still transfering my pokemon?

Thanks for ur help Guys..

**Comment by Markersx** [comment]
"TransferWeakPokemon": false,
  "TransferDuplicatePokemon": false,
  "TransferDuplicatePokemonOnCapture": false,

Add pokemon to "PokemonsNotToTransfer" list.
Remove pokemon to   "PokemonsTransferFilter" list.
Here is your updated config:
http://pastebin.com/a0pct8L8

**Comment by huCyy** [comment]
try this "KeepMinCp": edit that one. its transfering CP below 2000!

**Comment by recon88** [comment]
Visit our Discord for configuration help: https://discord.gg/VXKxNFr
