### ISSUE TITLE
How to complete the config for NidoranM and NidoranF

### ISSUE THREAD

**Issue by Marsupilami73** [NECROBOTIO/NecroBot#4475]
Hi

I saw it collets many Candys for the nidoran m+f
How can i update the config to envolve this 2 and get more EP?

Thanks and best wishes
Marsipulami

**Comment by Markersx** [comment]
NidoranMale
NidoranFemal

**Comment by Marsupilami73** [comment]
Hi

But where to complete in the config file?
I tried to put nidoranfemale in the envolve section, but it didn't worked.

Greetz
Marsipulami

**Comment by recon88** [comment]
Visit our Discord for configuration help: https://discord.gg/VXKxNFr
