### ISSUE TITLE
Cant see zh_hk.json in Translations, already downloaded the latest version

### ISSUE THREAD

**Issue by kenip125** [NECROBOTIO/NecroBot#4477]
Cant see zh_hk.json in Translations, already downloaded the latest version
Even if change the language to zh_hk in config, it shows English version.

**Comment by Small-Ku** [comment]
佢好似冇中文(香港),用住中文(臺灣)先啦
It seems like that there is no any Chinese(Hong Kong) Translation.

**Comment by Oolaruu** [comment]
Can you checked again latest compile ?
I submitted a pr who modify  zh_hk to zh-HK
https://github.com/NECROBOTIO/NecroBot/pull/4963
