### ISSUE TITLE
please give me the configuration of all pokemon transferee

### ISSUE THREAD

**Issue by djodiek** [NECROBOTIO/NecroBot#4481]
why can be that master , please help

**Comment by djodiek** [comment]
my pokemon has gone

**Comment by LordYash10** [comment]
Same
All pokemon got transferred

**Comment by huCyy** [comment]
Try this!!!!

"KeepMinCp": 1000,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true

**Comment by djodiek** [comment]
where? all pokemon config?

**Comment by huCyy** [comment]
@djodiek Check Confiq folder>>>>>open config file with notepad and edit it.

**Comment by LordYash10** [comment]
Thanks huCyy

**Comment by recon88** [comment]
Visit our Discord for configuration help: https://discord.gg/VXKxNFr
