### ISSUE TITLE
All pokemon transferred in update 0.8.5

### ISSUE THREAD

**Issue by LordYash10** [NECROBOTIO/NecroBot#4483]
All pokemon are getting transferred automatically in the latest update, even the highest CP ones.
I lost my Aerodactyl.

**Comment by Gandaflux** [comment]
Check your **KeepMinDuplicatePokemon** config

**Comment by frager45** [comment]
no use auto update

**Comment by LordYash10** [comment]
Ok

**Comment by thedarkfalcon** [comment]
Sadly that happened to me in update uh... 0.80.. I have no idea why they made the new default behavior to transfer all the dupes! :((

**Comment by peha84** [comment]
Someone joked, setting the default value **0** in the variable **KeepMinDuplicatePokemon**

**Comment by huCyy** [comment]
Did happen when i updated, i use KeepMinCP: 1000 and it changed to 1250 after update.

My settings:

"KeepMinCp": 1000,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true

Now its all good. check the config

**Comment by LordYash10** [comment]
Thanks
