### ISSUE TITLE
VPN failure, help?

### ISSUE THREAD

**Issue by mitch2798** [NECROBOTIO/NecroBot#4484]
Hello, 

I have a annoying problem.

When I use a VPN and start up te bot it says I need to edit my 2 step authentication password from  my google account in the AUTH.json file. 
But I don't have a 2 step auth password on my accounts.

I tried several countries but none worked. even my own country.

what should i do?

I tried to use a proxy in the auth.json file too but my bot crashed.

**Comment by recon88** [comment]
Enable 2 Step Auth and set an APP password on google

**Comment by mitch2798** [comment]
Okay i got one but where do i type it all in my auth?
