### ISSUE TITLE
[BUG?] 0.8.1 has better sniping than 0.8.2 and above

### ISSUE THREAD

**Issue by dansali** [NECROBOTIO/NecroBot#4488]
### Expected Behavior
0.8.2 + should have better sniping as changelogs say

### Actual Behavior
0.8.1 and lower have better sniping

### Your config.json
http://pastebin.com/UYt4nPda

### Steps to Reproduce
Load 0.8.1 and it snipes large amount of pokemon and stops going to pokestops
Load 0.8.2 and it keeps going around pokestops and only snipes rarely and fails to find any pokemon

### Other Information
Version: 0.8.1
Windows Version: Win7 SP1 x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): snipe

Picture comparison between 0.8.1 through to 0.8.5: http://imgur.com/a/9p7Lg

**Comment by Gandaflux** [comment]
#4403

**Comment by jazzu20** [comment]
hi can you share to me your config? thanks

**Comment by jamalbaharun** [comment]
yes i thing so, please fix this problem

**Comment by nfettinger** [comment]
Duplicate

**Comment by Gandaflux** [comment]
@nfettinger but duplicate #4403 it's also closed.

**Comment by dansali** [comment]
Stop closing the issues, you already closed the previous one. This is not fixed!!
