### ISSUE TITLE
config the bot to only snipe?

### ISSUE THREAD

**Issue by gigaguy** [NECROBOTIO/NecroBot#4489]
Is there a way to config the bot to only snipe?  i just want to "catch them all".

**Comment by recon88** [comment]
Visit our Discord for configuration help: https://discord.gg/VXKxNFr

**Comment by yonrin** [comment]
https://github.com/drz44/DrZ-Configs

This guy made a config for high caliber snipe. Read the README and check it out. His massexp is pretty good aswell, around 100-200k /hour

**Comment by Korni1987** [comment]
it dont works no pokestops

**Comment by yonrin** [comment]
@Korni1987 if you are not able to read and configure the settings to do what you want then dont use it. And yes it does use pokestops, but only when it is necessary.
