### ISSUE TITLE
Still Recycling my pokeballs

### ISSUE THREAD

**Issue by aleslenfeld** [NECROBOTIO/NecroBot#4490]
Hello,
After update the bot keep recycling some of pokeballs even if they are lower than keep value. I have 100 pokeballs in config but anyway its still recycling like 4x PokeBalls even if I have only 9 of them! :/

config: http://pastebin.com/7CuNCWMG

**Comment by peha84** [comment]
Someone joked, setting the default value 0 in the variable KeepMinDuplicatePokemon

**Comment by theloser** [comment]
@aleslenfeld What is your TotalAmountOfPokeballsToKeep setting and how much balls do you have in **total** an your account?

**Comment by aleslenfeld** [comment]
@theloser "TotalAmountOfPokeballsToKeep": 120, and I have 5 PokeBalls at total, at least bot is showing me that i have 5 left. But 7 lines above in bot window it recycled 11x PokeBall, but why i set 120 PokeBalls and it keeps recycling, my config is above in this thread

**Comment by TheseusKingz** [comment]
it is total balls you probly have like 50 grate and 60 u balls so it drops you pokeballs first as thay low grade then grate i had mine at 200 balls an had 190 u so it kept 0ing my pokeballs

**Comment by aleslenfeld** [comment]
Okay, i will set more PokeBalls, but thats the problem of code they should split "TotalAmountOfPokeballsToKeep" to PokeBalls, GreatBalls etc.

**Comment by theloser** [comment]
@aleslenfeld No. If you want to keep 120 balls IN TOTAL, the bot of course keeps the BEST 120 balls he could get. If you have 100 Greatballs and 20 Ultraballs already -- why keep any Pokeballs?

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

RandomRecycleValue in the wiki!
