### ISSUE TITLE
auth.json for iPhone

### ISSUE THREAD

**Issue by rickadipa** [NECROBOTIO/NecroBot#4493]
{
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "",
  "PtcPassword": "",
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "nexus7gen2",
  "DeviceId": "e0864bc2ebab92c3",
  "AndroidBoardName": "flo",
  "AndroidBootloader": "FLO-04.07",
  "DeviceBrand": "google",
  "DeviceModel": "Nexus 7",
  "DeviceModelIdentifier": "razor",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "asus",
  "HardwareModel": "Nexus 7",
  "FirmwareBrand": "razor",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "google/razor/flo:6.0.1/MOB30P/2960889:user/release-keys"
}

This is default, I want put information from my iPhone 5s, but I don't know where can I get that informations.

**Comment by theloser** [comment]
Thanks for your password! :+1:

**Comment by thelemonenergy** [comment]
Ricardo Targueta its very dangerous to paste a password

**Comment by JakeCube** [comment]
Thanks for sharing... Account?

**Comment by Yummster** [comment]
ouch

**Comment by rickadipa** [comment]
So, I tried get help but I didn't see that file get accounts information. This guys is so fast, change password and e-mail...

**Comment by thelemonenergy** [comment]
well his twitch description is funny... https://www.twitch.tv/rickadipa/profile

**Comment by rickadipa** [comment]
Let the games begin!!!!

=D Thanks for make my revange more easy.

**Comment by thelemonenergy** [comment]
Dont worry, the guys on github are usually nice. But better change every login.

**Comment by rickadipa** [comment]
They change the acc e-mail, I only bot for 1 hour in these acccount. But the guy try do other things, and now I have some good information about him.

How can I say in Deutsch... Hallo!

**Comment by Sudiddo** [comment]
Hahaha i lol.. better careful next time, matw

**Comment by theloser** [comment]
@rickadipa Ich hoffe, Du hast nicht dieselben Account-Daten auch für andere Zugänge benutzt, denn dann: gute Nacht!

**Comment by rickadipa** [comment]
@theloser. Probably you took my pokemon account and try other accounts, if you are german , but only one had the same password, but 2-step verification. 

I will be friendly, i got tha IP that who stole the acc.

This ip is from Germany.

**Comment by rickadipa** [comment]
Lübeck, Alemanha

**Comment by theloser** [comment]
@rickadipa I am not interessted in your Ptc account, don't worry, wasn't me :)

**Comment by rickadipa** [comment]
@theloser these account I only create to test the necrobot. But the guy that stole the ptc go so far... that is the problem.

I am not interessted in these ptc account too.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
