### ISSUE TITLE
Add random speed of movement between 2 ranges

### ISSUE THREAD

**Issue by javimoya** [NECROBOTIO/NecroBot#4497]
Niantic is banning when detect an ip that walks quickly and constantly at the same speed.
We need a range : 
MinWalkingSpeedInKilometerPerHour
MaxWalkingSpeedInKilometerPerHour
and then the bot should walk , every 5 seconds, at a different random speed between this range.

**Comment by justinma98063** [comment]
how can you change that setting?

**Comment by 4valanch3** [comment]
Any proof of this Ninantic banning policy?

**Comment by ChemiHatake** [comment]
the bot is walking in a random speed.

**Comment by ousik** [comment]
i set speed to 4.1 km/h. Is it stable speed for walk?

**Comment by justinma98063** [comment]
how did you set the speed?

**Comment by ousik** [comment]
"WalkingSpeedInKilometerPerHour": 4.1,

**Comment by justinma98063** [comment]
where do you enter this?(thanks for reply)

**Comment by ousik** [comment]
folder "config" - config.json

**Comment by KauKauHat** [comment]
maby random speed will work with Vector class

**Comment by Yanush7** [comment]
Add this option !

**Comment by deduijk** [comment]
See issue 3597; 

> AT least a random variance on the vector needs to be implemented:
> 
>     Speed up, slow down (A human doesn't walk at a constant speed.)
>     Variances within the travelling vector (slight perpendicular movement on the vector, also random (but small amount)
>

**Comment by KauKauHat** [comment]
can it work ?

std::default_random_engine generator;
std::uniform_int_distribution<int> distribution(1,6);
int dice_roll = distribution(generator);  // generates number in the range 1..6 
  

For repeated uses, both can be bound together:

auto dice = std::bind ( distribution, generator );
int wisdom = dice()+dice()+dice();

**Comment by nfettinger** [comment]
Duplicate #3597

**Comment by ronalbur** [comment]
i set speed to  30.0 km/h, getting 180 EXP P/HR
