### ISSUE TITLE
GPX Pathing

### ISSUE THREAD

**Issue by Inijester** [NECROBOTIO/NecroBot#4499]
hey. whats the link to create gpx pathing? i cant see it here: https://github.com/NECROBOTIO/NecroBot/wiki/GPX-Pathing-Setup
Thanks!

**Comment by kauegimenes** [comment]
The URL was https://wtracks.appspot.com/

**Comment by Inijester** [comment]
Thanks! But is there any other page i can creat gpx pathing with?

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
