### ISSUE TITLE
Help softban?

### ISSUE THREAD

**Issue by lNath** [NECROBOTIO/NecroBot#4501]
i get softbanned 40-50min ago and now when i open the bot again, this msg appear "0 pokestops found in your area) What i can do? new account? wait more time?  pls help.

I open my acc in my phone and works fine, can take pokeballs from pokestops and catch pokemon

**Comment by Gandaflux** [comment]
changing your ip can help.

**Comment by Zarovzky** [comment]
Use proxy services, max 2 bots / proxy, you can buy 10 ip proxies for 5$

**Comment by kentsang77** [comment]
just wait around 1 hour to get unban.
try not to open more than 1 bot on same IP... 
or try decrease the walk speed to a lower value for 2 or more bots. 
It just a guess. I am still not sure the underlying softban logic.

**Comment by thedarkfalcon** [comment]
Did you look at all the other threads with similar titles before opening this one?
Restart your router (to get a new external IP), reduce **WalkingSpeedInKilometerPerHour** to something like _15_ (the default of _31_ is too high). Also make sure you have **DisableHumanWalking** set to _false_.

**Comment by lNath** [comment]
Thx to all
now is working again (L)

**Comment by pomolopomolo11** [comment]
Hello,
how can i use proxy services please ? 
Thanks !!

**Comment by dkazuma** [comment]
googling will help

**Comment by pomolopomolo11** [comment]
@dkazuma : if you don't wanna help just don't answer, you're not adding a value here ;)

**Comment by WuddyMarco** [comment]
Use google !

**Comment by Mamutebr** [comment]
@Zarovzky which site?

**Comment by TazDevil66** [comment]
You can try a few of the free VPN programs that are out there. I'm currently using one called Windscribe as mt son also runs the bot so it saves us clashing with IP's

**Comment by Zarovzky** [comment]
@Mamutebr http://actproxy.com/ I just bought 10 proxies and they work perfectly.

**Comment by bouncer07** [comment]
INATH, what was the resolution? That would help out

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
