### ISSUE TITLE
(PokeWatchers.com) Error converting value "Mr_mime" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[0].pokemon', line 1, position 34.

### ISSUE THREAD

**Issue by sing1222** [NECROBOTIO/NecroBot#4502]

**Comment by NeCx** [comment]
Same problem

**Comment by LudMiller** [comment]
try mrMime

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

Please check your configurations!
