### ISSUE TITLE
How to not catch any Pokemon, just get balls ? 

### ISSUE THREAD

**Issue by pogotrainer9** [NECROBOTIO/NecroBot#4504]
Hello, thanks for all your great works. I want to ask how do I config not to catch any Pokemon, but just get to Pokestops and fill up my Pokeballs ? Thanks to any help.

**Comment by fatchan** [comment]
by reading the config

**Comment by TemhAAhmeT** [comment]
"CatchPokemon": true,

**Comment by pogotrainer9** [comment]
Thanks ! I totally missed that part actually...

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
