### ISSUE TITLE
pokezz

### ISSUE THREAD

**Issue by zenis12** [NECROBOTIO/NecroBot#4506]
pokezz is not working, gettting error.. same issue to everyone?

**Comment by elmaarmut** [comment]
Pokezz and Pokewatchers are giving errors for me. And the whole bot is crashing occasionally when trying to snipe (like every 5-10 minutes)

**Comment by elmaarmut** [comment]
And not a single coordinate from skiplagged.com is correct, all of them empty -.-

**Comment by zenis12** [comment]
how we remove that skiplagged from server

**Comment by zenis12** [comment]
exact same problem as im gettting

**Comment by zenis12** [comment]
now im getting no pokestops on one bot and the other is working fine.. so its not ip ban

**Comment by elmaarmut** [comment]
I wish I could just use the coordinates from PoGoFeeder, and not these sucky servers like pokezz etc. Is there any way to use PoGoFeeder anymore?

**Comment by Firedor** [comment]
I used pokezz when I play on Nox emulator and it works great. But here in bot i'm getting these all the time
![nnnn](https://cloud.githubusercontent.com/assets/20915853/17553250/2754a876-5f05-11e6-9b2b-adfb07e92173.PNG)
![bnbnbnhjtgh](https://cloud.githubusercontent.com/assets/20915853/17553253/28c14656-5f05-11e6-8f08-4b8b728c08e8.PNG)

**Comment by nfettinger** [comment]
Duplicate issue
