### ISSUE TITLE
Getting less XP

### ISSUE THREAD

**Issue by juantamadz** [NECROBOTIO/NecroBot#4507]
i just want to know if you guys know how can we maximize the XP we gain in this new version. thanks

**Comment by elmaarmut** [comment]
By making all delays 0, increasing the ecellent throw chance and curveball chance to 100, using large movement speeds (50+), and possibly getting permabanned in the future.

**Comment by StarvingDeveloper** [comment]
I am sure nobody in own mind keep all data players(bots) generate in this game, so if you not banned now, and switch to official client then you are safe. If you get banned you will get banned there and now, not somewhere in the future.

**Comment by charmsluckyme** [comment]
^^^

The biggest problem here is that botting will continue to be a cat and mouse game with Niantic.  If you wish to have a truly safe and enjoyable experience, I recommend botting as if you were actually playing the game (i.e. believable walking speed, normal delays between actions, etc.).  Just leave the bot running all day, try not to think about it, and you will farm tons of XP.  Also, on the bright side, when you aren't sniping or using custom configs to farm XP, you are gathering a wider variety of candy, allowing you to evolve the pokemon and level them up late game, which is ultimately the end goal I would think?  There isn't really a point in reaching level 40+ and having nothing to do when you get there.. if that makes sense.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
