### ISSUE TITLE
No poke stops

### ISSUE THREAD

**Issue by patrol34** [NECROBOTIO/NecroBot#4509]
Hi,
This is my problem: http://imgur.com/a/Z4RH4
Version. 0.8.3 DrZ

I was change config 10 times - doesn't help
I was change versions 0.8.0, 0.8.5 - doesn't help
I was change km/h  50->7 - doesn't help
I was change coordinates still doesn't help
I try  use VPN but Nerobot was crash when i turn on VPN.

Some one can help me?

**Comment by thedarkfalcon** [comment]
Reduce **WalkingSpeedInKilometerPerHour** to _10.0_
Make sure **DisableHumanWalking** is set to _false_
Restart router (to get new ip).

**Comment by charmsluckyme** [comment]
Same thing happened to me.  I left my account sniping all night and woke up to a softban on my IP.  I recommend deleting all your release files/folders, resetting router, waiting about an hour or so, redownloading Necro, setup Config (be careful here, as default duplicate pokemon is set to 0, you might want it at 1, change walking speed from 31--->15, and make sure you like all the CP values etc, and change DisableHumanWalking to false), and then trying again.  This worked for me.

**Comment by cawk** [comment]
Yes sounds like niantics new softbans are removing the pokestops 
please wait for the softban to finish

**Comment by patrol34** [comment]
OK it's work.
I think it was the new soft ban.

**Comment by zenis12** [comment]
now getting softban every 5 minutes xD Miss those old days when everything was working great .. ehe

**Comment by joaoaug** [comment]
its a IP ban, try to connect to your mobile network and check. it will work on a different IP

**Comment by patrol34** [comment]
i will try to change my ip adress
