### ISSUE TITLE
thus version 8.5 not transferring even high cp pokemon?

### ISSUE THREAD

**Issue by jemrick** [NECROBOTIO/NecroBot#4510]
answer please guys thank you

**Comment by charmsluckyme** [comment]
Having a little trouble understanding what you are asking.. do you mean its transferring high CP pokemon as well? or..?

**Comment by clownnut** [comment]
0.85 just a version of the bot. cp have to do with your lvl. higher lvl = high cp. have nothing to do with the version of the bot

**Comment by pluem544** [comment]
You can edit in config.json

**Comment by GrimDemon** [comment]
@pluem544 yeah sure, but it shouldn't transfer high CP/IV pokemon by default. I don't know what @jemrick had in mind, but I saw few of my pokemons (eg. Seadra 1080CP, account lvl 26) transfered without a reason (no duplicate or anything).

**Comment by sh1thapp3n** [comment]
the 8.5 version is transfering all pokemon even the best CP pokemon any solution about thing issue?

**Comment by rachong** [comment]
In config..set transferweakpokemon "false"

**Comment by Schwrid** [comment]
Just put the ones u like as favurite and ur good to go

**Comment by rachong** [comment]
And also please check your setting to minduplicatepokemon..default value is 0..so change the value

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

If you find a specific bug in the code please open a new issue.
