### ISSUE TITLE
How to use 2 bots at a time ? 

### ISSUE THREAD

**Issue by Schwrid** [NECROBOTIO/NecroBot#4515]
I am using 1 without a problem 
using 2 or more bans my ip for 10-15mins 

anyone figured out how to use multiple accounts recently ?

**Comment by RiPPERD** [comment]
yeah ive just had the same thing... didnt happen with v0.8.1 but updated to 0.8.5 today and its banned both accounts

**Comment by Schwrid** [comment]
yea but using one account a time and setting walk speed to 21 is helping me and going on for abt 2h now

**Comment by theloser** [comment]
Use different proxy server for each bot. If you need more information, please go to discord (link on the main page) and ask for help, thanks.

**Comment by Schwrid** [comment]
theloser bro can u help with the link pls

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
