### ISSUE TITLE
No Usable Pokestops found in Your Area 

### ISSUE THREAD

**Issue by vyshu007** [NECROBOTIO/NecroBot#4516]
I'm sure it's not softban. Experts Please help

**Comment by Schwrid** [comment]
did u use multiple accounts  ?

**Comment by vyshu007** [comment]
Yeah

**Comment by vyshu007** [comment]
Any solution?

**Comment by kalesnor** [comment]
same here used 2 acc

**Comment by kalesnor** [comment]
ptc and google

**Comment by CakeHole83** [comment]
Yeah I can tell you it is not a softban. Same thing for me. Tried changing both deviceid and ip but nothing happends.

**Comment by costapj** [comment]
I have the same issue as well on both accounts when I go to the phone app it logs in but no poke stop or gyms spawn around me uh oh

**Comment by kubson218** [comment]
just restart router :)

**Comment by vyshu007** [comment]
Will that help?

**Comment by pax123** [comment]
same problem here, just using for 1 account, i restarted router many times but doesnt fix the problem

**Comment by kubson218** [comment]
me helped :v

**Comment by CocoLoco5550** [comment]
I have the same problem :(

**Comment by kubson218** [comment]
in this case, time is the best solution

**Comment by asrelasrel** [comment]
same problem here, but how to restart the router ?

**Comment by kubson218** [comment]
turn off and turn on XD

**Comment by asrelasrel** [comment]
not working

**Comment by TomPK** [comment]
I've the same problem, but i think its soft ban yes, cuz after the 2/3hours is back to normal..

**Comment by Plotin** [comment]
It seems to be an IP based ban. After moving my bots to different servers and using one IP per bot, it runs ok again

**Comment by clownnut** [comment]
dont run 2 bots at the same ip. it wasnt an issue til today. i just got ip ban for 1 hr this morning. now i am back to farming again

**Comment by TomPK** [comment]
maybe, tried to enter different ip by proxy, but the bot won't connect, I tried switching the ip, but does not work

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by clownnut** [comment]
i dont think necrobot work with vpn/proxy.

**Comment by TomPK** [comment]
I found a solution Download an application that hide ip, or to change your ip! Plotin was right..

**Comment by TomPK** [comment]
Here it worked

**Comment by costapj** [comment]
any suggestions on apps

**Comment by TomPK** [comment]
Give a little lag.. cuz you change ip.. but, you can play ;)
https://www.hotspotshield.com/

**Comment by vyshu007** [comment]
what's the use in changing IP? Even if it is changes, when we use multiple bots, they can track the same IP in all these accounts, right?
