### ISSUE TITLE
How to fix this User credentials are invalid and login failed.

### ISSUE THREAD

**Issue by dtscript** [NECROBOTIO/NecroBot#4517]
User credentials are invalid and login failed.

**Comment by Schwrid** [comment]
remember them ?

**Comment by Aeohard** [comment]
Put a quotation mark (") before and after of your email address and password..

**Comment by deduijk** [comment]
or remove the auth.json and config.json and walk through the configuration again.
You need to anyways, because new options might have been introduced etc.
(REMEMBER to check the config before you let necro continue after initial setup!!)

**Comment by dtscript** [comment]
Thank you.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
