### ISSUE TITLE
Candy count shown incorrectly when transferring weak/duplicate Pokemons

### ISSUE THREAD

**Issue by DBa2016** [NECROBOTIO/NecroBot#4518]
### Expected Behavior
When multiple pokemons of the same type are transferred, candy count shown should increase after each transfer
### Actual Behavior
Candy count remains constant

![candy](https://cloud.githubusercontent.com/assets/20729632/17553160/7d07b73c-5f04-11e6-85a8-fb77aeb04c20.png)

**Comment by cawk** [comment]
Can you check to see if this has been fixed i tried reproducing myself and was fine

**Comment by cawk** [comment]
https://gyazo.com/045f59e1412b16a64c77650432e12f1e
just checked it out seems to be fixed
