### ISSUE TITLE
[Addition] Eggcounted speed in the windowbar

### ISSUE THREAD

**Issue by neoflomo** [NECROBOTIO/NecroBot#4519]
At the moment we are only able to choose which speed the bot should run.

I think it would be cool to show us the distance/hour the eggs get, so we would be able to adjust the speed to get as many eggs breeded as possible.

could look like this:
![eggcounted](https://cloud.githubusercontent.com/assets/20717941/17553233/0a4a1f22-5f05-11e6-9d10-a34ca7ec1a0c.png)

**Comment by Schwrid** [comment]
dat photoshop doe

**Comment by neoflomo** [comment]
dat paint my friend ;)

**Comment by nfettinger** [comment]
If you set your walking speed appropriately, all distance you travel will be counted towards your egg, and your walking speed WILL be your eggspeed
