### ISSUE TITLE
ip ban

### ISSUE THREAD

**Issue by ewaah** [NECROBOTIO/NecroBot#4521]
hey

i'm using two accounts on different desktops
1 works fine the other says no pokestops
so it can't be an ip ban,
is there a fix or a way to avoid it

**Comment by ewaah** [comment]
and my config and everything else is perfect, walkingspeed is 15, and i used it yesterday on 100 with no problems at all

**Comment by schadis** [comment]
the fix is dont snipe!
you arent ip banned .. you got troll cordinates from discord...
this cordinates are in india
india is geoblocket!!!!
there are no pokestops arenas and pokemons...
so what the bot tells you is true ... no stops in range

**Comment by ewaah** [comment]
well checking that right now

**Comment by Schwrid** [comment]
speed 21 is fine

**Comment by ewaah** [comment]
ok i checked
1: i'm not sniping
2: i rechecked my coords, they are in central park
3:what did you mean with trolled by discord, cause i did not used it?
4:sorry for the questions

**Comment by ewaah** [comment]
could it be just a softban

**Comment by costapj** [comment]
i am pretty sure it ip related when i am connected to the network on my phone and i open the app no poke stops spawn if i get off the wifi and go on data the account pulls up poke stops and gyms

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by ewaah** [comment]
its not a configuration mistake, discord chat sucks thats why everybody comes here, and everything worked fine till 1 hr ago, but ok doenst matter because nobody can fix it here

**Comment by Trenars** [comment]
Not sure if this is helpful to anyone, but still decided to share my rules around botting...
1. I am using bot on 3 accounts simultaneously on same PC (same IP)
2. I am NOT using any proxy service
3. I NEVER been soft banned
4. I AM using VPN
5. I AM very careful when I change the countries. I always check how long would it take me to drive/fly from one location to other in real life and I am NOT using bot/logging in game for that period of time.
6. I AM trying to set my IP to the geo location of my bot (or as close as possible)
7. I ALWAYS double check my config file before each launch (cords, speed, delays and so on)
8. I rarely use sniping (have used it for 3 hours in about week time)
9. Movement speed is never greater than 10 km/h and delay between actions is about 5000 ms
10. If I stop the bot, I leave 15 to 30 min before I restart it
11. I never log in the accounts from the phone while bot is running (If I want to log in on my phone, I ensure Location settings are set to GPS only and GPS is turned off). If I want to log in on my phone and have GPS on, rule Nr 5 applies. 
12. I use bot for no longer than 14 hours/day.

Hope this helps :)
