### ISSUE TITLE
Can´t Download Release.zip ( Update

### ISSUE THREAD

**Issue by rich0788** [NECROBOTIO/NecroBot#4524]
Tried it on autoupdate but suddenly after that the *exe was deleted by itself automatically.
If I try to download the release on github, the download just does not finish.
Tried on several computers and with firefox / IE

Any ideas?

**Comment by theloser** [comment]
Download from GitHub works perfect, must be an issue on your end. Sorry.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
