### ISSUE TITLE
Can I use back the old version of necrobot?

### ISSUE THREAD

**Issue by Zandrick** [NECROBOTIO/NecroBot#4527]
Please do not update the version when the old one works fine...

EvolveAllPokemonWithEnoughCandy = false
But still evolving

**Comment by theloser** [comment]
Just set AutoUpdate to false and use any version you think will work for you. See: https://github.com/NECROBOTIO/NecroBot/releases

**Comment by Zandrick** [comment]
I see. Thanks

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
