### ISSUE TITLE
Having issues , where can I download old version ?

### ISSUE THREAD

**Issue by Kuristinyaa** [NECROBOTIO/NecroBot#4529]
I'm having issues with the current Necrobot after updating it . 

Was wondering if anyone can provide me with the download link for the older version ?
Can't seem to find it .

**Comment by theloser** [comment]
https://github.com/NECROBOTIO/NecroBot/releases

**Comment by luxhakim** [comment]
theres v0.8.5 work? anyone?

**Comment by theloser** [comment]
I have multiple 0.8.5. versions running (with different proxies), of course it works!

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
