### ISSUE TITLE
No pokestops in area.. IP Ban, Soft ban??

### ISSUE THREAD

**Issue by KASHiRiNKiTO** [NECROBOTIO/NecroBot#4534]
Help.
I am using 2 Accounts. But both accounts/bots cant find any pokestops in area..

Is it an IP Ban or what? How can I set proxy?

**Comment by costapj** [comment]
a few of us are having the same issue still waiting to figure out what it is and a solution

**Comment by theloser** [comment]
Your account is permabanned. Stop playing Pokemon Go.
(And use the search function before opening new issues, please!)

**Comment by feroniameimei** [comment]
similiar #4501

**Comment by CptnKvin** [comment]
had same issue yesterday and no I WAS NOT permabanned ;)
i changed deviceId and it worked out for me ^^'

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by princejhedz22** [comment]
use 1 bot only
