### ISSUE TITLE
Bot won't snipe manual locations

### ISSUE THREAD

**Issue by StephenFierce** [NECROBOTIO/NecroBot#4535]
The bot won't snipe my long/lat locations anymore? (since 0.8.5). When i try to downgrade i get google error that i have to fill in my username and password (which i did...). but it still won't log in...

What to doooo..

**Comment by StephenFierce** [comment]
how do i disable those stupid useless websites (pokesnipers and so on) and enable my own locations that are totally awesome?

**Comment by costapj** [comment]
what are your locations lol

**Comment by StephenFierce** [comment]
all over the world, all major cities.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
