### ISSUE TITLE
vpn update failure

### ISSUE THREAD

**Issue by mitch2798** [NECROBOTIO/NecroBot#4536]
hello,

i just made a second step app password for my gmail but where do i add it in my auth.json file?
i dont see any options in there.

btw it is to allow my bot to use with VPN.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by mitch2798** [comment]
And where is that option. would be nice if u actually said where it was.
