### ISSUE TITLE
work now v0.8.5

### ISSUE THREAD

**Issue by luxhakim** [NECROBOTIO/NecroBot#4539]
![screenshot_1](https://cloud.githubusercontent.com/assets/20949058/17554105/877f7d74-5f33-11e6-9796-fdb9bd979b04.png)

**Comment by luxhakim** [comment]
thx everyone...

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by ronalbur** [comment]
Walking speed please?
