### ISSUE TITLE
using 2 bot on 2 different computer BAN IP!!

### ISSUE THREAD

**Issue by crest1993** [NECROBOTIO/NecroBot#4541]
if i use 2 bot on 2 different computer i get ban ip, after restarting router everything is fine... but stil..

**Comment by LordDeimos** [comment]
But still your wan has always the same IP, what's the point to use 2 computer that share the same WAN ip.

**Comment by theloser** [comment]
I am pretty sure he doesn't know what a "wan" is.

And: This is NOT a developement issue -- use [Discord](https://discord.gg/VXKxNFr) to get help.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
