### ISSUE TITLE
[ASK] can i get banned if my default location is in united states but my ip is in indonesia?"

### ISSUE THREAD

**Issue by BlackCobra89** [NECROBOTIO/NecroBot#4542]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by theloser** [comment]
This is NOT a developement issue -- use [Discord](https://discord.gg/VXKxNFr) to get help.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
