### ISSUE TITLE
FUCK NIANTIC: POKESTOP DISSAPEAR

### ISSUE THREAD

**Issue by fuckNIANTIC** [NECROBOTIO/NecroBot#4543]
Can someone please kindly overwrite this. I think the focus isnt that unknown6 we faced before. The real issue is hacking into their system and revealing the hidden pokestop for that Ban shit. Fuck niantic, peaceout!

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
