### ISSUE TITLE
Proxy Type

### ISSUE THREAD

**Issue by AtomClock** [NECROBOTIO/NecroBot#4546]
Hello,

To assure the proxy setting works what type of proxy should we use ?

HTTPS? SOCKS4? SOCKS5?

Or is regular HTTP is good enough? 

Also if you have any suggestion of reliable free proxy site please share !

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
