### ISSUE TITLE
what is the name from nidoran female in the bot?

### ISSUE THREAD

**Issue by jowar** [NECROBOTIO/NecroBot#4548]
i need the english name for nidoran female for the bot config

**Comment by theloser** [comment]
nidoranfemale
Thanks for using the issue tracker, please close.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by jowar** [comment]
ok thx what is the discord link?

**Comment by theloser** [comment]
The link is on the main page, right at the top.
