### ISSUE TITLE
Suggestion - option for auto update enable/disable. 

### ISSUE THREAD

**Issue by smoothrunnings** [NECROBOTIO/NecroBot#4549]
I don't like the app auto-updating that I would rather do it myself as I don't know what changes are made that could affect my current game play. 

There should be an option in the config file.

**Comment by theloser** [comment]
It is. Check your config.
Thanks for using the issue tracker, please close.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
