### ISSUE TITLE
Sniping not working at all

### ISSUE THREAD

**Issue by elmaarmut** [NECROBOTIO/NecroBot#4550]
### Expected Behavior
Actually snipe.

### Actual Behavior
0 successful snipes. Pokewatchers not working, nothing from pokezz, Skiplagged gives false coordinates (no pokemon there).

### Your config.json
[config.zip](https://github.com/NECROBOTIO/NecroBot/files/411086/config.zip)

### Steps to Reproduce
Just run it with my config and see.

### Other Information
Version: 0.8.5
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Snipe

Screenshot:
![1](https://cloud.githubusercontent.com/assets/20822856/17554655/909caa2c-5f14-11e6-97fe-7c0f4004d940.jpg)

**Comment by nfettinger** [comment]
Duplicate issue
