### ISSUE TITLE
Will not catch any pokemon - stuck in loop

### ISSUE THREAD

**Issue by binarydaddy1234** [NECROBOTIO/NecroBot#4551]
http://prntscr.com/c3yi2v Any fixes? Yes i have catch pokemon true in config..

**Comment by kloudfour** [comment]
I have the same issue too, however should also mention that i use DrZ's config.

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
