### ISSUE TITLE
bot giving error [18:40:48] (EGG) Incubator status update: 0.92km left [18:40:48] (EGG) Incubator status update: 1.64km left [18:40:49] (ATTENTION) No usable PokeStops found in your area. Is your maximum d istance too small? [18:40:50] (EVOLVED) Potential Evolutions: 0

### ISSUE THREAD

**Issue by hunter11995** [NECROBOTIO/NecroBot#4553]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Actual Behavior
[18:40:48] (EGG) Incubator status update: 0.92km left
[18:40:48] (EGG) Incubator status update: 1.64km left
[18:40:49] (ATTENTION) No usable PokeStops found in your area. Is your maximum d
istance too small?
[18:40:50] (EVOLVED) Potential Evolutions: 0

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Heavy1209** [comment]
always like that i have same problem

**Comment by nfettinger** [comment]
Probably softbanned.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
