### ISSUE TITLE
Error and relogin after some snipes

### ISSUE THREAD

**Issue by dudaefj** [NECROBOTIO/NecroBot#4554]
My Config: http://pastebin.com/FCRcrkpy
It is pretty simple and easy to reproduce (at least for me it is happening 100% of the times)

Basically it gets error when it tries to snipe: http://prntscr.com/c3ygrh

I also had pokewatchers, pokesniper and pokezz seted to true on the config file, I just changed to false cuz I tought the error was caused by them, but even using only PogoFeeder I get the same error when sniping

**Comment by nfettinger** [comment]
Duplicate #3295
