### ISSUE TITLE
Make Telegram Bot Access limited to authorized telegram users.

### ISSUE THREAD

**Issue by cvbkf** [NECROBOTIO/NecroBot#4556]
### Actual Behavior
Currently, you can search in Telegram for Nekrobot Users and access their stats, location of the bot and profile name. Theoretically, Niantic could check for users to ban there. 

### Expected Behavior
Prepare a whitelist for allowed telegram users in config.json, and let the bot reply with data only to whitelisted users.

**Comment by nfettinger** [comment]
You need a telegram key to be able to read anything anyways. Hopefully you generated your own unique one.

**Comment by theloser** [comment]
@nfettinger Wait, please reopen this issue, because I think this is important!
Of course every bot has it's ony key (if this is what you meant), but the bot will react to anyone who sends commands, right? So anyone who knows the name of my bot can start a "chat" with him and send commands. That's a bad idea with commands like "/restart" are being worked on.

**Comment by cvbkf** [comment]
That's what i meant, the bot itself is publicly accessible for every telegram user if the name is known. And some users name their bots "Necrobot", just try a search.

**Comment by theloser** [comment]
> just try a search

I did :)

**Comment by theloser** [comment]
From Telegram:

> You can probably add in a hardcoded check of message.From.Id in PoGo.NecroBot.Logic.Service.TelegramService.OnTelegramMessageReceived() in the meantime

**Comment by theloser** [comment]
From Discord again:

> Necro is working on a fix right now

Promising!

**Comment by nfettinger** [comment]
This has been fixed. Please wait for the next release, or pull from source

**Comment by theloser** [comment]
Pulling (and testing) it right away... Thanks!

**Comment by theloser** [comment]
Unfortunatelly the "fix" doesn't work, crashes the bot.
According to Discord (#development) other users are getting the same error:

> [19:14] Chemi: @Necronomicon I'm getting an error

This is the error (in german):

> Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Security.VerificationException: System.Net.Http.CloneableExtensions.Clone-Methode: Das "System.Net.Http.Headers.MediaTypeHeaderValue"-Typargument verletzt die Einschränkung des "T"-Typparameters.

This is the original screenshot Chemi posted on Discord: 
![capture](https://cloud.githubusercontent.com/assets/1885031/17570702/c9e4f44a-5f4d-11e6-88f8-9eb7815c7f47.PNG)
