### ISSUE TITLE
latitude, longitude can't appear in pokesniper

### ISSUE THREAD

**Issue by gundalas** [NECROBOTIO/NecroBot#4559]
i have a problem with pokesniper, like this:

![image](https://cloud.githubusercontent.com/assets/20949793/17554923/8d373924-5f37-11e6-8fe9-c0278a570284.png)

does everyone can explain how to solve it?

**Comment by theloser** [comment]
How is this an issue with NecroBot?

**Comment by nfettinger** [comment]
This is not an issue with NecrBOT

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
