### ISSUE TITLE
Can't run 2 bot at a time

### ISSUE THREAD

**Issue by spardadt** [NECROBOTIO/NecroBot#4562]
I know there is the IP ban so i changed the setting not to travel at impossible speed, etc. But it seems like I still can't run 2 bots at the same time. It was fine running 1 and after I started another one, just shortly after, i get IP banned on both account. Any1 knows why or how to fix?

**Comment by spamfighter82** [comment]
only run one bot

**Comment by spardadt** [comment]
So it's impossible to do 2 bots at a time? I guess some people are just lucky that they can run 2?

**Comment by nfettinger** [comment]
Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
