### ISSUE TITLE
[FEATURE REQUEST][INCUBATOR] only use inf egg for 2k eggs (NOT 1579)

### ISSUE THREAD

**Issue by erikk00** [NECROBOTIO/NecroBot#4565]
First things first this is NOT a repeat of https://github.com/NECROBOTIO/NecroBot/issues/1579 

This request is the ability to only use the inf egg on 2k eggs (ie if all eggs are 2k eggs the limited use incubators just aren't used) or even better as per a setting (maybe someone only wants to use limited incubators on 10k eggs).  I know that egg prioritization is 10>5>2 for limited eggs and I know that 2>5>10 for the infinite egg.  But at some point unless I'm buying limited eggs I'm going to be in a situation where I only have the infinite one left and I don't want my limited use eggs wasted if the first 30 or 300 eggs I get on an account are all 2k eggs;  I'd rather be walking with unused incubators for those first 30 eggs and then use the limited ones once I get better eggs since there's going to be time walking with no limited incubators eventually no matter what happens (rather front load the unused walking time than have it later at higher level).  I mean we're going to hit 40 sooner or later and unless limited incubators are dropping from pokestops and I'm not aware of it, there's going to be a time when you're "walking" and you have no limited incubators at all.

**Comment by kkekof** [comment]
+1

**Comment by nfettinger** [comment]
This is a duplicate issue. There is already an issue to make eggs configurable, and not just default to 10.

**Comment by erikk00** [comment]
I'm not trying to be contentious but do you mind referring me to the issue that actually covers this?  Unless it's being discussed on the backend outside the open github issues section I haven't seen an issue with this specific request.  

https://github.com/NECROBOTIO/NecroBot/issues/3233 Discusses making changing egg priority possible but doesn't talk at all about making incubators sit unused.  
https://github.com/NECROBOTIO/NecroBot/issues/3923 Also talks about changing egg priority manually but doesn't talk about not using limited incubators at all.
https://github.com/NECROBOTIO/NecroBot/issues/1579 which is referenced often with regards to this doesn't reference not using limited incubators.

Closed issues:
https://github.com/NECROBOTIO/NecroBot/pull/2479 talks about changing egg priority for inf incubator but not having limited incubators sitting unused.  
https://github.com/NECROBOTIO/NecroBot/issues/521 might reference this but is so "old" at this point I'm not sure it's even on the radar.
https://github.com/NECROBOTIO/NecroBot/issues/832 doesn't talk about it at all.  

I'm just using the above to demonstrate that I did look for this issue before posting my request.  And I'm sincerely asking for a link to the issue that deals with this if for no other reason than to possibly lend feedback/opinion.  

I really don't think the concept of not using an incubator is part of any open issue and if it's part of a closed issue is there any chance someone is working on it?  I'm just trying to help and I don't know the code side so I can only offer suggestions on features others might like having.
