### ISSUE TITLE
GPX path starts over when "throttling API Calls" alert comes up

### ISSUE THREAD

**Issue by 2slippy** [NECROBOTIO/NecroBot#4568]
When the bot reports "Servers unstable, throttling API Calls", it returns to the first coordinate in the gpx file (or the default position since they are the same in my case). In my case I have disablehumanwalking set to false so it does path back to the starting point rather than jumping, but it still causes it to repeat the first part of a path over and over when it sees server issues. Can the bot retain its current index position in the gpx file and the coordinates in that position on a soft restart (or whatever it is called when it throttles API or has an error and restarts)? If gpx pathing is still set to true and retained coordinates matches the coordinates in the gpx file at the retained index then it would be safe to assume the bot wants to continue from that point?

**Comment by nfettinger** [comment]
Duplicate Issue.
