### ISSUE TITLE
Did not find a Pokemon...SPAM!

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#4569]
After 5min of botting:

![image](https://cloud.githubusercontent.com/assets/20842205/17555335/8157a2c4-5f0f-11e6-9bc5-8a9ff214d122.png)

How can Necro exp like this?

**Comment by kkekof** [comment]
permban?

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by Profetorum** [comment]
@nfettinger can you link me please?

**Comment by STCOZT** [comment]
same 4 me
