### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RemSc10** [NECROBOTIO/NecroBot#4570]
Bonjour j'ai une erreur sur l'application necrobot, quand je lance l'appilacion il apparais se texte : " (ATTENTION) Impossible de trouver un Pokestop. Mmodifiez la valeur de MaxTravelDistanceInMeters dans le fichier config.json " Pouvez vous m'aidez ?  Merci ! 

Hello I have an error on the necrobot application, when I run the appilacion Appear it is text : " (WARNING ) Can not find a Pokestop Mmodifiez value MaxTravelDistanceInMeters config.json in the file. " Can you help me ? Thank you !

**Comment by nfettinger** [comment]
IP Banned

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

**Comment by azza89** [comment]
Hi, It looks like you can only run one version of the bot atm, it appears Pokemon Go have started monitoring IP address
