### ISSUE TITLE
BanIp

### ISSUE THREAD

**Issue by RemSc10** [NECROBOTIO/NecroBot#4573]
![capture2](https://cloud.githubusercontent.com/assets/20950094/17555592/645d9ed4-5f10-11e6-88dc-8d06370b157f.PNG)

Est-il possible de se debanir ou de changer l'ip s'ill vous plait ! 

Is it possible to Unban or change the ip is ill please!

**Comment by nfettinger** [comment]
We cannot help you with this here. You could try using Google.
