### ISSUE TITLE
No usable pokestops found in your area.

### ISSUE THREAD

**Issue by mikegrimmers** [NECROBOTIO/NecroBot#4574]
This problem is re-occurring, prior to this message was a softban alert, do these link?

Would love if someone could provide me with an answer instead of closing the thread!

Appreciate it guys, thanks for all your work & help.

**Comment by nfettinger** [comment]
TransferWeakPokemon

**Comment by nfettinger** [comment]
Please use Discord chat for theses types of issues and questions.
