### ISSUE TITLE
"No pokestops near you"

### ISSUE THREAD

**Issue by R4bidMoose** [NECROBOTIO/NecroBot#4575]
I have an issue with the bot.
It says there aren't pokestops near my location, but this morning everything was all right.

I tried restarting my modem and changing the coordinates, but it just doesn't work.

Any idea?

**Comment by nfettinger** [comment]
Please use Discord chat for theses types of issues and questions.

**Comment by chauhan-rahul** [comment]
in the app also, i am seeing nothing... guess a new anti cheat meckanism by niantic!

**Comment by juantamadz** [comment]
redownload the bot and leave the setting as it is. works for me
