### ISSUE TITLE
MaxTravelDistanceInMeters resulting in No usable Pokestop

### ISSUE THREAD

**Issue by 123787** [NECROBOTIO/NecroBot#4579]
Dear developers,

I notice that the bot will show no usable pokestop found in your area error once reach out the "MaxTravelDistanceInMeters" from the config.json. The issue will still show even I have set "MaxTravelDistanceInMeters": 1000 or 10000 or any number. It just a matter of time the error will show. The temporary solution I found is to use gpx pathing and it will not show any of that issues.  

![01](https://cloud.githubusercontent.com/assets/20950159/17555720/8703ac60-5f08-11e6-8d95-eb2e94f0ddf5.jpg)

Back on the "UseGpxPathing": false. I would like to request if its possible when the no usable pokestop error shows, says a few count of the error, could you reset back to the  "DefaultLatitude" "DefaultLongitude".

Many Thanks.
Regards
123787

**Comment by mitch2798** [comment]
I have this too

**Comment by nfettinger** [comment]
IP BAN

**Comment by mitch2798** [comment]
No it isn't?

**Comment by iw4nkz** [comment]
Waiting fix from developer

**Comment by 123787** [comment]
I dont think is IP ban, this issues have been same from necrobots early build.

**Comment by 123787** [comment]
This issue also can be temporary solve by exiting the bots and starting the bots.. therfore I believe its not an ip ban issue.
