### ISSUE TITLE
No usable pokestops found in your area

### ISSUE THREAD

**Issue by lynnkuuers** [NECROBOTIO/NecroBot#4583]
If i start up the bot i instantly get :
No usable pokestops found in your area. Is your maximum distance too small? 
Its also not catching any pokemons.
I tried switching Longitutes. but nothing works.
Help PleasE? 

BTW: I also cant find the discord server

**Comment by Krome333** [comment]
same .. i have test on my cell phone am not ban ... but on bot its found no pokestop too

**Comment by Sparagmos** [comment]
same issue. the bot is not moving at all according to the incubator status update.

**Comment by TiermitBier** [comment]
same

**Comment by nfettinger** [comment]
IP BAN. Your cell phone will get a different IP

**Comment by aiyaqin** [comment]
same here... waiting for next update

**Comment by lynnkuuers** [comment]
How can i change IP on my Phone than?
