### ISSUE TITLE
Softbanned Repeated !

### ISSUE THREAD

**Issue by xXhieXx** [NECROBOTIO/NecroBot#4584]
![untitled](https://cloud.githubusercontent.com/assets/20947126/17555997/e6ef6492-5f3b-11e6-860c-f34d23479781.png)

somebody help me ? whats wrong with my bot .
the first time boting is normal, until 10 or 15 minutes bot work and the screen like this. full of notification softbanned, and can't bot again, until i close the bot and take some 5 minutes and bot can normaly, but this notification will come again repeat to me.

bytheway, i running 5 bot with 5 different folder
help me. thankyou :)

**Comment by nfettinger** [comment]
Please use Discord chat for help in this area. We cannot help you here.
