### ISSUE TITLE
UsePokemonToNotCatchFilter not working

### ISSUE THREAD

**Issue by blackturtle25** [NECROBOTIO/NecroBot#4586]
### Expected Behavior
Not to catch pokemons listed under PokemonsToIgnore

### Actual Behavior
Catches everything listed under PokemonsToIgnore, instead of skipping them. 

### Your config.json
```
"UsePokemonToNotCatchFilter": true,

"PokemonsToIgnore": [
    "bellsprout",
    "caterpie",
    "hitmonchan",
    "horsea",
    "krabby",
    "lickitung",
    "mankey",
    "oddish",
    "paras",
    "porygon",
    "pinsir",
    "psyduck",
    "rattata",
    "rapidash",
    "sandshrew",
    "spearow",
    "seel",
    "spearow",
    "zubat",
    "weedle"
  ],
```

### Other Information
Version: v0.8.5
Windows Version: 8.1
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): catching, sniping

**Comment by nfettinger** [comment]
Duplicate.

**Comment by blackturtle25** [comment]
@nfettinger I've looked through 4 pages of issues and no one had this problem. I saw a guy who said his filter gets deleted, but mine doesn't, so please read what the problem is before you close it.
