### ISSUE TITLE
Catch only strong pokemons

### ISSUE THREAD

**Issue by shaharbukra** [NECROBOTIO/NecroBot#4590]
### Expected Behavior
i want to set property to enable catching only pokemon above 1000cp i dont want all the 10-600 weak pokemon that spend the pokeballs :+1: 

### Actual Behavior
dont have it

### Your config.json
```
your config here
```

### Other Information
Version: latest
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): catch

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.

**Comment by cacacap** [comment]
is that an issue? read the config you'll get what u need.
