### ISSUE TITLE
Backup config.json file deletet from config map.

### ISSUE THREAD

**Issue by Tupilak** [NECROBOTIO/NecroBot#4593]
### Expected Behavior
Keep my backup config files in the folder.

### Actual Behavior
Deleted all the config file I hade when updated from 7.6 to latest version 8.5

### Steps to Reproduce
Have a file called Config-fastexp.json in your config folder for test use, and then upgrade to new version

### Other Information
Version: now 8.5
Windows Version: win 7

I don't expect the program to wipe the config folder after a upgrade. Do I need to keep then in a other folder so when I upgrade again it will not be deleted ?

**Comment by nfettinger** [comment]
Please keep backups of your files. There is nothing we can do here.
