### ISSUE TITLE
No usable PokeStops found in your area.

### ISSUE THREAD

**Issue by chrlsrara** [NECROBOTIO/NecroBot#4600]
I thought if you're soft ban they hide the PokeStops and Pokemons to prevent the anti soft ban.

**Comment by nfettinger** [comment]
Please use our Discord chat rooms for help with general questions and configuration issues.
You have an IP ban

**Comment by smoothrunnings** [comment]
You are soft banned. 
You must only have 1 ID, 1 IP. You can no longer do multiple ID, 1 IP.

**Comment by draknyte1** [comment]
Whats an IP ban incur? I've got legitimate users playing fine across home wifi on mobiles.. yet multiple pcs fail?
