### ISSUE TITLE
Bot sells on Ebay etc

### ISSUE THREAD

**Issue by JameesJameesJamees** [NECROBOTIO/NecroBot#4601]
So i saw that a lot of guys who are trying to sell the Bot on Ebay etc. Its a freeware and Open Source Programm, what the developer thinks to do against it ?
They're trying to sell something that isnt their own and without any righs on it. 

Always if i see a auction with the bot, i hope these guys are getting banned from ebay etc.
They wanna earn money with smthin that isnt even their own.. 

ps.: Sorry for opening this Thread and not writing at discord, but i cant connect to discord atm its a endless loading :S

**Comment by nfettinger** [comment]
We are aware of the issue.
