### ISSUE TITLE
IP Ban issue. 

### ISSUE THREAD

**Issue by lechoogas** [NECROBOTIO/NecroBot#4604]
Please fix this soon, no pokestop available after starting the bot

**Comment by sianyuw7** [comment]
same problem

**Comment by smoothrunnings** [comment]
its nothing to do with the bot. 
The soft ban only kicks on if you have more than 1 ID using 1 IP

**Comment by nfettinger** [comment]
We cannot help you with this. Please stop opening issues.
Please use our Discord chat rooms for help with general questions and configuration issues.
