### ISSUE TITLE
No usable pokestops found in your area. is your ,maximum distance too small? anyone can fix this?

### ISSUE THREAD

**Issue by MichaelJ27** [NECROBOTIO/NecroBot#4605]
![image](https://cloud.githubusercontent.com/assets/20928246/17557518/19507c74-5f4a-11e6-85bc-3b1328223559.png)

**Comment by nfettinger** [comment]
You have an IP ban

**Comment by MichaelJ27** [comment]
how can i fix this?

**Comment by sennz7** [comment]
same me too like that,help pls

**Comment by MichaelJ27** [comment]
closed it without fixing it
