### ISSUE TITLE
Can't get rid of IP Ban

### ISSUE THREAD

**Issue by thelemonenergy** [NECROBOTIO/NecroBot#4609]
I tried default config, my config, any versions and multiple VPNs.
(VPNs are working, the IP shown in the bot changes)

But i can never find any Pokestops. When I switch to another VPN i can sometimes farm for 2 minutes.
In the Adroid App there are Pokestops and no Softban

Im using OkayFreedom for VPN
And it is only one client in my network

**Comment by nfettinger** [comment]
Please use Discord chat for help regarding general questions, and ALL configuration issues.
The VPN is probably getting its IPs banned.

**Comment by vsera** [comment]
I am going through the same issues and can't get the bot to work at all on any ip

**Comment by Venin87** [comment]
same here

**Comment by vsera** [comment]
I got it to only work on my old accounts. My new ones do not work at all for some reason.

**Comment by thelemonenergy** [comment]
To confirm that it is not only the VPN Servers of common VPN software, I tried it with a VPN to another Network of mine, where definitely never was played Pokemon go in before. Same issue

**Comment by vsera** [comment]
I now got it to work on one of my new accounts, but soon stopped working. And my old accounts just stopped working also. Seems like Niantic is catching the IP's fast as hell/: Might be ending

**Comment by thelemonenergy** [comment]
You who share the problem, ´do you also have super fast internet, like 100Mbits ore more? Maybe too much API calls?

**Comment by vsera** [comment]
It's been working fine for me for the past 16 hours straight with 1 account, but with 2 I was only able to do it for 1-2 hours before I got the temporary IP ban. But just make SURE you have "FastSoftBanBypass" set to "true".
