### ISSUE TITLE
No pokestops in the area

### ISSUE THREAD

**Issue by Mikajac** [NECROBOTIO/NecroBot#4611]
Since a few updates, my bots keep saying that there are no Pokestops near them and ask me if the range is wide enough. It used to work without problems a few updates ago.

**Comment by TheBorna** [comment]
Not a bot issue, niantic added ip bans recently.

**Comment by BlackWaltz89** [comment]
Same here,

**Comment by cesarbecerra** [comment]
So i need to change my ip? to make it work?

**Comment by temel38** [comment]
change your ip adress using vpn/proxy or wait a couple hours.

**Comment by nfettinger** [comment]
Please use Discord chat for help regarding general questions, and ALL configuration issues.
