### ISSUE TITLE
Manual Locations Sniping doesn't work

### ISSUE THREAD

**Issue by Profetorum** [NECROBOTIO/NecroBot#4613]
According to: https://github.com/NECROBOTIO/NecroBot/wiki/Manual-Locations-Sniping-Guide

>  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.015,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
>

![image](https://cloud.githubusercontent.com/assets/20842205/17558363/a10121da-5f1a-11e6-80ed-8aa3ea6b5864.png)

Never goes to a snipe location

**Comment by nfettinger** [comment]
Please use Discord chat for help regarding general questions, and ALL configuration issues.
You are not making a bug issue, or a feature request. Therefore, you are wasting our time.
