### ISSUE TITLE
why trnsfrd got wrong??

### ISSUE THREAD

**Issue by luxhakim** [NECROBOTIO/NecroBot#4616]
![screenshot_2](https://cloud.githubusercontent.com/assets/20949058/17558641/84a86d24-5f45-11e6-8eea-95e51a902a32.png)

**Comment by DemonCow5761** [comment]
Probably keeping because it's your highest IV and you have it set to keep IV above 90% would be my guess.

**Comment by nfettinger** [comment]
We cannot help with Configuration issues here. Please use Discord chat.
