### ISSUE TITLE
Red lines after sniping

### ISSUE THREAD

**Issue by ExarSenpai** [NECROBOTIO/NecroBot#4617]
Why am I encountering red lines after some time from starting the bot? They are usually appearing after sniping. Checked the issues before, no one is complaining about server being off  
![sniper](https://cloud.githubusercontent.com/assets/20814692/17558751/f09d4eca-5f1b-11e6-8be1-90a7ea6fb420.png)

**Comment by nfettinger** [comment]
Duplicate #3295
