### ISSUE TITLE
Lucky eggs arent used

### ISSUE THREAD

**Issue by Artixia** [NECROBOTIO/NecroBot#4618]
Hi, 

I dont know why lucky eggs arent used, config should be ok :/
"EvolveAllPokemonWithEnoughCandy": true,
"EvolveKeptPokemonsAtStorageUsagePercentage": 99.0,
"KeepPokemonsThatCanEvolve": true,
"UseLuckyEggConstantly": false,
"UseLuckyEggsMinPokemonAmount": 100,
"UseLuckyEggsWhileEvolving": true,

Bot tell me that i can evolve 130 pokemons, why they have not evoluated at 100 ?
When the 99 % was reached, the bot starts evolution without lucky eggs, why ? 

Thanks

**Comment by nfettinger** [comment]
We cannot help with Configuration issues here. Please use Discord chat.

**Comment by mastermike1011** [comment]
Yes, it is a setting issue, there is a space where you can alter the "evolved pokemon" used for upgrading. Just scroll through the entire list.

**Comment by Artixia** [comment]
I have a list with evolved pokemon, but what does that have to do with this ?
