### ISSUE TITLE
Can't find ANY Pokéstops at all

### ISSUE THREAD

**Issue by senic35** [NECROBOTIO/NecroBot#4620]
Doesnt matter what coords i tried, doesnt matter how high i set the max distance to, i still cant seem to find any pokestops at all. The bot is stuck in a loop for that reason. Can anyone help me if im just way too stupid or is my config f'ed up in any way? Or is it something completely other than that, Thanks for any help. 
![image](https://cloud.githubusercontent.com/assets/18623619/17558958/b1732890-5f1c-11e6-9513-202200502086.png)

**Comment by senic35** [comment]
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/411438/config.txt)

**Comment by feroniameimei** [comment]
re-download -> use vpn/proxy to change ip address -> start bot

**Comment by TheBorna** [comment]
You are ip banned.

**Comment by nfettinger** [comment]
We cannot help with Configuration issues here. Please use Discord chat.

**Comment by cacacap** [comment]
see this #4511

**Comment by senic35** [comment]
my other bot i have running is working fine, the necrobot runs on a proxy already

**Comment by cacacap** [comment]
Change the proxy maybe? Niantic had blacklisted vpn/proxy too many. Or just dont use proxy
