### ISSUE TITLE
auth.json

### ISSUE THREAD

**Issue by sjlarowe** [NECROBOTIO/NecroBot#4621]
Not a user specific issue, but rather the auth.json file for everyone

It reproduces some specs of an emulated device, so if you happen to share this file with a friend, Niantic servers will spot it, causing one of the bots or both bots to stop working.

Was thinking is there a way to add a wizard at the beginning that allows you to input your specific device model and information, that way everyone's bot would match their device they use to play the game.

The only other issue I can see happening here would need to spoof the IP address for the mobile data to play the game, rather than seeing a known IP prefix for a wi-fi location: 

Example: Comcast uses 10, 67, 69, etc for the prefix of IP addresses.

**Comment by nfettinger** [comment]
That is outside the scope of the bot. Please use whatever platform you have to set this up manually.
