### ISSUE TITLE
Not Eneugh Loot Pokestop on the bot

### ISSUE THREAD

**Issue by mucro9** [NECROBOTIO/NecroBot#4622]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by nfettinger** [comment]
I dont understand what your issue is.

We cannot help with Configuration issues here. Please use Discord chat.

**Comment by sianyuw7** [comment]
icant open discord ,

**Comment by Unentertained** [comment]
I get it, you are trying to be helpful by suggesting that we use a template for users submitting issues (albeit mildly sarcastic by using an intentionally mistyped title).

But this request/information should go in the wiki not in our issue feed.
