### ISSUE TITLE
the bot is not finding any pokestops in my area, how can I fix this issue ??

### ISSUE THREAD

**Issue by gab2ms** [NECROBOTIO/NecroBot#4625]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by 20giis** [comment]
what's the meaning of this post..? you want the "Issue" section deleted?

**Comment by sjlarowe** [comment]
You are likely IP banned, Niantic is getting aggressive again

**Comment by nfettinger** [comment]
Your IP is banned. wait 10 minutes or get a new one.

**Comment by ruchern** [comment]
What is this? I am actually giggling on this post.
