### ISSUE TITLE
Ignore not working???

### ISSUE THREAD

**Issue by Jinnocid** [NECROBOTIO/NecroBot#4628]
![image](https://cloud.githubusercontent.com/assets/20916720/17559702/c30b2366-5f51-11e6-8579-40c93f1a24d3.png)

![image](https://cloud.githubusercontent.com/assets/20916720/17559708/c7a38008-5f51-11e6-8011-db3351064101.png)

**Comment by Simpuhl** [comment]
Do you have the option to use the ignore list set to true?

**Comment by Jinnocid** [comment]
tried to find those where are they located at the config?

**Comment by head0r** [comment]
You need to clear it also from the Pokemon to snipe list...
Far at the bottom, the list begins with "Pokemon": [

**Comment by nfettinger** [comment]
This is a known issue, closing as duplicate.
