### ISSUE TITLE
soft ban with new version

### ISSUE THREAD

**Issue by diester** [NECROBOTIO/NecroBot#4635]
**French** :

bonjour, je subis un soft ban avec la nouvelle version de necrobot, pourtant j'ai bien dans ma config la ligne : 

 "FastSoftBanBypass": false,

je ne me suis pas téléporter en direct, j'ai attendu 2 heure avant de changer de point de spawn ( qui sont espacer de  2 heure en déplacement normal ) 

qui peut me dire la raison ?

**english** :

hello, I suffered a soft ban with the new version of necrobot, yet I am in my config line:

  "FastSoftBanBypass": false,

I did not teleport live, I waited two hours before changing spawn point (which space of two hours in normal displacement)

who can tell me the reason?

**Comment by andri0331** [comment]
If only using 1 instance, it was ok, I try with 2 bot running, then it immediately show soft ban, but after 5 minute I try again run 1 bot it working again, but after 10 minutes, i run another bot, then it started to softban again, so the conclusion is if only run 1 bot it was no problem

**Comment by nfettinger** [comment]
Please take general questions and configuration issues to our Discord chat rooms. We cannot help you here.

**Comment by smoothrunnings** [comment]
1 ID to 1 IP. The servers were updated to this last night, so there is nothing wrong the bot.

**Comment by diester** [comment]
I asked just made in the question because I did not find answer in the forum. but the answer was to (1 bot only) 2 because it is a soft ban.

désoler I use the forum because I do not speak English and that the live chat that is too complicated to read and reply because I use a translator

thank you for your interest and your answers
