### ISSUE TITLE
Wrong player name

### ISSUE THREAD

**Issue by ortreum** [NECROBOTIO/NecroBot#4637]
Hello,

my googlemail address is like name123@googlemail.com. But my player name is something like YouDontKnow. The bot's name is name123 (level 0) and not YouDontKnow (level 12).
Please add a field in the auth.json to make this editable if you can not access it otherwise.

Michael

**Comment by nfettinger** [comment]
Please take general questions and configuration issues to our Discord chat rooms. We cannot help you here.

**Comment by nfettinger** [comment]
The player name is given by the server. We display what we are given

**Comment by ortreum** [comment]
But it is not the same player ...
