### ISSUE TITLE
permanent ip ban??? 

### ISSUE THREAD

**Issue by erich91** [NECROBOTIO/NecroBot#4638]
On my phone (connected to wifi) I havent been able to see pokestops, pokemon, nor gyms, for over 12 hours. If I disconnect from my wifi they pop up fine! Seems like Niantic is handing out permanent IP bans!

**Comment by nfettinger** [comment]
Please take general questions and configuration issues to our Discord chat rooms. We cannot help you here.

**Comment by Gladi0n** [comment]
works fine for me, pokestops dissapeared and are back now
