### ISSUE TITLE
Can't fin pokestops

### ISSUE THREAD

**Issue by smenty** [NECROBOTIO/NecroBot#4644]
bot is looking for pokestops and cant find it, already changed coordinates and distance to walk but did not work. server problem? it is happening all my acc

also like to know if someone could help me how to set up for the bot to get and keep 2 Pokemon of each evolution as an example bulbasaur 2  Ivysaur 2 venusaur 2 and when a third fourth or fifth maintain two strong and transfer the weaker

ty

### Other Information
Version:  0.8.5
Windows Version: w10

**Comment by Krome333** [comment]
Ur Ip is ban ... i can't use more than 1 bot now without been banned

**Comment by robertwilianto** [comment]
it happening to me also. what can i do ?

**Comment by mdoza86** [comment]
did you try to change the walking speed. maybe softban,. Also, there is a config setting to keep 2 copy = 2 pokemon.

  "KeepMinDuplicatePokemon": 1,

**Comment by robertwilianto** [comment]
walking speed is 50

**Comment by Aumis** [comment]
How long dose the ban last?

**Comment by robertwilianto** [comment]
"WalkingSpeedInKilometerPerHour": 50.0,
"KeepMinDuplicatePokemon": 1,

**Comment by mdoza86** [comment]
Change your walkin speed to 16 ( default in new version). After the update Niantic is banning if your walk is too fast...  soft ban may last between 16-30 min. try it and let me know.. i works good for me. slower but good

**Comment by Aumis** [comment]
i seem to be back up  ty modoza86

**Comment by robertwilianto** [comment]
not working, still same " no usable pokestops found in your area"

**Comment by mdoza86** [comment]
@robertwilianto that's weird. what version of necrobot are you using?

**Comment by robertwilianto** [comment]
@mdoza pity.., v0.8.5

**Comment by mdoza86** [comment]
@robertwilianto if your walking speed and distance are normal. it should work. try changing your coordinates too. It is working fine for me

**Comment by robertwilianto** [comment]
It's work now, thx. That softban coz walking speed.

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 11, 2016 at 0:08, mdoza86<notifications@github.com> wrote:   
@robertwilianto if your walking speed and distance are normal. it should work. try changing your coordinates too. It is working fine for me

**Comment by mdoza86** [comment]
great!
