### ISSUE TITLE
Attention! There are no pokestops nearby. 

### ISSUE THREAD

**Issue by Ragbeez** [NECROBOTIO/NecroBot#4645]
Currently I have version 0.8.5.

If i start the bot I get the following error : 
There are no pokestops nearby, maybe your reach is to small. 

In the config.json document the MaximumTravelDistance is set to 10000. Also I have tried to set it to 500, 1000, 20000 and 30000 but it won't work. 

The error appears immediatly and keeps popping up. 

Sometimes out of nowhere the bot works for 30minutes and then gives the error again. 

Any solutions ??

**Comment by vyshu007** [comment]
do you use multiple bots?

**Comment by javonjw** [comment]
I was having the same issue but it just started working again like 5 min ago not sure what the setback was

**Comment by Wcidd** [comment]
change coords

**Comment by Ragbeez** [comment]
@vyshu007 

Right now I try to run it with 1 bot. Yesterday i had 2 bots running and everything worked fine.

**Comment by smoothrunnings** [comment]
You have been soft banned. Only 1 bot per 1 IP.  You can't run multiple bots anymore unless you are using Vmware and have a VPN service like HMA.

**Comment by willbp** [comment]
I have a same error @Ragbeez 
i need a solution too

**Comment by Ragbeez** [comment]
@smoothrunnings 

How long does it take for a softban to dissapear ?

**Comment by willbp** [comment]
I change coords and fail

**Comment by smoothrunnings** [comment]
@Ragbeez if your IP is Soft banned you must wait 1 hour before you can start playing again.

**Comment by Ragbeez** [comment]
@smoothrunnings Allright, probably a softban then.. I will check again in one hour and report it here. 

Thanks

**Comment by willbp** [comment]
@smoothrunnings send your coords?

**Comment by KillerOffers** [comment]
My solution was to change the location in config.
went to central park NY and it works fine now!
heres the Lat and Long at       40.77113	-73.97419
Paste Lat and Long in place of current location.

**Comment by Ragbeez** [comment]
@KillerOffers Thankyou, will also try this. I assume moving from the netherlands to NY is to obvious ?

**Comment by vyshu007** [comment]
guys, anyone using snipe feature?

**Comment by Ragbeez** [comment]
@vyshu007 Nope

**Comment by Ragbeez** [comment]
Solved, 2 bots on the same IP = Softban for one hour. !

**Comment by willbp** [comment]
@Ragbeez for me 2 bots on the same ip are running OK now. 
@KillerOffers  thanks solved for me, nice coords

In the moment the problems were solved.
>for me

**Comment by Ragbeez** [comment]
@willbp Same ip different devices or at the same device ?

**Comment by willbp** [comment]
@Ragbeez same ip in same device

**Comment by willbp** [comment]
Now the 2 bot's down. 

They were Running for 1 hour without problems
