### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by rahim3000** [NECROBOTIO/NecroBot#4646]
The bot transfered al my pokemons

**Comment by Aneduna** [comment]
Configuration Issue.

Also: When you created your issue. There was Text in the Textbox. Read it!

**Comment by antoinevastel** [comment]
You need to check config.json and adapt the parameters

**Comment by yonrin** [comment]
no bug, check your config

**Comment by nfettinger** [comment]
We cannot help you with that here, Please use Discord chat for further assistance.

**Comment by yonrin** [comment]
rekt

**Comment by Freestyleyang** [comment]
Me too. I did change anything about the bot, but it is now transferring all my pokemons. Does any know how to fix this?

**Comment by yonrin** [comment]
@Freestyleyang use my config and https://www.diffchecker.com/ to check the difference. Change what seems to cause the problem. 


{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 20,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 1,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 40.773481251816435,
  "DefaultLongitude": -73.973039388656616,
  "WalkingSpeedInKilometerPerHour": 80.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 2000,
  "DelayBetweenPokemonCatch": 1000,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 100.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 1800,
  "KeepMinIvPercentage": 98.0,
  "KeepMinLvl": 35,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "CentralPark_Period.gpx",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": true,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 100,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 150,
  "MinPokeballsWhileSnipe": 20,
  "MinDelayBetweenSnipes": 1000,
  "SnipingScanOffset": 0.75,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 10,
  "MaxTravelDistanceInMeters": 20000,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 0,
  "TotalAmountOfRevivesToKeep": 0,
  "TotalAmountOfBerriesToKeep": 150,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": true,
  "NiceThrowChance": 60,
  "GreatThrowChance": 40,
  "ExcellentThrowChance": 20,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "abra",
    "bellsprout",
    "rattata",
    "oddish",
    "poliwag",
    "machop",
    "geodude",
    "gastly"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {},
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by Freestyleyang** [comment]
@yonrin Thank you so much for the code. Now it is working and I really appreciate your kind help. By the way, the config in the `release` is wrong.

**Comment by yonrin** [comment]
@Freestyleyang no problem, but since it is my personal config it might have some values that you do not wish to have

**Comment by yonrin** [comment]
"KeepMinDuplicatePokemon": 0, should be set to 1. That's why it transfer pokemons that are below requirements no matter what.

**Comment by Freestyleyang** [comment]
@yonrin  You are totally right, and I do not know why this "KeepMinDuplicatePokemon: 0" error exists in the original `release`. I have lost many high CP pokemons. By the way, walking speed is too high, and I am afraid that it may be detected by the pokemon company. You may consider to reduce it a little. Thanks.

**Comment by yonrin** [comment]
@Freestyleyang 
"KeepMinCp": 1800,
"KeepMinIvPercentage": 98.0,
"KeepMinOperator": "or",

These are really important if you have set "KeepMinDuplicatePokemon: 0". If a pokemon is under 1800cp or 98iv it transfer it. If you have "KeepMinDuplicatePokemon: 1" you always have the best of that pokemon, unless you get two pokemons with either over 1800cp or 98iv. after using the bot for a while "KeepMinDuplicatePokemon doesn't matter that much, as you are going to have captured extremely high cp and iv pokemons.

**Comment by yonrin** [comment]
edit: if you have to pokemons over the desired mincp/iv it keeps both of them

**Comment by Freestyleyang** [comment]
@yonrin Thank you for the explanation.
