### ISSUE TITLE
pokestop

### ISSUE THREAD

**Issue by steponme** [NECROBOTIO/NecroBot#4647]
wy does it say no useable pokestop nearby?

**Comment by sianyuw7** [comment]
same problem, i dont find solution

**Comment by SnowBoard12** [comment]
It's probably cause of a softban. I got the same problem. Every time I run my bot for 2 a 3 mins I get a softban and all the pokestops are gone. It happens when talking to a pokestop. Not sure how or why it happens.

**Comment by Rick058** [comment]
That indicates that you are soft banned. If you are running more than 2 bots, please don't unless your proxy is correctly configured. Use a VPN te get rid of the softban loop of no usable PokéStops nearby.

**Comment by sianyuw7** [comment]
what vpn you use ? please give me link download

**Comment by KillerOffers** [comment]
Location LAT and LONG must be changed in order for POKESTOPS to work.
I put in for Central Park NY at:
40.77113	-73.97419
Copy and paste over current CONFIG. LOCATION 
Save then Reenter Bot.
Worked for me!

**Comment by sianyuw7** [comment]
not workig for me

**Comment by Rick058** [comment]
Pretty much every free VPN is currently in use by the people who know the method by now... Looks like it's no longer a 100% working method, should've kept it to myself :p. Proxy is the best option after that.
