### ISSUE TITLE
The bot is transferring all my pokemons!

### ISSUE THREAD

**Issue by Freestyleyang** [NECROBOTIO/NecroBot#4651]
I am using the latest version and I did not change anything about the bot. But, the bot is now transferring my highest CP pokemon.  Is there a solution? Thanks a lot.
![qq 20160810103008](https://cloud.githubusercontent.com/assets/20953347/17562040/217c06a2-5ee6-11e6-95db-e20e124070bc.png)

**Comment by nfettinger** [comment]
This is a configuration issue. Please use Discord chat, we cannot help you here.

**Comment by huCyy** [comment]
New update is resetting the custom made config file. so please edit it. 

make sure you have,

"KeepMinDupicate:" 1,
