### ISSUE TITLE
  "EvolveAllPokemonWithEnoughCandy": true = doesnt work

### ISSUE THREAD

**Issue by f0xie** [NECROBOTIO/NecroBot#4653]
### Expected Behavior
Make it work? ;/

### Actual Behavior
I set the auto evolve with enough candy and it still ignores it transferring pokemons no matter if i got 20 candies or 2k.

### Your config.json
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
### Steps to Reproduce
I'm not sure but i think aditional check to the post catch to evolve should made the deal?

### Other Information
Version: 0.8.5
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):evolve

**Comment by nfettinger** [comment]
I verified that it is working.
This is a configuration issue. Please use Discord chat, we cannot help you here.
