### ISSUE TITLE
Did Not Find a Pokemon within the location, pokemon despawned? 0.8.5

### ISSUE THREAD

**Issue by IamtheTitan** [NECROBOTIO/NecroBot#4656]
Keep getting this message.

Worked fine all morning updated to 0.8.5

Screenshot here: 
![d441cbdc4af0e86a5c6cad10402d335c](https://cloud.githubusercontent.com/assets/20945444/17562121/39de1cea-5f21-11e6-8064-d2ba28893e33.png)

**Comment by nfettinger** [comment]
Duplicate issue.
