### ISSUE TITLE
Where can i get a Proxy Server?

### ISSUE THREAD

**Issue by TheWaah** [NECROBOTIO/NecroBot#4659]
I want to multi bot but i dont know how to get a proxy host ? Has anyone here a site for free proxy host? Or must i download i program?

**Comment by Lord-Haji** [comment]
dont make useless issues of this dammit
its ur personal problem
Dont flood issues for this
It isnt a coding bug rather a needed improvement
CHeck guidelines before u create a issue

**Comment by Rick058** [comment]
Ever heard of Google? https://www.google.nl/search?q=free+proxy+list
You can request help in the Discord channel as well.

**Comment by Lord-Haji** [comment]
wtf man
try out this @TheWaah 
this works pcool
http://lmgtfy.com/?q=free+proxy+list
