### ISSUE TITLE
Suggestion: reverse traversal of GPX path?

### ISSUE THREAD

**Issue by GoGoDong** [NECROBOTIO/NecroBot#4661]
If I'm understanding it correctly, in current versions we should set the start point and end point close, otherwise a sudden location change may cause soft ban.

But drawing a gpx file is a bit tiring, especially when you forgot to save and get browser crashed.... :( I'm hoping if we could have an option like "reverse traversal of GPX path", then we can draw only half gpx file!

**Comment by nfettinger** [comment]
This is a needless complexity. Simply reverse the order in your GPX file.
