### ISSUE TITLE
HELP ME FIX THIS

### ISSUE THREAD

**Issue by patoroko** [NECROBOTIO/NecroBot#4666]
[13:49:01] (UPDATE) Perfect! You already have the newest Version 0.8.5
[13:49:01] (INFO) Logging in using Google
[13:49:01] (INFO) Your IP is: XXXXXXXXXX
[13:50:46] (INFO) System.Threading.Tasks.TaskCanceledException: Uma tarefa foi c
ancelada.
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next() na C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Exte
nsions\HttpClientExtensions.cs:linha 98
--- Fim do rastreamento de pilha do local anterior onde a exceÃ§Ã£o foi gerada -
--
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() na C:\Users\
ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:linha 86

--- Fim do rastreamento de pilha do local anterior onde a exceÃ§Ã£o foi gerada -
--
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() na C:\Users\ciamo
\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:linha 89
--- Fim do rastreamento de pilha do local anterior onde a exceÃ§Ã£o foi gerada -
--
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() na C:\Users\ciamo\S
ource\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:linha 44
--- Fim do rastreamento de pilha do local anterior onde a exceÃ§Ã£o foi gerada -
--
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() na C:\Users\
ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:linha 35
[13:51:06] (INFO) Logging in using Google

**Comment by MrProblematic** [comment]
Tenta dar uma olhada na sua config.json .. Vc pode ter mudado algo lá diferente do que o programa pode compilar...

**Comment by nfettinger** [comment]
We can only help people who use english.
Duplicate #3723
