### ISSUE TITLE
bot crashes after using proxy

### ISSUE THREAD

**Issue by Rashk999** [NECROBOTIO/NecroBot#4669]
hello i want to ask where i made a mistake

![in](https://cloud.githubusercontent.com/assets/20931806/17562687/2f1f922e-5f2c-11e6-919f-1a9fff5fc195.jpg)

made proxy to true, then ip add and port number

**Comment by Rick058** [comment]
Can you show auth.json, how did you fill in the proxy part?

**Comment by Rashk999** [comment]
{
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "...",
  "PtcPassword": "...",
  "UseProxy": true,
  "UseProxyHost": 192.126.123.36,
  "UseProxyPort": 8118,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "galaxy-tab3",
  "DeviceId": "46af4915da775644",
  "AndroidBoardName": "smdk4x12",
  "AndroidBootloader": "T310UEUCOI1",
  "DeviceBrand": "samsung",
  "DeviceModel": "SM-T310",
  "DeviceModelIdentifier": "lt01wifiue",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "SM-T310",
  "FirmwareBrand": "lt01wifiue",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/lt01wifiue/lt01wifi:4.4.2/KOT49H/T310UEUCOI1:user/release-keys"
}

**Comment by Rick058** [comment]
```
"UseProxy": true,
"UseProxyHost": 192.126.123.36,
"UseProxyPort": 8118,
```

Should be:
```
"UseProxy": true,
"UseProxyHost": "192.126.123.36",
"UseProxyPort": "8118",
```

**Comment by Rashk999** [comment]
![in2](https://cloud.githubusercontent.com/assets/20931806/17563123/1db5f044-5f2e-11e6-8789-9632df40c933.jpg)

**Comment by Rick058** [comment]
Then your proxy doesn't work, try another proxy address? 
Having the same issues, took a while before I found a good working proxy.
For so far I know HTTPS proxies do work, did not test SOCKS5.

**Comment by Rashk999** [comment]
its okay to use for example ip from germany and location in france?

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
