### ISSUE TITLE
The bot is transferring all my pokemons!

### ISSUE THREAD

**Issue by Freestyleyang** [NECROBOTIO/NecroBot#4676]
I did not change anything about the config, but it is transferring all my pokemons. Any solution? 
![qq 20160810103008](https://cloud.githubusercontent.com/assets/20953347/17562998/94f084b0-5eea-11e6-8381-c8715191c098.png)

**Comment by boolhool** [comment]
set "TransferDuplicatePokemon" to false

**Comment by Freestyleyang** [comment]
The transferred pokemons are unique, there is no duplicate.

**Comment by Rick058** [comment]
`  "TransferWeakPokemon": false,`
Is ^ on false or true?

**Comment by BMaae4** [comment]
Check the IV config for Pokémon transfer. I think default is 90 I believe.

**Comment by solenrus** [comment]
same thing happened to me, it competely ignored these settings and just kept 1 of each:
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

latest master, it felt like   "KeepMinDuplicatePokemon": 1, just overrid everything else.

**Comment by Freestyleyang** [comment]
I just checked, "KeepMinIvPercentage": 90.0

**Comment by BMaae4** [comment]
I believe that is why it it transferring you Pokémon. They are below 90% perfect IV.

**Comment by cacacap** [comment]
NO. set "TransferDuplicatePokemon" to 1 so it become
"TransferDuplicatePokemon": 1

**Comment by HipsterBwP** [comment]
So, if we don't use the source code we just have to wait for a new update I'm assuming?

**Comment by cacacap** [comment]
no update for it. just change it on config

**Comment by solenrus** [comment]
"TransferDuplicatePokemon": true,
is not longer true or false, but a number? what? @cacacap

**Comment by HipsterBwP** [comment]
How?

**Comment by cacacap** [comment]
thats my fault hehe
"KeepMinDuplicatePokemon": 1, @solenrus 
@HipsterBwP just find the config.json on config folder. edit it using notepad, you had it on your computer dont u? then change the number on "KeepMinDuplicatePokemon": 1. it means you only had 1 pokemon qty each. the "KeepMinDuplicatePokemon" value it belongs to what you set on "PrioritizeIvOverCp". true if you need iv and ignore cp, false for ignore iv and save the cp. nvm just keep it 'true'

**Comment by HipsterBwP** [comment]
@cacacap so if I set the value of 'KeepMinDuplicatePokemon' : 3 it will keep 3 of each?

**Comment by cacacap** [comment]
Yes, but if the value is 3 u need to manage ur pokemon inventory often. Bc it will always full

**Comment by HipsterBwP** [comment]
@cacacap It's still transferring out stuff, like unique, High CP Pokes even after I made that change.

**Comment by Freestyleyang** [comment]
Me too.

**Comment by cacacap** [comment]
alright if you dont wanna transfer anything on your pokemon too fill up the empty space for bot working, just set "TransferDuplicatePokemon" : false. @HipsterBwP  @Freestyleyang

**Comment by cacacap** [comment]
bot transfered what u dont need as what is written on config.json. pls had a backup first of the config. so when u had wrong command, u still had another to bring back the setting
