### ISSUE TITLE
Softban was done by blocking our IP temporarity by niantic. Please allow the code which is can enabled the TelNet automatically for windows and run the Modem/Router Reboot Script to renew the IP.  "Option explicit Dim oShell set oShell= Wscript.CreateObject("WScript.Shell") oShell.Run "telnet" WScript.Sleep 3000 oShell.Sendkeys "open 192.168.254.254~" WScript.Sleep 3000 oShell.Sendkeys "username~" WScript.Sleep 3000 oShell.Sendkeys "password~" WScript.Sleep 3000 oShell.Sendkeys "reboot~" WScript.Sleep 3000 oShell.Sendkeys "~" Wscript.Quit"

### ISSUE THREAD

**Issue by pisocoin** [NECROBOTIO/NecroBot#4677]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Rick058** [comment]
You are soft banned, also ONE 'issue' is more than enough...
Use VPN/Proxy to get rid of it and close all your spam issues, thanks.

**Comment by smoothrunnings** [comment]
@pisocoin You were soft banned. Learn to be wiser and use multiple machines with some kind of VPN service installed on each.
