### ISSUE TITLE
my work's proxy firewall blocking the bot

### ISSUE THREAD

**Issue by Ferelpis** [NECROBOTIO/NecroBot#4678]
My work's proxy firewall that im having internet only that way. (no other option) blocking the bot. Any ideas to connect??? 

ps  : i've tried to connect through "hotspot shield" and i cant too

**Comment by smoothrunnings** [comment]
@Ferelpis  Speak to your local network admins. They are the only ones who can let you through!

**Comment by Ferelpis** [comment]
@smoothrunnings that is not an option......

**Comment by pehur** [comment]
Just use teamviewer to run it on your pc/laptop at home.. can even control it on your phone this way!

**Comment by Ferelpis** [comment]
.....................................................................  no comment

**Comment by Ferelpis** [comment]
any serious idea how to bypass proxy restriction?

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
