### ISSUE TITLE
(PokeSnipers.com) One or more errors occurred.

### ISSUE THREAD

**Issue by Squatching** [NECROBOTIO/NecroBot#4680]
[13:20:36] (PokeSnipers.com) One or more errors occurred.

**Comment by spamfighter82** [comment]
well if you try to go to their site you get an DNS error, guess they are down, not a necrobot issue

**Comment by Hectorite** [comment]
i got the same issue and their website works fine

**Comment by adman9031** [comment]
their website is down for me

**Comment by adman9031** [comment]
has been for over an hour

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
