### ISSUE TITLE
Total amount of different Pokeballs to keep

### ISSUE THREAD

**Issue by Apexcery** [NECROBOTIO/NecroBot#4681]
Instead of just having the option to keep the total amount of Pokeballs, it might be a good idea to have options for each of the different versions. I don't know if anyone else is having the issue but by leaving the bot running, it tends to transfer the normal Pokeballs as the "TotalAmountOfPokeballsToKeep" is made up of the better versions, resulting in using Ultraballs to catch things that would not otherwise use one.

**Comment by EmperorPidgey** [comment]
If you accumulate an inventory of nothing but ultra balls, why would it be a problem to use it on a weak monster?

**Comment by Apexcery** [comment]
I... never really thought of it like that, I just seen it as a waste
