### ISSUE TITLE
Where to set and fill PROXY SERVER

### ISSUE THREAD

**Issue by TaeTae01** [NECROBOTIO/NecroBot#4682]
Someone can tell me how to fill the proxy server
thank

**Comment by Rick058** [comment]
Proxy auth.json:
`  "UseProxy": true,`
`  "UseProxyHost": "xxx.xxx.xxx.xxx",`
`  "UseProxyPort": "xxxx",`

Replace xxx.xxx.xxx.xxx with your own Proxy IP and xxxx with Proxy Port.
If your proxy requires authentication be sure to fill in the information below as well, else ignore it.
`  "UseProxyAuthentication": true,`
`  "UseProxyUsername": "username",`
`  "UseProxyPassword": "password",`

**Comment by MrProblematic** [comment]
You can find some cool's proxys there> http://proxylist.hidemyass.com/
Just do what @Rick058 said.

**Comment by TaeTae01** [comment]
Thank everyone i can fix it with myself
thank again for all answer
For who have same problem with me
1.go to auth.json and EDIT it
2. @ Proxy auth.json:
"UseProxy": true,
"UseProxyHost": "xxx.xxx.xxx.xxx",
"UseProxyPort": "xxxx",
on xxxx you should find fake IP for proxy server  on this site  [http://www.freeproxylists.net/](url)
3.choose only one Proxy IP and Port
4.use Proxy ip you choose replace xxxxx @UseProxyhost
5.Use Port you choose replace xxxx @UseProxyPort
6.Save then Enjoy the bot

Thank

**Comment by jinkawasaki333** [comment]
Additional question:

What if some other people are using the exact same Proxy? Will it cause softban as well?

**Comment by MrProblematic** [comment]
yes.. hahahahaha

**Comment by Rick058** [comment]
@TaeTae01 Good to hear it works :)
@jinkawasaki333 Most likely yes, so it's better to use a proxy from a rather unknown site instead of the standard 'freeproxy' sites.

**Comment by kalesnor** [comment]
it says invalid proxy to me

**Comment by kalesnor** [comment]
do you have any example

**Comment by TaeTae01** [comment]
"UseProxy": True,
  "UseProxyHost": 124.244.xx.xxx,
  "UseProxyPort": 8xxxx,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

This is my example script and it work

**Comment by kalesnor** [comment]
thanks!!

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
