### ISSUE TITLE
My own Sniper locations dont work anymore

### ISSUE THREAD

**Issue by Hectorite** [NECROBOTIO/NecroBot#4683]
i have added alot of snipe coordinates by hand.
but the bot is not sniper there anymore.
anybody that can help me out here ?

**Comment by MrProblematic** [comment]
#4679

**Comment by TemhAAhmeT** [comment]
snipe feature is not working on me too at v0.8.5. Better to use v0.8.1

**Comment by berthojoris** [comment]
But using v0.8.1 error when set up is ready. Alwasy error "**You need to fill out GoogleUserName and GooglePassword in auth.json**"

What prompted by an error message already done at an early stage, and if the file is checked in auth.json, **username** and **password** are already filled. There is a solution?

**Comment by Hectorite** [comment]
well i am using v0.8.1 now .. but still he is not using my own sniper coords.

**Comment by MrProblematic** [comment]
try 0.70. here is working fine

**Comment by phparmand** [comment]
@berthojoris open config.json and switch "autoupdate" to false

**Comment by Hectorite** [comment]
ok i tryed v0.7.0 and there is actually no sniping going on... xD

**Comment by MrProblematic** [comment]
Working fine here...

My Config: http://pastebin.com/QMwEKEbV

Prove:
[![Sem título.jpg](https://s10.postimg.org/3w3t7ui6h/Sem_t_tulo.jpg)](https://postimg.org/image/8urbmdlz9/)

**Comment by MrProblematic** [comment]
BTW if someone have another configuration or idea for do more xp/h plz share. hahahaha

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
