### ISSUE TITLE
Error while sniping.

### ISSUE THREAD

**Issue by DieHoe** [NECROBOTIO/NecroBot#4684]
https://postimg.org/image/owiib9o2d/ get this error verry often... why??

**Comment by MrProblematic** [comment]
wich version u r using? the newest?

**Comment by Ansez** [comment]
I'm using the newest version and I experience the same.

**Comment by MrProblematic** [comment]
Try to use old version like 0.81 or 0.70 (im using 0.70)

**Comment by Naprosnia** [comment]
Same error here. with 0.8.5

**Comment by nfettinger** [comment]
Server or proxy issue.
Duplicate #3295

**Comment by Alker4753** [comment]
any links for version 0.7.0 ?
