### ISSUE TITLE
UseBerriesMin not work

### ISSUE THREAD

**Issue by snwsnwsnw** [NECROBOTIO/NecroBot#4685]
the bot sometimes use berry even cp 400 or iv 30

### my config.json
  "UseBerriesMinCp": 2000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",

Version: 0.8.5
Windows Version: win10 x64 home

**Comment by Petnavi** [comment]
It's the probability modifier that's causing it. Change modifier from or to and or you can lower the probability rate required. There's no perfect solution, you'll have to compromise.
