### ISSUE TITLE
Request Feature:- Show current level of trainer with total xp while running bot.

### ISSUE THREAD

**Issue by angeshpokharel** [NECROBOTIO/NecroBot#4687]
It would be better if we could see current level of trainer with total xp while running bot so need not open the app on mobile n check time to time.

**Comment by Pokemongobottttttt** [comment]
Isnt this already shown at the top the screen?

**Comment by random189268** [comment]
For me this is in the status window already.

**Comment by nfettinger** [comment]
Already implemented
