### ISSUE TITLE
Proxy Authentication Not Working (IP Invalid)

### ISSUE THREAD

**Issue by NightsDream** [NECROBOTIO/NecroBot#4689]
I bought some private proxy, they give me username and password to login (I have tried the proxy on my browser, it works perfectly)

I have also tried a public proxy without authentication, it is working too but when it comes to authentication part, it seem like not working (it shows IP invalid and a bunch of error coming)

This is the format I'm using for proxy part

  "UseProxy": true,
  "UseProxyHost": "172.98.1XX.X",
  "UseProxyPort": "2XXXX",
  "UseProxyAuthentication": true,
  "UseProxyUsername": "XX1556",
  "UseProxyPassword": "XXXX9X5X7X",

**Comment by Sameeeh** [comment]
try using a https proxy server because sock4/5 dont work with the bot

**Comment by dverlik** [comment]
Check if the proxy is a HTTPS type. Necrobot does not support socks proxies.
