### ISSUE TITLE
IP banned?

### ISSUE THREAD

**Issue by VCorleone** [NECROBOTIO/NecroBot#4692]
![unbenannt](https://cloud.githubusercontent.com/assets/20933763/17564631/59aa2fec-5f34-11e6-8297-f35dafbd801e.png)

Does the red color mean that my IP is banned? And, if so, how can I solve the problem?
Thank you!

**Comment by Nilcrazy** [comment]
Try to reset your internet modem

**Comment by Seyrenvox** [comment]
no. it's just telling your IP

**Comment by dverlik** [comment]
The red line only shows you your IP. The rest means your IP is softbanned.

**Comment by VCorleone** [comment]
what can I do?

**Comment by Seyrenvox** [comment]
do whatever you wanna do. enjoying life, maybe

**Comment by Squatching** [comment]
wait half hour or so no bot running works for me

**Comment by SDMU** [comment]
do a fresh install or use a vpn

**Comment by SDMU** [comment]
unless they have banned your mac id or something like that , it should solve your problem
