### ISSUE TITLE
Pokéstops

### ISSUE THREAD

**Issue by Jelle0162** [NECROBOTIO/NecroBot#4694]
Hi, i am using Necrobot for a day now and really enjoy it.
But there's 1 problem, my Necrobot does 80% pokestops and a little bit pokemons.
But I want to have more pokemons, and less pokestops, is that possible? Tried everything.

**Comment by smoothrunnings** [comment]
The object of the Necrobot is to do the work for you, it's not supposed to be run a long side your actual game or you could find yourself being banned.

**Comment by Jelle0162** [comment]
Yes i know, but because we have a config folder, i thought maybe you could edit that pokestops are becoming less and pokemon encounters are becoming more

**Comment by Jelle0162** [comment]
I litterally catch 1 pokemon in 2 minutes its going really slow..

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
