### ISSUE TITLE
User Credentials are Invalid

### ISSUE THREAD

**Issue by gl1129** [NECROBOTIO/NecroBot#4695]
what does it mean?

**Comment by Rick058** [comment]
That your login details in auth.json are incorrect

**Comment by monkeypandey** [comment]
your quotations might not be correct.
go to config->auth->and put the user name and password in ("")double inverted commas

**Comment by gl1129** [comment]
still not working

**Comment by Rick058** [comment]
please post your auth.json and remove your loginname & password with xxxx

**Comment by gl1129** [comment]
![ccc](https://cloud.githubusercontent.com/assets/20955137/17565796/f380e5a4-5f8c-11e6-83c9-c3c6b8071452.png)

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
