### ISSUE TITLE
Pokemon wont transfer

### ISSUE THREAD

**Issue by wildycardy** [NECROBOTIO/NecroBot#4696]
wont transfer duplicate pokemon...transferduplicatepokemononcapture is working tho

**Comment by Firedor** [comment]
Maybe your Minimum CP is 1250 and you have 250 pokes with 1500 cp. That happens to me. Check your pokes.

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
