### ISSUE TITLE
No Pokestops nearby

### ISSUE THREAD

**Issue by Olister** [NECROBOTIO/NecroBot#4698]
![image](https://cloud.githubusercontent.com/assets/20955207/17565248/ab65ed42-5f04-11e6-9bb7-af2ec89af3b9.png)

Getting the Min distance bug again? running V0.8.5 not sure why its doing this again :(

**Comment by OkancanCosar** [comment]
ip ban. u can use vpn

**Comment by rahim3000** [comment]
You cant use vpn i tried it to and it say im on the blacklist of niantic

**Comment by Olister** [comment]
So basically switch up my IP address should I just wait my ISP changes it automatically every hour or so

**Comment by monkeypandey** [comment]
technically yea...or we can even use different proxy servers

**Comment by muxahuk** [comment]
is there a posibility to integrate vpn in these bot ?
I'm kind of dumb and don't know hot to use vpn, but setting config to "use_vpn" : true i could..

**Comment by TaeTae01** [comment]
#4682
It your way

**Comment by skynetken** [comment]
server is down. i tried to log in.

**Comment by nfettinger** [comment]
We cannot integrate a VPN.
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
