### ISSUE TITLE
Transefering all my pokemons

### ISSUE THREAD

**Issue by jamesazwe** [NECROBOTIO/NecroBot#4701]
so after the new actualization it stopped logging me so ichecked the auth and mi google acc was errased, so i setted it up again and started playing , then i noticed it started transfering all mi pokemon not even counting the config for not to transfer the highest powered ones or the iv's, then i used my last config archive (replacing the new with the old) trying to fix that but didnt worked.

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.

**Comment by actislav** [comment]
there is in current version major bug with transfer someone who is implemented multimove list, make mistake in logic, and all clients with empty move list will lose all their pokemon
