### ISSUE TITLE
Warning when reseting the config.json

### ISSUE THREAD

**Issue by vacadude** [NECROBOTIO/NecroBot#4708]
Just a friendly warning when the upgrade is going to set the config.json back to default values.

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.

**Comment by M3NTALITY** [comment]
Still worth making everyone aware of.That's enough to ruin an account

**Comment by vacadude** [comment]
it's not a configuration issue, is so that the program when updating warns "this update will reset your configuration" in nice red letters. I'm sure that's not so hard to add...
