### ISSUE TITLE
Suggestion: Auto restart Bot after Crashing.

### ISSUE THREAD

**Issue by vincentchengws** [NECROBOTIO/NecroBot#4710]
The bot and the location snipper always crash after 1-2 hours.
Is there any application that can automatically restart bot again when the bot is crashed? Thanks.

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.

**Comment by vincentchengws** [comment]
@nfettinger No. it is not a configuration issue.
The configuration is good. but the bot is not stable sometimes. So after a while, it will crash. I know many people also have same problem
