### ISSUE TITLE
Add pikachu to default not transfer list

### ISSUE THREAD

**Issue by SaitDev** [NECROBOTIO/NecroBot#4711]
I take so hard to get a pikachu in real Pokemon Go (mobile).
And now I tried your bot, it's great. But by default, It transfers my ONLY ONE pikachu :cry: 
God, Niantic or any other body, bring the pikachu back to me :sob: 

### Steps to Reproduce

Run
Setup
StartAuto
*and lost your pikachu

### Other Information
Version: 0.8.5
Windows Version: 10 ver 1607
What is affected : transfer

**Comment by nfettinger** [comment]
You could have added him yourself.
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.
