### ISSUE TITLE
NecroBot Crashing at Startup after Enabling Telegram API

### ISSUE THREAD

**Issue by Aneduna** [NECROBOTIO/NecroBot#4713]
### Expected Behavior
Working Telegram Bot

### Actual Behavior
Crashing with AggregateExecption in Line 31 in TelegramService.cs

(Inner Exception is Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.)

### Your config.json
```
"UseTelegramAPI": true,
"TelegramAPIKey": "26------qr8",
```
Anything else from the config should not be relevant, because it only happens after setting UseTelegramAPI to true.
I am not using a proxy.

### Steps to Reproduce

Enable Telegram Bot
### Other Information

Latest Commit. Have not tried with latest release.
The Message from Botfather with the API key https://s.put.re/EoJ49v5.PNG censored api key

As for the ClonableExtensions.Clone.
I cloned the github fresh and it still happens.

This should not be a configuration issue as the bot created a different error message when the API key is malformed.

**Comment by nfettinger** [comment]
We cannot help you with configuration issues here. Please use our discord chat channels for additional help.

**Comment by Aneduna** [comment]
![image](https://cloud.githubusercontent.com/assets/9990060/17566518/ecd7d31a-5f65-11e6-992c-9684f0fce732.png)

**Comment by Aneduna** [comment]
thank you @nfettinger . Probably not even read the whole wall of text.

**Comment by Yedion** [comment]
I´ve got the same problem after enabling telegram

**Comment by ChemiHatake** [comment]
#4947 
this will make the telegram work 
and won't just prevent it from crashing.
