### ISSUE TITLE
Cant find any pokestops nearby, Error.

### ISSUE THREAD

**Issue by ABCLost** [NECROBOTIO/NecroBot#4718]
Im getting an Error highlighted in dark yellow with the message :
Cant find any nearby pokestops. Used the hack like halfhour before quited and restarted it and it gave me this error, already tried to change the beginning latitude and longitude
-
My config 
http://pastebin.com/CsEnrpkW

**Comment by nfettinger** [comment]
Your IP is banned.

**Comment by ABCLost** [comment]
And why am i ip banned?
