### ISSUE TITLE
Cyberghost "No pokestops found in your area"

### ISSUE THREAD

**Issue by albysprx** [NECROBOTIO/NecroBot#4720]
Hi, I'm getting "No pokestops found in your area" while using Cyberghost VPN, with my real IP everything is ok

**Comment by KuroHunter13** [comment]
same issue

**Comment by nfettinger** [comment]
Your IP is flagged and softbanned.

**Comment by nfettinger** [comment]
or your VPN IP

**Comment by KuroHunter13** [comment]
server down

**Comment by KuroHunter13** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by albysprx** [comment]
and what VPN are you using to get it working? I don't want to get my ip banned

**Comment by albysprx** [comment]
if anyone want to use Cyberghost just stop and start again to get a new IP
