### ISSUE TITLE
Config Explainations

### ISSUE THREAD

**Issue by AtomicLaser** [NECROBOTIO/NecroBot#4722]
Not an issue as such, but is there a more comprehensive manual for the config settings?

There's a lot of settings which aren't explained in the wiki; one example being:

> AmountOfTimesToUpgradeLoop

Would be nice to know more about what these settings are for rather than guessing!

**Comment by nfettinger** [comment]
We cannot help you with that here. Read the wiki and use Discord chat for help.

**Comment by AtomicLaser** [comment]
read the wiki, isn't there, but thanks for the great help.  

Would rather not have to go to discord as I need to create an account to post!

hmmmmft.
