### ISSUE TITLE
2 bytes Characters display in console window

### ISSUE THREAD

**Issue by artieas** [NECROBOTIO/NecroBot#4723]
Most famous 2 bytes character is Chinese.
It is written perfectly in log file, but is not displayed correctly in console window.
I'm not sure what is problem.
I'm asking you while I'm making Korean translation file.

Another problem is: when the dump monster's status, if monster's name is translated in 2 bytes characters, monster's name is displayed special characters combined with monster's level in same cell.

**Comment by nfettinger** [comment]
Duplicate issue
