### ISSUE TITLE
No usable pokestops.

### ISSUE THREAD

**Issue by winstonnolten** [NECROBOTIO/NecroBot#4730]
I know this is maybe the 99999999th issue reported about the "no usable pokestops" problem but even though i read some previous issues a lot of things are still not clear to me. 

Currently i am with 3 people on one network. We have three different computers (laptops). We all use bluestack to check our inventories and pokemons and we all use necrobot. We are all experiencing constantly the "no usable pokestops" issue. I am just guessing but... aren't we allowed to use 3 bots on 3 different pc's on one modem? and if we would only use one bot, does bluestack interfere necrobot which causes ip bans?

**Comment by willbp** [comment]
maybe softban wait 1 hour

**Comment by WuddyMarco** [comment]
Yes. a few hours ago you were able to use max 2 Bots at the same time. Now i have even problems using 2 and i´m back to one.
