### ISSUE TITLE
Searched with no answers Softbanned V0.8.5

### ISSUE THREAD

**Issue by Toke216** [NECROBOTIO/NecroBot#4731]
i Have searched with no resolution. Necro bot softbans after 5 min on newest update and i was wondering how to run 3 acts at once without getting a ip softban. ever since this program started showing the red ip address on stat up i get softbanned (No pokestops and no gyms type ban). please help im not a total newb to botting but im not sure what maybe causing all this. i have always selected y on every update is it a config issue were i have to restart from fresh config?
Thankyou anyone for any kind of help, i jus need some good answers thank you.

**Comment by nfettinger** [comment]
Use discord chat for help.
