### ISSUE TITLE
Bot stops working on wifi, no pokestop error.

### ISSUE THREAD

**Issue by k2ieger** [NECROBOTIO/NecroBot#4732]
Bot stops working on wifi, no pokestop error. When connected to different network (eg. Mobile hotspot )the pokestops reappear, This is happening with the app as well. is it possiblly ip ban ?

**Comment by smoothrunnings** [comment]
Your IP is soft banned, you need to wait 30 minutes to hour.

**Comment by smoothrunnings** [comment]
You can only play 1 bot per IP.. The servers don't accept 2 bots per IP anymore.

**Comment by k2ieger** [comment]
Thanks for the quick response, I am using only a single bot (i.e. only one account). I will wait for an hour or so and update if the issue persists.

**Comment by AndreasGilja** [comment]
No pokestopa awible

Sendt fra min iPhone

Den 10. aug. 2016 kl. 21.34 skrev k2ieger <notifications@github.com<mailto:notifications@github.com>>:


Bot stops working on wifi, no pokestop error. When connected to different network (eg. Mobile hotspot )the pokestops reappear, This is happening with the app as well. is it possiblly ip ban ?

-
