### ISSUE TITLE
Feature request: Walk away from a catch depending on cp/iv/moves

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#4735]
Currently the bot keeps sniping everything (based on the filters set which pokemon are ""wanted"") and using great/ultra balls by the dozen.

It would be great if you could filter the pokemon you really want and ignore the rest based on:
- Moves
- CP
- IV

`WalkAwayFromPokemon:true/false`
`WalkawayFromPokemonFilter: `will contain a lit of pokemon and when to walk away. This should work about the same as the transferfilter.

I don't know if the cp/iv and/or move values are available before a pokeball is thrown?

**Use-case (by example):**
I have several dragonites, but almost all with low iv and with the same moves.
Some i've levelled up a bit, some i haven't.
_Now i'm looking for dragonites with certain moves OR with higher cp/iv only._

Hope this is possible.

See also issue:

**Comment by nfettinger** [comment]
Duplicate issue

**Comment by deduijk** [comment]
OF case? because searching didn't turn up an existing case?!
