### ISSUE TITLE
Sniper ERROR

### ISSUE THREAD

**Issue by coelhots** [NECROBOTIO/NecroBot#4736]
My SNIPER bot begun to mistake a few minutes. Error by both site and search for skipedlagged.
Anyone know how fix this?

PRINT
![error](https://cloud.githubusercontent.com/assets/20956408/17568155/f61b6c90-5f18-11e6-84b0-2efad9fcf6a4.png)

**Comment by nfettinger** [comment]
Use Discord chat for help
