### ISSUE TITLE
(ATTENTION) No usable PokeStops found in youre area

### ISSUE THREAD

**Issue by ingoplaczek** [NECROBOTIO/NecroBot#4737]
Hello everybody,
i am using a free proxy, but after a hour i am getting the following error. Also by selecting a different proxy..

May someone else also got this problem?
![image](https://cloud.githubusercontent.com/assets/19225436/17568198/0e58f898-5f43-11e6-9ba4-c35716ec72ec.png)

Here's my config:

[config.txt](https://github.com/NECROBOTIO/NecroBot/files/411970/config.txt)

**Comment by eXj0k3r** [comment]
i have same problem...

**Comment by nfettinger** [comment]
Use Discord chat for help
