### ISSUE TITLE
Pokemon transfer!!

### ISSUE THREAD

**Issue by repelsteeltjehd** [NECROBOTIO/NecroBot#4738]
all my pokemons got transfered.. gonna switch from bot because you guys messed it all up

**Comment by nfettinger** [comment]
Use Discord chat for help

**Comment by Ezoteric** [comment]
@repelsteeltjehd no, you most likely messed with the config if not you should :P

**Comment by repelsteeltjehd** [comment]
lol, i updated from 7.8 and it started deleting all pokemon when updated to 8.5
