### ISSUE TITLE
Feature request: Configuration file split: filters to a seperate file?

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#4739]
I suggest moving the filters to a separate configuration file?; That's likely not to change from release to release, since that is more personal preference (unless options are added or changed for the filter, but then a filter example file can be included and the user can use that to implement his own filters again).

If the filters are switched over to xml they could be validated using an xsd and transformed with an xslt when new options are added or option (names) are changed.

And there is room for comments and grouping, so less error prone. (especially with xsd validation: can let the user know he made a horrible mistake and should check his typing skillz:):)

Would mean a lot less clutter in the main configuration file that is subject to more change.

When this is done the configuration file could be reorganized to at least group related options together. (better would be to convert this to an xml file too: room for comments, grouping etc.)

Pros:

**Comment by nfettinger** [comment]
We will not do this
