### ISSUE TITLE
Incorrect remaining count message after using a lucky egg

### ISSUE THREAD

**Issue by N0ct3** [NECROBOTIO/NecroBot#4740]
When popping an egg, the following message is logged:

> Used Lucky Egg, remaining: xx

The next item status message will however be:

> Berries: aa | Incense: bb| LuckyEggs: xx-1 | Lures: cc

Either the popping egg message is unclear, or it does not accurately reflect the number of remaining eggs (taking into account the one that has just been used).

### Other Information
Version: 8.5

**Comment by dddbliss** [comment]
Fixed in #4831
