### ISSUE TITLE
Running on Raspberry Pi 3

### ISSUE THREAD

**Issue by ItsFletch** [NECROBOTIO/NecroBot#4742]
Anyone know if it is possible to run this on a raspberry Pi 3. I know this is not an Issue but i don't know where else to ask

**Comment by Alehap** [comment]
The same question, does is project can build for linux :+1:

**Comment by N3KRoN** [comment]
arch different... But on linux you can use wine! :)

**Comment by nfettinger** [comment]
Currently, the master branch does not. However, the changeset required is minimal if you work with the source.
