### ISSUE TITLE
New commands to telegran/Necrobot

### ISSUE THREAD

**Issue by dsmello** [NECROBOTIO/NecroBot#4745]
add password.

and:

/startbot ( start the bot)
/stopbot ( stop the bot)

/gogpx XXX.gpx ( chose a new route to follow )

/profile"xxx"  ( allow you chose just poke stops "/mission pokestop"; load customs config.json)

**Comment by Aneduna** [comment]
Password added in [this](https://github.com/NECROBOTIO/NecroBot/commit/23f1cb7fa759d4194ee8486dac55db0dced03cab)

start stop at #4181 being worked on

The other 2 might be a good addon

**Comment by nfettinger** [comment]
Duplicate issue
