### ISSUE TITLE
Request - Add opprutunity to transfer pok below certain CP

### ISSUE THREAD

**Issue by dimonstrer** [NECROBOTIO/NecroBot#4746]
Hi. Can you add  opprutunity to transfer pokemons below certain CP? I've got some troubles with pok inventory and that should help a lot.

**Comment by Andi-fr** [comment]
An opportunity to implement this might be to introduce an Keyword like 'any' (matching each pokemon) for the PokemonsToTransferList (and maybe other lists).

The implementation should be pretty quick and brings a lot of power to the users.

**Comment by nfettinger** [comment]
Already exists, use your config
