### ISSUE TITLE
LevelUpPokemonTask continue instead of break

### ISSUE THREAD

**Issue by 30er** [NECROBOTIO/NecroBot#4749]
LevelUpPokemonTask.cs
Line 56 and line 85

hi
guess u wanted to make a:
**continue** instead of **break**:

"session.Inventory.GetPlayerStats().Result.FirstOrDefault().Level + 1) **break**;"

otherwise it stops if u have a highlvl poke in your inventar

**Comment by cawk** [comment]
fixed here #4782
