### ISSUE TITLE
Freezing after spinning one Pokestop

### ISSUE THREAD

**Issue by random189268** [NECROBOTIO/NecroBot#4750]
Bot loads fine but seems to stop after spinning one Pokestop. Seems like something server side is preventing it from proceeding?

Have not recently modified the config.

Edit: Thank you to @KurtKoko 

"GetSniperInfoFromPokezz": true
to
"GetSniperInfoFromPokezz": false,

**Comment by CreativiTimothy** [comment]
Same. I have this problem right now. Are the servers lagging or something?

**Comment by KurtKoko** [comment]
Same here. 
Reproducable.

When I restart, the bot goes to one Pokestop and freezes. After restarting bot does the same.


Pokemongostatus.org says all servers are up and online.

**Comment by hmate9** [comment]
Same problem here. Definitely something server-side.

**Comment by Hectorite** [comment]
same here

**Comment by tangdami** [comment]
Same. Stop working, restart, then stop after first pokestop...

**Comment by Hacksterrenewed** [comment]
Same issue here - i figured something maybe got patched serverside

**Comment by KurtKoko** [comment]
Just turned 

`"GetSniperInfoFromPokezz": true`
to
` "GetSniperInfoFromPokezz": false,`

and everything works now.

**Comment by jdude1** [comment]
It's related to using GPX pathing
 I turned my gpx pathing off and it worked.

**Comment by jdude1** [comment]
j/k disregard, hit one poke stop and froze.

**Comment by random189268** [comment]
Perfect, thank you @KurtKoko that fixed it for me!

**Comment by hmate9** [comment]
This causes the problem:
"GetSniperInfoFromPokezz": **true**

A quick workaround is to have it set to **false**.

The codebase should be modified so that it doesn't hang on a request. Maybe change requests from snipe servers to be asynchronous?

**Comment by Hectorite** [comment]
KurtKoko i did the same and it works

**Comment by Hacksterrenewed** [comment]
Can confirm that Pokezz is the issue here, as mentioned by @KurtKoko

**Comment by deduijk** [comment]
Seeing the same behaviour.  turning sniping off fixes the issue.
Worked fine up untill a few minutes ago. Looking at the sites they all give info, so i don't know if it's related to a request.

**Comment by Sh0cky** [comment]
"SnipeAtPokestops": false, works when you leave pokezzz set to true and vice versa snipe true pokezzz false however with the second option i get a lot of sniper skip lagged errors

**Comment by orangesuave** [comment]
WINNER!!!!!!!!!!!!!! Solution for sniping is to disable everything other than localhost and use PoGoLocationFeeder.

**Comment by TheStrikes** [comment]
Is there a way you can keep "GetSniperInfoFromPokezz" on and still snipe?

**Comment by orangesuave** [comment]
Use PoGoLocation Feeder and the following: 


"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 400, //replace this with your start snipe pokeball counter
  "MinPokeballsWhileSnipe": 150, //replace this with your minimum snipe pokeball counter
  "MinDelayBetweenSnipes": 1,
  "SnipingScanOffset": 1.0,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by orangesuave** [comment]
I've also seen a better return using 0.8.1 instead of 0.8.5.

**Comment by kokkie2012** [comment]
Is it possible to contine sniping? cant snipe when i turn of: "GetSniperInfoFromPokezz"

**Comment by deduijk** [comment]
Turn on the other 2 sites and turn off pokezz. Then you can still snipe.
Or use the option of orangesuave (although much more work to implement).

**Comment by Lord-Haji** [comment]
Same problem having here

**Comment by Lord-Haji** [comment]
we can use https://pokesniper.de
as an alternative
We need to code the necessary utils on the bot tho
