### ISSUE TITLE
Don´t get any item from pokestop?

### ISSUE THREAD

**Issue by mrturkk** [NECROBOTIO/NecroBot#4751]
i dont get any items from pokestops...

**Comment by 30er** [comment]
softban?
maybe your ip is blocked.... try to reduce walkspeed
i run at 10

**Comment by polygamma** [comment]
@mrturkk what do you think is the point of the Issue-Tracker?

**Comment by MrrJ94** [comment]
In your config make sure you change the following to what I have and it will work.

"GetSniperInfoFromPokezz": false,

**Comment by mrturkk** [comment]
its says nothing about softban...
i already have it on false..
my walkingspeed was 19..
