### ISSUE TITLE
Support Socks v5 Proxies

### ISSUE THREAD

**Issue by MatteCarra** [NECROBOTIO/NecroBot#4752]
Necrobot doesn't support socks v5 proxies right now but it would be really useful to support them.
For example anyone with a vps/dedicated server/ec2 could create a dedicated socks v5 proxy server easily 

> ssh -N -D{PROXYPORT} {USER}@{IP}

**Comment by TimIsOverpowered** [comment]
Use proxifier. they won't support it as dev stated before
