### ISSUE TITLE
IP Banned?

### ISSUE THREAD

**Issue by jeff-kingston** [NECROBOTIO/NecroBot#4759]
Necrobot stopped working today. I now get an error saying that there are no pokestops near me. 

If I open the app on my Phone while on my home network I log in and no data is displayed. I cant see any pokestops. If I disconnect from my wifi, everything works fine.

I tried running with my VPN client turned on, but Necrobot just crashes if VPN is enabled.

**Comment by jeff-kingston** [comment]
Closed with no comment?

**Comment by smoothrunnings** [comment]
@jeff-kingston you are IP is soft banned. It likely won't work for another 30 minutes to an hour. If you are going to use VPN service I would recommend you use Hide MY Ass. 

Also NOTE: The servers no longer support 2 ID one 1 IP. They only work with 1 ID with 1 IP.
