### ISSUE TITLE
fixed pokemon transfer problem.. 

### ISSUE THREAD

**Issue by repelsteeltjehd** [NECROBOTIO/NecroBot#4762]
change these settings in config.json

  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 0,

To

  "UseKeepMinLvl": true,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,

**Comment by nfettinger** [comment]
Use Discord chat for help.
