### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by rossetto999** [NECROBOTIO/NecroBot#4768]
![sem titulo](https://cloud.githubusercontent.com/assets/20957263/17570190/cb2263a0-5f21-11e6-9df3-018d68a00f80.jpg)

**Comment by smoothrunnings** [comment]
What error?

**Comment by rossetto999** [comment]
Crashed in pokestop, the bot dont walk

**Comment by random189268** [comment]
Set Pokezz sniping to false

**Comment by random189268** [comment]
"GetSniperInfoFromPokezz": true
to
"GetSniperInfoFromPokezz": false,
