### ISSUE TITLE
Bot is transferring every pokemon!

### ISSUE THREAD

**Issue by albysprx** [NECROBOTIO/NecroBot#4769]
Hi created a new account and every pokemon that the bot capture is transferred (i saw a IV 73% transferred)
here is a screenshot:
![immagine](https://cloud.githubusercontent.com/assets/16463429/17570191/b4042ba2-5f4b-11e6-9582-2fb5d7f3ffde.png)
and here is a screenshot of my setting:
![immagine2](https://cloud.githubusercontent.com/assets/16463429/17570196/bc33f118-5f4b-11e6-8d56-8696bfc8eb4c.png)

**Comment by albysprx** [comment]
i'm level 6 and i have 0 pokemons

**Comment by kokkie2012** [comment]
set "KeepMinDuplicatePokemon" to 1, like this: "KeepMinDuplicatePokemon": 1,

**Comment by albysprx** [comment]
why it isn't set as default!?

**Comment by kokkie2012** [comment]
Idk, a bug i think, but now you can Catch 'Em All :)
