### ISSUE TITLE
No pokestop found in your area..

### ISSUE THREAD

**Issue by jamal004** [NECROBOTIO/NecroBot#4777]
Geen geschikte pokemonstops gevonden in je omgeving, is je omgeving te klein??

Trans:  No pokestops found in your area, is your area to small??

Im only using one account bot,  i was using it on my own IP, then  used a VPN on VPN it worked like 5mins ? then again no pokestops found??

Help?

**Comment by nfettinger** [comment]
Use Discord chat for help.
