### ISSUE TITLE
Bot is suddenly freezing

### ISSUE THREAD

**Issue by ExarSenpai** [NECROBOTIO/NecroBot#4778]
Like, the process is not freezing, that I have to close it or anything, but bot stops doing actions

**Comment by nfettinger** [comment]
Use Discord chat for help.

**Comment by tanbk209** [comment]
My Bot was same situation. Freezed after starting few seconds.

**Comment by ExarSenpai** [comment]
It is not correct to tell people to use discord for help, if more people have the issue.
