### ISSUE TITLE
[BUG] Weak 90IV+ pokemon transfer issue

### ISSUE THREAD

**Issue by dfmeier** [NECROBOTIO/NecroBot#4783]
### Expected Behavior
Previous versions keep my 90+ but weak pokés

### Actual Behavior
Transferred some of them:
![badtransfer](https://cloud.githubusercontent.com/assets/12189742/17570805/340e9d44-5f4e-11e6-9467-4eb9ced25eda.jpg)

### Related part of my config.json 
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 1,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,

### Other Information
Version: 0.8.5. DEV
Windows Version: 10
What is affected: transfer

**Comment by deduijk** [comment]
Works as designed.
It's keeping the highest Drowwzee which has 94.85% IV, which you prioritize.
Duplicate = 1 so only 1 will remain.

**Comment by dfmeier** [comment]
But
"KeepMinIvPercentage": 90.0,
Meant all the 90+ had been kept

**Comment by deduijk** [comment]
Yea just noticed u used or operator.

**Comment by dfmeier** [comment]
UseKeepMinLvl is for the level only not for the IV if I turn it on none of my pokemons on level 1 or above will be transferred

**Comment by dfmeier** [comment]
My goal would be to keep all the 90+IV pokes strong and weak ones and manually transfer them.

**Comment by nfettinger** [comment]
Use Discord chat for help.

**Comment by dfmeier** [comment]
I reported a bug IMHO, but ok I try discord again.

**Comment by CreativiTimothy** [comment]
@dfmeier Hope it works out for you (the Discord)! I love Necrobot and how the developers put so much time and effort into this. For some reason, they do appear to get tired frequently and be harsh/cold on issues -- although there are indeed some stupid posts on issues that aren't actually bugs. But your post and a couple of my other posts were detailed and clear so yeah

**Comment by deduijk** [comment]
Up the level... u put 'OR' operator. Meaning it will keep all pokemon that comply to:
LVL >1 or IV >90 or CP>1500

Increase the level and you should be set.

**Comment by CreativiTimothy** [comment]
@deduijk Since he put "or", it's supposed to keep anything that is either ""KeepMinCp": 1500," or 
"KeepMinIvPercentage": 90.0,"

UseKeepMinLvl is set to false so increasing the level wouldn't do anything

**Comment by somani6** [comment]
If you are using current master rep #4705

**Comment by dfmeier** [comment]
@deduijk if I want to keep all the pokes above a certain level your recommendation would be perfect but I want to keep pokes above a certain IV which is different and had no relation with your solution. It worked previously but not with the latest version. Thanks anyway.

**Comment by dfmeier** [comment]
@somani6 Yes I do, but honestly I'm a rookie with this github thing so don't know exactly how can I get your patch before it will be merged.

**Comment by actislav** [comment]
fixed in #4827
