### ISSUE TITLE
Feature Request : Redefine Recycle Event

### ISSUE THREAD

**Issue by KurtKoko** [NECROBOTIO/NecroBot#4785]
Everytime i am starting the bot, I add the following lines for a bag of 350 at max usage 330

```
  "TotalAmountOfGreatballsToKeep": 55,
  "TotalAmountOfUltraBallsToKeep": 70,
  "TotalAmountOfSuperPotionsToKeep": 10,
  "TotalAmountOfHyperPotionsToKeep": 30,
  "TotalAmountOfMaxPotionsToKeep": 30,
  "TotalAmountOfMaxRevivesToKeep": 15,
  "TotalAmountOfBerriesToKeep": 40,
```

Everytime the bot restarts, the lines are deleted. 

Why does this happen?
Could it be added to config.json as standard values ?

I am adding these lines, because the bot itself recycles not the way i want it. So maybe redefining the Recycle Event to something like:

> 
>  **"IntelligentRecycle": bool,** _<-- when true than use predefined values. if false than use custom values_
>  _"TotalAmountOfPokeballsToKeep": 40,_
>   "TotalAmountOfGreatballsToKeep": 55,
>   "TotalAmountOfUltraBallsToKeep": 70,
>   _"TotalAmountOfPotionsToKeep": 5,_
>   "TotalAmountOfSuperPotionsToKeep": 10,
>   "TotalAmountOfHyperPotionsToKeep": 30,
>   "TotalAmountOfMaxPotionsToKeep": 30,
>   _"TotalAmountOfRevivesToKeep": 35,
>   "TotalAmountOfMaxRevivesToKeep": 15,
>   "TotalAmountOfBerriesToKeep": 40,

_Pokeball is a standard Pokeball
Potion is standard Potion
Revive is standard Revive_

Intelligent Recycle is a predefined and uneditable from the User with these Values as percentage.
```
"MaxPokeballsToKeep": 0.45,
"MaxPortionsToKeep": 0.25,
"MaxRevivesToKeep": 0.15,
"MaxBerriesToKeep": 0.1,
```

**Comment by nfettinger** [comment]
Keeping better balls is ALWAYS better. The old method is depreciated and will not be coming back.
