### ISSUE TITLE
Why my bot stop working? 

### ISSUE THREAD

**Issue by valldy** [NECROBOTIO/NecroBot#4788]

**Comment by TheBorna** [comment]
... more info?

**Comment by bello356** [comment]
Same thing happening to be. It only does 1 command then stops. Either captures 1 pokemon or goes to 1 pokestop and then nothing happens

**Comment by jasonisnear** [comment]
Same as bello 365 here!

**Comment by OoDex** [comment]
Easy - "  "GetSniperInfoFromPokezz": false,"
And you got it

**Comment by KurtKoko** [comment]
Please read before posting.

Read means not only the first 5 issues but all of them.
AND go to Discord Channel.

**Comment by valldy** [comment]
im sorry , i dont now .. thanks for your information

**Comment by jasonisnear** [comment]
@OoDex I just set it to false but why now it is only travel and collect items from one Pokestop to another?

**Comment by valldy** [comment]
Help , my bot still don't work ..
this screenshot bot, stop working like that
sorry for my bad englis..
![image](https://cloud.githubusercontent.com/assets/20920945/17571708/81306580-5f7b-11e6-9149-c7a8bdd3618e.png)

**Comment by OoDex** [comment]
Dude
  "GetSniperInfoFromPokezz": false,

**Comment by nfettinger** [comment]
Use Discord chat for help.

**Comment by jasonisnear** [comment]
![default](https://cloud.githubusercontent.com/assets/20944070/17572019/8d6f293e-5f4a-11e6-8197-af4ec32a4d84.JPG) Keep showing me this

**Comment by GdS88** [comment]
thx for the aswers for how to stop bot to stop doing his thing :P 
when my bot is sniping this appears:  (ERROR) (PokeWatchers.com) There were one or more errors. (translated from my language).
anyone knows how to fix that?
