### ISSUE TITLE
Keep 1 of each pokemon with highest IV?

### ISSUE THREAD

**Issue by yawnm3** [NECROBOTIO/NecroBot#4789]
Having problem to keep only 1 highest IV pokemon. Any dupes will be transferred if the IV is lower than the highest one? Not sure what am I missing out here. Still keeping dupes for me.

```
"LevelUpByCPorIv": "iv",
"KeepPokemonsThatCanEvolve": false,
"KeepMinIvPercentage": 90.0,
"PrioritizeIvOverCp": true,
"KeepMinDuplicatePokemon": 0,
"TransferWeakPokemon": true,
 "TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,
"FavoriteMinIvPercentage": 95.0,
 "AutoFavoritePokemon": true,

"PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
```

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
