### ISSUE TITLE
Necrobot/ No usable poke-stops, (the old issue) and Transferring 

### ISSUE THREAD

**Issue by gormgaming** [NECROBOTIO/NecroBot#4795]
![transferring](https://cloud.githubusercontent.com/assets/17522531/17571679/1f70d528-5f49-11e6-9df7-327b94273010.png)
![pokemon](https://cloud.githubusercontent.com/assets/17522531/17571685/22c840d0-5f49-11e6-8144-bfff77c9b8b8.png)
Please help, i don't want to start it up again if it might transfer the rest of my pokemon and i need help with the 'No usable pokestops' which came up before it started transferring everything :(

**Comment by Rick058** [comment]
No usable Pokéstops indicates that you are soft banned.
Use a VPN / proxy.

**Comment by OoDex** [comment]
What is anyone supposed to do with your transfer-problem if you don't attach the config file?!

**Comment by nfettinger** [comment]
Use Discord chat for help.

**Comment by gormgaming** [comment]
My config has been added
