### ISSUE TITLE
Proxy configuration cleaned after restart

### ISSUE THREAD

**Issue by Cero9** [NECROBOTIO/NecroBot#4798]
Hello,
I'm trying to make my Necrobot use a SOCKS proxy to connect to servers.

While I couldn't find anything in my config.json file about proxies, I found on this thread ( https://github.com/NECROBOTIO/NecroBot/issues/3235 ) that they should work and I copy-pasted their configuration in my file.

```
"UseProxy": true,
"UseProxyHost": *PROXY IP*,
"UseProxyPort": *PROXY PORT*,
"UseProxyAuthentication": false,
```

This is said to work in such thread, however, when I modify the config file with these settings and run Necrobot, these lines are simply deleted. It connects without the proxy, and when I go back to check the config file, those lines are no more there.

Do you have any similar issue?
What am I doing wrong?
Thanks

**Comment by nfettinger** [comment]
SOCKS will not be supported officially.
Use Discord chat for help.
