### ISSUE TITLE
SnipePokemonNotInPokedex

### ISSUE THREAD

**Issue by pacioc193** [NECROBOTIO/NecroBot#4802]
is SnipePokemonNotInPokedex work ?? Becouse i set to true and bot start to snipe everythings

**Comment by kalilc** [comment]
Its working as intended. True means that, read the option again.

**Comment by pacioc193** [comment]
What about if i set to false an try to snipe every pokemon ? :S

**Comment by shcheuk** [comment]
This setting means , when u snipe for Pokemon in ur snipe pokemon list , u also snipe Pokemon that u haven't caught before. So if u turn it on it will add those u never caught to ur snipe Pokemon list .

**Comment by shcheuk** [comment]
So it is not snipe for everything , it snipe mainly base on ur snipe Pokemon list no matter u turn it on or off.

**Comment by dddbliss** [comment]
It will add Pokemon you have not caught in your Pokedex to your PokemonToSnipe list.
