### ISSUE TITLE
Can't Sniping 

### ISSUE THREAD

**Issue by guifortini** [NECROBOTIO/NecroBot#4803]
Hey guys, i try a lot of things to work sniping again, but in the moment i can't. Are someone sniping now? If are, could you give me your config file please?
Thanks e.e

**Comment by MrPK2710** [comment]
thx

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
