### ISSUE TITLE
bot just stops doing anything after first pokestop visit.

### ISSUE THREAD

**Issue by slyfoxjosh** [NECROBOTIO/NecroBot#4804]
### Expected Behavior
to operate like normal.

### Actual Behavior
just stops running after the first poke stop visit unlike before

EX:
[16:34:19] (INFO) Traveling to Pokestop: 東京ディズニーランド Partner's Statue (65m) (2 seconds)
[16:34:20] (INFO) [Pokemon ignore filter] - Ignoring Rattata as defined in settings
[16:34:20] (POKESTOP) Name: 東京ディズニーランド Partner's Statue XP: 50, Gems: 0, Items: 3 x ItemPokeBall, Lat: 35.633506, Long: 139.880048

and then nothing after.

### Your config.json
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 35.6328964,
  "DefaultLongitude": 139.8803943,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 1,
  "DelayBetweenPokemonCatch": 1,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 100.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 0,
  "UseBerriesMinIv": 0.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "and",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 3000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 80.0,
  "UseUltraBallAboveIv": 90.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 1000
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "bulbasaur",
    "ivysaur",
    "venusaur",
    "charmander",
    "charmeleon",
    "charizard",
    "squirtle",
    "wartortle",
    "blastoise",
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "rattata",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "pikachu",
    "raichu",
    "sandshrew",
    "sandslash",
    "nidorina",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "clefairy",
    "clefable",
    "vulpix",
    "ninetales",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "abra",
    "kadabra",
    "alakazam",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "golem",
    "ponyta",
    "rapidash",
    "slowpoke",
    "slowbro",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "onix",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "exeggcute",
    "exeggutor",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "koffing",
    "weezing",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "kangaskhan",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "jynx",
    "electabuzz",
    "magmar",
    "pinsir",
    "tauros",
    "magikarp",
    "gyarados",
    "lapras",
    "ditto",
    "eevee",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dratini",
    "dragonair",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsTransferFilter": {
    "Mewtwo": {
      "KeepMinCp": 2500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 35.6328964,
        "Longitude": 139.8803943
      },
      {
        "Latitude": 40.712784,
        "Longitude": -74.005941
      },
      {
        "Latitude": 38.907192,
        "Longitude": -77.036871
      },
      {
        "Latitude": 37.77493,
        "Longitude": -122.419416
      },
      {
        "Latitude": 52.520007,
        "Longitude": 13.404954
      },
      {
        "Latitude": 51.507351,
        "Longitude": -0.127758
      }
    ],
    "Pokemon": [
      "caterpie",
      "weedle",
      "rattata",
      "pidgey"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

### Steps to Reproduce
[16:34:12] (ATTENTION) Detected realistic Traveling , using Default Settings inside config.json
[16:34:12] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 35.6329595760127 Lng: 139.880293945603
[16:34:13] (INFO) ====== DisplayHighestsCP ======
[16:34:13] (INFO) # CP 1651/1807 | (40.57% perfect)     | Lvl 25         NAME: Victreebel        MOVE1: AcidFast             MOVE2: LeafBlade            Candy: 844
[16:34:13] (INFO) # CP 1632/1703 | (68.99% perfect)     | Lvl 20         NAME: Lapras            MOVE1: IceShardFast         MOVE2: IceBeam              Candy: 18
[16:34:13] (INFO) # CP 1590/1697 | (60.14% perfect)     | Lvl 28         NAME: Pinsir            MOVE1: FuryCutterFast       MOVE2: ViceGrip             Candy: 272
[16:34:13] (INFO) # CP 1456/1566 | (51.60% perfect)     | Lvl 22         NAME: Vileplume         MOVE1: AcidFast             MOVE2: SolarBeam            Candy: 330
[16:34:13] (INFO) # CP 1451/1592 | (46.00% perfect)     | Lvl 29         NAME: Golbat            MOVE1: BiteFast             MOVE2: PoisonFang           Candy: 2892
[16:34:13] (INFO) # CP 1444/1635 | (26.67% perfect)     | Lvl 28         NAME: Seaking           MOVE1: PoisonJabFast        MOVE2: DrillRun             Candy: 477
[16:34:13] (INFO) # CP 1396/1522 | (45.95% perfect)     | Lvl 24         NAME: Tentacruel        MOVE1: PoisonJabFast        MOVE2: Blizzard             Candy: 381
[16:34:13] (INFO) # CP 1365/1493 | (45.42% perfect)     | Lvl 25         NAME: Pidgeot           MOVE1: SteelWingFast        MOVE2: AirCutter            Candy: 4389
[16:34:13] (INFO) # CP 1361/1423 | (67.43% perfect)     | Lvl 16         NAME: Snorlax           MOVE1: ZenHeadbuttFast      MOVE2: BodySlam             Candy: 15
[16:34:13] (INFO) # CP 1359/1404 | (80.94% perfect)     | Lvl 26         NAME: Venomoth          MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 978
[16:34:13] (INFO) ====== DisplayHighestsPerfect ======
[16:34:13] (INFO) # CP  738/ 738 | (100.00% perfect)    | Lvl 24         NAME: Eevee             MOVE1: QuickAttackFast      MOVE2: Swift                Candy: 1027
[16:34:13] (INFO) # CP  871/ 888 | (90.98% perfect)     | Lvl 27         NAME: Koffing           MOVE1: AcidFast             MOVE2: SludgeBomb           Candy: 82
[16:34:13] (INFO) # CP  456/ 470 | (88.31% perfect)     | Lvl 20         NAME: Shellder          MOVE1: TackleFast           MOVE2: IcyWind              Candy: 18
[16:34:13] (INFO) # CP  306/ 318 | (88.03% perfect)     | Lvl 23         NAME: Kakuna            MOVE1: BugBiteFast          MOVE2: Struggle             Candy: 1480
[16:34:13] (INFO) # CP  261/ 273 | (86.88% perfect)     | Lvl 20         NAME: Metapod           MOVE1: BugBiteFast          MOVE2: Struggle             Candy: 664
[16:34:13] (INFO) # CP 1209/1237 | (85.24% perfect)     | Lvl 20         NAME: Aerodactyl        MOVE1: BiteFast             MOVE2: AncientPower         Candy: 3
[16:34:13] (INFO) # CP  652/ 666 | (85.09% perfect)     | Lvl 08         NAME: Exeggutor         MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy: 274
[16:34:13] (INFO) # CP 1156/1185 | (84.96% perfect)     | Lvl 20         NAME: Scyther           MOVE1: FuryCutterFast       MOVE2: BugBuzz              Candy: 72
[16:34:13] (INFO) # CP  827/ 853 | (84.18% perfect)     | Lvl 20         NAME: Hitmonlee         MOVE1: RockSmashFast        MOVE2: StoneEdge            Candy: 35
[16:34:13] (INFO) # CP  726/ 745 | (84.10% perfect)     | Lvl 14         NAME: Primeape          MOVE1: LowKickFast          MOVE2: LowSweep             Candy: 38
[16:34:13] (EVOLVED) Potential Evolutions: 0
[16:34:14] (EGG) Incubator status update: 2.35km left
[16:34:14] (EGG) Incubator status update: 4.92km left
[16:34:14] (INFO) Amount of Pokemon Seen: 105/151, Amount of Pokemon Caught: 104/151
[16:34:14] (INFO) Pokeballs: 3 | Greatballs: 40 | Ultraballs: 79 | Masterballs: 0
[16:34:14] (INFO) Potions: 1 | SuperPotions: 0 | HyperPotions: 3 | MaxPotions: 77
[16:34:14] (INFO) Revives: 36 | MaxRevives: 25
[16:34:14] (INFO) Berries: 50 | Incense: 2 | LuckyEggs: 9 | Lures: 9
[16:34:15] (RECYCLING) 2x ItemPokeBall
[16:34:16] (RECYCLING) 1x ItemPotion
[16:34:16] (RECYCLING) 1x ItemRevive
[16:34:19] (INFO) Traveling to Pokestop: 東京ディズニーランド Partner's Statue (65m) (2 seconds)
[16:34:20] (INFO) [Pokemon ignore filter] - Ignoring Rattata as defined in settings
[16:34:20] (POKESTOP) Name: 東京ディズニーランド Partner's Statue XP: 50, Gems: 0, Items: 3 x ItemPokeBall, Lat: 35.633506, Long: 139.880048

### Other Information
Version: latest 0.8.5
Windows Version: 10
What is affected (everything):

**Comment by valldy** [comment]
"GetSniperInfoFromPokezz": true, change to false

**Comment by slyfoxjosh** [comment]
but this config worked before just fine without that being true? can you explain why that would be the issue? not being facetious i'm honestly just curious.

**Comment by Adenahmed** [comment]
That worked, thanks! Still curious on why we had to change

**Comment by pacioc193** [comment]
Something in pokezz has change i think

**Comment by theloser** [comment]
According to pull request #4787 bot waits for an infinite amount of time for a response from pokezz. If the site is down or under heavy load this could stop your bot.

**Comment by catalinutzz** [comment]
turn that "GetSniperInfoFromPokezz": true, to false,it should work fine

**Comment by PeYouRoti** [comment]
@valldy Do I have to change it to false for the others (pokewatchers, pokesnipers..)? I don't know the goal of this feature..

**Comment by slyfoxjosh** [comment]
I can confirm it works and thank you tremendously for the fix!

I made the change in the config i was working on:
Mind giving it a look over for me i just started editing this stuff lol
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 32.73530650964904,
  "DefaultLongitude": -117.14896559715271,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 1,
  "DelayBetweenPokemonCatch": 1,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 100.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 0,
  "UseBerriesMinIv": 0.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "and",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 50,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 3000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 80.0,
  "UseUltraBallAboveIv": 90.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 50
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 1000
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "mewtwo",
    "jolteon",
    "flareon",
    "vaporeon",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "bulbasaur",
    "ivysaur",
    "venusaur",
    "charmander",
    "charmeleon",
    "charizard",
    "squirtle",
    "wartortle",
    "blastoise",
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "raticate",
    "rattata",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "pikachu",
    "raichu",
    "sandshrew",
    "sandslash",
    "nidorina",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "clefairy",
    "clefable",
    "vulpix",
    "ninetales",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "abra",
    "kadabra",
    "alakazam",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "golem",
    "ponyta",
    "rapidash",
    "slowpoke",
    "slowbro",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "onix",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "exeggcute",
    "exeggutor",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "koffing",
    "weezing",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "kangaskhan",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "jynx",
    "electabuzz",
    "magmar",
    "pinsir",
    "tauros",
    "magikarp",
    "gyarados",
    "lapras",
    "ditto",
    "eevee",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dratini",
    "dragonair",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsTransferFilter": {
    "Mewtwo": {
      "KeepMinCp": 2500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 32.73530650964904,
        "Longitude": -117.14896559715271
      },
      {
        "Latitude": 32.73471086704159,
        "Longitude": -117.14925527572632
      },
      {
        "Latitude": 32.73419644522264,
        "Longitude": -117.14931964874268
      },
      {
        "Latitude": 32.734106195474574,
        "Longitude": -117.15026378631592
      },
      {
        "Latitude": 32.73481916599358,
        "Longitude": -117.15026378631592
      },
      {
        "Latitude": 32.73430474479967,
        "Longitude": -117.1505856513977
      },
      {
        "Latitude": 32.73387154570195,
        "Longitude": -117.1510362625122
      },
      {
        "Latitude": 32.73463866766717,
        "Longitude": -117.15137958526611
      },
      {
        "Latitude": 32.733970820681144,
        "Longitude": -117.15194821357727
      },
      {
        "Latitude": 32.734755991620915,
        "Longitude": -117.15184092521667
      },
      {
        "Latitude": 32.73415132036002,
        "Longitude": -117.15325713157654
      },
      {
        "Latitude": 32.73373617055215,
        "Longitude": -117.15445876121521
      },
      {
        "Latitude": 32.73488234032148,
        "Longitude": -117.15439438819885
      },
      {
        "Latitude": 32.735414807877234,
        "Longitude": -117.15320348739624
      },
      {
        "Latitude": 32.73561335428718,
        "Longitude": -117.15173363685608
      },
      {
        "Latitude": 32.735568230141965,
        "Longitude": -117.15088605880737
      },
      {
        "Latitude": 32.736281188965556,
        "Longitude": -117.15140104293823
      },
      {
        "Latitude": 32.73653388186319,
        "Longitude": -117.15239882469177
      },
      {
        "Latitude": 32.7371475616317,
        "Longitude": -117.15284943580627
      },
      {
        "Latitude": 32.737968802945815,
        "Longitude": -117.15272068977356
      },
      {
        "Latitude": 32.73822149105837,
        "Longitude": -117.15206623077393
      },
      {
        "Latitude": 32.73842905575771,
        "Longitude": -117.15110063552856
      },
      {
        "Latitude": 32.73852832566041,
        "Longitude": -117.1501886844635
      },
      {
        "Latitude": 32.737959778357116,
        "Longitude": -117.15014576911926
      },
      {
        "Latitude": 32.73729195625725,
        "Longitude": -117.15066075325012
      },
      {
        "Latitude": 32.73729195625725,
        "Longitude": -117.14953422546387
      },
      {
        "Latitude": 32.736579005519516,
        "Longitude": -117.14967370033264
      },
      {
        "Latitude": 32.736579005519516,
        "Longitude": -117.14967370033264
      },
    ],
    "Pokemon": [
      "caterpie",
      "weedle",
      "rattata",
      "pidgey"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by theloser** [comment]
@slyfoxjosh If you want a check of your config please use our [Discord channels](https://discord.gg/VXKxNFr) to get help, thanks!

**Comment by wyvern19** [comment]
"UseSnipeLocationServer": false,
  "SnipeAtPokestops": false,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
