### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by MrPK2710** [NECROBOTIO/NecroBot#4806]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Actual Behavior
My Bot stop on the first pokestop. what i need to do?

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by pacioc193** [comment]
#4803

**Comment by Adenahmed** [comment]
Some guy said to do this:
"GetSniperInfoFromPokezz": false,
Set it to false. It worked! No idea why

**Comment by draconiscor** [comment]
no working for me

**Comment by theloser** [comment]
According to pull request #4787 bot waits for an infinite amount of time for a response from pokezz. If the site is down or under heavy load this could stop your bot.

**Comment by jjskuld** [comment]
Pokezz changed their implementation which was causing a hang in the bot.  Until #4787 is fixed, just set to false as @theloser said.

**Comment by MrPK2710** [comment]
work for 4 min... stop again..

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by nfettinger** [comment]
We cannot help with sniping anymore
