### ISSUE TITLE
[Feature] multiple GPX Files

### ISSUE THREAD

**Issue by PegasusExe** [NECROBOTIO/NecroBot#4809]
A good Feature would, if you can add 5 or more GPX Files and then if the first is finished he will do the second and so on. This would be better too avoid softbans. But the last and first postion of each gpx file should be the start postion so you change the way everytime you are at your start pos. And then you can do a random pic and no order from the gpx files.

**Comment by theloser** [comment]
Why not just creat a GPX file with different "loops"? There are many [online services](http://lmgtfy.com/?q=create+gpx+file+online) which you can use to create a GPX file.

**Comment by PegasusExe** [comment]
Buit i want a random value in it so he don't walk every loop again... i want that he walk route 1 the random 5 then 2 then 1. not every time first secon third and so on...

**Comment by theloser** [comment]
Oh, I see.

**Comment by nfettinger** [comment]
I like this request, but I think it is too complicated to make mainline. Please download the source and build your own version.
