### ISSUE TITLE
Help me( vant login with ptc)

### ISSUE THREAD

**Issue by 1Darkrai1** [NECROBOTIO/NecroBot#4810]
Hey Guys, 
I just wanted to ask you how that shit with login to the ptc works. I can login to my google
account easily but when I try to login to my ptc account at the bot itselfs (in the auth.json)
it doesnt work. It says : Make sure to login with youre right email adress or something like this

**Comment by Rick058** [comment]
How's your auth.json ?

If you use PTC it should be like this:
```
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "username",
  "PtcPassword": "password",
```

And if you use Google:
```
  "AuthType": "google",
  "GoogleUsername": "user@gmail.com",
  "GooglePassword": "password",
  "PtcUsername": null,
  "PtcPassword": null,
```

**Comment by 1Darkrai1** [comment]
okay i fixxed it thank ya all!

**Comment by theloser** [comment]
If it's fixed, please close this issue.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
