### ISSUE TITLE
[bug/request] Resetting GPX-route every time the server hiccups

### ISSUE THREAD

**Issue by mo0ojava** [NECROBOTIO/NecroBot#4813]
### Expected Behavior
The bot follows the GPX-track nicely. If a server- or traffic-hiccup occurs the bot gracefully resumes the track where it left.

### Actual Behavior
Right now the bot starts a straight beeline for the first pos in the GPX-file whenever the traffic is interrupted. The walking-speed while returning home seems to be the same as when following the track. The problem would be that this "straight line home" tends to go through pretty impassable objects. 

This behaviour has been observed on different machines and dating back to at least 0.7.1, propably longer. It seems 100% triggered by this so should be easy to reproduce. See the attached pic for an illustration.

### Other Information
Version: 0.8.5
Windows Version: 10
Affected part: GPX-pathing
![gpx-robustness](https://cloud.githubusercontent.com/assets/20909700/17572719/55b48b4a-5f56-11e6-83c8-6c5dc5b2cbf3.png)
[config.json.txt](https://github.com/NECROBOTIO/NecroBot/files/412184/config.json.txt)

**Comment by nfettinger** [comment]
Duplicate  issue.

**Comment by Zenotron** [comment]
![gpx_error](https://cloud.githubusercontent.com/assets/20955229/17600523/e688e3f2-5fd1-11e6-81c4-db34048ee99a.jpg)

**Comment by mo0ojava** [comment]
Really intriguing find. What kind of mechanic results in server-hiccups based on the pos..? Nevertheless. I can verify that the "throttling" tends to happen at the same place, but far from every time.

My guess would be that the "same position" you're talking about is actually the starting point for your gpx. See my reported issue about the gpx-tracker restarting instead of moving on.

**Comment by Zenotron** [comment]
The starting point is where all the red lines comes together, at the south-west. Im using the GPX file named "CentralParkPokestops_Period.GPX" available here [](https://github.com/NECROBOTIO/NecroBot/wiki/Locations-&-GPX-Route-Files). Everytime the position gets to north-east, Necrobot seems to throttle, I know it makes no sense but I tried a lots of things to avoid that, and to understand that problem, but with no success. Here is the path it is supposed to follow.
![centralparkpokestops](https://cloud.githubusercontent.com/assets/20955229/17608780/de123dd8-5ffc-11e6-853d-608d30405084.jpg)

**Comment by Zenotron** [comment]
Found something else ! It seems that Necrobot throttles API calls every 30 minutes EXACTLY ! couple of seconds difference but looking at my logs I can confirm that every 30 minutes it throttles and I go back to default longitude/latitude. Here somes logs examples:

[11:11:35] Niantic Servers unstable, throttling API Calls.
[11:41:42] Niantic Servers unstable, throttling API Calls.
[12:11:50] Niantic Servers unstable, throttling API Calls.
[12:41:58] Niantic Servers unstable, throttling API Calls.
[13:12:06] Niantic Servers unstable, throttling API Calls.
[13:42:13] Niantic Servers unstable, throttling API Calls.

..... and it goes and on and on every 30 mins !!!
