### ISSUE TITLE
NecroBot is transferring all my Pokemon

### ISSUE THREAD

**Issue by Gladi0n** [NECROBOTIO/NecroBot#4815]
Hey,

everytime i setup my config new, NecroBot is transferring all my current Pokemon
anyone got any solutions?

thx
Gladi0n

**Comment by jjskuld** [comment]
If you are on master, then see #4705

**Comment by ausscheider** [comment]
when you lost all pokemons then you have follow in your config:

"KeepMinDuplicatePokemon": 0,

change it to

"KeepMinDuplicatePokemon": 3,

**Comment by Gladi0n** [comment]
Thanks ausscheider, it worked. I didnt know how i couldn't see that because i checked the config several times

**Comment by actislav** [comment]
fixed in #4827
