### ISSUE TITLE
Crash when use other translation than en

### ISSUE THREAD

**Issue by DrisBigB** [NECROBOTIO/NecroBot#4817]
Hello,

I got this problem with 0.8.5, if I wanna use other language than english.

http://prnt.sc/c45vgg

**Comment by theloser** [comment]
Did you press "Y" when it asked you to rebuild the translation folder? Is it still crashing afterwards? What language are you trying to enable?

**Comment by DrisBigB** [comment]
I tried to use hungarian language. After I pressed "Y" the bot relunched and used english.

Now I tried it with german translate and it worked, so I'll compare the files and If I find the problem, I'll upload it.

**Comment by theloser** [comment]
After rebuilding the translation folder, please edit your config.json to set your language:

> "TranslationLanguageCode": "hu",

Does the bot still crash?

**Comment by DrisBigB** [comment]
I did, same problem

**Comment by theloser** [comment]
Ok, then please do what you suggested, check the "hu" translation file for errors (and if you find some create a pull request with your fixes) -- thanks!

**Comment by DrisBigB** [comment]
Okey, I made a new translation file, cause the old one had more bugs than the hobo's have who live under the bridge.. :D 

There is some problem with our language, cause the special letters (like áéóöőűúí). I'll fix it today.

**Comment by DrisBigB** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/4863
