### ISSUE TITLE
Necrobot not run

### ISSUE THREAD

**Issue by LawMarcos** [NECROBOTIO/NecroBot#4819]
![image](https://cloud.githubusercontent.com/assets/20958496/17573340/b8284868-5f27-11e6-8a9b-271fc6ed228f.png)
It still there, and not progress. Why? Today it was working, until now.

**Comment by theloser** [comment]
Set "GetSniperInfoFromPokezz" to false

**Comment by CharliePrown** [comment]
got this false but mine isnt running too right now)

**Comment by jayson0408** [comment]
Theloser THANK YOU!!!! got it fixed

**Comment by wyvern19** [comment]
"UseSnipeLocationServer": false,
  "SnipeAtPokestops": false,
