### ISSUE TITLE
Necrobot Inventory Information 

### ISSUE THREAD

**Issue by ohitzbrian** [NECROBOTIO/NecroBot#4820]
Is there a way to make necrobot show how much pokeballs/potions/revives you have?

### Other Information
Version: 0.8.5
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Gateway753** [comment]
Telegram does it

**Comment by ohitzbrian** [comment]
okay thank you

**Comment by theloser** [comment]
Just set "DetailedCountsBeforeRecycling" to true.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
