### ISSUE TITLE
Asks for 2FA code even after 2FA has been disabled

### ISSUE THREAD

**Issue by mioriee** [NECROBOTIO/NecroBot#4821]
[04:57:56] As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[04:57:56] Opening Google App-Passwords. Please make a new App Password (use Other as Device)
[04:58:03] Make sure you have entered the right Email & Password.
Screenshoot
![error](https://cloud.githubusercontent.com/assets/20920276/17573445/9d09b0be-5f84-11e6-8d19-22b1397be572.png)

**Comment by jakesmurf** [comment]
I was able to get around this by logging into my gmail account fresh and then log back out using a browser.  

It seems to let you start the client up again.   

Unfortunately, I have no idea how to get around it if you're trying to rotate IPs constantly or something.

**Comment by albysprx** [comment]
every locations with hide.me vpn and some of okayfreedom have this problem, i don't have this with cyberghost (but it have almost every ip softbanned)

**Comment by mioriee** [comment]
It was work fine before,then I kinda want to try use some proxy and then that happen,disable proxy and the problem still exist.

**Comment by Dayclone** [comment]
Its because you guys are using proxies or VPN and Google is flagging it. When you leave the window open it opens up a window to allow for you to login. I would suggest you turn off security for apps that have lower security in Google. https://support.google.com/accounts/answer/6010255?hl=en

**Comment by mioriee** [comment]
Tried to turn on 2FA then turn it off but the problem still exist. Tried that security for apps to on and off,nothing changed. Not sure if my IP flagged because I tried NecroBot with another account and it works fine. It's more like account thingy but I still can login fine in my phone

**Comment by dddbliss** [comment]
This is a google account issue, not a bot issue. This has to due to Google treating your account as if 2FA is active when it is not.

**Comment by fischersito** [comment]
same problem here!, can't fix!
