### ISSUE TITLE
bot throws away higher cp pokemons and keeps lower ones(

### ISSUE THREAD

**Issue by CharliePrown** [NECROBOTIO/NecroBot#4823]
well,  after first use he throw them all away, only kept 20 of the 91 seen ones, nice...

then i thought i got used with, edited the config and kept 1 duplicate, but he does not keep the high one.

dratini: 629 and 255, the 629 cp thrown away.

wiki is not that useful, config tab is short as hell.

so what do we have to do to keep at least one of each kind and then that one with highest cp?

config at start is just for fast ep but low pokemon collection am i right(

but cannot be to get up to lvl 30 mabye with loosing all one per species catches therefore.

thanks a lot

**Comment by steponme** [comment]
Iv man. well, i think.

**Comment by ausscheider** [comment]
post your config

**Comment by theloser** [comment]
There is a current known bug with pokemon transfer. Please wait for an update.

**Comment by CharliePrown** [comment]
config is out of the box

just edited...keep deuplicate  0 to 1 

so i thought he keeps one of each kind and therefore the highest cp?

**Comment by ausscheider** [comment]
what do you want? high IV or high CP?

"PrioritizeIvOverCp": false <--- this one for high CP
or
"PrioritizeIvOverCp": true <---- this one for IV

**Comment by ruchern** [comment]
You probably prioritised IV over CP.

**Comment by CharliePrown** [comment]
well maybe i did so, seems legit

is iv over cp always an advantage or keep it off?

thx

**Comment by CharliePrown** [comment]
EDIT:

iv is not over cp

but sometimes in the console says:

xxxx with xxx cp sent, highest xx cp

which for me reads like...lower one kept?

or just misunderstanding?)

**Comment by CharliePrown** [comment]
[01:03:37] (VERSCHICKT) Voltobal        - WP:  480  IV:  80.87%   [Beste WP:  480  IV:  80.87%] (Bonbons: 45)
[01:03:44] (VERSCHICKT) Karpador        - WP:   58  IV:  95.44%   [Beste WP:  147  IV:  95.83%] (Bonbons: 889)
[01:03:50] (VERSCHICKT) Karpador        - WP:  147  IV:  95.83%   [Beste WP:  147  IV:  95.44%] (Bonbons: 889)
[01:03:54] (VERSCHICKT) Karpador        - WP:  147  IV:  95.44%   [Beste WP:  147  IV:  95.44%] (Bonbons: 889)
[01:04:00] (VERSCHICKT) Dratini         - WP:  219  IV:  95.45%   [Beste WP:  219  IV:  95.45%] (Bonbons: 61)
[01:04:06] (VERSCHICKT) Safcon          - WP:  269  IV:  95.91%   [Beste WP:  269  IV:  95.91%] (Bonbons: 20)
[01:04:12] (VERSCHICKT) Nebulak         - WP:  365  IV:  98.01%   [Beste WP:  365  IV:  98.01%] (Bonbons: 16)


just a copy and paste sample.

**Comment by Pokemongobottttttt** [comment]
I dont think there is anything you can do about it at the moment. I have tried many many different settings/combinations, as well as read this problem from multiple people. I feel like every option results in it keeping the best IV for whatever reason.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
