### ISSUE TITLE
"SnipeAtPokestops": true freezes bot

### ISSUE THREAD

**Issue by Zarovzky** [NECROBOTIO/NecroBot#4824]
This is a strange issue that makes me not understand bots sniping behaviour.

So with "SnipeAtPokestops": TRUE the bot will freeze at the first pokestop it finds. 
This has been working for around 8 hours as TRUE but now it doesnt work anymore. 
**When does the bot snipe IF NOT in a pokestop?**

With "SnipeAtPokestops": false the bot never snipes anything... 
How to set the bot to snipe when NOT AT pokestops?

Ah and this is my config btw.
[config.zip](https://github.com/NECROBOTIO/NecroBot/files/412239/config.zip)

**Comment by psblackz** [comment]
yes this happen to me too. Why ?

**Comment by psblackz** [comment]
the 1st pokestop the bot find, complete freeze!

**Comment by deduijk** [comment]
Search, read, get the answer.
turn off pokezz option and it works.

**Comment by theloser** [comment]
Have you searched for "first pokestop" before filing this issue? No, you haven't, otherwise you would have found a solution: set GetSniperInfoFromPokezz to false.

**Comment by Zarovzky** [comment]
but i want to use pokezzz to snipe whenever available lol...

**Comment by psblackz** [comment]
both pokezz ?

**Comment by theloser** [comment]
If you want to use pokezz, bot just freezes.
So, you ether can live with the freeze or turn pokezz off.
Your turn.

And please close this issue, thanks.
