### ISSUE TITLE
can't snipe at all?

### ISSUE THREAD

**Issue by mrturkk** [NECROBOTIO/NecroBot#4829]
![sssssss](https://cloud.githubusercontent.com/assets/20909623/17573808/2440f132-5f5d-11e6-8745-e7bccb31c7d1.jpg)

**Comment by kokkie2012** [comment]
Same here....

**Comment by Sylencer90** [comment]
Whenever i turn on sniping the bot freezes up for me.

**Comment by ausscheider** [comment]
@Sylencer90 
set "GetSniperInfoFromPokezz": false,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
