### ISSUE TITLE
INFORMATION! Speed bans

### ISSUE THREAD

**Issue by Reborn1990** [NECROBOTIO/NecroBot#4830]
Hey i don't know how much people are experiencing this or if maybe I'm just unlucky. I used to have my speed set to 40 and 30 for my 2 bots. i couldn't get the bot to run more than 30 mins a few hours ago. i adjusted the speed for both bots to 25 and they have been running for a little more than an hour. Anyone else experiencing this?

**Comment by ruchern** [comment]
Niantic limitation. Run only 1 bot now.

**Comment by Reborn1990** [comment]
alright. if i use one can i go do what ever speed i want?

**Comment by smoothrunnings** [comment]
@Reborn1990  Speed only work if DisableHumanWalking is set to false. I have my speed set to 9.0km, but technically a average person can walk a max of 5 kmph.

**Comment by Reborn1990** [comment]
@smoothrunnings i understand that part but before i was able to set my speed to 40 and let the bot run over night no issues with disablehumanwalking set to false.

**Comment by theloser** [comment]
Yeah,but "before" Niantic was less strict in banning ip addresses I suppose. So "now" is a different time with a different Niantic banning policy.

But: this does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by Caterpee** [comment]
My speed is set to 7 and I'm only running a single bot. Does not prevent me from getting soft banned after running the bot for just a couple of minutes though.

**Comment by iwantmyfile5** [comment]
@theloser If this is a Niantic issue, wouldn't other bots be affected?

**Comment by Reborn1990** [comment]
I can confirm its what was originally posted i ran 2 bots at a lower speed for almost 2 hours and then i got soft banned. i am running one bot at 40 to verify results.

**Comment by jumpcom** [comment]
it's not just walkingspeed parameter that cause softban those included 

DelayBetweenPokemonCatch (i set to 1000) and  DelayBetweenPlayerActions (i set to 2500)

**Comment by Caterpee** [comment]
"DelayBetweenPlayerActions": 7500,
"DelayBetweenPokemonCatch": 4500,

I always use these settings. Doesn't really help though.

**Comment by theloser** [comment]
@iwantmyfile5 Maybe, I don't know, I don't use other bots.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
