### ISSUE TITLE
Full pokemon bag and nothing happens

### ISSUE THREAD

**Issue by suzsuzuki** [NECROBOTIO/NecroBot#4833]
I'm using the default configuration in 0.85 and can't cath any pokemon. Also deleted the mr.mime  in transferFilter  and none is tranfered,  (i have moe than 30 mr. mime and it's not in "notToTransfer" list

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by ausscheider** [comment]
what you have in your config on this?

  "KeepMinDuplicatePokemon": 3,

**Comment by suzsuzuki** [comment]
sorry... solved just restart the bot

**Comment by theloser** [comment]
If it's solved, please close this issue, thanks!
