### ISSUE TITLE
Not evolving the correct amount of pokemons

### ISSUE THREAD

**Issue by LuisAlmeidaIST** [NECROBOTIO/NecroBot#4838]
Hi guys,

I had 2 Rattatas and 300 candies, they are on the evolve list and i have this on the config file

```
"CatchPokemon":true,
"KeepPokemonsThatCanEvolve": false,
"KeepMinDuplicatePokemon": 1,
```

Expected result:
Evolve 2 Ratatas
Transfer N-1 Raticates

Verified Result:
Evolved 1 Ratata
Transfer 1 Ratata (i ended up with 0 ratatas)
Transfer N-1 Raticates

here is the Log:
```
[23:57:33] Potential Evolutions: 2 -> this was only for the ratatas
[23:57:33] Catch 28 more Pokemon to use a Lucky Egg!
[23:57:34] Rattata successfully for 500xp -> Evolved
[23:57:39] Rattata     	- CP:   82  IV:  50.10%   [Best CP:  106  IV:  34.51%] (Candies: 319) -> Transfered
```

Thank you very much

**Comment by actislav** [comment]
1 ratata saved because of KeepMinDuplicatePokemon = 1, another transfered, because of bug in current master with multi move list

**Comment by LuisAlmeidaIST** [comment]
No no, one was evolved. Apparently the code works like this: "Look I have 2 ratatas but I can only keep 1, let's  transfer one but before that let me evolve one first" 
It should have evolved both, the evolve method should have priority over the transfer method. 
Something like 
While (can evolve) {evolve() ;} 
While (can transfer) {transfer() ;}

**Comment by samtch999** [comment]
same problem

**Comment by nfettinger** [comment]
Duplicate issue #3244
