### ISSUE TITLE
Serious problem with transfers

### ISSUE THREAD

**Issue by CarlitosDubs** [NECROBOTIO/NecroBot#4839]
Hi , since I updated to version 0.8, Necrobot transferred me all Pokemons . No matter if it is duplicated or not, I transferred ALL Pokemons and not let me progress . Any solution?

Version: 0.8.5
Windows 7

**Comment by Gladi0n** [comment]
set "KeepMinDuplicatePokemon" from 0 to the number of dublicate pokemon you want to have

**Comment by actislav** [comment]
already fixed in current master pls update it from source or wait new release

**Comment by schwartzadev** [comment]
update required for fix.
