### ISSUE TITLE
Manual local snipe issue Necro v0.8.5

### ISSUE THREAD

**Issue by 123787** [NECROBOTIO/NecroBot#4840]
Dear developers, 

I found out that the necro v0.8.5 did not work well on manual snipe using local coordinate. I have turn off the 3rd party coordinate feed info from pokezz, pokesnipers, and pokewtcher and hope it will snipe using local coordinate. However, nothing is happening, no snipe is activated. Below are the cited lines from my config.json.

 "GetSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

"UseSnipeLocationServer": false,
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": true,

Note, The previous version does work on local snipe with all the 3rd party snipe off. On this version, I could not resolve this issue myself therefore would require help and guidance
Many Thanks.
Regards,
123787

**Comment by kurozani** [comment]
tagging here, i want to know too

**Comment by 123787** [comment]
I would like to add, on the necro V0.8.1 the lines that used to work with manual location snipe is as below,

"GetSniperInfoFromPokezz": true,
"GetOnlyVerifiedSniperInfoFromPokezz": true,

"UseSnipeLocationServer": false,
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": true,

By using manual location snipe, with the same setting above in necro v0.8.5 the bot will stop at a successfully collected pokestop (blueline) but from there it just stuck there without error message. I notice it after leaving it 3 hour with the same line. I have restart the bot to check, and it after one successive pokestop it then hangs there.  

Update Note: After tested the same line with all previous necrobot versions v0.85, v0.8.1, v 0.7.7. I believe the same setting have stop working on all bots for manual location snipe.

**Comment by JustRegisteredToSayThis** [comment]
#4679

**Comment by glitter007** [comment]
Same issue happening to me. I have tried changing values but nothing works.

**Comment by junior00719456** [comment]
Turn all the snipes to false aka off for some reason they aren't working and is making the bot stupid! So turn all snipes to false then restart your computer then boot up the program but boot it up as an administrator! Solved my issues now I'm getting 200k an hour!

**Comment by 123787** [comment]
Dear @junior00719456,

Could you please clarify your statement of 'Turn all the snipes to false '. I have set to the setting below  to simulate what you have describe and the snipe is still not working. 

"GetSniperInfoFromPokezz": false,
"GetSniperInfoFromPokeSnipers": false,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": false,

"UseSnipeLocationServer": false,
"SnipeAtPokestops": false,
"SnipeIgnoreUnknownIv": false,

Usually to know the manual location snipe works is the bot will show the MinPokeballsToSnipe before start of the snipe. Nothing of such for now.

**Comment by 123787** [comment]
Apparently looking at newer issues that "GetSniperInfoFromPokezz":true will casue the bot hang. 
https://github.com/NECROBOTIO/NecroBot/issues/4983
https://github.com/NECROBOTIO/NecroBot/issues/5010
https://github.com/NECROBOTIO/NecroBot/issues/5011

However as tested with the setting on my first post, with all 3rd party snipe off, the manual location snipe is not working. I believe the manual location snipe requires pokezz info to true, but since that crashes the bot so the manual location sniping is not usable.

**Comment by CptnCrazy** [comment]
I  got the same problem.
I think it is because of the latest update, which removed the 3rd party code plugin.
Unless there is a new update I don't think we can do much, but I would gladly be wrong in this case...

**Comment by Profetorum** [comment]
Were be possible, with 0.8.1, to exp into config locations and snipe in the same time?

**Comment by nfettinger** [comment]
We cannot help you with sniping.
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
