### ISSUE TITLE
Transferring all my Pokémon 

### ISSUE THREAD

**Issue by tatejensen6** [NECROBOTIO/NecroBot#4844]
Hello,
I have the necrobot for Pokémon Go, it has been working fine other than going ham on transferring all my Pokémon

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
