### ISSUE TITLE
no pokestops useable

### ISSUE THREAD

**Issue by itzjaydon** [NECROBOTIO/NecroBot#4845]
![image](https://cloud.githubusercontent.com/assets/20823634/17574900/d6887faa-5f5c-11e6-8f9f-8c091c133795.png)

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by itzjaydon** [comment]
@theloser so whats the fix?

**Comment by theloser** [comment]
Please use our Discord channels to get help with your questions.

**Comment by itzjaydon** [comment]
@theloser yeah but the issues page is here for a reason bro

**Comment by bulubebek** [comment]
run only 1 bot in 1 IP address. :)

**Comment by yonrin** [comment]
@itzjaydon Set "UseWebsocket": false, to TRUE. Worked for me

**Comment by iPollox** [comment]
@itzjaydon the issue page is mostly for bugs that the program has, which the devs can work from here and such. when there's other things available example, Discord these kind of stuff can be asked over there.

**Comment by theloser** [comment]
@itzjaydon I am not your "bro", and the issue page is for development issues only, NOT for config related issues. If you want help with your config or if you have trouble with siftbans, then go to the doscord channel and ask for help.

**Comment by itzjaydon** [comment]
@theloser sheesh, definitely the loser

**Comment by theloser** [comment]
I told you this is a softban related issue, and not a bug in the bot. I kindly asked you to use the Discord channel to get further assitance. You were still asking "so what's the fix?". The only, reliable fix for not getting softbanned is to not use any snipers/bots for PokemonGo. Other than that -- please go to the Discord channels to discuss softban related strategies.

Thanks a lot in advance.

**Comment by itzjaydon** [comment]
@theloser as you can see i asked so whats the fix **once** 13 hours ago dumbass, look back read what actually was said then come and talk to me instead of making up shit

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
