### ISSUE TITLE
Necro stop working

### ISSUE THREAD

**Issue by Drigod** [NECROBOTIO/NecroBot#4848]
after opening the necrobot it captures 1 or 2 pokemons and goes to a stop,then he don't do anything

**Comment by beelzbub** [comment]
same with me, it looks like there will be a more recent update of necro.

**Comment by theloser** [comment]
Please use the search function for issues -- there already is a solution out there!
And please close this issue.

**Comment by deduijk** [comment]
Search, there are multiple issues with this AND the solution (well...work-around).

**Comment by myn** [comment]
It takes as much effort to post "use the search function" as it does to provide a link to the solution, in most cases. Be nice to each other..

**Comment by Drigod** [comment]
i realy don't find the issue with my problem,
 i'm not a frequently user og github and i don't now how deleta an issue

**Comment by qwer4790** [comment]
Use 0.8.1, it's working

**Comment by wyvern19** [comment]
"UseSnipeLocationServer": false,
  "SnipeAtPokestops": false,
