### ISSUE TITLE
Transferring all my Pokémon 

### ISSUE THREAD

**Issue by tatejensen6** [NECROBOTIO/NecroBot#4849]
I have the necrobot and recently it just started transferring all my Pokémon that I only had one of. Right when I run the necrobot this issue happens please help

**Comment by johnhvp** [comment]
could be either:
keepmincpvalue 
or
transferweakpokemon=true

**Comment by JonSuperKnife** [comment]
change "KeepMinDuplicatePokemon": 0,
V
"KeepMinDuplicatePokemon": 1,
(Just change 0 to 1) 
make sure to check other threads before posting , they probably have been solved

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by actislav** [comment]
fixed in #4827

**Comment by schwartzadev** [comment]
fixed
