### ISSUE TITLE
[Request} Please change "HandleEvent" code to not contain pre-formatted strings

### ISSUE THREAD

**Issue by theloser** [NECROBOTIO/NecroBot#4851]
### Expected Behavior

Values translated by translation.XX.json file should not contain any pre-formatted strings.

### Actual Behavior

Values translated by translation.XX.json file should do contain pre-formatted strings.

### Steps to Reproduce

Change language to "en".
Start the bot and watch the output. When pokemon are transfered this is the output:
```
[01:49:14] (TRANSFERED) Rattata      - CP:   72  IV:  72.81%  [Best CP:  412  IV:  72.54%] (Candies: 361)
```

This is because of some formating done in at the following code (in ConsoleEventListener.cs):
```
        private static void HandleEvent(TransferPokemonEvent transferPokemonEvent, ISession session)
        {
            Logger.Write(
                session.Translation.GetTranslation(TranslationString.EventPokemonTransferred,
                session.Translation.GetPokemonTranslation(transferPokemonEvent.Id).PadRight(12, ' '), 
                transferPokemonEvent.Cp.ToString().PadLeft(4, ' '),
                transferPokemonEvent.Perfection.ToString("0.00").PadLeft(6, ' '), 
                transferPokemonEvent.BestCp.ToString().PadLeft(4, ' '), 
                transferPokemonEvent.BestPerfection.ToString("0.00").PadLeft(6, ' '), 
                transferPokemonEvent.FamilyCandies),
                LogLevel.Transfer);
        }
```

Please change this to the following:
```
        private static void HandleEvent(TransferPokemonEvent transferPokemonEvent, ISession session)
        {
            Logger.Write(
                session.Translation.GetTranslation(TranslationString.EventPokemonTransferred,
                session.Translation.GetPokemonTranslation(transferPokemonEvent.Id), 
                transferPokemonEvent.Cp.ToString(),
                transferPokemonEvent.Perfection.ToString("0.00"), 
                transferPokemonEvent.BestCp.ToString(), 
                transferPokemonEvent.BestPerfection.ToString("0.00"), 
                transferPokemonEvent.FamilyCandies),
                LogLevel.Transfer);
        }
```
 Thanks!

(If i'd knew how to create a pull request I would have done this by myself, sorry!)

**Comment by LordDeimos** [comment]
Well you need first to make a fork of the current state of the master branch on your repo, modify your repo like you proposed then on you make a pull request from necro official repo and yours, this way you make a pr.

Probably I could explain better, but I am like in sleep deficit and can't even think right now.

**Comment by theloser** [comment]
@LordDeimos Thanks for trying to teach me making pull requests. I tried several guides bot none was working so far, I will try to get this working and create a pr.

**Comment by Oolaruu** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/5113

**Comment by Oolaruu** [comment]
I've submitted a fix for ya issue.

**Comment by FabryB** [comment]
Why was this done?

The formatting was done by me to improve readability in #3304

This was the improvement:
BEFORE:
![before](https://cloud.githubusercontent.com/assets/312795/17491612/a49e8080-5da8-11e6-8a08-4a1348319f0d.PNG)

AFTER:
![after](https://cloud.githubusercontent.com/assets/312795/17491618/a9c1ed0e-5da8-11e6-984f-a089e1c14bf8.PNG)

**Comment by theloser** [comment]
@FabryB It's better to do the "layout" in the translation file (which everyone can customize), not in actual code (which only a few can edit). That's why I asked for this change.

**Comment by FabryB** [comment]
Then please show equivalent of padleft and padright in translation file, so I can update them accordingly

**Comment by theloser** [comment]
@FabryB Just put this in your translation file:

|{0,-20}| gives you
```
|Rattata             |
```
and |{0,20]| will result in
```
|             Rattata|
```
Same for number etc. Hope that helps!
