### ISSUE TITLE
Transfering pokemons, Pokemon inventory full

### ISSUE THREAD

**Issue by alexmanea2000** [NECROBOTIO/NecroBot#4852]
Hello! I searched for like 3 hours and I tried to modify my config in many ways, but I couldn't manage how to make my bot to catch at least 1 or maximum 2 pokemons for every pokemon and transfer the low CP/IV ones.It catches all pokemons, it doesn't transfer almost no pokemon and after some time, I get 250/250 pokemons and I receive the message "Pokemon inventory full".

If you don't understand, here is an example: I own 2 Evee, one has CP 600, one has CP 550, if the bot catches a new Evee CP 580, I want the bot to transfer the 550 CP Evee.

Thank you!

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by Zarovzky** [comment]
Ill give you my config, it should work and clean not needed pokemons, just remember to change the coordinates to avoid softban. 

[config.zip](https://github.com/NECROBOTIO/NecroBot/files/412356/config.zip)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by dartmagus** [comment]
I had the same problem, i didnt change anything related to transfer pokemon, but i reset config and it worked...
