### ISSUE TITLE
changing ip due to softban

### ISSUE THREAD

**Issue by solbiee** [NECROBOTIO/NecroBot#4853]
hi i have been trying to work around the soft ban issue since when my friends laptops bot as well when they come over, so i was trying to change my ip to a static ip and whenever i run the bot it has a debug error. 1

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by solbiee** [comment]
ok thanks

**Comment by djdookie** [comment]
Close pls.
