### ISSUE TITLE
GPX

### ISSUE THREAD

**Issue by NozFiend** [NECROBOTIO/NecroBot#4854]
First off, not sure who the owner is but GREAT WORK on necrobot!! this small program fuckng ROCKS!!!!!!!
finally figured it all out within one night.

I would loooooooveeee to get my gpx file working. I have a great monica pier/3rd street prominade route that's fukng PREMIUM for stops and pokemon. 
I even deleted that metadata section in my gpx file and it' does not work :/ 
Is that something you're working on? or am I doing something wrong? 
thanks alot everyone

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / GPX file issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by NozFiend** [comment]
Definitly a development Issue or bug.. and the discord channels are hectic I won't find my answer there. 
upon further investigation, the [GPX Wiki](https://github.com/NECROBOTIO/NecroBot/wiki/GPX-Pathing-Setup) has a post saying they're looking for a new source. I'm hoping they can re-enable GPX
thanks!

**Comment by theloser** [comment]
I don't use GPX, but I know for sure it works. Just try one of the already [submitted GPX files](https://github.com/NECROBOTIO/NecroBot/wiki/Locations-&-GPX-Route-Files) to see if it's working.

You said you did delete that metadata section (as you are supposed to do), but maybe you did it wrong and broke it? That's why I asked you to go to the Discord channels to get further assistance.

Thanks for your understanding.

**Comment by NozFiend** [comment]
For sure bro thanks for the tip. I will try one of the submits and compare them to my file. maybe I did break it. haha cuz It would say "no pokestops nearby" or some error similar to that. 
thank you ill try it

**Comment by theloser** [comment]
Wait, first you said "it didn't work". Now you are saying it worked, but you can't find any pokestops nearby -- really?

No pokestops found --> softban. Has NOTHING to do with your GPX file.

**Comment by NozFiend** [comment]
No you are confusing yourself buddy SLOW DOWN

**Comment by NozFiend** [comment]
the GPX does work thanks to the submits that were uploaded. I remade a gpx file of santa monica using that website Wtracks. Now that my bot is folling my gpx coordinates, I am catching pokemon but no stops :/

**Comment by NozFiend** [comment]
wow it barely caught 1 pokestop when the 3rd street promenade has like 30 in the same area xD

**Comment by theloser** [comment]
@NozFiend I am not your buddy, and I am not "confusing myself". You said (quotes):
>I even deleted that metadata section in my gpx file and it' does not work :/ 

and later

>  I'm hoping they can re-enable GPX

I said, GPX **is** working, it's your GPX file that's causing issues. Then you said:

> cuz It would say "no pokestops nearby" or some error similar to that.

That's completely the opposite of "GPX not working". GPX **is** working. If you have "no pokestops nearby" this is a **softban**.

Last but not least you said:

> it barely caught 1 pokestop when the 3rd street promenade has like 30 in the same area

That's also very likely a GPX file issue, the bot is running fine.

Please, go to the Discord channels to get further assistance with your GPX file, thank you!

**Comment by NozFiend** [comment]
no its not soft ban you big bafoon xD lmfao if you're not my buddy and cannot solve my riddle then kindly SHUT THE FUCK UP
