### ISSUE TITLE
0.8.5 Hangs at logging in with google (behind a proxy)

### ISSUE THREAD

**Issue by vfuyong** [NECROBOTIO/NecroBot#4857]
0.7.6 is working fine, but all recent releases are not. I am behind a proxy.

**Comment by Georgexp** [comment]
I have same issue was working fine until a few hours ago..

**Comment by djdookie** [comment]
I believe 0.7.6 doesn't use proxies correctly, though you can enter the proxy data in the config. I think if your proxy is very slow, you have to wait some minutes and it connects. Or try again some times and give it some time. If nothing works, use another proxy. Some free proxies work, some do not. Give it time. But I bet you can't use a proxy with 0.7.6 and oyu will quickly be IP-softbanned if you try to use 2-3 bots on that version, proxy in config or not. This is also the reason it connects always fast with 0.7.6. This is my observation. ;)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
