### ISSUE TITLE
(Suggestion) Unban before capturing Pokemon

### ISSUE THREAD

**Issue by yorkhung** [NECROBOTIO/NecroBot#4864]
Currently, if DisableHumanWalking=true, Necrobot will get softban if travel distant greater than 200m.
Upon arrive to pokestop, it captured the pokemon first so all the pokemon will flee.
Suggestion is to pick up the pokestop item to unban it before capturing the pokemon

Another suggest is to add a (Max teleport range), so all teleport occurs only under 200m. If teleport is greater than 200m it will teleport to the middle point. This may prevent the softban from happening.

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by AdamWeishaupt1776** [comment]
I had submitted a PR for this exact thing a long time ago (before necro/pokemob split).

The best solution IMO would be to add (yet another!) config var called something like 
```
"TestSoftbanOnStartup" : true
```

so if that var is set to true, the first thing the bot does, is go to a Pokestop and spin it until it returns XP, before the bot tries to do anything else.

**Comment by nfettinger** [comment]
How about you set your bot NOT to get softbanned. You are just increasing the risk for the rest of us.
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
