### ISSUE TITLE
Always getting soft banned with necro bot

### ISSUE THREAD

**Issue by idkwateva** [NECROBOTIO/NecroBot#4866]
SO, I don't understand what's the problem but after the new bot update (after the pokemon change their API) I'm always getting softbanned in 1 hour or less. I didn't change my config json. Walk 5km/h with 1000m range.

I'm also using pokemongo-bot but not experiencing this softbanned much, even though it runs 6 hours++

Any setting i could change?

**Comment by ikkosams** [comment]
sama kayak ane gan,,,,ane juga kayak begitu dari kemarin malam,,,softbanned mulu dah sejak pembaruan ke versi 0.8.5

**Comment by smoothrunnings** [comment]
@idkwateva  how many bots do you have running? They changed they policy, its now only 1 bot 1 IP. Even if you log in with a device while you are farming you'll get soft banned.

**Comment by fass1993** [comment]
i'm logged in with my phone and i don't get softbanned

**Comment by m4nj1** [comment]
@fass1993 is not your account, is your IP

**Comment by ikkosams** [comment]
saya dari Indonesia,,,saya akan coba bantu,,,sepertinya Niantic membatasi hanya 1 alamat IP saja,,,jika kamu menggunakan alamat IP lain,,,maka akan di-softbanned,,,,saran saya gunakan HH yang biasa kamu gunakan mai PokemonGo sebagai Hotspot,,,jangan pakai jaringan lain,,,itu bekerja baik untuk saya,,,semoga bisa membantu

**Comment by idkwateva** [comment]
I'm running only one bot per ip.

**Comment by smoothrunnings** [comment]
@idkwateva they could have prem banned you.

**Comment by idkwateva** [comment]
nope.... i'm getting softbanned every hour or so... the bot will unban itself and then got softbanned again in one or two hour....

**Comment by kauegimenes** [comment]
Can you share the log that says you got softbanned?

**Comment by bootlick** [comment]
have you looked in #4868

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by sharan16** [comment]
It is not your IP I think same problem happened to me.There were only 2 pokestops where I put the default longitude and latitude so it kept circiling those stops.Since you cannot refarm a stop in under like 5 minutes it kept thinking it is banned.Find a fairly pokestop infested area near you and set that.
