### ISSUE TITLE
No usable pokestops in your area? how to deal with that?

### ISSUE THREAD

**Issue by huCyy** [NECROBOTIO/NecroBot#4867]
No usable PokeStops found in your area. Is your maximum distance too small?

please help me with this?

**Comment by ikkosams** [comment]
saya dari Indonesia,,,saya akan coba bantu,,,sepertinya Niantic membatasi hanya 1 alamat IP saja,,,jika kamu menggunakan alamat IP lain,,,maka akan di-softbanned,,,,saran saya gunakan HH yang biasa kamu gunakan mai PokemonGo sebagai Hotspot,,,jangan pakai jaringan lain,,,itu bekerja baik untuk saya,,,semoga bisa membantu

**Comment by yachinor** [comment]
same issue here, no usable pokestops in your area since 1 hour ago.

**Comment by huCyy** [comment]
@yachinor it seems its a softban issue. need to use 1 ID per IP. but before 2 ids worksjust fine. lets see

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by yachinor** [comment]
@huCyy Hi, dude, ur softban fixed? Its been 2 hours....

**Comment by ragnastevie** [comment]
I had to remove the LastPos file in my Config folder to fix this.
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/pokemon-go-chat/565006-attention-no-usable-pokestops-found-your-area-your-maximum-distance-too-smal.html

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
