### ISSUE TITLE
Kaspersky detected malware in NecroBot

### ISSUE THREAD

**Issue by CapzFelix** [NECROBOTIO/NecroBot#4870]
This morning, suddenly Kaspersky detected malware in NecroBot. The malware detected is USD:DangerousObject.Multi.Generic.

I would appreciate a statement from Necrobotio here.

**Comment by theloser** [comment]
Kaspersky is not the only one who flagged NecroBot as "malicious" in the past few days. Pretty sure it's a "false positive", but if you don't trust it, then don't use it.

**Comment by djdookie** [comment]
Simply have a look into the source code if you don't trust the Necrobot! ;)
