### ISSUE TITLE
What better "SnipingScanOffset": 0.005, or   "SnipingScanOffset": 0.003,

### ISSUE THREAD

**Issue by vipery** [NECROBOTIO/NecroBot#4871]
Hi Boiz. What better? Im only use sniper Necro+Feeder. What i must set for better sniping?
Thnaks

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
