### ISSUE TITLE
add back the ability to choose how many pokeball,greatball,ultraball and potion I want to keep in config.json

### ISSUE THREAD

**Issue by Speedmod88** [NECROBOTIO/NecroBot#4872]
so the title say everything!

It should be great to but back in the config file the amount of each items I want to keep before recycling...
because right now, I have like 200 pokeball, 10 greatball and 3 ultraball...

because put a max amount of pokeball like 300 can give me 300 pokeballs and 0 great 0 ultra... well don't need to explain you that its better having 20 pokeballs, 100 great 100 ultra! ;)

same for potion and revive!

Thank You
Continue you great work guys!
Regards!

**Comment by theloser** [comment]
If you want to keep 300 balls in total, the bot will keep the 300 BEST balls you will find. No need to set specific amounts.

If you are running low on Greatballs and/or UltraBalls check your settings, you are probably wasting to many an low level/low iv pokemon.

And this does not ssem to be a development issue or a bug. More like a config.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.

**Comment by nfettinger** [comment]
We moved away from your suggestion to our new method because it is ALWAYS better to keep better balls and potions.
