### ISSUE TITLE
bot freezes atfter the first pokestop loot, what to do ? 

### ISSUE THREAD

**Issue by julian3101** [NECROBOTIO/NecroBot#4873]
having a problem here, i just DLed the new version of necrobot 0.8.5 and every time i go my first pokestop the game stops and i dont know why. it just freezes. i left it for about 15 min now and still nothing. This happens everytime i start it up again. any suggestions ?

**Comment by aaron25th** [comment]
got that to

**Comment by theloser** [comment]
Did you search for issues already describing your issue? There are TONS and the solution has been posted already.

Please close this issue.

**Comment by smoothrunnings** [comment]
@julian3101 change your start point.

**Comment by wyvern19** [comment]
"UseSnipeLocationServer": false,  "SnipeAtPokestops": false,

**Comment by TagorHP** [comment]
@wyvern19 if "SnipeAtPokestops"=false, the snipe function will not running.
I think something wrong about sniping the pokezz, so skip it at the moment.
"SnipeAtPokestops"=true, 
"GetSniperInfoFromPokezz": false,  -> disable snip from pokezz.
"GetSniperInfoFromPokeSnipers": true, -> snip from pokesnipers.
