### ISSUE TITLE
bot doesnt show upgrade messages despite upgrading pokemon

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#4875]
### Expected Behavior
the bot should give feedback to the user when upgrading pokemon via text output

### Actual Behavior
it appears the bot does no longer give visible feedback to the user whenever it upgrades pokemon, thus resulting in the user thinking the bot froze while its actually busy upgrading.

### Your config.json
http://pastebin.com/WCiRk5Aa

### Steps to Reproduce
activate upgrading of pokemon in any given config, run necrobot 8.5 and see your stardust melt.

### Other Information
Version: 0.8.5
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
levelup/powerup

**Comment by theloser** [comment]
Duplicate of #4859 (did you even search for similar issues?)
Please close this issue, thanks!

**Comment by Marsinator** [comment]
I sure did not, sorry about that.
