### ISSUE TITLE
Higher IV being transferred even when PrioritizeIvOverCP is set to 'true'

### ISSUE THREAD

**Issue by hostagexii** [NECROBOTIO/NecroBot#4876]
```
  "KeepMinCp": 1500,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
```
![bang](https://cloud.githubusercontent.com/assets/20957480/17576145/a086b51c-5f3d-11e6-8fa0-491a7ac846ff.png)

In one scenario I had a Flareon with 1300 CP and an IV of 94 and another one at 2203CP and IV at 85.
However, my higher CP was transferred even though it fell below the 1500 parameter, the higher IV, while not at 95 should have been kept since IV should be prioritized. Or am misunderstanding how it all works?

Attached is a different example.

**Comment by theloser** [comment]
There is a known bug with some tranfers in the current version. Please wait until it's fixed, thank you.

**Comment by TagorHP** [comment]
In my opinion, better to set at "PokemonsTransferFilter", and maximize the min value, i.e:
setting below will always kept 3-flareon with the highest CP or IV.
    "flareon": {
      "KeepMinCp": 5000,
      "KeepMinLvl": 101,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 99.9,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },

**Comment by can99** [comment]
"KeepMinCp": 1500,
 "KeepMinIvPercentage": 95.0,

flareon cp = 1257
flareon iv = 85.54

of course it transferred

**Comment by jumpcom** [comment]
it's not bug ! maybe it was overridden by PokemonsTransferFilter remove pokemon in that array and it work fine

**Comment by theloser** [comment]
@jumpcom I didn't say **this** is a bug. I said **there** is a bug with transfers (see #4705 and #4827), and because this bug can lead to some strange transfers, he/she should wait until it's fixed and then try again.

**Comment by nfettinger** [comment]
Duplicate #3338
