### ISSUE TITLE
change latlong work?

### ISSUE THREAD

**Issue by Sudiddo** [NECROBOTIO/NecroBot#4879]
Guys i want to know,

i use someone config, and it's located on central park, i forget to change the latlong to jakarta, indonesia.

and its work, and then i realize and change it into jakarta latlong, and i got ip banned, so i try to change it again into central park latlong. It's work !

any idea?

**Comment by theloser** [comment]
Wait, what?

This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by Sudiddo** [comment]
yes, it works.. i dont even know what happen.. i think its not a config issue

**Comment by theloser** [comment]
If it works now, please close this issue.

**Comment by Sudiddo** [comment]
well i just asking if this an issue or not, thank you for your hospitality.
