### ISSUE TITLE
Transfers some Pokemon, explained more in the description. 

### ISSUE THREAD

**Issue by sukhmypreet** [NECROBOTIO/NecroBot#4881]
Why is the bot transferring pokemon that are stronger than the weak? For example, I had a 1000+ CP Magmar, the bot managed to catch another Magmar, which was 31 CP. Instead of transferring the 31 CP for candies, it transferred the 1000+ CP Mangar, why is that? And is there a solution?

**Comment by derrickmehaffy** [comment]
Please read the wiki, this is explained there.

https://github.com/NECROBOTIO/NecroBot/wiki/Config#transferring

**Comment by iPollox** [comment]
Do you have "PrioritizeIvOverCp" to true?

**Comment by sukhmypreet** [comment]
no, "PrioritizeIvOverCp" is set to false.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
