### ISSUE TITLE
Transfer all my pokemon :(

### ISSUE THREAD

**Issue by andreslong** [NECROBOTIO/NecroBot#4882]

**Comment by sukhmypreet** [comment]
go into your config, and change "KeepMinDuplicatePokemon": 0, to "KeepMinDuplicatePokemon": 1,

it should work perfectly fine after that. :P

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by TagorHP** [comment]
also set "TransferWeakPokemon" into false.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
