### ISSUE TITLE
Cannot Use Necrobot 8.5 version 

### ISSUE THREAD

**Issue by kaonui** [NECROBOTIO/NecroBot#4883]
Hello guys, I am having problem to use 8.5 version when I launch the Necrobot.
It will pop up an error" Windows cannot access the specified device,path or file. You may not have the appropriate  permission to access them".

I have no problem to launch any version before 8.5

Please help...Check the online solution checking the access right , antivirus and etc nothing has block the application.

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version: Window 7 64 bits
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by theloser** [comment]
What did you do exactly?
Which file did you download?
Where did you extract the files?
How are you trying to run the bot?

**Comment by kaonui** [comment]
What did you do exactly?
Hello guys, I am having problem to use 8.5 version when I launch the Necrobot.
It will pop up an error" Windows cannot access the specified device,path or file. You may not have the appropriate permission to access them".

I have no problem to launch any version before 8.5

Please help...Check the online solution checking the access right , antivirus and etc nothing has block the application.
Which file did you download?
I downloaded the release.zip
Where did you extract the files?
Extract the folder to desktop
How are you trying to run the bot?
Open necrobot.exe

:/

**Comment by theloser** [comment]
Can you pleae upload a screenshot of the error message? Thanks in advance!

**Comment by Sasamechan** [comment]
![necro](https://cloud.githubusercontent.com/assets/20960739/17576856/c178f35c-5fba-11e6-9287-86d2ccf188a9.jpg)

**Comment by kaonui** [comment]
![wtf](https://cloud.githubusercontent.com/assets/20686973/17576860/033e75c0-5faa-11e6-86a0-45dce6c2de28.JPG)

Please check this

**Comment by kaonui** [comment]
Currently I am launching 8.4 version and it is working but not 8.5

**Comment by theloser** [comment]
You said, you checked your anti virus software, but maybe there is something you missed...?! Seems to me like Windows Defender or any other Anti Virus software is blocking your access to some files.

**Comment by IdontKnownothing** [comment]
The same here??
![necro crash](https://cloud.githubusercontent.com/assets/20960818/17577076/1ba414a8-5f50-11e6-82f3-2984296a52b7.png)

Help me please.

**Comment by theloser** [comment]
@IdontKnownothing You have a different issue. You are able to run the bot, but it crashed - that is most likely a configuration issue. Please use our Discord channels to get assistance in getting a working config.

**Comment by se1zur3** [comment]
I am also having the issue originally posted. Malwarebytes said that it found a backdoor installed and blocked it.

**Comment by IdontKnownothing** [comment]
Configuration OK and cheked
![configuration ok](https://cloud.githubusercontent.com/assets/20960818/17577176/14f0ebe4-5f51-11e6-9ed5-9edf02a1b073.png)


just restarted and crashed

**Comment by Sasamechan** [comment]
@theloser uhm i checked and it seems K*sp*rsky is behind the restriction and somehow i couldn't change its status from "untrusted" to "trusted" (still has red dot thingy on the application rules)... i have no idea :( but im running 0.8.4 vers and I hope it would do just fine >_<
thanks for the help anyway :)

**Comment by se1zur3** [comment]
I am also running kaspersky internet security so that must be the issue.

**Comment by kaonui** [comment]
Same thing running kaspersky . It seems like will have this issue

2016年8月11日 上午10:30於 "se1zur3" <notifications@github.com>寫道：

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
