### ISSUE TITLE
How to hatch eggs faster

### ISSUE THREAD

**Issue by canuckle604** [NECROBOTIO/NecroBot#4884]
Hey i was wondering, what settings should i keep to hatch my eggs faster? and also what settings can i use to let the bot know which (KM) egg i want to hatch

**Comment by Oolaruu** [comment]
You have to keep your humanwalk between 10-31 (?) i guess is better to keep 10-15km/h
and wait a bit or you'll get anyway softbanned so...

**Comment by canuckle604** [comment]
shit... LOL i want my eggs to hatch faster xD... any other suggestions or setup anyone uses thats reliable?

**Comment by Oolaruu** [comment]
Maybe take a train or a plane, should help.

**Comment by theloser** [comment]
If you would like to hatch your eggs faster, it's **actually very easy**:

- Take your phone, start the PokemonGo App
- Put an egg into an incubator.
- Throw your phone as fast and as far as you can.
- Rince and repeat.

Should work, havn't tested it, though.

**Comment by canuckle604** [comment]
LMFAO. ^

**Comment by canuckle604** [comment]
Maybe I should find the tallest building in my city and drop it down

**Comment by theloser** [comment]
@canuckle604 No, that will definitely not work. It's not the height, that counts for hatching eggs, I am sorry.
