### ISSUE TITLE
soo lagy and super slow

### ISSUE THREAD

**Issue by arabcurry** [NECROBOTIO/NecroBot#4885]
my necro bot is going really slow and lagging alot and my computer is really good so its my computer. it does one action and then doent do anything for a while. i think this might be a bug, just trying to help.

**Comment by mrteddi** [comment]
Sniping with Pokezz is currently not working. It has been fixed and merged (I believe) but not implemented in a release yet.

In the meantime set
  "GetSniperInfoFromPokezz": false,

**Comment by kurozani** [comment]
walking speed, check it

and delay action

**Comment by bootlick** [comment]
For sniping I am running all as false and the most recent Location Feeder, it is working perfectly.  I do adjust the scan though as I find it more successful.  "SnipingScanOffset": 0.05,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
