### ISSUE TITLE
How to set up and just get pokestops not catch pokemon?

### ISSUE THREAD

**Issue by lFeeeeelipe** [NECROBOTIO/NecroBot#4887]
How to set up and just get pokestops not catch pokemon?

**Comment by theloser** [comment]
Use the PokemonsToIgnore setting.

This does not ssem to be a development issue or a bug. More like a config issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by mrteddi** [comment]
You could also go into the config and set
  "CatchPokemon": false,
