### ISSUE TITLE
VS 2015 - The Type or namespace 'PokemonGo' couldn't be found

### ISSUE THREAD

**Issue by CDAGaming** [NECROBOTIO/NecroBot#4888]
### Expected Behavior
It should usually build successfully, with the usual 3 warnings

### Actual Behavior
74 Errors appear in VS 2015 and Build fails

Error:
CS0246 - The Type or namespace name 'PokemonGo' could not be found (are you missing a using directive or an assembly reference

### Steps to Reproduce
Happens When in VS 2015 while building

### Other Information
Version: V0.8.5 (Latest Commit)
Windows Version: Windows 7 x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Build in VS

EDIT: Fix was Reloading Project files

PLEASE CLOSE ISSUE!

**Comment by dddbliss** [comment]
We had some issues with reverting back to .net 4.5, pull and try again.
