### ISSUE TITLE
Bot not working after update

### ISSUE THREAD

**Issue by parthroxx** [NECROBOTIO/NecroBot#4889]
bot hangs in between after two tasks...

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by mrteddi** [comment]
Sniping with Pokezz is currently not working. It has been fixed and merged (I believe) but not implemented in a release yet.

In the meantime set
"GetSniperInfoFromPokezz": false,

**Comment by parthroxx** [comment]
now it stops after pokestop

**Comment by parthroxx** [comment]
n

**Comment by jackdaripperman** [comment]
im still getting stopped after one pokestop?! any ideas?

**Comment by jackdaripperman** [comment]
Got it. Thanks for the help!
