### ISSUE TITLE
After update to 0.8.5 i find that when i visiting a pokestop, it just hang there like forever.

### ISSUE THREAD

**Issue by kayuanderson** [NECROBOTIO/NecroBot#4891]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by theloser** [comment]
> Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.

Obviously you did not. Shame on you.
Please close this issue.

**Comment by kayuanderson** [comment]
Sorry my bad, my issue have solved. ^_^
