### ISSUE TITLE
Error while battle in GYM

### ISSUE THREAD

**Issue by mie11** [NECROBOTIO/NecroBot#4892]
Hai there I got error msg while battle in the gym is it because Niantic found I'm spoofing GPS.
Much help is needed

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.

**Comment by TagorHP** [comment]
I think this is a softban issue, happened to me many times.
1. just close your bot, wait for about 5-10minutes, then 
2. run pogo in gadget.
3. check at pokestop, if you can spin and get items, then you can do battle without problem.
(you might have to spin many times, like 20spin or more before softban is over)

or, at step 
1, close the bot and change the lang,lat to your spoof location, 
2. then run the bot, there will be a softban messages coming
3. after softban over (items received at pokestop), close the bot.
4. run pogo at your gadget.
5. re-check by getting items from pokestop
6. go to battle

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
