### ISSUE TITLE
Bug 0.8.5

### ISSUE THREAD

**Issue by Leynix** [NECROBOTIO/NecroBot#4893]
Hi everyone ! 

When i'm using the bot i have this message again and again ... 
Can someone help me please ? 
![2016-08-11_035833](https://cloud.githubusercontent.com/assets/20960787/17576915/49f65bf4-5f78-11e6-8883-9d0a616d6818.png)

**Comment by djdookie** [comment]
Get new IP and delete device id from auth.config.

**Comment by theloser** [comment]
Softban.

This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by ABCLost** [comment]
djdookie what id we have to use then?

**Comment by TagorHP** [comment]
yes, I think this is softban issue.
close your pogo played in ur gadget.
close necrobot
delete the auth.json & config.json at config directory
start necrobot, follow the new setting (username/password)
it should working fine.

**Comment by Leynix** [comment]
Yes it worked !
You guys are the bests

**Comment by theloser** [comment]
If it works, please close this issue, thank you!

**Comment by SirMannyPants** [comment]
@Leynix how did you fix yours? I'm having the same problem

**Comment by Sanskritmp** [comment]
@SirMannyPants You might be IP Banned. Were you running 2 bots at the same time in a computer/laptop or were you running 2 accounts with different computer/laptop? If that's the case, then you just wait a few hours, not exactly sure how long it'll take but as people have said "Patience is a virtue".

**Comment by dan-k-memes** [comment]
I'm also having problems with this.  Gave me 3 straight soft bans and now will not do anything

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
