### ISSUE TITLE
"(INFO) Exception caught, writing LogBuffer"

### ISSUE THREAD

**Issue by FAndresCO** [NECROBOTIO/NecroBot#4894]
![error](https://cloud.githubusercontent.com/assets/20806975/17576961/26aa11c0-5f3e-11e6-8e9d-f1b09b58a4c9.PNG)

**Comment by theloser** [comment]
Thanks for ignoring the issue template and **not** providing any details.
We can't help you.

Please close this issue, thanks.

**Comment by FAndresCO** [comment]
Sorry XD
