### ISSUE TITLE
Pokemon farming

### ISSUE THREAD

**Issue by Hisako1** [NECROBOTIO/NecroBot#4896]
Hi, 

I was wondering how you can farm/snipe specific pokemon with Necrobot. I know some place that are nest for specific pokemon. Can you program necrobot to stay there and hunt them. If not what is the best way to farm Pikachu or Charmander as an example.

Thank you guys

**Comment by kurozani** [comment]
use snipping to that coordinat

**Comment by Hisako1** [comment]
Could you explain me how to do that please @kurozani  

Thank you

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
