### ISSUE TITLE
the bot was fine before thie release....

### ISSUE THREAD

**Issue by jawad90** [NECROBOTIO/NecroBot#4897]
after the last release the bot stays at pokestops again and keeps spamming softban again .... someone is really fucking screwing necrobot code instead of fixing other stuff (lucky eggs and evolution)

**Comment by theloser** [comment]
You ignored the issue template (which told you to **search** for similar issues befor creating a new one). Therefore I will ignore you and will not tell you that this issue has already been solved and you would have found the solution if you searched for it.

**Comment by nekochan23** [comment]
yes, it was very easy got softban the newest released. but still i really happy with egg incubator. soo, still thank you for your hard work, guys. keep it's up. i'm sure you will fix the bug.

**Comment by jawad90** [comment]
i know its because of that stupid IP function added in the last release so stop creating new accounts to just dislike the question instead of helping
