### ISSUE TITLE
stuck on first pokestop

### ISSUE THREAD

**Issue by kindral** [NECROBOTIO/NecroBot#4898]
my bot just stuck in first pokestop. and do nothing.
it never happen before

any one can help?

**Comment by sing1222** [comment]
Please use search function and close this issue.

**Comment by h3300420** [comment]
I have th same problem！

**Comment by robertwilianto** [comment]
I also have same problem, how to solve ?

**Comment by JonSuperKnife** [comment]
had same issue just reinstall

**Comment by mrteddi** [comment]
This has been reported many times, please look around before making the exact same complaint.

How to temporarily fix until next release:
Sniping with Pokezz is currently not working. It has been fixed and merged (I believe) but not implemented in a release yet.

In the meantime set
"GetSniperInfoFromPokezz": false,
