### ISSUE TITLE
Is this an issue? Transfer multiple same kind pokemon, candy only increase 1

### ISSUE THREAD

**Issue by ValorRed** [NECROBOTIO/NecroBot#4899]
![image](https://cloud.githubusercontent.com/assets/20829876/17577269/9f076cac-5f49-11e6-8a5a-a9b2c4d1bfb7.png)

**Comment by nfettinger** [comment]
Duplicate issue

**Comment by ValorRed** [comment]
Which one it is duplicating to? I tried to search "Transfer", not much clue which one.
