### ISSUE TITLE
Got this as report to 8.5, lots of fail snipe

### ISSUE THREAD

**Issue by ochirutenshi** [NECROBOTIO/NecroBot#4900]
Photo is being taken, cause of username.

**Comment by ochirutenshi** [comment]
![image](https://cloud.githubusercontent.com/assets/20918437/17577367/e371cb0a-5fa6-11e6-8da9-5ea8a653688f.png)

**Comment by ochirutenshi** [comment]
Now it stop and not doing anything
![image](https://cloud.githubusercontent.com/assets/20918437/17577445/0ae96836-5fa8-11e6-82d1-8ff19fd6946f.png)

**Comment by kurozani** [comment]
it simply means in that coordinate there is no pokemon to snipe

you put manual after all

CMIIW

**Comment by kurozani** [comment]
for the last screenshot, what is your snipe set up?

**Comment by fuckNIANTIC** [comment]
Blur out your username dude, u want to get banned?

**Comment by avatarium** [comment]
lots of fake coords, disable all online snipers and use latest version of PogoLocationFeeder, at least you won't get many fake coords

  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 30,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,

**Comment by kurozani** [comment]
can you give me link how to use pogofeeder?

**Comment by avatarium** [comment]
1st result on google, download cli version, run, change in necrobot:
"UseSnipeLocationServer": true,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
done

**Comment by wyvern19** [comment]
Need "SnipeAtPokestops": true....

**Comment by kurozani** [comment]
okay thanks

**Comment by kurozani** [comment]
I did that, but still it didn't snipe anything XD

should i use snipe at pokestop true or false??
avatarium use false, but wyvern said to turn it false :(
