### ISSUE TITLE
Problems with logging in.

### ISSUE THREAD

**Issue by ABCLost** [NECROBOTIO/NecroBot#4902]
![y](https://cloud.githubusercontent.com/assets/20955834/17577284/1b59d826-5f7c-11e6-90a4-6e243c227693.png)

**Comment by mie11** [comment]
Just copy your paste your old auth file in config foler.

**Comment by Rick058** [comment]
You probably used the wrong type of password due to 2-step authentication.
Give this a try and use the App password instead of your account password: https://support.google.com/mail/answer/185833?hl=en

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
