### ISSUE TITLE
black screen / Not working anymore

### ISSUE THREAD

**Issue by jazzu20** [NECROBOTIO/NecroBot#4905]
anyone of you guys experiencing the same?

**Comment by avatarium** [comment]
v0.8.5 works great with pogolocationfeeder, almost 10 hours runtime & no softban

**Comment by jazzu20** [comment]
whats pogolocationfeeder? where do i find it?

**Comment by avatarium** [comment]
1st result on google

**Comment by jazzu20** [comment]
kinda confusing to set it up.. should I run both? GUI + necrobot ?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
