### ISSUE TITLE
Softban after 5 minutes

### ISSUE THREAD

**Issue by gunzshit** [NECROBOTIO/NecroBot#4906]
Hey Guys , 

I was starting my BOT and after 2 mins i get a softban?
I dont know why , cause i started it for the first time today ..

**Comment by gunzshit** [comment]
anyone?

**Comment by avatarium** [comment]
this is stable for me and no softbans
  "WalkingSpeedInKilometerPerHour": 20.0,
  "DelayBetweenPlayerActions": 2000,
  "DelayBetweenPokemonCatch": 2000,
  "MinDelayBetweenSnipes": 10000,
  "MaxTravelDistanceInMeters": 1000,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
