### ISSUE TITLE
Is my security compromised? What is this?

### ISSUE THREAD

**Issue by Indomin0us** [NECROBOTIO/NecroBot#4907]
There's unusual information in my auth.json file. When I enter my account info, save and close the file, run the bot, and finally check the auth file again I see an android device which I do not own. Is my information getting leaked?? It's not the first time this happens as I've seen a sony phone in the file before. To add to that, I've had messages from google about unauthorized email logins and one of the phones that did connect to my email account a few hours ago was indeed an android device. Wtf. Please let me know what's going on.
![img_1354](https://cloud.githubusercontent.com/assets/20961504/17577716/15d03ce2-5f4f-11e6-96ca-ae78b6876e82.jpg)

**Comment by dan-k-memes** [comment]
This just shows the "fake" phone being used for the bot

**Comment by Indomin0us** [comment]
Are you sure? How do you know this?

**Comment by LeoRaid** [comment]
because that is the way it is, lol

**Comment by pogotrainer9** [comment]
If you're afraid of your account security, turn on 2-factor authentication, grab a App Password and insert it in the auth file.

**Comment by avatarium** [comment]
yes you always get an email from google when you login from unknown device, just go to google acc and enable that device or simply ignore that email

**Comment by dddbliss** [comment]
The recent update from Niantic requires us to send "phone" identification information. Your fine.

**Comment by Indomin0us** [comment]
Yeah tried to get an app password but that didn't work. Anyways, everything is clear now, my google warning was probs from me using vpn earlier and as for the android phone that logged in, it must have been the device used for the bot. Thank you all
