### ISSUE TITLE
Sniping and use of berries

### ISSUE THREAD

**Issue by overtuned** [NECROBOTIO/NecroBot#4909]
I'm sniping on the latest version of Necrobot and the PoGo Location feeder. I noticed that the bot does not follow the below configs:

"MaxBerriesToUsePerPokemon": 3

"UseBerriesMinCp": 1000,
 "UseBerriesMinIv": 90.0,
 "UseBerriesBelowCatchProbability": 0.2,
 "UseBerriesOperator": "or",

I'm constantly running out of berries in about >10mins because the bot would use more than 5 berries on a single pokemon that is below 1000 CP and IV90. The bot also uses berries on pokemons with catch probability above 20%. I'm surprised no one has ever brought this up.

Help appreciated. TIA :)

**Comment by GRINSPANKER13** [comment]
Check the chance value of the Pokemon you are catching.

`"UseBerriesBelowCatchProbability": 0.2,`

0.2 = 20% so anything 20% or lower will trigger a berry.
I'd suggest putting it to either 0.1 (10%) or 0.05 (5%).

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
