### ISSUE TITLE
what is this?sever is offline????

### ISSUE THREAD

**Issue by kimo75110** [NECROBOTIO/NecroBot#4913]
what's going on?
![1470885142933](https://cloud.githubusercontent.com/assets/20961806/17577846/f1dfac12-5fb4-11e6-9c72-35670644b43b.jpg)

**Comment by nalancer08** [comment]
Same issue =(

**Comment by zsinghua** [comment]
restart your modem/hub.

**Comment by Rick058** [comment]
Servers are unstable, just keep trying.

**Comment by Zilverwings** [comment]
it says here every time, it can`t see a pokestop... think server is down??

**Comment by Dokha** [comment]
Same...
Ok wait next update

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
