### ISSUE TITLE
The garbled when Dump Pokemon Stats

### ISSUE THREAD

**Issue by david082321** [NECROBOTIO/NecroBot#4914]
### Expected Behavior
i use DumpPokemonStats

### Actual Behavior
but i only get garbled
(i know the reason, see at "Other Information")

pic 1
https://www.dropbox.com/s/52twqgcz5o282p9/1.JPG?dl=0

### Your config.json
```
  "TranslationLanguageCode": "zh_tw",
  "DumpPokemonStats": true,
```

### Other Information
Version: 0.8.5
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): If the language choose   **"zh_tw",** then change the coding from **UTF-8** to **ANSI**.

pic 2
https://www.dropbox.com/s/etp8kuxc3q1zco9/2.png?dl=0

**Comment by nfettinger** [comment]
Duplicate issue
