### ISSUE TITLE
this not working anymore?

### ISSUE THREAD

**Issue by lFeeeeelipe** [NECROBOTIO/NecroBot#4916]
Or it may be a configuration error?
![sem titulo](https://cloud.githubusercontent.com/assets/20939628/17577939/b549e142-5f59-11e6-9068-41f3ca38d1b1.png)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
