### ISSUE TITLE
Invalid Proxy. I know it works but not with necrobot.

### ISSUE THREAD

**Issue by dimaino** [NECROBOTIO/NecroBot#4918]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. YES
2. Hasn't been answered.
3. I joined discord and no one answered it.

### Expected Behavior
Working proxy.

### Actual Behavior
![asdasdasd](https://cloud.githubusercontent.com/assets/8098826/17578062/9a42d63a-5f39-11e6-8cdf-af5c7be28ea6.PNG)

### Your config.json
Shouldn't be needed.

### Steps to Reproduce
Make"UseProxy": true, "UseProxyHost": "1xx.xxx.xx.xxx",  "UseProxyPort": "3xxx" and there is no Authentication. I'm using proxifier and set the proxy to the program.

My proxy host is set to the correct proxy and port of the proxy.

Also, when I made the proxy my default connection the bots would connect so its not the proxy host.

### Other Information
Windows Version: windows 10 64-bit
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
proxy settings

**Comment by can99** [comment]
same problem~
![image](https://cloud.githubusercontent.com/assets/20637900/17578228/8ae60c9e-5fb0-11e6-89e4-45d2f8d4522e.png)

**Comment by Rick058** [comment]
1) What kind of proxy is it? SOCKS4, SOCKS5, HTTP, HTTPS?
2) Is it correctly configured in auth.json?

**Comment by can99** [comment]
1. http. https works ok
2. yup

**Comment by dimaino** [comment]
1.) HTTPS for me
2.) Yes, also

It also worked a few updates before but I always get a google auth error on older versions.

**Comment by kronthto** [comment]
I'm trying to use a SOCKS5 proxy with host "127.0.0.1" and port "1081" and also get *INVALID_PROXY*. Would appreciate if a solution gets found here :smile:

**Comment by DarkSkull91** [comment]
It doesn't work with any proxy.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
