### ISSUE TITLE
No useable pokestops

### ISSUE THREAD

**Issue by ExReservoir** [NECROBOTIO/NecroBot#4919]
I put coordinates at bottom right of central park, yet it keeps saying no useable pokestops, it's also MaxTravelDistanceInMeters": 100000000, all jsons are valid btw

**Comment by deblackfisk** [comment]
so do i here..

**Comment by vesper86** [comment]
1 bot per 1 IP or 1 modem
MaxTravelDistanceInMeters": 100000000, << 100000 KM

restart your modem 1st

**Comment by ExReservoir** [comment]
oh whoops i used 2 necrobots

**Comment by ExReservoir** [comment]
https://gyazo.com/47486fda09f2bc649b1df5e0f7efb366

**Comment by brightjoyy** [comment]
yes @vesper86 it can work only for1 modem right or one computer for 1 bot ?

**Comment by jesussson** [comment]
Will try the same

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
