### ISSUE TITLE
would maxtraveldistance matter?

### ISSUE THREAD

**Issue by whydareme** [NECROBOTIO/NecroBot#4920]
just a question in view of the more aggressive soft bans for the last two days.

would a maxtraveldistance of say 20km draw undue attention from the server algorithms? this is while keeping walking speed reasonable at 5km per hour. thanks!

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
