### ISSUE TITLE
request auto changed ip

### ISSUE THREAD

**Issue by jeremycons21** [NECROBOTIO/NecroBot#4922]
request for auto changed ip, for bypass softban

**Comment by Oolaruu** [comment]
Can you explain a little more ? and use the request format ?

**Comment by tatejensen6** [comment]
Can someone tell me how to change my "movement speed" in the config

**Comment by tatejensen6** [comment]
like where it is

**Comment by jarpoks** [comment]
"WalkingSpeedInKilometerPerHour": 31.0,

**Comment by huthutblur1** [comment]
@tatejensen6 remember this
"DisableHumanWalking": false,
"WalkingSpeedInKilometerPerHour": 250.0,

**Comment by Oolaruu** [comment]
Why "DisableHumanWalking" is not set as false to prevent future issues?

**Comment by jeremycons21** [comment]
I use the bot, but every 2 or 3 min I get softban, but when I change my ip, I bypass the softban

**Comment by tatejensen6** [comment]
does increasing the "WalkingSpeedInKilometerPerHour" increase your chance of getting soft banned?

**Comment by mystogenz** [comment]
@huthutblur1 Walking seed 250 ??

**Comment by huthutblur1** [comment]
if two point not too far , will not get softban ,because humanwalk need speed-up 0 to 250 .

**Comment by mystogenz** [comment]
@huthutblur1 Do you know everytime when i open the bot, it will pop out the red ip address. isit will detect when we bot some where else ?

**Comment by huthutblur1** [comment]
@mystogenz can be trace to check your account gps and ip(place) to know is that fake gps or not .
but do not across too far country is not a problem , i used japan vpn last night got softban after 1x min bot running , while i set at other country QAQ

**Comment by rizalblue** [comment]
U can't change Public IP. Use proxy server

**Comment by mystogenz** [comment]
Can show me how to use it?

**Comment by mystogenz** [comment]
@huthutblur1 How many bot can be opened ?

**Comment by Oolaruu** [comment]
How many do you want ?

**Comment by mystogenz** [comment]
@Oolaruu Because just now i opened 2 its fine but i try to open another one  bot, havent 5 mins all my 3 bots soft banned.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
