### ISSUE TITLE
IP softban?

### ISSUE THREAD

**Issue by Indomin0us** [NECROBOTIO/NecroBot#4923]

**Comment by pixerx** [comment]
Restart your phone and find proper GPS location.
Wait 15min after restart.

**Comment by Olister** [comment]
Whats going on is You prob got more then 1 Bot from your WIFI at home running and they changed it so only 1 Can run Per IP now. You might have it logged in your phone or something also if you're not running 2 bots or more

**Comment by TomPK** [comment]
download hotspot (vpn change) and be happy.

**Comment by Indomin0us** [comment]
yeah Ive done that
