### ISSUE TITLE
snipe at pokestop

### ISSUE THREAD

**Issue by makhao** [NECROBOTIO/NecroBot#4931]
snipeatpokestop = true

hang the whole bot? false the bot will run as per normal.. what is wrong?
am using latest version of both necrobot and pogolocationfeeder

any advise?

**Comment by jumpcom** [comment]
snapshot or log please

**Comment by makhao** [comment]
[NecroBot-2016-08-11-11.txt](https://github.com/NECROBOTIO/NecroBot/files/412528/NecroBot-2016-08-11-11.txt)

**Comment by makhao** [comment]
[NecroBot-2016-08-11-12.txt](https://github.com/NECROBOTIO/NecroBot/files/412530/NecroBot-2016-08-11-12.txt)

**Comment by makhao** [comment]
11-11 the log which hang
11-12 the one which i  put snipeatpokestop false

**Comment by Lordseis03** [comment]
Any fix to this issue?

**Comment by makhao** [comment]
The bot is running perfectly as long my snipeatpokestop is false. Otherwise
it will hang at pokestop.

**Comment by Lordseis03** [comment]
So sniping is disabled at the moment?

**Comment by Darkgroom** [comment]
Sniping works for me at this moment, try it again (only pokezz is currently not working)

**Comment by makhao** [comment]
Ok. Tested still working for the snipping. Just need to change infofrompokezz to false can continue to snipe. Thanks
