### ISSUE TITLE
Pokemon Storage Confusion 

### ISSUE THREAD

**Issue by ProfKush** [NECROBOTIO/NecroBot#4932]
Theres a small not so harmful issue were when your sniping and run out of pokemon space it would say "blah blah Pokemon Disappeared?" (same message when the snipe was fake or soft banned) and I had 0 way of finding out because there was no way to check my pokemon storage so I never knew what the issue was until I messed around.

Maybe the message can't be fixed but maybe add a warning or on the top add it where it shows how much pokemon storage you have and how much is taken out and maybe also add a console warning like (Warning) You have 10 spaces left for pokemon, & (Warning) You have run out of space for pokemon!

**Comment by nfettinger** [comment]
Duplicate
