### ISSUE TITLE
cant catch pokemon

### ISSUE THREAD

**Issue by dogzrule6** [NECROBOTIO/NecroBot#4934]
after using necrobot when am not using it i cant catch pokemon every time i throw a pokeball it rocks twice then on the third rock it pops out and runs ive already tried restarting my phone and reinstalling pokemon go please help me

**Comment by sukhmypreet** [comment]
softban.

**Comment by dogzrule6** [comment]
what does that mean

**Comment by dogzrule6** [comment]
how do i fix it pls help

**Comment by szewing627** [comment]
you can try to spin the pokeshop first, if you can get anything from pokeshop it means not softban if cannot. means ahaha softban.

**Comment by dogzrule6** [comment]
what pokeshop

**Comment by szewing627** [comment]
where you can get the refill pokeball etc.

**Comment by dogzrule6** [comment]
what try to use diffrent words i dont get what your saying do you mean pokestop

**Comment by rizalblue** [comment]
Use proxy server.

**Comment by dogzrule6** [comment]
where do i do that

**Comment by szewing627** [comment]
if sued phone go out side travel around you can see the pokeshop

**Comment by dogzrule6** [comment]
you make no sence

**Comment by szewing627** [comment]
if used bot that will be auto unban itself.

**Comment by Joloxx9** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
 Please use the Discord channels to get help with your questions.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
