### ISSUE TITLE
bot start sniping without checking "MinPokeballsToSnipe"?

### ISSUE THREAD

**Issue by Seyrenvox** [NECROBOTIO/NecroBot#4936]
### Expected Behavior
check `MinPokeballsToSnipe`.
if `MinPokeballsToSnipe` >= minimum value, then execute snipe

### Actual Behavior
sniping, then return error caused by `MinPokeballsToSnipe` < minimum value.

### Your config.json
i only show my config related to this problem
```
"UseSnipeLocationServer": false,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"GetSniperInfoFromPokezz": false,
"GetOnlyVerifiedSniperInfoFromPokezz": false,
"GetSniperInfoFromPokeSnipers": true,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": false,
"MinPokeballsToSnipe": 5,
"MinPokeballsWhileSnipe": 0,
"MinDelayBetweenSnipes": 35000,
"SnipingScanOffset": 0.003,
"SnipeAtPokestops": true,
"SnipeIgnoreUnknownIv": true,
"UseTransferIvForSnipe": false,
"SnipePokemonNotInPokedex": false,
```

### Other Information
Version: 0.8.5 (latest)
Windows Version: 10
What is affected: this unusual flow leads to softban, i believe

this is a chunk of my log

> [09:15:29] No Pokeballs - We missed a Dragonite with CP 1925
> **[09:15:30] (PokeSnipers.com) Sniping a Chansey** with 94 IV at 33.4009168499828,-111.847962155927...
> **[09:15:30] Not enough Pokeballs to start sniping! (0/1)**
> [09:15:31] Traveling to Pokestop: Clock in the Strand Arcade (74m) (42 seconds)
> [09:15:32] Looking for Pokemon...
> [09:15:37] Looking for incense Pokemon...

as you can see above, it sniping first, and returning an error saying that "we can't do sniping!"
and after that, i got softban.
i assume, when the bot start sniping in that coordinat, and realize that the pokeballs doesn't met minimum requirement, the bot start walking without savely teleporting back to last position. leads to softban.
.
.
.
(additional bug, maybe.
these two lines loop for an hour and i got softbanned:

> **[09:15:32] Looking for Pokemon...
> [09:15:37] Looking for incense Pokemon...**

what is _looking for Pokemon_ actually? i thought the bot is walking from pokestop to another, and catch whatever Pokemon shows up.)

**Comment by nfettinger** [comment]
Inventory might be reporting 0 balls because you are banned.

**Comment by Seyrenvox** [comment]
oh, man... I really don't like it if you just close the issue without hearing, or reading the feedback after you respond. 

yes, I'm softbanned. but after the bot trying to snipe. NOT before it. 
my pokeballs really empty that time
