### ISSUE TITLE
Cant find pokestop ?

### ISSUE THREAD

**Issue by vphuong** [NECROBOTIO/NecroBot#4937]
I tried to download the newest version of Necrobot but I still got the same issue. I copied a config file from my friend computer, (he still using necrobot normally) but the same issue. Please help
[NecroBot-2016-08-11-11.txt](https://github.com/NECROBOTIO/NecroBot/files/412546/NecroBot-2016-08-11-11.txt)

**Comment by hasbiputro** [comment]
same problem here

**Comment by szewing627** [comment]
ip ban. reset router or change ip

**Comment by VasTShadowZ** [comment]
Use VPN when it happends

**Comment by Joloxx9** [comment]
Mate I don't want to be rude, but here we should write issues with bot, not question how to run it etc.

Bot is working fine, if you have that kind of message that mean you have been banned, multi bot/ wrong config.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
