### ISSUE TITLE
till now my bot cant Work , stil searching pokestop

### ISSUE THREAD

**Issue by handy9996** [NECROBOTIO/NecroBot#4938]
help me please put a tips

**Comment by jesussson** [comment]
i got the same issue

**Comment by LeonardRz** [comment]
same on me -_-'

**Comment by ubulem** [comment]
What kind of error do you get? Maybe it's IP ban?

**Comment by LeonardRz** [comment]
acctually my bot was stuck.. doing nothing.. they say because of snipe.. idk what to change at my config..

**Comment by joeskyfrog** [comment]
try with this.. change the settings in config.json :
"UseSnipeLocationServer": false,
"GetSniperInfoFromPokezz": false,
"GetOnlyVerifiedSniperInfoFromPokezz": false,
"GetSniperInfoFromPokeSnipers": false,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": false,

**Comment by LeonardRz** [comment]
alright.. thanks for ur help..

**Comment by potato16** [comment]
what's happen with snipe?

**Comment by Joloxx9** [comment]
Mate I don't want to be rude, but here we should write issues with bot, not question how to run it etc.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
