### ISSUE TITLE
What happen here? Please advise. Necrobot not working

### ISSUE THREAD

**Issue by ochirutenshi** [NECROBOTIO/NecroBot#4939]
![image](https://cloud.githubusercontent.com/assets/20918437/17579074/3b0caed4-5fbb-11e6-9926-fc631768358d.png)

**Comment by ubulem** [comment]
Correct spelling of pokemon name is "shellder" with two "l". 
It seems bot can't parse and throws exception.

**Comment by 10w042** [comment]
Read the error, you have a misspelled pokemon name, should be "Shellder" at line 209 of your config, under PokemonsToEvolve.

**Comment by ochirutenshi** [comment]
oo darn thanks you two bro, hahaha stupid shoot mistake.
Closing the issue with thanks, now i know where to read. Panic thought of getting banned.
