### ISSUE TITLE
2 step verification is off but bot still thinks it's on

### ISSUE THREAD

**Issue by Indomin0us** [NECROBOTIO/NecroBot#4940]
![img_1356](https://cloud.githubusercontent.com/assets/20961504/17579092/5edbd54e-5f5f-11e6-938a-3afa6902d991.jpg)
Title says it all. How do I fix this?

**Comment by jesussson** [comment]
by fixing the .json

**Comment by Indomin0us** [comment]
Is it in the auth or config? And where is it?

**Comment by jesussson** [comment]
auth make sure you change to correct format as such
  "AuthType": "google",
  "GoogleUsername": "your user name here",
  "GooglePassword": "your password here",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by jesussson** [comment]
if you get lost just drag and drop the default file then config also make sure you don't delete the " or the ,

**Comment by Indomin0us** [comment]
The code was correct and it still had the issue

**Comment by Indomin0us** [comment]
I even tried redownloading the whole file. I also am 100% sure that the 2 step is off

**Comment by Indomin0us** [comment]
It works now. Just had to delete the fake phone info

**Comment by jesussson** [comment]
so when you login to google in your browser it's not asking foe 2-step at all???

**Comment by jesussson** [comment]
oh ok good job..
