### ISSUE TITLE
Always same error 

### ISSUE THREAD

**Issue by omear** [NECROBOTIO/NecroBot#4941]
iam always getting this error since 0.7 and now 0.8.5
![gotthis](https://cloud.githubusercontent.com/assets/5305155/17579103/2dd78a98-5f9a-11e6-8062-a1ff24f785d8.PNG)

MY CONFIG FILE 

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": true,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 5,
  "DetailedCountsBeforeRecycling": false,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 22.2994629,
  "DefaultLongitude": 114.1723075,
  "WalkingSpeedInKilometerPerHour": 150.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 1,
  "DelayBetweenPokemonCatch": 1,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": true,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 50,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 1.0,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": false,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 8,
  "MaxTravelDistanceInMeters": 3050,
  "TotalAmountOfPokeballsToKeep": 150,
  "TotalAmountOfPotionsToKeep": 100,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 15,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.1,
  "UseUltraBallBelowCatchProbability": 0.05,
  "UseMasterBallBelowCatchProbability": 0.02,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemPotion",
      "Value": 0
    },
    {
      "Key": "itemSuperPotion",
      "Value": 0
    },
    {
      "Key": "itemHyperPotion",
      "Value": 25
    },
    {
      "Key": "itemMaxPotion",
      "Value": 120
    },
    {
      "Key": "itemPokeBall",
      "Value": 150
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemUltraBall",
      "Value": 200
    },
    {
      "Key": "itemMasterBall",
      "Value": 999
    },
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Mewtwo": {
      "KeepMinCp": 2500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2900,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 2400,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Arcanine": {
      "KeepMinCp": 2500,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Chansey": {
      "KeepMinCp": 600,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 99.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1200,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Poliwag": {
      "KeepMinCp": 620,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      },
      {
        "Latitude": 34.022956,
        "Longitude": -118.472995
      }
    ],
    "Pokemon": [
      "abra",
      "kadabra",
      "alakazam",
      "aerodactyl",
      "articuno",
      "bellsprout",
      "weepinbell",
      "victreebel",
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "caterpie",
      "metapod",
      "butterfree",
      "chansey",
      "charmander",
      "charmeleon",
      "charizard",
      "clefairy",
      "clefable",
      "cubone",
      "marowak",
      "diglett",
      "dugtrio",
      "ditto",
      "doduo",
      "dodrio",
      "dratini",
      "dragonair",
      "dragonite",
      "drowzee",
      "hypno",
      "electabuzz",
      "ekans",
      "arbok",
      "eevee",
      "vaporeon",
      "jolteon",
      "flareon",
      "exeggcute",
      "exeggutor",
      "farfetchd",
      "gastly",
      "haunter",
      "gengar",
      "geodude",
      "graveler",
      "golem",
      "goldeen",
      "seaking",
      "grimer",
      "muk",
      "growlithe",
      "arcanine",
      "hitmonlee",
      "hitmonchan",
      "horsea",
      "seadra",
      "jigglypuff",
      "wigglytuff",
      "jynx",
      "kabuto",
      "kabutops",
      "kangaskhan",
      "koffing",
      "weezing",
      "krabby",
      "kingler",
      "lapras",
      "lickitung",
      "machop",
      "machoke",
      "machamp",
      "magikarp",
      "gyarados",
      "magmar",
      "magnemite",
      "magneton",
      "mankey",
      "primeape",
      "meowth",
      "persian",
      "mew",
      "mewtwo",
      "mrMime",
      "moltres",
      "nidoranMale",
      "nidorino",
      "nidoking",
      "nidoranFemale",
      "nidorina",
      "nidoqueen",
      "oddish",
      "gloom",
      "vileplume",
      "omanyte",
      "omastar",
      "onix",
      "paras",
      "parasect",
      "pidgey",
      "pidgeotto",
      "pidgeot",
      "pinsir",
      "pikachu",
      "raichu",
      "poliwag",
      "poliwhirl",
      "poliwrath",
      "ponyta",
      "rapidash",
      "porygon",
      "psyduck",
      "golduck",
      "rattata",
      "raticate",
      "rhyhorn",
      "rhydon",
      "sandshrew",
      "sandslash",
      "seel",
      "dewgong",
      "shellder",
      "cloyster",
      "scyther",
      "slowpoke",
      "slowbro",
      "snorlax",
      "spearow",
      "fearow",
      "staryu",
      "starmie",
      "squirtle",
      "wartortle",
      "blastoise",
      "tangela",
      "tauros",
      "tentacool",
      "tentacruel",
      "venonat",
      "venomoth",
      "voltorb",
      "electrode",
      "vulpix",
      "ninetales",
      "weedle",
      "kakuna",
      "beedrill",
      "zapdos",
      "zubat",
      "golbat"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by Joloxx9** [comment]
This does not ssem to be a development issue or a bug. 
 Please use the Discord channels to get help with your questions.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
