### ISSUE TITLE
No useable pokestops found in your area

### ISSUE THREAD

**Issue by sammyloy** [NECROBOTIO/NecroBot#4946]
### Expected Behavior
Visting to pokestop rapidly

### Actual Behavior
No usable PokeStops found in your area. Is your maximum distance too small?

help help!

**Comment by mihoarang** [comment]
Same issue, need some help regarding with this issue. Anyone?

**Comment by szewing627** [comment]
ip ban. reset router or change ip address

**Comment by mrbosor20** [comment]
hi.. i will help you with my config

**Comment by mihoarang** [comment]
how to change my ip ad?

**Comment by sammyloy** [comment]
@mrbosor20 would you pls show me ur config?

**Comment by mihoarang** [comment]
Can you just me send your config file then i will delete mine then paste
your config? What do you think?

**Comment by mrbosor20** [comment]
@mihoarang @sammyloy 
1. download hotspotshield
2. on of if you got baned
3. change this for config 
"WalkingSpeedInKilometerPerHour": 250.0,
 "FastSoftBanBypass": true,
 "UseSnipeLocationServer": false, (eror for sniping, i dont know with other)
4. keep safe only 1 bot for open

**Comment by sammyloy** [comment]
im trying to change my version right nw, the new version has stupid ip address shit. perhaps is the issue i will update you guys!

**Comment by sammyloy** [comment]
nope no changes

**Comment by mihoarang** [comment]
still no usable pokestop

**Comment by sammyloy** [comment]
no fucking idea, haha, its working properly now, i didnt do anything. just reset'ed my router

**Comment by mrbosor20** [comment]
nice

**Comment by szewing627** [comment]
ip ban. reset router or change ip address i said that before.

**Comment by sammyloy** [comment]
fak haha the ip got banned again i guess

**Comment by sammyloy** [comment]
anyone has a good config for pokeballs and pokestop sniping only? no pokemons

**Comment by g00tch** [comment]
When it spams that "No usable PokeStops", I just stop and restart the bot.

**Comment by mrbosor20** [comment]
im fine 1 hour running

**Comment by mihoarang** [comment]
I did reset my modem, and yeah it work perfectly fine right now.

**Comment by mihoarang** [comment]
Thanks mrbosor20!

**Comment by Joloxx9** [comment]
Mate I don't want to be rude, but here we should write issues with bot, not question how to run it etc.

Bot is working fine, if you have that kind of message that mean you have been banned, multi bot/ wrong config.

**Comment by sammyloy** [comment]
fixed  "UseProxy": true,
  "UseProxyHost": "165.138.66.247",
  "UseProxyPort": "8080",
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by geeks121** [comment]
hi my ip is banned ,,, so i install ssh on pc ,,, there other way to run?

**Comment by Joloxx9** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
 Please use the Discord channels to get help with your questions.
 If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
