### ISSUE TITLE
Rename only non-favorite pokemon?

### ISSUE THREAD

**Issue by NPP000** [NECROBOTIO/NecroBot#4949]
Rename only non-favorite pokemon?

**Comment by theloser** [comment]
Already a feature. Use
>  "RenamePokemon": true,
>  "RenameOnlyAboveIv": false,

Favorited pokemon will **not** be renamed.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
