### ISSUE TITLE
How Many Bots Can I Run On 1 Computer?

### ISSUE THREAD

**Issue by VasTShadowZ** [NECROBOTIO/NecroBot#4950]
Just Wondering? With All Other Bots They Keep Getting IP Banned

**Comment by Oolaruu** [comment]
1 only

**Comment by VasTShadowZ** [comment]
@Oolaruu Thanks

**Comment by potato16** [comment]
atm i running 2 bots and its still working

**Comment by chohitoshiri** [comment]
One suggest.....more than two....will be ban IP soon....

**Comment by Joloxx9** [comment]
Mate I don't want to be rude, but here we should write issues with bot, not question how to run it etc.

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
