### ISSUE TITLE
Looking for incense Pokemon...

### ISSUE THREAD

**Issue by spamfighter82** [NECROBOTIO/NecroBot#4951]
according to the logs:

> [04:45:59] Looking for Pokemon...
> [04:45:59] Looking for incense Pokemon...
> [04:46:00] Looking for Pokemon...
> [04:46:01] Looking for incense Pokemon...

is the bot really checking every second for pkmn and incence even you can only get get new map data every 10 sec and i'm not using incense at all. we keep getting softbanned for running more than 1 bot on 1 ip, yet you can run 1 bot and multiple pogp map workers without issues so it cant be the number of connections alone and this seems to me like a ton of requests that are totally unnecessary,

**Comment by szewing627** [comment]
try close problem and reset router.

**Comment by spamfighter82** [comment]
i'm not softbanned, im asking if would be worth if we 
a) dont check for incense pkmn when we dont use insence
b) get an option to only scan for pkmn every 10 sec
c) specially when sniping, if you ever did it by hand, you will know that you have to wait for a map refresh after teleporting.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
