### ISSUE TITLE
working on windows 7?

### ISSUE THREAD

**Issue by ShingShangFu666** [NECROBOTIO/NecroBot#4955]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Oolaruu** [comment]
Do you have Windows 7 ?
If yes, go ahead to run latest release.zip
and give us feedback :)

**Comment by ShingShangFu666** [comment]
my NET framework initialization error :(

**Comment by spamfighter82** [comment]
it does run

**Comment by ShingShangFu666** [comment]
why?

**Comment by spamfighter82** [comment]
i guess i installed the net framework properly? just head to microsoft and install that shit

**Comment by ShingShangFu666** [comment]
what net framework you used?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by chohitoshiri** [comment]
You need to installed .netframework 4.6.2, the 0.8.6 not compatible with 4.5.2
