### ISSUE TITLE
Doesn't keep Pokemon?!

### ISSUE THREAD

**Issue by KuroTheBang** [NECROBOTIO/NecroBot#4956]
Somehow in the previous Revisions it kept every Pokemon at least one or two, even if it didn't meet the requirements (MinCP, MinIV). Now it somehow doesn't :O

**Comment by feroniameimei** [comment]
"KeepMinDuplicatePokemon": 1,

**Comment by RayKoopa** [comment]
Had a similar issue #4953 and were wondering too.

**Comment by KuroTheBang** [comment]
Yea, found it. It wasn't that, It was   "TransferWeakPokemon": somehow set to true, whyever. Thank you anyway guys!

**Comment by RayKoopa** [comment]
Don't forget to close when it's solved

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
