### ISSUE TITLE
Bot doesn't find all pokemons in my inventory.

### ISSUE THREAD

**Issue by Lillecarl** [NECROBOTIO/NecroBot#4957]
### Expected Behavior
(await session.Inventory.GetPokemons()).ToList().Count should return amount of pokemon i have in my inventory.

### Actual Behavior
(await session.Inventory.GetPokemons()).ToList().Count returns some obscure number (90 as i'm testing atm) when in the pogo app it says 250.

### Your config.json
https://gist.github.com/Lillecarl/9a0418aec802922cd16b6bb6902dcaf4

### Steps to Reproduce
Print (await session.Inventory.GetPokemons()).ToList().Count to console

### Other Information
Version: 0.8.5
Windows Version: W10 x64 PRo
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
transfer, evolve, powerup

**Comment by ppa993** [comment]
I have the same problem

**Comment by theloser** [comment]
You are not mixing the number of pokemons you actually have in your inventory (can be 0-250 if you didn't buy any inventory expansions) with number of pokemons you **can** have in your inventory (whhich is 250 if you didn't buy any inventory expansions), right?

If you dump your pokemondata with the bot (use DumpPokemonStats), how many bots do you have in your inventory?

**Comment by Lillecarl** [comment]
@theloser When this is true (in either of the catch tasks)
if (encounter.Result == IncenseEncounterResponse.Types.Result.PokemonInventoryFull)

I call this:
await TransferWeakRelativePokemonTask.Execute(session, cancellationToken);

Which is my own task that i made, which looks like this:
https://gist.github.com/Lillecarl/702de38037a138cc9a88a3e9d492cc59

And the count is never 250 (see line 48 where i print it), even though my inventory cap is 250, which makes it very hard for this to function properly.

Thanks for the reply though, but this issue is quite breaking the bots original functions too! :/

**Comment by Lillecarl** [comment]
@theloser http://i.imgur.com/7IIMvsy.png <- Here's my task in action, so you can see the code and compare the result :)

**Comment by actislav** [comment]
i think its related to https://github.com/NECROBOTIO/NecroBot/pull/4954

**Comment by Lillecarl** [comment]
@actislav I tried manually refreshing in my task now, got this response:
http://i.imgur.com/hDlAdG0.png

138 of 250 pokemons found, wiee.....

**Comment by alexmanea2000** [comment]
Lillecarl, you solved it?

**Comment by Lillecarl** [comment]
@alexmanea2000 No it's still broken, someone who's more familiar with the RocketAPI will need to look at this.

**Comment by theloser** [comment]
@Lillecarl I still don't get what you are trying to tell us, sorry.

So, apparently session.Inventory.GetPokemons()).ToList().Count returns a wrong number, right?
You coded your own task where you counted all pokemon with ++count, correct?

Now, is there a difference between your number and session.Inventory.GetPokemons()).ToList().Count, and how many pokemon you actually have?

**Comment by Lillecarl** [comment]
@theloser no, i checked this too.

The fact that i made my own task should not really be the issue here, it should be the fact that we don't get all the pokemons that's in the inventory at the time. Which breaks all logic related to the inventory really, if some are missing and we can't calculate on them.

If you read the code through you will see that there's no abnormal usage whatsoever of the getpokemon, and there's a foreach loop that increases the counter (could use .count and did first, but i tested this as well and didn't revert).

Each time my task fires i have 250 pokemons, because it only fires once i get inventoryfull error from a pokemon encounter.

Note: The pokemon count that i get from the getpokemon function is not the same at all times.

**Comment by nfettinger** [comment]
Duplicate issue. It counts your eggs and pokemon together.

**Comment by Lillecarl** [comment]
@nfettinger if it counts my eggs and my pokemons together, how come the value sometimes is less then 100 when i have 250 pokemons in my inventory when looking in the app?

And could you refer to the duplicate?

Thanks
