### ISSUE TITLE
[0.8.5]  log "C:\Users\ciamo\Source\" ???

### ISSUE THREAD

**Issue by dariodotsid** [NECROBOTIO/NecroBot#4959]
Hi,
in log file i find:
<<at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:>>

**ciamo???**

**Comment by Profetorum** [comment]
i notice it too

**Comment by AndikaTanpaH** [comment]
Yes i got this one to,
its developer user? or just typo on code

**Comment by dariodotsid** [comment]
can you give us some info about CIAMO user?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
