### ISSUE TITLE
Is it possible for two computers to run two necrobot connected to only one router?

### ISSUE THREAD

**Issue by ivannavea** [NECROBOTIO/NecroBot#4962]
After like 5 or 10 mins i get ip banned and had to restart router again even though i use two different computers running two bots. Thanks for the reply

**Comment by Joloxx9** [comment]
Mate I don't want to be rude, but here we should write issues with bot, not question how to run it etc.

**Comment by ruchern** [comment]
Two computer share 1 WAN IP over the router.

**Comment by sambora91** [comment]
1wan ip only 1 account

**Comment by ivannavea** [comment]
is there a possibility to let them work together without having the ip banned issue

**Comment by fence1247** [comment]
You could add a unique IP VPN to one computer, such as the one torguard can provide.

**Comment by ivannavea** [comment]
thanks for the reply mate i will try to find a proper IP changer software @fence1247

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
