### ISSUE TITLE
Bot is not searching!

### ISSUE THREAD

**Issue by Korni1987** [NECROBOTIO/NecroBot#4966]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Korni1987** [comment]
http://imgur.com/a/72x6o

**Comment by dariodotsid** [comment]
me too:
"[08:38:00] No usable PokeStops found in your area. Is your maximum distance too small?"
i try 2 account in 2 differente country

**Version**:
Windows Version:
What is affected PokeStops

**Comment by theloser** [comment]
@Korni1987 Thanks for **not** filling out the issue template. Giving us **no** information at all. Therefore I just have to say this:

This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use our [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by Korni1987** [comment]
yes after change location it works. one bot per ip?

**Comment by theloser** [comment]
Please use our Discord channels to get help with your questions.

**Comment by sammyloy** [comment]
dude, add into ur config        
  "UseProxy": true,
  "UseProxyHost": "165.138.66.247",
  "UseProxyPort": "8080",
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by theloser** [comment]
@sammyloy You are **not** helping (instead, your proxy ip will be blocked/blacklisted in no time).

**Comment by Korni1987** [comment]
loser stupid?why you blacklist his proxy?

**Comment by theloser** [comment]
@Korni1987 Yes, I have blacklisted this IP, and I will blacklist **any** IP you will ever use. In fact, I am just blacklisting every IP! :facepunch:

**Comment by Korni1987** [comment]
biggest idiot

**Comment by theloser** [comment]
@Korni1987 Thanks for not filling out the issue template. Giving us no information at all. Please close this issue, and thanks for using the issue tracker.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
