### ISSUE TITLE
[Feature Request] Collect Coins/Stardust from Gym (not a duplicate!)

### ISSUE THREAD

**Issue by Sasstraliss** [NECROBOTIO/NecroBot#4968]
**This is NOT a duplicate, because the prior issues on this were closed with NO RESPONSE.**

Would be nice if the bot auto-collected rewards from the shop for holding gyms.

**Comment by ruchern** [comment]
We do not have gym functions at the moment.

**Comment by blue1Elephant** [comment]
Therefore it's a Feature Request.

And if they implement gym functions, why not place a Pokemon in a gym when there is a gym of your own fraction with a free slot?

**Comment by nfettinger** [comment]
The RocketAPI     MUST     be updated to include this functionality before we could even think of adding it here.
