### ISSUE TITLE
always Ip ban after few minutes

### ISSUE THREAD

**Issue by devilangelsoul** [NECROBOTIO/NecroBot#4971]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
  "TranslationLanguageCode": "it",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 10,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": false,
  "UseLevelUpList": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 41.890042,
  "DefaultLongitude": 12.49664,
  "WalkingSpeedInKilometerPerHour": 10.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 2,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 5,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 700,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.35,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 30,
  "MaxTravelDistanceInMeters": 10000,
  "TotalAmountOfPokeballsToKeep": 180,
  "TotalAmountOfPotionsToKeep": 70,
  "TotalAmountOfRevivesToKeep": 50,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 850,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 15000,
  "UseGreatBallAboveIv": 10000.0,
  "UseUltraBallAboveIv": 10000.0,
  "UseGreatBallBelowCatchProbability": 0.25,
  "UseUltraBallBelowCatchProbability": 0.15,
  "UseMasterBallBelowCatchProbability": 0.005,
  "EnableHumanizedThrows": true,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 20,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 800,
  "ForceExcellentThrowOverCp": 900,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
```

### Other Information
Version: 0.8.5
Windows Version: 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
hi I run only 1 bot, but after few minutes i get always ip ban.
I obverve that if I run an older version,type 0.7.6, it work fine and don't give me an ipban....why???

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
If it turns out to be a real bug, please come back and file an issue -- Thanks!

**Comment by sammyloy** [comment]
add  "UseProxy": true,
  "UseProxyHost": "165.138.66.247",
  "UseProxyPort": "8080",
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by sammyloy** [comment]
i had problem just now, ur ip is banned, dont try reset router blah blah blah. just  "UseProxy": true,
  "UseProxyHost": "165.138.66.247",
  "UseProxyPort": "8080",
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by theloser** [comment]
> fuck after few minutes that ip got banned again

What did you expect what would happen if multiple user use the same proxy server?

**Comment by sammyloy** [comment]
http://proxylist.hidemyass.com/

**Comment by geeks121** [comment]
hi,, i my ip is banned ,, i tryng it on rdp ,,, and ip is banned ,,, so i try installing bitvise n proxyfire ,,, all done i can login and bot it again,,, you can try this trick,,, but my bot stoped walking ,, after 1 pokestop visited... thankyou and sory for bad english :)

**Comment by Caterpee** [comment]
I've experienced the same problem. When I'm running the bot at home I have a lot of soft ban trouble right after 5 mins of usage but when I'm running the bot from company network there seems to be no problem at all. Company uses static IP while at home I've got common dynamic IP from my provider (no VPN, no proxy). There is nobody else using my network at home (according to DHCP table) and I'm only running a single bot with very moderate settings using my google account.

I've tested with a copy of my NecroBot 0.8.5 folder, so I'm using exact same settings on both sites. Also operating system is the same on both sites (Win 7 Pro SP1, x64). In both network my mobile is connected via wifi as well but I'm not running both Pokemon Go app and NecroBot at the same time.

I can't explain that behaviour... Even if I change my IP at home by restarting the router I'm again getting soft banned in less than 5min. I've not tested with any previous version of Necrobot at home yet to verify your experience with less problems when using 0.7.X version though.

**Comment by isolah123** [comment]
basically if im using static IP i got banned in 5-10 min botting, but if im using ip/vpn changer the bot works atleast gmail account need to authentication password so often

**Comment by devilangelsoul** [comment]
isolah123 how to use an ip/vpn charger?

**Comment by theloser** [comment]
This does **not** ssem to be a development issue or a bug. More like a config / "how-to" issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
