### ISSUE TITLE
[Request] Hotkey to display top pokemons

### ISSUE THREAD

**Issue by hannemaster** [NECROBOTIO/NecroBot#4972]
Hi,
I always need to restart the bot to see the top list pokemon. Is it possible that you code in a hotkey to display this? and pokeballs. perhaps you can let user set the key in config.

**Comment by theloser** [comment]
Use the telegram feature, it allows you all that (/profile, /items, /top, ...)

**Comment by hannemaster** [comment]
ok thank you sir!
