### ISSUE TITLE
NO POKESTOP AGAIN :(

### ISSUE THREAD

**Issue by andreslong** [NECROBOTIO/NecroBot#4973]

**Comment by theloser** [comment]
So, what? Is this a bug? No. It's just another softban. Nothing the devs could do right know to prevent this.

Please close this issue, thanks!

**Comment by sammyloy** [comment]
"UseProxy": true,
  "UseProxyHost": "165.138.66.247",
  "UseProxyPort": "8080",
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,

**Comment by sammyloy** [comment]
add this in no problem afterwards

**Comment by theloser** [comment]
Sure! He now will use the same proxy as you, and this IP address will get softbanned in 3... 2... 1... now! :dash:

**Comment by wanadry** [comment]
Thanks @sammyloy .. i use proxy from http://www.proxylisty.com/ip-proxylist and thats works
sorry for my bad english :smile:

**Comment by Gladi0n** [comment]
I cant find the Proxy settings in my config, do I have to manually add it?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
