### ISSUE TITLE
using different config/auth files

### ISSUE THREAD

**Issue by Morthym** [NECROBOTIO/NecroBot#4974]
starting the .exe always uses the files in /Config. OK

Using different auth or config always forces me to  
a) alter the files in /Config with Notepad manually
b) duplicate the whole bot file structure
c) ?

Is there an Option like a paramter for the exe? "necobot.exe -a e:\bot1\auth.json -c e:\bot1\config.json"

Are there any paramters documented?

Maybe this would be a nice Feature request...

**Comment by theloser** [comment]
This has been asked a few times already, and the devs decided not ti implement this, sorry.
And the bot does not support command line options.

**Comment by weedorbeat** [comment]
> And the bot does not support commandline options.

Of course the bot supports commandline. First argument its taken as subpath from root folder. Program.cs lines 46 - 55. Look at #667 this is apparently only for the configfile not for authfile

**Comment by theloser** [comment]
@weedorbeat Wow, you are actually right, didn't know that! :+1: 

So to use different config.json files you have to create the following subfolder structure (as an example):

> necrobot\
> necrobot\config
> necrobot\config_1
> necrobot\config_2

And the bot will **always** use the auth.json file from necrobot\config subfolder, but if you have a config.json in these subfolders "config_1" and "config_2" you can just do the following:

> necrobot.exe config_1

or

> necrobot config_2

Great!

**Comment by weedorbeat** [comment]
Right, and to switch quickly you can also create shortcuts with the respective parameters.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
