### ISSUE TITLE
Sniping manual coords doesnt work

### ISSUE THREAD

**Issue by pkosukhin** [NECROBOTIO/NecroBot#4976]
So sinse very beginning, there is no direct option to use or not manual locations for sniping. I mean 
"PokemonToSnipe": {
"Locations": [
]}

I ask to implement "UseSnipeManualLocations" independently of "UseSnipeLocationServer" and of any other pokez, poke, etc. Before last updates it worked like set "UseSnipeLocationServer" to true and bot uses localfeeder, false - and it uses manual locations, but now it is not. Generally, I want use both: online servers when they give some interesting pokemons (now I have 145/151, so I snipe only for strongest ones) and all the other time I snipe for pidgeys and rats using manual locations.

**Comment by TemhAAhmeT** [comment]
You are right, somehow they broked/changed it. So i am using v0.8.1
But wasnt worked sniping to either local and online at the same time. It would be nice to snipe local and online at the same time.

**Comment by max1404** [comment]
@TemhAAhmeT can you post your config - doesn't work for me with v0.8.1.

Thanks

**Comment by Profetorum** [comment]
Same, i wanted to use them as nests for exp (yeaaaah), but it doesn't work in newest versions. Try to downgrade to 0.7.6

**Comment by pkosukhin** [comment]
Before I used manual switch: first I use online feeders for rare pokemons sniping and amount of pokeballs increases very fast. When I rich about 250-300 pokeballs, switch back to manual locations and snipe all the nests for exp. When pokeballs is over, switch back to snipe rare pokemons and saving up pokeballs for nest sniping. So switched to 7.6 for now.

**Comment by Profetorum** [comment]
Same.

**Comment by max1404** [comment]
@pkosukhin 

Can you post your config @ pastebin.com?

**Comment by 123787** [comment]
Looking at your log it seems its using skiplagged.com for snipes not the local coordinate setup. My settings are posted with similar issue link as follow.
https://github.com/NECROBOTIO/NecroBot/issues/4840

**Comment by pkosukhin** [comment]
I used alot of defferent combinations. So using skiplagged.com according to the source code means using local locations, but its always out of pokemons. Smth works wrong.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance. This includes sniping "issues".

**Comment by pkosukhin** [comment]
Hey! This post not about confugurating what I want, it was just my usecase. Its about broken or missing option "use manual snipe locations"!

**Comment by Profetorum** [comment]
They're keeping close this type of issues. But it's a code issue!
