### ISSUE TITLE
NecroBot and Kaspersky Antivirus

### ISSUE THREAD

**Issue by Naografix** [NECROBOTIO/NecroBot#4979]
Hey,

My bot working everyday and everytime and this night at 3h (French hour) My kaspersky antivirus has detected your bot like a virus :

http://i.imgur.com/lZtOK5d.png

I just have this screen, i can't really help you but i think i must share this problem

**Comment by theloser** [comment]
Why did you **not** search for "kaspersky" before opening a new issue?
Why did you ignore the issue template?

This a duplicate of some other issues.
Please close this one and use already existing issues to comment on. Thanks!

**Comment by Naografix** [comment]
My bot work good. I created this issue just for help, it was my first idea when i saw this error : post this issue to necrobot github. Sorry...

**Comment by PenjagaHati** [comment]
![1](https://cloud.githubusercontent.com/assets/20869593/17581644/214dd8b8-5fd1-11e6-835e-06cac1587524.JPG)
Done

**Comment by PenjagaHati** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/3830

**Comment by Naografix** [comment]
I know ;)

**Comment by theloser** [comment]
@PenjagaHati Slightly offtopic, but you excluded "C:\Program Files" from your anti virus software? Great choice! Why not exclude "C:\" instead?

**Comment by PenjagaHati** [comment]
had forgotten why I created the first

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
