### ISSUE TITLE
[TELEGRAM] Add Security Access

### ISSUE THREAD

**Issue by TakRiuto** [NECROBOTIO/NecroBot#4984]
Hello! It would be possible to add a function that only allows specific users to access the information from the bot?

(Like in Ar1i PoGoBot) ^^

**Comment by TemhAAhmeT** [comment]
They already add that. And probably will be available at next version..

**Comment by theloser** [comment]
Yes, Duplicate of #4556 -- they implemented it, but it's not working atm. Please wait till it's fixed and released.
