### ISSUE TITLE
Bot stops to work after 5 minutes or so

### ISSUE THREAD

**Issue by ExarSenpai** [NECROBOTIO/NecroBot#4985]
just as title says. bot after 5 minutes of catching pokemon, transfering, or visiting pokestops stops its actions. i can provide my config, also Im using pogofeeder 0.1.2 to snipe. Note that duplicates in sniping list did not cause any problems
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/412713/config.txt)

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by Joloxx9** [comment]
Put your log on pastebin... First try it without pogofeeder, then if it work try latest pogofeeder 1.2 is old.

**Comment by ExarSenpai** [comment]
it just stopped taking actions, left it for some minutes seeing if it can recover and take actions, but it couldnt. pasting the log. no red lines. wondering what causes that bug. also, to mention, pogofeeder has nothing to do with it, checked with it and without, same result, bot stops. didnt change anything in config for long time despite pokemon to transfer list
[LOG.txt](https://github.com/NECROBOTIO/NecroBot/files/412734/LOG.txt)

**Comment by ExarSenpai** [comment]
Another log when it stopped working
[log2.txt](https://github.com/NECROBOTIO/NecroBot/files/412753/log2.txt)i

**Comment by theloser** [comment]
Do you have "QuickEdit" enabled on your console window? Check it!

I suppose you have, and with this enabled, if you "click" into your console window it automatically will select a single character and the output to this console window is paused -- and so is the running program (aka bot).

**Comment by ExarSenpai** [comment]
Unfortunately, I had it turned off whole of the time

**Comment by theloser** [comment]
Ok. Have you tried:

>  "UseSnipeLocationServer": false,
>  "GetSniperInfoFromPokezz": false,
>  "GetOnlyVerifiedSniperInfoFromPokezz": false,
>  "GetSniperInfoFromPokeSnipers": false,
>  "GetSniperInfoFromPokeWatchers": false,
>  "GetSniperInfoFromSkiplagged": false,
>  "SnipeAtPokestops": false,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
