### ISSUE TITLE
Problem With the New Update 1.3.1 releaded 5 minutes ago

### ISSUE THREAD

**Issue by kainbr3** [NECROBOTIO/NecroBot#4986]
the Necrobot can't snipe or find any Pokestop or even walk around. He can't login like the servers were offline, but i guess it's should be related to the new update (1.3.1) released 5 minutes ago.

**Comment by mrteddi** [comment]
I think you have the wrong github.

**Comment by theloser** [comment]
There is a 1.31. of NecroBot? Wow, and I am still on 0.8.5!
Geez...

**Comment by kainbr3** [comment]
the 1.3.1 mentioned is the new version of the game, pokemon GO. the previous were 0.33 and now its 1.3.1

**Comment by ev4ng3l1n3** [comment]
can't see it in android's play store yet.

**Comment by lnmtriet93** [comment]
I think 1.3.1 is iOS version number :)
And I don't think if there's problem if it's just client side update

**Comment by Joloxx9** [comment]
Everything working great.

**Comment by kainbr3** [comment]
I guess it should be a new type of ban? I will try a proxy here

**Comment by Joloxx9** [comment]
It is not related to the development, go to discord!

**Comment by kainbr3** [comment]
Yeah, it was that! I've had my ip blocked. Using a proxy it still works. 

PS: I start using Necro half a hour ago, i'm so unlucky T_T I will using the proxy and go to bed, and when i wake up, i will check if my ip still blocked and give the feedback here, to help those who had the same issue and are in doubt if it is permanent or not.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
