### ISSUE TITLE
Adding pkmn to the sniping list

### ISSUE THREAD

**Issue by schnork111** [NECROBOTIO/NecroBot#4989]
### Expected Behavior
I added some pokemon, which are missing in my pokedex to the snipinglist - didn´t work out.

### Actual Behavior
the bot crashes

### Steps to Reproduce
adding in : 
 "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "muk",
      "cloyster",
      "gengar",
      "marowak",
      "rhydon",
      "chansey",
      "kangaskhan",
# ##       ** "oddish",**
      "mrMime",
      "scyther",
      "magmar",
      "gyarados",
      "lapras",
      "ditto",
      "porygon",
      "kabutops",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]

### Other Information
Version: 8.5
Windows Version: 7 prof. 
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by Joloxx9** [comment]
This does not seem to be a development issue or a bug. More like a config issue.
 Please use the Discord channels to get help with your questions.
