### ISSUE TITLE
Stop Work after ten minute

### ISSUE THREAD

**Issue by SeemLike** [NECROBOTIO/NecroBot#4991]
Anyone ?

**Comment by Joloxx9** [comment]
This does not seem to be a development issue or a bug. More like a config issue.
 Please use the Discord channels to get help with your questions.

**Comment by Profetorum** [comment]
Stop saying this is a config issue. Since 0.8.0, bot worked with same configs for a lot of us.

**Comment by Joloxx9** [comment]
It is config issue. I'm on same config since 0.6 dropped and its working.

**Comment by theloser** [comment]
How does the bot stop? Where did it stop? Post logs/configs/details or we can't help you.

**Comment by ExarSenpai** [comment]
I think this is same issue as mine

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
