### ISSUE TITLE
Bot stopping

### ISSUE THREAD

**Issue by teknojix** [NECROBOTIO/NecroBot#4992]
![screenshot_4](https://cloud.githubusercontent.com/assets/13542417/17582236/36ab1a54-5fb3-11e6-82a6-80125f05b384.png)

**Comment by TheMaskedMonkey** [comment]
There's already an issue open for this. #4943 

Please search for other issues before opening dupes.

**Comment by Joloxx9** [comment]
This does not seem to be a development issue or a bug. More like a config issue.
 Please use the Discord channels to get help with your questions.

**Comment by TheMaskedMonkey** [comment]
> This does not seem to be a development issue or a bug. More like a config issue.
Please use the Discord channels to get help with your questions.

Actually I think it's a bug. There's no way miss configuration of the config should cause the bot to stop working at all. It has a loop of tasks to perform and it looks like that loop is breaking.

**Comment by iamaheroAsh** [comment]
maybe his network connection is too slow. I had tried once. I advice you to test the bot with a better network.

**Comment by TheMaskedMonkey** [comment]
My home connection has 200Mbp/s and some of the servers I've run them on too have 1Gbps along with another having 10Gbps. Pretty sure it's not connection.

**Comment by theloser** [comment]
There is a known bug where the bot waits for an infinite time if some sniper sites are having trouble or are down. I think there already is a fix for that, so please just disable sniping for now and wait for the next release.

(If you had searched for your issue beforehand you would have found tons of duplicates on this and solutions are posted an most of them. So: shame on you!)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by nfettinger** [comment]
This includes sniper issues.
