### ISSUE TITLE
Can not fight with sniped Pokemon in Arena?

### ISSUE THREAD

**Issue by andele123** [NECROBOTIO/NecroBot#4998]
Does someone have the same issue?
Catched some nice Pokemon and wanted to fight with them. There is an Error directly after beginning the match.
I read something about waiting for 2-3 hours and then it should work?!

**Comment by theloser** [comment]
Why not just do this, wait for 2-3 hours and try again?

And how is this a bot issue/bug?

This does not ssem to be a development issue or a bug. More like a config / softban issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by ubulem** [comment]
It's softban, not a bot bug. Try to unban first then fight

**Comment by andele123** [comment]
This is an issue resulting by using the bot.

@ubulem There was no softban...

**Comment by ubulem** [comment]
@andele123 why so sure? I had same problems when got softbanned. Other option - it's IP ban.

**Comment by theloser** [comment]
> This is an issue resulting by using the bot.

Yeah, maybe. But it's not a bug with the bot itself, right? Bot is working as intendend, correct?

If you want to fight gyms, please use your main account (because you **never ever** bot with your main account).

**Comment by andele123** [comment]
@ubulem If the Account is IP banned, the bot should also not work anymore, right? How do I fix Softbans? I thought the bot does this automatically?!

@theloser Yeah, bot is working apart from sniping.

**Comment by ubulem** [comment]
@andele123 yeah, bot does it automatically. you don't.
Try QuickSpin for unban. Set the coordinates of gym, make unban for your account and try to fight. 
And it's really not a bot problem.

**Comment by dtdw** [comment]
@theloser not related but i'm curious how did you came into this conclusion

> If you want to fight gyms, please use your main account

Then erm, what's the purpose of using the bot in the first place?

**Comment by andele123** [comment]
Is setting the coordinates of the gym essential? At the moment the coordinates are set to Central Park

**Comment by andele123** [comment]
@dtdw Same thing i'm thinking about

**Comment by ubulem** [comment]
@andele123 well, do you understand a reason of softban? For example you are in Moscow and bot is set for Central Park. 
Suddenly in five minutes you were moved for 10000 kilometers in 5 min. That's really suspicious that's why you get softban. So if you want to fight in your local gym you must have tell to system your actual location. But I don't know where you are, maybe in Central Park? Then you don't need to set your actual coordinates :)

**Comment by andele123** [comment]
I'm in cologne.

But...where I can see if I got softbanned or not?

**Comment by ubulem** [comment]
@andele123 Oh boy... Just download QuickSpin, set necessary settings and launch it. It will say you are softabnned or not and unban if you are.

**Comment by andele123** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20966236/17584016/67bdb3d0-5fb4-11e6-8a70-2ed878a4c7e8.JPG)

**Comment by andele123** [comment]
Seems to be not softbanned

**Comment by ubulem** [comment]
Great. And where is the gym? Not too far from you? Can you fight right now?

**Comment by andre1974** [comment]
You have to change the coordinates in Quickspin to your home coordinates. At the moment your coordinates are for Central Park.

**Comment by andele123** [comment]
I know @andre1974...Just tested if i am softbanned or not. I am in the office right now. Testing it for later. Thank you guys for answering my question. It's a pity that sniping doesn't work.

**Comment by andre1974** [comment]
You are not softbanned in Central Park, but at your home you are. So change coordinates and let Quickspin run again to unban you.

**Comment by andele123** [comment]
Good idea

**Comment by ubulem** [comment]
@andele123 come on...  in the first place I said you have to set coordinates of the gym, not Central Park or whatever.

**Comment by andele123** [comment]
Acutally i was softbanned at home

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
