### ISSUE TITLE
crash when re-login

### ISSUE THREAD

**Issue by V-E-O** [NECROBOTIO/NecroBot#5002]
Hi,

Sometimes server becomes unstable, bot will do re-login, and crash, not always.
I used the latest dev code. now I compiled a debug version to traceback it.

> [16:11:25] (ERROR) Causing Method: System.Collections.Generic.Dictionary`2[System.String,System.String] PerformAuthRequest(System.Collections.Generic.Dictionary`2[System.String,System.String]) Source: GPSOAuthSharp Data: System.Collections.ListDictionaryInternal
> [16:11:26] (INFO) Exception caught, writing LogBuffer.
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in E:\Code\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 69
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by V-E-O** [comment]
it's exception from GPSOAuthClient, temp workaround is try catch Null exception around client.PerformMasterLogin() in GoogleLogin.cs, and raise other exception to retry.it's exception from GPSOAuthClient, temp workaround is try catch Null exception around client.PerformMasterLogin() in GoogleLogin.cs, and raise other exception to retry.

**Comment by nfettinger** [comment]
The server is returning you an error
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by V-E-O** [comment]
You really sure it's configuration issue??
It crashes at certain timing in different bot instances and different proxies.
login the bot, working, server down, re-login, crash/not crash.
            var client = new GPSOAuthClient(email, password); //working configuration here!
            response = client.PerformMasterLogin(); //crash may happen here
Okay, I'll fork and fix it myself.
