### ISSUE TITLE
Pokemon keeps filling up to 250/250 and wont transfer?

### ISSUE THREAD

**Issue by Blackjesus69** [NECROBOTIO/NecroBot#5003]
heres my config
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/412796/config.txt)

**Comment by Cyruz007** [comment]
It keeps every pokemon above the values.
"KeepMinCp": 1250,
"KeepMinIvPercentage": 95.0,

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by Lillecarl** [comment]
@theloser https://github.com/NECROBOTIO/NecroBot/issues/4957 Could be related to this too, that the bot doesn't find lower CP pokemons to transfer (since i only found 99 on last try, when in app i had 250).

**Comment by Blackjesus69** [comment]
I have a bunch of low CP pokemon and alot of Golbats and bunch of dups that it just doesnt get rid of

**Comment by Lillecarl** [comment]
@Blackjesus69 i have a bunch of everything random that i can't get rid of programmatically, really bothers me.

**Comment by dimonstrer** [comment]
Same problem. Is there solution?

**Comment by silvantastisch** [comment]
"KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 20,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": true,

It will delete all pokemons under level20 and under CP1250. It works for me to get rid of all the rattata's, weedles, pidgeys and the evolves of those pokemons. BUT, it will also transfer pikachu, bulbasaur and these kind of pokemons.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by Lillecarl** [comment]
@nfettinger since the getpokemons function doesn't work as it should (it doens't include all pokemon in inventory) after awhile it won't find any duplicates and will therefore not remove them. Which i clearly explained in https://github.com/NECROBOTIO/NecroBot/issues/4957 which you also closed.
