### ISSUE TITLE
Bot can't find any Pokestops ?

### ISSUE THREAD

**Issue by waitingforanswer** [NECROBOTIO/NecroBot#5005]
Hi everyone,

Just about 15p ago i have this issue, and i think maybe Niantic changed something and our code can't work ?

My config.txt is fine and i use the lastest version.

![333](https://cloud.githubusercontent.com/assets/20966566/17583358/d4d2f54a-5fda-11e6-82ca-b07dc447a894.png)

**Comment by Deuxgod** [comment]
You have an IP ban. Either wait couple of hours for it to lift, restart your router and hope to get a new IP or get a VPN for boting.

**Comment by Sanskritmp** [comment]
@Deuxgod I've restarted my router, added a proxy and have vpn accessibility. Still, after 5hours, I can't even login in app and/or the bot. Any bot actually.

**Comment by Deuxgod** [comment]
@Sanskritmp that looks like an IP ban behaviour. Maybe the proxy/VPN is also banned.

**Comment by mrbosor20** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/4946

**Comment by Lolisniffer** [comment]
I also got this after opening 3 bot at the same time in same PC for a few hours. Changed my IP and problem solved. I'm not gonna multi bot again

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
