### ISSUE TITLE
cant find any pokestops

### ISSUE THREAD

**Issue by nuncx** [NECROBOTIO/NecroBot#5007]
checked everything, everything is fine. just suddenly stopped working. is this bug only for me or for everyone?

**Comment by Chuggers** [comment]
Currently working for me

![image](https://cloud.githubusercontent.com/assets/19950166/17583552/6fb9eb36-5fa9-11e6-8890-dda5d8a6f10e.png)

**Comment by Deuxgod** [comment]
You have a IP ban. Need to wait few hours max for it to lift, restart the router and hope to get a new IP or use a VPN for boting.

**Comment by waitingforanswer** [comment]
Thanks, but why i have band? and how to avoid that.

**Comment by mrbosor20** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/4946

**Comment by Deuxgod** [comment]
Well, try to keep your bot speed reasonable and avoid using more then one account per IP. Who knows how Niantic is issuing IP bans.

**Comment by waitingforanswer** [comment]
i put my account WalkingSpeedInKilometerPerHour =30 , so it safe. Yah, i think maybe Niantic bans because of using more than one account per IP

**Comment by xMicky24OF** [comment]
Where I can find a free vpn?

**Comment by nuncx** [comment]
i get it, i was using 2 accs. ty guys :)

**Comment by waitingforanswer** [comment]
hot spot shield, google you can find a lot.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
