### ISSUE TITLE
Bot can't find any pokestop

### ISSUE THREAD

**Issue by xMicky24OF** [NECROBOTIO/NecroBot#5008]
Bot can't find pokestops, rip

**Comment by mrbosor20** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/4946

**Comment by LordDeimos** [comment]
You could use the search tool on issue tracker, and look how many people like you have reported this issue, and look for yourself the solution.

That's probably a IP ban from Niantic side. This isn't anyway a development issue, and those question should be diverted to the discord chat.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
