### ISSUE TITLE
BOT stop working after visiting pokestop.

### ISSUE THREAD

**Issue by dzejkob89** [NECROBOTIO/NecroBot#5010]
It's happened to me few times today. All went fine few minutes, ant then nothing happened. I was trying to reset my cfg but it won't help.

![necrobot](https://cloud.githubusercontent.com/assets/20966834/17583797/1d33ae56-5fb3-11e6-8a7b-27481ac95534.PNG)

**Comment by Ollie102** [comment]
Turn "GetSniperInfoFromPokezz": false,

**Comment by dzejkob89** [comment]
@Ollie102 Thanks dude! Looks like it helps! :)

**Comment by Ollie102** [comment]
Yeh it helped me move past the first pokestop, but as ive said in my post above, my sniping really doesent work very well, can almost never find anything

**Comment by altindal52** [comment]
Thnx bro

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
