### ISSUE TITLE
[Bug] when catching a lured pokemon, the command line always say 'Candies: 3'

### ISSUE THREAD

**Issue by iTayGNR** [NECROBOTIO/NecroBot#5012]
when catching a lured pokemon, the command line always say 'Candies: 3'
Even when you have much more candies.

**Comment by mrbosor20** [comment]
your config?

**Comment by markemonb** [comment]
Probebly because of this line:
"MaxBerriesToUsePerPokemon": 3,

**Comment by nfettinger** [comment]
Duplicate issue.
