### ISSUE TITLE
Launching the bot Via a script from a different directory

### ISSUE THREAD

**Issue by 1Zeus1** [NECROBOTIO/NecroBot#5013]
So I am developing a bot manager so that people can use one program taht can create a new bot, give it preset configs and just manage all there bots in one place. However there is an error with the bot when ever i try to launch it from a different directory. When I run my script in the same directory as the bot it works fine.
The error that the bot gives me
[10:40:23] () Exceptiion caught, writing LogBuffer.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.GlobalSettings.Load(String path, Boolean boolSkipSave) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 716
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.CLI\Program.cs:line 63

**Comment by WishmasterNano** [comment]
dont know much about scripts but maybe this from the wiki helps? `If you plan to create a script that runs them, make sure the current working directory in your console is the root of each NecroBot's installation.`

**Comment by f998601** [comment]
set StartInfo.WorkingDirectory = DirPath (the location of the .exe) this will make you able to launch it.

**Comment by 1Zeus1** [comment]
Ive got around this by doing this 
os.chdir(botPath)
but i still think it should be fixed. One of the devs said to put this as an issue on here.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by 1Zeus1** [comment]
One of your devs told me this was an issue with the bot that they should fix and he told me to put it here so reopen this.
