### ISSUE TITLE
What should i do ? 

### ISSUE THREAD

**Issue by pkownsz** [NECROBOTIO/NecroBot#5014]
I'm using default settings so why no pokestops for me? 
DefaultLatitude": 40.785092,
  "DefaultLongitude": -73.968286,
  "WalkingSpeedInKilometerPerHour": 40.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": true,
  "DelayBetweenPlayerActions": 300,
  "DelayBetweenPokemonCatch": 2000,
![be pavadinimo](https://cloud.githubusercontent.com/assets/20967282/17584348/b4b866b2-5fbe-11e6-9bea-bb3f62bf8f98.png)

**Comment by mrbosor20** [comment]
ip banned

**Comment by pkownsz** [comment]
how can i be ip banned? :D firts of all this message always been for a while i mean i used it first time and got that message after 15mins again works fine now again.. xD

**Comment by LordDeimos** [comment]
40km/h and 300ms delay betwwen player action, you're asking to get IP banned for this settings.

Niantic became more aggressive on those behaviours

**Comment by pkownsz** [comment]
@lordDeimos now again works fine but i frozen on first pokestop what now? ;x i changed my settings 30km/h and 600ms

**Comment by ausscheider** [comment]
"WalkingSpeedInKilometerPerHour": 15.0,
"MaxSpawnLocationOffset": 10,
"FastSoftBanBypass": false,
"DelayBetweenPlayerActions": 5000,
"DelayBetweenPokemonCatch": 2000,

try this one and you need a new ip, before you try this one

**Comment by ausscheider** [comment]
@pkownsz 
set sniper to false

**Comment by pkownsz** [comment]
@ausscheider sniper from what? pokestops or what?:D btw i using your config now

**Comment by charlieswb** [comment]
what is the fastest legal walking speed?

**Comment by LordDeimos** [comment]
@charlieswb not more than 20 if you want to be fast, not more than 10 if you want to stay safe.

**Comment by ausscheider** [comment]
charlieswb how fast can you run? :D 
i use 15 and it works perfect

**Comment by ausscheider** [comment]
@pkownsz all sniper, when i remember the sniper was fix in the next release

**Comment by kurozani** [comment]
I use 45 and worked fine till now

did you set disablehumanizewalking (or something) to false

**Comment by jinkawasaki333** [comment]
I use 60 km/h with 1 to 5 ms delay between action, and no ban at all.
It's the matter with how many bots you run, or whether you connect multiple devices that run PoGo from one IP address (with home/office Wi-Fi router).

**Comment by pkownsz** [comment]
THANK YOU auschieder i false all snipers and did 15km/h 5k and 2k ms and now its perfect working thanks ! <3

**Comment by charlieswb** [comment]
I set it to 25km/hr and it's ok but in console
it says "travelling to pokestop : .... (112m) (8s)"
by my calculation that's 14m/s or roughtly 50km/hr. Is this a bug?

**Comment by nuncx** [comment]
so whats the best speed to use?

**Comment by TagorHP** [comment]
walking is around 5-10km/h,
running is around 10-20km/h
bicycle is around 20-40km/h
my experience: setting is less than 40km/h otherwise will got softban.

**Comment by Linewalker** [comment]
@pkownsz Please close this config-issue, if solved.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
