### ISSUE TITLE
Cannot run Necrobot on Ubuntu with Wine

### ISSUE THREAD

**Issue by AmazingGamerBoy** [NECROBOTIO/NecroBot#5016]
Hi guys,

I always get errors when I try to install the bot on Ubuntu using Wine. Many people have this problem so could someone please figure out how to successfully get it to work and then to make a tutorial on how to do it?

Thanks

**Comment by LordDeimos** [comment]
Simply as the question, that doens not have nothing related with development on this project.
The bot is programmed in .NET, you can try to compile the project in mono with Xamarin (6+) but the work to make the code compatible with mode is underway as i see from the commits.

That is a question more for wine if you want to run with it.

**Comment by qwert95** [comment]
Already have this open :
https://github.com/NECROBOTIO/NecroBot/issues/3289

Please close here
