### ISSUE TITLE
[Feature Request] Seperate Delay Setting for Evolution

### ISSUE THREAD

**Issue by elmaarmut** [NECROBOTIO/NecroBot#5017]
I'm using a 7sec delay for player actions, but evolving that fast isn't humanly possible. And I don't want to set the player action delay timer to 30 secs, or transfers would take forever.

Can we PLEASE have seperate delay settings for these actions? I really don't want to keep using a different config just to do my evolves with a larger delay, and change it back and restart after I'm done evolving.

**Comment by ev4ng3l1n3** [comment]
Yeah, we could use more options for delays, so we can make the bot act more human-like.

**Comment by nfettinger** [comment]
Duplicate issue.
