### ISSUE TITLE
translation.th Not work .

### ISSUE THREAD

**Issue by bomshiza** [NECROBOTIO/NecroBot#5019]
translation.th Not work . help me

![untitled](https://cloud.githubusercontent.com/assets/20646841/17585165/62c23286-5fe4-11e6-8dd7-afedb89145a6.png)

**Comment by Oolaruu** [comment]
Have you tried to download/setup the Thai language for your windows ?

**Comment by bomshiza** [comment]
Win8.1 64Bit

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
