### ISSUE TITLE
Confusion in transfer

### ISSUE THREAD

**Issue by catvinhquang** [NECROBOTIO/NecroBot#5020]
Config file:
"KeepMinCp": 2000,
"KeepMinIvPercentage": 90.0,
"KeepMinLvl": 6,
"**KeepMinOperator**": "**or**",
"UseKeepMinLvl": false,
"**PrioritizeIvOverCp**": **false**, // Currently, i set this value to **true**, but i'm not sure...
"**KeepMinDuplicatePokemon**": **3**
"TransferWeakPokemon": true,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": true,

Result:
(CatchSuccess) | (Normal) Arcanine Lvl: 11 CP: (935/938) IV: 98.00% | Chance: 9.03% | 5768193.92m dist | with a UltraBall (22 left). | 210 EXP earned | Candies: 71 | lat: 40.410888 long: -3.689543

KeepMinOperator is OR and my inventory just have only one Arcanine (above), why BOT transfer this? I suddenly exit BOT so i can't screenshot TRANSFER log.

Sorry for my English not well!

**Comment by ubulem** [comment]
Possible different settings in PokemonsTransferFilter list that overrides any other settings.
Could you please check your PokemonsTransferFilter list?

**Comment by TagorHP** [comment]
set "TransferWeakPokemon": false,

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
