### ISSUE TITLE
Question mark symbol box thingy HELP!

### ISSUE THREAD

**Issue by TrialCrafter** [NECROBOTIO/NecroBot#5021]
Left side of picture = Console? Cmd? Bot?
Right side of picture = part of my config

![image](https://cloud.githubusercontent.com/assets/20967708/17585132/3f59c8d6-5fe4-11e6-817d-fe4fdcd4e55f.png)

My console is showing part of it with this question mark box symbol. /\ /\ /\ /\
Btw I'm on windows 10

**Comment by TrialCrafter** [comment]
Feel free to zoom in the picture

**Comment by pyrotimux** [comment]
Try changing the language in your config? "TranslationLanguageCode": "en",

**Comment by TrialCrafter** [comment]
Oh that was easy sorry

**Comment by TrialCrafter** [comment]
Its part Th and part En

**Comment by Linewalker** [comment]
Please close, if solved. Config-Issue.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
