### ISSUE TITLE
Got softban again, with UseSnipeLocationServer : false & SnipeAtPokestops : false

### ISSUE THREAD

**Issue by Jojoushi81** [NECROBOTIO/NecroBot#5022]
Hi Guys,

I got softban again. Possibly IP ban too.
I'm using this config:
http://pastebin.com/rmjx7WPJ

Can u give me solution again?

Thanks.

**Comment by lukaskris** [comment]
im too, get softban but 3times in pokestop fail unban, wait the solution

**Comment by bomshiza** [comment]
1IP wan 1 bot not work 2 bot 1ip wan

**Comment by Caliboss** [comment]
i get ipbanned if i dont snipe lol.. once sniping goes off im ipbanned within 10min. i even put my delayes high....

**Comment by Jojoushi81** [comment]
I just use 1 bot on my laptop...

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
