### ISSUE TITLE
Best config?

### ISSUE THREAD

**Issue by VCorleone** [NECROBOTIO/NecroBot#5023]
can anybody share a good config or where can I find one?
my config is not good and I don't know what I'm doing wrong...
thanks!

**Comment by blue1Elephant** [comment]
why do you mean it's not good?

**Comment by VCorleone** [comment]
it isn't working good. it stops after catching one pokemon. it needs 3,5 hours for 120K EXP

**Comment by kurozani** [comment]
it is good enough :(

35K exp per hour is good enough
