### ISSUE TITLE
"Device Info" setup

### ISSUE THREAD

**Issue by CaptainPojar** [NECROBOTIO/NecroBot#5024]
https://github.com/NECROBOTIO/NecroBot/wiki/Device-Setup
here given the following values:

> "DeviceId": "", // adb.exe shell settings get secure android_id
> "AndroidBoardName": "", // adb.exe shell getprop ro.product.board
> "AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader
> "DeviceBrand": "", // adb.exe shell getprop ro.product.brand
> **"DeviceModel": "", // adb.exe shell getprop ro.product.model**
> "DeviceModelIdentifier": "", // adb.exe shell getprop ro.product.name
> "DeviceModelBoot": "qcom",
> "HardwareManufacturer": "", // adb.exe shell getprop ro.product.manufacturer
> **"HardwareModel": "", // adb.exe shell getprop ro.product.model**
> "FirmwareBrand": "", // adb.exe shell getprop ro.product.name
> "FirmwareTags": "", // adb.exe shell getprop ro.build.tags
> "FirmwareType": "", // adb.exe shell getprop ro.build.type
> "FirmwareFingerprint": "" // adb.exe shell getprop ro.build.fingerprint

Are you sure that the "DeviceModel" and the "HardwareModel" have the same value? And how accurate are other values?

**Comment by nfettinger** [comment]
They are often the same, but they are reported in separate fields in the phone itself.
