### ISSUE TITLE
Auto Favourite by IV

### ISSUE THREAD

**Issue by edoth76** [NECROBOTIO/NecroBot#5026]
I love how auto favourite now is available, but i was thinking to how put this action before transfer pokemon action that not meet the criteria when we start this necrobot.
_Or perhaps this action (auto favorite) can be done immediately after we catch that pokemon (edited)._
Because I had lost my dragonite with 85 IV that i forget to favorite before starting the bot.

**Comment by ausscheider** [comment]
"KeepMinIvPercentage": 90.0,

set this to 85 when you mean 85 is ok for you

**Comment by edoth76** [comment]
the problem is  I had already set that value (Min IV : 85) but when the bot start, the action of transfering pokemon done which ignoring this "KeepMinIvPercentage": 85.0 value. then the result is dragonite transfered to candy.
Anything wrong with my config?

**Comment by jasonisnear** [comment]
I guess you need to set PrioritizeIvOverCp to be true

**Comment by edoth76** [comment]
already set that value mate ... thanks for your attention.

**Comment by noodle-** [comment]
@edoth76 post your config

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
