### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by Shawak** [NECROBOTIO/NecroBot#5029]
First of all, this is a suggestion.

The bot should not start twice within the same directory, especially if you are updating because that may break your config files. My idea is to implement a mutex, something like "necrobot_<path of .exe>" to prevent running it twice without copying it.

Regards

**Comment by nfettinger** [comment]
This would increase complexity for a few ignorant people.

**Comment by Shawak** [comment]
complexity?

This is like five lines code
