### ISSUE TITLE
Help me..What happened!!!

### ISSUE THREAD

**Issue by inwsamurai** [NECROBOTIO/NecroBot#5033]
![what](https://cloud.githubusercontent.com/assets/20932652/17586274/dda32086-5fea-11e6-8230-52249daad3fa.JPG)

**Comment by ubulem** [comment]
You have a IP ban than, don't run more than 1 bot on 1 IP address, now you should wait 1-2 hours and than continue with ONE bot

**Comment by wowanshai9** [comment]
ban ip need to reset ip

**Comment by wowanshai9** [comment]
ban ip need to reset ip

**Comment by wowanshai9** [comment]
ban ip need to reset ip

**Comment by wowanshai9** [comment]
ban ip need to reset ip

**Comment by EyesReye** [comment]
your IP Got banned, Wait 1-2 Hours or use a VPN, Also don't run more than 2-3 bots on 1 IP Adress.

**Comment by inwsamurai** [comment]
oh very thanks!!

**Comment by idkwateva** [comment]
There's another IP Ban warning...

> Connection refused. Your IP might have been Blacklisted by Niantic. Exiting..

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
