### ISSUE TITLE
CANT CHANGE COORDINATES

### ISSUE THREAD

**Issue by catherines99** [NECROBOTIO/NecroBot#5034]
I CAN NOT CHANGE THE COORDINATES. ALWAYS PUTS NEW YORK. HOW CAN I DO??

**Comment by ubulem** [comment]
It seems you don't even try...
Put desired coordinates to these lines (for example Sydney)
  "DefaultLatitude": -33.859048,
  "DefaultLongitude": 151.213183,

**Comment by Linewalker** [comment]
Please read Wiki :-) and close this. Config-Issue.

**Comment by theloser** [comment]
@catherines99 Btw, your caps lock is broken.

**Comment by ev4ng3l1n3** [comment]
Close the bot before you edit the coordinates then start the bot.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
