### ISSUE TITLE
walking distance 1000 meters, thats radius? and no egg machines collected.

### ISSUE THREAD

**Issue by CharliePrown** [NECROBOTIO/NecroBot#5035]
am i right that for big cities like in the usa 5000 would fit better?

its radius, circle around coordinates?

so anything between 4000 and 8000 metres should be better for getting around the city?

and sorry for not knowing the english word, is there one and named in the config so that i only have my one endless machine for breeding but no more machines that are to be used thrice and then done?

they are to be gotten at pokestops or by leveling up?

thought on stops, but bot maybe config that he does not collect them?

thanks from me for your answer already

**Comment by TagorHP** [comment]
5000 is in meter, so it mean 5km..
I used to set as 150000 (150km)

**Comment by CharliePrown** [comment]
ha, really?

means small county too?

no idea why it is just 1000 meters out of the box)

**Comment by ruchern** [comment]
IP ban.

**Comment by CharliePrown** [comment]
in relation to what that answer?

no machines dropping?

**Comment by TagorHP** [comment]
event its a big number, but it will walking around 20km max.
my sugestion: close your bot and pogo at the gadget, delete config.json, and run the bot again.
and get a fresh config.json the default value should running fine.
then you can customize your needs.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
