### ISSUE TITLE
WHY 90%+ IV?

### ISSUE THREAD

**Issue by jazzu20** [NECROBOTIO/NecroBot#5038]
can somebody explain why we should prioritize sniping 90%+ IV, instead of high CP? 

thanks!

**Comment by ubulem** [comment]
Because when you level up pokemon with higher IV it will be stronger.
That's a question for Discord I think...

**Comment by maryo555** [comment]
why i cant use snipelocation??

**Comment by maryo555** [comment]
snipelocation : true
but my necroboat cant walk
what a problem?

**Comment by jazzu20** [comment]
@maryo555 unrelated topic bro.

**Comment by maryo555** [comment]
yea,i know,i just want ask 1 question
sory dude

**Comment by AdamWeishaupt1776** [comment]
im dying. @jazzu20 calls out @maryo555 for being off topic, yet this entire issue should never have been posted to github in the first place. Well played.

**Comment by burntable** [comment]
@maryo555 Just a guess, but maybe your "necroboat" can't walk because you need to put it on water?

**Comment by spylor** [comment]
High CP is nice and easy to use in gyms and such, as they can be used without needing candy and dust to upgrade.
IV (an individual modifier of every pokémon ranging from 0 to 100,) indicates how much potential it has. Let's say 50 is average. This modifier if I'm correct gives about a 10% stats boost. 
So if you ever take a pokémon to level all the way, you might pick one with high IV as it'll have an edge on pokémon with lower IV at the same CP level. So a pokémon of CP 2000 IV 20 might be a great catch, but it might not be your best choice for using your candies on. A pokémon of CP 800 IV 92 might need more candies and dust, but it'll be almost as strong as you can get it (92/100), if you have the dust and the candy to boost the CP of course. (Don't go comparing charmanders and squirtles...)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by jazzu20** [comment]
@spylor this is the most satisfying answer. thanks !!
