### ISSUE TITLE
Two istances with webSocket

### ISSUE THREAD

**Issue by lorenzo93** [NECROBOTIO/NecroBot#5039]
Hi,

I keep two istances of NecroBot running on the same computer and everything works fine except for the webSocket.
The two istances have two different WebSocket port (14251, 14252) but works only the websocket port of the first istance that I run.
The other seem not working or not anwsering, like there is no service listening on that port.

**Comment by Linewalker** [comment]
Try 15251 for the second instance.
Config-Issue, please refeer to Discord.

**Comment by theloser** [comment]
If you set the Websocketport to 14521, the bot actually will create **two** websockets, on port 14521 (HTTP) and 14522 (HTTPS). So for the next to work you have to set the websocket port to 14523 -- just skip one port number per bot and it'll work.

**Comment by lorenzo93** [comment]
Thank you @theloser. Now I figured out the problem!
Maybe this should be written in the config wiki

**Comment by theloser** [comment]
I suppose there will be no more websockets in the near future. The devs are working on a GUI already, and the creator of the necrobotvisualizer is aware of that (see his comment on the latest release: "Most probably the latest version. I don't use it anymore, and there is an official UI in the way anyway.")

**Comment by lorenzo93** [comment]
I hope they are creating a web UI, with AngularJS or something similar.
So they keep working on two different software, the CLI and an interface (Maybe written in Node.js) that connects to the CLI via WebSocket.
