### ISSUE TITLE
Pokemonstoignore is not working anymore

### ISSUE THREAD

**Issue by sevdem** [NECROBOTIO/NecroBot#5042]
"PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "rapidash",
    "venonat",
    "poliwag",
    "poliwhirl",
    "paras",
    "psyduck",
    "diglett",
    "articuno",
    "zapdos",
    "moltres",
    "zubat",
    "horsea",
    "magikarp",
    "ekans",
    "slowbro",
    "golduck",
    "krabby",
    "sandshrew",
    "slowbro",
    "slowpoke",
    "snorlax",
    "rhyhorn",
    "clefairy",
    "staryu",
    "tentacool",
    "magnemite",
    "mankey",
    "goldeen",
    "drowzee",
    "eevee",
    "nidoranMale",
    "nidoranFemale",
    "ponyta",
    "mewtwo",
    "mew"
  ],

Previous versions were skipping them just fine, I just want to catch what I need, I don't want hundreds of zubat candies, latest version is catching them all even though I tell it to ignore, what should I do?

**Comment by sevdem** [comment]
found it, never mind :)

**Comment by alexmanea2000** [comment]
How you solved it?

**Comment by ev4ng3l1n3** [comment]
I think you can close your own issues. Please do it so the developers won't waste time on reading this. :)

**Comment by ev4ng3l1n3** [comment]
@alexmanea2000 He probably changed 
`"UsePokemonToNotCatchFilter": false,` 
to 
`"UsePokemonToNotCatchFilter": true,`

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
