### ISSUE TITLE
cant open this version on my pc

### ISSUE THREAD

**Issue by khaki1986** [NECROBOTIO/NecroBot#5043]
17:00 () exception caught, writing log buffer
unhandled Exception : System.NullReferenceException : object reference not set to an instance of an object.
at PoGo.necrobot.CLI.program.CheckKillSwitch()
at Pogo.Necrobot.Cli.Program.Main(String[]args)

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by TagorHP** [comment]
have you:
- close the pogo on the gadget?
- use the default config.json?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
