### ISSUE TITLE
NecroBot just stopped working...

### ISSUE THREAD

**Issue by PROPANganda** [NECROBOTIO/NecroBot#5044]
So, yesterday like 10 pm (Europe), I restarted my NecroBot. After the restart, he worked fine, until he looted the first Pokéstop. After a thousand times of restarting it, I thought it the problem may be gone the next day, but today it is still not working. I tried VPN, Proxy, checked if my json files are valid, deinstalled the bot and installed it again,, nothing worked. Also on the internet i could only find one more person with this problem, so there were no answer to the issue. Does anyone else has this problem or had it and fixed it? Thank you for answers

**Comment by sevdem** [comment]
how does it not work? any errors? try with a different computer with different connection?

**Comment by TagorHP** [comment]
please set "GetSniperInfoFromPokezz": false it should run well,
if it doesn't also set "SnipeAtPokestops": false,

**Comment by Linewalker** [comment]
1. Set "GetSniperInfoFromPokezz" to false
2. Possably soft-banned
3. Possably IP-banned

**Comment by PROPANganda** [comment]
![bereich11](https://cloud.githubusercontent.com/assets/20954548/17587141/b243abf0-5fc6-11e6-8064-6fe787b1f046.png)

**Comment by PROPANganda** [comment]
@Linewalker @TagorHP Yes, there was an issue with Pokezz. I set it to false and it worked. Thank you very much :)
