### ISSUE TITLE
Made 210 EXP on catchsucces - always

### ISSUE THREAD

**Issue by spylor** [NECROBOTIO/NecroBot#5050]
### Expected Behavior
I would expect to get exp values ranging between 100 and 210.

### Actual Behavior
In the console it always gives 210 on capture

### Your config.json
I have set in the config chances for nice, great, excellent of 21, 9, 3 and 92 for curveballs. (I've tried putting 0.21 and so on, but that doesn't seem to work.)

**Comment by rachong** [comment]
Set HumanizeThrow  "true"

**Comment by spylor** [comment]
That makes sense.
