### ISSUE TITLE
[REQUEST] Add new transfering option- Keep the best IV and also CP 

### ISSUE THREAD

**Issue by Rago11** [NECROBOTIO/NecroBot#5051]
It would be great if you add a new option for transfering pokemons.

It should work like that you choose the number of duplicates for pokemons for best IV and than for best CP.

For example: KeepDuplicatedSortByIV: 2
                    KeepDuplicatedSortByCP: 3
It will compare the pokemons you have to pokemon you catched and than will decide which should be transfered, but it will everytime keep 3 with the highest CP and 2 with the highest IV.

That is the option I am missing and only that holds me back from this great BOT :( 
Becouse on the one hand I want to keep highest CP pokemons I already have and of course catch new ones in case I ll not have dust to POWER UP. And on the other hand I want to find 90+ IV pokemons. 

Thank you. 

### Other Information
What is affected: transfer

**Comment by spylor** [comment]
Keeping a pokémon of IV 26 isn't very useful, even if it's the best IV you have...
I get what you mean. But it's already half way there, the way it works now, as it'll keep the pokémon with IV higher than the value you set and in general check for CP to keep the best 2 or 3 pokémon you tell it to keep, so it'll keep more pokémon if you got low CP high IV pokémon (the 2 CP once and all the once with IV above the set amount) and you won't be getting tons of very high IV pokémon of the same type very soon anyway.

**Comment by nfettinger** [comment]
Duplicate issue.
