### ISSUE TITLE
i need pokezz snipe. How to use pokezz(sorry my english is suck)

### ISSUE THREAD

**Issue by boomzbe** [NECROBOTIO/NecroBot#5053]
how to use it ?

**Comment by Deamxxx** [comment]
Set: 
 "GetSniperInfoFromPokezz": true,
 "GetOnlyVerifiedSniperInfoFromPokezz": true,

**Comment by boomzbe** [comment]
dont' work 

i set that true bot will Sleep 
sleep immediately.now i set pokezz to false bot is work again.

**Comment by Deamxxx** [comment]
There are some problems around with Pokezz at the moment.
Try the other Snipe Sites set to TRUE and wait for more infos : )
Hope that i had helped you.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by WishmasterNano** [comment]
@nfettinger this actually is a code issue: https://github.com/NECROBOTIO/NecroBot/pull/4787
but already fixed for the next version @boomzbe
