### ISSUE TITLE
Can Anyone Help Me?

### ISSUE THREAD

**Issue by SunSmileOverTheMoon** [NECROBOTIO/NecroBot#5054]
![ss](https://cloud.githubusercontent.com/assets/20969626/17587962/7636d754-5f80-11e6-965b-9efd8919fc42.png)
Any suggestion?
I waited for half an hour but nothing change ...

**Comment by Deamxxx** [comment]
Had Problems with the use of Pokezz. May you too?
Set the snipe to false and it worked well for me.

**Comment by SunSmileOverTheMoon** [comment]
It worked ...
Thank u sir
