### ISSUE TITLE
user cresidentials invalid on necrobot 0.8.5

### ISSUE THREAD

**Issue by Dimisan** [NECROBOTIO/NecroBot#5057]
Hello after I updated my Necrobot on 0.8.5 i am experiencing the title issue and while i have tried the solutions that were suggested on previous patches i still cannot make my bots run. Any idea?

**Comment by Oolaruu** [comment]
Can you post your Auth.json ?
hide your login.

**Comment by Dimisan** [comment]
![save me](https://cloud.githubusercontent.com/assets/20969742/17588235/28c6e116-5fd6-11e6-8636-64f0077d4304.png) 

Here you go

**Comment by AnigmaL** [comment]
Same issue here, even autosetup result the same output

**Comment by theloser** [comment]
Could you please delete your auth.json (make a backup), then start the bot and go through the setup routine? Is this working for you?

**Comment by Dimisan** [comment]
did that as well but still experiencing the same issues wil ltry again just in case

**Comment by Dimisan** [comment]
and nothing changed unfotrunately

**Comment by AnigmaL** [comment]
Ha~~I found the problem....eventually I didn't activate my account......
How come now only got issue....

**Comment by theloser** [comment]
Have you tried using your Ptc login credentials on the actual site from niantic? Are they working?

**Comment by theloser** [comment]
[PEBKAC](http://lmgtfy.com/?q=PEBKAC) and not a bot issue then, please close this issue -- thanks!

**Comment by muschter** [comment]
@AnigmaL You are given two days to activate your account, or else you have to login again to get another link e-mailed to you,

**Comment by AnigmaL** [comment]
I'm not sure Dimisan facing the same issue as me, but mine is solve

Now the bot transfer all my pokemon T.T

**Comment by Dimisan** [comment]
I guess i had the same issue since verifying and activating seem to be different thanks for the help
