### ISSUE TITLE
NECROBOT Crashes before config creation

### ISSUE THREAD

**Issue by nunnaldo** [NECROBOTIO/NecroBot#5061]
### Expected Behavior
allows me to follow through setup as it did before

### Actual Behavior
see screenshot
![capture](https://cloud.githubusercontent.com/assets/20923609/17588311/e73d1fcc-5fc5-11e6-9276-3f8fd43e77aa.JPG)

### Your config.json
your config here

``` haven't been able to configure it yet 
just downloaded the zip release and this happened 
```

### Steps to Reproduce
opened the zip folder, extracted to local desktop, ran the necrobot.exe 
error occurs immediatel

### Other Information
tried redownloading 
took from https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.8.5
Version:v0.8.5
Windows Version: 7 64 bit professional 
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
logging on and using it

**Comment by Oolaruu** [comment]
Just checked latest compile, and everything work like a charm.
Can you retry again ?

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
