### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by Gladi0n** [NECROBOTIO/NecroBot#5064]
Hey, i got an error with my proxy, can anyone help me?

### Expected Behavior
Proxy changes IP

### Actual Behavior
Necorbot chrashes

![necrobot crash](https://cloud.githubusercontent.com/assets/20952880/17588422/0e9f9b54-5fcf-11e6-8ce8-37b05cbe5ca4.PNG)

auth.json:

{
  "AuthType": "ptc",
  "GoogleUsername": null,
  "GooglePassword": null,
  "PtcUsername": "Censored",
  "PtcPassword": "Censored",
  "UseProxy": true,
  "UseProxyHost": 80.112.179.53,
  "UseProxyPort": 80,
  "UseProxyAuthentication": true,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "xoom",
  "DeviceId": "f79ba5ef47e0a2ca",
  "AndroidBoardName": "",
  "AndroidBootloader": "1050",
  "DeviceBrand": "motorola",
  "DeviceModel": "Xoom",
  "DeviceModelIdentifier": "tervigon",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "Motorola",
  "HardwareModel": "Xoom",
  "FirmwareBrand": "tervigon",
  "FirmwareTags": "test-keys",
  "FirmwareType": "userdebug",
  "FirmwareFingerprint": "motorola/tervigon/wingray:4.1.2/JZO54K/485486:user/release-keys"
}

**Comment by theloser** [comment]
This does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by thoramisu** [comment]
add quotes around your proxy's ip

"UseProxyHost": "80.112.179.53",

**Comment by Gladi0n** [comment]
Thanks @thoramisu!
