### ISSUE TITLE
Cant find pokestops ?

### ISSUE THREAD

**Issue by Roodren** [NECROBOTIO/NecroBot#5066]
I cant find pokestops. I have tried to change position but doesnt help. This is what the bot says!
![help with bot](https://cloud.githubusercontent.com/assets/20970153/17588504/cb63a49c-5fcf-11e6-9625-0c2ad3f16336.JPG)

It worked for an hour ago.

**Comment by theloser** [comment]
Search issues before creating new one, **please**

Then close this one, because it's a duplicate of a duplicate of a duplicate of ...

**Comment by Roodren** [comment]
Have been searching, without answers.

**Comment by theloser** [comment]
How did you not find any?
I suppose you are lying to me.

https://github.com/NECROBOTIO/NecroBot/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20pokestops

Returns 33 open and 344 (!) closed issues!

**Comment by thoramisu** [comment]
Your IP has been softbanned. This will last for 30 minutes to 1 hour.
Only run 1 bot on your network and limit api calls.

**Comment by ubulem** [comment]
Don't lie please. It was answered like hundred times. It's IP ban, so just wait couple of hours or change it and launch one bot per IP

**Comment by Roodren** [comment]
Im new to this site so dont know how to search proparly. My bad!
Thx Thoramisu.

**Comment by Dequim** [comment]
Meh.... Wait for a few hours, then try with VPN, configure low walking speed and big delays between interactions. (for being more humanly)

And every 5th issue is about this....

**Comment by Roodren** [comment]
I wait then. Im closing this chat and if it doesnt work I make a new one :smile:
