### ISSUE TITLE
Collecting Pokestops before arriving at it

### ISSUE THREAD

**Issue by Zellerich** [NECROBOTIO/NecroBot#5067]
### Expected Behavior

Collect the Pokestop when you are at it.

### Actual Behavior

It writes how far the Pokestop is, and then starts collecting the Pokestop even if it isnt in range. The further away the Pokestop is, the more often it writes that you eventually have a softban, even though you just arent in range.

### Fix

Just collect the Pokestop when you actually are at it.

**Comment by nfettinger** [comment]
Already implemented when using GPX files.

**Comment by theloser** [comment]
Well, I am pretty sure that's is axactly how the bot works! It says "Hey, I am walking to the next pokestop, it's xx meters away and using a walking speed of xx km/h it'll probably take xx seconds until I'll arrive at the pokestop.". Then the bot "walks" to the stop, and if it has arrived, it spins it and collects the items.

Don't know how the bot works if you have DisableHumanWalking set to true, could be that the bot just teleports to the pokestop instantly. But that's something you can turn off in your config.json.
