### ISSUE TITLE
Cant catch pokeom in real life anymore

### ISSUE THREAD

**Issue by ckuti86** [NECROBOTIO/NecroBot#5070]
I have a major problem starting using this software today and when close it down leave the house to play the game all Pokemon escape after a throw and then run anyway

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by Pilskopf** [comment]
You should know u have to wait a cupple of hours before log in into ur right location.
For example u farm in New York but u actually live in San francisco. So you "ported" within minutes an 2 hour flight
