### ISSUE TITLE
Finds one pokestop in central park then stops.

### ISSUE THREAD

**Issue by hamwarrr** [NECROBOTIO/NecroBot#5071]
Has gotten stuck like this for the past day. Any ideas how to fix it? 
thank you.

![untitled](https://cloud.githubusercontent.com/assets/20892513/17589294/d2b751c0-5fcb-11e6-949f-f23055906d9f.png)

config is default one but with ''KeepMinDuplicatePokemon": 1'' changed to ''KeepMinDuplicatePokemon": 3''

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
