### ISSUE TITLE
Stop looting pokestops after a condition has been met

### ISSUE THREAD

**Issue by Dam-son** [NECROBOTIO/NecroBot#5072]
First, I want to thank you guys for the amazing work you do!

As far as I know, I don't think it's currently possible to stop looting pokestops after a condition has been met. The condition I personally would want is: the amount of pokeballs is equal to or more than "TotalAmountOfPokeballsToKeep". If this condition is true, I would still want to wander around, but without actually looting the pokestops.

A bug that could occur is when a sniping config has been set up, usegpxpathing is set to false and looting pokestops has been disabled, no sniping would be done. In that case, maybe it's better sniping executes every second or based on the value "forMinDelayBetweenSnipes" in milliseconds (whichever is higher).

It would be really nice if this were to be implemented.

**Comment by nfettinger** [comment]
Not worth the complexity cost.
