### ISSUE TITLE
Pokestop issue

### ISSUE THREAD

**Issue by APokegod** [NECROBOTIO/NecroBot#5073]
Necrobot v0.8.5, "no usable pokestops found" 
[Release.zip](https://github.com/NECROBOTIO/NecroBot/files/413233/Release.zip)

**Comment by smoothrunnings** [comment]
you have been IP soft banned. 
You can only have 1 bot per IP now. 
You have to wait 30 minutes to an hour before you can start again.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
