### ISSUE TITLE
[Request] Improve config file

### ISSUE THREAD

**Issue by Kraker01** [NECROBOTIO/NecroBot#5075]
Is it possibile to enhance the config file? I mean, creating some sections like:

[Evolving options]
[Sniping options]
[Humanize options]
[General options]

and so on, so it will be easier to configure the bot from scratch

**Comment by Oolaruu** [comment]
[Proxy options]
[Telegram options]
[Navigation options]
maybe more?

**Comment by nfettinger** [comment]
.json does not support sections
