### ISSUE TITLE
Invalid Proxy

### ISSUE THREAD

**Issue by epsonc83** [NECROBOTIO/NecroBot#5077]
Why Invalid Proxy???

PROXY paid but can not be used

![proxy](https://cloud.githubusercontent.com/assets/20931481/17589681/b1fe200c-6008-11e6-9e96-030f129687ef.png)
![proxy3](https://cloud.githubusercontent.com/assets/20931481/17589685/b616cd10-6008-11e6-992b-356e1a04bb0d.png)

**Comment by nfettinger** [comment]
****
