### ISSUE TITLE
TransferWeakPokemon

### ISSUE THREAD

**Issue by ilihack** [NECROBOTIO/NecroBot#5079]
TransferWeakPokemon have an bug,
it should be Transfer all weak Pokemon wher are under the KeepSettings,
But it ignore the KeepIV setting and only lock to the KeepCP setting.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by nfettinger** [comment]
Duplicate
