### ISSUE TITLE
regarding minimum pokeballs when trying to snipe 

### ISSUE THREAD

**Issue by Seyrenvox** [NECROBOTIO/NecroBot#5080]
since my issue is closed (https://github.com/NECROBOTIO/NecroBot/issues/4936), though with unclear answer, I want to suggest that the bot won't execute sniping IF pokeballs not met minimum requirement. 

the current version is,  it always check the sniping location first THEN checking the pokeballs. 
which is, for me, redundant.
because it should be checking the pokeballs first, and then trying to snipe the Pokémon in specific location. not vice versa.

**Comment by nfettinger** [comment]
Please do not open new issues because you are unhappy with a Mod's response. Discuss it in Discord.
We are unable to handle the number of sniping issues, therefore we cannot help.

**Comment by Seyrenvox** [comment]
with all my respect, mod. this is not about me unhappy with your respond. 
this is actually a bug, don't you think? 
the logic of minimum pokeballs and executing the sniping action is inverted. 

please, don't close the issue just because you can't respond it nicely 😞
