### ISSUE TITLE
Problem with remane

### ISSUE THREAD

**Issue by rigodonchu** [NECROBOTIO/NecroBot#5081]
When you first enable the rename pokemons feature, if u have many of them to rename, the bot does it at same time than any other actions (in my case while walking, getting pokestops and snipe).
That many actions cause a softban i can't evade.

### Expected Behavior
Bot should stop all other actions just after starting to keep renaming (and maybe transfers) up to date to avoid the ban.

### Actual Behavior
Refer to the problem.

### Your config.json
I guess the important fields are:

  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",

  "DelayBetweenPlayerActions": 500,

### Steps to Reproduce
Have maybe 100 or so pokemons not renamed, and enable the feature. It will end in a ban.

### Other Information
Version: 0.8.5
Windows Version: Windows7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
rename

**Comment by nfettinger** [comment]
Turn off sniping and you wont have an issue.
