### ISSUE TITLE
no useable pokestop in my area

### ISSUE THREAD

**Issue by DongWei0437** [NECROBOTIO/NecroBot#5083]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
farming

### Actual Behavior

no useable pokestop in your area.
### Your config.json

[config.json.zip](https://github.com/NECROBOTIO/NecroBot/files/413315/config.json.zip)

### Other Information
Version:0.8.5
Windows Version:window 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
catching and farming
https://cdn.discordapp.com/attachments/209274859488804866/213284093226516480/unknown.png

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by ubulem** [comment]
Have you even tried search before creating issue...?
https://github.com/NECROBOTIO/NecroBot/issues?utf8=%E2%9C%93&q=no%20usable%20pokestop

It's IP ban. Don't use more than one bot per one IP address
