### ISSUE TITLE
SoftBanned

### ISSUE THREAD

**Issue by kantankerousmind** [NECROBOTIO/NecroBot#5084]
### Expected Behavior
pokestop not being recognized appears that account is softban

### Actual Behavior
logs in but reports that no pokestop are nearby. Actual game no longer updates with nearby pokemon or shows pokestops

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by ruchern** [comment]
IP banned.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
