### ISSUE TITLE
PogoLocationFeeder (LocationServer) not working

### ISSUE THREAD

**Issue by jakesmurf** [NECROBOTIO/NecroBot#5085]
I hope this isn't a repost but I haven't seen this issue in a quick search.  

As of the latest version, my bot no longer pulls sniping coords from PogoLocationFeeder.  

I snooped the local network traffic and I'm not even seeing a request to 127.0.0.1:16969 being sent.  It seems that PogoLocationFeeder is working because A) It works with old versions of the bot and B) It prints coords etc.  

I tried reinstalling but I'm still not getting a connection, nor sniping any of the appropriate coords.

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here, including sniping. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
