### ISSUE TITLE
I have a problem HELP!!!!!

### ISSUE THREAD

**Issue by losmatanza** [NECROBOTIO/NecroBot#5087]
My necrobot doenst find any pokestop and any pokemon please help look. i try a lot of things and it doesnt work nothing hel please before it was working really good but now it doesnt work later of the last update of pokemon go 
![screenshot_1](https://cloud.githubusercontent.com/assets/20968511/17590851/b7d7e878-5fdb-11e6-97df-faf2a7325072.png)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Comment by m3tal** [comment]
I heve same plroblem...
I thought we wad banned or something .. :/

**Comment by kasabians** [comment]
And me

**Comment by losmatanza** [comment]
where i can find sopporter please
