### ISSUE TITLE
is the necrobot down again i am getting the error of no usable pokestops in your area 

### ISSUE THREAD

**Issue by baldmonkey1** [NECROBOTIO/NecroBot#5088]
[##]([url](url)) Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by janga11** [comment]
you just got ip banned... necrobot is working fine

**Comment by buettner123** [comment]
use discord for questions like this

**Comment by m3tal** [comment]
ok Will try with a proxy or VPN..

**Comment by baldmonkey1** [comment]
how did i get banned?
any specific reason?

**Comment by janga11** [comment]
idk try to restart router or use proxy

**Comment by smoothrunnings** [comment]
@baldmonkey1 You got banned, live with it. Wait 30 minutes to an hour and start playing again. Just remember you can only have 1 ID per IP. And trying not to fly around the map, I think they are starting to ban people for doing this. Set walking speed to 9km

**Comment by nfettinger** [comment]
This space is for code bugs and issues only. Please use Discord chat for further help.

**Comment by baldmonkey1** [comment]
okay bro i will try iwthin an hour hope it works and i use only 1 id per ip but i  change locations very soon

**Comment by m3tal** [comment]
JUST IP ban Change Ip and that work !!

**Comment by Pokemongobottttttt** [comment]
Can you run more bots with multiple computers in the same house? Or is it all linked to your internet IP

**Comment by baldmonkey1** [comment]
no i never used multiple bots my isp sucks if i change the ip or use vpn it resets automatically
