### ISSUE TITLE
SOFT BAN 

### ISSUE THREAD

**Issue by pkownsz** [NECROBOTIO/NecroBot#5090]
Why so  often i got SOFT BAN ?:D  walk speed 15km/h
![be pavadinimo](https://cloud.githubusercontent.com/assets/20967282/17591207/db3d1b1c-5fe5-11e6-9c2f-0c702cd69133.png)

**Comment by nfettinger** [comment]
This space is for code bugs and issues only. Please use Discord chat for further help.
