### ISSUE TITLE
[REQUEST] feature

### ISSUE THREAD

**Issue by jordileme** [NECROBOTIO/NecroBot#5091]
I'd like to see a feature which: lets say u filter a snorlax with specific moveset and iv and cp and everything, bot still catches the noob snorlaxes and then transfers them. What I'm thinking is something like this: IgnoreBelowIV: and IgnoreBelowCP:. In a way that the bot wont even bother if it's lower than our standards.

**Comment by nfettinger** [comment]
Duplicate issue
