### ISSUE TITLE
request add toggle remove soft ban on/off for sniping

### ISSUE THREAD

**Issue by aapikz** [NECROBOTIO/NecroBot#5092]
its really annoying when the bot starts to unban for 1/45 when the bot vist the pokestop for 2nd time... and particularly when you are auto sniping from discrod  and really miss alot of 1/10 pokemons because of annoying unban .. it would be great to add toggable option for sofan on/off (for sniping)

**Comment by nfettinger** [comment]
Set up your sniping correctly and you wont be softbanned.
This space is for code bugs and issues only. Please use Discord chat for further help.

**Comment by aapikz** [comment]
sure you wont have problem when theres 200+ pokestop .. but when youre living in 30-50 pokestop.. softban is really annoyig
