### ISSUE TITLE
Thought on unbanning

### ISSUE THREAD

**Issue by laquaces** [NECROBOTIO/NecroBot#5095]
![asd](https://cloud.githubusercontent.com/assets/20681555/17591525/2a711f46-6011-11e6-9467-9eea4ddc4629.png)

Softban? Yes, softban, i'm not asking "why am i softban" like those lazy ass never found some info.

This time, I wonder if we can adjust the bot "**to loot one more pokestop**" instead of sniping **immediately after spinning 45 times** becoz just like the photo has shown so that the bot will know if we have been unbanned yet after 45 spins. Actually it's becoz I think the continuous softban is due to sniping while still softbanned....

**Comment by nfettinger** [comment]
Set up your sniping correctly and it wont softban you. Several mods are having NO issues with sniping.
This space is for code bugs and issues only. Please use Discord chat for further help.

**Comment by laquaces** [comment]
@nfettinger 
- Never had I got help there in discord.
- Using config by default (changed to false in some getting sniping info stuff:
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.006,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": true,
  "SnipePokemonNotInPokedex": true,
- It's not issue of sniping.
- Never can I transmit my thought.
- I am not complaining about the softbans but wanna help improve the bot (bad in coding
