### ISSUE TITLE
Necrobot not running from yesterday

### ISSUE THREAD

**Issue by Gregtheo** [NECROBOTIO/NecroBot#5098]
Until yesterday necrobot was running perfect!! It catched for me some rare pokemons like snorlax,dratini,lapras etc but suddenly stoped working or better i run it and on the 1st pokestop stuck. i use this config http://pastebin.com/i7BqJ6qc and i tried to run it on version Necrobot 0.7.6 and on all updates. on this version Necrobot 0.7.6 it runs but it doesnt sniping. any ideas why it doesnt not sniping all these rare pokemon waiting me to catch them?

**Comment by PolarJunction** [comment]
You should post this in the Discord help chat instead, there will be people able to help you with your set up.

**Comment by TurntKFC** [comment]
download necrobot 8.5 for bug fixes etc...

**Comment by Muode** [comment]
"GetSniperInfoFromPokezz": true
to
"GetSniperInfoFromPokezz": false,

**Comment by Gregtheo** [comment]
i have these settings.. but necrobot 8.5 is still not working for me


2016-08-11 17:37 GMT+03:00 Muode <notifications@github.com>:

**Comment by jlutz24** [comment]
I think 8.5 is currently down.

**Comment by Gregtheo** [comment]
if it is up can you sent me a mail?

2016-08-11 17:41 GMT+03:00 jlutz24 <notifications@github.com>:

**Comment by ausscheider** [comment]
"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by Gregtheo** [comment]
on v8.5?

2016-08-11 17:57 GMT+03:00 ausscheider <notifications@github.com>:

**Comment by ausscheider** [comment]
yes

**Comment by Gregtheo** [comment]
let me try it


2016-08-11 18:01 GMT+03:00 ausscheider <notifications@github.com>:

**Comment by Gregtheo** [comment]
it stuck here http://prntscr.com/c4g0vg

2016-08-11 18:03 GMT+03:00 Greg Theo <grigoristeo@gmail.com>:

**Comment by jlutz24** [comment]
Mine gets stuck everytime I get to a pokestop

**Comment by Gregtheo** [comment]
what we do now?


2016-08-11 18:14 GMT+03:00 jlutz24 <notifications@github.com>:

**Comment by jlutz24** [comment]
no clue
