### ISSUE TITLE
Cant catch pokemon ?

### ISSUE THREAD

**Issue by psblackz** [NECROBOTIO/NecroBot#5101]
This is just farming pokestops and pokemons nothing....

**Comment by ausscheider** [comment]
set   "CatchPokemon": true,

**Comment by ausscheider** [comment]
set   "CatchPokemon": true,

**Comment by psblackz** [comment]
isnt that.. just snipe all coordenates and nothing.. back to farm again..

**Comment by nfettinger** [comment]
This is a configuration issue. Please use discord chat for additional help.

**Comment by ausscheider** [comment]
pokestops are ok?

**Comment by psblackz** [comment]
Yes

**Comment by ausscheider** [comment]
then i have no idea sorry
