### ISSUE TITLE
[REQUEST] [SUGGESTION] Auto update - Countdown for answer

### ISSUE THREAD

**Issue by 30er** [NECROBOTIO/NecroBot#5103]
Hi
is it possible that u add some kind of countdown/timeout for choosing Y/N when there is an update?

have some auto reboot scripts running... and bot gets stuck if there is an update...
i know i could disable updates ;) but normaly i want to keep them up-todate...
so some kind of 10-15sec timeout would be nice...
if user doesnt react... continue as normal

**Comment by cpanel10x** [comment]
you can set it to false before afk time

**Comment by nfettinger** [comment]
No, you should inspect your config EVERY time you update to prevent issues.

**Comment by 30er** [comment]
u didnt get the point... i dont want that it auto updates.... but it should continue with old version... without being stuck at Y/N for ever
