### ISSUE TITLE
No pokemon or pokestops in area IP ban fix?

### ISSUE THREAD

**Issue by Warnerbro1234** [NECROBOTIO/NecroBot#5107]
When will this get fixed, very annoying.. works for a bit then it says that.

**Comment by PolarJunction** [comment]
Are you trying to run more than one bot? To avoid bans you should use proxies.

**Comment by Tanzil420** [comment]
same problem here...it happens when i run 3/4 at a time

**Comment by Warnerbro1234** [comment]
how do I use proxies

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.
