### ISSUE TITLE
[Request] Possible to focus only on high cp iv lvl pokemons?

### ISSUE THREAD

**Issue by Bpanda9** [NECROBOTIO/NecroBot#5108]
hey, guys i was wondering if its possible to set the conf to snipe only high CP and LVL Pokemon. I been changing the  conf but i don't see any changes.

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.

**Comment by Pokemongobottttttt** [comment]
This may be possible but I cant confirm it. You can just raise your IV/CP standards so it gets rid of them if its not to your liking though.
