### ISSUE TITLE
Telegram not working? Why is there a field with TelegramPassword in Config?

### ISSUE THREAD

**Issue by infslash** [NECROBOTIO/NecroBot#5110]
My Telegram Bot doesn't respond.
What am I doing wrong? What am I supposed to do with the Password Value?

>   "UseTelegramAPI": true,
>   "TelegramAPIKey": "xxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx", // it's actually not xxx... :D
>   "TelegramPassword": "", // tried also with null and without ""

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.

**Comment by infslash** [comment]
Well why should I use support channel if nobody helps there?! It's actually a issue of developement!
