### ISSUE TITLE
[Question] How to put Nidoran M/W in config?

### ISSUE THREAD

**Issue by Zellerich** [NECROBOTIO/NecroBot#5111]
Does anybody know how to put both Nidorans into the config?

I tried:
 `"PokemonsToEvolve": [
 	"nidoran♀",
	"nidoran♂"	
],`

 `"PokemonsToEvolve": [
 	"nidoranf",
	"nidoranm"	
],`

 `"PokemonsToEvolve": [
 	"nidoranfemale",
	"nidoranmale"	
],`

but all three versions dont work and necrobot just crashes.

**Comment by golitsyn** [comment]
"nidoranMale",
      "nidoranFemale",

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.
