### ISSUE TITLE
Bot wont continue to work

### ISSUE THREAD

**Issue by Riku92** [NECROBOTIO/NecroBot#5112]
Everytime I start it it up, itll get one pokestop and just stop right there. Is there anything I can do to fix that?

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.

**Comment by ausscheider** [comment]
set  "GetSniperInfoFromPokezz": false,

**Comment by Riku92** [comment]
i am sorry, new to this

**Comment by ausscheider** [comment]
loog at your config 

you find this line:

  "GetSniperInfoFromPokezz": true,

please change to 

  "GetSniperInfoFromPokezz": false,
