### ISSUE TITLE
No useable pokestops

### ISSUE THREAD

**Issue by korkor1** [NECROBOTIO/NecroBot#5114]
No useable pokestops in your area, max distance too small?

**Comment by Caliboss** [comment]
your ipbanned.. try and go into your auth file, change one letter in your device name and save it.. run bot

i just did it and i got unbanned

**Comment by ausscheider** [comment]
change your IP

**Comment by Rick058** [comment]
@Caliboss That is not how IP bans works lol.
@korkor1 Change your IP, possible with a VPN or configure the proxy settings in auth.json
