### ISSUE TITLE
My bot keeps transferring all my pokemon

### ISSUE THREAD

**Issue by soaplicker** [NECROBOTIO/NecroBot#5116]
Why does my bot transfer all my pokemon, it never happened before..
It just sold my squirtle 600 cp and more...

**Comment by ausscheider** [comment]
set   "KeepMinDuplicatePokemon": 3,
or another number what you want

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.

**Comment by soaplicker** [comment]
when I open discord it says, it expired?
