### ISSUE TITLE
Log in Issues

### ISSUE THREAD

**Issue by Pyronetic** [NECROBOTIO/NecroBot#5119]
I don't seem to be able to log in despite being able to do so last night
http://prntscr.com/c4g8jh

I didn't change anything but can't seem to log in.
I reinstalled the release.zip and re-did log in details etc.
http://prntscr.com/c4g9q0
But still get that error of username and password not filled out

**Comment by CDAGaming** [comment]
Can You send your auth.json in Please

**Comment by nfettinger** [comment]
We cannot help you with this here. This space is for code development and bug reporting only. Please use our Discord #support chat channel.
