### ISSUE TITLE
Pokesniper bugged

### ISSUE THREAD

**Issue by DocNoob** [NECROBOTIO/NecroBot#5121]
First of all thanks for thisbot it really helped me a lot!

And as the issue ... Pokesniper no more works for me, I checked the web if the server is off or any other problem is there but nope.. there is no problem.

I tried reinstall , redownload , update and all that i can do . But from the last update it just doesn't work.

**Comment by Gregtheo** [comment]
if u find a solution can u email me on grigoristeo@gmail.com?

**Comment by nfettinger** [comment]
Issues not relating to a bug in the code will be closed. Please use Discord chat #support for help.

**Comment by ausscheider** [comment]
set   "GetSniperInfoFromPokezz": false,

**Comment by Gregtheo** [comment]
and from where it will snipe?

**Comment by ausscheider** [comment]
"GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,

**Comment by DocNoob** [comment]
Thanks bro it worked ..!! you are savior <3

**Comment by TomPK** [comment]
What, here dont worked :\ 

 "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,

![caralho](https://cloud.githubusercontent.com/assets/20949145/17596804/7a298408-5fc9-11e6-9f9f-74f968bc326c.png)

**Comment by Gregtheo** [comment]
you find solution?

2016-08-11 19:43 GMT+03:00 TomPK <notifications@github.com>:

**Comment by DocNoob** [comment]
@Tompk you need to put false for skiplagged
