### ISSUE TITLE
SOFTBAN

### ISSUE THREAD

**Issue by onceelace** [NECROBOTIO/NecroBot#5123]
[11:44:46] (SOFTBAN) Name: Pounding Rice INFO: Looting failed, possible softban. Unban in: 3/45

I always get this error.

And almost all of my Pokemon is transfered.

**Comment by ausscheider** [comment]
set     "KeepMinDuplicatePokemon": 4, 
or another number what you want

softban:
max. 1 bot per IP

**Comment by jesussson** [comment]
stop trying to login for like 15 mins to 20 mins or login your phone using your mobile network then close pokemon go app then try running software that usually works for me.
