### ISSUE TITLE
Last position feature

### ISSUE THREAD

**Issue by Rashk999** [NECROBOTIO/NecroBot#5125]
Can be added a feature which ask you after you start the bot to use your last position, when Im power leveling, or something Im changing config, have to restart the program to use new config and the bot start every time on setted position in config. for example 20 20 after some minutes are on 21 21 then i want to power lvl up, but i have to change settings and restart bot, can be here some question which ask me if i want to use last position, if yes bot will use it, if not bot will use default lat long position... hope you understand what i mean :)

**Comment by nfettinger** [comment]
Duplicate issue

**Comment by deduijk** [comment]
Duplicate of 3581
