### ISSUE TITLE
How to fix zh-TW being Garbled?

### ISSUE THREAD

**Issue by kyle12377** [NECROBOTIO/NecroBot#5126]
### Expected Behavior
words should be displayed as correct chinese character.

### Actual Behavior
but it turned out like this.....
I have changed file from zh_tw to zh-TW. still didn't work
http://imgur.com/a/fhdPm

{
  "TranslationStrings": [
    {
      "Key": "pokeball",
      "Value": "寶貝球"
    },
    {
      "Key": "greatPokeball",
      "Value": "高級球"
    },
    {
      "Key": "ultraPokeball",
      "Value": "超級球"
    },
    {
      "Key": "masterPokeball",
      "Value": "大師球"
    },
    {
      "Key": "wrongAuthType",
      "Value": "錯誤的認證資訊"
    },
    {
      "Key": "loginInvalid",
      "Value": "用戶憑證失效，登入失敗"

  "TranslationLanguageCode": "zh-TW",

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by nfettinger** [comment]
Duplicate issue
