### ISSUE TITLE
Feature request: Better Humanlike Walking

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#5128]
I had already submitted a case proposing better human like walking (#3597), but that case got closed with suggestion to use gpx pathing. Re opened this issue because gpx pathing doesn't solve the issue at hand: 

Currently the bot walks straight vectors from 1 pokestop to the next. 
Gpx pathing could solve the issue of the bot walking over water and through walls/houses, but not the use of straight and constant movement vectors.

**AT least a random variance on the vector needs to be implemented:**
- Speed up, slow down (A human doesn't walk at a constant speed.)
- Variances within the travelling vector (slight perpendicular movement on the vector, also random (but small amount)

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by deduijk** [comment]
WHAT CASE?. you closed my other case and search didn't turn up a case?

**Comment by ausscheider** [comment]
https://github.com/NECROBOTIO/NecroBot/pull/3766

**Comment by deduijk** [comment]
Thanks.
