### ISSUE TITLE
No pokestops in every location..again

### ISSUE THREAD

**Issue by Jordano3710** [NECROBOTIO/NecroBot#5133]
![image](https://cloud.githubusercontent.com/assets/20824860/17596209/40322f10-5fe8-11e6-85db-38d24dcf5745.png)
 Please help its just happend and is in every location

**Comment by iwantmyfile5** [comment]
Its an IP softban. Use only 1 bot per router that you can connect to. Even if you have multiple computers, you need a second router to run a second bot now. Pretty sure it was a Niantic update that caused this. You'll have to change your IP or wait a while to lift the softban.

**Comment by Jordano3710** [comment]
How long does it take to lift the ban?

**Comment by ausscheider** [comment]
take a new ip and you can start immediately
