### ISSUE TITLE
Sniping server offline, Skiplagged (HELP)

### ISSUE THREAD

**Issue by TomPK** [NECROBOTIO/NecroBot#5137]
I'm using version, 0.85

![caralho](https://cloud.githubusercontent.com/assets/20949145/17596433/b41e7242-5fc7-11e6-99d8-6aba1dd3f39c.png)

**Comment by nfettinger** [comment]
We cannot support 3rd party servers.

**Comment by TomPK** [comment]
and what i do?

**Comment by ausscheider** [comment]
"SnipeWithSkiplagged": false,
