### ISSUE TITLE
[REQUEST] Add option "skip pokestop"

### ISSUE THREAD

**Issue by vincent86830** [NECROBOTIO/NecroBot#5142]
Skip pokestop can slow down the time we advance.
This help us to stay in "low level" and also "UsePokemonSniperFilterOnly".
If this funtion will be added, that would be great.

**Comment by travisty357** [comment]
Yes, a much needed feature as many near the max level it would be nice to farm pokemon only and hit stops only for balls when the reach a defined level.

**Comment by CreativiTimothy** [comment]
Great Idea! I think a good way to implement it is:

SkipPokestops = true/false
SkipPokestopsIfAbovePokeballs = 30

**Comment by nfettinger** [comment]
Hitting Pokestops gives you XP regardless of your inventory. If you dont want to advance, dont use a bot

**Comment by CreativiTimothy** [comment]
@nfettinger We know. We want it to not spin Pokestops at all unless we have a minimum of 20-30 pokeballs or something
