### ISSUE TITLE
[Request]  Favour LocationFeeder over Snipesites

### ISSUE THREAD

**Issue by happysam5** [NECROBOTIO/NecroBot#5144]
add setting to priorities PogoLocationFeeder (now they have skiplagged verifcation) over snipe sites you have turned on.

currently it waits to long to check the <localhost> snipes and misses them!

thoughts?

**Comment by nfettinger** [comment]
Waiting too long misses them, waiting to short of a time gets you banned. This is a sniper configuration issue that does not belong here. Please use Discord chat.
