### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by jemadrid** [NECROBOTIO/NecroBot#5147]
Been trying to log in for the past few days but I get the following error.

Running version 0.8.5

http://jsonlint.com/
![loginfail](https://cloud.githubusercontent.com/assets/2494806/17597520/636444f8-5fb3-11e6-9793-9487bf9334a1.PNG)

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki
