### ISSUE TITLE
Fake NecroBot Facebook, website and Paypal ?

### ISSUE THREAD

**Issue by NZX-DeSiGN** [NECROBOTIO/NecroBot#5149]
Hello,

I've just found out a bot manager tool called "Go Manager" on a Facebook page named as your project NecroBot, a website and a Paypal page. The tool works fine, but I can not stop thinking  that it is possible that it is a keylogger, because I think it's not your Facebook page or website and  I haven't found the sources of the software.

Can confirm that they are impostors and the sofware may be a keylogger ?

Links :
https://www.facebook.com/necrobotsoftware/
http://necrobot.net/
http://necrobot.net/PayPal

I hope you can stop them (if they are impostors)

**Comment by Aneduna** [comment]
This is not the official website afaik. The original website should be http://necrobot.io/ but as it is linking to the github as download, it is not giving any malware. The Paypal might be shady tho.

**Comment by ruchern** [comment]
@NecronomiconCoding

**Comment by NZX-DeSiGN** [comment]
They steal your donations ! 
Here's the post of the "Go Manager" software I suspect to be a keylogger : https://www.facebook.com/necrobotsoftware/posts/317156135295575
