### ISSUE TITLE
Sniping error

### ISSUE THREAD

**Issue by SDMU** [NECROBOTIO/NecroBot#5155]
when i set  "UseSnipeLocationServer" to true , the bot only travels to the 1st pokestop and just stops . it does not do anything else . just stops and does not move to the next pokestop . when it set it back to false , only then does the bot move to the further pokestops .

[config.txt](https://github.com/NECROBOTIO/NecroBot/files/413810/config.txt)

**Comment by ausscheider** [comment]
set   "GetSniperInfoFromPokezz": false,

**Comment by SDMU** [comment]
It was working perfectly a few hours ago though .

**Comment by SDMU** [comment]
I'll try that and let you know .

**Comment by SDMU** [comment]
It worked ! Thanks a lot !

**Comment by SDMU** [comment]
Why was that causing an error ?

**Comment by ausscheider** [comment]
this can happen if the server from pokezz is down
