### ISSUE TITLE
softbans me forever when i start only 2 bots

### ISSUE THREAD

**Issue by MegaClinton** [NECROBOTIO/NecroBot#5158]

**Comment by MegaClinton** [comment]
It softbans me when i open up only 2 bots then when i close them out and start one it keeps saying that there's no pokestop at coordinates (im 100% sure there are)

**Comment by ausscheider** [comment]
1 bot = 1 IP

**Comment by Purmey** [comment]
This happens with me aswell. Niantic must be cracking down.

**Comment by MegaClinton** [comment]
so i can only start up one bot?

**Comment by Purmey** [comment]
Must be
I need to run multiple bots aswell but I might use a different bot for a different account..

**Comment by ausscheider** [comment]
yes @MegaClinton

**Comment by MegaClinton** [comment]
before all the updates came, i could start up 2 bots with no problems so how come why i cant anymore? any idea?

**Comment by Purmey** [comment]
Niantic API update most likely.

**Comment by Linewalker** [comment]
No Code-issue, please close.
As said: 1 bot = 1 IP, use Proxy for each instance.

**Comment by MegaClinton** [comment]
ahh ok

**Comment by Purmey** [comment]
How do I set up the Proxy?

**Comment by MegaClinton** [comment]
u go into ur auth folder

**Comment by Linewalker** [comment]
Discord -> Support.

**Comment by MegaClinton** [comment]
it still has the same problem even when i set up proxy

**Comment by Purmey** [comment]
Yeah and change use proxy etc..

**Comment by MegaClinton** [comment]
u have same problem?

**Comment by Purmey** [comment]
If you get softbanned, run a VPN like Private Tunnel and run 1 bot

**Comment by MegaClinton** [comment]
damn so now we can only run 1 bot?

**Comment by Purmey** [comment]
Seems so

**Comment by Purmey** [comment]
Yeah now the bot fixes my soft ban

**Comment by MegaClinton** [comment]
yes but the softban is forever for some reason

**Comment by Purmey** [comment]
Use PrivateTunnel

**Comment by Purmey** [comment]
The softban can be upto 12 hours

**Comment by MegaClinton** [comment]
ok thanks

**Comment by MegaClinton** [comment]
do i activate vpn when im done softbanned

**Comment by smoothrunnings** [comment]
@MegaClinton You need to get some computer skillz! If you are using a VPN service they will provide you with an IP address, providing the other Pokemon farmers haven't gotten that IP soft banned you should be OK. Connect to the VPN first, make sure you get a new IP address, see your VPN software, then launch the Nectro.exe app.

**Comment by MegaClinton** [comment]
okay
