### ISSUE TITLE
Won't Unban

### ISSUE THREAD

**Issue by VenusMods** [NECROBOTIO/NecroBot#5159]
I am using 1 bot and 1 bot only, and whenever I use the bot, I can log in, but It just passes over pokestops, not trying to un softban me. Why?

**Comment by ausscheider** [comment]
have you a log or your config?

**Comment by TomPK** [comment]
You need change your ip

**Comment by VenusMods** [comment]
I'm not ip banned since I am on a vpn each time i try.

**Comment by Linewalker** [comment]
No code, but config issue, please close. Try Proxy.

**Comment by VenusMods** [comment]
It fixed itself :/ but it happens sometimes

**Comment by sidneynxavier** [comment]
I have the same problem, and I'm not using the Same IP Adress.
This problem has began last night.
And Now, when I was trying to use the Bot I have the Message : No usable PokeStops found in your area. Is your maximum distance too small?", 
I Think that Niance has been change something in the servers.

**Comment by carlitogwapito** [comment]
I've encounter same problem. I've been running one bot only, but I still get soft banned. So, I tried changing the coords to somewhere near my place with pokestops. I don't know if this is a fix or what, but that's what I did. So far, it's running smoothly. If I go somewhere like 20km away from my current position, i'll get soft banned for 10-45 seconds then it'll be bypassed. I hope this helps.

**Comment by Purmey** [comment]
If the bot needs an update, update it. The bot is made to bypass non-ip soft bans so you should be good there. But it seems niantic have stepped their game up as I am getting softbanned more often.

**Comment by smoothrunnings** [comment]
Make sure the you are connecting your VPN again instead of leaving it connected. It's IP could be soft banned.

**Comment by ausscheider** [comment]
1 IP = 1 Bot

**Comment by immoempe** [comment]
VPN/Proxy are IPs too, If more people are using the same, they will IP ban the VPN/proxy too, so take that in consideration when using a proxy/vpn to bypass the IP ban
