### ISSUE TITLE
Unexpected behaviour with Move Filter

### ISSUE THREAD

**Issue by ShadowCX** [NECROBOTIO/NecroBot#5161]
### Expected Behavior

Keep all Snorlax according to the following rule:

CP>2200 OR IV>100.0 OR (Has Move "ZenHeadbuttFast" AND "HyperBeam")

### Actual Behavior

Erroneously transfers the following Pokemon:

Name: Snorlax
Lvl: 23
CP: 1954
IV: 66.70194696
Move1: ZenHeadbuttFast
Move2: HyperBeam

### Your config.json

    "Snorlax": {
      "KeepMinCp": 2200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        "zenHeadbuttFast",
        "hyperBeam"
      ],
      "KeepMinOperator": "or",
      "MovesOperator": "and"
    },

### Other Information
Version: 0.8.5
Windows Version: 10
What is affected: Pokemon Transfer Filter

Note: Move names are automatically changed to lower-case in the config.json after running NecroBot.

**Comment by Linewalker** [comment]
Whats not in here, do you have more than 1 snorlax? "KeepMinDuplicatePokemon": 1,

**Comment by ShadowCX** [comment]
Yes, I had 38 Snorlax before raising the CP limit from 1800 to 2200, which caused a bunch of them to be transfered correctly, and some of them incorrectly even though they had the required movesets. I just gave one of the erroneously transfered Snorlax as an example in this post, since it illustrates the point well enough I believe.

**Comment by actislav** [comment]
moves operator applied to keepmin section, between moves always OR. 
you can take version from source to have improved logic, there your request will work with multi list

**Comment by ruchern** [comment]
You probably had more than 1 Snorlax, and a Snorlax with a higher IV.

So this gets transferred.

**Comment by ShadowCX** [comment]
Oh I see, though the way the operators are applied does seem counter-intuitive at best imo. If I understand correctly you are saying that the logic has been improved in the meantime? Will it be available in the next release?

**Comment by ruchern** [comment]
@ShadowCX Just wait for the new release. You can pull the repo and build them yourself (if you know how).

**Comment by ShadowCX** [comment]
Nah, that's fine, if it's the next release I'm happy enough with it. 
Closing this issue now, thanks for the answers!
