### ISSUE TITLE
Bot doesn't find all pokemons that's really in inventory.

### ISSUE THREAD

**Issue by Lillecarl** [NECROBOTIO/NecroBot#5163]
https://github.com/NECROBOTIO/NecroBot/issues/4957

The GetPokemons function doesn't return all pokemons that exist in users Pokemon inventory.

Yes the previous issue was closed for unknown reason, but this is a real issue and should be dealt with.

I'm running wichever necro is the latest (from source) from day to day.

@nfettinger Don't close issues until you know what they're about, it has negative impact on this opensource thing, specially the community part.

Cheers

**Comment by Linewalker** [comment]
This took a little time to know, what you want. The "Issue" is on Line 518 in Inventory.cs. The Counter is only refreshed after 3 retries.

**Comment by Lillecarl** [comment]
@Linewalker The issue is very real, because even after making a manual refresh function and calling it the returned list isn't complete with all pokemons from Inventory.

**Comment by nfettinger** [comment]
GetPokemons returns what the server sends it. Your issue sounds like it is with the RocketAPI, and not with Necrobot

**Comment by Lillecarl** [comment]
So I should report it on the rocket API fork that you're also a developer
on?
Done that already, but apparently my issue still is a non issue and all
you're trying to do is find excuses to close and forget it.

**Comment by Lillecarl** [comment]
@nfettinger As a dev, when closing an issue that actually happens you might want to direct me where i should report it instead, or if i'm missing any data that would be valueable for this report to get the recognition it deserves.
