### ISSUE TITLE
Settings Reverting to old version? 

### ISSUE THREAD

**Issue by u189961** [NECROBOTIO/NecroBot#5165]
I tried searching everywhere and cannot find any information so I'm hoping someone could help. I had Necrobot set up at my work computer and was working fine until the API change. After the fix went out, I still can't get it to work (works perfectly fine at home). Here is the weird issue, I download the newest version and run the set up however the settings keep reverting back to the older version and I get the non usable pokestop error (due to old config settings it keeps reverting to. I try to go in and add the updated setting, hit save and restart the bot but it will change the settings to older version. 

here is what is keeps reverting to, I partially copied and pasted:

{
  "AmountOfPokemonToDisplayOnStart": 60,
  "AutoUpdate": true,
  "DefaultAltitude": 0.0,
  "DefaultLatitude": 33.762886,
  "DefaultLongitude": -118.195869,
  "DelayBetweenPokemonCatch": 2000,
  "DelayBetweenPlayerActions": 5000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseEggIncubators": true,
  "DumpPokemonStats": false,
  "GpxFile": "GPXPath.GPX",
  "UseGpxPathing": false,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxTravelDistanceInMeters": 1000,
  "KeepMinCp": 1250,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 85.0,
  "KeepPokemonsThatCanEvolve": false,
  "PrioritizeIvOverCp": true,
  "RenameAboveIv": false,
  "RenameTemplate": "{0}_{1}",
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UsePokemonToNotCatchFilter": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "SnipeAtPokestops": false,
  "ItemRecycleFilter": [

and the below is what I'm trying to paste and save to make it work but it keeps changing to the above:

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 60,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 33.762886,
  "DefaultLongitude": -118.195869,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 85.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": true,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{0}_{1}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 700,
  "TotalAmountOfPotionsToKeep": 150,
  "TotalAmountOfRevivesToKeep": 50,
  "TotalAmountOfBerriesToKeep": 100,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [

Another thing I noticed is that the default account info shows as below, which is also the outdated info:

{
  "AuthType": "google",
  "GoogleRefreshToken": null,
  "PtcUsername": null,
  "PtcPassword": null,
  "GoogleUsername": null,
  "GooglePassword": null
}

I then paste the correct new info, save and it doesn't revert life the settings:

{
  "AuthType": "google",
  "GoogleUsername": "login",
  "GooglePassword": "password",
  "PtcUsername": null,
  "PtcPassword": null,
  "UseProxy": false,
  "UseProxyHost": null,
  "UseProxyPort": null,
  "UseProxyAuthentication": false,
  "UseProxyUsername": null,
  "UseProxyPassword": null,
  "DevicePackageName": "nexus-6p",
  "DeviceId": "cce791d165ab9f7a",
  "AndroidBoardName": "angler",
  "AndroidBootloader": "angler-03.52",
  "DeviceBrand": "google",
  "DeviceModel": "Nexus 6P",
  "DeviceModelIdentifier": "angler",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "Huawei",
  "HardwareModel": "Nexus 6P",
  "FirmwareBrand": "angler",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "google/angler/angler:6.0.1/MTC19X/2960136:user/release-keys"
}

Any ideas why this could be happening?

**Comment by Linewalker** [comment]
No code issue, Discord -> #Support thank you. Please close.
