### ISSUE TITLE
Bug: Pokestop not found in central park

### ISSUE THREAD

**Issue by Lofifr** [NECROBOTIO/NecroBot#5167]
Hey,
I publish my message after few days trying to bot.
I'm botting in NYC near central park (viva basic settings)
But most of time my bot can not find any pokestop (Cf. pic attached)
![capture](https://cloud.githubusercontent.com/assets/20974818/17598711/0c79020c-5ffc-11e6-8e3e-e779f000098b.PNG)
I though that it was linked that i putted too much account in necrobot with the same IP. I tried to put 1 or 2 acc, but there is still some problem of pokestop... If anyone has answer pls inform me.
I'm sorry if this topic already exist but i did'nt find it...
You can check also my config there...
Thanks to read my topic.
Best regards
Lofifr
[config2.txt](https://github.com/NECROBOTIO/NecroBot/files/413845/config2.txt)

**Comment by VCorleone** [comment]
i have the same problem

**Comment by Aneduna** [comment]
Duplicate + Config Issue

Discuss in Discord or read other issues

**Comment by ausscheider** [comment]
1 IP = 1 Bot

change your IP and it works

**Comment by marcomarvelous** [comment]
You're IP banned, have to wait until it subsides and only use 1 bot per IP

**Comment by VCorleone** [comment]
I only have one bot and I have the same problem. But sometimes I changed my config. Could it be the reason for softban?

**Comment by Lofifr** [comment]
Ok thanks guys.
How to use another ip?
I need an IP dynamic, or should i use some proxy or it will say same thing? 
Thx for fast answer.

**Comment by smoothrunnings** [comment]
Use VPN.

**Comment by VCorleone** [comment]
I only have one bot and I have the same problem. But sometimes I changed my config. Could it be the reason for the softban?

**Comment by KillerOffers** [comment]
The FAST way is to REBOOT your Internet Modem, wait a few minutes till it restarts, then try your BOT again.  Works Great if your on Cable Internet vs DSL.
You can only have 1 BOT running through your IP Address.
Try it and let me know if it worked for you!

**Comment by KillerOffers** [comment]
You can change specs in the CONFIG file while running the BOT by Control S or SAVE.
Made easy to tweak your BOT.

**Comment by Lofifr** [comment]
So according to you i can run one acc, then change my IP config via my modem, and run another one?

**Comment by immoempe** [comment]
No Lofifr: he said change your IP to avoid the IP what is banned and keep playing. You can run 1 bot per IP only

**Comment by KillerOffers** [comment]
You'll need a VPN Service to have another IP ADDRESS...

**Comment by Lofifr** [comment]
F... ok i'll suscribe to a vpn service. Thx guys.
Do you know a good one, stable and cheap, (i don't need a good connexion just enough to bot)

**Comment by KillerOffers** [comment]
REBOOT MODEM - Unplug Power Cord then Restart it works great to change IP Address.

**Comment by braudy1100** [comment]
I tried using VPN but i am still banned ..
