### ISSUE TITLE
[CONFIG ISSUE] transfer All Pokemon From smaller CP

### ISSUE THREAD

**Issue by twensever** [NECROBOTIO/NecroBot#5168]
please check code for "pokemontransfer" maybe there wrong 
I just run bot and start with transfer all my pokemon from smaller CP

![1](https://cloud.githubusercontent.com/assets/12656309/17598920/f22c37a4-6026-11e6-8ef9-f458c39a9861.png)

maybe any one can fix this problem ?

**Comment by Aneduna** [comment]
Urgent are Crashes.
This is not urgent. This is a Config Issue.

**Comment by ausscheider** [comment]
set   "KeepMinDuplicatePokemon": 4,
or another number what you want

**Comment by Aneduna** [comment]
Nice that you changed the title. But config issues are discussed on discord not on Github

**Comment by twensever** [comment]
sorry I have no duplicate pokemon, but bot still transferred All my pokemon (?)

**Comment by ausscheider** [comment]
look at your config
you have this?
 "KeepMinDuplicatePokemon": 0,

when you have this, then transfer all pokemon

also you set on 1,2,3,4 or what you want

**Comment by twensever** [comment]
okay thanks miss it :(
