### ISSUE TITLE
Help or suggestion

### ISSUE THREAD

**Issue by lFeeeeelipe** [NECROBOTIO/NecroBot#5169]
I would like to know if you like or you can add the option of capturtar via snipers Pokemon that I still have in my pokedex. If you already have this option, please would like to publish here the setting for this? (I'm sorry for poor English) Thank you.

**Comment by yonrin** [comment]
are you looking for a way to snipe ONLY pokemons that are ALREADY in your pokedex?

**Comment by Ferdi342** [comment]
You can create a custom list to snipe only the pokemon you want

**Comment by lFeeeeelipe** [comment]
I would pick those who have not.
But some do not have in my city, it has some way to get them?

**Comment by Linewalker** [comment]
https://discord.gg/VXKxNFr -> #Support, Please close, no code issue.
