### ISSUE TITLE
[feature request] detailed TotalAmountOfPokeballsToKeep?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [NECROBOTIO/NecroBot#5170]
I feel sad when recycling takes ultra balls and master balls away, no matter how high I set `TotalAmountOfPokeballsToKeep`.

Maybe add options to never recycle great & ulta pokeballs? This way normal pokeballs can be prioritized when recycling and we'll have shit ton of greatballs and ultraballs when catching pokemon.

![image](https://cloud.githubusercontent.com/assets/159209/17599313/55a6a4a0-5fb3-11e6-9915-8f82a71234e2.png)

In brief, if there are normal pokeballs, don't recycle better ones.

**Comment by ausscheider** [comment]
read your config, you can set to what you want

  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,

**Comment by ahmetalpbalkan** [comment]
@ausscheider no matter what I set `TotalAmountOfPokeballsToKeep` it recycles great/ultra balls. I think when it has normal pokeballs it should prioritize recycling them, not the premium ones. You're not reading what I typed above.

**Comment by ausscheider** [comment]
in a older version it was so, you can exactly set the number of balls.
but i have see, in the new version is this not.

**Comment by Linewalker** [comment]
The bot prioritize balls, keeping Ultra and great balls and recycles the "smaller" balls for space for the better ones. You can set the amount of Pokeballs in the config.

**Comment by ahmetalpbalkan** [comment]
@Linewalker why is nobody reading what I posted above?

My great/ultra balls are recycled when there are still normal balls. I'm saying this is not good.

**Comment by CreativiTimothy** [comment]
I haven't had this problem yet since my bag hasn't been full, but I think this is great because it should priotize keeping great and ultra balls while discarding pokeballs as the first solution to cleaning up the bag.

**Comment by nfettinger** [comment]
This is not reproducible on our end. Make sure you are using the lastest software.

**Comment by ahmetalpbalkan** [comment]
@nfettinger I am but anyway...
