### ISSUE TITLE
Bot stops working at Pokestop! 

### ISSUE THREAD

**Issue by 123top** [NECROBOTIO/NecroBot#5171]
The bot stops at a Pokestop. It's not crashing but nothing happens after the visit of a Pokestop. Even after restart same issue. It just doesn't move. Someone else who can help me solve this issue?

**Comment by ausscheider** [comment]
set   "GetSniperInfoFromPokezz": false,

**Comment by Linewalker** [comment]
Yes. Please close.

**Comment by KillerOffers** [comment]
Change it in the CONFIG FILE

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki
