### ISSUE TITLE
[IDEA] for unban

### ISSUE THREAD

**Issue by GrumpyOet** [NECROBOTIO/NecroBot#5172]
Use Quickspin for unban (it unban ip bans to (when i used it))

**Comment by braudy1100** [comment]
what is quickspin?

**Comment by immoempe** [comment]
softban and IP ban are different things, softban -> you can see pokestops and pokemon in your map, IP ban you can't see anything in the map (until you can change your IP of course), so how are you use quickspin if you can't see/use pokestops?

**Comment by GrumpyOet** [comment]
i don't know i look on my pokemon go and i don't saw any pokemon or pokestop which i normaly see but when i used quickspin 10 seconds later i was unbanned
