### ISSUE TITLE
WHAT IS THAT AND WHAT SHOULD  I DO?? 

### ISSUE THREAD

**Issue by pkownsz** [NECROBOTIO/NecroBot#5173]
WHAT IS THAT??? 
![image](https://cloud.githubusercontent.com/assets/20967282/17599481/f3ba3504-6007-11e6-8635-a2fb85f21971.png)

**Comment by VenusMods** [comment]
Restart and try again

**Comment by pkownsz** [comment]
@VenusMods  i did it 1000x time..

**Comment by KillerOffers** [comment]
You have 2 Step Authorization on your Google Acct.

**Comment by pkownsz** [comment]
i got codes but i dont know where i should write it...

**Comment by proinw555** [comment]
you too

**Comment by proinw555** [comment]
i iwant how to

**Comment by VenusMods** [comment]
Same problem, and no i dont i have 2 step on.

**Comment by pkownsz** [comment]
@VenusMods   i just reinstall program and write in google " google two factor authentication turn off" and i just turned off and works fine!

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by haroendzt** [comment]
Just  login to your google account then log out, restart the bot. its work,
sorry 4 my bad english :3
