### ISSUE TITLE
How to change my language and location?

### ISSUE THREAD

**Issue by james88498** [NECROBOTIO/NecroBot#5175]
hi there! im a taiwanese 
i got 2 questions here....
I'm wondering that what is the code to change into chinese 

and how should i change the location to taiwan??

**Comment by Linewalker** [comment]
There's no translation for "cn" right now. use "en" or PR a translation for cn.
#Config-Issue

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki
