### ISSUE TITLE
[REQUEST] More Recycle Options

### ISSUE THREAD

**Issue by VenusMods** [NECROBOTIO/NecroBot#5176]
I think there should be the option to recycle the types of items rather than the general thing. Cause right now you can choose to recycle how many pokeballs or revives, but there should be an option to recycle and keep the individual items like a great ball, or ultra ball, or max revive, because I like to have no regular revives and keep all max revives.

**Comment by Gandaflux** [comment]
You can set all items limits in ItemRecycleFilter.

**Comment by nfettinger** [comment]
It is always better to keep the BETTER balls and potions, which is what the logic does.
