### ISSUE TITLE
Poke Stops not found 

### ISSUE THREAD

**Issue by sugarsparkz** [NECROBOTIO/NecroBot#5180]
error during bot process. poke stops not found, search area to small, checked configs and they are correct. 

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by ausscheider** [comment]
change your IP
and run again

1 IP = 1 Bot
