### ISSUE TITLE
new to Necro, a little help please

### ISSUE THREAD

**Issue by OfficialValor** [NECROBOTIO/NecroBot#5182]
so i downloaded all 3 zip files, and i see everyone talking about changing their jason file. where can i find my jason.config? ive opened every folder and i have not found it. i would greatly appreciate it

**Comment by nfettinger** [comment]
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by sugarsparkz** [comment]
discord is the forum for this read the wiki guide

**Comment by ausscheider** [comment]
release.zip
unpack
start necrobot

after the setup 
open release folder
config folder
here you can find auth and config file

**Comment by OfficialValor** [comment]
thanks for the help!
