### ISSUE TITLE
my google account cant produce app specific pwrds

### ISSUE THREAD

**Issue by cindynico** [NECROBOTIO/NecroBot#5183]
Whenever I try to log into my account it gets stuck at the error code (error) "as you have google 2 step authentication enabled, you will need to insert an app specific password into the auth.json"

"opening google app password. Please make a new app password (use other as device).

Following those directions do not work however, in the older versions it had no problem logging me into both the udel.edu login and the university login. 

I do not have it turned on, on my google account and it doesnt seem i even can seeing i did all the steps i could find in forums and my google account sais i do not have the right account t create an app pw.... Is there another way to skip this and run it anyway?

ty

**Comment by proinw555** [comment]
wait too

**Comment by cindynico** [comment]
wait too?

**Comment by ruchern** [comment]
Dude, this is not a Google helpdesk.

**Comment by FirstDestro** [comment]
@ruchern is right.
Please see the possible reason below and close.

This happend to me when i used a proxy or vpn, google detects that you are logging in to a different ip from another country and blocks the login.

If that is the case, remove proxy or vpn, and log in with you recent/country ip.
Wait 10 min, If there is a possible softban, Necrobot will bypass.
And running more than 2 bots causes softbans, so run only one.

**Comment by cindynico** [comment]
i know DUDE this is info for my necrobot. i do not have the 2 auth so why does it sais that i have it anbaled when i have not? DUDE

**Comment by cindynico** [comment]
enabled*

**Comment by ruchern** [comment]
@cindynico Probably VPN/Proxy issue. Google detects location to verify if you are the owner of the account while logging in.

**Comment by nfettinger** [comment]
This is not a problem with Necrobot.
