### ISSUE TITLE
Keep Getting IP Banned

### ISSUE THREAD

**Issue by VasTShadowZ** [NECROBOTIO/NecroBot#5184]
HelP

**Comment by Ceranimo** [comment]
1 IP + 2 Bots = Ban
I'm getting banned after 10 mins every time when use 2 bots.

**Comment by Linewalker** [comment]
Please Close.

**Comment by ChrizDoe** [comment]
is PogoLocationFeeder considered a bot? im only running this and one instance of Necrobot but i keep getting softbanned and necrobot cant unban me

**Comment by ruchern** [comment]
@ChrizDoe No, it uses a port to connect to the bot.

**Comment by CreativiTimothy** [comment]
If yuo're running another account on your phone, you will get banned. Doesn't matter if you're a bot or not -- you can only play one account per IP, even if you have brothers and sisters I think

**Comment by Linewalker** [comment]
No code issue, use a proxy. For help ->  https://discord.gg/VXKxNFr #Support

**Comment by ChrizDoe** [comment]
@ruchern no im just using one account. i think my ISP is bundling a lot of people behind the same ip, that would explain it -.-
