### ISSUE TITLE
Status info

### ISSUE THREAD

**Issue by smoothrunnings** [NECROBOTIO/NecroBot#5186]
I noticed when I am farming with my PTC account that I get frequent stat inf on how many which balls and how many I have, berries, etc. When I use my Google account to farm I don't see any of those stats. Is this a bug or is this info only available on the PTC accounts? 

Sorry the Discord site doesn't work on my machines. I guess my cisco firesight doesn't like it. :(

**Comment by Linewalker** [comment]
The stats are shown if you cant loot anymore or automaticly after some time.

**Comment by nfettinger** [comment]
Probably IP banned

**Comment by smoothrunnings** [comment]
@nfettinger are you a noob? Geezus! It's not IP banned otherwise I wouldn't be catching pokemon.. lol
