### ISSUE TITLE
Keeps saying no usable pokestops is your area found

### ISSUE THREAD

**Issue by sandor111** [NECROBOTIO/NecroBot#5187]
Keeps saying no usable pokestops is your area found.
I already enabled a vpn or used a working proxy tested antoher account but still not working

**Comment by nfettinger** [comment]
Use Discord for help.
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by sandor111** [comment]
If i use discord it says the invite is unavaileble

**Comment by ausscheider** [comment]
change your ip
some free proxy works, some not
niantiv know the proxys and ban someone

**Comment by hrrywsh** [comment]
same :-1: :
