### ISSUE TITLE
No Pokestops WITHOUT Soft Ban

### ISSUE THREAD

**Issue by OoDex** [NECROBOTIO/NecroBot#5190]
Since a couple hours my Bot says he can't find any PokeStops to use for, so I thought I got softbanned.
Checked in with Bluestacks - no SoftBan, I can use any PokeStop around me. 
The only thing that "changed" for my eyes is everytime I open it it says "Download update" and I got a Release.zip next to the Release-Folder. 
I rewrote the Coordinates for Central Park, set MaxTravelDistance to 2k instead of 1k, but it stays the same. Anyone got an idea?

**Comment by nfettinger** [comment]
Not a development issue. Go to Discord.
Maybe an IP ban.

**Comment by ausscheider** [comment]
you need a new IP

remember 1 Bot = 1 IP
