### ISSUE TITLE
sniper often miss out existing pokemon

### ISSUE THREAD

**Issue by kennedyyiu** [NECROBOTIO/NecroBot#5192]
the sniper misses out existing pokemons most of the time
it said DID NOT FIND A POKEMON WITHIN THE LOCATION
but after I used pokemonsniper to snipe it, it was actually there
is it due to the 10 sec request response delay or the coding?

  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": true,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 500,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 100.0,
  "EvolveAllPokemonAboveIv": true,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 10,
  "KeepMinIvPercentage": 98.0,
  "KeepMinLvl": 1,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 2000,
  "UseBerriesMinIv": 95.0,
  "UseBerriesBelowCatchProbability": 0.08,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 1000,
  "SnipingScanOffset": 0.01,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by nfettinger** [comment]
Probably due to the delay, but this is not a code bug but a configuration issue.

**Comment by ruchern** [comment]
There could be fake locations or the pokemon time expired.
