### ISSUE TITLE
[SUGGESTION] "Botbreak"

### ISSUE THREAD

**Issue by temel38** [NECROBOTIO/NecroBot#5193]
I came up with an idea to make the bot more human.
because no person can play for 24/7 a day :DD

adding breaks in config, so for example, the bot stops/signs out for every 30 minutes, and after that it restarts again.

"SetBotBreak" True/False
"SetTimerBotBreak" (milliseconds)

**Comment by ruchern** [comment]
You can choose to manually restart the bot yourself.

**Comment by temel38** [comment]
@ruchern i cant see any option to set a break?

**Comment by nfettinger** [comment]
Duplicate issue
