### ISSUE TITLE
Not transfering "KeepMinIvPercentage" correctly...

### ISSUE THREAD

**Issue by DieHoe** [NECROBOTIO/NecroBot#5194]
I set my Bot to 

"KeepMinIvPercentage": 100.0,

but hes not transfering pokemon between 90% and 100% IV
For e.g my Flareon with 97.61% IV

WHY?

**Comment by ruchern** [comment]
Check PokemonTransferFilters.

**Comment by temel38** [comment]
@ruchern i was just gonna say the same :)

**Comment by nfettinger** [comment]
Known issue, Duplicate. Get latest source code.
