### ISSUE TITLE
[Feature Request] Highlight console message for catchsuccess event meeting 'keepmin' values

### ISSUE THREAD

**Issue by jgwallace3** [NECROBOTIO/NecroBot#5195]
Please highlight caught pokemon that exceed the keepmin values like keepminiv, keepmincp, etc.

This would help them stand out from the more mundane cp 20 pidgey captures.

**Comment by nfettinger** [comment]
Duplicate suggestion.

**Comment by jgwallace3** [comment]
Duplicate of what issue #?

**Comment by jgwallace3** [comment]
Ok, found this: "[REQUEST] Different font color when an high IV-CP pokemon is found #3685". 
I'll assume that'll do what I want.
