### ISSUE TITLE
Start the bot?

### ISSUE THREAD

**Issue by PCKGOHCKTEAM** [NECROBOTIO/NecroBot#5197]
How to Start the Bot?

Prefer in German please

THY TO ALL!

Have a nice day!

**Comment by nfettinger** [comment]
Maybe your parents can help you. Or maybe you can read the manual.
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by ausscheider** [comment]
Was genau willst Du wissen? Nur wie man den Bot startet oder mehr?
