### ISSUE TITLE
Unclear behavior of Transferfilter

### ISSUE THREAD

**Issue by Scarkritter** [NECROBOTIO/NecroBot#5200]
Hey,

I want the Transferfilter to only keep Pokemons, which have an IV over 95% and the given moveset, which means i don't care about the CP of the Pokemon at all.

### Expected Behavior

As an example I want a Jynx with an IV >= 95% and the moves frostBreathFast and psyshock and the bot should keep up to 3 of them. Everything else should be send straight away (I set "TransferWeakPokemon": true,).

### Actual Behavior

It keeps a Jynx with a good IV but with the wrong move set. In this case poundFast and psyshock.

### Your config.json

I think the mistake is somewhere here:

    "Jynx": {
      "KeepMinCp": 0,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 2,
      "Moves": [
        "frostBreathFast",
        "psyshock"
      ],
      "KeepMinOperator": "and",
      "MovesOperator": "and"
    },

Here a complete copy: http://pastebin.com/pvZhJG5j

### Other Information

Version:  8.5.0
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): transfer

**Comment by nfettinger** [comment]
This is not the place for configuration help.
https://github.com/NECROBOTIO/NecroBot/wiki

**Comment by Scarkritter** [comment]
The thing is the documentation relating to this point is not compelete that is why I needed to ask here. The documentation never talks about the move filter.
