### ISSUE TITLE
[request] Can u create pokemon "value" calculator ?

### ISSUE THREAD

**Issue by muxahuk** [NECROBOTIO/NecroBot#5201]
Hello, Currently as i understand u can eather keep pokemons with hight CP or IV.
I'm asking u to make 3-rd option - wich will be CP * IV.

So, for ex.  i have 2 pokemons. 1-st CP is 600 and IV is 62.5% and 2-nd CP is 500 and IV 80%.
So doing small calculation we could calculate pokemon "value".
For 1-st pok. it would be 600 * 62.5% = 393,
for 2-nd pok. - 500 * 80% = 400

So we keep 2-nd pok.

Could these be implemented ?

**Comment by nfettinger** [comment]
Not worth the effort. IV doesnt change, and CP is a useless factor when you have the Pokemon level to use.

**Comment by muxahuk** [comment]
then mb. IV * LVL  ?
