### ISSUE TITLE
Add Linux Mono/Wine Support

### ISSUE THREAD

**Issue by SaubereSacheLP** [NECROBOTIO/NecroBot#5203]
Hi, could you please add Liniux Support? My PC OS is Linux and I would like to run it on my Server... But mono dont works and Wine too...
If you have any solution to fix it please tell me!

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by SaubereSacheLP** [comment]
Please reopen, the second issue is sovled, but dont works on me

**Comment by SaubereSacheLP** [comment]
Error code:

sauberesachelp@SaubereSache ~/Schreibtisch/Const $ wine NecroBot.exe 
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"configSections" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"sectionGroup" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"section" in state 3
fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5.2" not implemented
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"runtime" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyBinding" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"dependentAssembly" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"assemblyIdentity" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"bindingRedirect" in state 3
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"connectionStrings" in state 1
fixme:mscoree:ConfigFileHandler_startElement Unknown element L"add" in state 3
fixme:mscoree:CLRMetaHost_GetRuntime Unrecognized version L"v4.0"

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'PoGo.NecroBot.Logic, Version=0.8.5.0, Culture=neutral, PublicKeyToken=null'
