### ISSUE TITLE
[IDEA] Pokeball configuration for individual pokemon

### ISSUE THREAD

**Issue by Gondost** [NECROBOTIO/NecroBot#5209]
The PokemonToTransfer section would be the idea place for this from a usability standpoint, but might not be the right place from a code standpoint.

Example: Always use Ultra Balls on all Snorlax
Example: Never use more than a Pokeball on a Pidge*.
Example: Use as many Ultra Balls as you have until encounter ends
Example: Use a maximum of 3 Pokeballs on a Rattata

MaxBalls could be a simple number.

Pokeballs to use might be best implemented like the Moves section.

Example:
`      "Balls": ["UltraBall","GreatBall"],`
`      "Balls": ["PokeBall"],`

**Comment by nfettinger** [comment]
You can set your config up to meet these requirements as is. This adds complexity so that the users who are lazy can still get by.

**Comment by Gondost** [comment]
@nfettinger how is this possible now?  You can't go by IV or CP to differentiate between a L27 Paras and a L2 Snorlax, unless I'm completely missing something.
