### ISSUE TITLE
problem to snipe pokemons

### ISSUE THREAD

**Issue by NicoPr0** [NECROBOTIO/NecroBot#5210]
### Expected Behavior
catch pokemons

### Actual Behavior
http://prnt.sc/c4k8iy
(the red message means "one or more errors occured")

### Your config.json

your config here
http://pastebin.com/q817B5Ae

### Steps to Reproduce
sometimes the bot behaves like this. it snipes pokemons correctly for 3-5 minutes then it starts doing like this until i restart it (sometimes even the restart doesnt work)

### Other Information
Version: 0.8.5
Windows Version: win 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): catch

**Comment by nfettinger** [comment]
Issues regarding pokemon sniping are due to external sources, or configuration errors, This is not a bug in the code. Please use Discord for discussion and help.

**Comment by ruchern** [comment]
Not NecroBot related.
