### ISSUE TITLE
PokemonsTransferFilter NOT WORKING!

### ISSUE THREAD

**Issue by KBLOSO** [NECROBOTIO/NecroBot#5211]
I have the following config:

"KeepMinCp": 1800,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,

...
"PokemonsTransferFilter": {
"Aerodactyl": {
      "KeepMinCp": 1700,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
}

I have a lot of 'Aerodactyl that should be transfered. If i change the gloabal variables this doesnt respect TransferFilter variables!!
Ex.: 553 cp, 95 iv
94 cp, 99 iv

How can i achieve that?? HELP ME PLXXX

**Comment by ruchern** [comment]
"KeepMinOperator": "and"

Your MinCp is 1700, MinIV is 80.0

553 cp, 95iv did not meet requirement.

**Comment by wilsondgonzales** [comment]
your filter for aero is set to KeepMinOperator": "and"

**Comment by nfettinger** [comment]
This is not the place for configuration issues. Unless you can pinpoint a bug in the code, please use Discord chat for discussion.

**Comment by KBLOSO** [comment]
I changed to 'or' but still not working.
I think its a bug.
Im telling that i want to keep only aero with 1700 min CP AND 80 IV.
Why it not transfer 553cp aero??
