### ISSUE TITLE
Problem with the Sniping

### ISSUE THREAD

**Issue by Impossibol** [NECROBOTIO/NecroBot#5213]
Hello!
I've a big problem with the Last Version of NecroBOT (0.8.5)

When i set "true" the "UseSnipeLocationServer", my bot doesn't work, it goes only in a Pockestop and after it doesn't run anywhere.
Screen: http://prntscr.com/c4kf5e

My config: http://pastebin.com/TG3ShW74

Thanks

**Comment by nfettinger** [comment]
Use Discord for help.

**Comment by Impossibol** [comment]
What is Discord? xD

**Comment by ausscheider** [comment]
set   "GetSniperInfoFromPokezz": false,
