### ISSUE TITLE
[Feature Request] 'Sleep' process when message shows "...Unban in: 45/45" and/or "No usable Pokestops found..."

### ISSUE THREAD

**Issue by gangliadrawn** [NECROBOTIO/NecroBot#5216]
It would be nice if we can put Necrobot to sleep if the message:
"Looting failed, possible softban. Unban in 45/45" or 
"No usable Pokestops found in your area. Is your maximum distance too small?" shows up consecutively. 

And then, wake it up again, maybe after 1.5 hours.
I noticed that if these messages shows up, I close it, and open it again after about 1.5 hours.
It becomes okay again.

**Comment by nfettinger** [comment]
Duplicate issue.
