### ISSUE TITLE
Rename Pokemon does not respect delay between actions

### ISSUE THREAD

**Issue by r-pearce** [NECROBOTIO/NecroBot#5218]
### Expected Behavior
IV-based Renaming Pokemon action would be separated at least by DelayBetweenPlayerActions value, if not a new config delay value when there are a lot of Pokemon to be renamed. (Renaming Pokemon would be expected to take much more time on the UI than other actions do.)

### Actual Behavior
2-3 Pokemon per second are renamed, which is very unrealistic.

### Steps to Reproduce
1. Have several Pokemon above the rename IV threshold.
2. Log into an account that has not had renames before  OR  Change the naming pattern to something new.
3. Observe all your Pokemon given new names with less than 500ms between each...

### Other Information
Version: 0.8.5
Windows Version:  Windows 10 x64
What is affected: Renaming by IV function.

**Comment by nfettinger** [comment]
Known issue, duplicate

**Comment by r-pearce** [comment]
I searched through all issues for "rename" and came up with nothing open. Is this known, but not listed as an issue, or am I blind?
Thanks

**Comment by r-pearce** [comment]
Issue still exists in the newest patch. No commits about "rename" anything, no open issues about "rename" anything. Please cite the duplicate so this simple issue is not blocked from being fixed. Or can I put in the fix myself?
