### ISSUE TITLE
Bot closes right away after opening it

### ISSUE THREAD

**Issue by julian3101** [NECROBOTIO/NecroBot#5221]
Problem here, i just open open the bot to make it run and it just shuts down and closes right away !
doesnt even give me time to see what it did. what is happening , i didnt change any of my config. 

what can be the issue?

**Comment by evansims** [comment]
In Explorer, open the folder you extracted Necrobot to.
Holding shift, right click inside an empty space in the folder.
Choose "Open command window here."
Type necrobot.exe and hit enter to run the bot.
You should be able to see what the error is now.

**Comment by julian3101** [comment]
it says that its not recognized as an internal or external command or batch file. i dont get it, i didnt change anything in the config

**Comment by nfettinger** [comment]
Please use Discord for future assistance.

**Comment by julian3101** [comment]
discord ?? what is that ?

**Comment by evansims** [comment]
It's a chat application. Great place to ask configuration questions and get general advice.

- You can signup for Discord at https://discordapp.com
- After signing up, join the Necrobot community by clicking this link: https://discord.gg/VXKxNFr
- You'll see the "N." graphic for Necrobot's server on the left. Click it to see the server.
- Choose the support channel from the list.
