### ISSUE TITLE
Pokesniper feature

### ISSUE THREAD

**Issue by zzzz9999** [NECROBOTIO/NecroBot#5223]
Is this feature working on v 0.8.5 ?
How do I know if it's enabled, I haven't change any related setting in config file...
How can I know if bot pokesniped something?
Thanks

**Comment by dartmagus** [comment]
snipeonpokestops: true

**Comment by zzzz9999** [comment]
"SnipeAtPokestops": false

**Comment by mattyk4** [comment]
Change it to "true"

**Comment by nfettinger** [comment]
We cannot help with sniping issues here.

**Comment by Epic81** [comment]
I have mine disabled. You get to many hang time errors. The connection to "pokesnipers has been lost" lot of wasted time just snipe them manually.

**Comment by zzzz9999** [comment]
How to do it manually?
