### ISSUE TITLE
Help pls: Pokesniping

### ISSUE THREAD

**Issue by mattyk4** [NECROBOTIO/NecroBot#5225]
Can someone give me an easy quick step by step process to enable pokesniping pls cause I seem to eff it up doing it myself.

**Comment by Adenahmed** [comment]
Hi mate.
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 70000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

Give that a go

**Comment by Adenahmed** [comment]
Hi mate!

  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 70000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

Give this a go.

**Comment by mattyk4** [comment]
Hey dude thanks but it's still not working, I had it working with similar settings for around 6 hours straight today. Roughly an hour ago necrobot started playing up, whenever I change ANY settings it tells me ##### config.json ##### which is normal but then nothing appears afterwards, as if the program died, which can be fixed usually by redownloading but then it breaks again so yeh fml

**Comment by MrProblematic** [comment]
> "SnipingScanOffset": 0.013,
What that do?

**Comment by Adenahmed** [comment]
Hmm, my best guess is to redownload and start fresh mate. If it works after a fresh install. Try moving your old config into the new one. If it crashes again, something buggy is going on in your config

**Comment by Adenahmed** [comment]
My guess is that it's the area the snipe will look for. The bigger number, the larger number. But I'm not sure. All I know is that you don't want to enter a huge number, like 10 blank

**Comment by jjskuld** [comment]
@MrProblematic SnipingScanOffset is only used with SkipLagged scanning (locations determined by locations in your config file). It determines the radius of the search area for pokemon.  The default smallest setting is 0.003 so at 0.013, the above user has increased the search radius.  It does not affect the other sniping methods (Pokesnipers, PokeZZ, PokeWatchers, etc)

**Comment by Adenahmed** [comment]
Awesome, thanks for telling! @jjskuld

**Comment by MrProblematic** [comment]
TY @jjskuld !!! Another question XD this range is in meters right? You now the max value?

**Comment by MrProblematic** [comment]
NVM i found my answer in here: #3621

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
