### ISSUE TITLE
pokemon caught number still the same, even if they were transfered

### ISSUE THREAD

**Issue by shaohsing** [NECROBOTIO/NecroBot#5226]
in the inventory appear 10 pokemon, and you can only see 3 pokemon in the inventory
how can i fix this...

other thing, how can i change the config to do not tansfer pokemon

**Comment by Linewalker** [comment]
Count your eggs. No Code issue, please close. Refeer to https://discord.gg/VXKxNFr

**Comment by shaohsing** [comment]
and how can i change the config to do not transfer pokemon, and i choose wich i want to transfer
