### ISSUE TITLE
Multiple bots at once?(Question)

### ISSUE THREAD

**Issue by Epic81** [NECROBOTIO/NecroBot#5227]
Is anyone running mulitple bots at once with no problem?
with the same i.p and on the same network?
I am currently running one bot and would like to run a second but i would like to know if you get i.p banned like on pokebuddy?

**Comment by jaypeeb0917** [comment]
running 20 bots same ip no problem :)

**Comment by MrProblematic** [comment]
if i try to run more then 1 bot.. i get my ip banned..

**Comment by smoothrunnings** [comment]
Every bot must have it's own public IP address.

**Comment by fass1993** [comment]
@jaypeeb0917  how?
