### ISSUE TITLE
Bot closes right away after opening it

### ISSUE THREAD

**Issue by julian3101** [NECROBOTIO/NecroBot#5234]
STOP CLOSING MY ISSUES SO FAST !!!
 
my bot closes right after i double click on the .exe
but when i tried running the program from the command prompt from it works.

why is that ? 
Please do not tell me to use Discord, that will not help me fix this!

**Comment by Adenahmed** [comment]
Hi. Download the bot again. Do a fresh install. Try it. If it works, something buggy is on your config.

**Comment by julian3101** [comment]
but i didnt change my config lol but the bot works only when i open it from the CLI not when i double click the icon .exe file

**Comment by Adenahmed** [comment]
Might be a firewall or something? I've no idea mate. Wish you the best and hope someone else comes around to guide you

**Comment by julian3101** [comment]
thanks anyways ...anyone else have any ideas ?

**Comment by olaioo** [comment]
Are u checked if u write right your email and your password, in the release folder has a config file auth something. Just check it

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.
