### ISSUE TITLE
[request] TransferFavorite : False

### ISSUE THREAD

**Issue by nan0tEch** [NECROBOTIO/NecroBot#5236]
Please add an option to transfer or not your favorite pokemon. I want to use Necrobot with my account, but i don't want to get my actual favorite's to transfer by some kind of other rule.

**Comment by burntable** [comment]
Necrobot transfers your favorited pokemons?

**Comment by nan0tEch** [comment]
I don't know, i don't wanne try it out on my life account.

**Comment by alix-the-alicorn** [comment]
it does not transfer any favorites

**Comment by NeCx** [comment]
I tried many times. Never transfers favorites.

**Comment by nan0tEch** [comment]
ok thx , you'll by me a bear when it does :)

**Comment by Bananab0y** [comment]
Neither you nor the bot can transfer favorites.
