### ISSUE TITLE
no pokestops in area

### ISSUE THREAD

**Issue by faris2000** [NECROBOTIO/NecroBot#5237]
is the bot down again or is it just me?

**Comment by smoothrunnings** [comment]
Bot is not down, you have just been banned by the server.

**Comment by faris2000** [comment]
banned how?

**Comment by Caliboss** [comment]
search previous issues

**Comment by faris2000** [comment]
can u refer me to some?

**Comment by cconoly** [comment]
I had the same problem, but closed the bot, waited 10 minutes and then it worked fine.

**Comment by faris2000** [comment]
ok thanks alot
