### ISSUE TITLE
necrobot crashes after 10, 20 or sometimes 30 minutes

### ISSUE THREAD

**Issue by janga11** [NECROBOTIO/NecroBot#5239]
this is the text whats in the log when it crashes:

Causing Method: System.Collections.Generic.Dictionary`2[System.String,System.String] PerformAuthRequest(System.Collections.Generic.Dictionary`2[System.String,System.String]) Source: GPSOAuthSharp Data: System.Collections.ListDictionaryInternal

### Other Information
Version: v0.8.5
Windows Version:10

**Comment by Adenahmed** [comment]
Seems like the internal dictionary is offset. Have you tried writing a new one?

**Comment by smoothrunnings** [comment]
Have you run Windows updates? 
Works fine on my Win10 and 2012 R2 boxes, fully up-to-date patched.

**Comment by janga11** [comment]
@smoothrunnings everything is updated.

**Comment by janga11** [comment]
@Adenahmed no i didn't, but i'll try
