### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by VCorleone** [NECROBOTIO/NecroBot#5260]
How much range is good ? And how to have a good configuration to level up, can you show me your config if it works good?

**Comment by Bananab0y** [comment]
As far as I know, any range is fine, as long as you don't cross your country's borders.
To level up faster, try increasing `"WalkingSpeedInKilometerPerHour": ??` or set `"DisableHumanWalking": false`. You can enable evolving of Pokemon as well. Use Lucky Eggs and Incense, and enable Pokemon sniping.
See here for configs: http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/
