### ISSUE TITLE
Can some on send me the settings for snipe 

### ISSUE THREAD

**Issue by Hkayas** [NECROBOTIO/NecroBot#5262]
No pokemon found to snipe 
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 10000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by Bananab0y** [comment]
`"UseSnipeOnlineLocationServer"` does not exist in my config. Make sure you have the latest version.

**Comment by Hkayas** [comment]
Well on the v0.8.5 config file  "UseSnipeLocationServer": false, it sure does 

can u copy your file please

**Comment by Bananab0y** [comment]
"UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 10,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.01,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by Bananab0y** [comment]
Update to the newest version please.

**Comment by Hkayas** [comment]
i did brah thx buuuuuut now i am softban doesnt unban me lol

**Comment by Bananab0y** [comment]
Make sure you updated your coordinates in the config.json. Or just be patient.

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
