### ISSUE TITLE
Not catching that many pokemon! Change location? New settings?

### ISSUE THREAD

**Issue by kipperjx2** [NECROBOTIO/NecroBot#5268]
Share your locations? Which have you found work best?

This morning i was catching alot of pokemon, now only 1 or 2 every so often. 

Share your settings?!

Is this common right now?

Is it the feeder sites?

Best,

**Comment by luisonator** [comment]
same here...

**Comment by rootm0s** [comment]
Questions is on discord:  https://discord.gg/VXKxNFr! This is for coding issues only.
