### ISSUE TITLE
How to do the setting to get more pokeballs ?

### ISSUE THREAD

**Issue by mystogenz** [NECROBOTIO/NecroBot#5272]

**Comment by Bananab0y** [comment]
`"TotalAmountOfPokeballsToKeep": ??`

**Comment by mystogenz** [comment]
@Bananab0y "RecycleInventoryAtUsagePercentage": 90.0, Need to reduce this one ?

**Comment by Skolzack** [comment]
I want to know how to "TotalAmountOfPokeballsToKeep" works, because it keep getting the UltraBall and recycling the rest of PokeBall and GreatBall.. How to limit by each?

**Comment by kurozani** [comment]
total amount is total of that 3 type

and it will prioritize ultraball, so if you have 120 ultraball, it will recycle all your poke and great

**Comment by Skolzack** [comment]
@kurozani But between the time of recycles, he gets much more Pokeballs than GreatBalls, sometimes 10 PokeBalls and 0 GreatBalls, so I lost much more pokemons because this thing happen. No way to limit by each?

**Comment by Simpuhl** [comment]
This section is for bugs.

Questions can be answered by going to https://discord.gg/VXKxNFr

Please close your issue.
