### ISSUE TITLE
Recycling regular pokeballs

### ISSUE THREAD

**Issue by NozFiend** [NECROBOTIO/NecroBot#5284]
Hello, changed the config file to save more pokeballs and less potions but even then my bot is still recycling all the regular pokeballs. no big problem but anyway to fix that? thanks

**Comment by kurozani** [comment]
it is the total pokeball you will have

see your total amount of pokeball

let see you set

150 pokeball
20 potion

it will save a total of 150 pokeball (ultra, great, poke) and will prioritize ultra - great - poke

it will recycle your poke first

**Comment by NozFiend** [comment]
Yea i set it at 250 pokeballs and 10 potions 
and it still recycles literally every single 1 of my pokeballs. 
just launched a new a different account and it recycled 119 pokeballs :////// super sad face

**Comment by kurozani** [comment]
how much greatball and ultra you have?

it might recycle all your pokeball but you still have ultra and great

**Comment by NozFiend** [comment]
yea i have 230 ultra balls and like 15 great balls

**Comment by NozFiend** [comment]
so i guess that's pretty sweet. ahahahahha

**Comment by kurozani** [comment]
yup, 250 is total of ALL type of pokeball, it doesn't matter if the pokeball got recycled, you still got ultra XD
