### ISSUE TITLE
HttpRequestException

### ISSUE THREAD

**Issue by ChenGaoYuan** [NECROBOTIO/NecroBot#5288]
HttpRequestException, network is OK, My account login in iphone is OK, bot doesn't work

**Comment by oneplusTree** [comment]
Me too! http://pgorelease.nianticlabs.com/plfe/rpc  this Url is 404 error

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
