### ISSUE TITLE
Move Zen Headbutt causes crash, unknown json

### ISSUE THREAD

**Issue by zimmey** [NECROBOTIO/NecroBot#5290]
I have a number of other move filters working, couldn't work out what the format for Zen Headbutt is to add to Snorlax.

I tried

"zenHeadbutt"
"zenHeadButt"
"ZenHeadbutt"
"Zen Headbutt"

Is there a list of acceptable values somewhere? I've searched and searched, and cannot find any in the wiki or otherwise.

**Comment by vfuyong** [comment]
Try "zenHeadButtFast"

**Comment by zimmey** [comment]
That seemed to do it, thank you!

Is there a list somewhere?

**Comment by vfuyong** [comment]
It might be in the code somewhere. It should not be hard to search?

**Comment by zimmey** [comment]
Ok, I'll dig. Thanks for your help.

**Comment by vfuyong** [comment]
By the way, I think Lick might be a better move.

**Comment by zimmey** [comment]
I was just going by this... https://pokemon.gameinfo.io/pokemon/143-snorlax

do you have a different source?
