### ISSUE TITLE
Distance too Small ? 

### ISSUE THREAD

**Issue by jamboljack** [NECROBOTIO/NecroBot#5293]
(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

Since yesterday i got that message.. Why ?

**Comment by jamboljack** [comment]
I use map Sydney, or another country..but same message

**Comment by YahyahyahCF** [comment]
You are softbanned, just need to close the bot for a while before trying again

**Comment by feroniameimei** [comment]
change your IP address

**Comment by smoothrunnings** [comment]
@jamboljack  You have been banned. You can only have 1 bot per IP. You can't be logged in on your phone and using a bot. The banned goes away 30 minutes to 1 hour.

**Comment by hclcrome** [comment]
Im having the same problem and im not banned. What would i do to fix it?

**Comment by cruerboyz** [comment]
i have same problem..
when i login on my phone no problem..
i can get gift from pokestop..
![whatsapp image 2016-08-12 at 11 13 57 am](https://cloud.githubusercontent.com/assets/20983030/17612428/477990b4-6084-11e6-806c-b1bf738a4afe.jpeg)

**Comment by jamboljack** [comment]
I can login and play with my phone,, but if i use bot from my laptop with IP from ISP the bot not working.... :(

**Comment by jamboljack** [comment]
@cruerboyz : yes,, that is.

**Comment by jamboljack** [comment]
@feroniameimei : IP Public from ISP,,, i can't change it...  😄

**Comment by luckyboyshy** [comment]
I got that every day since botting. Just restart your wifi-router and ISP modem if you have one, you will be fine. And be advised, DO NOT bot more than 1 account on your laptop. DO NOT get greedy.

**Comment by cruerboyz** [comment]
after restart my pc the tools become working back..
its says me to donload new update..
![whatsapp image 2016-08-12 at 12 21 41 pm](https://cloud.githubusercontent.com/assets/20983030/17612699/98fe0476-6087-11e6-9431-34988779023a.jpeg)

**Comment by jamboljack** [comment]
Still same,, i restart my router,, but still not working.... 😢 
IP public from my ISP is static,,,so... any other solution ??
(https://cloud.githubusercontent.com/assets/6668588/17612790/35c70788-6080-11e6-89bb-5b80492f32ce.jpg)

**Comment by cruerboyz** [comment]
my ip also static..
i cannot change my ip too..

**Comment by jamboljack** [comment]
Argghhhhhh

**Comment by cruerboyz** [comment]
its solve my distance too small..
but another prob come..
bot always travel but non pokemon it catch..
only travel like holiday from pokestop to another..
urghhhh

**Comment by jamboljack** [comment]
i have update to 0.8.6...it;s work guys...

**Comment by jamboljack** [comment]
![086](https://cloud.githubusercontent.com/assets/6668588/17613062/7ce97f1c-6083-11e6-85ef-79d3d5ca86e9.jpg)

**Comment by cruerboyz** [comment]
@jamboljack where got the new update

**Comment by jamboljack** [comment]
@cruerboyz Yes,,,

**Comment by cruerboyz** [comment]
@jamboljack can share link for new bot tools
