### ISSUE TITLE
Can Catch Pokemon, but softban on every pokestops

### ISSUE THREAD

**Issue by evoamac** [NECROBOTIO/NecroBot#5300]
every pokestop fails, but can still catch every pokemon. weird?
![capture](https://cloud.githubusercontent.com/assets/5290339/17611386/5fd211ea-600c-11e6-83a3-c60488b96a53.PNG)

**Comment by evoamac** [comment]
![capture](https://cloud.githubusercontent.com/assets/5290339/17611399/8078dda2-600c-11e6-9a6b-981de414d8ba.PNG)

**Comment by thebestt** [comment]
Try turning "DisableHumanWalking": true, into "DisableHumanWalking": false,

It fixed the issue for me once I did that

**Comment by leonnjh** [comment]
1. Close the application
2. Open the Config folder
3. Open config with notepad
4. Change the walking speed to 25 or lesser

The softban is generated because of an unnaturally movement by the bot.

**Comment by evoamac** [comment]
lol, guess i was walking/flying too fast

**Comment by Rick058** [comment]
That means the unbanner did his job correctly, that you get banned again straight after is something completely else.
Are you using a VPN/proxy? Is your config correctly filled in? I'm on 60km/h and have 1-2 softbans each hour where-as my other bot runs on 100km/h and receives softbans way more often.

**Comment by evoamac** [comment]
@Rick058 actually the unban didn't work. it reached max 45 re-try, and moves on to the next and does another 45 and moves on.

**Comment by evoamac** [comment]
@Rick058 and no VPN, 1 account. config file was fine, fan fine for 6 hours this morning. just started acting this evening.

**Comment by BallsackBro** [comment]
WRONG !

I've set "DisableHumanWalking": false,
and I've also set "WalkingSpeedInKilometerPerHour": 5.0,
AND STILL I get non-stop soft banned poke stop after pokestop , please help ???
![ovo brate](https://cloud.githubusercontent.com/assets/20982171/17611587/fcc5796a-6048-11e6-94f3-db84c050236b.jpg)

**Comment by ciblnt** [comment]
Mines doing the same thing now. It was set to walk speed of 20 and the disablehumanwalking is set to false. Still doing the same thing his is.

**Comment by ciblnt** [comment]
Looks like Niantic changed something again.

**Comment by evoamac** [comment]
@BallsackBro wow, 5km/h, that's like swimming speed. but ya, same here, still can catch pokemon for some reason

**Comment by ciblnt** [comment]
Yup, Mine will catch as well but can't spin them stops lol. So i just shut it down before I have no more balls lol.

**Comment by evoamac** [comment]
@ciblnt it's working again now, after i waited about 30 minutes-ish

**Comment by ciblnt** [comment]
Weird ... ok. Ill wait a little while then.

**Comment by BallsackBro** [comment]
@evoamac I know, right ? I've set it to such a slow walking speed and changed the human walking which means it should be like real life walking and playing , but still I get this lol.
I reckon the Niantic changed something and I hope the Necrobot is going to fix it soon.
Damn it, I live in Europe and it's 5:02 AM right now, just woke up to get some water and now I am awake trying to fix this issue. Just when I thought to sleep all night and let this fine bot do his job , damn it xD

**Comment by evoamac** [comment]
@BallsackBro got no balls? xD. i'm fixing to go to bed, was hoping to leave it over night, but i don't know how low it will last though. i'm real close to level 40. by real close, i mean another solid 80 hours without interruption . lol

**Comment by evoamac** [comment]
@BallsackBro btw, i was going at 150/h. hahahahaha, just slightly unrealistic. but it's pretty normal interstate driving speed here in texas tho.

**Comment by BallsackBro** [comment]
@evoamac I got plenty of balls xD
Yeah, I'm also going to sleep and hope in the morning they will fix it.
I was kinda worried for my account though.
I am soon I think lvl 36 and I could say that few days would help me to get that lvl 40 as well, but I hope we won't get perma ban till then xD
I usually put the speed like 5 and I get less soft bans and still the bot runs pretty fast from the pokestops, but damn this time even enabling human walking didn't worked O,O
Anyways , sleep well and let's hope for the best.
Peace out :3

**Comment by BallsackBro** [comment]
@evoamac P.S. I just opened my inventory and realized I had no ordinary pokeballs , just great and ultra.
Damn , gotta fix the config for the bot to use these as well :/

**Comment by ciblnt** [comment]
It does use them. What happens is it hits pokestops over and over and it replaces the regular pokeballs with the higher balls. Like im sitting on 730 Ultra Balls lol. No Regular and No Great. Just all Ultra. Which is fine with me cause the higher the ball the easier the catch.

**Comment by Effesus** [comment]
I have the exact same problem as the issue picture. I use all config default settings, Use no VPN but only use 1 bot for one account. Not sure whats going on but Im just wanting to be another satisfied user bringing this issue to attention. Thank you, keep up the great work.

**Comment by lostgecko** [comment]
I know how this is may sound a bit dumb but it worked turn off your modem for a few minutes i turned mine off for 10 min turn it back on and you should be back to sniping . been running the bit for 3 hrs now no problems.

**Comment by lostgecko** [comment]
Bot*

**Comment by kurozani** [comment]
you didn't get softbanned

just make sure to move to other area, you visited a poketops which has been SPINNED before and not yet refreshed and bot recognize it as SOFTBANNED

**Comment by evoamac** [comment]
@kurozani if that's the case, it should work after 5 minutes. but it's not happening

**Comment by ciblnt** [comment]
I dont know what the deal is. I haven't used it in over an hour and its still not spinning pokestops. Keeps saying im softbanned and can't unban me.

**Comment by B4700** [comment]
Started happening for me roughly 30 minutes ago.    Catching pokemon no problem. Set at 16. Suddenly no stops. Shut down. Timed 5 minutes. Restarted. Tried again. 3 times before I shut it down. Have been at the same location for 6 hours.

**Comment by ciblnt** [comment]
Same here. I know people above said they got it working but I have serious doubts about that. This has been running flawlessly for days for the most part except a snipe issue here and there but now this. And this issue isn't changing no matter what I change. Somethings up.

**Comment by B4700** [comment]
Just logged into mobile no problem. Not near enough a stop to try without walking a block and my wife killing me. Hopefully an answer soon. Had hoped to leave it up all night again

**Comment by Itsapaul** [comment]
Yeah I got softbanned as well... stops work fine on my legit account but not on the bot account, even when I log in on Nox with the bot account.  Might be some new kind of ban tbh.

**Comment by B4700** [comment]
@Itsapaul Are irl trying to spinn on your bot account

**Comment by ciblnt** [comment]
Im not. Im not getting out at this time of the night to go spin a fake poke stop lol. I'll wait until the morning. The last time Niantic changed stuff the bot I was using started acting up. I left in my car and could catch pokemon fine. Could spin pokestops fine but turn on the bot and the bot just wouldn't do what it was supposed to. So im sure its the same thing again either that or im banned. But i doubt im banned because it was catching pokemon just not spinning stops so im leaning on they changed something again. Ill get out tomorrow and check to see if they still spin in real life.

**Comment by B4700** [comment]
Still. It is unlikely a "ban" as you can stil log in and catch pokemon on bot and log in irl to bot on mobile and catch. Was just curious if the bot irl could spin... almost midnight and I really want to try lol only a block away too...

**Comment by spiner0518** [comment]
The issue keeps happening, better stop botting till we get some kind of fix. 

Zero balls, no stops around, I guess I'll have to go back to the streets again...

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by B4700** [comment]
Closed based on a link to a reddit that does not address the specific top of this issue?
