### ISSUE TITLE
New Potential Ban- "Failed To Retrieve Game Data From The Servers" When Game Is Up

### ISSUE THREAD

**Issue by TWM94** [NECROBOTIO/NecroBot#5304]
### Expected Behavior
Should start making API calls without error

### Actual Behavior
After authenticating successfully and hanging for about 10 seconds the bot outputs the following error:
[22:28:47] Make sure Lat & Lng are right. Exit Program if not! Lat: 43.0914820116349 Lng: -79.0750613494288
[22:29:12] Pokemon Servers might be offline / unstable. Trying again...
[22:29:13] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 391
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56
Initializing NecroBot logger at time 8/11/2016 10:38:28 PM...

If I try to login to the account on my phone it gets passed the authentication and the loading bar gets to about halfway then I get "Failed To Retrieve Game Data".

It should be noted that I am using private proxies and running about 7 bots. This has happened with 2 of the 7 accounts so far. I am running 1 bot per 1 proxy.

I have preformed the following troubleshooting:
-Tried logging in a known working account with the proxy the broken account was using. The working account was able to start making API calls successfully.
-Tried logging the broken account in with a known working proxy and received the same error as above
-Tried logging into the app on both LTE and local WiFi. Both receive "Failed to retrieve game data".

This leads me to believe this an account specific issue and that it may be a ban. I am going on about an hour so far. 

### Other Information
Version: 0.8.5
Windows Version: Windows 7 (Up to date)
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Any API call

**Comment by anti2canz** [comment]
but why would you bot 7 accs...

**Comment by bulubebek** [comment]
Take a break for a while (20-30 minutes).  AFAIK, its happen when Niantic's server is currently down.

**Comment by TWM94** [comment]
That's hardly the issue. All 7 are running on different proxies.

**Comment by TWM94** [comment]
@bulubebek Currently running the other accounts without issue.
https://ispokemongodownornot.com reports no issues with the servers

**Comment by bulubebek** [comment]
AFAIK, If Niantic banned your ID, then you should not able to login via official app. It will shown "Account Banned" notification.

**Comment by TWM94** [comment]
@bulubebek is there any proof of a banned message as of this moment? Heard quite a few rumors and seen lots of photoshop efforts but have yet to see any solid proof they have explicitly declared a ban on a given account.

**Comment by lahum** [comment]
istirahat lah.. untuk beberapa waktu,,,

**Comment by Rick058** [comment]
@TWM94 I'm very skeptic about these 'bans'... Why would _one_ individual who runs a couple of bots receive a permanent **account** ban where-as I know people who have botted/sold over 1000 accounts and did not receive a single ban on any.

In one case, a 'popular' YouTuber tweeted out someones username who had taken over EVERY gym in his city with a botted/gps spoofed account... I mean, no one has 6 high CP Dragonites without cheating. He gave his followers the username of this account and the link to a Pokémon website to report him, the next day he was removed from all the gyms.

**Comment by TWM94** [comment]
@Rick058 I completely agree. That is why I brought the issue forth as presented it as "potential". From my standpoint and troubleshooting there is no reason why the 2 affected accounts should be having any issues.  They are piratically the same as the other working accounts I have right down to the config.

**Comment by Ninoob** [comment]
yes i have also the same issue, its is a new type of ban ?
tried using vpn, landline isp and also LTE, all failed.

**Comment by TWM94** [comment]
@ninoob At this point we are unclear if this is a new ban or not.

**Comment by casper-gh** [comment]
can confirm, cannot login to game and received same message as OP `Failed to get game data from the server`

**Comment by mishuan** [comment]
can confirm, can't log in on phone; tried wifi and LTE

**Comment by TWM94** [comment]
@casper-gh @mishuan Thank you for the feedback. Looking like it could very well be a ban.

**Comment by Ninoob** [comment]
just for info, they are catching up with the bot, just for experiment i create new account and fully bot it from lvl 1 to 10, No snipe, no spoof just basic farm in local region and it get banned now...

**Comment by casper-gh** [comment]
@Ninoob what kind of ban? 

- No data from server (account tied)
- Able to spin pokestop but pokemon all flee
- Not able to spin pokestop nor catch pokemon

**Comment by bizonovsky** [comment]
Same issue here.
Anyone know if this is permanent?
And why some users received the ban while many others did not?

**Comment by Insurgentx** [comment]
@Ninoob I don't think so dude, I've done the same thing and made a new account and it's powering along fine with full sniping, full teleport etc.

**Comment by TWM94** [comment]
I have also created another account and it is still working properly. Just turned level 16.
As for why some and why not others I am unsure. If we could pinpoint a trigger that would be excellent but nothing is apparent at the moment

**Comment by irazar** [comment]
Same here used bot this afternoon only and used on phone once it was ok loot local stop ok caught one Pokemon, then after a while started to get this msg I tested another account which is unbotted it was fine pretty sure mine is now banned... What to do! :(

**Comment by Ninoob** [comment]
@casper-gh its hard banned, cant connect to server anymore...

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
