### ISSUE TITLE
Working release, I promise

### ISSUE THREAD

**Issue by truimagz** [NECROBOTIO/NecroBot#5306]
I've done alot, and I mean alot to this project. To get rid of the bloat and get to the point.

You can now use real related delays, and your bot will actually act human and also tell you everything it's doing, instead of making 30 api calls without telling you.

http://truimagz.com/Release.zip

Happy Hunting

**Comment by lahum** [comment]
this phising??

**Comment by truimagz** [comment]
You see my username? You see the domain I linked? Go to it. You see my phone number and picture...

No it;s not phishing

**Comment by lahum** [comment]
what's the difference with the bot is downloaded directly from the official necrobot ?

**Comment by Rick058** [comment]
What are the 'better' differences? For anyone wondering about phishing: it's not, it's completely clean and safe for so far I can see.

Also... `  "WalkingSpeedInKilometerPerHour": 3.0,` man, that is super slow. What is the XP per hour, 10k?

**Comment by lahum** [comment]
@Rick058 can i see your config.jeson. thanks..

**Comment by truimagz** [comment]
If you're looking to setup a rotating bot farm, Necrobot does way too many calls every time you take  step, or do anything, and it never even tells you. I cut out all the bull.

Yes, you'll get about 10-15k xp an hour and 10-20ph

But you can run 10 unattended forever.

**Comment by lahum** [comment]
@truimagz just share yout Config.json

**Comment by GUiHKX** [comment]
The *NecroBot.exe* in the zip file **DOES NOT** match with the latest official release. Do not download it.

**Comment by Rick058** [comment]
@truimagz That's good for people who prefer to bot more than 1 account on the same IP. I run 5 bots at 100k xp/h, all their own proxy IP. But I can imagine people who don't have that luxury prefer to bot 5 accounts at 10k xp/h without getting soft banned constantly.

@GUiHKX Ow I wonder why... maybe because he made changes to it?

@lahum http://pastebin.com/F9Vsykpe around 100k xp/hour on 0.8.5

**Comment by CalmerThanTheDude** [comment]
@truimagz you left the Logs folder in the ZIp file which contains your real PoGo username or real secondary/fake account, whatever.

**Comment by GUiHKX** [comment]
If he made changes to the program and didn't provide the souce code, he's violating NecroBot's license (AGPL). Do not download this crap.
