### ISSUE TITLE
How to keep a pokemon of each

### ISSUE THREAD

**Issue by eveliojosegarcialeon** [NECROBOTIO/NecroBot#5307]
Everything is ok but I'd love to know how to keep one pokemon of each that the bot catches. E.g: catched a pikachu, keep it, if catched another, just transfer it... This is meant to get all of the pokemons from pokedex and still have one of each pokemon. Help, what do I have to modify?

**Comment by Bananab0y** [comment]
config.json:

`"TransferDuplicatePokemon": true`
`"KeepMinDuplicatePokemon": 1`

**Comment by Rick058** [comment]
^ + Be sure to configure your sniping correctly and use
`  "SnipePokemonNotInPokedex": true,`

**Comment by eveliojosegarcialeon** [comment]
THANKS

**Comment by eveliojosegarcialeon** [comment]
omg, I used those three commands and all my best pokemons started to transfer x.x what should I do?

**Comment by Rick058** [comment]
Please post your whole config.json.

**Comment by eveliojosegarcialeon** [comment]
oh, cool-wait, I actually had too many duplicate pokemons but they were not weak at all, thought my best and favorite pokemons were gone, I got confused and scared so inmediatly closed necrobot, I'm sorry...everything is ok now...I used the two commands Bananab0y shared and "SnipePokemonNotInPokedex": true too...THANKS

**Comment by eveliojosegarcialeon** [comment]
Hope the bot gets at least a few different pokemons now without transfering them and keeping one of each.

**Comment by Rick058** [comment]
If you want to be 100% sure you don't lose your 'favorite' Pokémon, favorite them!
NecroBot will never transfer Pokémon that are favored :)

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
