### ISSUE TITLE
Softban Issue

### ISSUE THREAD

**Issue by zappiy** [NECROBOTIO/NecroBot#5315]
I've been using Necrobot for about 3 days straight and with softbans, it usually only lasts about a few seconds. But starting like an hour ago, my softban has been going on and the bot is trying its best to bypass it but it will just not. Is this happening to people recently?

**Comment by polypalm** [comment]
same to me

**Comment by MegaClinton** [comment]
same

**Comment by royyzh** [comment]
yep, same here, seems like an account issue this time rather than ip ban since 3G/cellular is not working either

**Comment by Sanskritmp** [comment]
You will need to have to wait for 12-24 hours. Servers in your area might be down.
Visit https://discord.gg/VXKxNFr for #Support.

**Comment by polypalm** [comment]
no. i changed accounts and it works the problem are the accounts not the servers

**Comment by Sanskritmp** [comment]
@polypalm Requesting to close issue if fixed.

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
