### ISSUE TITLE
30+level banned?

### ISSUE THREAD

**Issue by eveliojosegarcialeon** [NECROBOTIO/NecroBot#5318]
Hey, I was asleep and left my computer with the necrobot opened, I'm level 24 now, and I have the whole pokedex almost full- If I do this again, and I reach 30 level+ (higher than level 30) that would cause a ban?

**Comment by Sanskritmp** [comment]
This doesn't seem to be an issue.
For help/support, please visit https://discord.gg/VXKxNFr.

**Comment by TWM94** [comment]
I have seen multiple accounts over level 30 without a ban. With that said you should setup a config that more or less mimics human behavior. I.e. keep a reasonable walking speed, enable humanized throws and movement etc. Furthermore, don't leave the bot running 24/7. That is a red flag in itself.

**Comment by kurozani** [comment]
nope, I am 33 and didn't get banned

**Comment by M3NTALITY** [comment]
level 35 no ban...180k xp per hour and non hum as hell

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.

**Comment by SmilingSword** [comment]
I got banned. Im not sure its a banned but it said when log in from pokemon go apps fail to get data from server

**Comment by TWM94** [comment]
@SmilingSword please see issue 5304 that I have rasied regarding this. It is more than likely a ban.
https://github.com/NECROBOTIO/NecroBot/issues/5304

**Comment by Ninoob** [comment]
yeap i suppose it been banned, i also getting same error and because my pokedex is also almost completed, i think because sniping...

**Comment by SmilingSword** [comment]
yep its a banned because my other account can be login thorugh phone but my lvl 40 cant
