### ISSUE TITLE
Another Snipping Website

### ISSUE THREAD

**Issue by dzocrusher05** [NECROBOTIO/NecroBot#5320]
Pokezz is currently under maintenance/Down , So this is another snipping website , can u add this website to this tools ? 
this the website http://www.rarespawns.be/ 

Thx before

**Comment by Sanskritmp** [comment]
For discussions/suggestions please visit https://discord.gg/VXKxNFr

**Comment by schwartzadev** [comment]
This is not a code issue. For support, please join the [discord chat](https://discord.gg/VXKxNFr) and ask questions on the #support channel.
