### ISSUE TITLE
so, it is fixed that some account got hard banned from 8.6?

### ISSUE THREAD

**Issue by kurozani** [NECROBOTIO/NecroBot#5348]
I tried on nox, handphone, got banned just after tried 8.6 :(

**Comment by Baleki** [comment]
try change ip

**Comment by kurozani** [comment]
change IP? I don't think it was about IP, tried on phone, Nox, PC, all of them :(

**Comment by nerclid** [comment]
you cannot login?

**Comment by GoGoDong** [comment]
changed IP, no use.
Same IP with different account succeeds.

**Comment by 50800203** [comment]
Me too, it's maybe hard banned

Message response: Pokemon Servers might be offline / unstable. Trying again...

**Comment by Zaryabb** [comment]
Hardban is possible. I can log into my account on my phone though but cant catch any pokemon and quick spin didnt unban me changing my vpn didnt unban me usually changing vpn always fixes ip ban but this time nope.

**Comment by Rival94** [comment]
yes i think its possible
i can't login from my phone too :(

**Comment by zzxxzzxxSG** [comment]
Please check if your Server is working or down.
Cos if your location is set at Australia, it connects to Australia's Server.

http://www.mmoserverstatus.com/pokemon_go

**Comment by Pikachu92** [comment]
i think u use walking speed more than 50 ?

**Comment by Gregsf89** [comment]
did you see this screen http://i.imgur.com/v4Yndvq.png ?
if yes, it's probaly hard ban

**Comment by CMvet** [comment]
Yeah, seems to have happened to a lot of people.  I got it too and was only using a 5.2 km/h walk speed and stayed in my local area, no teleporting.

**Comment by Rival94** [comment]
hope just server down in indonesia

**Comment by XShido** [comment]
According to this site, theres server issues in a few countrys right now
http://www.mmoserverstatus.com/pokemon_go

**Comment by transteam** [comment]
Got same msg as Gregsf89p posted.  made another account on my phone, which can log in.  Main account is banned. -_-;; just hit level 33 too

**Comment by Evilgenius100** [comment]
Same message here. And I also just reached 33. Wonder if it has anything to do with the level?

**Comment by kurozani** [comment]
me too, level 33, LOL

we three has the same level

**Comment by Rival94** [comment]
lvl 27. i dont think its 'bout lvl

**Comment by markemonb** [comment]
Just reached lvl 34, same ban

**Comment by Evilgenius100** [comment]
Is there any pattern for those getting this message? Did everyone have the bots running for a length of time? Maybe something in the config settings about movement speed? I doubt this was done manually so there has to be some kind of criteria or something.

**Comment by Insurgentx** [comment]
@Evilgenius100

http://pastebin.com/KVgSbSLm

This is my config for the account that got banned. If the others in this thread can pastebin theirs we can begin to find a common theme.

**Comment by Evilgenius100** [comment]
Sounds like a plan

Mine: http://pastebin.com/afkXcyWB

**Comment by Rival94** [comment]
http://pastebin.com/QvUHSpCf
