### ISSUE TITLE
Pokemon snipping configuration

### ISSUE THREAD

**Issue by Zandrick** [NECROBOTIO/NecroBot#5349]
May I know how to config to get all the services of pokemon snipping?
I follow the wiki sniping to config like this currently. But it always not found 

  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": false,
  "SnipeWithSkiplagged": false,

**Comment by g00tch** [comment]
"GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": false,
  "GetSniperInfoFromSkiplagged": true,

**Comment by g00tch** [comment]
Pokezz crashes.
PokeWatchers throws an error.

**Comment by Zandrick** [comment]
I see. Thanks a lot!
