### ISSUE TITLE
Necrobot 8.6..No useable pokestops

### ISSUE THREAD

**Issue by rsngrd** [NECROBOTIO/NecroBot#5353]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Actual Behavior

It was working fine when I first started using it, then i changed config and it still worked but then softban, after softban, it has been saying [23:00:18] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by recon88** [comment]
Please fill out the form properly.
Also you are most likely soft, ip or perma banned
