### ISSUE TITLE
Attention!

### ISSUE THREAD

**Issue by ambitious20** [NECROBOTIO/NecroBot#5355]
Well I have a problem... I've entered the right coordinates for longitude and latitude and I keep getting the "no usable found in your area... is your maximum distance to small?" what can I do to fix this?
i'm new to this so call me a noob but any help is greatly appreciated!!!

Thank you!!

**Comment by Zarvation** [comment]
ip ban, change your vpn

**Comment by ambitious20** [comment]
how do I change that?

**Comment by Baleki** [comment]
change mac ip (if static), dynamic just rebot the moden or use proxy,vpn...

**Comment by ambitious20** [comment]
Thank you guys for the timely responds... Hehe it turns out I actually had the wrong coordinates adjusted in the config settings. Once again I appreciate you all! :)

**Comment by recon88** [comment]
Please check
https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
