### ISSUE TITLE
Failed to get Game data

### ISSUE THREAD

**Issue by donaldantonio** [NECROBOTIO/NecroBot#5356]
Hi Guys. It was doing fine until it stopped working. And when I logged in to my mobile, it says Failed to get game data. I tried loggin in another account, it works. Any other else who encountered this and might have solved it already?

**Comment by cuse65** [comment]
Its a ban. Ban waves just went out it seems

**Comment by wyvern19** [comment]
any clue on perm or soft?

**Comment by danooh** [comment]
guess perm.

**Comment by recon88** [comment]
Please check
https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
