### ISSUE TITLE
Did i just get hard banned ?

### ISSUE THREAD

**Issue by Enragedmaster** [NECROBOTIO/NecroBot#5362]
The pokestop spin does not work , Changed IP , Servers up , Whats going on?

**Comment by danooh** [comment]
hard banned would mean that you even cannot login with that specific account

**Comment by Zaryabb** [comment]
yeah someone made a good point they may have simply taken away the spin to unban feature thus every account is softbanned for the full period of time....

**Comment by x3r4n0** [comment]
dont jump to far in short time so u can avoid softbans...

**Comment by Pikachu92** [comment]
are you using "WalkingSpeedInKilometerPerHour" more than 50 ? got id banned, maybe soft or hard, dunno

**Comment by juantamadz** [comment]
i think i will just stay using the previous version which still working, although it gives less XP

**Comment by CMvet** [comment]
I got hard banned on 0.8.5 and only botted in my general area, walk speed 5.2 km/hr and never teleported

**Comment by Zaryabb** [comment]
What damn that's insane what does it say? If you can log into your account on phone you're not hard banned by if it says failed to get data then you're probably permanent banned

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
