### ISSUE TITLE
Constant soft ban warning? am I banned?

### ISSUE THREAD

**Issue by akivakiln** [NECROBOTIO/NecroBot#5363]
https://gyazo.com/48f3c14361e7601bbf795fa7cd00a2ed
I cant get any pokestops just keep getting the possible softban error. It never used to last this long.
I couldnt see if anyone else had this problem?

**Comment by Enragedmaster** [comment]
Same here

**Comment by Enragedmaster** [comment]
I believe they removed the spin unban trick

**Comment by Baleki** [comment]
yep, just stop the bot and wait for tomorow

**Comment by lordmcskaba** [comment]
I think its still softban, but the rollback unban system is experiencing malfunction. Because we still can login right?

**Comment by CMvet** [comment]
A lot of people seem to be getting the perm ban as well...

**Comment by sackthesack** [comment]
I can get any pokestops with exp but every pokemon is escaping. What is this?!

**Comment by abriffa** [comment]
same happens to me... I can still catch pokemon, but cannot get poke stops, always displaying soft ban

**Comment by levidread99** [comment]
i experience this aswell, we should all just try again tomorrow

**Comment by hoodude** [comment]
same here... I can get any pokestops with exp but every pokemon is escaping.

**Comment by sazzanm** [comment]
i cant get any pokestop , but i can catch pokemon lol ...

**Comment by jazzu20** [comment]
just turn off your bot and wait for tomorrow

![image](https://cloud.githubusercontent.com/assets/15447310/17614630/52013d3c-609a-11e6-9404-ccb2af545328.png)

**Comment by nexteve** [comment]
i can't log in :(

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
