### ISSUE TITLE
Can still get pokestops but not catch pokemon? they all just flee 

### ISSUE THREAD

**Issue by Blackjesus69** [NECROBOTIO/NecroBot#5375]

**Comment by masterxam** [comment]
same here

**Comment by TemhAAhmeT** [comment]
Same here

**Comment by ThomasSRL** [comment]
Please dont post duplicate issues

**Comment by HusbandoMax** [comment]
As far as I know its the new soft ban to kill use of pokestop spinning to remove the ban. I think you have to wait it out not sure tho. Not sure if its perm either.

**Comment by sazzanm** [comment]
i cant loot pokestops , but i can catch pokemons lol

**Comment by lkhgamer** [comment]
thats true, you still can catch a poke but the pokestop cant

**Comment by Blackjesus69** [comment]
Its not an IP cause the other accounts i have work just fine but this one will hit all the pokestops but all the pokemon flee

**Comment by kadekdharmalaksana** [comment]
@Ikhgamer same with me? how we can catch and spin the pokestop, back to normal like old version. can catch and get pokeball?

**Comment by recon88** [comment]
Most likely a soft, IP or Perma ban
