### ISSUE TITLE
"Failed to get game data from the server."

### ISSUE THREAD

**Issue by DagooNn** [NECROBOTIO/NecroBot#5376]
I get this info all time when try start on my device and on necrobot also cant start.
Is this server issue or perm. ban?

**Comment by charlieswb** [comment]
permanent ban

**Comment by transteam** [comment]
welcome to being perm banned.  I'm in the same boat

**Comment by DagooNn** [comment]
strange as this issue was already in past and was solved.
why niantec did not pop up message YoU are banned only 'Failed to get game data from the server'....

**Comment by mogibilal** [comment]
ninatic going rape botter

**Comment by DagooNn** [comment]
still strange another two account (also botting) still works fine....

**Comment by recon88** [comment]
Most likely soft, ip or perma banned
