### ISSUE TITLE
JSON Exception: After parsing a value an unexpected character was encountered: ". Path 'TransferConfigAndAuthOnUpdate', line 16, position 2.

### ISSUE THREAD

**Issue by sandzener** [NECROBOTIO/NecroBot#5377]
![cats](https://cloud.githubusercontent.com/assets/20985089/17614712/a0270652-6092-11e6-9895-368a6977a147.jpg)

**Comment by iHatePython** [comment]
Read what the error says, it's in simple English.

an unexpected character was encountered: ". Path 'TransferConfigAndAuthOnUpdate', line 16, position 2

Go and fix whatever you messed up in line 16

**Comment by sandzener** [comment]
Did I do something wrong?

![image](https://cloud.githubusercontent.com/assets/20985089/17614818/8fb78534-6093-11e6-88ce-8c2226c39586.png)
