### ISSUE TITLE
Log Error on necrobot 0.8.6 / error latitude and longitude

### ISSUE THREAD

**Issue by ArisenLegolas** [NECROBOTIO/NecroBot#5378]
When vo access the bot appears that => http://prnt.sc/c4pqjz

**Comment by avikapoor** [comment]
i am suspecting an issue with US servers, i was also using US lat long when this starting happening.
http://www.mmoserverstatus.com/pokemon_go ( even on this website there is something wrong with US server)

i will try some other location after few hours and will let you know.

**Comment by charlieswb** [comment]
some of my ids are fine some get this error.
I think it's perm ban.

**Comment by avikapoor** [comment]
@charlieswb - ids which are working are also located in US ?

**Comment by ArisenLegolas** [comment]
my ids is all in US talves is a bug temporary

**Comment by ArisenLegolas** [comment]
I hope you straighten this problem soon

**Comment by charlieswb** [comment]
@avikapoor nope and those banned are also not in US.

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
Also use the ticket template instead of removing it.
