### ISSUE TITLE
Moves for Vaporeon can't be recognised ( Hydro Pump )

### ISSUE THREAD

**Issue by ignok99** [NECROBOTIO/NecroBot#5379]
### Actual Behavior
JSON Exception: Error converting value "hydroPump" to type 'System.Collections.Generic.List`1[POGOProtos.Enums.PokemonMove]'. Path 'PokemonsTransferFilter.Vaporeon.Moves[0]', line 467, position 27.

### Your config.json
"Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
	  "HydroPump"
	  ],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }

### Other Information
Version: 0.8.6
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Transfer

**Comment by lkhgamer** [comment]
"Vaporeon": {
"KeepMinCp": 1500,
"KeepMinLvl": 6,
"UseKeepMinLvl": false,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1,
"Moves": [HydroPump],

**Comment by ignok99** [comment]
@lkhgamer Doesn't work

**Comment by Rabelaiss** [comment]
With version 0.8.5 i have this, it worked but dont know with the new version
    },
    "Omastar": {
      "KeepMinCp": 2000,
      "KeepMinLvl": 40,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 100.0,
      "KeepMinDuplicatePokemon": 0,
      "Moves": [
        "waterGun",
        "hydroPump"
      ],
      "KeepMinOperator": "or",
      "MovesOperator": "and"
    },

**Comment by recon88** [comment]
You need to provide both moves as far as I know.
