### ISSUE TITLE
Make sure you actually close 0.8.5 before opening 0.8.6

### ISSUE THREAD

**Issue by nakuma85** [NECROBOTIO/NecroBot#5380]
I had the same problem as many here reported. Softban and all pokemons fleeing.
Until I realized that 0.8.6 didnt actually close the 0.8.5 window. 

0.8.5 continued running in the background, unlike other times where it was auto closed.

**Comment by chohitoshiri** [comment]
For sure, 0.8.5 close, this is not the cause....for softban...

**Comment by nakuma85** [comment]
Sorry to hear, didnt want to give a false hope but i was soft banned in the same way other are reporting. Until i realized I stil had a 0.8.5 client running. Dont want to get peoples false hopes up but hey, maybe someone did the same as me.

**Comment by ThomasSRL** [comment]
This is not a code issue. No need to post this here.

**Comment by nakuma85** [comment]
Right, my bad, please delete.
