### ISSUE TITLE
0.8.6 can't run error LogBuffer....Anyone can help me?

### ISSUE THREAD

**Issue by freezingsign** [NECROBOTIO/NecroBot#5386]
![0 86error](https://cloud.githubusercontent.com/assets/20960583/17615032/571832f8-6095-11e6-97f5-95f81aa77596.png)

**Comment by robyccc** [comment]
Same here, with latest framework..

**Comment by likudo95** [comment]
me too

**Comment by mtaram** [comment]
![necrobot 0 8 6 error](https://cloud.githubusercontent.com/assets/14808170/17615740/c68a6b0e-608d-11e6-9a31-de7c03ea39bd.PNG)
Not able to launch application post config. Error attached.

**Comment by Mithrail** [comment]
same thing for me

**Comment by likudo95** [comment]
love v8.5 :v

**Comment by recon88** [comment]
Set UseProxyAuthentication to false
