### ISSUE TITLE
Recommend parameters for transferred.

### ISSUE THREAD

**Issue by jakele168** [NECROBOTIO/NecroBot#5387]
[23:57:45] (TRANSFERRED) Pinsir         - CP:  818  IV:  77.31%   [Best CP:  220  IV:  95.25%] (Candies: 23)

I am using the default config.json configuration.  How do I change so that better CP doesn't get transferred.  Above is an example.  Pinsir CP 818 was transferred over CP 220.

Thanks.

**Comment by iHatePython** [comment]
1. This is not an issue, shouldn't be posted here.
2. This question and similar can be asked on discord.
3. It got transferred because of the IV.

Open config file and read it, it might look complicated but it's not.

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
