### ISSUE TITLE
Permenant BAN , I think u should stop using now.....

### ISSUE THREAD

**Issue by parthroxx** [NECROBOTIO/NecroBot#5388]
STOP USING BOT , YOU MAY GET BAN

**Comment by ruchern** [comment]
How did you confirm this?

**Comment by Disane87** [comment]
I've got one too. I can't login, in the bot and PokemonGo-App

**Comment by parthroxx** [comment]
Dont use BOT now , u may get banned

**Comment by Rictorus** [comment]
please provide proof

**Comment by tranngocanh01071995** [comment]
[https://github.com/NECROBOTIO/NecroBot/issues/5342](url)

**Comment by tranngocanh01071995** [comment]
#5342

**Comment by rnsblue** [comment]
[http://ispokemongodownornot.com/](url) login is "critical"
Just wait a bit before attempting to log in

**Comment by heokp983** [comment]
it's true. dont using bot now. a lot of account got ban in 1 hour ago

**Comment by Insurgentx** [comment]
My account is banned.

**Comment by Markersx** [comment]
This is not true ![](http://i.imgur.com/mqWlzbu.png)

**Comment by Disane87** [comment]
The US login-servers might be down, but not the european and I'm from germany.

**Comment by heokp983** [comment]
@Markersx u will. just talk to all of u take care when use bot now

**Comment by Insurgentx** [comment]
@Markersx - I've copped a ban on one of my accounts (Config I was using http://pastebin.com/KVgSbSLm) 

I can log in to a number of my other accounts without issue. The one I was botting with this week banned.

**Comment by necr-0** [comment]
@Markersx, 

Just because you're not banned doesn' mean no one else is.

**Comment by parthroxx** [comment]
@Markersx Config?? plz

**Comment by DagooNn** [comment]
Failed to get game data from the server

**Comment by parthroxx** [comment]
@necr-0 cant update BOT ...

**Comment by Markersx** [comment]
@Insurgentx your walking speed it way too fast mine is set at 15km/h

**Comment by woooh77** [comment]
Same here . Not able to login into my PTC.

**Comment by emwedk** [comment]
PLS re-edit this issue !! don't scare people from stopping just because servers are seriously unstable !!
mmoserverstatus.com/pokemon_go

**Comment by vvvsrx** [comment]
My account is banned too.

**Comment by heokp983** [comment]
it's not server fail because i can log another account in my phone

**Comment by Disane87** [comment]
> PLS re-edit this issue !! don't scare people from stopping just because servers are seriously unstable !!
mmoserverstatus.com/pokemon_go

It is not a issue by the state of the servers. Its a ban. I can use another account...

**Comment by jakesmurf** [comment]
Not sure what this issue is.  It kinda makes me wonder if it's some kind of database failure on their end losing a bunch of accounts at random.  

It doesn't make sense to be a banwave because my 5 level 40s that run 24/7 and 20 other bots were untouched, but I lost 2 accounts created today only.  If it is, it's the weirdest/worst banwave ever.  It isn't an IP ban because the VMs those accounts were running on are able to login and bot different accounts and changing the IP doesn't help.  It isn't a hardware ban because I still can't log in after spoofing all new details and I can't log in even with a legit Android device.

**Comment by SuccumbTemptation** [comment]
Its a new type of soft ban. All bots are affected and its account based rather than IP. Thats all we know

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/572188-new-temp-ban-only-post-here.html

https://github.com/NECROBOTIO/NecroBot/issues/5397

**Comment by xebia0x539** [comment]
Same here! Stop using it for now. I can't login with my phone an my Bot.

**Comment by hoodude** [comment]
the message that appears when you try to roll the PokeStop is "try again later", I think that's what changed the game without I recall, did not show any mesage when I was in soft ban

**Comment by lkhgamer** [comment]
botting or not is your own choice.
if you are afraid to get ban, so dont use the bot. 
as for me, still using it wheter its getting ban or not.

**Comment by xebia0x539** [comment]
my google Account is still working. With the PTC account (if i logout before), i get an Server Error. It possible just could be an Authentication error with the PTC System.

Has anobody tried an other ptc account?

**Comment by DagooNn** [comment]
NOT A BAN checked acc. with NO DATA FROM SERVER by logging to other acc and checked GYMS .... all poke from acc with problem are still there.

**Comment by ewaah** [comment]
i can get in to my acc, using bluestacks, and i can see all te stops, but the image is black and i always get the message pls try again later, so i really dont know whats next

**Comment by ewaah** [comment]
and i put an new acc in place on same ip and its botting just fine
