### ISSUE TITLE
Question about Lucky egg

### ISSUE THREAD

**Issue by fbinsale** [NECROBOTIO/NecroBot#5389]
I have a general question please. Many Pokemon go bot support lucky egg for 2x XP
Like a button to click to use lucky egg etc....

So my question please could I use lucky egg throw the Necrobot? like adjust some Necro files to make it use lucky eggs always or something like that.

Thank you so much

**Comment by iHatePython** [comment]
This is not the place for general questions, it's for reporting issues with the bot, that being said, yes you can, open the config file and read it, it's in English

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
