### ISSUE TITLE
unban over 45/45 but it not unban me

### ISSUE THREAD

**Issue by holalala** [NECROBOTIO/NecroBot#5391]
over 45 unbaned , but i'm still banned, can't catch or do anything. help

**Comment by Rictorus** [comment]
change IP, works fine

**Comment by SparkzZone** [comment]
I have same issue changing ip does nothing

**Comment by kevinx7** [comment]
@SparkzZone  same +1

**Comment by frager45** [comment]
start after ban all time ban...

**Comment by holalala** [comment]
another account working, but my main account can't left ban, huhu , change ip doesn't help

**Comment by WaterFl0ws** [comment]
i think there is also a charban, wait, for 1 or 2 hour then change IP and login via official pogo

**Comment by Rictorus** [comment]
are people using proxies or vpn programs? I am using Hotspot VPN to change its worked fine for me. my home IP has been blacklisted the last couple days and i get softbanned within minutes using it.

Maybe proxies is broken?

**Comment by parthroxx** [comment]
#5388

**Comment by recon88** [comment]
You are most likely banned. Try again in a few hours or try changing your ip-
