### ISSUE TITLE
Deleting very high cp Pokemon due to lower iv how do I change this?

### ISSUE THREAD

**Issue by chrisj420** [NECROBOTIO/NecroBot#5393]
I saw on the bots output that it deleted a 760 evee(my highest one was 250) just because the iv was lower than a 250 cp evee, how do I change the code so it deleted by cp and not iv

**Comment by necr-0** [comment]
Set _PrioritizeIvOverCp_ to _false_.

**Comment by chrisj420** [comment]
It was already set to false

**Comment by elmaarmut** [comment]
Use:
  "KeepMinCp": 0,

**Comment by chrisj420** [comment]
It's still deleting higher Cp Pokemon after changing both of these settings

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
