### ISSUE TITLE
be safe guys (new soft ban update)

### ISSUE THREAD

**Issue by SparkzZone** [NECROBOTIO/NecroBot#5397]
It appears  that there is a new type of ban happening. It does not appear to be an IP-ban, rather an account one. There is not many details yet, it is all a mix of speculations and rumors, but there is definitely something happening. 
Other bots appear to have been hit harder than MobBot users. 
This may be related to high-EXP configuration. As more information comes in and is confirmed, we will keep you updated. At this time, it is suggested to only use low-EXP config (45K/h or less). 

Stay safe and bot smart, use your best judgement but don't be surprised if something turns out to be permanent. We are not saying permanent bans are guaranteed, just that they are a possibility.

We will continue bringing updates to further increase your chances of security, hopefully we can figure out what this is soon enough so we can make sure you guys can bot safely.

**Comment by PokeNuke** [comment]
if I try to logIn on iphone it says: "player data could not be retrieved from the server"
is this a permaBan?

**Comment by heokp983** [comment]
@pokenuke a lot of account had same ur issue

**Comment by VincentHui** [comment]
I've been having it as well. I've set up a new bot and will monitor its behaviors. Hoping for soft ban expecting a perma-ban. Keep botting

**Comment by cykablyater** [comment]
some say that people who have never used bot have the same issue

**Comment by parthroxx** [comment]
#5388

**Comment by charlieswb** [comment]
@cykablyater yep my brother never use bot but also get the "player data could not be retrieved from the server" warning.

**Comment by geo333** [comment]
botting account doesnt work, i log in but pokestops dont work, says try again later no matter what.
other account that i have never botted on is just fine.

**Comment by djodiek** [comment]
me if want battle gym "error" what this is ban?

**Comment by hoodude** [comment]
the message that appears when you try to roll the PokeStop is "try again later", I think that's what changed the game without I recall, did not show any mesage when I was in soft ban

**Comment by ProDoser** [comment]
Just tried the bot. Works for me ;) Try to change IP, restart the bot. For the first few IPs I've got "(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?" 
![necrobot](https://cloud.githubusercontent.com/assets/16388272/17616405/309853be-607d-11e6-8438-1470af5bd9b6.JPG)

**Comment by mufclaw** [comment]
my new softban is odd when you spin pokestop it says try again later and ive span it about 100x and still cant loot other accounts work fine i hope im wrong but if this is a new soft ban we will have to be very careful whilst botting
