### ISSUE TITLE
ConfigSetting: How does the Moves transfer filter function work now with the addition of DeprecatedMoves

### ISSUE THREAD

**Issue by slxdegrees** [NECROBOTIO/NecroBot#5398]
As per title.

**Comment by rnsblue** [comment]
"Moves" = moves you want your pokemon to have
"DeprecatedMoves": = moves you **don't** want your pokemon to have

example:
    "Dragonite": {
      "KeepMinCp": 1,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 5,
      "Moves":  [  "dragonBreath" ],
      "DeprecatedMoves": [ "hyperBeam"  ],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    }
Meaning, you'll keep Dragonites with either Dragon Breath & Dragon Pulse
or Dragon Breath & Claw.

**Comment by Rabelaiss** [comment]
Is this code good if I want Dragonites who have exclusively these 3 moveset Dragon Breath & Dragon Claw | Dragon Breath & Hyper Beam | Dragon Breath & Dragon Pulse? (I want Dragonites whose movesets contain one/two different moves (for example Steel Wing & Hyper Beam) to be transferred)

"Dragonite": {
"KeepMinCp": 2500,
"KeepMinLvl": 6,
"UseKeepMinLvl": false,
"KeepMinIvPercentage": 95.0,
"KeepMinDuplicatePokemon": 5,
"Moves": [ "dragonBreath","dragonClaw","hyperBeam","dragonPulse" ],
"DeprecatedMoves": [ "steelWing" ],
"KeepMinOperator": "or",
"MovesOperator": "and"

**Comment by rnsblue** [comment]
Any pokemon with any move listed in "DeprecatedMoves": will result in automatic transfer, since movesets are more important than iv/cp value.

But yes, with the "Moves": you've listed, you will keep all Dragonites with:
Dragon Breath & Dragon Pulse
Dragon Breath & Dragon Claw
Dragon Breath & Hyper Beam
But only if they are above 2500 CP or 95% IV

**Comment by Rabelaiss** [comment]
@rnsblue thanks man you really help
can you confirm that if i have one with Steel Wing but also with 2500+ CP or 95+ IV it will be transferred anyway ?

**Comment by rnsblue** [comment]
@Rabelaiss I mentioned this #5384 2 hours ago, what i didn't mention was it accidently transfered a 100% Vaporeon with best moveset, guess that's confirmation enough

**Comment by psentenac** [comment]
@rnsblue while i like your explanation, i can't find anywhere in the code something that tell me DeprecatedMoves is implemented. I'm sure i'm mistaken but could you where do you see this ?

**Comment by lalibi** [comment]
When my `config.json` auto converted top version 0.8.6, the `Moves` part became an array of arrays:

```
"Moves": [
        [
          "ironHead"
        ]
      ],
```

Does this have any significance, or it's just a converion glitch?

**Comment by slxdegrees** [comment]
@lalibi it's not a conversion glitch. Config can now only be read like that now. Changing it back to what it was previously will result in an exception.

**Comment by lalibi** [comment]
So, you can now declare pairs of move (movesets) you would like to keep?

```
"Moves": [
  ["move1", "move2"],
  ["move1", "move3"]
],
```

**Comment by Rabelaiss** [comment]
@psentenac i think its this https://github.com/NECROBOTIO/NecroBot/commit/e480da0e36de223580450e99e791e5d6cc08e37e

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
