### ISSUE TITLE
the bot transferred all my best pokemon!

### ISSUE THREAD

**Issue by ZHUYUEHAN1** [NECROBOTIO/NecroBot#5402]
![image](https://cloud.githubusercontent.com/assets/20943012/17615634/86a5e352-60aa-11e6-8865-0c0ecad68a26.png)

what happend?

"KeepMinCp": 600,
  "KeepMinIvPercentage": 85.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or", //what did this mean?
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,

///////////

  "TransferWeakPokemon": true,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by Arcticon** [comment]
The ["TransferWeakPokemon": true] is your problem!
Change it to false.

**Comment by iHatePython** [comment]
And the minimum IV

**Comment by FirstDestro** [comment]
And your MinCP is 600 and minIV% is 85, from what i see non of your transferred pokemons are above 600 CP and IV 85%

**Comment by ZHUYUEHAN1** [comment]
@FirstDestro
what if I had a CP500 IV 90?  is it will be trandferred?

**Comment by zzxxzzxxSG** [comment]
I won't Use
"TransferWeakPokemon": true,
It's a disaster when other config note set properly

**Comment by FirstDestro** [comment]
@ZHUYUEHAN1 yes it will, in most application settings it reads form the top to bottom.
So if you get a pokemon with a value on CP500 IV 90
Necrobot will read the first value from the top.

**Comment by qwer4790** [comment]
You call these "best pokemons"? 
They should be transferred.

**Comment by zzxxzzxxSG** [comment]
NO, it will not transfer.

"KeepMinCp": 600,
"KeepMinIvPercentage": 85.0,
"KeepMinLvl": 6,
"KeepMinOperator": "or", <---- Either Min IV or Min CP will keep
"UseKeepMinLvl": false, <--- It does not check For MIN Level
"PrioritizeIvOverCp": true, <---- Since Prioritize is IV, It will check IV
"KeepMinDuplicatePokemon": 1, <--- Only 1 Pokemon is Kept

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
