### ISSUE TITLE
The Bot do not catch any pokemon, all of them like catchflee!

### ISSUE THREAD

**Issue by Norb15** [NECROBOTIO/NecroBot#5403]

**Comment by LawMarcos** [comment]
Same is for me, i can get pokéstops but no pokémon, why?

**Comment by chohitoshiri** [comment]
which version you use ? 0.1.7 or 0.1.6 or 0.1.8 ?

**Comment by Norb15** [comment]
0.8.6

**Comment by Norb15** [comment]
Sorry!

0.8.5 and update every start to 0.8.6

**Comment by LawMarcos** [comment]
![image](https://cloud.githubusercontent.com/assets/20958496/17615997/e7f8a34e-603f-11e6-9d66-bc2ba6e25735.png)
Damn, i think is a half permanent soft-ban.

**Comment by LawMarcos** [comment]
I tried this config in another account, and it catches pokémon, but here all flee.

**Comment by parthroxx** [comment]
#5388

**Comment by spamfighter82** [comment]
Same here, Pokestops are working though

**Comment by Gabossxd** [comment]
I also have this problem :(

**Comment by saar95** [comment]
Same here
Is this a perament ban? there a way to solve it?

**Comment by chiko28** [comment]
new softban by niantic maybe, to prevent farming pokemons, but still gain exp on spinning pokestops to prevent removal of softban.. this also apply on lower versions of bots think so, since im using lower version :3

wish someone could find solution with this problem :3

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.

Also check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
