### ISSUE TITLE
necrobot not updating to 0.8.6

### ISSUE THREAD

**Issue by linkin2011** [NECROBOTIO/NecroBot#5404]
anybody else having a problem updating necrobot
says downloading update then logs into server

**Comment by parthroxx** [comment]
Yeah

**Comment by lostodyssey** [comment]
Same here, keeps updating all the time

**Comment by chohitoshiri** [comment]
You can manual download the 0.8.6 version.

**Comment by Brainenigma90** [comment]
https://github.com/NECROBOTIO/NecroBot/releases
 manually download it for now

**Comment by linkin2011** [comment]
yeah iv manually downloaded it

**Comment by sayabudi** [comment]
Maybe, it is because the file name for latest version is Release_0_8_6.zip, but the bot searching for Release.zip (usual file name) that is why you need to manually download it.
