### ISSUE TITLE
failed to get data from server

### ISSUE THREAD

**Issue by Carlosnwade** [NECROBOTIO/NecroBot#5405]
Is this a ban? if so about how long are these bans?

**Comment by Deuxgod** [comment]
There's no concrete info regarding that at this moment. It can be a permanent ban, a temporary one or no ban at all, just servers down or overloaded.

**Comment by blackuGT** [comment]
Yup... servers down http://www.mmoserverstatus.com/pokemon_go

**Comment by fuckNIANTIC** [comment]
It's a perm ban. Niantic didn't make a screen which say you have been ban, to hopefully crack your other accounts in this wave. I would stop bot until necro has a stable release

**Comment by pixerx** [comment]
No, its not ban. Work fine in my phone, suspected IP ban only.

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

You are permanently banned.
