### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CrispyBaconUk** [NECROBOTIO/NecroBot#5406]
![image](https://cloud.githubusercontent.com/assets/20986077/17615825/a5277e4a-6068-11e6-8fb5-6d632b607e28.png)

Am wondering if this is because the servers may be down in the US?
Anyone else able to test with the lat and long?

  "DefaultLatitude": 37.773972,
  "DefaultLongitude": -122.431297,

**Comment by Disane87** [comment]
#5388
