### ISSUE TITLE
Cannot connect to telegram anymore at 0.8.6

### ISSUE THREAD

**Issue by Festum** [NECROBOTIO/NecroBot#5408]
[15:26:53] (ERROR) Unkown Telegram Error occured.

Do I need to fill field TelegramPassword? How? Please update to Wiki.

**Comment by Kampring** [comment]
me too ,
 what telegram password ???

**Comment by iHatePython** [comment]
If you don't know what it is why are you trying to use it? The bot works fine without it

**Comment by sing1222** [comment]
@iHatePython Would you mind teach us?
I also have same problem.

**Comment by theloser** [comment]
Telegram is not working with 0.8.6, it's broken. Go back to 0.8.5. or wait until it's fixed. I suggest turning Telegram API of for now.

Also Duplicate of #5323
