### ISSUE TITLE
BAN WAVE PERM HAS STARTED

### ISSUE THREAD

**Issue by fuckNIANTIC** [NECROBOTIO/NecroBot#5409]
BANWAVE HAS STARTED BECAUTIOUS. 1/10 of my accounts got hit, if you got hit with it you will find unable to login on your phone, you will receive a message of 'Unable to receive player data' and the app just stops, in the loading screen.

**Comment by parthroxx** [comment]
#5388

**Comment by fuckNIANTIC** [comment]
So they can crack your other accounts in this wave. If they say ban, you will know about it and hence stop your other accounts. They're shifty fucks I know

**Comment by fuckNIANTIC** [comment]
It's not server issue, I'm from Australia. So I can clear that up

**Comment by PokeNuke** [comment]
did someone try to create a new acc. with same login data as "banned" acc.?

**Comment by fuckNIANTIC** [comment]
I would imagine you couldn't because you have created with that user before. They would most likely blacklist your email with it

**Comment by fuckNIANTIC** [comment]
Stay safe. The bot currently isn't running at a pace where it's worth to take the risk. Until necro release a bot which is efficient it's not worth the risk involve.

**Comment by r3n3gatu** [comment]
work ok with 40k xp/h . beside i create a new acc till  the ban problem somehow is fix . i`m not using my main now . i sugest do the same :)

**Comment by SparkzZone** [comment]
stop saying its a perma ban ITS NOT if it was it would say account banned and you would be e-mailed this is a new soft ban

**Comment by fuckNIANTIC** [comment]
Ok spark do what you like. Why would Niantic need to tell you ur account is ban? Isn't it similar to player data could not be retrieved?

**Comment by zzxxzzxxSG** [comment]
When it started in Germany, i always have that warning pop up.
It's the server unstable that is causing that prompt. But might have changed.

**Comment by SparkzZone** [comment]
check server status a lot of servers are down right now this is simply a combination of soft ban and server issues until its confirmed you shouldn't say its a perma ban you just make people panic

**Comment by baalij** [comment]
This is for sure a ban. But if it is perma ban... we dont know yet.

**Comment by fuckNIANTIC** [comment]
Imy country server is running fine being in the other side of the world, and since when is US server stable anyways if there's where your from

**Comment by SparkzZone** [comment]
I'm from uk and I have the pokestops not working but can catch pokemon and I can log in on my phone I can upgrade pokemon so sory but this is just a new wave of soft ban imo

**Comment by fuckNIANTIC** [comment]
If server has issue it will have a different screen which says server is currently facing issues (that screen with a lot of Pokemon on it) but that's not the case, my country server is doing fine.

**Comment by SparkzZone** [comment]
Well I'm waiting till there is confirmation cos like I said I ain't getting that screen it seems to be different for a lot of people God knows what's going on

**Comment by kurozani** [comment]
my GOOGLE EMAIL account got this so I made a PTC account with my email, I can log in, hhaa
but started at level 1

**Comment by FVKUALL** [comment]
So many people in my areas stop playing because of thinking this is perma ban, continues with uninstalling the PokemonGo app.

**Comment by pixerx** [comment]
I cant log in with bot(same issue), but it works fine in apps,..lol...so its not ban.

**Comment by lkhgamer** [comment]
If you dislike the game or niantic action, just uninstall it. #simple

**Comment by WishmasterNano** [comment]
some people who got "banned" could create new acc. with the same email and username, so the old acc. are already gone..

cant check it myself because luckely none of my acc. have this login "problem"

**Comment by SparkzZone** [comment]
See I can log in and catch Pokemon and evolve transfer anything but I can't fight gyms or spin pokestops so I don't think I'm banned

**Comment by lemissime** [comment]
Dunno if it's a ban, a soft ban or a server issue but since I started to snipe, with the same "slow farm" settings as always, I'm not able to connect with my bot account. I got 'Unable to receive player data' message. I can connect with any of my other vanilla accounts.

**Comment by Markersx** [comment]
Im not banned 
![](http://i.imgur.com/RHXng7j.png)

**Comment by lemissime** [comment]
Still, you're not using the snipe feature.

**Comment by siimveskilt** [comment]
LOL at @Markersx  SS with every pokemon fleeing. Nice ban!

**Comment by elmaarmut** [comment]
@Markersx LMAO you ARE banned you dimwit.

**Comment by kurozani** [comment]
play safe for now

walking human, humanize throw, slow km/h hhaaa

**Comment by DagooNn** [comment]
NOT A BAN checked acc. with NO DATA FROM SERVER by logging to other acc and checked GYMS .... all poke from acc with problem are still there.

**Comment by kurozani** [comment]
really??
I do want to check if my pokemon is still in the gym, I'll check it

**Comment by WishmasterNano** [comment]
@DagooNn did you try to create a new acc with the same credentials as the "no data from server" acc.?
just curios, because some people tell that they were able to do this

**Comment by Markersx** [comment]
@elmaarmut @siimveskilt I just relized.

**Comment by DagooNn** [comment]
how to creata acc. with google again think can't

**Comment by WishmasterNano** [comment]
oh thats probably right... maybe try to register a ptc acc. with this gmail address?

**Comment by DagooNn** [comment]
I prefere to wait as http://www.mmoserverstatus.com/pokemon_go    IN RED in my cantry
