### ISSUE TITLE
We cannot get pokestop anymore.

### ISSUE THREAD

**Issue by agustyn7** [NECROBOTIO/NecroBot#5411]
There are many pokestop but we can not get item.

**Comment by andreseveres** [comment]
perhaps soft ban

**Comment by Disane87** [comment]
could be #5388

**Comment by Tupilak** [comment]
You might be ban. It's working fine here.

**Comment by agustyn7** [comment]
yes but it does not solve soft ban i can catch pokemon but pokestop does not give anything.

**Comment by kayosetsu** [comment]
My IP's kept getting blacklisted. Had to switch VPN servers 3 times before I decided to go back to the old version. No problems anymore. Can't speak for everyone else, but the newest update was problematic for me. The likely issue is that your IP got blacklisted. Use a VPN if you're not already, try going back to the old version if you still got it in your recycle bin or whatever and try again.

**Comment by ShingShangFu666** [comment]
same problem here 1hr no pokestop

**Comment by kayosetsu** [comment]
Try what I said above and tell me if it works for you

**Comment by blasko87** [comment]
What do you mean by old version? 0.8.5?

**Comment by s1x** [comment]
Seems like IP Bans.

**Comment by agustyn7** [comment]
i restarted my router 10 times we can catch pokemon but pokestops dont give item. but we dont have ball anymore

**Comment by blasko87** [comment]
I tried VPN connections, doesnt work...

**Comment by kayosetsu** [comment]
Yeah I meant 0.8.5

**Comment by tggiml** [comment]
I did go back to 0.8.5 doesn't work. still show me 'try again later' but can still catch pokemon! but $$ for balls from now on...

**Comment by kayosetsu** [comment]
Are you talking about when you play the game from your phone you get the "Try Again Later"?

**Comment by tggiml** [comment]
no, not the phone. I use Bluestack. is it possible to use phone to get me out from this issue?

**Comment by kayosetsu** [comment]
If you're playing the game and running the bot at the same time, that may be the problem

**Comment by tggiml** [comment]
actually I don't use my phone to play pokemon only laptop with bluestack.. T T man.... I almost reach max lvl. Why today .........

**Comment by kayosetsu** [comment]
I know. I mean if you play pokemon go at all and use the bot simultaneously

**Comment by tggiml** [comment]
I personally did used my phone upto lvl 25.. but when my friend reach my lvl overnight with bot......... my mind blow away.

**Comment by kayosetsu** [comment]
With all due respect, we're getting sidetracked here. Run the 0.8.5 bot along with a VPN without playing the game at all for about 10 minutes and see if the bot works perfectly fine.

**Comment by tggiml** [comment]
any particular VPN you recommand?

**Comment by kayosetsu** [comment]
I've only ever used Private Internet Access, and if I remember correctly there's no free trial for it. Though for now, try any

**Comment by tggiml** [comment]
okay got it. thanks Kayosetsu!

**Comment by kayosetsu** [comment]
You're welcome! Let me know if it works for you

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
