### ISSUE TITLE
Need tutorial 0.8.6 

### ISSUE THREAD

**Issue by djodiek** [NECROBOTIO/NecroBot#5412]
I search everywhere cant find tutorial ..
and much not working

**Comment by linkin2011** [comment]
use the new interface on necro config

**Comment by djodiek** [comment]
not working

**Comment by linkin2011** [comment]
have u manually downloaded 0.8.6

**Comment by AllUpps** [comment]
we need wiki update for config settings. and also mention or remove settings that just dont work like:
  "SnipeIgnoreUnknownIv"
  "SnipePokemonNotInPokedex"
and alsow rename is pokemon is not working, if i renamed them manually

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
