### ISSUE TITLE
Google Two Factor Auth Enabled.  you will need insert an App Specific Password into the Auth.json

### ISSUE THREAD

**Issue by transteam** [NECROBOTIO/NecroBot#5417]
Not really an issue, 
Since i got banned. made a new account.
I dont have 2 factor enabled on this new email, but its asking for one.  
how and where do i make App Specific Password into the Auth.json
can anyone help.

**Comment by venduss** [comment]
Enable 2 factor auth and visit https://security.google.com/settings/security/apppasswords?utm_source=OGB create an app specific password. When you create it, write it to "GooglePassword": "HERE". This should work.

**Comment by transteam** [comment]
ooo 
thank you

**Comment by athena93** [comment]
hello im new here, can i know what that for? to run 2 bot at a same time?

**Comment by transteam** [comment]
it seems like a separate password for connected app to google account.  you just add the app name and google generates a password for it.

**Comment by athena93** [comment]
ohh like that. already doing two folder. another folder always say please insert google and passwords.
