### ISSUE TITLE
softban will not get bypass

### ISSUE THREAD

**Issue by sammyloy** [NECROBOTIO/NecroBot#5422]
any problem out there?

**Comment by Markersx** [comment]
use minimum settings for example 15km/h and no sniping

**Comment by athena93** [comment]
no sniping means? can u show me the command

**Comment by sammyloy** [comment]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1500.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 35.6328964,
  "DefaultLongitude": 139.8803943,
  "WalkingSpeedInKilometerPerHour": 15.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 0,
  "DelayBetweenPokemonCatch": 0,
  "DumpPokemonStats": true,
  "EvolveAboveIvValue": 1.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 500,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "and",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": true,
  "UseIncenseConstantly": true,
  "UseBerriesMinCp": 0,
  "UseBerriesMinIv": 0.0,
  "UseBerriesBelowCatchProbability": 0.0,
  "UseBerriesOperator": "and",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 300,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 100,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": true,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 30000,
  "TotalAmountOfPokeballsToKeep": 250,
  "TotalAmountOfPotionsToKeep": 20,
  "TotalAmountOfRevivesToKeep": 20,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1000,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 80.0,
  "UseUltraBallAboveIv": 90.0,
  "UseGreatBallBelowCatchProbability": 0.0,
  "UseUltraBallBelowCatchProbability": 0.0,
  "UseMasterBallBelowCatchProbability": 0.0,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": false,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": true,
  "ItemRecycleFilter": [

**Comment by sammyloy** [comment]
continuous looting fail bypass not successful

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
