### ISSUE TITLE
SOFBAN 45/45

### ISSUE THREAD

**Issue by reckless17** [NECROBOTIO/NecroBot#5424]
(SOFTBAN) Name: NOAA Weather Station Central Park INFO: Looting failed, possible softban. Unban in: 45/45

How do I solve this problem?1 I'm using bots and 1 account.

**Comment by Markersx** [comment]
Use minimum settings for example 15km/h no sniping

**Comment by reckless17** [comment]
I set it, but I still did not open the soft ban

**Comment by parthroxx** [comment]
#5388

**Comment by reckless17** [comment]
You can log in to the game through BlueStacks.but when I entered the ban does not turn soft necrobot

**Comment by iHatePython** [comment]
@parthroxx Stop referencing your useless post everywhere, your post isn't an issue therefor it doesn't belong and it doesn't offer any help nor a solution to the problem.

**Comment by kayosetsu** [comment]
My IP's kept getting blacklisted. Had to switch VPN servers 3 times before I decided to go back to the old version. No problems anymore. Can't speak for everyone else, but the newest update was problematic for me. The likely issue is that your IP got blacklisted. Use a VPN if you're not already, try going back to the old version (0.8.5) if you still got it in your recycle bin or whatever and try again.

**Comment by kayosetsu** [comment]
Just gonna copy/paste this until someone can confirm whether or not it works for others too

**Comment by tuahwp** [comment]
@kayosetsu im using EASY-HIDE-IP to change ip but limited 3 days only.. works great when i do stupid thing to softban.

**Comment by kayosetsu** [comment]
Did it work for you?

**Comment by reckless17** [comment]
(ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
(ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)

giving this error when I use VPN?

**Comment by kayosetsu** [comment]
You have 2 step authentication enabled on your google account. You'd have to turn it off most likely

**Comment by reckless17** [comment]
2-step verification is already closed.but the above error continues.

**Comment by kayosetsu** [comment]
Strange. It could probably be the VPN. I'm using Private Internet Access. What about you?

**Comment by reckless17** [comment]
OkayFreedom,Easy-HideIPVpn.I tried them

**Comment by kayosetsu** [comment]
Strange. Run without a VPN real quick and see if it'll log in without problems

**Comment by Dr-Death** [comment]
i got this when i run multi necrobot from the same pc

simply restart your router to get a new ip, and only run one account.

or you can use TOR proxy and get a new identity every time you got ip ban

**Comment by recon88** [comment]
Get a new IP and only run 1 bot.

**Comment by idkwateva** [comment]
Can't find pokestop even on my phone... there are so many angry folks at social media...
