### ISSUE TITLE
Catchflee for every pokemon sniped, can someone tell me what is happening ( Not softbanned ) 

### ISSUE THREAD

**Issue by Blaucide** [NECROBOTIO/NecroBot#5425]
![catchflee](https://cloud.githubusercontent.com/assets/20920779/17617052/10886d34-6078-11e6-82a1-1551ae58a52a.jpg)

**Comment by Markersx** [comment]
Niantic possibly fixed sniping and you should turn it off if you want to lower your chances of getting banned.

**Comment by Blaucide** [comment]
Some ppl are sniping without problems

**Comment by vvvsrx** [comment]
me too!
thx for @Markersx

**Comment by Doc5az** [comment]
same problem,is there another way to sniping without catchflee the pokemon?

**Comment by tuahwp** [comment]
my snipe still work.

**Comment by Ravenisking** [comment]
mine too cant catch a pokemon but pokestops works, i tried the game on my phone and all pokemons i tried to catch flee's, is this a softban?

**Comment by andre1974** [comment]
Same here

**Comment by tuahwp** [comment]
but this snipe catch low CP and IV.. pokesnipe2 can catch high CP with nice IV.. idk why

**Comment by AlexisjrFreitas** [comment]
Same here, pokestops works fine, but to catch any pokemon they fleeing.

**Comment by Zenex61** [comment]
Same here.

**Comment by emjey23** [comment]
Same probleme here with my one account, but my other account works fine.
So I think, it may be perma-ban or hard-ban?

**Comment by Ravenisking** [comment]
hope its not lets try it after 2 hrs

**Comment by emjey23** [comment]
perma ban i think

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
