### ISSUE TITLE
Snipe Delay No Working

### ISSUE THREAD

**Issue by K0D1NGL10N** [NECROBOTIO/NecroBot#5426]
"MinDelayBetweenSnipes" not working properly.

### Expected Behavior
After a pokemon sniped it should delay for x/1000 secs.

### Actual Behavior
It will keep sniping I dunno why.
BTW, nitanic update their ban logic and it seems this leads to a serious problem.

### Your config.json
```
  "MinDelayBetweenSnipes": 20000,
  "DelayBetweenPlayerActions": 2500,
  "DelayBetweenPokemonCatch": 4000,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
```

### Other Information
Version: 0.8.5
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by iHatePython** [comment]
Its minimum delay between sniping and other actions, your settings mean the bot starts sniping once every (20 seconds?) I believe, I'm not sure if its in ms

**Comment by K0D1NGL10N** [comment]
Yes but the problem is, after a successful snipe the bot will keep sniping without a delay (maybe till the list got from location server end.)
I think this may cause ban problem.

**Comment by recon88** [comment]
We are working on solutions and suggest not to snipe currently.
