### ISSUE TITLE
[NOT SOFTBAN]Can't catch any pokemon but pokestops work

### ISSUE THREAD

**Issue by davidzhaozdw** [NECROBOTIO/NecroBot#5427]
Can go to pokestop and get items. But everytime catch a pokemon, that pokemon will escape. No matter I use a bot or go out and catch myself.

**Comment by davidzhaozdw** [comment]
BTW I've already turned off snipe.

**Comment by Akilestar** [comment]
I have this same issue.

**Comment by spamfighter82** [comment]
same here

**Comment by thegodwarrior** [comment]
same problem

**Comment by 3HMonkey** [comment]
same

**Comment by LawMarcos** [comment]
same

**Comment by emjey23** [comment]
I have the same issue. (Can get items from pokestop but everytime my bot tries to capture pokemon, it flees)

My bot configs:
1. Using VPN (ofcourse, its different from my actual IP)
2. Using Sniping Pokemon (with Pogo Feeder) + Catching Pokemon
3. Walking Speed is 30kph

I also tried changing everything i could think like,
-changing IP from my vpn / going back to my real IP
-changing/lowering config values
-disabling sniping

I think it is Perm-Ban or Hard-Ban? 
So, be careful, i think Niantic is making their move for those not playing fair. =)

**Comment by davidzhaozdw** [comment]
Same here. Changing IP doesn't work.

**Comment by saar95** [comment]
Same here

**Comment by ridoknight** [comment]
same here

**Comment by polypalm** [comment]
SAME

**Comment by Gabossxd** [comment]
same here

**Comment by dratinie** [comment]
same here.. anyone can help me out?

**Comment by ipkpeople** [comment]
It's perma ban boys. We are all doomed. I waited 10 hours but the alleged "soft-ban" hasn't been removed.

**Comment by emjey23** [comment]
@ipkpeople sad for us.

**Comment by burntable** [comment]
:(
My other accounts are not affected (yet).
Apparantly they delete bot accounts aswell.

**Comment by daviwesley** [comment]
same here

**Comment by thejoker04393** [comment]
Is it soft ban or permanent ban.... ???

**Comment by ipkpeople** [comment]
@thejoker04393 Anyone who botted yesterday will get either of these 2 perma bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon)

**Comment by thejoker04393** [comment]
Ok then it's permanent ban :-(

**Comment by recon88** [comment]
You are banned, right

**Comment by davidzhaozdw** [comment]
@recon88 is it permanent ban or softban?

**Comment by recon88** [comment]
Wait some hours and try again.
