### ISSUE TITLE
Auth.json google login ?

### ISSUE THREAD

**Issue by Hackflag** [NECROBOTIO/NecroBot#5428]
When i launch the application, they ask if i want to update it, when i say yes or no, they say:

"you need to fill in your google name and google password in auth.json"

 but the thing is, in auth.json, my username and my password is correct..

**Comment by iHatePython** [comment]
Post your auth.json, only remove your user and pass

**Comment by 3HMonkey** [comment]
it will work after installing this: https://www.microsoft.com/de-de/download/details.aspx?id=48145

**Comment by marnixx9** [comment]
I installed that thing @3HMonkey  but it is still not working. im getting same error

**Comment by marnixx9** [comment]
this is my auth.json https://gyazo.com/7fd7b4bb184f5376e60d40ce4aff09e5

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
