### ISSUE TITLE
[0.8.5] Update function doesn't seem to work

### ISSUE THREAD

**Issue by sgtstrider** [NECROBOTIO/NecroBot#5430]
### Expected Behavior

Update function to work when I enter "Y".

### Actual Behavior

It downloads the zip, but then continues with the original version, and doesn't update.

### Your config.json
```
N/A
```

### Steps to Reproduce

Update from 0.8.5.

### Other Information

Just fyi, I manually updated though. Other machines have the same problem.
![error_update](https://cloud.githubusercontent.com/assets/20833783/17617283/9179d86e-6079-11e6-81e6-0ab7244ccba3.png)

**Comment by iHatePython** [comment]
Already mentioned before, do a manual update until its fixed.

**Comment by sgtstrider** [comment]
Hm, didn't notice. Just FYI.

**Comment by minseedsa** [comment]
u need manual Bro .
