### ISSUE TITLE
help for location,

### ISSUE THREAD

**Issue by JokerQuinzzel** [NECROBOTIO/NecroBot#5431]
hello everybody, may i know why does my NecroBot keeps on saying,
"(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?"
i have been changing my locations a lot of times but it keeps on appearing this,
and i have updated the latest version,
can anyone help me solve the problem?

**Comment by iHatePython** [comment]
Softban, fix it and try again, use QuickSpin, Google it.

**Comment by JokerQuinzzel** [comment]
can you help me elaborate to me please? i am new to this.

**Comment by iHatePython** [comment]
QuickSnipe, Google it, read about it, use it.

**Comment by JokerQuinzzel** [comment]
hey, thanks for the help man! i have finally solved it, thank you very much again.

**Comment by JokerQuinzzel** [comment]
hey, thanks for the help man! i have finally solved it, thank you very much again.

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
