### ISSUE TITLE
Wont open anymore

### ISSUE THREAD

**Issue by 212vix** [NECROBOTIO/NecroBot#5433]
The bot simply won't start anymore, I am receiving a message everytime I open the program "necrobot client for pokemon go has stopped working"
In the bot interface I can read some stuff like:not able to load System.Security.Authentication

**Comment by iHatePython** [comment]
Good thing you can read some stuff there, now start reading some stuff here, specially the issues page where you posted this one.

**Comment by 212vix** [comment]
Well, I did, everyone with the same problem as me got ignored... would you mind posting a reference?

**Comment by 3HMonkey** [comment]
post s screenshot pls

**Comment by 212vix** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/20987069/17617831/9946aaee-6052-11e6-8728-525026dfdf54.jpg)

**Comment by AutopsyMania** [comment]
![necrobot0 8 6](https://cloud.githubusercontent.com/assets/3266663/17617909/e0156210-607c-11e6-8832-a4dcab7a58e6.png)

**Comment by Dr-Death** [comment]
try to download and use a fresh release, i got this error if i have a misconfiguration in auth or config.

like forget to and "," after a value.

**Comment by 212vix** [comment]
using the  default and got this

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.
