### ISSUE TITLE
Config for evolving Pokemon

### ISSUE THREAD

**Issue by andele123** [NECROBOTIO/NecroBot#5434]
Good morning,

I have a problem regarding my config.
I want to change the config for keeping Pokemon until a specific limit and then using a lucky egg for evolving them all.
At the moment, the bot evolves all Pokemon directly after having enough candies.

**Comment by Cyruz007** [comment]
You just wrote the solution yourself :)
Change the percentage as you wish.

  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,

**Comment by andele123** [comment]
Doesn't that mean the Bot will never evolve any Pokemon?

**Comment by andele123** [comment]
The Bot is still transfering all Pokemon that can be evolved...

**Comment by Cyruz007** [comment]
It will evolve when it reaches 90%
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

It will still transfer pokemons until it has enough candy to do a complete evolve

**Comment by andele123** [comment]
Aaaah okay, thank you :+1:

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
