### ISSUE TITLE
bot 0.8.6 doesn't work

### ISSUE THREAD

**Issue by Coca50** [NECROBOTIO/NecroBot#5437]
I update the bot, reinstall everything nothing work : 

[10:54:31] (ERREUR) Pokemon Servers might be offline / unstable. Trying again...
[10:54:32] (ERREUR) Error: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()

**Comment by janga11** [comment]
mine works perfect

**Comment by hclivess** [comment]
I get error 141 and the window does not even open

**Comment by Coca50** [comment]
So i will dowload it and reinstall it again...

**Comment by Disane87** [comment]
see #5388

**Comment by Coca50** [comment]
This what i'm checking i will tell you more after testing !

**Comment by aommiez** [comment]
![2016-08-12_155735](https://cloud.githubusercontent.com/assets/1967790/17617729/e616e598-60a5-11e6-9713-179e59326179.png)

8.6 good for me

**Comment by gozonjoedaimar** [comment]
same issue here, Pokemon Servers might be offline / unstable. Trying again...

**Comment by Coca50** [comment]
I have launch pokemon go on nox and he can't conenct : Failed to get data from the server

So it's niantic servers problem i think and not perma ban !

**Comment by hughie123** [comment]
my windows worked for the 8.5 but closes the 8.6?

**Comment by Coca50** [comment]
you have to update this for 0.8.6 :  https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by gozonjoedaimar** [comment]
already did, but still the same

**Comment by sianyuw7** [comment]
yeah same with you Coca50 
I have launch pokemon go on my galaxy s7 and he can't conenct : Failed to get data from the server

**Comment by gozonjoedaimar** [comment]
also logged on my android phone and get Failed to get data from the server

**Comment by Coca50** [comment]
We have to wait i think !

Before i updated (on 0.8.5) i though i got the same problem so...

**Comment by Coca50** [comment]
Confirmed : 
![ss 2016-08-12 at 11 09 18](https://cloud.githubusercontent.com/assets/19392435/17617967/45972c86-607d-11e6-8903-6618f97997db.png)

**Comment by paulohdc** [comment]
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll' =/

**Comment by sianyuw7** [comment]
i don't understand with your picture coca

**Comment by gozonjoedaimar** [comment]
Coca50 what do you mean by confirmed?

**Comment by Coca50** [comment]
It is servers status, so they have connection problems (google login and pokeclub login)

**Comment by Coca50** [comment]
look at this : http://www.mmoserverstatus.com/pokemon_go

**Comment by recon88** [comment]
Server issues.
Also use the ticket template instead of removing it.
