### ISSUE TITLE
Always Softbanned?

### ISSUE THREAD

**Issue by Piels2** [NECROBOTIO/NecroBot#5438]
Hi guys,

I can catch pokemons if I had pokeballs, but I can't spin the pokestops anymore. Did I get a Ban? 

Hopefully somebody can help me, Im out of pokeballs so I can't catch anything at the moment..

This pic shows what my bot does constantly.

![kaak](https://cloud.githubusercontent.com/assets/20987357/17617683/bc212a70-607b-11e6-898d-3cba29a19deb.JPG)

N

**Comment by 7Hitnrun** [comment]
Probably, just try in 2 hours or so again. I had the same issue 2 days ago and i was able to use the bot after that period of time i said.

**Comment by xebia0x539** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5388

**Comment by SparkzZone** [comment]
@7Hitnrun are you sure it was the same thing can not bypass soft ban and can catch pokemon also can log in on mobile same situation cos I have the same thing and it seems a lot of people today got this at the same time as well as people reporting perma bans I just don't know what to believe

**Comment by kayosetsu** [comment]
From my point a view it seems to be a problem with the latest update. I'm trying to see if my solution work for others here #5411

**Comment by emjey23** [comment]
I remember when I had that issue, I tried changing my IP with VPN and it works.

**Comment by kayosetsu** [comment]
^Exactly what I did, though the VPN IP kept getting banned so I switched back to 0.8.5 too and now it's all good.

**Comment by Piels2** [comment]
So I have to use a VPN? Just another IP, because 0.8.5. give me the same problem.

**Comment by kayosetsu** [comment]
Yeah use a VPN along with 0.8.5. Your current IP is most likely banned

**Comment by Piels2** [comment]
But why can I catch pokemons with pokesniper? And not spin a pokestop? Sounds like a weird ban, if it's a ban ofcourse. It can't be, right?

**Comment by proyugi** [comment]
I have the same problem. It's not a normal ban. I try another accounts and everything is normal.

Change IP and change the location both don't work.

**Comment by kevintirtawinata** [comment]
Is it possible that Pokemon Go limit the number of the pokestop you loot each day?

**Comment by kayosetsu** [comment]
Nah. It's probably a new type of softban or a problem with the latest bot version. Or a combination of both. I'm headed to bed, hopefully the actual problem gets discovered by the time I wake up.

**Comment by proyugi** [comment]
@kevintirtawinata: you may be right, i rolled 4585 pokestops today.

**Comment by mpfourtz** [comment]
i cant spin pokestop, its says try again later, but i can catch pokemon, anyone have same problem like me?

**Comment by boXseven** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by proyugi** [comment]
@mpfourtz: i have the same problem with you
@Piels2 : ya, i actually don't know

**Comment by derkoenig** [comment]
servers are down/ in trouble! not necro or your problem! just wait for the servers to get stable again

**Comment by Piels2** [comment]
@boXseven so the servers are down! Just an update from Niantic? And for 3 hours?

**Comment by proyugi** [comment]
i had the problem from this morning, already 10 hours, i don't think the problem come from servers.

the other accounts work well.

**Comment by Piels2** [comment]
I need that stardust .. Somebody come with the solution please!
