### ISSUE TITLE
Can't log it since today

### ISSUE THREAD

**Issue by 7Hitnrun** [NECROBOTIO/NecroBot#5439]
![default](https://cloud.githubusercontent.com/assets/20987353/17618379/c0b07146-607f-11e6-8185-81dc63e7f412.jpg)

I saw some people have this issue but no clear answer if its a perma or temp ban or if its a necrobot issue or if its a server issue, i can log in with my google account wich i never used on necrobot but i cant with any of my bot ptc accounts. im trying to log in from my smartphone but it says something with there is no data or data delete or something like that.

**Comment by xebia0x539** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5388

**Comment by 7Hitnrun** [comment]
xebia0x539 this is not an aswer, i saw you posting this like 20 times. if you have infos then post them, if you just wanna link someone alses thoughts then stop it.

**Comment by Hackflag** [comment]
bro, delete is your ip is above there.

**Comment by ipkpeople** [comment]
THANKS FOR YOUR IP, EXPECT SOME SWAT ACTION SOON.

**Comment by 7Hitnrun** [comment]
i am at work, dont mind if you some shit hehehe

**Comment by xebia0x539** [comment]
Hey 7Hitnrun i don't want to answer 1000 Times. Just read the post or get back to work.in #5388 i posted some things i have tried.

**Comment by 7Hitnrun** [comment]
xebia0x539 you said things that i now :P, you think that its a ban, you are not sure, if i cant log in its obvious that im not using it :P no offence i just ask if someone knows for sure if its a perma ban

**Comment by 7Hitnrun** [comment]
New info, bot is working like a charm BUT with a new ptc, all my old ptc accounts are unable to log in so i just created a new to try and its working.

**Comment by sianyuw7** [comment]
so you meant your account get banned from niantic?

**Comment by ViezeVingertjes** [comment]
Yes, even people who did only try the bot once are getting banned as we speak.

**Comment by 7Hitnrun** [comment]
probably, niantic banned the accounts but its not 100% sure. i will get back to you after i try some things.

**Comment by recon88** [comment]
Duplicate, most likely banned. Try another device/ip
