### ISSUE TITLE
(PokeWatchers.com) Error converting value "Mr_Mime" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[1].pokemon', line 1, position 144.

### ISSUE THREAD

**Issue by sing1222** [NECROBOTIO/NecroBot#5440]
#4502 
>@nfettinger  Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.

>Please check your configurations!

I think this is an issue for code mistake. 
V.0.8.6 
(PokeWatchers.com) Error converting value "Mr_Mime" to type 'POGOProtos.Enums.PokemonId'. Path 'pokemons[1].pokemon', line 1, position 144.

**Comment by poutros** [comment]
Change Mr_Mime to mrmime in config file.

**Comment by sing1222** [comment]
I think it is not typing mistake in my config.
I think it is the code about PokeWatchers.com, but I don't know which file to correct it.
Would someone help?

**Comment by ReQuiem42** [comment]
Did you try what he said? I had the same problem, changed it to MrMime (like in the pokemon list in the bottom) and it fixed it.

**Comment by sing1222** [comment]
@ReQuiem42 Why I can catch MrMime form pokesniper or pokezz?
And I have already checked my config, it is ermine.
