### ISSUE TITLE
Account deleted by Niantic - Is this the end of botting?

### ISSUE THREAD

**Issue by markemonb** [NECROBOTIO/NecroBot#5442]
[04:33:29] Pokemon Servers might be offline / unstable. Trying again...
[04:33:30] Error: System.NullReferenceException..........
...........

After these loggings, i tried to create a new account and found out that I was able to use the same username and emailadress of my banned account
Apparently Niantic deleted the account and gave the username free again.

**Comment by Hackflag** [comment]
what did you use ? What were your config ?

- kmph above 10 ?
- using autosnipe ?

that can be reasone enough to be real banned..
im sorry for you

**Comment by mghanem86** [comment]
How did you knew that you are banned ?

**Comment by ruchern** [comment]
Weird policy. Banned accounts don't get deleted for many reasons. They want to restrict the use of that unique ID/email.

**Comment by sianyuw7** [comment]
i agree with ruchern

**Comment by altindal52** [comment]
mine also can't login

**Comment by altindal52** [comment]
at phone it tries to login to server after that turn back the where it is

**Comment by sianyuw7** [comment]
try to make new account, and i got  same problem

**Comment by markemonb** [comment]
I was walking 20 kmph and NEVER used snipe 
Until a few days ago I had 3 bots working on 1 IP, since yesterday only 1 bot at a time.
I did have a lot of soft bans because of unrealistic traveling. That's the only reason I can think of why my account is removed.

**Comment by headhunter1215** [comment]
@markemonb how do you know it's completely removed/deleted?

**Comment by sandzener** [comment]
Uh! Oh! Niantic :( i got same problem too
![201603_1131_bfdcb_sm](https://cloud.githubusercontent.com/assets/20985089/17618760/b3432ce8-60ab-11e6-8bf2-4a03abc4954a.png)

**Comment by halowarsss** [comment]
THE SAME!!!
I tried to log in the app. and i go

"Failed to get game data from the server."
Now WHAT???

**Comment by PenjagaHati** [comment]
![tepok jidat](https://cloud.githubusercontent.com/assets/20869593/17619308/a6c1b9c8-60ae-11e6-8108-164a59843046.jpg) @sandzener awkkawkawkaw

**Comment by Rival94** [comment]
@PenjagaHati norak lu njing. jangan malu2in negara. ini forum internasional

**Comment by halowarsss** [comment]
They deleted me. I don't get ip ban. Because with an other account i can logged in with the same ip and no problem. but with the other(my main acc.) doesn't work even when i try to log in on the phone the game says "Failed to get game data from the server."

**Comment by PenjagaHati** [comment]
![111](https://cloud.githubusercontent.com/assets/20869593/17619471/c78379d4-60af-11e6-9212-d4c68b85b354.jpg)
weq sewot,bocil :(

**Comment by recon88** [comment]
Most likely banned.
Also use the ticket template instead of removing it.
