### ISSUE TITLE
when launching this is happening:

### ISSUE THREAD

**Issue by Hackflag** [NECROBOTIO/NecroBot#5443]
when i launch the bot, this happend :-1: 

Initializing NecroBot logger at time 12-8-2016 11:07:03...
[11:07:05] AutoUpdater is disabled. Get the latest release from: https://github.com/NECROBOTIO/NecroBot/releases
 [11:07:05] Logging in using Google
[11:07:08] Playing as "gergsg"
[11:07:08] Make sure Lat & Lng are right. Exit Program if not! Lat: 51,8151680356352 Lng: 4,66781545213836
[11:07:08] System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__33.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:regel 359
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:regel 24
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:regel 16
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 36
[11:07:08] Logging in using Google
[11:07:09] Playing as tomdegeep
[11:07:09] Make sure Lat & Lng are right. Exit Program if not! Lat: 51,8151680356352 Lng: 4,66781545213836
[11:07:09] System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__33.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:regel 359
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:regel 24
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:regel 16
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 36

**Comment by cheah0105** [comment]
#5441 look at this

**Comment by Hackflag** [comment]
@cheah0105 Already did that..

**Comment by cheah0105** [comment]
Did you installed both ? 
download vc_redist.x64.exe for 64-bit OS
Dont install both

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.
