### ISSUE TITLE
NecroBot crashes every time i open

### ISSUE THREAD

**Issue by LazyBrand** [NECROBOTIO/NecroBot#5444]
This happens seconds i open NecroBot everytime. Only started doing it when i updated. Any fix?
![necrobot](https://cloud.githubusercontent.com/assets/20919996/17618058/a03bb1a8-60d1-11e6-96b4-a092a356ef71.jpg)

**Comment by ruchern** [comment]
You need .NET Framework 4.6.2

**Comment by LazyBrand** [comment]
Ah! Worked perfectly after i downloaded it. Thanks ruchern!

**Comment by ngboi** [comment]
downloading this now
