### ISSUE TITLE
Account lvl 34 got banned officially what a sad day for me 

### ISSUE THREAD

**Issue by Schwrid** [NECROBOTIO/NecroBot#5446]

**Comment by Profetorum** [comment]
This is NOT a forum!!!

**Comment by Schwrid** [comment]
Oh really ?

**Comment by sammyloy** [comment]
yup i  think mine got banned too

**Comment by sammyloy** [comment]
all pokestop unable to be unbanned

**Comment by sammyloy** [comment]
what a fucked up day @Schwrid

**Comment by bpkt119** [comment]
did u know why u got banned

**Comment by sianyuw7** [comment]
i think server is down, because i make new account and i cant login

**Comment by Schwrid** [comment]
i can login with another lvl 30 account of mine (botting with bokebuddy) but not my main lvl 36 account with 3325 dragonite and it was 100iv

**Comment by sammyloy** [comment]
@Schwrid  haha same my other account runs normally, and that 'banned' account stucks in a soft ban

**Comment by ruchern** [comment]
@nfettinger Can we just close this retarded issue?

**Comment by headhunter1215** [comment]
I'm sorry but how do you know it's banned for sure?
i get this error on 2 of my account's [failed to get game data from server] but when i login on a other account that actually works and then after that i try to login again on the other account i get the message with picture like server was down i tried using my ptc account on pokemon trainer club still works and my email is still attached to the account apparently so what does this mean for me ? XD

**Comment by ipkpeople** [comment]
Anyone who botted yesterday will get either of these 2 perma bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon)

**Comment by theloser** [comment]
@ipkpeople Yesterday I botted 24h straight on three accounts, and I am botting right now, so I call this "bullshit".
