### ISSUE TITLE
Less XP/hr 0.8.5 ->0.8.6

### ISSUE THREAD

**Issue by Jeweettoch13** [NECROBOTIO/NecroBot#5448]
It seems that the 0.8.6 is running a lot more stable than 0.8.5 with no bans at all in the 4 hrs i'm running the bot. But the amount of XP per hour dropped from ± 35.000 to 17.000. 

What is the best thing to  do to gain max xp for now without the risk of softbans?

### Other Information
Version: 0.8.6
Windows Version: 10 pro
What is affected (other): XP/hr

**Comment by Profetorum** [comment]
Check discord channels.
@everyone Softbans and hardbans appear to be increasing, for your safety we recommend you make these settings changes: disable sniping, reduce walking speed to 18kph or less, increase action delays to at least 2-3 seconds, and don't use proxies if you can avoid it.

**Comment by Jeweettoch13** [comment]
I did all that. Walking speed is 11, sniping disabled, action delay set to 5 seconds. But strange that xp is half the amount it used to be. Only side note is that i've enabled human like throw. Is that perhaps the issue for the low xp/hr?
