### ISSUE TITLE
Failed to login when using my phone

### ISSUE THREAD

**Issue by JasperLobbies** [NECROBOTIO/NecroBot#5452]
I was using my phone for awhile than I closed the app and went to the store than came out and went to login again and it keeps saying failed to login is this cause I used necrobot? Am I banned?

**Comment by burntable** [comment]
Yes.

**Comment by JasperLobbies** [comment]
Nvm I fixed it

**Comment by headhunter1215** [comment]
how did you fix it ? did you get [ failed to get game data from server] or ?

**Comment by JasperLobbies** [comment]
I just shut off my game waited a few minutes and tried again and it signed me right in
