### ISSUE TITLE
Softban detection faulty?

### ISSUE THREAD

**Issue by iPollox** [NECROBOTIO/NecroBot#5456]
### Expected Behavior
Should detect that a softban might be in place and try to search for a pokestop to try and unban itself.
![untitled](https://cloud.githubusercontent.com/assets/5094754/17618395/83d06bf0-604d-11e6-82ac-a206ff8cab0d.png)

### Actual Behavior
Keeps trying to catch pokemon with a softban in place, wasting all the pokeballs.

### Your config.json
```
http://pastebin.com/raw/E5AmPQCa
```

### Other Information
Version: 0.8.6
Windows Version: 10 Pro
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Softban Detection

**Comment by headhunter1215** [comment]
pokemon is acting weird.. i can't login on some accounts and i have seen more people complaining about this " bug" that pokemon keep fleeing even without soft ban because people without using programs have it as well.

**Comment by davidzhaozdw** [comment]
@headhunter1215 You mean people never used bots or snipe also have this pokemon fleeing problem?

**Comment by mpfourtz** [comment]
i cant spin pokestop, its says try again later, but i can catch pokemon, anyone have same problem like me?

**Comment by headhunter1215** [comment]
yes or at least they say they didn't use any bots so i don't know what to think of it.
Also some people told me there is apparently a bug that a pokeball fly's waaaay to far over the pokemon when you just throw it normally sometimes

**Comment by MrCrystaline** [comment]
Only bans =_=
![asdawsdawsdaws](https://cloud.githubusercontent.com/assets/20988076/17618706/ab20f1e6-609a-11e6-93ef-923f406de5df.PNG)

**Comment by michael8228** [comment]
my friend can't even catch a single one since 6 hours ago without using any prog.

**Comment by iPollox** [comment]
Guys, I tried logging in thru my phone, and nothing was loading, I turned off my wifi and worked again, I'm imagining Niantic is changing something with the IP bans? Seems like Pokestops are working fine, but catching pokemon isnt working, and nothing loaded from my phone until I changed connection (IP)..

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
