### ISSUE TITLE
how to set long delay for snipe? 

### ISSUE THREAD

**Issue by tuahwp** [NECROBOTIO/NecroBot#5457]
currently the snipe do after travelling two pokestop even i have 3 pokeball, but i dont have enuf pokeball,berry,etc to farm and snipe rare pokemon. 

"MinPokeballsToSnipe": 20,
"MinPokeballsWhileSnipe": 0,
"MinDelayBetweenSnipes": 60000, ( what amount to change for 30 min delay? )
"SnipingScanOffset": 0.005,

rip my english hope you guys understand.. :)

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
