### ISSUE TITLE
AutoUpdater from v0.8.5 to v0.8.6 dont works

### ISSUE THREAD

**Issue by SaubereSacheLP** [NECROBOTIO/NecroBot#5458]
Hi, your autoupdater dont works because the link which it is using dont exists!

**Comment by venduss** [comment]
Same here, it keeps asking me to update it, but it's stuck at 0.8.5.

**Comment by hclivess** [comment]
Stop oening new issues on this issue? Learn some basic english?

**Comment by VoidMaker** [comment]
same here

**Comment by linkin2011** [comment]
have to download it manually https://github.com/NECROBOTIO/NecroBot/releases

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
