### ISSUE TITLE
Constant Soft Ban

### ISSUE THREAD

**Issue by btd1993** [NECROBOTIO/NecroBot#5459]
Hey guys , 

I just flipped from 0.8.5 to 0.8.6 , because I got this error in 0.8.5 
But its all the same in new version too ..  I was using old version from the first minute it got released . 

Can someone determine the problem please ? Why does bot just started to give that error ? Why am I unable to bypass softban ? ( My sniper configs are off , and the pokestops I'm visiting is 10-20 meters to eachother )

I use Windows 7 Prof , with AMD A8 Processor .
 
![config](https://cloud.githubusercontent.com/assets/20987829/17618443/80d40e4e-6088-11e6-97d7-fbf2bf06798d.png)
![softban](https://cloud.githubusercontent.com/assets/20987829/17618447/834ec394-6088-11e6-83ec-eed156060252.png)

**Comment by fayaman77** [comment]
when I get the softban I just reset the internet modem to get a new ip... then it works... give it a try.

**Comment by Piels2** [comment]
#5438

**Comment by boXseven** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by andrea25** [comment]
Same problem here.
![softban](https://cloud.githubusercontent.com/assets/10176752/17618749/bad18cc2-6081-11e6-9c7e-5a71a0020d66.jpg)


I had the same issue yesterday night.

I can not understand how Niantic recognize that we are using a bot.

I was traveling 11KM/h with Human Walking ENABLED.



**Can the Necrobot prevent in an automatic way, without user input this kind of problems?**

**Comment by razer1337** [comment]
same problem here

**Comment by Rabelaiss** [comment]
Got softban after 50 min with these

  "WalkingSpeedInKilometerPerHour": 25.0,
  "DelayBetweenPlayerActions": 1000,
  "DelayBetweenPokemonCatch": 1000,

gonna try with 2000 delay and 20 km/h

**Comment by ruchern** [comment]
@Rabelaiss Settings are too fast.

**Comment by Rabelaiss** [comment]
@ruchern holy shh
so gonna try with 10 km/h, 5000-2500 delay, human walking and human throw

**Comment by andrea25** [comment]
I'am already using Human throw ENABLED. Ad I am using 5000-2000. Now I try with 6000-3000 to se if something changes. But I have to wait the end of the softban with this account.

**Comment by razer1337** [comment]
found this in config "FastSoftBanBypass": false, should i turn it on?

**Comment by andrea25** [comment]
Actually I am leaving FastSoftBanByPass OFF.
I someone can suggest anything else I'am listening.

**Comment by Rabelaiss** [comment]
What about sniping? Turn it off maybe could be better

**Comment by Naprosnia** [comment]
change "DisableHumanWalking" to false. or you walk faster for pokestops and Pokemon, and get softban.

**Comment by Rabelaiss** [comment]
@andrea25 you can reset your router or test a new account because the ban could be 2 hours or so
Daje

**Comment by ilihack** [comment]
Ip change help not bye this type of semi ban

**Comment by boXseven** [comment]
just wait and see

**Comment by btd1993** [comment]
I reseted my modem for over 3 times , nothing changed -.-

**Comment by Linewalker** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5522#issuecomment-239429286
Please close. No code issue.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
