### ISSUE TITLE
PSA: "DisableHumanWalking"  set to FALSE

### ISSUE THREAD

**Issue by jonsnowwatch** [NECROBOTIO/NecroBot#5460]
,no matter what you walking speed is. you can thank me later.  

After loads of bots being banned I notice as long as you have this set to "true", the bot will teleport you, then you get soft-banned. any soft-ban less than 20 times is trivial but if you hit 34 soft ban too often you will get semi-perm ban. Such as 100% catch-flee, or can-only-catch-but-nothing-else ban. They are different from IP ban, so change ip or phone wont work. There is no way to by-pass this kinda ban just yet. Stay safe botters!

**Comment by derkoenig** [comment]
bullshit

**Comment by kurozani** [comment]
nope, use these, still got banned

**Comment by ilihack** [comment]
I have a semi Soft Ban to my Second Account are Perfect

**Comment by ilihack** [comment]
And no ip ban will help

**Comment by wrau1** [comment]
I keep getting ip bans but I just my ip with Private Internet Access.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
