### ISSUE TITLE
Cant spin pokestop

### ISSUE THREAD

**Issue by mpfourtz** [NECROBOTIO/NecroBot#5462]
i cant spin pokestop, its says try again later, but i can catch pokemon, anyone have same problem like me?

**Comment by razer1337** [comment]
sometimes had the same issue after log out and in i saw that the pokestop was purple. i think that is a gps prob

**Comment by Caterpee** [comment]
Seems like servers are actually not running stable in some regions. Bot is fine but Niantic servers are not.

http://www.mmoserverstatus.com/pokemon_go

**Comment by mpfourtz** [comment]
well, my other account can spin the pokestop, but not my main account, its banned or something?

**Comment by mufclaw** [comment]
@mpfourtz same here 5hours now

**Comment by kkdvka** [comment]
@mpfourtz same problem here, my main acc can't spin pokestops but my lower acc can.. that's weird :s

**Comment by recon88** [comment]
Server issues of (soft)banned

**Comment by kkdvka** [comment]
But I am able to catch pokemon, can't be a soft ban
