### ISSUE TITLE
I can't catch any pokemon, only Pokestop works

### ISSUE THREAD

**Issue by daviwesley** [NECROBOTIO/NecroBot#5464]
I am using the bot for 3 day, and yesterday it was worked fine but now i can't get any pokemon, it always fly away.

**Comment by emrecanozkok** [comment]
because you are soft banned.

**Comment by thejoker04393** [comment]
Same thing happening with me .... Earlier version use to bypass soft ban ... By now??

**Comment by tggiml** [comment]
this is a good news. you need to wait 2 hours compeltely then ban will be gone.

**Comment by thejoker04393** [comment]
R u sure ??

**Comment by kaedekonami** [comment]
Same problem with me.....

**Comment by davidzhaozdw** [comment]
@tggiml seriously? #5427 a guy said he waited 10 hours still cannot.

**Comment by spamfighter82** [comment]
well the problem didn't even start 10 hours ago, so i call bullshit on that

**Comment by tggiml** [comment]
I was exactly same problem then I waited 2 hours and it was gone.

**Comment by burntable** [comment]
Good to know.
I thought the acc was gone.

**Comment by thejoker04393** [comment]
@tggiml... So now ur bot is now able to catch Pokemon's...

**Comment by mufclaw** [comment]
@tggiml is the pokestop try again later a confirmed new softban has have had it for last 5 hours??

**Comment by dose2k** [comment]
Had my bot running as it updated. Pokemon started fleeing at around 3am according to logs. It's now 11am. I've checked manual catching outside its the same. I guess this is a ban. Ain't no 2hour bs tho.

**Comment by thejoker04393** [comment]
Pokestop working gym working but no luck with catching Pokémon.... :-(

**Comment by anti2canz** [comment]
yea same thing happened around that timing, the new soft ban though hope anyone could find out what caused that

**Comment by thejoker04393** [comment]
Is this soft ban or permanent ban??

**Comment by anti2canz** [comment]
no idea yet though, the so called new "softban" still hanging there.

**Comment by thejoker04393** [comment]
Sad news
