### ISSUE TITLE
Please help me fix this

### ISSUE THREAD

**Issue by shredme04** [NECROBOTIO/NecroBot#5467]
![error pokemon go](https://cloud.githubusercontent.com/assets/20986381/17618970/397b08fe-60b5-11e6-8ffc-4fcd0477fdcc.jpg)

can't run version 0.8.6

**Comment by lacimester** [comment]
same problem.

**Comment by Oolaruu** [comment]
Start a fresh install, still problems ?
https://www.microsoft.com/en-US/download/details.aspx?id=48145
https://www.microsoft.com/en-us/download/details.aspx?id=53345

**Comment by lacimester** [comment]
Well, VS installed one of my pc, there is working, and on the another there is no VS and failing, so thats might be a problem, thanks for your advice! @Oolaruu

**Comment by AndikaTanpaH** [comment]
try run as administrator

**Comment by recon88** [comment]
For help or configuration issues visit https://discord.gg/VXKxNFr
