### ISSUE TITLE
Can't pass Softban becuase no Pokestop is available?

### ISSUE THREAD

**Issue by andele123** [NECROBOTIO/NecroBot#5468]
Hello guys,

i am using QuickSpin and when i want to pass a Softban in Central Park, it does not find any Pokestops.
Same in my home region.
Does that relay to the Servers at the moment?

**Comment by feroniameimei** [comment]
same, already tried all the tips in here, but nothing work.

**Comment by F4lc0n88** [comment]
If I log in with my account manually (not from the bot) there is no pokestops or pokemons around, and many people reported that as well, It is a server failure I guess.

**Comment by boXseven** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by prevorus** [comment]
I think you get ip ban

**Comment by SmokedBeef** [comment]
@prevorus no it's not. The server is down. Don't know where you get the idea that it's ip ban.

**Comment by andele123** [comment]
@SmokedBeef but why I can login with Bot Account in Germany and with PTC Account in Germany too. In both Accounts, i don't see Pokestops. But a friend of me does?!

**Comment by mufclaw** [comment]
i can see pokestops on my phone but they just say try again later span 100x and still wont lift softban????

**Comment by boXseven** [comment]
@andele123 maybe its not completely down but very usntable?

**Comment by andele123** [comment]
Seems to be
