### ISSUE TITLE
Telegram API shows error after update

### ISSUE THREAD

**Issue by Kyngo** [NECROBOTIO/NecroBot#5469]
I upgraded NecroBot from 0.8.5 to 0.8.6 and when starting it says "Unknown Telegram Error occured." The same thing says on the log files. I even tried creating a new bot, but it won't help.

**Comment by punga78** [comment]
my too

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.

**Comment by theloser** [comment]
Telegram is not working with 0.8.6, it's broken. Go back to 0.8.5. or wait until it's fixed.
I suggest turning Telegram API off for now.

Also Duplicate of #5323
