### ISSUE TITLE
login problem 0.8.6 

### ISSUE THREAD

**Issue by zenptg** [NECROBOTIO/NecroBot#5471]
![problem](https://cloud.githubusercontent.com/assets/20708239/17619126/9bf62840-60ad-11e6-96f2-86a98862bc70.PNG)
 i have a problem with ver 0.8.6. Ver 0.8.5 still working but stop after first pokestop .
Sr if my English not good

**Comment by GreatApo** [comment]
Closing the sniping features will let make your V0.8.5 work.
Don't know about 0.8.6, works here :/

**Comment by zenptg** [comment]
U mean edit snip in config file? 
tks for ur answer

**Comment by headhunter1215** [comment]
@zenptg i wouldn't use snipe atm it's unstable for version 0.86 and someone mentioned here problems with pokestops or something.

**Comment by GreatApo** [comment]
Actually only the pokezz.com was not working (stucking the bot) on v0.8.5.
If you change it to false, you will be able to pass the first pokestop. Or just disable snipping.

**Comment by dezayner** [comment]
i have similar problem too

**Comment by pokehacks6969** [comment]
Got the exact same problem, tried turning snipe settings to false but doesnt work

**Comment by recon88** [comment]
For help or configuration issues visit https://discord.gg/VXKxNFr

**Comment by dezayner** [comment]
I cant login with Pokemon Bot. Is it about configuration ? I dont think my login credential is incorrect.

**Comment by recon88** [comment]
Please read properly. I said for HELP and configuration issues.
