### ISSUE TITLE
stuck at the login in the bot 

### ISSUE THREAD

**Issue by LuthfyCooperz** [NECROBOTIO/NecroBot#5472]
![asf](https://cloud.githubusercontent.com/assets/20985667/17619183/ea1823ca-60ad-11e6-8911-a2f3b47d4f28.jpg)

necrobot v.0.86 HELP !!!! 

give me a solution to solve this ..

**Comment by headhunter1215** [comment]
@LuthfyCooperz  can you login with your phone? yes ? then it's bot problem , no? then probably some kind of ban. got the same on 2 acc's.

**Comment by LuthfyCooperz** [comment]
@headhunter1215 yes i can log in in my phone , 
what kind of ban ? and give me solution to solve it ..

**Comment by headhunter1215** [comment]
@LuthfyCooperz is your sniping on? and i don't know yet but a lot of people who used bot (myself included) get an error [failed to get game data from server] when we log in through our phones so probably a ban (maybe new longer soft ban maybe perm ban we don't know yet)

**Comment by LuthfyCooperz** [comment]
@headhunter1215 I've been looking nowhere for solve the problem , but still don't work on my laptop ..

**Comment by headhunter1215** [comment]
@LuthfyCooperz  it seems more people have this issue and a lot of people have other issues with bot and account's since today/yesterday so i guess we'll just have to wait it out and see what's happening,
anyway you're lucky you can still login on your phone because alot of people (including me ) can't anymore.

**Comment by LuthfyCooperz** [comment]
@headhunter1215  yeahh , wait for the clarity of the issue is the best way

**Comment by recon88** [comment]
You are most likely IP banned. Check again in a few hours or try getting a new IP
