### ISSUE TITLE
please help, how can i fix this?

### ISSUE THREAD

**Issue by vae4victis** [NECROBOTIO/NecroBot#5473]
help me pls 

[![image](http://i.hizliresim.com/1NjGoN.jpg)](http://hizliresim.com/1NjGoN)

**Comment by GreatApo** [comment]
![12bab8ea6a59c09e17a16db3cc8d08794c070ba21bf9e752722cbf2e9812c207](https://cloud.githubusercontent.com/assets/9620510/17619265/dea56c80-608c-11e6-9d82-d885b97e0abc.jpg)
Close and wait... some hours...

**Comment by SaubereSacheLP** [comment]
I had this type of softban yesterday. I think the accounts are gone **perma**...

**Comment by vae4victis** [comment]
bot is unbanned me but again banned

**Comment by headhunter1215** [comment]
@vae4victis  ye we don't know what's up with the problems yet, probably some kind of bans/ anti bot stuff from niantic tho.

**Comment by rayhvh** [comment]
anyone get an failed to login to app ?

**Comment by vae4victis** [comment]
@rayhvh no, no failed
