### ISSUE TITLE
no unable pokestop found in your area. Is your maximum distance to small?

### ISSUE THREAD

**Issue by aradzu10** [NECROBOTIO/NecroBot#5474]
"no unable pokestop found in your area. Is your maximum distance to small?"
why it keep write it to me?
And how to fix it?

**Comment by prevorus** [comment]
You propably get ip ban, try proxy or vpn

**Comment by aradzu10** [comment]
How can I setup proxy?

**Comment by tetrayam** [comment]
Same probleme

**Comment by prevorus** [comment]
ohh i just find this http://www.mmoserverstatus.com/pokemon_go

**Comment by ZHUYUEHAN1** [comment]
Same probleme!!!

**Comment by prevorus** [comment]
maybe servers down

**Comment by SaubereSacheLP** [comment]
The servers of germany are down for ~3h

**Comment by timaye** [comment]
bots not working for me as well. im in the us can play on my phone tho and works fine so bot is down

**Comment by ScriptorLord** [comment]
Logged in with my phone running on the same Wi-fi that I used on my laptop. Can be logged in but can't see any pokestop, gym or pokemons. Probably a IP ban, used my mobile data and everything's fine. -Singapore.

**Comment by aradzu10** [comment]
What can i do?

**Comment by xidus90** [comment]
only wait

**Comment by recon88** [comment]
Soft/IP Ban
