### ISSUE TITLE
Help meeeeeee 

### ISSUE THREAD

**Issue by dauqua222** [NECROBOTIO/NecroBot#5476]
![image](https://cloud.githubusercontent.com/assets/20988554/17619397/682ea620-60af-11e6-957d-0787147e1614.png)

**Comment by alessandro1989g** [comment]
![cattura](https://cloud.githubusercontent.com/assets/20768685/17619545/43b3bd22-6086-11e6-9584-48738f9fa800.PNG)
Similar problem here! 

I'm running Windows7 64 bit.
Can someone help us?

**Comment by SaubereSacheLP** [comment]
New build is bugged and is getting banned...
So DONT use it at the moment

**Comment by alessandro1989g** [comment]
![cattura2](https://cloud.githubusercontent.com/assets/20768685/17619591/a3166814-6086-11e6-8905-d1efad438a0b.png)
Same problem here, running Necro on Windows 7- 64 bit.
Can someone help us?

**Comment by cheah0105** [comment]
Don't use the latest version. It will cause u getting banned. Stay at previous version would be better
