### ISSUE TITLE
No usable Pokestops in you area, why??

### ISSUE THREAD

**Issue by Impossibol** [NECROBOTIO/NecroBot#5477]
After update, i've this error: http://prntscr.com/c4rvek

I'M NOT BANNED, 'CAUSE WITH ALL MY ACCOUNTS I'VE THIS PROBLEM!

**Comment by thadeustr** [comment]
it is not 1.8.6 issue. 
also 1.8.5 is not working so it is not necrobot related...

**Comment by Impossibol** [comment]
what do you think about this? New api update?

**Comment by boXseven** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by EyesReye** [comment]
You might have been IP banned, Change IP with VPN or wait 1+ Hour or the servers are down in your Region.

**Comment by thadeustr** [comment]
i cant say why this is happening. login servers r down maybe?

**Comment by cheah0105** [comment]
Just reset the IP address. It will be fine.

**Comment by knirb91** [comment]
you ip is banned by niantic got it last night waited about 2 hours and it worked again

**Comment by timaye** [comment]
seems like a bot problem to me tryed with vpn and 2 diffrent accounts and still bot is not working but i can play on my phone fine

**Comment by parthroxx** [comment]
i dont think so , i have same error

**Comment by Impossibol** [comment]
This isn't a BAN problem in my opinion, because other users have this problem..

**Comment by Impossibol** [comment]
So, Niantic banned all users, or the servers are offline xD

**Comment by thadeustr** [comment]
login servers pings are high atm. maybe another hacker attack?

**Comment by Brainenigma90** [comment]
i just logged in with account to nox and no pokestops appear on the map,i think the api changed again darn

**Comment by elmaarmut** [comment]
It'a an API change.

**Comment by SkyFyre** [comment]
Can we get some functionality where in this case (no pokestops found) the bot will still wander around to hatch eggs? I think walking can sometimes trigger the pokestops showing up too.

**Comment by thadeustr** [comment]
yea i think there is a server related problem.
pokestops and gyms r loding slow on my phone too..

**Comment by parthroxx** [comment]
they are banning people

**Comment by joeskyfrog** [comment]
maybe ban wave is coming.. lol

**Comment by nekochan23** [comment]
i think server maintenance. just wait till tomorrow then

**Comment by ImSharp** [comment]
Same here.

**Comment by thadeustr** [comment]
some regions r down probably another ddos attack.

**Comment by Goldberg80** [comment]
Never use MORE THEN ONE bot on your IP !!!
Its an IP ban....simply change your IP and DONT use free proxy server...most of them are already banned too.

**Comment by thadeustr** [comment]
actully more than half of the servers r down

**Comment by Impossibol** [comment]
i logged in with account to nox and no pokestops/pokémon appear on the map, so the servers are offline or in attack..

**Comment by jodirt282** [comment]
Don't believe everything you read here guys. The server are just unstable.

**Comment by jayson0408** [comment]
servers are down

**Comment by Tekka89** [comment]
I got an IP Ban...

To test, connect to your phone hotspot for internet access then run yout bot again to confirm.

**Comment by sounddanezzboiz** [comment]
change your ip address i solve this issues with that... your ip been block by niantics

**Comment by SkyFyre** [comment]
normal login to my main also showing 0 stops, errbody chill :+1:

**Comment by Goldberg80** [comment]
Servers are fine.....status page are fail... says Germany down since three hours....just logged in 10mins ago and playin without probs. As my wife also uses necrobot we have to set up a proxy for her or we will get this no pokestop shit every time....if we start with different fresh IP's then we have no problems.

**Comment by jayson0408** [comment]
share some working Ip's

**Comment by Piels2** [comment]
Gyms can't be also attacked.. Can do nothing anymore, is there more information about the issues?

**Comment by boXseven** [comment]
@Goldberg80 yeah cuz i think its not completely down but very unstable

**Comment by SkyFyre** [comment]
Weird info may help: Not getting the pokestop error when i use release 8.5 (one version back). Dunno if it's a coincidence or not...

**Comment by joeskyfrog** [comment]
i just restart my router.. my main account just can spin the pokestop and every want to catch some pokemon just gone (CatchFlee).. and then i try using with my 2nd account on same IP just works well.. snipping catch etc.. IP ban it's not the main problem i think

**Comment by parthroxx** [comment]
use vpn

**Comment by Impossibol** [comment]
Yes, i've restarted my router and it works again... so niantic started to ban all accounts or is only an unstable server? D:

**Comment by boXseven** [comment]
we will see i guess

**Comment by Shadow-MasterTf** [comment]
looks like server issues http://www.mmoserverstatus.com/pokemon_go

I changed location to monaco and its working fine now

**Comment by Linewalker** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5522#issuecomment-239429286
Please close. No code issue.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
