### ISSUE TITLE
Anyone gets out from a PokeSTOP 'try again later' ?

### ISSUE THREAD

**Issue by tggiml** [NECROBOTIO/NecroBot#5478]
I had this issue about 5 hours ago. So, waited 4 hours and logged in.

It is still the same....... is Nintendo wants me to buy balls to catch.....?

**Comment by xidus90** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by AlliedSignal** [comment]
I believe this issue is something about softban. Waiting.

**Comment by tggiml** [comment]
that's why?

**Comment by tggiml** [comment]
some people waited more than 5 hours but the result is still the same.

**Comment by gemeluna** [comment]
same here

**Comment by forliHD** [comment]
same here :(

**Comment by ewaah** [comment]
i can get in to my acc, using bluestacks, and i can see all te stops, but the image is black and i always get the message pls try again later, so i really dont know whats next
and oh, i have zero pokebals in my back dammit

**Comment by tggiml** [comment]
0...pokeballs = shame..on nintendo

**Comment by ewaah** [comment]
i had zero pokeball when i logged in so i woulnd know

**Comment by ewaah** [comment]
1 acc i cant log in at all, the other i can but i get that message, making a new acc to test some further

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
