### ISSUE TITLE
Help. The incubators just keeps refreshing

### ISSUE THREAD

**Issue by Noriclol** [NECROBOTIO/NecroBot#5479]
i dont know what to do???
![untitled](https://cloud.githubusercontent.com/assets/20988438/17619522/189194fc-6086-11e6-9581-005528844a5d.png)

**Comment by SaubereSacheLP** [comment]
The new build is a BIT buggy
200 Accounts of me got banned

**Comment by Noriclol** [comment]
ive tried reinstalling, im not softbanned. cant find a fix for this anywhere

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
