### ISSUE TITLE
Niantec make IP Bans

### ISSUE THREAD

**Issue by no42chance** [NECROBOTIO/NecroBot#5481]
Niantec make ip bans i was banned on one network (see no Pokestops and no gyms or pokemons)
after i make a VPN it works!!

**Comment by spamfighter82** [comment]
thats not news

**Comment by pkownsz** [comment]
y i Know with one ip i got message " you are on Niantic blacklist" xD

**Comment by marburger93** [comment]
yes, the same problem -.-
![bbvxvee](https://cloud.githubusercontent.com/assets/11341599/17619844/5deb0964-6088-11e6-9969-24b6401dfe07.png)

**Comment by no42chance** [comment]
sry i dont read it here so i write it ;)

**Comment by BerrysnakeLP** [comment]
So if i just connect with a program like CyberGhost it should work?

**Comment by michael8228** [comment]
@marburger93 so if it dont show the message it will not be perma ban?

**Comment by no42chance** [comment]
the account is not banned only the ip when you have a static ip then you need to run a vpn client
when you have a dynamic ip yo must only reconnect your router (here in Germany)

**Comment by marburger93** [comment]
@michael8228 No, I suspect a temporary ban (softban) only ....

**Comment by g00tch** [comment]
Yup. Softban confirmed...at least for me.

I was banned for about an hour. Back up and running smooth again on Necro 0.8.6

**Comment by marburger93** [comment]
i live in germany, i have a static ip from unitymedia - modem reboot will not work... ^^

**Comment by no42chance** [comment]
yeah unitymedia and kabel deutschland have static

**Comment by smoothrunnings** [comment]
@no42chance  Niantec is blocking IP's from VPN services. They have managed to blocked HMA New York and New Hampshire portals. They are also starting do reverse lookup on IP's connected to their servers, so if your IP originates in the US and you are in Japan you'll get soft banned or perm banned.

**Comment by no42chance** [comment]
ah ok thanks so when iam in us and make vpn us then it must be good or?
