### ISSUE TITLE
No PokeStops found?

### ISSUE THREAD

**Issue by OmegaGolem** [NECROBOTIO/NecroBot#5482]
Hey,
I installed NecroBot an this worked. But then it says, that there are no PokeStops.
I'm in Germany and the Bot-Location is default, Central-Park.
Am I banned, or are the Servers down?
I have the newest version of NecroBot.
What to do?
Thanks ~Omega

**Comment by prevorus** [comment]
I think new update glitching

**Comment by OmegaGolem** [comment]
O.K. that sounds good for me, i hope that I'm not banned :C.

**Comment by boXseven** [comment]
http://www.mmoserverstatus.com/pokemon_go

**Comment by OmegaGolem** [comment]
@boXseven means that, that the servers in Germany are since 3 hours down?

**Comment by xidus90** [comment]
Nein das heißt das der Server 3 Stunden brauch um zu Antworten (Latenz).
Wohl die 3h glaube ich auch nur ein Platzhalter ist.

**Comment by OmegaGolem** [comment]
Oke, das bedeutet in 3h geht es wieder?

**Comment by BerrysnakeLP** [comment]
I have the same problem with the bot. Yesterday it worked fine but not today. I think it is the new update cause the bot could login

**Comment by schnork111** [comment]
Xidus hat recht - du kannst dich auf dem Handy einloggen, aber es erscheinen keine Stops oder Arenen. 

Einfach abwarten :D

**Comment by OmegaGolem** [comment]
Ah, gut hatte Schiss, wollte nicht gebannt sein, puh.

**Comment by xidus90** [comment]
nein das kann auch noch 24 stunden dauern oder auch nur 30min.

Einfach immer mal wieder Testen.

**Comment by OmegaGolem** [comment]
@xidus90 Mach ich, danke ^^

**Comment by xidus90** [comment]
Bitte gerne hab 3 Acc  ( einen zum Testen, meinen und den meiner Freundin) komm mit einem rein aber bei den anderen 2 habe ich das selbe Problem.

**Comment by BerrysnakeLP** [comment]
Also in einem anderen Problem hier hab ich gelesen das hier IP Bans kommen und uns mit einem VPN wie CyberGhost verbinden sollen dann sollte es wieder gehen

**Comment by xidus90** [comment]
Ja gibt es auch, aber das hier ist einfach nur der Server.

**Comment by boXseven** [comment]
ich glaube eher, dass die server nicht komplett down sind sondern nur bestimmte bereiche bzw. sehr instabil. einfach abwarten.
glaube nicht an das ip ban bla bla, weil sonst könntest du dich erst garnicht einloggen.

**Comment by Stiggelsche** [comment]
Bei mir ist es definitiv IP Ban. Wenn ich mit meinem Nicht-Bot-Account über mein Handy gehe, dann sehe ich keine Pokestops wenn ich im WLAN bin und sobald ich über LTE gehe, also mit anderer IP, dann funktioniert alles. Kann ich beliebig oft hin und her machen.
Also bloß IP Ban in meinem Fall.

**Comment by boXseven** [comment]
es kann aber auch genauso gut sein, dass etliche ip ranges geblockt sind um den load zu reduzieren.
wir werden sehen...es scheint aber definitiv da was mit maintenance im gange zu sein.

**Comment by OmegaGolem** [comment]
Dann is ja gut, hoffe echt es sind nur die Server.

**Comment by Stiggelsche** [comment]
Bei mir läuft der Bot jetzt wieder.
Ich benutze relativ moderate Einstellungen, also 7km/h und 2 bzw. 4 sek. Delay, allerdings habe ich Sniping aktiv. Mal sehen wie lange es bis zum nächsten Ban dauert. :-)

**Comment by OmegaGolem** [comment]
Was ist Sniping, kenne mich da gar nicht aus?

**Comment by TheSwoodoo** [comment]
Wieso verschickt mein Bot Pokemons die ich nicht doppelt habe? Und wieso behält sich er manchmal die schwächeren und verschickt die stärkeren? Weiß das jemand von euch? 
Spiele mit den Standarteimstellungen

**Comment by OmegaGolem** [comment]
Geht bei dir der Bot?
Oder findet er auch wieder keine Stops

**Comment by Zerotask** [comment]
Ich habe das gleiche Problem seit heute morgen, dachte auch schon, dass ich gebannt wäre :D 
Habe es öfters am Tag mal probiert, mit und ohne Proxy... Unbann tickt weiterhin bis 45/45 hoch und hat keinen Erfolg.

**Comment by monster1777** [comment]
ich habe grube babe

**Comment by Linewalker** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5522#issuecomment-239429286
Please close. No code issue.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
