### ISSUE TITLE
"TransferDuplicatePokemon": false, - where do i need to write it?

### ISSUE THREAD

**Issue by ak47temas** [NECROBOTIO/NecroBot#5483]
Heeeelp, im kinda stupid :D

**Comment by boXseven** [comment]
open Config\config.json and change from false to true or vice versa

**Comment by ak47temas** [comment]
Cannot open that file.

**Comment by boXseven** [comment]
u can open it with any text editor

**Comment by ak47temas** [comment]
Already, thanks bruh :)

**Comment by yuyaa07** [comment]
Use notepad++ to ipen it
