### ISSUE TITLE
About Necrobot Permaban

### ISSUE THREAD

**Issue by pkownsz** [NECROBOTIO/NecroBot#5484]
Can i get permaban with Necrobot? and how

**Comment by headhunter1215** [comment]
for now nobody knows.. but i got 2 account's that i can't connect with to server that used necro bot
could be a new type of soft ban could be perm ban could be server failing, we don't know yet we have to wait it out.

**Comment by parthroxx** [comment]
its ip ban
use vpn

**Comment by parthroxx** [comment]
and  snipe should be false

**Comment by St0n3d** [comment]
How we use vpn? Teach me plz

**Comment by St0n3d** [comment]
My ip is banned and its fix I dunno how to use other ip not so good pcs

**Comment by BerrysnakeLP** [comment]
just download Cyberghost it works fine

**Comment by ScriptorLord** [comment]
I was using Necrobot yesterday, ran it for 6 hours and this morning I can't log into my account with my phone. " Cannot connect to server " . -Singapore

**Comment by spamfighter82** [comment]
its not an IP ban, cant loggin with my phone using 4G instead of WLAN either. But only for my googleacc, the PTC accs tested work fine...

**Comment by pkownsz** [comment]
@scriptlord maybe your walk speed was too high?:D

**Comment by ScriptorLord** [comment]
@pkownsz I kept it at 6.

**Comment by pkownsz** [comment]
@scriptlord maybe servers  messed up :)

**Comment by ScriptorLord** [comment]
@pkownsz I hope so too. Created a new account and currently facing the issue here : https://github.com/NECROBOTIO/NecroBot/issues/5474

**Comment by feroniameimei** [comment]
i already change my ip address, but still no pokestops

**Comment by ScriptorLord** [comment]
Tested. Using CyberGhost (VPN) currently Necrobot running perfectly. They do "ban" IPs.

**Comment by ipkpeople** [comment]
Anyone who botted yesterday will get either of these 3perma bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon) 3. Could not log in at all (death of an account)

**Comment by ZombiePm** [comment]
in my ip no one account not working

**Comment by EiTeR94** [comment]
it's perma ban if you get the error failed to retry data blablabla

**Comment by burntable** [comment]
@ipkpeople And you get AIDS for spreading lies.

**Comment by Wcidd** [comment]
Support channel in discord

**Comment by feedbuck** [comment]
@BerrysnakeLP but you have to buy it if you want to get vpn

**Comment by ZombiePm** [comment]
Ban by ip im tested on clear account.
