### ISSUE TITLE
For those who can't find Pokestops / worried about bans...

### ISSUE THREAD

**Issue by Candalos** [NECROBOTIO/NecroBot#5486]
It's not a ban on the account. This seems to be an IP blocking issue.

Tried logging on my phone via my wifi network with two accounts, one which is "clean" and the other which uses Necrobot. Both couldn't find any pokestops or 'mons anywhere.

Shut off the wi-fi connection on my phone and tried both accounts again purely over my data connection and voila - pokestops and 'mons reappeared and I could play as normal with both accounts.

Whether this is a permanent IP ban or not I'm not sure, but you can get around it by changing your IP, via a VPN service or such.

Hope this helps.

**Comment by RRM8** [comment]
Can you confirm what VPN's work with Necrobot? I was having trouble using Cyberghost last night.

**Comment by g00tch** [comment]
I was on the IP ban for about an hour, and I'm all good again.

Necro 0.8.6 running smooth again.

**Comment by Mr-Awesome** [comment]
Going to disagree on you there. 
I can't use any of my accounts on Necro or my phone, Necro using WiFi, phone using 4G.

**Comment by feroniameimei** [comment]
i already changed my ip address five times, i tried login at my phone with my 4g data, i can't spin any pokestops, and still no pokestops found in bot

**Comment by gkpuge1** [comment]
i reset my modem, got a new ip but after catching 1 pokemon it blacklist again.. any inputs?

**Comment by parthroxx** [comment]
hotspot shield works

**Comment by smoothrunnings** [comment]
@Candalos Just an FYI. They seem to be banning the IP's on Hide My Ass VPN services SLOWLY. They have already blocked New York, and New Hampshire.

**Comment by feroniameimei** [comment]
@parthroxx i used hotspot shield vpn elite too. but idk why it didn't work for me, still no pokestops found...

**Comment by Bananab0y** [comment]
Please keep in mind that this is not a forum. Since you don't seem to have any issues, please close this issue. For talking, use Discord please.

**Comment by headhunter1215** [comment]
i can't even login [failed to get game data from server] reaalllyy hoping this is a niantic issue bc with my clean acc i can login just fine..

**Comment by andele123** [comment]
Works for me, too.

**Comment by andele123** [comment]
Maybe we should stop bot for some hours/days.
