### ISSUE TITLE
help me i can capture pokemon but i can't gen item in pokestop "try again later" in all pokestop

### ISSUE THREAD

**Issue by Frostage** [NECROBOTIO/NecroBot#5487]
help i can catch pokemon but can't get item in all pokestop ..
how to fix this issue?

**Comment by ipkpeople** [comment]
Anyone who botted yesterday will get either of these 2 perma soft bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon)

**Comment by lukinhasmartina** [comment]
@ipkpeople how do you know that's a perma?

**Comment by Frostage** [comment]
how to repair this issue

**Comment by recon88** [comment]
For help visit https://discord.gg/VXKxNFr
