### ISSUE TITLE
 Bug at the " MaxTravelDistanceInMeters " and Transfer Version 0.8.6

### ISSUE THREAD

**Issue by Noxinfinity** [NECROBOTIO/NecroBot#5488]
Hellos from its 0.8.6 maj tells me that I must change " MaxTravelDistanceInMeters " I change the moin 10 times and nothing changes I can neither take nor pokestop pokemon .

and another bug since maj 0.8.4 eg
I have a pokemon A he 200CP
I grabs a pokemon B 400PC
and a pokemon C 250pc
So its transfer me the pokemon C but not the pokemon A.

my config:
Intel Celeron CPU 2.20
2GB Ram
windows 10, 64bits

Version 0.8.6

**Comment by recon88** [comment]
Please use the ticket template instead of removing it.
