### ISSUE TITLE
Pokestop not found and gym error

### ISSUE THREAD

**Issue by hug0pt** [NECROBOTIO/NecroBot#5490]
I have two problems, necrobot dont found pokestops and when i go to fight in a gym have always a message "error", it´s this a ban?? i think no because i can log in

**Comment by ipkpeople** [comment]
@hug0pt Anyone who botted yesterday will get either of these 2 perma soft bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon)

**Comment by andele123** [comment]
@ipkpeople Don't know if it's true. My main account (unbotted) can't see Pokestops, too.

**Comment by hug0pt** [comment]
Yes but i can this two things, junst cant fight in gym

**Comment by cawk** [comment]
there are now multiple stages of bans you are most likely banned please try again in a couple of hours
