### ISSUE TITLE
having to redownload v8.6

### ISSUE THREAD

**Issue by ASKcoTM** [NECROBOTIO/NecroBot#5491]
every time i run the bot it asks me to update, btw, im currently IP banned (pre sure anyway) so im waiting for that to ware off. is this just because of the ban?

**Comment by boXseven** [comment]
yeah auto update didnt work for me too
just download it manually
not sure if ip bans or server just unstable we will see

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
