### ISSUE TITLE
(ERROR) "POKEMON SERVER MIGHT BE OFFLINE OR UNSTABLE".. HELPP

### ISSUE THREAD

**Issue by someweird** [NECROBOTIO/NecroBot#5493]
![eror](https://cloud.githubusercontent.com/assets/20989244/17620385/35625fdc-60b6-11e6-9928-92a26935fbf7.JPG)

Help me please!! Why my account can't access the server! 
Thanks master

**Comment by boXseven** [comment]
thats why
http://www.mmoserverstatus.com/pokemon_go

**Comment by blackuGT** [comment]
Google accounts probably deleted

**Comment by recon88** [comment]
Server issues

**Comment by someweird** [comment]
so maybe the server is down in several countries..
