### ISSUE TITLE
TRANSFER POKEMON PROBLEM 

### ISSUE THREAD

**Issue by pkownsz** [NECROBOTIO/NecroBot#5495]
why my Necrobot dont transfer low cp pokemons? in config i using 
"KeepMinCp": 960,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 20,
but he save 400+~ cp pokemons and lower.. wtf

**Comment by boXseven** [comment]
"TransferWeakPokemon": true,

**Comment by recon88** [comment]
For help visit https://discord.gg/VXKxNFr
