### ISSUE TITLE
How to avoid IP ban?

### ISSUE THREAD

**Issue by yopilip123** [NECROBOTIO/NecroBot#5499]
Since most of us botters encountered IP Ban recently (previously it was just Softban). How can we avoid IP ban? What are the things that we need to do to avoid it? Is there a way to bypass IP Ban?

When my IP was banned (based on the issue I posted awhile ago, I experienced IP ban because it shows the error "Theres no pokestop ... bla bla" as said by other users) I just waited for 10 minutes and did nothing, and after that, I opened the bot again and now it works. I did not reboot the router or anything. (I have a static Public IP, FYI)

If you can have any solution, tips or tricks regarding IP Ban avoidance, feel free to comment it here. 

Thanks,
Phil

**Comment by cawk** [comment]
in the config make it as human like as possible
