### ISSUE TITLE
anyone else getting cant find pokestops? 

### ISSUE THREAD

**Issue by ice274845890** [NECROBOTIO/NecroBot#5500]
I'm so confused...

**Comment by ipkpeople** [comment]
Anyone who botted yesterday will get either of these 3perma bans : 1. No pokestops (cant spin but can catch pokemons) 2. No Pokemonst (can spin pokestops but cannot catch pokemon) 3. Could not log in at all (death of an account).

**Comment by Imadlekal** [comment]
Almost everyone is getting that message actually .
Read this : https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by ice274845890** [comment]
are u sure?

**Comment by ipkpeople** [comment]
Trust me like you trust Jesus @ice274845890

**Comment by ice274845890** [comment]
so u cant fix it ?

**Comment by theawesomepokemon** [comment]
unban not working for me. Permabanned i think

**Comment by andele123** [comment]
Just wait and try again later. Had the same issue. Works now. But -> I will stop now. Too dangeroues

**Comment by smoothrunnings** [comment]
@ice274845890 WTF. Stop farming for 30 minutes to an hour and try it again. If it doesn't then you have been perma banned.  They are now doing reverse lookups on IP, if your IP doesn't match the state or country you are farming in you'll get perma banned.

**Comment by ipkpeople** [comment]
Well, as what I've experienced and watched, there is no way to un-ban those 3 problems right now. Your best bet is to just wait it out see if it goes away. If not, say bye to your pokes. @ice274845890

**Comment by andele123** [comment]
Ok, lvl 30 is enough for me.

**Comment by feroniameimei** [comment]
After got banned, i tried to change my ip address (ip location: great britain), i used hotspot shield vpn elite, i re-downloaded bot, and i start the bot. mine is working fine now. :)

**Comment by ipkpeople** [comment]
@feroniameimei 
NorwegianVikings - Today at 8:36 AM
@everyone Softbans and hardbans appear to be increasing, for your safety we recommend you make these settings changes: disable sniping, reduce walking speed to 18kph or less, increase action delays to at least 2-3 seconds, and don't use proxies if you can avoid it.

**Comment by andele123** [comment]
I think it's clear enough to stop it for some hours/days

**Comment by theawesomepokemon** [comment]
not permabanned but defo stopped using necrobot for now. New update seems to have fucked it

**Comment by rickadipa** [comment]
If you run 2 or more necrobot at same time, You get ip block, change your ip and try again. And no bot 2 acc at same time.

**Comment by Gondost** [comment]
Not permabanned either, everything works in client. Don't spread misinformation.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
