### ISSUE TITLE
Proxy Necrobot setting how to use?

### ISSUE THREAD

**Issue by jayson0408** [NECROBOTIO/NecroBot#5501]
How to use this? 
![ssssss](https://cloud.githubusercontent.com/assets/20958625/17620646/6ceb22b8-60c0-11e6-94a0-f9d6c3376793.png)

**Comment by janga11** [comment]
search for proxy server and fill it in. (it has to be HTTPS and Port 80)

**Comment by jayson0408** [comment]
thanks

**Comment by djodiek** [comment]
must use proxy?

**Comment by janga11** [comment]
if your ip is banned you can wait or use proxy... u choice
