### ISSUE TITLE
The best sniping settings.

### ISSUE THREAD

**Issue by DhrFavor** [NECROBOTIO/NecroBot#5509]
Hello,

I would like to make this threath were everyone can share his settings and his opinion on it. This way we will al have the best settings. I hope someone can start with his settings!

Have a nice day.

**Comment by SaubereSacheLP** [comment]
Sniping = Ban?
I lost this morning 200 Accounts forever...

**Comment by DhrFavor** [comment]
So it´s currently not possible at all?
