### ISSUE TITLE
HI~~0.8.6

### ISSUE THREAD

**Issue by milk6312** [NECROBOTIO/NecroBot#5512]
I was about to open a new download 0.8.6

This situation is not set file I could not find the reason
![1471000733796](https://cloud.githubusercontent.com/assets/20989717/17620977/dd335fd4-60c2-11e6-9fa0-bf32e501cc83.jpg)

**Comment by EiTeR94** [comment]
do not use any bot, niantic will ban you.

 https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by Azaelx** [comment]
same error (i think,...)

**Comment by Wcidd** [comment]
Turn "UseProxyAuthentication": true, to false if you are not using a proxy or have not filled in proxy settings properly

**Comment by milk6312** [comment]
....?
