### ISSUE TITLE
Telegram API password

### ISSUE THREAD

**Issue by martinyan** [NECROBOTIO/NecroBot#5513]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Expected Behavior
Telegram integration has been working fine, but ever since I have downloaded 0.86 release , i notice message is thrown about Unknown Error with Telegram 
Notice there is a new line about telegram password...may I know what is that?
### Your config.json
```
 "TelegramAPIKey": "my telegram key",
  "TelegramPassword": "12345",
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Telegram integration is down

**Comment by theloser** [comment]
Telegram is not working with 0.8.6, it's broken. Go back to 0.8.5. or wait until it's fixed. I suggest turning Telegram API of for now.
