### ISSUE TITLE
Can't seem to make the program run after updating to v0.8.6

### ISSUE THREAD

**Issue by angelopdg** [NECROBOTIO/NecroBot#5515]
Hi,

I can't seem to make the program run after updating to v0.8.6. There is an error that says:

"System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

What could cause this error? I'll attach a screenshot of the error for further details.
![error](https://cloud.githubusercontent.com/assets/20989714/17621213/56d71960-60c4-11e6-9b53-a87f47ce3d81.jpg)

Thanks in advance.

**Comment by Life7Line** [comment]
update your .net framework to 4.6 . if failed update your window 7 then install .net framework 4.6 .

**Comment by geo333** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by albysprx** [comment]
same problem and i have net framework 4.6.2 and c++ 2010

**Comment by angelopdg** [comment]
Thank you Life7Line & geo333. Will try the steps that you guys have suggested.
