### ISSUE TITLE
"TRY AGAIN" When spinning pokestops.

### ISSUE THREAD

**Issue by feedbuck** [NECROBOTIO/NecroBot#5517]
"TRY AGAIN" When spinning pokestops. I am using a vpn. Does that med im permanbanned or what is it?

**Comment by Brainenigma90** [comment]
its a softban

**Comment by feedbuck** [comment]
@Brainenigma90 you cant bypass them anymore?

**Comment by Brainenigma90** [comment]
yes! i changed my ip(just unplug your router for 5-10min) and it worked, i think they are banning ips now alot

**Comment by feedbuck** [comment]
@Brainenigma90 I am using cyberghost but do i have to unplugg the router for it to work?
