### ISSUE TITLE
NecroBot Client for Pokemon GO has stopped working

### ISSUE THREAD

**Issue by jai-ch** [NECROBOTIO/NecroBot#5518]
NecroBot Client for Pokemon GO has stopped working
NecroBot Client for Pokemon GO has stopped working
NecroBot Client for Pokemon GO has stopped working
NecroBot Client for Pokemon GO has stopped working
NecroBot Client for Pokemon GO has stopped working

**Comment by Linewalker** [comment]
https://github.com/NECROBOTIO/NecroBot/issues/5522#issuecomment-239429286
Please close. No code issue.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
