### ISSUE TITLE
"Logging in using google" - and it stays like that.

### ISSUE THREAD

**Issue by ak47temas** [NECROBOTIO/NecroBot#5519]
Correct login and password, but it doesn't connect. Why?

**Comment by RoySp** [comment]
Try to download the latest release by hand. I had the same issue this morning.

**Comment by ak47temas** [comment]
Could u give me the link please? I can't find it

**Comment by ak47temas** [comment]
It doesnt help!

**Comment by jazzu20** [comment]
i have the same issue

**Comment by YangSkyL** [comment]
try to login with your phone, if it fails, you are probebly perma-banned. https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
