### ISSUE TITLE
Softban loop with fix

### ISSUE THREAD

**Issue by diksm8** [NECROBOTIO/NecroBot#5520]
Stuck in a softban loop. Tried to use QuickSpin which spins until the account is unbanned and it got unbanned after 50 spins. Any way to change the max spins in necro when unbanning? Have loads of accounts stuck in softban loops now.

**Comment by Zenex61** [comment]
I used quickspin but ı still banned :(

**Comment by diksm8** [comment]
Probably IP banned.
This is for softbans.
