### ISSUE TITLE
Possible Softban/IP-Ban Fix

### ISSUE THREAD

**Issue by Skyfail** [NECROBOTIO/NecroBot#5522]
First of all, sorry for creating this as an issue, I'd have created a Pull request but I'm currently not at my home PC.

I also had the problem that my IP Addresses apparently got banned after about 5 minutes of botting.
I then had a look at the source and noticed that all values in sig.SensorInfo are set to random values, which I believe can be detected since some of the fields are just the normalized value of another field.
I hardly know anything about that accelerometers, magnetometers and whatever so I might be completely wrong. But removing the GenRandom() calls in GenerateSignature() seems to work for me.

**Comment by Linewalker** [comment]
You just need to do the following, without changing the source:
change delays to a longer period, e.g.:
  "DelayBetweenPlayerActions": 30000,
  "DelayBetweenPokemonCatch": 15000,
and don't forget to enable the Recycledelay

**Comment by athena93** [comment]
@Linewalker confirm can fix?

**Comment by Linewalker** [comment]
Sure, as you see in the screenshot. The unban happened automaticly. The bot is still running.
![pokemongo_1](https://cloud.githubusercontent.com/assets/7597479/17621797/244d5d48-6096-11e6-857a-ba8ae44da531.png)

**Comment by athena93** [comment]
@Linewalker can i know your value for "WalkingSpeedInKilometerPerHour" and entire exp/h u currently use?

**Comment by Linewalker** [comment]
2.7 kp/h, like google definition. It's very slow ;)

**Comment by mattyk4** [comment]
Hey could you guys tell me what setting I should have "FastSoftbanBypass" set too?

**Comment by ahungrybear** [comment]
i think i might have an IP ban, 
log in using wifi and there is no pokestop and gyms around
log in using mobile data and everything is back to normal.

this happens after i get a softban msg and even it is 45/45 it will not get unban.

hope this helps the troubleshooting and solve some questions from the others 

Singapore

**Comment by Skyfail** [comment]
@Linewalker I set DelayBetweenPlayerActions to 5000 and DelayBetweenPokemonCatch to 15000. Got softbanned with a new IP after ~5 Minutes, after removing the random values in the API I aquired a new IP once again and my bot is running for 1,5 hours now with the same Delay values.

**Comment by athena93** [comment]
@Skyfail where can i find the random values in the API? i want to follow ur step

**Comment by ahungrybear** [comment]
@Skyfail me too haha

**Comment by Skyfail** [comment]
@athena93 GenerateSignature in RequestBuilder.cs from PokemonGo.RocketAPI

**Comment by athena93** [comment]
@Skyfail aww sad i can't do coding. 5% knowledge coding only. didn't know where to find it.
