### ISSUE TITLE
What's up with this error? Didn't do anything with the bot, besides change the config via NecroConfig. http://i66.tinypic.com/2s7jog6.png

### ISSUE THREAD

**Issue by AleXX3k** [NECROBOTIO/NecroBot#5525]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by AleXX3k** [comment]
Oops, well I get this error, there's a screenshot of it on this link ( http://i66.tinypic.com/2s7jog6.png ).
Could you explain what I have to do, to get rid of it?

**Comment by Wcidd** [comment]
Install http://go.microsoft.com/fwlink/?LinkId=780597

**Comment by theloser** [comment]
@Wcidd You sure? Current master is still on .NET 4.5.2 (they reverted it back before releasing 0.8.6), so I don't think version 4.6.2. is needed.
