### ISSUE TITLE
problem with an exception...

### ISSUE THREAD

**Issue by crinq98** [NECROBOTIO/NecroBot#5526]
i searched on internet and i didn't find anything reguarding this problem, my problem is that when i start the bot, it says to me: [13:58:51] () Exception caught, writing LogBuffer.

Eccezione non gestita: System.TypeInitializationException: L'inizializzatore di
tipo di 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' ha generato un'eccezi
one. ---> System.TypeLoadException: Impossibile caricare il tipo 'System.Securit
y.Authentication.SslProtocols' dall'assembly 'System.Net.Primitives, Version=4.0
.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   in System.Net.Http.HttpClientHandler..ctor()
   in PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   in PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy a
piFailureStrategy)
   in PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings
 logicSettings)
   in PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings
 logicSettings)
   in PoGo.NecroBot.CLI.Program.Main(String[] args)

and it close the program so i don't know what to do.. pls help me

**Comment by Wcidd** [comment]
Either you have to disable proxies or you have to install http://go.microsoft.com/fwlink/?LinkId=780597

**Comment by totopetok** [comment]
try install dotnet 4.6.1 offline
https://www.microsoft.com/en-us/download/details.aspx?id=49982
