### ISSUE TITLE
Bot is sniping only, not moving?

### ISSUE THREAD

**Issue by head0r** [NECROBOTIO/NecroBot#5527]
After the update it seems the bot is sniping only :D
After start it walks to the first pokestops, turns it, then begins sniping. 
It catches wild pokemon between snipes, but it doesnt move anymore o.O
Walking Speed is 17 km/h in a max distance of 600m, no GPX.

>   "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "GetSniperInfoFromSkiplagged": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 300000,
  "SnipingScanOffset": 0.03,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,

**Comment by head0r** [comment]
UPDATE:
Now all Pokeballs are empty. It said sniping is not possible, caused by amount of pokeballs.
After that it starts moving to pokestops again

**Comment by qzqzqz** [comment]
got the same problem. u know how to fix it?
maybe by setting the amount of pokeballs to start sniping very high?

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
