### ISSUE TITLE
Multi Times BOT

### ISSUE THREAD

**Issue by GitHubRule** [NECROBOTIO/NecroBot#5528]
Hello

Wanted to ask if I can open Multi Times bot in one computer ?

Thank you

**Comment by Suchat777** [comment]
you will be softban coz IP duplicate

**Comment by GitHubRule** [comment]
So I can use same computer for Multi Times?

**Comment by rockycabaero** [comment]
no

**Comment by GitHubRule** [comment]
And another copmuter in the same wifi ?
