### ISSUE TITLE
There is no fix pokestop problem

### ISSUE THREAD

**Issue by agustyn7** [NECROBOTIO/NecroBot#5530]
i change my ip, i tried vpn, i opened my account on phone and i did everything but pokestop does not give item when i open it on phone it says try again later but i can catch pokemon what is solution?

**Comment by thadeustr** [comment]
it could be a server problem. earlier i was having same issue but i can play fine now...

**Comment by mattyk4** [comment]
Ban could be linked directly to your account? Try it again in 30 minutes

**Comment by tggiml** [comment]
thadeustr, so you mean you had a same issue then you now can play fine ? you are able to get items from stops?

**Comment by agustyn7** [comment]
i can not play since morning 6-7 hours passed still same :s
