### ISSUE TITLE
Doesnt connect with google account.

### ISSUE THREAD

**Issue by ak47temas** [NECROBOTIO/NecroBot#5535]
![image](https://cloud.githubusercontent.com/assets/20987627/17621780/58a8e3d4-609e-11e6-8046-0e7185c1fce8.png)
It says that it's logging in using google, then it shows me these codes, and then again "logging in using google", then again codes, and again and again.

**Comment by ak47temas** [comment]
idk what to do, i have the latest version.

**Comment by LuthfyCooperz** [comment]
same issue with me ,

**Comment by Wcidd** [comment]
Us servers seem to be down
Or it could be a ban
