### ISSUE TITLE
Feature request: Bypass new bot detection mechanism by niantic

### ISSUE THREAD

**Issue by deduijk** [NECROBOTIO/NecroBot#5541]
**Issue**
I have noticed several issues by players stating they saw new bans.

1 in particular caught my eye (my ip was softbanned for the first time) and the amount of pokeballs i got supports i was probably banned because of the new detection (quite likely??).

1. Not allowing pokemon to be caught, but pokestops works
2. No pokestops, but you can still catch pokemon.

I believe I fell victim to the first one, since i had a lot of pokeballs, while normally I have next to none.

**Proposed solution:**
Detect if catching pokemon and spinning pokestops is still possible every x (5?) stops 
(Spinning pokestops still possible? -> yes; did i catch or snipe any pokemon between the last x pokestops?)
If either isn't possible pause x minutes?

**Proposed New config items:**
`AntiSplitDetection: true|false`
`AntiSplitDetectionPause: # (minutes)`

**Comment by nfettinger** [comment]
Duplicate issue.

**Comment by deduijk** [comment]
OF CASE?
