### ISSUE TITLE
after exception

### ISSUE THREAD

**Issue by crinq98** [NECROBOTIO/NecroBot#5542]
i solved the problem of exceptions but now it says to me travelling to *** (the pokestop) and than it says softban for every pokestop and sometimes it find a pokemon to capture but it escape from me...

**Comment by ASKcoTM** [comment]
how did you fix the exeptions

**Comment by crinq98** [comment]
by downloading and installing this:  http://go.microsoft.com/fwlink/?LinkId=780597
