### ISSUE TITLE
BOT KEEP HAVING PROBLEM WITH SOFT BAN AFTER SPINNING THE POKESTOP

### ISSUE THREAD

**Issue by BallsackBro** [NECROBOTIO/NecroBot#5547]
Hello

Am I the only one who has problems with the bot ? Even with the new update , I get soft bans all the time each time after it spins the pokestop 1-45.

any solutions ? It worked since yestreday , but today it's messed up.

**Comment by nfettinger** [comment]
Please use our Discord chat for help.
https://github.com/NECROBOTIO/NecroBot/wiki
